### ISSUE TITLE
Help Wanted. A person who can clean my code

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#1]
Please leave a comment if you are interested (or even better, make a pull request after cleaning it on your fork of this)

**Comment by ItzLevvie** [comment]
If I've time, I will format your code.

**Comment by Andrews54757** [comment]
Thank you!!

**Comment by NatsuTheGreat** [comment]
I'll format it too ^-^

**Comment by LegitSoulja** [comment]
@Andrews54757 lol do you still need this?

**Comment by Andrews54757** [comment]
no

**Comment by LegitSoulja** [comment]
@Andrews54757 I could make you like a cool minifier that you can minify all files at once. Like copying the files to another folder before committing, and minify all at once.

**Comment by XenoYT** [comment]
The first issue is so beautiful :D

**Comment by ItzLevvie** [comment]
xD

**Comment by Agarian** [comment]
ikr (i know XenoYT is banned still)

**Comment by Agarian** [comment]
This is historic

**Comment by SharkFinPro** [comment]
lol
