### ISSUE TITLE
How minion change points

### ISSUE THREAD

**Issue by LostCodesy** [AJS-development/Ogar-unlimited#1000]
Hello,

I need minion change points,

for command **minion [yourid] [amount] [minionname]**.

Thank you.

**Comment by LostCodesy** [comment]
**Help me.**

**Comment by Agarian** [comment]
That makes no sense...

**Comment by Agarian** [comment]
Hard to believe the 1000th issue was wasted.

**Comment by NatsuTheGreat** [comment]
^^ Very sad.
