### ISSUE TITLE
Buttons pls i need help :(

### ISSUE THREAD

**Issue by RelTakeover** [AJS-development/Ogar-unlimited#1001]
hello comunity ,
I need the server selection buttons ,
I bring it to the desired ips

sorry my english

I think it's jQuery and html

CALVINHDK have the  same problem , pls a programmer 
give full html code and jquery please...

example : (
I do not know if it is ok  , only for 
represent my problem)

 <------ " :+1: JS O JQUERY :100:  , I do not know...

 var CONNECTION_URL = "91.121.30.118";
    var GAMETYPE_FFA_PORT = "451";
    var GAMETYPE_EXP_PORT ="452";

success: function() {
                wsConnect("ws://" + CONNECTION_URL + ":" + GAMETYPE_PORT) " ---->

-

:100: HTML: :+1: 

<-----"
select id="gamemode" class="form-control  btn" onchange="setGameMode($(this).val());" Srequired=""
option selected value="FFA">  PARTY 1</option
option value="EXP"> BIG</option>  "
---->

-

i do not know nothing , only copy and paste the example , pls a programmer , give full code html and jquery for comunnity plsss :(

**Comment by LostCodesy** [comment]
**Please screenshot give for your need element.**

**Comment by RelTakeover** [comment]
![image](https://cloud.githubusercontent.com/assets/19374681/16020976/b0b9d2be-3186-11e6-8db8-8d58310cebb2.png)

i need that this buttons connect to ip of servers :(

**Comment by Andrews54757** [comment]
multiverse does not allow cross-ip as a security feature

**Comment by LegitSoulja** [comment]
@Andrews54757 they might be confused over the Statistics server thing I recently added.

**Comment by Tokoagar** [comment]
@LegitSoulja How can I put my server on the stats? I got port forward and statistics plugin install what do I need to do next?

**Comment by bobys16** [comment]
This is for the  server selection div

            <div id="locationUnknown" style="display:yes;">
                <select id="region" class="form-control" onchange="TFunction()">
                    <option selected disabled value=""> -- Select Your Server --</option>
                    <option value="103.206.98.183:1502">FFA 1 [ASIA][ONLINE]</option>
                    <option value="103.206.98.183:1501">Mega+FastMove [ASIA][Online]</option>
                    <option value="103.206.98.28:5002">FFA 3 [ASIA][ONLINE]</option>
                    <option value="51.254.157.61:1802">Experimental [Europe][ONLINE]</option>
                    <option value="51.254.157.61:1801">FFA 5 [Europe][ONLINE]</option>
                    <option value="51.254.157.61:1803">RAINBOW FFA [Europe][ONLINE]</option>
                    <option value="103.206.98.28:5001">FFA 2 [ASIA][ONLINE]</option>
                </select>
            </div>

this for js functions

function connectToServer() {
var defaultserv = "ws://103.206.98.183:1501"

 connect(defaultserv, true);
}
function TFunction() {
    var x = document.getElementById("region").value;
    connect("ws://" + x, true);
}

and for main_out js .
delete all line with CONNECTION_URL and var CONNECTION_URL delete all .

and serch this line .

    function wsConnect(wsUrl) {
        if (ws) {
            ws.onopen = null;
            ws.onmessage = null;
            ws.onclose = null;
            try {
                ws.close()
            } catch (b) {
            }
            ws = null
        }
begin nodesOnScreen = [];
and the end off nodesOnScreen = [];

and replace with .

function wsConnect(wsUrl) {
        if (ws) {
            ws.onopen = null;
            ws.onmessage = null;
            ws.onclose = null;
            try {
                ws.close()
            } catch (b) {
            }
            ws = null
        }
nodesOnScreen = [];
        playerCells = [];
        nodes = {};
        nodelist = [];
        Cells = [];
        leaderBoard = [];
        mainCanvas = teamScores = null;
        userScore = 0;
        console.log("Connecting to " + wsUrl);
        ws = new WebSocket(wsUrl);
        ws.binaryType = "arraybuffer";
        ws.onopen = onWsOpen;
        ws.onmessage = onWsMessage;
        ws.onclose = onWsClose;
        ws.onerror = function () {
       gameMode = 1; 
          wjQuery("#gamemode").val(1);
            console.log("socket error");
            return 54
        }
    }

..

if error please use inspect element and send the console screenshot log here :D ..

hope u understand

**Comment by bobys16** [comment]
or u can copy from my server
http://agar.red-bulls.one

thnx
