### ISSUE TITLE
exists a programmer that help me?

### ISSUE THREAD

**Issue by RelTakeover** [AJS-development/Ogar-unlimited#1002]
only need create a button ( i believe that use html and jquery ) that connect with ip of servers

I do not know anything about jquery , pls a progammer give full code PLS NOT CLOSE ISSUE 

I NEED HELP  urgent..

example :+1: 

FFA1 ws://127.0.0.1:447

FFA2 ws://127.0.0.1:448

FFA3 ws://127.0.0.1:449

**Comment by Andrews54757** [comment]
become a progreammer, we are not your slaves

**Comment by Andrews54757** [comment]
and you just need to do `multiverse create [name] [port]`

**Comment by raphyjb** [comment]
Multiverse doesnt work

**Comment by Megabyte918** [comment]
@RelTakeover 

> that connect with ip of servers

what exactly do you mean by that?
theres a "reconnect"  and "fetch servers" button on play.ogarul.tk i dont know what else you could possibly mean

**Comment by LegitSoulja** [comment]
@RelTakeover Don't get confused over http://stats.ogarul.tk servers and multiverse.
