### ISSUE TITLE
Skins like poland, 9gag, france no longer works in bots help!

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#1003]

**Comment by Agarian** [comment]
We know! Custom skins are broken ATM

**Comment by LegitSoulja** [comment]
@Agarian they aren't broken. You just have to use specific clients.
- http://play.ogarul.tk
- http://ogarul.io
- and ajs client github page

**Comment by Agarian** [comment]
I mean Like skins like Doge, USA, etc

**Comment by Andrews54757** [comment]
We hate Moneyclip
