### ISSUE TITLE
Bad news...

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#1004]
My computer is f*cked. For some reason, when i turn on my computer, it shows the BIOS startup screen like normal, but instead of showing "starting windiws", it shows a black screen. And then shows "windows failed to start". I tried running startup repair, but it lead to a black screen aswell. IDK what to do now, as i cannot afford a new PC.

**Comment by LegitSoulja** [comment]
What did you do last before it crashed?

**Comment by David1ali12** [comment]
just do a format

**Comment by LegitSoulja** [comment]
Don't do a format with a recovery option.

**Comment by Agarian** [comment]
I cannot format if the PC won't startup.
The only way i can commit to tye project easily now is:
- if i rack up enough money for a new PC
- somehow get it working again
- use another PC
And BTW i have no restore points (they seem to have vanished), i have no recovery images or disc either.

**Comment by Agarian** [comment]
*sigh* it was fun while it lasted.

**Comment by LegitSoulja** [comment]
What error does your computer get at boot?

**Comment by Agarian** [comment]
No error. Just goes to "windows failed to start". Selecting "start windows normally" doesn't work. Startup repair doesnt load.

**Comment by LegitSoulja** [comment]
Laptop or Desktop?

**Comment by Agarian** [comment]
Desktop

**Comment by LegitSoulja** [comment]
Try going into your bios setting, and boot safe mode.

**Comment by Agarian** [comment]
Not possible. Safe mode doesn't work, as it directs to startup repair, which doesnt work! I seriously barely can do anything on the computer! The F8 thing doesn't work either!

**Comment by Agarian** [comment]
Actually i just selected safe mode, its losding really slowly.

**Comment by Agarian** [comment]
And it tried to  direct to startup repair

**Comment by firelightning13** [comment]
@Agarian Same thing happens to me :/
When I boot up my computer, it shows BSOD. Also, my monitor didn't show anything so my pc is f**cked up.

Now I left it for a year and still doesn't work .-.
Now, I use my laptop crap for fun... while it lasts.

**Comment by LegitSoulja** [comment]
It's not hard to get a hold of a bootable disc / recovery. If you have custom graphics and such you'll have to install them back unless your graphics are built with the board, and recovery includes it.
