### ISSUE TITLE
About stats(public servers)

### ISSUE THREAD

**Issue by David1ali12** [AJS-development/Ogar-unlimited#1005]
### begin killed by console  in Public server(listed from stats)
Please @LegitSoulja  make some rules for those who make their server public( who list on stats) 
I was playing with friend wasa on raw server 
we played until we became first then raw begin to cheating used alot of bots personal
^^ ok np then he killed us twice by console o.O Shame on you raw(aka system root) 
making your server public then doing kid stuff I understand the server is yours but making public means you cant cheat on players you dont respect any player so ofc your server will be unlist until you respect the players  (public server rules) 
that's unfair

**Comment by David1ali12** [comment]
*listed server must Have rules

**Comment by LegitSoulja** [comment]
@systemroot do you own Raw servers?

**Comment by Andrews54757** [comment]
It is his server, he has the right to do anything he wants

**Comment by David1ali12** [comment]
@Andrews54757 ok its his server he can what he wants but not when its public

**Comment by raphyjb** [comment]
Just dont play on his server.. Play on Raphy's Server 
Thats my servers and i dont play into them! <3

**Comment by LegitSoulja** [comment]
@David1ali12 I won't ban him, but he need's to know the rules of fair gameplay.
@systemroot http://stats.ogarul.tk/ban/

**Comment by systemroot** [comment]
@LegitSoulja Why you created minions and now you start making people banned o.O ??
@David1ali12 i killed you twice? Hmm but yes. What to do when others go +100K mass ?! O.o ?
and this is not a cheat. For as time as this plugin is created by Ogar Developers is not a cheat. :) 

bye.

**Comment by LegitSoulja** [comment]
@systemroot im sorry, looking over it all there wasn't much to why you needed to get banned except the fact you was killing people. But now that I understand that it was minions, then reason why you killed people because they was too big I understand. Maybe you should **LIIMIT** bots use.

**Comment by systemroot** [comment]
@LegitSoulja My server was without limits, only mass limit for player was 33M. Unlimited connections. 
But well, all other persons which have an Ogar server in their VPS or home PC, have make an limit example server will be restarted every 20Minutes, Or limited With 30K mass. 
because if a player go +100K mass this player and his team will eat all other players. and for this i make some "killall" and server start to going lagy not for this reason but just when Players start to HIT , W , too much. 
For minions i use just 10. i make giveway too much. i give all my mass 20-30K to any player. 
some times i add minions to all players not too much but 1-5, just to make team with it.
Anyway is not needed to talk for this anymore its done now.

**Comment by LegitSoulja** [comment]
@David1ali12 Yea, I'll update with a list of rules when people install the plugin. 

I'll also be releasing a better functional statistics update aswell with fixes and patches, and additional security and noob proof.

**Comment by systemroot** [comment]
@LegitSoulja i suggest you a rule!
**" When you are team with a minion Don't eat Davit and his team with a tricksplit, Because he will raport you and you will be banned :trollface: " **

**Comment by David1ali12** [comment]
@systemroot not even funny I got killed by console I dont care about minions :angry: I dont wanna talk about this anymore closed

**Comment by NatsuTheGreat** [comment]
Such I funny joke I forgot to laugh, systemroot.

**Comment by LegitSoulja** [comment]
Oops, and the joke was soo funny, nobody laughed nor got raported.

**Comment by NatsuTheGreat** [comment]
LMAO You pointed out his spelling error XDD  "raported" I'm dead XD

**Comment by systemroot** [comment]
For as time as is a suggestion is not needed to laughed. U can accept or ignore without  u'r ironic comments.!

@NatsuTheGreat  Well what is your lang ?! mine is ALBANIAN. I don't know to talk perfectly english so fuck off dude.

**Comment by NatsuTheGreat** [comment]
That profanity is making you sound mad. Just a tiny bit mad though.
