### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#1006]
Hello, I really need someone who can re-create the README at ogar-unlimited. Why? because it is not very explanatory (some people find certain things hard to understand), It is messy, and we want to look completely different from ogar (we are trying to be independent from things such as ogar or money clip). So I want a person, who can recreate the readme so that people can understand it better. It is also somewhat outdated. The requirements are

1. Knowledge of most features in OgarUL
2. Proper grammar
3. Enthusiasm

That is all the requirements, If you want to apply, please say so. **OFF TOPIC COMMENTERS WILL BE BANNED!!!** (by that I mean people who talk about things such as feature requests and bugs here, or chat)

**Comment by agariobro12** [comment]
Hey i´m German I can All Translate to German the plugins etc For german users

**Comment by LegitSoulja** [comment]
I don't think we need translation. If we do German we have to do other languages aswell.

**Comment by Megabyte918** [comment]
should this be closed?

**Comment by LegitSoulja** [comment]
I don't think the readme is what he wanted :/.. Atleast not yet.

I added a table for all commands, and added an installation, and created several artworks even gif(which didn't work)

**Comment by David1ali12** [comment]
Great Idea I will make some gif

**Comment by LegitSoulja** [comment]
@David1ali12 No, Gif's don't work..

**Comment by XtremePlayzCODE** [comment]
I can
