### ISSUE TITLE
You have been banned. Wut?

### ISSUE THREAD

**Issue by systemroot** [AJS-development/Ogar-unlimited#1007]
Please read the FAQ in advance.
Yes i have read it.
YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED
Yes i have search for my error.
What game mode were you in when you had the issue?
Free for fun and all.
What version are you on?
6.9
What command did you type if any?
killall
You must have a description as well
I'm asking why i'm banned.?
Most common questions involve:
-
Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.
-
Can you make minions split by pressing E or R key?
A: NO, as agar.io client doesn't support those keys. Otherwise, you would need to use another client, and that is illegal.
my minions are working.
VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH
Ok.
![](http://image.prntscr.com/image/1054e737e69441da9b16fbe2d8afa410.png)

**Comment by David1ali12** [comment]
#1005 follow rules

**Comment by systemroot** [comment]
if minions are part of Ogar those rules can't be seriosly :)

**Comment by David1ali12** [comment]
if you want a make your server public you must fellow rules no problem with minions just dont kill players with console :angry:

**Comment by Andrews54757** [comment]
why are we banning people?

**Comment by LegitSoulja** [comment]
@Andrews54757 Misunderstandings. He's not banned. Nobody is..
https://github.com/AJS-development/Ogar-unlimited/issues/1005

**Comment by SevenSlayy** [comment]
wait so there banning people when there coding a server that is for a game by miniclip LOOOOOOOOOOOOL

**Comment by LegitSoulja** [comment]
@SevenSlayy unfortunately, miniclip powers don't extend that far. They can't do that. They wished..

**Comment by SevenSlayy** [comment]
@LegitSoulja yeah moneyclip dont give a shit

**Comment by LegitSoulja** [comment]
@SevenSlayy They maybe care, we don't.
