### ISSUE TITLE
My Agar.io Private Server Good?

### ISSUE THREAD

**Issue by LostCodesy** [AJS-development/Ogar-unlimited#1010]
Hi,

I'm a server build is www.minioner.tk

It is server good for me, have minions to all players :)

I waiting yours comments.

**Comment by David1ali12** [comment]
copy & paste

**Comment by fayizan** [comment]
Guys please don't go to www.minioner.tk just look at this image

![screenshot_7](https://cloud.githubusercontent.com/assets/19163419/16040813/9e043758-324f-11e6-8629-60c15e6b67ad.jpg)

**Comment by David1ali12** [comment]
dont host on c9.io    c9 no vps

**Comment by Megabyte918** [comment]
its laggy asf

**Comment by LostCodesy** [comment]
Yes, wait i upgrading.

**Comment by LegitSoulja** [comment]
@David1ali12 This the main reason why I don't fool with skin because of people like you who likes to steal. If stealing is your thing, thing making issues isn't neither. **Stop stealing other people work, claiming it as yours**.

**Comment by LegitSoulja** [comment]
@LostCodesy nobody cares about your site, and plus you are using c9, I hope you get banned soon :). That will teach you a lesson about stealing skins.

**Comment by LostCodesy** [comment]
i what is for thief?

**Comment by LostCodesy** [comment]
@LegitSoulja i testing agar.io private server i sorry

**Comment by LostCodesy** [comment]
give me your skype

**Comment by LegitSoulja** [comment]
@LostCodesy Why whould I give you my skype when you have stole mostly all the skins, and also stole my code source and encrypted it xD kid please. How about you do your own damn work and not steal other people work.

**Comment by Andrews54757** [comment]
Does it matter if they steal, we are an open source project

**Comment by Andrews54757** [comment]
Technically, Its his server

**Comment by LostCodesy** [comment]
It is a easy server okey go to me your developer team?

**Comment by LegitSoulja** [comment]
@Andrews54757 if people gonna make skins, then have them stolen and claimed by a non creator of the skins, then I don't think people will make skins anymore. I wouldn't.

**Comment by Andrews54757** [comment]
I dont see how he stole them

**Comment by LostCodesy** [comment]
Easy

**Comment by LegitSoulja** [comment]
@Andrews54757 by going over to ogarul.io, downloading them one by one http://minioner.tk/skins_temp/

**Comment by LostCodesy** [comment]
No :)

**Comment by LostCodesy** [comment]
Brothers i am a good coder, leave me your teams ?

**Comment by Andrews54757** [comment]
@LegitSoulja I can easily put a protector on everything we own , so noone can copy, but, I dont do that because this is open source and I dont want to be opaque. This is the same reason why I hate moneyclip.

**Comment by LostCodesy** [comment]
Hey @LegitSoulja your team join me? Im good coder

**Comment by Andrews54757** [comment]
no

**Comment by LegitSoulja** [comment]
@Andrews54757 Well, there is a protector http://ogarul.io/skins, but the thing is this kid bypassed, and download them individually. I have no problem people using them skins, but stealing them?

**Comment by Andrews54757** [comment]
I feel like no one really knows me. I mean REAL protection. not some thing like that.

**Comment by LostCodesy** [comment]
I m not a thief

**Comment by LostCodesy** [comment]
Im a coder

**Comment by LostCodesy** [comment]
I need a vps

**Comment by LostCodesy** [comment]
for my server

**Comment by LegitSoulja** [comment]
thats good, im done, i don't care anymore..

**Comment by LostCodesy** [comment]
Hey @LegitSoulja your have a vps? or give your team me for private server design ?

**Comment by Andrews54757** [comment]
please be quiet

**Comment by LegitSoulja** [comment]
I don't even want to talk to you, we aren't here to help you with designing. Do it yourself.

**Comment by Andrews54757** [comment]
BTW the fetch servers function is broken. And if you want to ban people from stats, you should add a rules page on the site and on the plugin docs

**Comment by LegitSoulja** [comment]
@Andrews54757 for some reason that button doesn't work with mobile..
And I added rules when people install the plugin for the first time.
