### ISSUE TITLE
split distance is very short

### ISSUE THREAD

**Issue by RelTakeover** [AJS-development/Ogar-unlimited#1015]
how increase the split distance ? where i could change it

**Comment by ErikParacelsus** [comment]
splitspeed on config.ini

**Comment by Megabyte918** [comment]
Try editing something in /core/Physics.js, lines 72 through 77
If i had to pinpoint one line of code, I think it might be in line 74:43 or 74:47
I might make a config for it later

**Comment by RelTakeover** [comment]
splitSPEED , YOU COULD READ ? DISTANCE , NOT SPEED ...

**Comment by Agarian** [comment]
I have a partial solution

**Comment by Agarian** [comment]
In physics.js,
Replace:
    var splitSpeed = gameServer.config.splitSpeed + (split.getSpeed() * 3 / 2); //70 * Math.max(Math.log10(newMass) - 2.2, 1); //for smaller cells use splitspeed 150, for bigger cells add some speed //splitSpeed = 70 + (split.getSpeed() + 10);
      //split.setMoveEngineData(splitSpeed, 32, 0.85); //vanilla agar.io = 130, 32, 0.85
      split.setMoveEngineData(splitSpeed, 40, 0.87); // set it to 45 if 40 is bad
With:

    var splitSpeed = gameServer.config.splitSpeed + (split.getSpeed() * 3 / 2) *     Math.max(Math.log10(newMass) - 2.2, 1);
		if (cell.mass <= 10) {
            split.setMoveEngineData(132, 32, 0.85);
            } else 
        if (cell.mass <= 610) {
            split.setMoveEngineData(122, 32, 0.85);
            } else 
        if (cell.mass <= 5000) {
            split.setMoveEngineData(110, 32, 0.90);
            } else 
        if (cell.mass <= 10000) {
            split.setMoveEngineData(105, 32, 0.91);
            } else 
        if (cell.mass <= 20000) {
            split.setMoveEngineData(105, 32, 0.92);
            } else 
        split.setMoveEngineData(splitSpeed, 32, 0.85); //vanilla agar.io = 130, 32, 0.85
