### ISSUE TITLE
LAG

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#1016]
Ok, i bought myself a vps 8GB ram and 4 Core, 40 GB 
trying to run a server, theres way to much lag, I tho "oh ill buy a vps thats stronger" but it didnt do shit, the game is the problem !
Is there a way to fix that lag? Please try to go play on any of my servers on: http://stats.ogarul.tk
Ur ganna see wat i mean. This is a problem , A HUGE PROBLEM. so much poeple like playing in but theres to much lag thats why they stop playing
*** PRAYING TO GOD FOR LAG TO GTFO ***
Looks like server are made to be for 3 poeple, or else more then that.. LAG 
At this point all i could do is put FPS = 1000 (this aint a joke the main one has 1000 fps and its shitty ass slow, but still better then 20 fps)

**Comment by mafiakb** [comment]
Yes, my server with 100 user is lag :/ , i have 32GB dedicated :(

**Comment by raphyjb** [comment]
PRAY TO GOD FOR #NOLAG

**Comment by LegitSoulja** [comment]
Kids let's not bring God into your / own problems.

**Comment by David1ali12** [comment]
I run on free vps 22 players no lag

**Comment by fayizan** [comment]
@raphyjb You have to limit your servers to 2 or 3 instead of creating 10 servers

**Comment by LegitSoulja** [comment]
@fayizan There's no limits to servers that can be created. You can make as many you want.

The table is ordered by the highest number of server players. Get your server to the top if you want to compete.

 Raphy servers are doing good as of now. Thanks raphy for providing servers for ogarul / the public / community. 🏆

**Comment by raphyjb** [comment]
awwwwwww Means alot Legit!! Bought those vps just to try to "run my own project"  
Now maybe ill be running a different project!
Looking for something else to run on that vps (:

**Comment by LegitSoulja** [comment]
@raphyjb I was thinking about making a bukkit plugin similar to ogarul but in minecraft as a mini game. I thought it be cool.

Though I've been stopped playing minecraft every since Microsoft took over, and the Eula kindof shut me down because I used to host premium and limited free servers, but I stopped when the Eula appeared.

But I mean if you want something else to run try Minecraft. I can pass you my old McMyAdmin license 😊

**Comment by LegitSoulja** [comment]
About the lag I'm slowly making my way to finding the bug. I though it was the client, but now I have to really check both.

**Comment by raphyjb** [comment]
kk !! And yes id love to run that old server of urs!! :D 
(:

**Comment by LegitSoulja** [comment]
Old server? All of that stuff was wiped out :/. I no longer have it but I can pass you the license and we could build a server from scratch

**Comment by raphyjb** [comment]
that could be awsome. All i need in the server is Minions to work. and popsplits to work. And skins
Thats it!

**Comment by LegitSoulja** [comment]
@raphyjb You need to FOCUS!.

**Comment by raphyjb** [comment]
we ganna do 1 thing at a time!

**Comment by Andrews54757** [comment]
I think I know where the lag is from, been trying to fix in the lag branch

**Comment by raphyjb** [comment]
<3 Find it please!
Btw i recognize even without bots or with bots. doesnt change anything still get lag at 20+ poeple in server. Is it skins?
