### ISSUE TITLE
Leaving AJS/Continuing life

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#1017]
I'm deciding wether or not I should or shouldn't leave. 
I have many reason why I want to leave.

Questions:
Why was I ever part of AJS?
What will happen if I leave?
Who actually wants me here?
Why is there another account as similar as mines?
https://github.com/LegitSoulja/
https://github.com/LegitSouIja

Ogar-unlimited was good at first, now things have turned another direction. I don't even play Ogar, nor have servers anymore which I shut down completely.

I don't know what to do anymore.

If I ever do leave, I will be deleting everything I have created since I no longer want to be part of OgarUL and I will no longer support whatever I have made, and on top of that I will delete my github account because now there's 2 of me :/.

I have many reason why I want to leave, but I don't know if I should or shouldn't. I'm stressed, going through depression, and extremely annoyed.

Sorry if I made someone feel some type of way.

**Comment by raphyjb** [comment]
<3 Hope u get better buddy! I Really hope u stay!

**Comment by David1ali12** [comment]
thanks for all you have done :cry:  I will miss you  I hope you stay

**Comment by NatsuTheGreat** [comment]
> Sorry if I made someone feel some type of way.

That did make me sad.

**Comment by Agarian** [comment]
I have one thing to say.
# STAY.

**Comment by Agarian** [comment]
This is really why u have the RIP cover photo?

**Comment by DTMClanDeveloper** [comment]
Thanks for contributing to the community, you really meant a lot to AJS

**Comment by MinersMC** [comment]
i really hope u stay..

**Comment by MrRageGamersMC** [comment]
Stay

**Comment by NarutoGamerPro** [comment]
# Stay. @LegitSoulja

**Comment by MinersMC** [comment]
Please STAY!

**Comment by MinersMC** [comment]
**Stay**

**Comment by vatsmonty** [comment]
Please and as we all need you here think about the community.I would only say stay pls

**Comment by firelightning13** [comment]
LegitSoulja pls stay we really need you :(

**Comment by fayizan** [comment]
# **STAY** we need you @LegitSoulja

**Comment by CalvinDKHD** [comment]
STAY MAN! I luv u!

**Comment by SorryAgario** [comment]
# **STAY** @LegitSoulja

**Comment by Kappa0Kappa** [comment]
Bruhhh :3 come on chill and stayy

**Comment by NatsuTheGreat** [comment]
# Stay

**Comment by ErikParacelsus** [comment]
# STAY

**Comment by Andrews54757** [comment]
@LegitSoulja Let me guess, final exams. It will pass. Also, if you want to leave, you should release all the website files. I hope you recover. You did so much to OgarUL and lots of people look up to you. It would be hard to run this repo without your but if you do want to leave, than its okay. Whenever I feel like this, I take a long break.

**Comment by Andrews54757** [comment]
Please though, enjoy life, life is meant to be enjoyed, not to be frustrated about. Follow your dreams

**Comment by LegitSoulja** [comment]
@Andrew54757 Exams?? I've been done with school and college, I'm saying like I need to focus on life more with family, and not being lazy

**Comment by LegitSoulja** [comment]
And I thought you do have access to the web files?

**Comment by mastkilxp** [comment]
would love to say: STAY HERE!, but ur right family is way more important then this all. and its better then sitting behind a computer for hours. enjoy whatever ur gonna do bud :).

**Comment by Megabyte918** [comment]
this is really heartwarming to see the overwhelming amount of support for you Soulja, I think you should stay, but just make sure to take some breaks every now and then. dont stress yourself out too much

**Comment by Agarian** [comment]
Lol this is like what happened when wun wun dissapeared, but its happening b4 that!

**Comment by Andrews54757** [comment]
@LegitSoulja My advice is to take a LONG break (a year?) you've done soo much already, I feel like you deserve a break

**Comment by XxRaizerxX** [comment]
me too

**Comment by XxRaizerxX** [comment]
i agree andrews
