### ISSUE TITLE
Why cant i connect to my ogar server?

### ISSUE THREAD

**Issue by tommyb008** [AJS-development/Ogar-unlimited#1018]
my server is on but i cant connect
i have port forwarded and i have a second computer with the server on it
i put this ws://50.173.201.239:4411
i connect using ogarul.io and it wont connect

**Comment by LegitSoulja** [comment]
We can't help you if your server cannot connect. Maybe you should check for yourself?
- http://www.canyouseeme.org/

Use that tool and make sure that your ports are open.
