### ISSUE TITLE
[NEW] How to port forwading on uTorrent

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#1019]
You're looking for a server but can't pay for one? 
There's your chance to have one without pay **nothing**.
First, download and install uTorrent, from [THIS](http://www.utorrent.com/intl/us/).
After you installed, you goto Options, it'll open a window like that, 
![image](https://cloud.githubusercontent.com/assets/15003706/16061760/57efd31a-3265-11e6-8bfd-131c7ca0d051.png).

After you did that you goto "Conection" and see "Used port for intrance connections" and change it to your server port, done, but don't close uTorrent, if you close it'll close the port, Warning: THIS CAN AFFECT YOU ROUTER/COMPUTER IF SOMEONE DDOS, BECAUSE THE PORT WILL BE OPEN.

**Comment by LegitSoulja** [comment]
I don't recommend using illegal software's but there's other options
- http://www.simpleportforwarding.com/

**Comment by Megabyte918** [comment]
I said the same thing on #121

**Comment by Lukkez** [comment]
I don't use uTorrent to download cracked programs etc, i don't recommend it because can be a trojan and bye bye pc.

**Comment by LegitSoulja** [comment]
I confirm that this does not work. You will need to have access to and from your router, and also firewall needs to be disabled which is also not recommended. Use simple port forwarding tool, or do it manually, or just forget about making a server period.
