### ISSUE TITLE
IS THERE ANWAY TO STOP THE UNL COMBINING WHEN OP

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#102]
IS THERE ANWAY TO STOP THE UNL COMBINING WHEN OP?
can i like remove that option when u press space when first C and u combine only on pressing it?

**Comment by Andrews54757** [comment]
why do you want that?

**Comment by Andrews54757** [comment]
also, your wording is confusing

**Comment by elitajmx** [comment]
Argh, sorry but,is there a way to disable the Unlimited Combining Time when pressing C and Space because after i do it i combine forever. except if i go in one piece, but after u get to max mass 22500 yall basically split and combine again :")

**Comment by Andrews54757** [comment]
It doesn't combine forever. because 1. the effect is gone when you merge into one piece. 2. the effect is gone after a period of time

**Comment by Andrews54757** [comment]
I just added the feature to disable certain things in op

**Comment by elitajmx** [comment]
saw it thanks
