### ISSUE TITLE
Chat Blocker

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#1020]
Please, add a chat blocker, I was with a guy saying much things bad, and I was **needing** yo ban him, and if he use VPN or maybe Proxy again, he will be back on the server and I will need to ban him again
so, I just wanted to have a chat blocker or maybe a muter, to mute the person. Sorry for don't put this at *suggestions* part and sorry if my english was bad, i am typing very fast...

**Comment by David1ali12** [comment]
`chatban id `

**Comment by LegitSoulja** [comment]
@Lukkez common buddy, you are a member of ajs. You should know the command usages, right?? I'm just saying.

**Comment by LegitSoulja** [comment]
If that person using a proxy or vpn there's nothing you can do with banning. You are pretty much screwed, unless you make a website with user authentication and force people to be logged in to play.

**Comment by Lukkez** [comment]
@LegitSoulja I was on break, and i don't saw that LARGE update, that's why, i am seeing the new commands now, but thanks, i'll just make people start with disabled chat on client config.
