### ISSUE TITLE
Error starting start.sh

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#1024]
I basically use `screen ./start.sh` when in the src folder.
I get this error - https://gyazo.com/1de2986ec98e44851696a674f2359ad9

Anyone know?!
THANKS!

**Comment by David1ali12** [comment]
downgrade node to 5.9.0
```
`sudo npm cache clean -f`
`sudo npm install -g n`
`sudo n 5.9.0`
```

**Comment by CalvinDKHD** [comment]
THANKS WORKED!
