### ISSUE TITLE
Minions permently, or timed.

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#1025]
Hey! So i want to make a bot service on my server but you cant for example do minion 1 [amount of time] etc. And the playerID doesnt stay when you refresh.

Can i make a service?
does a plugin exist for this?
THANKS!

**Comment by Andrews54757** [comment]
will be one, Im on a break. I am quitting ogarUL for a while (taking a break).

**Comment by CalvinDKHD** [comment]
Ohh, ok. What do you mean by will be one?

**Comment by LegitSoulja** [comment]
@CalvinDKHD so basically a timer for minions?

and I guess he meant it will be implemented soon with ogarul.

**Comment by CalvinDKHD** [comment]
Cool, yeah @LegitSoulja i do mean a timer :P and a permanant player ID so when they refresh they dont looser their bots. you can do Minions [IP ADRESS] amount etc.

**Comment by raphyjb** [comment]
Calvin go on skype

**Comment by Agarian** [comment]
Wait, does that mean minions have to be paid for? I thought we were against using minions as a server, considering its for everyone.

**Comment by raphyjb** [comment]
Payed bots are coming in service in plugins <3
when andrews ganna be back from his break

**Comment by LegitSoulja** [comment]
@Agarian we decided to go against miniclip. So yea, server's can have payments for things like minions and etc.

**Comment by Agarian** [comment]
But that's f*cked up

**Comment by CalvinDKHD** [comment]
@Agarian I do agree, but i have 250+ people on my server a day. I need to make money to buy a better host etc. But we making good money from ads etc now.

**Comment by fayizan** [comment]
@CalvinDKHD you game ip please..?

**Comment by LegitSoulja** [comment]
Nothing isn't free in life. If you want to run a server, without creating revenue then go for it. That's just your money being spent and not regained.

It's not messed up, that's if that person and that server decides to give people abilities to buy things in-game. Not saying all servers should be that way.

For agariohub, I was going to have a coin/token system so people can earn coins whilst playing to unlock things like skins and etc. Well, that's not going to happen :/

**Comment by CalvinDKHD** [comment]
My server is agarextreme.ml click on minions button to go to the actual
ogarul server.

**Comment by CalvinDKHD** [comment]
@LegitSoulja Dude, pls contact me over skype - calvin.leonhardt
i wanna talk about agariohub.

**Comment by LegitSoulja** [comment]
I don't want to talk about agariohub. I'm done with it. I spent a lot of work and time making the site, but I'm no longer maintaining it. Therefor I shut it down completely, including the servers.

**Comment by CalvinDKHD** [comment]
@LegitSoulja I would like to continue it!

**Comment by LegitSoulja** [comment]
@CalvinDKHD I can't do that. I'm no longer running ogarul servers.

**Comment by CalvinDKHD** [comment]
@LegitSoulja Well i can run it.

**Comment by CalvinDKHD** [comment]
@LegitSoulja  I have PLENTY of free time to develop it! I can run it 24/7. I will keep updating it.

**Comment by LegitSoulja** [comment]
@CalvinDKHD How much of PHP, MySQL, JavaScript, and ruby do you know?

**Comment by CalvinDKHD** [comment]
PHP i know 60 percent of, Java. Umm yeah 50/60. Dunno waht ruby is. But if i am running it i will run it on a dedicated server. Not using PhP.

**Comment by CalvinDKHD** [comment]
Check out my server - agarextreme.ml

**Comment by LegitSoulja** [comment]
Java? I'm not running no web app. My sites are fully php, and JavaScript. I use a little bit of ruby for some things.

And running it? No I can run the site, I'm just not running ogarul servers anymore. Lack of maintaining multiple servers..

**Comment by CalvinDKHD** [comment]
I can run the servers. Got a 16g vps.

**Comment by LegitSoulja** [comment]
I had a few moderators but there last activity was horrible. I don't blame them for not being there because I closed the site when agar.io disallowed private servers so I lost most traffic. I barely play games nor ogarul so mostly all the servers was bagged up and not cleaned/maintained, so that was the reason I just closed it down for good.

**Comment by LegitSoulja** [comment]
I'll think about it but I don't know

**Comment by CalvinDKHD** [comment]
Yeah well, i wanna continue it for you. Currently i have been making a lot of money on my server. I can donate some of it towards agariohub.

**Comment by CalvinDKHD** [comment]
Yeah, just think. I really wanna host agariohub because i want a login system. The plugin is just wierd. Atleast i think. Well thanks anyways.

**Comment by LegitSoulja** [comment]
Agariohub don't accept donations. I don't want to make money from it. There's really no need for it.

**Comment by CalvinDKHD** [comment]
Well, i just wanna continue it :P

**Comment by LegitSoulja** [comment]
My login system was mainly for back end admin panel, moderation, and chat and avatars. Also ability to give people individually access to a specific server

**Comment by LegitSoulja** [comment]
Pretty much a in-game console for admins and mods via OgarConsole.

**Comment by CalvinDKHD** [comment]
OgarConsole is out of date right? CAUSE I LOOVVVEEED ITT! and does rcon work?

**Comment by CalvinDKHD** [comment]
Cause i really need an ingame console or something like what you just talked about.

**Comment by LegitSoulja** [comment]
The default non plugin OC discontinued. The plugin is updated, and was recoded :/. And rcon?

**Comment by CalvinDKHD** [comment]
rcon is like a command ingame in the chat, like /rcon [pass] [command to issue]
like an ingame console.

**Comment by CalvinDKHD** [comment]
rcon means - remote console

**Comment by LegitSoulja** [comment]
Um, I don't know to tell you the truth if it works or not. I didn't even know it existed.

**Comment by CalvinDKHD** [comment]
Ohh, ok lol. Ill be home soon from school. Is there anyway you can help me with login and pass for levels, coins skins etc?

**Comment by LegitSoulja** [comment]
I added you on skype. Chat with me there. It's 6am for me btw I'm in heading to bed soon

**Comment by LegitSoulja** [comment]
@CalvinDKHD I don't know when I'll have time too. I'm kindof busy doing a lot of things. If you can make a site and such with logins I can implement it all for you and work on a coin system. I'm thinking more about public server databases so that everyone can use coins and etc.

**Comment by Agarian** [comment]
@CalvinDKHD isn't school over?

**Comment by Tokoagar** [comment]
nan

**Comment by Tokoagar** [comment]
for me 5 or 4 days...

**Comment by CalvinDKHD** [comment]
school aint over, 1 more week.

**Comment by Agarian** [comment]
Wtf my school was over 1 week ago,what school you go to?

**Comment by ItzLevvie** [comment]
I've 1.5 months till my school finishes, after that I'm going to be in Year 9 ;P

**Comment by ErikParacelsus** [comment]
Lol I got 1 more day of school.

**Comment by Agarian** [comment]
@ItzLevvie do you mean 9th grade? If so, same here

**Comment by ItzLevvie** [comment]
^^ Yup.

**Comment by jollesnaas** [comment]
This might work:
https://github.com/AJS-development/OgarUL-Plugin-Library/tree/master/ipBots

**Comment by systemroot** [comment]
@LegitSoulja Will be a good idea to add on chat /rcon 
or to make some things example /minions
this command will show ex "Don't ask for minions the are random"
or /admin and output "Admin is this" 
i was think about this but first i don't know where can i edit chat at myclient or at Ogar server files.! Maybe can you tell me ? i will try to add those and some more.
