### ISSUE TITLE
Skins not working.

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#1027]
so i downloaded the latest client, installed it etc. But the skins dont work. I am doing the < skin > without the spaces betweeen skin and brackets OFC. but i cant get it to work < /random > doenst work either.

**Comment by LegitSoulja** [comment]
@CalvinDKHD The skins can only be used with http://play.ogarul.tk and http://ogarul.io

If you are using your own client you will have to obtain your own skins. Don't ask me why but it was david decision to patch it so it can only be used with the official clients.

**Comment by CalvinDKHD** [comment]
Got it to work, just used another skin source.
