### ISSUE TITLE
VPS

### ISSUE THREAD

**Issue by InfernoYT** [AJS-development/Ogar-unlimited#1029]
Hey ! Please help me I don't know how to put my server on VPS. I have one.
I didn't find the way to put it in vps.
Thank you.

**Comment by raphyjb** [comment]
No one here is ganna help u out ...
U must know how to use a vps. before buyin one..
If u want info skype: raphy.jb

**Comment by NatsuTheGreat** [comment]
"We do not help you with hosting, in order to setup a VPS you must have some of your own knowledge about it"
