### ISSUE TITLE
How may I add my server to the fetch servers option so people can see my server on the list?

### ISSUE THREAD

**Issue by WolfOGG** [AJS-development/Ogar-unlimited#1030]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?

What version are you on?

What command did you type if any?

You must have a description as well

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

Can you make minions split by pressing E or R key?
A: NO, as agar.io client doesn't support those keys. Otherwise, you would need to use another client, and that is illegal.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

**Comment by David1ali12** [comment]
`plugin install Statistics `


@LegitSoulja  dude you sure you wanna leave? your stats become popular soon it will reach 100
See you have done a great thing you can more great thing  please :cry:  dont leave

**Comment by raphyjb** [comment]
once thats done.. open port 88 on ur router so it get listed on stats.ogarul.tk

**Comment by WolfOGG** [comment]
so I got to plugins in this website and I find what David said and then i just port forward to port 88 because i already port forwarded to 443 so my friend could join but that's it

**Comment by raphyjb** [comment]
yup
1+1=2 
same if u want OgarConsole... u need open port for the console too ect...ect..

**Comment by LegitSoulja** [comment]
@WolfOGG you need port 88 open aswell for statistics to work
