### ISSUE TITLE
Auto Restart for linux

### ISSUE THREAD

**Issue by eevaqueen** [AJS-development/Ogar-unlimited#1032]
Hello,
does this client have auto restart after xx time in linux?,and my other question does Ogar-unlimited is illegal client as old ?,becuase i was using it when it is legal when you connect using agar ip,so any help about that?

Thank you.

**Comment by David1ali12** [comment]
Not possible

**Comment by LegitSoulja** [comment]
Yes there's an auto restart. You have to run the start.sh though
