### ISSUE TITLE
Private/Public server 

### ISSUE THREAD

**Issue by TehRealShot** [AJS-development/Ogar-unlimited#1033]
My server wont show up in the list of servers. Please help me.

**Comment by Megabyte918** [comment]
Are you hosting it locally?

**Comment by TehRealShot** [comment]
Yes

**Comment by Megabyte918** [comment]
It will not show up if your hosting it locally, you need to port-forward, see #174 or #153, make sure your ports are open, and make sure you have the statistics plugin installed (see #1030 or #1021)
