### ISSUE TITLE
Line Split

### ISSUE THREAD

**Issue by CodingKuda** [AJS-development/Ogar-unlimited#1036]
Is there some update enabling us to do line splits. where you put ur cursor in the midle of your cell. Then spam space. I just wanna know. Thanks

**Comment by Peppyrotom** [comment]
yes,you can

**Comment by Megabyte918** [comment]
Not at the moment, I'm currently trying to add them into my fork but I cant seem to find the code that controls the angles in which you split when your cursor is in the middle. I searched EVERYWHERE

**Comment by Agarian** [comment]
This is in the client. I tested it on agar client and it worked

**Comment by Megabyte918** [comment]
Do you think that there is a way to add this into ogarul WITHOUT the agario client?

**Comment by Agarian** [comment]
Well, that may have to be added in play.ogarul.tk

**Comment by Megabyte918** [comment]
Alright ill keep that in mind
