### ISSUE TITLE
every bot is shaking and i am too and i split really fast and its glitchy help

### ISSUE THREAD

**Issue by HazardYT** [AJS-development/Ogar-unlimited#1042]
every bot is shaking and i am too and i split really fast and its glitchy help and i dont know what to do

**Comment by HazardYT** [comment]
#652

**Comment by HazardYT** [comment]
#642

**Comment by NatsuTheGreat** [comment]
Everybot shaking? Wtf?

**Comment by jollesnaas** [comment]
Send gif or video pls!

**Comment by LegitSoulja** [comment]
I told agar.io to stop doing crack. You see what happens?

**Comment by Tokoagar** [comment]
same thing for me...

**Comment by PrinceDark9243** [comment]
same for me

**Comment by LegitSoulja** [comment]
Hazard can you follow the guideline? Just because you say doesn't help us at all. Re-edit with the proper guideline of how it happen, when it happened, what commands you used, your node version etc..
