### ISSUE TITLE
Can't connect: even with localhost

### ISSUE THREAD

**Issue by jollesnaas** [AJS-development/Ogar-unlimited#1043]
I'm having some problems with connecting: I use the [play.ogarul.tk](http://play.ogarul.tk/) client, but still, I can't connect. I'm running OU (Ogar unlimited) on windows server 2012 vps and even when I try to connect to my server ON THE VPS with play.ogarul.tk/?ip=127.0.0.1:443, I still can connect what can I do?

Here is a console log:

> [INFO] Loading Config Files...
[INFO] Loading C:/Users/Administrator/Desktop/Ogar-unlimited-master/src/core/../
settings/advConfig.ini
[INFO] Loading C:/Users/Administrator/Desktop/Ogar-unlimited-master/src/core/../
settings/clientConfig.ini
[INFO] Loading C:/Users/Administrator/Desktop/Ogar-unlimited-master/src/core/../
settings/config.ini
[INFO] Loading C:/Users/Administrator/Desktop/Ogar-unlimited-master/src/core/../
settings/override.ini
[INFO] Your unique id is: NxrydpkoII
[INFO] Loading plugins
[INFO] Starting ConsoleService
#This is the ogar unlimited big text sign:
                                        _ _       _              _
                                       | (_)     (_)_           | |
  ___   ____  ____  ____    _   _ ____ | |_ ____  _| |_  ____ _ | |
 / _ \ / _  |/ _  |/ ___)  | | | |  _ \| | |    \| |  _)/ _  ) || |
| |_| ( ( | ( ( | | |      | |_| | | | | | | | | | | |_( (/ ( (_| |
 \___/ \_|| |\_||_|_|       \____|_| |_|_|_|_|_|_|_|\___)____)____|
      (_____|
#This was the ogar unlimited big text sign: ^^
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 17.2.5
TypeError: `port` or a `server` must be provided
    at new WebSocketServer (C:\Users\Administrator\Desktop\Ogar-unlimited-master
\node_modules\ws\lib\WebSocketServer.js:44:11)
    at GameServer.start (C:\Users\Administrator\Desktop\Ogar-unlimited-master\sr
c\core\GameServer.js:287:25)
    at ControlServer.start (C:\Users\Administrator\Desktop\Ogar-unlimited-master
\src\core\ControlServer.js:62:21)
    at Multiverse.create (C:\Users\Administrator\Desktop\Ogar-unlimited-master\s
rc\core\Multiverse.js:86:7)
    at Multiverse.init (C:\Users\Administrator\Desktop\Ogar-unlimited-master\src
\core\Multiverse.js:141:26)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\Ogar-unlimited-master\
src\index.js:38:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
[OK] Uniban updated

If any one wants to help me on skype: jolle.snaas1
I can give acces to vps if needed: (No private stuff on it)

Thanks
- Jolle

**Comment by raphyjb** [comment]
Obviously u didnt put a port as i see.. If u need help $$ contact me on skype: raphy.jb

**Comment by jollesnaas** [comment]
And were do I fill in the port?

**Comment by David1ali12** [comment]
src/settings/AdvConfig
>Server port

**Comment by raphyjb** [comment]
haters ganna hate

**Comment by David1ali12** [comment]
github is not for making money

**Comment by raphyjb** [comment]
i was just jokin bud..

**Comment by LegitSoulja** [comment]
@raphyjb everytime I see you on an issue you are giving away your skype name. No wonder why you get ddosed a lot :/,

- But that's non of my business

**Comment by raphyjb** [comment]
kk ill stop givin my skype i guess

**Comment by Megabyte918** [comment]
@jollesnaas turn the vps config off, and if you need it on then provide your port where the error tells you to
