### ISSUE TITLE
ANYONE GIVE ME THE CSS OF THE INDEX OF play.ogarul.tk

### ISSUE THREAD

**Issue by RelTakeover** [AJS-development/Ogar-unlimited#1045]
pls anyone give me the css of the index of play.ogarul.tk of the section skin gallery +

![image](https://cloud.githubusercontent.com/assets/19374681/16132779/12082f78-33eb-11e6-84e5-f1dd109044b2.png)

this css pls

**Comment by LegitSoulja** [comment]
NO!

**Comment by LegitSoulja** [comment]
That's not even going to be the official way of how the skins will be shown.. It was going to be a slide out, but somehow it glitches with the canvas, so this here won't be released. 

Have you ever heard of jQuery dialog?

**Comment by RelTakeover** [comment]
i recently learn js css and html , pls... give me only the css of skin selector

**Comment by LegitSoulja** [comment]
@RelTakeover there's no CSS.

**Comment by RelTakeover** [comment]
pls give me the codee

**Comment by LegitSoulja** [comment]
@RelTakeover the code wont work for you

**Comment by David1ali12** [comment]
it so funny when you see ppl steal codes then encode it :smile:
