### ISSUE TITLE
Is it possible to use a gif as a custom skin?

### ISSUE THREAD

**Issue by mrzack506** [AJS-development/Ogar-unlimited#1046]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
null
What version are you on?
1.7
What command did you type if any?
null
You must have a description as well
I want to know if you could use a gif as a custom skin in customskins.txt? Thanks.
Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

**Comment by LegitSoulja** [comment]
It's possible, but I don't recommend it.

**Comment by LegitSoulja** [comment]
No, because a canvas cannot play a gif image by each individual frame. So no it's not possible, but there could be a work around, but then at the same time it's a bad idea, and it would be very laggy
