### ISSUE TITLE
Bot Controls

### ISSUE THREAD

**Issue by CodingKuda** [AJS-development/Ogar-unlimited#1047]
Can you bind the bot controls Eg. E, R To other keys? Thanks.

**Comment by NatsuTheGreat** [comment]
What do you mean?

**Comment by LegitSoulja** [comment]
No, there's no key bindings.

**Comment by CodingKuda** [comment]
Do you know how the bots controls are E and R. Can I change it to like. I
and O?

**Comment by LegitSoulja** [comment]
You will have to change the client, and servers keycode, but we don't discuss about clients.
