### ISSUE TITLE
JxCore Installation

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#1048]
I said I was going to show you people who don't know how to use JxCore, so here you go...

###### Windows
* Download -> [jx_winsetup.zip](https://github.com/AJS-development/Ogar-unlimited/files/319596/jx_winsetup.zip).
* Extract content, and run JXcore_setup.exe.
* Accept the license agreement.
* Select **Chakra x64** (Note, Others will not work!) Chakra using V8, and recent EC6 :)
![capture](https://cloud.githubusercontent.com/assets/4976824/16137817/3b0282da-33f4-11e6-890c-fded83f54a0f.PNG)
* Go to your ogar-unlimited directory, shift and right click on an empty space and click **open command prompt here**, or open a new cmd, and cd to directory.
* Start node using **jx index** or replace node with jx in the bat file
![capture](https://cloud.githubusercontent.com/assets/4976824/16137845/98088a24-33f4-11e6-86ba-6dec227dd2ce.PNG)

###### GNU/Linux/Ubuntu
You can try downloading your library installation here
>> https://github.com/jxcore/jxcore-release/tree/master/0311

##### Or

* Git clone > https://github.com/jxcore/jxcore
* ./configure --engine-chakra
* make
* make install 

###### More information
>> https://github.com/jxcore/jxcore/blob/master/doc/HOW_TO_COMPILE.md

**Comment by LegitSoulja** [comment]
Test JxCore? Go to http://play.ogarul.tk, fetch servers, and go to NoLag Test Server

**Comment by LegitSoulja** [comment]
[JXcore.zip](https://github.com/AJS-development/Ogar-unlimited/files/319632/JXcore.zip)

**Comment by LegitSoulja** [comment]
[Chakra.zip](https://github.com/AJS-development/Ogar-unlimited/files/319633/Chakra.zip)

**Comment by NatsuTheGreat** [comment]
Access denied.

**Comment by fayizan** [comment]
@LegitSoulja  thank u so much and can u please add Cent Os to the tutorial

**Comment by fayizan** [comment]
@LegitSoulja unfortunately I can't find chakra in the list 

![screenshot_5](https://cloud.githubusercontent.com/assets/19163419/16140815/3aef7f86-3472-11e6-8ac7-04679b93e732.jpg)

**Comment by LegitSoulja** [comment]
@fayizan I forgot, you need Visiual C++ Redistributable 2015 I believe. The stuff I work with in development with visual studios came with everything I need. I don't know if you need that or not but you can try.

**Comment by fayizan** [comment]
@LegitSoulja even after I installed Visiual C++ Redistributable 2015 I can't find chakra package 
I m using windows 7

**Comment by LegitSoulja** [comment]
@fayizan I'll figure it out soon.

**Comment by LegitSoulja** [comment]
Bad news, I heard that options is hidden for Windows except Windows 10. 

The required libraries for Chakra comes from the edge browser. Try installing the edge browser on win7. If that doesn't work I will have to find an alternative way to install Chakra :/. Hope that helps.

**Comment by fayizan** [comment]
@LegitSoulja It is impossible to install edge browser in windows 7 :(

**Comment by systemroot** [comment]
If you can find a way for linux this will be awesome :confused: 
i have try on ubuntu but..
![](http://image.prntscr.com/image/5b089500ba374d83b4fe5f369fda5f79.png)

**Comment by LegitSoulja** [comment]
@systemroot I will release for Linux, I just haven't got a chance too yet. The jxcore you used isn't supported with ogarul since I think what you used isn't updated.

**Comment by David1ali12** [comment]
am getting the same error using windows 10 :(

**Comment by fayizan** [comment]
@Legitsoulja Linux is best than windows in handling ogarul and it will be more awesome to see ogarul with jxcore in linux

**Comment by CalvinDKHD** [comment]
this error occurs when i follow the steps - https://gyazo.com/356ef45ac733cf5e49355a0ffd4cf3e9

**Comment by CalvinDKHD** [comment]
BTW Sorry soulja, if i said something wrong.

**Comment by CalvinDKHD** [comment]
@fayizan Single, thats why it sucks.

**Comment by LegitSoulja** [comment]
@fayizan @CalvinDKHD @systemroot Linux tut added

**Comment by systemroot** [comment]
@LegitSoulja as i say JXcore has delete their binaries and files :sob: 
<pre>
wget https://s3.amazonaws.com/nodejx/jx_deb64.zip
--2016-06-20 23:27:04--  https://s3.amazonaws.com/nodejx/jx_deb64.zip
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.120.154
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.120.154|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2016-06-20 23:27:06 ERROR 403: Forbidden.
</pre>

**Comment by firelightning13** [comment]
It was deleted a long time ago...

**Comment by NoiseControllers** [comment]
http://jxcore.com/xi.sh = 404 not found
https://s3.amazonaws.com/nodejx/jx_ub64.zip = 403 forbidden
https://s3.amazonaws.com/nodejx/jx_deb64.zip = 403 forbidden
https://s3.amazonaws.com/nodejx/jx_rh64.zip = 403 forbidden

Congratulations for the guide. It has been very useful to me ;-)

**Comment by ItzLevvie** [comment]
JXCore is discontinued that's why they removed the links.

**Comment by LegitSoulja** [comment]
@JXCore nope, they didn't. There's still working version but the Linux one is long and complicating and I could get it to work. I tried self installing, building it, nothing :/.

**Comment by ItzLevvie** [comment]
^^ http://www.nubisa.com/nubisa-halting-active-development-on-jxcore-platform/

**Comment by LegitSoulja** [comment]
@ItzLevvie actually, it's simple. 

* Git clone > https://github.com/jxcore/jxcore
* ./configure --engine-chakra
* make
* make install 

You should have jxcore installed. Haven't tested it but that should work.

**Comment by NoiseControllers** [comment]
I have followed your footsteps
https://gyazo.com/d57f58f63754eb8324074a6fcca53ea6

**Comment by LegitSoulja** [comment]
Did you use chakra engine on configuration?

**Comment by XtremePlayzCODE2** [comment]
Is this supposed to fix lag?

**Comment by LegitSoulja** [comment]
No, it allows you to run on more cores than one

**Comment by NoiseControllers** [comment]
how to solved?

https://gyazo.com/a741430f1f68cf6ece127a043f7ebc81

**Comment by fayizan** [comment]
**@LegitSoulja did u remember this  #38  ...?**

**Comment by CalvinDKHD** [comment]
I get an error  / https://gyazo.com/7a4ba76f32919c3c4a465ce598557d30
its when i do ./configure --engine-chakra

**Comment by LegitSoulja** [comment]
I'll open this back when I get **proper** installations for all os.

**Comment by genckaptan55** [comment]
As I've searched, chakra engine isn't avaible for Linux distrubutions at least for now which means you can run multithread node application just with windows server. That's really sad.
