### ISSUE TITLE
Huge Mass Glitch

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#1049]
Eject some 4000-7000 Mass in corner then do virus throw you will see your server lags and when you eat the thrown viruses you will get 100k-213k Mass! that is the Glitch!

**Comment by LegitSoulja** [comment]
We all know about the ejected mass and viruses. Of course doing that will just make things worse

**Comment by Hazani** [comment]
you got an clap;my friends do that to get 100k+ so thanks for sharing it.I will now try to make an fix for this like changing settings

**Comment by Agarian** [comment]
Same here! When Ejecting tons of viruses into one spot, lags. And when eating it, it gives WAY more mass than it should.

**Comment by PrinceDark9243** [comment]
@Andrews54757 Need to fix it its so Cheating Glicth work on Rhapy's Server Well!

**Comment by Andrews54757** [comment]
Fixed in upcoming update
