### ISSUE TITLE
Bots on kill disconnect also not respawn

### ISSUE THREAD

**Issue by agariobro12** [AJS-development/Ogar-unlimited#1050]
I add 20 bots i killing he and the bots not respawn also i need to add new bots Please help its Su** :D

**Comment by PrinceDark9243** [comment]
lol the bots are brand new!

**Comment by lotfis** [comment]
@agariobro12 in src/settings/config.ini change botrespawn to 1 (botrespawn = 1)

**Comment by Agarian** [comment]
Bots are not brand new... they've been around for years! Minions tho have been here for months.
