### ISSUE TITLE
How do you put this on a website?

### ISSUE THREAD

**Issue by pleashehelpz** [AJS-development/Ogar-unlimited#1051]
Im having trouble on what to do with the agarioclient and where to put it in my website and where to put the other things, could you help me?

**Comment by LegitSoulja** [comment]
We can't help you. If you don't have experience we don't care. Too many people stealing our work and claiming it as there's w/o giving credit.

**Comment by RelTakeover** [comment]
http://agario.city/betaserver/play.php , fuck leitsoulja :p

**Comment by NatsuTheGreat** [comment]
You want to get you shit pushed in? 

@LegitSoulja Some manners this guy has got.

@Andrews54757 In your opinion what should we do with [this](http://prntscr.com/bhn969)

**Comment by David1ali12** [comment]
@RelTakeover go to hell

**Comment by systemroot** [comment]
@RelTakeover  Rlly ?
![](http://image.prntscr.com/image/a7dd44a257e240e081b63f9797a375c0.png)

**Comment by NatsuTheGreat** [comment]
Lmao I am not even going to disable anything.

**Comment by Agarian** [comment]
@systemroot get Anti-adblock-killer at https://reek.github.io/anti-adblock-killer/ for tampermonkey/greaseymonkey, it'll fix ur problem :]

**Comment by LegitSoulja** [comment]
@NatsuTheGreat it's fine, we don't have to do nothing about it. That's just what happens when kids get upset.

**Comment by NatsuTheGreat** [comment]
@LegitSoulja Alrighty :) Never was going to play on there anyway.
