### ISSUE TITLE
I can't control my Cell and Minions

### ISSUE THREAD

**Issue by DerpyYT** [AJS-development/Ogar-unlimited#1053]
So I got the version of Ogar 17.2.5 and it Reduced Lag, I joined my server and put the command prompt, >minion 1 80 </random> and some annoying thing happened,  The minions and my Cell itself were uncontrollable, When I split with my cursor on the right, my cell splitted left and movement was annoying, the same thing for the minions aswell, If you Don't understand what I mean, Here's a Vid Link>https://www.youtube.com/watch?v=d2se_9TpXh4&feature=youtu.be

Can Anyone Help!

**Comment by Hazani** [comment]
Try re-downloading it,if again happens maybe problem with node.js or with your coumputer.If it worked,
try doing the same changes if that happens maybe you made something wrong in your changes at your config,clientconfig,advconfig (i dont write override beacuse thats nothing xD maybe old thing can glitched it too.)

**Comment by Agarian** [comment]
Actually i have experienced this in the past
