### ISSUE TITLE
Issue in the RecombineTime{branching off to my previous issue}

### ISSUE THREAD

**Issue by DerpyYT** [AJS-development/Ogar-unlimited#1057]
So i figured out the problem to the glitchy splitting on my previous issue, but I'm not sure why this one part of the config is the cause, the config "Recombined Time" cause the weird splitting for some reason, when i put the Recombine time to 1, it started the weird splitting thing, but when I put it back to 30, it magically fixed itself, someone please help me why this is causing it.

**Comment by LegitSoulja** [comment]
@DerpyTV you play PS3?

And because, recombine if set to 1 your cell will automatically start merging back again.. Duhhh. Set it to 2-4 for a better splitting

**Comment by DerpyYT** [comment]
@LegitSoulja 

No what I mean That when my cursor is on the left and i wanna split left but my cell splits right, and i put in the command prompt, >minion 1 80 </random>, so i have minions, when putting the recombine time to 1, but it fixes itself when i put the recombine time to 30,

**Comment by DerpyYT** [comment]
@LegitSoulja also look at my previous issue of what i mean

**Comment by Agarian** [comment]
Please don't duplicate issues!

**Comment by Agarian** [comment]
@LegitSoulja he means this https://www.youtube.com/watch?v=d2se_9TpXh4&feature=youtu.be
