### ISSUE TITLE
Skins in Ogarul.io

### ISSUE THREAD

**Issue by AverageUser123** [AJS-development/Ogar-unlimited#1059]
Some time ago in Ogarul.io skins list appeard.I try to use them but that not working :(
If anyone can tell me how to use skins list correctly?

Thanks :)

Sorry for any spelling mistakes :)

**Comment by David1ali12** [comment]
Remove skins in customskins,txt then it should work , remove all links & names.

**Comment by AverageUser123** [comment]
When I remove it all skins in skin list disappeared.

**Comment by David1ali12** [comment]
idk what you mean
> skin list disappeared. 
not possible

**Comment by Agarian** [comment]
I think he means the url ogarul.io/skins/

**Comment by Agarian** [comment]
It simply redirects  back to http://ogarul.io

**Comment by David1ali12** [comment]
not supported!.

**Comment by LegitSoulja** [comment]
@Agarian some things you just can't see with your eyes but it's there.

**Comment by AverageUser123** [comment]
Ech,ok so it doesn't work.Thanks anyway :)

**Comment by steventhekiller** [comment]
someone can tell me how to get the skins change alone

**Comment by LegitSoulja** [comment]
@steventhekiller The skin change? Or do you mean just the skins? I had the link public but @Megabyte918 removed it by ill add it back. Just don't remove this link because I provided it for a reason(Public reasons, meaning I don't care about it). Thanks.........

> http://play.ogarul.tk/skins.zip
