### ISSUE TITLE
"Deleted server from Statistics"

### ISSUE THREAD

**Issue by systemroot** [AJS-development/Ogar-unlimited#1060]
![](http://image.prntscr.com/image/1a57d1d3efd94a1e9379030303c29aa4.png)
Both my server are deleted. Why?

**Comment by raphyjb** [comment]
👍

**Comment by systemroot** [comment]
@raphyjb what do you want to say with that?

**Comment by Andrews54757** [comment]
@LegitSoulja I think the ban system is faulty, I think there is bugs with it. Maybe you should remove the ban system entirely

**Comment by NoiseControllers** [comment]
WTF...
they know that ip use our servers?, 
if this is so I will stop using ogar. backdoors

**Comment by systemroot** [comment]
@Andrews54757 I hope they will fix it. 
But ill not gonna use it again. One time was banned and now my servers deleted. 
If is any problem this will be for all not just for my servers. 
and this plugin is so f'ed. keep send me too much notifications u'r banned and statistics fail to find srv ip as much as i can't write a command in console. and look that color in console wtf. Just a little plugin and 100 errors from it. I suggest LegitSoulja to work more seriosly. And to use "ping" on stats.ogarul.tk this is not a good idea  because some vps providers has disable **icmp** for clients and  Ogar servers can't be showed at stats. And i disable my security on my server because if anynone will try to ping server that much will be banned.

**Comment by raphyjb** [comment]
There is no bug to this :* this was made to be so*
-LegitSoulja will answer u!

**Comment by systemroot** [comment]
@raphyjb First i'm not judge anyone just i'm telling what happen. If Ogar is for free For what are you asking o.O ? If you don't know to create/Develop a plugin what do you want to do with that?
And you will need to ask "How old are you" after this try to call me "Kid"
And don't tell me "learn how to setup" Because i have explain all on my comment and you have not understood nothing for it so i'm sorry but your a fucking noob. which just know how to start/stop server Ok ?!
And when your are a noob don't try to call others "Kid" "bitch" etc. And go the fuck way i don't have time to talk with you. If i deserve a ban. Will be banned.

**Comment by LegitSoulja** [comment]
@Andrews54757 No, the ban system is not faulty, system root was banned for a reason. He should've never modified the plugin and made his players high to cheat on the stats table. That's why he was banned and his servers was removed, and statistics was encoded. After all he can get unbanned if he update statistics and don't modify the plugin again.

**Comment by LegitSoulja** [comment]
In the past there was a few bugs with the ban system, but I have already fixed that. If you mistaken got a ban message your servers wouldn't be removed :/. But his was removed manually by me.

Note: My ban system is by IP address and not game uid. If you get banned all your servers that's on the ip will be dropped from the table. There's rules that needs to be followed. Other than that if nobody can't follow them I'll just get rid of statistics completely.

**Comment by LegitSoulja** [comment]
@systemroot aka **Raw Servers**

**Comment by LegitSoulja** [comment]
@systemroot and FYI since you modified the plugin, and don't know what you are talking about it would be stupid of me to even PING the client site. IF you can read properly like how you modified your players only thing that's get pinged is Google to check the ping. I guess you really don't know anything :/

**Comment by systemroot** [comment]
@LegitSoulja i swear i have not try to edit or doing anything with it. Because i have not learn about node i have not use it before and i don't know how it work!
i have delete now all it  + ogar folder, but my config.ini was like this
<pre>
// Your unique specfic name for your server :) **YOU HAVE TO CHANGE THIS**
serverName = "Server (name)"

// Make this 0 to Disable alerts abouts stats on connections and updates via statistics
alerts = 1

// If enabled(1) your ip or VPS ip will be updated. Use (0) to use customip/domain
usevpsip = 1

// This can only be used if usevpsip is 0. Mainly your IP your friends will connect to. NOT LOCAL HOST!
// DO NOT ADD A PORT!!!!!
customip = "mydomain.com"

// Make this 1 to be able to opt out and keep the plugin, and remove all statistic information.
optout = 0

// If you are using a client other than play.ogarul.tk, enter here. Ex("example.com") Don't add /?ip!. it is not required. But your server will use this to redirect.
// By default, if clientlink is null/empty/contains no char play.ogarul.tk client will be used instead of agar.io or any other.
clientlink = "mydomain.com"
// If you want to see more information output in your console you might not even understand but be my guest..
debug = 0
</pre>

One of my srv was showed 2 times i don't know why! 
just today 1hour ago i check stats.ogarul.tk and i didn't see my server when i logged in say a notification Statistics was updated and i shut down Ogar, i go at /plugins i delete that old folder and i turn on Ogar i try "plugin install Statistics" then i try "stats create, refresh " as you can se in that scr!

And stats.ogarul.tk is pinging VPS ip m8, try to block icmp and your server will be offline in stats.ogarul.tk :)

**Comment by LegitSoulja** [comment]
stats don't ping.. Stats and the client both checks to see if the server is online or not then it cancels instantly with a 1 second time out.

I'm not talking about you modifying the config, I'm talking about you modifying the plugin. I have witness of your server reported of you having 20 static server players with nobody on your server but 1 or 2 people. You can't cheat to have you server on top. Since that you was banned. Update the plugin then I will Unban you. If you do it again you won't be unbanned.

**Comment by LegitSoulja** [comment]
Specifically **Raws Main** was reported. Update statistics on that server, and the rest of your servers and I will Unban you,

**Comment by systemroot** [comment]
@LegitSoulja For real i'm telling you i have not modify anything. I don't want my server ontop. 
If i want i will not use 10 minions only for myself. and trolling people as much as they start to "blame" or i don't know how to say in eng, when some one start telling "fu, you" and those things. -.-

but for ping, just i'm telling why some servers can't be online at stats.ogarul.tk, (If ports are OK.)
if you want i can give you a vps install ogar + statistics, make it onlline on "stats."
and i will block ping, after this you will not see it anymore on stats.
i was deleted all other server online was only "raw official " and "raw monsta"

**Comment by Andrews54757** [comment]
@LegitSoulja Unban him, il help you make the plugin uncheatable

**Comment by LegitSoulja** [comment]
@Andrews54757 it's best to be encoded. People who knows can edit the plugin with ease. I have found some recent problems that I do need to fix, it's not big problems but eh, it could be a better setup of the plugin for better maintaining, and checks and stuff before sending data to the server.

@systemroot you will be unbanned in a minute or so.

**Comment by systemroot** [comment]
Ok Thanks.

**Comment by LegitSoulja** [comment]
@systemroot system bots, and players are both differently calculated. You have a few bots and 20 players, but in reality at the time you only have 1-2 players on. Minions and bots aren't players.

About the ping, and with the servers there's only 1 way I can test if a server is online or not. It still isn't the best way but it's the only way. I would test ws test, but that's a bad idea. If I find a better solution I will use that. I even tried fsock and all connections failed :/

**Comment by systemroot** [comment]
@LegitSoulja Exactly this was problem, because "RAWCLAN (Official)"  was 2 times in Stats, 
One day I make a VPS restart and he didn't start again so i delete it an i create it again, i reinstall ogar+statistics
after this i Forget Server name and i make it like this " RAWCLAN (OFFICIAL) "
when i visit stats.ogarul.tk i see my server 2 times with the same ip.
"RAWCLAN (Official)"  and another one " RAWCLAN (OFFICIAL) " 

This is just to show server up/down ?! maybe 
<pre>
if (fsockopen('$server', 443)){
   echo('online');
} else{
   echo('offline');
}
</pre>
 :confused:

**Comment by LegitSoulja** [comment]
Fsock doesn't work for me, I've tried different many ways but nope it doesn't work. The reason why 2 server's appeared is because you deleted ogarul, and what it did was regenerated and new gameuid, and you didn't delete / stats abort when you removed statistics when you restarted.

I'm coming out with a new update, which shouldn't duplicate, nor replace, nor have common errors with like network connectivity, failed to get ping, and failed to update. I'm coding it much better than what I did last time :/. Statistics was kindof like a beta for testing to see how everything will work out.

**Comment by systemroot** [comment]
@LegitSoulja Now i understood, 
i create that vps from snapshot and i think my old gameuid was into it
Sorry, If i make any new install i will delete all files before!
*i don't know if you have make any change but now i can find 149.202.248.153:443 on stats*
Waiting for updates :+1:

**Comment by LegitSoulja** [comment]
@systemroot do stats delete, then restart the server

**Comment by Agarian** [comment]
Can i close this?

**Comment by Agarian** [comment]
FAIL its already closed
