### ISSUE TITLE
Whats token of our server (ogarul.io) 

### ISSUE THREAD

**Issue by Zertag** [AJS-development/Ogar-unlimited#1061]
i want to play w/ my friend in ogarul.io i have console launched and ther is "Party/IP/Token" whats it ?

**Comment by Andrews54757** [comment]
your ip

**Comment by Zertag** [comment]
how to find it

**Comment by Zertag** [comment]
i have it it doesnt work halp plz

**Comment by Andrews54757** [comment]
Try to use play.ogarul.tk/?ip=(yourip)

**Comment by Zertag** [comment]
dont work

**Comment by LegitSoulja** [comment]
No, your token/ip is ws://{IP}:{PORT} if you are using ogarul.io

Or you can do
play.ogarul.tk/?ip={IP}:{PORT}

If you are running the server your ip is localhost with port 443, you give your friends your ip http://ipchicken.con

Note: Don't include the brackets

**Comment by Zertag** [comment]
ok
