### ISSUE TITLE
Port Forwarding help

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#1062]
I opened the ports: **88(ServerStatsUpdate) , 60(ServerStatsPort), 564(My server port) and 1000**,when I test all fail, I'm sure they so open more do not know why they fail, I used the progam " Simple Port Tester " to test if ports are working, but when I start the test all went wrong, look [here](http://prntscr.com/bhxvs8) .
**Modem : TP-Link TL-WR841N**

**Comment by LegitSoulja** [comment]
Check your firewall

**Comment by GhostShot3** [comment]
@LegitSoulja Disabled

**Comment by LegitSoulja** [comment]
Is it working? I wouldn't recommend disabling it, I would set my inbound rules for the ports you got open.

**Comment by GhostShot3** [comment]
@LegitSoulja Hes firewall is 100% disabled.

**Comment by LegitSoulja** [comment]
Ok so you confirm that your ports are open now? If so please close this issue. Thanks.

**Comment by GhostShot3** [comment]
@LegitSoulja Yes they are open more tested and just does not work.

**Comment by LegitSoulja** [comment]
@GhostShot3 next then is to check windows defender, or any anti virus software you have. Sometimes they come with a port manage system aswell since it is also a firewall. Norton, and windows defender i know for a fact does this.

Use the simple port forwarding tool if you don't know how to port forward correctly. Your port has to redirect to your ipv4 computer ip address in your router NAT.

**Comment by GhostShot3** [comment]
@LegitSoulja 
This all disabled and the door still does not work.

**Comment by LegitSoulja** [comment]
@GhostShot3 I recommend looking up on google on how to portforward with your specific router. There's no further help that can be provided. Now it's all up to your router that needs to be dealt with correctly.

**Comment by GhostShot3** [comment]
@LegitSoulja I'm sure it opens right,reopen.

**Comment by Megabyte918** [comment]
@GhostShot3 I'm not sure how this works, but the same thing happened to me when @David1ali12 tried to join my server even after i port forwarded and opened all my ports. I installed uTorrent and left it open (after the server was started) running on the same port as my server and THEN he could joinr some reason

**Comment by LegitSoulja** [comment]
@Megabyte918 it had to have some type of firewall issue. Like the last issue you said you can port forward using uTorrent which is false, but whilst uTorrent is running it runs through firewall which the allow that port through firewall.

Any anti-virus software, Windows defenders, and type of security, and firewall can be common issues why ports aren't working.

Make sure in skype network settings and disable port **443** and to use a random port.

Open cmd and run **netstat -a** and make sure you have no active ports open on your **IPv4**.

Al check your network adapters. If you are using either wireless, or Ethernet you need to specify that adapters IPv4 when port forwarding.
