### ISSUE TITLE
Multiverse?

### ISSUE THREAD

**Issue by aqweqwel123** [AJS-development/Ogar-unlimited#1063]
when i connect to my 2nd server when i use multiverse and you try to connect to it and join u can join but it glitched and everyone names have chinese symbols, then u cant see the map anymore.

**Comment by SorryAgario** [comment]
did u use the ogarul client?[play.ogarul.tk](url)

**Comment by aqweqwel123** [comment]
yes

**Comment by Megabyte918** [comment]
try changing the packet version in advconfig.ini

**Comment by Megabyte918** [comment]
try changing the packet version in advconfig.ini
