### ISSUE TITLE
How To Install Ogar Unlimited On Cloud 9 (c9.io) 13 steps :/

### ISSUE THREAD

**Issue by sethdm02** [AJS-development/Ogar-unlimited#1064]
1. If you havent already make an account Make sure you use Ubuntu When you create a workspace
2.download it `wget https://github.com/AJS-development/Ogar-unlimited/archive/master.zip`
3.Now unzip it `unzip master.zip`
4.now do `sudo apt-get update` then `sudo apt-get install rlwrap`
5.install nodejs `https://deb.nodesource.com/node_5.x/pool/main/n/nodejs/nodejs_5.9.0-1nodesource1~trusty1_amd64.deb` then `sudo dkpg -i nodejs_5.9.0-1nodesource1~trusty1_amd64.deb`
6.go to the directory  `cd Ogar-unlimited-master`
7. now type this command 'npm install' (what from i know ogar client does not work but you can play on play.ogarul.tk)
8. on the left their should be a file manager go to the directory were ogar unlimited open src  then settings the double click advconfig and change the port to either 8080 to 8082
9. then press run at the top wont do anything but it saves it idk how to save it :P unless you press run then going back to the other terminal press 
10.drag start.sh to text editor and put sudo in front of node (make sure theres a space) then press run at the top
11. at the top click on windows then share then you will see see application copy that and go to [Play.Ogarul.tk](http://play.ogarul.tk/)
12 copy the applictaion link ws://applicationlink:port you used for ogar unlimited
13.And there you have it that didn't work idk

**Comment by LegitSoulja** [comment]
We don't support C9, and it's against there TOS.

**Comment by sethdm02** [comment]
oh lol xD

**Comment by sethdm02** [comment]
Got banned pretty fast wtf
