### ISSUE TITLE
Anyone know how to add extra zoom ?!

### ISSUE THREAD

**Issue by systemroot** [AJS-development/Ogar-unlimited#1065]
Please can you help me with this?!
All times which i have play agar i was using agar+ then they patch those and i run away from agar. 
i can't play without extra zoom please suggest me any option which you know!
it's ok when i'm small, but what if i go bigger?
![](http://image.prntscr.com/image/9f4faabc53b648beb79439a644ba8931.png)

i'm using this client https://github.com/AJS-development/Ogar-unlimited/issues/918

Edit: Andrews54757 has wrote : "don't ask about it" but well i really want extra zoom i'm sorry :confounded:

**Comment by SorryAgario** [comment]
use an old version of ogar, then use bagar helper, but u expect alot of bugs

**Comment by ItzLevvie** [comment]
You can edit the zoom settings in the main_out and in the Ogar-unlimited server.

**Comment by LegitSoulja** [comment]
There's 2 types of zoom. ViewZoom, and the radius from your cell of what you can actually see. We don't discuss about clients, and this question shouldn't be answered.

**Comment by systemroot** [comment]
@ItzLevvie I will try :/ Thanks
@LegitSoulja I'm sorry again!
