### ISSUE TITLE
Minion counter

### ISSUE THREAD

**Issue by MineMooreALT** [AJS-development/Ogar-unlimited#1066]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
no issue
What version are you on?
Latest
What command did you type if any?

You must have a description as well
Hey is there any way we can have a minion counter like if you have 50 a box in the top left that says 50 minions with the name "minion"
Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

**Comment by aqweqwel123** [comment]
just us LBstats

**Comment by Agarian** [comment]
Not exactly what he means.

**Comment by LegitSoulja** [comment]
Is it possible to update the end leaderboard of a player and not everyone else's? Or is the leaderboard just for all?

**Comment by Agarian** [comment]
Its for all ATM, but cool idea

**Comment by Agarian** [comment]
It could be a new command: 'boardplayer playerID text'

**Comment by LegitSoulja** [comment]
@Agarian I was wondering.. Im making a new plugin called LeaderboardFX https://github.com/AJS-development/OgarUL-Plugin-Library/tree/master/LeaderboardFX. I was just wondering :/

**Comment by Megabyte918** [comment]
closing this 4now, please put in suggestions

**Comment by Megabyte918** [comment]
closing this 4now, please put in suggestions
