### ISSUE TITLE
Questions about hosting & infrastructure

### ISSUE THREAD

**Issue by twigario** [AJS-development/Ogar-unlimited#1067]
Hi,
When i choose a dedicated server , what are the importants characteristics ?
The ram ? CPU ? ... etc ?

What is the best offer i can choose ( < 120 $ ) 
https://www.soyoustart.com/us/cpu/
https://www.ovh.com/fr/serveurs_dedies/enterprise/ 

& how many players can be connected without lags , how many servers i can put online in the server ?

It's very important thx ...

**Comment by systemroot** [comment]
If you want to spam with those things here this is not a good idea!

If u'r seriosly, then go at gaming zone https://www.ovh.com/fr/serveurs_dedies/game/ a server with 4.0/ 4.4 GHz will be a real monsta.!

**Comment by SorryAgario** [comment]
LOL
