### ISSUE TITLE
Can't connect even with localhost

### ISSUE THREAD

**Issue by jollesnaas** [AJS-development/Ogar-unlimited#1073]
I'm having some problems with connecting: I use the play.ogarul.tk client, but still, I can't connect. I'm running OU (Ogar unlimited) on windows server 2012 vps and even when I try to connect to my server ON THE VPS with play.ogarul.tk/?ip=127.0.0.1:443, I still can connect what can I do?

Here is a console log:

> [INFO] Loading Config Files...
> [INFO] Loading C:/Users/Administrator/Desktop/Ogar-unlimited-master/src/core/../
> settings/advConfig.ini
> [INFO] Loading C:/Users/Administrator/Desktop/Ogar-unlimited-master/src/core/../
> settings/clientConfig.ini
> [INFO] Loading C:/Users/Administrator/Desktop/Ogar-unlimited-master/src/core/../
> settings/config.ini
> [INFO] Loading C:/Users/Administrator/Desktop/Ogar-unlimited-master/src/core/../
> settings/override.ini
> [INFO] Your unique id is: jolleou
> [INFO] Loading plugins
> [INFO] Starting ConsoleService
>                                         _ _       _              _
>                                        | (_)     (_)_           | |
>   ___   ____  ____  ____    _   _ ____ | |_ ____  _| |_  ____ _ | |
>  / _ \ / _  |/ _  |/ ___)  | | | |  _ \| | |    \| |  _)/ _  ) || |
> | |_| ( ( | ( ( | | |      | |_| | | | | | | | | | | |_( (/ ( (_| |
>  \___/ \_|| |\_||_|_|       \____|_| |_|_|_|_|_|_|_|\___)____)____|
>       (_____|
> [Game] Ogar Unlimited - An open source Agar.io server implementation
> [Game] By The AJS development team
> [Game] Server version is 17.2.5
> [Game] Loaded stats server on port 88
> [Main] Listening on port 443
> [Main] Current game mode is Free For All
> Garbage collecting in 1440 minutes!
> TypeError: "callback" argument must be a function
>     at exports.setTimeout (timers.js:314:11)
>     at GameServer.mainLoop (C:\Users\Administrator\Desktop\Ogar-unlimited-master
> \src\core\GameServer.js:1564:7)
>     at tryOnImmediate (timers.js:543:15)
>     at processImmediate [as _immediateCallback] (timers.js:523:5)
> >[OK] Uniban updated
> 

I can give acces to vps if needed: (No private stuff on it)

Thanks
- Jolle

**Comment by ItzLevvie** [comment]
```
TypeError: "callback" argument must be a function
at exports.setTimeout (timers.js:314:11)
at GameServer.mainLoop (C:\Users\Administrator\Desktop\Ogar-unlimited-master
\src\core\GameServer.js:1564:7)
at tryOnImmediate (timers.js:543:15)
at processImmediate as _immediateCallback
```

Downgrade to Node 5.9.0

**Comment by LegitSoulja** [comment]
You are running windows. I recommend download ![Node v5.9.0_x64](https://nodejs.org/download/release/v5.9.0/node-v5.9.0-x64.msi)

**Comment by jollesnaas** [comment]
@LegitSoulja @LegitSoulja Thanks for the fast replay
!
