### ISSUE TITLE
Possible ?

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#1074]
When up to 4000 mass he line is automatically disable, I'm sure the Smooth Render is disabled,i want how keep forever,if possible.

**Prints
Line -4000 mass > http://prntscr.com/bifc9b
Line +4000 mass > http://prntscr.com/bifdm3**

## Sorry bad inglish.

**Comment by David1ali12** [comment]
yes Possible
src/settings/clientconfig 
you can make smooth render as default for server.

**Comment by GhostShot3** [comment]
@David1ali12 It's not that I want the smooth rendering off,and want this line keep forever because when up to 4000 it auto disable

**Comment by David1ali12** [comment]
this from client you cant :/

**Comment by GhostShot3** [comment]
@Daiid1ali12 you have java script experience

**Comment by GhostShot3** [comment]
@David1ali12  you know how to use cigar

**Comment by David1ali12** [comment]
idk I have never used.

**Comment by RelTakeover** [comment]
is possible , edit main_out.js , change smoothrender = .4 to smoothrender= false;


I warn you bring lots of lag

**Comment by GhostShot3** [comment]
@RelTakeover Give me code

**Comment by RelTakeover** [comment]
what code

**Comment by LegitSoulja** [comment]
We don't discuss about clients. Recent update you can now update the client via game files ./settings/clientconfig.ini
