### ISSUE TITLE
How Do This ????

### ISSUE THREAD

**Issue by kareemman00** [AJS-development/Ogar-unlimited#1076]
How Make Servers like That And Made It For Puplic And How Make Them With Skins like That http://i.imgur.com/S5ByRkL.png

**Comment by SorryAgario** [comment]
ummmm portforward or use a vps.

**Comment by David1ali12** [comment]
:smile:  did you really searched ogarbot.ovh XD

**Comment by LegitSoulja** [comment]
Puplic .. You know, any issues with no effort just close them cause I'm pretty sure nobody wants to be embarrassed. :)

**Comment by Agarian** [comment]
Puplic
---^
TypoError: Incorrect letter P
