### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SorryAgario** [AJS-development/Ogar-unlimited#1079]
Why not do the same look of the new agario? https://github.com/OgarProject/Ogar like that? make everything better and add minions :)

**Comment by Megabyte918** [comment]
??

**Comment by Andrews54757** [comment]
Why? I like the old look better and I think money clip would sue us if we used the new graphics

**Comment by Agarian** [comment]
Maybe add a stroke style to the cell border even in smooth render? on the client.

**Comment by David1ali12** [comment]
Can we have a special cell border for each skin
this will make the graphics so beautiful
@Andrews54757 can you add it please 
I will make a list of all skin borders colors
