### ISSUE TITLE
How to add 2 servers in client?

### ISSUE THREAD

**Issue by RasyiidWho** [AJS-development/Ogar-unlimited#1080]
How to add 2 servers in client?
Like FFA connect to 127.0.0.1 and FFA 2 connect to 121.12.12.211

**Comment by Andrews54757** [comment]
yeah but for it to work with the official client, it is only cross-port. You need your own client to do this

**Comment by CalvinDKHD** [comment]
i got it too work xD but its running on 3 different ports.
