### ISSUE TITLE
Gracias!

### ISSUE THREAD

**Issue by loganagar32** [AJS-development/Ogar-unlimited#1085]
Gracias por la adición de español
mi sugerencia
![fgrgrg](https://cloud.githubusercontent.com/assets/19589095/16200163/cf66ae60-3714-11e6-86c4-6cbf667b9e13.PNG)

**Comment by Andrews54757** [comment]
De nada.

**Comment by NarutoGamerPro** [comment]
Yo igual le agradezco a usted @Andrews54757
