### ISSUE TITLE
Nodejs is using single core or multi cores?!

### ISSUE THREAD

**Issue by systemroot** [AJS-development/Ogar-unlimited#1087]
To have lag in a server with 24 cores and 30 GB ram 30GB swap, this is not good.!
So i start monitoring node. 
I got a server with 8GB ram 15GB Swap 4Cores and i install vnc, I start to make tests after some fails i found this. 
![](http://image.prntscr.com/image/75d9d6feb7bb4929a48a8818f640b75f.png)
i search on google about this and i found this.  http://stackoverflow.com/questions/2387724/node-js-on-multi-core-machines

Maybe ogar-unlimited team can make nodejs to run in multi cores?! or is done with this?!
I read about that **cluser option** https://nodejs.org/api/cluster.html But i have no idea how node work and i don't know how to do this.

**Comment by sethdm02** [comment]
no Nodejs is not mutli core :( get jx core

**Comment by systemroot** [comment]
@sethdm02 jxcore has delete their binaries and some other files. 
but i try from here https://github.com/thaliproject/jxcore , and i get an error with "readline"

Now i'm waiting for LegitSoulja release on linux!

**Comment by fayizan** [comment]
I hope @LegitSoulja will soon upload a working JxCore Method for all OS,I m too waiting for it soo eagerly and all u need is to follow his issue #1048  for the JxCore updates
