### ISSUE TITLE
skins?

### ISSUE THREAD

**Issue by aqweqwel123** [AJS-development/Ogar-unlimited#1088]
im not sure how i messed them up but i added the Client folder to my vps and to my site and still did not work go http://agarprivate.cf/ if u would like to see what im talkin about

**Comment by systemroot** [comment]
1.
add a sking into 
**src/customskins.txt**
example **doge :http://aweb.com/aimage.png**

2.
open **src/randomSkins.txt**
add **doge**

**Comment by Andrews54757** [comment]
We dont explain client hosting.
