### ISSUE TITLE
Can you play with friends on ogar ul without c9?

### ISSUE THREAD

**Issue by AgarioIsBest1602** [AJS-development/Ogar-unlimited#1089]
I really want to play with my friends on my server, so we can do a bot battle. But i dont know how i can let him play on my server and if its possible. Does any1 of you know how to do it?

**Comment by olivierek6** [comment]
hamachi

**Comment by LegitSoulja** [comment]
Hamachi isn't supported..
https://github.com/AJS-development/Ogar-unlimited/issues/687

**Comment by LegitSoulja** [comment]
/\ A few deals..

**Comment by Ckicky** [comment]
Well...I can use Hamachi for it tho...

**Comment by CodingKuda** [comment]
@Ckicky  Yeah. But Hamachi lags everything ;-;

**Comment by Agarian** [comment]
Plus you should not use c9 for just play.

**Comment by LegitSoulja** [comment]
Hamachi just sucks period. I never used it, but always had those friends who use it.
