### ISSUE TITLE
What is the language you prefer ?

### ISSUE THREAD

**Issue by Prime55** [AJS-development/Ogar-unlimited#1092]
This message shows up in the console **"What is the language you prefer ? Available : en english es espanhol"** and i can't do anything. If i type anything i get the message **"That language does not exist!Error :ENOENT: no such file or directory, open 'C:Users\...\Desktop\Ogar Unlimited\ogar-unlimited-master\src\locals\english.js** What do i have to do ? @Andrews54757 @LegitSoulja

**Comment by Andrews54757** [comment]
type `en` or `es`

**Comment by Prime55** [comment]
@Andrews54757 Oh damn, so simple, i didn't know what those en/es mean lol. Thanks!
