### ISSUE TITLE
Not optimized at all.

### ISSUE THREAD

**Issue by darknight99x** [AJS-development/Ogar-unlimited#1094]
I have an empty server with around 5 bots and 4 players.

CPU usage is at 15%, and won't use anymore cores.

Kind of getting fed up as there is no way to utilize mutli-core processing on here, as jxcore does not work with ogarUL.

**Comment by darknight99x** [comment]
Nevermind, I apologize.

**Comment by Andrews54757** [comment]
There are more disadvantages for people if we have it multicore. Also, it uses up bandwidth for vps users

**Comment by darknight99x** [comment]
Well it could use some optimizations, I can barely hold 10 players without it falling apart in lag.

**Comment by LegitSoulja** [comment]
The mass ejection got even worse. Don't use macros or your game will lag terribly. I can hold players, but when it comes to shooting w's... R.I.P

Also, minions & viruses don't go together. If a minion eat a virus it could grow 5x its size giving away a lot of mass.

Btw, yes I'm running multi cores, with a over locked CPU with about 32GB ram still laggss :/.

CPU isn't bad, memory stays around 200-700MB, frame rate ehh not to happy with

**Comment by LegitSoulja** [comment]
Gonna try my vps shortly after I upgrade my parts **liquid coolant** and 1 more 16GB **GTX**, red hat os.

If my main computer, nor my vps handles then there's a big problem with ogarul :/
