### ISSUE TITLE
Server only working on internet explorer. HELP

### ISSUE THREAD

**Issue by DTMClanDeveloper** [AJS-development/Ogar-unlimited#1095]
My server only works on internet explorer please help me

**Comment by Agarian** [comment]
Tf? The client is incompatible with internet explorer. Please be more specific

**Comment by LegitSoulja** [comment]
Maybe he meant edge. It's supported actually :). I recommend chrome, but I'm don't use chrome I use canary :D

**Comment by firelightning13** [comment]
@LegitSoulja Hey same as me :D(except that i dont use it right now bcause my laptop's charger is broken atm)

**Comment by LegitSoulja** [comment]
Canary version is awesome, and better than regular ole, ram eater chrome. I hope they trash it and replace it.

**Comment by Agarian** [comment]
Never heard of canary =P

**Comment by LegitSoulja** [comment]
I know. Don't tell anyone about it

**Comment by Agarian** [comment]
then imma delete some comments
