### ISSUE TITLE
[Suggestion] "Rush Mode" new game mode

### ISSUE THREAD

**Issue by NoiseControllers** [AJS-development/Ogar-unlimited#1096]
Preview: https://www.youtube.com/watch?v=DzmeUeO4w-M

is possible?

thanks :)

**Comment by LegitSoulja** [comment]
Looks pretty simple and easy to make haha

**Comment by mafiakb** [comment]
how? :(

**Comment by LegitSoulja** [comment]
I don't see the difference between rush mode and hunger games. There wasn't nothing really much but a timer :/

**Comment by firelightning13** [comment]
Thus is pretty much as FFA Timer mode but not the color of the virus

**Comment by mafiakb** [comment]
![image](https://cloud.githubusercontent.com/assets/12769609/16217973/43c4da92-373e-11e6-8750-b6b4cca22c7b.png)

This is my ogar client :3

**Comment by NoiseControllers** [comment]
The difference Between both is:
Rush Mode
 - It has a timer (4 minutes).
 - Start with 80 mass If this reaches 0 dead
 - the mass is decaying fast
 - you have to eat something to survive

**Comment by NatsuTheGreat** [comment]
@firelightning13 We don't know the exact behavior of the viruses.

**Comment by mafiakb** [comment]
@NoiseControllers this web http://agarz.com or http://happyfor.win have rush mode

**Comment by RelTakeover** [comment]
The developers are thinking create rush game for unlimited?

**Comment by Megabyte918** [comment]
closing this 4now

**Comment by Megabyte918** [comment]
closing this 4now

**Comment by NoiseControllers** [comment]
Why close? it goes develop?
@Megabyte918
