### ISSUE TITLE
Custom url

### ISSUE THREAD

**Issue by clint59876** [AJS-development/Ogar-unlimited#1098]
I have Ben looking for ways to make a custom URL for my server so i don't have to tell people my ip and stuff.

I would like a video tutorial on this problem. I would like a video tutorial because i have no programming skills and other people I know have no programming skills. 

I believe a video would help a lot of people. 

If you text it becomes confusing and hard to understand.

If you can't make a video then maby in the next version you could have a file with the program for a custom URL, with a tutorial on how to use it.

Thank you for your time.

**Comment by LegitSoulja** [comment]
* First you need to buy a domain.
* Second, you need a DNS provider. I recommend using cloudflare, or Blazing.io
* Third, Learn how to add nameservers to domains, and learn what a '**A**' record is.
* Last, Once you made a 'A' record, or 'CNAME' towards your computer ip tha domain is now active, and router to route to your ip.

CloudFlare supercharges your website, and also give you security.

**Comment by Andrews54757** [comment]
Also, we won't explain.
