### ISSUE TITLE
Updates Not Updating

### ISSUE THREAD

**Issue by CodingKuda** [AJS-development/Ogar-unlimited#1099]
When I do "Update Updates" It says "<--- Last few GCs --->

   64716 ms: Scavenge 1399.0 (1458.1) -> 1399.0 (1458.1) MB, 0.8 / 0 ms (+ 7.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   67444 ms: Mark-sweep 1399.0 (1458.1) -> 1398.4 (1458.1) MB, 2727.6 / 0 ms (+ 8.0 ms in 2 steps since start of marking, biggest step 7.0 ms) [last resort gc].
   70787 ms: Mark-sweep 1398.4 (1458.1) -> 1398.4 (1458.1) MB, 3342.2 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000008FAF9E3AD1 <JS Object>
    2: loading [C:\Users\-\Documents\-\Aplications\Ogar-unlimited\src\core\Updater.js:~73] [pc=00000001A88388D5] (this=0000026230FF0B21 <an Updater with map 000002D6D238E879>,action=0000008FAF90CD79 <String[19]: Running npm install>)
    3: runNpmInstall [C:\Users\-\Documents\-\Aplications\Ogar-unlimited\src\core\Updater.js:146] [pc=00000001A90882E8] ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory"

Then when it loads again it says [Console] We have detected a update, Current version: 17.3.0 ,Available: 17.3.1
[Console] Update Details: Found the source of ejected mass and other lag. Stupid typos caused it.
[Console] To update quickly, use the update command!

Why isn't it updating!!??

**Comment by LegitSoulja** [comment]
Weird, that never happened before. Btw this is how you update.

> update all

**Comment by CodingKuda** [comment]
Yeah. DId do Update all. Still it came up with the new update thing..

**Comment by LegitSoulja** [comment]
You shouldn't have to. Sometimes you do when errors happens you can't fix, or a specific file failed to download during updating.

But redownloadinh is fine, and actually better. You should be able to update afterwards in the future.

**Comment by CodingKuda** [comment]
Okey thanks. @LegitSoulja
