### ISSUE TITLE
Smoother Split

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#11]
This 'Smoother Split' of your version not change much, try to add code from https://github.com/ItzLevvie/Ogar-1

**Comment by Andrews54757** [comment]
I am working on it on a separate branch called "Smooth Test" you can use that but it may hold bugs

**Comment by Andrews54757** [comment]
I Perfected the code and it is now updated on master (YAY!!!, Finally)

**Comment by Agarian** [comment]
why can i not create pull requests? it just says compare or something and doesn't let me create a pull. i just has one tweak for splitting and one gameserver.ini

**Comment by Agarian** [comment]
*Choose different branches or forks above to discuss and review changes.*
that's what i get next to the pull request button^
it doesn't let me click it.
![capture](https://cloud.githubusercontent.com/assets/15255724/12691909/832c00b6-c6be-11e5-98e7-36b5fb321e71.JPG)
