### ISSUE TITLE
Splits bug on version 1.7.3.1

### ISSUE THREAD

**Issue by RelTakeover** [AJS-development/Ogar-unlimited#1103]
The split speed , velocity , speed, virus speed and all speeds it increase the velocity from the nothing , splits are unstable velocity is unstable ... the developers will create a good version stable? How fix all bugs?

**Comment by Megabyte918** [comment]
what exactly do you mean by "unstable"

**Comment by RelTakeover** [comment]
split change the velocity of the nothing ... splits very fast , the splitSpeed NOT WORKING , more?

**Comment by Megabyte918** [comment]
You didn't use the latest version from the PR did you?

**Comment by RelTakeover** [comment]
see title 1.7.3.1

**Comment by RelTakeover** [comment]
the version have full bugs , splitSpeed not work , split change its velocity of the nothing..

**Comment by RelTakeover** [comment]
i put splitSpeed = 1 , same speed , splitSpeed = 90 , same speed ...

**Comment by RelTakeover** [comment]
where i can change manually?

**Comment by PrinceDark9243** [comment]
same with me

**Comment by RelTakeover** [comment]
yes is so buggy

**Comment by RelTakeover** [comment]
We need help

**Comment by Megabyte918** [comment]
in lines 88, 91, and 93 of physics.js, change the numbers "78", "74", and "70", to the word "splitSpeed" (**case sensitive**), keep in mind that doing this will make it so every size will have the SAME splitspeed

**Comment by David1ali12** [comment]
Change FPS to 16 or 16.5

**Comment by RelTakeover** [comment]
78  74 and 70 are complementary?

**Comment by Megabyte918** [comment]
they are different splitspeeds

**Comment by RelTakeover** [comment]
What I should change?

**Comment by David1ali12** [comment]
src/settings/advConfig very first lines the splits are perfect with 16 or 16.5 fps does not fit with 20fps 
that was the only way to fix pushback :/

**Comment by Megabyte918** [comment]
Doesn't editing the FPS break everything else that depends on the server ticks tho?

**Comment by RelTakeover** [comment]
edit or no edit fps -.- pls..

**Comment by Megabyte918** [comment]
if you want splitspeed back then you dont have to edit it, but if you want no pushback like david says then change the fps, it may or may not break some things or mess up some timers idk. do what you want
