### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by Mohammad1972050** [AJS-development/Ogar-unlimited#1105]
everything is updated and running good but when i enter the game on the website and click play it stays on the same screen (the menu fades away) but does not enter me to the game.

**Comment by LegitSoulja** [comment]
You aren't connecting to the server with the client properly

**Comment by Megabyte918** [comment]
see the troubleshooting guide or search the issues for a similar problem to yours

**Comment by Megabyte918** [comment]
see the troubleshooting guide or search the issues for a similar problem to yours

**Comment by Mohammad1972050** [comment]
Thanks
