### ISSUE TITLE
problem with last update ..  

### ISSUE THREAD

**Issue by bangana** [AJS-development/Ogar-unlimited#1108]
euh.. last update my server start freezing like crazy and when i feed food ejacts like crazy veryy fast and splitting is a bit slow or something what ever last update didn't reduce lag and made it worst.hope u fix it ASAP @AJS-development/ogar-unlimited-devs

**Comment by David1ali12** [comment]
I did last update its works just so fine  it has 0 problem lag is reduced so much, you might  did something wrong .

**Comment by RelTakeover** [comment]
same problem

**Comment by RelTakeover** [comment]
the splits change its velocity of the nothing , eject mass change its velocity of the nothings , new update , new bugs ...

**Comment by Megabyte918** [comment]
It only freezes when you w too much, the source of the problem is unknown at the moment.

**Comment by RelTakeover** [comment]
the splits change its velocity ..

**Comment by Megabyte918** [comment]
velocity? what do you mean by that?

**Comment by RelTakeover** [comment]
THE SPEED OF SPLITS CHANGE OF THE NOTHING

**Comment by RelTakeover** [comment]
try on http://agario.city/betaserver/play.php

**Comment by RelTakeover** [comment]
try error on agario.city/betaserver/play.php

**Comment by Megabyte918** [comment]
I just told you how to fix that

**Comment by RelTakeover** [comment]
change fps ?

**Comment by Megabyte918** [comment]
the split speed, how to get it to work

**Comment by David1ali12** [comment]
your client dont even have play button -_-

**Comment by RelTakeover** [comment]
see error pls , you not understand me

**Comment by RelTakeover** [comment]
http://agario.city/betaserver/play.php

**Comment by RelTakeover** [comment]
aaaa buugs bugs everywhere

**Comment by Megabyte918** [comment]
ima clean these comments

**Comment by David1ali12** [comment]
be quit programmers are not your slave

**Comment by RelTakeover** [comment]
no!!! THE SPLITS CHANGE ITS SPEED OF THE NOTHING !! NOTHINGG !!! splits fast , slow , fast slows , lagg ,freeze ,fast , slow

**Comment by David1ali12** [comment]
freezing is better than lagging haven't you see vanilla agario it freezes instead of lag looks that you have a bad vps my server is just so smooth with new update

**Comment by RelTakeover** [comment]
dedicated vps

**Comment by Agarian** [comment]
Of the nothing? Elaborate.

**Comment by bangana** [comment]
but it was just fine after i updated it ..

**Comment by LegitSoulja** [comment]
@bangana Yes I know I'm aware, and so the DEV. We still don't know the source of this strange lag but hopefully it gets fixed soon.
