### ISSUE TITLE
Help With GiveMeMinionsToo!

### ISSUE THREAD

**Issue by systemroot** [AJS-development/Ogar-unlimited#1109]
Just i'm editing those configs to minimize the lag on server. 

At my server a player will start with 310 Mass.
and minions will start with the same mass. *(I Don't Know Why.)*

 If a player with try to feed himself with minions in server will be lag too much. maybe server will stop for some sec. 

at my server GiveMeMinionsToo config is 
2 random players will get 5 minions for 2min. 
i was play alone to find better configs for my public server. and if GiveMeMinionsToo will start minions with 10-15Mass they can't feed or split and will not be lag as before. If player will make 1 minion bigger this is not problem even if he will try to feed himself with minion.

So if is anyway how to change GiveMeMinionsToo Mass can you please tell me?
And if is not possible can you make this available in next update of GiveMeMinionsToo ?!
Thanks.

**Comment by LegitSoulja** [comment]
Minions spawn the same as player mass since its recreating a new cell from the same place. This could be fixed, but cannot be part of the plugin but ogarul itself. Maybe when the minion command extension is released it can be added to the plugin. But as of right now it's not possible unless you do it yourself.

**Comment by tommyb008** [comment]
@LegitSoulja how can i get my server on the server list?

**Comment by systemroot** [comment]
@LegitSoulja I understood. thank you.
I realy need your help now. with statistics! i restart server i do **stats override** and Raw (Monsta) 
In stats has stop as Raw official before :/ 
bots/players 15/13 
But in server i have 12 players and 10bots :/  can you take a look at this? maybe from c9.io i can share a instance with you, and i can connect my vps from c9.io terminal..

**Comment by LegitSoulja** [comment]
@systemroot you supposed to do stats override before restarting to save your last configuration. I don't understand what you mean so can you provide more clarity to help you with your problem?

**Comment by systemroot** [comment]
@LegitSoulja is an problem with Statistics :/ 
and i'm asking maybe you can take a look at my server about this from c9.io because i can connect my VPS in c9.io terminal like this 
![](http://image.prntscr.com/image/91e28a2ce641453da977e2c229741968.png)
if yes what is your username at c9? or email. 
If no, no problem :confused:

**Comment by tommyb008** [comment]
if you can please add this to the server list ws://50.173.201.239:443

**Comment by LegitSoulja** [comment]
@tommyb008 use the Statistics plugin

@systemroot there's unknown resolves for c9 because of there domain usage. With your shared c9 domain / link make sure you set **usevpsip** to 0, and set your c9 domain as **customip**

**Comment by systemroot** [comment]
@LegitSoulja m8 you are not understooding me. i'm telling i can connect my VPS from c9.io remotly!

And for problem is this and i have not modify anythink.! just config.ini as you can see from scr.
![](http://image.prntscr.com/image/117d3143885d4acda16d55c019f6b43c.png)
![](http://image.prntscr.com/image/4b4ace83b66d4d268f88eaa90ccf4419.png)

**Comment by systemroot** [comment]
after delete server is still online 
![](http://image.prntscr.com/image/d27db2d3582e4660ac56b704d7124b08.png)
i'm trying to re'add server in *stats.ogarul.tk* because stats is not updating players and bots is just 15/13

**Comment by LegitSoulja** [comment]
@systemroot how about I just delete it? And let the server recreate it on restart?

**Comment by LegitSoulja** [comment]
@systemroot You need to delete the plugin, and reinstall it.

**Comment by systemroot** [comment]
![](http://image.prntscr.com/image/3906197c36f94b1bb74322ec733006d6.png)
![](http://image.prntscr.com/image/5213acf51d37471cbe7ca377be752f9d.png)
![](http://image.prntscr.com/image/5f2e3ff0392d4df3a5cb3e4ad38ef9ba.png)

**Comment by systemroot** [comment]
ahm ok i will try to delete now :/ just plugin or all ogar files :/ ?

**Comment by LegitSoulja** [comment]
Just the plugin

**Comment by LegitSoulja** [comment]
You was the main person who modified the plugin before which gave me a reason to add a non modifications. Do to your images, Statistics was never installed correctly the first time, and the plugin was modified. Delete the plugin and install it properly using the plugin install command.

**Comment by tommyb008** [comment]
i have the statistics plugin and edited it so it shows my servername why dont it show up on the server list

**Comment by systemroot** [comment]
@LegitSoulja nop. As you can ses is an freesh install 17.3.1 before was 17.2.5 !
And i don't know why you think i have edit it. but is not true! I'm Sure 100%.

**Comment by LegitSoulja** [comment]
@systemroot That didn't make no sense. It doesn't matter if you are using a latest version or not. Ogarul updates don't update plugins.

**Comment by LegitSoulja** [comment]
@tommyb008 make sure your stat port is open / port forwarded.

**Comment by tommyb008** [comment]
oh

**Comment by LegitSoulja** [comment]
@tommyb008 now your server is on the list.

**Comment by tommyb008** [comment]
it says typeerror:cannot read property 'command' of undefined
also i cant fine my server

**Comment by systemroot** [comment]
@LegitSoulja Well. If you think i have make any modification about Statistics. Started from now i'll not add any of my server/s in statistics.. 
I have not do anythink to add my server/s on'top as you think or as that person which has raport me think. because i don't care about this i'm not 10 years old i'm 21. I have open those server just for fun to play some times because i can't play agar anymore.
and If i find an way to edit your plugin or anythink else i'll tell you look dude fix your plugin because i found this problem.

**Comment by tommyb008** [comment]
nvm i got it to work but i got a big big error

**Comment by tommyb008** [comment]
and wont let me join

**Comment by tommyb008** [comment]
[WARN] Stopped at packethandler. Probably because of wrong packet/client usually normal

**Comment by tommyb008** [comment]
any fix?

**Comment by LegitSoulja** [comment]
@tommyb008 
Run command
> plugin update Statistics

**Comment by LegitSoulja** [comment]
And no there's no fix because this problem isn't happening to me.

**Comment by Andrews54757** [comment]
@systemroot @LegitSoulja made a mistake. I apologise. @LegitSoulja The anti-modify system I created for you would false trigger if you update without updating the version number in index.js. So maybe thats the reason

**Comment by Andrews54757** [comment]
As long as you update the version number every edit, it is fine

**Comment by tommyb008** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/17815538/16252473/58ecc36c-37e3-11e6-8d44-9b90c59beb5d.png)

**Comment by tommyb008** [comment]
it spams my console

**Comment by tommyb008** [comment]
whenever someone joins

**Comment by LegitSoulja** [comment]
@tommyb008 what other plugins are you using? Statistics should not prevent people from joining.

@Andrews54757 it's kindof like a hotfix now. If I update without updating the version, the plugin will automatically update to the recent file. Still though, with his problem in a picture he provided files.txt file was not even found, which leads to me to think he installed the plugin incorrectly.

**Comment by tommyb008** [comment]
leaderboardfx
leaderboard-stats-plugin
minionstart
minion-warning
statistics

**Comment by Andrews54757** [comment]
@tommyb008 Repudiate statstics. It should be solved

**Comment by tommyb008** [comment]
i did
didnt work

**Comment by LegitSoulja** [comment]
1 question, how did you install leaderboardfx when that's not even a plugin yet?

**Comment by tommyb008** [comment]
i got it from the plugin thing on github

**Comment by tommyb008** [comment]
where you guys keep your plugins

**Comment by Andrews54757** [comment]
Its my fault, I tried encrypting it but it failed. So reupdate again

**Comment by Andrews54757** [comment]
@LegitSoulja Maybe instead of "changes detected" it should say, "corrupted file, redownloading..." instead.

**Comment by tommyb008** [comment]
still dont work
i get dat error

**Comment by LegitSoulja** [comment]
It's best to use the plugin command, and the available plugins instead of downloading the plugin branch. Whilst theres some plugins are in development before released.

**Comment by Andrews54757** [comment]
go to the plugin library and download manually.

**Comment by tommyb008** [comment]
thats wwhat i did

**Comment by LegitSoulja** [comment]
@tommyb008 Do it again, because raw files don't update immediately.

**Comment by Andrews54757** [comment]
look at the index.js file. If you see only one line, thats the problem. You need to update like a minute later

**Comment by tommyb008** [comment]
it has everything in it

**Comment by systemroot** [comment]
*"Still though, with his problem in a picture he provided files.txt file was not even found, which leads to me to think he installed the plugin incorrectly."*
@LegitSoulja that is the reason why i tell you before *"Can you take a look at my server from c9.io"*
to view all files with your eyes is an modification or not :smiley:

**Comment by Andrews54757** [comment]
This is what I want you to do. 

1. tell me how many lines of code it has
2. restart the server
3. tell me the results

**Comment by LegitSoulja** [comment]
@Andrews54757 any modifications that's needed to the plugin feel free. Just keep me updated with a recent decoded file. thx

**Comment by tommyb008** [comment]
1. 518
2. i did
3. i get the same error and [Console] Language en Selected
[INFO] Loading Config Files...
[INFO] Loading C:/Users/ServerHostingPC/Desktop/Agario-Server/src/core/../settin
gs/advConfig.ini
[INFO] Loading C:/Users/ServerHostingPC/Desktop/Agario-Server/src/core/../settin
gs/clientConfig.ini
[INFO] Loading C:/Users/ServerHostingPC/Desktop/Agario-Server/src/core/../settin
gs/config.ini
[INFO] Loading C:/Users/ServerHostingPC/Desktop/Agario-Server/src/core/../settin
gs/override.ini
[INFO] Your unique id is: 2aaqpRrn1M
[INFO] Loading plugins
[Console] Give me minions running!
[OK] loaded plugin: GiveMeMinionsToo By AJS - Dev version 1.0.0
[LBStats] Started up and enabled. Use the CustomLB command to interact with this
 plugin
[LBStats] Stats are not turned on, do customlb stats to turn it on
[OK] loaded plugin: Leaderboard Stats By Andrews54757 version 1.0.0
[OK] loaded plugin: Minion Start By Andrews54757 version 1.0.0
[Statistics] OPTOUT? Or server name is still default. Check config. Statistics w
as not loaded!.
[OK] loaded plugin: Statistics By LegitSoulja version 1.1.0
[INFO] Starting ConsoleService
                                        _ _       _              _
                                       | (_)     (_)_           | |
  ___   ____  ____  ____    _   _ ____ | |_ ____  _| |_  ____ _ | |
 / _ \ / _  |/ _  |/ ___)  | | | |  _ \| | |    \| |  _)/ _  ) || |
| |_| ( ( | ( ( | | |      | |_| | | | | | | | | | | |_( (/ ( (_| |
 \___/ \_|| |\_||_|_|       \____|_| |_|_|_|_|_|_|_|\___)____)____|
      (_____|
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 17.3.1
[Game] Loaded stats server on port 88
[Main] Listening on port 443
[Main] Current game mode is Experimental
Garbage collecting in 1440 minutes!
[Main] The Game Was Paused to save memory. Join the game to resume!
>[OK] Uniban updated
C:\Users\ServerHostingPC\Links\Downloads.lnk
[Console] Invalid Command, try help for a list of commands.
>restart
[Console] Restarting server...
[INFO] OgarUnlimited terminated with code: 3
[Console] Language en Selected
[INFO] Loading Config Files...
[INFO] Loading C:/Users/ServerHostingPC/Desktop/Agario-Server/src/core/../settin
gs/advConfig.ini
[INFO] Loading C:/Users/ServerHostingPC/Desktop/Agario-Server/src/core/../settin
gs/clientConfig.ini
[INFO] Loading C:/Users/ServerHostingPC/Desktop/Agario-Server/src/core/../settin
gs/config.ini
[INFO] Loading C:/Users/ServerHostingPC/Desktop/Agario-Server/src/core/../settin
gs/override.ini
[INFO] Your unique id is: 2aaqpRrn1M
[INFO] Loading plugins
[Console] Give me minions running!
[OK] loaded plugin: GiveMeMinionsToo By AJS - Dev version 1.0.0
[LBStats] Started up and enabled. Use the CustomLB command to interact with this
 plugin
[LBStats] Stats are not turned on, do customlb stats to turn it on
[OK] loaded plugin: Leaderboard Stats By Andrews54757 version 1.0.0
[OK] loaded plugin: Minion Start By Andrews54757 version 1.0.0
[Statistics] OPTOUT? Or server name is still default. Check config. Statistics w
as not loaded!.
[OK] loaded plugin: Statistics By LegitSoulja version 1.1.0
[INFO] Starting ConsoleService
                                        _ _       _              _
                                       | (_)     (_)_           | |
  ___   ____  ____  ____    _   _ ____ | |_ ____  _| |_  ____ _ | |
 / _ \ / _  |/ _  |/ ___)  | | | |  _ \| | |    \| |  _)/ _  ) || |
| |_| ( ( | ( ( | | |      | |_| | | | | | | | | | | |_( (/ ( (_| |
 \___/ \_|| |\_||_|_|       \____|_| |_|_|_|_|_|_|_|\___)____)____|
      (_____|
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 17.3.1
[Game] Loaded stats server on port 88
[Main] Listening on port 443
[Main] Current game mode is Experimental
Garbage collecting in 1440 minutes!
[Main] The Game Was Paused to save memory. Join the game to resume!
>[OK] Uniban updated
stats create
[ERROR] Oh my, there seems to be an error with the command stats create
[ERROR] Please alert AJS dev with this message:
TypeError: Cannot read property 'Command' of undefined
>

**Comment by LegitSoulja** [comment]
@tommyb008 Ok, now since you have updated before, look at override.ini in the Statistics folder and make sure the server name isn't default.

**Comment by tommyb008** [comment]
i did

**Comment by LegitSoulja** [comment]
Well you would've got the error 
> OPTOUT? Or server name is still default. Check config. Statistics w as not loaded!.

**Comment by tommyb008** [comment]
it shows up as CyberServer on the serverlist but i get that one big error and i cant spawn

**Comment by tommyb008** [comment]
i did

**Comment by tommyb008** [comment]
//
//  PLEASE NOTE. SERVER STAT PORT HAS TO BE OPEN FOR THIS TO WORK!. DO NOT USE LOCALHOST INFORMATION,
//  THIS IS PUBLIC INFORMATION PEOPLE WILL NEED TO JOIN YOUR SERVER. 
//
//  BY YOU AGREEING, AND INSTALLING THIS PLUGIN, YOU ARE ALLOWING OGAR UNLIMITED TO STORE YOUR SERVER INFORMATION FOR PUBLIC USE FOR GAME CONNECTIVITY, AND STATS, AND OTHER GAME INFORMATION.
//  IF YOU HAVE CONCERNS, CONTACT USE HERE https://github.com/AJS-development/OgarUL-Plugin-Library/issues
//

// Your unique specfic name for your server :) **YOU HAVE TO CHANGE THIS**
serverName = "CyberServer"

// Make this 0 to Disable alerts abouts stats on connections and updates via statistics
alerts = 1

// If enabled(1) your ip or VPS ip will be updated. Use (0) to use customip/domain
usevpsip = 1

// This can only be used if usevpsip is 0. Mainly your IP your friends will connect to. NOT LOCAL HOST!
// DO NOT ADD A PORT!!!!!
customip = "example.com"

// Make this 1 to be able to opt out and keep the plugin, and remove all statistic information.
optout = 1

// If you are using a client other than play.ogarul.tk, enter here. Ex("example.com") Don't add /?ip!. it is not required. But your server will use this to redirect.
// By default, if clientlink is null/empty/contains no char play.ogarul.tk client will be used instead of agar.io or any other.
clientlink = ""

// If you want to see more information output in your console you might not even understand but be my guest..
debug = 0

**Comment by LegitSoulja** [comment]
I don't understand how stats create can lead to command undefined. Give me a minute while I do another check over it all. I'm not having no problems at all what so ever.

**Comment by LegitSoulja** [comment]
@systemroot sure, i can take a look. My c9 is **LegitSoulja**

**Comment by tommyb008** [comment]
still whenever i join i get that long error

**Comment by tommyb008** [comment]
it works fine without the statistics

**Comment by systemroot** [comment]
@LegitSoulja was needed to give this answer before. For now. is deleted with all Ogar files

**Comment by LegitSoulja** [comment]
@systemroot the reason why i didnt answer before is because i don't use c9. But if it was a huge problem I could help you. But okay

**Comment by tommyb008** [comment]
[warn] stopped crash at packethandler. probably because of packet/client. usually normal

**Comment by LegitSoulja** [comment]
@tommyb008 try deleting statistics and try again using the plugin command.

**Comment by LegitSoulja** [comment]
Otherwise, I don't know what else to say. I'm not getting no errors with statistics.

**Comment by tommyb008** [comment]
...

**Comment by tommyb008** [comment]
somehow that worked

**Comment by tommyb008** [comment]
thanks

**Comment by LegitSoulja** [comment]
wow.. well atleast now it works :/

**Comment by LegitSoulja** [comment]
And your welcome. I'm glad that worked.
