### ISSUE TITLE
WHERE I CAN CHANGE DISTANCE OF SPLITS?

### ISSUE THREAD

**Issue by RelTakeover** [AJS-development/Ogar-unlimited#1110]
title , no speed , no playerspeed, no split speed , i need change on version , i need change DISTANCE SPLITS , thx

**Comment by Megabyte918** [comment]
I answered this already, #1015 there will be a config for it once the current PR is merged.
And please don't duplicate issues it could result in a ban. This is like your third issue today

**Comment by David1ali12** [comment]
Please lets vote to ban this guy 
makes so much issue with no sense 
been so rude to developer even said to a dev **** you 
think the developers are his slaves 
Asking too much about client which is not explained

**Comment by RelTakeover** [comment]
dont cry pls

**Comment by LegitSoulja** [comment]
@RelTakeover one more offense, or duplicate issue, or an issue that doesn't even make sense a ban result is what you will get from these issues. 

We do not tolerate your kind of behavior, and we are not forced to do anything for you. Anymore spam issues, or created issues that you make today you will be banned.
