### ISSUE TITLE
position:0,0

### ISSUE THREAD

**Issue by KrayTheCoder4** [AJS-development/Ogar-unlimited#1111]
Okay so I started up my server on a mac following a tutorial I found on here and when I tried connecting I join but when i click play,my screen stays on white and when I do playerlist this shows up.
 ID         | IP              | NICK            | CELLS | SCORE  | POSITION    
 ------------------------------------------------------------------------------
          1 | 127.0.0.1       | Voith           |     1 |     10 |     0,     0
>
Help please I'm on mac btw.

**Comment by David1ali12** [comment]
use play.ogarul.tk/?ip=127.0.0.1:yourport instead of agar.io/?ip=127.0.0.1:yourport.

**Comment by KrayTheCoder4** [comment]
Still having same problem :// @David1ali12

**Comment by NatsuTheGreat** [comment]
Please follow the guideline. We need more details to be able to help you.

**Comment by KrayTheCoder4** [comment]
Version 17.3.1
I just started the server up on terminal and when i connected this happens :/

**Comment by NatsuTheGreat** [comment]
What packet version?

**Comment by KrayTheCoder4** [comment]
How do i check?

**Comment by NatsuTheGreat** [comment]
advConfig.ini

**Comment by KrayTheCoder4** [comment]
// Packetversion: 1 = old packet from about 10 months ago (most clients use this) 0 = latest client before moneyclip ruined the game

**Comment by NatsuTheGreat** [comment]
That is the comment, not your value. Your value looks like *packeVersion = 1 or 0*

**Comment by KrayTheCoder4** [comment]
packetversion = 1

**Comment by NatsuTheGreat** [comment]
Try changing it to 0.

**Comment by KrayTheCoder4** [comment]
Okay i changed it to zero, joined the server again once I restarted it then the same problem...
ID         | IP              | NICK            | CELLS | SCORE  | POSITION    
 ------------------------------------------------------------------------------
          1 | 127.0.0.1       | Voith           |     1 |     10 |     0,     0
          2 | 127.0.0.1       | An unnamed cell |     1 |     10 |     0,     0
>

**Comment by KrayTheCoder4** [comment]
Help plss

**Comment by David1ali12** [comment]
Can you put a screenshot of terminal and the white screen you are talking about

**Comment by KrayTheCoder4** [comment]
Sure.

**Comment by KrayTheCoder4** [comment]
When I join my server using ws://127.0.0.1:343 on http://play.ogarul.tk/ and click play this happens.
https://gyazo.com/c341657c51afc48ce62f46332d40565a
Terminal:https://gyazo.com/5bce2aa7c207c0cbb2183546d7e35931

**Comment by David1ali12** [comment]
the problem is with your node version  downgrade it to v5.9.0

**Comment by KrayTheCoder4** [comment]
Okay I installed V 5.9.0 and made server again and the same thing happens :///
ID         | IP              | NICK            | CELLS | SCORE  | POSITION    
 ------------------------------------------------------------------------------
          1 | 127.0.0.1       | v               |     1 |     10 |     0,     0
>

**Comment by KrayTheCoder4** [comment]
Help me I'm so confused ._.

**Comment by ItzLevvie** [comment]
Show us the terminal

**Comment by David1ali12** [comment]
I got this problem on Nitruos I was also using nodejs v5.9.0  
Try change you ports Stats port &server port Try this one always worked for me
8080 server port
8081 stats port

**Comment by KrayTheCoder4** [comment]
I changed the stats port and server port same problem...
https://gyazo.com/d8f9318d55c747ab1b730e966c9f653d

**Comment by David1ali12** [comment]
:confused: its your node version then

**Comment by KrayTheCoder4** [comment]
I have version V5.9.0 
is there a problem that I'm on a mac?

**Comment by ItzLevvie** [comment]
I have version V5.9.0 
is there a problem that I'm on a mac?

"callback" argument must be a function means that you're running a newer version of Node which doesn't support the setImmediate code, If you've Node 5.9.0 you probably haven't installed it properly.

**Comment by KrayTheCoder4** [comment]
Can you please link me to correct version of V 5.9.0 ?

**Comment by ItzLevvie** [comment]
https://nodejs.org/dist/v5.9.0/

**Comment by KrayTheCoder4** [comment]
Which one do I download if I'm on a MAC?

**Comment by ItzLevvie** [comment]
https://nodejs.org/dist/v5.9.0/node-v5.9.0.tar.gz

**Comment by KrayTheCoder4** [comment]
Okay I installed it,opened it and it made a folder in my desktop
am I finished installing it?

**Comment by LegitSoulja** [comment]
Yes

**Comment by KrayTheCoder4** [comment]
Okay so I start up server again? let me test it.

**Comment by KrayTheCoder4** [comment]
https://gyazo.com/c487f253ef5e02a61553333120aae75c
Don't work!! ;(

**Comment by LegitSoulja** [comment]
Redownload ogarul

**Comment by KrayTheCoder4** [comment]
kk.

**Comment by KrayTheCoder4** [comment]
WORKED!!!
THANKS SO MUCH EVERYONE <3 Appreciate it a lot ;D

**Comment by Ckicky** [comment]
Wow everyone was sooooo trying to help with other solutions, but then as @LegitSoulja just read it all, he just banged it "Redownload OgarUL" ...

**Comment by NatsuTheGreat** [comment]
What's your point?

**Comment by Agarian** [comment]
@Ckicky well it worked...

**Comment by LegitSoulja** [comment]
@Ckicky Actually I didn't read it all. The problem he had which was in the image
https://gyazo.com/c487f253ef5e02a61553333120aae75c

was solved by redownloading. 

Reason? If you are using nodejs with our supported version, and that error happens then there was a problem with coding, which was fixed. That's why I told him to redownload. As it looked, he couldn't use commands, therefor he wasn't even able to use the command *update all*
