### ISSUE TITLE
Virus bug

### ISSUE THREAD

**Issue by RelTakeover** [AJS-development/Ogar-unlimited#1112]
when i eject mass a
and throw the virus Where are the ejected mass , the virus multiplies enormously

**Comment by Megabyte918** [comment]
thats supposed to happen, its called a virus throw

**Comment by RelTakeover** [comment]
50 virus of 7 ejected mass is normal ?

**Comment by RelTakeover** [comment]
it is like agarz

**Comment by Megabyte918** [comment]
really? 50? this has never happened to me before wtf. virus throws work perfectly for me, can you please make a gif or something of it happening? and did you get any errors in console?

**Comment by LegitSoulja** [comment]
@RelTakeover I have not to long ago told you not to make any more issues. By you not listening you will be banned for a week from the issues. 

###### Issues Made
22
###### Ban Notice
https://github.com/AJS-development/Ogar-unlimited/issues/1110#issuecomment-227567491

###### Issues
https://github.com/AJS-development/Ogar-unlimited/issues/1083
https://github.com/AJS-development/Ogar-unlimited/issues/1103
https://github.com/AJS-development/Ogar-unlimited/issues/1091
https://github.com/AJS-development/Ogar-unlimited/issues/1090
https://github.com/AJS-development/Ogar-unlimited/issues/1082
https://github.com/AJS-development/Ogar-unlimited/issues/1045
https://github.com/AJS-development/Ogar-unlimited/issues/1081

**Comment by NatsuTheGreat** [comment]
Finally.
