### ISSUE TITLE
bugs i found

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#1114]
Ejected mass collision no longer works
The clientConfig.ini seems to have no effect to the client anymore
I will look into this and try redownloading ogarUL.

**Comment by David1ali12** [comment]
Ejected mass collision works but its off by default now untill getting fixed it makes lag you should turn it on.

**Comment by Megabyte918** [comment]
Ejected mass collision set to off seems to fix the lag

**Comment by NatsuTheGreat** [comment]
>Ejected mass collision works but its off by default now untill getting fixed it makes lag you should turn it on.

**Comment by Agarian** [comment]
Andrews found tye source! #1115
