### ISSUE TITLE
Found the lag source

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#1115]
It is in getCellsInRange(). As you can see, it is with Node.reduce() (aka cell removal) . It goes indefinatly down, causing lag
![screenshot from 2016-06-22 13-53-09](https://cloud.githubusercontent.com/assets/13282284/16277404/c66d694e-3880-11e6-8766-a9ddd23807ac.png)

**Comment by LegitSoulja** [comment]
I thought it was a collisions. After collisions was disabled the lag went away for the w's

**Comment by Megabyte918** [comment]
Thank god, the w thing was really starting to get annoying. Now all thats left is to fix the movement stutter

**Comment by Andrews54757** [comment]
It is the problem with Node.reduce, aka the removing of cells

**Comment by Agarian** [comment]
So is there a fix

**Comment by Andrews54757** [comment]
yep, it is to use FastMap instead of SortedMap. I tested it and it works

**Comment by Agarian** [comment]
So ejected mass lag is mostly fixed?

**Comment by bangana** [comment]
#WeNeedNocollusionback :(

**Comment by Andrews54757** [comment]
Profiles after fix:


[Uploading data.zip…]()

**Comment by Agarian** [comment]
so like will it be added?

**Comment by Agarian** [comment]
Because ejected collision isnt working

**Comment by Agarian** [comment]
For some reason, I'm seeing cells dissapear when they split a lot. For example: One time, I split my bot to 16 to feed me, BUT, 3 of my bot's cells dissapeared and my cell did too, which killed me. It's causing a lot of mass loss! I even tried splitting into a mothercell, instead of feeding the mothercell, it and 4 of my cells dissapeared! HELP!

**Comment by eevaqueen** [comment]
my cpu 90% with only 30 players ? is that normal? and server lag as hell!,only me have that?
![a1](https://cloud.githubusercontent.com/assets/17146668/16323005/b886e152-39a7-11e6-809b-0490d85cc654.jpg)
Please help.

**Comment by Barbosik** [comment]
**eevaqueen**: try MultiOgar: https://github.com/Barbosik/MultiOgar

it can run 1000 bots. Tested it with 120 players online, with such player count it has some lag. But with 60 players it's pretty smooth

**Comment by Barbosik** [comment]
**Andrew54757**: there are several bottleneck in ogar code:
1) code in packet folder it's too slow to handle a lot of connections
2) PlayerTracker: getVisibleNodes
3) getCellsInRange

**Comment by Barbosik** [comment]
Also, ogar code works with mass instead of size it leads to a lot of calls to slow Math.sqrt.
And also it uses a lot of sin/cos/atan2 which is slow and can be replaced with fast vector arithmetic

**Comment by Agarian** [comment]
Srsly For some reason, I'm seeing cells dissapear when they split a lot. For example: One time, I split my bot to 16 to feed me, BUT, 3 of my bot's cells dissapeared and my cell did too, which killed me. It's causing a lot of mass loss! I even tried splitting into a mothercell, instead of feeding the mothercell, it and 4 of my cells dissapeared! And after a while of entities dissapearing, LAG occurs. HELP!

**Comment by Agarian** [comment]
Is the W reduce lag thing gonna be added?

**Comment by Barbosik** [comment]
**Agarian**: try MultiOgar, it works much faster and cells never disappearing

**Comment by Agarian** [comment]
does it have all the features from here? if not then idc about it.

**Comment by Barbosik** [comment]
no, it's just very smooth, fast and has another physics - very close to vanilla.

**Comment by NatsuTheGreat** [comment]
How'd get those players on?

**Comment by LegitSoulja** [comment]
@NatsuTheGreat #Multi #Ogar

**Comment by David1ali12** [comment]
MultiOgar does not have features :/ I cant even use Minions at least it should have.

**Comment by Andrews54757** [comment]
@Barbosik I found out that yes, the things you said cause lag. Another thing I noticed was that it has TONS of idle time. If only I can make some use of that. My goal is 1000 bots and no lag. Currently, I am learning about child proccesses and is going to put it to use.

**Comment by Andrews54757** [comment]
Multiple protocals will also be supported in the future. But that would be after solving lag

**Comment by Andrews54757** [comment]
@Barbosik If only I had more time, also @MichaelLeeHobbs is gone, so its all on me. If only we had experienced programmers. We only have 2. but everytime I ask someone (who is very expirienced) to help, they refuse.

**Comment by Andrews54757** [comment]
It makes me want to fire all the unexperienced coders on the spot

**Comment by NatsuTheGreat** [comment]
>We only have 2

You and LegitSoujla?

**Comment by Andrews54757** [comment]
Yes, by that I mean very very expirienced. But people like you are also expirienced.

**Comment by NatsuTheGreat** [comment]
Thanks, got a little worried there.

**Comment by NatsuTheGreat** [comment]
I am looking over PlayerCell.js, why do we have two calcMergeTime functions?

**Comment by Agarian** [comment]
Your not the only worried one

**Comment by loganagar32** [comment]
me thank you Barbosik  you ogar so much better fisics me love she

**Comment by LegitSoulja** [comment]
Also, I checked today after minifying all the code, there was a faster performance. And note that there was no lag, even with 100+ bots + with some little changes I've made 

Check my server http://join.ogarul.tk/legitsoulja

**Comment by Agarian** [comment]
@LegitSoulja Can i try it in my workspace? I wanna see just how much better it is than OgarUL is with 1GB ram.

**Comment by Agarian** [comment]
MultiOgar ran with flying colors (did extremely well) in even 1GB ram

**Comment by Agarian** [comment]
Why can't i use my own server's IP for join.ogarul.tk just because "its already in the database"? Why does it matter?(it doesn't/shouldn't) and who used my server IP anyway?

**Comment by raphyjb** [comment]
u running on more then 1 server? maybe delete ur uuid and start it back up!? change name on statistics name.. 
all thinks i did to make mine work

**Comment by LegitSoulja** [comment]
@raphyjb wtf are you talking about??

**Comment by LegitSoulja** [comment]
@Agarian that means that you already have a link made.

**Comment by LegitSoulja** [comment]
Ill add a fix so that if theres a link already made, it will show the link anyways.
