### ISSUE TITLE
how change PlayerMassDecayRate

### ISSUE THREAD

**Issue by nonproxd** [AJS-development/Ogar-unlimited#1116]
Hello , How i can change playerMassDecayRate on cmd ? , change playerMassDecayRate ".007" , not working the cmd said : playerMassDecayRate change to NaN .. HOW?

**Comment by LegitSoulja** [comment]
Change from inside the config instead of using the command.

**Comment by nonproxd** [comment]
I need change for multiverse

**Comment by LegitSoulja** [comment]
Or try change playerMassDecayRate 0.007 maybe that will work.

**Comment by nonproxd** [comment]
i have 3 servers , i need change with cmd :(

**Comment by LegitSoulja** [comment]
try changing with **0.007* instead of .007

**Comment by nonproxd** [comment]
![image](https://cloud.githubusercontent.com/assets/20098303/16283876/08b3d418-38a5-11e6-8d55-b742cfd29056.png)

Said : Invalid config value

**Comment by LegitSoulja** [comment]
@AJS-development/ogar-unlimited-devs

**Comment by NatsuTheGreat** [comment]
Let me look through the change command.

**Comment by nonproxd** [comment]
Ok , i wait :cake:

**Comment by nonproxd** [comment]
when i put 0.007 , said : playerMassDecayRate changed to 0

**Comment by NatsuTheGreat** [comment]
Try .007

**Comment by nonproxd** [comment]
![image](https://cloud.githubusercontent.com/assets/20098303/16284295/e89e020a-38a6-11e6-905f-c6ee27a4abe3.png)


Said NaN

**Comment by Agarian** [comment]
Odd, it didn't do this before

**Comment by nonproxd** [comment]
And I can do : c

**Comment by Agarian** [comment]
I got a new computer

**Comment by NatsuTheGreat** [comment]
#1117 fixed.
