### ISSUE TITLE
Cannot GET/ Error Help!!!

### ISSUE THREAD

**Issue by eevaqueen** [AJS-development/Ogar-unlimited#1119]
Hello,
First i read How To Tutorial and README.md also I check every issue before I make this topic,I try to host my own client,but sadly it cost this error can't understand why!!! please help!!!

![a](https://cloud.githubusercontent.com/assets/17146668/16285862/fa2cf8a0-38d8-11e6-8ec0-a2a5fc26437b.jpg)

**Comment by seifgaming** [comment]
its saying to  me what language you prefer english or spanich i say english it say error any help

**Comment by LegitSoulja** [comment]
@eevaqueen You have to download the client in order for it to work

@seifgaming (en) is for english, (es) is for spanish

**Comment by Andrews54757** [comment]
and we dont talk about clients

**Comment by eevaqueen** [comment]
@LegitSoulja which client please? I did as this Tutorial exactly #729
@Andrews54757 but i saw that you made Tutorial #729 How to host your own client. ?
thats why i asked!.

**Comment by LegitSoulja** [comment]
@eevaqueen we provide but we do explain about it since its illegal. It's only for the people with knowledge and experienced people. If you don't understand how to use it then I recommend you using http://play.ogarul.tk instead.

**Comment by LegitSoulja** [comment]
Pretty much if you read the tutorial you shouldn't have no problems with installing. Pretty self explanatory.
