### ISSUE TITLE
[ GIGANT BUG ] When i throw virus

### ISSUE THREAD

**Issue by nonproxd** [AJS-development/Ogar-unlimited#1121]
When i throw virus , it It is multiplied in a gigantic amount , 
as if throwing 1000 virus

**Comment by LegitSoulja** [comment]
Try letting a minion eat a virus. It's even worser

**Comment by nonproxd** [comment]
as when throw the virus on agarz

**Comment by nonproxd** [comment]
as :+1:

**Comment by Agarian** [comment]
@LegitSoulja play.ogarul.tk is not loading. is something wrong?

**Comment by nonproxd** [comment]
what i can do ?

**Comment by LegitSoulja** [comment]
@Agarian thanks for the notice. I will try to fix these issue as fast as possible

**Comment by LegitSoulja** [comment]
@Agarian Ok, everything is now fixed.

**Comment by nonproxd** [comment]
hey progammers , pls help me

**Comment by Andrews54757** [comment]
I will fix

**Comment by nonproxd** [comment]
fixed?

**Comment by NatsuTheGreat** [comment]
I'll leave this open. The viruses are huge anymore. I used a dirty fix, I don't know whether to keep this open or not.

**Comment by nonproxd** [comment]
temporaly fixed?

**Comment by NatsuTheGreat** [comment]
@nonproxd I don't know. Andrews reversed my commit. So the viruses can get big again.

**Comment by Agarian** [comment]
i kept it on my server, it works fine actually

**Comment by fayizan** [comment]
I really don't have any problem with viruses on my server**Asia Server**,everything seems stable now.
I think @nonproxd have old version of Ogarul

**Comment by Agarian** [comment]
That was ur server @fayizan ?

**Comment by Agarian** [comment]
I was on it

**Comment by Megabyte918** [comment]
can anyone do me a favor and test the virus throws for me? im not at my computer atm, i just need to know if viruses still teleport when doing virus throws after andrew reverted the fix. it may have been the client that messed it up IDK. but i think that i might have a fix that doesnt spam the console, i might add it in if they do

**Comment by Agarian** [comment]
ill try and test it

**Comment by Agarian** [comment]
it still multiplied alot, i shot 1k worth of ejected mass for the virus shot, the aftermath of eating those viruses gave me 4.5k

**Comment by Megabyte918** [comment]
it just multiplies them? they dont get gigantic or teleport?

**Comment by NatsuTheGreat** [comment]
They don't get gigantic anymore, as long at my commit is included, (the one andrews reverted and thought did nothing)

**Comment by Megabyte918** [comment]
do they teleport tho

**Comment by fayizan** [comment]
@Agarian yea **Asia Server ** is mine

**Comment by Megabyte918** [comment]
do they still teleport tho? thats all i need to know

**Comment by fayizan** [comment]
@Megabyte918  Try my server **Asia Server**  from http://stats.ogarul.tk

**Comment by NatsuTheGreat** [comment]
What exactly do you mean by teleport Mega? They never teleported for me. They only flew fast and I fixed it in #1132

**Comment by Megabyte918** [comment]
instead of seeing the viruses shoot out of each other and slide across the map, you wouldnt see them slide they would just teleport to where their supposed to go or "appear" out of nowhere

**Comment by NatsuTheGreat** [comment]
Never has happened to me. Try the latest version, I made the viruses shoot slower.

**Comment by Megabyte918** [comment]
Alright ill test it when i can, thanks for your help :)

**Comment by NatsuTheGreat** [comment]
Yep :)

**Comment by LegitSoulja** [comment]
![IMG](https://i.gyazo.com/1369ae0aedf6310ab50d39a8c9ac9af3.gif)
![IMG](https://i.gyazo.com/e7b36f768e549ec292d0eebb73af3745.gif)

**Comment by NatsuTheGreat** [comment]
Awesome man! Just a few bug I see with it. Great job =)

**Comment by LegitSoulja** [comment]
@NatsuTheGreat, yea, still in development. There's even will be more too it, even marquee, strobe effects, color effects, etcc. https://github.com/AJS-development/OgarUL-Plugin-Library/tree/master/LeaderboardFX

**Comment by NatsuTheGreat** [comment]
Very creative idea :)

**Comment by nonproxd** [comment]
the bug is fixed or not?

**Comment by NatsuTheGreat** [comment]
>@nonproxd I don't know. Andrews reversed my commit. So the viruses can get big again.

**Comment by nonproxd** [comment]
FIXED ?

**Comment by NatsuTheGreat** [comment]
You tell me?!

**Comment by nonproxd** [comment]
Hello, when you fix the bug

**Comment by systemroot** [comment]
i was trying to make this https://www.youtube.com/watch?v=B9b8XMM7tjU (sec 0:20)
and i fail xP
[img]http://image.prntscr.com/image/9d936950206b4b32ad48f70b4f6cc663.png[/img]
i hope will be fixed -.-

**Comment by Agarian** [comment]
I think that became possible again after #1131

**Comment by NatsuTheGreat** [comment]
That is true, Agarian.

**Comment by Megabyte918** [comment]
@nonproxd does turning the ejected mass collision back on reduce the virus amount?
