### ISSUE TITLE
Latest client from play.ogarul.tk

### ISSUE THREAD

**Issue by mrzack506** [AJS-development/Ogar-unlimited#1122]
Can anyone send the play.ogarul.tk (or similar) client in a zip? The one in the previous thread is glitchy with spectate (i.e pressing q won't do anything). Thanks :)

**Comment by Andrews54757** [comment]
no

**Comment by Andrews54757** [comment]
not yet

**Comment by LegitSoulja** [comment]
The client on play.ogarul.tk is official and modified. The things you people want there you will have to make it your own from the original client Andrew gives out and update. 

The client in fact does work but I already know what you want and either or not you obtain it it still will not work. You will need experience for these things that we will not provide. Ogarul doesn't own skins neither do I. So if you are asking about it *like most people are* you have to make it yourself.
