### ISSUE TITLE
mothercells seem to lose mass too quickly

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#1123]
in the name.

**Comment by NatsuTheGreat** [comment]
Just a little more specifics please?

**Comment by Agarian** [comment]
When mothercells are fed, they eject food like normal, but lose WAY more mass than they should.

**Comment by Agarian** [comment]
lol is that u in your cover photo?

**Comment by LegitSoulja** [comment]
@Agarian Dude, where's your meme history??
https://www.youtube.com/watch?v=DuT9GqUzJLY

**Comment by NatsuTheGreat** [comment]
Lmao.

**Comment by CodingKuda** [comment]
Fite me

**Comment by LegitSoulja** [comment]
Fight? I don't think you're ready bro haha.. You sure though? Nah jk that'll be a big mistake.

**Comment by NatsuTheGreat** [comment]
Set ```motherCellMassProtection``` to 0 in ```config.ini``` That will fix your problem.
