### ISSUE TITLE
"DIRTY FIX" ERROR

### ISSUE THREAD

**Issue by nonproxd** [AJS-development/Ogar-unlimited#1126]
the fix not working for me :( , the virus go ahead multiplican its number

**Comment by NatsuTheGreat** [comment]
The fix was for the viruses to stop growing really big. Not for the multiplication. The multiplication is there because the collision is turned off and the viruses get to eat a lot at once. Then a lot get to shoot.

**Comment by Andrews54757** [comment]
you can set the max of viruses though in config
