### ISSUE TITLE
same division?

### ISSUE THREAD

**Issue by nonproxd** [AJS-development/Ogar-unlimited#1127]
hello , the "splitspeed" is for all cells ? i mean big cells and small cells?

**Comment by Agarian** [comment]
yes. although there is an easy workaround.

**Comment by Megabyte918** [comment]
you didnt need to make an issue for this you could have just asked it somewhere else lol

**Comment by Agarian** [comment]
In Physics.js (in core folder) replace
    var splitSpeed = gameServer.config.splitSpeed + (split.getSpeed() * 3 / 2); //70 * Math.max(Math.log10(newMass) - 2.2, 1); //for smaller cells use splitspeed 150, for bigger cells add some speed //splitSpeed = 70 + (split.getSpeed() + 10);
      //split.setMoveEngineData(splitSpeed, 32, 0.85); //vanilla agar.io = 130, 32, 0.85
      split.setMoveEngineData(splitSpeed, 40, gameServer.config.splitDistance); // set it to 45 if 40 is bad
with:
    var splitSpeed = gameServer.config.splitSpeed + (split.getSpeed() * 3 / 2) * Math.max(Math.log10(newMass) - 2.2, 1);
       if (cell.mass <= 10) {
         split.setMoveEngineData(132, 32, 0.85);
       } else 
       if (cell.mass <= 610) {
           split.setMoveEngineData(122, 32, 0.85);
       } else 
       if (cell.mass <= 5000) {
       split.setMoveEngineData(110, 32, 0.90);
       } else 
       if (cell.mass <= 10000) {
         split.setMoveEngineData(105, 32, 0.91);
       } else 
       if (cell.mass <= 20000) {
         split.setMoveEngineData(105, 32, 0.92);
       } else 
       split.setMoveEngineData(splitSpeed, 32, 0.85); //vanilla agar.io = 130, 32, 0.85

**Comment by Megabyte918** [comment]
@Agarian you should make a config for that

**Comment by Agarian** [comment]
i was thinking splitSpeedVersion

**Comment by Agarian** [comment]
imma add that
