### ISSUE TITLE
Virus problem

### ISSUE THREAD

**Issue by RevivedSol** [AJS-development/Ogar-unlimited#1129]

**Comment by RevivedSol** [comment]
Hey ogar unlimited team. I just want to tell you that the viruses are flying too fast. I mean like when i feed the virus its moving like F1. Can you guys fix it ?

**Comment by NatsuTheGreat** [comment]
Viruses move slower and smoother now :)

**Comment by Megabyte918** [comment]
hey @NatsuTheGreat can you do me a favor and test the virus throws for me? im not at my computer atm, i just need to know if viruses still teleport when doing virus throws after andrew reverted the fix. it may have been the client that messed it up IDK. but i think that i might have a fix that doesnt spam the console
