### ISSUE TITLE
Banned? Why?

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#1134]
[Statistics] You have been banned from Statistics.
 Reason : You are not allowed to use this service anymore. Proceed with your daily life.
 Visit why you got banned -> http://stats.ogarul.tk/ban/ 
 Contact LegitSoulja if this was a mistake.
You have been banned from Statistics.
 
              Reason : You are not allowed to use this service anymore. Proceed with your daily life.

              Visit why you got banned -> http://stats.ogarul.tk/ban/ 
 
              Contact LegitSoulja if this was a mistake.
Not sure why i would be banned.. I never play on my server's i just let my fans join

**Comment by Agarian** [comment]
For some reason, Im seeing cells dissapear when they split alot, and for some reason, i split my bot to 16 to feed me, 3 of my bot's cells dissapeared and mine did too, killing me. its causing alot of mass loss!

**Comment by LegitSoulja** [comment]
@Agarian wrong post buddy
