### ISSUE TITLE
No Leaderboard on any gamemode

### ISSUE THREAD

**Issue by jackmio32** [AJS-development/Ogar-unlimited#1135]
i was playing on my server when i noticed the leaderboard wasn't there the whole time and there was no errors in the console log or chromes development tools? i never typed anything and there was no leaderboard?
Version:17.3.6
i also tried every other gamemode and the same thing happened

**Comment by LegitSoulja** [comment]
try the command
> resetboard

**Comment by jackmio32** [comment]
invalid command

**Comment by LegitSoulja** [comment]
@jackmio32 mybad its the other way around :/
> boardreset

**Comment by jackmio32** [comment]
kk

**Comment by LegitSoulja** [comment]
by the way, what gamemode was you using for this to automatically happen?

**Comment by jackmio32** [comment]
still not there and im using play.ogarul.tk

**Comment by jackmio32** [comment]
any

**Comment by LegitSoulja** [comment]
Try setting the board with some text for example
> board hey

then reset it

> boardreset

1. Did setting the board with text hey show the leaderboard?
2. When you reset did the leaderboard show back? or did it disappear? or it never was shown.

**Comment by jackmio32** [comment]
neither worked
not even setting to something and reseting it didnt work

**Comment by LegitSoulja** [comment]
@jackmio32 All I can say is try updating ogarul one more time using the command
> update all

If that doesn't work we will discuss this more further, and check for any bugs or anything with the leaderboard. Make sure you test the leaderboard the default gamemode FFA before changing. If you change and that gamemode you changed to doesn't show the leaderboard please let me know. That would help out way much more better to determine the issue here.

**Comment by Andrews54757** [comment]
If it doesnt work, send us the server files

**Comment by CodingKuda** [comment]
Maybe..no names..were enabled.

**Comment by Agarian** [comment]
@LegitSoulja i noticed what your profile pic resembles lol
PROOF: the guy who says "F*** it right in the P****"

**Comment by LegitSoulja** [comment]
@Agarian lol

**Comment by LegitSoulja** [comment]
And not it, but her

**Comment by NatsuTheGreat** [comment]
If you're really using 17.3.6, this shouldn't be a problem. As CodingKuda said, check and make sure ```No names``` isn't on. If it isn't, redownload OgarUL, the leaderboard is there.

**Comment by jackmio32** [comment]
where is no names?

**Comment by jackmio32** [comment]
command or config?

**Comment by NatsuTheGreat** [comment]
http://prntscr.com/bkkwzc

**Comment by LegitSoulja** [comment]
There, that options, or client config.
