### ISSUE TITLE
Dudee...

### ISSUE THREAD

**Issue by nonproxd** [AJS-development/Ogar-unlimited#1136]
hello , this not duplicate question , i have a question , the bug of the virus multiplier is fixed or not?

**Comment by nonproxd** [comment]
Fixed or not

**Comment by NatsuTheGreat** [comment]
I already answered that in #1121

**Comment by LegitSoulja** [comment]
@nonproxd You better no be RelTakeover.

@NatsuTheGreat he recreated his account yesterday after I had banned him, and he is back again making these spam issues again.

@Andrews54757 what should I do with him? He's just gonna keep creating accounts over and over again.

**Comment by Agarian** [comment]
How 2 do you know?

**Comment by David1ali12** [comment]
for sure its him he just made a new issue :smile:

**Comment by David1ali12** [comment]
@Agarian proof lol issue #1112 #1121 
![1](https://cloud.githubusercontent.com/assets/17472593/16322902/3f7636c0-39af-11e6-9483-76de709c0412.PNG)
![3](https://cloud.githubusercontent.com/assets/17472593/16322908/49713a4e-39af-11e6-9ce3-b18eecc8cde4.PNG)
![2](https://cloud.githubusercontent.com/assets/17472593/16322912/4ef4f744-39af-11e6-9f3d-d18d56f8f554.PNG)
![4](https://cloud.githubusercontent.com/assets/17472593/16322914/556a8346-39af-11e6-9858-10b9d791d0e3.PNG)

**Comment by nonproxd** [comment]
realtakeover is a kid , 
We only work on the same agar

**Comment by NatsuTheGreat** [comment]
You two speak very much alike. And why is it that you know he is a kid and work with him on the same agar?

**Comment by nonproxd** [comment]
I do not have too much time ,and he edit things , we work on the same agar

**Comment by Andrews54757** [comment]
I dont care if he is rei or not. Just spammers will BE BANNNED
