### ISSUE TITLE
[BIG BUG] NOT EAT POINTS

### ISSUE THREAD

**Issue by nonproxd** [AJS-development/Ogar-unlimited#1139]
Download the latest version recently .

I just switched ports.

When creating a multiverse and play in the second universe created . eating points the cell does not grow

NOTE : THE FIRST SERVER HAVE foodMass : 30 is work ( BIG SERVER )

the second server have foodMass: 4 not work ( PARTY SERVER )

**Comment by NatsuTheGreat** [comment]
@LegitSoulja Yep, I have a confident feeling this is RelTakeover now.

**Comment by David1ali12** [comment]
he is I proofed check #1136

**Comment by NatsuTheGreat** [comment]
Is the banning system on github weak?

**Comment by nonproxd** [comment]
no , Reltakeover is a kid , 
We only work on the same agar

**Comment by nonproxd** [comment]
They can fix the bug ?

**Comment by Agarian** [comment]
What if RelTakeover and nonproxd were accounts made by XenoYT? O_o

**Comment by nonproxd** [comment]
i cant understand...

**Comment by NatsuTheGreat** [comment]
@Agarian Some deep thinking.

**Comment by Agarian** [comment]
He even reports tons of issues like XenoYT did

**Comment by NatsuTheGreat** [comment]
They kind of do sound like him too.

**Comment by LegitSoulja** [comment]
Any final decisions on what to do? Or leave it up to @Andrews54657

**Comment by NatsuTheGreat** [comment]
Leave it up to andrews.

**Comment by NatsuTheGreat** [comment]
Should we close this?
