### ISSUE TITLE
bad lag cpu 90% help!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by eevaqueen** [AJS-development/Ogar-unlimited#1140]
my cpu 90% with only 30 players ? is that normal? and server lag as hell!,only me have that?
![a1](https://cloud.githubusercontent.com/assets/17146668/16327685/492bae48-39d2-11e6-9348-9fc09730147f.jpg)

Please help.!

**Comment by NatsuTheGreat** [comment]
Check and make sure you're using the LATEST version. Don't turn on ejected mass collision. 30 users could cause lag. Also, if there are other applications running, close the unneeded ones.

**Comment by eevaqueen** [comment]
@NatsuTheGreat thank you,iam using the latest version and I never  turn on ejected mass collision,also after update the cpu now is 97% and the ony application is running node :( in linux,so you have any idea why ? and can you tell me what is your normal cpu stats after last update please?.
thanks.

**Comment by NatsuTheGreat** [comment]
Try getting a smaller map, and less entities.

**Comment by eevaqueen** [comment]
@NatsuTheGreat thank you now after i change the border size cpu is 60%,so any border up 10k = big lag.

**Comment by NatsuTheGreat** [comment]
You may want decrease the amount of food cells / viruses too if you haven't.

**Comment by eevaqueen** [comment]
@NatsuTheGreat thank you for help

**Comment by NatsuTheGreat** [comment]
No problem, have a good time.

**Comment by eevaqueen** [comment]
@NatsuTheGreat there is no idea to have big border "map" without lag? other than decrease?

**Comment by NatsuTheGreat** [comment]
That will have to be developed further.

**Comment by eevaqueen** [comment]
@NatsuTheGreat nahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh xD thanks anyway for your big help :+1:

**Comment by NatsuTheGreat** [comment]
No problem, eevaqueen. Have fun on your server :P
