### ISSUE TITLE
OgarUL Minions Review

### ISSUE THREAD

**Issue by GamingLegendYT** [AJS-development/Ogar-unlimited#1144]
So guys I have been using OgarUL for a very Long Time 
now I decided to make a video showing the OgarUl minions , but I used this title 
> Agario 150 Bots !!! 60 Mass Bots , After Patch
I left some credits in the video and a disclaimer can you tell me if these are enough ?! I don't wanna copyright strikes or whatever 
and if yes its enough then thank you for checking if no , then tell me what should I add :) 
Also tell me if you liked the video 💃 

https://youtu.be/IWq18duqNY0

**Comment by NatsuTheGreat** [comment]
Alright, thanks for letting us know.
