### ISSUE TITLE
[BUGS] [REPORT]

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#1145]
Don't create issues over issues over bugs. Just list them below!

**Comment by Agarian** [comment]
i tried this once, it wasnt too popular. #184

**Comment by LegitSoulja** [comment]
I have found this one strange. Whilst having minions and moving sometimes you can't. You be forced in a direction that you aren't trying to go, or you are stuck in one position until the minions are gone.

Using the command *enlarge* does it job, but the border stays the same which you cannot pass.

When increasing the map size, stuck cells starts back again and you can't move when you spawn in the game.

Running into the border you sometimes lose cells, and you somethings glitch and and teleport around the map.

When you are OP and you shoot a virus, and that minion eat the virus the minion size increases, and if your minion was split before it eats the virus, all minion cells split.

When jumping off a bridge, it fails to commit suicide and I survived the fall.

**Comment by Agarian** [comment]
```When jumping off a bridge, it fails to commit suicide and I survived the fall.```'WTF

**Comment by GamingLegendYT** [comment]
Guys How can we get skins in Play.ogarul.tk

**Comment by NatsuTheGreat** [comment]
They are already there. Click ```Want skim list?" and pick the skin you want.

**Comment by Tokoagar** [comment]
What happend to the skin list? it's black

**Comment by NatsuTheGreat** [comment]
@LegitSoulja

**Comment by Tokoagar** [comment]
https://cdn.discordapp.com/attachments/155683663617458176/196046747523481602/unknown.png

**Comment by LegitSoulja** [comment]
@NatsuTheGreat @Tokoagar @GamingLegendYT @AJS-development/ogar-unlimited-devs 

@David1ali12 is having problems with domain issues, and hosting problems. I will resolve the issue with uploading the skins to play.ogarul.tk until his skins and website is resolved. Give me a minute while I upload them.

**Comment by LegitSoulja** [comment]
The skin list will be removed until the site is back up, but the skins should be working now.

**Comment by LegitSoulja** [comment]
Statistics will be shut down for a few days. Either there's attacks towards the site, or either I have to fix the site stress. Fetch servers, Statisitcs, will be on hold until then.

**Comment by Tokoagar** [comment]
ok

**Comment by loganagar32** [comment]
Andrew por qué nunca se puede corregir los errores de la física, que debe ser como agar

**Comment by fayizan** [comment]
I saw other issues of Virus Bug, could it be fixed faster bcoz most of them trying splits with virus but
`Both Virus and Mass Just Dissappear` and PopSplit is dead..!!!

**Comment by Agarian** [comment]
Yep, popsplit tends to make cells dissapear.

**Comment by Agarian** [comment]
Just because.

**Comment by Agarian** [comment]
How can i prevent the garbage collection from changing the leaderboard?

**Comment by LegitSoulja** [comment]
it does? everytime it runs?

**Comment by Agarian** [comment]
BTW /rcon doesn't seem to work anymore.

**Comment by fayizan** [comment]
@LegitSoulja yes garbage collect changing leaderboard on each time 

@Agarian I don't have any problem with `/rcon` its working perfect for me

**Comment by LegitSoulja** [comment]
@fayizan Yes, garbage collector pretty much deletes, and create a new leaderboard and update it. I've had no problems with it.

**Comment by Agarian** [comment]
i already fixed it

**Comment by Agarian** [comment]
and popsplit is dead BTW

**Comment by Agarian** [comment]
that Press a key to move bug still exists.

**Comment by Aanis12** [comment]
sometimes when a player/minion does into  a virus either the minion or minion with the player disapears

**Comment by Agarian** [comment]
lol wut?

**Comment by systemroot** [comment]
Version 17.4.0
My cells start to disappear. from 5K i go 500Mass in 3min -.-
I think this is just in fast merger, because i was playing "FFA" before and this doesn't happen.!

**Comment by Agarian** [comment]
@LegitSoulja could i have the LBFX plugin? it's not in the ogarul plugin library. Well it is but only a README.md file for it.

**Comment by LegitSoulja** [comment]
@Agarian I haven't released it yet. There's still a few bugs, and new additional things that needs to be added. I mean, you can take a working version but there's only scrolling.

**Comment by Agarian** [comment]
Thats what i wanted :P

**Comment by Agarian** [comment]
Also have you been noticing that cells tend to twitch when colliding with eachother?

**Comment by Agarian** [comment]
So is that a no? =\

**Comment by Agarian** [comment]
Even merging can cause cells to dissapear =\

**Comment by DerpyYT** [comment]
I just really want this to be noticed and fixed "minion bug with the merge set to lower values, the more i put lower values to the merge, the splitting whilst having minions bug out gets more and more buggy,"

**Comment by genckaptan55** [comment]
http://prntscr.com/bqp4o9

Server has stopped working with this warning. My dedicated has 32GB of memory.

I couldn't find where timer.js is.

**Comment by LegitSoulja** [comment]
There's no timer.js. Timer is what setTimeout, and interval uses.

@Megabyte918 remember what I said about using too many intervals and timeouts? This can potentially lead to this with Asynchronous code.

**Comment by genckaptan55** [comment]
@LegitSoulja There also is a problem with pfmsg. It crash the server after all messages is sent.

**Comment by LegitSoulja** [comment]
Ok I'll take a look at it shortly. Maybe using pfmag was the reason it crashed with the timer error. Just don't use it until fixed. Me myself never even used it before.

**Comment by Coolkid5101** [comment]
I am getting an error when I open start.bat. Using windows 10
module.js:442
    throw err;
    ^

Error: Cannot find module 'collections/fast-map'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\iamco\Downloads\Ogar-unlimited-master\Ogar-unlimited-master\src\core\WorldModel.js:20:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by Megabyte918** [comment]
@Coolkid5101 `npm install collections`

**Comment by Tokoagar** [comment]
https://youtu.be/Mc9DaHswPvU linespit and double split bug

**Comment by Megabyte918** [comment]
Oh. My. God. how many times to i have to say it, linesplits can be solved by using the vanilla client instead of play.ogarul.tk, as the vanilla client has the default splitting angles set to go sideways rather than diagonal on play.ogarul.tk

**Comment by Tokoagar** [comment]
wait what

**Comment by Tokoagar** [comment]
How can I fix this?

**Comment by Megabyte918** [comment]
you can't unless your the owner of play.ogarul.tk xd

**Comment by LegitSoulja** [comment]
@Megabyte918 i don't even see where split takes place in the client. Are you sure its not ogarul split physics?

**Comment by Megabyte918** [comment]
@LegitSoulja I'll take a look at it again

**Comment by Agarian** [comment]
@LegitSoulja there still exists a bug that makes you click to move

**Comment by LegitSoulja** [comment]
@Agarian ?

**Comment by Agarian** [comment]
it keeps happening and its annoying!

**Comment by LegitSoulja** [comment]
I don't know what you're talking about. Explain please/

**Comment by Agarian** [comment]
i thought you'd remember -_-

**Comment by Agarian** [comment]
pretty much, sometimes the cells do not follow the mouse unless you press a key that the client can read.

**Comment by LegitSoulja** [comment]
So, all the canvas needs is a little focus you are saying?

**Comment by Agarian** [comment]
Wut?

**Comment by LegitSoulja** [comment]
The client is the canvas, plus the main which draws onto the canvas. Don't confuse yourself.

I can join a server, and no, it does follow the mouse. I don't see any issues with a cell not following the mouse :/

**Comment by LegitSoulja** [comment]
And plus I never heard of clicking to make it follow the mouse. I don't know what big you are talking about. 

There was a bug where cells don't follow until it likes hit the border, or somehow it pops back into following the mouse.

**Comment by Megabyte918** [comment]
Doesn't that only happen if you switch to a different tab and go afk after a while

**Comment by LegitSoulja** [comment]
Lol ya @Agarian . The canvas just needs focus when it's not in focus.

All games does this if you are directly interacting with it. How about this. I'll just listen for no focus, and focus back when it's lost. I don't know if this will stop idle, or stop players from getting kicked in a certain amount of time, but only one way to find out.

**Comment by LegitSoulja** [comment]
And um, can like there be some cool addidtional features added in the future? Like when you pop, there's different effects, with the cells slowly coming back towards the mother cell.

I think OgarUl will bring more attraction if this was implemented. I just think is pretty cool too see

**Comment by Agarian** [comment]
sure why not?

**Comment by Agarian** [comment]
have you tried the mothership gamemode in diep.io tho?

**Comment by Megabyte918** [comment]
Should this be closed?

**Comment by Agarian** [comment]
I think it should

**Comment by LegitSoulja** [comment]
@Agarian I doubt I'll ever finish LeaderboardFX, I'll pass it to you and you can finish it. I'll pass to you ok gitter when I get home. I'm like an hour away from home ATM just got off work.
