### ISSUE TITLE
add retina graphics please! just like agario

### ISSUE THREAD

**Issue by DTMClanDeveloper** [AJS-development/Ogar-unlimited#1146]
retina graphics just like agario plssss

**Comment by LegitSoulja** [comment]
We could be sued if we use the same graphics as agario. This is thing that may, or may not be updated in the future.

**Comment by Agarian** [comment]
Can we at least have the stroke style for the cell border stay even in smooth render? This effect is seen in agar.io

**Comment by Megabyte918** [comment]
i think you get retina when using the official agario client

**Comment by Agarian** [comment]
yes, but the agar.io client disallows so many good features
