### ISSUE TITLE
Question i have when im hosting my client onto website.

### ISSUE THREAD

**Issue by tommyb008** [AJS-development/Ogar-unlimited#1147]
I have a website with my client it is http://agarbaria.tk. and i want to have multiple servers how can i have that because it says var defaultserv = "ws://50.173.201.239:8081";
and i dont know where to put multiple adresses for like different servers on my client.
bit confusing for me. ;(

**Comment by LegitSoulja** [comment]
Sorry, but we don't explain about clients, and client hosting. You need experience to do those things. We cannot provide you help with that. Sorry :/

**Comment by tommyb008** [comment]
how am i supposed to know?!?!!?!? theres no guide!

**Comment by LegitSoulja** [comment]
Why would there be a guide when we only support 1 server

**Comment by LegitSoulja** [comment]
Also, there's recent issues about your implementation. Someone else has answered your question. Maybe you could find it, but for anyone part of AJS will not tell you because we don't discuss about the clients.
