### ISSUE TITLE
Skins

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#115]
How can i use skins like t-rex or Black hole,star ball
they all have spaces in between and cant use

**Comment by ItzLevvie** [comment]
For T-Rex: <t_rex>
For Black Hole: <blackhole>
For Star Ball: <starball>

**Comment by elitajmx** [comment]
Oooh okty

**Comment by elitajmx** [comment]
doesnt work

**Comment by elitajmx** [comment]
for trex

**Comment by Agarian** [comment]
it should

**Comment by Agarian** [comment]
no capital letters no spaces just

    <t_rex>

**Comment by elitajmx** [comment]
ok
