### ISSUE TITLE
BUG FIX PLEASE

### ISSUE THREAD

**Issue by TheAngryGrandpa** [AJS-development/Ogar-unlimited#1151]
Before update i added customskins and they worked so great after update i added new skins same way but only i cant see them  my other friends cant see it fix please before update was good after update i cant see new skins i added i did same steps

**Comment by AlexandriteErikParacelsus** [comment]
@legitsoulja close?

**Comment by AlexandriteErikParacelsus** [comment]
@legitsoulja close?
