### ISSUE TITLE
IDE websites for host Ogar server

### ISSUE THREAD

**Issue by ErikParacelsus** [AJS-development/Ogar-unlimited#1152]
Can someone recommend for me a good IDE website without paying?

**Comment by LegitSoulja** [comment]
Code anywhere

**Comment by LegitSoulja** [comment]
IDE? For computer? Netbeans my suggestion

**Comment by Agarian** [comment]
i thought u said Code Anywhere wasn't a VPS

**Comment by LegitSoulja** [comment]
You can use code anywhere with SSH, if you already have hosting :/
