### ISSUE TITLE
Error when installing jxcore on ubtunu

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#1153]
Hey! so i followed legitsouljas steps....
and
I get an error / https://gyazo.com/7a4ba76f32919c3c4a465ce598557d30
its when i do ./configure --engine-chakra

I cloned the git and did cd jxcore and then did ./configure --engine-chakra
and the error happens, Error Running GYP.

Any1 know? thanks!

**Comment by CalvinDKHD** [comment]
Why legit soulja keep closing it, this is wierd. he never closes others. Its just a personal problem.

**Comment by LegitSoulja** [comment]
There's no fix for this. Don't use profanity.
