### ISSUE TITLE
Lag!

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#1155]
I am Using the latest version 17.3.6 when i added 30 bot its lagg so hard i stopped for a sec then move then stop then move WTF happening to Ogar UL!

**Comment by AlexandriteErikParacelsus** [comment]
#1115

**Comment by Megabyte918** [comment]
please [search](https://github.com/AJS-development/Ogar-unlimited/search?o=desc&q=lag&s=created&type=Issues&utf8=%E2%9C%93) for this stuff before you make an issue about it
