### ISSUE TITLE
STOP CLOSING MY ISSUES UNTIL YOU GIVE MEH A SOLUTION I WAITED 20 HOURS FOR A CLOSED ISSUE

### ISSUE THREAD

**Issue by TheAngryGrandpa** [AJS-development/Ogar-unlimited#1156]
Before update i added customskins and they worked so great after update i added new skins same way but only i cant see them my other friends cant see it fix please before update was good after update i cant see new skins i added i did same steps

**Comment by AlexandriteErikParacelsus** [comment]
What are you retarded? You can report bugs in #1145

**Comment by AlexandriteErikParacelsus** [comment]
And stop making issues about your retarded reasons

**Comment by NatsuTheGreat** [comment]
Go to #1145 and report it there.

**Comment by Agarian** [comment]
Note that issue duplication could result in ban! #570
