### ISSUE TITLE
What happend to ogarul.io?

### ISSUE THREAD

**Issue by tommyb008** [AJS-development/Ogar-unlimited#1157]
The ogarul.io page isn’t working

ogarul.io didn’t send any data.
ERR_EMPTY_RESPONSE

what the heck!?!
what happend to it?

**Comment by SharkFinPro** [comment]
go to play.ogarul.tk

**Comment by David1ali12** [comment]
rip

**Comment by tommyb008** [comment]
i mean ogarul.io
not play.ogarul.tk

**Comment by SorryAgario** [comment]
someone made an extension for ogarul.io i tried to change "ogarul.io" to "play.ogarul.tk" it loads up but when i spawn i dont see my cell :(
