### ISSUE TITLE
NoCollisionTeams possible bug ?

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#1158]
When I change the team of a bot to green ( ex : `team 6 g` ) it causes my server crash appearing this error in the server console.
look [here](http://prntscr.com/blhlqz) for the error.
Possible bug?

**Comment by GhostShot3** [comment]
...

**Comment by Agarian** [comment]
Y u steal my profile pic?

**Comment by Agarian** [comment]
that command never really worked.

**Comment by NatsuTheGreat** [comment]
Uhm... He didn't. Yours says "Agar.io IS The Best" his says just "Agar.io"

**Comment by Agarian** [comment]
...

**Comment by Agarian** [comment]
I swear im too tired for this

**Comment by NatsuTheGreat** [comment]
:)

**Comment by Agarian** [comment]
i changed my profile pic to an arena closer from Diep.io, it hasn't updated yey.

**Comment by NatsuTheGreat** [comment]
http://prntscr.com/bli278

**Comment by GhostShot3** [comment]
@Agarian Lol sorry i change if you want

**Comment by Agarian** [comment]
Lol its ok cause Imma keep the image i have

**Comment by Agarian** [comment]
But try not to confuze anyone xP

**Comment by PrinceDark9243** [comment]
LOL I AM NECROMANCER

**Comment by firelightning13** [comment]
Your picture profile makes me want to play diep.io again... too bad my laptop's charger is still not fixed

**Comment by Agarian** [comment]
Ya know an Arena Closer is the strongest tank in the game

**Comment by GhostShot3** [comment]
@PrinceDark9243  @Agarian the diep clan lol

**Comment by GhostShot3** [comment]
@Agarian Is possible to make areana closer in OgarUL ?

**Comment by Agarian** [comment]
Idk but i like the idea

**Comment by GhostShot3** [comment]
@Agarian Yes its coll ideia.

**Comment by VSabertail** [comment]
GO DIEP.IO
