### ISSUE TITLE
Hosting Problem!

### ISSUE THREAD

**Issue by WolfOGG** [AJS-development/Ogar-unlimited#1159]
I have hosted my server on port 443 and 88 for stats with the plugin Statistics, the server does no show up on the server list why?

**Comment by WolfOGG** [comment]
I have hosted my server on port 443 and 88 for stats with the plugin Statistics, the server does no show up on the server list why?

**Comment by fayizan** [comment]
you have to configure the config.ini which can be found in `Ogarunlimited>src>plugins>Statistics>config.ini`
