### ISSUE TITLE
Ogar UL stats problem.

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1160]
My Server Does Not Pop Up on stats.ogarul.tk
I Installed the stats plugin and all i changed was the server name, nothing else.
In the console it says it is running fine :/
Wuts wrong

**Comment by LegitSoulja** [comment]
@SharkFinPro whats your server name or gameuid?

**Comment by raphyjb** [comment]
port forward ur port of stats..
default is 88
