### ISSUE TITLE
It would be possible to use gifs as skins?

### ISSUE THREAD

**Issue by Tmuru321** [AJS-development/Ogar-unlimited#1161]
as the title says
as I can use **animated** skins?
like [this](http://www.gifs-animados.es/pescado-imagenes/pescado-imagenes/tiburones/gifs-animados-tiburones-50148.gif)

**Comment by LegitSoulja** [comment]
@Tmuru321 I mentioned this in another post,
> Unfortunately, the DOM doesn't expose individual frames of a GIF, so this is done by downloading the GIF (with XMLHttpRequest), parsing it, and drawing it on a <canvas>.
