### ISSUE TITLE
An issue i find with spectate

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#1163]
When spectating a player, the viewbox edges can be seen on screen
![capture](https://cloud.githubusercontent.com/assets/15255724/16401928/83e5418e-3cb6-11e6-82e0-4e65d8570afd.PNG)
As seen here, the (horribly drawn) blue rectangle is the viewbox (idk how to fix that). This effect can be seen when spectating any player with ONE cell.

**Comment by SharkFinPro** [comment]
Is It The same amount of distance between each side to each edge? Is it the same on all sizes? You could "zoom in" that amount

**Comment by Megabyte918** [comment]
please put this in #1145
