### ISSUE TITLE
Why OgarUL is extreme LAG?

### ISSUE THREAD

**Issue by nobsterr** [AJS-development/Ogar-unlimited#1166]
Hello , why I add 100 bots and i have lag ? why in multiogar or cigar , not have lag when i add 100 bots? pls fix this , i believe that is a bad js code

**Comment by Megabyte918** [comment]
https://github.com/AJS-development/Ogar-unlimited/search?o=desc&q=lag&s=created&type=Issues&utf8=%E2%9C%93
look through these.
