### ISSUE TITLE
C# Edition

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#1167]
Hey all, Today I will be trying to convert ogarul (nodejs/JavaScript) to c#.

With C# we can unleash the physics of Ogar, even with faster performance and of course multi threading abilities. Ogar unlimited is being convert to c# and multiogar as different versions. OgarUnlimited C will be a launcher to be able to create multiple types of games from 1, and ability to host and control all at once.

What do you think about this idea? Should it stay in development? Or is it a waste of time?

Check @LProject/Ogar-UnlimitedC
> @AJS-development/ogar-unlimited-devs - note that this can be compatible for other devices, but maybe not mac. It can be converted with mono for os. That will be a little extra more work, even re-writing it all.

**Comment by fayizan** [comment]
WoW @LegitSoulja I support your project..!!!

**Comment by LegitSoulja** [comment]
@fayizan Yea, I hope it goes well.

**Comment by NoiseControllers** [comment]
Why not in java?

**Comment by LegitSoulja** [comment]
@NoiseControllers eh, Java isn't my style.

**Comment by Megabyte918** [comment]
My only concern is that most people who develop Ogar servers(or at least from what ive seen) don't know c#, so you will most likely be doing this ENTIRE thing by yourself, which includes converting all the plugins, and future updates of OgarUL and others to c# which is alot of work for one person to handle.

**Comment by LegitSoulja** [comment]
The project won't follow behind. OgarUnlimited will be re-coded converted, better and more effeciently. All plugins can be wrote in cs and c and compiled to dll :). 

Hopefully it turns out good..

**Comment by LegitSoulja** [comment]
And it's fine if I'm solo on this project.

**Comment by Barbosik** [comment]
I already have ogar server written in C#. I created it even before first Ogar project was released :)

**Comment by LegitSoulja** [comment]
@Barbosik you want to share? Or help out?

**Comment by Barbosik** [comment]
It's in outdated state. I used it last time for about a year ago. Some parts broken because I experimented with new protocol. And there some issues with console on linux. It uses direct write into console buffer in order to allow command prompt editor with scrolling log output simultaneously. It works good on windows, but has some issues on linux with console window resize.
So there are a lot of things which should be fixed to make it ready to use

**Comment by LegitSoulja** [comment]
Are you willing to share? It's an easy fix

**Comment by Barbosik** [comment]
may be. There is some issue with code, the server share a lot of code with my client. And it has some code I don't want to share. So, there is need for a deep refactoring to cut some functionality.

**Comment by LegitSoulja** [comment]
Nvm then. I was going to occoporite your server with the project, but I'd rather not have to recode everything of yours if you already have.

I guess I will only support pure OgarUmlimited servers instead of Ogar :/

**Comment by Barbosik** [comment]
C# allows some things which is not available in node.js. For example it can utilize multithreading.
It has better syntax and more wide capabilities. But unfortunately it looks like dead language due to corporate marketing.
But node.js surprisingly looks not so bad even with single thread. It has limited capabilities and unpleasant language limitations, but due to marketing it looks like future language.This is why I'm trying to implement ogar server in node.js :)

**Comment by CodingKuda** [comment]
@LegitSoulja Support bruh

**Comment by LegitSoulja** [comment]
Eh, boosting products I see with the most easiest language in the world, it's going to be a popular thing. C# is what a man needs to know. 

About how some capability or functionality that nodejs has that c# doesn't I'm 100% sure c# has an alternate way of doing things :) so no, you shouldn't write nodejs style neither. Recode the game like supposed to be. Just in another language. You get the lingo?

But I'll just put this on pause until I finish.

**Comment by DTMClanDeveloper** [comment]
will it have retina graphics?

**Comment by Agarian** [comment]
Retina graphics are a client issue.

**Comment by LegitSoulja** [comment]
@Agarian I'll kindof update the client with some new features. According to the graphics, I'm just going to obtain them, and also clean up client source code aswell. 

We need to fix ogarul by clearing the code up more. There's too much of unessities, and unclear coding, that I can't even barely understand :/.

**Comment by Agarian** [comment]
I was wondering if there was an easy way for spectate ZOOM to change according to how much a person is split. Spectate zoom already gets affected by cell mass, but not cell splitting.

**Comment by Megabyte918** [comment]
@Barbosik do you by chance still have your c# version?

**Comment by Barbosik** [comment]
Yes, but I don't want to share it
