### ISSUE TITLE
Server Showcase

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#1171]
**Showcase your servers below!**

*Please provide the following information:*
- Client address, ip and port
- Status (24/7, rarely, sometimes, active, etc)
- Game mode
- Server version (Ogar, Cigar, MultiOgar, etc) (If its running OgarUL, please provide the version number)
- Amount of player bots

> You can use our custom link shortner here > http://join.ogarul.tk/

**play.ogarul.tk/ogarul.io servers are also allowed**

Im going to make server showcases every couple weeks/every month just so it wont get pushed to the bottom of the issues and people wont forget about them.

**Comment by Agarian** [comment]
### Agarian's server:
**Status:** sometimes active
**Currently:** CLOSED
**Features:** 10 minions on start, custom leaderboard stats, edited split physics.
**Link:** [here](play.ogarul.tk/?ip=ogarserverbeta-agarian.c9users.io)

**Comment by systemroot** [comment]
**Link:** http://volfteam.com/
**Status:** Online 23/7 .
**GameMode:** Fast Merge.
**Version:** Latest Ogar-Unlimited.
**Bots:** 20.
**Minions:** Disallowed.
**StartMass:** 310.
**MaxMass:** 3B.
**MaxCells:** 50.
**VirusMin/max:** 25/1000
**Skins:** http://volfteam.com/skins/
**Info:** This is Beta. I have write `online 23/7` because every day i will reboot server.
> This Comment Will Be Updated If i make an change or close my web/server.

**Comment by Insane-Agar** [comment]
# Insane Agar

**Status:** 24/7
**Currently:** Open 
**Bonus Features:** (work in Progress) Login and Level System
**Link:** [http://play.insane-agar.tk](http://play.insane-agar.tk)
**Other Info:** Lag is rare for US players, lag occurs occasionally for Asia Players. Almost always at the top of the Ogarul statistics page.

**Comment by fayizan** [comment]
# Asia Server
**Client Link:** http://play.ogarul.tk/?ip=139.59.4.192:443
**Status:** 24/7
**Gamemode:** FFA
**Server Version:** 17.3.6-Latest Version of Ogarul
**Minions:** One For Each Players
**Player Bots:** 0
**Info:** Ultra Smooth Server For Asian Players Hosting From India.

**Comment by inxlio** [comment]
Client Link: http://agario.city/betasv/
Status: 24/7
Gamemode: FFA
Server Version: 17.3.6-Latest Version of Ogarul
Minions: 0
Player Bots: 0
Info: Server private 24/7 , open to all

**Comment by siamkcs** [comment]
# Agar.io TSAR server
**Client Link**: http://agariotsar.ddns.net:447
**Status**: Active in sometimes , everyday the server will be opened at least 8 hours.
**Gamemode**: FFA
**Server Version**: 17.3.0
**Minions**: Not Allowed
**Player Bots**: 30
**Start Mass**: 132
** Mass Each Cell**: 22500
Info: A private server hosting by an agar.io player from Hong Kong

**Comment by David1ali12** [comment]
##German Server

Link:[http://agar.io/?ip=134.119.17.230:443](http://agar.io/?ip=134.119.17.230:443)
Status: Always on
players: 15-40
Gamemode: FFA
Server Version: MultiOgar
Start Mass: 132
client:agarlist.com
Specs:ubunutu 14.4 ,ram 32GB , 12 core

**Comment by NatsuTheGreat** [comment]
Wow, @David1ali12 My teammate and I are playing fair and you give yourself mass. Cheater. :/

**Comment by NatsuTheGreat** [comment]
Wow, now you kill use through command prompt.

**Comment by David1ali12** [comment]
dude rules killing admin = dead

**Comment by NatsuTheGreat** [comment]
You never stated that :/

**Comment by Tokoagar** [comment]
**Toko World**

Status: Some times
Gamemode: Expirimental
Version: Ogar using the lastest update
PlayerBots: 20
Startmass: 10 (Ask for 43 in chat If im only .-.)
CustumSkins: I added new kraken skins like 150 and 200
Info: runing from a windows 7 64bit i-5

**Comment by Tokoagar** [comment]
And http://join.ogarul.tk/8uzdq

**Comment by firelightning13** [comment]
@Tokoagar You could just edit... (delete this comment)

**Comment by VSabertail** [comment]
RestInPepperoni

**Comment by GetRektAgario** [comment]
Get Rekt servers
Join using: http://agar-rekt.ml/
Gamemodes: FFA, Instant merge.....
Version: 17.2.5
PlayerBots: Each playr gets 5 minions
StartMass: 100
CustomSkins: do <skinname> to see custom skins
Info: Running 9 servers on this website, all running of 3 different vps' which I bought of https://www.ovh.co.uk/
Join the discord for constant updates about the servers:
https://discord.gg/xfnCp

**Comment by SharkFinPro** [comment]
play.ogarul.tk/?ip=76.22.13.186:443

status: On Sometimes
Game Mode: FFA, Experimental, Teams, Hunger Games. Join, if alot of people request, ill switch it!
Version: Latest OgarUL
Player Bots: 0
minions: 0 or 21 (depends on the server im running at the time)

**Comment by DoreM123** [comment]
Link: http://agardm.ml/
Status: 24/7
Gamemode: FFA,Experimental,Teams,Crazy
Version: MultiOgar(FFA) , OgarUL(Rest, 17.4.0)
Player Bots: 0-5
Minions: 0-20
Specs: Windows 8, 32GB Ram, Amazon Web Services Enterprise

**Comment by NarutoGamerPro** [comment]
Link: http://agar.io/?ip=187.205.203.74:443
Status: On Sometimes
Gamemode: FFA
Version: MultiOgar (1.2.58)

**Comment by SharkFinPro** [comment]
should we close this, as there is stats.ogarul.tk?
