### ISSUE TITLE
I need help for my custom server

### ISSUE THREAD

**Issue by RepahidiS** [AJS-development/Ogar-unlimited#1172]
Hello guys I need your help for my custom (not vanilla) server. I want make a custom cell split like on agarz.com. If you eat a virus, server splitting you reverse side of virus. Thanks for help :)

**Comment by Agarian** [comment]
?

**Comment by RepahidiS** [comment]
updated sorry :)

**Comment by abdurrahmanekr** [comment]
In fact, I am need

**Comment by omurcakmak** [comment]
I need this too

**Comment by Megabyte918** [comment]
@RepahidiS that still makes no sense lol

**Comment by nobsterr** [comment]
Change the speed of spaces, and the bug of the virus is still

**Comment by Megabyte918** [comment]
the speed of spaces? the speed of spaces depends on how fast you can press the spacebar right?

**Comment by RepahidiS** [comment]
I mean like this guys player splitting to reverse side of virus : http://i.hizliresim.com/5VnWBl.gif

**Comment by abdurrahmanekr** [comment]
So... How to escape from the virus ? @Megabyte918 @Agarian

**Comment by LegitSoulja** [comment]
Ohh.. You mean't if you ever to somehow happen to split, you wont split towards a virus? :/

**Comment by RepahidiS** [comment]
@LegitSoulja yeap like on this gif -> http://i.hizliresim.com/5VnWBl.gif

**Comment by Megabyte918** [comment]
https://github.com/AJS-development/Ogar-unlimited/issues/1181#issuecomment-229685191
