### ISSUE TITLE
Skin List

### ISSUE THREAD

**Issue by XtremePlayzCODE** [AJS-development/Ogar-unlimited#1173]
Since skin list has been removed I just want a list or a link of all the files in http://play.ogarul.tk/skins/.
I tried many things but they don't work.

P.S. Are the new skins like teddy bear skins on OgarUL yet?

**Comment by CodingKuda** [comment]
For the "teddy bear" skins, That will only be able if anyone finds a png
image of all of the skins, and post's it to imgur. Only if you or anyone
can find those skins, yes they will be added. But they might not be able to
use them due to copyright problems..

**Comment by SorryAgario** [comment]
https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSCOSiZ85WlD-sVFDAWUvZXvXtKsyUhptmdltspQGjtQtzOj3j0

FOUND THE TENDER HEART CARE BEAR SKIN

**Comment by SorryAgario** [comment]
http://imgur.com/a/eJN49 I GOT YOU XD

**Comment by LegitSoulja** [comment]
No the skin list was removed. It will be added back eventually. I don't think ogarul.io is coming back :/

**Comment by Megabyte918** [comment]
RIP ogarul.io :(

**Comment by LegitSoulja** [comment]
@Megabyte918 @SorryAgario  @XtremePlayzCODE  skin list was added back.

**Comment by XtremePlayzCODE** [comment]
@LegitSoulja http://imgur.com/a/eJN49 They're here, could you add them in?
