### ISSUE TITLE
Server Hosting Help

### ISSUE THREAD

**Issue by TheAngryGrandpa** [AJS-development/Ogar-unlimited#1175]
Can someone give me steps how to host my server from c9.io

**Comment by LegitSoulja** [comment]
No. As we don't support c9 and its against there ToS. You will get banned instantly if you do run ogarul :/.

**Comment by TheAngryGrandpa** [comment]
@LegitSoulja Okay so how to host server please ?

**Comment by LegitSoulja** [comment]
If you don't have no experience, then I'm sorry

**Comment by TheAngryGrandpa** [comment]
@LegitSoulja Thanks sir :)

**Comment by SorryAgario** [comment]
@LegitSoulja its the angry grandpa, watch out xD

**Comment by XtremePlayzCODE** [comment]
Ok this guy is actually starting to spam.
