### ISSUE TITLE
How to change ip?

### ISSUE THREAD

**Issue by AgarioIsBest1602** [AJS-development/Ogar-unlimited#1176]
I want to play with friends on my server so i think i have to change the ip of my server... But how can i do that?

**Comment by LegitSoulja** [comment]
Are you sure you want to change? Or use a ip cover up?

**Comment by Megabyte918** [comment]
i used duck dns

**Comment by AgarioIsBest1602** [comment]
Is that free?

**Comment by Megabyte918** [comment]
ye https://duckdns.org

**Comment by AgarioIsBest1602** [comment]
How to use it?

**Comment by Megabyte918** [comment]
@AgarioIsBest1602 Add your ip and ipv6, once thats done create a subdomain.
then if your using the official agario client like i am do `agar.io/?ip=[subdomain].duckdns.org:[port]`
and if yoru using play.ogarul.tk do `http://play.ogarul.tk/?ip=[subdomain].duckdns.org:[port]`
the port is the port your server is running on

**Comment by LegitSoulja** [comment]
@Megabyte918 no-ip.org aswell

Otherwise renewing your DHCP w/ a new lease would give you a new IP address.
