### ISSUE TITLE
mega split not working!

### ISSUE THREAD

**Issue by Dramex** [AJS-development/Ogar-unlimited#1177]
Hi, 

we used to use 
`playerRecombineTime : -1000
`
on ogar to make the server support very fast split as this video :
https://www.youtube.com/watch?v=6mmhgg0FOT0

when i tried ogar-unlimited its has an issue which is when i reach about 500 score i cannot split :)
its like i merge before i split,

so any help about this ?

**Comment by Megabyte918** [comment]
@Dramex find and remove these lines of code in /core/gameserver.js under the updateMoveEngine function:
<pre>
if (check.cellType === 0 && (client != check.owner) && (cell.mass < check.mass * this.config.sizeMult) && this.config.playerRecombineTime !== 0) { //extra check to make sure popsplit works by retslac
          check.inRange = false;
          return;
        }
</pre>
I don't know why this happens, but for some reason this breaks instant merging. Keep in mind that removing this code means that you can no longer popsplit on your server, as of now there is no other known fix for this problem

**Comment by Dramex** [comment]
its okay to remove popsplit ..
i tried to remove the code you asked me to remove, **same problem**

**Comment by Megabyte918** [comment]
Is your recombine time config working? mine suddenly stopped working and i cant change it. are you using the unlimited FFA gamemode for this?

**Comment by Megabyte918** [comment]
Nevermind got it working again, I downloaded a fresh version and tried with the recombine time set to -1000 and 0 and they both seemed to recombine instantly, even without popsplitting removed. what version are you running?

**Comment by Dramex** [comment]
I use fresh version, its working until the mass reach 500 as i said in my frist post, then its wont split

-1000 different from 0 its faster
You can't do as the video in 0

**Comment by Megabyte918** [comment]
Huh... im not sure... that fix USED to work for an older version of ogarul but im not sure why it isnt for this one... try using an older splitversion and see what happens

**Comment by AlexandriteErikParacelsus** [comment]
Go to PlayerCell.js and change the code to this
PlayerCell.prototype.calcMergeTime = function(base) {
    // Check for merging time
    var r = false;
    if (base == 0 || this.owner.mergeOverride) {
        // Instant recombine in config or merge command was triggered for this client
        r = true;
    } else {
        var rec = Math.floor(base); // base seconds
        if (this.recombineTicks > rec) r = true; // Can combine with other cells
    }
    this.shouldRecombine = r;
};
And change your recombine to 1.5 and max cell to 64 if you want to replica mega split in petridish.pw

**Comment by AlexandriteErikParacelsus** [comment]
Go to PlayerCell.js and change the code to this
PlayerCell.prototype.calcMergeTime = function(base) {
    // Check for merging time
    var r = false;
    if (base == 0 || this.owner.mergeOverride) {
        // Instant recombine in config or merge command was triggered for this client
        r = true;
    } else {
        var rec = Math.floor(base); // base seconds
        if (this.recombineTicks > rec) r = true; // Can combine with other cells
    }
    this.shouldRecombine = r;
};
And change your recombine to 1.5 and max cell to 64 if you want to replica mega split in petridish.pw

**Comment by AlexandriteErikParacelsus** [comment]
Go to PlayerCell.js and change the code to this
PlayerCell.prototype.calcMergeTime = function(base) {
    // Check for merging time
    var r = false;
    if (base == 0 || this.owner.mergeOverride) {
        // Instant recombine in config or merge command was triggered for this client
        r = true;
    } else {
        var rec = Math.floor(base); // base seconds
        if (this.recombineTicks > rec) r = true; // Can combine with other cells
    }
    this.shouldRecombine = r;
};
And change your recombine to 1.5 and max cell to 64 if you want to replica mega split in petridish.pw

**Comment by Megabyte918** [comment]
@AlexandriteErikParacelsus that doesnt work, if your gonna use ogar's code at least merge it with ogarul's so theres no error
@Dramex use the code underneath the `calcMergeTimeU` function, its basically the same thing that Erik said but its already merged, when I used that code the mega split worked for me

**Comment by Megabyte918** [comment]
Fixed #1208

**Comment by Megabyte918** [comment]
https://github.com/Megabyte918/Ogar-unlimited/commit/0182d1ef282d5a04715df3212ec914a87b3e3347
just realized its not physically possible to reproduce
