### ISSUE TITLE
Controling Minions

### ISSUE THREAD

**Issue by GetRektAgario** [AJS-development/Ogar-unlimited#1178]
I have installed the MinionStart plugin and the SuperMinion plugin and I was wondering if it was possible to have players spawn at mass 100 and to automatically get minions which spawn in at 10 mass?

**Comment by Aanis12** [comment]
to get players to spawn at mass 100 just simply go to config file and change playerstartmass to 100 i dont know about minions spawning to mass 10

**Comment by GetRektAgario** [comment]
yeah I know how to do that it is making them spawn in at different masses is the problem

**Comment by Agarian** [comment]
do superminion playerID amount minionname 10
then minions spawn with 10 mass.

**Comment by GetRektAgario** [comment]
yes but I want it so that it gives minions automatically so I don't have to type anything. Such as how the plugin minion start works.

**Comment by LegitSoulja** [comment]
@GetRektAgario 
> plugin install GiveMeMinionsToo

**Comment by MineMooreALT** [comment]
i did the superminion command with Super Minions installed but they still spawn with the default player mass not the ammount i selected in the command
