### ISSUE TITLE
Controling Minions

### ISSUE THREAD

**Issue by GetRektAgario** [AJS-development/Ogar-unlimited#1179]
I want to have player spawn in at 100 mass and minions to spawn in at 10 mass of the minion start plugin, how can I edit the minion start file so that this happens automatically without me having to type anything into the console?

**Comment by PrinceDark9243** [comment]
Cant there is not any plugin that can make dude you can close issue!

**Comment by LegitSoulja** [comment]
Don't make any more duplicate issues or you will be banned

**Comment by GetRektAgario** [comment]
I made a duplicate issue cos you closed it without answering it properly, which you just did again......
