### ISSUE TITLE
Spawning bug

### ISSUE THREAD

**Issue by jvremy** [AJS-development/Ogar-unlimited#1180]
I just downloaded the new Ogar as I had an outdated version of it. Installed the dependencies, then ran start.bat, I tried it, but as soon as I pressed play it just did a weird glitch and gave me a random bot name and then I didn't see my cell or anything and saw the X and Y moving very rapidly. What can I do? I have restarted it multiple times but it didn't seem to work. Any solutions? 
(if this is a bad explanation i'm willing to make a video of this, thanks)

**Comment by NatsuTheGreat** [comment]
>I just downloaded the new Ogar

You mean Ogar Unlimited correct?

**Comment by jvremy** [comment]
> You mean Ogar Unlimited correct?
yes.
