### ISSUE TITLE
Where is the setAsMovingNode in Gameserver.newCellVirused

### ISSUE THREAD

**Issue by abdurrahmanekr** [AJS-development/Ogar-unlimited#1181]
Hello, newCellVirused in GameServerjs.

this.setAsMovingNode(newCell)  had the old version
How do I use it in the current version? Please help me :)

**Comment by Megabyte918** [comment]
update

**Comment by abdurrahmanekr** [comment]
Where can I find that state of. in that case we are growing with more viruses.

**Comment by Megabyte918** [comment]
the state of what? `this.addNode(newCell, "moving");` is the new version of `this.setAsMovingNode(newCell)` , if you update then it should replace that one with the new one. And if you want to increase your virus amount see "virusMinAmount" and "virusMaxAmount" in src/settings/config.ini

**Comment by abdurrahmanekr** [comment]
my english sucks :( that's why I'm using google translate :D. 
What it is used for "moving",
I want to do is actually on the [http://i.hizliresim.com/5VnWBl.gif](url)
I do not want to eat it won virus :+1:

**Comment by abdurrahmanekr** [comment]
sorry bro size of the image was high. I've just realized.
How do I prevent the virus approach, just laying food ?

**Comment by Megabyte918** [comment]
The angle of which your cells pop out is decided randomly, in other words, if someone shoots a virus at you in ogarul you have no way of knowing where the big cells will popout. Like in vanilla agar. So it COULD hit the virus but if you're lucky it'll miss. I think the random angle is decided in /entity/Virus.js under the "onConsume" function. Just look for `angle = Math.random() * 6.28;` in there and try editing them to what you want. And can you please explain your last comment a little batter? i dont understand :P
