### ISSUE TITLE
I have bug when I throw virus

### ISSUE THREAD

**Issue by liomessip** [AJS-development/Ogar-unlimited#1182]
https://camo.githubusercontent.com/43fa53c7242573edf008cdca7ead110b7681245a/687474703a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f39643933363935303230366234623332616434386637306234663663633636332e706e67

this bug...

The virus it multiply when 
I throw a lot of mass

**Comment by Megabyte918** [comment]
Does turning the ejected mass collision back on help?

**Comment by liomessip** [comment]
yes collisionejected = 1

**Comment by Megabyte918** [comment]
well does it still multiply alot?

**Comment by liomessip** [comment]
Yes , 
https://camo.githubusercontent.com/43fa53c7242573edf008cdca7ead110b7681245a/687474703a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f39643933363935303230366234623332616434386637306234663663633636332e706e67

**Comment by inxlio** [comment]
Same error , the collideEjected is turn on ,and the virus  it multiply

pls test on http://agario.city/betasv/

**Comment by AgarioIsBest1602** [comment]
This isnt a bug. A virus needs normally 7 feed to get shooted. He gets mass and he shoots again.

**Comment by inxlio** [comment]
the configure is on 7 ... the same bug...

**Comment by inxlio** [comment]
virusFeedAmount = 7

**Comment by Agarian** [comment]
This is a bug, but we don't really know the reason.

**Comment by Megabyte918** [comment]
I will try to fix this.. idk how i will do it tho maybe i'll add a timeout

**Comment by Agarian** [comment]
yes

**Comment by Agarian** [comment]
i have nothing to do :P

**Comment by Agarian** [comment]
@Megabyte918 lets go on discord or something

**Comment by LegitSoulja** [comment]
@Megabyte918 there's way too many timeouts and interval. Only limited to 1 CPU. That's a lot of stress

**Comment by Megabyte918** [comment]
@LegitSoulja it will only be for virus throws tho

**Comment by Agarian** [comment]
@Megabyte918 im on discord
