### ISSUE TITLE
2 Questions i have

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#1184]
- How can I make a cell get a random color when it splits?
- How can I make food spawn at random mass?

**Comment by LegitSoulja** [comment]
* Same as ejected mass, w/ random color.
* Easily, by creating a new cell with it size.

**Comment by Agarian** [comment]
Your first answer i get but the second, idk

**Comment by LegitSoulja** [comment]
@Agarian you can do that via config, but for split cell color changes will have to be added since it doesn't exist.

**Comment by NatsuTheGreat** [comment]
```
 spawnFood() {
    this.foodSpawned++;
	var randomMass = Math.floor(Math.random() * 5);
    let f = new Entity.Food(this.gameServer.getWorld().getNextNodeId(), null, utilities.getRandomPosition(this.config.borderRight, this.config.borderLeft, this.config.borderBottom, this.config.borderTop), randomMass, this.gameServer);
    f.setColor(utilities.getRandomColor());

    this.gameServer.addNode(f);
    this.gameServer.currentFood++;
  };
```

For random mass.

**Comment by Agarian** [comment]
kk

**Comment by Megabyte918** [comment]
That would make a nice config

**Comment by Agarian** [comment]
i may make it a config

**Comment by Megabyte918** [comment]
@Agarian come on discord

**Comment by Agarian** [comment]
@Megabyte918 you wanted me on discord?
