### ISSUE TITLE
Cell color with skin

### ISSUE THREAD

**Issue by MineMooreALT** [AJS-development/Ogar-unlimited#1185]
Hey can we make it where the cell have the same color with the certain skin like agario.
this used to happen but when we moved over to play.ogarul.tk the borders are differnt colors it just really 
bugs my ocd.

**Comment by Agarian** [comment]
lol at the time it also bugged me, but i got used to it. Those who do not understand, me means cell border colors with premium skins as what happens in agar.io

**Comment by MineMooreALT** [comment]
Thanks Agarian for the simpler version lol

**Comment by Agarian** [comment]
I think ill close this

**Comment by LegitSoulja** [comment]
Do agar.io get a random pixel of an image, then apply the color? I know this is pretty easy to do using bitmap c# but with JavaScript I kindof got an idea on doing this.

Not all colors can be used though.

**Comment by Agarian** [comment]
@LegitSoulja i also missed something, in the diep.io mothership gamemode (i suggested for OgarUL), IDK how tank upgrades would work, as the client doesn't support it lol

**Comment by LegitSoulja** [comment]
@Agarian could be chat commands, since that's a thing now. I could easily add a GUI for the client also for the server that has the gamemode :)

**Comment by Agarian** [comment]
Speaking of the gamemode, hows it been doing?
