### ISSUE TITLE
How to make a server selection like this? QUESTION!

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#1186]
https://gyazo.com/80d6df2078772cb15393a9f63d0865d3

Title says, anyone have any code? would be much appreciated.

**Comment by DTMClanDeveloper** [comment]
oh hey thats gota! :D

**Comment by LegitSoulja** [comment]
@CalvinDKHD last strike before ban. I've told you already if you don't have experience too bad. Anymore issues like this you will be banned for spam for questions we will not answer...

**Comment by CalvinDKHD** [comment]
Whaa, so many other people gets help. Its a personal issue, you are mad at me. I dont understand why other people get help and i dont!

**Comment by LegitSoulja** [comment]
Other people don't get help. Check the issues yourself. Those things are personal correct. This is OgarUnlimited, not client help. We provide a client, but anything else you will need experience for that.

**Comment by CalvinDKHD** [comment]
Sorry never knew i couldnt get support for the client. I am sorry, and thanks for letting me know before hand. (not).

**Comment by LegitSoulja** [comment]
@CalvinDKHD I have told you plenty of times, on more than one issue you created about showing your servers. Like I said we don't discuss about clients, and if you don't have experience that's on your behalf. Maybe you should go learn.

Anymore duplicate posts from you about this you will be banned.

**Comment by CalvinDKHD** [comment]
You never told me you didn't help with clients.. You told me not too post
questions in issues. But I put a questions thing on and I made an issue
that I don't know where to ask questions and you just closes straight
away......

**Comment by LegitSoulja** [comment]
Google is your friend. Learn javascript

**Comment by CalvinDKHD** [comment]
Lol, yes. xD for the most i know VB and HTML. Not much js.....

**Comment by Andrews54757** [comment]
@CalvinDKHD Copy multiverse
