### ISSUE TITLE
Transparent cell - QUESTION

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#1187]
Hello! how do i make my cells transparent like in cellcraft?

**Comment by AgarioIsBest1602** [comment]
Why the hell u want transparent cells? It makes no sense and it only gives lag...

**Comment by Agarian** [comment]
this used to exist by the client, but we don't discuss clients.

**Comment by Megabyte918** [comment]
@CalvinDKHD use an extension

**Comment by LegitSoulja** [comment]
There's no transparency on cells. Only thing similar is the spy skin.
