### ISSUE TITLE
Speeds are too slow

### ISSUE THREAD

**Issue by joery1337** [AJS-development/Ogar-unlimited#119]
In comparison with Agar.io the speed of the player cells is slower.

**Comment by Agarian** [comment]
change playerSpeed in gameserver.ini to a higher value.

**Comment by joery1337** [comment]
Do you have an idea what's the perfect value, I'm not able to find it.

**Comment by Agarian** [comment]
i go with 40

**Comment by ErikParacelsus** [comment]
30-40 is perfect.

**Comment by Andrews54757** [comment]
I changed it to 35 for default
