### ISSUE TITLE
WHATS THE ISSUE OF PUTTING RETINA GRAPHICS IN THE GAME!!??

### ISSUE THREAD

**Issue by DTMClanDeveloper** [AJS-development/Ogar-unlimited#1190]
i never really get answered but WHY CANT RETINA BE PUT IN THE CLIENT!?

**Comment by Agarian** [comment]
First off, it belongs to miniclip. Taking it could make them sue us.
Second off, its harder than you think.
Third off, stop making duplicate/useless issues!
