### ISSUE TITLE
[ASK] Make Portuguese language.

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#1191]
@Andrews54757 Can i make portuguese language for Ogar-UL? i just don't know how to implement, sorry for all this time offline, i am having very huge school jobs :/

**Comment by LegitSoulja** [comment]
@Lukkez check the locals folder, you can make a language file for Portuguese, then I will implement it

**Comment by Lukkez** [comment]
Ok, i think on 1~2 hours i make it.

**Comment by Andrews54757** [comment]
@Lukkez Use the devtools plugin. Using it, you can create it in minutes
