### ISSUE TITLE
Plugin avaiable doesn't exist

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#1192]
When i try to install a plugin like MinionStart and i type wrong like "MimionStart" the answer who is given is: [Console] That plugin does not exist. Do plugin available to see available plugins and plugin search to search plugin
But, we don't have it more, just change it, or i self change it =p

**Comment by LegitSoulja** [comment]
It has been deprecated, which means it no longer exist. To search a plugin now you can do it simply by doing
> plugin search MinionStart

Installing plugins is normal
> plugin install MinionStart

**Comment by Lukkez** [comment]
I know, i am saying the console says wrong

**Comment by Lukkez** [comment]
just remove the part who says "Do plugin available to see available plugins and plugin search to search plugin"

**Comment by LegitSoulja** [comment]
@Lukkez ohhh, i gotcha.
