### ISSUE TITLE
Please how can i make cell borders bigger ?

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#1194]
Can i make cell borders bigger and fatter ? please tell me the file and the text to change thanks !!

**Comment by SharkFinPro** [comment]
What Do you mean by cell borders?

**Comment by SharkFinPro** [comment]
i think that stuff would be in the client, not the server...

**Comment by DarkZYT** [comment]
Ok ...

**Comment by DarkZYT** [comment]
But how ?

**Comment by AlexandriteErikParacelsus** [comment]
We don't discuss about client @Agarian close?

**Comment by Agarian** [comment]
k then

**Comment by DarkZYT** [comment]
Wait we are not sure if it is in the client ? open it please

**Comment by Agarian** [comment]
it is the client, it has to do with strokeStyle.

**Comment by DarkZYT** [comment]
Ok .. Thanks
