### ISSUE TITLE
Can someone please test me this

### ISSUE THREAD

**Issue by Ckicky** [AJS-development/Ogar-unlimited#1195]
http://play.ogarul.tk/?ip=192.168.1.100:80
If it doesn't work then tell me

**Comment by systemroot** [comment]
No is not working. Because  ip isn't an public ip we all have an ip like this by default
you can test ports at http://www.yougetsignal.com/tools/open-ports/ 
put ip and ogar port if port is opened is working.

**Comment by LegitSoulja** [comment]
@Ckicky You will find your ip here http://ipchicken.com 

Once you open your ports, thats your public ip, and people will be able to connect.
You can use this http://www.canyouseeme.org/ to test your ports

**Comment by Ckicky** [comment]
OMG i noob i putted the wrong ip

**Comment by Ckicky** [comment]
http://play.ogarul.tk/?ip=117.1.181.216:80

**Comment by Ckicky** [comment]
This is soooo complicated

**Comment by Ckicky** [comment]
The port forwarding

**Comment by Ckicky** [comment]
not rly

**Comment by Ckicky** [comment]
The ip stuffs
