### ISSUE TITLE
4th Of July

### ISSUE THREAD

**Issue by CodingKuda** [AJS-development/Ogar-unlimited#1201]
Does anyone have the fourth of july skins??? I really want to add them..

**Comment by DarkZYT** [comment]
Go to agar.re , all new skins are there , every new skin is always uploaded there !

**Comment by LegitSoulja** [comment]
I'll make some 4th of july skins :)

**Comment by CodingKuda** [comment]
Thanks both of ya

**Comment by LegitSoulja** [comment]
New fourth of july skins
* ```<4ofjuly>```
* ```<firework>```
*```<fw>```

and also alot of other new skins :)

**Comment by fayizan** [comment]
@LegitSoulja Thank u soo much for the new awesome skins and What Happened to the **BorderLine** I requested...? can u add it please...

**Comment by Tokoagar** [comment]
Did you had uncle Sam?
