### ISSUE TITLE
Linesplit and Popsplit bugs

### ISSUE THREAD

**Issue by Hunter2890** [AJS-development/Ogar-unlimited#1203]
1) Anybody who watches agar.io knows what a linesplit is but anyways it doesnt work on this private server it just clumps them together please someone explain how to fix this and second when i popsplit a bot/minion the mass will get deleted sometimes idk what caused this it didnt start happening till the latest update 

Please dont delete this post till i get a proper response, Thanks!

**Comment by DarkZYT** [comment]
Yeah i wanted to annouce this issue but we he did !

**Comment by Megabyte918** [comment]
@Hunter2890 Linesplits can be solved by using the official agario client instead of play.ogarul.tk

**Comment by LegitSoulja** [comment]
I thought play.ogarul was official?.

@Andrews54657 Do you no longer have site access or what happened? I know you asked me to share the files if I go, but I thought you still had access to FTP and etc. Let me know if not.

**Comment by CodingKuda** [comment]
@Megabyte918  Although the thing is that when you use ogarul on agario, it doesn't work....For me its just a white screen

**Comment by Zertag** [comment]
Oficial clinets dont work

**Comment by Agarian** [comment]
if you want OgarUL to work on the agar.io client, use https://github.com/AJS-development/Ogar-unlimited-noclient/

**Comment by AlexandriteErikParacelsus** [comment]
@agarian close pls

**Comment by AlexandriteErikParacelsus** [comment]
@agarian close pls

**Comment by Agarian** [comment]
Fine jeez
