### ISSUE TITLE
Minions feature

### ISSUE THREAD

**Issue by MineMooreALT** [AJS-development/Ogar-unlimited#1204]
can you make a option where minions connect gradualy

**Comment by firelightning13** [comment]
what

**Comment by Agarian** [comment]
i think he means that he wants a feature where the minion amount would increase slowly as time goes on.

**Comment by LegitSoulja** [comment]
Minion clamps :)

**Comment by Agarian** [comment]
This could be a plugin :D

**Comment by LegitSoulja** [comment]
I don't think so :/

**Comment by Agarian** [comment]
:(

**Comment by LegitSoulja** [comment]
Some things you can and can't do with a plugin
