### ISSUE TITLE
New Chat Command Update-Errors

### ISSUE THREAD

**Issue by fayizan** [AJS-development/Ogar-unlimited#1206]
After the chat command update,The errors I have seen

**1.Chat showing My Name along with my Skin Name(I don't want the skin name to be displayed)**
**The Skin is from my Server not from play.ogarul.tk**

![error1](https://cloud.githubusercontent.com/assets/19163419/16545337/aa544ce6-4145-11e6-809d-9d817b3d4532.jpg)

**2.Console Generating Lots of Error Messages if I use Chat command**  Note:some Kiddy players were always using `/bots 10000` command which also generate this error message in the console

![error](https://cloud.githubusercontent.com/assets/19163419/16545308/d6b2eaaa-4144-11e6-88b5-fe9bcfa9c7fc.jpg)

**Comment by NatsuTheGreat** [comment]
Are commands like that added? Or is it an undefined command that they are using and confused the code?

**Comment by LegitSoulja** [comment]
David started it with the chat commands thing that doesn't exist :/

Seems to me with your server and the client, you are having problems.

**Comment by NatsuTheGreat** [comment]
It's probably getting problems from the command being undefined/unkown.

**Comment by LegitSoulja** [comment]
I'm 100% sure that's not the issue. There no such thing as commands in chat. The only command usage in chat is 
./rcon

He had these problems before, which was claimed to be Statistics error/Crash, but Statistics has no bugs. Install it again?

**Comment by fayizan** [comment]
@LegitSoulja  none of the colour chat command is working for me,whenever I type the command that error message shows up in console but no problem to the server,game is normal

**Comment by fayizan** [comment]
what about my first question-skin that is loading from server shows skin name in chat..?

**Comment by Andrews54757** [comment]
I will look to it

**Comment by Agarian** [comment]
Will close for now.
