### ISSUE TITLE
ANTI LAG , LIKE MULTIOGAR?

### ISSUE THREAD

**Issue by inxlio** [AJS-development/Ogar-unlimited#1207]
PLS MAKE OGAR UNLIMITED ( MORE FEATURES ) , SAME THAN MULTIOGAR ( ANTI LAG )

**Comment by NatsuTheGreat** [comment]
Andrews is trying.

**Comment by LegitSoulja** [comment]
I wonder if my version of no lag will differ from Andrews?

**Comment by Megabyte918** [comment]
tell him about the changes before its too late, maybe he can add it into his current pr

**Comment by LegitSoulja** [comment]
@Megabyte918 it won't be compatible. I can revert back again after he released the update.
