### ISSUE TITLE
i need help hosting Digitalocean.com

### ISSUE THREAD

**Issue by Yamanourani** [AJS-development/Ogar-unlimited#1210]
i have my a digitalocean vps how can i host the server there

**Comment by LegitSoulja** [comment]
We don't help with hosting. If you don't have experience you will have to go discover more about it.

**Comment by Yamanourani** [comment]
wow :/ okay...

**Comment by systemroot** [comment]
read some old stories https://github.com/AJS-development/Ogar-unlimited/issues/1012
or read some new stories https://github.com/NoiseControllers/ogar-unlimited-autoinstall
