### ISSUE TITLE
Bad service. :(

### ISSUE THREAD

**Issue by Yamanourani** [AJS-development/Ogar-unlimited#1211]
tried to get info how can i host ogar ul on digital ocean they closed it  and never helped me

**Comment by XtremePlayzCODE** [comment]
They can't help you, and that is not AJS member's issue. Do some research, they are TIRED of getting requests on "How do I ____ this on ____".

**Comment by LegitSoulja** [comment]
Duplicate issues is another thing we are **TIRED** of. Why not just continue commenting on a closed issue? It doesn't take a rocket scientist to figure out that the same thing will happen if you did create another issue. The sad thing about it is, Just by duplicates, and not following guidelines, and coming here asking for help for things we don't know about NOR own, we can't help you at all. 

###### This is only OgarUnlimited Servers. Which means
* We don't provide hosting (You will have to provide)
* We don't discuss on how to host (Which you will have to figure out)
* We don't discuss about clients (Which the knowledge you need to know)

You will need experience to work with these things.

Millions of people will come here asking the same questions over and over again, and we are not going to help everyone, nor waste time when it's there responsibility when they come here, and download ogarul. Why download when you don't have no clue on how to use it?
