### ISSUE TITLE
OgarUL , THE FATHER OF LAG

### ISSUE THREAD

**Issue by nobsterr** [AJS-development/Ogar-unlimited#1214]
Sorry if I speak wrong, but I must say things clearly:

: OgarUL not hold more than 30 users on a dedicated

: OgarUL does not work in multicore

: Cigar and multiOgar and others , has a huge advantage in the field of lag

: Servers with OgarUL and more than 30 players is UNPLAYABLE ( tester for me , based on a dedicated 16gb ram)

Many Solutions But no result , 
One day take out an update that is really efficient?

**Comment by David1ali12** [comment]
Use MultiOgar its the best

**Comment by Agarian** [comment]
Yet is does not have the features OgarUL does.

**Comment by Agarian** [comment]
But if you really want to use it, https://github.com/Barbosik/MultiOgar

**Comment by LegitSoulja** [comment]
Eh, my server don't lag at all lol. 200+ bots no lag

**Comment by nobsterr** [comment]
is impossible

**Comment by LegitSoulja** [comment]
@nobsterr it's possible. Don't believe me go join yourself > join.ogarul.tk/legitsoulja

**Comment by fayizan** [comment]
@Legitsoulja can u please share your lag free version of ogarul
