### ISSUE TITLE
How do you forward ports?

### ISSUE THREAD

**Issue by Dylandonute** [AJS-development/Ogar-unlimited#1216]
1 https://github.com/AJS-development/Ogar-unlimited/issues/1215

Game Server Port = (443)
Stat Server Port = (88)

**Comment by lotfis** [comment]
https://www.youtube.com/watch?v=SXT8Ed-e1Sg

**Comment by LegitSoulja** [comment]
If you don't know how use the simple port forward tool. And don't create unnecessary, duplicate posts. Thanks.
