### ISSUE TITLE
Recommendations for play.ogarul.tk

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#1217]
Hey, I am here to say that any recommendations that should be added to play.ogarul.tk please list below. Here's all the polls you can take as of right now for something new to be added to the site. 

> Created polls will be added here http://ogarul.tk/vote.php

**Note**: All recommendations has to be voted for before added!. 

###### What's recently new/added?
* Online visitor counter

###### Winning polls
* [Global Site Chat](http://www.poll-maker.com/results743519xd2FB49CF-30?v=98#tab-2)

Create your own poll, and provide a link when you comment a recommendation.

> http://www.poll-maker.com/

**Comment by Megabyte918** [comment]
I was just about to make an issue like this for bugs xD

**Comment by ZitroAgario** [comment]
Please,show me how to set my server in list!
Thk

**Comment by fayizan** [comment]
@ZitroAgario do `plugin install Statistics` in the console and configure the config.ini in `/src/plugins/Statistics/`

**Comment by ZitroAgario** [comment]
i'm doing that but nothing going.
Maybe I what's doing wrong=(

**Comment by ZitroAgario** [comment]
I'm nu-ub

**Comment by GhostShot3** [comment]
@fayizan Help me with statitics,have skype ?

**Comment by LegitSoulja** [comment]
@GhostShot3 @ZitroAgario **You have to change the server name in order for it to work**. After changing, restart the server. You will get a message about your server being added to statistics.

**Comment by GhostShot3** [comment]
@LegitSoulja 
I changed, open all ports and still does not work, it was to work did everything is correct.

**Comment by GhostShot3** [comment]
Add Clear Chat command.
when running the chat is automatically cleaned.
http://www.strawpoll.me/10713592/r
#1252

**Comment by GhostShot3** [comment]
@LegitSoulja Is all correct,i changed names and port foward but dont works.

**Comment by LegitSoulja** [comment]
Use an open port checker to make sure your stat port is open. If it is then you shouldn't worry about not being able to see it on the stats yourself because obviously you won't be able to, but other people can.

**Comment by LegitSoulja** [comment]
What about a aim guide? I seen this on one site with an aiming guide from the center of mother cell, to mouse position. Thought it would be a nice addition for precise measures

**Comment by Agarian** [comment]
Idk what that would be like

**Comment by LegitSoulja** [comment]
It's a guide assistant, it's basically a line from your your main cell to mouse pointer.

If you don't understand how simple I explained it then, I have no other / better way to explain.

**Comment by Agarian** [comment]
oh i saw this in agarplus a long time ago

**Comment by SharkFinPro** [comment]
can you make it so in the chat there is a space after the semicolon? it gives a really crammed feeling...

**Comment by NatsuTheGreat** [comment]
^^ I hate that.

**Comment by Agarian** [comment]
lol this isn't exactly info or an announcement

**Comment by LegitSoulja** [comment]
@SharkFinPro sure, I'll fix it

**Comment by GhostShot3** [comment]
@LegitSoulja Why closed this ?

**Comment by Agarian** [comment]
Because he is quitting/leaving AJS.

**Comment by GhostShot3** [comment]
@Agarian  MY GOD SERIOUSLY ????

**Comment by Agarian** [comment]
Yep :neutral_face:

**Comment by Agarian** [comment]
See #1353

**Comment by GhostShot3** [comment]
@Agarian LOOOOOOOOOOOL NOOOO

**Comment by Agarian** [comment]
Unfortunately its TRRRRRRUUUUUUUUUUUEEEE

**Comment by Agarian** [comment]
:neutral_face: :gun:

**Comment by GhostShot3** [comment]
@Agarian On the good side it was a good ajs member at least for me.
