### ISSUE TITLE
How He Did This !!!!!! xD

### ISSUE THREAD

**Issue by kareemman00** [AJS-development/Ogar-unlimited#1218]
http://www.agarp.me/p/agario.html

**Comment by LegitSoulja** [comment]
Looks like MultiOgar, using agar.io.

**Comment by kareemman00** [comment]
But With Out Bagar HOW !!????????

**Comment by LegitSoulja** [comment]
MultiOgar works with multiple protocols. Even agar.io client can be used. 

This is nothing new to us :/

**Comment by MineMooreALT** [comment]
@LegitSoulja How do i get multiogar

**Comment by Agarian** [comment]
https://github.com/Barbosik/MultiOgar
