### ISSUE TITLE
Minion split

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#122]
How i put the minions to split, i can't, someone help

**Comment by Megabyte918** [comment]
I dont think that feature has been added yet. Its probably being worked on as we speak tho

**Comment by ErikParacelsus** [comment]
He will makes a big surprise for use so stay tune :)

**Comment by Andrews54757** [comment]
@ErikParacelsus  yo are right!!, a very big update will come soon!

**Comment by Agarian** [comment]
can't wait

**Comment by Andrews54757** [comment]
I just added minion control, just feature a of the big update ;)
