### ISSUE TITLE
Downloable Agar.io Client ?

### ISSUE THREAD

**Issue by nobsterr** [AJS-development/Ogar-unlimited#1220]
Downloable agario client ? original with retina graphics

**Comment by MineMooreALT** [comment]
im intersted

**Comment by nobsterr** [comment]
Please bring someone

**Comment by ItzLevvie** [comment]
https://github.com/ItzLevvie/Agar.io-files

**Comment by nobsterr** [comment]
how install it¿?

**Comment by nobsterr** [comment]
how install :C

**Comment by XtremePlayzCODE** [comment]
If you don't know how to install it why do you need it?

**Comment by nobsterr** [comment]
I need agario index . maint out and full files for graphics retina and borders

**Comment by XtremePlayzCODE** [comment]
omfg, use that script!

**Comment by nobsterr** [comment]
this script download only the folders , but not archives

**Comment by ItzLevvie** [comment]
It downloads the files as well

**Comment by ItzLevvie** [comment]
You need to make sure to run the .sh file

**Comment by raphyjb** [comment]
Tryed to run it.. got it.. Only files nothing else... Empty folders :(

**Comment by ItzLevvie** [comment]
I haven't tested the script on official VPS. Only tested it on C9 / Koding.

**Comment by raphyjb** [comment]
well it doesnt work... its really wierd when downloading, it goes directly to the root folder and paste in there.. and not in folder i put it in..
Also when i put it as bat, on windows i only get files
when i put on vps i get the rest of the folders and some docs but not all.. :/ possible to get a link to download? :/

**Comment by raphyjb** [comment]
Need the link for agario's client :) please!
