### ISSUE TITLE
AJS-development TEAM I need your help

### ISSUE THREAD

**Issue by HEROx29** [AJS-development/Ogar-unlimited#1222]
hi guys       
-----------------------------------------------------------------------------------------------------
# I have this server  : http://play.ogarul.tk/?ip=178.62.126.229:443 :AGARHERO
# and           this       : http://agarheros.me/  : AGARHERO
or in the server list: http://stats.ogarul.tk/  :AGARHERO 
-----------------------------------------------------------------------------------------------------
1-I am using Ogar-unlimited file I'm not trying to take your work  and say I make it  who made this game is AJS-development TEAM  (  but I need your help  for making my server a better )
-------------------------------------------------------------------------------------------------------
2-  I need your help for making multiple games  on one server  like  FFA TEAM EX  all in the same time  
--------------------------------------------------------------------------------------------------------
3-can I have the skin list or skin folder because  the skin Not working in my own Client
--------------------------------------------------------------------------------------------------------
4-can I use ads in my server  because I have to pay for the server every month 
-------------------------------------------------------------------------------------------------------------
# Thx

**Comment by XtremePlayzCODE** [comment]
4. Ads are OK
3. Download HTTrack and download the website play.ogarul.io/skins/ and the skin list is your problem.
2. Multiverse!
1. If you don't know how to use Node.js then you can't do that, wait for AJS team to make the best update ever with no lag, etc.

**Comment by LegitSoulja** [comment]
@XtremePlayzCODE hahah HTTrack doesn't even work. Is that a ban for talking about illegal tools to copy a site? Hmm 

Ads aren't allowed on play.ogarul.tk so make your own client.

With more than one game mode on a server use multiverse

**Comment by LegitSoulja** [comment]
Since you can't obtain all the skins, you have to add this SKIN_URL in your main out. 

Instead of ogarul.io use
> //play.ogarul.io/skins

**Comment by Agarian** [comment]
wrong link

**Comment by Agarian** [comment]
its 
play.ogarul.tk/skins

**Comment by LegitSoulja** [comment]
Oops, fixed. I'm using my phone and auto-correct I hate it.

**Comment by XtremePlayzCODE** [comment]
lol httrack was a joke, everyone knows its a lie

**Comment by Agarian** [comment]
I h8 autocorrect =\
That's why I use Android instead of IOS

**Comment by XtremePlayzCODE** [comment]
indeed

**Comment by LegitSoulja** [comment]
@Agarian I love apple over android.. I've never had an android. You can disable autocorrect with iOS though, but I haven't did so until now :/

**Comment by HEROx29** [comment]
Multiverse!
 ؟

**Comment by raphyjb** [comment]
ads are allowed. Andrew even made a plugin for this go look by urself

**Comment by LegitSoulja** [comment]
@raphyjb Yea, ads that you cannot make money off of. They aren't actually ads, but more like a broadcast feature.

Anything else you would like to tell me that I'm wrong about?

**Comment by HEROx29** [comment]
@LegitSoulja     ? = Multiverse!  how to make Multiverse!

**Comment by LegitSoulja** [comment]
@HEROx29 by using the multiverse command.

**Comment by HEROx29** [comment]
_multiverse command. not working_

**Comment by HEROx29** [comment]
nothing happened

**Comment by HEROx29** [comment]
@LegitSoulja  multiverse command. not working nothing happened
