### ISSUE TITLE
some play.ogarul.tk bugs i found and a suggestion

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#1224]
Here is a list of bugs i've found with the play.ogarul.tk client, if you have any more leave them here
- <del>you can still see skins when turning on the "no colors" setting on</del> theres a hide skin option too lol
- the "hide grid" option does not work in dark mode and changes it to light
- talking into chat while in spectate mode can bypass the spam filter, i saw this happening on Soulja's no lag server earlier, someone was spamming the link to their server all over the chat and no one could talk and i couldn't ban them because there name was just "spectator" and i didnt know who they were, this should be fixed
- Cell borders dissapear around 1.5k mass and so on, they should be present during all sizes like in vanilla

**about angles:** splitting and w default angles go all over the place and are hard to control, now that we have our own official client, we don't have to rely on the Agar.io client for the default splitting and w'ing angles. The default splitting angles should be changed to horizontal, but also be sensitive enough that if you were to move your cursor a couple pixels upward, then the angle would be changed to vertical so it would allow for things like [vertical linesplits](https://www.youtube.com/watch?v=FwOKY7U-pK8) to happen. angles like these would make splitrunning and teaming MUCH easier and it would be much easier to control where you want to split. Right now you just go every direction possible. it would also allow for linesplits and vertical linesplits to happen like i said before. the w-angles should be set to go to the left by default and also be sensitive enough that if you were to move your cursor a couple pixels to the right or upward, then it changes to said direction.

thank you for your time :D

**Comment by Agarian** [comment]
Also the skin flicker problem still exists (unless it was fixed)

**Comment by Agarian** [comment]
I once accidentally did a line split in play.ogarul.tk

**Comment by Megabyte918** [comment]
for some reason it very rarely sets the default split/w angle to go vertical, if your lucky that'll happen but most of the time its just diagonal and it breaks the line :/

**Comment by Agarian** [comment]
Yep

**Comment by Agarian** [comment]
@Megabyte918 Are you available on discord?

**Comment by Megabyte918** [comment]
yeah but im about to leave :/ meet me there

**Comment by LegitSoulja** [comment]
@Megabyte918 I'll take a look and fix these issues.

@Agarian during the time of using SkinChanger the flicker of the skins was caused if the plugin was reloaded which duplicated the interval on setting/changing skins. Now, recent update of SkinChnager has been fixed and multiple instances cannot be ranned. Correct me if I'm wrong if that wasn't the issue. That was the only skin flickering I've seen happen from that

**Comment by raphyjb** [comment]
popsplits... u lose the alot of mass for no reason try it.. ur ganna see

**Comment by LegitSoulja** [comment]
We already know. This isn't a client issue though. Try again.

**Comment by DerpyYT** [comment]
What about the minion bug with the merge set to lower values, the more i put lower values to the merge, the splitting whilst having minions bug out gets more and more buggy,

**Comment by LegitSoulja** [comment]
And again.. That is not a client bug. Report that in bug reports....
