### ISSUE TITLE
Server Won't Run.Needs Root Priveleges. What is that, and how do I fix that?

### ISSUE THREAD

**Issue by hlevine9** [AJS-development/Ogar-unlimited#1225]
I tried looking up the solution, but nothing came up, and no-one has ever had this problem. I feel that someone may solve this easily, because i am not good with computers. When I run the Start.bat File, it says that it terminated with code 1 and it also says above that Ogar has to be running with root priveleges. How do I fix this? Please quick, because i want to play on this again :(

**Comment by Agarian** [comment]
What os? If linux, make sure to run the server with sudo.

**Comment by LegitSoulja** [comment]
> plugin install PermsSolver

**Comment by Agarian** [comment]
isnt it `Permissions-Issue-Solver`?

**Comment by LegitSoulja** [comment]
@Agarian no, the plugins doesn't go by the folder name, its the name in files.txt of plugin library

**Comment by iDonaldTrump69** [comment]
wow

**Comment by raphyjb** [comment]
not voting for donaldtrump

**Comment by LegitSoulja** [comment]
Who said vote? You have the rights but you really don't have too. Plus you live out of this country so why would you even care? Are you mad you as not a u.s citizen? Don't be because it might just be a good idea not to even live in the United States anymore :/. United States is corrupted, even the government... I hate dealing with court.

**Comment by hlevine9** [comment]
Where do I put that in? In the Windows cmd?

**Comment by hlevine9** [comment]
I have windows 10.

**Comment by hlevine9** [comment]
Or Just give me the link to the PermsSolver plugin

**Comment by LegitSoulja** [comment]
Are you able to run commands or no?

**Comment by LegitSoulja** [comment]
Axtually, what server port did you change too? 

Also, the plugin is kindof unessary but easier for people who don't know anything but only thing you have do do is crown/chmod your files.

**Comment by hlevine9** [comment]
It just goes to Press any key to exit... and the port was 443, then i opened skype, changed the port to 444 then things went haywire.

**Comment by hlevine9** [comment]
I tried changing it back to 443 but it didnt fix

**Comment by LegitSoulja** [comment]
###### Skype:
Tools > Options > Advanced > Connection > and uncheck
![capture](https://cloud.githubusercontent.com/assets/4976824/16638195/f92c3178-43aa-11e6-9745-35015ec440f6.PNG)

> After that, you can use skype without having the port 443 error. Skype should randomly pick a port to use other than port 443.

###### Ogar Unlimited
* Change server port to 443
* Change stat port to 88

> Start the server. You should not have no problems. If you change your port to something else other than 443 and get the error **OgarUnlimited has to run with administration permissions** then you need to choose another port to use.

**Comment by hlevine9** [comment]
Its not that it says it needs administration privileges, it says it needs root privileges.

**Comment by NatsuTheGreat** [comment]
Did you click 'Allow Access' when first opening the batch file?

**Comment by hlevine9** [comment]
Yeah. It just suddenly stopped working. It worked for a while

**Comment by raphyjb** [comment]
Got it fixed by changing port to 4411, and it was at 445

**Comment by LegitSoulja** [comment]
How come you are always randomly jumping into conversations? I didn't even reply to your nor I didn't even state your name. 

Obviously, you don't need help but the person created the issue did. The only thing you ever said was you was not going to vote for Donald trump... Ok, why make a remark about that when you aren't even u.s citizen? You can't even vote.. Just hush. I wish I had a mute button somewhere.

**Comment by NatsuTheGreat** [comment]
> I wish I had a mute button somewhere.

I remember saying this about a year ago to someone in real life. o.O

**Comment by hlevine9** [comment]
My port is 443 if you didn't listen to my story above, and the stats port is 88.
I changed the stats port to 80 and nothing fixed. Should i try the port 4411? Or something random?

**Comment by LegitSoulja** [comment]
The stat port isn't the issue, it's the server port. Try using another.

**Comment by hlevine9** [comment]
Oh. I forgot.
I didn't know how to click "Allow Access" to the windows batch file because when i right click, i don't see that. Then the next best thing i think to click is "Run as Administrator"

**Comment by hlevine9** [comment]
Sorry NatsuTheGreat.

**Comment by hlevine9** [comment]
Pls show me how to click Allow access

**Comment by LegitSoulja** [comment]
That's doesn't work actually. Running as administrator doesn't set the right directory path but instead it runs where cmd is stored which is in system32. 

You would get an error about index.js not found..

What I would do if changing ports don't work is to add node into your firewall as an application and allow access. By default when you first run, node asks for permission which has to be allowed. Adding node to firewall should work. Add your ports inbound also in firewall.

**Comment by hlevine9** [comment]
Changing ports doesn't work, but i don't know how to add node to the firewall, nor how to add the ports into the firewall either. I am really bad at computers...

**Comment by LegitSoulja** [comment]
###### Add app to firewall

Control panel > Windows Firewall > Allow an app or feature through Windows Firewall

Change settings > Allow another app > Browse & go to this directory
> C:\Program Files (x86)\nodejs

double click on node.exe

###### Add port to firewall (If above method still doesn't work)

Control panel > Windows Firewall > Advanced settings > Inbound rules > New rule

From there select port, tcp, specific port (443) > Allow the connection > Next > add a name, any name.

Do it again for udp, and for your other port 88 aswell..

**Comment by hlevine9** [comment]
1. I can't find Node to allow into the firewall, and I do already have it downloaded, so i retried downloading it but nothing changed.
2. I look up Node on my computer through the search bar on the bottom left of the screen, it comes up, and i am able to run Node.js Version 6.3.0

**Comment by hlevine9** [comment]
I found out how to find Nodejs, but its not there...
How can i find it browsing?

**Comment by hlevine9** [comment]
Found Node, but still not working... Lemme try the port next.

**Comment by hlevine9** [comment]
Still not working... :(

**Comment by hlevine9** [comment]
Any other solutions? I added Node.js command prompt, and Node.js itself, i couldn't find nodejs. I also did the ports 444 and 88.

**Comment by hlevine9** [comment]
I alsotried re-instlling dependencies, but that didn't work either.

**Comment by LegitSoulja** [comment]
Go to your toolbar, or task manager and close skype completely and try again. I'm just making sure skype isn't the problem.

**Comment by LegitSoulja** [comment]
You can also open cmd and type
> netstat -a

Which will list all your running services. Just make sure there's no port interference

**Comment by raphyjb** [comment]
if i were u id ask ur mom to disable parental control...
lool

**Comment by Agarian** [comment]
I was wondering, and i thought maybe it would be easier to create a mothership entity instead of a mothership gamemode. @LegitSoulja  What do you think?

**Comment by LegitSoulja** [comment]
A mother-ship entity? Like a bot? Protect it for a certain amount of time? Give rewards to everyone who helped protect?

**Comment by Agarian** [comment]
That's not what i mean. Remember when i suggested to have a mothership gamemode? Similar to the one from diep.io? That's the mothership i'm referencing. But in entity form. Look i like to play as a mothership in diep.io but i rarely spawn as one. And even if i do, the gamemode only gives 2 minutes to do so. But i want more time, and i thought maybe using one in OgarUL would be cool.

**Comment by Agarian** [comment]
And also, join.ogarul.tk always gives me an error: "Please enter a URL" even if there is a URL in there

**Comment by LegitSoulja** [comment]
Oh, idk dude. That'll be weird having an unknown entity randomly appear in game from diep.
