### ISSUE TITLE
Cant Connect To My Server Via IP

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1226]
I Try To Connect TO My server using ip:port and it wont work, but when i do localhost:443 it does work.
Both The Stats Port And The Game Port are open (i checked)
How would i be able to connect to my server via ip?

**Comment by LegitSoulja** [comment]
You might not be able too but other people can. Just use the open port checker tool and call it a day

**Comment by SharkFinPro** [comment]
ok
