### ISSUE TITLE
Old Protocol

### ISSUE THREAD

**Issue by CAvcii** [AJS-development/Ogar-unlimited#123]
Hello there,
I have my old server protocol. When I integrate these files to the server, it remains in the connecting portion. How do I fix this?

**Comment by Andrews54757** [comment]
Remember, if you are useing a client clone, and not useing `agar.io/?ip=yourip:port` it is fully ILLEGAL and we do not support this

**Comment by Andrews54757** [comment]
but since i saw these things too many times, i created a config at the bottom to allow client clones. IT IS NOT RECOMMENDED THOUGH

**Comment by CAvcii** [comment]
@Andrews54757 Again, is this type can be prepared in a config file?

**Comment by Andrews54757** [comment]
?
