### ISSUE TITLE
Console flood

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#1230]
http://prntscr.com/bpcxh2
And i dont have plugins...

**Comment by LegitSoulja** [comment]
Did you update to the child update PR?

**Comment by GhostShot3** [comment]
@LegitSoulja  I use the last version.

**Comment by GhostShot3** [comment]
@LegitSoulja Updated Now

**Comment by LegitSoulja** [comment]
Let me ask you again. Did you update to the child branch / child PR?

If so, don't because it has not be released and if you have issues then they won't be solved since it's not released and will be fixed before release.

**Comment by GhostShot3** [comment]
@LegitSoulja #1196 ?

**Comment by LegitSoulja** [comment]
Yes. If you are using that then I cannot solve your issue because this is still in development and haven't been released / merged yet.

If this issue is regarding that, you should post the issue under that PR instead of making issues about something that hasn't even been released yet.

**Comment by LegitSoulja** [comment]
Unless you are using v17.4.0, and not that.

**Comment by GhostShot3** [comment]
@LegitSoulja Fixed in #1196 ?

**Comment by LegitSoulja** [comment]
Why was this opened again?

**Comment by GhostShot3** [comment]
@LegitSoulja Flood again...

**Comment by GhostShot3** [comment]
fix
