### ISSUE TITLE
PlayersMass vs BotsMinimumMass

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#1231]
Is there a way to change the mass of bots and not the players mass.. Lets say i spawn with 500 mass i dont want bots with 500 mass, even tho i got a plugin called SuperMinions looks like the plugin wont allow to go lower then the Playerstartmass , bin wondering this for a while now.. and bin checkin in alot of documents (.js) but didnt find anything.
Goal is to get in the config.ini a Minimumbotmass (so all bot when i go on console and i do minion 1 10, ill get lets say 10 bots with minimum mass on config.ini
Thanks for help! Hope anyone could find a fix to this!

**Comment by LegitSoulja** [comment]
_sigh_ after Andrew PR merge, I'll be glad to add a config for bots mass. But as of right now, no.

This has already been suggested, so I'll close this since it's a duplicate.

**Comment by raphyjb** [comment]
k

**Comment by Megabyte918** [comment]
just use the "spawnmass" command

**Comment by raphyjb** [comment]
lol ur funny that changes the bots mass and players mass!

**Comment by Megabyte918** [comment]
`spawnmass [id] mass` makes sure that THAT id gets a special starting mass

**Comment by raphyjb** [comment]
lol i want multiple poeple getting bots when they join.. Automaticaly does it.. i dont wanna do spawnmass id mass each time..

**Comment by SharkFinPro** [comment]
:|
do: 
`plugin install MinionStart`
`plugin install SuperMinions`
then edit the plugin to your liking - instaed of "minion" do "superminion" in the minionstart.js

**Comment by raphyjb** [comment]
k
ty
