### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by jollesnaas** [AJS-development/Ogar-unlimited#1232]
I can't code but I want to help, I'll make an Dutch translation. How can I add it to the Ogar-unlimited github? Or do I need to just upload the file and send a link?
Greetings from the Netherlands!

**Comment by AgarioIsBest1602** [comment]
Yo ik ben ook nl ik wil wel helpen

**Comment by LegitSoulja** [comment]
Use the dev tool plugin to create the language, and the yes you'll be able to upload.

**Comment by jollesnaas** [comment]
@AgarioIsBest1602 Add me dan ff op skype: jolle.snaas1
