### ISSUE TITLE
Making a diep.io clone

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#1233]
@AJS-development/ogar-unlimited-devs 
Me and @SharkFinPro are trying to make a diep.io private server. We've got most tank models down(we need the "drone" class tanks, the hybrid tank, the stalker, the ranger, there may be more) but could use help in other aspects of the server. Go here to help https://discord.gg/P4vVX7B
(Yeah i feel like this'll be closed by someone)

**Comment by SharkFinPro** [comment]
make the name this plz

`making a diep.io clone, Help Wanted`

**Comment by Agarian** [comment]
k

**Comment by SharkFinPro** [comment]
thats good

**Comment by SharkFinPro** [comment]
Github Repo Here:
https://github.com/SharkFinProductions/diepio

**Comment by Agarian** [comment]
thats kinda outdated tho

**Comment by SharkFinPro** [comment]
@Agarian Yes, but i havent added the most recent stuff yet

**Comment by SharkFinPro** [comment]
@LegitSoulja lol

**Comment by SharkFinPro** [comment]
@LegitSoulja can u go here plz
https://discord.gg/P4vVX7B

**Comment by LegitSoulja** [comment]
@SharkFinPro I'm good. I no longer have discord, and it took them a long time just to delete my account. Sorry but I don't use nor have discord. Skype is better, and im more comfortable with it.

**Comment by SharkFinPro** [comment]
ok

**Comment by Agarian** [comment]
gow about we use gitter @LegitSoulja?

**Comment by Agarian** [comment]
@SharkFinPro Will be out for the next few days =\

**Comment by LegitSoulja** [comment]
Gitter is fine

**Comment by PrinceDark9243** [comment]
![classes](https://cloud.githubusercontent.com/assets/17459204/16656182/20f27b50-4477-11e6-9d03-b6c179fe473e.png)
These are the Classes you can see from here when the server finishes can you make it free to download or paid or Private!

**Comment by Agarian** [comment]
@LegitSoulja are you able to come on gitte now?

**Comment by mrzack506** [comment]
@PrinceDark9243 That list does not include Hunter X, which is an upgrade from hunter.

**Comment by LegitSoulja** [comment]
@Agarain I'm getting on now

**Comment by LegitSoulja** [comment]
@Agarian *

**Comment by Agarian** [comment]
@LegitSoulja im on now

**Comment by VSabertail** [comment]
is it done?

**Comment by Agarian** [comment]
not even close.

**Comment by PrinceDark9243** [comment]
@LegitSoulja You Closed my Help Issue but you dident Close this Diep.io Help Issue it is Not Fair!

**Comment by Agarian** [comment]
**I need help with:**
- Modeling the remaining tanks
- Bullet angles
- Adding bullet functions to other tanks
- Add player/shape collisions
- Making drones for the following tanks: Overseer, Overlord, Manager, Necromancer.
- Scores/LVLing up

**Comment by LegitSoulja** [comment]
@PrinceDark9243 there's a difference between when a dev make an issue, vs a non dev. And besides, you where looking for help, and this was already started but was looking for more people to help out. Eventually this will be closed aswell.

**Comment by LegitSoulja** [comment]
And this isn't a modified a game, this is a new game creation. There's a huge difference between this issue and yours.

**Comment by PrinceDark9243** [comment]
oh but sorry about my issue OK CONTINUE!

**Comment by Agarian** [comment]
@Megabyte918 Please tell me you are available on discord

**Comment by VSabertail** [comment]
the invite is expired i need a new one

**Comment by Agarian** [comment]
@Megabyte918 can we not be "uncoordinated" on getting on gitter/discord? Join now

**Comment by Agarian** [comment]
i give up, no one ever seems to have time to help.

**Comment by VSabertail** [comment]
i wish i could help

**Comment by Agarian** [comment]
The invite isn't expired btw

**Comment by Agarian** [comment]
@Megabyte918 and/or @LegitSoulja You have time?

**Comment by LegitSoulja** [comment]
@Agarian im on now, but only for a little bit.

**Comment by Agarian** [comment]
k

**Comment by LegitSoulja** [comment]
@Agarian what do you need help with? The same thing?

**Comment by Agarian** [comment]
yes

**Comment by Agarian** [comment]
im on gitter

**Comment by LegitSoulja** [comment]
@Agarian can you get skype for once? Im on skype with mega....

**Comment by Agarian** [comment]
i dont have skype

**Comment by Agarian** [comment]
i guess ill make an acc

**Comment by LegitSoulja** [comment]
That's why I said get it

**Comment by Agarian** [comment]
i have to install it?

**Comment by Agarian** [comment]
psh no thanks

**Comment by LegitSoulja** [comment]
there's a web version aswell

**Comment by Agarian** [comment]
oh

**Comment by LegitSoulja** [comment]
http://web.skype.com

**Comment by LegitSoulja** [comment]
but you wont be able to talk, nor share files.. So web skype is kindof pointless.

**Comment by Agarian** [comment]
i dont wanna share files

**Comment by Agarian** [comment]
why cant we use gitter??

**Comment by Agarian** [comment]
you know i don't even have a mic or even a web cam

**Comment by LegitSoulja** [comment]
I don't have a mic, nor web cam..

**Comment by Agarian** [comment]
ok you know what,? FINE. i have an acc, how to i find you?

**Comment by LegitSoulja** [comment]
whats your skype name?

**Comment by Agarian** [comment]
Agarian9876

**Comment by Agarian** [comment]
i found mega

**Comment by VirgoAgario** [comment]
Can someone show me how to actually play it... I have everything installed it's just I don't know what to do know D:

**Comment by SharkFinPro** [comment]
its called search up "agario" on youtube

**Comment by LegitSoulja** [comment]
search youtube "**play.ogarul.tk**". There's many of topic. Find recent videos by using the filter, and upload date.

**Comment by VirgoAgario** [comment]
No the Github Repo... I know how to play OgarUL i'm a pro at it but the Diep.io thing I just can't get to.  :hankey: :-1:

**Comment by SharkFinPro** [comment]
go to diepio.ga its in development

**Comment by Agarian** [comment]
Virgo it is unfinished, so hold your shit.

**Comment by Agarian** [comment]
@SharkFinPro you available?

**Comment by LegitSoulja** [comment]
His constipation is urgent haha
