### ISSUE TITLE
Server Wont Show Up On stats.ogarul.tk

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1234]
I tested With @Agarian and he could come onto my server, i have the stats plugin installed, but my server wont show up on stats.ogarul.tk

**Comment by LegitSoulja** [comment]
Make sure you don't have **'** in your server name. For some odd reason it doesn't with with a apostrophe.

**Comment by SharkFinPro** [comment]
ok

**Comment by SharkFinPro** [comment]
That Didnt Work...

**Comment by SharkFinPro** [comment]
![capture](https://cloud.githubusercontent.com/assets/18649707/16636253/c684e39c-438b-11e6-8d4d-e388b6ae78f8.JPG)
:| wai...

**Comment by LegitSoulja** [comment]
show me your configuration for statistics.

**Comment by LegitSoulja** [comment]
Do you have your stat port open?

**Comment by SharkFinPro** [comment]
yes, both ports are open

**Comment by LegitSoulja** [comment]
Can you start the server for me? Thanks

**Comment by SharkFinPro** [comment]
just did

**Comment by LegitSoulja** [comment]
> http://76.22.13.186:443/ (Offline)
http://76.22.13.186:88/ (Offline)

**Comment by LegitSoulja** [comment]
I recommend using this open port checker tool.
> http://www.canyouseeme.org/

Note: Your server is listed on stats, but your ports are not open to test connectivity. Therefor your server will appear offline.

**Comment by SharkFinPro** [comment]
:|

**Comment by LegitSoulja** [comment]
Your port 443 just connected, but port 88 is still offline.

**Comment by SharkFinPro** [comment]
both are open

**Comment by LegitSoulja** [comment]
Nope :/

**Comment by SharkFinPro** [comment]
hmm

**Comment by LegitSoulja** [comment]
![capture](https://cloud.githubusercontent.com/assets/4976824/16637034/a184a4cc-43a1-11e6-8392-adeb9f037b79.PNG)

**Comment by SharkFinPro** [comment]
hmm
it wont work
before i restarte dit was working...
how would i port forward? i allready did...

**Comment by SharkFinPro** [comment]
now when i connect to my server, it says port 88 is open, but 443 is closed

**Comment by SharkFinPro** [comment]
now 88 is closed and 443 is open o_O

**Comment by LegitSoulja** [comment]
88 just came online, and port 443 went offline. Now they are both off again.

**Comment by LegitSoulja** [comment]
well port 88 is still on, but not 443

**Comment by SharkFinPro** [comment]
hmm
what do u think is the problem

**Comment by LegitSoulja** [comment]
How are you port forwarding? What type of router do you have?

**Comment by SharkFinPro** [comment]
i dont know, i dont know

**Comment by LegitSoulja** [comment]
443 is now up, but 88 went back off lol

**Comment by SharkFinPro** [comment]
lol

**Comment by LegitSoulja** [comment]
OK STOP!

**Comment by LegitSoulja** [comment]
they are both on now

**Comment by SharkFinPro** [comment]
both are open

**Comment by SharkFinPro** [comment]
yes

**Comment by LegitSoulja** [comment]
![capture](https://cloud.githubusercontent.com/assets/4976824/16637135/7f644a2c-43a2-11e6-92fe-88a303d5a5bf.PNG)

**Comment by LegitSoulja** [comment]
looks good.

**Comment by SharkFinPro** [comment]
ok

**Comment by SharkFinPro** [comment]
wai cant i see it...

**Comment by LegitSoulja** [comment]
hm?

**Comment by SharkFinPro** [comment]
i cant see it

**Comment by SharkFinPro** [comment]
when i go to stats.ogarul.tk

**Comment by LegitSoulja** [comment]
You won't be able too, but other people can. If you set your hosts file correctly you can be able to see it :)

**Comment by SharkFinPro** [comment]
ok

**Comment by LegitSoulja** [comment]
If you go to **C:\Windows\System32\drivers\etc**
You can add a host for example I think

Your public ip      ipv4.

Like for example
76.22.13.186       192.168.0... < your ipv4

**Comment by LegitSoulja** [comment]
So when you connect to your ip 76.22.13.186, it will route back to your ipv4 :)
