### ISSUE TITLE
How to connect it on agar.io?!

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#1235]
Ok ive bin looking around and ive saw private server but still on agar.io site
was wondering how to change it to be on agar.io and not play.ogarul.tk

**Comment by Hunter2890** [comment]
you have to use the no client one

**Comment by Hunter2890** [comment]
this is what you have to use https://github.com/AJS-development/Ogar-unlimited-Noclient

**Comment by Hunter2890** [comment]
@agarian this needs to be closed :P

**Comment by raphyjb** [comment]
that doesnt work... U got skype 
add me : raphyjb

**Comment by LegitSoulja** [comment]
No client protocol and packet needs updating again, so therefor it doesn't work.

**Comment by raphyjb** [comment]
when is update?!

**Comment by LegitSoulja** [comment]
Idk....

**Comment by raphyjb** [comment]
kk :) thanks!

**Comment by LegitSoulja** [comment]
No client does work with agar.io... I just tested..
