### ISSUE TITLE
can not....

### ISSUE THREAD

**Issue by Hunter2890** [AJS-development/Ogar-unlimited#1236]
im getting error : cannot  find module 'collections/fast-map' it didnt happen till latest update (when one come i install again and delete old one) but same happens when i install dependencies

**Comment by Agarian** [comment]
It doesn't seem like the fast-map module is not in package.json

**Comment by Hunter2890** [comment]
so what do i do?

**Comment by LegitSoulja** [comment]
Look at the trouble shooting issue. Your solution is there.

**Comment by LegitSoulja** [comment]
@Agarian @Hunter2890 Just simply do 
> npm install collections

or download https://github.com/montagejs/collections

**Comment by Hunter2890** [comment]
@LegitSoulja @Agarian where do i put "fast-map"?

**Comment by Agarian** [comment]
@Megabyte918 you available on discord/gitter?

**Comment by Agarian** [comment]
@LegitSoulja How about you?

**Comment by Agarian** [comment]
Can any one help me with bullet angles on my diep.io clone??

**Comment by Agarian** [comment]
nvm too late

**Comment by Megabyte918** [comment]
im on now
