### ISSUE TITLE
Need the client that has chat

### ISSUE THREAD

**Issue by mrzack506** [AJS-development/Ogar-unlimited#1237]
Hi, everytime I try to do a command in the chat, it says this "Stopped crash at packethandler. Probably because of wrong packet/client . Usually normal.". I know I have the correct packet, but I don't think I have the right client. Can anyone send me the new one? Thanks.

**Comment by LegitSoulja** [comment]
https://github.com/AJS-development/Ogar-unlimited/issues/918#issuecomment-225019348
