### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#1238]
I am Making a Android Mech Server so i need some help:

1. How i can make every Entity does not bounce from border like android and ios agar.io

2. How i can make split like Android and Ios agar.io splits instantly i set the cRestoreTicks to 0 and 1 but i dosent work

3. how i can make my server support double nick like:
![maxresdefault](https://cloud.githubusercontent.com/assets/17459204/16662847/f6fb1f3e-4492-11e6-98a3-e8d5bc0dbd80.jpg)

4. can i able to make my server will decay mass 1 by 1 ms (milisecond) its mean 1 mass will decay in a millisecond but when you have 11999 to 22500 mass

5. in ogar ul big cell will give us long recombine but i want that recombine time is only 30 sec no more going to be add

6. in ogar ul if i have 4 cells if all cells are going to recombine only 2 cells recombine and restore ticks get higher so other cell take 4-3 sec to combine again but i need not higher tick 4 cells recombine at same time! but when i splitted at same time! if you dont understand me then you play on mobile agar.io then you see everthing in it!

PLEASE DONT CLOSE THIS ISSUE WITHOUT MY PERMISSION!

A HELP WILL BE APPRICATED!

Thanks!

**Comment by LegitSoulja** [comment]
This is something you will need knowledge of to do for your own, or have someone else to help you.

Maybe you should try this on vanilla Ogar instead of here. And permissions? I think I have the rights to bypass that. Any further questions can be answered in this issue. Please don't make another issue.

**Comment by NatsuTheGreat** [comment]
>PLEASE DONT CLOSE THIS ISSUE WITHOUT MY PERMISSION!

Lmao :/

**Comment by Agarian** [comment]
@LegitSoulja i'm back on gitter now, sorry to keep u waiting =\

**Comment by Agarian** [comment]
@Megabyte918 can you come on discord or gitter? I think Legit is off his PC.
I need help with bullet angles, shape/player collisions etc.

**Comment by LegitSoulja** [comment]
I'm back on

**Comment by Agarian** [comment]
Too late -_-

**Comment by Agarian** [comment]
We have to continue tomorrow
