### ISSUE TITLE
The new minions update

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#124]
Okay, so let's say i want 100 bots to spawn, i do this:
addbot 100
then i want them as my minions,i do this:
minion 1
and after that i want 100 bots that wont go into me.

So 100 minions i have
and i want 100 bots that will play by theirselves, is there a way for this?

**Comment by Megabyte918** [comment]
Not at the moment. As of now the only command is minion [Id] so that means whatever id you input is who ALL the bots go to. You'll have to get a separate bottling extension if you want to have your own private bots

**Comment by elitajmx** [comment]
Ok

**Comment by Andrews54757** [comment]
I will make a system that makes bots and minions separate so it would be `minion [id] [number]` and to turn off it would be `minion [id]` or to turn off completely, do `minion destroy`

**Comment by firelightning13** [comment]
The minion is nice though, i like it :) but pressing "Q" is a little weird because it will conflict when u r in op mode

**Comment by Agarian** [comment]
i cannot leave for a couple of hours without missing major updates -_-

**Comment by firelightning13** [comment]
Me too lol its 2:04 AM now xD

**Comment by PrinceDark9243** [comment]
Can someone plz make it like login system. for example a file that conatains all op username and password in the file Pro999:iamcool Username:Password when you type same nick server will check is this name is matched the player will get a selected skin and name PLZ MAKE IT i like Ogar Unlimited

**Comment by Agarian** [comment]
where will the user type the username and password? the current agario client only has a text box for the name. unless the username:password is typed there.

**Comment by Andrews54757** [comment]
it is impossible since the character limit for agar.io is 15 and you can't do `username:lol password:something` because it doesn't fit

**Comment by Andrews54757** [comment]
I have created a opbyip feature though
