### ISSUE TITLE
how to get ultimate skins ?

### ISSUE THREAD

**Issue by liomessip** [AJS-development/Ogar-unlimited#1240]
how to get ultimate skins of agario? 

what is the direct link of skins 11/07/16 ??

**Comment by LegitSoulja** [comment]
? What ultimate skins?

**Comment by liomessip** [comment]
11/07/16

**Comment by Megabyte918** [comment]
Idk what 11/07/16 means but i found this http://agario-skins.org/premium-skins

**Comment by ItzLevvie** [comment]
@Megabyte918 He was talking about the 10th of July skins

**Comment by NatsuTheGreat** [comment]
I automatically got them today. Got their names too :D
