### ISSUE TITLE
Upgrade Required on my VPS

### ISSUE THREAD

**Issue by dokicro** [AJS-development/Ogar-unlimited#1241]
Hi,

I just installed and run Ogar-unlimited on my VPS.
When I try to connect to server through **play.ogarul.tk**  with my ip everything works, but I want to be able to start the game on my domain, so when I just type my ip adress:port I get this error
**Upgrade Required**

I tired to download Client plugin and when I try to run ipadress:8080 i get this error:
**Cannot GET /**

**Comment by firelightning13** [comment]
After you install the Client plugin, just download the client files here #918 , refer to the tutorial if you dont know how to setup the client

**Comment by dokicro** [comment]
Thanks!
