### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by tommyb008** [AJS-development/Ogar-unlimited#1242]
What settings do i need to change for exact agario physics?
like splitting, you know collisions all that stuff how can i get it exact as agario?

**Comment by LegitSoulja** [comment]
There's no settings to change. Neither Ogar nor multiogar has good physics.

**Comment by tommyb008** [comment]
like with linesplitting

**Comment by tommyb008** [comment]
oops
wrong button

**Comment by tommyb008** [comment]
like its impossible to linesplit with the current settings what do i change?

**Comment by hlevine9** [comment]
I know Linesplitting is so difficult... when my server was working.

**Comment by Megabyte918** [comment]
You change the client for linesplits

**Comment by tommyb008** [comment]
how?

**Comment by tommyb008** [comment]
what do i change?

**Comment by Megabyte918** [comment]
Use the Agar.io client instead of play.ogarul.tk

**Comment by tommyb008** [comment]
@Megabyte918 do you possibly know why i cant connect to any server?
lets say when i try to join my server this is what i get
jquery-1.11.3.min.js:5 GET http://85.113.183.38:88/ net::ERR_CONNECTION_REFUSEDsend @ jquery-1.11.3.min.js:5ajax @ jquery-1.11.3.min.js:5(anonymous function) @ legitsoulja.js?0443350:9each @ jquery-1.11.3.min.js:2success @ legitsoulja.js?0443350:8j @ jquery-1.11.3.min.js:2fireWith @ jquery-1.11.3.min.js:2x @ jquery-1.11.3.min.js:5b @ jquery-1.11.3.min.js:5
legitsoulja.js?0443350:11 XwrSCh6Eco > Offline
legitsoulja.js?0443350:11 IDKx5JigZc > Offline
main_out.js?v1.0.0b:40 Connecting to ws://50.173.201.239:443
main_out.js?v1.0.0b:43 socket open
main_out.js?v1.0.0b:44 socket close
connect ("ws://50.173.201.239:443")
main_out.js?v1.0.0b:40 Connecting to ws://50.173.201.239:443
undefined
main_out.js?v1.0.0b:43 socket open
main_out.js?v1.0.0b:40 Connecting to ws://104.214.106.58:444
main_out.js?v1.0.0b:43 socket open
main_out.js?v1.0.0b:44 socket close
main_out.js?v1.0.0b:40 Connecting to ws://50.173.201.239:443
main_out.js?v1.0.0b:43 socket open
main_out.js?v1.0.0b:44 socket close
and it wont let me join any help?

**Comment by NatsuTheGreat** [comment]
Are you using any type of extension?

**Comment by LegitSoulja** [comment]
Ignore the log from legitsoulja.js. I forgot to remove that :/.

Are you using any type of extension? Using an extension with an old boot wont work.

**Comment by tommyb008** [comment]
no im not

**Comment by tommyb008** [comment]
fixed.
