### ISSUE TITLE
Anyone can help me?

### ISSUE THREAD

**Issue by inxlio** [AJS-development/Ogar-unlimited#1243]
As add on the leaderboard , my current top, as in mobile agario , whatever be my position

**Comment by Agarian** [comment]
what?

**Comment by fayizan** [comment]
@Agarian I think He is saying that he wants the leaderboard to show his current position like in the mobile agario 
![x7zqo7i](https://cloud.githubusercontent.com/assets/19163419/16706037/3c9a8538-45bb-11e6-9364-468e36512c4e.png)

**Comment by LegitSoulja** [comment]
Show his position on the leaderboard? Come again?

**Comment by Agarian** [comment]
Like if he is #56, he will still see himself on the leaderboard, but labeled #52

**Comment by inxlio** [comment]
![x3](https://cloud.githubusercontent.com/assets/20158370/16708680/4c42f738-45d2-11e6-8949-66da5fc6bf9c.png)

**Comment by PrinceDark9243** [comment]
oh you want to have current position on leaderboard

**Comment by inxlio** [comment]
yess :c

**Comment by PrinceDark9243** [comment]
I am not a Dev so i cant able to help you i need that thing too :D

**Comment by LegitSoulja** [comment]
Oohhh.. Have his position on the leaderboard last.. @Agarian um wtw was that??

**Comment by Agarian** [comment]
lol its not like i can simplify everything...

**Comment by LegitSoulja** [comment]
but you showed me an issue about someone being mean to eachother, then another one that was blank..

**Comment by Agarian** [comment]
who me?

**Comment by Agarian** [comment]
And you available for gitter Legit?

**Comment by VSabertail** [comment]
GO DIEP.IO

**Comment by LegitSoulja** [comment]
@VSabertail spam?

**Comment by inxlio** [comment]
@LegitSoulja  @Agarian  can help me?

**Comment by LegitSoulja** [comment]
@inxlio if its about the leaderboard thing, i will try my best add it. I'll have to re-write the leaderboard system in order to do that.

**Comment by firelightning13** [comment]
@VSabertail It's already on the way, #1233

Also, pls dont spam :)

**Comment by firelightning13** [comment]
Well nvm
