### ISSUE TITLE
 Someone may make public the code that uses c0nsume.me , for graphics

### ISSUE THREAD

**Issue by inxlio** [AJS-development/Ogar-unlimited#1245]
the dev can ? please

**Comment by NatsuTheGreat** [comment]
We are not going to use agar.io's graphics, not c0nsume.me's graphics, not anyone's graphics. We aren't going to make any code public, if you want the graphics that bad, talk to lulzy. We are not going to search for the client's graphics.

**Comment by inxlio** [comment]
ok sorry
