### ISSUE TITLE
Help with font.

### ISSUE THREAD

**Issue by mrzack506** [AJS-development/Ogar-unlimited#1246]
Hi, if possible, I'd like to know the font in the most recent version of agar.io. It looks like this 
![capture](https://cloud.githubusercontent.com/assets/19736068/16709126/6a385dc0-45d5-11e6-84d8-22f3c68c0a3d.JPG)
Thanks.

**Comment by inxlio** [comment]
Is in main_out.js

**Comment by ItzLevvie** [comment]
Yes.

**Comment by NatsuTheGreat** [comment]
We are not going to help with taking agar.io's font/graphics. They could sue us.
