### ISSUE TITLE
So much lag even with only 5 bots 

### ISSUE THREAD

**Issue by VSabertail** [AJS-development/Ogar-unlimited#1247]
I was deciding to go on agar.io unlimited and i added 20 bots it lagged like shit then i took away ten still lagged then i tooked away 5 and still lagged then i took away all the bots then there was only a little lag but last time i play i could but 30 bots and 10 minions and no lag what is causing this i need answers  so i can go back to having fun again on my server

**Comment by VSabertail** [comment]
I tried to use a different computer and it still lagged its not my computer its the server

**Comment by AlexandriteErikParacelsus** [comment]
#1115

**Comment by fayizan** [comment]
@VSabertail Check your server bandwidth speed..!! Mainly the upload speed should be more than 30mbps..!!
