### ISSUE TITLE
Why OgarUL have lag when i have +30 users

### ISSUE THREAD

**Issue by liomessip** [AJS-development/Ogar-unlimited#1248]
title^^

I have a dedicated vps ...

there is a stable version of ogarUL without lag?

**Comment by LegitSoulja** [comment]
You know, It doesn't matter because you have a dedicated vps.. It's pointless actually knowing nodejs only runs on 1 core. There's no potential in the server what so ever.

**Comment by inxlio** [comment]
and multiogar ? , 
They can do as multiogar ?

**Comment by VSabertail** [comment]
Look at my issue i have same problem but worse

**Comment by VSabertail** [comment]
i love fighter tank in diep.io it is bae i love it so much you should use it its so good omg u get so many points so fast people think ur hacking use 0,0,0,7,7,7,7,5 its awesome u get so many points sorry but i had to say this

**Comment by Agarian** [comment]
also @liomessip probably not =\

**Comment by raphyjb** [comment]
Kinda wierd i dont lag and i had 94 poeple in it..
No bots tho :) and 4000 pellets

**Comment by VSabertail** [comment]
GO DIEP.IO!!!!

**Comment by VSabertail** [comment]
4000 TANK PELLETS RAPHYJB YEAH HE LIKES DIEP.IO GO DIEP GO DIEP GO DIEP YEAH

**Comment by LegitSoulja** [comment]
@VSabertail Enough of this diep.io spam. You will be banned for a week!. This is ogar!, not diep. nobody cares!.

**Comment by mrzack506** [comment]
@LegitSoulja Actually, if he does npm instal lpm2@latest -g and then create a file that will start index.js using PM2 (ex: pm2 start index.js), he can use all cores. And it works extremely well :)

**Comment by fayizan** [comment]
@mrzack506 what is the node version you are using..?

**Comment by LegitSoulja** [comment]
I never knew this existed.. Thanks for sharing I guess

**Comment by fayizan** [comment]
Cool..!! So this is Process Manager for Node.js  http://pm2.keymetrics.io/

**Comment by fayizan** [comment]
WoW its working..!!! but how do I access the ogarul console..??

**Comment by mrzack506** [comment]
@fayizan Use @LegitSoulja's plugin: Ogarconsole :)

**Comment by fayizan** [comment]
@mrzack506 Thank u so much, mine is working great with PM2 

**With 20 players and 20 bots,Cluster Mode**

![screenshot_15](https://cloud.githubusercontent.com/assets/19163419/16713314/93788d76-46c1-11e6-961a-ed2754629dca.jpg)

![screenshot_16](https://cloud.githubusercontent.com/assets/19163419/16713313/93712dec-46c1-11e6-94d5-06fc56bb0cc0.jpg)

**Comment by inxlio** [comment]
how to use console ogarul ?

**Comment by LegitSoulja** [comment]
Since pm2 is a solution, this will now be closed.
