### ISSUE TITLE
Keep getting an error.

### ISSUE THREAD

**Issue by mrzack506** [AJS-development/Ogar-unlimited#1249]
"Stopped crash at packethandler. Probably because of wrong packet/client . Usually normal."
Console says that if i were to type a chat command. Or it happens every 5-30 seconds.

**Comment by LegitSoulja** [comment]
I figured out this new recent update it happens when a player tries to execute a command via chat. I'll see what's wrong with this new feature.

**Comment by LegitSoulja** [comment]
Fixes will have to be placed on hold until recent PR merge. I'll keep this opened and locked until then

**Comment by Megabyte918** [comment]
Just remove the error message from the file where it comes from i guess. i mean, its not causing any bugs right? might as well. and im going to close this because it doesn't look like the child update will be happening any time soon.
