### ISSUE TITLE
All things are small

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#125]
![image](https://cloud.githubusercontent.com/assets/15003706/13222821/7d52f096-d960-11e5-8a2d-78ef35c7573e.png)
When i use the last version

**Comment by Megabyte918** [comment]
Did you try changing the virus and food mass in gameserver.ini?

**Comment by Lukkez** [comment]
But as you can see i'm with 12 mass and looks like 1 mass and the virus is 100 mass

**Comment by Megabyte918** [comment]
Oh sorry I didnt see that =P try just updating the server using the update command that should fix everything

**Comment by Lukkez** [comment]
I can't fix

**Comment by Megabyte918** [comment]
Did you edit any of the files? If so tell me which

**Comment by Lukkez** [comment]
Nope, only gameserver.ini i changed ejectMassCooldown to 1

**Comment by Megabyte918** [comment]
look for `Cell.prototype.getSize` in Cell.js and replace the only number with 100. It should look like this:

Cell.prototype.getSize = function() {
    // Calculates radius based on cell mass
    return Math.ceil(Math.sqrt(100 * this.mass));
};

**Comment by Luka967** [comment]
Already known issue when changing map borders while console is active. I have no idea why. To fix it just restart the server.

**Comment by Andrews54757** [comment]
It is because the client thinks you passed the border. It is not recommended to use the enlarge command often.
