### ISSUE TITLE
Can you use Hamachi to forward ports to allow friends to join?

### ISSUE THREAD

**Issue by Dylandonute** [AJS-development/Ogar-unlimited#1250]
I want to know if I can use Hamachi to forward ports, because basic port-forwarding is complicated, and Hamachi is easier.

**Comment by LegitSoulja** [comment]
You we don't support hamachi.

**Comment by LegitSoulja** [comment]
Hamachi Is not easier.. That's the most complicating thing ever. If it was easy you would've necer asked a question.
