### ISSUE TITLE
How do you port forward on play.ogarurl.tk? 

### ISSUE THREAD

**Issue by Dylandonute** [AJS-development/Ogar-unlimited#1251]
I want to know how to forward ports on ogarurl. A few weeks ago, you started using ogarurl, instead of agar.io. Before I used to type "ip" in the Google search bar and gave it to my friends while they were on my port, but now I dont know how to do it with agar.io 
Thanks!!

**Comment by LegitSoulja** [comment]
play.ogarul.tk & agar.io uses the same concept. 

Learn how to port forward. You can share your server using the statistics plugin, or give your friends a custom like directly to your server. For example

http://play.ogarul.tk/?ip=example.com:443, but example.com would be your ip address that you get from google.
