### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#1252]
Add `Clear Chat` command.
when running the chat is automatically cleaned.
http://www.strawpoll.me/10713592/r

**Comment by Agarian** [comment]
Good idea but put it in #510

**Comment by GhostShot3** [comment]
@Agarian Why closed ?

**Comment by LegitSoulja** [comment]
Close because this has been added to suggestions. Move your poll there instead.
