### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ghost** [AJS-development/Ogar-unlimited#1253]
## Please do not go off topic!

   **RULES:**
1. Do not make a comment that is not a suggestion!
2. Do not say things like "lets talk on discord"!
3. Please, use https://gitter.im/AJS-development/Ogar-unlimited for chat!
4. Please refrain from spam and profanity!
5. Do not make separate issues for your suggestions!

**Comment by GhostShot3** [comment]
Add Clear Chat command.
when running the chat is automatically cleaned.

**Comment by lotfis** [comment]
fix the lagg this shit is unplayabl
it seems andrew is not able to fix this issue so merge whit multiogar

**Comment by LegitSoulja** [comment]
Merge with MultiOgar. That's not even possible, and I promise you that will not happen.

**Comment by lotfis** [comment]
why not its so smooth 0 lag 300bots

**Comment by LegitSoulja** [comment]
c+? You meant c#? Yea, i don't think i'll be doing that. I changed my mind about that a week ago.

**Comment by lotfis** [comment]
well wr f*****ed

**Comment by LegitSoulja** [comment]
@lotfis not really. If andrew can prove the child update can reduce the lag then there shouldn't be no issues. All is left is alot of optimizations and stability. OgarUnlimited can run with a golden eye, but right now no. Hopefully soon though.

**Comment by Megabyte918** [comment]
Heres mine from the previous suggestions issues:
- A powerups gamemode, Like random powerups (like speedboost, invinsibility, etc) spawn randomly throughout the map.
- A config/plugin/gamemode called "Slitherboost" that when enabled, when you left-click your cell speeds up and leaves a trail of w's or pellets behind you (and you decay mass faster too) just like in slither.io when you left click
- a config (or maybe an addon to the SuperMinions plugin?) that when enabled, when you put `</m>` in front of your name if automatically gives you like 3 minions (or however many is specified).
so that way, if somebody joins my server and they want minions they can just do `</m>` and i wont have to give them some in the command prompt every time
- a new command called `install` for missing files, so say your missing /core/Multiverse.js or something, you could just do `install /core/Multiverse.js` or if your missing multiple files, you could just do `install missing` and it would download the specified file(s) from the repo, so people wouldn't have to re download the zip and insert the file(s) manually

**Comment by LegitSoulja** [comment]
if there's any missing files it would be impossible for someone to use commands to install the missing files. They will have to re-download the branch and replace the missing files. Unless there was some sort of backup thing you can run with ogarul to update all the files and make sure they are all there.

**Comment by SharkFinPro** [comment]
you could make a file checker...

**Comment by LegitSoulja** [comment]
or it can be a thing that checks before actually starting the server :/

**Comment by LegitSoulja** [comment]
I think all suggestions, and fixes, and additions shall be placed on hold until andrew releases his PR. We wouldn't want to interfere with anything. Just take note of all bugs, and suggestions and prepare to add, or fix when PR is merged

@Andrews54757 are you there? I haven't heard from you in a while.

**Comment by SharkFinPro** [comment]
ok

**Comment by GetRektAgario** [comment]
A plugin where you can set it to automatically do Killall if the server gets too big, such as if the largest person is over 100K, or if it reaches the end of a timer which is displayed above.

**Comment by LegitSoulja** [comment]
So when a player reaches 100k score, timer will start for killall and server reset?

**Comment by GetRektAgario** [comment]
Yeah like that , but you have a choice between a timer or if the player reaches 100K.

**Comment by GetRektAgario** [comment]
Another one could be that you can set all minions spawn mass different to players mass because if you wanted lets say minions to spawn in at 10 mass with minionstart plugin but you don't want the players to spawn in at 10 mass because otherwise they are not big enough to eat the minions.

**Comment by Tokoagar** [comment]
A config/plugin called MinionBoard It make a board with nuber of minion (And time optional)
Ex: minion [id] [number] [name] [time as minutes] [Board name]
And it can also work with superminion if want it to
Ex: superminion [id] [number] [name] [spawnmass] [speed] [time as minutes] [Board name]
And add a config so that people who don't like it can do the command or in config minionboard off/on if in config file

**Comment by GetRektAgario** [comment]
yeah tokoagar that would be sooo cool

**Comment by LegitSoulja** [comment]
Not possible, not with a leaderboard.

**Comment by PrinceDark9243** [comment]
make Ogar ul Support `agar.io` and `play.ogarul.tk` and other clients TOO!

**Comment by Agarian** [comment]
@LegitSoulja suggestions are open for all.

**Comment by LegitSoulja** [comment]
because idk, waiting for andrew.

**Comment by Tyler3D** [comment]
Popsplit,Linesplit fix. A config for playerstartmass for ips. And superminion spawnmass less than playerstartmass.

**Comment by Tyler3D** [comment]
linesplit,popsplit fixes. A config for playerstartmass for ips only. Team DM gamemode like diep.io. gamemode LV up system like diep.io. And a skin selector like agar,io.

**Comment by GhostShot3** [comment]
@Agarian @LegitSoulja  @Andrews54757 , can add it ?

**Comment by GhostShot3** [comment]
@LegitSoulja @Agarian @Megabyte918 @Andrews54757

**Comment by GhostShot3** [comment]
@Agarian @LegitSoulja @Megabyte918 @Andrews54757 Can add `Clear Chat` command ?

**Comment by LegitSoulja** [comment]
@GhostShot3 No, so stop asking. I told you no new features will be added now!.

**Comment by AgarioIsBest1602** [comment]
close

**Comment by AgarioIsBest1602** [comment]
Plz

**Comment by Agarian** [comment]
then ill do this

**Comment by Agarian** [comment]
and fine it can be locked

**Comment by GhostShot3** [comment]
Mothercell start mass config
Mothercellstartmass = 100

**Comment by Agarian** [comment]
How about a `serverTeamAmount` config?

**Comment by GhostShot3** [comment]
@Agarian Because you're locking/unlocking ?

**Comment by NatsuTheGreat** [comment]
What are you even talking about, @GhostShot3

**Comment by GhostShot3** [comment]
@NatsuTheGreat the Agrarian is locked and unlocked.

**Comment by Agarian** [comment]
I am not `the Agarian`

**Comment by NatsuTheGreat** [comment]
Hahaha

**Comment by GhostShot3** [comment]
@Agarian Fake ?

**Comment by Agarian** [comment]
That `j` is fake:
"j" ORIGINAL
",j" FAKE
lol i wanted to say something

**Comment by WolfOGG** [comment]
There should be a ping kick so if someones ping is too high it auto kicks them so the rest of the people don't lag.

**Comment by LegitSoulja** [comment]
@WolfOGG Then, I would no longer to play nomore. Lol, well I guess it really doesn't matter since I don't really play.

**Comment by Agarian** [comment]
I just had the idea to call the `Timed FFA` gamemode `Rush mode`

**Comment by GhostShot3** [comment]
Nice ideia @Agarian

**Comment by Remiks169** [comment]
I cant do linesplit, can you do command like freeze but with possibility to split?? I like linesplits but i cant do it ;(

**Comment by Megabyte918** [comment]
Linesplits are fixed on my fork

**Comment by Agarian** [comment]
**My suggestions:**
- A `virusStartAmount` config.
- A config that enables or disables freeroam spectate? (Could be `serverFreeroamSpec`) 
If it is disabled, the server would spectate players by the leaderboard. So pressing Q with freeroam spectate disabled would go down the list of players on the leaderboard (As original ogar used to). And obviously, with freeroam spectate enabled, pressing Q will activate/deactivate freeroam spectate.

**Comment by iamyou** [comment]
Can I translate this into Chinese?

**Comment by iamyou** [comment]
troll [id] [mass] [name] [RecombineTime]

**Comment by elitajmx** [comment]
WHY DO SUPERMINION NOT WORK WITH SPAWNMASS WTF

**Comment by LegitSoulja** [comment]
@elitajmx SuperMinions, and MassStart :)

**Comment by NatsuTheGreat** [comment]
@elitajmx Chill the caps.

**Comment by elitajmx** [comment]
i mean like my config has spawnmass set to 44 and now if i try spawning minions like this: superminion 1 10 bot 132   the spawnmass (132) doesn't work, just stays at 44 mass

**Comment by LegitSoulja** [comment]
Usr superminions and MassStart.

Set settings/config.ini playerStartMass = 1
Set plugins/MassStart/config.ini playerStartMass to whatever. (Mainly your player join mass)

Now.. Case closed.

**Comment by elitajmx** [comment]
1 more thing, i put the playerstartmass to 44 in masstart but when i add bots they start with 1 massD:

**Comment by LegitSoulja** [comment]
Then set the mass in settings/config.ini or use super minions

**Comment by elitajmx** [comment]
but if i use in config superminions wont work wiht being 10 mass, can you just tell me how to make food spawn quicker?

**Comment by LegitSoulja** [comment]
You can't make food spawn quicker, but you can increase the food spawn limit, and food set amount

**Comment by elitajmx** [comment]
well if i do that it completely crashes ogarul in 5min


2016-08-17 0:46 GMT+02:00 LegitSoulja <notifications@github.com>:

**Comment by Megabyte918** [comment]
any errors?

**Comment by elitajmx** [comment]
YES, food not spwaning, if i increase it, ogarul crashes

**Comment by Megabyte918** [comment]
I mean the error when it crashes

**Comment by LegitSoulja** [comment]
He probably increase the food too much, that there's a lag spike when food is added.Please provide your food portion of the config just so we know you are doing it correctly.

**Comment by Megabyte918** [comment]
I don't think we'll need these anymore, should this be closed?

**Comment by NatsuTheGreat** [comment]
Not with the rate of the donations as of now.

**Comment by Agarian** [comment]
Whats the rate?

**Comment by NatsuTheGreat** [comment]
7$ and it's been about 4 days.

**Comment by LegitSoulja** [comment]
Client site also has a countdown (days) aswell. The last day the site will go down automatically. I guess. I don't know if it should stay or not. I guess we will just find out later. 

I'll come into GitHub maybe every 2-3 days to check up with what's going on, incase I'll have to remove the plug from the site when the day turns 0.
