### ISSUE TITLE
how i can use PLUGIN CONSOLE OGARUL ?

### ISSUE THREAD

**Issue by inxlio** [AJS-development/Ogar-unlimited#1255]
I'm using PM2 , and need to use the console ogarUL worse not understand how , I can not download it

**Comment by LegitSoulja** [comment]
###### Readme
https://github.com/AJS-development/OgarUL-Plugin-Library/blob/master/OgarConsole-Installer/README.md

###### Installation
> plugin install OgarConsole

go to 
> plugins/OgarConsole/config.ini 

change the password, and port (if needed)

visit: localhost:1000

**Comment by inxlio** [comment]
how to start with PM2 @LegitSoulja  ?

**Comment by LegitSoulja** [comment]
Don't ask me, because I don't know anything about that, nor I wouldn't recommend using it.
