### ISSUE TITLE
how to start OgarConsole using PM2 ?

### ISSUE THREAD

**Issue by inxlio** [AJS-development/Ogar-unlimited#1256]
1 - pm2 start index.js

![image](https://cloud.githubusercontent.com/assets/20158370/16715617/a2cc0358-46bb-11e6-9449-ffbcf6f47fa0.png)

AND AFTER ? HOW TO START OGARCONSOLE

**Comment by LegitSoulja** [comment]
I don't have no clue to what that is, but you would install OgarConsole plugin, then after that you would visit http://localhost:1000

**Comment by fayizan** [comment]
@inxlio tell me your skype id,I will try to fix it

**Comment by GhostShot3** [comment]
@fayizan Help me too statitics too ?

**Comment by fayizan** [comment]
@GhostShot3 same reply like I said above

**Comment by GhostShot3** [comment]
@fayizan Ghostshot3.private

**Comment by LegitSoulja** [comment]
@GhostShot3 Statitics? Or Statistics?

**Comment by inxlio** [comment]
MY SKYPE IS eduardosebastian710@hotmail.com , pls add me and fix it :( thanks

**Comment by LegitSoulja** [comment]
@fayizan is offline atm. He will get to you asap.
