### ISSUE TITLE
How to use ogar console plugin ?

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#1257]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?

What version are you on?

What command did you type if any?

You must have a description as well

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

**Comment by GhostShot3** [comment]
already learned

**Comment by LegitSoulja** [comment]
GhostShot3 enough with these issues. Stop creating issues or else I would have to temporarily disable your issue creating. Hopefully you will learn not to create duplicate of issues over and over again. But this here is just rediculus. 

Just a warning

**Comment by GhostShot3** [comment]
Sorry @LegitSoulja It will not happen anymore.
