### ISSUE TITLE
OgarConsole PLUGIN Error

### ISSUE THREAD

**Issue by inxlio** [AJS-development/Ogar-unlimited#1259]
error  say: first use? installing dependences for ogarConsole and restarts infinitely

**Comment by GhostShot3** [comment]
Run `Ogar-unlimited-master\src\Istall Depedencies (Windows).bat`

**Comment by inxlio** [comment]
error say: first use? installing dependences for ogarConsole and restarts infinitely

**Comment by LegitSoulja** [comment]
@inxlio delete the OgarConsole plugin folder. When it says that wait until OgarConsole dependencies is installed.

@GhostShot3 that was the wrong thing to say. if you would install OgarConsole dependencies you would cd to OgarConsole plugin directory then npm install.

**Comment by GhostShot3** [comment]
@LegitSoulja I got it wrong.

**Comment by inxlio** [comment]
i cant understood

**Comment by inxlio** [comment]
i cant understand @LegitSoulja

**Comment by LegitSoulja** [comment]
well too bad. OgarConsole does a simple installation. You read what it said but you didn't follow the instructions. Delete OgarConsole and let it install it's dependencies then you can do your configuration.
