### ISSUE TITLE
Ogar Console

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#1260]
I type the password, but when I type -help it requires the password again.
It is that way indefinitely.

**Comment by LegitSoulja** [comment]
?

**Comment by GhostShot3** [comment]
@LegitSoulja No only opens the server once I entered the island and asks two password instead,reopen.

**Comment by GhostShot3** [comment]
If you need,I record proving.

**Comment by LegitSoulja** [comment]
Record your proof then. And no I will not re-open this issue. This is my plugin, and I handle the issues.

**Comment by GhostShot3** [comment]
@LegitSoulja So help me how to fix.

**Comment by GhostShot3** [comment]
@At no time this fighting with you.

**Comment by LegitSoulja** [comment]
You said you was going to record proving your issue so that's what im waiting on. Until then I can't help you because this isn't even a issue, nor nobody else is having that issue.

**Comment by GhostShot3** [comment]
@LegitSoulja Ok.
