### ISSUE TITLE
PM2 & OgarConsole

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#1262]
If you are using OgarConsole, whilst using **PM2** please note that OgarConsole cannot be used with full functionalities and potential. Which means, you will not be allowed to use plugin commands, multiverse commands, chat commands, and a few other commands.

If you have an issue with OgarConsole, leave a comment below. Otherwise don't make no issue about how to use OgarConsole. I will not be making anymore OgarConsole update patches/fixes since it has been discontinued. I have kindly re-wrote OgarConsole as a plugin for OgarConsole use so enjoy it.

###### Note:
If you have a huge server, note that when using the command playerlist. The site can stop responding due to a huge packet of data being sent to OgarConsole. OgarConsole is not efficient to be running without an actual OgarUL backend console usage. Please use these OgarConsole commands wisely for better performance.

* clear (Clears the console)
* -r, r (Refreshes the console)
* -release (Re-download public files)
* -cmd (Run cmd commands **NOT OGARUL COMMANDS**)
* -update (Update plugin)

**Comment by mrzack506** [comment]
If I were to load OgarConsole on my pc and do a command, it wouldn't do anything. So forcefully, I have to use my phone for commands.

**Comment by LegitSoulja** [comment]
@mrzack506 

go into
plugins > OgarConsole and delete the **src** folder.

Restart the server and try again.

**Comment by mrzack506** [comment]
@LegitSoulja Thank you very much :)

**Comment by GhostShot3** [comment]
How to run without PM2 ? Please do not swear at me LegitSoulja

**Comment by LegitSoulja** [comment]
I'd never cursed at you. So you're just going to lie on me? You get no respect at all -_-

**Comment by GhostShot3** [comment]
http://prntscr.com/bsmwx8
Just to say that is not a lie but thanks for the help.

**Comment by LegitSoulja** [comment]
I never knew the word **annoying** was a profanity term. If i said it, then its the truth.

**Comment by GhostShot3** [comment]
@LegitSoulja 
offended me

**Comment by GhostShot3** [comment]
@LegitSoulja forgets that.
