### ISSUE TITLE
Cant Open My Servers Ports

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1263]
I have Port forwarded...it was working before (remember @LegitSoulja ?). My server port wouldnt open, so i updated my server and now both ports wont open

**Comment by Agarian** [comment]
your back?

**Comment by SharkFinPro** [comment]
Now server port is still closed, but stats port is open...

**Comment by LegitSoulja** [comment]
@SharkFinPro I really can't determine your issue, nor I don't have a clue to how you are port forwarding. If you are having these types of issues I suggest you to check your firewall and allow those ports to gain access.

**Comment by SharkFinPro** [comment]
my firewall let them through before...

**Comment by LegitSoulja** [comment]
Make sure that the ports are inbound enabled, and not blocked.

**Comment by SharkFinPro** [comment]
its not

**Comment by LegitSoulja** [comment]
What type of router do you have? If you have netgear, I know a lot of my friends have had problems with netgear routers. I never had one, cause I've always had a server router which is a Cisco server router.

It's heavy duty, handle almost about anything :)
