### ISSUE TITLE
I want to make a plugin, should i wait till Andrew releases his update?

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1265]
The title says it all...

**Comment by LegitSoulja** [comment]
What's the plugin?

**Comment by Megabyte918** [comment]
its fine, he isnt doing anything to the plugins

**Comment by LegitSoulja** [comment]
Any plugins that's added I will have to go over it before adding. So you may upload here for me to look over before adding to the library

**Comment by LegitSoulja** [comment]
I'll make it :)

**Comment by LegitSoulja** [comment]
@SharkFinPro 
[ChatMessages.zip](https://github.com/AJS-development/Ogar-unlimited/files/358152/ChatMessages.zip)

Edit it how you like

**Comment by SharkFinPro** [comment]
ok

**Comment by LegitSoulja** [comment]
I left comments to what i've done so you can understand. I think that's exactly how you wanted it. If you have any questions let me know. I have tested it, and i confirm that it does work!.

**Comment by LegitSoulja** [comment]
@SharkFinPro I added new additions

###### configuration
* enabled = enable, and disable message intervals
* joinMessage = enable or disable join messages

###### Json Config
* joinmessage = Join message
* {player} = player name

Fixed join message spam when players join, and fixed some other stuff.
