### ISSUE TITLE
Disappearing Cells is a SERIOUS PROBLEM.

### ISSUE THREAD

**Issue by CubeTiger** [AJS-development/Ogar-unlimited#1266]
I understand that this issue has already been made many times, but it has gotten to the point where I can no longer use OgarUnlimited as a private server. Random cells disappear when rejoining, so thousands of mass can disappear out of nowhere. When split running, I lose 80%-90% mass in less than a minute. After about a minute of use I am down to about 600 mass. 

This happens with the settings right out of the box, and with other settings that I have messed with. I've tried different collision times, split speeds, split types, recombine times, etc. Nothing is working, and OgarUnlimited is unplayable.

Yet again, sorry for repeating an issue, (plz no ban) but I feel this needs some major recognition as the current state of the game is unplayable.

Question: Could this have been a result of the attempts to reduce lag???

**Comment by CubeTiger** [comment]
Question - Could this have been a result of the attempts to reduce lag???

**Comment by Agarian** [comment]
It is.

**Comment by Agarian** [comment]
i'm thinking of using multiogar instead at this point, but then again, this is the only project i've really been contributing to.

**Comment by David1ali12** [comment]
Use mulitogar

**Comment by Megabyte918** [comment]
I think I know what might be causing the dissapearing cells bug #1124, i will revert this but it might inrease lag a small bit, but at least its better than having your cells dissapear :/

**Comment by Agarian** [comment]
Idk, i can't test ATM

**Comment by Megabyte918** [comment]
Yep, it does :)

**Comment by Megabyte918** [comment]
I'll commit this on my fork and ill PR it once Andrew gets back
