### ISSUE TITLE
Running Ogario on VPS in background

### ISSUE THREAD

**Issue by dokicro** [AJS-development/Ogar-unlimited#1267]
Hi, 
I have successfully made my ogario server working :)
For process manager I use http://pm2.keymetrics.io/ and everything working in background, but the problem is I cant open console again to enter commands?

Do I need to change process manager or I am missing something?

**Comment by dokicro** [comment]
I found solution:
https://github.com/AJS-development/Ogar-unlimited/issues/1255

**Comment by LegitSoulja** [comment]
Don't use pm2 it's pointless and stupid, and there whole pm2 description lies!. 

pm2 does not run multi-core, pm2 does not reduce lag, PayPal doesn't even use pm2 which they also lied about. pm2 just stupid period. Just wait for ogarul child update.
