### ISSUE TITLE
2 Error in console

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#1270]
Error 1 : http://prntscr.com/bs2d93
Error 2  
[Statistics] OCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-sc
ale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; font-family: Helvetica, Arial, sans-serif;
font-size: 100%;}
    h1 {font-size: 1.5em; color: #404040; text-align: center;}
    p {font-size: 1em; color: #404040; text-align: center; margin: 10px 0 0 0;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 20px;}
    @-webkit-keyframes bubbles { 33%: { -webkit-transform: translateY(10px); tra
nsform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transfor
m: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: tran
slateY(0); } }
    @keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform:
translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: trans
lateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0
); } }
    .bubbles { background-color: #404040; width:15px; height: 15px; margin:2px;
border-radius:100%; -webkit-animation:bubbles 0.6s 0.07s infinite ease-in-out; a
nimation:bubbles 0.6s 0.07s infinite ease-in-out; -webkit-animation-fill-mode:bo
th; animation-fill-mode:both; display:inline-block; }
  </style>

    <script type="text/javascript">
  //<![CDATA[
  (function(){
    var a = function() {try{return !!window.addEventListener} catch(e) {return !
1} },
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c
) : document.attachEvent("onreadystatechange", b)};
    b(function(){
      var a = document.getElementById('cf-content');a.style.display = 'block';
      setTimeout(function(){
        var s,t,o,p,b,r,e,a,k,i,n,g,f, NrXGHWS={"MtILZQKkarFa":+((!+[]+!![]+!![]
+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]))};
        t = document.createElement('div');
        t.innerHTML="<a href='/'>x</a>";
        t = t.firstChild.href;r = t.match(/https?:\/\//)[0];
        t = t.substr(r.length); t = t.substr(0,t.length-1);
        a = document.getElementById('jschl-answer');
        f = document.getElementById('challenge-form');
        ;NrXGHWS.MtILZQKkarFa*=!+[]+!![]+!![]+!![]+!![]+!![];NrXGHWS.MtILZQKkarF
a+=+((!+[]+!![]+!![]+[])+(+!![]));NrXGHWS.MtILZQKkarFa+=+((+!![]+[])+(!+[]+!![]+
!![]));a.value = parseInt(NrXGHWS.MtILZQKkarFa, 10) + t.length; '; 121'
        f.submit();
      }, 4000);
    }, false);
  })();
  //]]>
</script>

</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript><h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn J
avaScript on and reload the page.</h1></noscript>
  <div id="cf-content" style="display:none">
    <div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before acc
essing</span> ogarul.tk.</h1>
    <p data-translate="process_is_automatic">This process is automatic. Your bro
wser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>
  </div>
  <form id="challenge-form" action="/cdn-cgi/l/chk_jschl" method="get">
    <input type="hidden" name="jschl_vc" value="d789f99c12a27f4fd853d9cb6085d1a1
"/>
    <input type="hidden" name="pass" value="1468348794.904-RXoHzXqo2J"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
</div>

          <div class="attribution">
            <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=iua
m" target="_blank" style="font-size: 12px;">DDoS protection by CloudFlare</a>
            <br>
            Ray ID: 2c169ec721254ca8
          </div>
      </td>
    </tr>
  </table>
</body>
</html>

[Statistics] OCTYPE HTML>
<html lang="en-US">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
  <meta name="robots" content="noindex, nofollow" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-sc
ale=1" />
  <title>Just a moment...</title>
  <style type="text/css">
    html, body {width: 100%; height: 100%; margin: 0; padding: 0;}
    body {background-color: #ffffff; font-family: Helvetica, Arial, sans-serif;
font-size: 100%;}
    h1 {font-size: 1.5em; color: #404040; text-align: center;}
    p {font-size: 1em; color: #404040; text-align: center; margin: 10px 0 0 0;}
    #spinner {margin: 0 auto 30px auto; display: block;}
    .attribution {margin-top: 20px;}
    @-webkit-keyframes bubbles { 33%: { -webkit-transform: translateY(10px); tra
nsform: translateY(10px); } 66% { -webkit-transform: translateY(-10px); transfor
m: translateY(-10px); } 100% { -webkit-transform: translateY(0); transform: tran
slateY(0); } }
    @keyframes bubbles { 33%: { -webkit-transform: translateY(10px); transform:
translateY(10px); } 66% { -webkit-transform: translateY(-10px); transform: trans
lateY(-10px); } 100% { -webkit-transform: translateY(0); transform: translateY(0
); } }
    .bubbles { background-color: #404040; width:15px; height: 15px; margin:2px;
border-radius:100%; -webkit-animation:bubbles 0.6s 0.07s infinite ease-in-out; a
nimation:bubbles 0.6s 0.07s infinite ease-in-out; -webkit-animation-fill-mode:bo
th; animation-fill-mode:both; display:inline-block; }
  </style>

    <script type="text/javascript">
  //<![CDATA[
  (function(){
    var a = function() {try{return !!window.addEventListener} catch(e) {return !
1} },
    b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c
) : document.attachEvent("onreadystatechange", b)};
    b(function(){
      var a = document.getElementById('cf-content');a.style.display = 'block';
      setTimeout(function(){
        var s,t,o,p,b,r,e,a,k,i,n,g,f, ZuRUeCE={"jldSc":+((!+[]+!![]+!![]+!![]+[
])+(!+[]+!![]))};
        t = document.createElement('div');
        t.innerHTML="<a href='/'>x</a>";
        t = t.firstChild.href;r = t.match(/https?:\/\//)[0];
        t = t.substr(r.length); t = t.substr(0,t.length-1);
        a = document.getElementById('jschl-answer');
        f = document.getElementById('challenge-form');
        ;ZuRUeCE.jldSc*=+((!+[]+!![]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![
]+!![]+!![]));ZuRUeCE.jldSc-=+((!+[]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![
]));ZuRUeCE.jldSc-=!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![];ZuRUeCE.jldSc*=+((!+[
]+!![]+!![]+[])+(!+[]+!![]+!![]+!![]+!![]+!![]+!![]+!![]));a.value = parseInt(Zu
RUeCE.jldSc, 10) + t.length; '; 121'
        f.submit();
      }, 4000);
    }, false);
  })();
  //]]>
</script>

</head>
<body>
  <table width="100%" height="100%" cellpadding="20">
    <tr>
      <td align="center" valign="middle">
          <div class="cf-browser-verification cf-im-under-attack">
  <noscript><h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn J
avaScript on and reload the page.</h1></noscript>
  <div id="cf-content" style="display:none">
    <div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
      <div class="bubbles"></div>
    </div>
    <h1><span data-translate="checking_browser">Checking your browser before acc
essing</span> ogarul.tk.</h1>
    <p data-translate="process_is_automatic">This process is automatic. Your bro
wser will redirect to your requested content shortly.</p>
    <p data-translate="allow_5_secs">Please allow up to 5 seconds&hellip;</p>
  </div>
  <form id="challenge-form" action="/cdn-cgi/l/chk_jschl" method="get">
    <input type="hidden" name="jschl_vc" value="ccb5b7498333907b762a2391753cc327
"/>
    <input type="hidden" name="pass" value="1468348854.699-461C8gHKW9"/>
    <input type="hidden" id="jschl-answer" name="jschl_answer"/>
  </form>
</div>

          <div class="attribution">
            <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=iua
m" target="_blank" style="font-size: 12px;">DDoS protection by CloudFlare</a>
            <br>
            Ray ID: 2c16a03cdb6b4b09
          </div>
      </td>
    </tr>
  </table>
</body>
</html>

**Comment by LegitSoulja** [comment]
Statistics is shut down, and won't be back up for a while.

**Comment by GhostShot3** [comment]
@LegitSoulja 
Because ?

**Comment by LegitSoulja** [comment]
Don't worry why. It's not important for you to know.

**Comment by Agarian** [comment]
@LegitSoulja play.ogarul.tk is aswell

**Comment by GhostShot3** [comment]
@LegitSoulja Okay, will be how long? just tell me this please.

**Comment by LegitSoulja** [comment]
@GhostShot3 Everything is running smoother than before.

**Comment by GhostShot3** [comment]
@LegitSoulja Its coll
