### ISSUE TITLE
PLay.ogarul.tk is down?

### ISSUE THREAD

**Issue by Tokoagar** [AJS-development/Ogar-unlimited#1272]
What happend to play.ogarul.tk I can't connect

Error:

Ce site est inaccessible

Impossible de trouver l'adresse DNS du serveur play.ogarul.tk.
Effectuez une recherche Google sur play ogarul tk.

**Comment by Tokoagar** [comment]
Oh wait I had my google french 
This site is inaccessible

Can not find the DNS server address play.ogarul.tk .
Do a Google search on play ogarul tk .

**Comment by HugoMSantos** [comment]
@Tokoagar 
Thats happening to me, not only for you.

**Comment by Tokoagar** [comment]
ok I don't know how to play

**Comment by HugoMSantos** [comment]
Me to, what about to wait? :/

**Comment by Tokoagar** [comment]
the error

**Comment by Tokoagar** [comment]
Did they take down the site?

**Comment by HugoMSantos** [comment]
@Tokoagar 
I don't know anything about it, I'm not gonna complain about that.
Btw for me it just says "Connecting through the server" (*something like that*)

**Comment by Tokoagar** [comment]
ok

**Comment by Tokoagar** [comment]
http://ajs-development.github.io/client/ here You can use it it work's fine

**Comment by MizovoGames123** [comment]
yea the client is down for some reason

**Comment by SharkFinPro** [comment]
client is open again

**Comment by Tokoagar** [comment]
ok thanks for letting me know

**Comment by HugoMSantos** [comment]
@SharkFinPro 
What? Its down, again.

**Comment by Agarian** [comment]
It's still down. @LegitSoulja you took it down? Can you run it through http://ajs-development.github.io/client/ if you can't bring it back?

**Comment by Tokoagar** [comment]
why is he doing this he was supose to do this only on statisctic plugin I don't understand

**Comment by LegitSoulja** [comment]
I've been applying security and fixes. I had a php outage, due to that, I have to re-write a few of my code to prevent this from happening, due to alot of traffic.

Everything should be running fine now.

**Comment by LegitSoulja** [comment]
@Tokoagar I was planning on removing statistics completely, but I will give it another chance. I will see how it goes performance wise.

**Comment by Tokoagar** [comment]
ok
