### ISSUE TITLE
Info on play.ogarul.tk

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#1273]
The client appears to be down, so until it is back up, we'll need to stick with 
http://ajs-development.github.io/client/

**Comment by SharkFinPro** [comment]
its open again...
if it doesnt work, refresh

**Comment by Agarian** [comment]
skinlist is down

**Comment by SharkFinPro** [comment]
@Agarian Go to discord

**Comment by Agarian** [comment]
uhh Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Additionally, a 503 Service Unavailable error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by Agarian** [comment]
its back

**Comment by Hunter2890** [comment]
@Agarian i had a problem that was never fixed...
 module.js:341
    throw err;
    ^

Error: Cannot find module 'collections/fast-map'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Gavin\Downloads\Ogar-unlimited-master\Ogar-u
nlimited-master\src\core\WorldModel.js:20:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

Press any key to exit...
I have no ides what i have to do to fix it please help

**Comment by Agarian** [comment]
you may need to do ``npm install collections``

**Comment by LegitSoulja** [comment]
Site is back up and running. Skin list was down for security reasons, so was statistics whilst I was doing development.

**Comment by Agarian** [comment]
the site still is down

**Comment by LegitSoulja** [comment]
*sigh*.. These errors are pissing me off.

**Comment by Hunter2890** [comment]
@Agarian as you can see if i press any key it will close it...

**Comment by HugoMSantos** [comment]
@Hunter2890 
do `npm install collections` , not inside the install dependencies (windows)

**Comment by Hunter2890** [comment]
@HugoMSantos where is it?

**Comment by Agarian** [comment]
why is this issue listed as reported in my profile?
