### ISSUE TITLE
Bug when i have 2 different servers

### ISSUE THREAD

**Issue by inxlio** [AJS-development/Ogar-unlimited#1275]
When you have 2 server created by multiverse commands and with different mass sizes , the player can´t eat the mass of second server

**Comment by liomessip** [comment]
same problem

**Comment by Megabyte918** [comment]
what do you mean by "the player can't eat the mass of the second server"

**Comment by NatsuTheGreat** [comment]
He means the players can't eat food etc on the second server.

**Comment by liomessip** [comment]
plis i have same error , fix this

**Comment by Agarian** [comment]
Same issue, idk why

**Comment by liomessip** [comment]
please fix

**Comment by Andrews54757** [comment]
I dont understand what he means by this

**Comment by Megabyte918** [comment]
so, if i was to do this then if i went on the second server and instead of being able to eat the food i would just go over it? what?

**Comment by Megabyte918** [comment]
this will be closed if not explained.

**Comment by Megabyte918** [comment]
so if i was to do this then if i went on the second server and instead of being able to eat the food i would just go over it? what? and what do you mean by "different mass sizes?"

**Comment by Megabyte918** [comment]
Im going to close this if its not explained, its been open for a while :/
