### ISSUE TITLE
[BUG] Top Left

### ISSUE THREAD

**Issue by AgarioIsBest1602** [AJS-development/Ogar-unlimited#1276]
Always if i play with playerbots i make them big, so i try to kill him. But always if a playerbot is big it comes to top left corner. I guess this is a bug.

**Comment by Megabyte918** [comment]
How did you produce this? Ive been playing on my freshly downloaded version and Ive never seen this happen once

**Comment by NatsuTheGreat** [comment]
He probably isn't playing on a fresh version then.

**Comment by tommyb008** [comment]
im having it to!

**Comment by Agarian** [comment]
Actually i've seen this happen a few times, usually because of a lack of food pellets.

**Comment by AgarioIsBest1602** [comment]
I dont download everytime again i just change the version.

**Comment by LegitSoulja** [comment]
@Agarian , remember that day when things glitches out, and a few people died, and a lot of bots and minions got stuck top left corner? Yea, whatever causes that, fixes this problem. 

Which yea, I was thinking the same thing about lack of food, but just to think about it, shouldn't things go back to normal when there is?

**Comment by Megabyte918** [comment]
wut

**Comment by Megabyte918** [comment]
Ohh, i get what you're saying now this has happened to me a few times

**Comment by Agarian** [comment]
You have time for discord @Megabyte918?

**Comment by Megabyte918** [comment]
Yeah man

**Comment by Megabyte918** [comment]
I think I have fixed this on my fork, It will be merged once i am finished with physics.
