### ISSUE TITLE
IDEA: Make a gamemode list command

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1277]
This would be nice so you can easily tell what gamemodes are what numbers

**Comment by Agarian** [comment]
i did that on my server

**Comment by Agarian** [comment]
i'll make a PR

**Comment by Agarian** [comment]
i was actually thinking of adding it to the `gamemode` command:
`gamemode list`

**Comment by SharkFinPro** [comment]
thats what was thinking too
