### ISSUE TITLE
IDEA: 1v1 Gamemode

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1278]
I dont need to explain the title....

**Comment by GhostShot3** [comment]
@SharkFinPro Nice idea.

**Comment by Agarian** [comment]
that can already be done, Hunger games.
All you need to do is change `serverGamemode` in `config.ini` to 11
Then change `tourneyMaxPlayers` in `config.ini` to 2

**Comment by SharkFinPro** [comment]
but what if you wanted to have a hunger games sometimes, and 1v1 others...

**Comment by Megabyte918** [comment]
isn't there already a PvP gamemode?

**Comment by NatsuTheGreat** [comment]
PvP is legit FFA. you can look through ```src/gamemodes``` and find which ever gamemode you'd like.
