### ISSUE TITLE
Can't Move!!!!!

### ISSUE THREAD

**Issue by WolfOGG** [AJS-development/Ogar-unlimited#1280]
When I spawn it sends me straight to the top left corner

**Comment by tommyb008** [comment]
Same any fix

**Comment by LegitSoulja** [comment]
I'm doing some client fixes, this will be resolved shortly once I figure out the cause.

**Comment by WolfOGG** [comment]
ok thanks

**Comment by tommyb008** [comment]
kk thanks

**Comment by tommyb008** [comment]
cuz evry 1 in my server has that so thanks!

**Comment by WolfOGG** [comment]
you have a server?

**Comment by LegitSoulja** [comment]
Issue has been fixed
