### ISSUE TITLE
por qué no puedo entrar al juego ogarul.tk? no me cargan los servidores.

### ISSUE THREAD

**Issue by Crystalxxx1996** [AJS-development/Ogar-unlimited#1282]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?

What version are you on?

What command did you type if any?

You must have a description as well

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

**Comment by Agarian** [comment]
¿Qué quieres decir? Es la lista de servidores no se muestra ?

**Comment by Agarian** [comment]
Tenga en cuenta que hay un botón debajo de "Play" que dice "Fetch servers (Online)"

**Comment by LegitSoulja** [comment]
si está utilizando un dispositivo móvil , que no funciona

**Comment by mafiakb** [comment]
De seguro has puesto mal los puertos

**Comment by LegitSoulja** [comment]
It can't be bad ports, if he is joining a server from the server list, unless it's his own server..


advierta que HSVE para conectarse a través 127.0.0.1 localhost y , o , no su IP le das a los amigos

**Comment by Crystalxxx1996** [comment]
le doy click a "Fetch the servers" y no carga ningun servidor ### ****

**Comment by LegitSoulja** [comment]
está usando un teléfono móvil ?

**Comment by Crystalxxx1996** [comment]
@LegitSoulja No...

**Comment by Agarian** [comment]
una vez que se hace clic "Fetch servers" debería haber una lista de servidores, haga clic en un servidor y debe conectarse a él .

**Comment by PrinceDark9243** [comment]
I dont understand

**Comment by Tokoagar** [comment]
xD

**Comment by Agarian** [comment]
Well thats not my problem.

**Comment by PrinceDark9243** [comment]
lol
