### ISSUE TITLE
How to LineSplit?

### ISSUE THREAD

**Issue by zKurama** [AJS-development/Ogar-unlimited#1283]
When I do LineSplit, not divided erect it gets bent and goes wrong

**Comment by Agarian** [comment]
We know this, but do not know why it happens. If you want to linesplit, use https://github.com/AJS-development/Ogar-unlimited-noclient/ and connect through the Agar.io client.

**Comment by zKurama** [comment]
Sorry, I do not understand. You have to download this Client and enter the agar.io ??

**Comment by Agarian** [comment]
No, download https://github.com/AJS-development/Ogar-unlimited-noclient/
Then connect with http://agar.io/?ip=127.0.0.1:`port`

**Comment by LegitSoulja** [comment]
I wonder if its the vector's using with the client that we have?

Whoever wrote it, did a bad job.

**Comment by Megabyte918** [comment]
I think the code for the angles of splits might be in the `getAngleFromTo` function in Physics.js or these lines: 
<pre>let angle = Physics.getAngleFromTo(player.mouse, cell.position);
if (angle == 0) angle = Math.PI / 2;
......
if (angle == 0) angle = Math.PI / 2;</pre>
or these variables in PlayerCell.js under `calcMove`
<pre>var deltaY = y2 - this.position.y;
var deltaX = x2 - this.position.x;
var angle = Math.atan2(deltaX, deltaY);</pre>

I could be wrong, I'm not very good with angles but I'll see what I can do, if its not anything I describes above then its definitely client-sided

**Comment by NatsuTheGreat** [comment]
It isn't client sided :)

**Comment by LegitSoulja** [comment]
We need to fix this. I know it's not client sided but everyonr says it is. I couldn't even find no type of splitting, nor angles on client.

**Comment by ItzLevvie** [comment]
```I wonder if its the vector's using with the client that we have?

Whoever wrote it, did a bad job.```

That Vector.js controls the mobile's movement

**Comment by LegitSoulja** [comment]
oh okay, just making sure.

**Comment by NatsuTheGreat** [comment]
It's never going to be client sided because split physics are server-side. The client isn't going to give you default physics, especially where the entities are going to written differently.

**Comment by Megabyte918** [comment]
fixed on my fork

**Comment by Agarian** [comment]
really?? omg

**Comment by Agarian** [comment]
IT WORKSS

**Comment by Agarian** [comment]
NICE, also i made spectate **much more** accurate :D

**Comment by Megabyte918** [comment]
sweet, you should pr it :)

**Comment by Agarian** [comment]
i will but i gotta test it for bugs, the last version had this weird annoying canvas bug, idk why.

**Comment by Agarian** [comment]
And BTW this is the country of Sealand:
http://ichef.bbci.co.uk/wwfeatures/wm/live/624_351/images/live/p0/2p/4x/p02p4xn1.jpg
