### ISSUE TITLE
You know the original branch is outdated

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#1284]
remember this? https://github.com/AJS-development/Ogar-unlimited/tree/Original
it doesn't allow connections through any other client besides agar.io, but it is incompatible with agar.io.

**Comment by LegitSoulja** [comment]
You just now figured that out? I'll update the packets, and nodes.

Actually, i will fork the original branch to LProject, and update the packet and nodes to the current, to work with the client ogarul.tk, and a no client branch.

Tomorrow after I get off of work.

**Comment by Agarian** [comment]
Actually i knew for a while

**Comment by LegitSoulja** [comment]
Should I make the old version compatible with agar.io? or ogarul.tk?

**Comment by Agarian** [comment]
just ogarul.tk lol its probably easier

**Comment by AgarioIsBest1602** [comment]
No plz do agar.io agar.io client is much better

**Comment by Agarian** [comment]
:|

**Comment by LegitSoulja** [comment]
both are easy ... You decide.

**Comment by SharkFinPro** [comment]
agar.io =)

**Comment by raphyjb** [comment]
agar.io :dancer:

**Comment by Agarian** [comment]
Both

**Comment by LegitSoulja** [comment]
I'll fix it for ogarul first, because I don't too much play on agar.io. That'll be the last.

**Comment by Agarian** [comment]
Closing
