### ISSUE TITLE
the website(play,ogarul.tk) isnt work for me 

### ISSUE THREAD

**Issue by Souf123** [AJS-development/Ogar-unlimited#1286]
**Resource Limit Is Reached

The website is temporarily unable to service your request as it exceeded resource limit. Please try again later.**

**Comment by SharkFinPro** [comment]
:|
please...Dont make an issue on this :( this just means that the server is at its max capacity. You can try refreshing a few times and it should work.

Close This Issue Now Please

**Comment by Souf123** [comment]
:o

**Comment by LegitSoulja** [comment]
@SharkFinPro It's scripts that's running on the site. I own more than 1 site, and this, plus all my other sites I own this happens. I'll have to increase the capacity limit which i haven't yet

**Comment by LegitSoulja** [comment]
And, its mainly that counter I made for the site, which is causing overage, thanks for letting me know. I was trying to figure out myself but it didnt go up for me, but now since that you reported this I know now, so things.

**Comment by HugoMSantos** [comment]
@LegitSoulja 
Is it Online again?

**Comment by LegitSoulja** [comment]
it will be up in 10 seconds.

**Comment by LegitSoulja** [comment]
right after I updated php to 5.6 (latest) this stuff happened. Maybe i should downgrade it again :/.

I was using php new features but eh, ill revert.

**Comment by LegitSoulja** [comment]
@HugoMSantos ok everything is good now, :/
