### ISSUE TITLE
Please add new "Summer skins" 

### ISSUE THREAD

**Issue by liomessip** [AJS-development/Ogar-unlimited#1287]
the skins at 16/07/16 please add

**Comment by LegitSoulja** [comment]
No agar.io skins will be added to play.ogarul.tk. You can add your custom skins to your custom file for your private server.

**Comment by HugoMSantos** [comment]
@LegitSoulja 
How?

**Comment by Tokoagar** [comment]
agario-skins.org

**Comment by Tokoagar** [comment]
here are the skins add it to your custumskin list

sunbath :http://agario-skins.org/images/skins/custom/sunbath.png?v0.10.5
diver :http://agario-skins.org/images/skins/custom/diver.png?v0.10.5
surfer :http://agario-skins.org/images/skins/custom/surfer.png?v0.10.5
starfish :http://agario-skins.org/images/skins/custom/star-fish.png?v0.10.5

**Comment by LegitSoulja** [comment]
You add them to your server A.K.A custom skins, but this will not be added into site.
