### ISSUE TITLE
Please Ban This IP from ogarul.tk

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1288]
60.234.124.71
he has been really annoying on my server...being rude, spamming and all sorts

**Comment by LegitSoulja** [comment]
Ok,

There also been fake console players joining players asking people to donate to them for bots. If you ever happen to catch one of these people on your server please let me know, and provide evidence. Thanks

**Comment by SharkFinPro** [comment]
ok
