### ISSUE TITLE
[BUG] Normal BG with Dark BG + No Grid!

### ISSUE THREAD

**Issue by HugoMSantos** [AJS-development/Ogar-unlimited#1294]
As you can see the tittle already say it.
I was on the **latest ogario version** and in the configurations of the server I enable Dark Theme + Hide Grid and the result wasnt normal. 
The Background turned into white.

**Comment by GhostShot3** [comment]
Yes its a bug with client

**Comment by LegitSoulja** [comment]
It's not a big with the client, I think Andrew did it that way, lazyness I guess. I'll try to fix it.

**Comment by GhostShot3** [comment]
@LegitSoulja Ah,its ok

**Comment by HugoMSantos** [comment]
@LegitSoulja 
Thank you. Let us know when its fix!
