### ISSUE TITLE
Looking For Devs

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1295]
**CURRENT PROJECT:** https://github.com/SharkFinProductions/diepio

Im Trying To Create A dev team. Right Now @Agarian is also in it.
you have to have some knowledge in coding.

**Comment by LegitSoulja** [comment]
I would, but i don't know much about pjs. And by the way,  what I seen about you, you are just getting people to do all the work for you. The past few days, i have not seen no other progress, other than what agarian did.

**Comment by SharkFinPro** [comment]
i wus gone away from the computer for a bit last weekend...
ive contributed most to the project, and i am working on it right now...

**Comment by Agarian** [comment]
@LegitSoulja i mainly modeled some tanks, and me and him added some bullet functions for each tank, but they turned bust =/

**Comment by Agarian** [comment]
And for the record, i actually want a diep.io private server.

**Comment by Agarian** [comment]
And i mean this sunday, as in 7/17/16

**Comment by NatsuTheGreat** [comment]
I like agar.io better :blush:

**Comment by SharkFinPro** [comment]
BTW @Agarian Ur In Charge While I'm Gone

**Comment by Agarian** [comment]
Oh screw it i give up on this project -_-

**Comment by NatsuTheGreat** [comment]
RIP

**Comment by LegitSoulja** [comment]
RIP

**Comment by Agarian** [comment]
Yeah. rip

**Comment by firelightning13** [comment]
well RIP

**Comment by Megabyte918** [comment]
ripe

**Comment by SharkFinPro** [comment]
alive

**Comment by LegitSoulja** [comment]
Alive alone it looks like.

**Comment by NatsuTheGreat** [comment]
yep XD
