### ISSUE TITLE
/rcon [pass] myid

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1296]
This would be a good command for admins that can't see the console...

**Comment by GetRektAgario** [comment]
Yes that would be really useful or a way to see peoples id by there name

**Comment by SharkFinPro** [comment]
and @developers Where is the rcon command? is there any way to create custom commands that can be sent as a pm or a server broadcast?

**Comment by GhostShot3** [comment]
how many milliseconds have in a tick?

**Comment by LegitSoulja** [comment]
@GhostShot3 lol. What type of question is that? If it's anything more than 1 that wouldn't be considered a game tick, that will be slow.

@SharkFinPro I'll take a look at rcon, and add some new features.

**Comment by LegitSoulja** [comment]
I can't even get chat pm working...

@Andrews54757 please fix.

**Comment by LegitSoulja** [comment]
@Agarian Um... What you think I didn't know? I guess I'm a noob to you like everyone else.  It don't work. And plus, there's so many things in the ph that needs to be fixed, even chat. Chat commands has no security, that's why most of the time you get those packet error. That's cause when people be trying to execute chat commands "/"

But like I said, chat pm does not work. Console service won't execute, nor gameServer pm. I've tried many things, but looks like all this needs a fix.

**Comment by Agarian** [comment]
I was talking  to SharkFinPro

**Comment by Agarian** [comment]
He was the very first person to introduce smooth splitting into the game.

**Comment by Megabyte918** [comment]
yep

**Comment by firelightning13** [comment]
Yeah I know retslac. But didn't see him for awhile

**Comment by retslac** [comment]
Did i hear my name drop? :smiley:

**Comment by Megabyte918** [comment]
YOOOO retslac waddup man long time no see

**Comment by Agarian** [comment]
YOUR ALIVE!!!

**Comment by Agarian** [comment]
Where ya been this whole time?

**Comment by Megabyte918** [comment]
lol

**Comment by retslac** [comment]
I've been busy real live.
And in my spare time been working a little bit on a custom modded agario client + server.

**Comment by Megabyte918** [comment]
@Agarian @retslac are either of you available? I need some help with a few things

**Comment by retslac** [comment]
@Megabyte918 sry mate, have some other stuff to do before i leave on holiday tomorrow.  Be back in August.

**Comment by NatsuTheGreat** [comment]
@retslac Hope to see you back soon :)

**Comment by LegitSoulja** [comment]
@NatsuTheGreat i have something to ask you quick, before I like have no other time to ask.

**Comment by NatsuTheGreat** [comment]
@LegitSoulja I think Mega already told me about it. I legit couldn't find the problem.

**Comment by LegitSoulja** [comment]
:/. I just don't understand why it's not working the way it supposed to be working. Main reason why I really don't like nodejs.

But, I'll be back this weekend. Adios amigos.

**Comment by NatsuTheGreat** [comment]
See ya!
