### ISSUE TITLE
Here are the new skins of the agar client

### ISSUE THREAD

**Issue by Tokoagar** [AJS-development/Ogar-unlimited#1297]
here are the skins add it to your custumskin list

sunbath :http://agario-skins.org/images/skins/custom/sunbath.png
diver :http://agario-skins.org/images/skins/custom/diver.png
surfer :http://agario-skins.org/images/skins/custom/surfer.png
starfish :http://agario-skins.org/images/skins/custom/star-fish.png

:)

**Comment by LegitSoulja** [comment]
Thanks @Megabyte918

> The reason why this is closed is because we aren't accepting miniclip skins, plus we have over 200 skins. If there was ever new skins added, it will be done cool ones that's made.

I don't even think I'll even try to make skins, because someone just going to end up stealing them, and it will be pointless to add watermarks and or imagery copyrights.

**Comment by Tokoagar** [comment]
ok
