### ISSUE TITLE
fix for cells collision/cell squeezing...

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#13]
if you did notice, the cells collision it's self it strange and the squeezing is the same. splitting is fine tho. (thanks btw) i give a fix to collision/squeezing issue. 
**replace collision check in playerCell.js**

    // Collision check for other cells
    for (var i = 0; i < this.owner.cells.length; i++) {
        var cell = this.owner.cells[i];

        if ((this.nodeId == cell.nodeId) || (this.ignoreCollision) || (cell.ignoreCollision)) {
            // Don't collide with cell that has ignoreCollision on, when I have ignoreCollision on, or with yourself
            continue;
        }

        if ((cell.recombineTicks > 0) || (this.recombineTicks > 0)) {
            // Cannot recombine - Collision with your own cells
            var collisionDist = cell.getSize() + r; // Minimum distance between the 2 cells
            dist = this.getDist(x1, y1, cell.position.x, cell.position.y); // Distance between these two cells
			if (!this.simpleCollide(x1,y1,cell,collisionDist)) {
                // Skip
                continue;
            }

            // Calculations
            if (dist < collisionDist) { // Collided
                // The moving cell pushes the colliding cell
                // Strength however depends on cell1 speed divided by cell2 speed
                var c1Speed = this.getSpeed();
                var c2Speed = cell.getSpeed();
                var mult = 0.9 // Limit from 0.5 to 2, not to have bugs

                var newDeltaY = y1 - cell.position.y;
                var newDeltaX = x1 - cell.position.x;

                var newAngle = Math.atan2(newDeltaX, newDeltaY);

                var move = (collisionDist - dist) * mult;

                x1 = x1 + (move * Math.sin(newAngle)) >> 0;
                y1 = y1 + (move * Math.cos(newAngle)) >> 0;
            }
        }
    }

**Comment by Andrews54757** [comment]
I will look at it

**Comment by Andrews54757** [comment]
Change Reviewed and Accepted (I fixed it)

**Comment by Agarian** [comment]
kk
