### ISSUE TITLE
Making Private Servers Public?

### ISSUE THREAD

**Issue by hlevine9** [AJS-development/Ogar-unlimited#1300]
I don't know how to make my server public, and tried port forwarding 1 billion times (exaggeration), but my friends have never been able to join, so I resorted to hamachi, sadly not knowing how to install it on Mac. Please help!

**Comment by SharkFinPro** [comment]
:|
check if your ports are open

**Comment by SharkFinPro** [comment]
did you install the Statistics Plugin And Edit Your Server's Name?

**Comment by LegitSoulja** [comment]
You can't use hamachi, and ogarul doesnt support hamachi. You need to open your server port. Then you give your friends your ip. Search google for your ip or go to http://ipchicken.com

your friend will join from that ip with your server port. For example

0.0.0.0:443, replace 0.0.0.0 with the ip you get online.

Some routers, you can't port forward. You need to search google how to port forward based on the router you have.

@SharkFinPro I don't think he meant statistics.
