### ISSUE TITLE
Mising file

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#1307]
Sorry for the duplicate,i had the same error,I'm not getting fix anymore.
Error : Mising file `highscores.txt`
![kjjkjl](https://cloud.githubusercontent.com/assets/18537420/16902286/58d31fb8-4c31-11e6-94fb-731fcf37ea6f.png)

**Comment by LegitSoulja** [comment]
I have already told you.. If you are using the high score feature you need to enable logging in your configurations. This was disabled a while ago to decrease lag for things that wasn't being used.

**Comment by GhostShot3** [comment]
Where ? Advconfig or config ?

**Comment by Megabyte918** [comment]
config.ini

**Comment by GhostShot3** [comment]
@Megabyte918 Line ?

**Comment by LegitSoulja** [comment]
* serverLogLevel = 1 (config.ini)
* highscore = 1 (config.ini)

**Comment by GhostShot3** [comment]
@LegitSoulja Thx <3

**Comment by LegitSoulja** [comment]
Then make a txt file.

**Comment by GhostShot3** [comment]
`highscores.txt` ?
