### ISSUE TITLE
Quick Question...

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#1308]
So I recently found a way for perfect popsplits to work as in vanilla, It's by changing the first mult in Virus.js under the `onConsume` function to "2" instead of "3.33" 
<pre>
        if (m > 466) { // Threshold
          // While can split into an even smaller cell (1000 => 500, 250, etc)
          var mult = 3.33; //here
          while (m / mult > 24) {
            m /= mult;
            mult = 2;
            bigSplits.push(m >> 0);
            i++;
          }
        }
</pre>
The only problem with doing so, however, is that it makes the regular virus explosions look kindof weird :/ If you were to run into a virus around less than 2.5k mass with a mult of 2 then your cells would sort of teleport, and instead of exploding into equal size pieces when your less than 1.5k or a couple big ones and the rest of them be small under 3k, they would all try to explode into a couple big ones and small ones by default. Anything else above those masses is fine.
.
.
So as a solution to this I thought that I would have it change the mult to 2, BUT ONLY while doing popsplits. And the rest of the time have mult stay at 3.33. That way every explosion is normal up until someone does a popsplit so perfect ones (same-size or two cells afterward) can occur and work %100, and noone see's anything weird. Im talking about inserting it into this code here in gameserver.js under the `updateMoveEngine` function.
<pre>
if (check.cellType === 0 && (client != check.owner) && (cell.mass < check.mass * this.config.sizeMult) && this.config.playerRecombineTime !== 0) { //extra check to make sure popsplit works by retslac
          check.inRange = false;
          return;
        }
</pre>
Now here's where the hard part comes in, how do I make it so it changes that specific mult to 2 instead of 3.33 when `check.inRange = false` , but after the popsplit is over and `check.inRange = true` again, the mult changes back to the normal value of 3.33 and the explosions turn normal again?? Can any @AJS-development/ogar-unlimited-devs or anyone else who knows the solution to this please help me? I've been working on this all day but to no avail :(

**Comment by Agarian** [comment]
Not sure. Both of us aren't very good problem solvers in javascript. Twice we spent a long time trying to fix something that ended up being very easy to fix.

**Comment by NatsuTheGreat** [comment]
It'll be too late to change to change the multiplier. The virus explosion will probably already happen.

**Comment by Megabyte918** [comment]
Nevermind... i think i might have found a different way to get it to work :D

**Comment by Megabyte918** [comment]
Nevermind... i think i might have found a different way to get it to work :D
