### ISSUE TITLE
a video how to use minions try my times and still says minions are off 

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#131]
I can't use agarmods it give the game sound and make more fun . is there's a way that I can use it ?

**Comment by Megabyte918** [comment]
Enter "playerlist", scroll down till you see your name. There should be an id next to it.
Then enter "minion [your id]" then the bots should start following you. Whatever id is who the bots will follow. View the Readme for more information. I'll answer your other question in #130

**Comment by problemsofworld** [comment]
thxs for explaining got it works well as hell
