### ISSUE TITLE
Lags From Others Servers

### ISSUE THREAD

**Issue by UltraSirius** [AJS-development/Ogar-unlimited#1312]
I See Some Servers are issuing lags I've palying Raphy no lag. 

when i've became so big. its very lag. everythin is off but nothin happened! and suddently the server crashes. 

(including other servers) 

pls someone advise them! thank you!

**Comment by darknight99x** [comment]
@UltraSirius Lag will not be fixed in OgarUL anytime soon, OgarUL is meant for "invite your friends" type of deal. 

OgarUL has many fun features packed into it, it will never not lag, there is so much content.

If you wish to have a server that can handle many people, but has very limited features for performance reasons, head over to MultiOgar. https://github.com/Barbosik/MultiOgar

**Comment by darknight99x** [comment]
Well someone deleted my comment, too bad I cannot tell the truth to users that OgarUL will never be a performance host.

**Comment by darknight99x** [comment]
If you're looking for a performance server to run, go look at MultiOgar.

OgarUL has many features which kills it's stability and performance.

**Comment by darknight99x** [comment]
OgarUL is going to be laggy for a while, considering the heavy amount of features it has.
MultiOgar on the other hand is lag-free, but does not have any of the fun features OgarUL has.
If you want lag free performance, go to MultiOgar.

**Comment by NatsuTheGreat** [comment]
Other servers? @LegitSoulja Is that possible?

**Comment by LegitSoulja** [comment]
@NatsuTheGreat It's not possible for 1 server to crash all others, but it is possible to get attacks on all servers from someone. But, I think this guy just feel bad about his server lagging period and want it fixed like everyone else. I don't blame him. But im also not the person who plays agar.io for life.

**Comment by Barbosik** [comment]
This is because you're running all servers from single node process. Just run it separately and it will not affect each other. It also will improve performance for serveral times on multi core systems.

**Comment by LegitSoulja** [comment]
@Barbosik I don't think people are making more than 1 server in 1 node process.
