### ISSUE TITLE
Are you guys really that sensitive about the true problems of OgarUL?

### ISSUE THREAD

**Issue by darknight99x** [AJS-development/Ogar-unlimited#1313]
Okay so someone keeps deleting a comment I am putting out for a user that was complaining of lag.

The facts are real, OgarUL will never really be lag free under javascript with the amount of features it holds. On the other hand, I told the user to direct himself to MultiOgar for a lag-free setup, minus the features.

What harm is done in this? I am just being honest with him, if you could quit deleting my comment for him, that would be great.

**Comment by LegitSoulja** [comment]
Checked audit log, and the only person that has a M in there name is your enemy. No, we are better off knowing true things about ogarul so that it can be fixed. I don't understand why comments was even deleted.

**Comment by NatsuTheGreat** [comment]
I agree. OgarUL Need to take down some of it's features. Expecially the CPU consuming features including setTimeout or setInterval. Lets hope someone's still working on the C# version. And ROFL LegitSoulja XDD

**Comment by LegitSoulja** [comment]
@NatsuTheGreat the only person who was ever to work on a c# version was me, but i quit. I don't even have time to do that anymore because of work. Plus, nobody else here has experience with C language except for me and that'll be a-lot of work.

**Comment by NatsuTheGreat** [comment]
Well RIP OgarUL C#

**Comment by LegitSoulja** [comment]
@NatsuTheGreat I can still be able to work on it during the weekends, but it won't be a thing that'll be released soon. I still have the project I was working on but removed it from github. I can continue, but I have no clue on when i'll ever be finished with it since it will be a lot of work, with no help what so ever.

**Comment by LegitSoulja** [comment]
And the limited amount of time ill even have to work on it.

**Comment by NatsuTheGreat** [comment]
I understand.

**Comment by Agarian** [comment]
i made this https://github.com/Agarian/Ogar-unlimited-simplified
