### ISSUE TITLE
Bots in team mode bug?

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#1314]
@AJS-development/ogar-unlimited-devs 
I'm not sure if this happens to everyone, but playerbots always spawn as the red team in `Teams` mode.
I cannot find what's causing it =/
Note this happens in the latest version (`17.4.0`)

**Comment by LegitSoulja** [comment]
@Agarian about what I mentioned about Natsu and Mega has check gitter.

**Comment by Agarian** [comment]
What do you mean?

**Comment by Megabyte918** [comment]
@Agarian are you available?

**Comment by Agarian** [comment]
Yes

**Comment by Agarian** [comment]
Let me get on my pc

**Comment by Agarian** [comment]
@LegitSoulja Any ideas on this? Me and Megabyte tried finding the source, with no avail.

**Comment by Agarian** [comment]
@Megabyte918 You available now?
