### ISSUE TITLE
Question cRestoreTicks and sRestoreTicks

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#1315]
A quick question,on file `config.ini` what are the differences `cRestoreTicks` and `sRestoreTicks` ?
@LegitSoulja 
@Agarian 
@Megabyte918 
@Andrews54757

**Comment by darknight99x** [comment]
`cRestoreTicks` is the general time of ticks it takes for the cell to reset.
`sRestoreTicks` is supposedly supposed to set the amount of ticks until collision resets after splitting, but I haven't seen this affect anything no matter what you change it to.

**Comment by GhostShot3** [comment]
For example if I put `cRestoreTicks=10` and `sRestoreTicks = 10` , will be the same when split that only put cRestoreTicks = 10 only?

**Comment by darknight99x** [comment]
You should probably ask the official devs.

**Comment by Agarian** [comment]
Actually cRestoreTicks was changed to sRestoreTicks, we just never removed it =/

**Comment by GhostShot3** [comment]
@Agarian They are the same thing?

**Comment by Agarian** [comment]
Yes but cRestoreTicks has no effect anymore

**Comment by GhostShot3** [comment]
@Agarian Thx.
