### ISSUE TITLE
Herokuapps

### ISSUE THREAD

**Issue by DoreM123** [AJS-development/Ogar-unlimited#1316]
hello guys, i was trying to run this app on Herokuapps, i already did all steps till `git push heroku master`
and i think im going good, but when i open "Open App" on heroku, it says:

> Application Error
> An error occurred in the application and your page could not be served. Please try again in a few moments.
> 
> If you are the application owner, check your logs for details.

here is my website: [AgarDM](http://agardm.ml)

Note: html code has 
`function connectToServer() {
            var defaultserv = "ws://ogardorem.herokuapp.com:8080"`

**Comment by darknight99x** [comment]
I wouldn't run it on there, or cloud9.io. Their cloud testing servers are not meant to run long term applications such as OgarUL, I recommend purchasing a VPS.

Running this sort of stuff on their clouds is usually against their TOS, and you'll be shutdown/banned from their services.

**Comment by DoreM123** [comment]
well, i runned it on there because of a reason, check out [This Website](www,kutuart.com) , they use the exact thing, on heroku, but i dont know how ;( 
it already worked on nitrous.io but i need to open the app all the time

**Comment by darknight99x** [comment]
Sorry, I can't help you, I don't understand your problem, and like I said I wouldn't run anything on there if I were you, if you're using a free version? If it's paid then there is no problem.

Try Amazon's 1 year free instance server, it allows Ogar to be ran there.
https://aws.amazon.com/?nc2=h_lg
Go there and create an AWS account, it will offer a year free trial. You can then run either Linux, CentOS, or Windows Server.

**Comment by DoreM123** [comment]
hello, i have done it and registered as "Enterprise"
hope you can see my latest issue, if you didnt, here it is:


> Hello Everyone!
> Today I registered at AWS(Amazon Web Services) As Enterprise option, i already have a [website](http://agardm.ml) with everything ready EXCEPT the server, here are my questions:
> 
> 1. Will my ogar hosting work?
> 2. What must i use? "Build A Web App" Or "Launch A Virtual Machine" Or "Host A Static Website" ?
> 3. If it will work, add me on skype if you're professional , its: dorem.yt
> 
> Thanks..

**Comment by LegitSoulja** [comment]
0.1. Calm down. I know you need help, but we are limited to help you with client hosting.

###### 1. Yes, Ogar can be hosted on a VPS, (Not a website)
###### 2. Question #1 answeres that for you.
###### 3. It will work, my skype is private so I cannot share, but if someone else is willing to then good luck.

**Comment by DoreM123** [comment]
ok, thanks

**Comment by RasyiidWho** [comment]
@DoreM123 you have facebook?
