### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#1317]
Mothercell start mass config
`Mothercellstartmass = 100`

**Comment by LegitSoulja** [comment]
This should go in suggestions. Stop making issues over petty things. Thank you.

**Comment by GhostShot3** [comment]
@LegitSoulja Ok

**Comment by GhostShot3** [comment]
@LegitSoulja Agarian locked conversation,i cant.

**Comment by Agarian** [comment]
its unlocked now

**Comment by GhostShot3** [comment]
@Agarian Ok
