### ISSUE TITLE
mother cell get the foods out instantly  

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#132]

**Comment by problemsofworld** [comment]
how  to fix spaw out speed of mother cell

**Comment by Megabyte918** [comment]
Try disabling `motherCellMassProtection` in gameserver.ini

**Comment by problemsofworld** [comment]
I did same 
:( help 
it's gets dots out so quickly

**Comment by Megabyte918** [comment]
Okay, go to src/entity/MotherCell.js, scroll down untill you see `MotherCell.prototype.update` then go down a little more untill you see // Spawn food
under that it should say `var maxFood = 10` , replace that with a lower number. The lower the number the lower the speed. (i think "1" is the same speed as vanilla agario)

**Comment by problemsofworld** [comment]
worked well thxs for helping :+1:

**Comment by NatsuTheGreat** [comment]
I was just reading this issue and I see you comment instantly 0.O
