### ISSUE TITLE
Ogar Hosting

### ISSUE THREAD

**Issue by DoreM123** [AJS-development/Ogar-unlimited#1322]
Hello Everyone!
Today I registered at AWS(Amazon Web Services) As Enterprise option, i already have a [website](http://agardm.ml) with everything ready EXCEPT the server, here are my questions:

1. Will my ogar hosting work?
2. What must i use? "Build A Web App" Or "Launch A Virtual Machine" Or "Host A Static Website" ?
3. If it will work, add me on skype if you're professional , its: dorem.yt

Thanks..

**Comment by darknight99x** [comment]
Hosting OgarUL on there should work fine. Launch a Virtual Machine.
You can add me on skype @ darknight99x for more information,

**Comment by DoreM123** [comment]
thanks , ill add you now

**Comment by ItzLevvie** [comment]
Also, by default the Virtual Machine uses a Dynamic IP (meaning that when you restart your VM the IP wil change). 

If you want to create a static IP, you have to create an Elastic IP.

**Comment by LegitSoulja** [comment]
What is a static website? :/

**Comment by hlevine9** [comment]
Can you guys do a video tutorial, because I don't understand how to host my server either, nor do I understand what you're trying to get across.

**Comment by NatsuTheGreat** [comment]
We cannot assist you with this, the only suggestion we have, is port forward. I can also see that you have ffa.html on your server which looks like OgarUL to me.
