### ISSUE TITLE
Can i create an new like this?

### ISSUE THREAD

**Issue by systemroot** [AJS-development/Ogar-unlimited#1326]
Can i create an new **setup.sh** :question: 
i think this  isn't good.
![](http://image.prntscr.com/image/42b42aa668fe4d289b9506af0357c374.png)
I'm thinking to create an new one which will detect From which distro is trying to installed Ogar And to call the right installation file. 

example in setup.sh will be only
if ' centos ' then
wget balbalbabla.centos
./blablabla
fi

if 'ubuntu' then
wget blablabla.ubuntu
./blablabla.ubuntu
fi
...
those files can be here https://github.com/systemroot/ou
or you can move those at ogar repo or you can create a new repo with those or you can do whatever you want. just i was thinking to fix setup.sh . Let me know if i can do this.

**Comment by LegitSoulja** [comment]
? This isn't even necessary m8.

**Comment by systemroot** [comment]
yeah u'r right.
but here some times i can read new issue's "how to install" :p
