### ISSUE TITLE
Agario Skins

### ISSUE THREAD

**Issue by CodingKuda** [AJS-development/Ogar-unlimited#1328]
Does anyone know how to get agar.io skins, but as pngs? For example change your date to 23 of july and the "birthday skins" will be avaliable..But can anyone tell me? Because agar.re is down, that has all the skins. and i cant find it anywhere else..thanks

Kuda

**Comment by LegitSoulja** [comment]
It's very simple, and I'll explain by little detail.

If you know the name of the skin, that's even better. Now note that using a browser, you can see every loaded source, including an image. You'll have to play for the image to load, then which you'll be able to obtain the link to the image afterwards.

**Comment by CodingKuda** [comment]
@LegitSoulja So your saying I have to actually buy the agar.io skins, for me to be able to get them? There has to be an easier way..

**Comment by NatsuTheGreat** [comment]
>You'll have to _play_

Did you read that wrong? :P

**Comment by nulcearc** [comment]
@CodingKuda https://configs-web.agario.miniclippt.com/live/v4/117/FunShine_Bear.png i found one

**Comment by CodingKuda** [comment]
Okey, Mb mb. I will try again. And no i didn't

**Comment by CodingKuda** [comment]
Oh, Yet i still dont get it. k im just gonna give up. i swear..

**Comment by ItzLevvie** [comment]
I have all of the skins ;P

**Comment by NatsuTheGreat** [comment]
I have all 182 skins too ItzLevvie :$

**Comment by Agarian** [comment]
I need them

**Comment by nulcearc** [comment]
If you need ALL skins list in agar.io , i have them.

**Comment by CodingKuda** [comment]
@nulecear can i have them? Do you have the new birthday  skins??

**Comment by Megabyte918** [comment]
agario-skins.org

**Comment by nulcearc** [comment]
@CodingKuda I have brithday, premium, veteran and other skins. https://gist.github.com/nulcearc/065b1434658e47ded2f6107635db1842

**Comment by CodingKuda** [comment]
@nulcearc I mean, i need the png's. HOw can i use those names/skins to get the png's?

**Comment by CodingKuda** [comment]
@Megabyte918  Thanks

**Comment by CodingKuda** [comment]
Oh nvm @nulcearc  I found it! Thanks bro! If you can. For the new skins can you keep updating the list? And how did u find the skin names?

**Comment by ItzLevvie** [comment]
^^ It's pretty easy to find the skin names.

**Comment by nulcearc** [comment]
@CodingKuda from here https://configs-web.agario.miniclippt.com/live/v4/146/GameConfiguration.json.
Yes i'll update skins list.

**Comment by CodingKuda** [comment]
xD @ItzLevvie  i dont even understand some html xD

**Comment by LegitSoulja** [comment]
That's not HTML.. You don't need no HTML experience for this lol.

**Comment by SharkFinPro** [comment]
that's JSON

**Comment by CodingKuda** [comment]
See @LegitSoulja  Thats what im saying, im really bad at programming/coding. And @ItzLevvie Notify me when ur done with the script

**Comment by nulcearc** [comment]
@ItzLevvie notify me too. Skins are very important for my client :)
