### ISSUE TITLE
bot with font names 

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#133]
HI I tryed to add bots with font names then file asked to save as is there's a way to add font names to bots

**Comment by Megabyte918** [comment]
What do you mean by font? you mean like fancy text? if you have any unicode characters inside of your botnames.txt file, make sure to save it as UTF-8 or else the names wont load

**Comment by problemsofworld** [comment]
worked  thxs

**Comment by problemsofworld** [comment]
closed
