### ISSUE TITLE
NEW GAMEMODE ??

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#1330]
Can u add a gamemode , that sometimes a cell spawn with a virus close to it , so players have t popsplit these cells ( with a fast merge ) 

>*********************************************************

> Or maybe a pokemon go gamemode ?????????????????????? WHAT?

>*********************************************************

**Comment by Megabyte918** [comment]
df is a pokemon go gamemode

**Comment by darknight99x** [comment]
lmfao okay im done. this is by far the most autistic post I have ever seen.

**Comment by DarkZYT** [comment]
@NatsuTheGreat What about the popsplit gamemode

**Comment by Megabyte918** [comment]
popsplit gamemode? what?

**Comment by NatsuTheGreat** [comment]
@DarkZYT Try FFA ;)

**Comment by DarkZYT** [comment]
pleeeaaase

**Comment by DarkZYT** [comment]
k den

**Comment by Megabyte918** [comment]
sorry i just had to

**Comment by firelightning13** [comment]
lol
