### ISSUE TITLE
Gamemodes!

### ISSUE THREAD

**Issue by DoreM123** [AJS-development/Ogar-unlimited#1332]
Hello guys!, i was trying to make new gamemodes to [my website](http://agardm.ml/), and i have a couple of questions!

1. Do i need to make a new Virtual Machine to do it? or will it work on the same one?
2. If i need to use the same one im using, how do i run 2 gamemodes with the same ip?

Notes:
I'm using Amazon Web Services, Enterprise service
I Already have a virtual machine

**Comment by DoreM123** [comment]
ANSWER:
Hey The Solution IS:
Duplicate The Folder As Your Gamemodes (FFA-Exp-Teams-Virus Shoot)

in each server goto `/src/settings/advconfig` and change the ServerPort To A Different Number Than The others! Thank Me Later

**Comment by Agarian** [comment]
Umm ok

**Comment by DarkZYT** [comment]
lol

**Comment by LegitSoulja** [comment]
Andrew really made it for 1 server per machine, but I guess you can do that. Just note that nodejs only uses 1 core, the same core for all. Doesn't matter if you got a triple, quadruple, quad core CPUs it will only use 1 and 1 for all. All in 1 cause nodejs sucks.
