### ISSUE TITLE
can I add sound

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#134]
I would love to add some sound from agarmods can I do that :) ?

**Comment by firelightning13** [comment]
Leave a suggestion here : #46

**Comment by Andrews54757** [comment]
Also, this is impossible

**Comment by Agarian** [comment]
it is a client side issue.

**Comment by hassanila97** [comment]
@Andrews   Is it possible to maybe make a tampermonkey script ..  som that we can now control client side also... meaning that if we want for example sounds we can add it just by installing userscript..   think about it

**Comment by Andrews54757** [comment]
Agar.io disabled those things

**Comment by hassanila97** [comment]
Wtf  :((  what you mean by disabled    they dont allow right?   Come on JUST DO IT  :P

**Comment by Andrews54757** [comment]
no, they completely disabled it. not by law, but by code. (i think)

**Comment by Lukkez** [comment]
You can use agar expose....

**Comment by Andrews54757** [comment]
also, i feel too lazy

**Comment by Agarian** [comment]
wtf that?
