### ISSUE TITLE
2 VIRUSES WERE DETECTED IN THE OGARUL.TK CLIENT

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#1341]
The title says it , and i cant use this client !!
Object :
       `play.ogarul.tk/security.php?type=legitsouljac`
Virus :
       `JS:Agent-DWR [Tjr]`

**Comment by ItzLevvie** [comment]
@LegitSoulja People can still see the script.

**Comment by Influxx** [comment]
LOL! Not sure why @LegitSoulja is trying to hide a console.log statement.
You can simply view the contents of the file in chrome dev tools. It eval's to:

`console.log("LegitSoulja aka OgarUnlimited Co-Owner is responsible for this site. Please respect all other servers, and this site content. Thanks!.");`

**Comment by ItzLevvie** [comment]
I saw that xD. @LegitSoulja, you should use a better encryption other than eval. Anyone can decode an eval script because eval creates a list of variables that are in your code and there are plenty of eval unpackers / decoders.

**Comment by DarkZYT** [comment]
It got fixed thanks !

**Comment by LegitSoulja** [comment]
@ItzLevvie @DarkZYT I'm not trying to hide anything. The reason why I used eval was because the file that the console logged from would not be located directly. 

I'm not really trying to hide, nor decode anything. I'm just a smart thinker when it comes to things like this.

**Comment by LegitSoulja** [comment]
Haha, A virus. Well, I guess you don't really know what a virus is. :/

**Comment by ItzLevvie** [comment]
Okay, that makes more sense.
