### ISSUE TITLE
A random skin .

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#1342]
Hey guys i wanna create a skin , that gives you a random skin from a defined list , example : 
If you write : `<veteran>`
that gives you a random veteran skin : `<kraken> <bear> <fly>`...
like the `</random>` skin
*******************************************************************************************************
           `if it can be as a plugin ir a file.js , just give me the code i can do it`
                                       im a begginer on JavaScript
*******************************************************************************************************
<h1>**THANKS!**</h1><h7>Sorry for my bad english

**Comment by NatsuTheGreat** [comment]
I already did this on my server. But it's my modified server, not OgarUL.

**Comment by DarkZYT** [comment]
how ? just how do </random> work ?

**Comment by Agarian** [comment]
You can use the SkinChanger plugin:
`plugin install SkinChanger`

**Comment by Tokoagar** [comment]
Im not sure is talking about that because it use online custumskins and he want's only veteran and it stays fix and do not change

**Comment by DarkZYT** [comment]
but i dont want only veteran , i wanna some customized skins

**Comment by DarkZYT** [comment]
and skin changer changes the skin every seconds so ya

**Comment by Tokoagar** [comment]
go to randomskins.txt and add

kraken
t-rex
raptor
mammoth
shark
crocodile
lion
panther
cougar
bear
sumo
hunter
fox
snake
bat
lizard
wasp
spider
fly
Then put the name </random and you get a vertran :)

**Comment by Tokoagar** [comment]
</random> *

**Comment by Tokoagar** [comment]
don't froget do add the > at the end

**Comment by DarkZYT** [comment]
but i wanna much for example <veteran> <premium> <retina> ....

**Comment by LegitSoulja** [comment]
You can use custom skins for the skin changer, plus you can increase the skin change time if it's too fast.

There's also an option for using just a skin.txt file for skins you would only use for skin changer, but that only happens when live skins aren't obtainable.

**Comment by DarkZYT** [comment]
wait how can i make the skin change time infinite , maybe `-1` ? or a big number like `99999999` ?

**Comment by LegitSoulja** [comment]
infinite?

**Comment by DarkZYT** [comment]
sorry im not english i mean : that never updates the skin

**Comment by LegitSoulja** [comment]
@DarkZYT so that skins doesn't change? Just increase the numbers high

**Comment by DarkZYT** [comment]
oh yeah , i tried -1 but i changes reaaaaaaaaaaaaaaAaaaaaly fast , my eyes explosed

**Comment by LegitSoulja** [comment]
-1 isnt a valid time -_-

**Comment by DarkZYT** [comment]
k den

**Comment by firelightning13** [comment]
> oh yeah , i tried -1 but i changes reaaaaaaaaaaaaaaAaaaaaly fast , my eyes explosed

When you know too much about time travel

**Comment by LegitSoulja** [comment]
lol

**Comment by DarkZYT** [comment]
lol xD

**Comment by AlexandriteErikParacelsus** [comment]
lol firelightning13's best joke yet
