### ISSUE TITLE
Question on client configs

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#1343]
So how you can see in gamemode files like `UnlimitFFA.js`, they contain a function (onServerInit) that changes a config when the gamemode is selected. I tried doing the same with client configs, but came with no result. So how would i do so with client configs?

**Comment by NatsuTheGreat** [comment]
Simple.

For example here I enabled W Macro.

```
gameServer.config.clientWMacro = 1;
```

Added that in ```onServerInit```.

**Comment by LegitSoulja** [comment]
Um.. Same as any other configuration.

**Comment by Agarian** [comment]
That didn't work

**Comment by NatsuTheGreat** [comment]
it worked for me, The macro was turned on, but it wasn't turned on with FFA (0).

**Comment by Agarian** [comment]
Im trying this with the `clientSkins` config

**Comment by NatsuTheGreat** [comment]
Oh. I'll look into it.

**Comment by Agarian** [comment]
Wait, so that doesn't work?

**Comment by NatsuTheGreat** [comment]
it'll probably be just the same. I am very busy now, Try:

```gameServer.config.clientSkins = 1/2/3;``` (which ever value you need).

**Comment by Agarian** [comment]
I said i already did

**Comment by Agarian** [comment]
nvm it
