### ISSUE TITLE
Can't install on linux ubuntu

### ISSUE THREAD

**Issue by Tokoagar** [AJS-development/Ogar-unlimited#1344]
idk how to install ogar on my linux computer
When I do : git clone http://github.com/AJS-developement/Ogar-unlimited.git
The error : The " git " program is not yet installed . You can install it by typing:
sudo apt install git
Pops up can u please help me

**Comment by Tokoagar** [comment]
@LegitSoulja Last issue I made you said Run in terminal I did it and the error The "run" command is not found, did you mean :
 The command " Runc " package " Runc " (universe )
 The command " grun " package " grun " (universe )
 The command " rup " package " rstat - client" (universe )
 The command " srun " package " slurm - client" (universe )
 The command " zrun " package " moreutils " (universe )
 The command " rn " package " trn4 " ( multiverse )
 The command " rn " package " trn " ( multiverse )
 The command " QRUN " package " torque- client" (universe )
 The command " QRUN " package " torque -client- x11 " (universe )
 The command " runq ' package ' sendmail -bin " (universe )
 The command " runq " package " exim4- daemon-heavy " ( hand)
 The command " runq " package " exim4- daemon-light " ( hand)
run: command not found
hapens please help me

**Comment by ItzLevvie** [comment]
"You can install it by typing: ```sudo apt install git```"

^^ Read the error first before creating an issue.

**Comment by Tokoagar** [comment]
Thanks I should read next time :P

**Comment by raphyjb** [comment]
lol get rekt son
