### ISSUE TITLE
HTML CODES

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#1345]
Please , how can i use an html code in the client description : 
`clientInstructions`
Cause it doesn't even work

**Comment by LegitSoulja** [comment]
You can't.

**Comment by DarkZYT** [comment]
@LegitSoulja I saw a server with it !!!!!! wait please dont close !

**Comment by LegitSoulja** [comment]
You never seen a server with it.

**Comment by DarkZYT** [comment]
k den
