### ISSUE TITLE
can´t connect to ogarul.tk from a other PC

### ISSUE THREAD

**Issue by ArnieTheOne** [AJS-development/Ogar-unlimited#1349]
Hi delophers!
I´ve a question:
        I started the server on my laptop and connect to the game in Firefox Delopher Edition. But if I wanted to connect from a other computer as my there´s a connection error.

Gamemode: Experimental 2
Version: 17.4.0

How can I fix that to connect from the home network or internet the server?

Thanks in adverange

Best Regards
Arnie

**Comment by Agarian** [comment]
You may need to portforward your ports, or use some kind of VPS

**Comment by LegitSoulja** [comment]
You don't need to port forward. He said home server or Internet server.

@ArnieTheOne sorry, you don't need to port forward unless you playing just by yourself or with friends or family in your house connected to the same Internet. 

You'll get an alert box when you get onto the site. Just click ok. If you changed ports or anything make sure you change it in the alert box.

**The server has to be started before you try connecting with the client.**

**Comment by ArnieTheOne** [comment]
Thank you very much LegitSoulja and Agarian!
yor´re my livesaver :+1:

**Comment by LegitSoulja** [comment]
I never had actual life savers in a while. Probably because I don't eat candy as much haha.

**Comment by Agarian** [comment]
@Megabyte918 discord?

**Comment by Megabyte918** [comment]
yup

**Comment by Agarian** [comment]
@Megabyte918 how bout now?
