### ISSUE TITLE
Tremendous glitch, please fix!

### ISSUE THREAD

**Issue by WolfOGG** [AJS-development/Ogar-unlimited#1352]
I noticed a glitch about 2 weeks ago while my 2 friends and I were attempting to make a virus go across the top of the map, instead of the virus traveling and self shooting itself towards the other edge of the map, it grew and when my friend split over the over sized weird virus he grew up to 7000 mass, then we tried it again, this time we fed about 20 feeds in front of a virus and shot the virus and it happened again we split over the big viruses and gained up to 8000 mass, we have not spoken about this glitch to anyone in any other public server so we could keep the OgarUL the community from cheating in servers, please fix this so there is no cheating later on when other people start noticing this glitch.

Thanks, ~Venom/WolfOGG

**Comment by Megabyte918** [comment]
@WolfOGG replace your `onAutoMove` function in Virus.js with this one:
<pre>
Virus.prototype.onAutoMove = function (gameServer) {
  var r = 100; // Checking radius
    let ejectedNodes = gameServer.getEjectedNodes();
    for (var i = 0; i < ejectedNodes.length; i++) {
    var check = ejectedNodes[i];
    if (check.quadrant != this.quadrant) continue;
      var topY = check.position.y - r;
      var bottomY = check.position.y + r;
      var leftX = check.position.x - r;
      var rightX = check.position.x + r;

    if (this.collisionCheck(bottomY, topY, rightX, leftX)) {
      check.angle = 0; //vanilla default is right
      this.feed(check, gameServer);
      this.mass = gameServer.config.virusStartMass;
      ejectedNodes.length--;
    }
  }
};
</pre>
I removed the second to last decrement from original function and now they shoot at normal speed again. And I re-added @NatsuTheGreat's dirty fix from #1121 just in case. I would PR this but I don't feel like redoing everything I've done on my fork =P

**Comment by Megabyte918** [comment]
@Agarian do you mind PRing this fix for me? I would but I don't feel like redoing everything I've done on my fork =P

**Comment by Megabyte918** [comment]
@AlexandriteErikParacelsus thx m8

**Comment by AlexandriteErikParacelsus** [comment]
k
