### ISSUE TITLE
Pardon The Interruption

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#1353]
I am officially leaving AJS. The reason being is that I need to do more with my life instead of being here. I just don't fit in with the community, plus mostly everyone here is younger than me and things aren't just right. I am 24, turning 25 in the next next week in August, so I'm planning on leaving work, and moving out of state and going back to a town which I used to stay and start life there, and also get a better job which pay a good ($17 an hour). I wish I was more into working with you guys, but I feel bad for not helping as much, but I was still learning and not much communication was going on with each other, and not much of things was organized here.

It was fun in the beginning, but now it has got more depressing, even having to deal with NodeJS which is now my least favorite, which I have officially stopped working with. I'll be going back to what I used to do which is joining back with the modding community (NextGenUpdate) for all platforms, especially PS3 and PC. 

When I first became part of AJS I was still new to NodeJS. Me and Beil the owner of agariohub.net, we were working together which I had the site (agariohub.tk) which was another hub for agario servers. I thought about doing server hosting for ogario servers, that's why I created OgarConsole. I never got far into it once agar.io kind of stopped accepting private servers after there bot patch, and when they changed protocols which I thought agariohub.tk was officially done. It took a while for them to come back, but then I have gave up entirely and closed the site down. I didn't really too much play agar.io, nor other games recently. Work really has just been up my ass the past weeks since I worked full time, 6-9pm, which I'll then come home tired which I sleep then go right back to work again. Not really having much time to do things, except on the weekends. I'll have to find a way to get layed off, since I'm planning on moving for my birthday with my fiancé.

I decided to come over here, since Beil told me about OgarUnlimited, and I've made OgarConsole work with this platform, and Andrew discovered me. Which then, for some reason I was instantly made an Owner of AJS which kind of left me clueless, but no questions was asked. I really hope OgarUL finds someone that's experienced to help out, and not have a lot kids run around the place. 

I may, or may not be back, but I'm leaving github completely since I have no use at all whatsoever. Most of my work that I do I really don't share publicly, and github is a fool to think ill pay for private subscription per team member for a private repo haha. That'll never happen. 

But anyways, I may or may not come back, and hopefully I do get back into nodejs. I just had bad times with it working standalone (Not with ogarul) but with some things I was working on. 

Sorry, if everything it out of place, I'm using my phone and it's really not a proper thing to use for editing which you'll spend a while trying to which I'm not so I'm hoping I have no mistaken, or bad grammar context. Anyways, farewell, and I hope to see ogarul again in the future.

**Comment by Agarian** [comment]
Kill me now

**Comment by Megabyte918** [comment]
It's been nice knowing you man, I wish you the best of luck with moving and getting that job. I think you made the right choice if it was depressing you that much. Happy pre-birthday btw, I'm going to miss you :(

**Comment by AlexandriteErikParacelsus** [comment]
Yeah, your work put into this project was really amazing. I'm going to miss you.

**Comment by GhostShot3** [comment]
@Agarian Kill me before

**Comment by firelightning13** [comment]
Goodbye @LegitSoulja , we will miss you :(

**Comment by GhostShot3** [comment]
Goodbye @LegitSoulja  :(

**Comment by David1ali12** [comment]
Thanks for all you have done I'm still using OgarConsole  which a great thing you have made

**Comment by Agarian** [comment]
You were as good in life as you were in death. It's been nice knowing you.

**Comment by Megabyte918** [comment]
Pretty sure he's not dead lol

**Comment by LegitSoulja** [comment]
@Agarian don't kill yourself....
@David1ali12 No, Thank you!.
@AlexandriteErikParacelsus Thanks :)
@firelightning13 I will miss you aswell.
@GhostShot3 Goodbye
@Megabyte918 Nope, not yet. Maybe.

**Comment by Agarian** [comment]
@LegitSoulja Can you do me one last favor? I would like for this server ( https://github.com/OgarPlus/Ogar-Plus ) to be compatible with play.ogarul.tk, if you cannot do that, at least tell me how? I wanna experiment with this server.

**Comment by LegitSoulja** [comment]
@Agarian Got it connected to the client, now there's a few things that I have to figure out because now, player spawns, but the cell is all glitched out, and I can't move. Once i figure that out, then ill pass it. Other than that if you don't hear a reply from me then I guess I was never able to figure out why.

**Comment by LegitSoulja** [comment]
Mostly, is the playertracker that needs updating in ogarplus. Im too lazy to fix that. Maybe you can, but i got it working for the client, its just the updating of the player.

**Comment by firelightning13** [comment]
@LegitSoulja , I hope you'll remember this moment.... #539

**Comment by Agarian** [comment]
@LegitSoulja Thank you, i don't really see why all entities spawn in one place tho, may be because if a `NaN` kind of thing.

**Comment by GhostShot3** [comment]
@Agarian he left it? :(

**Comment by LegitSoulja** [comment]
@Agarian it'll take some work to have it properly working for the client. You got the fix that allows it to connect to the client, now there's a few more things that has to be fixed for it to work properly.

**Comment by Agarian** [comment]
Anywars, come on man, you don't need to quit!

**Comment by Agarian** [comment]
The lack of notifications in OgarUL is giving me a headache -_-

**Comment by LegitSoulja** [comment]
?

**Comment by Agarian** [comment]
Also that mouse bug is getting on my nerves! I seriously feel like i should use the github.io client

**Comment by LegitSoulja** [comment]
I don't know what you're talking about still... There's no difference with the github client link, and play.ogarul.tk

**Comment by LegitSoulja** [comment]
@Agarian fixed????

**Comment by Agarian** [comment]
@LegitSoulja How do i fix the no moving bug with the OgarPlus server? I just can't find out why it happens, of course, i've never been a good problem finder :neutral_face:

**Comment by Megabyte918** [comment]
@Agarian I can help you find it, got nothin better to do :P

**Comment by LegitSoulja** [comment]
@Agarian put the project on dev.ogarul.tk and share it with me

**Comment by Agarian** [comment]
Do you not have it though?

**Comment by Agarian** [comment]
And its too late anyway

**Comment by LegitSoulja** [comment]
@Agarian ... No.. I normally don't keep random junk like that on my computer. I really use a SSD for most downloads, and another for my applications, another for games, other for documents, and also I have cloud storage WD. 

But, eh, I've got to the point where I was tired of cleaning my computer, and just cleaned up MAYJORLY afterwards. 

I pretty much have to toss trash on another HDD, then destroy the partitions, re-write them. I don't even have(use) a trash bin lol.
