### ISSUE TITLE
PHP User Online Script

### ISSUE THREAD

**Issue by jxstmartin** [AJS-development/Ogar-unlimited#1354]
Is there any way to create a PHP Script which shows how many users are on a server? 
Thanks

**Comment by LegitSoulja** [comment]
@jxstmartin I was using this with play.ogarul.tk. I don't mind sharing. You do need to have MySQLi access. I provided a file called legit.sql which you will need to execute(SQL) into your database, and also update counter.php mysqli credentials. Counter is used with stored session of each person that execute the script. I provided a usage txt file on how im using it. You could also just include the script, but I used jquery load.

[Counter.zip](https://github.com/AJS-development/Ogar-unlimited/files/380503/Counter.zip)

Good luck.
