### ISSUE TITLE
My opinion on the Digital millenium Copyright act and why I wont create any more commits

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#136]
One day ago, Devin Ryan, the creator of ogar, DMCA ed this project. I understand that all he wants  is credit and i agree that the owner should always have credit. But, the real problem comes in when you just send a DMCA form. This makes it so the project is removed if you dont do something. Although I support credit to other people I think this is not the right answer. It is considered un-courteous and rude to do so if you dont tell that person beforehand in like a issue or a pull request. Instead, some people just do it without being courteous. Many people, including me, put their hearts out for their project. My opinion is that DMCA just hurts developers. it just makes us occupied with legalities instead of making the world a better place. if you are not a developer and you do not understand, it is sorta like writing a 50 page paper for your class and everybody who reads it is amazed but when you get home, it is unusually silent at dinner and then your parents explode, saying WHY WHY WHY. The reason: You forgot to put a cite for a source in your paper so your teacher gave you a F. This doesn't happen usually because before putting up the grade, the teachers usually tell you that one of your cites are missing in the feedback. just like that, if Devin told me in a issue or made changes in a pull request, I would have agreed and made changes. Instead, some people just give you the form for the DMCA like if your teacher just gives you the grade before giving you feedback.

**So in recognition in this, i will halt all commits, even pull requests until the end of the week (includes the big update planned for today)**

**Comment by Agarian** [comment]
That sucks because next week, im going to see my family im my home state (Michigan) for 2 weeks cannot wait til that time comes still.

**Comment by Megabyte918** [comment]
;~;

**Comment by Agarian** [comment]
Ikr =/

**Comment by Agarian** [comment]
Just in case,  im downloading a fresh copy

**Comment by Megabyte918** [comment]
Is this all because of that copyright problem in the license.md

**Comment by Megabyte918** [comment]
Does this mean that this project will be deleted? God I hope not. In my opinion Andrew, I don't think that you should stop making commits over something like this. It wasn't your fault this happened it was just a simple mistake in the license. Thats all. If Devin wanted some credit, all he had to do was make a pull request. There was NO way of knowing this would have happened unless he openly came out and told people to credit him in the license. It wasn't your fault. It wasn't anybody's fault but his.

**Comment by ItzLevvie** [comment]
@Megabyte918 No.

**Comment by Andrews54757** [comment]
another reason I stopped - I have lots of work

**Comment by Andrews54757** [comment]
Also, I am not stopping because of the DMCA, i am stopping to say "Don't be rude and dmca people" to everybody

**Comment by Agarian** [comment]
any way to disable the mergeoverride? (with the "merge" command)

**Comment by Andrews54757** [comment]
i will add that next week

**Comment by Agarian** [comment]
any possible way to delete a "disabled" fork?
https://github.com/Agarian/OgarServ

**Comment by Agarian** [comment]
and yes i changed my cover photo ^-^

**Comment by Megabyte918** [comment]
@Agarian like your new prof pic

**Comment by kcxx** [comment]
Lets create new server from scratch. I can help with protocol.

**Comment by Agarian** [comment]
lol pls dont i like this one

**Comment by Megabyte918** [comment]
This one is fine the way it is
