### ISSUE TITLE
I cant port foward

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#1362]
**First excuse my bad english am using translator, I have little access English in my country.**

I opened all the ports, but it does not work the ports,I use a site for testing and it appears that does not work, it's all right i opened them correctly, my server with statitics plugin does not work,because the ports are not working.
Ports open : 567( `serverPort` ) and 88( `serverStatsPort` )

Some observations
-Used IPV4 To open ports
-Fixed IP
-DMZ Area enabled
-Firewall 100% off
-Windows Defender 100% off
Contact
**Skype: ghostshot3.private**

**Comment by Barbosik** [comment]
Check your router, you should configure it to bypass external connections on selected ports to your home computer.

By the way, I don't recommend to use port numbers smaller than 2048. But this suggestion is significant for linux operating system. It seems like you're using windows, so it's not important for you.

**Comment by GhostShot3** [comment]
@Barbosik Yes windows,Any suggestions to make?

**Comment by Barbosik** [comment]
Open your router configuration page and add port forwarding. For example to forward external ports 88-600 to your local IP and ports 88-600.

**Comment by GhostShot3** [comment]
@Barbosik Yes, I did it but still does not work the door.

**Comment by Barbosik** [comment]
Did you tried MultiOgar with enabled `serverTracker=1`? Try to start it and check if your server appears on ogar tracker: http://ogar-tracker.tk

**Comment by GhostShot3** [comment]
@Barbosik Thank I not know I had in multiogar.

**Comment by GhostShot3** [comment]
@Barbosik It does not work on multiogar also

**Comment by Barbosik** [comment]
so, it means that your port forwarding doesn't works. Check if it configured correctly, also try to change port from 567 to 40000 or above. Because ports below 1000 is reserved for registered services and it may conflict with some service.

**Comment by GhostShot3** [comment]
@Barbosik I  just open the ports  567 `serverPort` ,60 `serverStatsUpdate` and 88 `serverStatsPort`

**Comment by ItzLevvie** [comment]
You don't have to port forward serverStatsUpdate. That's just an interval (probably in ms or seconds) on when to update the stats with the new information (players, spectators, etc..) sent from the server.

**Comment by NatsuTheGreat** [comment]
```serverStatsUpdate``` Is in milliseconds. It is multiplied by 1000 in the code.

**Comment by GhostShot3** [comment]
@NatsuTheGreat Thx
@ItzLevvie Thx too

**Comment by GhostShot3** [comment]
@NatsuTheGreat @ItzLevvie  Removed the `serverStatsUpdate` port, but still does not work.

**Comment by NatsuTheGreat** [comment]
We just said it doesn't need to be port forwarded, not that it would be fixed. :P

Please check:

http://www.yougetsignal.com/tools/open-ports/

**Comment by GhostShot3** [comment]
@Megabyte918 WHY CLOSE

**Comment by Agarian** [comment]
Why not?

**Comment by GhostShot3** [comment]
@Agarian Not solved.

**Comment by Megabyte918** [comment]
This does not have to do with OgarUL
