### ISSUE TITLE
About Plugins

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#1363]
In `OgarConsole` does not work `Shortcuts` plugin commands, commands like `ka sp` etc but in cmd works.

**Comment by Megabyte918** [comment]
Please put this issue in https://github.com/AJS-development/OgarUL-Plugin-Library

**Comment by LegitSoulja** [comment]
You cannot use plugin commands in OgarConsole. It's limited to many things.
