### ISSUE TITLE
Custom Skins?

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1366]
I want to have a folder for custom skin images, but when i do that and then in customskins.txt  i put /images/filename.png but that doesnt seem to work :/

**Comment by Souf123** [comment]
You need to do this : next to the Url

**Comment by SharkFinPro** [comment]
there was a :to the left of it, like all the others

**Comment by Agarian** [comment]
This isn't possible right now, but that may be a good suggestion for #1253!
