### ISSUE TITLE
isnt workin

### ISSUE THREAD

**Issue by lolwwwweafwwea** [AJS-development/Ogar-unlimited#1367]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?

What version are you on?

What command did you type if any?

You must have a description as well

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

**Comment by lolwwwweafwwea** [comment]
it wont work even with node it just stoped working HELP

**Comment by NatsuTheGreat** [comment]
>it wont work even with node

Recommended node version is 5.9.0

**Comment by lolwwwweafwwea** [comment]
how do i download it u cant anymore

**Comment by Megabyte918** [comment]
nvm install 5.9.0

**Comment by Megabyte918** [comment]
nvm install 5.9.0

**Comment by Agarian** [comment]
@Megabyte918 You were on discord earlier, you have time now?
