### ISSUE TITLE
Getting rid of some commands/gamemodes.

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#1369]
Hello everybody, @NatsuTheGreat and I were discussing how currently there are WAY too many commands and gamemodes in OgarUL, so we are going to remove some. The problem is, we don't know exactly which ones to remove yet. 

We need everyone else's opinion first before we start. So I have created a bunch of voting polls with the lists of commands and gamemodes, I need everyone to click on these polls and basically vote on which gamemodes/commands get to stay, and which ones get to be removed. The highest voted and most used commands and gamemodes will be kept, the least used and least voted commands and gamemodes will be removed. 

Commands (yes ik theres alot):
http://www.strawpoll.me/10863662
http://www.strawpoll.me/10863714
http://www.strawpoll.me/10863747

Gamemodes:
http://www.strawpoll.me/10863800

NOTE: You can pick multiple votes whenever you vote!

Current results:
- Commands
[Strawpoll one](http://www.strawpoll.me/10863662/r)
[Strawpoll two](http://www.strawpoll.me/10863714/r)
[Strawpoll three](http://www.strawpoll.me/10863747/r)

- Gamemodes
[Strawpoll one](http://www.strawpoll.me/10863800/r)

Thank you for your time :)

**Comment by NatsuTheGreat** [comment]
Current results:
- Commands -
[Strawpoll one](http://www.strawpoll.me/10863662/r)
[Strawpoll two](http://www.strawpoll.me/10863714/r)
[Strawpoll three](http://www.strawpoll.me/10863747/r)

- Gamemodes -
[Strawpoll one](http://www.strawpoll.me/10863800/r)

**Comment by Andrews54757** [comment]
Why? commands dont impact preformance

**Comment by Megabyte918** [comment]
I'm not saying it does, its just 71 commands might be a *bit* too much. Its kinda overwhelming when you do help, because all 71 commands get listed at once and it takes forever to scroll through to find the one you want. There's also some unnecessary commands + some people don't even use so i thought it might be a good idea to just remove them.

**Comment by Megabyte918** [comment]
But, since support for this project is coming to an end I guess this will not be needed anymore :/
