### ISSUE TITLE
Need help with FDmultiplier

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#137]
Hello! I need help with using FDmultiplier in gameserver.ini.
Im trying to replicate the effect with vanilla agar with how you can surpass the 22.5k mass limit for a split second when someone splits into you, and I figured that I could just use the FDmultiplier setting in gameserver.ini to decay mass by 100 times the normal speed when i get more than 22.5k mass to replicate the effect

How would I make it so ANY mass over 22.5k gets the fast mass decay and not just one number? And STILL make myself able to split at 22.5k? I'm completely stumped

**Comment by Andrews54757** [comment]
What do you mean, it does make it so any mass above that number has the fast decay effect

**Comment by Megabyte918** [comment]
How would I make it so the max mass is 50k for one cell, but at 22.5k I still split?

**Comment by firelightning13** [comment]
You need to change something in Cell.js, modify it yourself.
```
Cell.prototype.addMass = function(n) {
    if (this.mass + n > this.owner.gameServer.config.playerMaxMass && this.owner.cells.length < this.owner.gameServer.config.playerMaxCells) {
        this.mass = (this.mass + n) / 2;
        var randomAngle = Math.random() * 6.28 // Get random angle
        this.owner.gameServer.newCellVirused(this.owner, this, randomAngle, this.mass, 350);
    } else {
        this.mass = Math.min(this.mass + n, this.owner.gameServer.config.playerMaxMass);
    }
};
```

**Comment by Megabyte918** [comment]
What exactly would I modify? I don't even know where to start haha

**Comment by Agarian** [comment]
what am i assigned for?

**Comment by Andrews54757** [comment]
I dont understand what they mean. Also, i gave you write access

**Comment by Agarian** [comment]
cool

**Comment by Andrews54757** [comment]
But if i were you, just to be safe from errors, i would do updates in pull request fashion so travis can check it

**Comment by Agarian** [comment]
can i keep it this time? lol last time i remember i was unknowingly assigned for like 20 minutes

**Comment by Andrews54757** [comment]
Yes, that was an accient. (Stupid touchscreen) and now it is real. Also, if you do it in pull request fashion, it would be nice if you create a new branch, not in your fork

**Comment by Agarian** [comment]
how exactly would i do that?

**Comment by Andrews54757** [comment]
On the top left area, there is a box with the words master, click on it and in the text box, type in desired branch name. One warning, when editing that branch, do not click on the big title, small title ok but large title no or else it will bring you to master again

**Comment by Andrews54757** [comment]
Actually, its the area next to the pull request button

**Comment by Agarian** [comment]
CAN YOU REWORD THAT AND WHAT AREA

**Comment by Andrews54757** [comment]
But if it is a small thing such as skins or botnames, youcan edit directly

**Comment by Andrews54757** [comment]
And it is the box next to the green pull request button at home page

**Comment by Agarian** [comment]
dude

**Comment by Andrews54757** [comment]
Just edit directly. I dont care anymore

**Comment by Agarian** [comment]
uhh whatever then?

**Comment by Andrews54757** [comment]
Edit like if you were editing your own repos

**Comment by Megabyte918** [comment]
So uh.. about the modification thing...

**Comment by firelightning13** [comment]
Well ive done like this:

change this line
`this.mass = Math.min(this.mass + n, this.owner.gameServer.config.playerMaxMass);`
to this?
`this.mass = this.mass + n
`
I tested it out and it does work but it seems to decrease too much like below 22500 (like 21k~19k)
It means its too much, need to modify FDMultiplayer, but im lazy to figure it out lol

**Comment by StormGS5** [comment]
im a beginner at coding can someone help i am good at coding but not how make de codes!

**Comment by Andrews54757** [comment]
Added feature in upcoming update. see #182

**Comment by Megabyte918** [comment]
Thank you guys so much for all your help, ive been trying to do this for the longest time :)
