### ISSUE TITLE
Big Buttons

### ISSUE THREAD

**Issue by MizzahHD** [AJS-development/Ogar-unlimited#1371]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
FFA

What version are you on?
17.4.0

What command did you type if any?
None

What Browser are you using? 
Chrome Version 51.0.2704.103 m

You must have a description as well
I'm having these weird Buttons on my Screen. There's like a Mass Shoot Button and a Split Button. How do you get rid of that? http://prntscr.com/bzgx6l

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

**Comment by LegitSoulja** [comment]
Get off mobile

**Comment by LegitSoulja** [comment]
Or don't play in a small resolution

**Comment by firelightning13** [comment]
@MizzahHD This happens to me also, because my laptop have touch screen features. (up to 10 touch points)
Unfortunately, I don't know how to disable it (the button)
