### ISSUE TITLE
Hm Glitch when using bots BOTS TWERKING

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#1372]
Ok so when using 10 bots with 300 mass then it looks like i cant move and it starts to twerk :/
:+1: Please fix! LMAO TWERK?

**Comment by Megabyte918** [comment]
I'll see if I can find why this happens

**Comment by LegitSoulja** [comment]
Its something with the minions.

**Comment by Megabyte918** [comment]
Yeah :/ whenever i use minions i end up getting forced to move towards them, removing them seems to fix the problem however, i never experienced this problem ever since the quad update so maybe that or something else after it caused the bug

**Comment by Agarian** [comment]
I experienced this problem long b4 the quad update.

**Comment by LegitSoulja** [comment]
Yea, I confirm it was after the quad update

**Comment by Megabyte918** [comment]
Well its definitely not a problem with MinionPlayer, I just checked by replacing mine with the old one from 4 months ago, same problem.

**Comment by Megabyte918** [comment]
I have a feeling the problem might be linked to #1113, will look into this later

**Comment by Megabyte918** [comment]
I think I found whats causing the problem, remove the timeout that was added here: https://github.com/AJS-development/Ogar-unlimited/pull/1040/commits/0643f1e830ea851da78f522655ea875482cf431f
I played for about 10 minutes with this removed, and I didn't experience the movement stutter. Let me know what happens for you

**Comment by Megabyte918** [comment]
I legit can't find the problem. I looked through all the PR's from 3 months ago until now line by line searching for anything even remotely related to this bug but I couldn't find anything :/

**Comment by Luka967** [comment]
Was thinking about this for some time. Try manually logging cell movement position/angle wherever it is to see if there's something wrong. I'll do it now.

**Comment by Megabyte918** [comment]
You managed to fix the cell movement? How? Was the fix even related to quadrants?

**Comment by Megabyte918** [comment]
I have a feeling it might be related to #1040 in the edits in cell.js, but I could be wrong. Maybe the movement stutter happens when cells change quadrants?

**Comment by Megabyte918** [comment]
Well that didn't go too well :/

**Comment by Luka967** [comment]
No, I didn't experience any movement problems at all. Only the bots' "twerking".
Today they blocked my c9 account today while debugging this. I had a heavily modified Ogar which contained plugin support, now I have to do it all again...

**Comment by Agarian** [comment]
you could ask them to retrieve it tho

**Comment by NatsuTheGreat** [comment]
^^
