### ISSUE TITLE
MassStart (Plugin)(OgarUL Enhancement)

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#1373]
Ok ok ok, **Note: It can be a game temporary fix now, having 2 configs for bots and players _'wink'_**

> You want a custom player start mass? But bots are spawning as the start mass, or higher and not less?

I've made this plugin to fix your issues. Here's how to use
* in ./settings/config.ini change playerStartMass to 1. 

> (**Now used as bot mass**)(**Use SuperMinions to override**)

<details><summary>Code Source v1.0.0</summary><a href="http://dev.ogarul.tk/data/public/0c3cc3" target="_blank">Source</a></details>
<details><summary>Code Source v1.0.1 (Patch0.2)</summary><a href="http://dev.ogarul.tk/data/public/491b71" target="_blank">Source</a></details>

#### Install method : Command usage

> plugin install MassStart

###### Download & Source

<details><summary>MassStart 1.0.1(Patch0.2)</summary><a href="http://dev.ogarul.tk/data/public/369b1c" target="_blank">Download</a></details>
<details><summary>MassStart 1.0.0</summary><a href="http://dev.ogarul.tk/data/public/a7ac4f" target="_blank">Download</a></details>

###### Contact
> Report any given bugs here, or contact me [here](mailto:support@legitsoulja.info)

###### v1.0.1 Development
* [x] Few bugs fixes.
* [x] Create log system for mass. 
* [x] Remove all plugin lag.
* [x] Better log handler.
* [x] Better MassList display.
* [x] Better, working efficient layout.
* [x] Working on languages, for of my plugins.
* [x] Add more color, for the beauty, and intensity.
* [x] Rescope and retouch the layout.
* [x] Make tests..
* [x] Uploading to plugin database. :+1: [{#37}](https://github.com/AJS-development/OgarUL-Plugin-Library/pull/37)

#### Change MassStart Configuration
* in ./plugins/MassStart/config.ini change playerStartMass to your player(s) start mass.

###### Configurations...
* ```playerStartMass```

> The mass your player's will receive in game. (**IP MassStart may be added in the future**).

* ```notificiation```

> The player will receive an in-game message about there **mass** changes.

##### v1.0.1 Additions
* ```masslist```

> Enable, and disable Mass List usage

* ```ipperplay```

> How many players per IP can join at once.

* ```debug```

> Output some information. Used for debugging.

* ```output``` (Deprecated)

> For those people who don't want nothing showed in the console at all. (Deprecated)

#### Now what?
Now, you are able to have bots in your game less size than players. Any size you are willing to spawn in-game you can. SuperMinions will come handy. **Bots size will spawn with 1 mass** (which you have added) unless there size is declared with SuperMinions, or changed in default(config) just for bots..

When players spawn in the game, there mass thats provided in MassStart config, will be given to only **Players** on join, (**Not bots**).

#### MassStart Commands
* ms [add,set,rem] [id] [mass]

> You are allowed to add, set, or remove certain amount of mass from players.

#### MassStart Commands v1.0.1 Features
* msl [add,rem] [add(id,ip), rem(id,ip,all)] [mass(add,rem)]
* msl reload (Reloads log)

###### That's all folks. This is a very handy, useful plugin.

**Comment by AlexandriteErikParacelsus** [comment]
Ayy @LegitSoulja nice work mate

**Comment by raphyjb** [comment]
will it work with ur plugin Ipbots?

**Comment by LegitSoulja** [comment]
@raphyjb Yes!. Just change the default config playerStartMass to 1, then for ipbots set the mass for the minions under superminions. the minions :).

**Comment by raphyjb** [comment]
gg :+1: Love it!! Just got 2 ip with bots now :P hihi

**Comment by LegitSoulja** [comment]
@raphyjb yes, ill be making a mini version of mass start and ipbots, so new update coming soon.

**Comment by raphyjb** [comment]
We need a fix on Ipbots. Hm, so they dont connect more then 1 time on the server.. :/ (Ill need to change mean while the number of connections per ip.

**Comment by LegitSoulja** [comment]
@raphyjb ok. Ill make those changes to MassStart aswell.

##### ```Updates In Dev // MassStart```
* [ ] Create log system for mass. 
* [ ] Few bugs fixes
* [ ] Rescope and retouch the layout.
* [ ] Make tests..

**Comment by fayizan** [comment]
Thank you so much @LegitSoulja :+1:  ,Yea I could use ipbots now..!!

**Comment by LegitSoulja** [comment]
@fayizan also, timing may be added if I can find out a good way, that woks efficiently, better than ipbots. Nobody have had problems so I might not even change it. I made a really mini log and add system :), so now any plugin could easily use a log system. 

Anyways, still fixing some bugs, but retouching first before fixing. I'll have it finished soon. Note bugs if you have any with ipbots, or massstart

**Comment by LegitSoulja** [comment]
@fayizan @raphyjb @AlexandriteErikParacelsus @systemroot
## Test out the new features
- [Here](http://ogarul.tk/mass/)

**Comment by fayizan** [comment]
wow that was awesome @LegitSoulja, Thank you soo much

**Comment by LegitSoulja** [comment]
@NatsuTheGreat @Agarian @Megabyte918 

Check gitter for something useful. You can store your files, and ability to share them privately. All uploads are privately, and you can share with each other (members). I have shared some my of project, and useful things that will be shared with AJS. Check your gitter inbox for the detaylls.

**Comment by DerpyYT** [comment]
Okay Let me say something, when i set my combineTime: to 0.1 and go into my game, and add >minion 33 40 </random> I start twerking and cant control my cell nor my minions,  but when my combineTime is at 30, its all fine, Please Help I need this solution fixed

**Comment by LegitSoulja** [comment]
@raphyjb you need to update MassStart to v1.0.1. There's a bug where people can get alot of mass on the server because of a bug issue.

**Comment by Astro533** [comment]
whats ipbots?

**Comment by LegitSoulja** [comment]
**ipbots** is a plugin where you can assign bots to specific players using there IP. 

They will get the amount of minions in-game when they join, that is set by the owner.

**Comment by mAIZN** [comment]
very good one thx alot bro

**Comment by DarkZYT** [comment]
This doesn't help me cuz i can already do : change playerStartMass 100 and it works

**Comment by SharkFinPro** [comment]
Will This be added to the plugin library?

**Comment by LegitSoulja** [comment]
@SharkFinPro are you blind?

**Comment by LegitSoulja** [comment]
https://github.com/AJS-development/OgarUL-Plugin-Library/pull/37

**Comment by SharkFinPro** [comment]
no XD

**Comment by DarkZYT** [comment]
i already made my plugin to customize if players or bots or minions spawn with any mass !

**Comment by LegitSoulja** [comment]
@DarkZYT This is better, and efficient. 

Also in the future, with client shops people will be able to buy mass starters, and or minions.

Which won't interfere with any bot sizes. MassStart also collects a data list of players that's assigned to join with specific mass. :)

**Comment by DarkZYT** [comment]
Nice i wonder just if i can get a client so i can modify the html code to create your idea , people will be able to buy skins (made by me or premium agario) or to buy mass starters and bots like you said !

**Comment by LegitSoulja** [comment]
@DarkZYT Well, I'm making the client already, but it won't be public for everyone else to get. Since, many people won't have the proper equipment to run the client to work with those things.

You can download the regular client and customize it they way you like, but I'm re-writing the entire client because it's sloppy

**Comment by LegitSoulja** [comment]
But, with your idea, I'm not doing. I'm making a coin system. Servers can enable this feature to only allow people who bought a skin with coins.

The thing is, you earn coins. You don't buy. Nobody isn't trying to make profit except the server owners, which yes for each server will have there own shop where you can buy things.

Time will tell when I'm done. Maybe 1-2 more weeks

**Comment by DarkZYT** [comment]
Ok then , good luck , i will see if i can make this system or not

**Comment by LegitSoulja** [comment]
@DarkZYT Good luck, because I have everything under control. I don't know about you but, good luck with that.

**Comment by Megabyte918** [comment]
Should this be closed?

**Comment by LegitSoulja** [comment]
Since i've been done with MassStart i guess so.
