### ISSUE TITLE
Every Player have same IP plz help me! i am New but HELP!!!

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#138]
When i started my server i did command >playerlist and i saw every player have same ip i am using a dynamic domain 
![untitled](https://cloud.githubusercontent.com/assets/17459204/13320022/afac8c48-db7a-11e5-804b-eeedcd445c7a.png)

**Comment by Lukkez** [comment]
You need port forwading to see other players ip, this happened with me (Sorry bad English).

**Comment by PrinceDark9243** [comment]
I already port forwarded and can't fix plz help

**Comment by Lukkez** [comment]
Idk why, i can see other players normally

**Comment by PrinceDark9243** [comment]
can you send me you console image so i can server ip is viewing

**Comment by PrinceDark9243** [comment]
- [ ] sa

**Comment by Andrews54757** [comment]
It seems that because of the `192.168` beginning, it is because you used something like weaved or hamachi.

**Comment by Lukkez** [comment]
Or at same network...

**Comment by PrinceDark9243** [comment]
No I don't use any type of these the players are playing from different
countries Plz Help!

**Comment by Andrews54757** [comment]
Well, about that, that is not the problem of the software but more of the problem with your hardware, i guess the hardware isnt as hard as we thought ;)

**Comment by NatsuTheGreat** [comment]
I found your problem.

The problem is you're connected to localhost. You have to connect through your public IP. So it would be: *http://agar.io/?ip=[YourPublicIP]:[Port]*. If the IPs are still the same they're just bots.
