### ISSUE TITLE
Install on linux problem

### ISSUE THREAD

**Issue by Tokoagar** [AJS-development/Ogar-unlimited#1382]
Hey Im on Centos 7 and I go to install node and this happend

[acer@localhost Desktop]$ curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash - sudo apt-get install -y nodes
[sudo] password for acer: 
/bin/sudo: /bin/sudo: cannot execute binary file

Can you tell me why it's doing this?
The command is from the installation from the wiki.

**Comment by systemroot** [comment]
Are you trying to run "apt-get" on centos?! :trollface:

**Comment by Tokoagar** [comment]
idk how it works... If I can,T i wont use it :P

**Comment by systemroot** [comment]
apt-get is debian command, which used in Debian, Ubuntu and some other Modified Distros. 
For centos u'll need to  use "yum", you can install apt-get on centos :v But you will not be able to install nodejs from that link which is based on Debian Distros.
example you can install nodejs like this
**yum -y install build-essential nano wget curl**
**wget http://nodejs.org/dist/v0.10.30/node-v0.10.30-linux-x64.tar.gz**
**tar --strip-components 1 -xzvf node-v* -C /usr/local**
**npm cache clean -f**
**npm install -g n**
**n 5.9.0**
**sudo ln -sf /usr/local/n/versions/node/5.9.0/bin/node /usr/bin/node**

**Comment by Tokoagar** [comment]
Thanks
