### ISSUE TITLE
Error when running on jxcore, 

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#1384]
so i execute the command "jx index.js"
But this happens https://gyazo.com/4950db15131d9afe9b08084feb536082

Anyone know a fix? THANKS

**Comment by LegitSoulja** [comment]
I've tested jxcore, and I have not seen any good performance for ogarul whatsoever.

**Comment by firelightning13** [comment]
Close?

**Comment by Agarian** [comment]
I think i'll close this

**Comment by CalvinDKHD** [comment]
OK thanks got trying though :D  No Sarcasm

**Comment by Agarian** [comment]
I forgot to close =/
