### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1385]
how do you broadcast info out of your ip? I'm making a diepio private server, but can't find out how anywhere

**Comment by NatsuTheGreat** [comment]
>how do you broadcast info out of your ip?

WHAT?!

**Comment by Agarian** [comment]
I think imma close this :neutral_face:

**Comment by SharkFinPro** [comment]
at least answer :/

**Comment by Agarian** [comment]
But whay do you mean?
