### ISSUE TITLE
White bug, map glitch?

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#1386]
hey so i click play and this happens, it basically just is a white screen and twitches now and then.
https://gyazo.com/bab1f5ee21962ecfef22627e42905d30

Fix?

THANKS

**Comment by mrzack506** [comment]
If you own the website, try re-downloading the client from somewhere.

**Comment by CalvinDKHD** [comment]
its a client using js, multiogar works fine. i think its the positioning of the map or something...

**Comment by mrzack506** [comment]
We can't help you with clients. This thread may be closed.

**Comment by CalvinDKHD** [comment]
This is not client sided, happens anyways.... without the client o.o

**Comment by CalvinDKHD** [comment]
and if i was using a client howcome multiogar works?

**Comment by NatsuTheGreat** [comment]
You answer me.

**Comment by CalvinDKHD** [comment]
Natsu u havin same prob? this happens without a client aswell...

**Comment by CalvinDKHD** [comment]
Natsu u got a server? send me link if you do

**Comment by CalvinDKHD** [comment]
Ohh wait, first i tested with a client cause i am making server. THEN without one, same prob...

**Comment by NatsuTheGreat** [comment]
What I meant by "You answer me" was that MultiOgar has multiple protocol support, so it's really compatible with anything. And what are you using as your server and what client?

**Comment by CalvinDKHD** [comment]
Agar plus as a client but I tried without I got the same problem

**Comment by NatsuTheGreat** [comment]
What's your server?

**Comment by CalvinDKHD** [comment]
cellextreme.pw which uses cigar but I am changing
