### ISSUE TITLE
Bots feed bug

### ISSUE THREAD

**Issue by AgarioIsBest1602** [AJS-development/Ogar-unlimited#1387]
What game mode were you in when you had the issue?
Experimental

What version are you on?
17.4.0

What command did you type if any?
minion 1 25, killall, killall

Everytime if i feed my bot, the w's go through him.

**Comment by firelightning13** [comment]
Be more descriptive please

**Comment by Agarian** [comment]
Change `botupdate` in `/src/settings/config.ini` to a lower number, like 1

**Comment by AgarioIsBest1602** [comment]
Its already on 1.

**Comment by Agarian** [comment]
Oh, in not sure then.

**Comment by Megabyte918** [comment]
I couldn't reproduce this glitch

**Comment by Agarian** [comment]
Wait do you mean minions? if so,
Change `minionupdate` in `/src/settings/config.ini` to a lower number, like 1

**Comment by firelightning13** [comment]
@AgarioIsBest1602 Did you change anything in config.ini or advConfig.ini?

**Comment by AgarioIsBest1602** [comment]
@firelightning13 Yes i did.

**Comment by AgarioIsBest1602** [comment]
I know the problem
