### ISSUE TITLE
Splitting 

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#139]
Another problem here.. This is what happens when i have my bots very clever, i am in middle of them and they can just move like this:
![untitled](https://cloud.githubusercontent.com/assets/16438675/13355141/2e03f1f6-dc9f-11e5-84fe-1833b68b7896.png)

**Comment by elitajmx** [comment]
also when i split i can be like this forever:
![untitled](https://cloud.githubusercontent.com/assets/16438675/13355330/17af363a-dca0-11e5-8d5f-cf84ade68084.png)

**Comment by elitajmx** [comment]
Or this kind of thing.
![fs](https://cloud.githubusercontent.com/assets/16438675/13355338/20f3d94e-dca0-11e5-996a-0c9fb044f44b.png)

**Comment by elitajmx** [comment]
And those aren't MINIONS, they are the server bots just so u dont get me wrong :3

**Comment by firelightning13** [comment]
1. That's what bots do
2. In gameserver.ini
- Did u change botupdate = 0?(i nvr tried that bfore)
- Did u change something in playerRecombineTime?(default should be 30)
