### ISSUE TITLE
Client

### ISSUE THREAD

**Issue by MineMooreALT** [AJS-development/Ogar-unlimited#1391]
Hi where do i get the client files

**Comment by AgarioIsBest1602** [comment]
Install the server. Go to the map src, go to settings, go to clientconfig

**Comment by MineMooreALT** [comment]
No I am hosting a website i need the agarclient

**Comment by AgarioIsBest1602** [comment]
Oh than idk

**Comment by firelightning13** [comment]
[#918(comment)](https://github.com/AJS-development/Ogar-unlimited/issues/918#issuecomment-225019348)
