### ISSUE TITLE
Error: 327

### ISSUE THREAD

**Issue by Astro533** [AJS-development/Ogar-unlimited#1393]
OgarUnlimited - Master
module.js:327
    throw err;
    ^

Error: Cannot find module 'collections/sorted-map'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Michael\Downloads\Ogar-unlimited-16.5.7\Ogar-unlimited-16.5.7\src\core\WorldModel.js:5:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Everything was at its default settings. I didn't do anything but run the Install Dependence. Then Just Clicked Start and Run. And this is what I got .
Someone please Help.

**Comment by Astro533** [comment]
I already redownload the file Ogar Unlimited - Master. I also reran the Install Dependence again.

**Comment by Souf123** [comment]
do npm install ws

**Comment by Astro533** [comment]
How do you do npm install ws. Whats ws ?

**Comment by Astro533** [comment]
What I do after that? Here is what happened 
Your environment has been set up for using Node.js 4.4.7 (x64) and npm.

C:\Users\Michael>npm install ws
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ws"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Michael\npm-debug.log

C:\Users\Michael>npm

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install, issues, la,
    link, list, ll, ln, login, logout, ls, outdated, owner,
    pack, ping, prefix, prune, publish, r, rb, rebuild, remove,
    repo, restart, rm, root, run-script, s, se, search, set,
    show, shrinkwrap, star, stars, start, stop, t, tag, team,
    test, tst, un, uninstall, unlink, unpublish, unstar, up,
    update, upgrade, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Michael\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@2.15.8 C:\Program Files\nodejs\node_modules\npm

C:\Users\Michael>

**Comment by Astro533** [comment]
After this I went back to the src folder and clicked Start and this happened 
module.js:327
    throw err;
    ^

Error: Cannot find module 'collections/fast-map'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Michael\Downloads\Ogar-unlimited-master\Ogar-unlimited-master\src\core\WorldModel.js:20:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Press any key to exit...

**Comment by Astro533** [comment]
The only thing that changed was this

First time I clicked Start:
Error: Cannot find module 'collections/sorted-map'

Second time I clicked Start:
Error: Cannot find module 'collections/fast-map'

**Comment by Megabyte918** [comment]
https://github.com/AJS-development/Ogar-unlimited/issues/1335

**Comment by Astro533** [comment]
What is addRemoteGit ?

**Comment by Astro533** [comment]
This what happened when I install collections/sorted-map
It still doesn't work

C:\Users\Michael>npm install collections/sorted-map
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  collections/sorted-map resetting remote C:\Users\Michael\AppData\Roaming\npm-cache\_git-remotes\git-github-com-collections-sorted-map-git-50620412 because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\Michael\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/collections/sorted-map.git C:\Users\Michael\AppData\Roaming\npm-cache\_git-remotes\git-github-com-collections-sorted-map-git-50620412: undefined
npm ERR! git clone --template=C:\Users\Michael\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.com/collections/sorted-map.git C:\Users\Michael\AppData\Roaming\npm-cache\_git-remotes\git-github-com-collections-sorted-map-git-50620412: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  collections/sorted-map resetting remote C:\Users\Michael\AppData\Roaming\npm-cache\_git-remotes\https-github-com-collections-sorted-map-git-96228774 because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\Michael\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/collections/sorted-map.git C:\Users\Michael\AppData\Roaming\npm-cache\_git-remotes\https-github-com-collections-sorted-map-git-96228774: undefined
npm ERR! git clone --template=C:\Users\Michael\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/collections/sorted-map.git C:\Users\Michael\AppData\Roaming\npm-cache\_git-remotes\https-github-com-collections-sorted-map-git-96228774: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  collections/sorted-map resetting remote C:\Users\Michael\AppData\Roaming\npm-cache\_git-remotes\git-github-com-collections-sorted-map-git-290ba2de because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\Michael\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:collections/sorted-map.git C:\Users\Michael\AppData\Roaming\npm-cache\_git-remotes\git-github-com-collections-sorted-map-git-290ba2de: undefined
npm ERR! git clone --template=C:\Users\Michael\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:collections/sorted-map.git C:\Users\Michael\AppData\Roaming\npm-cache\_git-remotes\git-github-com-collections-sorted-map-git-290ba2de: undefined
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "collections/sorted-map"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Michael\npm-debug.log

**Comment by Megabyte918** [comment]
npm install request. I dont know why i had npm install collections/sorted-map in there, i'll change it later

**Comment by Megabyte918** [comment]
make sure your installing the modules directly outside of the /src folder

**Comment by Megabyte918** [comment]
and if it still doesn't work try npm install request.

**Comment by Astro533** [comment]
oh but how do you install from src folder?

**Comment by Megabyte918** [comment]
the same way you did with the other commands but just outside /src

**Comment by Astro533** [comment]
kk

**Comment by Astro533** [comment]
This is what I got for doing the samthing outside of src folder

p-git-290ba2de: undefined
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "collections/sorted-map"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Michael\npm-debug.log

**Comment by Astro533** [comment]
I went and clicked Start and now I'm getting this 

module.js:327
    throw err;
    ^

Error: Cannot find module 'C:\WINDOWS\system32\index.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

Press any key to exit...

**Comment by Astro533** [comment]
This is when I used npm install request this happend still not working please help

C:\Users\Michael>npm install request
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "request"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Michael\npm-debug.log

**Comment by firelightning13** [comment]
@Astro533 Uninstall your current version (node 4.4.7 LTS) and install 5.9.0 [here](https://nodejs.org/download/release/v5.9.0/)

And then delete the "node_modules" folder, then click "Install Dependencies" 

Tell me if it works

**Comment by Megabyte918** [comment]
Do it in the repo folder but outside the src folder. So if you downloaded and extracted the zip to C:\Users\[user]\desktop\Ogar-unlimited-master, you would install the modules in THAT folder. Not outide of that folder, not in the src folder, but in the repo folder (the folder of the zip you extracted). So afterwards after installing the modules, in the repo folder there should be a src folder, a .github folder, and a node_modules folder.

**Comment by firelightning13** [comment]
I think we need video tutorial here

**Comment by Megabyte918** [comment]
Yeah probably but who would do it? I can't cuz my computer isn't powerful enough to record :/

**Comment by Astro533** [comment]
Which version of Node.js should I download though?   

../
docs/                                              16-Mar-2016 20:22                   -
win-x64/                                           16-Mar-2016 20:27                   -
win-x86/                                           16-Mar-2016 20:24                   -
SHASUMS256.txt                                     16-Mar-2016 21:33                2678
SHASUMS256.txt.asc                                 16-Mar-2016 21:33                3569
node-v5.9.0-darwin-x64.tar.gz                      16-Mar-2016 20:15            10221428
node-v5.9.0-darwin-x64.tar.xz                      16-Mar-2016 20:15             7222148
node-v5.9.0-headers.tar.gz                         16-Mar-2016 20:26              471791
node-v5.9.0-headers.tar.xz                         16-Mar-2016 20:26              342924
node-v5.9.0-linux-arm64.tar.gz                     16-Mar-2016 20:13            11722501
node-v5.9.0-linux-arm64.tar.xz                     16-Mar-2016 20:14             7658988
node-v5.9.0-linux-armv6l.tar.gz                    16-Mar-2016 21:10            11487551
node-v5.9.0-linux-armv6l.tar.xz                    16-Mar-2016 21:15             7478880
node-v5.9.0-linux-armv7l.tar.gz                    16-Mar-2016 20:21            11599799
node-v5.9.0-linux-armv7l.tar.xz                    16-Mar-2016 20:22             7568256
node-v5.9.0-linux-ppc64le.tar.gz                   16-Mar-2016 20:13            12162145
node-v5.9.0-linux-ppc64le.tar.xz                   16-Mar-2016 20:13             7829836
node-v5.9.0-linux-x64.tar.gz                       16-Mar-2016 20:15            12254372
node-v5.9.0-linux-x64.tar.xz                       16-Mar-2016 20:15             8393272
node-v5.9.0-linux-x86.tar.gz                       16-Mar-2016 20:14            11817597
node-v5.9.0-linux-x86.tar.xz                       16-Mar-2016 20:14             8029832
node-v5.9.0-sunos-x64.tar.gz                       16-Mar-2016 20:19            13083942
node-v5.9.0-sunos-x64.tar.xz                       16-Mar-2016 20:20             8572264
node-v5.9.0-sunos-x86.tar.gz                       16-Mar-2016 20:16            12158581
node-v5.9.0-sunos-x86.tar.xz                       16-Mar-2016 20:16             7978916
node-v5.9.0-x64.msi                                16-Mar-2016 20:27            11104256
node-v5.9.0-x86.msi                                16-Mar-2016 20:24            10174464
node-v5.9.0.pkg                                    16-Mar-2016 20:22            13236392
node-v5.9.0.tar.gz                                 16-Mar-2016 20:23            22455112
node-v5.9.0.tar.xz

**Comment by firelightning13** [comment]
You have windows x64 bit, so download the node-v5.9.0-x64.msi 16-Mar-2016 20:27 11104256

**Comment by Astro533** [comment]
Ok thx

**Comment by Astro533** [comment]
For some reason its not downloading? Its just saying at bottom left screen  Wating for Node.js.org........

**Comment by firelightning13** [comment]
Its fine for me. Check your internet connection

**Comment by Astro533** [comment]
Its working good but idk why. Talk latter gtg

**Comment by firelightning13** [comment]
@Astro533 Forgot to mention, have you check that your windows is 64 bit or 32 bit?

**Comment by Agarian** [comment]
We don't even use sorted map anymore... we use fast map now don't we?

**Comment by Astro533** [comment]
I have 64 bit

**Comment by Astro533** [comment]
It still not downloading but I guess I'll just wait untill what happens to the download

**Comment by Astro533** [comment]
Nvm It downloaded

**Comment by Astro533** [comment]
Thx for everything :D It worked
