### ISSUE TITLE
Someone made bots for my server!!!!

### ISSUE THREAD

**Issue by WolfOGG** [AJS-development/Ogar-unlimited#1394]
someone keeps joining my server with bots and it lags hard, cant ban him ;-;

**Comment by SharkFinPro** [comment]
umm
are they the ogarUL bots?
or differrent bots

**Comment by Souf123** [comment]
yes he is annoying the servers his yt account =https://www.youtube.com/channel/UCd2-A66PFYs0f736qxyOBFw/featured

**Comment by WolfOGG** [comment]
not minions

**Comment by Megabyte918** [comment]
Why can't you ban him?

**Comment by WolfOGG** [comment]
http://imgur.com/1QWpuNA

**Comment by WolfOGG** [comment]
he did it again server froze

**Comment by WolfOGG** [comment]
can get rid of him i banned him and he joined again

**Comment by Megabyte918** [comment]
Have you tried #566?

**Comment by WolfOGG** [comment]
not yet thank you tho

**Comment by fayizan** [comment]
My server too getting this annoying bot..

**Comment by fayizan** [comment]
![screenshot_49](https://cloud.githubusercontent.com/assets/19163419/17448815/ede9bf98-5b73-11e6-98a9-5b32ee8237a3.png)

**Comment by Souf123** [comment]
Nice

**Comment by fayizan** [comment]
@Souf123 Nice..?

**Comment by Souf123** [comment]
his name : ƦΛƇ🔥Royalty
his yt channel https://www.youtube.com/channel/UCd2-A66PFYs0f736qxyOBFw/featured

**Comment by Souf123** [comment]
ban his ip

**Comment by fayizan** [comment]
@Souf123 How do u know that..?

**Comment by Souf123** [comment]
look at this: 
Raphy No3Lag (Online: 402)(Bots:0)

**Comment by NatsuTheGreat** [comment]
All the IP are the same? Ban it. If that doesn't work, it's a problem with banning itself.

**Comment by Megabyte918** [comment]
Suggest this ip in Uniban requests

**Comment by LegitSoulja** [comment]
@NatsuTheGreat @Megabyte918 the accounts I shared with you on gitter, I'll share the ban list(uniban.txt)  on the  site. You'll be allowed to edit. Use wisely!. This is the play.ogarul.tk site ban. I'll make a way for people to submit, and vote for bans :).

**Comment by Astro533** [comment]
OgarUnlimitedMaster
I have a problem when I click Start in the src folder this is what happens.Please help.

module.js:327
    throw err;
    ^

Error: Cannot find module 'collections/fast-map'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Michael\Downloads\Ogar-unlimited-master\Ogar-unlimited-master\src\core\WorldModel.js:20:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by LegitSoulja** [comment]
go into the Ogar-unlimited folder, NOT SRC,

shift + right click an empty space, then select "open command prompt here, or you can cd to the folder."

After that, once you're in the command prompt, and in that directory, run the command

npm install collections

**Comment by Astro533** [comment]
Please Help I'm having errors

module.js:327
    throw err;
    ^

Error: Cannot find module 'collections/fast-map'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Michael\Downloads\Ogar-unlimited-master\Ogar-unlimited-master\src\core\WorldModel.js:20:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Press any key to exit...

**Comment by Astro533** [comment]
This is my npm-debug Not sure if theres something wrong?


0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'request' ]
2 info using npm@2.15.8
3 info using node@v4.4.7
4 verbose install initial load of C:\Users\Michael\Downloads\Ogar-unlimited-16.5.7\Ogar-unlimited-16.5.7\package.json
5 warn package.json Ogar_Unlimited@16.1.5 license should be a valid SPDX license expression
6 verbose readDependencies loading dependencies from C:\Users\Michael\Downloads\Ogar-unlimited-16.5.7\Ogar-unlimited-16.5.7\package.json
7 silly cache add args [ 'request@2.72.0', null ]
8 verbose cache add spec request@2.72.0
9 silly cache add parsed spec Result {
9 silly cache add   raw: 'request@2.72.0',
9 silly cache add   scope: null,
9 silly cache add   name: 'request',
9 silly cache add   rawSpec: '2.72.0',
9 silly cache add   spec: '2.72.0',
9 silly cache add   type: 'version' }
10 silly addNamed request@2.72.0
11 verbose addNamed "2.72.0" is a plain semver version for request
12 silly mapToRegistry name request
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry data Result {
15 silly mapToRegistry   raw: 'request',
15 silly mapToRegistry   scope: null,
15 silly mapToRegistry   name: 'request',
15 silly mapToRegistry   rawSpec: '',
15 silly mapToRegistry   spec: 'latest',
15 silly mapToRegistry   type: 'tag' }
16 silly mapToRegistry uri https://registry.npmjs.org/request
17 verbose addNameVersion registry:https://registry.npmjs.org/request not in flight; fetching
18 verbose request uri https://registry.npmjs.org/request
19 verbose request no auth needed
20 info attempt registry request try #1 at 10:41:42 AM
21 verbose request id b524f951c260bb7f
22 http request GET https://registry.npmjs.org/request
23 info retry will retry, error on last attempt: Error: unable to verify the first certificate
24 info attempt registry request try #2 at 10:42:58 AM
25 http request GET https://registry.npmjs.org/request
26 info retry will retry, error on last attempt: Error: unable to verify the first certificate
27 info attempt registry request try #3 at 10:43:59 AM
28 http request GET https://registry.npmjs.org/request
29 verbose stack Error: unable to verify the first certificate
29 verbose stack     at Error (native)
29 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:1017:38)
29 verbose stack     at emitNone (events.js:67:13)
29 verbose stack     at TLSSocket.emit (events.js:166:7)
29 verbose stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
29 verbose stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)
30 verbose cwd C:\Users\Michael\Downloads\Ogar-unlimited-16.5.7\Ogar-unlimited-16.5.7\src
31 error Windows_NT 10.0.10586
32 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "request"
33 error node v4.4.7
34 error npm  v2.15.8
35 error code UNABLE_TO_VERIFY_LEAF_SIGNATURE
36 error unable to verify the first certificate
37 error If you need help, you may report this error at:
37 error     <https://github.com/npm/npm/issues>
38 verbose exit [ 1, true ]

**Comment by fayizan** [comment]
![screenshot_54](https://cloud.githubusercontent.com/assets/19163419/17456840/4f422d5a-5c02-11e6-83ff-9adb8c49445a.png)

Ban This ip 213.113.83.231

**Comment by Megabyte918** [comment]
@LegitSoulja how do i get to the banlist? the interface confuses the heck out of me >.<

**Comment by FinalBlu** [comment]
Same IP as fayizan:
![screenshot_2016-08-03-12-19-30](https://cloud.githubusercontent.com/assets/13651170/17458067/cfb451c0-5bbc-11e6-949a-4aaf4b20a998.png)
![screenshot_2016-08-04-08-36-39](https://cloud.githubusercontent.com/assets/13651170/17458068/cfb4989c-5bbc-11e6-94b0-dfbe98685e18.png)

**Comment by FinalBlu** [comment]
Same IP's as fayizan
First image is dark because of an app I use to reduce blue light
![screenshot_2016-08-04-08-36-39](https://cloud.githubusercontent.com/assets/13651170/17458092/7579a664-5bbd-11e6-8e7c-dc36e1acf8a1.png)
![screenshot_2016-08-03-12-19-30](https://cloud.githubusercontent.com/assets/13651170/17458093/757a1de2-5bbd-11e6-893d-c7be47ff15e7.png)

**Comment by WolfOGG** [comment]
this kid is ruining servers http://r-bots.tk/ so I will shut his website down.

**Comment by LegitSoulja** [comment]
Banned. Server Uniban will be uploaded to client bans aswell. 

@Megabyte918 close

**Comment by LegitSoulja** [comment]
@Megabyte918 I had removed the share last night because I was fixing workspaces. I'll share it back with you soon, but I'm traveling ATM.

**Comment by Megabyte918** [comment]
Alright, thanks

**Comment by LegitSoulja** [comment]
I don't really know exactly what bit system they are using. If they are connecting via websocket, or the client (http). 

We may seriously need to update uniban but I don't quiet know the format of how OgarUL reads ban.

**Comment by LegitSoulja** [comment]
Bot* not bit

**Comment by fayizan** [comment]
@ya345 I never can't connect to your server
