### ISSUE TITLE
Random Bots with a bit.ly link to a screamer

### ISSUE THREAD

**Issue by wassupmyagarios** [AJS-development/Ogar-unlimited#1395]
Someone made bots for all the servers, not just mine. And it seems they just freeze and have a link to a screamer, is there any option to make a max number of connections per ip?

**Comment by Megabyte918** [comment]
check out #566 and #1394. And there already is a max connections per ip option, see /src/settings/advConfig.ini

**Comment by Agarian** [comment]
@Megabyte918 i need help connecting to my server with codenvy

**Comment by Agarian** [comment]
Like seriously idk how to do this

**Comment by AlexandriteErikParacelsus** [comment]
@Agarian lol he struggle to join his server too so don't ask him xD
