### ISSUE TITLE
DDOS since a long time ago, Now tired, may retire over here!

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#1399]
<--- Last few GCs --->

105492271 ms: Mark-sweep 211.3 (2450.6) -> 207.3 (2450.6) MB, 123.0 / 0 ms [allocation failure] [scavenge might not succeed].
105492867 ms: Mark-sweep 211.2 (2450.6) -> 207.2 (2450.6) MB, 218.3 / 0 ms [allocation failure] [scavenge might not succeed].
105633450 ms: Scavenge 211.5 (2450.6) -> 208.9 (2450.6) MB, 2.4 / 0 ms (+ 29.7 ms in 6 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x21297dcb4629 <JS Object>
    1: onconnection [net.js:~1403] [pc=0x14a7b1c5750] (this=0x130052cf33d9 <a TCP with map 0x1f78622cb289>,err=0,clientHandle=0x3557a90fff79 <a TCP with map 0x1f78622cb289>)

==== Details ================================================

[1]: onconnection [net.js:~1403] [pc=0x14a7b1c5750] (this=0x130052cf33d9 <a TCP with map 0x1f78622cb289>,err=0,clientHandle=0x3557a90fff79 <a TCP with map 0x1f...

FATAL ERROR: Committing semi space failed. Allocation failed - process out of memory
Aborted
root@vps84427:~/Ogar2/Ogar-unlimited-master/src#

THIS IS WAT I GET EVERYDAY WHILE GETTING DDOS...................................................................
I know i cant fix this, but does someone know how to get the ip of the ddos and hack him? Im pretty sure its someone in the comunity and thats jelous that i got 50 players+ on each server i do, Ive bin here for long enough and i deserve being on the top** 
that said lemme show u something else: http://prnt.sc/c2ovnv
This doesnt show all ddos i get cuz sometimes the person just laggs it out
Anything i can do? Doing a server his shit cuz of the ddos and its wat to do!

**Comment by fayizan** [comment]
Dear @raphyjb ,
**Everyone loves ogarul and your server**,please don't quit it  I would recommend you to limit max connection like I do in my server, I never got jealous on your server but instead got angry sometimes bcoz you have 20 players but 30 spectators

**Comment by raphyjb** [comment]
max connection per ip: 1
i dont like the new situation with bots either!

**Comment by Megabyte918** [comment]
have you read #566 #1394

**Comment by LegitSoulja** [comment]
I'm re-making the client as most will know, and this will be a future I will be implementing. I will put a limit to per connection that's able to visit the site, and also have an automatic uniban feature!.

Besides that, with denial situations, I will have a fix for that as well by patching up leaks of people public IP address. By meaning, patching all connection error event, and clearing console information. Be smart about public source, and obtainable source. I will be planning a good move with this new client. 

**Statistics**:
> WILL NO LONGER EXIST!.

**Comment by LegitSoulja** [comment]
I'll also check for socket security that can be placed into ogarul.

**Comment by Agarian** [comment]
closing for now.
