### ISSUE TITLE
Merge command

### ISSUE THREAD

**Issue by AgarioIsBest1602** [AJS-development/Ogar-unlimited#1402]
When i type merge 1 it gives me 1 bot and if i have bots it says removed  minions... Can somebody help me?

**Comment by Hunter2890** [comment]
same happens for me

**Comment by NatsuTheGreat** [comment]
It's @Agarian 's pull request.. I don't know what the hell he was doing. Let me revert it.

**Comment by NatsuTheGreat** [comment]
#1403 Fixed.
