### ISSUE TITLE
skins

### ISSUE THREAD

**Issue by RevivedSol** [AJS-development/Ogar-unlimited#1406]
what is the size of the skin in pixels. Also give what type of skin should i make

**Comment by RevivedSol** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/18722207/17518437/777c34ee-5e7a-11e6-9e01-19d8ee49f43d.jpg)
 Name - Dragon

**Comment by RevivedSol** [comment]
![army](https://cloud.githubusercontent.com/assets/18722207/17519310/f6c402b0-5e7d-11e6-8cfa-3aba1a6f406d.jpg)

Name - Army/Camouflage

**Comment by RevivedSol** [comment]
![gdfs](https://cloud.githubusercontent.com/assets/18722207/17519889/5e7b5c4e-5e80-11e6-81fb-779b0d8c0f13.jpg)

Name - Appreaciation

**Comment by SharkFinPro** [comment]
the size of skins is a squre XD it doesnt really matter that much

**Comment by Hunter2890** [comment]
@SharkFinPro  size not shape ;p

**Comment by LegitSoulja** [comment]
All images/skins needs to be resized to its appropriate cell image filter. Therfor, no new skins will yet be added to OgarUL Client.

The skin pixel size varies. Many skins i've seen use 508x508, but I normally make skins with 512x512.

**Comment by RevivedSol** [comment]
damn i made it 580x580

**Comment by SharkFinPro** [comment]
u can resize them

**Comment by Souf123** [comment]
Nice skins bro!!!

**Comment by RevivedSol** [comment]
@Souf123. Thanks

**Comment by AgarioIsBest1602** [comment]
Please close this issue

**Comment by NatsuTheGreat** [comment]
Why?

**Comment by LegitSoulja** [comment]
Because, skins isn't needed right now.

**Comment by NatsuTheGreat** [comment]
Okay.
