### ISSUE TITLE
How do you use multiverse?

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1407]
i do:
`multiverse create SharkFin 444 89`
and it still asks me for another port :/

**Comment by NatsuTheGreat** [comment]
You probably mixed up the arguments.

**Comment by Agarian** [comment]
you do not include the status port... just do 
`multiverse create SharkFin 444`

**Comment by SharkFinPro** [comment]
When i try that it asks me for a port
