### ISSUE TITLE
since when did custom skins make the cell color transparent?

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#141]
![capture](https://cloud.githubusercontent.com/assets/15255724/13367992/cb18e55e-dcb4-11e5-9edc-e014b6eeabc1.JPG)

**Comment by Agarian** [comment]
can u make this a config? its cool but not for like all time tho

**Comment by Lukkez** [comment]
How u make this? LOL

**Comment by Agarian** [comment]
i added a custom skin that contains a grid for a back ground 
for example(go to this link):
https://www.google.com/search?q=illuminati&rlz=1C1AFAA_enUS432&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi_t6CgyZbLAhWLJh4KHd-sAu8Q_AUIBygB&biw=1024&bih=643#imgrc=86XK6V_xmaj-FM%3A
notice the grid meaning its empty space.

**Comment by firelightning13** [comment]
Pictures always do that, leaving some areas empty

**Comment by firelightning13** [comment]
But the pictures that makes the cell transparent is really amazing xD

**Comment by Agarian** [comment]
ddnt b4

**Comment by Megabyte918** [comment]
That's actually pretty cool! now I can have a skin that's almost exactly like the grid :P

**Comment by Megabyte918** [comment]
okay there we go, use this name for completely transparent skin xD
[v.ht/rx5A]

**Comment by firelightning13** [comment]
Nice can i use ur skin :3?

**Comment by Megabyte918** [comment]
Sure m8

**Comment by Lukkez** [comment]
What's your server?

**Comment by Andrews54757** [comment]
At the server showcase area here #56
