### ISSUE TITLE
the override.ini

### ISSUE THREAD

**Issue by rydens** [AJS-development/Ogar-unlimited#1410]
Do you think you could explain a bit more in-depth about how to use the `config.ini`?

Thanks,
rydens

**Comment by SharkFinPro** [comment]
its simple
you just copy whatever values you want to keep from config.ini when it updates in override.ini
close this

**Comment by rydens** [comment]
But what do you mean by "values"? For example, if I wanted to keep `serverPort`, would I put in the `override.ini` 
`serverPort`  or would I put `serverPort = 443`, or would I put something entirely different?

Thanks,
riders

**Comment by rydens** [comment]
And for that matter, could it include configs from `advConfig` or just `config`?

**Comment by SharkFinPro** [comment]
only config.ini i think - but possibly not

**Comment by Agarian** [comment]
It can include all configs

**Comment by rydens** [comment]
Okay, but what about the format of the "values"?

Thanks,
rydens
