### ISSUE TITLE
NoCollisionTeam Z Is Missing in Ogar Unlimited Gamemode?

### ISSUE THREAD

**Issue by UltraSirius** [AJS-development/Ogar-unlimited#1411]
I've Seen Theres No NoCollisionTeamZ In The Gamemode Of Ogar Unlimited.

I Only See noCollisionTeam And NoCollisionteam X Is.....

And i need NoCollisionTeamZ because i will create a server...

is there anyone can help me?

**Comment by SharkFinPro** [comment]
:|
its not missing - its just _not_ there

**Comment by LegitSoulja** [comment]
Some gamemodes was removed because they were either the same, or didn't work.

You'll have to talk to @Agarian about the gamemodes.

**Comment by Megabyte918** [comment]
@UltraSirius NoCollisionTeamZ was removed because it supposedly caused "lag", see this PR: #1113. If you want to have it back, just re-add the file.
