### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by MizzahHD** [AJS-development/Ogar-unlimited#1413]
Alright for some reason, i can't connect to my Server with the ipv4 address. I can only use the Localhost IP. A couple of minutes ago, i was still able to play on my Server with the IPV4 Adress, i don't really use my Localhost one. Now all of a sudden, i can only play on my Localhost IP. Let me give you some Screenshots here. http://prntscr.com/c5d1i5 http://prntscr.com/c5d1rf

**Comment by SharkFinPro** [comment]
this isn't an ogarUL issue... close this now
