### ISSUE TITLE
what is this 

### ISSUE THREAD

**Issue by supportAC** [AJS-development/Ogar-unlimited#1419]
I trying making a border like agar.io , but have a problem
![image](https://cloud.githubusercontent.com/assets/20979049/17669860/b947ab46-62e5-11e6-9d94-3d9a226615b3.png)

what is this?

i mean wing green part of the cell That you can see

**Comment by NatsuTheGreat** [comment]
That is because you are splitting and we can see the graphics aren't very fast to update it. That will be gone once the split is done.

**Comment by supportAC** [comment]
how to fix this?

**Comment by NatsuTheGreat** [comment]
Go ask the client owners.
