### ISSUE TITLE
cannot do npm install

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#142]
C:\Users\owner\Downloads\src>npm install
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.0
npm ERR! npm  v2.14.7
npm ERR! path C:\Users\owner\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open 'C:\Users\owner\pa
ckage.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\owner\Downloads\src\npm-debug.log

now i cant play on my server.

**Comment by ItzLevvie** [comment]
That error means that package.json doesn't exist on the directory 'C:\Users\Owner\pa
ckage.json'.

**Comment by Agarian** [comment]
then what do i do???

**Comment by Andrews54757** [comment]
Drag your folder to a different directory other than downloads

**Comment by Andrews54757** [comment]
It is probably because you deleted everything except for the src folder seeing that i dont see /ogar-unlimited/ folder

**Comment by Agarian** [comment]
**no diff:**

C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\Ogar-unlimited-ma
ster\src>npm install
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.0
npm ERR! npm  v2.14.7
npm ERR! path C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\Oga
r-unlimited-master\src\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open 'C:\Users\owner\De
sktop\Agar.io Stuff\Private servers\Ogar-devs\Ogar-unlimited-master\src\package.
json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directo
ry.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\Ogar
-unlimited-master\src\npm-debug.log

**Comment by Agarian** [comment]
fine now.
