### ISSUE TITLE
supermininon not working1!111

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#1420]
+supermiinoon spawnmass not wroking hyelp

**Comment by Agarian** [comment]
?

**Comment by elitajmx** [comment]
superminion 1 10 abc (SPAWNMASS) <-- NOT F*CKING WORKING

**Comment by elitajmx** [comment]
i have mass 44 on config and if i put spawnmass for a minion like 10 it  doesnt work

**Comment by elitajmx** [comment]
also the food(small rainbow cells) are not spawning properly.. 5 dots on like 40 minutes

**Comment by Souf123** [comment]
same

**Comment by AlexandriteErikParacelsus** [comment]
Because the damn playerspawnmass is 44 and it can't fucking get down to 10, holy shit i'm tired of these idiotic issues.

**Comment by NatsuTheGreat** [comment]
Use ```SuperMinions``` and ```MassStart```

**Comment by elitajmx** [comment]
great so how am i supposed to play with bots then, if i set the spawnmass to 10, bot's spawn with 10 mass, and if there is no dots they cant get big, how do i like........
