### ISSUE TITLE
Why is this happening?

### ISSUE THREAD

**Issue by mrzack506** [AJS-development/Ogar-unlimited#1421]
Why are there two ips and 2 ids? This isn't for one person either. I also believe it's a source of lag. Help? 
![whyyy](https://cloud.githubusercontent.com/assets/19736068/17736365/6d05339a-6455-11e6-8112-1635056a78af.JPG)

**Comment by ya345** [comment]
I've seen these on my servers: usually someone who was already playing on your server accidently reconnected - they'll go away if that person isn't using another tab on your server
