### ISSUE TITLE
Players spam in chat Help!!!!

### ISSUE THREAD

**Issue by eevaqueen** [AJS-development/Ogar-unlimited#1425]
![rara](https://cloud.githubusercontent.com/assets/17146668/17826428/92a532b8-6625-11e6-85fa-900adfc4d5f9.jpg)
some bad players spam like this screenshot, There is no way to mute them without close holy chat with hidden chat?
need help please thanks!

**Comment by GhostShot3** [comment]
Change values
Ogar-unlimited-master\src\settingsconfig.ini
`chatIntervalTime = ?`
`chatMaxMessageLength = ?`

**Comment by Megabyte918** [comment]
Or just ban the person =D

**Comment by GhostShot3** [comment]
@Megabyte918 Ya
