### ISSUE TITLE
Ploblem with lag

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#1427]
When i add 20+ bots it lags.
2.90 ghz

**Comment by SharkFinPro** [comment]
its ur computer&wifi

**Comment by GhostShot3** [comment]
@SharkFinPro No my computer is good and my internet too.

**Comment by NatsuTheGreat** [comment]
How much computer ram? What ping, download, upload speed?

**Comment by GhostShot3** [comment]
RAM :3,00
Ping :Realtime
Downloa and,upload :5.20,6.76

**Comment by NatsuTheGreat** [comment]
Check out (this)[http://speedtest.net] Those results don't seem right to me.

**Comment by GhostShot3** [comment]
@NatsuTheGreat I will test in your site.

**Comment by GhostShot3** [comment]
Tested,results:

**Comment by GhostShot3** [comment]
Ping:2ms
Dowload Speed:5.51 (mbps)
Upload Speed:6.80 (mbps)

**Comment by NatsuTheGreat** [comment]
Your ping is very good, download speed is slow. Upload speed is good.

**Comment by GhostShot3** [comment]
In another site ping is 0ms(realtime),in your site is 2ms.

**Comment by NatsuTheGreat** [comment]
Your download speed is quite slow.

**Comment by GhostShot3** [comment]
@NatsuTheGreat Oh,it make OgarUL lagging for me ?

**Comment by NatsuTheGreat** [comment]
It makes your internet lag, which is probably what lags your server.

**Comment by GhostShot3** [comment]
@NatsuTheGreat Suggests any solution?

**Comment by NatsuTheGreat** [comment]
Get a better modem.

**Comment by GhostShot3** [comment]
@NatsuTheGreat Close.

**Comment by GhostShot3** [comment]
@NatsuTheGreat Just curious what your download speed, upload speed and ping ?

**Comment by NatsuTheGreat** [comment]
ping 24, download 22, upload 2.

**Comment by GhostShot3** [comment]
@NatsuTheGreat THX

**Comment by SharkFinPro** [comment]
Mine:

Ping: 11 ms.
Download: 17.01 mbps.
Upload 5.95 mbps.

I have a G router :/

**Comment by NatsuTheGreat** [comment]
That's a nice result :)

**Comment by GhostShot3** [comment]
@SharkFinPro Ah sorry for disagree,is the internet really.

**Comment by ItzLevvie** [comment]
My internet :P

Ping : 11 ms
Download : 104.60 Mbps
Upload : 6.48 Mbps

**Comment by GhostShot3** [comment]
you dowload is 1 mega ?

**Comment by ItzLevvie** [comment]
104 mbps

**Comment by NatsuTheGreat** [comment]
104?? How much do you pay?

**Comment by ItzLevvie** [comment]
£37.25/m

**Comment by NatsuTheGreat** [comment]
Dayum!

**Comment by firelightning13** [comment]
what.

**Comment by GhostShot3** [comment]
@Agarian Why you modify my issue ?

**Comment by Megabyte918** [comment]
typo

**Comment by GhostShot3** [comment]
@Megabyte918 Where ?

**Comment by firelightning13** [comment]
lol

**Comment by GhostShot3** [comment]
Really.
