### ISSUE TITLE
Moving like a minion

### ISSUE THREAD

**Issue by SevenSlayy** [AJS-development/Ogar-unlimited#1431]
What game mode were you in when you had the issue? Experimental

What version are you on? 17.4.0

What command did you type if any? minion 1 100 

You must have a description as well: My cell like moves weird when using minions
https://gyazo.com/4dd2b1871395aea8ebc1645a03daf38f

**Comment by SevenSlayy** [comment]
ignore the part where it says bagar.io i like playing with random names

**Comment by SevenSlayy** [comment]
im a noob with this

**Comment by UltraSirius** [comment]
happens to me..

**Comment by RevivedSol** [comment]
Lol never happened before

**Comment by SevenSlayy** [comment]
@UltraSirius its so dumb
i think i found the source of the bug but im a bit bad at coding so idk 
there are lines checking for small people and big people `  getBiggest(list) {
    // Gets the biggest cell from the array
    var biggest = list[0];
    for (var i = 1; i < list.length; i++) {
      var check = list[i];
      if (check.mass > biggest.mass) {
        biggest = check;
      }
    }

    return biggest;
  };`

**Comment by Hazani** [comment]
Well thats happens me too.So try to play with older versions.I hope its fixed.Itsnt fixed then it can be problem with nodejs your coumputer or connection.

**Comment by NatsuTheGreat** [comment]
How would that affect anything @SevenSlayy It's the script for the bots, not you lol.

**Comment by TYTheBeast** [comment]
Natsu the code it's right i think when my bots split and try to merge back they get your cell move to merge in them too! That's why there are problems like moving as a minion.

**Comment by NatsuTheGreat** [comment]
What are you talking about? That code has nothing to do with the merging of bots. Infact that does not affect the movement AT ALL.

**Comment by Agarian** [comment]
And that function may be needed for the "minionavoid" config.

**Comment by SharkFinPro** [comment]
@everyone
I think that the source of this issue is LAG! SevenSlayy was probably abusing their , as that is what it looks like to me
@SevenSlayy Did you look at your CPU usage on task Manager?

**Comment by NatsuTheGreat** [comment]
^^ Exactly! It's lag, minion movement won't affect player movement in any way...

**Comment by SevenSlayy** [comment]
@SharkFinPro node.js is using around 0% to 30%
The agario game is using about 3%
Nothing else open

**Comment by SevenSlayy** [comment]
and if anything else my graphics card is a Intel iris 6100

**Comment by UltraSirius** [comment]
Lets Make this Easier: If I Control Minions and i died. my mouse dont go at my direction where my mouse is pointed,while my bigger minion is trying to get me up... do you get it?  so its 100% Bug... bigger minions wil attract my cell up to him

**Comment by SevenSlayy** [comment]
yep

**Comment by firelightning13** [comment]
@UltraSirius It's basically caused by lag. Sometimes it happens to me too

**Comment by SevenSlayy** [comment]
@firelightning13 its not lag. since it runs super smooth until i die to a minion, then it starts moving me towards the minion i died too, still smooth though. ITS NOT LAG!

**Comment by SharkFinPro** [comment]
It is Lag XD
#1435

**Comment by UltraSirius** [comment]
Lol Lag? But my cpu percentage is about 40 - 50%

**Comment by SevenSlayy** [comment]
i have:
Intel i3 5157U 2.7GHz
8gb ram

**Comment by SevenSlayy** [comment]
I'm pretty sure its a bug. It wasnt happening before updating
extracting my original zip and putting and old version stops it

**Comment by AlexandriteErikParacelsus** [comment]
Oh is this the same as the cell twerking bug thingy?

**Comment by SharkFinPro** [comment]
@SevenSlayy 
i3 and 8 GB ram will make ur server lag with bots XD
You cant use 100 bots like that :P

**Comment by LegitSoulja** [comment]
Maybe, everyone is in this issue right now should learn how OS(s) works. Because this was very sad to read.

**Comment by UltraSirius** [comment]
Like @LegitSoulja said 9/10 its the packethandler or Sockets Of Minions.

I Dont Understand. I will try to look at the Sockets,Player And Loader For Minions Cuz I will look for the bugs if necessary, Right Now We Dont know what is it.

Like A Player Cell,Minions Are Controllable Unlike Those Minions/Bots In Agar.io Our Ogar Unlimited Minion Is Very Special.

But We can Fix All The Bugs If We..................... help each other,Learn Using LSL,C++ And Javascript, (Now i am good at scripting) and programming (7/10 just little bit) But I am Using Wordpad For Just Normal. because i have C++ i dont have javascript and i have node.js.

So Its Not a Lag, Its Not A Bug Its 100% Some Conclusion (fixes that was applied) For Like PacketHandler. We Must All Know Using Program Not Just All AJS Admins will fix it all, but we volunteer it. (oh also i am speaking generiosly)

**Comment by LegitSoulja** [comment]
@UltraSirius LOL what are you talking about??
> ,Learn Using LSL,C++ And Javascript,

Do you even know what LSL is? You just read that from me and have no clue what it is. Maybe you should chill, and focus on school instead of trying to get into other things.

**Comment by UltraSirius** [comment]
but i just wanted to help. i am just asking are these codes are bugged. then warn me? fuck i am a nonsense  member in this ogar github. soooo thanks for warning it :) i am a fucking idiot boy. now you see. no more. i will not a add something thats all i will say.

**Comment by SevenSlayy** [comment]
so apparently my i3 cant handle a circle game but it can handle 720p games recording at 60fps at max settings? k

**Comment by LegitSoulja** [comment]
@UltraSirius im not teacher. So im not teaching anything. And im not leaving no negative comments, it's just that you said that 

> But We can Fix All The Bugs If We..................... help each other,Learn Using LSL,C++ And Javascript

How will learning LSL benefit OgarUnlimited, or coding in any way?

**Comment by NatsuTheGreat** [comment]
13 and in 6 grade? Hmmm

**Comment by SharkFinPro** [comment]
@NatsuTheGreat I Have A friend that Will be 13 when he is in 6th grade :/ im 12 in 7th grade

**Comment by NatsuTheGreat** [comment]
Around what region do you live?

**Comment by SharkFinPro** [comment]
What do u mean?
PST <--Time ZOne

**Comment by NatsuTheGreat** [comment]
Like I don't know how you would be 13 and in 6th grade without getting held back :/ I live in the US so I don't know if anything's different age wise where you live (if you don't live in the US)

**Comment by ItzLevvie** [comment]
I'm 13 and I'm in 9th grade :P

**Comment by NatsuTheGreat** [comment]
Hang on, are you a boy or girl?
