### ISSUE TITLE
Game runs really badly unless I am clicked out of chrome

### ISSUE THREAD

**Issue by KingColstons** [AJS-development/Ogar-unlimited#1434]
When I open the cmd box and join the server, it runs like absolute horse shit, however when I go to type commands, the game runs perfectly. I can obviously move my cell but if I try and split it just types in the command box (obviously). Then I click back into my browser and it does back to what it was before. 

Can anyone help? My server version is 17.4.0 and I am on FFA.

Thanks

~KingColstons

**Comment by SharkFinPro** [comment]
I think you are abusing ur CPU
Close this issue now

**Comment by SharkFinPro** [comment]
#1435

**Comment by LegitSoulja** [comment]
Don't use default chrome. It's shitty.

**Comment by Megabyte918** [comment]
`var chrome = ROASTED;`

**Comment by Agarian** [comment]
```javascript
var firefox = betterPerformance;
```

**Comment by UltraSirius** [comment]
Opera has better performance too?

**Comment by firelightning13** [comment]
var ChromeCanary = evenBetterPerformance;

**Comment by LegitSoulja** [comment]
@firelightning13 love it. I was hoping someone was going to through that out lol.

**Comment by LegitSoulja** [comment]
Throw. Haha

**Comment by LegitSoulja** [comment]
Chrome don't become shitty unless you don't manage it, and use extensions, and extra scripts.

**Comment by LegitSoulja** [comment]
For ogarul.tk. If you keep refreshing slow and slow the page will load slow. Caching, cause by query caching on some files. Bad in my opinion after realizing.

**Comment by Agarian** [comment]
Maybe i should try chrome canary

**Comment by MineMooreALT** [comment]
use oprea its 10x better than firefox

**Comment by LegitSoulja** [comment]
Canary is 100x faster, smarter, and optimizable, and still in development.

Fair shot for everyone to use the new gen of chrome :)
