### ISSUE TITLE
Do You Have Really Bad Lag?

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1435]
If you have really bad lag on your server, and there are only a few players, or alot - the most common issue is you are abusing your CPU.

First, think about how much RAM you have, and what kind of Processor you have.
Then, Check Task manager and look at your CPU usage. If CPU is at 100%, it means it is probably trying to go over 100%. Which will cause lots of lag.

Some ways to fix are:
1. Stop streaming music from YouTube or other streaming services.
2. If your computer is syncing something like OneDrive, close OneDrive completely so your computer isn't constantly Syncing.
3. If you have any other apps open like a recording app, close it - because it will use alot of CPU.
4. Change game settings so that it is not as hard on your computer.

This should fix it. if it doesn't, you probably have too slow of a processor, or not enough RAM.

@Devs
Please don't close this, but instead put the FAQ label, and the Info label on this thread.

**Comment by LegitSoulja** [comment]
I use this cool memory/game booster software which kill unessary processes. 

Also, turn off all programs on boot those gets annoying.

Another, if your CPU is overclocked you should've have problems. I never really had many bad problems with ogarul.

**Comment by ya345** [comment]
Any tips for a linux VPS?

**Comment by SharkFinPro** [comment]
@ya345 If you dont know how ot use it, dont ask here - ask somewhere else, this is off-topic :/

**Comment by UltraSirius** [comment]
Is My Specs Are good?

RAM:4GB (DDR3)
Processor: Intel Core TM I3 -2100CPU 3.10GHz 3.10GHz 
GPU: None But I am Still Buying
Video Memory: 1682MB (If U Want Proof)

So Are These Good For Hosting OgarUL? 

Infact I Have Avast Premier Anti-Virus Since I Have 0% Process On my CPU Now I have 25%

**Comment by RevivedSol** [comment]
@ultraSirius its quite good already but if your can ,  get i5 and 8gb ram

**Comment by SharDX** [comment]
So i have a intel i7 8 cores @ 3.5ghz
a gtx 860 with 4GB of vram
8 gb of ram
AND A FKIN 1.5MBPS ! i cant play nor agar or ogarul ;'(
i crei evry tim

**Comment by SharDX** [comment]
@UltraSirius 
Sir how do you have Video Memory without having a GPU ? 
The GPU comes with Video Memory unless you mean ram ?

**Comment by RevivedSol** [comment]
@SharDX what do you mean that u can't play ogarul?

**Comment by RevivedSol** [comment]
@UltraSirius how do u even have video memory when you have no gpu?

**Comment by firelightning13** [comment]
@RevivedSol @SharDX It's called "integrated graphic card", it allocates RAM and uses it for video memory
