### ISSUE TITLE
How do i get custom skins on http://play.ogarul.tk/ anyone know? PLEASE HELP! 

### ISSUE THREAD

**Issue by IKingKev** [AJS-development/Ogar-unlimited#1438]
people say type it in customskin.txt but not telling me how to do so someone plz help me fully and not 50%

**Comment by Agarian** [comment]
Ok first get the skin's image link, say you want to use this skin:
`https://s-media-cache-ak0.pinimg.com/736x/41/99/ed/4199edcef653e72fa3dd9b9bb629f2f5.jpg`
It is an awesome face skin. Now, decide what name you want to use for the skin, lets just use `awesome`.
This is how you would type it into ``customskins.txt:``
```awesome :https://s-media-cache-ak0.pinimg.com/736x/41/99/ed/4199edcef653e72fa3dd9b9bb629f2f5.jpg```
So now to get the skin in game, use the name <awesome>
And use this process for all other custom skins.
