### ISSUE TITLE
codenvy

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1439]
@Megabyte918 I FOUND OUT HOW TO USE CODENVY - FINALLY
Dont CLose This Issue Untill mega byte responds plz
:D
:D
:D
:D
yayyayayayyayayayayay
Free web IDE with up to 32GB Ram :D
yay
Awesomeness
finally :D

**Comment by Agarian** [comment]
Then how?

**Comment by SharkFinPro** [comment]
Its Simple

**Comment by Megabyte918** [comment]
take this to discord pls =D

**Comment by fayizan** [comment]
why closed this..?

**Comment by NatsuTheGreat** [comment]
What is with codenvy?...

**Comment by SharkFinPro** [comment]
its good - possibly better than c9

**Comment by SharkFinPro** [comment]
up to 4 GB ram to start, and you cna buy up to 200GB ram
200GB RAM for 1 hour costs 50$

**Comment by Agarian** [comment]
well how do i connect to my server in codenvy?? that's the only problem i've had

**Comment by Megabyte918** [comment]
Please don't explain it here, i dont want it to turn into c9 again when they have to start blanket banning.

**Comment by SharkFinPro** [comment]
@Agarian Ill Tell u on discord, PM Me
