### ISSUE TITLE
Real agar.io virius mechanics 

### ISSUE THREAD

**Issue by StormGS5** [AJS-development/Ogar-unlimited#144]
i cant popsplit in my server if u dont know what it is look up agario popsplit on youtube can u make it possible ?

**Comment by Agarian** [comment]
same

**Comment by Andrews54757** [comment]
What happens when you try to do it

**Comment by Agarian** [comment]
ill make gif

**Comment by Agarian** [comment]
![popsplit](https://cloud.githubusercontent.com/assets/15255724/13376011/6d9e6e16-dd7d-11e5-82e0-a4baf6ed0555.gif)

**Comment by Agarian** [comment]
that^

**Comment by Andrews54757** [comment]
WTF, WHY DOES IT DO THAT!!!

**Comment by Agarian** [comment]
idfk

**Comment by NatsuTheGreat** [comment]
That one was a little too close.

**Comment by PrinceDark9243** [comment]
sometimes it works i tried it. The chances of work and dosent work i think is 10.32% WORK 89.68% 
DOSENT WORK

**Comment by StormGS5** [comment]
i tried only works if u  put max cells to 32  damn ill try to code some and figure out how to make it and ill give you the code

**Comment by StormGS5** [comment]
i figured it out the splitting is not the same ogar master has real agar.io splitting but not the smooth splitting i know that the owner of http://agar.io/?ip=parisgamma.iomods.com:1501

**Comment by StormGS5** [comment]
and you must be half the size of the person u want to popsplit i do it all the time in real agar.io success rate is %90

**Comment by Lukkez** [comment]
I want popsplit too, i already lose much mass trying to make popsplits, fuuu, i only feed the guy when i try

**Comment by StormGS5** [comment]
i know

**Comment by Megabyte918** [comment]
You split too slow which caused your first cell to clear the virus and not go into the bot

**Comment by Megabyte918** [comment]
I think the problem might be the virus split speed in virus.js

**Comment by Andrews54757** [comment]
I just don't know how to make it so it does work. I need a person who knows lots of physics. Ask @retslac on doing it. He is a good physics-person

**Comment by retslac** [comment]
I've never really tested popsplit before, but i'm planning to.  Does anyone know how big both cells can or should be for it to work?

**Comment by retslac** [comment]
Just did a little quick and dirty test and popsplit seems to work pretty good.  I made 2 small changes.
I'll post here what i changed.  Hopefully it works for Ogar Unlimited as well.

remove this.getSquareSize() from cell.collisionCheck2
```
return (dx * dx + dy * dy <= objectSquareSize);
```

add extra check in gameserver.updateMoveEngine
```
if (check.cellType == 0) {
    if ((client != check.owner) && (cell.mass < check.mass * 1.25)) { //extra check to make sure popsplit works
        check.inRange = false;
        continue;
    }
    len--;
    if (check.nodeId < cell.nodeId) {
        i--;
    }
}
```

**Comment by NatsuTheGreat** [comment]
Come one discord with me @retslac

**Comment by retslac** [comment]
@NatsuTheGreat sry man, some other time maybe, was just about to quit

**Comment by NatsuTheGreat** [comment]
@retslac It's giving me bugs.

**Comment by Megabyte918** [comment]
Dont give up @retslac ! You must stay determined!

**Comment by Megabyte918** [comment]
Also, thank u for making virus throws possible. You truly are a master coder :3

**Comment by retslac** [comment]
@NatsuTheGreat what bugs do you have?

**Comment by firelightning13** [comment]
@Megabyte918 Wow cool

**Comment by NatsuTheGreat** [comment]
@retslac I was able to fix them. Can you come on discord today?

**Comment by retslac** [comment]
@NatsuTheGreat Not much time today.  Have some other things to do, but if you've got a quick question...

**Comment by NatsuTheGreat** [comment]
@retslac I alwayd get lag when I popsplit it has never been there before. why?

**Comment by retslac** [comment]
Did it start happening after you made the 2 changes above?  Does it only happen when you popsplit?

**Comment by NatsuTheGreat** [comment]
It kinda happens when my cells are done not colliding when split in a lot. But mainly I get that lag spike while popsplitting. When I first had the smooth splitting with the pushing it didn't happen. Do I need simple collide?

**Comment by retslac** [comment]
Not sure what causes the lag.  Probably something in the collision code.  But i think you have almost the same collision code as me and I don't have any lag!?

**Comment by NatsuTheGreat** [comment]
Try popsplitting with someone else I get a tiny lag spike when I eat the guy. I don't have simple collide, do I need that?

**Comment by retslac** [comment]
You have simpleCollide in Cell.js

**Comment by NatsuTheGreat** [comment]
Oh. I don't need it in PlayerCell.js?

**Comment by retslac** [comment]
No, not needed if you have it in cell.js.

**Comment by NatsuTheGreat** [comment]
Let me check.

**Comment by NatsuTheGreat** [comment]
Yes I have it.

**Comment by NatsuTheGreat** [comment]
It's just a lag spike (about 1 second) when the guy pops and I eat it all.

**Comment by retslac** [comment]
strange, try to find out if lag spike occurs right on the moment that collision is restored.  Maybe set restore collision ticks higher and lower to test?

**Comment by NatsuTheGreat** [comment]
I found out when it happens. It happens right when I eat the guy that got popped.

**Comment by retslac** [comment]
Is your server running right now?

**Comment by NatsuTheGreat** [comment]
Yes it is, it's paused though. You want to join?

**Comment by retslac** [comment]
ok, i'm joining right now

**Comment by NatsuTheGreat** [comment]
Okay, i'll unpause it.

**Comment by retslac** [comment]
@NatsuTheGreat Don't know what causes the lag.  I even ran your server on my localhost but i'm not getting that lag spike here.  Might be because i have a really fast computer?

**Comment by Andrews54757** [comment]
I think it is just the bad foundation of ogar. we are trying to improve. see #196

**Comment by Andrews54757** [comment]
also, do you wanna play  here http://agar.io/?ip=ogar-unlimited-andrews54757.c9users.io ? Il give you op

**Comment by Andrews54757** [comment]
nvm, im leaving, but the server will be up

**Comment by retslac** [comment]
how do you start game?

**Comment by Andrews54757** [comment]
Do you mean get past the verification system?

**Comment by Andrews54757** [comment]
to get past the verification system, you are given a code.
press w.
type code in nickname box
press play
press w

**Comment by retslac** [comment]
ok that worked but north Korea just killed me after 1 sec
gonna try again :)

**Comment by Andrews54757** [comment]
you only need to do that once in the game

**Comment by Andrews54757** [comment]
also, i dont understand why your name is 803 as it saves the name you choose when you joined

**Comment by retslac** [comment]
yeah that was me, i tried joining with that name

**Comment by retslac** [comment]
was that you Lol

**Comment by Andrews54757** [comment]
yes

**Comment by retslac** [comment]
jee man, don't know what the hell is goin on, i just exploded into bits

**Comment by Andrews54757** [comment]
i know, its a feature called the explode virus that ops can use

**Comment by Andrews54757** [comment]
now you have op

**Comment by retslac** [comment]
now that was funny, i just gobbled up the whole map
needs some gettin used to, that OP thing, didn't know what the hell i was doing

**Comment by Andrews54757** [comment]
read the readme and you will find out

**Comment by retslac** [comment]
yeah, i already did
but i couldn't remember which key was for what

Well, that game was funny as hell!!!  Nice work there! :+1: 

It's getting late here, so i'm gonna go.

**Comment by Andrews54757** [comment]
okay, bye
