### ISSUE TITLE
Thanks and bye

### ISSUE THREAD

**Issue by SharDX** [AJS-development/Ogar-unlimited#1441]
@Andrews54757 
hia ,  after i saw the post about andrews closing or abandoning the project if he couldnt get 2000$ in a month for charity and he said that we are addicted and stuff
so i want to point at something its totally impossible to get 2000$ from (us kids under 18 years and mostly no one have a full time job) 
also its not that bad i was once addicted to agar that was 2 years ago now i stopped playing games and iam trying to learn some real stuff like learning russian , english and Thanks for your REPO ! it got me into coding when i downloaded the code i had no idea how to use it but i got more experience , and now I'm into coding i want to make my own ogarul but in python so i started to learn python 2 weeks ago
so i wanted to say thanks for the repo it helped me alot and goodbye :)

**Comment by SharDX** [comment]
and by the way if anyone wanna learn python i have a very good book just ask me

**Comment by NatsuTheGreat** [comment]
You have to purchase a book? :/

**Comment by RevivedSol** [comment]
I want js and nodejs

**Comment by ZfsrGhS953** [comment]
I know these two. So yes, js and nodejs.

**Comment by SharDX** [comment]
@NatsuTheGreat  
Nope my friend gave it to me for free :D

**Comment by SharDX** [comment]
i dont have nodejs books cuz iam working on python atm 
@ZfsrGhS953 
@RevivedSol

**Comment by iTzArrowFx** [comment]
Whait, You close the servers of Ogar?

**Comment by bangana** [comment]
@iTzArrowFx  exactly.

**Comment by LegitSoulja** [comment]
?

**Comment by ZfsrGhS953** [comment]
Yes, it good for bikslou because My server, Petridish Ogar runs faster than Ogar Unlimited and can have 1500 132 mass-bots with less lag. And it will be useful for his clickbait videos.

**Comment by iTzArrowFx** [comment]
@ZfsrGhS953 its another to Ogar Unlimited?, please link !!!

**Comment by ZfsrGhS953** [comment]
But not on Github, because the repository for it is outdated.
