### ISSUE TITLE
Willy Wonka (Gene Wilder) Rest In Peace

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#1442]
Please leave Gene Wilder condolences if you may like.

![genewilder-12-272x423](https://cloud.githubusercontent.com/assets/4976824/18100528/f9e39ef4-6eb0-11e6-9bfa-165feb22cb8c.jpg)
Everyone is going to miss Gene. He was such a talented person. I got to say, with a person with as much humor as him, I hated to see his day end yesterday. My childhood years, I really enjoyed watching the Chocolate Factory, especially with family. I watched both versions of the Chocolate Factory last night to bring back memory's and I know I had a few tears, here and there.

Gene made alot of movies in the 1900's. The producers was also a good movie I enjoyed. I remembered Gene had spoke about his disease in one of his movies, but you know how Gene sometimes is, (Never meant to say certain things).

**08.29.16** - _Gene Wilder_ (**Age 83**). **D**ied of his defendant (Alzheimer Disease). His disease was not a thing he wanted everyone to know. He knew he had this disease a few years from now, and no he didn't react, nor try to get help which I think (There's no cure for Alzheimer nor dementia). He didn't even tell his family, until they figured out at the last minute after Gene Wilder passed away.

###### Just a question?.
> What would you do if you went to the doctor and figured out you're not healthy? Or you wont live to see an age in your life. Would you tell your family? Would you keep it a secret? Or would you try to end your life faster by knowing you wont see an age in life?

If you have condolences, or Willy Wonky, or just Gene memories and you would like to share please do so.

**Comment by AgarioIsBest1602** [comment]
Rest in peace...

And about that question, i would live my life i never did before.

**Comment by agariotips** [comment]
Rest in piece..

**Comment by UltraSirius** [comment]
Rest In Piece! :(

**Comment by LegitSoulja** [comment]
@AgarioIsBest1602 :) 

Good decision to make. 

@agariotips @UltraSirius piece? Are you serious right now? You kids always take things as a joke. 

Last that I heard Gene was not cremated, so therefor he is not resting in pieces, but in peace(whole)!.

**Comment by SharDX** [comment]
RIP :( 
@LegitSoulja  they probably don't mean it , not every is good at english  and sometimes you do some mistakes , but if they Literally mean it then they should  go to hell srysly, this man was great :(

**Comment by Agarian** [comment]
R.I.P :cry:

**Comment by rydens** [comment]
:(

**Comment by agariotips** [comment]
He was an illness-pirate, unlike in so many cases, he never stole his ability to recognize those that were closest to him, nor took command of his central-gentle-life affirming core personality
