### ISSUE TITLE
Game Is Glitchy

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1443]
If you shoot a w at a virus, the virus does not allways grow, causing you to loose lots of mass.
I would like to try and fix this, but where would this be located in the code?
Or is this part of the client issue with dissapearing cells, mass, etc.

**Comment by SharkFinPro** [comment]
:O
thx megabyte

**Comment by NatsuTheGreat** [comment]
Lol he deleted the messages? :/

**Comment by Megabyte918** [comment]
i told him on disc i didnt feel like going to github lol

**Comment by NatsuTheGreat** [comment]
MKay, but to read this you probably went on github ;)
