### ISSUE TITLE
How does that chat on play.ogarul.tk work?

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1447]
I would like to create a bot for my chat to moderate it, but i need to know how the chat sends and recieves messages :/

**Comment by UltraSirius** [comment]
Chat is Like a Normal Message for player. idk somethin like consoles?

**Comment by firelightning13** [comment]
You would want to see in "src/packet/Chat.js". That should give you a clue.

Still.... this project is gonna end anyway

**Comment by NatsuTheGreat** [comment]
PacketHander Message 99 and ```src/packet/Chat.js``` as firelightning13 suggested.

**Comment by SharkFinPro** [comment]
k

**Comment by LegitSoulja** [comment]
You can also make an onChat event if you decide to make a plugin to handle it.
