### ISSUE TITLE
Trying to run on codenvy and get this...

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1449]
[default] /projects/ogarUL/src/index.js:2
[default] const Readline = require('readline');
[default] ^^^^^
[default] SyntaxError: Use of const in strict mode.
[default]     at exports.runInThisContext (vm.js:73:16)
[default]     at Module._compile (module.js:443:25)
[default]     at Object.Module._extensions..js (module.js:478:10)
[default]     at Module.load (module.js:355:32)
[default]     at Function.Module._load (module.js:310:12)
[default]     at Function.Module.runMain (module.js:501:10)
[default]     at startup (node.js:129:16)
[default]     at node.js:814:3

**Comment by ZfsrGhS953** [comment]
Their node.js version is outdated. Call their support and tell them that they should update to latest.

**Comment by ItzLevvie** [comment]
Or you can update it using the terminal

**Comment by ZfsrGhS953** [comment]
Wait, I thought codenvy doesn't give you root privileges?

**Comment by SharkFinPro** [comment]
@ItzLevvie How?

**Comment by rydens** [comment]
Somehow get 5.9.0
Try [nvm](https://github.com/creationix/nvm).

**Comment by LegitSoulja** [comment]
When you install che, it is pre-installed with an older version of nodejs. You need to change the stacks version for nodejs, or update it via terminal.

**Comment by SharkFinPro** [comment]
how do u update via terminal?

**Comment by LegitSoulja** [comment]
It's best to change the stack version to the required nodejs version.

```
sudo npm cache clean -f
sudo npm install -g n
sudo n 5.9.0
```

**Comment by SharkFinPro** [comment]
@LegitSoulja Thanks, that worked.
Popslits Self With Bot*
Lol
