### ISSUE TITLE
lineWidth help? 

### ISSUE THREAD

**Issue by agariotips** [AJS-development/Ogar-unlimited#1450]
I might as well just create an issue about a client while I can, as ogar unlimited is going bye bye.
Anyway, i need assistance (if anyone is willing to) with helping me with linewidth in a base agario client. I know how to change the name so it looks 'bulkier' but the only thing is, is that it's not constant. If you were to be at 142-2500 mass, it would look fine, but then it would start returning to it's original old agar font. I know we can't talk about clients, but might aswell as the funeral of Ogar-Unlimited is near.

**Comment by agariotips** [comment]
![linewidthgood](https://cloud.githubusercontent.com/assets/21321103/18226774/180381ac-71df-11e6-81eb-434f6a3cf391.JPG)
this is how I want it, but after a bit of mass, it looks like this:
![linewidthprob](https://cloud.githubusercontent.com/assets/21321103/18226777/22d9d2fc-71df-11e6-8c1c-9b6462cd3b42.JPG)

**Comment by Megabyte918** [comment]
Its not that it "returns to its original agar font", the line width stays the same nomatter what size, so the bigger you get the less visible it is. the same goes with cell borders. What client are you trying to implement this on? I tried to add this feature into the OgarUL client a while back but i couldn't because i didn't know what kept track of the mass/size of a player. So i cant help your using that one

**Comment by Agarian** [comment]
I think he means he wants a StrokeStyle on the player's name. I personally want a StrokeStyle on the cell borders.

**Comment by SharkFinPro** [comment]
@Agarian I might try to remake the client in PJS - its better for graphics

**Comment by LegitSoulja** [comment]
Yea, @Megabyte918 the days trying to calculate the mass size for the cell borders... Failled..

But since I was re-writing the client I understand it now.

**Comment by agariotips** [comment]
@Megabyte918 Using the base Cigar webclient.

**Comment by agariotips** [comment]
Okay, I've done some experiments. I set the linewidth to 92 here are the results:
This looks nasty at small, and people have been nauseous when they see it.
![nasty](https://cloud.githubusercontent.com/assets/21321103/18229480/142c763c-7249-11e6-8a01-0799f9f93d1b.JPG)

This on the other hand looks good, at 3k to 6k mass.
![swee](https://cloud.githubusercontent.com/assets/21321103/18229487/32489718-7249-11e6-993d-5092dbb19304.JPG)

This looks like it's fading out. Not good.
![nastier](https://cloud.githubusercontent.com/assets/21321103/18229488/36fd5ac8-7249-11e6-91ef-3acee2a505c5.JPG)

**Comment by Megabyte918** [comment]
you need to make it so it increases the linewidth by a certain amount as the mass of the player increases

**Comment by agariotips** [comment]
hmm ok ill study it a little more.

**Comment by LegitSoulja** [comment]
@agariotips Which should involve math calculations. 

Shouldn't be that hard. I haven't looked at cigar web based client, so I can't distinctly tell

**Comment by LegitSoulja** [comment]
Well nvm, I forgot cigar uses the same

**Comment by agariotips** [comment]
I imagine `ctx.measureText` would be used?

**Comment by agariotips** [comment]
@Agarian Is this what you mean?
![borders](https://cloud.githubusercontent.com/assets/21321103/18230729/de27083e-7272-11e6-922e-0cb8eab69f4d.JPG)

**Comment by agariotips** [comment]
@Megabyte918 `this.size` is probably what calculates mass.

**Comment by LegitSoulja** [comment]
@agariotips nobody here knows about the client here except me and Andrew. The same reason why we don't support about clients because we don't. Only people that can help with client problems is yes me, and or Andrew.

this.size is not the cell mass size. (Well I guess it depends on what this.size you're talking about.)

ctx.measureText only measures the text on the canvas.

This issue needs to be closed because nobody will help with client side as much, (limited support/limited knowledge for everyone else). 

You just can't ask someone something about a client if they don't know nothing about it, which they didn't even create.

All I got to say is good look with the client. But you are on your own with this one. Even though ogarul is dying, still as too what I said is the reason why we don't talk about. It's a waste of time when you can just go and figure it out.

**Comment by ZfsrGhS953** [comment]
This is the draw name/mass code I use to keep lineWidth constant and eliminate lag related to name/mass drawing. 
```javascript
if (0 != this.id) {
                    var b = ~~this.y;
                    if ((showName || c) && this.name && this.nameCache && (null == e || -1 == knownNameDict_noDisp.indexOf(skinName))) {
                        ncache = this.nameCache;
                        ncache.setValue(this.name);
                        ncache.setSize(this.getNameSize() * viewZoom);
                        var rnchache = ncache.render(),
                            m = Math.floor(rnchache.width / viewZoom),
                            h = Math.floor(rnchache.height / viewZoom);
                        ctx.drawImage(rnchache, Math.floor(this.x) - Math.floor(m / 2), b - Math.floor(h / 2), m, h);
                        b += rnchache.height / 2 / viewZoom + 4
                    }

                    //draw mass
                    if (showMass && (c || 0 == playerCells.length && (!this.isVirus || this.isAgitated) && 20 < this.size)) {
                        if (null == this.sizeCache) {
                            this.sizeCache = new UText(this.getNameSize() / 2, "#FFFFFF", true, "#000000")
                        }
                        c = this.sizeCache;
						c.setValue(Math.ceil(this.size * this.size / 100));
                        c.setSize(this.getNameSize() / 2 * viewZoom);
                        e = c.render();
                        m = Math.floor(e.width / viewZoom);
                        h = Math.floor(e.height / viewZoom);
                        ctx.drawImage(e, Math.floor(this.x) - Math.floor(m / 2), b - Math.floor(h / 2), m, h);
                    }
                }
```

**Comment by LegitSoulja** [comment]
Yea, that's another way to accomplish of getting the mass to increase things overtime when a cell gets bigger.

**Comment by LegitSoulja** [comment]
But don't spoonfeed.

**Comment by ZfsrGhS953** [comment]
Updated code, other one included some unneccessary changes

**Comment by ZfsrGhS953** [comment]
Such as ceil the mass instead of floor/truncate it
And Math.floor is slower than ~~

**Comment by LegitSoulja** [comment]
You know what, I was wondering what ~~ was for, because for me I'd just use Math.floor to get a whole number. Well that's more easier now knowing.

**Comment by agariotips** [comment]
Thank you so much.

**Comment by Agarian** [comment]
Where would i put that code?

**Comment by agariotips** [comment]
1. Press ctrl + F 
2. search for  var b = ~~this.y;
3. replace the code until the two close brackets ( { { )
and btw, that math.ciel makes it so after a certain amount of mass, it stops lag by changing amount of detail.

**Comment by Agarian** [comment]
Thanks

**Comment by Agarian** [comment]
So can you do cell borders next?

**Comment by NatsuTheGreat** [comment]
~~ and Math.floor give different results, but still work fine.

**Comment by Agarian** [comment]
What would that look like?
