### ISSUE TITLE
Im hosting ogarul.tk when site goes down

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1451]
For now im doing ogarul.ga - i only have play.ogarul.ga in right now.
@LegitSoulja Can i have source code for the stats page? and possibly the styling for the new client that you never finished?

**Comment by ya345** [comment]
Nice. XD

**Comment by LegitSoulja** [comment]
@SharkFinPro 

Final blue has also emailed me regarding statistics and no I cannot share that neither because im not going to explain how it works because its complicating and a waste of my time.

The new client that I was working on will be the new client for the next release of OgarUnlimited, so that is a thing I will be working on until then.

**Comment by SharkFinPro** [comment]
:O so thats what new client is for - ok.
We could recreate it, but we just want to see source code to keep it the same

**Comment by LegitSoulja** [comment]
@SharkFinPro not really, before OgarUnlimited was going to die I was going to update the client. So therefor, since the site will be closed down, i guess it will be used in the future site of the client.

**Comment by SharkFinPro** [comment]
oh :(

**Comment by LegitSoulja** [comment]
@SharkFinPro and what service are you even using to provide site hosting?

**Comment by LegitSoulja** [comment]
If its free hosting you're not gonna have good luck with it because of bandwidth. Not to many people will be able to enjoy playing on ogarul.ga.

**Comment by SharkFinPro** [comment]
hostfree.pw
its free

**Comment by SharkFinPro** [comment]
but its good

**Comment by SharkFinPro** [comment]
Bandwidth:	Unlimited

**Comment by SharkFinPro** [comment]
heh heh hheh

**Comment by SharkFinPro** [comment]
![capture](https://cloud.githubusercontent.com/assets/18649707/18228246/010c5d46-71fa-11e6-9d63-892ae07d87b5.JPG)

**Comment by SharkFinPro** [comment]
Not joking :P

**Comment by LegitSoulja** [comment]
You may want to take a look at this http://hostfree.pw/tos.php

**Comment by SharkFinPro** [comment]
there is nothing wrong with what im doing...lol

**Comment by LegitSoulja** [comment]
@SharkFinPro your bandwidth is 4MB

For play.ogarul.tk, it's using atleast 4GB of memory.

Daily hits? Is that a traffic limit?
Disk space is low, so you might not even be able to upload all skins

that's actually bad

**Comment by SharkFinPro** [comment]
i have unlimited disk sace

**Comment by SharkFinPro** [comment]
unlimited bandwith

**Comment by LegitSoulja** [comment]
ok, whatever you say.

good luck with that.

**Comment by SharkFinPro** [comment]
the only thing that i may have to upgrade for is daily hits

**Comment by LegitSoulja** [comment]
What about security?

**Comment by SharkFinPro** [comment]
Ermmm

**Comment by SharkFinPro** [comment]
your can make files require a password :/

**Comment by LegitSoulja** [comment]
? That won't do a thing.

**Comment by LegitSoulja** [comment]
Im not talking about files

**Comment by SharkFinPro** [comment]
oh

**Comment by SharkFinPro** [comment]
what do u mean

**Comment by LegitSoulja** [comment]
I'll let you figure out the hard way, you'll understand better then.

**Comment by SharkFinPro** [comment]
Ok...

**Comment by LegitSoulja** [comment]
Why upgrade free hosting? Just get hosting

**Comment by SharkFinPro** [comment]
the only limit is daily hits

**Comment by Andrews54757** [comment]
@LegitSoulja You will be able to use the client for the new one. It would support multiple protocols.

**Comment by SharkFinPro** [comment]
@Andrews54757 Can i help with the new version?
