### ISSUE TITLE
Ogar Split Version bug

### ISSUE THREAD

**Issue by REVOLTA809** [AJS-development/Ogar-unlimited#1456]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
experimental
What version are you on?
latest
What command did you type if any?
start up coms

----------------------------------------------------------------------------------------------------------------------------------------------------------------

When i set split version to 0 2 3 4 5 6 the cells merge but dosent actually merge
its hard to explain but look at a video i made https://drive.google.com/file/d/0B88mhaSCYJuIVy1LdVVTLVNBcVk/view

**Comment by LegitSoulja** [comment]
@REVOLTA809 there's only 2 split version. 1 default, and the other was made by Megabyte. It doesn't go beyond 1

**Comment by LegitSoulja** [comment]
And that gamemode is experimental. That's a game feature that always been that way. I don't know if it was meant to be that way, or its a bug. But it has always been like that.

There's no way that I know to fix that.
