### ISSUE TITLE
The clients need

### ISSUE THREAD

**Issue by arxn** [AJS-development/Ogar-unlimited#1457]
for make a custom client i need learn about?

canvas
nodejs
websocket
jquery

is correct?

**Comment by SharkFinPro** [comment]
no

**Comment by hossem123** [comment]
c++

**Comment by SharkFinPro** [comment]
No
no C++

**Comment by SharkFinPro** [comment]
You dont need nodeJS

**Comment by SharkFinPro** [comment]
Look here and close this issue
https://github.com/AJS-development/client/tree/gh-pages

**Comment by LegitSoulja** [comment]
HTML, and basic JavaScript knowledge,

And a side note of CanvasAPI. Nothing more.

With play.ogarul.tk is using multiple languages, but it's not required. I decided to do it that way.

**Comment by LegitSoulja** [comment]
C++ lmfao
