### ISSUE TITLE
Custom client you guys made doesn't work in other browsers except Google Chrome.

### ISSUE THREAD

**Issue by darknight99x** [AJS-development/Ogar-unlimited#1458]
I don't know what the deal is, but only people that're using Chrome can load the client properly.

Any other browser just shows a white page with the chat bar on it.

Please rewrite it where it will be fixed.

**Comment by Andrews54757** [comment]
safari works only IE and firefox I think doesn't work

**Comment by systemroot** [comment]
firefox, chrome, torch are working for me. (for PC) 

for phone i have test Safari and Maxthon, both working.

**Comment by darknight99x** [comment]
You guys are shit devs, fucking help for once, jesus christ even the maker of this pile of shit doesn't care, buh-bye
