### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by iTzArrowFx** [AJS-development/Ogar-unlimited#1459]
As I think my PUBLIC server for FREE, or cheap, please help!

To me it did not work with me c9

**Comment by rydens** [comment]
I'm not sure I understand...
Are you trying to make your server, but for free, or not very expensively?
Or something entirely different?

Sorry,
> rydens

**Comment by Agarian** [comment]
He wants to host his server, either free, or inexpensive. And he said he was notified not to use Cloud9, which is good.

**Comment by rydens** [comment]
Okay, I would suggest [Digital Ocean](digitalocean.com). I just use the basic option, which is only $5 a month. It works fine.
