### ISSUE TITLE
The max mass

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#146]
So i got up to 16 pieces with 360000 mass and, when people go in me, mass will still stay 360k and it doesnt go up. In agario world record is 396k and can u make it possible for mass to be going up

**Comment by Agarian** [comment]
the record is 415K https://www.youtube.com/watch?v=Kj_Gtjj1010
skip to 5:12

**Comment by elitajmx** [comment]
yes but i have a problem here

**Comment by firelightning13** [comment]
#46

**Comment by Andrews54757** [comment]
I have added this feature in the upcoming update. see #182

**Comment by elitajmx** [comment]
Nice ;)
