### ISSUE TITLE
Game Launcher

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#1460]
I am started a new project called GameStation if anyone is interested in trying. It's better to use this than any other browsers. Better performance, and supports wide range of web functionalities.

GamsStation is built from a similar like Chrome engine, but is fully managed for best use.

A browser will also be made after this just because I know many people would rather want a browser instead, but GameStation will hopefully be the popular gaming spot. 

###### Currently only for Windows OS
https://github.com/LegitSoulja/GameStation

###### My future browser 
https://github.com/LegitSoulja/Core-Browser
> Watch Core-Browser for the release.

These projects are all created/developed by me. No help is needed, but you may request things, or notify me of bugs, and or things to help improve GameStation! **_Not Open Sourced (Copyrighted material)_**

**Comment by Megabyte918** [comment]
neat

**Comment by AlexandriteErikParacelsus** [comment]
Will this support extensions?

**Comment by SharkFinPro** [comment]
@Megabyte918 Yes...

**Comment by LegitSoulja** [comment]
@Megabyte918 have any ideas for the new Core browser and how it should be?

**Comment by arxn** [comment]
will look as chrome pls

**Comment by Megabyte918** [comment]
@LegitSoulja what about the ability to add custom sites to the start menu?

**Comment by LegitSoulja** [comment]
@Megabyte918 it's already been added.. I guess I should've never asked you yet because of it not being fully released.

**Comment by LegitSoulja** [comment]
As chrome, I mean it's a chrome 42 based engine. This is still chrome, but the base of it.

Not much ram is used up here. You can compare chrome, to the GameStation if you like.
