### ISSUE TITLE
Borders of points and of cells

### ISSUE THREAD

**Issue by arxn** [AJS-development/Ogar-unlimited#1461]
how to remove the borders of points ( smoothrender) , but  without remove the borders of the cells , like agar.io client

**Comment by Agarian** [comment]
I will tell you when I'm actually allowed to be awake. I credit @retslac though.

**Comment by LegitSoulja** [comment]
You would accomplish this in drawGameScene=>userScore

**Comment by arxn** [comment]
why in userscore? i mean to this points ( draw)

**Comment by Agarian** [comment]
[Client.zip](https://github.com/AJS-development/Ogar-unlimited/files/470047/Client.zip)
Try this: it has what you want and more. But it is NOT up to date with play.ogarul.tk!

**Comment by LegitSoulja** [comment]
spoon feeding never helps

**Comment by arxn** [comment]
@Agarian  this cause lag? how to remove the borders of points ? without remove the borders of cells

**Comment by LegitSoulja** [comment]
Sorry, but Agarian is no longer part of AJS, and he removed his account.

**His last words to me**
> Welp thats the end of me. Goodbye cruel world, I never liked it anyway. And one more thing before I go, tell Andrews my account no longer exists

@Andrews54757

**Comment by Andrews54757** [comment]
I am doing a filter of AJS-members, to make it more professional

**Comment by SharkFinPro** [comment]
@Andrews54757 You Finally Got A New Logo :D

**Comment by LegitSoulja** [comment]
@Andrews54757 I'll need another invite to the group plz. 

I changed my mind about leaving. Looks like my job isn't full time.

**Comment by Andrews54757** [comment]
Ok, and @SharkFinPro I made it myself (the ajsdev logo is also different)

**Comment by SharkFinPro** [comment]
Cool :)
