### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by arxn** [AJS-development/Ogar-unlimited#1464]
how to put Online Players on the index ? the same players online appear on the emulator , that appear on the index.html , how to?

like this ( say 8 players on the selector of gamemodes )

![image](https://cloud.githubusercontent.com/assets/21227214/18608999/a759c49e-7ccd-11e6-97ae-2f1cfad6422d.png)

**Comment by LegitSoulja** [comment]
@arxn Do you know how to use ajax?

**Comment by systemroot** [comment]
@LegitSoulja in some plugins i have read some commands which post their output into your/our client 
when i start a server will read this 
![](http://image.prntscr.com/image/c24691f4ce1c4d42aef05243bb416ff6.png)
what if i host my client with nodejs not with apache or nginx and if i put 
in index.html `this.configfile = "/fullpath/config.ini";` or in file.js  those 4 files from that scr
can i execute commands from index.html or file.js example to get playername etc and to post output into my client? Will this work?!

**Comment by LegitSoulja** [comment]
Unfortunately not..

**Comment by systemroot** [comment]
thanks for answer

**Comment by arxn** [comment]
@LegitSoulja  u can help me with the code? i not know about ajax

**Comment by LegitSoulja** [comment]
@arxn No, sorry, I cannot help with that.
