### ISSUE TITLE
Idea for future version: New Command

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1465]
How about a plugin disable command - if you are using massstart plugin but you want to do hunger games with less mass, how about a command to disable that plugin

**Comment by LegitSoulja** [comment]
How about I have the mass change for each gamemode with mass start?

**Comment by SharkFinPro** [comment]
Ok!
But a plugin disable command would still be good for others...

**Comment by LegitSoulja** [comment]
I'll see what I can do. I don't think it would be possible. You would have to restart anyways for a plugin to not take effect.

Best to edit the plugin loader to disable specific plugins by name, or just delete it

**Comment by SharkFinPro** [comment]
ok
