### ISSUE TITLE
Help Needed!

### ISSUE THREAD

**Issue by systemroot** [AJS-development/Ogar-unlimited#1467]
anyone can create as plugin or whatever. 

what is needed is. 
one (plugin) (or code in ogarul) 
to execute one bash script! plus one argument. 
this argument is player ip when player connect on server
example when player will connect, nodejs will get player ip 
and nodejs will execute this bash script like 
>'scan.sh PLAYERIP'

this scan.sh just will check player is this dude welcome'd in server or not. 
please anyone can help with this. ?
i just want to do this to stop kids with minions. 

Thanks.

**Comment by LegitSoulja** [comment]
I'm pretty sure you know how to exec commands. You can send the path to scan.sh followed by the IP argument I'm guessing when a player joins.

**Comment by systemroot** [comment]
my problem is with nodejs i don't know how/where to write the code to get player ip and then exec bash script!

**Comment by LegitSoulja** [comment]
@systemroot I advise you to check the wiki, and also learn the "Exec" section of nodejs.

**Comment by LegitSoulja** [comment]
I would provide you on how, but I don't spoonfeed.

**Comment by systemroot** [comment]
okay thank you -.-

**Comment by LegitSoulja** [comment]
@systemroot
It's best to learn, and get it over with. The wiki gives basic explanatory of how to create a plugin.

##### Player (Before)Spawn Event

```
this.beforespawn = function(player){
    var ip = player.socket.remoteAddress;
    var exec = require("child_process").Exec;
}
```

Read up exec here 
https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

Wala. How easy was that?

**Comment by LegitSoulja** [comment]
```
this.beforespawn = function(player){
    var ip = player.socket.remoteAddress;
    var exec = require("child_process").exec;
    exec("scan.sh " + ip, function(err, stdo, ster){
        if(!error){
            // no error, output results
            console.log(stdo);}
        else{
            // error 
            console.log(error);
        }
        // allow player to join game, false deny.
        return true; 
    });
    // allow player to join game, false deny.
    return true;
}
```

**Comment by systemroot** [comment]
@LegitSoulja 
The only think which is making me to use nodejs is ogarul for this i haven't learn it!
So thank you again.

**Comment by LegitSoulja** [comment]
@systemroot there. Finished the entire plugin. I'm using my phone, so I'm not sure if you'll run into any errors or not.

make a folder in the plugins folder(Name it anything), create a file in that folder you created named **index.js** and paste the contents I provided.

**Comment by LegitSoulja** [comment]
I don't know what scan.sh is but you'll need to compare the output to decide rather or not to kick or deny that IP from joinin.

**Comment by systemroot** [comment]
plugin is loading, but isn't working
i try just 
>if [ "$1" ]
>then
>touch $1
>fi

that file isn't created, 
what i'll do is to execute bash script and that bash script will scan port of that ip, will not put port range because will take some time to scan but just the most of used ports.

**Comment by LegitSoulja** [comment]
@systemroot I don't know much about linux scripting since I don't barely work with linux.

**Comment by systemroot** [comment]
:confused:  it's simple
$1 is the argument 
when you execute one bash script in linux example **./execute.sh**
in script
> #!/bin/bash
> echo "you executed this"

a bash script which can executed only with one argument like in out case
example $1 is the argument ($1 = the first word after ./script.sh)
then script will executed **./execute.sh IP** EX. **./execute.sh 123.123.123.123**
>#!/bin/bash
>if [ "$1" ] 
>then
>   echo "your argument is $1"
>else
>   echo "Argument is missing"
>fi

i was trying to do what i want from bash script because i don't understand nodejs, 
but if you know how can we do to scan player ports example 8080,1080 etc, when the player join. if those ports are opened then ban this ip if not let it to play. 
so if you can do this with nodejs this will be cool :/ so we can stop minions because when they come the only way which we have is to shut server down!
i know to scan a port some times will take some time but it's better to "take some time" then let them to join.

**Comment by LegitSoulja** [comment]
In your sh file, for example I'll have a number return from sh like an echo.

If player port whatever is open, then echo 0, then nodejs will get sh output (0) then you can compare and kick player from game, and ban aswell.

**Comment by systemroot** [comment]
can nodejs get that number from echo ?!
that will ban ip only if those ports are opened so we can change like this
<pre>
#!/bin/bash
host=$1
for port in {1080,8080}; do 
    (echo > /dev/tcp/$host/$port) &>/dev/null
    [ $? -eq 0 ] && echo "0"
done
</pre>
but if this ip have more than 1 of those ports opened output will be
<pre>
root@cls:~/nodejs# ./t.sh 0.0.0.0
0
0
</pre>
is this problem?!

**Comment by LegitSoulja** [comment]
Ok, so you are checking if a player ip has a specific port open correct?

What you need to do is if the player ports are no open echo 0, else if ports are open return 1.

I will update the code in a sec above.

**Comment by systemroot** [comment]
1 folder plugins/hellominion
index.js plugins/hellominion/index.js
<pre>
'use strict';   // dont touch
const exec = require("child_process").exec;
this.command = []; // dont touch
this.commandName = []; // dont touch
this.gamemodeId = []; // dont touch
this.gamemode = []; // dont touch
this.addToHelp = []; // dont touch

// [General]
this.name = "HelloMinion"; // Name of plugin REQUIRED
this.author = "LegitSoulja & SystemRoot"; // author REQUIRED
this.description = 'F.Minions'; // Desciprtion
this.compatVersion = ''; // compatable with (optional)
this.version = '1.0.0'; // version REQUIRED

// INSERT PLUGIN BELOW


// [Functions]
this.init = function (gameServer, config) {};

// this function is called before a player join the server
this.beforespawn = function(player){
    try{
        let ip = player.socket.remoteAddress.toString();
        // make sure scan.sh is in this file directory
        exec(__dirname  + "/scan.sh " + ip, function(err, stdo, ster){
            if(!err){
                // no error, output results
                switch(parseInt(stdo)){
                    case 0:
                        // player ports are not opened
                        return true;
                    case 1:
                       // player port is opened
                       return false;
                }
            }else{
                // error
                console.log(error);
            }
            // allow player to join game, false deny.
            return true;
        });
        // allow player to join game, false deny.
        return true;
    }catch(e){
        console.log("Error " + e.toString());
        return true;
    }
}
module.exports = this;

</pre>

scan.sh plugins/hellominion/scan.sh
<pre>
#!/bin/bash
host=$1
if [ "$1" ]; then
    for port in {80,8080,1080,8888,3129,3128,2226,3389,22}; do
        (echo > /dev/tcp/$host/$port) &>/dev/null
        [ $? -eq 0 ] && echo "1"
    done
else
  echo "0"
fi
</pre>

i have chmod +x scan.sh
isn't working. maybe nodejs isn't executing this bash script. 
lets try something else example i have wrote just 
> echo "1"

into scan.sh which this will deny all players to join. 
but i'm able to join in server!

**Comment by LegitSoulja** [comment]
@systemroot It should work, but idk why it's not. Give me a sec while I look over child processes for clarity.

**Comment by LegitSoulja** [comment]
@systemroot Try this
```
'use strict';   // dont touch
const spawn = require("child_process").spawn;
this.command = []; // dont touch
this.commandName = []; // dont touch
this.gamemodeId = []; // dont touch
this.gamemode = []; // dont touch
this.addToHelp = []; // dont touch

// [General]
this.name = "HelloMinion"; // Name of plugin REQUIRED
this.author = "LegitSoulja & SystemRoot"; // author REQUIRED
this.description = 'F.Minions'; // Desciprtion
this.compatVersion = ''; // compatable with (optional)
this.version = '1.0.0'; // version REQUIRED

// INSERT PLUGIN BELOW


// [Functions]
this.init = function (gameServer, config) {};

// this function is called before a player join the server
this.beforespawn = function(player){
    try{
        let ip = player.socket.remoteAddress.toString();
        // make sure scan.sh is in this file directory
        let child = spawn(__dirname + "/scan.sh", [ip]);
        child.stdout.on("data",function(data){
            if(data && !isNaN(data)){
                switch(parseInt(data))
                {
                    case 0:
                        // player ports are not opened.
                       return true;
                    case 1:
                        // player ports are opened, disallow join
                        return false;
                    default:
                        return true;
                }
            }
        });
    }catch(e){
        console.log("Error " + e.toString());
        return true;
    }
}
module.exports = this;
```

**Comment by systemroot** [comment]
now is a error, 
<pre>
Error: spawn ./scan.sh ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)

</pre>

**Comment by LegitSoulja** [comment]
@systemroot Do you get a packet error when trying to join? I think it would deny joining if whatever script is taking too long before it returns true or false for the player to join.

How long does it take for scan.sh to finish checking if the ports are open? I think it would be faster IF a site tested for open ports, because then you could add a timeout limit if it's taking to long to resolve. Maybe @Andrews54757 can help with this one. This guy has a nodejs book lol, I don't. He knows all the tips and tricks.

I wished I could test this on my own but I don't own a Linux. I could download and boot up a VM, but it's a waste of time.

**Comment by systemroot** [comment]
@LegitSoulja  
well about time i don't rlly know how much players can connect in the same time. but if is one player every 3-4 minutes this will not be problem. bacause i have write which port to scan you can try to do "nmap ip" to see how much time is needed, and you can try any checker online or that bash script which i have wrote to check one ip for those ports. so yes also will see to add one time out. 
but i think isn't problem here, if nodejs code can fix'ed i can try another ways to check some ports isn't problem for bash script. 
about vm, i say before i'm saying again i can deploy one VM with docker isn't problem, we can talk on gitter tell me what distro you need and what open ports you want and it's done!

Hope Andrews can help, all what we want is to make that nodejs code to work because if echo output is **0** player isn't able to join!

**Comment by LegitSoulja** [comment]
@systemroot I use the paid version of VMWare workstation :). Other than that to a docker I'll use vagrant. 

You should check to see how long it takes for scan.sh to finish, because without a timeout there could be problems.

**Comment by systemroot** [comment]
now the easy way is to call this bash script with **timeout 1 ./scan.sh argument**
timeout is an command which is installed on linux so if this "timeout 1" can add on nodejs code then ok. if no i'll need to add another script which will call scan.sh

**Comment by LegitSoulja** [comment]
1 is ms? for linux? or 1 second? or minute?

**Comment by systemroot** [comment]
1 secound. 
timeout also have options to set like -s (sec) -m(min)

**Comment by LegitSoulja** [comment]
@systemroot 
```
'use strict';   // dont touch
const spawn = require("child_process").spawn;
this.command = []; // dont touch
this.commandName = []; // dont touch
this.gamemodeId = []; // dont touch
this.gamemode = []; // dont touch
this.addToHelp = []; // dont touch

// [General]
this.name = "HelloMinion"; // Name of plugin REQUIRED
this.author = "LegitSoulja & SystemRoot"; // author REQUIRED
this.description = 'F.Minions'; // Desciprtion
this.compatVersion = ''; // compatable with (optional)
this.version = '1.0.0'; // version REQUIRED

// INSERT PLUGIN BELOW


// [Functions]
this.init = function (gameServer, config) {};

// this function is called before a player join the server
this.beforespawn = function(player){
    try{
        let ip = player.socket.remoteAddress.toString();
        // make sure scan.sh is in this file directory
        let child = spawn("timeout 5000 ./scan.sh", [ip]);
        child.stdout.on("data",function(data){
            if(data && !isNaN(data)){
                switch(parseInt(data))
                {
                    case 0:
                         // player ports are not opened.
                        return true;
                    case 1:
                        // player ports are opened, disallow player join
                        return false;
                    default:
                        return true;
                }
            }
            console.log("Error: No valid output could be compared.");
            return false;
        });
    }catch(e){
        console.log("Error " + e.toString());
        return true;
    }
}
module.exports = this;
```

**Comment by LegitSoulja** [comment]
Like I was saying, I did some testing and scan.sh is actually taking a long time to processes the output and close. stdout doesn't output until the shell is closed completely (Which I just now figured out).

Soo, Here is what I did
```
'use strict';   // dont touch
const exec = require("child_process").execSync;
this.command = []; // dont touch
this.commandName = []; // dont touch
this.gamemodeId = []; // dont touch
this.gamemode = []; // dont touch
this.addToHelp = []; // dont touch

// [General]
this.name = "HelloMinion"; // Name of plugin REQUIRED
this.author = "LegitSoulja & SystemRoot"; // author REQUIRED
this.description = 'F.Minions'; // Desciprtion
this.compatVersion = ''; // compatable with (optional)
this.version = '1.0.0'; // version REQUIRED

// INSERT PLUGIN BELOW


// [Functions]
this.init = function (gameServer, config) {};

// this function is called before a player join the server
this.beforespawn = function(player){
    try{
        let ip = player.socket.remoteAddress.toString();
        // make sure scan.sh is in this file directory
		exec(__dirname + '/scan.sh ' + ip,
		  function (error, stdout, stderr) {
			console.log('stdout: ' + stdout);
			console.log('stderr: ' + stderr);
			if (error !== null) {
			  console.log('exec error: ' + error);
			}
		});
    }catch(e){
        console.log("Error " + e.toString());
        return true;
    }
}
module.exports = this;
```

So now, the issue behind this all is the time.

**Comment by LegitSoulja** [comment]
Also, while testing, for some reason I cannot get the output from the shell. Is it because of windows? idk but i tried this
```
		exec(__dirname + '/scan.sh ' + ip,
		  function (error, stdout, stderr) {
			  if(!error){
				  console.log("stdout: " + stdout);
				  console.log("stderr: " + stderr);
				  console.log("error: " + error);
				  if(stderr && !isNaN(stderr)){
					  switch(parseInt(stderr)){
						  case 0:
						    // allow player to join in-game
							this.gameServer.pm(player.pID, "You have been authorized.");
							return true;
						  case 1:
						    // deny player to join in-game
							this.gameServer.pm(player.pID, "You are not allowed to join this server!.");
							return false;
						  default:
							return true;
					  }
				  }else{
					  // invalid responce. No output, or invalid number(0 or 1).
					  console.log("No valid output > " + stderr);
					  return true;
				  }
			  }else{
				  console.log("Error: " + error);
				  return true;
			  }
```
and results
```
127.0.0.1
stdout:
stderr:
error: null
No valid output >
```

**Comment by systemroot** [comment]
to execute that bash you will need to write it like **./scan.sh**
not directly **/scan.sh**

**Comment by LegitSoulja** [comment]
@systemroot __dirname is the directory of index.js then /scan.sh as the bash file. **./scan.sh** is the same way of writing.

And, I have no idea to stop minions. I had an idea, but I don't see it working 100 effectively.

**Comment by LegitSoulja** [comment]
for MassStart, it blocked multiple connections per player. What I did was checked the joining player and made sure there's no other alike connections in game. You can test it yourself. I works, but kindof gets annoying when a player crash out of the game, or reload by mistake. Then they'll have to wait until there player die, and out the game before joining again.

**Comment by systemroot** [comment]
well i will try it :confused: thank you

**Comment by LegitSoulja** [comment]
@systemroot minions as in bots?

**Comment by systemroot** [comment]
i don't know for this i'm asking, in playerlist i'll se like this (when someone start to add minions)
<pre>
         99 | 134.168.55.226  | Bоt             |    15 |    923 | 13560,  6095
        100 | 104.219.251.135 | Bоt             |     7 |    219 | 12943, 14338
        101 | 107.140.239.136 | Bоt             |    15 |   1001 | 16066,  4444
        102 | 112.126.68.96   | Bоt             |    15 |   1054 | 16326,  6034
        103 | 47.88.79.207    | Bоt             |     8 |   1057 |  3623, 17100
        104 | 115.88.95.107   | Bоt             |     8 |   1312 |  9135,  6544
        105 | 218.15.113.3    | Bоt             |     8 |   1006 | 19258, 18023
        106 | 64.179.175.54   | Bоt             |     8 |   1469 | 18937,  2685
        107 | 88.149.170.111  | Bоt             |     8 |   1006 |  4386, 13362
        108 | 94.251.9.10     | Bоt             |     4 |    503 |  3971,  5474
        109 | 177.223.103.75  | Bоt             |     1 |   1035 | 17587,  5274
        110 | 134.168.55.226  | Bоt             |     4 |   1007 |  8753, 13561
        111 | 75.97.107.190   | Bоt             |     1 |   1009 | 10292, 10397
</pre>
if i'll make player max connect 20 and i will try to add 100+ bots
http://image.prntscr.com/image/bea1bfdc786446f7b684b5193ec04547.png
output
<pre>
        710 | BOT             | 8ch             |     1 |   1032 | 13210,  5469
        711 | BOT             | byzantium       |     1 |   1052 |  8471,  3280
        712 | BOT             | indiana         |     1 |    992 | 10061,  9961
        713 | BOT             | reddit          |     1 |    992 | 13094,  3397
        714 | BOT             | german empire   |     1 |    954 |  2040, 10238
        715 | BOT             | mexico          |     1 |   1023 | 10436, 12631
        716 | BOT             | moon            |     1 |   1052 |  7801,  1482
        717 | BOT             | ireland         |     1 |   1091 |  2544,  1761
        718 | BOT             | sweden          |     1 |    992 | 14499, 12279
        719 | BOT             | japan           |     1 |   1052 | 12604,  4924
        720 | BOT             | cia             |     1 |   1023 |  2041, 14074
        721 | BOT             | brazil          |     1 |   1122 | 12927,  1146
</pre>
i'm able to add more bots then player max limit, 
how ogarul detect this is player or bot? from just name called "BOT" in playerlist or if this player have one ip or not?! i don't know 
they will come from diferent ip's just name is "Bot" so player max limit *(serverMaxConnections)* will work i think ?!

**Comment by Andrews54757** [comment]
Omar detects if it has a socket address or not

**Comment by rydens** [comment]
If you wanted to stop minions or such, maybe try the thingy that checks if you are human or not...
`src/settings/advConfig.ini` 
`Anit-Suicide Bot Measures >> verify`

**Comment by systemroot** [comment]
@Andrews54757  can you please make this to work if **echo output is 0** allow player if 1 then deny please ?!
<pre>
'use strict'; // dont touch
const exec = require("child_process").execSync;
this.command = []; // dont touch
this.commandName = []; // dont touch
this.gamemodeId = []; // dont touch
this.gamemode = []; // dont touch
this.addToHelp = []; // dont touch

// [General]
this.name = "HelloMinion"; // Name of plugin REQUIRED
this.author = "LegitSoulja & SystemRoot"; // author REQUIRED
this.description = 'F.Minions'; // Desciprtion
this.compatVersion = ''; // compatable with (optional)
this.version = '1.0.0'; // version REQUIRED

// INSERT PLUGIN BELOW


// [Functions]
this.init = function (gameServer, config) {};

// this function is called before a player join the server
this.beforespawn = function (player) {
    try {
        let ip = player.socket.remoteAddress.toString();
        // make sure scan.sh is in this file directory
        exec(__dirname + '/scan.sh ' + ip,
            function (error, stdout, stderr) {
                if (!error) {
                    if (stderr && !isNaN(stderr)) {
                        switch (parseInt(stderr)) {
                        case 0:
                            // allow player to join in-game
                            return true;
                        case 1:
                            // deny player to join in-game
                            return false;
                        default:
                            return true;
                        }
                    } else {
                        // invalid responce. No output, or invalid number(0 or 1).
                        return true;
                    }
                } else {
                    console.log("Error: " + error);
                    return true;
                }
            });
    } catch (e) {
        console.log("Error " + e.toString());
        return true;
    }
}
module.exports = this;
</pre>

i know this will deny all who have open ports. but well i will not let this active 24/7 i'm online the most of time and i will active only when minions are coming also if this will work i can get all socks ip's and ban by subnet!

**Comment by LegitSoulja** [comment]
@sytemroot it does not work. Scan.sh takes too long too do its job. 

Then the output isn't even captured... So, even if you did echo 1, or 0, nothing will happen.

**Comment by systemroot** [comment]
@LegitSoulja 
Maybe you already have think about this but well i just want to say.
To stop exposing server ip's in public. For as time as you own the client and stats then public have nothing to do with server ip.
Then we will not have ddos attack, those minions. And another new spam which someone start to do it in my server i read that repo about spam here in github i'm searching for that guy i hope he haven't any server. And someone else start to spam welcome message  ''monster yt'' 
This gay started to spam just to read more than one time "welcome monster yt"
Kids in action.

**Comment by LegitSoulja** [comment]
@systemroot Spam for chat has been fixed as I recall of doing. Using ChatMessages, there's no prevention from people join, and leaving and joining the server spamming those join messages. There's no way to stop that unless you turn join messages off..

With statistics, I will be getting rid of permanently. I've got tired of it, and i've came up with a better way to do things.

With the new client im making, and plugin, players are allowed to join your server using your unique game uid. For example
> http://ogarul.io/?id={gameuid}

Doing this way, nobody cannot figure out what ip, and or connections they are connecting too.

Other than that, I am mainly dealing with ddos issues, and bot prevention's. I'm not too much worried about that, as the owner can handle spam issues for him/her self.

**Comment by LegitSoulja** [comment]
All changes, and things I will make will be added to the forum since it's the proper place to keep things organized. I think you registered on the forums before, which there is a new forum. You should be able to login with your same account credentials. If you account is not recoverable, then contact me with your account information, then I will be glad to help you resolve your lost account.

Email: support@legitsoulja.info
Forums: http://forum.ogarul.io

- LegitSoulja

**Comment by systemroot** [comment]
For spamers ban is an good option!

About stats and client that's amazing :')

Yes i'm registered, i will contact you tomorrow maybe  you can send just my email because i don't remember with which one i was registered because i want to recover my password!

**Comment by LegitSoulja** [comment]
@systemroot You can login with your username, and or email. If you can remember your password then thats good, you can update your profile information.

**Comment by LegitSoulja** [comment]
@systemroot Actually, Since I do not see your account I guess you never activated your email on the old forums. You will need to register again.

**Comment by systemroot** [comment]
My username isn't that, is 'raw' actived and confirmed with email!

**Comment by LegitSoulja** [comment]
@systemroot yes, there is an account with the username raw. Can you confirm the partial of the email you provided?

**Comment by systemroot** [comment]
i don't remember! can you just send me one activation email or something like this and i will check my emails to find which one?!

**Comment by LegitSoulja** [comment]
@systemroot Sure, I will send you a recovery email. Just a handy tip, the email contains the keyword **owner**.

**Comment by systemroot** [comment]
**owner@dope-** yea thank you now i remember.

**Comment by LegitSoulja** [comment]
@systemroot correct. A password reset request has been emailed to you. Please follow the instructions in that email.

**Comment by systemroot** [comment]
@LegitSoulja i have try to reset password with username but i didn't receieve one email! 
also i haven't get this email which you say!
is forum configured right with email service?!

**Comment by LegitSoulja** [comment]
@systemroot there may be a small delay with the email service. You should look for an email with headers **no-reply@ogarul.io** containing your information on resetting your password. 

About my email service, since the site your email is used isn't a site, but email is configured. Are you receiving emails at all?

**Comment by systemroot** [comment]
i have not get any email, also i'm checking spam folder. 
i think something is wrong with ogarul email!

**Comment by LegitSoulja** [comment]
@systemroot If so, then nobody would be able to register, and there been multiple people registering lately. I've also checked it myself and got a email within a minute of requesting it.

**Comment by systemroot** [comment]
to verify that owner@dope* is my email you can email me from your gmail example 1+1= and i will post here answer .
or whatever you want.

**Comment by LegitSoulja** [comment]
Obviously, that's a waste of time if your email services are not working. GoDaddy emailing services is slow anyways, if you aren't using it correctly, and not having it redirected elsewhere.

You can reset your password here using your email
> http://forum.ogarul.io/lost-password/

**Comment by systemroot** [comment]
np i have try that.
just i will create new acc.

**Comment by LegitSoulja** [comment]
@systemroot just email me with that email, then I will send you a password to use apon logging in, and resetting it.

**Comment by systemroot** [comment]
that email will redirect emails to my gmail, because i was using cloudflare for free and cloudflare for free doesn't support emails. so i can't send you email directly!

**Comment by LegitSoulja** [comment]
@systemroot You are using godaddy correct? 

Received emails will go through cloudflare, to godaddy rather or not it's free. 

To send emails, you will have to visit your cpanel, and or login elsewhere with smtp.

**Comment by systemroot** [comment]
i'm using this email for a long time in some forums, facebook, wordpress, my websites, and is working, 
is email forward,  owner@dope > my@gmail.com directly
when i was using cloudflare i was registered at freevps.us and the admin contacted me and wroted "change your email please because we aren't able to send you email because you are using cloudflare for free" i didn't know that if i use cloudflare i'll not be able to receieve emails so 
http://image.prntscr.com/image/1c271e0a7a064e0b876fadfa7f2a8983.png
after this i deactivate cloudflare and i use email forward directly.

**Comment by LegitSoulja** [comment]
Yes exactly. To what he said your DNS, (MX Records) is not configured properly. I never heard of cloudflare not allowing emails for free services, because I have a couple domains using cloudflare free, and email works fine without no problems. It's actually faster than not using cloudflare.

**Comment by systemroot** [comment]
this is the reason why i use cloudflare for fast dns, but well in that time i was under ddos attack and was needed to hide all informations about server ip. was just free hosting and some guys start with ddos for nothing :/ after that we closed that project.

**Comment by LegitSoulja** [comment]
free cloudflare won't prevent ddos, but it will close down if there was attacks so it won't flood the site.
