### ISSUE TITLE
White screen and no gameserver.ini

### ISSUE THREAD

**Issue by baana101** [AJS-development/Ogar-unlimited#1470]
Okay simple I have a vps and when I play Ogar.io everything is fine But i want to play on agario way but all i get is a white screen(cant spawn in) also I have no gamefile.ini in ogarmasterunlimited please help

**Comment by LegitSoulja** [comment]
**gameserver.ini** is replaced with both **advConfig.ini**, and **config.ini** in **./settings**. Also client settings is new for customizing the client.

With this current version of OgarUnlimited, it is not supported for agar.io use. You'll have to use [No-Client](https://github.com/AJS-development/Ogar-unlimited-Noclient) instead
