### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by baana101** [AJS-development/Ogar-unlimited#1471]
module.js:341 throw err; ^ Error: Cannot find module 'collections/sorted-map' at Function.Module._resolveFilename (module.js:339:15) at Function.Module._load (module.js:290:25) at Module.require (module.js:367:17) at require (internal/module.js:16:19) at Object.<anonymous> (C:\Users\Michael\Desktop\Ogar-unlimited-Noclient-mast er\src\core\WorldModel.js:5:19) at Module._compile (module.js:413:34) at Object.Module._extensions..js (module.js:422:10) at Module.load (module.js:357:32) at Function.Module._load (module.js:314:12) at Module.require (module.js:367:17) Press any key to exit...

As you can see I cant type anything on this Itll just close Any fix I tried looking at others but they dont have" Press any key to exit..."

**Comment by LegitSoulja** [comment]
@baana101 make sure you are using node version 5.9.0 or higher..

install this module
> npm install collections
