### ISSUE TITLE
Hosting question

### ISSUE THREAD

**Issue by MineMooreALT** [AJS-development/Ogar-unlimited#1472]
Hi would 8GB of be good enough for 40 players max and 5 bots per player?

**Comment by locktrap** [comment]
i wish i could find out, but my PC's specs aren't that good. however, it depends on your processor as well.

**Comment by ZfsrGhS953** [comment]
You should be OK even with 512mb. The bottleneck in Ogar Unlimited is the CPU, because it doesn't use quadtrees. So, for each player cell, it's going to check for unnecessary collisions. This is what slows it down so much.

**Comment by LegitSoulja** [comment]
It's not about the ram, its your processor which can handle the entire game without problems. Since nodejs, is single cored, only 1 processor can be used. 

I've ran ogarul using an overclocked processor, no problems what so ever. It all goes down to latency, and processor qualifications.
