### ISSUE TITLE
Vps Question 2

### ISSUE THREAD

**Issue by jobakas** [AJS-development/Ogar-unlimited#1473]
100 player and have 5 minion for a player, what needs?

**Comment by jobakas** [comment]
How should CPU and RAM ? No have unnecessary extensions, everything is completely up to date.

**Comment by systemroot** [comment]
my vps with 32GB RAM. 8CPU X 4GHz . 
and 90-100 players was lag asf.
i haven't try to add 5/minion per player this will cause lag++

**Comment by jobakas** [comment]
I understand, :( I expect a better response.

**Comment by jobakas** [comment]
Okey, okey. Forget minions. Only 100 players, what needs? most needed ram or cpu? example; 8gb ram or 6 gb cpu

**Comment by jobakas** [comment]
@systemroot

**Comment by systemroot** [comment]
6gb ram is ok for 100players. The problem is your with cpu.
