### ISSUE TITLE
Why no have linesplit?

### ISSUE THREAD

**Issue by jobakas** [AJS-development/Ogar-unlimited#1474]
Hey why linesplit no have? I run fast split to line and fail linesplit. ?

No have linesplit in  OgarUL ?

**Comment by AlexandriteErikParacelsus** [comment]
It's because the client

**Comment by jobakas** [comment]
No have settings in web-client. It have in OgarUL settings reason web-client cells using websocket packets condition.

**Comment by NatsuTheGreat** [comment]
Dude are you serious? How can the client affect the issues of the cell? In this case linesplit.

**Comment by UltraSirius** [comment]
Client -(in a network) a desktop computer or workstation that is capable of obtaining information and applications from a server.

the Point Is LineSplit Dont Work because the Map Floor And the cell are  outdated (Just Like In A Old Agar.io)

**Comment by jobakas** [comment]
Its hard?

**Comment by LegitSoulja** [comment]
@jobakas I wouldn't say its hard, But if i knew exactly how to accomplish this I would.

**Comment by NatsuTheGreat** [comment]
It's not because of the the map floor and cells being outdated either.
