### ISSUE TITLE
no new skins, lag, this is dead

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#1477]
play.ogarul.tk should really  realllly get new skins, its boring af theres no point in playing with old shit skins with bots that don't even move sometimes, yeah... about the lag, always happens when adding more minions/bots, anyways, even dots/small cells that you can eat, those are like limit 5 on the map, if i reduce the map height to like 11k it will have more dots but i want a vanilla map....
its dead boys

**Comment by LegitSoulja** [comment]
No new skins will be added because that client is dead. When the new client is finished there will be new skins, better things. But that won't be until next year. (6 more days left).
