### ISSUE TITLE
Ban This IP

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1478]
![capture](https://cloud.githubusercontent.com/assets/18649707/18804985/ec470866-81b7-11e6-95e0-48363a8cbfbe.JPG)

This is their first time - they have done it several times afterwards too, with rude things towards Legit Too.

**Comment by LegitSoulja** [comment]
@SharkFinPro don't even worry about it.

**Comment by SharkFinPro** [comment]
k
