### ISSUE TITLE
Agario old version private server and 5 Minions to everyone :)

### ISSUE THREAD

**Issue by crazyverymmonkey** [AJS-development/Ogar-unlimited#1481]
Hey he is developing agario old version 6 months previous version.

[http://unforgiven.pw/](http://unforgiven.pw/)

Good 👍 Go here :)

**Comment by AlexandriteErikParacelsus** [comment]
Nice no lag

**Comment by crazyverymmonkey** [comment]
@AlexandriteErikParacelsus Thanks 👍 Very good substructure and other elements. Constantly updated.
