### ISSUE TITLE
serverMaxConnectionsPerIp is not working? And bots have in my server

### ISSUE THREAD

**Issue by crazyverymmonkey** [AJS-development/Ogar-unlimited#1482]
http://i.hizliresim.com/LQR36o.png

my serverMaxConnectionsPerIp = 3 but in my server a ip 100 players please fix and ban this ip.

Need a solve for bots...

And node.js v5.9.0 need?

**Comment by fayizan** [comment]
@crazyverymmonkey No more Support in Ogarul...

**Comment by SharkFinPro** [comment]
@crazyverymmonkey Try the massStart Plugin to fix it

**Comment by LegitSoulja** [comment]
Yes, MassStart can be a solution.
