### ISSUE TITLE
how the bordes moving?

### ISSUE THREAD

**Issue by arxn** [AJS-development/Ogar-unlimited#1483]
In agar.io when the cell rub others elements , as virus , the borders of the cell is move , how to do this?

**Comment by NatsuTheGreat** [comment]
I knew google translate isn't the best to use. This is because of graphics.

**Comment by LegitSoulja** [comment]
It's called better physics.

**Comment by NatsuTheGreat** [comment]
Not really the physics, it's mostly the rendering of the cells.
