### ISSUE TITLE
Very bugs have in ogar-unlimited.....

### ISSUE THREAD

**Issue by crazyverymmonkey** [AJS-development/Ogar-unlimited#1484]
1 - Minion splits in spectate mode....
2 - Failure to screen right, sometimes...
3 - serverMaxConnectionsPerIp is not found...
4 - feed breakings...

And other bugs..........

Please an update....

**Comment by crazyverymmonkey** [comment]
This bugs no have in real Ogar or JaraLowell/OgarServ

**Comment by LegitSoulja** [comment]
@crazyverymmonkey You can fix the problems yourself. But other than that, this project is discontinued!. There will not be anymore further updates.
