### ISSUE TITLE
Extension Agar

### ISSUE THREAD

**Issue by baana101** [AJS-development/Ogar-unlimited#1485]
In order for people to join my server they need a raga modz extension Is there a way to fix this im playing on agario If they dont have the extension theyll get the white screen pls help

**Comment by rydens** [comment]
I guess the issues will close in a few days anyway, so I might as well tell you this little thing:

Use the client files from [here](https://github.com/AJS-development/client/tree/gh-pages).
They work well enough, but aren't the same from old.ogarul.io.

**Comment by baana101** [comment]
What do i do with these files?

**Comment by rydens** [comment]
Find a way to host them, just like you would a normal website.
Just don't use Github pages, it's a little funky.
I recommend [surge.sh](surge.sh)

**Comment by systemroot** [comment]
you also can play from here http://old.ogarul.io/?ip=  *ex* **[ http://old.ogarul.io/?ip=1.1.1.1:443 ]**

**Comment by baana101** [comment]
The problem Is i have the  host and everything where do i drag these files?

**Comment by LegitSoulja** [comment]
The easiest way buddy is to download the client plugin, create a folder called client, and upload the files into that folder. Then you are done... Or 

Host your own web server. Which you will need an apache server. If you ever do pick one, I recommend xamp, or usb webserver(portable).
