### ISSUE TITLE
Install commands for linux centos 7 x64 

### ISSUE THREAD

**Issue by crazyverymmonkey** [AJS-development/Ogar-unlimited#1488]
Hello,

How node v5.9.0 install to linux centos 7 x64?

No have install node v5.9.0 in commands?

I'm using v6.6.0 but have bugs :/

And I love AJS developers :) Your legends :)

**Comment by crazyverymmonkey** [comment]
Or have install commands your ?

**Comment by systemroot** [comment]
**`npm cache clean -f`**
**`npm install -g n`**
**`n 5.9.0`**
**`sudo ln -sf /usr/local/n/versions/node/5.9.0/bin/node /usr/bin/node`**
**`cd ~/ && mkdir ogarul`**
**`cd ~/ogarul/`**
**`git clone https://github.com/AJS-development/Ogar-unlimited.git`**
**`cd Ogar-unlimited/src`**
**`npm install`**
**`node index.js`**

use forum for support http://forum.ogarul.io/ and post your problems on category "General support" http://forum.ogarul.io/forums/general-support.9/

**Comment by crazyverymmonkey** [comment]
Thx I try now <3

**Comment by fayizan** [comment]
Another Method,Follow Steps

Step 1: `curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -`
Step 2: `yum -y install nodejs`
Step 3: `yum groupinstall 'Development Tools'`
Step 4: `git clone https://github.com/AJS-development/Ogar-unlimited.git`
Step 5: `cd Ogar-unlimited`
Step 6: `npm install`
Step 7: `node index`
