### ISSUE TITLE
minionLoader ERROR in Ogar Unlimited v10.0.0

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#152]
I STARTED MY SERVER AND THEN I SAW UPDATE MESSAGE I DO >update yes THEN SERVER IS DOWNLOADING FILES THEN I SAW ERROR 
![error](https://cloud.githubusercontent.com/assets/17459204/13377690/6c860e18-dd9a-11e5-99c0-b73c93c1880a.png)

**Comment by Megabyte918** [comment]
Download the minionloader file and put it in the folder it says its missing from

**Comment by PrinceDark9243** [comment]
where i can download can you plz give me the link

**Comment by firelightning13** [comment]
Re-download the zip files

**Comment by PrinceDark9243** [comment]
i did but dosent work but when i created a new file with name minionLoad.js i put this file into ai folder then i run the server its work but when i did the command update yes again the minion loader and other files are created WOW WORK ISSUE FIXED
