### ISSUE TITLE
Agar.io public server

### ISSUE THREAD

**Issue by StormGS5** [AJS-development/Ogar-unlimited#153]
i cant make my server public other people cant join who can make my server public

**Comment by StormGS5** [comment]
what do i have to do to make my server online like so people can join it like agar.io

**Comment by ItzLevvie** [comment]
You'll have to port forward these ports (443, 88) and after that go on agar.io/?ip=localhost:443. For other people to join your server you'll have to replace 'localhost' with your external IP.

**Comment by StormGS5** [comment]
whats my external ip?

**Comment by StormGS5** [comment]
how do i port forward

**Comment by StormGS5** [comment]
ohh i get it now heres my server http://agar.io/?ip=192.168.1.89:443

**Comment by Agarian** [comment]
not work bro

**Comment by StormGS5** [comment]
it doesent!

**Comment by Agarian** [comment]
nope

**Comment by Agarian** [comment]
Connecting
If you cannot connect to the servers, check if you have some anti virus or firewall blocking the connection.

**Comment by StormGS5** [comment]
do u know how to make it work?

**Comment by Agarian** [comment]
no =\

**Comment by Agarian** [comment]
how do i get my external IP?

**Comment by StormGS5** [comment]
ill try to get it to work

**Comment by StormGS5** [comment]
i dont know thats what im trying to figure out to

**Comment by ItzLevvie** [comment]
http://www.whatsmyip.org

**Comment by StormGS5** [comment]
ok

**Comment by StormGS5** [comment]
i did that and it dident work

**Comment by StormGS5** [comment]
the one on the top not work

**Comment by hassanila97** [comment]
you need to port forward dude

**Comment by hassanila97** [comment]
and change port 443 to something else if youre using skype

**Comment by StormGS5** [comment]
HOW? GIVE ME LINK TO PORT FORWARD
I DONT USE SKYPE im on my pc

**Comment by ItzLevvie** [comment]
^

**Comment by hassanila97** [comment]
Come here I help you: https://join.skype.com/rwLQKnE5v9JO

**Comment by StormGS5** [comment]
i dont have skype

**Comment by hassanila97** [comment]
-_-

**Comment by StormGS5** [comment]
i have discord

**Comment by StormGS5** [comment]
just tell me here

**Comment by StormGS5** [comment]
pls

**Comment by hassanila97** [comment]
Goto 192.168.1.1

**Comment by StormGS5** [comment]
for what

**Comment by hassanila97** [comment]
open this link:  http://192.168.1.1   and tell me what you see

**Comment by StormGS5** [comment]
it said This webpage is not available.

**Comment by hassanila97** [comment]
Teamviewer??    Eamil id and pass here  hassaila97@gmail.com   if oyu wnt help    -_-

**Comment by StormGS5** [comment]
no i make a chat

**Comment by StormGS5** [comment]
heres my chat  i havent been on for 5 months http://bestnbkagarioclan.chatovod.com/

**Comment by PrinceDark9243** [comment]
@StormGS5 You need to port forward to make you server public like me http://agar.io/?ip=unnamedcell.ddns.net:28

**Comment by Megabyte918** [comment]
@StormGS5 Check out #121 it should explain how to do it :)

**Comment by Andrews54757** [comment]
To port foward, copy the number when you search up in google my ip. Then enter that number in your browser.

**Comment by NatsuTheGreat** [comment]
@StormGS5 I don't think anyone wants to join a trash server, just keep it in the junk yard along with yourself.

**Comment by Megabyte918** [comment]
Savage af

**Comment by NatsuTheGreat** [comment]
No, just MLG af.

**Comment by NatsuTheGreat** [comment]
@Megabyte918 Who are you referring to?

**Comment by Agarian** [comment]
The only savage person in this issue (you) :p

**Comment by NatsuTheGreat** [comment]
@Agarian Sorry that you aren't you against him. You might wanna join him and be the same disgrace he is.
