### ISSUE TITLE
how do u make a pull request

### ISSUE THREAD

**Issue by StormGS5** [AJS-development/Ogar-unlimited#154]
i dont know how tell me ! what is a pull request

**Comment by StormGS5** [comment]
i dun no how!

**Comment by Agarian** [comment]
Lol fork the respiratory

**Comment by NatsuTheGreat** [comment]
@StormGS5 You don't know how to do anything but be racist. Maybe you should know how to be smart with a rope and a tree branch.

**Comment by Andrews54757** [comment]
THIS IS SHAMEFUL THAT I HAVE TO PERSONALY REMOVE BAD COMMENTS
