### ISSUE TITLE
Ogar Unlimited v10.0.0 Commmand Error in Board and Opbyip

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#159]
When i got new version of ogar unlimited i am playing with my friends then i did board command when i did i saw my nick on board 4 time i typed `Hello lets Play Firends`
![untitled](https://cloud.githubusercontent.com/assets/17459204/13394879/05ea32cc-dea0-11e5-963c-fac0d0f44a9d.png)
Then after i did new Opbyip Command i typed `opbyip add 192.168.1.1` By testing command then a Error pop ups
![2](https://cloud.githubusercontent.com/assets/17459204/13394924/35b0b2b0-dea0-11e5-9634-6153594ef49f.png)

**Comment by ItzLevvie** [comment]
Change  ```view.setUint32(offset, 1, true);```  to  ```view.setUint32(offset, 0, true);```  in UpdateLeaderboard.js

**Comment by Andrews54757** [comment]
Fixed

**Comment by PrinceDark9243** [comment]
WHAT ABOUT OPBYIP COMMAND

**Comment by Andrews54757** [comment]
yeah, i fixed that too

**Comment by PrinceDark9243** [comment]
@Andrews54757 Thanks! For Creating good server for agar.io Very Much!!!! I love YOU!!!
