### ISSUE TITLE
Andrew how can i make the auto split like real agario?

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#16]
Andrew how can i make the auto split like real agario?

**Comment by Andrews54757** [comment]
Il look at it later

**Comment by Andrews54757** [comment]
BTW what do you mean make autosplit better?

**Comment by Agarian** [comment]
he means when you split at *playerMaxMass* limit, the splitting is off. its not like the regular split.

**Comment by Andrews54757** [comment]
I dont know how real autosplit works but what do you mean the splitting is off, does it mean you cant split again

**Comment by Agarian** [comment]
instead of directly splitting, it splits, stays there for half a second, then collides normally afterwards. ill make a gif if i can

**Comment by Agarian** [comment]
also freeroam works now :D

**Comment by Agarian** [comment]
here: 
![split](https://cloud.githubusercontent.com/assets/15255724/12706631/16e61dde-c857-11e5-8b98-b00ef963a523.gif)

**Comment by Agarian** [comment]
elitajmx wants to fix that^

**Comment by Agarian** [comment]
ur still here right?

**Comment by Andrews54757** [comment]
I will fix it by next week (or 2 days)

**Comment by Andrews54757** [comment]
i see what you mean and I can change it

**Comment by Andrews54757** [comment]
Oh yeah, I added it but realised that it was too buggy. I will make it better

**Comment by Andrews54757** [comment]
(A long time ago)

**Comment by Agarian** [comment]
Mk then good luck with the fix

**Comment by Agarian** [comment]
btw same issue with splitting on viruses

**Comment by Andrews54757** [comment]
I temporarily fixed autosplit and you mean the issue for viruses are only when you are big?

**Comment by Agarian** [comment]
yes

**Comment by Andrews54757** [comment]
Ok il see what I can do and can you guess what the future gamemode will be?

**Comment by Andrews54757** [comment]
Sorry but i cant do it now though I need to do the lab of mixing sulferic acid with magnesium

**Comment by Andrews54757** [comment]
I also have to do my history homework

**Comment by Agarian** [comment]
the gamemode is virus off

**Comment by Agarian** [comment]
also:
![capture](https://cloud.githubusercontent.com/assets/15255724/12734960/f128b7b2-c911-11e5-8af6-85a6523c1f60.JPG)

**Comment by Andrews54757** [comment]
Yes it is for developing mainly (especially with autosplit) and thenerror is probably caused because you are using an older version

**Comment by Andrews54757** [comment]
You can tell you have an older version if you dont have the colortext command

**Comment by Agarian** [comment]
i fixed it

**Comment by Andrews54757** [comment]
I also fixed maxclientsperip because even after leaving, the client number would be the same so i fixed it so it decreases. I would update. (Unless you dont have friends playing)

**Comment by Agarian** [comment]
fun with random ejected mass color
![lol](https://cloud.githubusercontent.com/assets/15255724/12735263/4d8007ca-c914-11e5-90c8-5b25ce5957bb.jpg)

**Comment by Andrews54757** [comment]
also I added you to https://github.com/AJS-development/Ogar-unlimited-Test list of collaborators so you can play around. It is a copy so dont worry and invited you to AJS dev

**Comment by Agarian** [comment]
cool

**Comment by Andrews54757** [comment]
Lol removed all unnecessary comments making this long

**Comment by Agarian** [comment]
about the GIF skins on cells, is there a way around having to get a newer OS or system for the GIF animations to work??

**Comment by Andrews54757** [comment]
Nope, that, you have to talk to the os creators or agar.io creators

**Comment by Agarian** [comment]
Shit

**Comment by Agarian** [comment]
close this?
