### ISSUE TITLE
Discuss here

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#162]

**Comment by Megabyte918** [comment]
hi

**Comment by hassanila97** [comment]
Hi @Megabyte918    I'm Terabyte.... LOL  :)

**Comment by Megabyte918** [comment]
Haha nice to meet you too terabyte xD

**Comment by StormGS5** [comment]
im stormbyte

**Comment by Megabyte918** [comment]
Hello stormbyte im megabyte :D

**Comment by Andrews54757** [comment]
@Agarian i gave you edit access becaz i am too lazy. Please dont do anything werd though

**Comment by Andrews54757** [comment]
@Megabyte918 i added you to the ajs organsation

**Comment by Megabyte918** [comment]
@Andrews54757 im honored ಥ_ಥ

**Comment by firelightning13** [comment]
lol

**Comment by StormGS5** [comment]
what just happened you make me wanna change my profile image!

**Comment by PrinceDark9243** [comment]
I love you @Andrews54757

**Comment by MichaelLeeHobbs** [comment]
I've finished up an initial review of the code and have addressed formatting / basic syntax issues. Tomorrow I'm going to take a look at some code that uses Sync which is bad on severs unless it is called during boot. I'm going to comment the ones that are a non-issue and try to address the ones that are an issue.

Formatting: I have applied the same .editorconfig that https://github.com/angular-fullstack/generator-angular-fullstack uses. It's fairly simple.

**Comment by StormGS5** [comment]
@MichaelLeeHobbs  is ur name michael?

**Comment by MichaelLeeHobbs** [comment]
Yeap

**Comment by ErikParacelsus** [comment]
HI megabyte it's me the guy who play on your private server, my skin was <maxrage>

**Comment by Megabyte918** [comment]
Hey man :) do u have skype? we could talk on there

**Comment by Andrews54757** [comment]
Everybody, Get prepared for the Suggestions Update described here! #182 ! it is slated for saturday mar 5

**Comment by Megabyte918** [comment]
Sweet! I cant wait :D

**Comment by Megabyte918** [comment]
Oh yeah, and thanks for adding the max mass thing ive been trying to figure out how to make that work forever

**Comment by ErikParacelsus** [comment]
Megabyte918 i sent you a contact on skype

**Comment by Megabyte918** [comment]
Got it

**Comment by Andrews54757** [comment]
THIS IS SOO SHAMEFUL THAT PEOPLE ARE DISRESPECTING OTHERS, I AM FREEZEING ALL ASSETS

**Comment by VSabertail** [comment]
https://discordapp.com/channels/167731579928576000/167731579928576000

**Comment by VSabertail** [comment]
#362

**Comment by VSabertail** [comment]
@Andrews54757  HOW COME EVERYONE BUT ME IS ADMIN >:(

**Comment by VSabertail** [comment]
@Andrews54757  THEN HOW COME EVERYONE BUT ME CAN LABLE AND ASSIGN TELL ME

**Comment by VSabertail** [comment]
@Andrews54757 # TELL ME!!!!!!!!

**Comment by Andrews54757** [comment]
only about 5 people are priveledged. and they do lots of edits and code. i dont think you do

**Comment by VSabertail** [comment]
I CAN CODE

**Comment by VSabertail** [comment]
Then how come you where saying u need a auto moderator then if 5 PEOPLE ARE!

**Comment by Andrews54757** [comment]
yeah but there is a reason only 5 can edit, its confusing enough that 5 are working, its even more confusing if more are working. Example, michealleehobbs is having a hard time because he needs to keep up with the lots of updates i do so that when he postshis changes, they dont overwrite mine and i have troouble with others working when i dont know exactly what they did. and i said that because comment moderating is not a big issue for the devs so we should have a robot do it for us, deleting extra comments as it takes forever to click them.

**Comment by Andrews54757** [comment]
we devs are very busy, i didnt add people becaz they can be social, i did it so we can work togethor on out code

**Comment by VSabertail** [comment]
OK  can code and i can make a robot auto moderator

**Comment by Andrews54757** [comment]
no,its probably really hard, i havent read the github api and i dont have a server that goes 24/7 all the time to moderate. end result: Not a really good idea in my circumstances

**Comment by Andrews54757** [comment]
i wish there was an option so you can only moderate comments only but it is not possible at this point, when github adds it, you will be the first one i go to

**Comment by VSabertail** [comment]
all i got to do is if someone doesen't mention a server link or something that has agario servers it auto deletes

**Comment by Andrews54757** [comment]
making the program is easy, but making it work well with github is hard. you would have to use its api

**Comment by VSabertail** [comment]
i get it

**Comment by VSabertail** [comment]
i have already made a auto messager bot before but a auto moderator bot seems hard i get i t now

**Comment by VSabertail** [comment]
i got a bot in my server on discord https://discordapp.com/channels/167731579928576000/167731579928576000

**Comment by VSabertail** [comment]
try to mention TypicalBot in chat it will msg you XD

**Comment by Agarian** [comment]
There was a similar bot called AutoModerator but its gone :disappointed:

**Comment by VSabertail** [comment]
Yes

**Comment by Agarian** [comment]
I hate using my android here!!!

**Comment by Agarian** [comment]
Also you can't link channels directly, u need to make an invite

**Comment by VSabertail** [comment]
https://discord.gg/0w5UeD1FjesTfSjv

**Comment by VSabertail** [comment]
me and the bots are having a fun time

**Comment by VSabertail** [comment]
LOL

**Comment by firelightning13** [comment]
eww

**Comment by VSabertail** [comment]
Guys go here http://agar.io/?ip=ogar-unlimited-server-mhfkoala.c9users.io

**Comment by firelightning13** [comment]
Trying to connect my private server using agarplus...
![image](https://cloud.githubusercontent.com/assets/17120382/14400587/c67ee61c-fe2c-11e5-8d1d-5935dae17e64.png)
RIPPED :"(

**Comment by Agarian** [comment]
im on

**Comment by firelightning13** [comment]
Why Travis-CI always say "build failing"?

**Comment by Agarian** [comment]
maybe a bug?

**Comment by MichaelLeeHobbs** [comment]
@firelightning13 @Agarian it was a bug on dev but I fixed it this weekend.

**Comment by XxRaizerxX** [comment]
sup

**Comment by VSabertail** [comment]
Heyyy Broo wuts up man!

**Comment by XxRaizerxX** [comment]
The sky is up

**Comment by XxRaizerxX** [comment]
LOLOL!

REKT

**Comment by XxRaizerxX** [comment]
Why is github so much alike to another website name?

**Comment by VSabertail** [comment]
DONT SAY IT LOL

**Comment by XxRaizerxX** [comment]
l

**Comment by XxRaizerxX** [comment]
Its not a bad word one of the server bots name is pornhub

**Comment by VSabertail** [comment]
yeah

**Comment by VSabertail** [comment]
ikr

**Comment by VSabertail** [comment]
go on my server

**Comment by firelightning13** [comment]
@Agarian Clean this thing up

**Comment by Agarian** [comment]
kden

**Comment by Megabyte918** [comment]
join this https://discord.gg/0vYaIdmfM1alqDTq

**Comment by RevivedSol** [comment]
help me .. I cant use the server.
I pressed istall independence(windows).bat but the thing didnt really work. It said something like cannot find phyton executable. then i try starting the server it said cannot find module

**Comment by Andrews54757** [comment]
try `npm install request`

**Comment by RevivedSol** [comment]
how should i do it

**Comment by Megabyte918** [comment]
open a terminal outside of the "src" folder and enter the command

**Comment by LegitSoulja** [comment]
I did both

**Comment by RevivedSol** [comment]
i did both but still not working

**Comment by Andrews54757** [comment]
do some research on google
