### ISSUE TITLE
I CANT START STAR.BAT WHAT THE FUCK!!!!!!!!!!! IM GONNA HURT MYSELF!!!!!!!!!!!!

### ISSUE THREAD

**Issue by StormGS5** [AJS-development/Ogar-unlimited#164]
WHY CANT I FREAKING START START.BAT WHYYYYYYYYYYYYYYYYYY!!!!!!!!!!!!!!!!!!!!!!!AAAAAAAAAAAA!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ItzLevvie** [comment]
Calm down

**Comment by NatsuTheGreat** [comment]
@StormGS5 Don't just hurt yourself, kill yourself.

**Comment by Agarian** [comment]
Im cutting out "WHAT THE FUCK!!!!!!!!!!! IM GONNA HURT MYSELF!!!!!!!!!!!!" From the issue name lol
