### ISSUE TITLE
Start.bat not working

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#165]

**Comment by Megabyte918** [comment]
send me the code directly then

**Comment by StormGS5** [comment]
it sais SyntaxError: Unexpected token if 
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:387:25
at Object.Module._extensions..js:357:32)
then bla bla blan 
then it sais Press any key to exit... 
by the way i already ran the install.bat stuff

**Comment by StormGS5** [comment]
heres the code @echo off
title Ogar Unlimited
:loop
node index.js
if errorlevel 1 (
	if not errorlevel 3 (
		GOTO END;
	))
goto loop
:END
echo.
echo Press any key to exit...
pause >nul

**Comment by Andrews54757** [comment]
The error was a typo, i fixed it now
