### ISSUE TITLE
Realistic bot names

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#170]
Hey @Andrews54757 I wanted to have more realistic botnames instead of just a bunch of skins, so I went out and played some agario, and I copied some names I saw (like clan names and stuff) and some other names that i saw, and i replaced the default names with those ones to have the more realistic ones and when i played. the leaderboard actually made it look like i was playing regular agar!

I was wondering if i could merge the botnames.txt that i have (not in my repo yet) with the default one for more realistic bot names. BUT the thing is, it has some cursewords and stuff in them (based off of the names i saw) and im not sure if i should make a pull request.

**Comment by StormGS5** [comment]
:+1:

**Comment by StormGS5** [comment]
:-1:

**Comment by StormGS5** [comment]
:+1:

**Comment by StormGS5** [comment]
LIKE MY new profile picture? '_'

**Comment by hassanila97** [comment]
-_-

**Comment by StormGS5** [comment]
XD

**Comment by Andrews54757** [comment]
yeah, you can make a pull request to do it and i will look over it.

**Comment by Agarian** [comment]
should i close this or no?

**Comment by Agarian** [comment]
thats a first for me

**Comment by Lukkez** [comment]
I will make pull request for some botnames, i have some custom nicks, like fakes yt ppl

**Comment by ErikParacelsus** [comment]
go to this website, it has a load of clan names nickagar.tk

**Comment by Lukkez** [comment]
I make some realistic names, download newer version
