### ISSUE TITLE
How to make your friends join your server (Port Forwading on Windows)

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#174]
Instructions to make a server who all can join and don't need hamachi:

1. Open your router at web, (mine is 192.168.25.1)
 1.1 How to get the router ip, press Windows + R, will appear a box at bottom left, type cmd, press enter, will appear the pc cmd, will appear:
![image](https://cloud.githubusercontent.com/assets/15003706/13434393/69fb7504-dfb4-11e5-8f0a-7505ad4b8d52.png), now get the adress with 192.168.your.ip, go to browser and type the ip
2. Go to advanced configurations, if you don't have see port forwading tuto for your router, this is only for some routers, now go to Port Forwading, now get your pc ip at config 'local web'
![image](https://cloud.githubusercontent.com/assets/15003706/13434560/0de4b41e-dfb5-11e5-90ce-962311513220.png)
, on my case it's 192.168.25.20, now go to 'Port forwading' 
![image](https://cloud.githubusercontent.com/assets/15003706/13434576/1eb9aa7e-dfb5-11e5-8565-58815efa5447.png), put the port you want and put tcp/udp and a name, save, now go to DMZ
![image](https://cloud.githubusercontent.com/assets/15003706/13434605/3a11cc20-dfb5-11e5-9268-7346b7540f8d.png) and put your ip and put on and save, now go to windows firewall and disable for the ports you forwaded. 
Sorry if i make any mistake, i'm brazillian and i didn't finish my English at school
3. Go to [whatismyip](https://www.whatismyip.com/) Get your ip, send the server for you friends like:
http://agar.io/?ip=your.ip.here.xxx:PORT

**Comment by StormGS5** [comment]
WHAT THE LINK IDIOT ! TO THE PORT FORWARDING IN NOT A GENIUS

**Comment by StormGS5** [comment]
192.168.1.89

**Comment by StormGS5** [comment]
mine dont link jackass

**Comment by Lukkez** [comment]
I say: get the 192.168.your.ip and put this on web

**Comment by firelightning13** [comment]
Hmm how to host it 24/7? Sorry im newbie

**Comment by ItzLevvie** [comment]
Leave your computer on or just buy a VPS

**Comment by Andrews54757** [comment]
or use something like heroku. Go to https://github.com/Andrews54757/Ogar-unlimited-heroku and click the deploy button

**Comment by Agarian** [comment]
its outdated.

**Comment by Andrews54757** [comment]
but it works. I will update on the big update

**Comment by Lukkez** [comment]
This not outdated, it's for ppl who don't have money to buy vps, i can but i don't want to waste money

**Comment by firelightning13** [comment]
Ok ill try it later

**Comment by Andrews54757** [comment]
THIS IS SOO SHAMEFUL THAT PEOPLE ARE DISRESPECTING OTHERS, I AM FREEZEING ALL ASSETS

**Comment by Agarian** [comment]
lol c9 is way easier than this tho #280

**Comment by firelightning13** [comment]
@Agarian :D

**Comment by Agarian** [comment]
Should i close this?

**Comment by SharkFinProductions** [comment]
When i run the server it says that my port "443" is open, i can join using 127.0.0.1, but when i use my ip instead of 127.0.0.1 i ca n't join, does this mean my friends can't join too?
