### ISSUE TITLE
Individual Player Starting Mass

### ISSUE THREAD

**Issue by MasonBurdette** [AJS-development/Ogar-unlimited#179]
Feature Request:
----------------------------
I would like to be able to set player starting mass, by ID.

Example
----------------------------
ID 1 - 43 mass
ID 2 - 132 mass
ID 3 - 10 mass

**Comment by Lukkez** [comment]
Please put on Suggetistions

**Comment by MasonBurdette** [comment]
@Lukkez Where would I locate that?

**Comment by Agarian** [comment]
#46  < click that
