### ISSUE TITLE
agario nazi skin not working

### ISSUE THREAD

**Issue by StormGS5** [AJS-development/Ogar-unlimited#183]
the nazi skin is not working add it pls

**Comment by Andrews54757** [comment]
No, it is extremely disrespectful to the holocaust. Also, i am researching it now in school and it is nothing to joke about

**Comment by NatsuTheGreat** [comment]
@StormGS5 No one will serve a cum guzzler.

**Comment by Andrews54757** [comment]
THIS IS SOO SHAMEFUL THAT PEOPLE ARE DISRESPECTING OTHERS, I AM FREEZEING ALL ASSETS
