### ISSUE TITLE
Bug reports

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#184]
any bugs that are found can be discussed and/or reported here.

**Comment by StormGS5** [comment]
OK PLS NAZI SKIN NEED ADDING!!

**Comment by Andrews54757** [comment]
No, not if you have any respect for what happened in the holocaust

**Comment by Lukkez** [comment]
Agar.io removed, not a bug, i can add but NO, Hitler is one of most BAD PEOPLE of world, as @Andrews54757 Says

**Comment by Megabyte918** [comment]
Same with trump hahaha

**Comment by Andrews54757** [comment]
[Click this for details on the holocaust] (https://www.ushmm.org/wlc/en/article.php?ModuleId=10005143)

**Comment by Megabyte918** [comment]
Sometimes when playing with minions when i press "q" the B from my name doesnt dissapear and it gets really confusing

**Comment by Andrews54757** [comment]
it is when you have an empty name, i don't know why it happens

**Comment by Megabyte918** [comment]
and is this supposed to happen? http://prnt.sc/aahq0w

**Comment by Andrews54757** [comment]
its because your not using the stable update, you are using the update in pull requests

**Comment by Agarian** [comment]
lol i didn't like having to create a whole new issue for every bug someone finds. so i had this and already business is booming :smile:

**Comment by Andrews54757** [comment]
not really, because then we don't know when there is a new bug. i just like the way it pops up in my notifications. but sure, if you want to solve them.

**Comment by Megabyte918** [comment]
@Andrews54757 again thank u so much http://giphy.com/gifs/3ornjOHiHtItz0MRUY

**Comment by NatsuTheGreat** [comment]
@StormGS5 Go fucking go suck up to your gay boy Hitler. He loves fanboys like you trying to make him fell better in hell after commiting suicide when he got fucking crushed. Unless you want to a nazi fanboy you might aswell do it in hell and afterward die in agony for the little shit you are. He can't fight nor can you. Hitler and his wife did suicide. You're a fan boy right? Go through the same steps, but without a wife, no one would want to marry you. Go die in a torment.

**Comment by Andrews54757** [comment]
@NatsuTheGreat please dont be mean. Although storm is sometimes a idiot. You should still respect others

**Comment by NatsuTheGreat** [comment]
@Andrews54757 His love for Hitler doesn't belong here.

**Comment by Andrews54757** [comment]
I know, i deleted them now

**Comment by Andrews54757** [comment]
It is completely rude to joke about something as serious as the holocaust

**Comment by Andrews54757** [comment]
So i condem him for that

**Comment by NatsuTheGreat** [comment]
K. I want to let him read it then remove it. All that the Nazis did to the poor unarmed people was just horrid. I don't understand a person who would suck up to the Nazis

**Comment by Andrews54757** [comment]
I understand as i am actualy researching the topic for a project right now. That was why i was busy. To do the paper and everything

**Comment by Megabyte918** [comment]
Oh another bug: when feeding minions the w's sometimes shoot through them instead instead going into them

**Comment by firelightning13** [comment]
Set minionupdate = 1 in gameserver.ini

**Comment by PrinceDark9243** [comment]
I want to say that in experimental mode spawner dosent give us mass back it just always losing mass

**Comment by hassanila97** [comment]
@PrinceDark9243 I have the same problem...  the spawner is too buggy ...   also when I split near it I go inside for no reason....

**Comment by StormGS5** [comment]
HEY HOW BOUT YOU GO SUCK URSELF

On March 2, 2016, at 11:44 PM, NatsuTheGreat <notifications@github.com> wrote:

@StormGS5 Go fucking go suck up to your gay boy Hitler. He loves fanboys like you trying to make him fell better in hell after commiting suicide when he got fucking crushed. Unless you want to a nazi fanboy you might aswell do it in hell and afterward die in agony for the little shit you are. He can't fight nor can you. Hitler and his wife did suicide. You're a fan boy right? Go through the same steps, but without a wife, no one would want to marry you. Go die in a torment.

**Comment by StormGS5** [comment]
I'm 25% Nazi we will star ww3 and end the world
And by the way I am getting married when I'm older I already have a girlfriend who loves me 


On March 2, 2016, at 11:44 PM, NatsuTheGreat <notifications@github.com> wrote:

@StormGS5 Go fucking go suck up to your gay boy Hitler. He loves fanboys like you trying to make him fell better in hell after commiting suicide when he got fucking crushed. Unless you want to a nazi fanboy you might aswell do it in hell and afterward die in agony for the little shit you are. He can't fight nor can you. Hitler and his wife did suicide. You're a fan boy right? Go through the same steps, but without a wife, no one would want to marry you. Go die in a torment.

**Comment by ItzLevvie** [comment]
@NatsuTheGreat shh

**Comment by ItzLevvie** [comment]
@StormGS5 I'm already married :P

**Comment by Agarian** [comment]
Lol

**Comment by ItzLevvie** [comment]
Lol

**Comment by ItzLevvie** [comment]
Ok

**Comment by ItzLevvie** [comment]
LOLOLOLOLOLOL

**Comment by StormGS5** [comment]
@Andrews54757 the nazi skin not work

**Comment by Andrews54757** [comment]
THE NAZI SKIN IS DISABLED ON PURPOSE

**Comment by Agarian** [comment]
@StormGS5 GS why are you so into the Nazi skin? if you like it so much maybe you should marry it. lol but seriously stop the nonsense.

**Comment by NatsuTheGreat** [comment]
@StormGS5 Fuck off, no matter how much you try to be a nazi suck-up boy they don't accept shit like you. Get off of github you disgrace to humanity.

**Comment by Agarian** [comment]
WHAT THE F@$# DO UOU HAVE AGAINST GS?

**Comment by NatsuTheGreat** [comment]
Nazi.

**Comment by Agarian** [comment]
I said besides nazi but i realized thats actually a good reason.

**Comment by NatsuTheGreat** [comment]
Dude just being a fanatic of Nazi's ruined his reputation.

**Comment by Megabyte918** [comment]
R.I.P bug reports
2016-2016

**Comment by firelightning13** [comment]
ripped lol

**Comment by zynch** [comment]
is this supposed to happend? http://imgur.com/ftQqNOT because i cant spawn and connected to the private server, pls help!

**Comment by fayizan** [comment]
@zynch  see this troubleshooting guide #638

**Comment by zynch** [comment]
@fayizan thanks. :D
