### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#189]
# Lets try this again...

**Comment by StormGS5** [comment]
can u add it so people can join the server without port forwarding just by creating a link in gameserver.ini

**Comment by Andrews54757** [comment]
no as that is impossible

**Comment by StormGS5** [comment]
ok
then how to i even port forward

**Comment by StormGS5** [comment]
pls i tried so many times

**Comment by StormGS5** [comment]
Finally i'm done whew well i made a split macro using Q took me a while to make it
but i dont know how to make it into a 1 word link :(

**Comment by StormGS5** [comment]
@Andrews54757  can you show me how to do that

**Comment by StormGS5** [comment]
// ==UserScript==
// @name         Agario Mass - Q
// @namespace    Very Fast Macro
// @version      0.5
// @description  fastest macro ever
// @author       StormGS
// @match        http://agar.io/
// @match        http://agar.io/?ip=*
// @grant        none
// ==/UserScript==

//v1
//Press a will fire upto 8 feeds
/*$(document).on('keydown',function(e){
if(e.keyCode == 81){
for(var i = 0; i<8; i++){
$("body").trigger($.Event("keydown", { keyCode: 87}));
$("body").trigger($.Event("keyup", { keyCode: 87}));
}
}
})
*/

//v2
//Press a will fire upto 8 feeds
/*$(document).on('keyup',function(e){
if(e.keyCode == 81){
var count = 0;
var interval = setInterval(function() {
if(count > 7){
clearInterval(interval);
return;
}
count++
console.log('firing')
$("body").trigger($.Event("keydown", { keyCode: 87}));
$("body").trigger($.Event("keyup", { keyCode: 87}));
}, 50);
}
})*/

//v3
//Press Q will fire upto 20 feeds
/*var interval;
var theSwitch = false;
$(document).on('keyup',function(e){
if(e.keyCode == 81){
var count = 0;
if(theSwitch){
theSwitch = false;
clearInterval(interval);
return;
}
theSwitch = true;
interval = setInterval(function() {
if(count > 20){ //Change this number if you want more
theSwitch = false;
clearInterval(interval);
return;
}
count++
console.log('firing')
$("body").trigger($.Event("keydown", { keyCode: 87}));
$("body").trigger($.Event("keyup", { keyCode: 87}));
}, 10);//increase this number to make it fire them out slower
}
})*/

//v4
//Hold a down and it will keep firing untill you take your finger off!
console.log('called');
var interval;
var switchy = false;
$(document).on('keydown',function(e){
console.log('keydown e.keyCode="'+e.keyCode+'"');
if(e.keyCode == 81){
console.log('keydown 81, switchy '+switchy);
if(switchy){
return;
}
switchy = true;
interval = setInterval(function() {
console.log('firing');
$("body").trigger($.Event("keydown", { keyCode: 87}));
$("body").trigger($.Event("keyup", { keyCode: 87}));
}, 3);//increase this number to make it fire them out slower
}
})

$(document).on('keyup',function(e){
console.log('keyup e.keyCode="'+e.keyCode+'"');
if(e.keyCode == 81){
console.log('stop firing');
switchy = false;
clearInterval(interval);
return;
}
})

**Comment by StormGS5** [comment]
`// ==UserScript==
// @name         Agario Mass - Q
// @namespace    Very Fast Macro
// @version      0.5
// @description  fastest macro ever
// @author       StormGS
// @match        http://agar.io/
// @match        http://agar.io/?ip=*
// @grant        none
// ==/UserScript==

//v1
//Press a will fire upto 8 feeds
/*$(document).on('keydown',function(e){
if(e.keyCode == 81){
for(var i = 0; i<8; i++){
$("body").trigger($.Event("keydown", { keyCode: 87}));
$("body").trigger($.Event("keyup", { keyCode: 87}));
}
}
})
*/

//v2
//Press a will fire upto 8 feeds
/*$(document).on('keyup',function(e){
if(e.keyCode == 81){
var count = 0;
var interval = setInterval(function() {
if(count > 7){
clearInterval(interval);
return;
}
count++
console.log('firing')
$("body").trigger($.Event("keydown", { keyCode: 87}));
$("body").trigger($.Event("keyup", { keyCode: 87}));
}, 50);
}
})*/

//v3
//Press Q will fire upto 20 feeds
/*var interval;
var theSwitch = false;
$(document).on('keyup',function(e){
if(e.keyCode == 81){
var count = 0;
if(theSwitch){
theSwitch = false;
clearInterval(interval);
return;
}
theSwitch = true;
interval = setInterval(function() {
if(count > 20){ //Change this number if you want more
theSwitch = false;
clearInterval(interval);
return;
}
count++
console.log('firing')
$("body").trigger($.Event("keydown", { keyCode: 87}));
$("body").trigger($.Event("keyup", { keyCode: 87}));
}, 10);//increase this number to make it fire them out slower
}
})*/

//v4
//Hold a down and it will keep firing untill you take your finger off!
console.log('called');
var interval;
var switchy = false;
$(document).on('keydown',function(e){
console.log('keydown e.keyCode="'+e.keyCode+'"');
if(e.keyCode == 81){
console.log('keydown 81, switchy '+switchy);
if(switchy){
return;
}
switchy = true;
interval = setInterval(function() {
console.log('firing');
$("body").trigger($.Event("keydown", { keyCode: 87}));
$("body").trigger($.Event("keyup", { keyCode: 87}));
}, 3);//increase this number to make it fire them out slower
}
})

$(document).on('keyup',function(e){
console.log('keyup e.keyCode="'+e.keyCode+'"');
if(e.keyCode == 81){
console.log('stop firing');
switchy = false;
clearInterval(interval);
return;
}
})
`

**Comment by StormGS5** [comment]
[// ==UserScript==
// @name         Agario Mass - Q
// @namespace    Very Fast Macro
// @version      0.5
// @description  fastest macro ever
// @author       StormGS
// @match        http://agar.io/
// @match        http://agar.io/?ip=*
// @grant        none
// ==/UserScript==

//v1
//Press a will fire upto 8 feeds
/*$(document).on('keydown',function(e){
if(e.keyCode == 81){
for(var i = 0; i<8; i++){
$("body").trigger($.Event("keydown", { keyCode: 87}));
$("body").trigger($.Event("keyup", { keyCode: 87}));
}
}
})
*/

//v2
//Press a will fire upto 8 feeds
/*$(document).on('keyup',function(e){
if(e.keyCode == 81){
var count = 0;
var interval = setInterval(function() {
if(count > 7){
clearInterval(interval);
return;
}
count++
console.log('firing')
$("body").trigger($.Event("keydown", { keyCode: 87}));
$("body").trigger($.Event("keyup", { keyCode: 87}));
}, 50);
}
})*/

//v3
//Press Q will fire upto 20 feeds
/*var interval;
var theSwitch = false;
$(document).on('keyup',function(e){
if(e.keyCode == 81){
var count = 0;
if(theSwitch){
theSwitch = false;
clearInterval(interval);
return;
}
theSwitch = true;
interval = setInterval(function() {
if(count > 20){ //Change this number if you want more
theSwitch = false;
clearInterval(interval);
return;
}
count++
console.log('firing')
$("body").trigger($.Event("keydown", { keyCode: 87}));
$("body").trigger($.Event("keyup", { keyCode: 87}));
}, 10);//increase this number to make it fire them out slower
}
})*/

//v4
//Hold a down and it will keep firing untill you take your finger off!
console.log('called');
var interval;
var switchy = false;
$(document).on('keydown',function(e){
console.log('keydown e.keyCode="'+e.keyCode+'"');
if(e.keyCode == 81){
console.log('keydown 81, switchy '+switchy);
if(switchy){
return;
}
switchy = true;
interval = setInterval(function() {
console.log('firing');
$("body").trigger($.Event("keydown", { keyCode: 87}));
$("body").trigger($.Event("keyup", { keyCode: 87}));
}, 3);//increase this number to make it fire them out slower
}
})

$(document).on('keyup',function(e){
console.log('keyup e.keyCode="'+e.keyCode+'"');
if(e.keyCode == 81){
console.log('stop firing');
switchy = false;
clearInterval(interval);
return;
}
})
](url)

**Comment by StormGS5** [comment]
> // ==UserScript==
// @name         Agario Mass - Q
// @namespace    Very Fast Macro
// @version      0.5
// @description  fastest macro ever
// @author       StormGS
// @match        http://agar.io/
// @match        http://agar.io/?ip=*
// @grant        none
// ==/UserScript==

//v1
//Press a will fire upto 8 feeds
/*$(document).on('keydown',function(e){
if(e.keyCode == 81){
for(var i = 0; i<8; i++){
$("body").trigger($.Event("keydown", { keyCode: 87}));
$("body").trigger($.Event("keyup", { keyCode: 87}));
}
}
})
*/

//v2
//Press a will fire upto 8 feeds
/*$(document).on('keyup',function(e){
if(e.keyCode == 81){
var count = 0;
var interval = setInterval(function() {
if(count > 7){
clearInterval(interval);
return;
}
count++
console.log('firing')
$("body").trigger($.Event("keydown", { keyCode: 87}));
$("body").trigger($.Event("keyup", { keyCode: 87}));
}, 50);
}
})*/

//v3
//Press Q will fire upto 20 feeds
/*var interval;
var theSwitch = false;
$(document).on('keyup',function(e){
if(e.keyCode == 81){
var count = 0;
if(theSwitch){
theSwitch = false;
clearInterval(interval);
return;
}
theSwitch = true;
interval = setInterval(function() {
if(count > 20){ //Change this number if you want more
theSwitch = false;
clearInterval(interval);
return;
}
count++
console.log('firing')
$("body").trigger($.Event("keydown", { keyCode: 87}));
$("body").trigger($.Event("keyup", { keyCode: 87}));
}, 10);//increase this number to make it fire them out slower
}
})*/

//v4
//Hold a down and it will keep firing untill you take your finger off!
console.log('called');
var interval;
var switchy = false;
$(document).on('keydown',function(e){
console.log('keydown e.keyCode="'+e.keyCode+'"');
if(e.keyCode == 81){
console.log('keydown 81, switchy '+switchy);
if(switchy){
return;
}
switchy = true;
interval = setInterval(function() {
console.log('firing');
$("body").trigger($.Event("keydown", { keyCode: 87}));
$("body").trigger($.Event("keyup", { keyCode: 87}));
}, 3);//increase this number to make it fire them out slower
}
})

$(document).on('keyup',function(e){
console.log('keyup e.keyCode="'+e.keyCode+'"');
if(e.keyCode == 81){
console.log('stop firing');
switchy = false;
clearInterval(interval);
return;
}
})

**Comment by StormGS5** [comment]
nevermind i got it 
[Agario Q split macro.txt](https://github.com/AJS-development/Ogar-unlimited/files/160048/Agario.Q.split.macro.txt)

**Comment by StormGS5** [comment]
you can probally add it to game

**Comment by StormGS5** [comment]
and i got another one coming for the agario minion like a minion split using e and minion eject using r
so

**Comment by MasonBurdette** [comment]
@StormGS5 are you lief (skype)?

**Comment by BoatXD** [comment]
Could you do an account system? (facebook login or so..?)

**Comment by Andrews54757** [comment]
@BoatXD  that would be very hard

**Comment by BoatXD** [comment]
Isn't that the point? :)

**Comment by StormGS5** [comment]
can you add servers like agarserv where u can make a server and let your friends join it like agarserv

**Comment by StormGS5** [comment]
can you?

**Comment by Lukkez** [comment]
Let's make a auto annunce, like every 10 mins put a link for something, or change board ?, idk if already have if have i will delete my comment

**Comment by StormGS5** [comment]
works

**Comment by Megabyte918** [comment]
What about a gamemode where there would be things that look like black holes, but their a different color and when you hit them it bounces you back, and also have black holes ;p

**Comment by NatsuTheGreat** [comment]
@Megabyte918 I could try to work on that, just can you specify the black holes more?

**Comment by Megabyte918** [comment]
I just mean random cells that spawn around the map (not spiked) that when you run into them they bounce u back and not the same color as the black holes in the black hole gamemode cause that would be confusing

**Comment by NatsuTheGreat** [comment]
I could create that but what do you mean by "bounce off"?

**Comment by Megabyte918** [comment]
when you hit it your cell bounces back kind of like a "spring"

**Comment by NatsuTheGreat** [comment]
How far?

**Comment by Megabyte918** [comment]
im thinking that it would depend on your size cause if big cells get pushed at the same speed as smaller ones than it wont really affect big people that much

**Comment by NatsuTheGreat** [comment]
Is bouncing off the only thing that will happen?

**Comment by Megabyte918** [comment]
for the bouncy things yes and then black holes will just teleport

**Comment by NatsuTheGreat** [comment]
Teleport? xD

**Comment by Megabyte918** [comment]
OMG i was thinking of the blackholes on agarserv im so stupid >.>

**Comment by Megabyte918** [comment]
you go into the blackholes and they teleport you to a random spot on the map

**Comment by Agarian** [comment]
STORM GS TOOK MY DAMN MACRO!

**Comment by Megabyte918** [comment]
How?

**Comment by Andrews54757** [comment]
@Megabyte918 agrarian made a macro script and stormgs copied it, claiming as his own

**Comment by NatsuTheGreat** [comment]
Wow. Didn't know he'd go from Nazi to a plagiarizer.

**Comment by Megabyte918** [comment]
You guys DO know that if you look up "agario scripts" on google u can find like 20 of them right

**Comment by Agarian** [comment]
Apologies for my lack of collaboration lately, I've been in Michigan and wil be until the 22nd of March. And my only available form of communication, currently, is android.

**Comment by Megabyte918** [comment]
Its alright m8, im actually leaving to go to California for 2 weeks on the same date u get back xD

**Comment by Megabyte918** [comment]
OOH what about a gamemode from agariomods that when you press "q" your cell moves faster kind of like sprinting

**Comment by Agarian** [comment]
But only temporary. And wity a cooldown of 10 seconds

**Comment by StormGS5** [comment]
@agarian no i dident copy anything of it i made a new one from scratch using a different key

**Comment by StormGS5** [comment]
@agarian and my friend helped me so if i got the wrong text out it could of been a mistake but if it was 
then tell me

**Comment by StormGS5** [comment]
i can name lots of stuff not copied first i had `}, 10);//increase this number to make it fire them out slower` you had }, 2);//increase this number to make it fire them out slower

**Comment by StormGS5** [comment]
oh and i made a new one to show u i dident copy it 
bruh 
how bout not bitch
[Macro.txt](https://github.com/AJS-development/Ogar-unlimited/files/168264/Macro.txt)

**Comment by StormGS5** [comment]
@NatsuTheGreat yeah we all have our likes and dislikes if i found out ur most embarassing one i will announce

**Comment by Megabyte918** [comment]
Guys, please be respectful this is why andrew closed the issues in the first place

**Comment by NatsuTheGreat** [comment]
> i can name lots of stuff not copied first i had }, 10);//increase this number to make it fire them out slower you had }, 2);//increase this number to make it fire them out slower

First. That's one thing you named.

Second. Modifying stuff behind // and stuff like the above doesn't mean it isn't agarian's. You Took his version and copied that stuff word for word then modified the most unimportant things without acknowledging what is does or what it's used for. You wouldn't understand one bit of the code he wrote.

About your dislike/like thing, the only dislike here is you. I just announced that for you, so no need for you to announce it, no one wants to hear you anyways.

**Comment by firelightning13** [comment]
Guys, don't do this again....

**Comment by Agarian** [comment]
This is the house i lived in 12 yrs ago lol 
![14577245396311380029989](https://cloud.githubusercontent.com/assets/15255724/13713170/a3f17720-e795-11e5-925d-8c70f739edc1.jpg)

**Comment by NatsuTheGreat** [comment]
Doesn't look too bad!

**Comment by Agarian** [comment]
Is was definitely a rural area =/

**Comment by NatsuTheGreat** [comment]
Yeah I bet.

**Comment by firelightning13** [comment]
@Andrews54757 How to make pmsg repeating infinitely?

Oh and 1 more thing: The mothercell is so buggy right now, spawning the foods non-stop, making the map difficult to spawn food. pls fix it

AND, about gameserver.ini, i think i can sort/generalize some of the configs so it doesnt look messy when reading the comment lines

**Comment by Megabyte918** [comment]
back to suggestions: 
@Andrews54757 what about a config that lets you change how much bigger you have to be to eat someone? in vanilla agar you have to be 25% bigger but what about something like `sizeconsumepercent` or something

**Comment by firelightning13** [comment]
@Megabyte918 That would be a good idea!

@Andrews54757 The mothercell is buggy right now, spawning foods very often and causing the game will be difficult to spawn food in the map

**Comment by Megabyte918** [comment]
what about a config that allows switching between vanilla Ogar virus explosions and OgarUL virus explosions? imo the ogar one is more similar to vanilla agario

**Comment by NatsuTheGreat** [comment]
what is ogarul? Can I have the link?

**Comment by Megabyte918** [comment]
abbreviation for ogar unlimited

**Comment by NatsuTheGreat** [comment]
Oh xD

**Comment by Megabyte918** [comment]
oh and [anotha one,](http://imc.ulximg.com/image/src/cover/1382993011_0fa861f425ad9baaf30e8207da8e7bca.jpg/ba3fc5b69ae0a2612aa50158b5978bfe/1382993011_c527424d219aa9ddf2c5aa78d5d37d61.jpg) what about a minionbyip command? kind of like opbyip, but it gives you minions every time you connect with a specific ip. cause i cant give myself minions when i dont have access to the command prompt lel

**Comment by firelightning13** [comment]
Ogar original is better at virus explosion?

**Comment by Agarian** [comment]
Yes

**Comment by Megabyte918** [comment]
In my opinion

**Comment by elitajmx** [comment]
There should be a thing added called: gamespeed, where you could change gamespeed in the CONSOLE if that is possible?

**Comment by MichaelLeeHobbs** [comment]
@elitajmx it is possible but that wont happen till after our major update/over haul we are working on.

**Comment by elitajmx** [comment]
ok

**Comment by Megabyte918** [comment]
What about a config that lets you change the amount of ram in mb your server runs on?

**Comment by elitajmx** [comment]
if possible, id' be awesome if you can change the like thing that would allow all your minions to have skins

**Comment by Agarian** [comment]
U can make ur minions have  skins

**Comment by Lukkez** [comment]
Put ``minion id <skin>name amount`` like: ``minion 1 <spy>Bot 10``

**Comment by Agarian** [comment]
what @Lukkez said

**Comment by Andrews54757** [comment]
@elitajmx , gamespeed is controlled by fps. As it stands for frames per second

**Comment by elitajmx** [comment]
yeah but when u like spawn 50 of them, every bot has a different skin.. i can do that but takes like 10min, is there anyway to save it?

**Comment by elitajmx** [comment]
How about making some bots 10 mass and without skin and some bots 44 mass and with skin? is it like possible to have some 10 and some 44 mass.

**Comment by Eragos** [comment]
Maybe it is possible to move all the config files to a separate config dir, so people with a docker image have an easier life to map this dir to a persistent storage?

**Comment by Andrews54757** [comment]
@Eragos Have you seen the dev branch? I think this answers your question. @MichaelLeeHobbs and I are completely refactoring ogarUL so expect very big changes! 
features include
plugins
preformance (now you can load 700 bots and be fine)
much more

**Comment by Megabyte918** [comment]
@Andrews54757 Can't wait! When will this be merged?

**Comment by Agarian** [comment]
Omg

**Comment by Eragos** [comment]
Another suggestion: 
When you run Ogar behind docker nginx proxy, you get the docker gateway (172.17.0.1) as client IP. Nginx is set a proxy header "header x-forwarded-for" but Ogar do not look at this.

> Q2016-03-30T21:11:57.094991200Z A player with an IP of 172.17.0.1 joined the game

Normally you can user something like this:
`var ip = req.headers['x-forwarded-for'] || req.connection.remoteAddress;`

**Comment by firelightning13** [comment]
How to make a cell with 130 mass eating virus **NOT** 136 mass **WITHOUT** change the virus's mass?

 | Vanilla Agar.io | Ogar/OgarUL
--- | --- | ---
**Mass required to eat a virus** | 130 | 136

**Comment by Lukkez** [comment]
@firelightning13 The mass to eat on a virus is 132 or 133 to up, **these masses** other's you can't.

**Comment by firelightning13** [comment]
@Lukkez wat

**Comment by Agarian** [comment]
I suggest that the experimental mothercells here should be more like the mothercells in ogarproject.
Also @NatsuTheGreat i didn't mention this b4 but the smoother eject mass didn't actually seem to do anything.

**Comment by NatsuTheGreat** [comment]
@Agarian I didn't really want to copy Ogar, but I will fix the ejecting mass.

**Comment by Agarian** [comment]
I suggest a config for *botrespawndelay*
the config name says it all.

**Comment by NatsuTheGreat** [comment]
Uhm isnt serverBotAmount meant for that?

**Comment by Agarian** [comment]
no it would set a delay for when a bot respawns. if it were set to 6 for example, then when a bot dies, it takes 6 seconds to respawn.

**Comment by NatsuTheGreat** [comment]
Oh, we can try to set up a timeout for bot respawn.
I think that should be somewhere in BotPlayer.js

**Comment by NatsuTheGreat** [comment]
I really give up, this stupid AI can't read the property of 'gameMode' -.-

**Comment by Megabyte918** [comment]
@MichaelLeeHobbs your good with AI, right? Maybe add this config in the upcoming update?

**Comment by VSabertail** [comment]
You should add something like Last Man Standing and maby make bot skills random like one of the bots is better and one is worse like random bot update 1-25 for each bot random number 
BotRandomSpawn-Set 1 for bots to spawn with random skills set to 0 for bots to spawn with a certain bot update 
And also maby add Something that Allows Bots to team with each other

**Comment by VSabertail** [comment]
It might be hard but, its i thinks its worth a try.

**Comment by firelightning13** [comment]
@VSabertail They still needs a lot of bigger fish to fry ;D

Am I right? lol

**Comment by VSabertail** [comment]
@firelightning13  maby but i mean like after hey go on discord pls 
https://discordapp.com/channels/156531998696013824/156531998696013824

**Comment by Andrews54757** [comment]
i going to refresh suggestions as this goes off topic too much
