### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#191]
These are the top FAQs
----------------------------------------------------------
**1.Auto restart?**
Auto restart only works if you use the windows start file.

**2.See high score?**
To see high score, do the highscore command or use live console. If you want to periodically display the highscore in game, do the announce command to start the feature or set AnounceHighScore to 1 in `config.ini`. You can edit the duration and the delay in `config.ini`.

**3.Why is there a "cannot find module" error?**
Instead of `npm install ws`, you have to either `cd` into `src`, do `npm install` or if you did `npm install ws`, do `npm install request`. You can also run the file `Install dependencies(windows).bat`

**4.How to join through hamachi?**
We do not know how to do it and it is outside of the scope of the project but to see some answers from the community, try issues #121 or #174, you can also try c9.io, as it is way easier. See issue #280.

**5.How to join the server?**
See issue #174 or read README.md.

**6.I see a interesting update pull request, why not update now?**
There is a method to our madness. That way, there is less bugs and we can add more features as well. No last minute changes.

**7.How do you start the server?**
Please go to the installation guide In the repository or issue #280

**8.How to set up using heroku?**
Please go to Andrews54757's repo called ogar unlimited heroku.(outdated )

**9.Help, the Agar.io website has gone crazy and/or is not working!**
If it does, it is probably not our problem as it is client sided. So it's probably the website. But it might also be your computer, try switching browsers. If it still doesnt work, contact agar.io.

**10.Why is there so much lag?**
It is because of nodejs's limited functionality and the foundation ogar unlimited was placed upon. Since ogar unlimited has many features and node is a limited, single threaded shell, it is difficult as the entire server pauses until a proccess is completed. It might be fixed as the problem is mainly on ogar unlimiteds crumbling foundation by ogarproject . Since many people are working  on the problem , it might be solved. Please see issue #196 or any other issues regarding performance. A recent update for stability has been made. #786

**11.How do i use premium skins on the server?**
Simply do so by putting:

    <skinname>

As your name. 
If, for example, you want a kraken skin, then put:

    <kraken>

As your name. And so on for all other premium skins.
You can also do:

    name playerID <skinname>

In the console. 

**12.Can I make minions split and eject by using E and R keys?**
Yes. But, It is not possible in the agar.io client as it doesn't support/read E and R keys. If you want to do this, use the latest version of Ogar-Unlimited and use this client: http://play.ogarul.tk
 
**13.I have a burning suggestion, but where should i put them?**
Go to issue #510 to post them :smiley: 

**14.Where are the config files?**
Find a folder in `src` called `settings`.

**15.When i use the update command or autoupdate, my original configs get overwritten. How do i fix that?**
Copy and past the configs you do not want to be overwritten by updates into the `override.ini` file in the `settings` folder.

**Comment by Megabyte918** [comment]
i r8 8/8

**Comment by VSabertail** [comment]
so its illeagal so the FBI is after me right now ? >_<

**Comment by firelightning13** [comment]
wat

**Comment by Agarian** [comment]
@VSabertail you made a client clone?

**Comment by Agarian** [comment]
I wonder if closing snd opening this would move it to the top of the issue list

**Comment by LegitSoulja** [comment]
Lol nope, and nodejs doesn't pause btw. Most of the times it just waits for a callback whilst doing other things and goes back when a callback is complete. :P

**Comment by Agarian** [comment]
Will close then reopen in a new issue.
