### ISSUE TITLE
how do i node install again?

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#192]
i went into the node.js command prompt but i forgot how to install
toString error.

i was trying: node install node.js install install and all different shit..

**Comment by Andrews54757** [comment]
go [here] (http://nodejs.org)

**Comment by Andrews54757** [comment]
if you want to install node js over command line, do this

`sudo npm cache clean -f`
then do
`sudo npm install -g n`
then do 
`sudo n stable`
to check your version type
`node -v`

**Comment by Andrews54757** [comment]
to update npm do this
`sudo npm install -g npm`

**Comment by elitajmx** [comment]
Ayy thanks
