### ISSUE TITLE
Virus Throw Not Working

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#195]
@Andrews54757 Or Every AJS-Development Members Can you please make that Viurs Throw Work in Ogar Unlimited plz

**Comment by Andrews54757** [comment]
why is a virus throw important anyway?

**Comment by retslac** [comment]
Not sure what virus throw is, but i believe i posted what you want some time ago.
Look at [https://github.com/OgarProject/Ogar/issues/374](https://github.com/OgarProject/Ogar/issues/374)

**Comment by Andrews54757** [comment]
@retslac I added you into ajs dev and gave you write permission

**Comment by retslac** [comment]
@Andrews54757 thx for invitation.  I will help if i can but only for problems that interest me as well.  Just don't have the time for it all.  I'm already involved in too many projects as it is.

**Comment by PrinceDark9243** [comment]
@Andrews54757 I ADDED THIS

Virus.prototype.onAutoMove = function(gameServer) {
    var r = 100; // Checking radius

    var len = gameServer.nodesEjected.length;
    for (var i = 0;i < len;i++) {
        var check = gameServer.nodesEjected[i];

        var topY = check.position.y - r;
        var bottomY = check.position.y + r;
        var leftX = check.position.x - r;
        var rightX = check.position.x + r;

        if (this.collisionCheck(bottomY,topY,rightX,leftX)) {
            check.angle = this.angle; //make sure new virus shoots in same direction as this virus
            this.feed(check,gameServer);
            i--;
            len--;
        }
    }
};
 


TO Virus.js And Virus Throw Works Thanks! to @retslac  he coded this! THANK!
