### ISSUE TITLE
Annoying bug! 

### ISSUE THREAD

**Issue by mogokcp** [AJS-development/Ogar-unlimited#198]
This says all : https://gyazo.com/1a2b4b9f1a273d3ee52d09cb98a4e4f0

very as fuck annoying bug. Please help, we had to restart browser to fix FOR A WHILE and it is really annoying. Merging is -7, speed is 100.

**Comment by Andrews54757** [comment]
That is not the servers fault, it is your computer/agario client. I cannot do anything about that

**Comment by Andrews54757** [comment]
Also, what bug are you talking about

**Comment by Lukkez** [comment]
You use ogar-feeder-bot? if yea, press "D"

**Comment by Andrews54757** [comment]
Yes, I updated the scramble that's why
