### ISSUE TITLE
better startup console text art...

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#2]
i think you should replace the "ogar unlimited" text art with this: 

    ("   ___                  ___");
    console.log("  / _ \\ __ _ __ _ _ _  / __| ___ _ ___ _____ _ _");
    console.log(" | (_) / _` / _` | '_| \\__ \\/ -_) '_\\ V / -_) '_|");
    console.log("  \\___/\\__, \\__,_|_|   |___/\\___|_|  \\_/\\___|_|");
    console.log("       |___/  \u001B[32mAn open source Agar.io server\u001B[0m");
    console.log("");

it will look like this :)
![console](https://cloud.githubusercontent.com/assets/15255724/12600182/9db0caee-c465-11e5-8c95-970e7f4c5962.jpg)

**Comment by Agarian** [comment]
its not popping up correctly in the github comment...

**Comment by Agarian** [comment]
there

    ("   ___                  ___");
    console.log("  / _ \\ __ _ __ _ _ _  / __| ___ _ ___ _____ _ _");
    console.log(" | (_) / _` / _` | '_| \\__ \\/ -_) '_\\ V / -_) '_|");
    console.log("  \\___/\\__, \\__,_|_|   |___/\\___|_|  \\_/\\___|_|");
    console.log("       |___/  \u001B[32mAn open source Agar.io server\u001B[0m");
    console.log("");

**Comment by Andrews54757** [comment]
where did you get that? that looks interesting

**Comment by Agarian** [comment]
i got it from ogarserv and modified it. note this goes into index.js:
// Imports
var Commands = require('./modules/CommandList');
var GameServer = require('./GameServer');

// Init variables
var showConsole = true;

// Start msg
console.log("\u001B[8;37;44m   ___                  ___                       ");
console.log("  / _ \\ __ _ __ _ _ _  / __| ___ _ ___ _____ _ _  ");
console.log(" | (_) / _` / _` | '_| \\__ \\/ -_) '_\\ V / -_) '_| ");
console.log("  \\___/\\__, \\__,_|_|   |___/\\___|_|  \\_/\\___|_|   ");
console.log("       |___/  \u001B[32mAn open source Agar.io server       \u001B[0m");
console.log("");

// Handle arguments
process.argv.forEach(function(val) {
    if (val == "--noconsole") {
        showConsole = false;
    } else if (val == "--help") {
        console.log("Proper Usage: node index.js");
        console.log("    --noconsole         Disables the console");
        console.log("    --help              Help menu.");
        console.log("");
    }
});

// Run Ogar
var gameServer = new GameServer();
gameServer.start();
// Add command handler
gameServer.commands = Commands.list;
// Initialize the server console
if (showConsole) {
    var readline = require('readline');
    var in_ = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    });
    setTimeout(prompt, 100);
}

// Console functions

function prompt() {
    in_.question(">", function(str) {
        parseCommands(str);
        return prompt(); // Too lazy to learn async
    });
}

function parseCommands(str) {
    // Log the string
    gameServer.log.onCommand(str);

    // Don't process ENTER
    if (str === '')
        return;

    // Splits the string
    var split = str.split(" ");

    // Process the first string value
    var first = split[0].toLowerCase();

    // Get command function
    var execute = gameServer.commands[first];
    if (typeof execute != 'undefined') {
        execute(gameServer, split);
    } else {
        console.log("[Console] Invalid Command!");
    }
}

**Comment by Andrews54757** [comment]
Cool! I will think about it.

**Comment by Agarian** [comment]
KK I gtg to bed it's like 11 pm

**Comment by Andrews54757** [comment]
I have improved the text art. but it isnt the one you have.

**Comment by Agarian** [comment]
good enough
