### ISSUE TITLE
My mouse is on center but cell still moving

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#201]
The title says all, the bots too, but this don't happen on normal Ogar, i think the code have a error

**Comment by StormGS5** [comment]
you mean when you split with your mouse in center your cells still move when they usually stop?

**Comment by Lukkez** [comment]
Nope when on 1 CELL still moving
And bots too

**Comment by Andrews54757** [comment]
I think i fixed it
