### ISSUE TITLE
w

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#207]
w goes throw cells

**Comment by Megabyte918** [comment]
Change botupdate and minionupdate to 1 in gameserver.ini

**Comment by problemsofworld** [comment]
how the fuck this fixed the problem lel

**Comment by problemsofworld** [comment]
help can't add more virus

**Comment by Megabyte918** [comment]
idk haha =P that should be the default
oh and try increasing virusminamount and virusmaxamount in gameserver.ini

**Comment by problemsofworld** [comment]
tried and don't works well

**Comment by Megabyte918** [comment]
what? that usually works for me... did you try changing the spawn interval?

**Comment by Megabyte918** [comment]
I'll look into it when i get home im in school rn :P

**Comment by Andrews54757** [comment]
no that doesn have anything to do with that, to fix reaally, turn fps to 40 and playerspeed to 20

**Comment by Megabyte918** [comment]
Thats weird

**Comment by Andrews54757** [comment]
i made it default now

**Comment by Megabyte918** [comment]
What happens when you change the fps in gameserver.ini?

**Comment by Andrews54757** [comment]
fps stands for Frames Per Second. Theoretically, if increased, the preformance also increases. It is true, but there can be some issues like things spawning too fast or players being too fast

**Comment by Megabyte918** [comment]
Ohhh alright I get it. So is that why you decreased the playerspeed by 15 and increased the fps by 20? To even it out?

**Comment by Andrews54757** [comment]
yes. i should also halve all the other time wise configs as well.

**Comment by Megabyte918** [comment]
Isnt there an easier way of doing this besides decreasing ALL the other timewise configs or is this the only way

**Comment by Andrews54757** [comment]
oh, im working on it, see what i did to gamemode tick?

**Comment by Andrews54757** [comment]
but the original ogar foundation never meant to include the fps option so im creating code that automatically sets those configs

**Comment by Megabyte918** [comment]
Ahh okay. smart :)

**Comment by problemsofworld** [comment]
ogar>will be better agar.io :)
