### ISSUE TITLE
24/7 Free vps?

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#208]
Someone have a free 24/7 free vps? like c9, but c9 automatically exit when nobody is making commands or afk

**Comment by NatsuTheGreat** [comment]
Hmm can you tell me more about c9? I want to try it out.

**Comment by StormGS5** [comment]
me too XD

**Comment by Lukkez** [comment]
http://c9.io/ It's a bit easy

**Comment by Lukkez** [comment]
You can test my server at: [Agar.io Experimental Server](agar.io/?ip=experimental-lukkez.c9users.io)

**Comment by NatsuTheGreat** [comment]
1. Does is cost anything?
2. What is the bandwidth?
3. Does it run 24/7, if not how does it go down and how long does it work?
4. I saw you had to do some coding there, do we do anything there?
5. How do I actually get it working?

**Comment by StormGS5** [comment]
no they dont cost but its hard to get a server and i dont even thing you can make a server with it

**Comment by Lukkez** [comment]
1. Free
2 Idk
3. Lifetime
4. You can put Ogar-Unlimited as template
5. Sign up, create a workspace with node.js put the link of ogar-unlimited as template and enjoy

**Comment by StormGS5** [comment]
@Lukkez  UR SERVERS NOT RUNNING

**Comment by Lukkez** [comment]
Ik, i closed, making a new

**Comment by Lukkez** [comment]
To post to reddit

**Comment by StormGS5** [comment]
oh

**Comment by StormGS5** [comment]
i like reddit

**Comment by Lukkez** [comment]
[Will here the server](http://agar.io/?ip=experimental-playogar.c9users.io) &nbsp;

**Comment by NatsuTheGreat** [comment]
@Lukkez Does it run 24/7 though?

**Comment by StormGS5** [comment]
dont work for me

**Comment by Lukkez** [comment]
Nope
I will try to make 24/7 by auto restarting

**Comment by StormGS5** [comment]
ok :)

**Comment by NatsuTheGreat** [comment]
Autorestart makes it 24/7? Auto restart in c9 or the agar.io server?

**Comment by Lukkez** [comment]
Agar.io server, idk if makes 24/7

**Comment by StormGS5** [comment]
ok when servers up ill have a troll skin (not the troll face skin)

**Comment by Lukkez** [comment]
With all the skins, transparent too

**Comment by StormGS5** [comment]
k
any transparent skins without the dot in the middle XD

**Comment by Megabyte918** [comment]
sorry bout that xd i had to have a dot somewhere or else you freeze when u try to play

**Comment by StormGS5** [comment]
oh XD

**Comment by StormGS5** [comment]
can u make it smaller

**Comment by StormGS5** [comment]
its ok

**Comment by StormGS5** [comment]
lol i saw ur post on reddit

**Comment by Megabyte918** [comment]
I'll try. Do you have skype btw?

**Comment by StormGS5** [comment]
i deleted it just now :p

**Comment by Megabyte918** [comment]
we should team sometime make a new one we could talk

**Comment by StormGS5** [comment]
we could team if you could host a server and me and u team on it and add bots XD

**Comment by Megabyte918** [comment]
i already have one m8 add me on skype and we could talk on there cause im pretty sure were probably pissing andrew off by turning this into a chat xD

**Comment by NatsuTheGreat** [comment]
Well chatting is why the comment feature was made.

**Comment by Megabyte918** [comment]
oh yeah i guess your right but this is for issues haha

**Comment by NatsuTheGreat** [comment]
Okay, can you reply on the suggestions issue?

**Comment by Megabyte918** [comment]
yeah sorry

**Comment by StormGS5** [comment]
@megabyte916 i only have discord

**Comment by StormGS5** [comment]
and i also cant talk very well i got braces in my mouth and i cant talk well

**Comment by Megabyte918** [comment]
im getting it now

**Comment by StormGS5** [comment]
ok

**Comment by Lukkez** [comment]
The vps options don't work for me :/
Why

**Comment by Lukkez** [comment]
[Server link: Online](http://agar.io/?ip=server1-playogar.c9users.io)

**Comment by StormGS5** [comment]
i cant spawn

**Comment by Megabyte918** [comment]
whts your discord thingy and how do i add it haha

**Comment by StormGS5** [comment]
create ur own discord and send a invite into this chat

**Comment by Megabyte918** [comment]
@Lukkez someone botted ur server its laggy af

**Comment by Megabyte918** [comment]
@StormGS5 how do i do that >.<

**Comment by StormGS5** [comment]
i cant even join WTF

**Comment by StormGS5** [comment]
ill make one then

**Comment by Lukkez** [comment]
Now i will put all botters ip at my post at reddit, feel free to ddos

**Comment by StormGS5** [comment]
here go here megabyte https://discord.gg/0sD6OT61FyskgLjk

**Comment by StormGS5** [comment]
LAGG OMG LAGG MY PC IS GONNA CRASH STOP THE SERVER

**Comment by Megabyte918** [comment]
I got the invisible skin its [v.ht/6ZBi]

**Comment by StormGS5** [comment]
thnx

**Comment by Megabyte918** [comment]
@Lukkez i dont really know any other free vps services but c9 and Koding cause i recently found out about them and i know this is probably a shitty response, but i would just search google for some m8 there has to be ONE out there

**Comment by Megabyte918** [comment]
LOL LOOK WHAT I GOT http://prnt.sc/aci4l0

**Comment by StormGS5** [comment]
lol i got 420 when i joined andrews doesent have a good bot system

**Comment by Andrews54757** [comment]
you cant bot my server

**Comment by Andrews54757** [comment]
lukka didnt update

**Comment by Andrews54757** [comment]
http://agar.io/?ip=ogar-unlimited-andrews54757.c9users.io

**Comment by Andrews54757** [comment]
also, if you think you got 400, it is probably wrong because ogar unlimited makes bots think their there when they arnt

**Comment by Lukkez** [comment]
ik one for 1 cent 24/7 but need paypal :/

**Comment by NatsuTheGreat** [comment]
1 cent? Lol really?

**Comment by Megabyte918** [comment]
Holy crap thats awesome

**Comment by NatsuTheGreat** [comment]
I have paypal I can get that! But one cent really?

**Comment by Lukkez** [comment]
I don't have link now

**Comment by Agarian** [comment]
how i host on C9??

**Comment by firelightning13** [comment]
@Agarian Ill make tutorial when I'm free or ask another ppl how, @ErikParacelsus @Lukkez @Andrews54757
