### ISSUE TITLE
Time to expire verification

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#210]
Put a time to expire verification, people are joining with bots, they don't move but still lagging on my server

**Comment by Andrews54757** [comment]
what is your server

**Comment by Andrews54757** [comment]
are you using latest version? becaz in the latest version, there is something called mousefilter that makes bots obselete

**Comment by Andrews54757** [comment]
use the update command and in gameserver.ini, turn vps into 1

**Comment by Andrews54757** [comment]
also, i tried to make a timer but it didnt work

**Comment by Andrews54757** [comment]
EURIKA!!! I added it now!
