### ISSUE TITLE
split doesn't look normal and speed of cell fix it 

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#213]

**Comment by Andrews54757** [comment]
What???

**Comment by PrinceDark9243** [comment]
@Andrews54757 The Split is Not Same as Old Ogar Unlimited It is Too fast Please Fix It

**Comment by problemsofworld** [comment]
yep that's what I meant old ogar unlimited was better

**Comment by Andrews54757** [comment]
Il fix

**Comment by Andrews54757** [comment]
It is because i increased fpsto boost preformance.

**Comment by Andrews54757** [comment]
I fixed it.

**Comment by problemsofworld** [comment]
ya now it's looks better than real agar.io thxs :+1:

**Comment by firelightning13** [comment]
Nope it doesnt it looks like "teleporting" when splitting
