### ISSUE TITLE
COMPETITION.

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#218]
1. After increasing performance, the config values dealing with physics were all messed up. Whoever who makes the better config the fastest gets to put their name in the header of the config. RESOLVED

2. Suicide bots are annoying and cause lag. Even though this is made to reduce as much lag as possible, it still lags. Now, the competition is to make a REAL lag free anti bot system. If you cannot do this another challenge is that to give the bots a taste of their own medicine, basically to DDoS them back. Whoever who completes the first part or the second part will get recognition in the read me and will get recognition in a world wide message.

**Comment by Megabyte918** [comment]
Looks like I have to finish learning java quickly haha

**Comment by NatsuTheGreat** [comment]
Lol weren't you the extremely happy one when you made the "No log Anti-Bot system"?

**Comment by Andrews54757** [comment]
Yeah, i wasnt as it still causes a little lag

**Comment by NatsuTheGreat** [comment]
We need to start on proxy protection.

**Comment by firelightning13** [comment]
How about this? #83

**Comment by retslac** [comment]
@Andrews54757 
1. I assume you're talking about the changed fps?  Unless i'm missing something, i really don't see how this will improve performance.  What are you trying to achieve with it: less lag or smoother movement?
2. For the suicide bots, maybe try what i suggested in #196.  It will not remove lag, only reduce lag.

@firelightning13 
Split range can be calculated from split speed, ticks, and decay.  If you want faster or slower speed but same range, you not only have to change speed, but need to change ticks and decay as well.
It would be nice though to have a split range in the config.  Ogar could then reverse calculate the corresponding ticks and decay for you.

**Comment by firelightning13** [comment]
@retslac You mean change everything to slow? oh god whay

If that in case, ill experiment on that and see what i achieve

**Comment by Andrews54757** [comment]
Sorry about the messed up physics, I was playing around, reverted those changes

**Comment by Agarian** [comment]
I am missing so much updates :disappointed:

**Comment by firelightning13** [comment]
The cell shouldnt move controlling with cursor when split, right?(or at least a bit movement)? Should it depends on the split speed? (especially when you are too big with a lot of pieces)

I mean it's weird that you still can control of the newly split cell until cRestoreTicks is done(you'll notice it when you playing around for a while).

I don't know if agar.io have this...

**Comment by ThunderGemios10** [comment]
What kind of dev makes a competition to fix these?

**Comment by MichaelLeeHobbs** [comment]
@ThunderGemios10 very busy ones...
