### ISSUE TITLE
Autosplitting

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#219]
Hey everyone, i have an issue regarding the speed of the max mass splitting. As you can see below the moment i pass 22.5k by eating the smallest guy underneath the bigger cell, my cell splits.

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/17245196/13657227/64f24cbc-e622-11e5-9c0f-294aee199aec.gif)

The reason why i died is because the moment i passed 22.5k my cell split into two 11k pieces which allowed the other biggest cell to eat all of me. In vanilla agario this wouldn't have happened, i would have consumed the smallest guy AND the other biggest guy while also splitting into two pieces. this is because in vanilla agario the cell would have surpassed 22.5k for a split second, allowing me to eat BOTH people at the same time, wherefore in vanilla ogar your cell IMMEDIATELY splits at 22.5k, which caused me to die. Its very annoying because this has caused me to die many times before.

Any help on how i would make this the same as vanilla agario would be greatly appreciated <3

**Comment by Andrews54757** [comment]
That's easy

**Comment by firelightning13** [comment]
Well actually your mass is not enough to eat it

**Comment by Megabyte918** [comment]
My mass was 19K, the biggest guy was 20K, and the smallest guy was 5K. In vanilla agario, when I ate the 5K guy on top of the 20K guy, my cell would have surpassed the 22.5K limit into 24K for just long enough for me to eat the 20K guy, then my cells would have split into two 22K pieces. But this doesn't happen in ogar.

**Comment by Agarian** [comment]
Megabyte is right

**Comment by NatsuTheGreat** [comment]
Well the multiplier is going to take effect. I am pretty sure 24k against 20k will not eat it.

**Comment by Megabyte918** [comment]
@NatsuTheGreat It wont? Well, anyways you guys get the point im trying to make, if i was big enough to eat it the same thing would have happened

**Comment by NatsuTheGreat** [comment]
Yes we get the point and yes it won't be able to eat it. You'd have to be more thank 24k to eat him.

**Comment by NatsuTheGreat** [comment]
That probably is the reason it happened.

**Comment by Andrews54757** [comment]
Btw I'm in the carribian on vacation so I can't code

**Comment by Megabyte918** [comment]
When will you be back?

**Comment by Andrews54757** [comment]
On Monday

**Comment by Agarian** [comment]
I wont b back from Michigan til march 22

**Comment by Megabyte918** [comment]
@retslac can you help with this by any chance I dont think I can wait till Monday cause this has been killing me (literally) ><

**Comment by retslac** [comment]
@Megabyte918 sry man, haven't got the time for it right now.  Will have to wait for Andrews solution.

**Comment by firelightning13** [comment]
@Megabyte918 From my calculation, if you have 25k, you could only eat a cell with 16k mass,which means it's not really enough to eat it :/. Unless you show me when you use the console command to set your mass to 37k, then it is something wrong :0

**Comment by NatsuTheGreat** [comment]
Can you try doing this with the other cell being like 10k? Like a lot bigger We'll see what happens.

**Comment by Megabyte918** [comment]
@Andrews54757 thank you so much

**Comment by Megabyte918** [comment]
@Andrews54757 its really buggy >.<

**Comment by Andrews54757** [comment]
how?

**Comment by Megabyte918** [comment]
let me make a gif hold on a sec

**Comment by Megabyte918** [comment]
![animation](https://cloud.githubusercontent.com/assets/17245196/13794872/72d8fedc-eabb-11e5-9c27-d635857496b4.gif)

**Comment by Megabyte918** [comment]
and sometimes i split and i dont split into the max

**Comment by Andrews54757** [comment]
I see

**Comment by Andrews54757** [comment]
will fix

**Comment by Andrews54757** [comment]
I fixed it, it was because I forgot to include a check

**Comment by Megabyte918** [comment]
@Andrews54757 when will it be added again?

**Comment by Andrews54757** [comment]
when I find out the solution for a better one

**Comment by Megabyte918** [comment]
alrighty then

**Comment by Andrews54757** [comment]
i finished the solution and I updated

**Comment by Megabyte918** [comment]
When i surpass 22.5k my cells dont split and i cant split with space unless i press w first

**Comment by NatsuTheGreat** [comment]
This is fixed silly goose, you can close this issue :$

**Comment by Agarian** [comment]
i got that covered lol

**Comment by NatsuTheGreat** [comment]
Thanks :D

**Comment by Megabyte918** [comment]
Natsu I LOVE you

**Comment by NatsuTheGreat** [comment]
Thanks :D

**Comment by Megabyte918** [comment]
Just tried it and it still doesnt work :(
i recreated what i did in the first gif but the two biggest cells were 18k, and i was eating one with 8k and the same thing happened but my cell split away with 13k mass (idk why this happens) i tried it 3 times and the same thing happened.
(i should really start testing things before i comment xP)

**Comment by Andrews54757** [comment]
i finished it in my private thing, but im not sharing until the humoungous update

**Comment by Agarian** [comment]
Sounds huge :DDD
