### ISSUE TITLE
Experimental Virus Speed!

### ISSUE THREAD

**Issue by eevaqueen** [AJS-development/Ogar-unlimited#222]
Hello,
How can i change the Virus in mode Experimental ID (2),When you shot Virus it move so slow for me,so anyone can help with that to make it more fast or speed it up when i shot at it?
Thank you.

**Comment by Megabyte918** [comment]
You mean the speed mass gets ejected from mothercells or the speed in which viruses shoot out?

**Comment by eevaqueen** [comment]
I mean when you shoot at Experimental viruses its move whatever you want,so i need to change the move of viruses speed,because when i shoot it with mass its move so slow.

**Comment by firelightning13** [comment]
He was meant for Experimental v2 ---> the moving virus

Thats ez m8 all u gonna do is add a multiplier to the new speed of a moving virus like this m89:

In the MovingVirus.js, under the feed function:
`var newSpeed = Math.sqrt(px * px + py * py) / m2 * 2;`

The number 2 is any number u want but dont set it too high or else you'll get 360noscope urself m8

**Comment by eevaqueen** [comment]
No imean (Id 2) Experimental,I need to change virus speed can you help me ?

**Comment by eevaqueen** [comment]
I need to change something around this?
// Pushes the virus
    this.setAngle(feeder.getAngle()); // Set direction if the virus explodes
    this.moveEngineTicks = 10; // Amount of times to loop the movement function
    this.moveEngineSpeed = 28;

Iam right or wrong? so i can change Pushes of virus speed!

**Comment by firelightning13** [comment]
Just trials and errors and you'll get something that you want :)

**Comment by eevaqueen** [comment]
Thanks it work :D

**Comment by Andrews54757** [comment]
I fixed moving viruses

**Comment by Agarian** [comment]
Might as well close this since it resolved

**Comment by Megabyte918** [comment]
seems like for every problem solved a new one emerges xD

**Comment by Agarian** [comment]
Indeed lel
