### ISSUE TITLE
Server Glitching???

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#228]
i got a problem, i dont know if it's me or either the server, when i move in one direction or just somewhere for 5 seconds, it just starts moving me in a complete different direction like my mouse was fucked up but it isn't..

**Comment by elitajmx** [comment]
oops i fixed it was an extension

**Comment by Agarian** [comment]
Which extension?

**Comment by elitajmx** [comment]
nahnah its just tampermonkye

**Comment by elitajmx** [comment]
agario auto respawn
