### ISSUE TITLE
Split And W Speed?

### ISSUE THREAD

**Issue by NovaHowl** [AJS-development/Ogar-unlimited#229]
Hi guys,
Is there any way to make the split and w speed the same as the original ogar?
Split speed:
It is way to fast, if you change it in gameserver.ini then it goes slow but then super fast again.

W Speed:
The default is 70, when I try bump it up it goes way to quickly, and if I lower it it becomes alright but the range is tiny.

Is there any way I can change this? Thanks!

**Comment by Agarian** [comment]
Thats the problem: since the dev team had lately been doing major performance upgrades, a recent pull request had screwed with some of those configs. 
# if thats not it,
Sry I've been on vacation in Michigan

**Comment by Andrews54757** [comment]
I reverted it
