### ISSUE TITLE
Unlimit FFA mode problem

### ISSUE THREAD

**Issue by firelightning13** [AJS-development/Ogar-unlimited#230]
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/17120382/13727217/c14f7eee-e924-11e5-87cb-3765f5bacda2.gif)

Cells are often refuse to split (but sometimes they do), there is a way but I don't remember, at least give me a code or what code to delete

**Comment by Agarian** [comment]
That happens when recombine time is 0 or less.

**Comment by firelightning13** [comment]
Yeah but if i set to 1, the big one cant even recombine

**Comment by NatsuTheGreat** [comment]
This is because of the new update. You need to get rid of the part about "popsplit working" Revert that code and you'll be good to go. (This is providing you're using a fresh updated version that had this update merged.)

**Comment by NatsuTheGreat** [comment]
That update does cause problems with instant merging.

**Comment by firelightning13** [comment]
Ok, i reverted the codes and it works now. Thanks @NatsuTheGreat

**Comment by NatsuTheGreat** [comment]
@firelightning13 No problem, glad to help!

**Comment by Megabyte918** [comment]
im so sorry i mess everything up :(
do u think it might be because i removed the first check in the pull request? this didnt happen to me before

**Comment by NatsuTheGreat** [comment]
It not because of that, and don't worry.

**Comment by firelightning13** [comment]
@Megabyte918 If you want normal ffa use that code, for unlimit ffa just rid of this code.

Dont worry, this thing is just a piece of cake :+1:
