### ISSUE TITLE
Mothercells Not Working Properly?

### ISSUE THREAD

**Issue by NovaHowl** [AJS-development/Ogar-unlimited#231]
Hey guys,
I love this version of Ogar compared to the original! But I have a problem in experimental. Whenever I feed a mothercell, the mass of the mothercell drains so quickly and also it doesn't spit out food. What's wrong?

**Comment by NatsuTheGreat** [comment]
You might need to check out gameserver.ini. If you scroll down or use CTRL + SHIFT + F and type in "mothercell" it should find those settings. If that doesn't help (considering you did everything right) You should just make the maxFood amount greater. If you don't want change foodMaxAmount and the mothercell setting don't help, I will guide assist you with more effective solutions.

**Comment by NovaHowl** [comment]
Yeah I tried everything with the settings, foodMaxAmount I don't wanna change because my interval of food spawning is quite high because of my setup so I need a more effective way to do it. Maybe code the mothercells to ignore maxFoodAmount and spit out food no matter what. Thanks!

**Comment by NatsuTheGreat** [comment]
We can make some new variales for mothercell food spawning. May I have your mothercell file?

**Comment by NatsuTheGreat** [comment]
I have to go very soon, so please hurry. Otherwise we'll have to do this tomorrow. It's 12:43 AM here.

**Comment by NovaHowl** [comment]
Hang on, I'm uploading it now!

**Comment by NatsuTheGreat** [comment]
And actually the higher of a value you put for the interval the slower it goes. The lower, the faster it goes.

**Comment by NovaHowl** [comment]
Oh yeah lol, sorry made a typo.
https://mega.nz/#!xEck3LKC!rIcYzZHAeN2CE-y__I0zSWt6D5paBjUzIY8qYtgpNO8

**Comment by NatsuTheGreat** [comment]
I'd really not prefer mega.nz. It's just too long of a process and gives me other unneeded things to download.

**Comment by NovaHowl** [comment]
Just click download through my browser

**Comment by NatsuTheGreat** [comment]
This would be easier, are you using the latest version of ogar-unlimited?

**Comment by NovaHowl** [comment]
Yeah

**Comment by NatsuTheGreat** [comment]
Yeah a very fresh one right? I could just look at that mothercell code and try to test it out and give it to ya when done.

**Comment by NovaHowl** [comment]
Well, I had posted an issue earlier about the split and they said they reverted and then that's when I downloaded it, that was like 4 hours ago.

**Comment by NatsuTheGreat** [comment]
Hmm the file is different from what it was before. But this is a piece of cake.

**Comment by NovaHowl** [comment]
Do you want me to re-download?

**Comment by NatsuTheGreat** [comment]
No it's fine. I think I can give you the one easy thing to change and you can test it.

**Comment by NovaHowl** [comment]
Alright, thanks so much.

**Comment by NatsuTheGreat** [comment]
Alright here it is, if you want to make this a config setting for your self, i'll help you out with that too. 

## Find the function called "update" after the getEatingRange function. It will look something like this:

````
MotherCell.prototype.update = function (gameServer) {
  // Add mass
  this.mass += 0.25;

  // Spawn food
  var maxFood = 10; // Max food spawned per tick
  var i = 0; // Food spawn counter
  while ((this.mass > gameServer.gameMode.motherCellMass) && (i < maxFood)) {
    // Only spawn if food cap hasn been reached
    if (gameServer.currentFood < gameServer.config.foodMaxAmount) {
      this.spawnFood(gameServer);
    }

    // Incrementers
    this.mass--;
    i++;
  }
};
````

## Then highlight all of that and replace it with this:

````
MotherCell.prototype.update = function (gameServer) {
  var maxSpawnFood = 100000; // Ignore GameServer's settings and use this instead.
  
  // Add mass
  this.mass += 0.25;

  // Spawn food
  var maxFood = 10; // Max food spawned per tick
  var i = 0; // Food spawn counter
  while ((this.mass > gameServer.gameMode.motherCellMass) && (i < maxFood)) {
    // If you want the MotherCell to spawn less food, decrease maxSpawnFood above.
    if (gameServer.currentFood < this.maxSpawnFood) {
      this.spawnFood(gameServer);
    }

    // Incrementers
    this.mass--;
    i++;
  }
};
````

**Comment by NatsuTheGreat** [comment]
I am going to test it right now to make sure it works.

**Comment by NovaHowl** [comment]
Yeah same

**Comment by NovaHowl** [comment]
Doesn't work, It's fine.

**Comment by NovaHowl** [comment]
I can figure it out.

**Comment by NatsuTheGreat** [comment]
It doesn't work?

**Comment by NovaHowl** [comment]
Somehow...

**Comment by NovaHowl** [comment]
Mothercells aren't giving out food anymore.

**Comment by NatsuTheGreat** [comment]
Okay I will try to figure something out.

**Comment by NovaHowl** [comment]
It's fine, you can get to sleep. Really, It's fine.

**Comment by NatsuTheGreat** [comment]
Alrighty, you can revert what we've done so far.

**Comment by NovaHowl** [comment]
Yeah, thanks for the help, I got school tomorrow so anyways.

**Comment by NatsuTheGreat** [comment]
If you don't mind I think I figured it out.

**Comment by NatsuTheGreat** [comment]
Let me test it real quick.

**Comment by NovaHowl** [comment]
Alright thanks!

**Comment by NovaHowl** [comment]
I've also noticed that the Mothercell mass drains super quickly.

**Comment by NatsuTheGreat** [comment]
Hang on for a little, making a couple more tweaks.

**Comment by NovaHowl** [comment]
Thanks so much, you are a lifesaver :)

**Comment by NatsuTheGreat** [comment]
You just want it to spawn food no matter what right?

**Comment by NovaHowl** [comment]
Yeah, just like the original ogar.

**Comment by NatsuTheGreat** [comment]
Okay then I need to make it slower.

**Comment by NovaHowl** [comment]
Yeah, thanks again for the help! :+1:

**Comment by NovaHowl** [comment]
What time is it for you?

**Comment by NovaHowl** [comment]
It's 6:25 PM here and I need to go to dinner at arount 6:45, any chance this could be done before that?

**Comment by NatsuTheGreat** [comment]
Yes I am almost done.

**Comment by NovaHowl** [comment]
Thanks.

**Comment by NatsuTheGreat** [comment]
Done. Let me send you the whole file. you can copy it all from there and just replace it with what I have. If you have any problems, tell me.

**Comment by NovaHowl** [comment]
Thanks Mate, appreciate it.

**Comment by Megabyte918** [comment]
change var maxFood = 10 to 1 it worked for me

**Comment by Megabyte918** [comment]
change var maxFood = 10 to 1 it worked for me

**Comment by NovaHowl** [comment]
Alright I'll try that.

**Comment by firelightning13** [comment]
Yeah it works for me aswell

**Comment by NatsuTheGreat** [comment]
Changing it to 1 just makes it spawn on food pellet per tick. I didn't know that that would help.. xD

**Comment by NatsuTheGreat** [comment]
Tell me if it works nova.

**Comment by Megabyte918** [comment]
its weird seeing all of u guys commenting at the same time haha

**Comment by NovaHowl** [comment]
Sorry, It didn't work for me :(

**Comment by NovaHowl** [comment]
It fixed the speed the mothercell was decaying but it didn't fix the food issue.

**Comment by NatsuTheGreat** [comment]
It didn't. Must have been the fact that they had a bigger foodMaxAmount. I knew it wouldn't help by decreasing the food spawning per tick.

**Comment by NovaHowl** [comment]
Exactly.

**Comment by NovaHowl** [comment]
Could you send me the modified file? Thanks!

**Comment by NatsuTheGreat** [comment]
Right on. Just one more thing I have to test out.

**Comment by NovaHowl** [comment]
Sure.

**Comment by NatsuTheGreat** [comment]
Yeah I see. The 1 helps it decay slower but doesn't help the food spawn.

**Comment by NatsuTheGreat** [comment]
One minute and i'll send it.

**Comment by Megabyte918** [comment]
thats weird ... it worked in #132 try messing around with var i = 0? (im not at my desktop so im not sure what works or not)

**Comment by NovaHowl** [comment]
Aldinjg thanks!

**Comment by NovaHowl** [comment]
Alright**

**Comment by NatsuTheGreat** [comment]
Hang on got an error...

**Comment by NatsuTheGreat** [comment]
Here you go. 

http://pastebin.com/1nDGRr1z

**Comment by NovaHowl** [comment]
Thanks, gonna try it now.

**Comment by NovaHowl** [comment]
Got an error when starting the server.

**Comment by NatsuTheGreat** [comment]
What is it?

**Comment by NovaHowl** [comment]
C:\Users\SuperUser\Desktop\Ogar-unlimited-master\src\entity\MotherCell.js:44
        if (this.mass > 222 + foodSize=) {
            ^^^^

ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\dalek\Desktop\Ogar-unlimited-master\src\gamemodes\Experimental.js:6:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by NatsuTheGreat** [comment]
Oh silly me. I accidentally put an unneeded "="

Find this line:

````
if (this.mass > 222 + foodSize=) {
````

And turn it into:

````
if (this.mass > 222 + foodSize) {
````

**Comment by NovaHowl** [comment]
Alright thanks, gonna try it.

**Comment by NovaHowl** [comment]
Another Error:

C:\Users\SuperUser\Desktop\Ogar-unlimited-master\src\entity\MotherCell.js:52
};a
  ^

ReferenceError: a is not defined
    at Object.<anonymous> (C:\Users\dalek\Desktop\Ogar-unlimited-master\src\entity\MotherCell.js:52:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\SuperUser\Desktop\Ogar-unlimited-master\src\gamemodes\Experimental.js:6:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by NatsuTheGreat** [comment]
Oh my stars. Sorry for these weird extra unneeded characters, it's just a problem with pastebin.

Find the line:
````
};a
````
And make it
````
};
````

**Comment by NovaHowl** [comment]
Yeah figured it out, I'm gonna try it now.

**Comment by Megabyte918** [comment]
remove the a

**Comment by NovaHowl** [comment]
Thanks So Much! You are the best. Never would have figured this one out without you. :+1:

**Comment by NatsuTheGreat** [comment]
Yay it works! Have fun with it NovaHowl!

**Comment by NovaHowl** [comment]
I also may increase the interval because it is a bit to slow, and thanks!

**Comment by NatsuTheGreat** [comment]
Yeah sorry about those physics. You'll have to do something about the interval speed and distance if it doesn't suit you.

**Comment by Megabyte918** [comment]
i love seeing issues solved xD

**Comment by NatsuTheGreat** [comment]
:P It feels nice helping people out.

**Comment by NovaHowl** [comment]
:P

**Comment by NatsuTheGreat** [comment]
Should we close this issue now?

**Comment by NovaHowl** [comment]
Holy Sh*t I just looked in the gamemodes folder and found so many!

**Comment by NovaHowl** [comment]
Yeah I'll do it.

**Comment by NatsuTheGreat** [comment]
Yeah there are a lot of GameModes! Have fun with them.

**Comment by firelightning13** [comment]
You've just earned a badge

**Comment by Megabyte918** [comment]
dang almost 90 comments under an hour

**Comment by NatsuTheGreat** [comment]
Maybe even under 30 minutes!

**Comment by firelightning13** [comment]
This is like live support

**Comment by NatsuTheGreat** [comment]
xD Yeah.
