### ISSUE TITLE
Can't make the gameserver.ini

### ISSUE THREAD

**Issue by ortex112** [AJS-development/Ogar-unlimited#232]
i can't make the player max mass or ejected mass 30 or anything i dont know how when i open gameserver i dont understand anything

**Comment by Megabyte918** [comment]
you need a program that can open and display the text correctly. notepad or any text editing software that comes with your operating system by default will not work. i recommemd using brackets :)

**Comment by NovaHowl** [comment]
I personally use Notepad ++

**Comment by ortex112** [comment]
iam using notepad and it is the same problem

**Comment by Megabyte918** [comment]
notepad as in the regular notepad?

**Comment by MichaelLeeHobbs** [comment]
For these type of files I strongly recommend Atom.io, Visual Studio Code, or Notepad++. Notepad, word, etc wont cut it as they do not hand variations in OS/platforms. The dev's work on a variety of different OS's. I for one do my dev work on both Linux and Windows depending on where I happen to be when I have some time. Being that node was originally a Linux only creation do not be surprised that node files have a LF line ending where as Windows expects a CRLF line ending. This is when you need a modern smart editor.

**Comment by MichaelLeeHobbs** [comment]
On a side note the gameserver.ini file you need to edit is the one in the folder from where you run OgarUL. For me:

In OgarUnlimited <-- folder
I run OgarUL like so: node src/index.js
Thus my gameserver.ini file is OgarUnlimited/gameserver.ini
Because that is the folder I ran it from.

**Comment by Agarian** [comment]
I use notepad++

**Comment by NatsuTheGreat** [comment]
You should do the following if you have Notepad++;

1. Find the gameserver.ini file.
2. Right click it.
3. Find the "Edit with Notepad++" option.
4. Click that.
5. It should be opened and you'll just need to find what is needed.
