### ISSUE TITLE
Make That Bots Will Not Ignor Virus PLZZZZ!!!!

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#233]
ASD@!!!!

**Comment by Agarian** [comment]
You mean you dont want the bots avoiding viruses or do you want them to avoid viruses?

**Comment by NatsuTheGreat** [comment]
He means bots that WILL NOT ignore viruses.

**Comment by PrinceDark9243** [comment]
dont want the bots avoiding viruses PLZSSSSSSSSSS!!!!!

**Comment by StormGS5** [comment]
that already dont avoid viriuses dumbass

**Comment by MichaelLeeHobbs** [comment]
Our bot AI is not the best but my AI class was many years ago and right now we have bigger fish to fry. I will say be careful what you ask for. I can make the AI brutal.

**Comment by firelightning13** [comment]
YES MAKE IT BRUTAL >:)

**Comment by PrinceDark9243** [comment]
@MichaelLeeHobbs Can you please make that bot will not avoid viruses

**Comment by Megabyte918** [comment]
@MichaelLeeHobbs make it extra brutal ( ͡°╭͜ʖ╮͡° )

**Comment by MichaelLeeHobbs** [comment]
@Megabyte918 Alright :) It'll be a few weeks before I can get to this as it will have to happen after we write the main loop to support multiprocessors. The more difficult we make the bots the more cpu time they will need. I've already been thinking about this a little bit as it is very annoying how you can pin a bot against a wall when they could easily flee.

**Comment by NatsuTheGreat** [comment]
@MichaelLeeHobbs Yeah man! The fact that you got AI classes is nice! I hope you can make the AI extremely brutal. The bots right now still have problems and I hope you can make it an actual challenge for me.

**Comment by ErikParacelsus** [comment]
Lol it's on the gameserver.ini

**Comment by Megabyte918** [comment]
@ErikParacelsus 1 is 2ez4me

**Comment by firelightning13** [comment]
@ErikParacelsus that iz not enuf 4 me i want moar

**Comment by MichaelLeeHobbs** [comment]
One quick trick one of the other dev's could tackle if they want is and a bot speed modifier to the ini file. Something along the lines of 1.02 to 1.05 speed multiplier. This would give the bots a distinct "CHEATING" advantage. It would also make them harder in general.

**Comment by ErikParacelsus** [comment]
@firelightning13 k m89

**Comment by Andrews54757** [comment]
@MichaelLeeHobbs . It would be nice if it was more brutal and @PrinceDark9243  I will try to make a config.

**Comment by Megabyte918** [comment]
Don't they already avoid them (most of the time) if you set update to 1?

**Comment by firelightning13** [comment]
@Megabyte918 no they dont

**Comment by Megabyte918** [comment]
indeed lelel

**Comment by MichaelLeeHobbs** [comment]
@Megabyte918 @firelightning13 I have noticed an issue where bots seem to "lock on to a target" and not care about anything else. It's like eating another cell has a higher priority than staying alive or not eating a virus.

**Comment by Andrews54757** [comment]
@MichaelLeeHobbs  I am really terrible on ai . Maybe you should really make them evil.

**Comment by Megabyte918** [comment]
@MichaelLeeHobbs yeah they do that to me alot its annoying af

**Comment by PrinceDark9243** [comment]
Make Bots Smarter

**Comment by firelightning13** [comment]
@PrinceDark9243 Be patient hes still trying to solve some issues, so wait for him to finish

**Comment by PrinceDark9243** [comment]
ok

**Comment by Agarian** [comment]
how do i host on C9?

**Comment by firelightning13** [comment]
? wat

**Comment by PrinceDark9243** [comment]
nothing XD!
