### ISSUE TITLE
My skin repository

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#239]
I will store much skins [here](https://github.com/Lukkez/Agario-Skins)
And if someone want to put these custom skins on own server you can :D List updated daily

**Comment by ErikParacelsus** [comment]
Nice repository! (starred)

**Comment by Megabyte918** [comment]
Thats pretty neat :)

**Comment by Lukkez** [comment]
Thanks :)

**Comment by Andrews54757** [comment]
Good job! That should be the official skins repo for Ogar unlimited.

**Comment by firelightning13** [comment]
@Lukkez Congratz m89

**Comment by Lukkez** [comment]
Thanks @firelightning13 And @Andrews54757 i can put on README.md :)

**Comment by NoorAgario** [comment]
How to use them plz help

**Comment by Lukkez** [comment]
Upload files to imgur, get the png link and put on customskins.txt

**Comment by Andrews54757** [comment]
so old, gonna add to readme in next update
