### ISSUE TITLE
extension

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#241]
hey everyone, im in need of a botting extension or script that i can use on my private server to practice teaming with. before anyone gets the wrong idea IM NOT TRYING TO USE ANY ON OFFICIAL AGARIO JUST ON MY SERVER FOR TEAMING PRACTICE. i would never want to ruin the game or make it unfair for anybody else.

teaming with minions is extremely difficult because i have to keep pressing q to switch between the controls and everytime i need them to split. it gets really confusing >.< thats why i need one that i can control the splitting and w's with different keys

if anyone has any suggestions on a good one that works please tell me. it doesnt need to work on agario servers just ogar ones so i can practice.

**Comment by firelightning13** [comment]
How about agario powerups?

**Comment by Megabyte918** [comment]
the extension and website was taken down :(

**Comment by firelightning13** [comment]
Oh i didnt know that, i havent use this for months now

**Comment by Megabyte918** [comment]
does it still work for u? (if u still have it)

**Comment by Agarian** [comment]
I have 1, but its back in florida :(

**Comment by Megabyte918** [comment]
its aight m7

**Comment by Lukkez** [comment]
And about Ogar-feeder-bot? put default, and disable scramble

**Comment by Andrews54757** [comment]
Don't forget to also disable mousefilter if you want to have bots

**Comment by Andrews54757** [comment]
And minimap scramble

**Comment by Megabyte918** [comment]
how do i use it? its really complicated >.<

**Comment by Lukkez** [comment]
Rlly?

**Comment by Megabyte918** [comment]
it is for me at least

**Comment by firelightning13** [comment]
I neither don't know how to use it, i just use built-in minions to practice teaming cus ive been used to this Q's thingy

**Comment by Megabyte918** [comment]
i would use those but i just wish they had different controls cause im used to using e and r to control them with an extension
