### ISSUE TITLE
Virus explosions

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#242]
How do i make the virus explosions look like this:

![animation](https://cloud.githubusercontent.com/assets/17245196/13826473/0ab8a07c-eb75-11e5-9f0f-31d4f5e543ea.gif)

and less like this:

![animation2](https://cloud.githubusercontent.com/assets/17245196/13826489/1d630050-eb75-11e5-9c66-902f1124c53b.gif)

**Comment by StormGS5** [comment]
I don't know I can't see the animation not letting me open it


On March 16, 2016, at 3:46 PM, Megabyte918 <notifications@github.com> wrote:

How do i make the virus explosions look like this:

￼

and less like this:

￼

**Comment by Megabyte918** [comment]
http://giphy.com/gifs/3osxYxLt0cV9dFrx6M 
http://giphy.com/gifs/3osxY7mRrwjSNKl8Iw

**Comment by firelightning13** [comment]
First problem: The collision ticks is too long.
Second problem: They moving while being split

**Comment by Megabyte918** [comment]
what do you mean by the second one?

**Comment by Megabyte918** [comment]
is there any way to make it shorter or does that mess something else up

**Comment by Megabyte918** [comment]
is there any way to make the ticks shorter? or does that interfere with something else

**Comment by Andrews54757** [comment]
You can make it shorter

**Comment by Andrews54757** [comment]
Add
` newCell.restoreCollisionTicks = this.config.cRestoreTicks; //vanilla agar.io = 10`
On line 1862

**Comment by Megabyte918** [comment]
alright. ill do it when i get home. but after that how would i make the cells pop out the same way?

**Comment by Andrews54757** [comment]
ok i added the code i mentioned to the master branch and what do you mean by the wy the cells pop out?

**Comment by Andrews54757** [comment]
i think the explosion looks like that because in the above, that person ran into the virus but yours, you slit into the virus

**Comment by PrinceDark9243** [comment]
where we add this`newCell.restoreCollisionTicks = this.config.cRestoreTicks; //vanilla agar.io = 10` is Cell.js of PlayerCell.js

**Comment by Megabyte918** [comment]
its already added

**Comment by PrinceDark9243** [comment]
it is not added i cant able to see that change in Ogar Unlimited. Can i need to do update command!?

**Comment by Megabyte918** [comment]
Yes

**Comment by Megabyte918** [comment]
Andrew ill make another gif comparing the explosions once I get back from school

**Comment by Agarian** [comment]
U in school? I have spring break in Florida but either way,  im im Michigan :smile:

**Comment by Megabyte918** [comment]
yeah but im going on vacation a week early so i miss the next week lol

**Comment by Megabyte918** [comment]
Okay, ive finally done it @Andrews54757 
Here is what virus esplosions in vanilla OgarUL look like:


![tricksplit](https://cloud.githubusercontent.com/assets/17245196/13903203/d0e13ed8-ee2e-11e5-8eda-cf14e44f09f5.gif)
![explosion](https://cloud.githubusercontent.com/assets/17245196/13903204/e189653a-ee2e-11e5-8f70-4ab29c0b88a8.gif)
![explosion2](https://cloud.githubusercontent.com/assets/17245196/13903205/e3929f90-ee2e-11e5-9369-66c1fc864d1f.gif)
![explosion3](https://cloud.githubusercontent.com/assets/17245196/13903206/e5acb98c-ee2e-11e5-891a-1beb0947181e.gif)
![explosion4](https://cloud.githubusercontent.com/assets/17245196/13903207/eb704708-ee2e-11e5-8b03-aba3d7c032a4.gif)


The ones under 10k-ish mass don't actually need to be changed, as they ARE similar to vanilla agario. But once they are over 10k, they change. you'll see in a sec.

**Comment by Megabyte918** [comment]
Here is what vanilla Ogar ones look like:
(couldn't get tricksplit footage cause didnt have minions) ...(or friends)

![ogarexplosion](https://cloud.githubusercontent.com/assets/17245196/13903221/a75d56fe-ee2f-11e5-92d9-e13762300b07.gif)
![ogarexplosion2](https://cloud.githubusercontent.com/assets/17245196/13903222/aa12c172-ee2f-11e5-81dd-4c5c7c4e4c7a.gif)
![ogarexplosion3](https://cloud.githubusercontent.com/assets/17245196/13903224/ac2fb82a-ee2f-11e5-85c1-1ac1427929ab.gif)
![ogarexplosion4](https://cloud.githubusercontent.com/assets/17245196/13903225/af1b2614-ee2f-11e5-8d4e-4f7b58194655.gif)

Maybe add a config to switch between the explosion versions?

**Comment by Megabyte918** [comment]
These are vanilla agario explosions (couldn't get own footage cause i suck)
i didnt get ones under 10k cause their actually similar to vanilla OgarUL, but once they are over 10k (or splitting into a virus with 8k) they change.

![agartricksplit](https://cloud.githubusercontent.com/assets/17245196/13903246/52fc3520-ee30-11e5-9c4b-562fc375c149.gif)
![agarexplosion](https://cloud.githubusercontent.com/assets/17245196/13903247/54f6fe50-ee30-11e5-882d-df119f1b9020.gif)

Its different once your over 10k or splitting into a virus with 8k, because the cells popout ALL AROUND the cell, while in OgarUL and Ogar only 3 big ones, and a bunch of small ones do.

**Comment by Megabyte918** [comment]
oh yeah and btw, when u are over 1k mass and you split on a virus when in more than one piece, the splits are 20 mass and not 36 each

**Comment by firelightning13** [comment]
Wow, ogar is making it more realistic than OgarUL (except the last one 21k, kinda weird when the big cell is moving so fast)

**Comment by firelightning13** [comment]
Tricksplit in ogar:

![ezgif com-optimize 1](https://cloud.githubusercontent.com/assets/17120382/13903927/abb64f72-eec9-11e5-9fe2-2255ecc60b91.gif)

:)

**Comment by Megabyte918** [comment]
Yeah lol

**Comment by Megabyte918** [comment]
@NatsuTheGreat can you make that pull request to make it more like the ones on ur server? So I can close this lol I dont like seeing so many issues

**Comment by Agarian** [comment]
same, i imagine the issues area will be like ogarproject's issue area am i right? :smile:

**Comment by Agarian** [comment]
@everyone my server is open http://agar.io/?ip=ogarservercloned-agarian.c9users.io
(idk if the everyone mention would work so hehe)

**Comment by Agarian** [comment]
join https://discord.gg/0hRsW0bTTrgCSVP4 for more info

**Comment by Megabyte918** [comment]
Lol yeah :P 
@Andrews54757 any luck?

**Comment by Andrews54757** [comment]
well, i changed the virus mech to that of ogarproject so thats that and i dont know any physics like this.

**Comment by Megabyte918** [comment]
alrighty then, thanks andrew its not PERFECT but at least its more similar to vanilla :D
