### ISSUE TITLE
EJECT MASS ERROR

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#247]
YOU CANT ABLE TO EJECT MASS WITH COOLDOWN

**Comment by Andrews54757** [comment]
what cooldown, it works fine for me

**Comment by Agarian** [comment]
He means, if there is no cooldown for ejected mass, apparently an error occurs

**Comment by Agarian** [comment]
Also the 2000th commit is coming :D

**Comment by Megabyte918** [comment]
@Agarian just 200 more to go lmao

**Comment by Andrews54757** [comment]
what killer feature should i add on that update?

**Comment by Andrews54757** [comment]
and @PrinceDark9243  fixed

**Comment by Megabyte918** [comment]
im not sure.... maybe gather a bunch of suggestions and implement them all?

**Comment by PrinceDark9243** [comment]
@Andrews54757. @Megabyte918 and Me get Same bug Help! and this bug is not fixed

**Comment by Andrews54757** [comment]
update and its fixed
