### ISSUE TITLE
Ogar Unlimited Error

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#248]
![untitled](https://cloud.githubusercontent.com/assets/17459204/13884221/51595e56-ecea-11e5-9160-c6ad0f006082.png)

**Comment by PrinceDark9243** [comment]
WHY THERE IS MANY ERRORS AND BUG IN OGAR UNLIMITED!!!! WHY?

**Comment by Agarian** [comment]
Idk

**Comment by PrinceDark9243** [comment]
can you plz fix it plz

**Comment by Agarian** [comment]
LOL IM IN MICHIGAN (no computer here im stuck on android)

**Comment by PrinceDark9243** [comment]
can you plz tell me how to fix and Thanks! for the popspliting fix now popsplit is Working 90%

**Comment by Andrews54757** [comment]
Il fix

**Comment by CheikoAsami** [comment]
PLEASE..... I want to play this so bad..... You have no idea...........

**Comment by Andrews54757** [comment]
its fixed
