### ISSUE TITLE
Prob Running Server

### ISSUE THREAD

**Issue by NoorAgario** [AJS-development/Ogar-unlimited#252]
So i ran the Start.bat and everything is fine , but i dont know how to join the game , it told me --> "[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 11.8.5
[Game] Loaded stats server on port 88
[Game] Listening on port 443
[Game] Current game mode is Free For All
[Autopause] The Game Was Paused to save memory. Join the game to resume!
>[Console] We recieved a world-wide message!: CONTRIBUTE: I need a person to format gameserver.ini so it is easier to find certain cofigs. Also, I feel like giving people a shoutout. Should I?. Alright, Thanks to assault gaming for the first how to install video of Ogar unlimited and to jp on agario for the really funny and weird video of a red cell dancing in Ogar unlimited. Ok, that's the end, now go back to doing whatever your doing"
What should i type in the address bar to play ?!! Help me plz

**Comment by NoorAgario** [comment]
and when i try to join using http://agar.io/?ip=127.0.0.1:443 it wont work :(

**Comment by ItzLevvie** [comment]
Miniclip is updating their servers.
