### ISSUE TITLE
Split And W speed could be slower and faster?

### ISSUE THREAD

**Issue by NovaHowl** [AJS-development/Ogar-unlimited#254]
Hey guys,
Whenever I download or update to a new copy of Ogar-Unlimited I always change the splitspeed from 130 to 100 because It's more realistic when big and also set the Eject speed to 130 because it is also more realistic. So my request is can we change that in the config officially?

**Comment by Megabyte918** [comment]
130 is the vanilla eject speed? it seems a bit slow

**Comment by Andrews54757** [comment]
you can copy and paste those configs in override.txt to make it so updates dont effect that
