### ISSUE TITLE
Error on latest update

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#255]
How do i fix this?

![capture](https://cloud.githubusercontent.com/assets/17245196/13895038/028c6146-ed45-11e5-9aca-e808b8d9cc13.PNG)

**Comment by firelightning13** [comment]
@MichaelLeeHobbs

**Comment by Megabyte918** [comment]
probably shouldn't update every time a file is updated lol

**Comment by firelightning13** [comment]
i missed so much update lol

**Comment by Megabyte918** [comment]
that might be a good thing xD

**Comment by firelightning13** [comment]
backup your file may be a good idea :+1:

**Comment by Megabyte918** [comment]
i should probably start doing that haha

**Comment by Andrews54757** [comment]
reverted it
