### ISSUE TITLE
W not working all the time

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#261]
Sometimes, when playing solo or teaming with minions, when i press W half my cells dont shoot out mass? and sometimes none of them do, but then they start to again when one of my pieces gets eaten or splits on a virus. this mostly seems to happen after i split on a virus or i split into the max

**Comment by PrinceDark9243** [comment]
Same!

**Comment by NovaHowl** [comment]
Yeah same. The same thing happened to me when teaming.

**Comment by firelightning13** [comment]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
@NatsuTheGreat @MichaelLeeHobbs

**Comment by NatsuTheGreat** [comment]
Have you tried making *ejectMassCooldown* 0?

**Comment by Megabyte918** [comment]
my eject mass cooldown is set to 100 but i dont want it at 0 cause its too fast

**Comment by NatsuTheGreat** [comment]
That COULD cause the problem.

**Comment by NovaHowl** [comment]
I'll try it while teaming now.

**Comment by NovaHowl** [comment]
Doesn't seem to be making a difference :/

**Comment by Agarian** [comment]
@Andrews54757 ?

**Comment by Andrews54757** [comment]
i will look into this

**Comment by firelightning13** [comment]
@Megabyte918 @Andrews54757 
Ok I see why you cant W all the time, when one of my cell is small than playerMinMassEject and cant W anymore, all the cell cant W anymore instead of the cell that with low than playerMinMassEject

**Comment by Agarian** [comment]
i have finally returned home lol

**Comment by Agarian** [comment]
also this only seems to happen if ejectMassCooldown is 0 or less.

**Comment by Agarian** [comment]
same annoying problem, and i popped on a virus and only a few cells actually ejected mass. even then, the few cells eventually stopped ejecting mass completely

**Comment by NatsuTheGreat** [comment]
@firelightning13 No I did not, I just added and removed tabs, spaces, etc. I really had this bug before too, just never bothered to make an issues since I use my old version of Ogar.

**Comment by PrinceDark9243** [comment]
@Andrews54757 Plz Fix these bug the are annoying!

**Comment by Andrews54757** [comment]
Fixed

**Comment by Megabyte918** [comment]
THANK YOU SO MOOCH

**Comment by NovaHowl** [comment]
You do not know how relieved I am right now.
