### ISSUE TITLE
Minion ?!

### ISSUE THREAD

**Issue by NoorAgario** [AJS-development/Ogar-unlimited#262]
is there any way to make your minion split / give mass ?!!? 
or there any bot that do that
I tried zekebot and agariopower ups and both are not working !

**Comment by PrinceDark9243** [comment]
@NoorAgario  press Q and B will popup on you Name in B mode you press Space Your Bots will split and when you press W your Bots Will Eject Mass Simple. and I have A Question Are you Muslim?

**Comment by firelightning13** [comment]
@NoorAgario See [here](https://github.com/AJS-development/Ogar-unlimited#minions)

**Comment by NoorAgario** [comment]
Yes I'm PrinceDark , iam Egyptian

**Comment by Megabyte918** [comment]
Egyptian damn son

**Comment by firelightning13** [comment]
lol wat

**Comment by NoorAgario** [comment]
what do u mean !? Megabyte918    (>.<)
