### ISSUE TITLE
Live Console does not seem to work

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [AJS-development/Ogar-unlimited#266]
I've only tested the dev branch but all I get is a blue box at the top of my console window on a linux system. Not sure what is going on here but I was about to refactor it into ConsoleService.js but it doesnt seem to work.

**Comment by Megabyte918** [comment]
I wish i could help but i dont have linux :(

**Comment by MichaelLeeHobbs** [comment]
@Megabyte918 does it work on windows? I'll load up my windows box latter and check it out.

**Comment by firelightning13** [comment]
![image](https://cloud.githubusercontent.com/assets/17120382/13904243/ccc37612-eed4-11e5-8b7e-6d6520b356da.png)
![image](https://cloud.githubusercontent.com/assets/17120382/13904244/d53998e4-eed4-11e5-9e1b-58bb1b22e3dc.png)
![image](https://cloud.githubusercontent.com/assets/17120382/13904246/e08b5d72-eed4-11e5-8f97-7540a724f7ec.png)

**Comment by MichaelLeeHobbs** [comment]
@Megabyte918 np, thanks this make sense. We are pushing special codes to the console to make this possible. It would take some research to make this work on linux so for now I'm going to close this issues as leave this as a windows only feature as I have already built a web site for controlling Ogar. I just need to take some time and update it to also control a OgarUL server.

**Comment by Megabyte918** [comment]
What website?

**Comment by MichaelLeeHobbs** [comment]
It's not published per say but more of a private web server you can run. You can check it out here: https://github.com/MichaelLeeHobbs/OgarMind

**Comment by Megabyte918** [comment]
How do i use it?

**Comment by MichaelLeeHobbs** [comment]
The short version is install it on a machine then open a browser and go to http:ipAddress:9000 login as admin@example.com pw: admin
Only admin can create servers. From there go to the server management page. Create a server then configure it as you like. Push the play button to start/restart the server. The play button is a tad buggy so dont spam it :D

**Comment by Megabyte918** [comment]
can you pls explain in a bit more detail i dont get it
