### ISSUE TITLE
Memory Leak (Ogar has this issue, too)

### ISSUE THREAD

**Issue by hartsindale** [AJS-development/Ogar-unlimited#267]
So both Ogar and Ogar-unlimited has this memory leak, and my server can't even last 6 hours. I wish I can use auto-restart, but I'm on a ubuntu VPS. Is it possible to fix the memory leak or create a auto-restart script for linux / ubuntu?

**Comment by MichaelLeeHobbs** [comment]
Use pm2 to run OgarUL it will ensure it auto restarts.
npm install pm2 -g
from src folder: pm2 start index.js

As to the memory leak, OgarUL is currently under going a major refactor that will leave us looking nothing like the original Ogar. Hopefully we will find the leak during this process. For now I will close this issue as I expect it to be resolved during our over haul/refactor.
