### ISSUE TITLE
Spawning/Splitting/Minions/Etc.

### ISSUE THREAD

**Issue by fodse** [AJS-development/Ogar-unlimited#268]
Hello, i found some issues that i would really appreciate if someone could fix them.

- If a player spawns from an Ejected Mass, he will always have the size of that mass (13 by default), and not the size that is displayed on "PlayerStartMass" in "Gameserver.ini" (which is 43 in my case).

- I'm not sure of this, but i think sometimes you also spawn with 10 mass from pellets, even though the max mass of them is set to 5.(I don't know if this happens in vanilla Agar.io, but it's very annoying, because i could simply spawn in another location of the map with 43 mass).

- In 80% of times  you'll spawn very close to some other player/bot or even dead.(The same happens with viruses).

- The size of the Minions should not be based on the size displayed in "PlayerStartMass", because i want to spawn with - for example - 43 mass but i dont want minions to spawn with the same mass, i want them to spawn with 10 mass.

- In vanilla Agar.io, when your cell is small and you get close to the border, it kinda goes inside of it. (This was possible in previous versions of Ogar i think).

- In vanilla Agar.io, when you split with the cursor in the middle of the cell, it doesn't split horizontaly, it actually splits to alot of directions and then freezes.

- In "Gameserver.ini" it says "BotMaxSplit = 4". Does it means that they can split 4 times or that they can only have 4 pieces? Because if you split 4 times you get 16 pieces, and i never saw a bot splitting to 16 pieces.

- In the recent updates when you split on a virus/auto-split or W too fast, the game glitches and you can't W anymore, or only with one cell.

- In previous versions, W'ing to a smaller cell would make the mass pass throught it. It's fixed, but the same still happens when splitting.(you're small and then split into a cell that have almost the same size as you).

PS: Sorry if i spelled anything wrong, english isn't my first language.
PS 2: If anything of what i said was already thinked by you guys, but for some reason you couldn't do it, im sorry, i'm kinda new here. And if anything what a said doesn't make any sense, please tell me.
PS 3: I'm not putting this on "Suggestions", since some of them are actually issues.

Thank you.

**Comment by Megabyte918** [comment]
@Andrews54757 ^^^^

**Comment by Megabyte918** [comment]
YES you just described EVERY problem/suggestion i had

**Comment by MichaelLeeHobbs** [comment]
I'll address these soon (some time in the next few weeks) unless some one else wants to tackle them. I know where the code for these issues is and like why it is happening. Some of your issues are easy others not so much.

**Comment by Lukkez** [comment]
More 1,

- When i was afk with mouse at center, i get hitted by a virus, my cells still moving, on agario they freeze, u can see much videos, see Jumbo trolling too;

**Comment by Megabyte918** [comment]
Another one:

- #219 
- virus explosions
- splitting is a little too fast when over 5k mass it kinda "speeds up" towards the end of the split
- w's need to slide for a longer duration when shot out like vanilla agario (possible config for this?)
- cells on the same team on teams mode can prevent another cell from moving, this is very annoying cause sometimes bots like to stick to you

@fodse 

- the same thing happens with viruses for you third issue
- for your fourth issue, its not possible because the official agario client only supports q, w, and the spacebar for keys
- for your seventh issue, i think ogar's doublesplit is more acurrate. check out their source code and make a pull request if you want it. but dont you mean "accurate" not "inaccurate" lol
- for your eighth issue, the same thing as the seventh, but ogar broke it when they updated it so you might have to revert it
- for your NEINth issue, it means bots wont split over 4 pieces
- for your final issue, please say again i dont get it

**Comment by firelightning13** [comment]
OH YES this is what I looking for, issues list.

**Physics**
- When splitting a new cell, the new cell shouldnt be move by cursor (or move a little bit) until cRestoreTicks is finish ticking. I don't know it is a mech from vanilla agar.io but you'll notice when you're too big.

- @Megabyte918 You are right about the third issue, however the value of 130 actually the "range" of vanilla agar.io but it was too fast and yes, snappy. The split should be slow, steady and far range (i know I've issued this bfore but I don't like it when changing the whole game's speed and changing values in the gameserver.ini) (possibly add range multiplier for this?)

**Camera**
The camera sometimes only focus to the smaller cell instead of the big one (possibly giving priority for the big cell?) (you'll notice when you have 2 pieces which is huge cell with very small cell at another one)

**Comment by fodse** [comment]
Thanks everyone for complementing my coment. I actually was aware of these bugs, but i literally forgot to write them because the ones that I mentioned are actually the ones that affects the most my gameplay.

@Megabyte918 About the seventh issue, that was badly explained, I know. What i meant was that in Agar.io if you double split too slowly or move your mouse a little bit when splitting, the cells wouldn't split completely lined up, and i thought this didn't happen in Ogar Unlimited. But i was wrong. I tested out again and realized that it is already like this. I'll remove that issue.

About the final issue...

The W thing

-In previous versions of Ogar Unlimited, if you were like 1500 mass and you W in the direction of a smaller cell (100 mass for example) being too close of it, the Ejected Mass would pass through the cell. This bug was fixed.

The Split thing

-If you're like 60 mass and then split in the direction of a cell with approximately the same size of you (150 mass for example) being too close of it you'll pass through the cell. And if the cell is alot bigger than you you'll get inside of the cell for a little bit without dying. 

"the same thing happens with viruses for you third issue". Did you mean some other issue? Because i mentioned that lol.

**Comment by Megabyte918** [comment]
Ohh okay i get it now. that would happen to me sometimes too. you can fix that happening with bots and minions by changing `botupdate` and `minionupdate` to 1 in gameserver.ini, but im not sure about real players. and oh yeah i guess u did mention the virus thing :p i must have read it too quickly

**Comment by Andrews54757** [comment]
eh, il look into it

**Comment by Megabyte918** [comment]
yisss

**Comment by PrinceDark9243** [comment]
Fix Every Thing as you Can!

**Comment by Megabyte918** [comment]
@fodse hey m8 can you explain ur second issue again? I dont get it xP

**Comment by NatsuTheGreat** [comment]
The spawning of minions does base of off playerstartmass as I used them today it was 10, then changed it to 43, it was 43.

**Comment by NatsuTheGreat** [comment]
> -In vanilla Agar.io, when your cell is small and you get close to the border, it kinda goes inside of it. (This was possible in previous versions of Ogar i think).

It does not go inside of it, it squished about to half of the cell and then it can't go any further.

**Comment by fodse** [comment]
@NatsuTheGreat Yes, that was what i meant. It just goes A LITTLE BIT inside of the border (idk why i said "kinda". Like i said, english isn't my first language. And about the minions... Can you explaing that better ? Because if what you mean is that if the playerstartmass is 43, the minions start with 43 mass, then i said that.

**Comment by Megabyte918** [comment]
If you want your minions to spawn with a different mass use the `spawnmass` command

**Comment by NatsuTheGreat** [comment]
@fodse The minions do spawn from playerStartMass.

**Comment by fodse** [comment]
@NatsuTheGreat ? That was what i said.
@Megabyte918 Ok, but i can't make all minions spawn with a different mass at once. I need to do one by one. Or is there a way to do it ?

**Comment by firelightning13** [comment]
@Andrews54757 make a new parameter for minion?

**Comment by Andrews54757** [comment]
instead use `range [start] [end] spawnmass [mass]` as doing it the other way isnt authentic for me

**Comment by problemsofworld** [comment]
if fix these problems  it will like normal agar

**Comment by Megabyte918** [comment]
i referenced this in ogar and used some of you guy's issues in the post i hope you guys dont mind (i gave all credit) 
these issues also apply there, too

**Comment by firelightning13** [comment]
> **Physics**
> - ~~When splitting a new cell, the new cell shouldnt be move by cursor (or move a little bit) until cRestoreTicks is finish ticking. I don't know it is a mech from vanilla agar.io but you'll notice when you're too big.~~**Does happened in agario but when you slowing the down (like less than 20 fps), kinda annoyed me**
> - ~~@Megabyte918 You are right about the third issue, however the value of 130 actually makes the "range" of vanilla agar.io but it was too fast and yes, snappy. The split should be slow, steady and far range (i know I've issued this bfore but I don't like it when changing the whole game's speed and changing values in the gameserver.ini) (possibly add range multiplier for this?)~~**Well I don't care about this now, as Luka have a new formula for splitSpeed(i like original Ogar's physics though)**

**Comment by Megabyte918** [comment]
Should I cross that off the list in the ogar issue too?

**Comment by firelightning13** [comment]
Yeah you should

**Comment by Megabyte918** [comment]
@Andrews54757 i found some more bugs, the killall and reset commands dont work, killall doesnt kill anything, and reset says "Tried to remove a nonexistant virus!" a bunch of times then crashes the server

**Comment by firelightning13** [comment]
Damn so many bugs...

**Comment by Megabyte918** [comment]
@firelightning13 lol ikr, and @fodse you need to update your list alot of these are now fixed

**Comment by Agarian** [comment]
i have a strange bug happen sometimes, the server sometimes stops reading my mouse and doesnt recover until i refresh... didnt happen in older ogar UL

**Comment by Megabyte918** [comment]
Lag maybe? that happens to me too

**Comment by firelightning13** [comment]
me 2 :(

**Comment by Andrews54757** [comment]
I just fixed killall. I think

**Comment by firelightning13** [comment]
About the physics thingy:

- When big splits, sometimes they are still "teleport" after collision resets **?**
- Its hard to control you big cell when you have _(a lot of)_small cell around you
- Still, when using config splitSpeed 100, it's still fast, and very short range when you are small **?**
- When a cell with a decent mass (like 200+) hit by a virus, the small cell should be popped **"gracefully"**(if you know what I mean), NOT "**rushingly**_(not even in dictionary)_" going back to cursor's position.
