### ISSUE TITLE
Split config into basic and advance

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [AJS-development/Ogar-unlimited#269]
Our config is getting crazy and I based on one of the issues that is currently open, I can already seen 2-3 more config options being added.

**Comment by MichaelLeeHobbs** [comment]
I'll setup the logic for this and the config files but someone else will need to go threw them and decided what goes in the basic and what goes in the advance.

**Comment by Lukkez** [comment]
Yes, the config getting CRAZY.

**Comment by Megabyte918** [comment]
by config you guys mean gameserver.ini right?

**Comment by MichaelLeeHobbs** [comment]
@Megabyte918 yeah

**Comment by MichaelLeeHobbs** [comment]
Alright, I banged this out this morning. I've got the changes pushed to the dev branch. It will require you to run npm install as I added a new node module to make this easier to address.

The configuration can be spread across an unlimited number of *.ini files. The only ini the server specifically looks for is the gameserver.ini
