### ISSUE TITLE
Refactor Main logic and Setup multi-processes

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [AJS-development/Ogar-unlimited#270]

**Comment by Megabyte918** [comment]
?

**Comment by MichaelLeeHobbs** [comment]
It is the task I am currently working on.

**Comment by Megabyte918** [comment]
Oh alright got it. Whats it supposed to do?

**Comment by MichaelLeeHobbs** [comment]
Completely over haul OgerUL so that we can set it up to use more than one cpu core. Hell after I'm done it will support full on clustering and I would not be surprised if it could not handle a greater load than agar.io =) Assuming you want to load it up on AWS and use multiples of their top tier instances. However, I will not be held accountable for the bill Amazon send you. ;) The server will be able to support a way larger load than the clients them self.

**Comment by Megabyte918** [comment]
Dang son i cant wait :D

**Comment by firelightning13** [comment]
Me too :D 
Wait what's AWS

**Comment by ItzLevvie** [comment]
[Amazon Web Services] (https://aws.amazon.com/free‎)

**Comment by firelightning13** [comment]
Oh thx @ItzLevvie

**Comment by Megabyte918** [comment]
Aye Itz Levvie xD
