### ISSUE TITLE
Implement this server on Cigar

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#271]
Someone can implement this server on cigar, i have one for friends but the split are buggy, the virus are buggy, the bots too, look ugly... if someone can thx.

**Comment by firelightning13** [comment]
What cigar? Sorry im newbie at this :/

**Comment by Agarian** [comment]
Idk what it was either

**Comment by NatsuTheGreat** [comment]
Cigar is a clone project meant to make clones for agar.io. Which is illegal and should not be discussed here, we don't support cigar. Therefore you'll have to do this by yourself.

**Comment by GhostShot3** [comment]
lukkez is from ajs ? lol

**Comment by firelightning13** [comment]
@GhostShot3 so?

**Comment by GhostShot3** [comment]
![sdsd](https://cloud.githubusercontent.com/assets/18537420/17334568/1157e1ea-58ad-11e6-8411-ffb91ffccf70.png)
