### ISSUE TITLE
Rewrite/Split gameserver.ini - Help Wanted

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [AJS-development/Ogar-unlimited#273]
I have added code to support multiple configuration files ie gameserver.ini  The way it works is any file in the src/configs folder will be read in as if it where gameserver.ini  The order in which they are read is UNKNOWN so do not use it thinking that a.ini will be overwritten by b.ini  This is where override.ini comes in. As always it will be read last and override any settings read in from any other ini file.

Now what we need is some kind soul to go and rewrite or gameserver.ini file and split it up so that it makes it easier for the average user to use and moves the advance options into there own files.

**Comment by Megabyte918** [comment]
Can do 👍

**Comment by Megabyte918** [comment]
[config.zip](https://github.com/AJS-development/Ogar-unlimited/files/181277/configles.zip)

**Comment by Megabyte918** [comment]
does this support overriding certain configs from advGameServer.ini configs in override.ini?

**Comment by MichaelLeeHobbs** [comment]
override.ini overrides everything. Outside of that there is no guarantee of which config file will be loaded in what order. The last one loaded wins but since we don't know who that will be we should not try to override a setting in any of the config files except for in override.ini.

**Comment by Megabyte918** [comment]
alright

**Comment by Megabyte918** [comment]
@Andrews54757 close?
