### ISSUE TITLE
WHY CANT I  FEED

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#274]
Whenever i start feeding it stops after like 10 feeds WTF?

**Comment by Megabyte918** [comment]
sem

**Comment by Agarian** [comment]
same annoying problem, and i popped on a virus and only a few cells actually ejected mass. even then, cells eventually stopped ejecting mass completely

**Comment by Andrews54757** [comment]
Fixed

**Comment by Megabyte918** [comment]
THANK YOU <333
