### ISSUE TITLE
Server IP

### ISSUE THREAD

**Issue by NoorAgario** [AJS-development/Ogar-unlimited#278]
ok so instead of using my normal ip I wanna make something like Agar.io/?ip=Somethin.noip,us 
I already registered a noip account but I don't know which Host Type should I use , I have different option like Type:
DNS Host (A)
 DNS Host (Round Robin)
 DNS Alias (CNAME) 
Port 80 Redirect 
Web Redirect
 AAAA (IPv6) 
I already made a DNS Host (A) and its not working it keeps on saying connecting while it still works on the Normal IP ? ? 
anyhelp , plz reply fast

**Comment by PrinceDark9243** [comment]
Use DNS HOST (A)

**Comment by PrinceDark9243** [comment]
and Are You Muslim?

**Comment by NoorAgario** [comment]
When I used DNS HOST (A) it keept saying that a firewall Is blocking the network and I cant play 
if u can try for me 
Agar.io/?ip=llclan.noip.me:443 


And yes iam a muslim

**Comment by NoorAgario** [comment]
llclan.noip.me I don't know how should we write it :/

**Comment by NoorAgario** [comment]
when I try to check if ports are open in llclan.noip.me it say its closed while its opened when I try to use my normal ip >.< any help ?

**Comment by PrinceDark9243** [comment]
https://www.youtube.com/watch?v=NIrGNDB91EM THIS CAN HELP! and I am Muslim too!

**Comment by PrinceDark9243** [comment]
when your server ready ill play on your server ok?

**Comment by ItzLevvie** [comment]
@NoorAgario make sure to portforward your server, these ports will need to be open (443, 88)

**Comment by NoorAgario** [comment]
yes I port forwardb8ed 443 and 88 Correctly and  when I check that with my normal ip it says that the port us open ! but when I use the noip one it says its closed and I cant join agario :((

**Comment by NoorAgario** [comment]
here is my ip : 197.39.197.4
My noip Host : llclan.noip.me 

The first one should work plz give them a try and tell me if they work or no 
THNX

**Comment by Megabyte918** [comment]
Thats the wrong ip

**Comment by NoorAgario** [comment]
what do u mean @Megabyte918 ??

**Comment by NoorAgario** [comment]
which one is wrong ?

**Comment by Megabyte918** [comment]
When you search google for your ip is that the one that comes up?

**Comment by NoorAgario** [comment]
yea

**Comment by NoorAgario** [comment]
but its always changing like now its 197.39.134.219
what can I do to prevent it from changing ?! @Megabyte918

**Comment by Megabyte918** [comment]
Thats weird. .. that only happens when you reset or turn off your router (for me at least)
Does that just randomly happen or did you turn off your router or...?

**Comment by NoorAgario** [comment]
It happens to me when I connect and disconnect to my router :/

**Comment by Megabyte918** [comment]
Just make sure your router stays connected and you'll be f9 m89

**Comment by firelightning13** [comment]
@NoorAgario Use static IP address instead of dynamic tht way it doesnt change everytime you connect it to internet

**Comment by NoorAgario** [comment]
will the static one keep my public ip from changing ?

**Comment by firelightning13** [comment]
idk, try?

**Comment by NoorAgario** [comment]
nope, I already have an internal (or whatever u call it) static ip , and my public 1 keeps changing like 2 times a day
