### ISSUE TITLE
[Tutorial] How to create and host server using Koding IDE (Alternative for Port Forward/Hamachi)

### ISSUE THREAD

**Issue by firelightning13** [AJS-development/Ogar-unlimited#280]
# How to create server using Cloud9 IDE
#### Too lazy to scroll down? [Click here!](https://github.com/AJS-development/Ogar-unlimited/issues/280#event-597212500) (Your welcome ;))
*If you can't see the images, click it.

1. Go to https://c9.io/
2. Sign in using your Github account or sign up using your e-mail.
![image](https://cloud.githubusercontent.com/assets/17120382/13944774/f84f7b22-f042-11e5-911f-14130ffad442.png)
_*when signing up you may need to follow the instruction on how to activate your email._

3. After that, create a new workspace.
![image](https://cloud.githubusercontent.com/assets/17120382/14015498/73a445fc-f1f4-11e5-9b7c-e4b39250e661.png)

4. In this page, you will name your project, descriptions(optional) and Git links.
    Copy this link for OgarUL : https://github.com/AJS-development/Ogar-unlimited.git
    _(To use another ogar, see the bottom of tutorial)_
    Then in "Choose a template", choose "Node.js".
![image](https://cloud.githubusercontent.com/assets/17120382/13945199/682bdab4-f046-11e5-945c-32b098299e3d.png)

5. Then click *create workspace*.
![image](https://cloud.githubusercontent.com/assets/17120382/13945283/011f6830-f047-11e5-97c6-83c4bf8a3942.png)

6. The C9 will load like this when creating your workspace.
   _Sometimes it takes too long to load, so be patient :)_
![image](https://cloud.githubusercontent.com/assets/17120382/13945314/43919ba2-f047-11e5-9fb0-42d08db51da7.png)

7. After C9 loads, it should be looks like this:
![image](https://cloud.githubusercontent.com/assets/17120382/13945468/7e2543bc-f048-11e5-985b-97a96b589c73.png)

8. In the terminal _(as shown in the above)_, type this:
`npm install`
    This will install node.js modules _(dependencies)_ for the server.
    **_WARNING: If you missed this step, it will not work when starting the server!_**

9. Find the file called "gameserver.ini" under "src" folder in the file manager _(see the image below)_.
![image](https://cloud.githubusercontent.com/assets/17120382/13945706/6c3a2d6e-f04a-11e5-8383-77a05530815b.png)
Then change these lines: `serverPort = 8080` and `serverStatsPort = 8082`
Then you can change whatever you want in the gameserver.ini for your server.

10. Save the file. _(or just press Ctrl + S)_
![image](https://cloud.githubusercontent.com/assets/17120382/13945777/f1c6e512-f04a-11e5-9903-9b8cd9faaaec.png)

11. Now, to start the server _(in terminal)_:
 - Create directory to "_src_" folder like this: `cd src`
 - Run Node.js into your server : `sudo node index.js`
![image](https://cloud.githubusercontent.com/assets/17120382/13945862/a0b1d884-f04b-11e5-8562-0df43bfb6b86.png)

There you go, now the server start. You can control everything in your server by directly using terminal.

### How to join

The link should be like this: `http://agar.io/?ip=<yourprojectname>-<yourusername>.c9users.io`

#### OR

- Click "_Preview Running Application_" in the preview tab.
![image](https://cloud.githubusercontent.com/assets/17120382/13945901/f74b3938-f04b-11e5-97d0-c19069f55896.png)

- Now a window appears, and your link will be there. Copy it and paste it in the browser's address like this : `http://agar.io/?ip=<paste your url in here>` .
**Note: DON'T INCLUDE"https://" AND "/"(the last character in the link) IN THE AGAR.IO'S IP ADDRESS OR ELSE IT MIGHT NOT WORK!**
![image](https://cloud.githubusercontent.com/assets/17120382/13946216/3d39ef5a-f04e-11e5-830b-85ee2e647395.png)
*Ignore the "_Upgrade Required_", there's nothing to worry about :P

#### How to use another version of ogar (instead of OgarUL)
In step 4, how did I get the Git link?
Well, that was easy to do. Lets say that I want to use Ogar instead of OgarUL.

In the main page of the repository, copy the link. _(look at the image below)_
![image](https://cloud.githubusercontent.com/assets/17120382/13946556/3c1bc704-f050-11e5-9b75-2d50a1578bd5.png)
Then you can paste the link like in the Step 4 above.

## Things you should note when using Cloud9 IDE
- I can't guarantee that this will run in 24/7 _(if you close the tab it only active for couple of hours only...)_
If you know how to run it 24/7, or probably other than using c9, please comment here.
_(other than leaving a computer for 24/7, no pls I know dat)_

- Use this if you want to play with your friends _(this is alternative for port forward/hamachi)_

**Comment by firelightning13** [comment]
The "vps" config doesn't seem to be working right now.

**Comment by Agarian** [comment]
thanks bro

**Comment by Megabyte918** [comment]
Nice!

**Comment by Agarian** [comment]
try my server? http://agar.io/?ip=ogarserveragarian-agarian.c9users.io

**Comment by NatsuTheGreat** [comment]
Hey I use another version of ogar not this and I don't have a specific link to it, this is asked for in step 4.

**Comment by firelightning13** [comment]
@NatsuTheGreat I'm on it!

**Comment by retslac** [comment]
@firelightning can you run server 24/7 here ?

**Comment by firelightning13** [comment]
@retslac No. I think you can't.

**Comment by ItzLevvie** [comment]
@firelightning13 It used to be for an week, but they changed it to an hour.

**Comment by ItzLevvie** [comment]
@firelightning13 It used to be active for an week, but they changed it to 1 - 2 hour.

**Comment by retslac** [comment]
Pity.  Would of been nice...

**Comment by firelightning13** [comment]
Umm... help?
![image](https://cloud.githubusercontent.com/assets/17120382/13951539/907705a4-f06c-11e5-9645-ea24f74cc25a.png)

I'm using koding right now and I don't know how to connect demmit ._.

**Comment by Agarian** [comment]
i have a server if u'd like to try it

**Comment by NatsuTheGreat** [comment]
@retslac How's going? Able to come on discord today?

**Comment by Agarian** [comment]
@NatsuTheGreat im back in

**Comment by Megabyte918** [comment]
Is there ANY way to have a 24/7 server without paying?

**Comment by NatsuTheGreat** [comment]
I was hoping i'd figure it out. I have windows and I can't find any way to host is free :( Only trials which require much other stuff.

**Comment by Megabyte918** [comment]
Damn...

**Comment by firelightning13** [comment]
I will make tutorial on how to use koding IDE once im free ;)

**Comment by Megabyte918** [comment]
Gr8 m8 I cant w8 :D

**Comment by firelightning13** [comment]
Done. Tutorial for koding IDE is up!

**Comment by Megabyte918** [comment]
@firelightning13 thank you so much <3

**Comment by NoorAgario** [comment]
i have done everything to make a c9 server but it tells me that there is a firewall blocking the connection ?! should i port forward 8080 and 8083 ?! or should i just use 443 and 80 @firelightning13

**Comment by ItzLevvie** [comment]
Use 8080.

**Comment by NoorAgario** [comment]
i was using 8080 and 8083 nw I'm using 443 and 88 and they r working

**Comment by ItzLevvie** [comment]
Oh you're using Koding. nvm

**Comment by NoorAgario** [comment]
which one gives less lag ?! koding or c9 @ItzLevvie

**Comment by Megabyte918** [comment]
c9 lagged ALOT for me

**Comment by ItzLevvie** [comment]
You tried JXCore? ^

**Comment by NoorAgario** [comment]
nope what is that ?

**Comment by Megabyte918** [comment]
Look above lol

**Comment by Megabyte918** [comment]
Oh sorry thought u meant c9 didnt see levvies comment >. <

**Comment by firelightning13** [comment]
@ItzLevvie Did u mean [this](https://github.com/jxcore/jxcore)?

**Comment by ItzLevvie** [comment]
@firelightning13 Yes.

**Comment by ErikParacelsus** [comment]
c9 crashed my pc so i switch to koding

**Comment by ItzLevvie** [comment]
C9 works fine for me.

**Comment by firelightning13** [comment]
@ErikParacelsus Whats your pc's spec?

**Comment by Megabyte918** [comment]
@firelightning13 how do i get the git links of a different branch? its just the same thing every time

**Comment by firelightning13** [comment]
@Megabyte918 Hmm i dunno

**Comment by markvillar** [comment]
@firelightning13 I think you can run it 24/7 on c9.io using `screen`

`sudo apt-get update`

`sudo apt-get install screen`

Change to `/src` directory

then run:

`screen -mdS server sudo node index.js`

the 'server' can be changed to anything you want to call the session with

that'll run as if you're staring the screen.

to get back to the command line:
`screen -r` or `screen -r server`

unless there's a CPU quote on the server.

**Comment by Agarian** [comment]
for some reason when i close the window with my server, it runs in the background...

**Comment by markvillar** [comment]
@Agarian Oh, I guess you don't need to use screen then, as long as it lasts for however long you intend it to run for.



@Megabyte918 I think you'd have to switch to the branch manually using `git checkout [name of the branch]`, I don't think you can clone a different branch directly.

**Comment by firelightning13** [comment]
@Agarian 
> for some reason when i close the window with my server, it runs in the background...
How long it will last?

@markvillar Kinda surprised that your server is still running even your comment is 18 hours ago, thanks for sharing the info :)

**Comment by Andrews54757** [comment]
I rather use tmux

**Comment by firelightning13** [comment]
how to use it? :/

**Comment by Megabyte918** [comment]
@markvillar what folder do i install screen to? node modules?

**Comment by firelightning13** [comment]
@Megabyte918 /workspace

**Comment by Megabyte918** [comment]
it doesn't do anything when I run the command

**Comment by markvillar** [comment]
@Megabyte918 which command?

**Comment by Megabyte918** [comment]
Ohh yeah it was :P i thought it wasn't cause the "ogar unlimited" thing didnt come up. Thank you man this is pretty cool!

**Comment by PrinceDark9243** [comment]
guys i want to know how to add Plugin in c9.io server @firelightning13 Can You do a Tutorial on it!

**Comment by firelightning13** [comment]
Welp, I'm too lazy to edit lol ._.

I'll do it when I have free time

**Comment by ErikParacelsus** [comment]
@markvillar Thanks for the 24/7 tip you helped me a lot.

**Comment by Andrews54757** [comment]
easy, do `plugin add [pluginfiles.txturl] [pluginname]`

**Comment by PrinceDark9243** [comment]
can someone make a vid on 24/7 plz i cant understand the english because i am from pakistan lol!

**Comment by Agarian** [comment]
this is not outdated :p

**Comment by firelightning13** [comment]
lel my brain exploded when reading this back

**Comment by timjrobinson** [comment]
Running Ogar on Cloud9 is against the Terms of Service and will get your account banned. See here: https://community.c9.io/t/can-i-use-cloud9-for-hosting/16/2 for more information.

Cloud9 is a development platform, to help people learn to code or build their own applications. It is not a free VPS.

**Comment by HappyRocketwheel** [comment]
hey, koding changed so there's only team mode, not solo mode

mind posting an updated version of the koding tutorial

**Comment by LegitSoulja** [comment]
@HappyRocketwheel I never used koding, but ill make a better update tutorial.

**Comment by jake11221212** [comment]
Is it possible to connect anymore? Agar.io just freezes when I try to join.

**Comment by LegitSoulja** [comment]
@jake11221212 nope, because miniclip sucks cucumbers for a living
 
use http://play.ogarul.tk

**Comment by hassanila97** [comment]
They just changed packets and everything but they didnt remove the private server option....

**Comment by LegitSoulja** [comment]
@hassanila97 I know, but they have not yet been reversed and found yet, as I know of.

**Comment by hassanila97** [comment]
@LegitSoulja Almost done.. check [**THIS**](https://github.com/xzfc/agar-expose/blob/master/expose.user.js)

**Comment by LegitSoulja** [comment]
Nicee

**Comment by hassanila97** [comment]
Yes almost everything is decoded... we just need moveTo, split and feed... then done

**Comment by LegitSoulja** [comment]
Agar.io graphics are bad. 

I don't understand the purpose of even trying to use agar.io client.

**Comment by firelightning13** [comment]
Im closing this, for now

**Comment by Agarian** [comment]
keep it open for koding bro

**Comment by firelightning13** [comment]
I accidently delete it lol, but still koding sucks now
