### ISSUE TITLE
MANY ANNOYING BUGS

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#281]
- ~~mothercells will continuously spawn food until they hit 0 mass~~ (fixed by @NatsuTheGreat #299 )
- ~~autosplit doesn't work all the time~~ (resolved in @NatsuTheGreat 's open Pull Request)
- ~~W doesn't work all the time and sometimes stops~~ (resolved by @Andrews54757 )
- ~~cells no longer squish on the map border or on other cells, but do on the borders of view bases X and Y~~
- i noticed minions sometimes, when removed, leave ghost cells

**Comment by ErikParacelsus** [comment]
"cells no longer squish on the border or other cells"
change `vps`= 20 to higher values example `vps` = 30 or `vps` = 40

**Comment by Agarian** [comment]
u mean fps?

**Comment by Megabyte918** [comment]
How does that fix it lol

**Comment by Agarian** [comment]
Thing is, cells do squish when beyond the borders of view bases X and Y

**Comment by firelightning13** [comment]
wtf is vps gonna do anyway?

**Comment by Megabyte918** [comment]
#makeogarunlimitedgreatagain xD

**Comment by firelightning13** [comment]
#WhereIsAndrewWeNeedHelp

**Comment by Agarian** [comment]
I saw a "backup" branch, that may be the answer

**Comment by Megabyte918** [comment]
Where?

**Comment by Agarian** [comment]
https://github.com/AJS-development/Ogar-unlimited/tree/backup

**Comment by NatsuTheGreat** [comment]
- I will try ti fix the mothercells if it isn't already fixed.
- I fixed autosplit in my pull request
- W is fixed

**Comment by Megabyte918** [comment]
@Agarian put your last one in #268 i guess this is where bugs will go
