### ISSUE TITLE
Last man standing 

### ISSUE THREAD

**Issue by ErikParacelsus** [AJS-development/Ogar-unlimited#282]
Can you make the server can start last man standing after certain times?

**Comment by Megabyte918** [comment]
You mean it would randomly choose whether to shut down the server and not let anyone else join? 
Oh and btw this belongs in suggestions

**Comment by Agarian** [comment]
i think so, if this is added, make it configurable
randlastmanstanding: if 1, after a random time, the server shuts down the server and does not let anyone else join. If 0, this doesnt happen (should be default)

**Comment by ErikParacelsus** [comment]
Or 
`lastmanstandingmins`: if 60 = 60 mins

**Comment by Megabyte918** [comment]
@Andrews54757 close?

**Comment by Agarian** [comment]
I got it
