### ISSUE TITLE
Virus Spawn Ticks

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#283]
This is a easy thing and is good for people who like make virus map (I like make)

**Comment by NatsuTheGreat** [comment]
What do you mean? We have the *spawnInterval* setting that takes care of the food and virus spawning. Can you explain is a little bit more or be specific? Otherwise you can use *spawnInterval*

**Comment by Lukkez** [comment]
The virus still slow for me with spawnInterval, and we can make one for food and one for virus

**Comment by NatsuTheGreat** [comment]
make spawnInterval 1 for fast.

**Comment by Megabyte918** [comment]
He means a seperate spawn interval for both viruses and food cause setting spawn interval to 1 ALSO makes the food spawn really fast

**Comment by NatsuTheGreat** [comment]
he wants it slower or faster? I'm confused.

**Comment by NatsuTheGreat** [comment]
If he wants a separate spawnInterval for viruses and for food it'll be easy to make. I could make the config values and test it for virus spawning.

**Comment by NatsuTheGreat** [comment]
I got it to work!

**Comment by Megabyte918** [comment]
You did? How'd u do it?

**Comment by Agarian** [comment]
you should make a PR (Pull Request) for it

**Comment by Lukkez** [comment]
Yes @Megabyte918 Is this, and sorry for offline time, my pc got **HACKED** and i needed to reinstall windows

**Comment by NatsuTheGreat** [comment]
Sure i'll make a pull request soon.

**Comment by Agarian** [comment]
Wtf hacked?!

**Comment by Agarian** [comment]
Accidental close ;-;

**Comment by Agarian** [comment]
@Megabyte918 are you online?

**Comment by Megabyte918** [comment]
i dont have access to my computer atm. im staying over my friends for the night :D 
ill be back tomorrow morning tho dont worry youll get it

**Comment by Lukkez** [comment]
Yes, i got hacked BEFORE

**Comment by Andrews54757** [comment]
good luck in making it, mabye i will make it before you, but im busy as im doing other things. (its really simple though)
