### ISSUE TITLE
Crashing problem

### ISSUE THREAD

**Issue by ErikParacelsus** [AJS-development/Ogar-unlimited#285]
When i play any ogar-unlimited server (except others ogar) on my chromebook i crashed after 10 mins of gameplay

**Comment by NatsuTheGreat** [comment]
Chrome book isn't the best thing to use but still use-able.

**Comment by Megabyte918** [comment]
What crashed? The server? The chromebook? The browser?

**Comment by ErikParacelsus** [comment]
The chromebook it shut down after 10 mins after game play.

**Comment by Megabyte918** [comment]
Thats weird... I dont think its a problem with ogar unlimited I think its the chromebook itself because I dont think that that would be able to shut a chromebook down lol
you might want to look into that thats not good xD

**Comment by NatsuTheGreat** [comment]
It may be a problem with the hard disk (make sure to keep the rage inside and not to bang the chrome book. Treat it gently. Check is your processor is good.) Check any other details in the chrome book. And try using some other device E.G a computer, and see if it crashes. Ogar Unlimited shouldn't crash a computer.

**Comment by Megabyte918** [comment]
@Andrews54757 close?

**Comment by Agarian** [comment]
i got it
