### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by GhostGuild** [AJS-development/Ogar-unlimited#286]
This might be a cancer post but I can't install this damn thing! I install the dependencies then when I start it it tries to look for files in system32 like wot da fuk? I can't avoid this either as it asks for admin permission. Is it supposed to do this? I put all files in sys32 and still doesnt work (replaced some because it looks directly in root)
Help dank coders!

(It says 'can't find xx module)

**Comment by GhostGuild** [comment]
module.js:341
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\WINDOWS\system32\modules\CommandList.js:8:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

Press any key to exit...

**Comment by ItzLevvie** [comment]
Do ```npm install request```.

**Comment by GhostGuild** [comment]
? Am very confused, I suck at this type of stuff

**Comment by GhostGuild** [comment]
Okay I THINK i did it right. I went into the folder and opened cmd there and put it in. It did some fancy stuff but when i open the server bat im still faced with the error

**Comment by ItzLevvie** [comment]
Windows Key + R, then type ``npm install ws request```

**Comment by GhostGuild** [comment]
Same error

**Comment by firelightning13** [comment]
@GhostGuild Where did you install Ogar-unlimited?

**Comment by ItzLevvie** [comment]
@GhostGuild Make sure you put Ogar-unlimited-master on the desktop, then open it, click the folder called ```src``` , then click on ```Install Dependencies (Windows).bat``` and finally click ```Start.bat```.

**Comment by GhostGuild** [comment]
@firelightning13 I installed it in the download folder
@ItzLevvie Same error because it looks for files in sys32

**Comment by GhostGuild** [comment]
Nvm it works now! Putting it in desktop did some dank coding stuff and now when i open it without admin it just works, dank help and sup00rt
