### ISSUE TITLE
How i can make ejected mass does not bounce from border and does not keep away form each other!

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#287]

**Comment by Agarian** [comment]
we wanted this. Its a part of ogar unlimited and its staying. Not 2 be rude

**Comment by Agarian** [comment]
to stop ejected mass collision tho, go to ejectedmass.js
remove this:
    EjectedMass.prototype.onAdd = function(gameServer) {
    gameServer.nodesEjected.push(this);
    };

**Comment by PrinceDark9243** [comment]
and how i can make it not bounce form border

**Comment by Agarian** [comment]
idk about that

**Comment by PrinceDark9243** [comment]
Anyone else can help i am making a Ogar Server for Mobile (LOL For PC)
