### ISSUE TITLE
Cell Color with Skin

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#292]
is there is a way to Make Cell Color With Skin like `Kraken have Dark Green Color then the cell color Change to Dark Green` Idea for Agar.io Mobile (ANDROID)

**Comment by PrinceDark9243** [comment]
The Outline of Skin in Cell will be Color. Can Andrews make it?

**Comment by Andrews54757** [comment]
Yes I can make it but it is entirely useless in my point of view, why care about border color anyway?

**Comment by Andrews54757** [comment]
If you convince me, I will add it

**Comment by PrinceDark9243** [comment]
OK add IT! and @Andrews54757

**Comment by Agarian** [comment]
U can do so by putting the premium skin as a custom skin url in customskins.txt
Andrews please dont make the actual premium skins not effect the cell border
