### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by XtremePlayzCODE** [AJS-development/Ogar-unlimited#293]
Everytime I load up agar.io, it keeps saying Connecting... And yes, I am going on agar.io/?ip=127.0.0.1:443 and everytime I load up OgarUnlimited this happens, and I always refresh and type in connect("ws://127.0.0.1:443") but yet I have to copy over everything from the zip I downloaded. It is soooo annoying

**Comment by XtremePlayzCODE** [comment]
Not even copying over everything from the zip works anymore... #makeogarunlimitedgreatagain

**Comment by NatsuTheGreat** [comment]
Make sure the port IS *443* if it this, this time try *agar.io/?ip=localhost:443*

**Comment by XtremePlayzCODE** [comment]
I said it was on 443, but thanks anyways

**Comment by Andrews54757** [comment]
Is a firewall up?

**Comment by Andrews54757** [comment]
If not, try using your lan ip

**Comment by XtremePlayzCODE** [comment]
No firewall

**Comment by XtremePlayzCODE** [comment]
I just had it working but then restarted in the console. Now it wont load. WTF?

**Comment by XtremePlayzCODE** [comment]
aCCIDENTALLY CLOSED THIS :p

**Comment by Andrews54757** [comment]
Try your lan ip and run sudo node index.js instead

**Comment by XtremePlayzCODE** [comment]
Ok then

**Comment by XtremePlayzCODE** [comment]
Tried lan and sudo... it still isnt loading... I tried patch 2, master, and backup incase you want to debug

**Comment by XtremePlayzCODE** [comment]
I am a coder myself, but im not used to node and websockets so i cant debug this myself

**Comment by Andrews54757** [comment]
It's your computer then, use c9 or Koding.com. Instructions here #280

**Comment by XtremePlayzCODE** [comment]
Thanks Andrew!
