### ISSUE TITLE
[Enhancement] Add the chat protocol like Cigar has

### ISSUE THREAD

**Issue by xXAndrew28Xx** [AJS-development/Ogar-unlimited#3]
Can you please add the chat protocol that https://github.com/CigarProject/Cigar has? This would make me use this over all other Ogar forks! I get like 20 people on everyday and need some variety

**Comment by Andrews54757** [comment]
I am sorry but it is fully ILLEGAL to create client clones. This fork has a detector so you must use the agar.io client. I wish I could also add chat or something else but I cannot. You can do it though, (but you cannot post it) I do not wish to be a violator of a copyright law. 

I will leave this 'Issue' open so other people can suggest on how you can implement chat.

**Comment by Andrews54757** [comment]
(It is also the reason why OP seems complex. because they only support key Q, W, and space)

**Comment by Andrews54757** [comment]
(Irony: ogar UNLIMITED is LIMITED to the legal client)

**Comment by RobinTheGod** [comment]
Making a agar.io Client clone is illegal. But making your own Client implementation can't be illegal. -> Its like making a Game in the same Genre. Thats legal to! 
Greetings,
Robin

**Comment by Andrews54757** [comment]
But cigar uses a illegal one

**Comment by Andrews54757** [comment]
Mabye i will add a chat protocal but they have to disable the client authenticity check by themselves

**Comment by Andrews54757** [comment]
Here is the disclaimer by the agario clone people
Disclaimer

Note that the aim of this repo is to study agar.io client, understand the mechanism and find potential improvements. It is worth pointing out that hosting a third-party agar client is against the Terms of Agario and not recommended by the owner of this repo. Please think twice before hosting the client and do it at your own risk. :)
