### ISSUE TITLE
This stupid bots...

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#304]
everytime i try to split someone with a virus a random bot goes on that virus and pops on it like every single bot was a team of the bot i wanted to split ..

P.S. i never got to split someone in ogar unlimited

**Comment by firelightning13** [comment]
@elitajmx Of course they are always wanna do that, because right now bots are stupid, they can't even  know how to avoid virus. Just wait until MichaelLeeHobbs will fix this ok?

**Comment by MichaelLeeHobbs** [comment]
@firelightning13 I will soon (trademarked)

**Comment by Megabyte918** [comment]
@Agarian close?
