### ISSUE TITLE
New Ogar2 Fork! (OgarioProject)

### ISSUE THREAD

**Issue by ThunderGemios10** [AJS-development/Ogar-unlimited#312]
We are pleased to announce the new fork of Ogar2, **The Ogario Project!**

## Features:
- Plugins
- Leaderboard
- Multi-Colored Food
- Better configuration
- Performance enhancements
- Bugfixes
- Splitting and Ejecting..

## Planned/Upcoming Features:
- Bots
- Chat (Maybe?)
- Commands API
- Many API features.

## Known Bugs:
- Entities sometimes are not disappearing/deleted from the world.

## Our GitHub repositories:

- [Ogar2-API](https://github.com/OgarioProject/Ogar2-API)
- [Ogar2-Server](https://github.com/OgarioProject/Ogar2-Server)

## Our Team members:

- SkorrloreGaming - (Project Lead/Implementation Lead Developer)
- ThunderGemios10 - (Developer/API Lead Developer)

Any help or contributions is always appreciated!

**Comment by MichaelLeeHobbs** [comment]
Doesn't really apply to us. Ogar 2 is Java and I'm fairly sure we plan to stick with node/js.

**Comment by ThunderGemios10** [comment]
@MichaelLeeHobbs I know that. I'm just sharing it :)

**Comment by Lukkez** [comment]
@ThunderGemios10 You can teach me how to install this? i really want this to test, but i don't know how to install Java servers/files.

**Comment by ThunderGemios10** [comment]
@Lukkez You can download the compiled builds on my Jenkins CI server,
http://ci.thundergemios10.com/job/Ogar2-Server/

**Comment by Andrews54757** [comment]
Lol, advertising another server from here

**Comment by Andrews54757** [comment]
also, this is very basic. But this would be entirely useless by the time @MichaelLeeHobbs merges dev into master as it would pretty much be the same preformenence, only difference would be ogarul would have more features and it doesn't have an api

**Comment by MichaelLeeHobbs** [comment]
@Andrews54757 I've been thinking about a plugin system, but didn't wont to put that out there so people start asking when, until the current set of changes are done as well as the bot upgrade.

**Comment by Andrews54757** [comment]
ive been thinking about that too, where gamemodes,commands,and configs can be added in a single plugin

**Comment by Andrews54757** [comment]
but i dont know how it works

**Comment by MichaelLeeHobbs** [comment]
The general idea would be to have a folder say called plugins. Inside would be more folders, each with an index.js file as the entry point to the plugin. The index.js file would need some sort of function that all are required to have, say init(). The plugin loader would iterate over each of these folders and require the index,js into an array of plugins calling the init() of each of them and pass in things like gameServer and other stuff they might need. That's the general idea but there are a lot of un-answer question here. That would have to be explored and fleshed out.

**Comment by ThunderGemios10** [comment]
@Andrews54757 Ogar 2 has an API, Which is very easy to learn, People can create plugins, let's say create their own Game Modes or so.

**Comment by Andrews54757** [comment]
I dont like that, I want people to learn the full code as api is useless on other projects, I want to make people learn how to code fully on their own so they could apply that on other projects too

**Comment by ThunderGemios10** [comment]
@Andrews54757 That's your opinion, But i respect that.

**Comment by Agarian** [comment]
guys stop messing with the issue name.

**Comment by Andrews54757** [comment]
whatever, just having some fun , lol

**Comment by ThunderGemios10** [comment]
@Andrews54757 Same here lol.

**Comment by Andrews54757** [comment]
ive decided to addd a plugin system. My prototype is on the dev branch

**Comment by ThunderGemios10** [comment]
@Andrews54757 Good luck lol.
