### ISSUE TITLE
DEVS - DO NOT EDIT OR ACCEPT PRS TO MASTER ANYMORE

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#314]
We are now moving to dev, so any edits must be on dev

**Comment by MichaelLeeHobbs** [comment]
@Andrews54757 Please review StickyCell.js - git merge failed badly on that file for some reason and I am not familiar with it.

**Comment by Andrews54757** [comment]
ok

**Comment by Andrews54757** [comment]
actually, lets not merge because it is too complicated, lets do it manualy, incorporating updates into dev

**Comment by MichaelLeeHobbs** [comment]
Yeah, the different formatting that has been used made the merge I tried this morning fail. I was thinking about checkout master, formatting it and committing it back. Then do the same to dev just to make sure it is also formatted the same. Then I was going to try another merge.

Going forward we need to make sure any bug fixes that get applied to master also get applied to dev.
