### ISSUE TITLE
c9 error pls help

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#318]
Failed to write to 'gameserver.ini'. Failed saving file ! : src/gameserver.ini ERR: Error: EACCES, open '/home/ubuntu/workspace/src/gameserver.ini'.

how can i fix this?

**Comment by Lukkez** [comment]
Create a new  workspace is c9 error

**Comment by MichaelLeeHobbs** [comment]
Sounds like a permission issue. Try running with sudo or root. You can switch to root with su - though not sure if you can do that on c9.

**Comment by MichaelLeeHobbs** [comment]
Wait how did you run it?

**Comment by Andrews54757** [comment]
im on gitter now

**Comment by Agarian** [comment]
nvm i fixed it

**Comment by firelightning13** [comment]
@Agarian How? I've got that error too when updating OgarUL

**Comment by Agarian** [comment]
I copied the text from the file, deleted it, recreated it, and pasted code in and saved the file?
