### ISSUE TITLE
GitterChat

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [AJS-development/Ogar-unlimited#319]
@Andrews54757 can you head over to https://gitter.im and create a git chat for us? I tried but it wouldn't let me do it for this project. It would only let me do it for projects I had created.

**Comment by Andrews54757** [comment]
added

**Comment by Andrews54757** [comment]
[![Join the chat at https://gitter.im/AJS-development/Ogar-unlimited](https://badges.gitter.im/AJS-development/Ogar-unlimited.svg)](https://gitter.im/AJS-development/Ogar-unlimited?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
