### ISSUE TITLE
I have ogar feeder but I want it to have smart bots like urs in blind mode HELP mE @ andrew plz 

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#321]
Please read the faq in advance

Most common questions involve:

Why is there an error "cannot find module"
A: Do npm install after you cd into the repo

**Comment by Andrews54757** [comment]
I do not support minions and I definatly dont like to support cheating, Actually, I find out more ways to defeat robots

**Comment by firelightning13** [comment]
This post is cancer

jkjk
