### ISSUE TITLE
DMCA Notice for all Ogar repositories.

### ISSUE THREAD

**Issue by ThunderGemios10** [AJS-development/Ogar-unlimited#323]
It seems Ogar Project has sent out DMCA notices to all Ogar forks.
A copy of the notice can be found here:
https://github.com/github/dmca/blob/master/2016-02-19-Ogar.md

**Comment by ItzLevvie** [comment]
aik

**Comment by Agarian** [comment]
Wtf

**Comment by ItzLevvie** [comment]
yikr

**Comment by ThunderGemios10** [comment]
@Agarian Agreed, WTF. :)
