### ISSUE TITLE
Custom skins doesn't work

### ISSUE THREAD

**Issue by markelite** [AJS-development/Ogar-unlimited#324]
customskins.txt seems to be not working, the cell will just become "An unnamed cell," only `<spy>` works at the moment. Could this be a bug?

I did follow [Skins and skin shortcuts](https://github.com/AJS-development/Ogar-unlimited/wiki/Skins-and-skin-shortcuts) carefully.

and when I reload the server, I get this error?

> [Console] Generating customskin.txt...
[ERROR] Oh my, there seems to be an error with the command reload
[ERROR] Please alert AJS dev with this message:
Error: ENOENT, no such file or directory './customskins.txt'

I did not touch or delete any file on the server.

**Comment by Megabyte918** [comment]
thats weird... it works for me. make sure your doing <skinname> (name)
so for example if i wanted to use the dark spy skin, i would use <darkspy> then my name

**Comment by markelite** [comment]
That's exactly what I'm doing.. I have untouched customskins.txt on my server, you can try it. `http://agar.io/?ip=agario.markelite.cu.cc:1500`

**Comment by Megabyte918** [comment]
what did you try to name yourself

**Comment by markelite** [comment]
`<darkspy>` pretty much everything in the customskins.txt don't work.

**Comment by Megabyte918** [comment]
damn... what could be wrong... your doing everything correctly @Andrews54757 do you know what might be wrong?

**Comment by fodse** [comment]
Yes, i had a custom skin named <twitch> that stopped working without i changing absolutely nothing. But make sure your skins shortcuts look like this :

`skin :http://i.imgur.com/blabla.png`

**Comment by markelite** [comment]
Yes.. but I mean even the default customskins.txt doesn't work, I did not even add anything in there.

**Comment by Andrews54757** [comment]
it is because it cannot find customskins.txt, are you using `sudo node src/index.js` or `sudo node index.js`. It doesnt work if you use the first way.
