### ISSUE TITLE
ejectMass glitch

### ISSUE THREAD

**Issue by loboere** [AJS-development/Ogar-unlimited#327]
ejectMass through another cell
![ezgif-243432740](https://cloud.githubusercontent.com/assets/15265895/14160862/ad21fae8-f6b5-11e5-9251-f1ab24883d5d.gif)

**Comment by NovaHowl** [comment]
Yea I've noticed that it doesn't really happen to real players but it does to bots or minions :/

**Comment by Lukkez** [comment]
Small fix, change botupdate to lower value, not fix at all but is good for a time

**Comment by Agarian** [comment]
botupdate should be 1 by default.

**Comment by Megabyte918** [comment]
@Agarian close?

**Comment by Agarian** [comment]
done :smile:
