### ISSUE TITLE
either im doing something wrong or PCMD command doesnt work

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#329]

**Comment by Agarian** [comment]
actually i just got an error from PCMD:

ReferenceError: r is not defined
    at null._repeat (/home/ubuntu/workspace/src/modules/CommandList.js:147:13)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by PrinceDark9243** [comment]
i think it is an error in CommandList.js File

**Comment by MichaelLeeHobbs** [comment]
I may have broken it when I did the refactor on the command list. The command list is an area I would like to revisit in the future. It is something that I think could benefit from the plugin system we are working on.

**Comment by Andrews54757** [comment]
no you didnt, it was my error, i fixed it

**Comment by Megabyte918** [comment]
@Andrews54757 clothes?

**Comment by firelightning13** [comment]
*close xD

**Comment by Megabyte918** [comment]
stupid auto correct xd
