### ISSUE TITLE
Minion Control

### ISSUE THREAD

**Issue by NoorAgario** [AJS-development/Ogar-unlimited#330]
How can we change the controls of the minion also how to remove that letter b that shows next to your name plz help pressing q then controlling is hard when you try to team with your bot and I wanna make videos about this Ogar Minions

**Comment by Agarian** [comment]
IK but Andrews says that wont work

**Comment by Andrews54757** [comment]
it is absolutely not possible. unless you use a client. and these are illegal

**Comment by MichaelLeeHobbs** [comment]
@Andrews54757 I might have a way. If we create a web service that serves a webpage with the real client in an iframe this would in theory allow us to  have other elements on the page to control/send other stuff to the server. Now, this likely will not work well for minion control but was thinking it might be a way to control other stuff on the server without having to use the console. However, it is very possible that the agario client will detect that it is in an iframe and refuse to work. As an example twitter wont work when it is in an iframe.

**Comment by Andrews54757** [comment]
1. i think this is illegal
2. I think it detects it
3. i thought iframs cannot go cross domain

**Comment by NoorAgario** [comment]
ok but can I use other bots that work in agario ?! i was using an agario feeder bot in ogar and it worked but its not working in ogarUN !!?

**Comment by MichaelLeeHobbs** [comment]
@Andrews54757 I agree with 1 and 2 which is why I haven't even try to do it. As to 3, they can.

@NoorAgario I don't know why your bot feeder doesn't work but we have much bigger fish to fry right now.
