### ISSUE TITLE
Why I cant use agarplus I want to train and get better but using agarplus on my private server or hk tool anyway to do that 

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#332]
Please read the faq in advance

Most common questions involve:

Why is there an error "cannot find module"
A: Do npm install after you cd into the repo

**Comment by Megabyte918** [comment]
right click and press "inspect element", then go to the console and paste connect("ws://IP:PORT") 
and press enter. (ik its annoying to do all the time but its the only way to connect atm)

**Comment by fodse** [comment]
@Megabyte918 You cant right click while using Agarplus I think.

**Comment by firelightning13** [comment]
It's so weird when playing using agarplus, using anime skins, when the moment that you pressed w

**Comment by Megabyte918** [comment]
animu c:

**Comment by firelightning13** [comment]
c:

**Comment by Lukkez** [comment]
@Megabyte918 you need to press F12, right click don't work for me, i will make "LIKE" a tutorial here:
- Go to agar.io with Agarplus open.
- Press F12 On Keyboard and go to Console.
- Paste this on console ``connect("ws://127.0.0.1:Port") and press enter; if [c9](https://c9.io) get one like this ``connect("ws://projectname-user.c9users.io)``.
- If you press play and the players is of your server, you connected correctly.

**Comment by Megabyte918** [comment]
@Agarian close?

**Comment by problemsofworld** [comment]
thx
