### ISSUE TITLE
Miniclip wants us to pay 5k coins for private servers..

### ISSUE THREAD

**Issue by ThunderGemios10** [AJS-development/Ogar-unlimited#333]
So recently.. Miniclip has taken over the Agar.io subreddit.
And here's their announcement regarding this.
https://www.reddit.com/r/Agario/comments/4cuev7/important_big_update_and_new_moderators/

Read No.2
and below that number you'll see this small text:

> _Please note, Miniclip has exclusive rights to run servers for this game - others may be contacted by our legal department._

**Comment by Agarian** [comment]
what?? why?

**Comment by Agarian** [comment]
soo u can run a real agario server for urself for 5000 coins??

**Comment by Agarian** [comment]
how?

**Comment by firelightning13** [comment]
They will implementing this in about 7 hrs left

**Comment by Agarian** [comment]
O_O

**Comment by firelightning13** [comment]
Well paying 5k for owning a private server, and 1k for Party Room Passes.........?!??!?!?!??!

### WTF MINICLIP

:neutral_face: :gun:

**Comment by ThunderGemios10** [comment]
@firelightning13 Yup!

**Comment by ItzLevvie** [comment]
Is Miniclip gonna DMCA'ing Ogar? :cry:

not really.

**Comment by ThunderGemios10** [comment]
@ItzLevvie  

> Please note, Miniclip has exclusive rights to run servers for this game - others may be contacted by our legal department.

**Comment by markvillar** [comment]
Could this be another April Fools joke being pulled off by reddit or miniclip? XD

**Comment by Andrews54757** [comment]
either way, i don't care, that means that ogarUL is gone, but not entirely, as they don't have the power to delete every single copy on the planet

**Comment by Agarian** [comment]
I'm worried for ogar unlimited...

**Comment by firelightning13** [comment]
I'm worried both

**Comment by Megabyte918** [comment]
guys im scared

**Comment by ThunderGemios10** [comment]
@markvillar Nope It's real...

**Comment by ItzLevvie** [comment]
It's april fools, now everything is back to normal.

**Comment by firelightning13** [comment]
:'( we got trolled by Miniclip ggwp

**Comment by markvillar** [comment]
Don't trust anyone on April fools day, even news websites tend to spread lies on the day.. lol

**Comment by Megabyte918** [comment]
xd wow i had a feeling...

**Comment by ThunderGemios10** [comment]
@ItzLevvie hahaha xD

**Comment by ItzLevvie** [comment]
https://www.reddit.com/r/Agario/comments/4d1431/ragario_april_fools_fools/

**Comment by ThunderGemios10** [comment]
@ItzLevvie GG, Agar.io Subreddit mods :D

**Comment by Agarian** [comment]
lololol
