### ISSUE TITLE
How to make the server bigger its too small :( please help ;(

### ISSUE THREAD

**Issue by XenoYT** [AJS-development/Ogar-unlimited#334]
the server work and all my friends can follow me but the server is tiny how to make it large ? please help you can get from bottom left to bottom right in 1 Split pls answer

**Comment by XenoYT** [comment]
Help me please

**Comment by Megabyte918** [comment]
1 split? thats weird, have you tried increasing the map size to the vanilla ones?

**Comment by XenoYT** [comment]
Yeah i tryed it and it works thanks :+1:
