### ISSUE TITLE
@andrew how to disable anti bots I disable it still dont let me use bots with my extesion 

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#336]
Please read the faq in advance

Most common questions involve:

Why is there an error "cannot find module"
A: Do npm install after you cd into the repo

**Comment by Agarian** [comment]
u have extension? i need lol
go into gameserver.ini look for:
*serverMaxConnectionsPerIp*
*serverSrambleCoords(set this to 0)*

**Comment by problemsofworld** [comment]
I used freeagarbot.tk v.2.2  it

**Comment by Agarian** [comment]
It what? And isnt the text gone from it?

**Comment by Megabyte918** [comment]
isnt freeagarbots patched? anyway, just disable everything in the anti suicide bot measures and do everything Agarian said and you should be good. Im not sure about davidmanns bots however... i tried those with everything off and it still didnt work (i might have done something wrong, or maybe theres a bug, idk) i would try a different extension just to be safe

**Comment by Lukkez** [comment]
You need mousefilter = **0**
- Mouse filter automatically kicks out players with same mouse.

**Comment by Andrews54757** [comment]
best option = whitelist your ip

**Comment by Lukkez** [comment]
@Andrews54757 no, for some people no, like me, i change ip every 24hours automatic, if youre going to host on own computer you can put ``127.0.0.1``.

**Comment by Lukkez** [comment]
P.S: i use vps
