### ISSUE TITLE
Some of the problems:

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#337]
The food doesn't spawn after being eaten (How to fix that?) 

Minions spawn out of a food cell, don't know if that is in vanilla same as here.

# (Also more realistic names would be pretty cool)

**Comment by NatsuTheGreat** [comment]
Can you explain that issue more?

**Comment by Megabyte918** [comment]
if you want more realistic names, change "botsrealnames" under the bots and minions section of gameserver.ini to 1

**Comment by NatsuTheGreat** [comment]
He wants more and different playernames other than what we have.

**Comment by NatsuTheGreat** [comment]
Some of the names do seem VERY VERY VERY random and like someone just put them down, like first thing that comes into mind.

**Comment by Megabyte918** [comment]
oh... then @elitajmx just find some on agario public servers and put them in there and make a PR 
EZPZ

**Comment by Megabyte918** [comment]
Get rid of the ones you don't like in realisticnames.txt then lol

**Comment by NatsuTheGreat** [comment]
But then we have less XD

**Comment by Megabyte918** [comment]
wont it reuse the same names tho?

**Comment by NatsuTheGreat** [comment]
Nope. It will go to *bot[#]*

**Comment by Megabyte918** [comment]
what?

**Comment by Megabyte918** [comment]
what the heck is a bot[#]

**Comment by NatsuTheGreat** [comment]
like *bot459* *bot758* *bot130* etcetera

**Comment by Megabyte918** [comment]
ive never seen that before lol usually it uses the same name like there would be 2 jumbos on the leaderboard or something maybe that's just on Ogar and not OgarUL?

**Comment by NatsuTheGreat** [comment]
Two jumbo's is because there are two Jumbo's in the list. If you add like 200 bots and then kick them all and re-add them you'll see what I meant. (It does happen on my server maybe it got prevented in this version)

**Comment by Megabyte918** [comment]
so your saying if I were to delete everyname except for one in botnames.txt and added 100 bots it would be just that one botname and then bot[#] up until 100

**Comment by NatsuTheGreat** [comment]
yes pretty much.
it'll be pretty weird if you have all bots named the same thing xD

**Comment by NatsuTheGreat** [comment]
Yep, just tested it on my server and it make all of the *bot[#]* except for the named one. (Again this is my server and I don't know if OgarUL did anything with the name structure)

**Comment by NatsuTheGreat** [comment]
Yep OgarUL has the same thing, one named, and the others *bot[#]*

**Comment by Megabyte918** [comment]
i should add this to my issues list

**Comment by NatsuTheGreat** [comment]
KK. I have to go to bed now. Hopefully see ya on skype tomorrow!

**Comment by markelite** [comment]
That's also one of my problems as well, I had to restart the server in order to get the realistic names back again.. it would be nice if they could be recycled back repeatedly in a loop, so if it runs out of names it goes back from the start again.

**Comment by MichaelLeeHobbs** [comment]
@Megabyte918 yeah add it to the list, this is something I can do latter as it sounds easy.

**Comment by NatsuTheGreat** [comment]
I will try to look at it too sometime, I get insanely bored at time and I'll probably try to fix that.

**Comment by NatsuTheGreat** [comment]
Hey I thought of something, how about instead of *bot675* we use the other botNames, (like *belgium*) those unrealistic names :P

**Comment by NatsuTheGreat** [comment]
I got that to work, allows 210+ bots without *bot[#]*

**Comment by Andrews54757** [comment]
@MichaelLeeHobbs it is really simple, i did it for random names because you dont want a player to be named 'player' when it runs out. all you have to do is remove one line of code in botloader.js. remove the code saying something like this.randomNames.splice. and your done
