### ISSUE TITLE
Small popsplit problem

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#340]
popsplit doesnt work with server minions or playerbots, probably has to do with botupdate

**Comment by Megabyte918** [comment]
Yeah same thing here. sometimes i would split through the bots completely and my cells would not get eaten. but changing the updates to 1 fixed it :D
they should be 1 by default imo, my only concern tho is that im not sure if it increases lag or not (hopefully this is fixed in the upcoming update)

**Comment by Agarian** [comment]
So did i

**Comment by Megabyte918** [comment]
What? changing it to 1 works for me every time... you sure you did it right? xd
lets just hope the smarter AI in the upcoming update fixes this

**Comment by Andrews54757** [comment]
already trying to fix. problem is overriding playertraker.
