### ISSUE TITLE
Dev's we have an in memory DataBase now...

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [AJS-development/Ogar-unlimited#342]
Head over to the chat for some details. Yes, I'm not putting the details here just to make you go over to the chat. :p https://gitter.im/AJS-development/Ogar-unlimited

We also OFFICIALLY have 2 processes running now :D I'm going to try and make it 3 tomorrow by splitting the GeneratorService off of the GameServer.

Now everyone don't get too excited, it's been a long road and while we are crossing the top of the mountain that means we are half way done with a long road still ahead.

**Comment by Agarian** [comment]
2 processes as in processor cores? If so pls dont make it more my processor only has 2 cores (My processor sucks IK)

**Comment by Agarian** [comment]
also the dev requited **way** to many files for NPM

**Comment by MichaelLeeHobbs** [comment]
@Agarian that doesn't make sense. Open a ticket and post dumps of your issues. My typical fullstack website will often require 20-30 dependencies. Also, yes it will now use more than one core but less say we have it split into 8 processes. If you had 8 cores or 4 in the case of a hyperthread core which most are now, it would use all them. On the other hand if you only had 2 then it would run 4 processes on one core and 4 on the other. As a side note, right now you are likely running 100-200ish assuming you are running windows.

**Comment by Agarian** [comment]
Nvm about the npm install issue

**Comment by Andrews54757** [comment]
@MichaelLeeHobbs  . bots no longer work, same with minions

**Comment by Agarian** [comment]
Minions never worked in the dev in the first place.

**Comment by Andrews54757** [comment]
no i fixed minions but now it doesnt work again. ( in my private server)

**Comment by MichaelLeeHobbs** [comment]
@Andrews54757 Lots of stuff is broken atm, we have so much broken encapsulation that it is hard to refactor with out breaking stuff.

**Comment by Andrews54757** [comment]
I dont know why it broke, If i know, i can fix. also I think you didnt break plugins

**Comment by Andrews54757** [comment]
also, it would be nice if you list all the things that are broken so I have an idea and i can fix

**Comment by Andrews54757** [comment]
i fixed minions and bots, it was just the change from gameserver.run to gameserver.running. we should be careful about these things in the future. used up two hours thinking of every possible way to debug it but it is done. Good work!

**Comment by MichaelLeeHobbs** [comment]
@Andrews54757 As to the broken stuff on my branch of dev it is bad, very bad. Trying to move the clients over into the worldModel cause the need for gameMode to be moved over. This in turn basically means that nearly every single file has to be edited. The biggest two issues we have with this project is separations of concerns and broken encapsulation. As an example of separations of concern, in the ejectMass function we have skin, verification, premium. On top of that that function is nearly 200 lines line. In general functions should be limited to 25-50 lines. If they get longer than that then they should be split into separate functions.

Honestly, working on the project has taught me tons about software development. At work we do things a certain way, now I know why. ;)
