### ISSUE TITLE
smaller cells still sometimes have a tendancy to push harder on larger cells

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#343]
so one of my cells were max mass (22,500) and all other cells were small and seemed to be pushing the 22,500 mass cell because it was going faster than a 3,000 mass (minion) cell. And i did not tamper with the cell speeds.

**Comment by firelightning13** [comment]
Umm how small?

**Comment by Agarian** [comment]
they ranged from 12 - 103 mass

**Comment by Andrews54757** [comment]
we know this already. but you also now we have currently bigger fish to fry. lol

**Comment by Megabyte918** [comment]
@Andrews can you fry this fish while your at it?

**Comment by firelightning13** [comment]
I want fish too

BTW you mention the wrong guy xD @Megabyte918

**Comment by Megabyte918** [comment]
woops lol
