### ISSUE TITLE
[QUESTION] GameServer.skinshortcuts - What does it do?

### ISSUE THREAD

**Issue by XtremePlayzCODE** [AJS-development/Ogar-unlimited#344]
How would I use GameServer.skinshortcuts? It's an array, and I'm assuming I can make <k> <kraken> or something like that. How do you actually use it in my case?

**Comment by Agarian** [comment]
it is im guessing how the server determines the text to use as a shortcut for items in *customskins.txt*

**Comment by Agarian** [comment]
like when you see:
*darkspy :http://i.imgur.com/OZdYBGu.png*
in *customskins.txt*, everything before the colon is the skin shortcut.

**Comment by XtremePlayzCODE** [comment]
so if i have K as a kraken skin, if i put <k> in my name it will come out as a kraken?

**Comment by problemsofworld** [comment]
good idea
