### ISSUE TITLE
created a discord chat just for everyone

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#345]
to get to it, join https://discord.gg/0vYaIdmfM1byycva
**make sure to create an account so you dont have to rejoin every time lol**

**Comment by Agarian** [comment]
@Andrews54757 i will transfer the server ownership to you when i can

**Comment by VSabertail** [comment]
ok i joined

**Comment by Agarian** [comment]
@AJS-development/ogar-unlimited-devs

**Comment by Megabyte918** [comment]
sweet I'm in

**Comment by Andrews54757** [comment]
nah, we dont use discord, we use gitter

**Comment by Agarian** [comment]
This should at least be open for others wha may actually want to join this. Lol

**Comment by Andrews54757** [comment]
it is and you log in with github

**Comment by Andrews54757** [comment]
#320

**Comment by Megabyte918** [comment]
what about gittercord ( ͡° ͜ʖ ͡°) ( ͡° ͜ʖ ͡°) ( ͡° ͜ʖ ͡°)
