### ISSUE TITLE
any gameserver txt like real agar

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#346]
Please read the faq in advance

Most common questions involve:

Why is there an error "cannot find module"
A: Do npm install after you cd into the repo

**Comment by Agarian** [comment]
u want gameserver.ini changed to gameserver.txt?

**Comment by Andrews54757** [comment]
it wouldnt matter, in the new update, it would be called config.ini and advconfig.ini in the settings folder

**Comment by problemsofworld** [comment]
I mean settings I wanna make it like real agar like amount of virus and other things

**Comment by Agarian** [comment]
ther virus amount is already vanilla agar

**Comment by Megabyte918** [comment]
do you mean you want the amount of viruses that spawn on the map to be just like the amount in vanilla agario?

**Comment by Megabyte918** [comment]
if so i set virusminamount to 40 and virusmaxamount to 170 (this is with the vanilla map size values) and it worked for me
