### ISSUE TITLE
Slither.io Private server?  

### ISSUE THREAD

**Issue by VSabertail** [AJS-development/Ogar-unlimited#349]
Lets go to slither.io and try to make a private server out of that maby and see how it works

**Comment by VSabertail** [comment]
Lets try this

**Comment by VSabertail** [comment]
And lets see if it works

**Comment by ItzLevvie** [comment]
nah

**Comment by Megabyte918** [comment]
2spoopy

**Comment by VSabertail** [comment]
it could be good

**Comment by VSabertail** [comment]
how do i lable this?

**Comment by Megabyte918** [comment]
they broke slither in their latest update I'm not sure now is the right time...

**Comment by VSabertail** [comment]
how do i lable this lol

**Comment by ItzLevvie** [comment]
Just went through the source code, and it seems like they've not implemented private servers yet.

**Comment by Megabyte918** [comment]
rip lol

**Comment by VSabertail** [comment]
oh :(

**Comment by VSabertail** [comment]
slither.io is good but one day its gonna be infested with bots

**Comment by VSabertail** [comment]
like agar.io

**Comment by Megabyte918** [comment]
people have already developed bots you can see some vids on yt

**Comment by Megabyte918** [comment]
@Agarian close?

**Comment by VSabertail** [comment]
WHAT

**Comment by VSabertail** [comment]
well ok

that sucks

**Comment by Megabyte918** [comment]
haha don't worry m8 it will happen eventually just be p4t13nt

**Comment by Megabyte918** [comment]
@Agarian close?

**Comment by VSabertail** [comment]
well ok

**Comment by Megabyte918** [comment]
I don't think this is the right place to ask for this anyway this is OGAR and the devs are already working hard on the new update but you can ask on their reddit page

**Comment by Agarian** [comment]
3impossible5me

**Comment by NoorAgario** [comment]
Nah ogarUn is just better :/

**Comment by PrinceDark9243** [comment]
Ya Lol XDDDDDDDD :D

**Comment by Agarian** [comment]
This sounds interesting...

**Comment by Megabyte918** [comment]
https://github.com/MasonBurdette/slither-client

**Comment by Zephyr1338** [comment]
Ahem, https://github.com/Zephyr1338/slither.io-bot ;)

**Comment by Agarian** [comment]
bruh

**Comment by firelightning13** [comment]
Bruh

**Comment by ErikParacelsus** [comment]
bruh

**Comment by ItzLevvie** [comment]
bruh

**Comment by firelightning13** [comment]
Oh no, you will ruin the game, lags everywhere

bruh

**Comment by Megabyte918** [comment]
bruh

**Comment by Lukkez** [comment]
bruh

**Comment by hassanila97** [comment]
Bruh

**Comment by Megabyte918** [comment]
lmfao

**Comment by Luka967** [comment]
bruh (?)

**Comment by LegitSoulja** [comment]
Slither.io servers arent even working yet. last time i check about a week agggooo, it wasnt even capable of running correctly.

**Comment by RowanHarley** [comment]
bruh
