### ISSUE TITLE
Official Plugin Library

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#351]
Hello all!

I have created an official plugin library repo. you can find it here

https://github.com/AJS-development/OgarUL-Plugin-Library

for those who are confused, this is for the new update which adds plugin support
In the new update, it will really be ogar UNLIMITED as it allows people to play around without messing with the actual code. If you want to add your own plugins, make a pull request to the repo

Thanks
andrew

**Comment by Agarian** [comment]
awesome!

**Comment by Megabyte918** [comment]
Das pretty neat

**Comment by ErikParacelsus** [comment]
Great works m89!1!!111!

**Comment by Andrews54757** [comment]
![Dev Branch on c9.io](https://cloud.githubusercontent.com/assets/13282284/14303159/4e2ab672-fb76-11e5-8555-54d6e4490c8e.png)

**Comment by Agarian** [comment]
What about it? I cant use it too well on c9 it consumes too much memory thus making the server MORE laggy on  c9.

**Comment by PrinceDark9243** [comment]
COOL!!!

**Comment by Megabyte918** [comment]
yeah its really laggy on c9

**Comment by Agarian** [comment]
Should this be closed?

**Comment by Agarian** [comment]
guess so

**Comment by Megabyte918** [comment]
check your disc
