### ISSUE TITLE
dev branch kickbots command not working

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#352]
using 'kickbots' gives an error

TypeError: Cannot read property 'close' of undefined

also c9.io memory sucks, anything like it with better memory/performance?

plus cells don't squish on borders anymore in the dev AGAIN

**Comment by Andrews54757** [comment]
Do I have to say this over again, DEV IS NOT READY

**Comment by Andrews54757** [comment]
we already know those issues
