### ISSUE TITLE
I have 500 Mass and bot have 250-273 but i cant able to Eat Fix it plz!!!

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#355]
Please read the faq in advance

Most common questions involve:

Why is there an error "cannot find module"
A: Do npm install after you cd into the repo

Can you make minions split on e or r?
A: NO as agario clients do not supposrt those keys. Otherwise, you would need to use another client, and that is illegal

**Comment by VSabertail** [comment]
Thats how it works you have to be %25 bigger than them to eat them

**Comment by VSabertail** [comment]
say if you when 1000 mass and you split for someone who is 500 you cant eat them unless there like 400

**Comment by VSabertail** [comment]
Agar.io would be a lot harder if you could eat someone who's half your size.

**Comment by VSabertail** [comment]
and if its over 250 mass and you could eat them it would make since

**Comment by VSabertail** [comment]
-:lable-update

**Comment by VSabertail** [comment]
-label:Update.

**Comment by VSabertail** [comment]
-lable:update

**Comment by Andrews54757** [comment]
also please make sure to include a description. No description = unreasonable closing of issue

**Comment by PrinceDark9243** [comment]
![untitled](https://cloud.githubusercontent.com/assets/17459204/14358951/2f0ee8f6-fca4-11e5-8ddc-2ad84f725bfa.png)
SO WHAT YOU THINK ABOUT IT!
