### ISSUE TITLE
lable:bug

### ISSUE THREAD

**Issue by VSabertail** [AJS-development/Ogar-unlimited#358]
Please read the faq in advance

Most common questions involve:

Why is there an error "cannot find module"
A: Do npm install after you cd into the repo

Can you make minions split on e or r?
A: NO as agario clients do not supposrt those keys. Otherwise, you would need to use another client, and that is illegal

**Comment by Agarian** [comment]
labels arent added like this.

**Comment by Agarian** [comment]
only devs can do that
