### ISSUE TITLE
Discord chats 

### ISSUE THREAD

**Issue by VSabertail** [AJS-development/Ogar-unlimited#361]
Chat here or go to one of the discord chats here
https://discordapp.com/channels/166198924128813057/166198924128813057
https://discordapp.com/channels/156531998696013824/156531998696013824
# You can also add one of your chats here

**Comment by VSabertail** [comment]
# make sure you don't spam

**Comment by VSabertail** [comment]
-info

**Comment by Andrews54757** [comment]
really

**Comment by VSabertail** [comment]
yes really

**Comment by VSabertail** [comment]
how do i lable this :P

**Comment by VSabertail** [comment]
for crying out loud+

**Comment by Megabyte918** [comment]
y u do dis

**Comment by Megabyte918** [comment]
just use the one in #345 or use gitter chat

**Comment by VSabertail** [comment]
no

**Comment by Andrews54757** [comment]
#162
