### ISSUE TITLE
How to do these things srry in kinda new

### ISSUE THREAD

**Issue by VSabertail** [AJS-development/Ogar-unlimited#363]
## how do you self assign and how do you lable and do all that stuff i need help

**Comment by VSabertail** [comment]
Pls tell me i need help

**Comment by ErikParacelsus** [comment]
Google.....

**Comment by VSabertail** [comment]
google?

**Comment by VSabertail** [comment]
i looked it up but i dont see a check mark where to lable and theres nothing that tells you how to self assign

**Comment by VSabertail** [comment]
PLS I NEED HELP

**Comment by VSabertail** [comment]
**I HAVE BEEN SEARCHING HOW TO DO THESE THING EVER SINCE I GOT HER >:(**

**Comment by Andrews54757** [comment]
only admins like myself can do that

**Comment by VSabertail** [comment]
THEN HOW COME EVERYONE BUT ME CAN DO THAT!!!!

**Comment by Andrews54757** [comment]
becaz they are devs, they are in ajs-dev

**Comment by firelightning13** [comment]
Hey, not everyone can do that
