### ISSUE TITLE
Player Eat Not good

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#364]
![2f0ee8f6-fca4-11e5-8ddc-2ad84f725bfa](https://cloud.githubusercontent.com/assets/17459204/14377009/2b4015dc-fd22-11e5-938c-a58966fc1452.png)
i have 888 mass and Bot have 488 mass but i cant able to eat
In real Agar.io you need to have 25% more Mass to eat you Enemy
i have 100% and My enemy is 51% SO!!!

**Comment by ortex112** [comment]
What is that extension you're using for Agar.io?

**Comment by Andrews54757** [comment]
you can

**Comment by PrinceDark9243** [comment]
Agar Powerups and about Issue it Fixed I just Changed the by an accidently .4 + .2 to 1.4 + .2 then i changed it back and it WorkS sorry for useless issue

**Comment by PrinceDark9243** [comment]
My english is Bad!

**Comment by firelightning13** [comment]
@PrinceDark9243 Ok, good for you then ;)
