### ISSUE TITLE
Missing Parameters?

### ISSUE THREAD

**Issue by CheikoAsami** [AJS-development/Ogar-unlimited#368]
https://gyazo.com/c8592ef71d011e45d84dc4f2f5799bb6

**Comment by Andrews54757** [comment]
its a template plugin

**Comment by CheikoAsami** [comment]
Except it stays there for like 5 to 10 minutes downloading Temp file from github.

**Comment by Andrews54757** [comment]
I thought you were talking about the template plugin, but actually you were talking about the downloading thing. That downloads filetemp.json that is very important to the updator

**Comment by firelightning13** [comment]
```
Loading Config Files...
Loading ./settings/advConfig.ini
Loading ./settings/config.ini
Loading ./settings/override.ini
[Console] Loading plugins
[Console] loaded plugin: example plugin By andrews54757 version 1.0.0
[Console] Didnt load pluginfile template because it was missing parameters
[Downloading] http://raw.githubusercontent.com/AJS-development/Ogar-unlimited/dev/src/files.json to: filesTemp.json
>
```
Waiting.....

**Comment by Agarian** [comment]
that part works fine on c9

**Comment by Agarian** [comment]
also @Andrews54757 you can change the ram amount in c9 but it requires premium and you know what that means...
