### ISSUE TITLE
Cannot find module ./core/ControlServer ???

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#369]
What is this?
i typed npm install
but i dont know what do u mean by ( cd in the repo) what does that mean?

**Comment by Andrews54757** [comment]
it means you have to do this first do `cd` then drag the src folder into the terminal and press enter. then do npm install

**Comment by elitajmx** [comment]
Where do i type cd?? and what is terminal im so sorry but i dont know

**Comment by Andrews54757** [comment]
terminal, or command prompt is the box where you enter commands

**Comment by elitajmx** [comment]
oh so i type cd thats all? then what

**Comment by elitajmx** [comment]
cd doesn't do anything

**Comment by Andrews54757** [comment]
then type npm install

**Comment by elitajmx** [comment]
and then? i typed npm install in the cmd
i tyyped all soooortt of thiingss omg..
this update fked up everything

**Comment by Andrews54757** [comment]
you know why? its probably because you used the update command. you cant use the update command

**Comment by elitajmx** [comment]
what now xD

**Comment by Andrews54757** [comment]
you have to manualy download it. It said so in the world wide message. then you do npm install then run the server

**Comment by elitajmx** [comment]
Ok, i downloaded, opened says cannot find module collections/sorted-map
then i opened node.js cmd and typed npm install
now i start the server again and still says cannot find module?
please tell me step by step

**Comment by elitajmx** [comment]
PLEASE HELP DUDe

**Comment by firelightning13** [comment]
r u in windows?

**Comment by elitajmx** [comment]
no sht

**Comment by Andrews54757** [comment]
you have to cd into the src foleder first

**Comment by elitajmx** [comment]
idk how to do that, im  gonna leave this xD

**Comment by Andrews54757** [comment]
very simple, type `cd` and then drag the folder into the terminal. then press enter

**Comment by elitajmx** [comment]
Oooooo ok now i type npm install

**Comment by elitajmx** [comment]
dangit man i didn't know u could drag folders into cmd's
i finally understand you

**Comment by Andrews54757** [comment]
you should update your files though, I just made it better. Theres less lag and less start time now

**Comment by elitajmx** [comment]
aight
