### ISSUE TITLE
Tested New Ogar Pre-release Bugs

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#371]
Bugs
- ~~Virus Cant get Mass From Ejected Mass~~
- ~~Reset Command dosent Work~~
~~- So Much Lag~~
~~- Server Takes So much Time to Start (Like 10-20 Min)~~

**Comment by Megabyte918** [comment]
rip :(

**Comment by elitajmx** [comment]
what just happened? what did andrew do?

**Comment by PrinceDark9243** [comment]
Dont be Sad i have old Ogar UN !!!YA!!!

**Comment by Andrews54757** [comment]
It doesnt take forever to load for me

**Comment by Andrews54757** [comment]
it only takes like 10 seconds

**Comment by Andrews54757** [comment]
It is probably because you are using a old version of nodejs

**Comment by Andrews54757** [comment]
or your computer is bad

**Comment by NoorAgario** [comment]
Hey @Andrews54757 I am having this prob when trying to install 
npm ERR! registry error parsing json

**Comment by Andrews54757** [comment]
Fixed virus ejection

**Comment by Andrews54757** [comment]
Fixed reset cmd

**Comment by PrinceDark9243** [comment]
I am Using Navidia Gforce GTX GIGABYTE Graphics Card and My Ram is 4GB Newest Node.js
so why it Takes To long!

**Comment by PrinceDark9243** [comment]
@Andrews54757 Why there is [build|failing] [Failed] in Code

**Comment by Andrews54757** [comment]
Fixed massive lag and fixed slow start time

**Comment by elitajmx** [comment]
Where is the gameserver so i can change things?

**Comment by elitajmx** [comment]
OMG THIS IS SO STUPIIID U DELETED THE CONFIG DDE

**Comment by elitajmx** [comment]
nevermidn

**Comment by Agarian** [comment]
@elitajmx lol all configs are now in the **settings** folder in **src**

**Comment by PrinceDark9243** [comment]
Virus ejection does not work!

**Comment by Andrews54757** [comment]
fixed now
