### ISSUE TITLE
Not really an Issue But a question?

### ISSUE THREAD

**Issue by CheikoAsami** [AJS-development/Ogar-unlimited#376]
How do I know if the server is starting up properly?

**Comment by Andrews54757** [comment]
if theres tho ogar unlimited logo and there is no errors

**Comment by CheikoAsami** [comment]
Is this an error? Because it does nothing after it pops this up https://gyazo.com/0740190cd15468f411ab7735cb3298df

**Comment by firelightning13** [comment]
Sometimes it does but sometimes it dont, idk whats goin on...

**Comment by CheikoAsami** [comment]
Anyway to play without it saying that?

**Comment by Andrews54757** [comment]
when that pops up, you have to wait for the ogar ul logo

**Comment by CheikoAsami** [comment]
It does not load The Ogar UI Logo does not load

**Comment by firelightning13** [comment]
Well it takes too long to load :/

Not really 10 seconds

**Comment by Andrews54757** [comment]
Fixed loading time
