### ISSUE TITLE
BUG, ERROR.

### ISSUE THREAD

**Issue by ortex112** [AJS-development/Ogar-unlimited#378]
When I click on Start.bat it makes that.
Loading Config Files...
Loading ./settings/advConfig.ini
Loading ./settings/config.ini
Loading ./settings/override.ini
[Game] highscores.txt not found... Generating new highscores.txt
[Console] Loading plugins
[Console] loaded plugin: example plugin By andrews54757 version 1.0.0
[Console] Didnt load pluginfile template because it was missing parameters
[Downloading] http://raw.githubusercontent.com/AJS-development/Ogar-unlimited/master/src/files.json to: filesTemp.json
>

(is that a bug or error or what...)

**Comment by firelightning13** [comment]
Well, almost everybody have this problem though, waiting the "Downloading" for too long... (not like 10 second k)

@Andrews54757

**Comment by Andrews54757** [comment]
no, the wait isnt for the download, its for starting the database

**Comment by Andrews54757** [comment]
Fixed
