### ISSUE TITLE
Many bugs...

### ISSUE THREAD

**Issue by ortex112** [AJS-development/Ogar-unlimited#379]
There is many bugs like:

1. It lags when I split with my minion and when I split on my minion or throw mass it goes through the minion.
2. When I split at least 1 time it lags my cell goes right, left, up and down.

Please fix that.
Thanks.

**Comment by firelightning13** [comment]
About the minion, Change `minionupdate` to 1 in config.ini

**Comment by ortex112** [comment]
there is still lag after that update please fix it.

**Comment by Andrews54757** [comment]
update again, then tell me your results
