### ISSUE TITLE
compile this to an exe?

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#38]
is that possible? ogarserv has done it with their's

**Comment by ItzLevvie** [comment]
Yes, It's possible.

**Comment by Agarian** [comment]
tell please

**Comment by Andrews54757** [comment]
I dont know how

**Comment by llbraughler** [comment]
Two minutes of searching on Google would have led you to this:

https://github.com/jaredallard/nexe

**Comment by JaraLowell** [comment]
Get JXCore... then read about how to package, compile an js application. :stuck_out_tongue: Down side, it not fully cross os compatible. As in compiled on windows 10 not per say makes it working on 8, 7 or xp... But yah...

**Comment by Andrews54757** [comment]
Too confusing. :)

**Comment by JaraLowell** [comment]
nuuuu!
Lets imagine, jx core was unpacked to folder.. C:\JXCore lets imagine the agario source is in C:\Ogar\src on a Windows machine. to make a nice executable start cmd (or create a bat) with the following lines:

`cd C:\Ogar\src`
`C:\JXCore\jx install ws http fs sys mysql url underscore`
`C:\JXCore\jx package index.js Ogar -native --slim "*.txt,*.md,License,LICENSE,.gitmodules,.npmignore,.travis.yml,.eslintrc"`

and poof you have an executable exe file in the src folder :smile: 
This also like excludes all the files in the executable that within the brackets.

**Comment by Andrews54757** [comment]
what about the gameserver.ini?

**Comment by JaraLowell** [comment]
the executable needs the gameserver.ini, botname.. all the config files at same spot where the executable is.

**Comment by Andrews54757** [comment]
I still dont get it

**Comment by JaraLowell** [comment]
so just make a zip with the executable, the ini files and the bot name file. and some read me files if you have them. See my release as example as what all goes with the exe file.

**Comment by Andrews54757** [comment]
ok

**Comment by JaraLowell** [comment]
or get yuor a$$ on skype and poke me a msg :P

**Comment by Andrews54757** [comment]
I Made it

**Comment by Andrews54757** [comment]
[Here] (https://github.com/AJS-development/Ogar-unlimited/releases)

**Comment by Agarian** [comment]
OMG IT WORKS

**Comment by Agarian** [comment]
how about for x32 windows systems?

**Comment by JaraLowell** [comment]
jxcore64 bit makes 64bit exe, jxcore32 bit makes a 32bit exe. :smile: so to can it make an executable linux file. though the size it becomes is truly not worth it to do so.

**Comment by Agarian** [comment]
pls tell

**Comment by Agarian** [comment]
please

**Comment by JaraLowell** [comment]
same as how you made the 64bit, download JXCore 32bit version, and compile with that. So jx install.. jx package..

**Comment by Agarian** [comment]
how can i tell if it is really x32?

**Comment by JaraLowell** [comment]
run it on laptop and see? :P

**Comment by Agarian** [comment]
it worked :+1:

**Comment by fayizan** [comment]
Someone Please help me with this,I wanna Try JXCore and I m having the latest OgarUL

**Comment by Megabyte918** [comment]
@fayizan do you need an exe too?

**Comment by fayizan** [comment]
yes please for the new agarUL with JXCore

**Comment by Megabyte918** [comment]
I just used this thing on start.bat haha http://www.battoexeconverter.com/

**Comment by fayizan** [comment]
what about JXCore..?

**Comment by firelightning13** [comment]
~~what is that supposed to do~~ nvm lol

**Comment by fayizan** [comment]
Someone please help me compile Ogar UL 16.5.7 with JXCore..!!!
Please Help Me

**Comment by firelightning13** [comment]
You could just download from andrew

**Comment by LegitSoulja** [comment]
Dude use a batch to exe converter. It's not that hard. And what's even the purpose?

**Comment by fayizan** [comment]
I wanna run OgarUL in JXCore  not in Node.js

**Comment by LegitSoulja** [comment]
Jxcore will do the exact same thing *face palm*

**Comment by LegitSoulja** [comment]
Go look online for jxcore help, not here. Nobody isn't going to help you anyways.

**Comment by LegitSoulja** [comment]
Since its unrelavent

**Comment by fayizan** [comment]
Well ok I will google it..Thank you guys

**Comment by Agarian** [comment]
lol
