### ISSUE TITLE
Minion command BUG

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#380]
Everytime i type in the cmd: minion 1 <fox>bot 150
it gives 1 minion.
But if i type: minion 1 150 150
it gives 150 bots??

**Comment by elitajmx** [comment]
Idk it only works if you put minion's names to numbers..

**Comment by elitajmx** [comment]
or either must be the number at first then a name, skins wont work on minions aswell.

**Comment by Agarian** [comment]
but they do

**Comment by Andrews54757** [comment]
its becaz in the new update i changed it to `minion [id] [amount] [name]`

**Comment by PrinceDark9243** [comment]
yes

**Comment by firelightning13** [comment]
Oh make senses now :/
