### ISSUE TITLE
Mass goes trough virus

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#381]
AND THE SPLITTING IS SO BAD WHAT HAAPPEPENENENENENEDF

**Comment by Agarian** [comment]
At this point I'm considering releasing my stable/older version of ogar UL...

**Comment by Andrews54757** [comment]
update and the eject mass works

**Comment by Andrews54757** [comment]
@Agarian Too late, its already here https://github.com/AJS-development/Ogar-unlimited/tree/Original

**Comment by firelightning13** [comment]
Hahaha nice Andrew
