### ISSUE TITLE
Where we are and Where we are Going...

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [AJS-development/Ogar-unlimited#382]
First of Dev is not ready! I am ripping it apart into different processes right now and while it does work it is not stable and it is full of bugs. The only game mode that I have tested is FFA. I am in the process of retro fitting the code to use the in-memory DB.

Please feel free to list FFA bugs you find on dev here. I am only concerned with FFA bugs as these are the core mechanics all the other modes are built on. 

Edit: For the dev's I'm going to move the Config into the DB. This will make it easier to share among the different processes and keep sync'ed.

Note: I am going to keep this thread clean so dont take offense if I delete your post. That means I read it and either it was lacking in value/info or I have updated one of my post to account for it.

**Comment by MichaelLeeHobbs** [comment]
Bug - Food Generator seems to spawn food/viruses too quickly.

**Comment by MichaelLeeHobbs** [comment]
Config is now in the DB but it is not stable yet. I will stabilize it tonight/tomorrow. Once that is done I will then be able to setup the server to use four processes, Generator, DB,  GameServer, and ControlServer. That may or may not get done tomorrow.

**Comment by olivierek6** [comment]
can you fix the throw err; error

**Comment by PrinceDark9243** [comment]
When i start my ogar after some min i just did reset command and WOW Food Spawning Faster and Infinite Food Spawn WTH Help Me or The Ogar Unlimited

**Comment by Agarian** [comment]
@PrinceDark9243 idk man its too buggy

**Comment by PrinceDark9243** [comment]
oh Ok but @Andrews54757 ?

**Comment by MichaelLeeHobbs** [comment]
@PrinceDark9243 are you talking about dev or master branch?

**Comment by Andrews54757** [comment]
master

**Comment by MichaelLeeHobbs** [comment]
@Andrews54757 alright, it will be complete different on dev soon. Right now I'm trying to get the WorldServer stood up. When that is done it will be completely self contain and detached from the GameServer. Thus is will be easy to adjust to how we want.

**Comment by Andrews54757** [comment]
you should also merge some changes in master into dev

**Comment by MichaelLeeHobbs** [comment]
@Andrews54757 yeah... That will be fun.

**Comment by Andrews54757** [comment]
lol, good luck!

**Comment by Megabyte918** [comment]
@MichaelLeeHobbs Hey man, i have a question. I found this old laptop from around 2007-10 (idk) and i'm considering using it to host my server instead of c9 cause c9 is laggy asf. The max amount of ram it can hold is 2GB and I want to get the most out of it. You talked about having a headless linux server that ran yours and could run about 500 bots before, how can i make this laptop like that? Im not going to use this laptop for anything else but running the server because it sucks, so how could i strip it down to use ONLY for my server and get the most out of the ram, and have the least amount of lag possible?

**Comment by MichaelLeeHobbs** [comment]
Note: If you do not know how to use 'sudo', 'su', 'chmod', 'chown', read up on them before you do anything else.

@Megabyte918 first off I'm gonna guess if you do some google you'll find that it can really hold 4g of ram as that is what the CPU is capable of however it is not supported by the maker of the laptop. Now with that said it is critical that if you go this route that you buy ram that is the RIGHT SPEED for the laptop. Do your research before you attempt this!

Optional: Laptop's generally have crappy slow hard-drives, so secondly, get an SSD, a small one will do. 40-120g what every the best bang for the buck is in that range. OUL does not really use the hd so this wont help performance but will decrees boot/startup time.

Note: For step three make sure you have another computer near by that you can google on. :)
Third go down load the install for Centos 7+ and burn it to a cd/dvd. If you more technical capable then you can do this with a usb. When you load Centos make sure you select the server option without a desktop. It's not critical as you can always turn off the desktop latter but not doing so will load software you don't need.

Forth: http://www.tecmint.com/things-to-do-after-minimal-rhel-centos-7-installation/
Specifically do: 2, 3, 9, 22 then 4, 6, 10, 11, 15, those are the critical ones, any things else is optional. Number 9 is critical but 2, 3, must be done first.

Fifth: yum install git   just in case it's not installed

Sixth: yum install node

Seventh : As root - this will solve all you firewall issues and what not. Generally, you should not do this as it is a security risk but as you will ONLY use this machine for OUL it will be ok. In other words don't store stuff on this machine you'd care about getting hacked.

cd /var/www
git clone https://github.com/AJS-development/Ogar-unlimited.git
cd Ogar-unlimited
npm install
npm install -g pm2   <-- This is a tool that will rerun an app if it crashes but you wont have a console
cd src
pm2 index.js  or node index.js

If you have ssh issues let me know, I think at this point I must have experience at least 50% of the possible ssh issues at home or work.

p.s. Wow, that was way more stuff than I planed on. We should turn this into a Linux guide at some point.

**Comment by markvillar** [comment]
@MichaelLeeHobbs @Megabyte918  I really would love to try that myself, but I've always been hesitant, cause wouldn't that pose a great security risk at your home network? I mean not just on the server you're hosting on but your entire home network could be in danger cause you're all technically sharing under the same public IP? So your network will be vulnerable to nasty things like DDoS attacks etc. ? How would you stop these kind of things and keep all other devices on your network secure?

**Comment by MichaelLeeHobbs** [comment]
Nothing you can do will stop a DDOS attack but no one would care to DDOS you. They had much rather steal your identity. As far as running a Linux box at home with an App running as root vs having a windows machine on your home network the windows machine is a greater security risk. Think about how often windows has to put out a security patch and how often people don't keep up on the windows updates. Worse yet are the many other devices in our homes that we don't keep up on the patches for or simple can't be updated. For example I had a router provided by an ISP. After I had learned a few new tricks for a security class I took I went digging. The router had a Linux image that was 4 years old and had never been patched. Sure Linux is good but a 4 year our image has holes.

**Comment by Megabyte918** [comment]
@MichaelLeeHobbs What are the risks of doing this? if i mess up in any of the steps i can still reinstall windows on it right? And how would i port forward my server, will it just be the same as if i was doing it with any other ogar server? I use the non-hamachi method on #121 that uses utorrent, and it works fine for me. i dont know any other methods that dont use hamachi besides that one, so will i be able to use it if i follow your instructions? I just want to know this stuff before i screw anything up

**Comment by markvillar** [comment]
@MichaelLeeHobbs I've just read somewhere that my ISP won't be able to protect me in case some lunatic decided to DDoS my network so I can't take any chance on that, unless there's a way to block all incoming connections immediately when it happens. perhaps port blocking could be a way?

btw is your server open to the public internet or is it some kind of FreeNAS thing for internal use?

> They had much rather steal your identity.
That's one of my greatest concern, hackers getting into my network. I won't be too worried about the server cause it should be able to take care of itself, plus they're easy to rebuild back up in case they get compromised. What I'm more worried about is other devices i.e. my family's phones and computers (Macs and Windows) using the same network,  and they probably don't get security patches installed immediately on those computers and even if they do, I wouldn't think that they're gonna be safe.

@Megabyte918 You can still reinstall windows, however you're probably better off using linux for your server, cause they're more efficient and much easier to manage. You do the port forwarding on your router/modem depending on your network setup, make sure you only open necessary ports and forward them to the right device i.e. your server.

**Comment by firelightning13** [comment]
Wait, can I dual-boot?

**Comment by ItzLevvie** [comment]
yes

**Comment by MichaelLeeHobbs** [comment]
@firelightning13 yes 

@markvillar people dont get DDOS'ed unless they have made someone angry at them and there is no protection from a DDOS. A DDOS can take down a small country, I'm not kidding. If your really concerned about people breaking into your server then make sure you install Centos 7.2.

firewall-cmd --permanent --add-port=<port>/tcp
firewall-cmd --permanent --add-port=<port>/udp

Where <port> is a port you need open of OUL. 

setcap 'cap_net_bind_service=+ep' /usr/bin/node
