### ISSUE TITLE
connection through c9 doesnt even work with new version

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#383]
WebSocket connection to 'ws://ogarserverbeta-agarian.c9users.io/' failed: Error during WebSocket handshake: Unexpected response code: 502

**Comment by MichaelLeeHobbs** [comment]
Fixing 502 errors - general
This problem is due to poor IP communication between back-end computers, possibly including the Web server at the site you are trying to visit. Before analysing this problem, you should clear your browser cache completely.

**Comment by Agarian** [comment]
nope, has to be the server because my older version connects fine.

**Comment by Agarian** [comment]
its working now...
