### ISSUE TITLE
change command not working

### ISSUE THREAD

**Issue by loboere** [AJS-development/Ogar-unlimited#385]

**Comment by Lukkez** [comment]
You can specifically say what says or the error?

**Comment by Agarian** [comment]
like does it say "invalid config value"?

**Comment by Agarian** [comment]
This command is caps sensitive. So if you wanted to change the *foodMaxAmount* config through the console, you can't just type *foodmaxamount*. You would need to type the config EXACTLY as it is in the config files including caps. So the correct usage for the *foodMaxAmount* config would be:

    change *foodMaxAmount* *number*

And so on for all other configs.

**Comment by Agarian** [comment]
please respond

**Comment by loboere** [comment]
[ERROR] Oh my, there seems to be an error with the command chang
[ERROR] Please alert AJS dev with this message:
TypeError: Cannot read property 'indexOf' of undefined
