### ISSUE TITLE
Bug / Error 

### ISSUE THREAD

**Issue by NoorAgario** [AJS-development/Ogar-unlimited#389]
Hey . last time I reported that there is a bug you told me to update Node.JS ! I updated and its still not working ! tell me the specific version I should use
IAM ALSO Having this error 
Installing dependencies, please wait...
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.7.4
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! registry error parsing json
npm WARN optional dep failed, continuing leveldown@1.4.4

> sqlite3@3.1.3 install C:\Users\Anony\Desktop\Ogar-unlimited-master\node_modules\pouchdb\node_modules\websql\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

**Comment by MichaelLeeHobbs** [comment]
Looks like a local network issue to me:

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.

**Comment by NoorAgario** [comment]
Can you send me your pre installed server so I can skip this plz !?
@MichaelLeeHobbs
