### ISSUE TITLE
when u will make the split like real agar it takes forever :( 

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#392]
Please read the FAQ in advance.

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

Can you make minions split by pressing E or R key?
A: NO, as agar.io client doesn't support those keys. Otherwise, you would need to use another client, and that is illegal.

**Comment by Andrews54757** [comment]
Please put a description or it will result in a unreasonable close
