### ISSUE TITLE
bug/question

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#393]
i have noticed the camera/viewbox on ogar is more focused on smaller cells that larger ones. In Agar.io, the camera/viewbox would be more focused on the larger cells. Is this a client or server issue?

**Also pcmd command gives this error:**
TypeError: gameServer.execommand is not a function
    at Timeout._repeat (C:\Users\owner\Downloads\Ogar-unlimited-master\src\modul
es\commands\pcmd.js:28:16)
    at Timeout.wrapper [as _onTimeout] (timers.js:408:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

I'm guessing there is supposed to be a period in-between exe and command to look like:
**gameServer.exe.command**
i guess but idk

**Comment by Agarian** [comment]
@AJS-development/ogar-unlimited-devs **SOME BUGS I WANT TO MENTION:**
-Kickbots command seems to select a random amount of bots to kick
-PCMD command gives an error

**Comment by Andrews54757** [comment]
i never noticed the camera, (mabye just mess with the camera view base in config?)

**Comment by Agarian** [comment]
Thats not at all what i meant

**Comment by Agarian** [comment]
Say you've been split by a virus, in regular agar, the screen would be focused more on the larger cells but in ogar, the opposite happens.
