### ISSUE TITLE
The new update

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#394]
Can any devs explain to me what exactly this new update is and what its for? What are the new features and how do i use them? Which suggestions were added? Were any bugs fixed from #268? Im so confused theres nothing in newfeatures.md and idk what has been updated and what to cross off the suggestions or bug lists

**Comment by Andrews54757** [comment]
Too many features (many you wouldnt notice) were added. main features

1. Improved preformance as we cleaned up a lot of code.(now, I can run 500 bots and be fine)
2. organised and moved configs
3. improved updater
4. plugins. See official library here #351 
5. other stuff im too lazy to tell. (mostely small things that are just for convenience when you play such as typing /random for your name it will give you a random name)

**Comment by Andrews54757** [comment]
dont forget many bug fixes. but also new bugs were introduced as well.

**Comment by Megabyte918** [comment]
do you know which bugs were fixed?
