### ISSUE TITLE
Bug Report: Moving Virus Spawn Crash

### ISSUE THREAD

**Issue by khuckins** [AJS-development/Ogar-unlimited#396]
I just started up with a fresh server built from master, cloned today ~8:30.
NPM version is v5.10.1(Latest Stable as of writing)
Gamemode is 8 (Experimental v2)

A crash begins when a moving virus is spawned.  

> TypeError: Cannot read property 'push' of undefined
>     at Mode.Experimental2.spawnMovingVirus (C:\...\Ogar-unlimited\src\gamemodes\Experimental v2.js:156:27)
>     at Mode.Experimental2.onTick (C:\...\Ogar-unlimited\src\gamemodes\Experimental v2.js:247:10)
>     at GameServer.gameModeTick (C:\...\Ogar-unlimited\src\core\GameServer.js:1483:21)
>     at GameServer.mainLoop (C:\...\Ogar-unlimited\src\core\GameServer.js:1339:15)
>     at tryOnTimeout (timers.js:224:11)
>     at Timer.listOnTimeout (timers.js:198:5)

**src/gamemodes/Experimental v2.js:**
```
Experimental2.prototype.spawnMovingVirus = function (gameServer) {
  // Checks if there are enough moving viruses on the map
  if (this.movingVirusCount < this.movingVirusMinAmount) {
    // Spawns a mother cell
    var pos = gameServer.getRandomPosition();

    // Check for players
    let nodesPlayer = gameServer.getPlayerNodes();
    for (var i = 0; i < nodesPlayer.length; i++) {
      ...
    // Spawn if no cells are colliding
    var m = new MovingVirus(gameServer.getWorld().getNextNodeId(),
      null,
      pos,
      this.movingVirusMass + Math.floor(50 * Math.random())
    );
    gameServer.movingNodes.push(m);
    gameServer.addNode(m);
  }
};
```
m is definitely defined here, so I looked a bit more at what code was changed.  I noticed that Sticky Cells have those same last couple lines(movingNodes.push(m); and addNode(m), with the movingNodes.push commented out.  I believe this is more because sticky cells don't move on their own, though.

**Comment by Andrews54757** [comment]
i will look at it.

**Comment by Andrews54757** [comment]
think i fixed
