### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#4]
When i try to get mass by virus i teleport to 0, 0 and the game make me killed (Show the stats)

**Comment by Andrews54757** [comment]
It is probably because you used op wrong. You had 2 'c's and you pressed space which shoots out antimatter. This minuses 100 mass from the consumer. The game is made  so anyone with negative mass are sent to the corner. (Because they are invalid) to gain mass, you need to have one c and press w

**Comment by Lukkez** [comment]
This happen with normal virus
And i'm not playing with op

**Comment by Lukkez** [comment]
EDIT: This happen with 22500 auto split and the virus

**Comment by Andrews54757** [comment]
Do you experience the same problem in regular agar.io

**Comment by Andrews54757** [comment]
I mean ogar
