### ISSUE TITLE
Still need 1 skin update

### ISSUE THREAD

**Issue by VSabertail** [AJS-development/Ogar-unlimited#401]
Please read the FAQ in advance.

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

Can you make minions split by pressing E or R key?
A: NO, as agar.io client doesn't support those keys. Otherwise, you would need to use another client, and that is illegal.

**Comment by VSabertail** [comment]
need Statue skin update

**Comment by Andrews54757** [comment]
?

**Comment by Agarian** [comment]
wtf does that mean?

**Comment by Megabyte918** [comment]
he wants the "statue" skin in agario
