### ISSUE TITLE
Split Does Not Same As Old Ogar But Popsplit Work Perfect and Some More!

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#402]
When i Split it Just Push My back Cell New Cell Does Go 20% Front ~~and When i Popsplit Someone My Largest Cell Go More Far than Real Agar~~.(SORRY I NOTICE THAT POPSPLIT IS GOOD LIKE REAL AGAR THANKS! @Andrews54757 And Other Dev's)
- **(Bug)** ~~When i did `reset` Command Food and Virus Spawns Instantly and Infinite Food Spawn~~ ~~WTF Very laggy.(Sometimes It Crashed the Server)~~ **(FIXED)**
- **(Bug)** doing `minion [ID]` Only Remove Some minion Some minions Are Ghost they cant able to eat anything but you can eat him when you have min mass.(When you eat them they never Respawn)
- **(Bug)** in Old Ogar Un i added 100 bot (Player Bots) it does not lag but In this New Ogar Un i added 20 Bot It lags.
- **(Bug)** Player Bot have two(2) Cells or More bot cell one go to other bot and other Cell go to other Bot.
- **(Error)** There are Skins in Team Mode In real Agar.io Skin are Not Allowed in Teams Mode its Annoying but When i set `skin = 0` its just give me this nick
`<kraken>Lvl 100` on Bots. I think you Dev's Need to add `teamSkins = 0 // Allow you to use Skin in Teams Mode` (Kinda Annoying)
- **(Change In New)** Spliting Changed in `v16.0.1` has Good Spliting but Its Just Push My back Cell.but in `v16.0.5` Its Not Good But OK in `v16.0.1` Spliting is Best `Popsplit Work Rate : 95%` GOOD but in `v16.0.5` `Work Rate : 45%` That Weird!

Note:For Dev(s) Please Don't Close this Issue Without My Permission Please i know you have power to close any issue but Please.Thank!
----------------------------------------------SORRY FOR MY BAD ENGLISH--------------------------------------------

**Comment by Megabyte918** [comment]
For the splitting, the new splitspeed works when your under around 12k-ish mass, then anything over that pushes you backward ALOT. It makes for good splitrunning, but when you have the splitspeed set to the default (130) you split a bit TOO fast when over 12k mass, so its a win one/lose one situation either way. In vanilla its supposed to be fast when your small, then it kinda slows down as you get bigger which allows for "slo-mo splitrunning" like zt, if you've ever seen their videos. Im currently trying to find a comprimise and will pr it when i do.

**Comment by PrinceDark9243** [comment]
Ik but it is Not Good As Real Agar I think its Take Forever to make Ogar Un like Real Agar I THINK ONLY! And About Popsplit You can Try You will Push To far From Range of Popsplit

**Comment by firelightning13** [comment]
About the physics thingy, there's always something wrong when I'm playing around a lot, but I DON'T EXACTLY KNOW WHAT IT IS and I can't even figure it out how to explain this. Ok, first!,

- When big splits, sometimes they are still "teleport" after collision resets **?**
- When the server lags, sometimes split can be f'ed up **?**
- Its hard to control you big cell when you have small cell around you
- Still, when using config splitSpeed 100, it's still fast, and very short range when you are small **?**
- When a cell hit by a virus, the small cell should be popped "gracefully"(if you know what I mean), NOT "rushingly(not even in dictionary)" going back to cursor's position.

**Comment by PrinceDark9243** [comment]
YES EXACTLY!!!
Thanks! @firelightning13 For Supporting Me (Issues)

**Comment by PrinceDark9243** [comment]
When i Double Split like This `(1)(2)(3)(4)` These Are Cell By Number. after Collision reset its just did this `(1) (3) (4) (2)` Its Just Push (First Second Cell to Front. You Can Test it by Eating a Cell With Double Split but Wait you need To close to Cell to See Like this
![asd](https://cloud.githubusercontent.com/assets/17459204/14520969/02676d40-01dc-11e6-9c98-a28ac1cf8358.png)
After When i Split its Just did this
![dsa](https://cloud.githubusercontent.com/assets/17459204/14520979/0eb10fe8-01dc-11e6-8e9f-34f5023b03fc.png)

**Comment by firelightning13** [comment]
@PrinceDark9243 
> - When big splits, sometimes they are still "teleport" after collision resets

**Comment by PrinceDark9243** [comment]
Yes Exactly! Thanks! @firelightning13

**Comment by PrinceDark9243** [comment]
Its Kinda Crazy HAHAHAHAHA But Wait did You Know That illuminati Near You. Scaning illuminati.
Its Kinda Crazy **(`H`A`H`A`H`A`H`A`H`A)** But Wait did You Know (A=illuminati) HAHAHAHAHHA OMG!!! JK :P

**Comment by Agarian** [comment]
wtf

**Comment by olivierek6** [comment]
did anyone told you that to popsplit you doublesplit not triplesplit

**Comment by PrinceDark9243** [comment]
no i dont know!

**Comment by Megabyte918** [comment]
thats what its supposed to do, in vanilla agario your front two cells switch order when doublesplitting, which allows you to still be able to eat someone when you doublesplit at them over a virus and switch your first two cells so that it looks like this after doublesplitting: ooOo

**Comment by PrinceDark9243** [comment]
Yes But Sometime when i popsplit someone its just do this `oOo`

**Comment by Megabyte918** [comment]
oh okay, if you want to get rid of the cell switching look for `var overlap = (collisionDist - dist) * mult;` in playercell.js and replace it with this: `var overlap = collisionDist - dist;` 
and replace 
`x1 = x1 + (move * Math.sin(newAngle)) >> 0; y1 = y1 + (move * Math.cos(newAngle)) >> 0;` 
with this: 
`xd += (move * Math.sin(newAngle));
                    yd += (move * Math.cos(newAngle));`

**Comment by Megabyte918** [comment]
should i make a config?

**Comment by PrinceDark9243** [comment]
I cant able to find these two line in Playercell.js

**Comment by Megabyte918** [comment]
Ctrl + F or Command + F and search for it

**Comment by PrinceDark9243** [comment]
Yes I did when i search its say Not Found! Please Make A Config on Playercell.js

**Comment by PrinceDark9243** [comment]
full edited File

**Comment by Megabyte918** [comment]
wait do you want me to make a config or send you the file or both? im confused. and i cant make a config in playercell it'll have to be in config.ini

**Comment by Agarian** [comment]
He wants the file on playercell.js that you have

**Comment by PrinceDark9243** [comment]
yes @Agarian is right!

**Comment by Megabyte918** [comment]
[Here ya go,](https://github.com/AJS-development/Ogar-unlimited/files/222535/PlayerCell.txt) you'll have to change it from a .txt file to a .js file cause apparently github doesnt support those. Ill make a config for it in my next pr

**Comment by PrinceDark9243** [comment]
ok thanks i am gonna try it!

**Comment by PrinceDark9243** [comment]
Work Thanks! @Andrews54757 need to change it to your file Great Work @Megabyte918 !

**Comment by NatsuTheGreat** [comment]
That was my file Megabyte sent out, I sent him my files. :/

**Comment by Andrews54757** [comment]
Doesnt matter, it wasnt really a bug, it was intended

**Comment by Andrews54757** [comment]
so i will not update my files

**Comment by Megabyte918** [comment]
@NatsuTheGreat That was my version from my workspace, you can tell by the onConsume function its different from yours because i've been experimenting with it. Compare it with yours

**Comment by Andrews54757** [comment]
so should i or should i not update my files

**Comment by NatsuTheGreat** [comment]
not.

**Comment by VSabertail** [comment]
@PrinceDark9243  YOUR GONNA TRY WHAT TELL ME WHAT FILE YOU HAVE

**Comment by VSabertail** [comment]
#441

**Comment by Agarian** [comment]
@Megabyte918 
> would you like me to add a pushback config?

that would be cool actually lol

**Comment by Megabyte918** [comment]
Okay, so I did some research and I noticed that the splitting in regular agar has SLIGHTLY (a very miniscule amount) less pushback than ogar and ogarul, most people wouldn't notice the difference because its so small, so I wont change anything in that regard because its perfect the way it is. BUT I recently discovered something, @lotfis the reason why your cells were pushing back more is because of lag, for some reason, as lag increases the split speed decreases and the amount of pushback increases. (w's also slow down and stutter as they slide too). I don't know WHY the hell this happens, or even where to begin to fix it, Ogar also has the same problem. So as long as your server isn't lagging or slow, the amount of pushback should be perfect when splitting. @AJS-development/ogar-unlimited-devs can anyone explain to me why this happens? i'm actually curious

**Comment by Megabyte918** [comment]
@lotfis @Agarian  if its REALLY that bad then I can try to fix it when private servers are fixed but I'm going to need help from one of the @AJS-development/ogar-unlimited-devs to point me in the right direction because I don't even know where to begin to fix this xD

**Comment by Agarian** [comment]
i dont think there is a fix. i had actually used the old code before you implemented pushback and it STILL pushed back and its really annoying

**Comment by LegitSoulja** [comment]
@Agarian @Megabyte918 Yea, when private servers are back to working this can be fixed.

**Comment by Agarian** [comment]
see thsts the thing i dont think private servers will be able to be fixed.

**Comment by NatsuTheGreat** [comment]
They removed the connect("") command, dang it.

**Comment by Agarian** [comment]
cigar works but it's server sucks

**Comment by NatsuTheGreat** [comment]
Could we merge in the Agario-Dump files into the Cigar files? Would be interesting.

**Comment by Agarian** [comment]
that doesnt fix the horrible server physics of ogar in cigar

**Comment by NatsuTheGreat** [comment]
Well by physics you mean the splitting etcetera right? We could try to find the physics portion of the agario-dump and merge it in.

**Comment by Agarian** [comment]
its NOT THE CLIENT!!

**Comment by NatsuTheGreat** [comment]
FFS the agar.io dump files are not only client files.

**Comment by Agarian** [comment]
ur saying that client has the ogar server in it like cigar?

**Comment by NatsuTheGreat** [comment]
Oh my god never mind, you're confusing me.

**Comment by LegitSoulja** [comment]
@Agarian @NatsuTheGreat I'll see if I can update agar graphics with cigar.. You sure cigar works?

**Comment by Agarian** [comment]
so look, cigar has an ogar server built into it

**Comment by LegitSoulja** [comment]
@Agarian But does OgarUL works with cigar? I havent tested

**Comment by Agarian** [comment]
but the physics on it are OUTDATED by  miles

**Comment by NatsuTheGreat** [comment]
@LegitSoulja it's fine, just focus on what you were focusing on.

**Comment by Agarian** [comment]
and i tried but i couldnt get it to work

**Comment by LegitSoulja** [comment]
You just cant replace the files you knoww...

**Comment by Agarian** [comment]
cigar has modules that root it to the masterserver etc and its confusing

**Comment by Agarian** [comment]
idk how to make it work with ogarUL

**Comment by Agarian** [comment]
you could try maybe?

**Comment by LegitSoulja** [comment]
@NatsuTheGreat I would try if cigar works with OgarUL.. If it doesnt, then cigar and cigar client is custom and only works for eachother.

**Comment by LegitSoulja** [comment]
But ill see whats what, because I have never tried cigar.

**Comment by NatsuTheGreat** [comment]
http://agar.io/?ip=151.236.222.67:9999 You have seen the news on this server right? It's amazing! It has it's own facebook system. This server is by miniclip, most likely miniclip is doing something.

**Comment by Agarian** [comment]
thats an actual agar.io server?

**Comment by NatsuTheGreat** [comment]
It's by miniclip

**Comment by LegitSoulja** [comment]
Few things to document
Skins :: https://configs-web.agario.miniclippt.com/live/v4/80/checksums/_manifestBase.json
More Skins :: Offsets :: Md_5 keys : https://configs-web.agario.miniclippt.com/live/v4/80/GameConfiguration.json

Another server : http://agar.io/?ip=151.80.96.53:1514

**Comment by NatsuTheGreat** [comment]
How do you find this xD

**Comment by Megabyte918** [comment]
@NatsuTheGreat @LegitSoulja those servers are by miniclip themselves? completely vanilla no editing what so ever? if so... maybe we could learn a few things about their physics and implement it into ogarul once private servers are fixed :) this is perfect exactly what we need as a reference point

**Comment by LegitSoulja** [comment]
@Megabyte918 learn physics.. Right.. Well I could, but it wont be until late this week. I will be gone until wednesday.

**Comment by NatsuTheGreat** [comment]
We are using javascript and they use c++, so we need some people who know c++.

**Comment by Megabyte918** [comment]
@everyone anyone know c++? lol
