### ISSUE TITLE
150 Bots and 200 players = MASSIVE LAG

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#403]
150 Bots and 200 players = MASSIVE LAG

1 Player(me) and 0 bots = Lag

???

**Comment by Lukkez** [comment]
lol

**Comment by Lukkez** [comment]
Maybe the configs, maybe the pc/vps

**Comment by elitajmx** [comment]
so what do i need to FIX heer???

**Comment by MichaelLeeHobbs** [comment]
@elitajmx I have not optimized players at all. The player code path is very complex compared to bots. This is something that will be worked on in the near future but for now I doubt my dev machine could handle 100 players.
