### ISSUE TITLE
Anti - Teaming // Need to fix.

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#405]
If you have Teaming set to 0 and after you eat someone or more pieces of someone you will get punished by Anti - Teaming.

**Comment by Andrews54757** [comment]
make sure to use config.js not gameserver.ini

**Comment by elitajmx** [comment]
i did :+1:

**Comment by Agarian** [comment]
config.js? why so many configs???

**Comment by Andrews54757** [comment]
make sure teaming is set to 1

**Comment by firelightning13** [comment]
No, he means when he eating someone he actually get anti-teaming penalty, instead of hit by a virus or prssing too much w
