### ISSUE TITLE
I Need Help !

### ISSUE THREAD

**Issue by NoorAgario** [AJS-development/Ogar-unlimited#410]
Guys when I'm installing decencies it tells me that its installed correctly but when I try to open the server (latest version ) it gives me this error
C:\Users\Anony\Desktop\Ogar-unlimited-master\src\index.js:3
const Readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

While I'm using the latest Node.Js version 5.1
Help Me I cant play on the new OgarUn  :(

**Comment by XenoYT** [comment]
Look Delete it and redownload it from this website

**Comment by NoorAgario** [comment]
I Already done that @XenoYT  can you send me your pre-installed server please ?!

**Comment by Andrews54757** [comment]
you need to update your nodejs

**Comment by NoorAgario** [comment]
yes I did @Andrews54757 my version is 5.10.1  >.<

**Comment by Andrews54757** [comment]
try the LTS version

**Comment by NoorAgario** [comment]
Can you Send me your Pre-installed server Please @Andrews54757

**Comment by Andrews54757** [comment]
there is no pre installed server
