### ISSUE TITLE
Plugin Request!

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#412]
I want a plugin where players can login and Register like `Login System Plugin for Mincraft` for Register Player need to type this Nick formation: `R/USERNAME:PASSWORD`**Nick Need Number after there Usename Ex:`R/Pd9:Pass123` after that Player has been Register. Player will spawn with this Nick `Register Successful! Now Type You Nick(Press W to die)` After When Nick Entered Player Setting Saved In PlayerState.txt Like customskins.txt formation is `USERNAME:PASSWORD:NICK:SKIN:LEVEL:XP` like `Pd9:Pass123:Killer:shark:30:34321`
You can Create a Config for this Plugin `loginSystem = 1` and Other Things You can Add.Thanks!!!

**Comment by Agarian** [comment]
where would they login?

**Comment by NoorAgario** [comment]
yes It would be awesome

**Comment by PrinceDark9243** [comment]
they will Login by puting username and Password in this Form `L/USERNAME:PASSWORD` LIKE
`L/Pd9:Pass123`. Player Can Change Skin By doing this after Login like this `skin/` putting this in your nick after login. Press w to Go Forward press q to go back to choose player Skin Will be Change when you Press W Go Forward Press Q to go back skin Player Skins Will be Unlocked by Level 3000 Xp added to Amount of Max Player Xp When he/She Level up Player get Xp by eating 1 Pellte=1 XP by eating a player will get 2 XP eating Virus will get 1 and default by all is 1 XP OK? Can anyone Can Create this Plugin Its Awsome!! THANKS!!! @Agarian For Asking!!!

**Comment by NoorAgario** [comment]
if @Andrews54757  could do this for us :/

**Comment by Andrews54757** [comment]
No, it is not a good idea as agar only allows 15 chars

**Comment by PrinceDark9243** [comment]
Oh (-_-) OK.

**Comment by PrinceDark9243** [comment]
but in nbk.io its Support this Plugin

**Comment by firelightning13** [comment]
@PrinceDark9243 They are using custom client, not agar.io client. Thus, we don't support it

**Comment by Andrews54757** [comment]
actually, i think I can pull it off, but the format is going to be different. I will do it when I have time

**Comment by Andrews54757** [comment]
I made it and I am going to make the account rewards plugin too so you can make some peoples accounts allways op and stuff . the auth plugin is here https://github.com/AJS-development/OgarUL-Plugin-Library

**Comment by MichaelLeeHobbs** [comment]
@Andrews54757 I have a website I built a while back to manage Ogar that I will eventually convert over to OUL. It will easily handle the stuff in this thread and more. It can support login's for G+, FB, twitter, as well as it's own account system. However, this is way down the road. Months away.
