### ISSUE TITLE
Hide Command Dosent Work

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#413]
hide Command Not Working My Friend Can See Me How?

**Comment by Agarian** [comment]
Same

**Comment by PrinceDark9243** [comment]
@Andrews54757 ?

**Comment by PrinceDark9243** [comment]
and Pcmd Dosent work too!!!

**Comment by Agarian** [comment]
also same -_-

**Comment by Megabyte918** [comment]
& killall

**Comment by Agarian** [comment]
this was the worst update EVER

**Comment by Andrews54757** [comment]
I thought i fixed hide and killall

**Comment by PrinceDark9243** [comment]
@Andrews54757 Fix It Plz its Breaking the Ogar Unlimited Server WHY ???????????

**Comment by Andrews54757** [comment]
try updating as i tweeked both

**Comment by PrinceDark9243** [comment]
OK

**Comment by Agarian** [comment]
killall seems to select a random amount of players

**Comment by MichaelLeeHobbs** [comment]
@Agarian No, it is a terrible software practice and makes maintaining the software hard.

**Comment by Andrews54757** [comment]
@MichaelLeeHobbs Can you fix killall and reset? (reset makes food spawn alot) I cant seem to find out what is going on

**Comment by MichaelLeeHobbs** [comment]
@Andrews54757 the issue is not with killall it is with bots. If you add 500 bots it will kill every other bot. However if you add 5 players and run kill all they all die. Something about the bots is not right.

**Comment by MichaelLeeHobbs** [comment]
@Andrews54757 killall was a concurrent modification error. That is the danger in iterating over an array or list and modifying it as you go.

**Comment by MichaelLeeHobbs** [comment]
@Andrews54757 the food spawn issue is the same issue I had on dev. Let me see if I can backport the changes I made on dev to master.
