### ISSUE TITLE
Skin changer plugin

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#414]
Me and my friends want to remember old times using Skin Changer, make a thing like if type ``<auto>Name``, ``<random>Name``, ``<changer>Name`` like ``<random>Lukkez``, and the skin will change to the skins who have on a changerSkins.txt like customSkins.txt, and have a delay on config.ini to set the ms to change like skinChanger = 200.
What file should be:

//Skins
kraken
mammoth
spy
usa

**Comment by Agarian** [comment]
i had that suggestion in #356

**Comment by Andrews54757** [comment]
Will implement this when I have time

**Comment by Andrews54757** [comment]
done. Do /random for skin and it will give you random. (note: you must have randomSkins.txt file from github)

**Comment by NoorAgario** [comment]
@Andrews54757 
 I wanna Unammed cells to have random names and skins . or just random skins whithout setting a command ? is that possible 
so if a player don't set a skin he ill be given a random skin ?!

**Comment by ortex112** [comment]
how to have random skins i dont know what to do...

**Comment by Agarian** [comment]
it doesnt work tho

**Comment by Andrews54757** [comment]
no, you have to do `</random> name`

**Comment by Agarian** [comment]
mind trying this? its an older version of ogar but with some of the new features (except plugins) http://agar.io/?ip=ogarservercloned2-agarian.c9users.io

**Comment by Andrews54757** [comment]
Fixed (it was a small error) you may need to redownload skins.txt and botnames.txt as well

**Comment by Agarian** [comment]
can someonw try http://agar.io/?ip=ogarservercloned2-agarian.c9users.io ? its almost like no one even cares about #190

**Comment by Andrews54757** [comment]
lol, but now i need to work on my auth rewards plugin

**Comment by Agarian** [comment]
ok then anyone try http://agar.io/?ip=ogarservercloned2-agarian.c9users.io
