### ISSUE TITLE
Some Skins Dosent Work!

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#418]
T-Rex ,Kraken and Facepalm Skin Dosent Work before they are Working Tell me Solution.

**Comment by PrinceDark9243** [comment]
and Sad Skin!

**Comment by Andrews54757** [comment]
that I dont know as client side skins are managed by agario

**Comment by Agarian** [comment]
t-rex has to be t_rex and the skin names CANNOT have capital letters, only custom skins!

**Comment by PrinceDark9243** [comment]
yes i know aboute T_rex Skin. lol
