### ISSUE TITLE
SO MUCH LAGG

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#420]
ALL I DO IS 
addbot 70
AND THERE IS SO MUCH FREEZE LAGG

**Comment by Megabyte918** [comment]
I can only run 25 :(

**Comment by Andrews54757** [comment]
use a better computer. In the update, we increased preformance but to have that increase, you need more cpu

**Comment by Agarian** [comment]
some ppl cant afford a new computer! jesus

**Comment by Andrews54757** [comment]
I have a really old windows 7 computer that is literally breaking apart but it works FINE.

**Comment by Agarian** [comment]
breaking apart? lol
i was thinking of upgrading to windows 10 but i found that PC minecraft (versions 1.7, 1.8, 1.9 etc) wouldn't work on win 10. so I'm still running win 7 home premium :D

**Comment by Andrews54757** [comment]
My comp is a hp computer that originaly ran on windows vista with a intel core (and it is missing like 5 screws)

**Comment by Agarian** [comment]
i saw a school computer one that simply couldn't even boot because some one wiped the hard drive! I kept getting "Invalid system disk, replace the disk and then press any key." 
I swear it was fucked up that bad

**Comment by NoorAgario** [comment]
Guys I have a good i7 8 cores Laptop , can I use all the cpu / gpu (4gb ram) and my  8 gigs ram to run el server 
so I could use all my pc power I hate lag and I can run gtav with max setting rly well , but agario lag ?!

**Comment by Agarian** [comment]
idfk

**Comment by Megabyte918** [comment]
So this makes c9 useless?

**Comment by Agarian** [comment]
yes.

**Comment by Andrews54757** [comment]
no, my c9 server runs really well.

**Comment by Megabyte918** [comment]
Before the big update i was able to run 40 bots at most NO problem at all, but after it, now i can only run like 20, and even then the server STILL slows down and freezes all the time. even with a fresh version on ogarul downloaded i tried and got the same results

**Comment by Andrews54757** [comment]
Example: http://agar.io/?ip=ogar-unlimited-andrews54757.c9users.io

**Comment by Andrews54757** [comment]
added 100 bots

**Comment by Andrews54757** [comment]
there is a bit of lag but compared to before, its huge improvement

**Comment by Megabyte918** [comment]
its still laggy but not AS laggy
why is it that everybody's version on ogarul lags but yours ;-;

**Comment by Megabyte918** [comment]
how much ram do u have dedicated to it? ive been using the 512mb by default on c9

**Comment by Andrews54757** [comment]
1gb ram (btw its free)

**Comment by Megabyte918** [comment]
doesnt it let you only use like 2 servers off of 1gb then if you delete it the rest are 512mb?

**Comment by Andrews54757** [comment]
yep

**Comment by Megabyte918** [comment]
but shouldnt i be able to run more than 20 bots off of 512mb of ram that seems a bit demanding dont you think?

**Comment by Andrews54757** [comment]
Ok, I will explain. What we did was actually simple: We increased preformance by alot, but in return, it does more proccesses so it needs more cpu. This is good if you have a good computer but bad if you have a bad one

**Comment by Megabyte918** [comment]
So im just stuck with 20 bots until i buy a better computer -.-

**Comment by Megabyte918** [comment]
wasnt the point of making it less laggy was to make it so you WONT need more cpu and processes to run the server, not that you WILL and people with a non-high-end computer are just screwed and cant do anything about it

**Comment by Andrews54757** [comment]
no, why dont you read the dev discussion?

**Comment by Megabyte918** [comment]
im done nevermind

**Comment by MichaelLeeHobbs** [comment]
My servers are a pair of Dell 1505e. I have removed the screens, cd-roms, and wifi cards. The each have the max of 4g ram and a 40g ssd. But the most important upgrade I did to them was load Linux with out a desktop. They can each handle 3 OUL's each running a 1000 bots. This is the current dev version which up's the bots from about 500 to 1000.

**Comment by PrinceDark9243** [comment]
WOW!!!!!!!

**Comment by elitajmx** [comment]
So basically, my computer was 1800$ and it's bad?

**Comment by elitajmx** [comment]
I'm soon about to buy a 2500$ gaming pc and that won't work either yeah.

**Comment by Andrews54757** [comment]
No, but you probably limited how much cpu nodejs can run on

**Comment by elitajmx** [comment]
what about splitting tho? it's fkd up

**Comment by elitajmx** [comment]
brooo the splitting.... only because of splitting i fucked up 56k mass lol

**Comment by Andrews54757** [comment]
no cussing

**Comment by Andrews54757** [comment]
the splitting is fine

**Comment by elitajmx** [comment]
no its not.. in normal agario i split and it splits me alot in the front but in ogar i split and it like... splits me back or how i say that.

**Comment by firelightning13** [comment]
Well, lag does affect the splitting :/

**Comment by Agarian** [comment]
Exactly, sometimes ,even on old ogar UL, the cells have a slight teleport effect when enduring lag

**Comment by Megabyte918** [comment]
@elitajmx did you update to the latest version? splitting should be fixed and teleporting should be reduced by alot

**Comment by Agarian** [comment]
im talking about cell movement during large lag

**Comment by elitajmx** [comment]
YEEESS THATS WHAT I MEANT LOL
