### ISSUE TITLE
error cannot find module pls fix this error

### ISSUE THREAD

**Issue by VSabertail** [AJS-development/Ogar-unlimited#427]

**Comment by MichaelLeeHobbs** [comment]
@VSabertail If you cannot take the time to at least cut and paste the error message then I'll just close your tickets.

**Comment by Andrews54757** [comment]
@VSabertail It is really annoying, especially if your trying to work something out, then a notification appears then on the issue there is no description so there is no way to help. Just a waste of time. I was working out on my auth rewards plugin.

**Comment by firelightning13** [comment]
^^^
