### ISSUE TITLE
MY BOTS DONT WORK EVEN IF I TURN ALL ANTI BOT STUFF OFF

### ISSUE THREAD

**Issue by VSabertail** [AJS-development/Ogar-unlimited#434]
ITS THE ONLY WAY TO TEAM WITH BOTS USING E AND R AND YOU FUCKERS BLOCKED IT EVEN WITHOUT CHANGING IT IN SETTINGS

**Comment by ErikParacelsus** [comment]
Wtf is wrong with you lol

**Comment by Agarian** [comment]
dude holy shit calm TF down

**Comment by Agarian** [comment]
i will close if i need to.

**Comment by firelightning13** [comment]
Caps lock, geez

**Comment by MichaelLeeHobbs** [comment]
@VSabertail I'm tired of your attitude. I work 40+ hours a week. I have two young boys at home. Any time I get to put into this project is my free time which I get very little of and then I have to deal with people like you who can't take the time to post even half decent bug reports nor spends time trying to google solutions to basic problems like installing npm dependices?

I've blocked you and if I could I would ban you from the project. But that is up to @Andrews54757

**Comment by Andrews54757** [comment]
I dont think you can ban people from projects. lol

**Comment by Agarian** [comment]
github should add that
