### ISSUE TITLE
Food not spawning or either spawning to slow

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#435]
Is there something wrong with food spawns?
if i add 50 bots they will get every food cell and they wont respawn unless in like 50 seconds even tho it's set to 28. In previous verison food was spawning by-time it was eaten

**Comment by VSabertail** [comment]
It might have been a coding bug let me check it out and how long have you been experiencing this? since what version

**Comment by VSabertail** [comment]
And i just noticed i am having the same problem

**Comment by VSabertail** [comment]
put spawn interval to 10

**Comment by PrinceDark9243** [comment]
me too

**Comment by elitajmx** [comment]
i put it to 1 and it doesn't spawn haha

**Comment by elitajmx** [comment]
so no fix?

**Comment by Andrews54757** [comment]
it works fine for me

**Comment by MichaelLeeHobbs** [comment]
Spawn rate is capped at someValue per minute. I think it is currently set to 200. If you have 50 bots they will easily eat all the food. At some point I want to change this code to a scaling value but for now just up the food spawn.

**Comment by elitajmx** [comment]
that's bad .. when will be this fixed? for having like 200 bots and food will still spawn

**Comment by MichaelLeeHobbs** [comment]
@elitajmx You can set the value in the config. It has always been this way. In the past food spawn was a reflection of the game effective frame rate. The higher the frame rate the faster food would spawn. In addition to that there were other settings that would affect food spawn. Now food spawns at a fix rate spread across a minute. It's really not different than before just a different way to get the same end result. 

Now with that said when I switch the code over to the new method I just picked the value 200 per minute at random. It is very likely too low. Why don't we come up with a new value and someone push it into the config and commit it. Down the road, I'd like to come up with a system that scales based on the number of players.

**Comment by elitajmx** [comment]
i have set the food spawn to 1 before it was 28 and it doesn't spawn.

**Comment by elitajmx** [comment]
+ you can't spawn more food than like 4k

**Comment by MichaelLeeHobbs** [comment]
@elitajmx Hang on, I just checked master and it is not what I though it was for food spawning. I'm going to pull the code off of the dev branch for food spawning and retrofit it for food spawning.

**Comment by MichaelLeeHobbs** [comment]
Currently the // foodSpawnAmount : The amount of food to spawn per interval. is set to 240 which is basically 4 food per second.

**Comment by elitajmx** [comment]
nevermind, i hope this all gets fixed from the food spawn to minions spawning top left corner instead all on the map in the next update.
