### ISSUE TITLE
Minions BUG or how to FIX?

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#436]
![ss](https://cloud.githubusercontent.com/assets/16438675/14644186/7741010c-0651-11e6-8194-daa138e675c6.png)

By that i mean as i get big and i'm about 5-10k mass with my minions and just 10 seconds after that minions will only spawn 5m around me, nowhere else on map.. how do i fix thet?

**Comment by Andrews54757** [comment]
not a bug. to "fix" turn player safe spawn off

**Comment by Megabyte918** [comment]
@elitajmx does this still happen when u turn it off? ive tested this before i pr'd it and it worked D:

**Comment by elitajmx** [comment]
yes, i go to the corner which happens all the time and they just keep spawning there again:/

**Comment by Megabyte918** [comment]
they spawn in the corner?

**Comment by elitajmx** [comment]
yes

**Comment by Megabyte918** [comment]
@elitajmx the spawning works fine for me

**Comment by elitajmx** [comment]
It's oke but if i make 2 people use about 100 bots they will probally spawn top l3ft

**Comment by Megabyte918** [comment]
I'll see what i can do
