### ISSUE TITLE
Doublesplit and split not working and it was better earlier 

### ISSUE THREAD

**Issue by VSabertail** [AJS-development/Ogar-unlimited#437]
https://www.youtube.com/watch?v=79F1INAhu4c how doublesplit is and go  on ogarul and look at splitting and compare it to the video :)

**Comment by VSabertail** [comment]
and also statue skin is not working :P

**Comment by VSabertail** [comment]
When I double split sometimes the 3rd pieces eats everything instead of the forth piece and its usually not like and i have no idea how popsplit is still working with the split like that but i can still doublesplit but in normal agario when i doublesplit the splits have more force like they move further and thats how it works `Popsplit = working (16.1.5)` `Doublesplit = not working (16.1.5)` `tricksplit =working (16.1.5)`

**Comment by VSabertail** [comment]
@Andrews54757 @MichaelLeeHobbs you think you can fix this error

**Comment by Megabyte918** [comment]
@VSabertail read #402

**Comment by VSabertail** [comment]
I KNOW ITS NOT ABOUT FUCKING POPSPLIT ITS ABOUT FUCKING DOUBLESPLIT DUMBASS

**Comment by VSabertail** [comment]
Sorry i got anger issues ok so guys please dont hate me

**Comment by Megabyte918** [comment]
its about both just read through it
