### ISSUE TITLE
create entity in mouse position?

### ISSUE THREAD

**Issue by loboere** [AJS-development/Ogar-unlimited#438]
Someone can make a system for creating entity in the position of the mouse (viruses, bots, minions etc).

Could it be that by pressing a key one entity is created in the position of the mouse.

also could make a level editor.

**Comment by VSabertail** [comment]
A key Do you know the rules did u read FAQ? ITS ILLEGAL TO USE KEYS LIKE E OR R!

**Comment by Agarian** [comment]
thats not what this is about sabertail

**Comment by Andrews54757** [comment]
@loboere I will try making a plugin when I have time

**Comment by NatsuTheGreat** [comment]
@VSabertail It's called MAKING MULTI-FUNCTIONAL KEYS AKA Q AND W.

**Comment by PrinceDark9243** [comment]
Guys How to use random skins?

**Comment by PrinceDark9243** [comment]
guys Answer ME plz i dont know how to use random skins!!!

**Comment by Andrews54757** [comment]
do </random>name in the nickname box

**Comment by Agarian** [comment]
</random>

**Comment by NatsuTheGreat** [comment]
</random> ?

**Comment by Andrews54757** [comment]
I hate markdown. i forgot to escape the charactor
