### ISSUE TITLE
I am working on Skins, please put your ideas here

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#44]
Like in parisgamma.iomods. IT DOES USE THE NORMAL CLIENT. I am figuring it our but you can help me

**Comment by ItzLevvie** [comment]
I've already added skins to my version of Ogar :P (It's not released yet, has the same physics as Agar.io [Accurate])

**Comment by Andrews54757** [comment]
I know

**Comment by Andrews54757** [comment]
Im very close to figuring it out

**Comment by Andrews54757** [comment]
:( I cant figure it out.

**Comment by Agarian** [comment]
@Andrews54757 what exactly does the "live console" do?
does it show when people join and leave or something?

**Comment by Andrews54757** [comment]
Try it out. turn it on at gameserver.ini and start the server. (I cannot explain) It is a much easier way to get stats

**Comment by Agarian** [comment]
it just blew my mind

**Comment by Andrews54757** [comment]
**Live console Preface**

(face 1)
```
     ___                                 Status
  / _ \ __ _ __ _ _ _          Players:      0
 | (_) / _` / _` | '_|         Spectators:   0
  \___/\__, \__,_|_|           Alive:        0
       |___/                   Max Players:  50
   u n l i m i t e d           Start Time:   1454463137680
```

Face 2
```
   ___                                Leaderboard
  / _ \ __ _ __ _ _ _                  1.nigeria
 | (_) / _` / _` | '_|                 2.germany
  \___/\__, \__,_|_|                   3.pakistan
       |___/                           4.european union
   u n l i m i t e d                   5.piccolo
```

Face 3

```
   ___                                 Status
  / _ \ __ _ __ _ _ _          Uptime:      529.172
 | (_) / _` / _` | '_|         Memory:      6488.18/9033.392 kb
  \___/\__, \__,_|_|           Banned:      0
       |___/
   u n l i m i t e d
```

**Comment by NatsuTheGreat** [comment]
@ItzLevvie You said got skins working, Can you please help use out? I don't think vram4 wants to give it out at all... And it's the agar.io client right? I am guessing vram4 somehow merged in main_out.js

**Comment by Andrews54757** [comment]
I feel too lazy to figure it out

**Comment by Andrews54757** [comment]
I will laugh if vram4 conviced miniclip to change the client

**Comment by Andrews54757** [comment]
@ItzLevvie Do you actually have it? Then pls pls pls tell the community

**Comment by Lukkez** [comment]
Lol a Ogar issue maked this and @ItzLevvie good work

**Comment by Lukkez** [comment]
@ItzLevvie I NEED THR CLIENT FUUUUUUU I WANT SO MUCH THE SKINS BECAUSE I LIKE KRAKEN SKIN AND I DONT HAVE

**Comment by NatsuTheGreat** [comment]
I really do not this vram4 made it. If he made it then it would have had something like ogar in the link. Not parisgamma.IOMODS.COM it's an Agar.io Mods and it was made by ElectroNoob. As you can see the post here has a little to the bottom. [Right here](https://www.reddit.com/r/Agario/comments/3vz18o/agario_ffa_server_with_miniclips_skins/)

**Comment by Agarian** [comment]
@ItzLevvie release pls?

**Comment by ItzLevvie** [comment]
@Agarian Probably in the future. I've to work on https://github.com/ItzLevvie/serverUpdate/

**Comment by NatsuTheGreat** [comment]
@ItzLevvie But will you release it though?

**Comment by ItzLevvie** [comment]
@NatsuTheGreat Probably in the future.

**Comment by Agarian** [comment]
whenever someone says probably, usually they mean no.

**Comment by NatsuTheGreat** [comment]
@ItzLevvie Please, it's an amazing feature.

**Comment by Agarian** [comment]
im kinda in it for the physics. if they're any different from here

**Comment by Andrews54757** [comment]
I highly doubt she has it ;)

**Comment by Agarian** [comment]
ikkkr :(

**Comment by Agarian** [comment]
still im kinda in it for the physics & features. if they're any different from here

**Comment by Lukkez** [comment]
I THINK NEVER I WILL USE KRAKEN  SKIN (sorry caps)

**Comment by aaxxo** [comment]
I don't quite understand how anyone can come to a repo about having done this yet not help anyone understand how? It adds nothing the discussion for those who are trying to implement this.

**Comment by Andrews54757** [comment]
I think only one person has it ever. I dont believe if someone says they have it but wont share. It is very hard to implement this

**Comment by Lukkez** [comment]
@Andrews54757 Two people, @ItzLevvie and /u/HelpMeGetALife

**Comment by NatsuTheGreat** [comment]
@Lukkez How do you know?

**Comment by Lukkez** [comment]
Parisgamma =P

**Comment by Lukkez** [comment]
And @ItzLevvie not is HelpMeGetALife
