### ISSUE TITLE
Update splitting so doublesplit works 

### ISSUE THREAD

**Issue by VSabertail** [AJS-development/Ogar-unlimited#441]
I Know theres already an issue for it but  andrews doesent want to update it when it should be updated CAUSE ITS ANOYING ANDREWS UPDATE IT PLEASE (and i love swearing and spamming! lololol)

**Comment by VSabertail** [comment]
# ANDREWS PLEASE UPDATE IT PLEASE

**Comment by Agarian** [comment]
I DON'T LIKE GETTING SPAMMED BY NOTIFICATIONS :angry:

**Comment by VSabertail** [comment]
THEN UPDATE SPLIT AND I WONT

**Comment by Andrews54757** [comment]
No. why should i

**Comment by VSabertail** [comment]
JUST PLEASE I BEG YOU I BEG YOU ANDREWS PLEASE PLEASE PLEASE PLEASE ILL DO ANYTHING

**Comment by ErikParacelsus** [comment]
@VSabertail Chillax bro one day he will. But you keep annoying him that makes nothing better.

**Comment by Andrews54757** [comment]
but what does it improve

**Comment by Agarian** [comment]
Splitting i guess, i stuck with an older version of ogarUL after the recent 'big update'

**Comment by firelightning13** [comment]
@VSabertail Can you not using caps lock, its annoying af...

**Comment by Megabyte918** [comment]
The splitting and doublesplit is perfect

**Comment by ErikParacelsus** [comment]
^ true

**Comment by XxRaizerxX** [comment]
he means that when you split the split moves cell 1 back and moves cell 2 further and same for doublesplit

**Comment by Megabyte918** [comment]
theres nothing wrong with it imo
