### ISSUE TITLE
Linux Scripts and [Console] We recieved a world-wide message!: If you dont have a plugins folder, make it manually! (github doesnt support empty folders)

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [AJS-development/Ogar-unlimited#445]
I've push two scripts onto master for linux. For linux this solves the [Console] We recieved a world-wide message!: If you dont have a plugins folder, make it manually! (github doesnt support empty folders)

setup.sh and start.sh - They do what they say.

setup.sh - Run this on initial download of Ogar Unlimited or after an Update. It will handle all you npm/node issues.

start.sh - Use this to run Ogar Unlimited. It will make sure you run from the right folder.

Remember on linux you have to run scripts with ./ in front of the script. This is a security function of linux to make sure you don't run something you didn't mean too.

Note: I've tested the start script but have not been able to fully test the setup script as my system has an issue where I can't make my self a sudo user. :) Go figure, lol.

**Comment by Megabyte918** [comment]
nice
