### ISSUE TITLE
Module error.

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#447]
## **Help me cmd error http://prntscr.com/avnto2**
Contact:
_**Skype : ghostshot3.private/ghostsixbr
Email : ghostshot3@gmail.com**_

**Comment by Andrews54757** [comment]
Do this: 

1. Delete node_modules folder
2. do npm install again

**Comment by GhostShot3** [comment]
@Andrews54757 this folder (" http://prntscr.com/avnwc0 ") ?,and 
where I need to npm istall ?

**Comment by Andrews54757** [comment]
no, i mean the folder node_modules under the main folder, not the src folder

**Comment by GhostShot3** [comment]
@Andrews54757 http://prntscr.com/avnxlf all ?

**Comment by Andrews54757** [comment]
I don't understand how you got that many, but yes, all

**Comment by GhostShot3** [comment]
@Andrews54757 deleted and now where I need to npm install?

**Comment by Andrews54757** [comment]
What computer do you have?

**Comment by GhostShot3** [comment]
@Andrews54757 Windows 7 pro

**Comment by Andrews54757** [comment]
OK, then click on installdependacies.bat in src

**Comment by GhostShot3** [comment]
@Andrews54757 I had done it before and so it gave this error now deletarei the folder and down again?

**Comment by Andrews54757** [comment]
?

**Comment by Andrews54757** [comment]
what folder is the src folder in?

**Comment by GhostShot3** [comment]
Had done before, and so gave this error now exclude the folder and down again zeroed?

**Comment by Andrews54757** [comment]
Here are some steps

1. Check to make sure package.json exists and is not empty in the folder that holds the src folder
2. Check to make sure there is no folder called node_modules in the folder holding the src folder
3. press install dep again

**Comment by Andrews54757** [comment]
what error did it it give?

**Comment by GhostShot3** [comment]
@Andrews54757 wait I will try what you said

**Comment by GhostShot3** [comment]
@Andrews54757 http://prntscr.com/avo6hz

**Comment by GhostShot3** [comment]
@Andrews54757 and i dont have "package.json" in src folder.

**Comment by Andrews54757** [comment]
you have to click on the install dependancies.bat script
