### ISSUE TITLE
a minor food growth bug

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#448]
when food grow is enabled, you would need to move away from the food for it to update it's mass once it has hit the `foodMassTimeout`. So if you move back into that area, the food mass updates.

**long story short:** you cannot see food mass grow on-screen, only off-screen.

**Comment by NatsuTheGreat** [comment]
true..

**Comment by retslac** [comment]
You need to reverse the if conditions, like this:
```
Food.prototype.sendUpdate = function() {
    // Whether or not to include this cell in the update packet
    if (this.shouldSendUpdate) {
        this.shouldSendUpdate = false;
        return true;
    }
    if (this.moveEngineTicks == 0) {
        return false;
    }
    return true;
};
```

**Comment by Agarian** [comment]
ok ill try it

**Comment by Agarian** [comment]
it works thanks! Ill make a PR on this

**Comment by NatsuTheGreat** [comment]
@retslac OMG! You're here atlast?!?! Can you come on discord?

**Comment by retslac** [comment]
LOL been away for a while
Can do discord tomorrow, have to go sleep now

**Comment by NatsuTheGreat** [comment]
Alrighty. Hopefully i'll see ya tomorrow man! I'll probably be around 12 PM maybe earlier.

**Comment by NatsuTheGreat** [comment]
@retslac You here yet?

**Comment by Agarian** [comment]
i'd ask you the same lol im sitting in discord

**Comment by retslac** [comment]
I'm here

**Comment by NatsuTheGreat** [comment]
Yay! Can you get on discord?

**Comment by retslac** [comment]
already on

**Comment by NatsuTheGreat** [comment]
@retslac Alright I am there.

**Comment by Andrews54757** [comment]
i think i fixed this one, i added food min amount config and if you increase it, you will fix this issue

**Comment by Agarian** [comment]
i already fixed it tho

**Comment by Agarian** [comment]
https://github.com/AJS-development/Ogar-unlimited/pull/449

**Comment by NatsuTheGreat** [comment]
@retslac Are you available today?
