### ISSUE TITLE
(Suggestion) automated on and off on a server

### ISSUE THREAD

**Issue by Codeidiot737** [AJS-development/Ogar-unlimited#45]
You could make your server turn on and off every hour. Or, you could make it turn on for a half hour, and then off for an hour.

**Comment by Codeidiot737** [comment]
you could do this so if anyone wants to play agar with you, they wouldn't have to ask every time

**Comment by Andrews54757** [comment]
stop it nick. I am working on live console

**Comment by Andrews54757** [comment]
I have autopause nick. I added it a long time ago
