### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#453]
It's not connecting to my server made with c9

**Comment by Lukkez** [comment]
Failed to load resourcFailed to load resource: net::ERR_BLOCKED_BY_CLIENTFailed to load resource: net::ERR_BLOCKED_BY_CLIENTe: net::ERR_BLOCKED_BY_CLIENT

**Comment by Agarian** [comment]
i have a similar problem on c9, but instead i get

WebSocket connection to 'ws://ogarservercloned-agarian.c9users.io/' failed: Error during WebSocket handshake: Unexpected response code: 502

**Comment by XxRaizerxX** [comment]
same idk why

**Comment by Lukkez** [comment]
A new update made this, when i use older versions works perfectly.

**Comment by Andrews54757** [comment]
I am pretty sure its not ogar ups fault, it is the web socket module.

**Comment by Andrews54757** [comment]
it works with me though

**Comment by Agarian** [comment]
Seems like everything thst doesn't work for us works for you lol

**Comment by Andrews54757** [comment]
It does, check out at http://agar.io/?ip=ogar-unlimited-andrews54757.c9users.io and i also just fixed the lag issue

**Comment by Andrews54757** [comment]
I'm adding like 300 bots once your in

**Comment by Andrews54757** [comment]
It works perfectly

**Comment by Agarian** [comment]
its not connecting

**Comment by Andrews54757** [comment]
i shut it down

**Comment by Andrews54757** [comment]
someone connected an  30 m ago, was it not you?

**Comment by Andrews54757** [comment]
then i turned it off as no-one uses it

**Comment by Agarian** [comment]
i ddnt connect

**Comment by Andrews54757** [comment]
ok

**Comment by Lukkez** [comment]
I'll update and see, i use 5 days old version
