### ISSUE TITLE
WHEN NEW UPDATE FOR MINIONS BUG AND FOOD BUG?

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#454]
When is the update for minions so they don't spawn in top left corner all the time and for food not spawning every 4 seconds like it did before.

**Comment by Andrews54757** [comment]
fixed a long time ago

**Comment by elitajmx** [comment]
so if i download it's fixed

**Comment by Andrews54757** [comment]
yep
