### ISSUE TITLE
Module error

### ISSUE THREAD

**Issue by jollesnaas** [AJS-development/Ogar-unlimited#461]
I know that is is asked often but I can't get it to work, I tried this (Inside the src folder:) `npm install ws` and `npm install request` and I have opend the `Install Dependencies (Windows).bat file`. I have installed `node.js 4.4.3` on my `windows 2008 VPS`. 
Here is the error:
![Image of the Error](http://i.imgur.com/O9Ntbu2.png)
What do I do?

**Comment by Andrews54757** [comment]
1. delete node_modules
2. do the install dependancies script

**Comment by Andrews54757** [comment]
this is not a problem with ogarul, it is with npm

**Comment by Andrews54757** [comment]
maybe try updating your nodes and npm

**Comment by jollesnaas** [comment]
@Andrews54757 how to do that? Install nodejs 5.11.0 from the site?

**Comment by Andrews54757** [comment]
Look up on google

**Comment by jollesnaas** [comment]
@Andrews54757 Still not working :(, I updated node and the npm.... I can give you acces to my windows server so you can do some things. If you think that that is a good idea contact me on skype or something: Skype: jolle.snaas1

**Comment by Andrews54757** [comment]
then redownload ogar ul, maybe that will do

**Comment by ErikParacelsus** [comment]
@jollesnaas Did you delete the node_modules file yet?

**Comment by jollesnaas** [comment]
@ErikParacelsus Yes I did, I'm now reïnstalling everything!

**Comment by ErikParacelsus** [comment]
Welp i don't know what's going on.

**Comment by jollesnaas** [comment]
@ErikParacelsus Me too, that is why I asked this. I might be doining still something wrong, I can give you temporally access to my vps, may that works. For that (Chat) skype me: [jolle.snaas1](skype:jolle.snaas1?chat)

**Comment by jollesnaas** [comment]
@ErikParacelsus @Andrews54757 OMG, I downloaded an other version of ogar (OgarServ) and it worked with that version... I'm happy that that worked, but I like ogar unlimited much more so yeah...
