### ISSUE TITLE
Pressing Q in spectate doesn't let you raom around

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#462]
q is broken

**Comment by ErikParacelsus** [comment]
Works fine for me

**Comment by Megabyte918** [comment]
what version are you on? im using the latest

**Comment by ErikParacelsus** [comment]
Me too

**Comment by Agarian** [comment]
If you use minions, it gets overridden.

**Comment by ErikParacelsus** [comment]
@Megabyte918 Close this?

**Comment by Megabyte918** [comment]
@Agarian thats weird
@ErikParacelsus alright i forgot to :P
