### ISSUE TITLE
Remove creating 'console.log' file

### ISSUE THREAD

**Issue by XtremePlayzCODE** [AJS-development/Ogar-unlimited#464]
I tried deleting OgarUnlimited to update it (idk why i didnt do update command) and I could not delete console.log file. I reinstalled it and through bash deleted it. Any way to disable writing it?

**Comment by LegitSoulja** [comment]
To disable console.log add this to configuration

serverLogLevel = 0;

And for me, I have had no luck getting the recent version of OgarUnlimited working..

**Comment by XtremePlayzCODE** [comment]
Me too.

**Comment by XtremePlayzCODE** [comment]
After about 5 seconds of joining theres an error

**Comment by LegitSoulja** [comment]
What's the error?

**Comment by XtremePlayzCODE** [comment]
Looks like its fixed now. 

P.S. Look at your Gitter, I helped with your question

**Comment by XtremePlayzCODE** [comment]
I solved this by deleting a few lines in "log.js".

**Comment by LegitSoulja** [comment]
P.S, I've already been solved my issue. I couldn't delete my question. Thanks though.

**Comment by XtremePlayzCODE** [comment]
I mean the requiring gameServer from index.js

**Comment by LegitSoulja** [comment]
Yea, I have already solved that problem. I appreciate your help. Check out OgarConsole. That what I was working on :).

**Comment by XtremePlayzCODE** [comment]
Whats it do?

**Comment by LegitSoulja** [comment]
Well, it has its own remote console. I've had problems with having to go back and forth between vps servers. Now with OgarConsole it's a separate server that hosts a console/cmd/terminal for you that you can connect to and monitor your server

**Comment by XtremePlayzCODE** [comment]
Nice, so I can run it and OgarUL and it connects?

**Comment by LegitSoulja** [comment]
Pretty much made it for that, and also I will be hosting Ogar servers. So now people have access to there console also :)

**Comment by XtremePlayzCODE** [comment]
Nice! We should make a public one. Notice how I said we. :)

**Comment by LegitSoulja** [comment]
With 11.9.0. Not the latest. If I can get the latest version working I will start working on it. But I can't even get the server started

**Comment by XtremePlayzCODE** [comment]
Nice

**Comment by LegitSoulja** [comment]
Check out my site http://agariohub.tk

**Comment by XtremePlayzCODE** [comment]
They're all offline... Also can you make a template for me?

**Comment by LegitSoulja** [comment]
They aren't offline. Make sure your not connecting with HTTPS and your not using a proxy

**Comment by XtremePlayzCODE** [comment]
Ok

**Comment by LegitSoulja** [comment]
And besides, if it says it's offline then there's security problems. It says it's offline because the stats for the server cannot be reached. If you join the game the game is actually online.

**Comment by LegitSoulja** [comment]
And sure we can work together. Do you have skype?

**Comment by XtremePlayzCODE** [comment]
Discord only, sry

**Comment by LegitSoulja** [comment]
Your out of luck.

**Comment by XtremePlayzCODE** [comment]
Wait I do have skype

**Comment by XtremePlayzCODE** [comment]
LOL I FORGOT

**Comment by LegitSoulja** [comment]
Add me. Mactown51

**Comment by XtremePlayzCODE** [comment]
Dont have a mic tho

**Comment by LegitSoulja** [comment]
That's fine.. Just for a place to chat instead of here

**Comment by XtremePlayzCODE** [comment]
cant connect to skype

**Comment by LegitSoulja** [comment]
Looks like you have some serious connection problems then

**Comment by XtremePlayzCODE** [comment]
LOL

**Comment by LegitSoulja** [comment]
Well farewell

**Comment by XtremePlayzCODE** [comment]
NUU SO CLOSE

**Comment by LegitSoulja** [comment]
You can register over at my site and talk to me there if you would like

**Comment by LegitSoulja** [comment]
And you need a template for what?

**Comment by XtremePlayzCODE** [comment]
Your hub

**Comment by LegitSoulja** [comment]
lol, I'm sorry. It took me a very long time to make my hub. I won't be able to release it to the public. Sorry

**Comment by LegitSoulja** [comment]
It's very easy to get started.. My hub is more advanced and have an admin panel. 

Best way to do this the easy way if you are hosting servers, store server data into mysql. Then from there setup a way to display each server you have.

**Comment by LegitSoulja** [comment]
I could help you develop your hub if you need help. But, mines is unique.

**Comment by LegitSoulja** [comment]
I'm using Bootstrap > Metro Tiles CSS > and a few other libraries. Use those to help you create something neat.

**Comment by LegitSoulja** [comment]
https://github.com/LegitSoulja/OgarConsole

Use Ogar original, or Ogar Unlimited 11.9.0. 11.9.0 is included with the download.

:+1:

**Comment by XtremePlayzCODE** [comment]
k

**Comment by LegitSoulja** [comment]
If you have any problems with it just issue a report there. I've been testing and testing.. I have no had problems yet. Soon there will be a UI update.

**Comment by XtremePlayzCODE** [comment]
get on skype

**Comment by XtremePlayzCODE** [comment]
Get on skype

**Comment by LegitSoulja** [comment]
Im on, you just gotta add me

**Comment by XtremePlayzCODE** [comment]
Im on

**Comment by XtremePlayzCODE** [comment]
I added  you

**Comment by LegitSoulja** [comment]
mactown51? You haven't send a contact request.

**Comment by XtremePlayzCODE** [comment]
Yeah i have

**Comment by LegitSoulja** [comment]
got it

**Comment by XtremePlayzCODE** [comment]
am i xtremeplayzyt
