### ISSUE TITLE
No Luck

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#465]
Before you say UPDATE, I have updated v6.0.0 Currect.. I have had no luck with OgarUnlimited after the BIG CORE update!. I've tried fixing it myself but ended up getting more errors.. 

> Ogar-unlimited-master\src\index.js:3
> const Readline = require('readline');
> ^^^^^
> SyntaxError: Use of const in strict mode.
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:906:3

I have no idea what could be the problem.

**Comment by Agarian** [comment]
same here, it just made c9 laggier too

**Comment by LegitSoulja** [comment]
I'm sticking to 11.9.0.. I'm not using the latest release until a stable fix

**Comment by Agarian** [comment]
thats what i've been doing here http://agar.io/?ip=ogarservercloned1-agarian.c9users.io

**Comment by LegitSoulja** [comment]
thats what i've been doing here http://agariohub.tk

**Comment by LegitSoulja** [comment]
I've uninstalled nodejs and install LTS 4.4.3, and still DONT WORK!!. @Andrews54757

**Comment by LegitSoulja** [comment]
same error as before after installing LTS version of nodejs

**Comment by Megabyte918** [comment]
Dang I should have updated the splitting on an earlier version that worked.... all the older versions before the big "core" one the splitting sucks (no offense)

**Comment by firelightning13** [comment]
Yeah you should I want to use old version though

**Comment by LegitSoulja** [comment]
You the old version then lol

**Comment by firelightning13** [comment]
Well i dont like the new version, i like the old version (no offense)

**Comment by LegitSoulja** [comment]
I need to get the new version working for a reason. It's not the reason that I'm using it for a server no. I am using he old version, but I'm working on a project that will work for this version, but haven't got it actually working yet.

**Comment by Agarian** [comment]
I think most of us like the older one.

**Comment by LegitSoulja** [comment]
But I don't understand how you can compare when the newer doesn't even work. I don't understand how people are getting it to work. I just give up

**Comment by Andrews54757** [comment]
1. download files
2. do `npm install` (do not use the update command)
3. do `sudo node index.js`

**Comment by LegitSoulja** [comment]
I've downloaded and downloaded. Nothing

**Comment by Andrews54757** [comment]
well, google it up, I am getting kinda annoyed at these sort of problems. not really problems with the software.

**Comment by Andrews54757** [comment]
i need a break

**Comment by Andrews54757** [comment]
https://github.com/sass/node-sass/issues/1268

**Comment by Andrews54757** [comment]
http://stackoverflow.com/questions/25226561/nodejs-and-npm-error-modules-missing

**Comment by Andrews54757** [comment]
pretty sure that it is because of request. try `npm install request`

**Comment by LegitSoulja** [comment]
Lol my problem isn't a module problem

**Comment by Andrews54757** [comment]
Then what is it?

**Comment by Andrews54757** [comment]
is it the nodejs? are you using homebrew?

**Comment by LegitSoulja** [comment]
I just gave you the error above. People say it's es6

**Comment by LegitSoulja** [comment]
All I can say is I'm running the servers on my Windows vps and I get that error every single time and I've download all recent file changes but I still get that error.

**Comment by ItzLevvie** [comment]
I'm using Node v7.0.0 and haven't got this error yet.

**Comment by LegitSoulja** [comment]
How there's a version 7?? lol I'm done with life and this

**Comment by firelightning13** [comment]
It's version 6.0.0 BTW

**Comment by ItzLevvie** [comment]
"How there's a version 7?? lol I'm done with life and this" It's the node.js 7.0.0 nightly builds.

**Comment by LegitSoulja** [comment]
Lol I'm done with this and this world

**Comment by LegitSoulja** [comment]
And does it works? The nightly build or whatever

**Comment by LegitSoulja** [comment]
NOPE!!........ Im done. Screw node and all these versions and the latest of OgarUnlimited if I can't get no help..

**Comment by Megabyte918** [comment]
are you still having the same error as your first comment?

**Comment by LegitSoulja** [comment]
Its the same as readline of mines that was closed and never solved

**Comment by LegitSoulja** [comment]
I just gave up on trying to get it to work

**Comment by Megabyte918** [comment]
try putting "use strict" at the top of index.js, im not at my computer so i cant see if it works or fix any of these issues myself

**Comment by LegitSoulja** [comment]
Its already there in the begin with

**Comment by Megabyte918** [comment]
should have checked the file before i said that haha

**Comment by Megabyte918** [comment]
ill come back later when i have time but rn i have to go

**Comment by Megabyte918** [comment]
@LegitSoulja I don't know what the hell is wrong... however I have my server files from before all these bugs and errors arose (not before the big core update tho) and it works fine there are no error messages I could send it to you if you want

**Comment by LegitSoulja** [comment]
@Megabyte918 sure.. Ill try that also.

**Comment by Megabyte918** [comment]
@LegitSoulja do you have skype or discord? I could send it to you there

**Comment by LegitSoulja** [comment]
I hate discord.. Skype fine > mactown51

**Comment by Megabyte918** [comment]
I made a contact request
