### ISSUE TITLE
I always get the same error :(

### ISSUE THREAD

**Issue by c0rt3xg4m1ng** [AJS-development/Ogar-unlimited#466]
I've read the FAQ (and have done it) but still my problem is still not fixed...

I always get this:

`module.js:341`
` `
`    throw err;`
`    ^`
` `
`Error: Cannot find module 'process-nextick-args'`
`    at Function.Module._resolveFilename (module.js:339:15)`
`    at Function.Module._load (module.js:290:25)`
`    at Module.require (module.js:367:17)`
`    at require (internal/module.js:16:19)`
`    at Object.<anonymous> (C:\Users\ADMIN\Desktop\Ogar-unlimited-master\no`
`de_modules\request\node_modules\readable-stream\lib\_stream_duplex.js:21:23)`
`    at Module._compile (module.js:413:34)`
`     at Object.Module._extensions..js (module.js:422:10)`
`    at Module.load (module.js:357:32)`
`    at Function.Module._load (module.js:314:12)`
`    at Module.require (module.js:367:17)`
` `
`Press any key to exit...`

**MY SPECS:**
**-Windows 7 Ultimate 32 bit**
**-4GB Ram**
**-Intel Core 2 Duo**

Why wont it run??? The classic "Ogar-windows-571bd36.exe" works... Except for the "change" command (I also get the same error).

And I've done doing `npm install` in the src folder...

**PLS Fix it...**

**Comment by firelightning13** [comment]
Waw so many bugs

**Comment by Andrews54757** [comment]
this is a problem with npm. I don't know how to fix. ask the creators of npm

**Comment by Agarian** [comment]
this is an issue that is ruining ogar unlimited.

**Comment by Megabyte918** [comment]
it works for me wat

**Comment by Andrews54757** [comment]
https://github.com/sass/node-sass/issues/1268 explains a but more

**Comment by Andrews54757** [comment]
http://stackoverflow.com/questions/25226561/nodejs-and-npm-error-modules-missing

**Comment by Andrews54757** [comment]
try `npm install request`

**Comment by c0rt3xg4m1ng** [comment]
i also tried `npm install request` but still didnt work... :(

**Comment by c0rt3xg4m1ng** [comment]
(For now) ill just try to run this on linux virtualbox then connect agar.io there...

:/
