### ISSUE TITLE
I can't connect [repost]

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#467]
I can't connect, says me 502 Websocket error, i have all node updated, last version of ogar-unlimited but still same thing

The setup.sh doesn't work too (using c9)

**Comment by NatsuTheGreat** [comment]
502 means bad domain/port connections/communications. Agarian got past this ( he had the same problem) @Agarian Can you help him out with this?

**Comment by XxRaizerxX** [comment]
Do npm install setup.sh.

**Comment by Agarian** [comment]
All i did was clone my c9 server with a workspace name i never use,  you can try a different server name.

**Comment by Jhair2015** [comment]
hello, well my problem is that when I open this start.bat I get this

if anyone knows the solution please me could say :+1 : D

http://imgur.com/fhjFOqP

**Comment by Lukkez** [comment]
I can't, it's because i'm trying to use a older c9.io acc who i have a premium workspace, who if i make a new workspace will be 512mb ram and this one have 2,5 gb :/

**Comment by Lukkez** [comment]
@Jhair2015 you can open a cmd on server folder and do ``npm install`` no module, will install the only who is needed to the server **run**.

**Comment by Jhair2015** [comment]
@Lukkez I could explain in detail please migo :) I do not understand much about this topic  :D

**Comment by LegitSoulja** [comment]
Theres nothing on line 21&23 of duplex.js.

**Comment by LegitSoulja** [comment]
It has to be your directory failing to get its own dependencies.

**Comment by LegitSoulja** [comment]
If readable-stream is installed, so are those packages that are missing. I'm having the same problems with 'Missing' things. I have not found a fix yet.

**Comment by Agarian** [comment]
i'll close this for now.

**Comment by jrgryph** [comment]
I find I have to do npm install twice for it to work.

**Comment by Megabyte918** [comment]
ive never had this problem
