### ISSUE TITLE
Food bug/ Map bug

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#468]
When i spawn the map is infinite and no food, i can w infinity, latest version

**Comment by NatsuTheGreat** [comment]
Any errors?

You'd probably get "Max call stack size exceeded" but idk.

Tell me if you get an error.

**Comment by Megabyte918** [comment]
revert the changes made in ini.js and it should work fine (at least for me)

**Comment by Andrews54757** [comment]
I think i just fixed
