### ISSUE TITLE
Problem with moving.

### ISSUE THREAD

**Issue by NatsuTheGreat** [AJS-development/Ogar-unlimited#469]
I do not know what is causing this but here is the problem:

When i multibox and I am over 1k mass, one of my tabs will eventually make me to click to move, I can only click to move, not roam my mouse.

**Comment by Agarian** [comment]
same here, it happens at random, i dont need to multibox tho, also W ing and splitting will have the same effect as clicking, even in old ogarUL

**Comment by NatsuTheGreat** [comment]
It's very annoying.

**Comment by Agarian** [comment]
ikr...

**Comment by Megabyte918** [comment]
ripped

**Comment by firelightning13** [comment]
@NatsuTheGreat @Agarian Do you use tab or window?

**Comment by Jhair2015** [comment]
hello, well my problem is that when I open this start.bat I get this

if anyone knows the solution please me could say :+1 : D

http://imgur.com/fhjFOqP

**Comment by ItzLevvie** [comment]
Try doing ```npm install process-nextick-args```

**Comment by NatsuTheGreat** [comment]
@Jhair2015 make your own issue, don't flood mine.

@firelightning13 I do CTRL + TAB

**Comment by Andrews54757** [comment]
this problem is also with slither.io and it is a problem with the client
