### ISSUE TITLE
Read ERROR correctly

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#471]
Once again.

> Ogar-unlimited-master\src\index.js:3
const Readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:906:3

I've installed LTS, v6.0.0, and nightly 7.0.0 and non of them works. You say over and over to update, or install packages. There's no missing packages, nor theres no other updates I can update too. You say install packages, and the error clearly stats and shows no package is needed. If i can't get no help with this im officialy done working with ogarul. I dont understand why close an issue thats not even solved. A closes issue isnt a solver issue. Thats just another person with anger, and depression thats about to go crazy over here if I cant get this working.. Its been almost a week. A WEEK. and nothing.. Im literally about the pull plugs.

**Comment by Agarian** [comment]
kthen
