### ISSUE TITLE
food doesnt seem to respawn.

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#474]
the description is in the issue name.
it seems to happen when the reset command is run, i also get ALOT of

[Warning] Tried to remove a non existing moving virus!

when i run the reset command

**Comment by MichaelLeeHobbs** [comment]
I have neither of these issues on the master branch. Are you sure you code is up to date? I pushed a food fix last weekend. Also what gamemode were you in?

**Comment by Agarian** [comment]
Nvm took care of it

**Comment by Agarian** [comment]
but food spawns slowly after the reset command is run

**Comment by Agarian** [comment]
and yes my code is up to date
