### ISSUE TITLE
tomato skin error!

### ISSUE THREAD

**Issue by XxRaizerxX** [AJS-development/Ogar-unlimited#475]
I was going on my ogarul server and i was going to use tomato skin <tomato> and then it did not show anything all there was was my cell with no skin

**Comment by VSabertail** [comment]
bro i have the same error :P

**Comment by LegitSoulja** [comment]
@XxRaizerxX is it only the tomato skin? or all the skins? You may have to update your skins.

**Comment by NatsuTheGreat** [comment]
@LegitSoulja How would we update them?

**Comment by Agarian** [comment]
the skins run directly off the agario client. updating this will not have an effect.
