### ISSUE TITLE
Do not upgrade to Node 6.0 - Node 5.9 is the highest version we support for now

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [AJS-development/Ogar-unlimited#476]
One of the libraries we require uses another library that in turn uses an old version of a library which uses graceful-fs@1.2.3, which is REALLY OLD and does not work on node 6.0. I have filed issues with the project owners and hopefully this will be resolved soon.

To control what version of node you use run the following commands:
npm install n -G
n 5.9.0

**Comment by MichaelLeeHobbs** [comment]
Resolved, you might have to delete your node_modules folder

**Comment by MichaelLeeHobbs** [comment]
TravisCI failed due to npm issue, reopening.

**Comment by Agarian** [comment]
Pretty dure thats just the CI bug, as this happened when i edited the randomSkins.txt file twice

**Comment by MichaelLeeHobbs** [comment]
@Agarian it is a library issue. One of our libraries requires an old version of glob which require a very old version of graceful-fs. Graceful-fs < 4.0 does not work on Node 6.0. We had our Travis set to use the latest node. This is not a good practice as it leads to these sorts of issues.
