### ISSUE TITLE
FAQ - Read Before Posting

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#48]
These are the top FAQs

1. Can you please make physics better?
A Yes, I am working on it and if you have it done, your more that welcome to make a pull request

2. Custom Skins?
A Currently, it is client sided and there is nothing I can do about it but i am creating a method similar to parisgamma.iomods

3. Auto restart?
A auto restart only works if you use the windows start file

4. High Score?
A To see high score, do the highscore command or use live console. If you want to periodically display the highscore in game, do the announce command to start the feature or set AnounceHighScore to 1 in gameserver.ini. You can edit the duration and the delay in gameserver.ini

5. What is the text after "server restarting" when I use restart, Should I be concerned?
A no, that is entirely normal because otherwise, restart wont work

6. Why when starting the server is an error "cannot find module request"?
A Instead of `npm install ws`, you have to either `cd` into src, do `npm install` or if you did `npm install ws`, do `npm install request`

7. How to join through hamachi?
A We do not know how to do it and it is outside of the scope of the project but to see some answers from the community, go to #121 

8. How to join?
A see #174 

9. I see a interesting update pull request, why not update now?
A There is a method to our madness. That way, there is less bugs and we can add more features as well . No last minute changes

10. How do you start the server?
A Please go to the installation guide at the wiki

**Comment by NatsuTheGreat** [comment]
Have you gotten an autorestarting system?

**Comment by Andrews54757** [comment]
yes

**Comment by NatsuTheGreat** [comment]
Can you give it to me?

**Comment by Andrews54757** [comment]
its already there

**Comment by Andrews54757** [comment]
but you need windows for it to work

**Comment by Andrews54757** [comment]
you also need to use the "clicktostart"

**Comment by NatsuTheGreat** [comment]
I have windows 10

**Comment by Andrews54757** [comment]
Somehow, auto restart and highscore options are not working, i will fix tommorrow
