### ISSUE TITLE
some bugs i found

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#480]
- Failed to delete folder 'eKiGCcQ'. Command failed: rm: cannot remove ‘/home/ubuntu/workspace/src/plugins/eKiGCcQ/README.md’: Permission denied rm: cannot remove ‘/home/ubuntu/workspace/src/plugins/eKiGCcQ/files.txt’: Permission denied rm: cannot remove ‘/home/ubuntu/workspace/src/plugins/eKiGCcQ/index.js’: Permission denied rm: cannot remove ‘/home/ubuntu/workspace/src/plugins/eKiGCcQ/config.ini’: Permission denied rm: cannot remove ‘/home/ubuntu/workspace/src/plugins/eKiGCcQ/command.js’: Permission denied .

- Failed to write to 'config.ini'. Failed saving file ! : src/plugins/eKiGCcQ/config.ini ERR: Error: EACCES, open '/home/ubuntu/workspace/src/plugins/eKiGCcQ/config.ini'. (happens to all files added via command)

- Also the leaderboard stats doesn't display the amount of people alive or the amount of spectators correctly, spectators changes when players join, and the amount of people alive always says 0. Say a player joined the server, the `Spectators` value would change according to the amount of real players in the server. And the `Players` value would remain at 0

**Any fix @AJS-development/ogar-unlimited-devs? It would be appreciated!**

**Comment by MichaelLeeHobbs** [comment]
sudo chmod -R username:username ~/
Where username in the username of the account you are running ogarul from

**Comment by Agarian** [comment]
?

**Comment by MichaelLeeHobbs** [comment]
This is a permission issue: Permission denied rm: cannot remove 

Likely something got ran as root and now you trying to run as non-root. Try sudo chmod -R ubuntu:ubuntu ~/ as it seems like ubuntu is the user account.

**Comment by Agarian** [comment]
chmod: invalid mode: ‘ubuntu:ubuntu’
Try 'chmod --help' for more information.

**Comment by Agarian** [comment]
not sure if i'm doing this right... probably making myself look stupid xD

**Comment by Agarian** [comment]
what about the other bugs?

**Comment by Andrews54757** [comment]
You mean the lbstats plugin. Next time pls put plugin issues there. il see

**Comment by Agarian** [comment]
have any idea around the permissions issue in c9? or at least how to run c9 as a root?

**Comment by Andrews54757** [comment]
not that i know of

**Comment by Agarian** [comment]
I'll just look into it later
