### ISSUE TITLE
Start.bat error

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#481]
# Ogar-unlimited module error on start server see the error **[here](http://prnt.sc/aywiih)** please help me!

**Comment by MichaelLeeHobbs** [comment]
Would be helpfful if we could see the part where it shows what you typed and where you were when you typed it.

**Comment by GhostShot3** [comment]
@MichaelLeeHobbs Can help me ?

**Comment by LegitSoulja** [comment]
Are you running in development mode? With a plugin?

**Comment by GhostShot3** [comment]
@ LegitSoulja  Yes,can not do it?

**Comment by LegitSoulja** [comment]
@GhostShot3 What is inside of your plugin folder? How is your plugin setup? Is it setup properly?

**Comment by Agarian** [comment]
You should probably try and update your server files or update your plugins.

**Comment by Andrews54757** [comment]
or you can delete readme.md in the plugins file
