### ISSUE TITLE
WORKING!!

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#483]
Ok, So I figured out why things were not going out as planned for me in the beginning. Before I started working with this IG WampDeveloper was a thing in that time. NodeJS was installed prior to that directory, So each time I would uninstall Node it would never actually uninstall. Now, After deleting everying Node wise, and Wamp(Because I never used wamp) away. 

Sorry misunderstandings, and old issues. They were on my behalf. I should've check my node path and made sure it was uninstalled. I installed both x86(5.9.1) and x64(5.9.0).

:) Finally works.!

**Comment by Agarian** [comment]
yay xD
