### ISSUE TITLE
Thinking about hosting an ogar unlimited website

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#486]
does anyone know a FREE and easy way to do so?

**Comment by NoorAgario** [comment]
haven't tried it but I guess its good : http://www.xtreemhost.com/
you can also use amazon webhosting free trail for 1 year

**Comment by markvillar** [comment]
I don't think that there are many free options out there without any lags or some kind of trade-off for them to become free service.

DigitalOcean is easy to setup, It costs about $5 to run a 512MB server for a month, though probably not the cheapest option still (I would say).

**Comment by LegitSoulja** [comment]
http://agariohub.tk I'm running a large package on amazon which is about $40 for 2 vps servers. Plus I self host on 16gb ram 4ghz and about 150mbs for connection and ddos protection. I have my own services because I used to host Minecraft servers back then. I can hook you up with something decent without limitations nor restrictions. If your curious let me know

**Comment by firelightning13** [comment]
Lol use github pages

**Comment by LegitSoulja** [comment]
@firelightning13 nah, thats not even a thing. How dare you say that

**Comment by firelightning13** [comment]
lol jk

@Agarian That would be cool though

**Comment by LegitSoulja** [comment]
@firelightning13 that would be cool, but think about the things you can't do with these pages. Best to get proper hosting for your needs.

**Comment by Megabyte918** [comment]
@firelightning13 i didn't even know there was a website :O

**Comment by Andrews54757** [comment]
there is

**Comment by Andrews54757** [comment]
and github pages can do everything, i just chose the automatic page generator

**Comment by LegitSoulja** [comment]
Php, MySQL, etc. I don't think github includes that

**Comment by Andrews54757** [comment]
i can go around with that

**Comment by LegitSoulja** [comment]
If html & css a lifestyle of a website, then be my guest. Theres so much you can't do without MySQL and PHP. Might as well just leak your servers everywhere

**Comment by Andrews54757** [comment]
or i can use something like heroku for mysql and stuff

**Comment by LegitSoulja** [comment]
And you need PHP to work with MySQL lol.

**Comment by Andrews54757** [comment]
it doesnt matter as making a website is not that important

**Comment by LegitSoulja** [comment]
SEO doesn't agree with that statement. Theres alot of importance of a website. Have you heard of the term crap before?

**Comment by Megabyte918** [comment]
@LegitSoulja hi

**Comment by Andrews54757** [comment]
i feel like iwe dont need a website for ogarul

**Comment by Megabyte918** [comment]
I feel the same way

**Comment by firelightning13** [comment]
lol

**Comment by Lukkez** [comment]
I can just make Ogar-unlimited.tk or another free domain if you guys accept work on a client, i have 1 host who allow 100gb per month

**Comment by Megabyte918** [comment]
not worth the effort, ogarul isn't popular enough that people will visit the site often no offense

**Comment by hassanila97** [comment]
OVH is the cheapest and best.. also if you want free then use amazon 1gb ram ec2 allOS free for 1 year
