### ISSUE TITLE
NodeJs ?!

### ISSUE THREAD

**Issue by NoorAgario** [AJS-development/Ogar-unlimited#487]
hey , I know this isn't related to OgarUn 
but  what is the best place to learn NodeJs (on the internet) ?! btw is OgarUn made with Node /?!

I'm 14 and I will be having tons of free time when I finish my school , I don't know anything about Java/Node

**Comment by LegitSoulja** [comment]
Learning node is really easy of you understand JavaScript and jQuery. http://nodejs.org give you an API docs of a few of there operations and how it works.

OgarUnlimited is with nodejs but structure is different. If you wanted to learn node & ogar observe the file and learn how things operate. 

Theres also a thing called 'npm' which are like add on packages/libraries. Most npm libraries themself comes with a document on how to use that package/library. L

Java is not node btw. Nodejs is pure JavaScript and jQuery syntax, envolving into ES6. Java is a different oriented language that is different from JavaScript

**Comment by Andrews54757** [comment]
npm is annoying

**Comment by LegitSoulja** [comment]
I agree.

**Comment by MichaelLeeHobbs** [comment]
@Andrews54757 @LegitSoulja NPM is AMAZING! You only think it is annoying because you have never had to deal with libraries with out it. Imagine trying to install all those libraries with out it.

@NoorAgario Checkout www.freecodecamp.org

**Comment by Andrews54757** [comment]
i dont hate npm, i use npm alot but i think it is really annoying sometimes.
