### ISSUE TITLE
C9 Is banning accounts!

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#489]
I saw my 2 acconts of c9 is blocked, they blocking accounts who make servers, like ogar, feeder bots, etc, i got blocked but i have another pc who i can acess my 3rd acc with some backups!

**Comment by Lukkez** [comment]
So, we only can make with koding now :/

**Comment by Agarian** [comment]
WTF

**Comment by Agarian** [comment]
Pls tell me this isn't true... if its true, they havent banned me yet

**Comment by LegitSoulja** [comment]
LOL

**Comment by LegitSoulja** [comment]
Bots probably was the reason. I don't blame them. And plus its free hosting 😂😂. Host yourself on dedicated servers or buy hosting. That simple.

**Comment by ErikParacelsus** [comment]
Thank you for the info

**Comment by Agarian** [comment]
were u blocked?

**Comment by Andrews54757** [comment]
i did not get blocked.

**Comment by Andrews54757** [comment]
if I get blocked, they are going to wish they never blocked me in the first place

**Comment by LegitSoulja** [comment]
@Andrews54757 it doesn't matter to them if its free hosting. And I'm 100% sure data will be destroyed on account termination.

**Comment by Andrews54757** [comment]
nope, i did some research and found out: https://community.c9.io/t/a-backup-for-blocked-account/669

**Comment by Lukkez** [comment]
I was having a "modified" ogar-feeder-bot to test with OgarUL, with 5 only proxies,  5 proxies will not consume much bandwidth and i was having 2 OgarUL servers :/ and i can't make new accs, i will use koding

**Comment by Andrews54757** [comment]
well, they ban accounts that use bots

**Comment by hassanila97** [comment]
Well...  why not use amazon ec2.. there no one cares about if you can use bots or not.. and it has 1gb ram all OS

**Comment by XxRaizerxX** [comment]
o_o

**Comment by hassanila97** [comment]
Q_Q

**Comment by firelightning13** [comment]
well dont use bots then

**Comment by Lukkez** [comment]
Isn't bot's fault, 5 proxies with 100 kbps , c9.io you can use max 100~200gb per month, i used 5gb all this month, LOL

**Comment by Lukkez** [comment]
And, i got my account re-open, it was a hacker trying to change my pass all times, solved =p

**Comment by Lukkez** [comment]
![image](http://i.imgur.com/iCbIoA3.png) The account is restoring files

**Comment by Lukkez** [comment]
And as @hassanila97 I will get a Amazon EC2, 3 years later, i have just 14 years lol (Don't say i'm kid)

**Comment by hassanila97** [comment]
Just get a fake cc with atleast 1$ and you're done.. I wont give any tips to how to do..
