### ISSUE TITLE
Cant add bots?

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#49]
Downloaded your new verison, now when i type addbot 5 agario crashes lol

**Comment by elitajmx** [comment]
Also, whatsup with the OP thing? doesnt work anymore pressing q?

**Comment by elitajmx** [comment]
oh nevermind with the op, i had some problems hah

**Comment by Andrews54757** [comment]
Can you show me your error messgae?

**Comment by Andrews54757** [comment]
It works fine for me

**Comment by elitajmx** [comment]
oh wtf now the bots work... thats weird

**Comment by elitajmx** [comment]
how can i use bots/minions?

**Comment by Andrews54757** [comment]
do addbot [number]

**Comment by elitajmx** [comment]
now it does this same error again i was just playing it worked now again:
TypeError: Cannot read property 'name' of undefined
    at GameServer.liveconsole
and so on

**Comment by elitajmx** [comment]
works again.. so weird wtf

**Comment by Andrews54757** [comment]
Are you using that latest version? You can tell if you have the reset comannd

**Comment by Andrews54757** [comment]
Restart command

**Comment by Andrews54757** [comment]
If you dont have the restart command, than thats the issue

**Comment by Andrews54757** [comment]
My guess is also that you are using live console
