### ISSUE TITLE
Bots that team: See progress at the team branch!

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#490]

**Comment by Agarian** [comment]
Cool

**Comment by Lukkez** [comment]
Great

**Comment by PrinceDark9243** [comment]
COOLEST THING EVERY IN OGAR UN THANKS! @Andrews54757

**Comment by PrinceDark9243** [comment]
i test team branch when i add bots the console is full of this text `ok true` and Sometime this `team timeout` But i dident see any bot teaming they just eject mass lol!

**Comment by firelightning13** [comment]
wew kewl cnt w8 to try m8

**Comment by Andrews54757** [comment]
its not finished

**Comment by PrinceDark9243** [comment]
Make that bots will team with players wow m8 i cnt w8!

**Comment by elitajmx** [comment]
ow boi dis oger onlimetid is su f8kng koll, i kentt ' w8 4 2 morrow wen bots wil be rlsd + wed on egeril.420

**Comment by Megabyte918** [comment]
I added 20 bots with 3gb of ram dedicated to my server and vanilla map values and it lagged like crap what the hell

**Comment by Agarian** [comment]
Tomorrow?

**Comment by Andrews54757** [comment]
I dont understand what you just said

**Comment by Lukkez** [comment]
@elitajmx Please don't use drugs :smiley: 
><del>Jk, i know who are trying to be *MLG*</del>

**Comment by Megabyte918** [comment]
Will it be like w-teaming, or split teaming?
and btw @LegitSoulja now's your chance too contribute haha

**Comment by Agarian** [comment]
i think both m8

**Comment by PrinceDark9243** [comment]
make bots to team with players.

**Comment by Agarian** [comment]
have patience

**Comment by XxRaizerxX** [comment]
add w teaming and splitting and feeding the bot and the bot feed you then the bot split then the bot feed you but splitrun i think will be too much stress for you guys

**Comment by firelightning13** [comment]
have patience Andrews know what hes doing

**Comment by PrinceDark9243** [comment]
everything hard working doing server making improvement and other useless thing F*CK MoneyClip(MiniClip) They Disabled every Private server you can only play with A CLient!

**Comment by ItzLevvie** [comment]
Private Servers still works, you just've to update the packets to comply with the new update.

**Comment by NatsuTheGreat** [comment]
@ItzLevvie Have you succeeded with that?

**Comment by Megabyte918** [comment]
@ItzLevvie wish i'd known that before

**Comment by Andrews54757** [comment]
Postponed

**Comment by Agarian** [comment]
:(

**Comment by problemsofworld** [comment]
how to use team branch
