### ISSUE TITLE
Request Plugins

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#492]
**YAY**!. 

> I love the new plugin implementations  :+1: - _@LegitSoulja_

 Which means, You now have time to spread ideas of what you really want implemented into OgarUL. Share your ideas below, and maybe a plugin will be created with your idea if it can happen. 

**Remember**  - 
When requesting plugins, You will be alerted if someone takes your idea and decides to develop it, And you will be alerted again when your idea/plugin is created.

**Developers** -
Take your roll in coming here and discussing information about plugins. Once your plugin has been created contact @Andrews54757 for submission to the OgarUL Plugin Library. Please make sure you fully tested your creation and make sure that it works before submitting. Please included the ideal thoughter who came up with the plugin also with the plugin submission.

**Requesters** -
**PLEASE!!!** Do not spam requests to make a plugin. We will soon get to you if we decide to. If we don't just be patient and wait for a reply about the idea. You'll eventually get one in return. 

`node Let's get baking`

**Comment by LegitSoulja** [comment]
Request plugins here >> [OgarUL-Plugin-Library](https://github.com/AJS-development/OgarUL-Plugin-Library/issues/2)

**Comment by Megabyte918** [comment]
@LegitSoulja should I close this?

**Comment by Agarian** [comment]
@Megabyte918 Why do you keep changing your cover photo to so many creepy things? lol

**Comment by ItzLevvie** [comment]
lol

**Comment by LegitSoulja** [comment]
@Agarian @Megabyte918 he finally realized 😂😂

**Comment by Agarian** [comment]
actually i knew for a while :P

**Comment by Megabyte918** [comment]
uh oh... uh...  um..

**Comment by Agarian** [comment]
@Megabyte918 check ur pm on discord
