### ISSUE TITLE
Adding more members to AJS dev

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#493]
Hello, I am announcing that I will add 5, and only 5 more people to the AJS dev group. Permissions include

1. Ogar-Unlimited
2. Ogar-Client
3. Ogar-Ul-Plugin-Library

Here are the five slots

1. @Megabyte918 
2. @LegitSoulja
3. @NatsuTheGreat 
4. 
5.

**Comment by LegitSoulja** [comment]
@Andrews54757 Permissions? Like work in those areas?

**Comment by Andrews54757** [comment]
Yep

**Comment by LegitSoulja** [comment]
Sounds good, I wouldn't mind.

**Comment by Agarian** [comment]
You should add retslac maybe

**Comment by Andrews54757** [comment]
already did but he declined saying he has no time

**Comment by Agarian** [comment]
Ok

**Comment by XtremePlayzCODE** [comment]
Can you please add me?

**Comment by LegitSoulja** [comment]
@XtremePlayzCODE 
after this
[WTF](https://github.com/XtremePlayzCODE/randmath/blob/master/index.html)
&
[LOL](http://stackoverflow.com/questions/36852806/javascript-pick-a-random-equation-with-random-numbers?noredirect=1#comment61277382_36852806)

Do you have experience bro?

**Comment by XtremePlayzCODE** [comment]
@LegitSoulja You are such a rude person, you know that? I have experience, but when I made that it was 3:00 AM.

**Comment by Andrews54757** [comment]
Hey, i also use stackoverflow

**Comment by Andrews54757** [comment]
well i used to

**Comment by XtremePlayzCODE** [comment]
@LegitSoulja See? Even good coders use it

**Comment by XtremePlayzCODE** [comment]
So, am I in?

**Comment by XtremePlayzCODE** [comment]
I report issues often so other users can enjoy this better with no errors.

**Comment by LegitSoulja** [comment]
@XtremePlayzCODE using stackoverflow doesnt mean you are a good coder. I use it sometimes to find solutions to stuff im working on, or if I need help, But I barely use it.

**Comment by Andrews54757** [comment]
(actually,most in the dev world uses it. even people who programs for a living use it)  and @XtremePlayzCODE il think

**Comment by Andrews54757** [comment]
(but there are actualy dumb questions in stackoverflow)

**Comment by XtremePlayzCODE** [comment]
@Andrews54757 I am actually working on a plugin for minion command rn.

**Comment by XtremePlayzCODE** [comment]
LegitSoulja: Yeah, like Xtreme's question

**Comment by XtremePlayzCODE** [comment]
@LegitSoulja You really think that's funny?

**Comment by Andrews54757** [comment]
@XtremePlayzCODE  Its impossible. I didnt add the functionality for plugins to do that yet

**Comment by XtremePlayzCODE** [comment]
I was failing tbh lol

**Comment by XtremePlayzCODE** [comment]
i tried to fs.writeFileSync it, but i didnt since errors

**Comment by Andrews54757** [comment]
Plugins are basic for now, will be even more advanced. Although there are ways to get over it. like I did with the ogarconsoleinstaller plugin that installs ogarconsole

**Comment by XtremePlayzCODE** [comment]
LegitSoulja made oc, you made the plugin.. right?

**Comment by Andrews54757** [comment]
I dont know why you would need to use fs

**Comment by XtremePlayzCODE** [comment]
yeah me neither

**Comment by LegitSoulja** [comment]
@XtremePlayzCODE Whats the reason to write to a file?

**Comment by Andrews54757** [comment]
do you know what fs does?

**Comment by Andrews54757** [comment]
@XtremePlayzCODE

**Comment by XtremePlayzCODE** [comment]
delete the old minion.js, and add a new one with some features

**Comment by Andrews54757** [comment]
(facepalm)

**Comment by XtremePlayzCODE** [comment]
lol

**Comment by LegitSoulja** [comment]
@XtremePlayzCODE you dont need to add extra things to modify the actual ogarul.. Just edit it yourself.. Customize it the way you like

**Comment by XtremePlayzCODE** [comment]
Well i would like to add a new command to the public

**Comment by XtremePlayzCODE** [comment]
But i cant cuz i cant commit

**Comment by XtremePlayzCODE** [comment]
Im not part of AJS

**Comment by LegitSoulja** [comment]
oh yea, well i'd just wait until theres more advanced features to plugins. Then maybe you could

**Comment by XtremePlayzCODE** [comment]
yeah :/

**Comment by XtremePlayzCODE** [comment]
oh so now your so nice mr. i have no experience?

**Comment by Andrews54757** [comment]
adding commands is already implemented though

**Comment by Andrews54757** [comment]
but editing the minions isnt

**Comment by LegitSoulja** [comment]
and you dont have to be a part of ajs to modify ogarul. You just need to stay away from updates because it might overwrte files.

**Comment by XtremePlayzCODE** [comment]
i also need to edit commandlist

**Comment by XtremePlayzCODE** [comment]
anyways, can i be a member or not?

**Comment by Andrews54757** [comment]
no, i implemented it, a long time ago. It was the first thing i implemented when making plugins.

**Comment by Andrews54757** [comment]
look at the example plugin to see

**Comment by Andrews54757** [comment]
it adds a `tptoplayer` command

**Comment by XtremePlayzCODE** [comment]
no to what again?

**Comment by LegitSoulja** [comment]
@Andrews54757 You can make commands.. [Plugin Tutorial](https://github.com/AJS-development/OgarUL-Plugin-Library) But there's no minion support.

**Comment by Andrews54757** [comment]
@LegitSoulja It is possible but that would take advanced programming but most people cant. (like i did with your ogarconsole)

**Comment by XtremePlayzCODE** [comment]
Is me in or nah?

**Comment by LegitSoulja** [comment]
@Andrews54757 Yea i seen, and you can delete this [repo](https://github.com/AJS-development/OgarConsoleInstaller) too

**Comment by Megabyte918** [comment]
Oh cool, thanks Andrew

**Comment by Lukkez** [comment]
I wasn't have option to update things, "only" pull requests i'm going to fix some things

**Comment by Andrews54757** [comment]
what do you mean?  i gave you guys full access

**Comment by LegitSoulja** [comment]
@Lukkez you should have access. I have it also. It been working for me every since day 1.

**Comment by NatsuTheGreat** [comment]
@Andrews54757 May I join the development?

**Comment by Andrews54757** [comment]
ok

**Comment by XtremePlayzCODE** [comment]
Yes, I would like to fix a few things but I can only pull request

**Comment by XtremePlayzCODE** [comment]
And add a command

**Comment by Andrews54757** [comment]
what command

**Comment by XtremePlayzCODE** [comment]
A command :)

**Comment by XtremePlayzCODE** [comment]
Like,
`minion 1 1 bot`
that type.

**Comment by Andrews54757** [comment]
?

**Comment by LegitSoulja** [comment]
@XtremePlayzCODE lol show me how to create a command, and use it.

**Comment by LegitSoulja** [comment]
@XtremePlayzCODE Make an example plugin you are trying to make

**Comment by XtremePlayzCODE** [comment]
A new minion command

**Comment by XtremePlayzCODE** [comment]
A better one

**Comment by XxRaizerxX** [comment]
Sir ? may i ?

**Comment by XxRaizerxX** [comment]
Join?

**Comment by XxRaizerxX** [comment]
Do i need to code to join
Which code do i need to learn more on

**Comment by LegitSoulja** [comment]
@XxRaizerxX everything is nodejs obviously.

**Comment by LPArigma** [comment]
Requirements to join? details please? I know about 85% js.

**Comment by XxRaizerxX** [comment]
ohhh ok

**Comment by XxRaizerxX** [comment]
how much do i need to know

**Comment by LegitSoulja** [comment]
@XxRaizerxX the entire nodejs environment. I know a wide range of languages. I've been coding for 15+ more years. I started coding when I was 7. I had my first computer when I was 5. Haha. I never been to college though. I self taught myself. I was more into developing games, and websites, and etc. I've been coding javascript for a long time, and nodejs was a new thing to me in 2015. If you know javascript, and go over nodejs docs, You learned nodejs. But theres extra libraries too you have to understand, and know hot it works, which is part of the node package manager.

**Comment by LPArigma** [comment]
@LegitSoulja i know javaScript mostly and im still learning things here and there, but is there like a way we have to prove that we are worthy?

**Comment by XxRaizerxX** [comment]
i am 17% through java
but i forgot most of it

**Comment by XxRaizerxX** [comment]
what coding website do you use

**Comment by LegitSoulja** [comment]
@LPArigma We could determine that if you had any work on github you have done to see the level of your coding experience. But you dont have any projects to base your experience off of.

**Comment by LegitSoulja** [comment]
@XxRaizerxX I used netbeans with nodejs. And i code websites using codeanywhere. Its a pretty nice file editor. I used it with ftp. edit my site on the dot :)

**Comment by LegitSoulja** [comment]
@LPArigma but after all. I dont know how andrew is accepting people. Im basing on you need coding experience. I mean, why be part of something with no experience?

**Comment by LPArigma** [comment]
I'm a new member to github and forums, i normally don't talk or make accounts on forums but i decided to give it a try on github since i use it alot. So yes my account is new and im new to github but i also know other languages too, im working on my webserver homepage right now and i want to host a agar server from that machine that i built (sorta what i built it for) so even if im not able to join id still be willing to help out and lend a hand if needed.

**Comment by LPArigma** [comment]
@XxRaizerxX I use eclipse for Nodejs, i like the ui and the color theme of it.

**Comment by XxRaizerxX** [comment]
i really wanna know how to code but its too hard :'( i wish i could have some1 to teach me to code chatting with me when i need help

**Comment by XxRaizerxX** [comment]
i sit doing code cademy doing 1 problem in javascript for hours still not figuring it out

**Comment by LegitSoulja** [comment]
@XxRaizerxX well, looks like you need to learn javascript & jquery before you learn nodejs. You have alot of work to do.

**Comment by XxRaizerxX** [comment]
do i have to do something before javascript like which one is the easiest

**Comment by LegitSoulja** [comment]
@LPArigma I only use eclipse and intellij with java.. I never knew eclipse using nodejs..

**Comment by LPArigma** [comment]
@XxRaizerxX i remeber codeacademy, thats what got me kickstarted in html and js

**Comment by LPArigma** [comment]
@LegitSoulja you can import the libraries if you have access to them on eclipse

**Comment by XxRaizerxX** [comment]
i cant wait till i complete code cademy and i wont get picked on by people who can code and i cant

**Comment by LegitSoulja** [comment]
@XxRaizerxX nope, theres no easier way, or an easier language to learn. Javascript is the starter. I mean you can learn java, and then go to javascript and might get a better understanding.. But java is alot to learn and understand, and plus java is no where related to javascript, but has similar ways since its object oriented.

**Comment by LegitSoulja** [comment]
@LPArigma does eclipse come with nodejs support? Like a output console & abilities to upload to github? and also other nodejs functionalities?

**Comment by XxRaizerxX** [comment]
this is the one i suck at https://www.codecademy.com/courses/getting-started-v2/3/4?curriculum_id=506324b3a7dffd00020bf661

**Comment by LPArigma** [comment]
@LegitSoulja No, i had a buddy of mine modify it for me to support nodejs. You can find it somewhere on the internet and you could prob find a github plugin for it too

**Comment by XxRaizerxX** [comment]
w8 nvm i just did **(*10 % 2 === 0 )** {
    console.log("The first number is even");
} else {
    console.log("The first number is odd");
}

**Comment by XxRaizerxX** [comment]
:D

**Comment by LegitSoulja** [comment]
@XxRaizerxX  LOL read and understand what it means. It wanted a else function that prints out an odd number which will return true. 5 % 5 outputs 1.. 10 % 2 outputs 0

**Comment by XxRaizerxX** [comment]
oh

**Comment by XxRaizerxX** [comment]
but explain this https://www.codecademy.com/courses/getting-started-v2/3/5?curriculum_id=506324b3a7dffd00020bf661# wtf

**Comment by LegitSoulja** [comment]
Thats easy also.. (facepalm). Only thing you are doing is getting the char of a string.. well that char value in the string actually. You can split a string a get whatever first or second child of the string.. So for example

var string = "ogar";
string.substring(2,4);

// output: ar

**Comment by LegitSoulja** [comment]
@XxRaizerxX  so your answer would be
```
var string = "wonderful day";
string.substring(3, 7);
```

**Comment by XxRaizerxX** [comment]
"wonderful day".substring(0, 14);

**Comment by XxRaizerxX** [comment]
oh i have to turn it around

**Comment by LegitSoulja** [comment]
Where you get 14 from??

**Comment by XxRaizerxX** [comment]
idk its the length of  wonderful day together

**Comment by LegitSoulja** [comment]
The value is 13.. Not 14

**Comment by XxRaizerxX** [comment]
oh then whats half of 13?

**Comment by XxRaizerxX** [comment]
6 1/2?

**Comment by LegitSoulja** [comment]
Yes 6 1/5

**Comment by LPArigma** [comment]
@XxRaizerxX it says to make it so you start at the 4th character of the string not 0

**Comment by LegitSoulja** [comment]
@LPArigma  you start at 3 to 7 -_-

**Comment by LegitSoulja** [comment]
Well im gonna go while you guys go learn how to code

**Comment by LegitSoulja** [comment]
@Andrews54757 you decide what you want to do with these 2 lol

**Comment by LPArigma** [comment]
@XxRaizerxX @LegitSoulja its so simple lol `"wonderful day".substring( 3, 7);
`

**Comment by LegitSoulja** [comment]
@LPArigma  [smh](https://github.com/AJS-development/Ogar-unlimited/issues/493#issuecomment-217036191)

**Comment by LPArigma** [comment]
@LegitSoulja you dont need to localize "wonderful day" or execute it to an output with code academy lol

**Comment by LegitSoulja** [comment]
@LPArigma I was not referring to code academy. I was giving him an example.

**Comment by XxRaizerxX** [comment]
the next 1 i did console.log( "ogar".substring(2, 4) );
and it said this Oops, try again. You didn't select the right substring from 'January'. 
i mean wtf does it mean by January what the fuck does that mean

**Comment by XxRaizerxX** [comment]
WHY CANT I DO MY OWN SUBSTRING

**Comment by LPArigma** [comment]
@LegitSoulja ik but he wanted help with codeacademy and it only accepts it a special way :/

**Comment by LegitSoulja** [comment]
@LPArigma actually, You dont have to do it a specific way. What I wrote for him still works in codeanywhere. Its best to write it your own way.

**Comment by LegitSoulja** [comment]
@XxRaizerxX maybe you should use January instead of Ogar..

**Comment by XxRaizerxX** [comment]
same it wont work its not right substring

**Comment by XxRaizerxX** [comment]
console.log( "January".substring(3, 7) );

**Comment by LegitSoulja** [comment]
Read the instructions on how to do it.

**Comment by XxRaizerxX** [comment]
console.log( "January".substring(0, 7) ); still not workin

**Comment by LPArigma** [comment]
@XxRaizerxX `console.log("January".substring(0,3))
console.log("Melbourne is great".substring(0,13))
console.log("Hamburgers".substring(3,10))`

**Comment by LPArigma** [comment]
> console.log("January".substring(0,3));
console.log("Melbourne is great".substring(0,13));
console.log("Hamburgers".substring(3,10));<

**Comment by LegitSoulja** [comment]
@XxRaizerxX thats valid.. That outputs the enire word.

**Comment by XxRaizerxX** [comment]
oh so u do them all

**Comment by LegitSoulja** [comment]
No

**Comment by XxRaizerxX** [comment]
i though those where other examples

**Comment by LegitSoulja** [comment]
Read the Instructions!!. We are giving you examples.

**Comment by LPArigma** [comment]
@XxRaizerxX it you use the variable for the start point and end point of the string you want to output

**Comment by LPArigma** [comment]
your putting the whole string in the variables bracket, you want to count the letters and put the startpoint as X and the end point of the variable you want to output as Y in the format (X,Y)

**Comment by XxRaizerxX** [comment]
ok 
then i did 2 more of the codes after that they where easyy

**Comment by XxRaizerxX** [comment]
i mean i did 1
more

**Comment by LPArigma** [comment]
@XxRaizerxX now do you get it?

**Comment by LPArigma** [comment]
@XxRaizerxX ask us if you need any more help!

**Comment by XxRaizerxX** [comment]
no

**Comment by XxRaizerxX** [comment]
how do you guys do all this functions when your making code like this. and split and dotsplit do i learn that in coding?

**Comment by LegitSoulja** [comment]
@XxRaizerxX @LPArigma You should discuss this over skype or some other chat service. I dont want this issue without tons of comments thats not even related to the topic.

**Comment by LPArigma** [comment]
@XxRaizerxX I learned js and nodejs from exploring it on my own so do what works for you, i'm going to stop talking because @LegitSoulja is correct, we are blowing this issue up with tons of irrelevant comments

**Comment by XxRaizerxX** [comment]
lol 139 comments

**Comment by LegitSoulja** [comment]
@LPArigma Thanks for your cooperation.

**Comment by Megabyte918** [comment]
it took me like 10 minutes to read all of these holy crap

**Comment by XtremePlayzCODE** [comment]
@Megabyte918 true dat

**Comment by XxRaizerxX** [comment]
hey @XtremePlayzCODE

**Comment by XtremePlayzCODE** [comment]
The only thing i've been doing since like a week ago is making fb bots work again

**Comment by XtremePlayzCODE** [comment]
like ffs

**Comment by LegitSoulja** [comment]
@Megabyte918 you pretty much just wasted 10 minutes of your life lol

**Comment by XxRaizerxX** [comment]
Xtreme wanna team? sorry  just wanna test your skillz ;)

**Comment by XtremePlayzCODE** [comment]
Oh your teaming with a pro den

**Comment by XtremePlayzCODE** [comment]
Get a party

**Comment by XxRaizerxX** [comment]
no server

**Comment by XxRaizerxX** [comment]
http://agar.io/?ip=ogar-unlimited-raizer.c9users.io/

**Comment by XxRaizerxX** [comment]
:D

**Comment by XtremePlayzCODE** [comment]
http://agar.io/?ip=xtreme-botz-2-0-demo-xtremeplayzcode.c9users.io

**Comment by XtremePlayzCODE** [comment]
fak

**Comment by XtremePlayzCODE** [comment]
mines better

**Comment by LegitSoulja** [comment]
@XtremePlayzCODE @XxRaizerxX go to http://agariohub,tk

**Comment by XtremePlayzCODE** [comment]
no

**Comment by XtremePlayzCODE** [comment]
im in raizer

**Comment by XxRaizerxX** [comment]
im in your server

**Comment by XtremePlayzCODE** [comment]
wtf

**Comment by XtremePlayzCODE** [comment]
ok then my server

**Comment by XxRaizerxX** [comment]
xD

**Comment by XtremePlayzCODE** [comment]
where r u

**Comment by XxRaizerxX** [comment]
i  cant get in i think

**Comment by XxRaizerxX** [comment]
im not in

**Comment by XtremePlayzCODE** [comment]
try again

**Comment by XxRaizerxX** [comment]
your servers not workin

**Comment by XtremePlayzCODE** [comment]
http://agar.io/?ip=xtreme-server-xtremeplayzcode.c9users.io

**Comment by XxRaizerxX** [comment]
im in

**Comment by XxRaizerxX** [comment]
the lag of the bots is bad

**Comment by LegitSoulja** [comment]
Please @XxRaizerxX  && @XtremePlayzCODE take the chat somewhere else!!.
https://gitter.im/AJS-development/Ogar-unlimited

Thanks!..

**Comment by LegitSoulja** [comment]
You guys are blowing up my phone with the comments, with the emails. Please stop.

**Comment by XxRaizerxX** [comment]
ok

**Comment by XtremePlayzCODE** [comment]
says you you had a converstion

**Comment by LegitSoulja** [comment]
@XtremePlayzCODE Yea and you guys are adding more comments to this page.. I dont think nobody wants to even come here nomore just because there so many comments now. What you guys are talking about is off topic to this issue. I know I was too, but im just asking could it stop.

**Comment by XxRaizerxX** [comment]
bots stop them the lag

**Comment by XxRaizerxX** [comment]
damnit

**Comment by XxRaizerxX** [comment]
STOP THE MOTHER FU*****BOTS GOT DAMN** FOR GOD SAKE My pc just freaked out

**Comment by Agarian** [comment]
i was thinking about adding a new command via plugins lol

**Comment by Agarian** [comment]
Raizer calm down lol

**Comment by XxRaizerxX** [comment]
lol this guy doe

**Comment by XxRaizerxX** [comment]
makin me mad

**Comment by Agarian** [comment]
who tf?

**Comment by XxRaizerxX** [comment]
xD I got mad irl and threw my headphones across my house and something broke

**Comment by XxRaizerxX** [comment]
its Xtreme

**Comment by Agarian** [comment]
irl?

**Comment by XxRaizerxX** [comment]
in real life

**Comment by Agarian** [comment]
i may start using that irl

**Comment by XxRaizerxX** [comment]
ok xD

**Comment by XxRaizerxX** [comment]
every time i get mad i think about my girlfriend and that time i forgot to when i threw my headphones

**Comment by XxRaizerxX** [comment]
AND THIS GUY KEEPS ON Freaking killing me

**Comment by XxRaizerxX** [comment]
WTF IS WRONG WITH THIS GUY

**Comment by XxRaizerxX** [comment]
IS HE FREAKING BLIND I HAVE FUCKING LOST MY TEMPER WHAT THE FUCK XTREME PLAYS MAN WHAT THE FUCK ARE YOU DOING WHY DO YOU KEEP KILLING ME

**Comment by Andrews54757** [comment]
Im locking this and reopening
