### ISSUE TITLE
Error with nodejs

### ISSUE THREAD

**Issue by ALBABOY** [AJS-development/Ogar-unlimited#494]
Does Ogar-unlimited work on the centos 6.7 x64 O.S.
because i have this bug showing up please tell me how can i fix it ?
process.on('exit', (code) => {
                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

**Comment by LegitSoulja** [comment]
@ALBABOY What version of node are you running?

**Comment by Andrews54757** [comment]
search up how to update nodejs on google

**Comment by ALBABOY** [comment]
nodejs-0.10.44

**Comment by Andrews54757** [comment]
update your nodejs by doing

1. `sudo npm cache clean -f`
2. `sudo npm install -g n`
3. `sudo n stable`

**Comment by Andrews54757** [comment]
then run it

**Comment by ALBABOY** [comment]
i already did it !

**Comment by Andrews54757** [comment]
now what is the version?

**Comment by Andrews54757** [comment]
`node -v`

**Comment by ALBABOY** [comment]
wait a second because i rebuild my system

**Comment by Andrews54757** [comment]
if it still doesnt work then try doing
`sudo n 4.2.6`

**Comment by LegitSoulja** [comment]
@ALBABOY 
Update node to v5.9.0 or higher to resolve this error. Closing issue.

**Comment by ALBABOY** [comment]
Guys im still facing the problem !!
please help me !
this is what i have tried !

[root@albaboy src]# sudo npm cache clean -f
npm WARN using --force I sure hope you know what you are doing.
[root@albaboy src]# sudo npm install -g n
/usr/bin/n -> /usr/lib/node_modules/n/bin/n
n@2.1.0 /usr/lib/node_modules/n
[root@albaboy src]# sudo n stable

     install : node-v6.0.0
       mkdir : /usr/local/n/versions/node/6.0.0
       fetch : https://nodejs.org/dist/v6.0.0/node-v6.0.0-linux-x64.tar.gz
######################################################################## 100.0%
   installed : v0.10.44

[root@albaboy src]# node index.js

/home/Ogar/src/index.js:3
const Readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
[root@albaboy src]#

**Comment by LegitSoulja** [comment]
@ALBABOY 
I've had the same problems like you had. This is how I fixed my problem

1. Run 'node -v' it should be v5.9.0 or higher. Not v0.10.44
2. Uninstall node
3. Run 'node -v' (Should return node undefined since its uninstalled) if it still returns the node version then you have node installed somewhere else aswell and need to be uninstalled. If node returns a version run 'where node' then go that directory and uninstall it.
4. Install node [v5.9.0](https://nodejs.org/download/release/v5.9.0/) which I used and is working
5. After installed run 'node -v' and it should return v5.9.0. If it is you are now good
6. Delete node_modules in OgarUL main directory. Not inside ./src but outside.
7. From outside of ./src run 'node install' 
8. Run OgarUl. Should run file

**Comment by ALBABOY** [comment]
Can you please Give the command on which you install Nodejs because i think this is giving me the problem !
i Install node js with curl ("curl --silent --location https://rpm.nodesource.com/setup | bash -")
please i really need this i really appreciate it if you give me the code

**Comment by LegitSoulja** [comment]
@Andrews54757 can help you. I run windows, im unfamiliar with centOs commands. Sorry

**Comment by LegitSoulja** [comment]
@ALBABOY check out https://nodejs.org/en/download/package-manager/

Just replace the version with the version recommended which was v**5.9.0**

**Comment by Andrews54757** [comment]
@ALBABOY Are you on linux? Because I am a linux user. I simply do `sudo apt-get update` and `sudo apt-get upgrade` and reinstall nodejs by doing `sudo apt-get install nodejs`

**Comment by Andrews54757** [comment]
or you can use the synaptic package manager which is easier (do `sudo apt-get install synaptic`)

**Comment by LegitSoulja** [comment]
@Andrews54757 how to install with a specific version of nodejs. Im using v5.9.0 and no problems. Maybe if he just use that version instead it'll work. I heard megabyte say that there was problems after v6. Idk maybe it been fixed.

**Comment by ALBABOY** [comment]
i use Windows but I manage my Linux centos 6 x64 vps from putty

**Comment by LegitSoulja** [comment]
Ok after you uninstalled did you make sure node didnt exist?

Then you can proceed to reinstall nodejs. After that process delete the **node_modules** folder outside of ./src of ogarul game directory. Then process to execute **npm install**, and maybe one more time just to make sure. Then start the ogarul.

**Comment by LegitSoulja** [comment]
Provide an error responce if you get an error.

**Comment by ALBABOY** [comment]
guys i just successfully runned the Ogar Unlimited Just because you guys helped me !!
i want to thank you guys for replying me 
big love

**Comment by LegitSoulja** [comment]
@ALBABOY No problem. The service was made, and we provide support. We mainly are active doing other work basically 24/7, but maybe not 5 days a week lol. Welcomes, and have fun.

**Comment by ALBABOY** [comment]
i basically reinstalled My vps and then i typed
yum update
then
yum -y install git wget curl
and then i just 
downloaded via curl
curl --silent --location https://rpm.nodesource.com/setup_5.x | bash -
then i installed nodejs 
yum install nodejs and then typed npm install to install node modules inside the ogar folder
i will create a tutorial of how to create a server.

**Comment by firelightning13** [comment]
nice

**Comment by Andrews54757** [comment]
im reopining this because of many similar issues
