### ISSUE TITLE
Lag with 3gb of RAM

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#498]
Hello, the other day I added 15 bots with vanilla map values and 2000 food for foodspawn and start amount and 6000 for foodmaxamount and 1500 for foodminamount (these settings seemed to have the perfect amount of food for the map size). I had 3gb of RAM dedicated to the server and it lagged like CRAP. Is it the vanilla map values? the amount of food? what is making it lag like this? im using the latest version

**Comment by Agarian** [comment]
same happens to me on C9

**Comment by PrinceDark9243** [comment]
i want a 24/7 host can someone tell me with 2gb or higher ram and 1gb space or higher and 24/7 it is good for me

**Comment by Agarian** [comment]
well c9 has 512mb - 1gb ram.

**Comment by Lukkez** [comment]
Well c9 have good cpu for free one =p, @Megabyte918 U need great cpu too

**Comment by LegitSoulja** [comment]
@Lukkez how many mbps does c9 give you? Thats a thing you really need the most.. and also a good cpu.

**Comment by Lukkez** [comment]
I think is arround 75mbps, some workspaces can have 10mbps, rlly

**Comment by LegitSoulja** [comment]
@lukkez 10mbps xDDDDDDDDDDDDDDDDDDDDD.. My servers are running 200mbps and higher on good clean days

**Comment by Lukkez** [comment]
i got one  before with 10mbps, rlly xDDDD, i installed team viewer on it and i saw... my best workspace have 140~150mbps all days :3

**Comment by LegitSoulja** [comment]
@Lukkez thats good atleast. I was telling mega the server strength all runs in the ram, cpu, and connection. Without them 3 being fully supported you will have problems with your servers.

**Comment by hassanila97** [comment]
Also... NodeJS isnt really made for performance..some other lang. like C# C++ is perfect in this case

**Comment by Megabyte918** [comment]
So... any help @AJS-development/ogar-unlimited-devs ?

**Comment by MichaelLeeHobbs** [comment]
@hassanila97 You don't know Node if you think it is not made for performance. Node is written in C and is extremely performant. 

@Megabyte918 I've been working on these issues for a while but they are complex and they take time. Right now my focus is on splitting the code base into multiple processes/servers.

**Comment by Megabyte918** [comment]
@MichaelLeeHobbs alright, thank you
