### ISSUE TITLE
Making a client

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#501]
I'm making a client at ogar-unlimited.tk, which will have all the servers on it, if someone want to help go to my profile and click on "Ogar-unlimited-client" or go to https://github.com/Lukkez/Ogar-unlimited-client

**Comment by Lukkez** [comment]
I know Andrews make a repo here, i don't like to wait all, when the client get the BASE finished i ask Andrews permission to upload on the client repo on AJS-development page, don't worry

**Comment by Lukkez** [comment]
And i need help with js :/ i don't know much js, more html/css

**Comment by LegitSoulja** [comment]
@Lukkez so an illegal client? Or are you making a website with ogar ul games?

**Comment by PrinceDark9243** [comment]
make that client support `E` and `R` keys plz

**Comment by LegitSoulja** [comment]
@Lukkez im down with you, I'm currently working on [OgarHost](https://github.com/LegitSoulja/OgarHost) & [OgarConsole](https://github.com/LegitSoulja/OgarConsole). I can help you with the client if you need help. And also I have some really nice ideas to addon. I see you added bootstrap and such, but i have something even better.

**Comment by Lukkez** [comment]
Isn't illegal client, just a client **LIKE** agar.io with redirect to another servers using agar.io/?ip=

**Comment by Lukkez** [comment]
I will add some plugins later

**Comment by Lukkez** [comment]
@PrinceDark9243 The client wasn't for this, but maybe i can make a tampermonkey extension for that

**Comment by LegitSoulja** [comment]
@Lukkez so kindof like my website? [agariohub](agariohub.tk)

**Comment by Andrews54757** [comment]
OOPS, i accidently put you as read for the client repo, sorry, you have edit acces now

**Comment by Lukkez** [comment]
Yes @LegitSoulja But instead of you use (open tab) i will just redirect to http://agar.io (I don't know a way who is not illegal to put on the same website the server)

**Comment by hassanila97** [comment]
Use an iframe

**Comment by LegitSoulja** [comment]
@Lukkez my site doesnt use open tabs. Im using iframs like @hassanila97 said..

**Comment by NatsuTheGreat** [comment]
We should start making a way to prevent proxies. A lot of programs use SOCKS4, SOCKS5, those types. And as I see, they have an address and a port. e.g: 122.344.544.68:10200 . I was thinking of only allowing connections from serverPort. I do not know if that is possible, I just noticed the different addresses and ports they Proxies use.

**Comment by hassanila97** [comment]
@NatsuTheGreat Not possible

**Comment by LegitSoulja** [comment]
@hassanila97 hmm. I wouldn't say it's not possible. It's possible but may take a lot of work.

**Comment by hassanila97** [comment]
@LegitSoulja  Its actually not possible to see the port of the proxy and even if its a SOCKS proxy there is no way of telling that apart from if you scrape all those free proxy sitest and block all connections from those ips..

**Comment by Agarian** [comment]
we may have to do this now.

**Comment by Andrews54757** [comment]
@LegitSoulja I guess your hub is also broken

**Comment by Lukkez** [comment]
Yea, that's why we need to make a own client, but most here just know js :/ i need css/html too

**Comment by LegitSoulja** [comment]
Im 100% sure everyone here dont know only js.. I mean common.. Thats stupid.. You would have never learned js if you never made a website. Im pretty sure a few people here has alot of experience. Even me. We just dont know nodejs. We know alot. Ogar just runs on nodejs. That's why its a big thing here. But other than that, you'd probably see me somewhere else doing c++ or c# work because c/c++ is my thing. .net c# is a thing i enjoy also.

**Comment by Andrews54757** [comment]
I know HTML. (and some of css) HTML and CSS was the first thing I learned

**Comment by Agarian** [comment]
i have web design A.T.M.

**Comment by Megabyte918** [comment]
I know html and most of CSS and i started js like a couple of weeks ago so i still kind of suck

**Comment by firelightning13** [comment]
Yeah me too i just know basic syntax of js but never learn about nodejs

**Comment by Lukkez** [comment]
I think we will use the leaked client

**Comment by Megabyte918** [comment]
cool
