### ISSUE TITLE
Cannot connect or update in start.bat

### ISSUE THREAD

**Issue by bangana** [AJS-development/Ogar-unlimited#502]
umh so yeahi just downloaded ogar unlimited with an old version if launch it up i typed "update all" it said not connected to servers,update will be aborted :'( i launch it back and i get this error 

module.js:440
    throw err;
    ^

Error: Cannot find module './core/ControlServer'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\PCHP\Desktop\Ogar-unlimited-master\src\src\i
ndex.js:5:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

Press any key to exit...

**Comment by LegitSoulja** [comment]
Download the new version of Ogar Unlimited here. Save your gamesettings.ini. Delete everything from the game folder. Upload the new version of Ogar Unlimited. Run the installation batch or run npm install outside of ./src. Go into settings/override.ini and copy the content from gamesettings.ini and pase it in override.ini. Start the server.

**Comment by bangana** [comment]
i've installed Dependencies (Windows) um it said successfully installed  , sorry i didn't understand i don't find npm ouside of ./src :( and could you please give me link of the newest version ? :hand:

**Comment by LegitSoulja** [comment]
@bangana http://ajs-development.github.io/Ogar-unlimited/

**Comment by LegitSoulja** [comment]
Once you download the new version do these steps.

1. Before you replace your files go to your game directory and save your **gamesettings.ini** file thats stored your game settings **./src/**.
2. Go back outside of **./src/** your game folder. Delete everything in that folder that exist. 
3. Open the **zip** file you downloaded and open the OgarUnlimted folder, and copy all the content from there into the folder you deleted everything from.
4. After everything was copied go into the **/src** folder and run the **Install Dependencies.bat** 
5. Open gamesettings.ini and copy all the text you see by press **ctrl + a**  then **ctrl + c**. 
6. go into your game folder inside **/src** and open the folder **settings** inside **override.ini** place the text you copied from **gamesettings.ini** into **override.ini**.

**Comment by LegitSoulja** [comment]
The start the server afterwards. If you can any errors after starting paste the error here again. Many people are have missing packages errors thats been annoying.

**Comment by bangana** [comment]
sorry but in the new version that i've downloaded i don't have gamesettings.ini :'(

**Comment by LegitSoulja** [comment]
the new version wont have a gamesettings.ini. I said get the old settings from the gamesettings.ini before you replaced the content.

**Comment by LegitSoulja** [comment]
Well now since your old configutation is lost, you have to setup your new configuration in **./settings/advConfig.ini** and **./settings/config.ini**. If you ever recover your **gamesettings.ini** replace the content in **gamesettings.ini** into **./settings/override.ini**

**Comment by bangana** [comment]
the only thing not clear is the first step sorry im getting annoying but ... i wan't to set it up so hard 
what do i need to copy to override.ini

**Comment by LegitSoulja** [comment]
@bangana You need the gameserver.ini file before you deleted and replace everything with the new version. If you got to your recycle bin you can probably find you **src** folder and recover you gamesettings.ini

**Comment by bangana** [comment]
#LegitSoulja sorry none of versions that i've downloaded has gamesettings.ini O_O

**Comment by LegitSoulja** [comment]
@bangana holdon are you downgrading? or upgrading?

**Comment by bangana** [comment]
lol u didn't understand meh i downloaded this version which is not working for me https://codeload.github.com/AJS-development/Ogar-unlimited/zip/master
then i downloaded another one http://download1067.mediafire.com/jz8b68sky4ig/ochfgnjrr5ajpi9/Ogar-unlimited-master.zip wich is working but i can't update it because it's needed and when i type 'update all' it said not connected to servers ,update'll be aborted and i get same problem when i launch the start.bat module.js:440 thing

**Comment by bangana** [comment]
btw the version that u sent to me is not working too im confused AF

**Comment by LegitSoulja** [comment]
@bagana Ok, the media fire one is an old one. It will work, but you are trying to update but you just cant update from this old version to the new version. OgarUnlimited updated alot and its best to download the new content. The old version that you said you used that worked, but trying to update does have a gamesettings.ini. You need to save that file. Delete everything old, upload the new contents. Go into **./src/settings/override.ini** and copy and paste the content from the old gamesettings.ini to the override.ini file.

**Comment by LegitSoulja** [comment]
And im here to help you. You said the new version doesnt work so why try to update from the old version? Just paste me your error log if you get any errors from the new version. Thanks..

**Comment by Andrews54757** [comment]
@bangana You cannot use the update command before version 16.0.0 like @LegitSoulja  said

**Comment by bangana** [comment]
this is the error i get of the new version module.js:440
    throw err;
    ^

Error: Cannot find module 'collections/sorted-map'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\PCHP\Desktop\AJS-development-Ogar-unlimited-
1c654c7\src\core\WorldModel.js:5:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

Press any key to exit...

**Comment by Andrews54757** [comment]
if it is a `cannot find module` error, then do npm install instead of npm install ws. and if it still says that, then do `npm install request`. If the error is like `Unexpected reserved word` then update your nodejs.

**Comment by Andrews54757** [comment]
also, make sure to do npm install after you cd into the repo

**Comment by LegitSoulja** [comment]
@bangana twice or maybe 3 times just to make sure :)

**Comment by bangana** [comment]
Could you talk english pls ? uhm i mean where do i have to type npm stuff in node.js ?

**Comment by Andrews54757** [comment]
if you still cannot do it, google `installing dependencies in npm`

**Comment by Andrews54757** [comment]
there are countless tutorial videos as well

**Comment by bangana** [comment]
i typed npm install request : 
Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits réservés.

C:\Users\PCHP>nmp install request
'nmp' n'est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

C:\Users\PCHP>npm install request
C:\Users\PCHP
+-- request@2.72.0
| +-- aws-sign2@0.6.0
| +-- aws4@1.3.2
| | `-- lru-cache@4.0.1
| |   +-- pseudomap@1.0.2
| |   `-- yallist@2.0.0
| +-- bl@1.1.2
| | `-- readable-stream@2.0.6
| |   +-- core-util-is@1.0.2
| |   +-- inherits@2.0.1
| |   +-- isarray@1.0.0
| |   +-- process-nextick-args@1.0.6
| |   +-- string_decoder@0.10.31
| |   `-- util-deprecate@1.0.2
| +-- caseless@0.11.0
| +-- combined-stream@1.0.5
| | `-- delayed-stream@1.0.0
| +-- extend@3.0.0
| +-- forever-agent@0.6.1
| +-- form-data@1.0.0-rc4
| | `-- async@1.5.2
| +-- har-validator@2.0.6
| | +-- chalk@1.1.3
| | | +-- ansi-styles@2.2.1
| | | +-- escape-string-regexp@1.0.5
| | | +-- has-ansi@2.0.0
| | | | `-- ansi-regex@2.0.0
| | | +-- strip-ansi@3.0.1
| | | `-- supports-color@2.0.0
| | +-- commander@2.9.0
| | | `-- graceful-readlink@1.0.1
| | +-- is-my-json-valid@2.13.1
| | | +-- generate-function@2.0.0
| | | +-- generate-object-property@1.2.0
| | | | `-- is-property@1.0.2
| | | +-- jsonpointer@2.0.0
| | | `-- xtend@4.0.1
| | `-- pinkie-promise@2.0.1
| |   `-- pinkie@2.0.4
| +-- hawk@3.1.3
| | +-- boom@2.10.1
| | +-- cryptiles@2.0.5
| | +-- hoek@2.16.3
| | `-- sntp@1.0.9
| +-- http-signature@1.1.1
| | +-- assert-plus@0.2.0
| | +-- jsprim@1.2.2
| | | +-- extsprintf@1.0.2
| | | +-- json-schema@0.2.2
| | | `-- verror@1.3.6
| | `-- sshpk@1.8.3
| |   +-- asn1@0.2.3
| |   +-- assert-plus@1.0.0
| |   +-- dashdash@1.13.1
| |   | `-- assert-plus@1.0.0
| |   +-- ecc-jsbn@0.1.1
| |   +-- getpass@0.1.6
| |   | `-- assert-plus@1.0.0
| |   +-- jodid25519@1.0.2
| |   +-- jsbn@0.1.0
| |   `-- tweetnacl@0.13.3
| +-- is-typedarray@1.0.0
| +-- isstream@0.1.2
| +-- json-stringify-safe@5.0.1
| +-- mime-types@2.1.11
| | `-- mime-db@1.23.0
| +-- node-uuid@1.4.7
| +-- oauth-sign@0.8.1
| +-- qs@6.1.0
| +-- stringstream@0.0.5
| +-- tough-cookie@2.2.2
| `-- tunnel-agent@0.4.2
`-- vuvuzela@1.0.3

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\PCHP\package.j
son'
npm WARN PCHP No description
npm WARN PCHP No repository field.
npm WARN PCHP No README data
npm WARN PCHP No license field.

C:\Users\PCHP>

**Comment by LegitSoulja** [comment]
@bangana You need to cd to the directory first before running that command. You just install unessarry packages. 

type

> cd C:\Users\PCHP\Desktop\Ogar-unlimited-master\src

then

> npm install

**Comment by bangana** [comment]
im done ........ could someone please just make a simple tutorial kuz im getting pissed again thanks very much for ur help im a Douche ... @_@

**Comment by bangana** [comment]
@LegitSoulja  i did what'u said 
Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits réservés.

C:\Users\PCHP>cd C:\Users\PCHP\Desktop\Ogar-unlimited-master\src

C:\Users\PCHP\Desktop\Ogar-unlimited-master\src>npm install
npm WARN prefer global node-ninja@1.0.1 should be installed with -g
npm WARN prefer global node-gyp@3.3.1 should be installed with -g

> sqlite3@3.1.3 install C:\Users\PCHP\Desktop\Ogar-unlimited-master\node_modules
\sqlite3
> node-pre-gyp install --fallback-to-build

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Users\PCHP\Desktop\Ogar-unlimited-master\
node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Users\PCHP\Desktop\Ogar-unlimited-master\node_modules\n
ode-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\PCHP\\Desktop
\\Ogar-unlimited-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "
--fallback-to-build" "--module=C:\\Users\\PCHP\\Desktop\\Ogar-unlimited-master\\
node_modules\\sqlite3\\lib\\binding\\node-v48-win32-x64\\node_sqlite3.node" "--m
odule_name=node_sqlite3" "--module_path=C:\\Users\\PCHP\\Desktop\\Ogar-unlimited
-master\\node_modules\\sqlite3\\lib\\binding\\node-v48-win32-x64"
gyp ERR! cwd C:\Users\PCHP\Desktop\Ogar-unlimited-master\node_modules\sqlite3
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.e
xe C:\Users\PCHP\Desktop\Ogar-unlimited-master\node_modules\node-gyp\bin\node-gy
p.js configure --fallback-to-build --module=C:\Users\PCHP\Desktop\Ogar-unlimited
-master\node_modules\sqlite3\lib\binding\node-v48-win32-x64\node_sqlite3.node --
module_name=node_sqlite3 --module_path=C:\Users\PCHP\Desktop\Ogar-unlimited-mast
er\node_modules\sqlite3\lib\binding\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\PCHP\Desktop\O
gar-unlimited-master\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\com
pile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:215:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\PCHP
\\Desktop\\Ogar-unlimited-master\\node_modules\\sqlite3\\node_modules\\node-pre-
gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\PCHP\Desktop\Ogar-unlimited-master\node_modules\s
qlite3
node-pre-gyp ERR! node -v v6.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.25
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\PCHP\Desktop\Ogar-u
nlimited-master\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-bu
ild --module=C:\Users\PCHP\Desktop\Ogar-unlimited-master\node_modules\sqlite3\li
b\binding\node-v48-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --modu
le_path=C:\Users\PCHP\Desktop\Ogar-unlimited-master\node_modules\sqlite3\lib\bin
ding\node-v48-win32-x64' (1)
npm WARN install:sqlite3@3.1.3 sqlite3@3.1.3 install: `node-pre-gyp install --fa
llback-to-build`
npm WARN install:sqlite3@3.1.3 Exit status 1

> leveldown@1.4.5 install C:\Users\PCHP\Desktop\Ogar-unlimited-master\node_modul
es\leveldown
> prebuild --install

prebuild WARN install No prebuilt binaries found (target=v6.0.0 arch=x64 platfor
m=win32)
prebuild ERR! configure error
prebuild ERR! stack Error: Can't find Python executable "python", you can set th
e PYTHON env variable.
prebuild ERR! stack     at failNoPython (C:\Users\PCHP\Desktop\Ogar-unlimited-ma
ster\node_modules\node-gyp\lib\configure.js:401:14)
prebuild ERR! stack     at C:\Users\PCHP\Desktop\Ogar-unlimited-master\node_modu
les\node-gyp\lib\configure.js:356:11
prebuild ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
prebuild ERR! not ok
prebuild ERR! build Error: Can't find Python executable "python", you can set th
e PYTHON env variable.
prebuild ERR! build     at failNoPython (C:\Users\PCHP\Desktop\Ogar-unlimited-ma
ster\node_modules\node-gyp\lib\configure.js:401:14)
prebuild ERR! build     at C:\Users\PCHP\Desktop\Ogar-unlimited-master\node_modu
les\node-gyp\lib\configure.js:356:11
prebuild ERR! build     at FSReqWrap.oncomplete (fs.js:117:15)
npm WARN install:leveldown@1.4.5 leveldown@1.4.5 install: `prebuild --install`
npm WARN install:leveldown@1.4.5 Exit status 2
- readable-stream@2.0.6 node_modules\request\node_modules\readable-stream
Ogar@1.0.0 C:\Users\PCHP\Desktop\Ogar-unlimited-master
`-- request@2.69.0
  +-- bl@1.0.3
  `-- http-signature@1.1.1
    `-- sshpk@1.7.4
      `-- assert-plus@0.2.0

npm WARN Ogar@1.0.0 license should be a valid SPDX license expression

C:\Users\PCHP\Desktop\Ogar-unlimited-master\src>

**Comment by LegitSoulja** [comment]
@Andrews54757 Is python a thing? He ranned the old version successfully

**Comment by LegitSoulja** [comment]
Or is that gyp because of version v6?

**Comment by LegitSoulja** [comment]
@bangana You should uninstall node, and install node v5.9.0

**Comment by LegitSoulja** [comment]
[Node v5.9.0](https://nodejs.org/download/release/v5.9.0/) @bangana

**Comment by bangana** [comment]
yep that's what im doing now

**Comment by Andrews54757** [comment]
@bangana There is a tutorial. I just figured out you are using windows. Use the install dependanices script in src. (double click `install dependancies.bat`) then run it using the start.bat

**Comment by LegitSoulja** [comment]
@bangana and delete the **node_modules** outside of the **./src** folder  and then use the **install depenencies** file inside of the **/src** folder twice. If it closes really fast then you need to run it again.

**Comment by bangana** [comment]
lol now im getting another one module.js:341
    throw err;
    ^

Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\PCHP\Desktop\AJS-development-Ogar-unlimited-
1c654c7\node_modules\minimatch\minimatch.js:10:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

Press any key to exit...

**Comment by Andrews54757** [comment]
do `npm install minimatch`

**Comment by bangana** [comment]
in node.js or normal CMD ?

**Comment by Andrews54757** [comment]
cmd

**Comment by Andrews54757** [comment]
If it still doesnt work, im going to send you my node_modules folder so you can just replace your node_modules

**Comment by LegitSoulja** [comment]
@bangana  make sure you cd to this directory while using cmd before you make any npm request do this command

> C:\Users\PCHP\Desktop\Ogar-unlimited-master\src

**Comment by bangana** [comment]
ok :)

**Comment by bangana** [comment]
didn't work '-'

**Comment by LegitSoulja** [comment]
Please provide errors

**Comment by bangana** [comment]
module.js:341
    throw err;
    ^

Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\PCHP\Desktop\Ogar-unlimited-master\node_modu
les\minimatch\minimatch.js:10:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

Press any key to exit...

**Comment by LegitSoulja** [comment]
do that cmd command again and do this

> npm install brace-expansion -g

**Comment by bangana** [comment]
same error :'(

**Comment by LegitSoulja** [comment]
place the folder in the zip inside node_modules outside of **./src**

[brace-expansion.zip](https://github.com/AJS-development/Ogar-unlimited/files/249553/brace-expansion.zip)

**Comment by bangana** [comment]
now missing concat-map module hey just send me all ur modules

**Comment by LegitSoulja** [comment]
@bangana ok give me a few minutes. I thought @Andrews54757 was doing it but he havnt uploaded anything yet to the repo. Im copying my files now and uploading to github soon. Just a moment.

**Comment by bangana** [comment]
thank you soo much  man you're the best <3

**Comment by Andrews54757** [comment]
https://github.com/AJS-development/nodemodules. replace your node_modules with this one

**Comment by bangana** [comment]
Ok now i got no more errors ;D

**Comment by bangana** [comment]
Yaaaaaaaaaaaaaaaaaaaaaaay it worked you're the best man i love you :DDDDDDD

**Comment by LegitSoulja** [comment]
Great to hear :)

**Comment by bangana** [comment]
Finally !!

**Comment by firelightning13** [comment]
I think we need a tutorial video over here lol

**Comment by LPArigma** [comment]
I made a batch file to install all the modules if your getting those errors because I had the same errors yesterday, can the batch file be added to the project files?

**Comment by Agarian** [comment]
closing this 4 now
