### ISSUE TITLE
error calback

### ISSUE THREAD

**Issue by djbencrazy** [AJS-development/Ogar-unlimited#504]
best,
I get this error.
TypeError: "callback" argument must be a function
    at exports.setTimeout (timers.js:314:11)
    at GameServer.mainLoop (C:\Users\Administrator\Desktop\Ogar-unlimited-master\src\core\GameServer.js:1453:9)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)

can anyone help me thank you.

**Comment by LegitSoulja** [comment]
@djbencrazy What occurs when the happens? What version of OgarUnlimted are you using?

**Comment by Andrews54757** [comment]
it should work

**Comment by Andrews54757** [comment]
update first

**Comment by djbencrazy** [comment]
ik gebruik de laaste versie van

**Comment by LegitSoulja** [comment]
@djbencrazy Ok you used the old version, but you should update to recent.

**Comment by djbencrazy** [comment]
it is the latest version believe me I've just fetched off today

**Comment by Andrews54757** [comment]
It works for me.

**Comment by djbencrazy** [comment]
why it does not to me.
I started this evening with the last version.

**Comment by djbencrazy** [comment]
![ogar](https://cloud.githubusercontent.com/assets/11022044/15030676/06f46b00-1254-11e6-855c-0749618b888e.png)

**Comment by Andrews54757** [comment]
mabye the update command didnt work. It doesnt always work with a success rate of 92%. This is probably because it couldnt connect clearly with the servers. Try using the update command again

**Comment by djbencrazy** [comment]
and how do I do that best way ?

**Comment by LegitSoulja** [comment]
update

**Comment by LegitSoulja** [comment]
@djbencrazy Does the game crash when it starts automatically? Are you able to enter commands? or does it crash right when it runs?

**Comment by djbencrazy** [comment]
I could execute commands in

**Comment by LegitSoulja** [comment]
@djbencrazy okay since you can still execute commands enter the command

> update all

**Comment by LegitSoulja** [comment]
that should update all your files..

**Comment by djbencrazy** [comment]
I have everything yet again done everything updated once. does not at all still the same error

**Comment by djbencrazy** [comment]
it worked but now I have another problem when I go on agar.io/?ip=ip:port I only get a screen with booths and further nieks and then I get this
![ogar2](https://cloud.githubusercontent.com/assets/11022044/15045419/a78bedfa-12da-11e6-8ca8-e31537a7d2b2.png)

**Comment by LegitSoulja** [comment]
What ip did you use? If you are localhost connecting using

> https://agar.io/?ip=localhost:{port}

Or

https://agar.io/?ip=127.0.01:{port}

**Comment by Agarian** [comment]
i think agario is enforcing the no server emulator thing, i cant even play anymore...

**Comment by Agarian** [comment]
i got this in the console

exception thrown: IndexSizeError: Index or size is negative or greater than the allowed amount,J<@http://agar.io/agario.core.js:8:6411
c.Ja._34d6ad15@http://agar.io/agario.core.js:8:90177
je@http://agar.io/agario.core.js:10:65126
Dd@http://agar.io/agario.core.js:10:55782
Ob@http://agar.io/agario.core.js:10:1028
Hc@http://agar.io/agario.core.js:10:28090
Uc@http://agar.io/agario.core.js:10:40024
Hs@http://agar.io/agario.core.js:12:67102
k.C@http://agar.io/agario.core.js:7:5706
Ra/e.g.aa/<@http://agar.io/agario.core.js:6:493
e.g.$a@http://agar.io/agario.core.js:8:74072
Ra/e.g.aa@http://agar.io/agario.core.js:6:436

**Comment by djbencrazy** [comment]
ik gebruik me ip van me vps.
moe ik die door geven vraag het dan. 
@LegitSoulja

**Comment by Agarian** [comment]
what?

**Comment by LegitSoulja** [comment]
@djbencrazy my dutch friend. Don't wtf other languages. He dont say wtf everytime we say something lol

@djbencrazy agar is updating there services. Just wait a moment until they are done with what the have to do.

**Comment by djbencrazy** [comment]
Vertaal

oke sorry voor me fouten in engels.
ik probeer me best te doen.
Oke ik zal wachten ik zal voorlopige de versie van agario zelf gebruiken
okay sorry for me mistakes in English.
I try to do my best.
Okay, I will wait, I will use the preliminary version of itself agario
