### ISSUE TITLE
permissions issue in c9, can anyone help?

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#505]
Failed to delete folder 'eKiGCcQ'. Command failed: rm: cannot remove ‘/home/ubuntu/workspace/src/plugins/eKiGCcQ/README.md’: Permission denied rm: cannot remove ‘/home/ubuntu/workspace/src/plugins/eKiGCcQ/files.txt’: Permission denied rm: cannot remove ‘/home/ubuntu/workspace/src/plugins/eKiGCcQ/index.js’: Permission denied rm: cannot remove ‘/home/ubuntu/workspace/src/plugins/eKiGCcQ/config.ini’: Permission denied rm: cannot remove ‘/home/ubuntu/workspace/src/plugins/eKiGCcQ/command.js’: Permission denied .

Failed to write to 'config.ini'. Failed saving file ! : src/plugins/eKiGCcQ/config.ini ERR: Error: EACCES, open '/home/ubuntu/workspace/src/plugins/eKiGCcQ/config.ini'.

Happens to ALL files added or edited by the server.

**Comment by LegitSoulja** [comment]
maybe you can chmod  your directories?

**Comment by Agarian** [comment]
how exactly?

**Comment by Andrews54757** [comment]
do this. `sudo rm -rf <directory>`

**Comment by Agarian** [comment]
then what?

**Comment by Andrews54757** [comment]
thats it. in terminal, do `sudo rm -rf <directory`

**Comment by Andrews54757** [comment]
replace `<directory~ with the directory of the folder you want to delete

**Comment by Agarian** [comment]
cool worked

**Comment by GhostShot3** [comment]
@Agarian How do you create these custom label?

**Comment by Agarian** [comment]
You have to be a Member/Developer

**Comment by Agarian** [comment]
Or do you mean in your respiratory?

**Comment by LegitSoulja** [comment]
what repo does he own? :/

**Comment by GhostShot3** [comment]
@Agarian I have a repository but do not know how you do it.

**Comment by GhostShot3** [comment]
@Agarian only have these labels :(
![fff](https://cloud.githubusercontent.com/assets/18537420/16848323/aa0a97f2-49cb-11e6-8a7e-1859f9be146e.png)

**Comment by LegitSoulja** [comment]
You are the type of person who really needs to learn how github works > https://help.github.com/
