### ISSUE TITLE
'callback' is not a function error

### ISSUE THREAD

**Issue by LPArigma** [AJS-development/Ogar-unlimited#508]
whenever I start the server I get this error

> 
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 16.3.7
[Game] Loaded stats server on port 88
[Game] Listening on port 34343
[Game] Current game mode is Free For All
TypeError: "callback" argument must be a function
    at exports.setTimeout (timers.js:314:11)
    at GameServer.mainLoop (C:\Users\minim\Desktop\Ogar-unlimited-master\src\core\GameServer.js:1453:9)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)

I saw another thread like this but nobody helped him solve the issue all you did was tell him to update although he gave proof he was at the latest update and so am I. Please actually help me rather then telling me to update!

Thanks!

**Comment by LegitSoulja** [comment]
The thing is I dont see the error. Like I dont understand why this error exist. Just give me a minute while I discover more.

**Comment by LPArigma** [comment]
i can show you a file if you'd like..... I didn't change any settings other than the port......thanks!

**Comment by LegitSoulja** [comment]
@LPArigma Does the game crash automatically?

**Comment by LegitSoulja** [comment]
@LPArigma I dont know what to say right now. If you can get the game running without it crashing run the command **update all**. I've been playing on the new version for a quite some time, and I have not experienced no errors.

**Comment by LPArigma** [comment]
@LegitSoulja i did the console does not crash the error just pops up and i can still type commands. it says it updates when i type `update all` but then i relaunch the console and get the error again :/

**Comment by Megabyte918** [comment]
what the hell...

**Comment by LPArigma** [comment]
@LegitSoulja also whenever i fresh install the new files i run the 

> install dependencies.bat<

file and the i start it and i get an error 

> module.js:440
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\minim\Desktop\Ogar-unlimited-master\node_modules\request\node_modules\readable-stream\lib\_stream_duplex.js:21:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

Press any key to exit...<

**Comment by hassanila97** [comment]
Yes. Some modules get missing... I got it when I fresh install.. and its not nice todo npm install all the time

**Comment by LPArigma** [comment]
@hassanila97 suddenly the error is happening with my other agar.io clients too :/ could i have a bad version of node? do i need the LTE version?

**Comment by LPArigma** [comment]
@hassanila97 @LegitSoulja what module conatins callback???

**Comment by Andrews54757** [comment]
do `npm install request`

**Comment by LPArigma** [comment]
@Andrews54757 @LegitSoulja lol you guys are all wrong it turns out you guys are building this on an older version of node lol the current LTS version is v4.4.3 and i just removed it and installed NodeJS v4.4.2 lol so thats the problem! spread the word! downgrade your nodejs to fix it lol

**Comment by LPArigma** [comment]
@Andrews54757 please put this in the Readme.md file somewhere that you need version Nodejs v4.4.2

**Comment by LPArigma** [comment]
#504 Problem solved

**Comment by LegitSoulja** [comment]
@LPArigma we aren't wrong. Problems with Ogar ul starts above v5.9.1. I'm using 5.9.0 and have no issues. Ogar ul supports v5.9.0 aswell and v5.9.1 for now.

**Comment by LegitSoulja** [comment]
And we already have v5.9.0 documentented. Why go even lower?

**Comment by LPArigma** [comment]
@LegitSoulja i mean that support  for LTS v4.4.3(latest version) should be added so those with the latest don't need to downgrade their Nodejs, the latest have different modules for some reason

**Comment by LegitSoulja** [comment]
And we already know that. That's why we asked don't use node update 6 because of gyp updated crap which doesn't work right with Ogar ul. So we recommend v5.9.0 of node..

**Comment by JakeTDC** [comment]
I love you legitsoulja you saved my life TY SO MUCH I LOVE YOUO
