### ISSUE TITLE
Adding more members to AJS dev

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#509]
Hello, I am announcing that I will add 5, and only 5 more people to the AJS dev group. Permissions include

1. Ogar-Unlimited
2. Ogar-Client
3. Ogar-Ul-Plugin-Library
4. slitherio

Here are the five slots

1. @Megabyte918 
2. @LegitSoulja
3. @NatsuTheGreat 
4. 
5.

**Comment by LPArigma** [comment]
May i join?

**Comment by Andrews54757** [comment]
Requirements


1. Experience with Node-JS and Javascript
2. Some proof of experience
3. Must be the top one contributed to Ogar UL that is not already a dev (use pull requests)
4. Some social experience (probably already fufilled)


I am just looking for "well-rounded" people.

**Comment by NatsuTheGreat** [comment]
I don't know if you know my skills andrew, I never gave you proof :P

**Comment by Andrews54757** [comment]
Yes you did

**Comment by NatsuTheGreat** [comment]
Oh, I just feel like I want to show you right now and be sure you know :P

**Comment by Andrews54757** [comment]
sometimes though, i notice you copy others. Its okay though, as long as you give them credit

**Comment by NatsuTheGreat** [comment]
I try to change it as much as a I can :P

**Comment by Andrews54757** [comment]
I would also like to have people who make plugins

**Comment by NatsuTheGreat** [comment]
What kind?

**Comment by XxRaizerxX** [comment]
i don't even know how to make a pull request

**Comment by XxRaizerxX** [comment]
i dont wanna be a member i wanna be ranked up to something below dev member

**Comment by LPArigma** [comment]
@Andrews54757 if i cannot be a dev can i at the least lend a helping hand for the development?

**Comment by Megabyte918** [comment]
@Andrews54757 are you still doing this? I'm not sure if this should be closed or not

**Comment by firelightning13** [comment]
> 4. slitherio
wow didnt know about dis

**Comment by Agarian** [comment]
Where has @NatsuTheGreat been?

**Comment by MizovoGames** [comment]
ajs/andrew i have a problem, i opened my ogar opened the client and then it said account suspended 
plz andrew fix this

**Comment by Ckicky** [comment]
Did you duplicate any issues?(Just asking)

**Comment by LegitSoulja** [comment]
@Ckicky no, a few days ago I shut down the client and webesites and it said it was suspended but it wasn't. He was referring to that, but its back up now.

**Comment by NatsuTheGreat** [comment]
> Where has @NatsuTheGreat been?

Watchya meaning there? :P Never read that comment before.

**Comment by David1ali12** [comment]
May I join ?  i could help out with issues and etc.

**Comment by Megabyte918** [comment]
Should this be closed?

**Comment by genckaptan55** [comment]
I can help with client side such as mysql based sorted top 20 skor list, announce game leader ingame etc.. I'm not an expert on Nodejs and Javascript but keep to continue improving my skills.

**Comment by LegitSoulja** [comment]
@ganckaptan55 nah, sorry but I'm in full control over that keeping it updated, and besides. I don't think that'll never happen. Especially not for a stranger.

**Comment by LegitSoulja** [comment]
You need JavaScript experience, jquery, ruby, PHP, sass, etc..

**Comment by genckaptan55** [comment]
I already have javascript, jquery, ajax, php, html, css experience. It is ok, i just wanted to help. It's up to you accepting or not. Thanks anyway for improving ogarUL :)

**Comment by LegitSoulja** [comment]
@genckaptan55 All of this work is experience work, and not little kiddie scripts and code.

I doubt the client is a big deal, but with nodejs development I know Andrew is looking for more dev's.

But, the client and everything else site wise is under control. I do appreciate you asking, but I'll have to decline :/.

**Comment by SharkFinPro** [comment]
@genckaptan55 If you want to help with something, look at issue #1223

**Comment by Agarian** [comment]
This is over a month old lol

**Comment by NatsuTheGreat** [comment]
True.

**Comment by Agarian** [comment]
@NatsuTheGreat can you come on discord?

**Comment by NatsuTheGreat** [comment]
Mkay.

**Comment by LegitSoulja** [comment]
Farewell. Sadly I'll no longer be accountable, and part of AJS. I'll leave a note ASAP about my farewell. Until then, any further questions feel free to contact me privately via my email on my github profile page. Thanks.

**Comment by fayizan** [comment]
Bye Bye @LegitSoulja,We Miss You :(

**Comment by Megabyte918** [comment]
I'm closing this. There's no point in leaving it open
