### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#510]
Please do not go off topic.

rules
1. Do not make a comment that is not a suggestions
2. do not say things like "lets talk on discord" without deleting them.
3. Please, use https://gitter.im/AJS-development/Ogar-unlimited instead of discord as the "join me on discord" messages are frequent and the official chat for this project is https://gitter.im/AJS-development/Ogar-unlimited.

**Comment by Agarian** [comment]
How about it to where you can choose the start mass of minion in the command:

    Minion [playerID] [minionamount] [minionstartmass] [minionname]

**Comment by Andrews54757** [comment]
previous answer: NO. that is not authentic. I will add the implementation to include that feature in a plugin

**Comment by XxRaizerxX** [comment]
is there a way to fix bots running into a virus sir andrews

**Comment by XxRaizerxX** [comment]
Can you make something that makes split slower like when teaming a slo motion splitrun to practice splitrun

**Comment by firelightning13** [comment]
@XxRaizerxX You just need change the splitspeed to lower value

**Comment by XxRaizerxX** [comment]
it does not work

**Comment by XxRaizerxX** [comment]
split speed does not work

**Comment by XxRaizerxX** [comment]
i could set it to 1000 and no difference

**Comment by Andrews54757** [comment]
By the way, I added a new plugin: Superminions. it adds the superminion command which allows you to edit their spawnmass and speed

>superminion [id] [amount] [name] [spawnmass] [speed]

**Comment by LPArigma** [comment]
@Andrews54757 Please note somewhere what version of nodejs you must have to run it without errors  let alone run it at all (working version Nodejs LTS v4.4.2 most recent version Nodejs LTS v4.4.3)

**Comment by LegitSoulja** [comment]
@LPArigma. LOOK AT THE .TRAVIS.YML FILE.. Do you see the versions?? Do you see the build passing? Shut up and fix your computer and your node problems. If that version works for you then ok good. But that doesn't mean everyone needs to go to that version.

**Comment by LegitSoulja** [comment]
@LPArigma [Ogar Unlimited Passing State](https://travis-ci.org/AJS-development/Ogar-unlimited)

**Comment by Megabyte918** [comment]
Heres mine from the other suggestions issue:
- A powerups gamemode, Like random powerups (like speedboost, invinsibility, etc) spawn randomly throughout the map.
- Or another gamemode where there would be things that look like black holes like the ones on agarserv, but their a different color and when you hit them it bounces you back, and also have black holes :P 
- <del>What about a config that lets you change how much bigger you have to be to eat someone? in vanilla agar your cell has to be 25% bigger but what about something like sizeconsumepercent or something that lets you change that? </del>
- What about a minionbyip command? kind of like opbyip, but it gives you minions every time you connect with a specific ip. cause i cant give myself minions when i dont have access to the command prompt lel

**Comment by Andrews54757** [comment]
Use ogarconsole to have access to console

**Comment by XxRaizerxX** [comment]
Can you make something that makes split slower like when teaming a slo motion splitrun to practice splitrun

**Comment by LegitSoulja** [comment]
@XxRaizerxX suggestions are on hold for now..

**Comment by Megabyte918** [comment]
@XxRaizerxX that's what it was made for ya silly

**Comment by PrinceDark9243** [comment]
Make Graphics like real agar Retina Graphics it will be good! :D

**Comment by LegitSoulja** [comment]
@PrinceDark9243 4K agar resolution haha. I doubt that's even possible with the browsers, and some computers won't be able to handle it. 

HD graphics would be nice. The graphics I have now on my 4K monitor looks very bad 😕

**Comment by Agarian** [comment]
so in PlayerTracker.js, you could see the following code:

> var mult = 2.5; // To simplify multiplier, in case this needs editing later on
      this.viewBox.topY = this.centerPos.y - this.gameServer.config.serverViewBaseY * mult;
      this.viewBox.bottomY = this.centerPos.y + this.gameServer.config.serverViewBaseY * mult;
      this.viewBox.leftX = this.centerPos.x - this.gameServer.config.serverViewBaseX * mult;
      this.viewBox.rightX = this.centerPos.x + this.gameServer.config.serverViewBaseX * mult;
      this.viewBox.width = this.gameServer.config.serverViewBaseX * mult;
      this.viewBox.height = this.gameServer.config.serverViewBaseY * mult;

This code increases the viewbase range in spectate mode, multiplying the viewbase by *2.5*, however, this only affects freeroam spectate, not when spectating a player. The default viewbases X and Y make spectating a player look buggy, as you cannot see all the entities past the viewbase. so you see them appear and dissapear ON SCREEN, unlike in regular agar, the viewbase in all spectate modes spans thw whole screen. So i had the idea for a viewbase multiplier that affects any spectate mode.

Also the spectate bug in the client is caused by the following code in **PlayerTracker.js** (lines 403-423) :

    // Map obfuscation
    var width = this.viewBox.width;
    var height = this.viewBox.height;

    if (this.cells.length == 0 && this.gameServer.config.serverScrambleMinimaps >= 1) {
      // Update map, it may have changed
      this.socket.sendPacket(new Packet.SetBorder(
        this.gameServer.config.borderLeft + this.scrambleX,
        this.gameServer.config.borderRight + this.scrambleX,
        this.gameServer.config.borderTop + this.scrambleY,
        this.gameServer.config.borderBottom + this.scrambleY
      ));
    } else {
      // Send a border packet to fake the map size
      this.socket.sendPacket(new Packet.SetBorder(
       Math.max(this.centerPos.x + this.scrambleX - width, this.gameServer.config.borderLeft + this.scrambleX),
            Math.min(this.centerPos.x + this.scrambleX + width, this.gameServer.config.borderRight + this.scrambleX),
            Math.max(this.centerPos.y + this.scrambleY - height, this.gameServer.config.borderTop + this.scrambleY),
            Math.min(this.centerPos.y + this.scrambleY + height, this.gameServer.config.borderBottom + this.scrambleY)
      ));
    }

 Remove it and that fixes the spectate bug on the client. (It doesn't matter if serverScrambleMinimaps is set to 0 or 1, as it will not fix the bug, only removing the above code will fix it.)

I FOUND A BUG: if "ejectbiggest" is set to 1, it gives the following error

ReferenceError: ejectedCells is not defined
at GameServer.ejectBiggest (/home/ubuntu/workspace/src/core/GameServer.js:1273:9)
at GameServer.ejectMass (/home/ubuntu/workspace/src/core/GameServer.js:1287:14)
at Mode.pressW (/home/ubuntu/workspace/src/gamemodes/Mode.js:61:18)
at PlayerTracker. (/home/ubuntu/workspace/src/core/PlayerTracker.js:301:73)
at Timer.listOnTimeout (timers.js:92:15)

**Comment by Andrews54757** [comment]
fixed the ejectbiggest bug

**Comment by Agarian** [comment]
How about to where if you do:

    speed [playerID] default

It would reset that players speed to the default value in config/override.ini

**Comment by Agarian** [comment]
or a config that makes food spawn with random mass

**Comment by Andrews54757** [comment]
@Agarian Its already implemented ages ago with the speed, all you need to do is set your speed to 0 and it uses default

**Comment by problemsofworld** [comment]
</random> minion name

**Comment by LegitSoulja** [comment]
@problemsofworld just type Random for the name

**Comment by LegitSoulja** [comment]
@problemsofworld I can add a command to GiveMeMinions too

**Comment by Martinali12** [comment]
Split Running teaming bots possible when i split to a bot he kill enemy around kinda like teaming but not feeding me back can make feed back the helper or to be team with bot it would be amazing...

**Comment by Agarian** [comment]
New suggestion for the minions *E* and *R* splitting:

Since this has been added via OPT-IN, how about when you press *T*, the bots freeze? This was in Agar.io Powerups (that extension... good times xD)

**Comment by Andrews54757** [comment]
why not

**Comment by Andrews54757** [comment]
i will make it soon

**Comment by Agarian** [comment]
cool

**Comment by Megabyte918** [comment]
hai

**Comment by Agarian** [comment]
mega can you go on discord?

**Comment by Megabyte918** [comment]
sure m8 :D

**Comment by Lukkez** [comment]
A random minion name generator, can be made with a array like:
``var minionNames = [
"name1",
"name2",
"name3",
]
``

And make a config to set the number of the name who have on the list, and make like **minionRandomNames** = 0/1 and **minionNames** = 2/3/617/312 Any number, will load that amount of lines, a help to make that random names is the math random (```[Math.floor(Math.random() * config.minionNames)]);``

**Comment by Andrews54757** [comment]
@Lukkez You can already do that by doing `/random` as the minions name

**Comment by Agarian** [comment]
thats random skins, not random names lol

**Comment by Agarian** [comment]
i even had the idea for a config that allows you to press S and freeze your cell by executing the freeze command

**Comment by Lukkez** [comment]
Have? i never saw, at what location?

**Comment by Agarian** [comment]
config files... should be *randomnames*

**Comment by LegitSoulja** [comment]
instead of not naming, or naming your minions you can use a random name by making the name /random

By doing so the randomnames.txt file is where your random names will be obtained

**Comment by Andrews54757** [comment]
@Agarian It also works with names. `/random` gives you random names, and `name\</random>` gives you a random skin

**Comment by firelightning13** [comment]
`</random>/random`

This would give you random skins and also random names

**Comment by Agarian** [comment]
Another suggestion: a config that allows or disallows ejected cells to collide.

**Comment by Megabyte918** [comment]
@Agarian THAT would be cool

**Comment by NatsuTheGreat** [comment]
that's easy to do

**Comment by Andrews54757** [comment]
@Megabyte918 I will add that in optin. see #669

**Comment by Andrews54757** [comment]
@NatsuTheGreat I also added your request and chat

**Comment by RasyiidWho** [comment]
Can add minimap on the client?

I have tried in my client, but there is a bug.
http://imgur.com/dcuynuG

**Comment by Martinali12** [comment]
am using agarplus can u add scripte for tampermonkey for those who are using normal client or agarplus to split minions With E and feed With R.

**Comment by Agarian** [comment]
@RasyiidWho That actually sounds interesting!
@Andrews54757 What would you say to a mini-map option for the client?
I also had the idea for a "Show map borders" option.

**Comment by notcarksss** [comment]
How about a minion [amount ] instead of just one at a time

**Comment by Andrews54757** [comment]
@Agarian I was considering it, but im gonna make it be able to be disabled by the server (it will send a special packet)

**Comment by Andrews54757** [comment]
YAY! i finished multiverse!

**Comment by notcarksss** [comment]
@andrews54757 why don't you add minion [ amount] instead of one at a time

**Comment by Andrews54757** [comment]
@notcarksss The minion command already has that `minion [targetid] [amount] [minionname]`

**Comment by Megabyte918** [comment]
@Andrews54757 OOH ANDREW ANDREW I have a good suggestion :P 
What about a config called "Slitherboost" that when enabled, when you left-click your cell speeds up and leaves a trail of w's or pellets behind you (and you decay mass faster too) just like in slither.io when you left click? now THAT would be pretty awesome

**Comment by Andrews54757** [comment]
@Megabyte918 Why not? i will do it

**Comment by Agarian** [comment]
It should be a config tho

**Comment by notcarksss** [comment]
Meh yeah but why don't you add those glowing and moving food like slither.io to fo with @Megabyte918's idea

**Comment by firelightning13** [comment]
:O Damn thats a good idea

**Comment by notcarksss** [comment]
Sorry for type it should be "to go with"

**Comment by notcarksss** [comment]
Sorry for typo it should be "to go with"

**Comment by Agarian** [comment]
you can edit comments lol

**Comment by notcarksss** [comment]
@Agarian i forgot xD anyway brb

**Comment by elitajmx** [comment]
MINION SUGGESTION!
It could have like a letter to press for ex. h, then minions will go get food if you know what i mean? they wont come to you but pick up food and try to get big,after pressing h again they will come to you by normal. Basically that food picking up is called the blind mode for minions yall know that already.

Hopefully it's a good suggestion!

**Comment by elitajmx** [comment]
Idk if possible, but would be awesome if made something like this
bots spawn with random mass, that would be: 10mass 30%, 44mass 50 % and 132mass 10%
Dat would be sick!

**Comment by Megabyte918** [comment]
Suggestion:
How about a config (or maybe an addon to the SuperMinions plugin?) that when enabled, when you put `</m>` in front of your name if automatically gives you like 3 minions (or however many is specified).
so that way, if somebody joins my server and they want minions they can just do `</m>` and i wont have to give them some in the command prompt every time

Another suggestion:
What about a new command called `install` for missing files, so say your missing /core/Multiverse.js or something, you could just do `install /core/Multiverse` or if your missing multiple files, you could just do `install missing` and it would download the specified file(s) from the repo, so people wouldn't have to re download the zip and insert the file manually

**Comment by LegitSoulja** [comment]
@Megabyte918 nice suggestions m8

**Comment by PrinceDark9243** [comment]
Make Skins Support

**Comment by PrinceDark9243** [comment]
and when we hod W it will keep Ejecting Mass and Same For Space and for other Keys in Config.ini
`keySpamEnable = 0 //Make it 1 For Key Spaming`

**Comment by NatsuTheGreat** [comment]
@Megabyte918 I am going really good with the slitherio thing, I just need to get the correct angling and I will be done.

**Comment by NatsuTheGreat** [comment]
@Megabyte918 https://gyazo.com/fc4eecf681d73297728edca701f550f3

**Comment by Megabyte918** [comment]
@NatsuTheGreat thank you so much! im excited :D

**Comment by NatsuTheGreat** [comment]
The only problem is it makes everyone go fast, I do not know a way to solve it now, I will try to though...

**Comment by Agarian** [comment]
That's the server, idk why it happens, its almost as if it makes the server calculate ticks correctly... same happens when ejected cells pudh each other around, when you eject alot of mass pellets into a certain spot, this makes them push each other out, which has the same effect.

**Comment by David1ali12** [comment]
What about bots try to find team by Tag like real players  [tag]name if bot cant find team by tag then will try random . getting in realistic names  .

**Comment by NatsuTheGreat** [comment]
@Agarian Wait, what are you talking about? xD

**Comment by Andrews54757** [comment]
@NatsuTheGreat You should have the food spawn from the center of the cell but be unable to be eaten until it goes out

**Comment by NatsuTheGreat** [comment]
@Andrews54757 What would that be for? :P Angling? I need a reverse that would reverse the angle of the mouse, but starting from the cell. What happened to me with my reverse system, it did reverse the angle, but not starting from the cell.

**Comment by NatsuTheGreat** [comment]
@Andrews54757 And then I need it to stop changing the config value globally but instead change it for only the person using the boost. I remember you did something where the player that shot a virus wouldn't pop by, maybe something like that in my case.

**Comment by elitajmx** [comment]
After you feed bots and give them your balls,they should feed you back at least? Thad' be a good one!

**Comment by notcarksss** [comment]
@elitajmx that could be used but if you press r on the keyboard the bots feed you

**Comment by elitajmx** [comment]
im takling about the bots, not minions

**Comment by notcarksss** [comment]
Minions are Bots dude :/

**Comment by elitajmx** [comment]
yeah but omg man... do i call those: Self-moving auto computer "BOTS" or rather just BOTS..?? If someone has an issue with minions and bots, will you go there and say, minions and bots are the same? We have seperate things for minons and bots & they are the same thing but just a different type

**Comment by notcarksss** [comment]
They are the same thing in my view but I get what you mean

**Comment by elitajmx** [comment]
why does spawnmass on superminion plugin don't work?

**Comment by PrinceDark9243** [comment]
i have an suggestion for mass command
make its like this `mass [ID] [SUB-CMD] [AMOUNT]` `ex`;`mass 1 add 2000`
Sub Command list:`add,remove,set`

**Comment by Agarian** [comment]
sounds cool

**Comment by Andrews54757** [comment]
@PrinceDark9243 Might do here: #786 . Format will be different

**Comment by Agarian** [comment]
Will the skins feature work on play.ogarul.tk? Or is that already added to the client?

**Comment by elitajmx** [comment]
hopefully:(

**Comment by Agarian** [comment]
it does, but the client lags BADLY and the show mass option doesnt work.

**Comment by notcarksss** [comment]
Can someone pls tell me, where can I download the client or is it on a website and bad if it lags badly

**Comment by Andrews54757** [comment]
@Agarian It doesnt lag

**Comment by Andrews54757** [comment]
Il fix showmass

**Comment by Andrews54757** [comment]
Done, its fixed

**Comment by elitajmx** [comment]
finallyyy :D

**Comment by elitajmx** [comment]
play.ogarul now works omg

**Comment by Agarian** [comment]
How about eject mass collision that lags the server less? It only takes maybe 20+ ejected cells colliding and pushing to cause server physics to become rough and uneven.

**Comment by Agarian** [comment]
And in #857 it was discovered that default agar skins have been broken (*DUN DUN DUUUUN!*)

**Comment by LegitSoulja** [comment]
@NatsuTheGreat you need some help there?

**Comment by David1ali12** [comment]
Can you add Scripts library like Plugin library.

**Comment by bangana** [comment]
all AJS devs why don't u make a yt or whatever channel to make video tutrials

**Comment by LegitSoulja** [comment]
@bangana we could, but eh. @Andrews54757 I could. I will start working on a nice AJS intro :)

**Comment by Agarian** [comment]
IDK why but it only takes maybe 20+ ejected mass cells colliding and pushing to cause server physics to become rough and uneven. IDK why ejected mass cells lags the server so easily. 
*(This problem has been around since the big core update, and is the one of the only remaining things on the server that still bugs me).*

**Comment by Agarian** [comment]
How about if you press the S key, bots will follow the cell instead of the mouse. Pressing it sgain does the opposite

**Comment by firelightning13** [comment]
How about we can edit the server's title from multiverse. For example, I don't like the name "Main" so i need to change it to something else like "Normal FFA".It would be like this:
`multiverse edit [name] [new title]`

**Comment by Andrews54757** [comment]
You could just edit multiverse.js on the init function

**Comment by PrinceDark9243** [comment]
@Andrews54757 
make its like this `mass [ID] [SUB-CMD] [AMOUNT]` ex;`mass 1 add 2000`
Sub Command list:`add,remove,set` make my suggestion come true plz

**Comment by PrinceDark9243** [comment]
make a gamemode like diep.io

**Comment by LegitSoulja** [comment]
@Agarian do you still want the random skins?

**Comment by Agarian** [comment]
YES
When did i say i didn't?

**Comment by LegitSoulja** [comment]
@Agarian I was working on it before I went to bed. Here's how it works before I finish it it a few hours.

There's a customskins.txt file and skins.txt file. Skin.txt contains the default skins that can be used at play.ogarul.tk. If you are using custom skins you can enable that.

You can set an interval in minutes of when the skin will change.

**Commands**
- rs [id] 
Use the command to add the player ID to a list to get random skins.

Anything else I'm missing?

**Comment by NatsuTheGreat** [comment]
Could the skins flashing be caused by some ```/random``` bug?

**Comment by LegitSoulja** [comment]
@Agarian ok im done
**Commands**
- rs [add,rem] [id]

**Install Usage**
> plugin install RandomSkins

new plugin @Andrews54757

**Comment by raphyjb** [comment]
theres an issue with multiverse... I see huge virusses and wierd names, my they are so big i cant see...

**Comment by Agarian** [comment]
How about when in the client (play.ogarul.tk), it would have a connecting panel, but would instead say "You are not currently connected to a server." or something else.

**Comment by LegitSoulja** [comment]
@Agarian It was like that before, but then it was removed. And I finished the RandomSkin plugin for ya

**Comment by Agarian** [comment]
:O

**Comment by Agarian** [comment]
i also had the idea for a plugin that changes only a PLAYER's start mass (via spawnmass command would be easy)

**Comment by Agarian** [comment]
not working =/

**Comment by LegitSoulja** [comment]
@Agarian Read the command usage.

**Comment by Agarian** [comment]
not the command!

**Comment by LegitSoulja** [comment]
What doesnt work then?

**Comment by Agarian** [comment]
Skins. The plugin is not loading any skins. But the server still does.

**Comment by LegitSoulja** [comment]
@Agarian are you using play.ogarul.tk?

**Comment by Agarian** [comment]
yes

**Comment by LegitSoulja** [comment]
@Agarian Are you joining using < rs >? Or the command?

**Comment by Agarian** [comment]
i tried both.

**Comment by LegitSoulja** [comment]
They both work, they wont work asap because its a 10 second interval between changing

**Comment by LegitSoulja** [comment]
http://stats.ogarul.tk/ join the test server

**Comment by Agarian** [comment]
I redownloaded it, it seems to be working

**Comment by LegitSoulja** [comment]
Oh ok. I could have been the skins file

**Comment by LegitSoulja** [comment]
and your welcome.

**Comment by Agarian** [comment]
Im gonna delete some unneccecary comments lol

**Comment by PrinceDark9243** [comment]
make a gamemode like diep.io

**Comment by NatsuTheGreat** [comment]
@retslac

**Comment by Agarian** [comment]
How about a `virusStartAmount` config?

**Comment by fayizan** [comment]
@Andrews54757 can u please provide this [skin explorer](http://prntscr.com/bez6f1) for the customclient

**Comment by fayizan** [comment]
@Andrews54757  can u please add this [skin explorer](http://prntscr.com/bez6f1) for the client #918 you have provided

**Comment by LegitSoulja** [comment]
@Andrews54757 no it won't work because it's private. He didn't add it but I did. It won't work with other sites other than play.ogarul.tk. Sorry :/

**Comment by LegitSoulja** [comment]
@fayizan no it won't work because it's private. He didn't add it but I did. It won't work with other sites other than play.ogarul.tk. Sorry :/

**Comment by LegitSoulja** [comment]
It's really up to @David1ali12 if he wants his skins publicly obtained.

**Comment by fayizan** [comment]
Most of the modded client have **Skin Gallery** Button , we don't have..!! please don't say no

**Comment by LegitSoulja** [comment]
@fayizan Yes, i know but the client's you guys get aren't fully the same as to what play.ogarul.tk is since its the official. The skins are made by david, and I kindly added the gallery to play.ogarul.tk so that other people can know what skins are there to be used. Right now, only play.ogarul.tk is allowed access to grab all of the skins for view like you saw. If david allow other people to get access then it could be added to the public client.

**Comment by fayizan** [comment]
@David1ali12 please give us that skin gallery box feature,its really awesome a

**Comment by fayizan** [comment]
@Andrews54757  can you please make a skin gallery page for public client

**Comment by LegitSoulja** [comment]
@fayizan you have to wait until David gets better hosting so that nobody want be spamming his site over images. The security is the reason other sites aren't allowed to obtain them.

**Comment by PrinceDark9243** [comment]
@Andrews54757 why you are ignoring me!? see my suggestion its Awsome for Ogar UL!
make its like this mass [ID] [SUB-CMD] [AMOUNT] ex;mass 1 add 2000
Sub Command list:add,remove,set make my suggestion come true plz

**Comment by Andrews54757** [comment]
@PrinceDark9243 , no, im just taking a break from coding now.

**Comment by PrinceDark9243** [comment]
oh ok after break make it true!

**Comment by PrinceDark9243** [comment]
i have an Suggestion for the Cell Border
in the customskins.txt the format is this `example :http://example.com/00000` Can you Able to make its like this `example :http://example.com/00000 :255,255,255` the Code `255,255,255` is the Color Code of the Border or the Cell Color! its Gonna be Awsome for Customizing your customskin border!

**Comment by Agarian** [comment]
I had that suggesion a long time ago

**Comment by PrinceDark9243** [comment]
i have an suggestion that it would be great if there is a gamemode like diep.io where you can choose classes and other config i have the tier Chart!
![classes](https://cloud.githubusercontent.com/assets/17459204/16352246/ff347df6-3a85-11e6-8219-04c6b1eee09d.png)

**Comment by fayizan** [comment]
Can This be added,atleast the border line 

![border](https://cloud.githubusercontent.com/assets/19163419/16388110/357ca164-3cb5-11e6-966b-28b4576a45aa.jpg)

**Comment by LegitSoulja** [comment]
@PrinceDark9243 I don't know about the class upgrades and stuff right now

@fayizan Yes, I will add a option for border lines.

**Comment by Agarian** [comment]
@AJS-development/ogar-unlimited-devs 
How about a config that enables or disables freeroam spectate? (`serverFreeroamSpec`) 
If it is disabled, the server would spectate players by the leaderboard. So pressing Q with freeroam spectate disabled would go down the list of players on the leaderboard (as older ogar did). And obviously, with freeroam spectate enabled, pressing Q will activate freeroam spectate.

**Comment by PrinceDark9243** [comment]
make its like this mass [ID] [SUB-CMD] [AMOUNT] ex;mass 1 add 2000
Sub Command list:add,remove,set make my suggestion come true plz

I COMMENTED 3 MONTH AGO WHY YOU GUYS ARE IGNORING ME WHY! I AM DONE WITH THESE COMMENT!

**Comment by LegitSoulja** [comment]
@PrinceDark9243 nobody isn't working on this project as of right now :/

**Comment by Agarian** [comment]
I did... #1183

**Comment by Agarian** [comment]
@LegitSoulja i wanted you to see this:

NOTE: I AM NOT REFERENCING FREEROAM SPECTATE BELOW!
"I was wondering if there was an easy way for spectate ZOOM to change according to how much a person is split. Spectate zoom already gets affected by a player's mass, but not when players split."
In vanilla agar and ogar, spectate ZOOM gets affected by cell mass and cell splitting. In ogarUL however, spectate ZOOM does get affected by cell mass, but NOT by cell splitting, even though the viewbases X and Y do get affected by cell splitting(In spectate). Any ideas on how to do so?

**Comment by Agarian** [comment]
How about a config that enables or disables freeroam spectate? (Could be `serverFreeroamSpec`) 
If it is disabled, the server would spectate players by the leaderboard. So pressing Q with freeroam spectate disabled would go down the list of players on the leaderboard (As older ogar did). And obviously, with freeroam spectate enabled, pressing Q will activate freeroam spectate.

**NOTE: I AM NOT REFERENCING FREEROAM SPECTATE BELOW!**
I also had this idea: 
"I was wondering if there was an easy way for spectate ZOOM to change according to how much a person is split. Spectate zoom already gets affected by a player's mass, but not when players split."
In vanilla agar and ogar, spectate ZOOM gets affected by cell mass and cell splitting. In ogarUL however, spectate ZOOM does get affected by cell mass, but NOT by cell splitting, even though the viewbases X and Y do get affected by cell splitting(In spectate). Any ideas on how to do so?

I also liked @fayizan's idea for an option for showing map borders.
I even had the idea for a new command: `gamemodelist`
Maybe a config that allows food to spawn with random mass? Could be `foodRandomMass.`
And one more thing, how about a `virusStartAmount` config?

**Comment by fayizan** [comment]
I saw a minimap code today and thought it can be added to play.ogarul.tk

[MINIMAP](https://github.com/dimotsai/agar-mini-map)

**Comment by LegitSoulja** [comment]
If it works then maybe it can be.

**Comment by firelightning13** [comment]
Suggestion: How about delete some of suggestions have been already added or unnecessary comments? Just thinking :) .

Also, if you try to delete this comments because this considered unnecessary, that's ok, because i can find it really funny xD (it's not -_-)

**Comment by LegitSoulja** [comment]
@firelightning13 that's really not a suggestion, nor it doesn't matter if some are deleted or not. It's nice to keep these records for who actually came up with idea.

**Comment by firelightning13** [comment]
@LegitSoulja ok

**Comment by firelightning13** [comment]
Something wrong with gitter right now
(I know this isnt a place to comment this)

**Comment by LegitSoulja** [comment]
@firelightning13 its fine, but whats the problem?

**Comment by firelightning13** [comment]
Spam message are all over the place.

**Comment by LegitSoulja** [comment]
I don't think nobody can fix that. Comments are old that they can't be deleted.

**Comment by VSabertail** [comment]
They should make a diep.io server or client cause i love diep.io and they should make an diep.io server

**Comment by Agarian** [comment]
maybe this should be closed then recreated
