### ISSUE TITLE
Can't join my own server

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#511]
As if i type " connect ("ws://127.0.0.1:80") " in the console, it will say: 

**Uncaught ReferenceError: connect is not defined(…)**

**Comment by LegitSoulja** [comment]
You can't use web sockets...

**Comment by Agarian** [comment]
i get:

exception thrown: IndexSizeError: Index or size is negative or greater than the allowed amount,J<@http://agar.io/agario.core.js:8:6411
c.Ja._34d6ad15@http://agar.io/agario.core.js:8:90177
je@http://agar.io/agario.core.js:10:65126
Dd@http://agar.io/agario.core.js:10:55782
Ob@http://agar.io/agario.core.js:10:1028
Hc@http://agar.io/agario.core.js:10:28090
Uc@http://agar.io/agario.core.js:10:40024
Hs@http://agar.io/agario.core.js:12:67102
k.C@http://agar.io/agario.core.js:7:5706
Ra/e.g.aa/<@http://agar.io/agario.core.js:6:493
e.g.$a@http://agar.io/agario.core.js:8:74072
Ra/e.g.aa@http://agar.io/agario.core.js:6:436

when i try to spectate. and pressing play does nothing...

**Comment by LegitSoulja** [comment]
This is on agar behalf, not oga ul. If this problem happens, there's nothing we can do for you. Unless you manage to open your own ports.

@Agarian I think they are updating there emulator.

**Comment by Agarian** [comment]
?

**Comment by elitajmx** [comment]
yeah what haha

**Comment by LegitSoulja** [comment]
@elitajmx The problem is on agar behalf. Looks to be they are updating there servers. You cant event go to //agar.io without connnection problems. Its just not the servers cant/wont connect.

**Comment by elitajmx** [comment]
k,on agarplus it works:)
