### ISSUE TITLE
Private Servers no longer work.

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#512]
Hello all, I am here to announce that agario has updated their client and private servers no longer work. I have emailed their developers about this and I hope we update this as fast as possible. @AJS-development/ogar-unlimited-devs

**Comment by Andrews54757** [comment]
Ok, I got their reply. They said "we do not share this kind of information"

**Comment by ItzLevvie** [comment]
lol ..

**Comment by LegitSoulja** [comment]
So what now?

**Comment by LegitSoulja** [comment]
Is Ogar updating there server?

**Comment by LegitSoulja** [comment]
And do we have to awell?

**Comment by ItzLevvie** [comment]
We might have to wait, maybe someone might popup with a correct solution.

**Comment by Andrews54757** [comment]
I guess we have to either

1. Use a client clone (possibly cigars)
2. reverse engineer agario
3. wait

**Comment by LegitSoulja** [comment]
Well I'm down for whatever to get them working back again asap. This might just be then end 😭. Get your clients out boys

**Comment by ItzLevvie** [comment]
They've also changed the JS codes, moved most of the code to http://agar.io/agario.core.js and obfuscated it. Our only solution is to use Wireshark if they changed their packets.

**Comment by aaxxo** [comment]
This is a sad day if they have just killed all private servers.

**Comment by hassanila97** [comment]
No, they cant just to this and fuck up all this hard work that you guys did... Fuck them

**Comment by Andrews54757** [comment]
its all about money. All miniclip (or should I say moneyclip) wants is money

**Comment by hassanila97** [comment]
Yes, Im really angry at them.. I will do whatever it takes to fuck them up. And their servers.. Yes I can do that and know how.

**Comment by Andrews54757** [comment]
Im going to implement agario clones version of the client

**Comment by Andrews54757** [comment]
at least there will be chat and in-game commands

**Comment by Andrews54757** [comment]
Or should  I pull the self-destruct lever fro this project

**Comment by hassanila97** [comment]
No... dont destruct this repo.. it is worth so much more than Agar.io and all it has in it...  Yes you should start looking at a client clone.. and dont give a fuck to MoneyClip by just saying that it is for learning purposes only :)

**Comment by PrinceDark9243** [comment]
make a client for Ogar un

**Comment by PrinceDark9243** [comment]
@hassanila97 i am using cloneclient so how i can play agar.io

**Comment by hassanila97** [comment]
@Andrews54757 but dont take too much risk as they wont let you go that easy if you make an illegal client..

**Comment by Andrews54757** [comment]
it wont be illegal.

**Comment by Andrews54757** [comment]
It will be like what @MichaelLeeHobbs said

**Comment by XenoYT** [comment]
Thanks for everyone that made ogar unlimited in ogar unlimited i learned all tricks with my littme brother thanks dev ill always wait until they fix it + agario is shit now all servers are laggy

**Comment by PrinceDark9243** [comment]
yes all agar.io servers are laggy

**Comment by Andrews54757** [comment]
The world doesnt know about this update YET but when they do, be prepared for a lot of rage

**Comment by PrinceDark9243** [comment]
lol

**Comment by XenoYT** [comment]
Yea specially famous youtubers

**Comment by PrinceDark9243** [comment]
yes youtubers get loled

**Comment by Andrews54757** [comment]
then agario goes bye-bye and slither.io becomes the next agario

**Comment by Andrews54757** [comment]
this is probably the last straw for many people

**Comment by XenoYT** [comment]
@Andrews54757 but i hate slither :( and if you make cigar version add skins and smooth splits please guys :(

**Comment by PrinceDark9243** [comment]
yea Cheers for Slither.io F*ck Agar.io

**Comment by PrinceDark9243** [comment]
i am using cigar and how i can join my server bro

**Comment by Andrews54757** [comment]
so, should I pull the Global-Ogar-Unlimited-Destruction lever?

**Comment by Agarian** [comment]
OH HELL NO

**Comment by XenoYT** [comment]
we can wait a week if famous youtubers raged miniclip should put old version back :/

**Comment by PrinceDark9243** [comment]
no plz dont pull it @Andrews54757

**Comment by Agarian** [comment]
hope i survive

**Comment by XenoYT** [comment]
@Andrews54757 and dont pull it you did alot of work guys and how to contact miniclip ill spam them

**Comment by Andrews54757** [comment]
dont spam them

**Comment by XenoYT** [comment]
@Andrews54757 ok just how to contact them ?

**Comment by Andrews54757** [comment]
@MichaelLeeHobbs What do you think?

**Comment by XenoYT** [comment]
promise

**Comment by ItzLevvie** [comment]
Don't distruct the repo, there might be a solution coming soon by others I think?

**Comment by XenoYT** [comment]
Yea im asking how to contact miniclip to ask them ;-;

**Comment by XenoYT** [comment]
AND I CANT JOIN ANYMORE SAME PARTY WITH A FRIEND

**Comment by Megabyte918** [comment]
*sighs *

**Comment by Agarian** [comment]
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU...

**Comment by ItzLevvie** [comment]
I'm 100% sure this has to do something with packets. Just spawned with the name "LOL" and the console returns "佌L"

**Comment by Agarian** [comment]
O_O

**Comment by Megabyte918** [comment]
Welp, I was gonna work on the splitting & spawning but I GUESS NOT

**Comment by Megabyte918** [comment]
At least the bots are patched

**Comment by hassanila97** [comment]
Well.. I hope its just about changed packets @ItzLeevie

**Comment by Lukkez** [comment]
Packets changed, and a help, isn't more main.out.js, IT'S agario.core.js

**Comment by Lukkez** [comment]
We need to work on a client who support Ogar-unlimited if doesn't work, the good part i'm making one, very slowly because i don't have help 
:disappointed: with <del>mini</del>**MONEY**clip's

**Comment by LegitSoulja** [comment]
@Lukkez **I** personally said that I wouldnt mind helping you. You wasn't making a client thought you was make a site. Since you changed your mind I would mind to have mind to help you with this mini project.

**Comment by LPArigma** [comment]
Any ideas for a fix yet? And just wait for bots to come back, StavJ brought them back after the big patch of chrome extension bots and he will do it again.

**Comment by ItzLevvie** [comment]
@LPArigma We've to update the "UpdateNode" packet for everything to work with the latest update.

**Comment by LegitSoulja** [comment]
Using extensions is way worse than joining a server with ease. Ill be
making a client soon, but I'm going to rest for today. I woke up tired and
down. Maybe I need some caffeine

**Comment by bangana** [comment]
lol sounds like moneyclip is working hard !!

**Comment by joeryd** [comment]
They moved all the not render things to http://agar.io/agario.core.js and obfuscated main_out.js. They did a really good job, let's be honest.

**Comment by LegitSoulja** [comment]
@joeryd http://agar.io/main_out.js its not obfuscated.. agario.core.js is more likely is though

**Comment by joeryd** [comment]
@LegitSoulja whoops, that's what I meant to say.
http://agar.io/mc/agario.js = interface stuff
http://agar.io/agario.core.js = render stuff

**Comment by LegitSoulja** [comment]
@joeryd Yea, that sounds better. And besides, Screw agar.io. Im going to be developing a client specificly for OgarUnlimited.. It will be more unlimited than ever. We can basically create Agar the way it supposed to be. And plus OgarUnlimited is much better than the original ogar..

**Comment by tommyb008** [comment]
@LegitSoulja When is that client your making going to be in beta or released?

**Comment by firelightning13** [comment]
Wow, I just woke up and this S*** happens?!??!?! WTF ~~MINI~~**MONEYCLIP**!!!!!!!!!!!!!!!!!!!!!!

**Comment by LegitSoulja** [comment]
@firelightning13 Yess. Im just watching the ragings its amazing. Hahah :)

**Comment by firelightning13** [comment]
https://www.reddit.com/r/Agario/comments/4h7328/monthly_rage_thread_5_0105/

**Comment by MichaelLeeHobbs** [comment]
@Andrews54757 Well, what a day. I was just sitting down and was going to post that it appears 'n' has some issues, it gave us problems at work this week and people should look at nvm. Then I read this. I'll try to hunt down one of our lawyers at work and see if he'll give me advice.

One thing I do know is that creating a clone of the client will cause us issues unless we make it look different, very different. Basically,  the safest thing to do would be to change names and looks, nothing to do with Agario. We may even just want to lock this repo and create a new one from scratch and create a new game that is very similar to Agario.

I have a copy of the client from a week ago and after looking at it, it is around 80k lines of code. A chunk of that I'm going to guess is for ad's. Either way it would take months to de-obfuscate.

Honestly, I don't know what to do at this point. Let me talk with people at work on Monday and less give this a couple of weeks.

**Comment by acydwarp** [comment]
About 3 months ago, several devs and I started working on a custom Agar.io client from scratch:
https://github.com/SNSA/NEXT

It uses ES6 classes, [PixiJS](http://www.pixijs.com/) for it's rendering and is based on [agario-client](https://github.com/pulviscriptor/agario-client) by pulviscriptor.

Development on this project has slown down, however, it is still in a fully working state so feel free to either contribute to it or fork it.

**Comment by MichaelLeeHobbs** [comment]
@acydwarp Very nice and the code is very clean.

@Andrews54757 if we continue then this is the way we should go, it will save us a ton of work.

**Comment by Megabyte918** [comment]
(yes ik this isn't related to anything at all haha I just had to get this off of my chest)
This really sucks because in the beginning of my high school year we had a party in the class, and at that party we got to play any game we wanted, and the class chose agario. (it was back when ogarUL didn't exist and ogar physics were bad) I made a private server for my friends to join so we can all have fun with the bots and kill each other, it was the most fun our class has ever had.

NOW today our class is supposed to have a big end-of-the year pizza & ice cream party for us passing the keystones and we get to choose any game we want. we all wanted to play agario again because last time was so fun. I was gonna show off all the new features and commands and better physics then we could all have fun with them it was gonna be AWESOME! but.... sadly... moneyclip had to patch private servers a DAY before the party so we couldn't play and I had to let them all down. *sigh *... why miniclip why...

**Comment by NatsuTheGreat** [comment]
@Megabyte918 Awe :'(

**Comment by Agarian** [comment]
U should see the rage in the /r/Agario rage section on reddit!!!

**Comment by NatsuTheGreat** [comment]
Lol k

**Comment by XxRaizerxX** [comment]
@agarian lol i have been there

**Comment by uWotMate** [comment]
I hope MoneyClip Wreck Em`Selves

![image](https://cloud.githubusercontent.com/assets/19249368/15097157/1d631c7e-1556-11e6-8e95-6457a2280ba0.png)

**Comment by ItzLevvie** [comment]
lol

**Comment by ItzLevvie** [comment]
Use agar.io/v72/ if you want to play on private servers.

**Comment by problemsofworld** [comment]
@ItzLevvie  can I play with friends if I use  http://agar.io/v72/

**Comment by ItzLevvie** [comment]
Yes, http://agar.io/v72/?ip=

**Comment by elitajmx** [comment]
But i tried http://agar.io/v72/?ip=ws://127.0.0.1:80 and it isn't working

**Comment by firelightning13** [comment]
It's working for me

**Comment by elitajmx** [comment]
wierd

**Comment by ItzLevvie** [comment]
Moneywhoreclip patched it

**Comment by firelightning13** [comment]
.......................

**Comment by elitajmx** [comment]
lol, soon enough they should be patching agario

**Comment by Andrews54757** [comment]
I DID IT! https://client-andrews54757.c9users.io.

**Comment by NatsuTheGreat** [comment]
We want fixed normal private servers too :/

**Comment by Andrews54757** [comment]
what normal private servers

**Comment by Andrews54757** [comment]
It only works with a special packet as well

**Comment by problemsofworld** [comment]
@Andrews54757  maybe new game called ogarunlimited.io and you can sell bots and gain a lot of money and enable all exstion like agar+ then moneyclip will fucked up

**Comment by bangana** [comment]
can someone explain me the problem with private servers like it's not that big problem for them to patch it

**Comment by problemsofworld** [comment]
@bangana  they patched all modes we need new client

**Comment by problemsofworld** [comment]
@Andrews54757  I  figure out how ur client works thx DUDe am ur fan I wonder how lukkez did not figure out lol :D

**Comment by LegitSoulja** [comment]
@problemsofworld That what I was thinking. If we make a client, and people use our client, and have ads and etc, we can create revenue.

**Comment by problemsofworld** [comment]
@LegitSoulja I was already finish with my bot site untill agar update I got 40$ from first day starting its very good if it going to has bots and agarplus and can be hosted on good servers we can get bunch of money and almost 50% very soon willl come 25% players wants bots even if they dont use  but not sure if its liggal or not XD

**Comment by LegitSoulja** [comment]
@problemsofworld of course not..

**Comment by problemsofworld** [comment]
bots ?

**Comment by LegitSoulja** [comment]
@problemsofworld It can be illegal in some cases.

**Comment by LegitSoulja** [comment]
@problemsofworld Like if someone uses it to destroy someone elses server. Legal cases would go against you, and the person who used it.

**Comment by problemsofworld** [comment]
:/

**Comment by problemsofworld** [comment]
no bots no life

**Comment by LegitSoulja** [comment]
It's more like you have no life if you use bots.

**Comment by problemsofworld** [comment]
I dont use bots I sell them

**Comment by Megabyte918** [comment]
welp, their patched now lol

**Comment by firelightning13** [comment]
Haha, its like more bots more money $$$ amiright?

**Comment by firelightning13** [comment]
@Andrews54757 I just put LegitSoulja's Agar.io Dump in the OgarUL-Client. Now what?

**Comment by Andrews54757** [comment]
do npm install after cd ing into the repo. then do sudo node index.js

**Comment by firelightning13** [comment]
Ive done that, now how to connect to server?

**Comment by uWotMate** [comment]
Everyone I have a solution.

Download the Bagar.io extension and then normally connect to your server

**Comment by LegitSoulja** [comment]
@uWotMate extensions are gay. Agar.io is gay. We are all done with agar.io.

**Comment by firelightning13** [comment]
lol rekt

**Comment by elitajmx** [comment]
works for a while but just kicks out when using bafagio extension

**Comment by Agarian** [comment]
bafagio? lol

**Comment by Agarian** [comment]
Closing 4 now

**Comment by ItzLevvie** [comment]
I managed to find this: https://agario-configurations.s3.amazonaws.com/dev/web/450/GameConfiguration.json (Seems like they've implemented "Rush Mode" but couldn't leak the web server yet)

**Comment by Agarian** [comment]
odd
