### ISSUE TITLE
Fuck you MoneyClip

### ISSUE THREAD

**Issue by hassanila97** [AJS-development/Ogar-unlimited#513]
This is an issue, not with this repo but with **MoneyClip**.  All people that want to tell something to **MoneyClip** plz do it here. I just wanna tell them FUCK YOU as they just fucked this repo that is worth more than their fucking code and servers. 👎 

@Andrews54757 you can close it if its not appropriate :)

**Comment by Agarian** [comment]
?

**Comment by hassanila97** [comment]
Ok then :(

**Comment by Agarian** [comment]
shit
