### ISSUE TITLE
New game??

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#514]
You know what, We just cant dump everything and not care about all the progress OgarUL have made. I mean just wait until something changes in the future. Maybe it wont be like this for long after all..

But how about we just make our own game? I'm not talking about blueprints writting. P.S I hate unreal engine. We could make our own version of agario right of a barebone of unity. I've been working on a slither project that I was 80% done with @Megabyte918 . I may release it to the public, I haven't decided yet.

Or we can just go fully illegal and say f** agario and f** miniclip and just make our own client?? I mean its not illegal if we made it. And who said making a game similar to another was illegal? As long as we dont use the same code/copy as there work for the client. They dont say anything about an illegal server, but we can just make our own client from a base. Just think about it. Ogar Unlimited will actually be unlimited.

**Comment by Andrews54757** [comment]
or we could adapt to a system like agario-clones

**Comment by Andrews54757** [comment]
by hutyd

**Comment by Megabyte918** [comment]
ima just wait a few days, I'm still in denial. hopefully this is all some elaborate prank :'(

**Comment by LegitSoulja** [comment]
@Andrews54757 I think i have an idea #515

**Comment by LegitSoulja** [comment]
Im gonna make a c++ client, that exectues the old script instead of the new scripts, and fix the packets.
