### ISSUE TITLE
(temporary)FIX TO AGAR.IO PRIVATE SERVERS

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#515]
JUST USE THIS EXTENSION : http://a-infinity.tk @AJS-development/ogar-unlimited-devs With this script works, see a live print: 
![image](https://cloud.githubusercontent.com/assets/15003706/15050990/d7c648b6-12cc-11e6-815a-50fc54e93c38.png)
Yes i am from this clan -_-

**Comment by Megabyte918** [comment]
what the hell...

**Comment by Lukkez** [comment]
Really works for me

**Comment by Lukkez** [comment]
![image](https://cloud.githubusercontent.com/assets/15003706/15051049/261382c2-12cd-11e6-9d88-fc98be5b7db5.png)

**Comment by LegitSoulja** [comment]
Hmm, I have an idea now.. Making a program that runs agar and exectues scripts will work.

**Comment by Lukkez** [comment]
That script have a own main.out.js
Agar.io changed to agario.core.js

**Comment by LegitSoulja** [comment]
Yea i know.. We just need that old script back and not the new one.

**Comment by LegitSoulja** [comment]
I seen that because they was working on that. That's where most errors was coming from. The thing was I wasnt able to view the script..

**Comment by Lukkez** [comment]
I think we can make a tampermonkey script use this instead of agario.core.js, and this fix the graphics ugly

**Comment by Lukkez** [comment]
For me it's

**Comment by Lukkez** [comment]
I used my friend c9 account: http://agar.io/?ip=snakeserver-juhbz.c9users.io you can see, it's live

**Comment by LegitSoulja** [comment]
I got something just holdon. I can make a client for this. Windows, Mac, and debian.

**Comment by LegitSoulja** [comment]
Chronium can come in handy finally this time. or EO.total

**Comment by Lukkez** [comment]
Good

**Comment by LegitSoulja** [comment]
@Lukkez was it just main.out that is needed? I can removed the new scripts, and just add that new one.

**Comment by Lukkez** [comment]
No, u need to fix the packets too, and i have a idea, make a .exe client for localhost play, like when i am travelling on plane i wanted to still play with bots, isn't a good idea for people who is some time without internet?

**Comment by LegitSoulja** [comment]
Yea im gonna do all that. And also you can host them 

https://github.com/LegitSoulja/OgarHost

> Since this is no longer needed, I can just dump this and make a client.

**Comment by Lukkez** [comment]
Good, i think i can help at html/css part if want

**Comment by LegitSoulja** [comment]
Pretty much an server that is created, the PID will be stored. Either or if is localhost or not, it will still show a game/server exist. I just wont disable functionality to localhost. And besides, I might just implemented a system to check and see if the port open and decide to display it as localhost or not.

**Comment by Andrews54757** [comment]
I guess its time to break away from the bonds of agarios client and make ogar UL truely unlimited

**Comment by Lukkez** [comment]
Yea, make like a client, i can help, i have some dev programs... because for now isn't **TOTALLY UNLIMITED** and i need to exit for a bit

**Comment by Megabyte918** [comment]
@Lukkez so YOUR snake, i've heard much about you in the clan chat we should splitrun sometime

**Comment by LegitSoulja** [comment]
@Andrews54757 @Lukkez ok and client or a program that can run/fix all agar private servers? Pick.. I can get started working on the program.

**Comment by Lukkez** [comment]
@Megabyte918 Haha, i'm like most of day on chat, just playing
@LegitSoulja The client is a .exe who open and you can run servers or connect to servers who use ogar-unlimited, i think this is a good choose

**Comment by LegitSoulja** [comment]
@Lukkez, But @Andrews54757 might be thinking about making a new web client.. I mean, if we can make our own web client, then Ogar Unlimited will be fully unlimited. Pretty much any ideas we have can be possible.

**Comment by Lukkez** [comment]
Or maybe the .exe open the web? like a windows but not in browser

**Comment by LegitSoulja** [comment]
@Lukkez I mean, Thats the only way to make a program.. I was going to use chronium or eo.total, which will run the client from **//agar.io**. Only thing I will have to do is attatch the old scripts to the browser..

**Comment by Andrews54757** [comment]
I feel exhausted today. need to rest. Good luck guys!

**Comment by Lukkez** [comment]
Oh, ok, and thanks Andrews, me too, i was on school and had some hard things, i will be here for the next 2 hours, and after go study

**Comment by LegitSoulja** [comment]
@Andrews54757 Just pick for me what do you want to do

A. Make a web client. A new agario client that will run in the browser. Giving us a wide spread, of better development, and unleash any creations or ideas we have

B. Make a program that fixes agario to use the old scripts, and fix packets, and just continue workiing on OgarUl from left off.

**Comment by Lukkez** [comment]
@LegitSoulja If andrews choose A i will give the ftp acess on PM to all ;)

**Comment by Andrews54757** [comment]
A is much better, just make sure it is legal

**Comment by Andrews54757** [comment]
@LegitSoulja You will be the head of the client development. I will make you an admin for ajs dev

**Comment by LegitSoulja** [comment]
@Andrews54757 ok sounds good.. A Ogar Unlimited client. I can get to working on that now locally, then maybe get a domain and all setup. and ok

**Comment by Lukkez** [comment]
I think i can later get a .co domain, freenom have some domains for free, and i need to exit, bye

**Comment by LegitSoulja** [comment]
I can get a free .net or .com domain for free. If not then I wouldnt mine buying it. I have like tons of websites, and domains.. Luckily you can only get to pay $10 or more a year, than whatever a month just for a domain.

**Comment by hassanila97** [comment]
Yes.. choose A .. thats a genuine client that doesnt need any programs to run and anyone couls join in 1 click just like before

**Comment by LegitSoulja** [comment]
@hassanila97 thats true, but im still making it lol, not a client to use agar.io, but, I have to have a OgarHosting framework to have abilities to create servers on the spot. Soon I will have an Ogar hosting company. Supporting Ogar and OgarUL, and others I discover thats worthy

**Comment by ErikParacelsus** [comment]
Im on school laptop so i cannot download extension

**Comment by fadythegamer** [comment]
How to add more bots?

**Comment by LegitSoulja** [comment]
@fadythegamer I dont think the that client supports the uid to be displayed..

**Comment by LPArigma** [comment]
@LegitSoulja i got a domanin for a year, it was $0.88 with a .com extension from whois.com, they host sales all the time

**Comment by LegitSoulja** [comment]
@LPArigma Im good. I would accept it if you was a AJS member. We need a ajs with domain control. Not you.

**Comment by LPArigma** [comment]
@LegitSoulja no im not selling it lol im telling you a website to get cheap domains

**Comment by LPArigma** [comment]
@LegitSoulja also may i be part of the development team if you decide to make a webclient?

**Comment by LegitSoulja** [comment]
@LPArigma Yea, I can probably get one for free. Prices is not a problem with me if it was for a decent price for a good domain.

**Comment by Andrews54757** [comment]
why do we need a domain?

**Comment by LegitSoulja** [comment]
@Andrews54757 for our own client silly goose

**Comment by LPArigma** [comment]
@Andrews54757 fo rthe webserver client to be accesed through rather then using you ip as the site address

**Comment by LegitSoulja** [comment]
@LPArigma you mean, for OgarUnlimited servers to be connect to our own client with a ip and port same as agar.io is setup.

**Comment by LPArigma** [comment]
@LegitSoulja need a cloud host? i got a dedicated server rig with 16 gbs of ram and now i have no use for it....

**Comment by Andrews54757** [comment]
Why dont we make it like cigar or something to avoid having domain problems

**Comment by LegitSoulja** [comment]
@LPArigma no, I have all services. Im good.

**Comment by LegitSoulja** [comment]
@Andrews54757 what domain problems?

**Comment by LegitSoulja** [comment]
@Andrews54757 do you just want to use Cigar and script it?

**Comment by LPArigma** [comment]
@LegitSoulja so you going to use a websites cloudhosting service?

**Comment by Andrews54757** [comment]
OK, if our domain is down for a while, people who use ogar unlimited wont be able to access it. If the client is on their computers, we dont need to worry about that. Also, someone probably will have to pay for the domain.

**Comment by Andrews54757** [comment]
I created a modified version of ogar ul on my desktop that also sends the agarioclone client at the same time

**Comment by LegitSoulja** [comment]
@Andrews54757 Dont worry. I can handle that. I've been making website for years. Only problem that could happen is dns problems, Which Cloudflare I trust.

**Comment by LPArigma** [comment]
Here's what i mean I have a dedicated server that you guys could host the site 24/7 on and i could buy your domain.....

**Comment by Andrews54757** [comment]
The bigger problem is if miniclip tries to shut down the server, and they win, what happens to those who use ogar ul?

**Comment by LPArigma** [comment]
we make a new domain

**Comment by Andrews54757** [comment]
I dont think it is safe this way

**Comment by LegitSoulja** [comment]
@LPArigma I have dedicated servers I can add domain extensions too, @Andrews54757 and they wont try to shut us down if we are smart about it

**Comment by Andrews54757** [comment]
We could use the HTTP module and Express and Socket.io modules to include the client within the software. @LegitSoulja It is still risky

**Comment by LegitSoulja** [comment]
@Andrews54757 so your thinking about who ever have OgarUnlimited will have there own client? Ok what about it they have more than 1 server?

**Comment by Andrews54757** [comment]
use a modified version of your ogarhost thing

**Comment by LPArigma** [comment]
wait wait wati, so your saying people can run theyre ogar UL and just type in the domain and it works?

**Comment by Andrews54757** [comment]
yep

**Comment by LegitSoulja** [comment]
@LPArigma they wont have a domain unless they redirect one to there selves. They can do that on there own.

**Comment by LegitSoulja** [comment]
ORR.. OgarUnlimited can have there own domain and such, and people who wants a server can register a sub domain??

**Comment by Andrews54757** [comment]
Also, I was also thinking about plugins that affect the client

**Comment by LPArigma** [comment]
So there would be a default domain for example www.example.ogar/(IP):(PORT)?

**Comment by Andrews54757** [comment]
that is what @LegitSoulja  wants, but there is a way to make it this way www.yourdomain.com

**Comment by LegitSoulja** [comment]
@LPArigma yes.. If the client supports more than one server then you would expect a get request for the ip and port of the server before connecting and joining the game

**Comment by LPArigma** [comment]
actually, that sounds like a good idea!

**Comment by LegitSoulja** [comment]
@Andrews54757 yes, and if theres a client with OgarUnlimited people can register a custom name for the server and if they want to join there server for example they can pay for a domain. And say for example I want a server thats named LegitSoulja right.. it would be legitsoulja.ogarunlimiteddomain.com and legitsoulja subdomain would redirect to my local ip for connections.

**Comment by Andrews54757** [comment]
I dont think that is a good idea. too risky

**Comment by LPArigma** [comment]
At first i was pissed you were abandoning ogar UL because i twitch stream and i host a priv server on my dedicated server rig for me and the viewers but now i kinda like the idea, but ogar ul should still be fixed to be usable for agar.io

**Comment by LegitSoulja** [comment]
@Andrews54757 I mean theres alot of things we can do. I think including a client with OgarUnlimited is a good idea also.

**Comment by Andrews54757** [comment]
I just dont want to see rage comments in the issues area when our servers dont work. How about we host the server, but the software is out there so they can host their own client if they like

**Comment by LPArigma** [comment]
so your going to fix ogar ul to run on the on agar.io?,

**Comment by LegitSoulja** [comment]
@Andrews54757 You mean buying a server? Do you know how much that will cost to host hundreds of servers for free?

**Comment by LPArigma** [comment]
also how come some plugins you can connect to private servers, if we can figure that out then we can fix ogar UL

**Comment by LegitSoulja** [comment]
@LPArigma @Andrews54757 The owner of http://agariohub.net I work with him, and he said he has a fix for it which will be released tomorrow his said.. I'll listen out and see what his plan is to fixing the problems. He might just use a client for his own also.

**Comment by Andrews54757** [comment]
NO, I mean we host a client. but if they dont like it, they could download the client server on their computer and run it on their.

**Comment by LegitSoulja** [comment]
oh ok. idk though yet.

**Comment by LPArigma** [comment]
@Andrews54757 so your saying we can host a public server (not officially public) and if people dont like it they can download ogar UL and host theyre own private onbe?

**Comment by LegitSoulja** [comment]
@LPArigma basically.

**Comment by Andrews54757** [comment]
ok, so they host the server. We host the client. but if they want to host the client on their computer,they can download the client and run it on their computer, this also allows for playing even when being offline

**Comment by LegitSoulja** [comment]
@Andrews54757 ok so is that the plan now? officially?

**Comment by Andrews54757** [comment]
It depends

**Comment by LPArigma** [comment]
@Andrews54757 that would be an amazing feature to implement in, offline mode.....

**Comment by Andrews54757** [comment]
the client and server are different things

**Comment by Agarian** [comment]
i have a VERY OLD bot extension and i can play with ease. But some of my newer ones broke

**Comment by LegitSoulja** [comment]
@Andrews54757 are we using cigar and modifiing it?

**Comment by LPArigma** [comment]
@legitsoulja develop our own

**Comment by LegitSoulja** [comment]
@LPArigma ... Are you andrew?

**Comment by LPArigma** [comment]
@LegitSoulja Develop a new one (my opinion)*****

**Comment by LPArigma** [comment]
Sorry i forgot the last part :P

**Comment by Lukkez** [comment]
Sorry, about the .com domain is waste of time, is better make a custom domain with DNS, i prefer make a custom, with vps, these things

**Comment by LPArigma** [comment]
@Andrews54757 can i have permission to chat in the Ogar UL Development issue please?

**Comment by PrinceDark9243** [comment]
make a fb login system like nbk.io o peoples can save theri progress

**Comment by LegitSoulja** [comment]
@LPArigma I made that only for developers. I'm sorry. 

@PrinceDark9243 If we do make a client, maybe I will implement this.

**Comment by NatsuTheGreat** [comment]
@LegitSoulja Right now it's better to try to focus on fixing the private servers :P

**Comment by LPArigma** [comment]
@LegitSoulja @Andrews54757 I agree with @NatsuTheGreat

**Comment by Parth1999** [comment]
doesnt work someone help plz . It doesnt connect

**Comment by firelightning13** [comment]
@Parth1999 They removed it, it doesnt work now...

**Comment by Parth1999** [comment]
But it works when i locally host ogar v1 on my pc using hamachi but it wont work for online hosted c9.io ogar unlimited

**Comment by ItzLevvie** [comment]
Use http://agar.io/v72/

**Comment by firelightning13** [comment]
Wait, how did u get that?

**Comment by ItzLevvie** [comment]
was hanging somewhere in the code

**Comment by firelightning13** [comment]
OMG it works I can't believe it :""")

(i hope miniclip didnt remove that...)

**Comment by MichaelLeeHobbs** [comment]
@ItzLevvie very nice find.

**Comment by Agarian** [comment]
Yassss!

**Comment by ItzLevvie** [comment]
^^ Patched

**Comment by Agarian** [comment]
omfg

**Comment by problemsofworld** [comment]
@ItzLevvie  still works ?

**Comment by Agarian** [comment]
idk how i loaded it on my tablet...

**Comment by problemsofworld** [comment]
does work this  http://agar.io/v72/?ip=[IP]:[PORT] or not LOL

**Comment by ItzLevvie** [comment]
@problemsofworld nupe

**Comment by problemsofworld** [comment]
why :'( fuck me clip

**Comment by Agarian** [comment]
ffs i reloaded the page on my tablet and got 404

**Comment by problemsofworld** [comment]
@Agarian  same here

**Comment by Agarian** [comment]
agar.io sucks now i give up on it

**Comment by GhostShot3** [comment]
@Lukkez  FireFox script pls

**Comment by Agarian** [comment]
Dont think there is one

**Comment by GhostShot3** [comment]
@Agarian give me firefox script

**Comment by bangana** [comment]
ok it's not working anymore :'( 
![capture](https://cloud.githubusercontent.com/assets/19194066/15098319/c4f11c64-153a-11e6-93b8-9a8bd24b5b6e.PNG)

**Comment by LegitSoulja** [comment]
This no longer works. Closing issue

**Comment by Megabyte918** [comment]
Ripped ;-;
