### ISSUE TITLE
OgarUL Client Development

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#516]
Todo list

**Comment by LegitSoulja** [comment]
Ok who is all helping make this client?

**Comment by NatsuTheGreat** [comment]
I can try.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat Client process is on hold for now until we get a plan going. We have many ideas, but we need to pick one that would be easy for the people to use.

**Comment by Agarian** [comment]
i have some education in html as i take web design classes

**Comment by LegitSoulja** [comment]
@Agarian HTML is like the one language that is the easiest of them all.

**Comment by NatsuTheGreat** [comment]
Minishit can go die, they think they get money by getting players on the official agar.io but they only infuriate people which doesn't benefit them, fuck them.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat I think they are updating and patching a few things. The packet nodes was changed which it doesnt allow any connections, including the original Ogar. Maybe after Ogar updates with the new UpdateNodes we can connect back again..

Its best to wait and see what going to happen to Ogar. They havent deleted it so im guessing there going to update that aswell.

Maybe they wasnt intentionally meaning to block everything, I just think its a security updates. Even for the bots. I dont think they like those.

**Comment by LegitSoulja** [comment]
And even if, they so stingy with money and all just think about it.. We still used it. We still got there ads. I just dont understand what is going on right now, nor what there plan is.

**Comment by Lukkez** [comment]
I will

**Comment by Lukkez** [comment]
Some Todo, 
- 1st Apply the inital html and css
- 2nd Apply bootstrap
- 3rd Make the helloDialog (The bigger part at center who put name etc)
- 4th Put things on helloDialog

**Comment by NatsuTheGreat** [comment]
@LegitSoulja I hope they're just updating. I am very ambivalent now.. I don't know what to do now..

**Comment by LegitSoulja** [comment]
@Lukkez LOL why bootstrap?? Thats unecassary. And a hello dialog? a waste of time.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat I guess wait until tomorrow and see whats going on. Just rest for today lol

**Comment by LegitSoulja** [comment]
@Lukkez I might make a slick smooth template using angularjs and some other things to make the layout easier

**Comment by Lukkez** [comment]
@LegitSoulja Agar.io is made with bootstrap o.o u want only  simple html?
I will post some prints with the reason

**Comment by LegitSoulja** [comment]
@Lukkez No i just dont think we need bootstrap. Im experience in html, and all. I really dont need extra libraries.

**Comment by Lukkez** [comment]
![image](https://cloud.githubusercontent.com/assets/15003706/15058076/9ca5a578-12f0-11e6-82e2-a0f05445862b.png)

**Comment by Lukkez** [comment]
Just that

**Comment by LegitSoulja** [comment]
And I can make a div, same as that thats fluid. We dont need boostrap and all the bootstrap necessities just for that little hello box

**Comment by Lukkez** [comment]
Bootstrap need to the shop, popups, i'm just saying that, if was me i use, we can use cdn, just 1 line of code

**Comment by NatsuTheGreat** [comment]
Have you guys seen what miniclip did to they're game, go see that shit.

**Comment by LegitSoulja** [comment]
one cdn.. Which would be css right? But for the hellobox and all thats also functions with bootstrap js.. It's just not needed. Just because its a cdn doesnt mean anything either. Hosting the files on the site is better than a cdn also.

**Comment by LegitSoulja** [comment]
@Lukkez im just the person who would rather want something unique without extra things. Bootstrap is nice with there layouts, but its not really needed. If we use bootstrap, you might as well just find a good responsize tempate with bootstrap and work from that. But I want to start from scratch.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat ive played but really didnt see no difference except for the new connecting display

**Comment by NatsuTheGreat** [comment]
Their graphics are a whole new thing.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat yea, when i was playing everything was glitching out.. I thought they was still working on it but I didnt pay much attention to the graphics.

**Comment by NatsuTheGreat** [comment]
I hate this update...

**Comment by LegitSoulja** [comment]
@NatsuTheGreat well you know nothing can stay the same forever

**Comment by NatsuTheGreat** [comment]
@LegitSoulja I hope we can get our servers back up.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat eventually. But good news.. Tonite im going to go through agar files and find the new protocol. @Andrews54757  @Lukkez @Megabyte918

**Comment by LegitSoulja** [comment]
Hopefully we can get the server back up

**Comment by Lukkez** [comment]
oh ok

**Comment by Lukkez** [comment]
http://agar.io/agario.core.js see that

**Comment by LegitSoulja** [comment]
@Lukkez I have already grabbed all the server files. Thanks though.

**Comment by LegitSoulja** [comment]
@Lukkez @NatsuTheGreat @Andrews54757 

If anyone interested in agar.io files, ive uploaded a dump here
https://github.com/LegitSoulja/Agar.io-Dump

**Comment by Lukkez** [comment]
Good, for now i will get some and put on mine client, and how u get files?!

**Comment by Lukkez** [comment]
I am like WTF

**Comment by LegitSoulja** [comment]
@Lukkez I have my ways.

**Comment by Lukkez** [comment]
I'll upload this on one website

**Comment by LegitSoulja** [comment]
@Lukkez this is not a client.. I doubt it will work correctly from the dump lol... But good luck. I should've download the dumb waaaayyyy before this even happened.. But I never had thought about the needs of having too.

**Comment by Lukkez** [comment]
I already got one, it's really fast, uploading now

**Comment by Lukkez** [comment]
It's free host
=p

**Comment by LegitSoulja** [comment]
@Lukkez ok good luck with that. I only needed the files to find the new protocol and the new packet nodes so that we can update OgarUnlimited.

**Comment by LegitSoulja** [comment]
I having a feeling Ogar will update the packets too..

**Comment by Lukkez** [comment]
And, worked

**Comment by Lukkez** [comment]
Not all, but says the connecting page

**Comment by Lukkez** [comment]
http://agariofiles.comli.com/

**Comment by LegitSoulja** [comment]
Yea, that all it does. I just said its not a client and will not work correctly.

**Comment by Lukkez** [comment]
Yeah, i know, but we have a part of it

**Comment by LegitSoulja** [comment]
@Lukkez part of what?? We arent trying to get sued here..

**Comment by Lukkez** [comment]
I know, i have some parts of client, i saw the files, and one thing, HTTrack isn't a good program to this

**Comment by LegitSoulja** [comment]
@Lukkez i wasnt using it for that.. I was using it just to get the js files.. I dont care about the other crap.

**Comment by Lukkez** [comment]
Yea i know too, i will see the files if i see some packets, if i find i tell here

**Comment by LegitSoulja** [comment]
packet nodes, and protocols.

**Comment by LegitSoulja** [comment]
You have to clean the code obviously so its readable.

**Comment by Lukkez** [comment]
I know... It's "encrypted"

**Comment by LegitSoulja** [comment]
@Lukkez and its easy to decrypt too.

**Comment by LegitSoulja** [comment]
I got some work to do. Ill be back here later.

**Comment by Lukkez** [comment]
ok, i know how to decrypt, java script beautifer on internet make this automatic, i have finished my work, i will see the things now

**Comment by LegitSoulja** [comment]
@Lukkez jsb doesnt decrypt it xDD it just align the code for you so its readable better.

**Comment by LegitSoulja** [comment]
Best to get a program to clean all the code and decrypt it :) Im like 50% done with that process

**Comment by Lukkez** [comment]
I know some lol http://jsbeautifier.org/ decrypt, just enable option =p

**Comment by LegitSoulja** [comment]
![lol](https://cloud.githubusercontent.com/assets/4976824/15059413/af7926ea-12df-11e6-8f41-6cdf82ae8750.PNG)

LOL I justr realized.. But the encryption agar uses isnt supported here.

**Comment by Lukkez** [comment]
Oh, what's the agario encryption?

**Comment by LegitSoulja** [comment]
Orbfuscate use HEX encoded, which is easy to decode, but its not even hex..

**Comment by Lukkez** [comment]
They use a great encryption but we can still decrypt i think

**Comment by LegitSoulja** [comment]
@Lukkez tbh with you, Im still looking.. All i know its not hex encoded.. I seen this encryption before but forgot what it was.. I know it wont be easy to decode the first time.

**Comment by Lukkez** [comment]
Yea i saw this one on a cigar modified client i downloaded

**Comment by LegitSoulja** [comment]
@Lukkez theres not alot of decryptions for javascript because theres only a few ways javascript can read the data itself..

**Comment by LegitSoulja** [comment]
and im hoping there is reverse engineering..

**Comment by LegitSoulja** [comment]
We already know its nor part of [AES](http://www.movable-type.co.uk/scripts/aes.html)

**Comment by Lukkez** [comment]
Oh, i know why u don't need bootstrap, you can do with style and border values

**Comment by LegitSoulja** [comment]
@Lukkez only thing you was talking about is a style and border radius.

**Comment by LegitSoulja** [comment]
It can be sooo easily created without bootstrap.

**Comment by Lukkez** [comment]
Have more, but still easy without bootstrap

**Comment by LegitSoulja** [comment]
css3 is nothing,

**Comment by Lukkez** [comment]
I wasn't remembering that =p

**Comment by LegitSoulja** [comment]
You should. Or sass. Css3 is both sass and css

**Comment by MichaelLeeHobbs** [comment]
They are not using encryption they are using https://github.com/kripken/emscripten

**Comment by Megabyte918** [comment]
@LegitSoulja I could try and help, but I don't have much free time

**Comment by Andrews54757** [comment]
I DID IT!!! https://client-andrews54757.c9users.io/

**Comment by NatsuTheGreat** [comment]
Not working for me andrews

**Comment by LegitSoulja** [comment]
@Andrews54757 Bravo!. It works!

**Comment by NatsuTheGreat** [comment]
Works now.

**Comment by NatsuTheGreat** [comment]
Is that a separate client? Or agario dump modified?

**Comment by LegitSoulja** [comment]
@NatsuTheGreat looks new. There's php also

**Comment by NatsuTheGreat** [comment]
Okay lel lots of things to still work on though xD

**Comment by LegitSoulja** [comment]
yup

**Comment by NatsuTheGreat** [comment]
Can we get some mass?

**Comment by LegitSoulja** [comment]
Why????? NOo lol

**Comment by LegitSoulja** [comment]
Too fast yoo

**Comment by NatsuTheGreat** [comment]
I can't join :@

**Comment by Lukkez** [comment]
@Andrews54757 Can you give acess to your c9.io workspace? i will ask, i will be playogar(I was trying to get a cool domain but failed xD)

**Comment by Lukkez** [comment]
I'll put some html/css things

**Comment by LegitSoulja** [comment]
@Andrews54757 YES!!, I need to get my site back up asap

**Comment by Lukkez** [comment]
Oops, i logged with another account, sry andrews

**Comment by LegitSoulja** [comment]
Igtg, i'll be back in a few days.

**Comment by Andrews54757** [comment]
Shut down server

**Comment by Andrews54757** [comment]
I will make a repo for it but I cant share the client because of the law, but I will find a way so you guys can get it

**Comment by Lukkez** [comment]
Andrews i sent a modify acess request on [ your c9 workspace](https://ide.c9.io/Andrews54757) I'll try to fix some things with server or client, if don't accept i will make one for me and download your client ;)

**Comment by LegitSoulja** [comment]
@Andrews54757 no problems. I'll be back wednesday. I have to go out of state and party with some old friends. Cya

**Comment by Lukkez** [comment]
cya @LegitSoulja

**Comment by Lukkez** [comment]
@Andrews54757 why did you put that domain at uploads.php, see line
62 and front
``
echo "<a href=\"http://**eureland.me**\">Go Back</a>"; 
?>
``
For what's is that domain?, shouldn't be http://**ogarunlimited.io**?

**Comment by Andrews54757** [comment]
https://github.com/AJS-development/OgarUL-Client

**Comment by Lukkez** [comment]
You can reduce one step, just put the modules inside the folder "client", so, now will only do, ``sudo node index.js"

**Comment by Andrews54757** [comment]
typo

**Comment by Lukkez** [comment]
Oh sry, i'm typing very fast because i'm busy =p

**Comment by Andrews54757** [comment]
no, I made a typo

**Comment by Andrews54757** [comment]
i wanted to say cd into the repo, not the client folder

**Comment by Lukkez** [comment]
Woah, 3k + files

**Comment by Lukkez** [comment]
![image](https://cloud.githubusercontent.com/assets/15003706/15099372/19fdac92-152a-11e6-94cf-6edb8af357e3.png)

**Comment by Andrews54757** [comment]
You should delete your copy of the client, it will do no use, It uses a special packet and I havent shared that yet

**Comment by Andrews54757** [comment]
Im not done with it

**Comment by Lukkez** [comment]
Oh ok, i'll delete the one who is at **Lukkez/Ogar-unlimited-client**

**Comment by Andrews54757** [comment]
I will finish up sooner or later

**Comment by Andrews54757** [comment]
Now, I have to do things

**Comment by Lukkez** [comment]
I can make some things like "clan chooser" ?, i have one who is pratically made, just put in

**Comment by Lukkez** [comment]
When i run  i only see [DEBUG] Listening on *:undefined

**Comment by Lukkez** [comment]
@Andrews54757 
> When i run i only see [DEBUG] Listening on *:undefined
*The client isn't working*

**Comment by Andrews54757** [comment]
What did I tell you, it is not finished

**Comment by Andrews54757** [comment]
It requires some special things

**Comment by Lukkez** [comment]
I know, but on your i can play, i downloaded from your workspace

**Comment by LegitSoulja** [comment]
Where's the patients lol.

**Comment by LegitSoulja** [comment]
@Lukkez did you hear anything Andrew said a while ago?

**Comment by Lukkez** [comment]
lol, i can have all the working client, i can connect to another servers too with this btw i can't connect with the server who come (or isn't?)

**Comment by Lukkez** [comment]
When i did connect("ws://myfriendprivateserver"; worked and i played but with a bit of more lag than normal

**Comment by Lukkez** [comment]
I'll stop chatting here =p i will just wait some time

**Comment by LegitSoulja** [comment]
Dude just wait. Its not even finished

**Comment by Lukkez** [comment]
> i will just wait some time

**Comment by Andrews54757** [comment]
@Lukkez  It took me forever figuring it out, it is not easy to use

**Comment by NatsuTheGreat** [comment]
Somebody is connected to my server...

**Comment by Megabyte918** [comment]
@NatsuTheGreat that's pretty spoopy

**Comment by LegitSoulja** [comment]
https://github.com/AJS-development/Ogar-unlimited/issues/537
