### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by djbencrazy** [AJS-development/Ogar-unlimited#520]
I have a question,
I cigar install on me vps.
but I want Ogar-unlimited and in the place of the cigar server there are no plugins and also a few things that I find to plant this version.
can someone help me.
thank you in advance

**Comment by LPArigma** [comment]
Sounds more like a statement @djbencrazy describe your question please.

**Comment by djbencrazy** [comment]
@LPArigma I've got a client now, but I'm not content with the server that is covered.
I use the cigar. but want to make their own client Ogar-unlimited

**Comment by djbencrazy** [comment]
@LegitSoulja you might help me?

**Comment by LegitSoulja** [comment]
@djbencrazy I have not yet used cigar with OgarUnlimited use. @Megabyte918 probably have.

**Comment by Megabyte918** [comment]
I haven't either lol

**Comment by djbencrazy** [comment]
oke goed jammer dat je niet kan helpen misschien anderen

**Comment by Megabyte918** [comment]
@AJS-development/ogar-unlimited-devs can anyone that has used cigar before help with this?

**Comment by LegitSoulja** [comment]
@djbencrazy Translate cigar help page/wiki if they have one and look for an installation on hosting the client.

**Comment by ErikParacelsus** [comment]
I know someone that uses Cigar but i don't he still using it but i will ask him.

**Comment by markvillar** [comment]
I think @lulzyyy have used Cigar's client on Ogar-unlimited before, I don't know if he still does today.

lulzyyy's server: http://c0nsume.me/

**Comment by djbencrazy** [comment]
@LegitSoulja @ErikParacelsus I have also installed themselves. but I find it much laggy in which I find less than fun. and also less game mode. and other fun things there are not.

@markvillar okay I'm also figuring out a bit how everything fits together. I just think nie nice that not all commands work

**Comment by LegitSoulja** [comment]
@djbencrazy Cigar has there own game client.. You'll have to implement it with it. I dont know is it compatible or not but you can try and see.

**Comment by Agarian** [comment]
@AJS-development/ogar-unlimited-devs agario has a new strange subdomain https://p.agar.io
doesnt do anything ATM

**Comment by firelightning13** [comment]
@Agarian It's a secret page i guess made by miniclip

**Comment by djbencrazy** [comment]
what they have done that we no longer private servers can is not like them

**Comment by lulzyyy** [comment]
yea I'm using modified Ogar Unlimited with modified Cigar :) www.c0nsume.me

**Comment by LegitSoulja** [comment]
@lulzyyy yeeaa,, I dont like cigar now after seeing it lol

**Comment by LegitSoulja** [comment]
And I crashed the first few seconds on the website LOL fail!.

**Comment by LegitSoulja** [comment]
Dude its broken lOL

**Comment by LegitSoulja** [comment]
![fail](https://cloud.githubusercontent.com/assets/4976824/15094875/f5d25838-146e-11e6-8cda-01fbfac56719.PNG)

**Comment by lulzyyy** [comment]
choose the server

**Comment by LegitSoulja** [comment]
I did.. This happens, and then a few seconds or minutes later it crashes

**Comment by LegitSoulja** [comment]
And its very glitchy..

**Comment by lulzyyy** [comment]
lol. i know there's problems with opera and chrome. just use firefox

**Comment by lulzyyy** [comment]
it's working fine

**Comment by Lukkez** [comment]
I was looking to use Ogar-unlimited with Cigar but doesn't work, how you fixed?

**Comment by LegitSoulja** [comment]
![fail2](https://cloud.githubusercontent.com/assets/4976824/15094891/6f8eb702-146f-11e6-812e-f7b4ad942f24.PNG)

Everything glitching out, and theres nothing appearing. There's people on the leadboard which also glitches in and out BUT I CANT SEE ANYONE

**Comment by lulzyyy** [comment]
do you play on firefox?

**Comment by LegitSoulja** [comment]
Yup and i dont see nothing

**Comment by lulzyyy** [comment]
it's glitching on opera and chrome idk why they changed smth in engine

**Comment by lulzyyy** [comment]
i dont know, there's 5000k people registered and a lot of guests playing about 4 months and noone was complaining.

**Comment by LegitSoulja** [comment]
I dont like cigar lol. It's just something about it

**Comment by lulzyyy** [comment]
so you must play shitty regular agario XD

**Comment by Agarian** [comment]
I hate cigar because the server physics sucks

**Comment by Agarian** [comment]
I will NEVER play regular agar

**Comment by lulzyyy** [comment]
but I;m using Ogar-unlimited physics

**Comment by LegitSoulja** [comment]
@lulzyyy I dont like cigar nor agar.io

**Comment by LegitSoulja** [comment]
Its the graphics I dont like with cigar.

**Comment by Lukkez** [comment]
Mine modified cigar is beautiful btw the physics make it sucks, i added much things

**Comment by Lukkez** [comment]
I tried to use ogar-unlimited physics but it crash the server :/

**Comment by lulzyyy** [comment]
Cigar is the only hope for private servers deal with eat. gl making oyour own client xD

**Comment by LegitSoulja** [comment]
F all of this lol. Im gonna make my own game. Agario is dead.

**Comment by Lukkez** [comment]
lol

**Comment by LegitSoulja** [comment]
Anyone knows a good game engine thats c++ instead of unreal engine?

**Comment by Lukkez** [comment]
I know a game who u can make easy servers and the mods for the server is coded with C++ do you want to test (the game use GTA:SA as the base for all)

**Comment by LegitSoulja** [comment]
Im making a game, not implementing for a game.

**Comment by LegitSoulja** [comment]
GTA:SA base? Must be shitty graphics.

**Comment by Lukkez** [comment]
See this again -_-
> Anyone knows a good game engine thats c++ instead of unreal engine?

**Comment by LegitSoulja** [comment]
Yea, and you suggesting a game.

**Comment by LegitSoulja** [comment]
Im just gonna use cry engine. nvm about what I said

**Comment by Lukkez** [comment]
The majority of games are on c++...

**Comment by LegitSoulja** [comment]
CryEngine is c#, c++ and  lua. I can dig that :)

**Comment by LegitSoulja** [comment]
And plus, CryEngine physics, and graphics are good

**Comment by Lukkez** [comment]
Yea, Unreal is too, but u need a very very good pc to run Unreal, i run on a 6GB Ram, I3 4th gen and pc crashed

**Comment by LegitSoulja** [comment]
I have a amd fx-8350, 32GB ram, 4.0-4.2 8mb ghz, and 12GB Nvidia GTX

**Comment by LegitSoulja** [comment]
well 16GB Nvidia GTX, I have 1 12gb, and one 4gb

**Comment by LegitSoulja** [comment]
Built it myself. :)

**Comment by LegitSoulja** [comment]
oh, and I have my own custom made bios, with overclock.

**Comment by LegitSoulja** [comment]
I have a amd fx-8350, 32GB ram, 4.0-4.2 8mb ghz, and 16GB Nvidia GTX

**Comment by firelightning13** [comment]
I have 3rd gen intel core i3-3217U 1.8Ghz, 4 RAM / 3.6 usable with fkin Intel HD Graphic 4000 aka fkin Integrated graphic(not dedicated) with 500GB HDD, I think im gonna die playing with unreal engine, as well as my pc i mean laptop

**Comment by Megabyte918** [comment]
I have a potato

**Comment by firelightning13** [comment]
best joke ever 2016 i think im gonna die
