### ISSUE TITLE
make something that we dont need agario anymore my friends cant play with me :(

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#521]
my c9.io is upgrade can do 10 of server per user  can I connect all of on on website like agario so when player create a party randomy to a server and when join a party send to same one like real agar because agar update sucks I want to make one with a lot of servers not laggy like agar :) any one help

**Comment by LegitSoulja** [comment]
@problemsofworld I had closed my site http://agariohub.tk after what miniclip did. Making a website and all you should wait because all private servers cannot connect to agar.io new client
