### ISSUE TITLE
See fast

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#522]
@AJS-development/ogar-unlimited-devs I saw this: http://52.28.223.51/ this guy leaked ALL the whole agar.io, it's totally working, see fast, the only thing who not work is fb

**Comment by LegitSoulja** [comment]
I have leaked it, but haven't got it working yet.. I wasn't going to create a client from it but I was going to get the scripts and find the new packet nodes and protocols. Nice to know this exist now.

**Comment by Lukkez** [comment]
This is totally working, all functions, people think is **Drgoat** the onwer, he is my friend, he have all the packets, if he give we will can fix the private servers i think

**Comment by LegitSoulja** [comment]
Yes we can actually. Try to get it

**Comment by LegitSoulja** [comment]
That will be less work for me. I've been working on it really slow

**Comment by Lukkez** [comment]
And, this is a koding default ip, if i leak the koding ip i maybe can acess to files... or maybe download
52... 53... 54... is koding ips mostly

**Comment by NatsuTheGreat** [comment]
@LegitSoulja HOW DID YOU DO IT MAN? I AM IN SHOCK XD Please tell me :O

**Comment by LegitSoulja** [comment]
@NatsuTheGreat how did I do what?

**Comment by NatsuTheGreat** [comment]
Yes man!

**Comment by NatsuTheGreat** [comment]
@LegitSoulja How did you get that site? It's just like agar

**Comment by LegitSoulja** [comment]
@NatsuTheGreat You mean this? https://github.com/LegitSoulja/Agar.io-Dump

**Comment by NatsuTheGreat** [comment]
@LegitSoulja That actually works?

**Comment by LegitSoulja** [comment]
@NatsuTheGreat Nah, Its not a client. Its a dump. It can be converted to a working agar.io clone, but I only did that to get the files from the site.. I was in the process of leaking some things throughout agar.io.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat Same as what this guy did http://52.28.223.51/ . He did the same thing, but he got it working. Mines a not working.

**Comment by NatsuTheGreat** [comment]
So if I download it it won't work? I really wanna try out something like that myself.

**Comment by LegitSoulja** [comment]
Holdon before you download it. I have to commit it again. And it will work, but you cant connect.

**Comment by NatsuTheGreat** [comment]
Alright man! I am dying of excitement!

**Comment by NatsuTheGreat** [comment]
Wait but how did he make it so we can connect?

**Comment by NatsuTheGreat** [comment]
I have to go somewhere quickly, report anything you get done here.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat updated.. You can download it if you want.. And i have not figured that out yet.

**Comment by NatsuTheGreat** [comment]
@LegitSoulja Still won't connect?

**Comment by Agarian** [comment]
i need help, if i try to open the file in a browser, it changes from file:///C:/Users/owner/Downloads/Agar.io-Dump-master/index.html
to
http://c/Users/owner/Downloads/Agar.io-Dump-master/index.html
help lol

**Comment by LegitSoulja** [comment]
@Agarian its best to run it on a shared, vps, or a local apache server.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat no, its just a dump. You can get it working if you want

**Comment by Agarian** [comment]
why doesnt the page load?

**Comment by LegitSoulja** [comment]
Because its not a working client, and its not connected to anything. Its just a dumb. Its useless unless you get it working on your own. But im not working on the client right now. I have beem with a slow pace, but ive just been lurking

**Comment by Agarian** [comment]
is there a way to get the client i have to allow server connections?? the page loads but wont connect to anything.

**Comment by LegitSoulja** [comment]
@Agarian use this if it works. http://52.28.223.51/

**Comment by LegitSoulja** [comment]
Actually that doesnt work neither.. I just tested.. @Lukkez what is this??

**Comment by LegitSoulja** [comment]
Client Fail :-1:

**Comment by Agarian** [comment]
yeah connect is not defined.

**Comment by Agarian** [comment]
really tho is there a way to get the client i have to allow server connections?? the page loads but wont connect to anything

**Comment by LegitSoulja** [comment]
I wasnt going to work on the client, but I will see if I can turn the dump I have into a working one. I really didnt want it to be found*, I might make it private afterwards if I do get it working.

**Comment by NatsuTheGreat** [comment]
Awe c'mon :/

**Comment by LegitSoulja** [comment]
@NatsuTheGreat for ajs you can have access to it.. Dont worry.

**Comment by NatsuTheGreat** [comment]
Awesome man!

**Comment by NatsuTheGreat** [comment]
How would I get it working myself though?

**Comment by LegitSoulja** [comment]
@NatsuTheGreat Im going to try to get it working, and ill update the repo and just redownload it

**Comment by NatsuTheGreat** [comment]
Alright, tell me if you succeed. I have some chores to do quickly.

**Comment by Agarian** [comment]
I made a better version of the USA skin lol http://i.imgur.com/2BBpQIB.png

**Comment by NatsuTheGreat** [comment]
@LegitSoulja Any success?

**Comment by LegitSoulja** [comment]
Yea, I figured that there was some things that the original client does have that the dump dont. Some files are missing so its incomplete. I can see its downloading the new agario.core but I dont see where and how its downloading. It's wierd actually. But give me a little bit. I'll eventually get it working.

**Comment by NatsuTheGreat** [comment]
Okay, sorry I am just impatient.

**Comment by Lukkez** [comment]
Updating the dump to agariofiles.comli.com

**Comment by Agarian** [comment]
agario had a new strange subdomain https://p.agar.io
doesnt do anything ATM

**Comment by NatsuTheGreat** [comment]
It's still http://agar.io ...

**Comment by Agarian** [comment]
theres also m.agar.io

**Comment by LegitSoulja** [comment]
m is for mobile

**Comment by LegitSoulja** [comment]
@NatsuTheGreat @Agarian @Lukkez I updated the dump.. Less errors.. Still working on it though

**Comment by NatsuTheGreat** [comment]
Still not connecting though?

**Comment by NatsuTheGreat** [comment]
All the files disappeared...

**Comment by LegitSoulja** [comment]
@NatsuTheGreat refresh, and nope.. Still woking on it

**Comment by LegitSoulja** [comment]
Theres alot of stuff lol

**Comment by NatsuTheGreat** [comment]
Oh there we go, I only had ReadMe.MD there. Now it's fixed.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat Yea I deleted everything and reuploaded.

**Comment by NatsuTheGreat** [comment]
KK.

**Comment by LegitSoulja** [comment]
![errors](https://cloud.githubusercontent.com/assets/4976824/15088814/b500f7d8-13b5-11e6-9621-4bc4c0cd25fe.png)

Just a few of this.. Then im going to detatch facebook sdk and all of that, and remove tokens and etc. Im going to strap it down.

**Comment by NatsuTheGreat** [comment]
http://agar.io/?ip=151.80.98.55:1521

Seems to work.

**Comment by LegitSoulja** [comment]
What server is that?

**Comment by NatsuTheGreat** [comment]
m.agar.io

**Comment by LegitSoulja** [comment]
And also i recorded this a day ago and on agario this always happen to me
http://legitsoulja.info/dl/Agar.io%20-%20Google%20Chrome%205_5_2016%205_38_04%20PM.mp4

**Comment by NatsuTheGreat** [comment]
I have seen people complain about that.

**Comment by LegitSoulja** [comment]
Yea like wtf.. Sucks. Graphics on horrible on this new update

**Comment by NatsuTheGreat** [comment]
There is also a file called ?ip=IP:PORT when we connect to the servers

**Comment by LegitSoulja** [comment]
LOL that is not a file

**Comment by LegitSoulja** [comment]
I might not be able to finish this all tonite though.

**Comment by Megabyte918** [comment]
Whoa... this is a lot of stuff to take in at once

**Comment by Agarian** [comment]
i need help with reducing the pushback on splitting pls lol

**Comment by Megabyte918** [comment]
I'm waiting until private servers are fixed to actually do anything

**Comment by Agarian** [comment]
that tells me it'll never be fixed

**Comment by LPArigma** [comment]
use intellitamper @LegitSoulja and you can explore all the server files and download them, this will allow you to see exactly how it works

**Comment by NatsuTheGreat** [comment]
I don't get intellitamper..

**Comment by NatsuTheGreat** [comment]
So are we going to ever get private servers back? i really miss mine.

**Comment by LegitSoulja** [comment]
@LPArigma I was using wireshark for a little bit, But ill check this out. I dont think i'll need any files, but i can see extra stuff that might be helpful

**Comment by LegitSoulja** [comment]
@NatsuTheGreat Problem not as soon.

**Comment by NatsuTheGreat** [comment]
Minishit is probably doing nothing about it :'(

**Comment by LegitSoulja** [comment]
@LPArigma http://www.intellitamper.com is down.. So i cannot download it.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat They tried to prevent bots.. They failed.. Since they failed, they suck, and they don't want part of private servers.

**Comment by NatsuTheGreat** [comment]
I see no bots, but they're stupid prevention disallows connecting through private servers

**Comment by LegitSoulja** [comment]
@NatsuTheGreat Well, a way to prevent bots is to rewrite coding, so actual bot clients wouldnt know what to do anywhere.

**Comment by NatsuTheGreat** [comment]
Well our private servers don't know what to do anymore either :'( And the sad thing is... bot sites may do re-coding too. :'(

**Comment by LegitSoulja** [comment]
Yea, see thats the reason why private servers wont be updated.. If they do, then bots can be updated prior to the new agario servers update.

**Comment by NatsuTheGreat** [comment]
Can we change our code? it may be hard but we gotta find a way to do it... Im dead bored right now, I tried teaming on agar.io but a 20k team killed my team at 500.. Agar.io is dying..

**Comment by LegitSoulja** [comment]
@NatsuTheGreat well, we could. Or continue making a client. In the end the same thing will happen again, and looking at whats new, its looks like the servers have a key/md_5 or whatever they are using to identify themselves when connecting to agar.io client. So it could be impossible. IDK.

**Comment by NatsuTheGreat** [comment]
but could we try?

**Comment by LegitSoulja** [comment]
@NatsuTheGreat yea, but we still need the packet nodes before we even update ogarul to work with agar.io

**Comment by NatsuTheGreat** [comment]
Okay. I feel really bored, may I help?

**Comment by LegitSoulja** [comment]
Everything is huge, doing this cause alot of frustration, and its time consuming. It gonna take a while.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat You could've been helping

**Comment by NatsuTheGreat** [comment]
> You could've been helping

What do you mean?

**Comment by LegitSoulja** [comment]
@NatsuTheGreat This isn't collaboration work. You could've been helping crack down what we are trying to do.

**Comment by LegitSoulja** [comment]
At first I was going to get OgarUL working with agar.io, but everyone wanted a client. I tried getting the clients working but theres even more to the client to even get it working.

**Comment by NatsuTheGreat** [comment]
Can we go back to making it work with agar.io?

**Comment by Megabyte918** [comment]
@Lukkez that server is exactly what i need, now we have a reference point for the physics to improve ogarul's

**Comment by Agarian** [comment]
i has solution m8

**Comment by Megabyte918** [comment]
k ( ͡° ͜ʖ ͡°)( ͡° ͜ʖ ͡°)( ͡° ͜ʖ ͡°)

**Comment by Megabyte918** [comment]
@Agarian I don't have permission for that chat

**Comment by Agarian** [comment]
click on the link -_-
