### ISSUE TITLE
Private servers coming back?

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#523]
Yoo. Idk if this is new or not but i found a new sub domain of agar.io

> [//P.AGAR.IO](//P.AGAR.IO)

Do you think they are bring private servers back?
Maybe? Maybe not? But what its for?? If its not?

**Comment by Agarian** [comment]
nope. it doesn't do anything. doesn't even load.

**Comment by LegitSoulja** [comment]
Also found some more interesting things

> develop-direct.agar.io:8080
> 151.236.222.67:8080 (151.236.222.67 A=develop-direct.agar.io)


wtf? what is all of this?

**Comment by Agarian** [comment]
not sure, i think that may be the agario database

**Comment by NarutoGamerPro** [comment]
http://agariohub.net/

**Comment by LegitSoulja** [comment]
@NarutoGamerPro That BielSSA work.. I know he has a client. He's not using that forever though. Me and him actually still trying to work some things out with the new protocols.

**Comment by LegitSoulja** [comment]
![proof](https://cloud.githubusercontent.com/assets/4976824/15089214/01dd7058-13bc-11e6-84ea-12bda2a3f385.PNG)

He had problems with it yesterday, and plus his client is php. You wont be able to clone it. Like moon dust split. I have it but I dont think he wants me sharing it 

> http://maq-1.agariohub.net:4030

**Comment by joeryd** [comment]
Port 9999 is Abyss, it's just a web server they use for development probably.

**Comment by joeryd** [comment]
@LegitSoulja http://develop-direct.agar.io:8080/info

**Comment by LegitSoulja** [comment]
@joeryd That looks like a completely new server stats server

**Comment by XxRaizerxX** [comment]
the server is easy to donimate there all noobs in there

**Comment by NatsuTheGreat** [comment]
Hole shit!!!!!!

http://agar.io/?ip=151.236.222.67:9999

This server has it's own facebook login system!

**Comment by XxRaizerxX** [comment]
kewl

**Comment by Lukkez** [comment]
WTF THIS SERVER, WORKED HOLY SHIT, I CANT BELIEVE A GUY DO THAT

**Comment by joeryd** [comment]
It's a test server made by Miniclip, no shit it works..

**Comment by Lukkez** [comment]
Oh :/

**Comment by NatsuTheGreat** [comment]
I was just going to say it's a miniclip server cause of 151.

**Comment by XxRaizerxX** [comment]
people betrey me on that server

**Comment by NatsuTheGreat** [comment]
I think miniclip is on to something.

**Comment by Lukkez** [comment]
I know, 1St april things are really, like pay for private servers, that's why they disabled private servers

**Comment by joeryd** [comment]
I still don't get why you are all complaining so much. It's their game and they can do what they want with it. There is probably a good reason why they changed the packets.

You can't recognize Miniclip by 151, `151.236.220.0 - 151.236.223.255` is a range from Linode.

**Comment by NatsuTheGreat** [comment]
The first three digits of the IP are 151 *facepalm* I found it on m.agar.io

**Comment by joeryd** [comment]
@NatsuTheGreat you did not say that. 

`I think miniclip is on to something.` please stop already.

**Comment by Lukkez** [comment]
151 Don't mean "Miniclip" but the location of their servers, as you said.

**Comment by NatsuTheGreat** [comment]
> I was just going to say it's a miniclip server cause of 151.

Did you read that?

**Comment by Lukkez** [comment]
I'm saying about joeryd
> You can't recognize Miniclip by 151, ``151.236.220.0 - 151.236.223.255`` is a range from Linode.
=p

**Comment by XxRaizerxX** [comment]
any more servers like deez onez

**Comment by NatsuTheGreat** [comment]
I was talking to joeryd lukkez :P

**Comment by joeryd** [comment]
@NatsuTheGreat 151 does not make it a Miniclip server,  it also has nothing todo with the location.

The only thing you both have done is complain.

**Comment by NatsuTheGreat** [comment]
@joeryd Tell me a part where I complained. And if you have not visited m.agar.io you'd see a 151. that is how I recognized it, if you think something is wrong, your bad, It is a miniclip server and I was right. Period.

**Comment by joeryd** [comment]
@NatsuTheGreat 

Searched really quick on my phone:
"I think miniclip is on to something."
"Minishit can go die, they think they get money by getting players on the official agar.io but they only infuriate people which doesn't benefit them, fuck them."
"Have you guys seen what miniclip did to they're game, go see that shit."
"I hate this update..."

And by looking at all the other issues you just say: "wow does this work?"

**Comment by NatsuTheGreat** [comment]
When did I say that?

**Comment by joeryd** [comment]
https://github.com/AJS-development/Ogar-unlimited/issues/516 here and all the other issues.

**Comment by NatsuTheGreat** [comment]
> wow does this work?

I mean that.

**Comment by NatsuTheGreat** [comment]
Your comments are becoming useless junk and spam, I am deleting them.

**Comment by joeryd** [comment]
Go fuck yourself.

**Comment by NatsuTheGreat** [comment]
> Go fuck yourself.

keep this behavior going and you'll get blocked.

**Comment by joeryd** [comment]
I proved myself being right, so you just remove my comments?

**Comment by NatsuTheGreat** [comment]
You were not right, you didn't bother responding until now.

**Comment by joeryd** [comment]
You are spamming all the fucking time, remove your own comments.

**Comment by XxRaizerxX** [comment]
Natsu got rekt

**Comment by NatsuTheGreat** [comment]
Raizor be quit I was venus and you lost to me every single time. I don't have time for people like jeoryd, his abortion was a waste of time aswell.

**Comment by XxRaizerxX** [comment]
Lol

**Comment by XxRaizerxX** [comment]
i was stealing as much mass as i can so i could lvl up

**Comment by XxRaizerxX** [comment]
and whos raizor? hello im raizer nice to meet you

**Comment by NatsuTheGreat** [comment]
You are raizor...

**Comment by XxRaizerxX** [comment]
no im raizer

**Comment by joeryd** [comment]
@NatsuTheGreat you seriously need to get yourself checked by an expert. There really is something wrong with you. Or are you an alcoholic?

**Comment by XxRaizerxX** [comment]
OHHH GET REKT NATSU OMG OHHHH

**Comment by NatsuTheGreat** [comment]
None actually, but I know you drink 5 bottle of vodka everyday. You need physical psychiatrists dealing with crap like you.

**Comment by XxRaizerxX** [comment]
OH GET REKT JOERYD

**Comment by joeryd** [comment]
You are just repeating me, is that all you can make up?

**Comment by NatsuTheGreat** [comment]
I can get all my abc's together and make better words than you.

**Comment by XxRaizerxX** [comment]
you guys know a lot of things except the definition of mercy

**Comment by XxRaizerxX** [comment]
3 days later you guys might be  still arguing

**Comment by NatsuTheGreat** [comment]
We can see that Jeoryd is very quiet right now.

**Comment by XxRaizerxX** [comment]
yeah he might have looked up the definition of mercy

**Comment by joeryd** [comment]
I have social contacts, you probably have no idea what that is.

**Comment by XxRaizerxX** [comment]
you talkin to me?

**Comment by XxRaizerxX** [comment]
i get that

**Comment by NatsuTheGreat** [comment]
yeah look at all those online social contacts who removed you from contacts already.

**Comment by XxRaizerxX** [comment]
you might be arguing with all your social contacts as well as us

**Comment by NatsuTheGreat** [comment]
Sorry that I don't take random people from online and make them my social contacts, you loners probably do that,

**Comment by XxRaizerxX** [comment]
are u talkin to me?

**Comment by XxRaizerxX** [comment]
loner(s)?

**Comment by NatsuTheGreat** [comment]
Talking to you AND jeoryd.

**Comment by XxRaizerxX** [comment]
ok well i have a clan and all the people in my social contacts are from my clan who contribute and have a  youtube channel that could cause lots of hate toward people who make fun of me

**Comment by NatsuTheGreat** [comment]
Okay? xD You don't them your clan in real life xD

**Comment by XxRaizerxX** [comment]
yeah many of them i know irl

**Comment by NatsuTheGreat** [comment]
on a scale from 1 - 10 how much do you think I believe that?

**Comment by XxRaizerxX** [comment]
1 2 3 4 5 6 7 8 9 10

**Comment by NatsuTheGreat** [comment]
Pick one.

**Comment by XxRaizerxX** [comment]
im giving you that option

**Comment by NatsuTheGreat** [comment]
Oh my god... I asked you ON A SCALE FROM `1 - 10 YOU PICK A NUMBER IN THAT RANGE AND GIVE IT TO ME. HOW STUPID CAN ONE BE TO NOT UNDERSTAND?

**Comment by XxRaizerxX** [comment]
Im sorry

**Comment by joeryd** [comment]
Mental disorder.

**Comment by joeryd** [comment]
Natsugreat

**Comment by NatsuTheGreat** [comment]
You have ADHD jeoryd so you're not too bright either.

**Comment by XxRaizerxX** [comment]
Joeryd im the one with the mental disorder

**Comment by XxRaizerxX** [comment]
and natsu i have ADD

**Comment by NatsuTheGreat** [comment]
I didn't know that until now.

**Comment by XxRaizerxX** [comment]
no joke
im just like VSabertail/StormGS

**Comment by XxRaizerxX** [comment]
except VSabertail is fucking ripped in real life

**Comment by NatsuTheGreat** [comment]
Hate that person.

**Comment by XxRaizerxX** [comment]
Yeah i know you do

**Comment by XxRaizerxX** [comment]
omg 
i 
know 
knw

**Comment by XxRaizerxX** [comment]
WHATS WRONG WITH YOU

**Comment by XxRaizerxX** [comment]
YOU HATE VSABERTAIL

**Comment by joeryd** [comment]
Why do you remove facts?

**Comment by XxRaizerxX** [comment]
Joeryd

**Comment by NatsuTheGreat** [comment]
I remove the trash you saw jeoryd, not facts. Trash shouldn't stay in the issue area.

**Comment by NatsuTheGreat** [comment]
yeah I hate vsabertail raizor, what now :P

**Comment by XxRaizerxX** [comment]
You know NatsuTheGreat you should be removed cause your trash

**Comment by Megabyte918** [comment]
Guys no hate pls

**Comment by XxRaizerxX** [comment]
STAY OUT OF THIS MEGABITE

**Comment by XxRaizerxX** [comment]
you will get hurt xD

**Comment by Megabyte918** [comment]
ugh

**Comment by XxRaizerxX** [comment]
go fuck yourself megabyte

**Comment by joeryd** [comment]
Are you VSabertail?

**Comment by NatsuTheGreat** [comment]
Raizor where you given birth to when a dog was taking a shit? Lmao?

**Comment by firelightning13** [comment]
I was wait for someone to say that

**Comment by Megabyte918** [comment]
if only the servers didn't have anti-teaming...
