### ISSUE TITLE
CLIENT WORKING!!

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#525]
@AJS-development/ogar-unlimited-devs 

Hey, I got good results :)

> http://client.ogar.ml/

And its weird you can play with no server right now. Its like local lol

**Source**: https://github.com/LegitSoulja/Agar.io-Dump

**P.S You cannot run this locally!.**

**Comment by LegitSoulja** [comment]
@NatsuTheGreat @Agarian @Lukkez

**Comment by NatsuTheGreat** [comment]
Awe I wanted to run something locally xD

**Comment by LegitSoulja** [comment]
@NatsuTheGreat Yea, I doesnt run locally .. I had to figure out the hard way

**Comment by NatsuTheGreat** [comment]
So would I have to port forward or something?

**Comment by LegitSoulja** [comment]
Um, no. It has to be on a domain

**Comment by NatsuTheGreat** [comment]
Oh shit. How do I get one? :/

**Comment by LegitSoulja** [comment]
Um, I can see if I can turn it locally.. There will be extra files I will have to go find, and theres some things I will have to take out

**Comment by LegitSoulja** [comment]
Like I DONT EVEN KNOW HOW THE GAME IS RUNNING NOW!!

**Comment by NatsuTheGreat** [comment]
Lol

**Comment by LegitSoulja** [comment]
And you know.. This one is running smoother than agar.io right nnow

I dont even know how thats possible lol

**Comment by NatsuTheGreat** [comment]
Well cause barely anyone is on.

**Comment by LegitSoulja** [comment]
yea but remember that glitching out problem I had? Its not doing it now.

**Comment by NatsuTheGreat** [comment]
Nice!

**Comment by LegitSoulja** [comment]
Like i want to know how this server is running?? Like can we finally now run agario through web?? LOOL

**Comment by NatsuTheGreat** [comment]
I hope we can run it locally or just port forward too :/

**Comment by NarutoGamerPro** [comment]
Very good

**Comment by LegitSoulja** [comment]
Who is joining saying turn off auto team? Im not even in control of these server, nor how tf is working rn.. LOL

**Comment by LegitSoulja** [comment]
RIP lol finally died

**Comment by NatsuTheGreat** [comment]
But how did you get the domain?

**Comment by LegitSoulja** [comment]
I had made this domain for OgarConsole because it was going to be a Console manager for the OgarConsoles.. You can get free domains online from places. I have my own hosting, the only thing I have to do is redirect it to my host using cloudflare.

**Comment by NatsuTheGreat** [comment]
Oh well rip me.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat Yea's not possible for local right now. There's still alot of things that needs to be fixed.. Im going to update the client with the old protocol... Maybe we can be able to connect to the servers afterwards.

**Comment by NatsuTheGreat** [comment]
Okay :'(

Anyway to fix the original servers without having to make a client?

**Comment by LegitSoulja** [comment]
Luckily for https://www.dropbox.com/s/543iaqjxw712nei/Infinity%20-%20Release.zip?dl=0 I might can..

**Comment by LegitSoulja** [comment]
Maybe I can go back to the old version..? Im doing some tests

**Comment by NatsuTheGreat** [comment]
Hmm okay

**Comment by LegitSoulja** [comment]
@NatsuTheGreat Sorry, I dont think its possible..

**Comment by NatsuTheGreat** [comment]
Awe dangit.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat I got a thing though. Im just going to have an illegal client, and if anyone wants to play there server they can connect through it.. Just until i find protocols from agar.io

**Comment by NatsuTheGreat** [comment]
Okay :P

**Comment by LegitSoulja** [comment]
It will connect through http://client.ogar.ml/?ip=127.0.0.1:545 for example.. I might as well use that domain. After I set all of that up you will be able to connect through it..

**Comment by Agarian** [comment]
I don't think its working, opening the html file changes the URL from 
file:///C:/Users/owner/Downloads/Agar.io-Dump-master/index.html
TO
http://c/Users/owner/Downloads/Agar.io-Dump-master/index.html
STILL

**Comment by LegitSoulja** [comment]
@Agarian You cannot run this locally once again!. You will get something like this http://client.ogar.ml/experimental/ not http://client.ogar.ml/

**Comment by Agarian** [comment]
i keep wasting my time finding a damn client that can at least know how to connect to servers. no more.

**Comment by LegitSoulja** [comment]
@Agarian Im working on it.. Use cigar or something.

**Comment by LegitSoulja** [comment]
Almost done :) before client is working

**Comment by Parth1999** [comment]
Finally ! :+1: \

**Comment by NarutoGamerPro** [comment]
I support it

**Comment by Parth1999** [comment]
Still cant connect to my private server lol . Little to excited i have allowed the use of other client but really guys u guys do a great job here i didnt even know abc of programming in js :P . You guys are awesome i have been following this issue when the Private servers no longer work issue was released.
i was reading every comment and tried everything u guys were try :P but nothing was succeeded . Atlas i decieded to wait and still waiting :) . Great job! I support you guys.

**Comment by problemsofworld** [comment]
@LegitSoulja  Can I add my server to ur client ?

**Comment by ItzLevvie** [comment]
@LegitSoulja HTTrack Website Copier is soo good, tried it on slither.io uploaded the files on to my VPS and I was able to join my slitherio private server xD

**Comment by ItzLevvie** [comment]
@problemsofworld That's not his server. It's a development server for Miniclip where they test their changes on that server before it's publicly uploaded to the real servers.

**Comment by firelightning13** [comment]
@ItzLevvie wow

**Comment by LegitSoulja** [comment]
@problemsofworlds in that case I would've been had a OgarUL server there && my site would be up >> http://AgarioHub.tk

**Comment by LegitSoulja** [comment]
@problemsofworld

**Comment by ItzLevvie** [comment]
There we go http://udkk844444b2.decuge31.koding.io/

**Comment by LegitSoulja** [comment]
@iTzLevvie is that the old main_out? 7.5.16

**Comment by ItzLevvie** [comment]
nupe the new one :/

**Comment by LegitSoulja** [comment]
Useless 😕

**Comment by ItzLevvie** [comment]
I used to have an old main_out but my computer had to get formatted.

**Comment by LegitSoulja** [comment]
Well that could've me saved sssooo much time. I can't even find the old

**Comment by LegitSoulja** [comment]
I have the protocols, I updated Ogar ul on my end, I can join but I can't move nor anything.. Still work in progress *sigh*

**Comment by ItzLevvie** [comment]
okay

**Comment by LegitSoulja** [comment]
Sucks I haven't even been to sleep yet. It'd 10a.m. I caught an all nighter. Thanks too monster energy lol

**Comment by joeryd** [comment]
"I have the protocols, I updated Ogar ul on my end, I can join but I can't move nor anything.. Still work in progress sigh"

In short: you don't have the right packet structure.

**Comment by LegitSoulja** [comment]
@joeryd I'll be done soon after I gather the rest. I found the protocols but there's nodes I still have to test out

**Comment by ItzLevvie** [comment]
well i found this http://ac.gcommer.com/ @LegitSoulja

**Comment by NatsuTheGreat** [comment]
Is that the old one?

**Comment by NatsuTheGreat** [comment]
http://prntscr.com/b1d1vd

**Comment by LegitSoulja** [comment]
@NatsuTheGreat and what does this supposed to mean?? Lol

**Comment by NatsuTheGreat** [comment]
it's the file I was talking about yesterday :P

**Comment by LegitSoulja** [comment]
That's not a file though.. Ok say for an example you connect using that GET request. It's part of index.html but it redirects/update on the request information. Basically it only changes the we socket on connecting.

**Comment by LegitSoulja** [comment]
ws*

**Comment by NatsuTheGreat** [comment]
I get it when I try to connect to my server.

**Comment by LegitSoulja** [comment]
It's a request. It's not a file its more like data.

**Comment by NatsuTheGreat** [comment]
kk.

**Comment by LegitSoulja** [comment]
The data is the ip and port obviously

**Comment by joeryd** [comment]
Do any of you have an idea what you are talking about, it really seems like you've no idea.

**Comment by LegitSoulja** [comment]
Yes.. What about you?

**Comment by NatsuTheGreat** [comment]
@joeryd Do you know what you're talking about saying that?

**Comment by Andrews54757** [comment]
I created the client here http://client-andrews54757.c9users.io/. but how did you get the server?

**Comment by LegitSoulja** [comment]
Is the client using the old js?

**Comment by Andrews54757** [comment]
no

**Comment by Andrews54757** [comment]
BTW it also works on localhost

**Comment by LegitSoulja** [comment]
Do you have an updated server?

**Comment by Andrews54757** [comment]
what updated server

**Comment by LegitSoulja** [comment]
Did you update OgarUL? What do you mean by how can you get the server?

**Comment by ItzLevvie** [comment]
I'm making my own .sh file so I can update the client if there was an update made to the Agar.io website :P

**Comment by Andrews54757** [comment]
so, I created the client there, from your dump files, but how did you get yours to connect with the server

**Comment by Andrews54757** [comment]
I will share my c9 repo with you if you have an account

**Comment by Andrews54757** [comment]
These are my files https://preview.c9users.io/andrews54757/client

**Comment by LegitSoulja** [comment]
Because it's not local host. And idk what server that is. I'm still puzzled on how it's even there

**Comment by Andrews54757** [comment]
What did you do for yours

**Comment by LegitSoulja** [comment]
@ItzLevvie said its an agar.io development sever but I don't understand how it's connecting to it.

And pretty much the same thing you did. I fixed most files, and errors, and recoded a few things.

**Comment by ItzLevvie** [comment]
Download agar.io/mc/atlas/main_shop.xml and move it to /client/mc/atlas/
Download agar.io/mc/particle/LevelUpSlotBar-ipadhd.plist and move it to /client/mc/particle/

**Comment by LegitSoulja** [comment]
There's a shop xml in mc/atlas. Just relocate. I have the plist app but forgot to add it to the commit lol

**Comment by LegitSoulja** [comment]
The plist isn't really needed btw. It's just the agar.io mobile app. Which will eventually redirect mobile to the App Store

**Comment by LegitSoulja** [comment]
Oops. And if I was you I would take the miniclip store functionality all the way out.

**Comment by Andrews54757** [comment]
it did nothing

**Comment by LegitSoulja** [comment]
@Andrews54757 theres really no effect.. And that wont make it work btw.. I dont even know what the purpose of fixing those 2 files

**Comment by LegitSoulja** [comment]
Ill get what you did from c9, and i will see what i can do with it

**Comment by LegitSoulja** [comment]
Well how can I download it?

**Comment by Andrews54757** [comment]
what is your c9 account. Im just gonna share with you

**Comment by LegitSoulja** [comment]
@Andrews54757 I dont have c9.. I dont have no need for it

**Comment by Andrews54757** [comment]
ok then, then I will give you the download link

**Comment by LegitSoulja** [comment]
oke

**Comment by Andrews54757** [comment]
[client.tar.gz](https://github.com/AJS-development/Ogar-unlimited/files/253500/client.tar.gz)

**Comment by XxRaizerxX** [comment]
guys 
private servers dont work anymore?

**Comment by Andrews54757** [comment]
yes

**Comment by LegitSoulja** [comment]
@Andrews54757 ok got it

**Comment by XxRaizerxX** [comment]
how do we fix this

**Comment by LegitSoulja** [comment]
We are trying too

**Comment by NatsuTheGreat** [comment]
@Andrews54757 

> BTW it also works on localhost

How?

**Comment by LegitSoulja** [comment]
@NatsuTheGreat he converted it using nodejs servers instead.. I never tried that way

**Comment by Andrews54757** [comment]
Because I made it that way.

**Comment by LegitSoulja** [comment]
Yeaa, What he said O.o

**Comment by NatsuTheGreat** [comment]
Oh. Andrews could you help me out?

**Comment by Andrews54757** [comment]
@NatsuTheGreat You might never know how good I really am

**Comment by LegitSoulja** [comment]
@NatsuTheGreat It doesnt connect though.. Which means it doesnt work. But m going to see if I can make it work

**Comment by Andrews54757** [comment]
The only thing that confuzzles me is packets. It just makes me angry and frustrated. I mean, I tried learning it but it just makes me confused.

**Comment by LegitSoulja** [comment]
@Andrews54757 Use a hex editor, and read the bytes

**Comment by LegitSoulja** [comment]
@Andrews54757 If you know how to edit memory of a program its the same way.

**Comment by NatsuTheGreat** [comment]
Holy shit my server worked for a second. Then it failed. The nodes are really screwed up.

**Comment by Andrews54757** [comment]
no, like what agario sends to its servers. I can read it, but i cannot implement it into my code as I get confused with the buffers and everything

**Comment by Andrews54757** [comment]
So, did you figure it out?

**Comment by NatsuTheGreat** [comment]
I connected through https://, spectated, and saw the screwed up nodes. Then it turned white.

**Comment by LegitSoulja** [comment]
@Andrews54757 I really dont think localhost will work.. It has to be on a domain. Same effect of running this on a apache server.

**Comment by Andrews54757** [comment]
Well, it might, we will have to change some code, but i think, it is possible

**Comment by Andrews54757** [comment]
Mabye we should copy off cigar or https://github.com/huytd/agar.io-clone

**Comment by Andrews54757** [comment]
I think that all I need is the old agario files

**Comment by LegitSoulja** [comment]
Yea, changing the codes will work.. I know facebook is a reason why it doesnt work. Facebook send packets to agar.io as well. And since its not on a domain it wont work the way you think it would

**Comment by LegitSoulja** [comment]
The old is what we need to make a client, but i couldnt never get a hold of the old files.

**Comment by Andrews54757** [comment]
I did dump the old client on my computer, but I reset it because of a virus

**Comment by LegitSoulja** [comment]
Ouch, That sucks. Same for a friends of mines. He had reset his whole entire computer, and he has an old one but its modified and he wont share it because it works with his client he made, specifically for his site.

**Comment by Andrews54757** [comment]
However, I found some gists such as this https://gist.github.com/edolganov/bda5ba88512bbc6a1f2c

**Comment by LegitSoulja** [comment]
Hmm.. Could we use that? I mean OgarUL may have to be updated to work with it

**Comment by Andrews54757** [comment]
I FOUND IT https://github.com/rapodaca/agario/tree/master/public

**Comment by joeryd** [comment]
Just use web.archive.org.....

**Comment by LegitSoulja** [comment]
@Andrews54757 Did you find a web version? And not a node version?

**Comment by XxRaizerxX** [comment]
what

**Comment by Lukkez** [comment]
wot

**Comment by XxRaizerxX** [comment]
legitsoulka you have to add anti team in your server really IM GETTING ANTI TEAM PUNISH FOR NOTHING I DID NOT TEAM

**Comment by NatsuTheGreat** [comment]
Dude.. He has no control over the server..

**Comment by XxRaizerxX** [comment]
Anti team for not teaming i split and shoot a virius and have a battle and someone eats some of me and i loose cause my mass keeps going down

**Comment by XxRaizerxX** [comment]
wtf he doesent

**Comment by XxRaizerxX** [comment]
then wtf

**Comment by NatsuTheGreat** [comment]
... It's a server that was leaked very recently... It's the agar.io files, they didn't make options to turn anti teaming off.

**Comment by XxRaizerxX** [comment]
how did he add the feature of anti team then

**Comment by Lukkez** [comment]
It's a self made server, no control, just the files

**Comment by NatsuTheGreat** [comment]
Omfg.. IT WAS THERE. Agar.io's files had the code in it.

**Comment by XxRaizerxX** [comment]
well then how come i cant make a party then

**Comment by NatsuTheGreat** [comment]
It's a one root server. You connect to the same thing, he does not have 200+ running servers like Agar.io does

**Comment by XxRaizerxX** [comment]
oh

**Comment by NatsuTheGreat** [comment]
You can't just expect everything at once.

**Comment by XxRaizerxX** [comment]
why did moneyclip do this anyway it ruined everyone there is lots of hate and the update caused millions to quit agar.io

**Comment by NatsuTheGreat** [comment]
We need to get the previous server files. A LOT of stuff was done by miniclip. I really wish they didn't update anything. It's the prevention of bots that ruined this. The only and ONLY reason i see why to get rid of servers is because the connections are connecting to the official agar.io client which makes about 250k players, (Private server players, bots, private server bots, etc) Those probably clog memory and cause lag. As I have played, there are a lot less servers and more people on them. Less lag too.

**Comment by problemsofworld** [comment]
Plz run bots

**Comment by problemsofworld** [comment]
how to use skins

**Comment by problemsofworld** [comment]
plz someone help me I want to run my server 2.5 ram

**Comment by Megabyte918** [comment]
This conversation is pretty interesting. I'm excited.

**Comment by ItzLevvie** [comment]
There we go finished my script: https://github.com/ItzLevvie/Agar.io-files/blob/master/startDownload.sh

**Comment by NatsuTheGreat** [comment]
What does it do?

**Comment by XxRaizerxX** [comment]
it might make us more stupid

**Comment by XxRaizerxX** [comment]
might make something wrong and we might break the agar.io moneyclip rules

**Comment by NatsuTheGreat** [comment]
No, it wouldn't make you stupid cause you're at the max level of stupidity raizor.

**Comment by XxRaizerxX** [comment]
You just saying that cause your jealous

**Comment by NatsuTheGreat** [comment]
And how may I be jealous?

**Comment by XxRaizerxX** [comment]
cause im smarter than you

**Comment by XxRaizerxX** [comment]
sometimes your smarter than me and sometimes im smarter than you

**Comment by NatsuTheGreat** [comment]
You have ADHD, you love vsabertail, and now I can tell you're even more stupid cause your dumb assumptions.

**Comment by XxRaizerxX** [comment]
i dont love vsabertail

**Comment by NatsuTheGreat** [comment]
You had a mental break down when I said I hated him. Go on discord and talk there.

**Comment by XxRaizerxX** [comment]
hes my friend

**Comment by LegitSoulja** [comment]
@XxRaizerxX Kids aren't allowed here btw.. jk

**Comment by LegitSoulja** [comment]
@ItzLevvie that was very pointless. But if someone wants the files they just got to run that script.

**Comment by ItzLevvie** [comment]
@LegitSoulja ik and lol Miniclip patched connecting to the development server.

**Comment by Agarian** [comment]
?

**Comment by LegitSoulja** [comment]
@ItzLevvie Yea, They shouldve added a .httaccess a long time ago.. You can still bypass and enter there server though.

**Comment by XxRaizerxX** [comment]
Natsu is a asshole

**Comment by ItzLevvie** [comment]
@XxRaizerxX calm down xD

**Comment by LegitSoulja** [comment]
@NatsuTheGreat is cool. You'r an arsehole though

**Comment by NatsuTheGreat** [comment]
@LegitSoulja Thanks man. I appreciate it.

**Comment by XxRaizerxX** [comment]
HE IS BEING MEAN TO ME
:'( i have mental issues its not my fault

**Comment by LegitSoulja** [comment]
@XxRaizerxX Your mental problems you can fix on your on time. You don't have to issue your issues here.

**Comment by NatsuTheGreat** [comment]
@XxRaizerxX Stop creating drama here please. Any comments disturbing the doing of other people, will be deleted.

**Comment by XtremePlayzCODE** [comment]
this is getting juicy

**Comment by XtremePlayzCODE** [comment]
the fact your still working on actual working versions without clients

**Comment by XtremePlayzCODE** [comment]
i already got that cracked

**Comment by LegitSoulja** [comment]
Dude go work on your random equation thing or whatever for school. You don't have nothing cracked or crack or whatever.

**Comment by XtremePlayzCODE** [comment]
I kinda do actually

**Comment by XtremePlayzCODE** [comment]
Splits and w's dont work, bots dont, basically you can only move around

**Comment by LegitSoulja** [comment]
Yea yea yea. I don't see someone with no experience crack something..

**Comment by XtremePlayzCODE** [comment]
OH OK SO NOW YOU SAY "I DIDN'T SAY YOU HAD BAD EXPERIENCE" AND NOW YOUR SAYING IT?

**Comment by LegitSoulja** [comment]
Well if only a few things worked you don't have nothing cracked. Your just saying things.

**Comment by XtremePlayzCODE** [comment]
Well not entirely cracked, but I'm getting there

**Comment by XtremePlayzCODE** [comment]
Just let me finish

**Comment by XtremePlayzCODE** [comment]
Get back in the woods, panda

**Comment by LegitSoulja** [comment]
Lol okay.. Bye now

**Comment by XtremePlayzCODE** [comment]
k

**Comment by LegitSoulja** [comment]
Go learn how to code. Noob.

**Comment by XtremePlayzCODE** [comment]
I DO KNOW HOW TO CODE FUCKING DOORKNOB

**Comment by XtremePlayzCODE** [comment]
This issue = cringe montage

**Comment by XtremePlayzCODE** [comment]
cuz the panda's here

**Comment by LegitSoulja** [comment]
What was that? Dont make me bring up the work you TRIED to do.. With no idea of what the hell you are doing

**Comment by XtremePlayzCODE** [comment]
You think that I don't know how to code

**Comment by XtremePlayzCODE** [comment]
And let me tell you, your wrong.

**Comment by XtremePlayzCODE** [comment]
IT WAS 3:00 AM

**Comment by XtremePlayzCODE** [comment]
Go take your brain mold somewere else, scrub

**Comment by LegitSoulja** [comment]
I don't think, I Know.. Plus you even told me you don't. And even on stackoverflow you can't even get help because your work is rediculus

**Comment by XtremePlayzCODE** [comment]
Says the one who can't spell

**Comment by XtremePlayzCODE** [comment]
"rediculus"

**Comment by XtremePlayzCODE** [comment]
rediculous**

**Comment by XtremePlayzCODE** [comment]
your welcome

**Comment by LegitSoulja** [comment]
Says the dude who said they don't know there A,B,C's in JavaScript Hahaha

**Comment by LegitSoulja** [comment]
Grammar is the only come back kid? I'm on a phone.

**Comment by LegitSoulja** [comment]
I will roast you right here up in these issues.. You feel me? This panda gonna go back in the woods okay?? Just to get away from people like you

**Comment by LegitSoulja** [comment]
I guess nobody can't code after 3am lol. I work 24/7. Your work is work. If you can't do something simple at 3 am then you cannot code obviously

**Comment by NatsuTheGreat** [comment]
C'mon little red sirius dumpster, where are you? The trashman come to my house to take trash out on Tuesdays, they don't wanna miss you.

**Comment by NatsuTheGreat** [comment]
> your 

I don't know why you say Soulja can't spell when you don't know the difference between you're and your.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat look at this work this kid tried to do https://github.com/XtremePlayzCODE/randmath

**Comment by NatsuTheGreat** [comment]
The fuck is that supposed to do?

**Comment by Agarian** [comment]
lemme try it

**Comment by LegitSoulja** [comment]
You probably don't even want know

**Comment by NatsuTheGreat** [comment]
getRandomNumber() I can tell this kid is first experience trying out new arithmetic in code...

**Comment by Agarian** [comment]
it generates random equations as in the name

**Comment by Agarian** [comment]
literally

**Comment by Agarian** [comment]
theres a "change difficulty" button

**Comment by NatsuTheGreat** [comment]
Totally focusing on random equation here little sirius fake. WE ARE GETTING AGAR.IO STUFF DONE, not little random equations xd

**Comment by Agarian** [comment]
idk what i missed i was playing Minecraft xD

**Comment by NatsuTheGreat** [comment]
Missed a fight,

**Comment by Agarian** [comment]
k then

**Comment by LegitSoulja** [comment]
He said he cracked agario before anyone else has LOL. I'm dying laughing right now

**Comment by NatsuTheGreat** [comment]
'Split and w's doesn't work'

^^ really cracked!

**Comment by Agarian** [comment]
xD

**Comment by NatsuTheGreat** [comment]
He called Soulja a panda then a doorknob. He thinks we would believe him he has experience. Probably copied someone on that equation thing xd

**Comment by Agarian** [comment]
this massive thing only took 1 hour to build thanx to a magic mod called world edit ♥
![capture](https://cloud.githubusercontent.com/assets/15255724/15095818/754a29e4-14a9-11e6-8378-a21cb35ea723.JPG)

**Comment by Agarian** [comment]
wait a doorknob?

**Comment by LegitSoulja** [comment]
That kid kept begging me to help him. And he kept begging me to help him make bits for agario lol

**Comment by LegitSoulja** [comment]
I like to turn knobs, he could slob on my knob though ...



Jk. I'm not gay

**Comment by Agarian** [comment]
lol, and how is calling someone "doorknob" offensive in any way??

**Comment by NatsuTheGreat** [comment]
'doorknob'
'panda' 
CWL!

**Comment by Agarian** [comment]
CWL? i don't know all the abbreviations used in chatting :P

**Comment by NatsuTheGreat** [comment]
Crying with laughter :P

**Comment by NatsuTheGreat** [comment]
http://prntscr.com/b1k4k6

Look at that crap, look at that spelling!

**Comment by Agarian** [comment]
oh :D

**Comment by Agarian** [comment]
pro spelling

**Comment by LegitSoulja** [comment]
Dude, Look this dude made a question on [stackoverflow](http://stackoverflow.com/questions/36852806/javascript-pick-a-random-equation-with-random-numbers?noredirect=1#comment61277382_36852806) right

In return, His post was stupid, and it was deleted by stackoverflow.. HAHA When does that ever happen?

**Comment by Agarian** [comment]
i shouldn't bee participating in this verbal fight against Xtreme so Cya :smile:

**Comment by NatsuTheGreat** [comment]
@LegitSoulja LMAO!!!

**Comment by Agarian** [comment]
what was his post (I'm curious of this)

**Comment by LegitSoulja** [comment]
About the equation thing lol

**Comment by LegitSoulja** [comment]
![wyg](https://cloud.githubusercontent.com/assets/4976824/15095853/e0f8aad6-1499-11e6-9dac-442e813096f1.PNG)

**Comment by LegitSoulja** [comment]
How does bots be a thing I wanted to make? When this kid kept asking me over and over to help him make bots.. LOL

**Comment by LegitSoulja** [comment]
Then he got mad at me and Andrews because he kept asking if he can join AJS but was denied.

**Comment by Agarian** [comment]
drama queen

**Comment by NatsuTheGreat** [comment]
As he said "it's simple af" WHY IS HE ASKING FOR HELP THEN? XDD

**Comment by Agarian** [comment]
beats me

**Comment by LegitSoulja** [comment]
Then he was talking about he hacked facebook, and have alot of accounts he was going to use for the bots lol.. I would share the whole convo but its stupid.. I was just going along with this kid, but then he just got on my nerves

**Comment by LegitSoulja** [comment]
Like this kid really has the nerves to think he can boss me around.. Lol.. This was before that pic i just showed.

![capture](https://cloud.githubusercontent.com/assets/4976824/15095858/db3fabe8-149a-11e6-9812-3ea95022bf35.PNG)

**Comment by NatsuTheGreat** [comment]
That kid... He'd need the token or cookies, not just the account. That is what I use for my previous bot extension, it randomly generated every hour. but I got rid of that extension ever since facebook bots were patched about in the beginning of april. My extension never worked again.. But it was fun :D

**Comment by LegitSoulja** [comment]
See that.. What he said? "its pretty simple(well, not for me)"  LOL im done..

**Comment by Agarian** [comment]
we need to stop, remember this is the kind of sh*t that got issues disabled.

**Comment by NatsuTheGreat** [comment]
He acts like StormGS...

**Comment by NatsuTheGreat** [comment]
Yes, any way to get rid of all these comments?

**Comment by LegitSoulja** [comment]
I guess hard things are simple to him, but he doesn't know how to do a thing.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat I can delete them all if you want me too?

**Comment by Agarian** [comment]
lets just delete these comments, u should know our reaction to stormGS was a major factor that got issues disabled!

**Comment by NatsuTheGreat** [comment]
Yes please, I don't want andrews disbaling issues again xd

**Comment by Agarian** [comment]
lets start by closing this if its ok?

**Comment by NatsuTheGreat** [comment]
that would just fix it all :P

**Comment by Agarian** [comment]
cant delete messages i get "Something went wrong with that request. Please try again."

**Comment by NatsuTheGreat** [comment]
@LegitSoulja By the way, how is it going with the servers?

**Comment by Agarian** [comment]
i gtg so see ya later

**Comment by NatsuTheGreat** [comment]
Bye.

**Comment by LegitSoulja** [comment]
@Agarian I had wrote a quick script to remove all comments childs :nth. Thats why you was getting the error. But everything is removed to the time till that kid came in

**Comment by NatsuTheGreat** [comment]
:nth

**Comment by LegitSoulja** [comment]
And yea, this can stay closed since agar.io patched there dev thing itzlevvi said, So i guess this issue is pointless

**Comment by Agarian** [comment]
lol ok

**Comment by LegitSoulja** [comment]
@NatsuTheGreat :nth?

**Comment by LegitSoulja** [comment]
I stopped playing minecraft 2 years ago when microsoft took over lol

**Comment by Agarian** [comment]
just for the hell of it i added a label ;)

**Comment by LegitSoulja** [comment]
Thats cool

**Comment by Agarian** [comment]
also i got myself another 10 minutes

**Comment by LegitSoulja** [comment]
Well Forge is still a thing. I had stopped playing minecraft and I went to playing tekkit classic for a lil bit, then i just stop playing minecraft after that lol

**Comment by Agarian** [comment]
note if you look in the picture above, you may be able to see quite a bit of mods went into that house

**Comment by LegitSoulja** [comment]
I remember my old server a such. I made soo many plugins for my server. Also you know the one in the chamber mini game? I made that.

**Comment by Agarian** [comment]
wait u did??

**Comment by LegitSoulja** [comment]
Yea, me and artish. I had got banned from bukkit

**Comment by LegitSoulja** [comment]
So it wont say im part of the development of it. And besides, Every since I left the plugin was never updated

**Comment by Agarian** [comment]
i used to run over 200 mods and it took so long to load minecraft, i had merged some mods bringing the amount down to 127 today, but it still takes as long to load as before *was 6 hours wasted :(*

**Comment by NatsuTheGreat** [comment]
Just get rid of them? xD

**Comment by Agarian** [comment]
i did get rid of some i didnt need in the process :P

**Comment by LegitSoulja** [comment]
Yea, modded servers wasnt my thing unless it was technic.. It's too much to have people download the mods just to play on the server. I took full advantage of making plugins to make my server seem as if there was mods.

**Comment by Agarian** [comment]
it was a good time on that server lol

**Comment by LegitSoulja** [comment]
Anyone play ps3? I make mods for ps3. Heres my [channel](https://www.youtube.com/channel/UCkp-KyqtK-I0DqE7E5-cQyg). I currently dont upload anymore since I recently moved, and my life changed alot.

**Comment by Agarian** [comment]
i dont have a ps3 i have an XBOX-ONE

**Comment by LegitSoulja** [comment]
Lol im not getting a next gen. If I do it would be a ps4. But I doubt I will buy one. I have my fun times with ps3.

**Comment by Agarian** [comment]
ok, i gtg 4 real this time

**Comment by ItzLevvie** [comment]
ahh those memories when I used to have an Intel atom processor in 2012 which ran Minecraft 30fps for me.

**Comment by LegitSoulja** [comment]
I cant wait for quantum computing.. Lol

**Comment by LegitSoulja** [comment]
I wonder what languages would there be on quantum? And I wonder is microsoft will be in the lead again? I hope not.

**Comment by LegitSoulja** [comment]
Actually there is a language lol [here](https://en.wikipedia.org/wiki/Quantum_programming)

**Comment by LegitSoulja** [comment]
Looks like c++ a little bit

**Comment by NatsuTheGreat** [comment]
Soulja you still there?

**Comment by LegitSoulja** [comment]
I guess, but I'm on my phone. I'm resting right now. But wassup?

**Comment by NatsuTheGreat** [comment]
I found an extension that I was able to connect  to my private server with. I was watching the console, I disconnected when it randomly connected me to an official server. It also has the connect("ws://") command.

**Comment by LegitSoulja** [comment]
Infinity works too I think. And that web socket command will always be
there unless they host the site using nodejs.

**Comment by NatsuTheGreat** [comment]
I tried infinity, doesn't work.

**Comment by NatsuTheGreat** [comment]
http://prntscr.com/b1kh4q

**Comment by LegitSoulja** [comment]
Oh.. Um that's weird. I don't know. I'll take a look at it later

**Comment by NatsuTheGreat** [comment]
Okay. That is that one thing that keeps disconnecting me.

**Comment by NatsuTheGreat** [comment]
connect() doesn't work on agar.io right now. Their update ruined it.

**Comment by NatsuTheGreat** [comment]
Goodnight, I am leaving now.

**Comment by Agarian** [comment]
Whst extension u had?

**Comment by firelightning13** [comment]
@Agarian Agario Infinity, was supposed to connect to private server without a problem

btw all this comment makes me lag wow

**Comment by ItzLevvie** [comment]
Hayyy look http://agar.io/v72/ @LegitSoulja

**Comment by firelightning13** [comment]
Wait, what? HOw?!

**Comment by lotfis** [comment]
worked for me!!! thanks

**Comment by NatsuTheGreat** [comment]
404 :@

**Comment by firelightning13** [comment]
Rip v72

**Comment by Agarian** [comment]
i didnt get to save the page code :(((

**Comment by lotfis** [comment]
it works with agario infinity :) :) 
remove /v72 (http://agar.io/?ip=127.0.0.1:25565)

**Comment by Agarian** [comment]
infinity not work
