### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#526]
.

**Comment by Parth1999** [comment]
Fk agar.io I will now only play ogarul agario has become a shit (nearly) they have changed something may be increased cell speed or split speed its different and i dont like it now anymore . i will host private server on c9 and play wid my friends untill we get comfortable with agar.io again. #nevergiveup :P

**Comment by Agarian** [comment]
Nvm i aint leaving

**Comment by Agarian** [comment]
This is too much to give up

**Comment by LegitSoulja** [comment]
@Agarian don't worry. Eventually everything will be back to normal.. Just know you wont have to worry about agar.io nomore.
