### ISSUE TITLE
How

### ISSUE THREAD

**Issue by XenoYT** [AJS-development/Ogar-unlimited#527]
Please devs i want like my own server with admin commands :/ plz

**Comment by LegitSoulja** [comment]
There are admin commands, and I've made an addon/plugin that you can remotely control your server from a console. 

You can do that buy typing the command below as a game command:
> plugin add OgarConsole 

Also there is op commands. You should check out.

**Comment by NarutoGamerPro** [comment]
Working private servers?

**Comment by NarutoGamerPro** [comment]
Still cant connect to my private server lol

**Comment by NarutoGamerPro** [comment]
OgarUL rip?

**Comment by NarutoGamerPro** [comment]
Rip OgarUnlimited?

**Comment by LegitSoulja** [comment]
nooooooo I doubt it.

**Comment by LegitSoulja** [comment]
Still a work in progress

**Comment by LegitSoulja** [comment]
It's taking me hours and hours just to bring something back we all enjoyed. I'm trying my best to bring everything back

**Comment by LegitSoulja** [comment]
But I doubt OgarUl will r.i.p. There's been too much time a work done to let something go so easily. Actually this is fun for me. Cracking Agar.io

**Comment by LegitSoulja** [comment]
@NarutoGamerPro

**Comment by NarutoGamerPro** [comment]
I support it @LegitSoulja

**Comment by Megabyte918** [comment]
@LegitSoulja I feel like a hacker just by reading all of these new issues xD
