### ISSUE TITLE
SO MUCH LAG + SERVERS(CONNECTING... PROBLEM)

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#529]
The lag is HUMONGOUS!! 50 Bots will almost crash the server for me, just saying that but 50 bots is like being in Sirius's live stream.

**Comment by elitajmx** [comment]
WHY THE HELL DID THEY PATCH SERVERS, THEY CAN DO ANYTHING BUT PATCHING BOTS, THOSE LIL FUX

**Comment by LPArigma** [comment]
@elitajmx the lag when spawning bots depends on you computers power and RAM, i can spawn up to 450 bots before the lag gets to me and i have 16 gb's of RAM and thats because it spawning multiple instances of a player on the same network connection and on the same pc so imagine if you open 50 tabs and run agar.io on each one and plug in 50 keyboards,mice, and monitors and had 50 people play. Now think for a moment..... would your pc lag?

**Comment by Agarian** [comment]
well i use c9 and it only has a horrible 1GB ram

**Comment by LegitSoulja** [comment]
@LPArigma Sending bot packets, are different than running open tabs of agario games.. Lag depends on your internet speed, ram, and cpu.. Without them your server wouldnt run with full potential

**Comment by LegitSoulja** [comment]
Chrome on the other hand uses up 50% of your ram. Try using another browser. I recommend firefox.

**Comment by elitajmx** [comment]
When are private servers coming?

**Comment by Megabyte918** [comment]
I can spawn up to 30 bots with 3gb of ram and it lags lol

**Comment by Andrews54757** [comment]
soon, I have the client already, but not gonna release for some time

**Comment by Megabyte918** [comment]
Sweet I cant w8 m8

**Comment by Andrews54757** [comment]
I cant release the client files but I released the client server already. its in the ogarul-client repo by ajs-dev

**Comment by Andrews54757** [comment]
The reason why I cant release the client files is because it is illegal. Instead, you have to download the client files and paste it into the client folder in the repo

**Comment by Megabyte918** [comment]
can you send it to me on discord or gitter?

**Comment by Andrews54757** [comment]
nope and it would do no use, it uses special packets

**Comment by Megabyte918** [comment]
shite...

**Comment by Andrews54757** [comment]
http://ogarul-client-andrews54757.c9users.io/ is my server

**Comment by Andrews54757** [comment]
im shutting it down becaz people are looking at my repo

**Comment by Andrews54757** [comment]
who is `bitch clan bots`. soo annoying

**Comment by firelightning13** [comment]
The annoying guy perhaps

**Comment by Megabyte918** [comment]
damnit i didnt get to try it out...

**Comment by Andrews54757** [comment]
Guide for client installation https://github.com/AJS-development/Ogar-unlimited/issues/537
