### ISSUE TITLE
problem with client clone

### ISSUE THREAD

**Issue by djbencrazy** [AJS-development/Ogar-unlimited#530]
best,
I got this error when I work with a client clone.
can someone help me.
thank you in advance
![ogar3](https://cloud.githubusercontent.com/assets/11022044/15094682/95ff880c-14ac-11e6-831c-52519b544028.png)

**Comment by LegitSoulja** [comment]
@djbencrazy I don't even think client clone works. It wasnt a thing we worried about. It looks like it crashed when you went to use the client. Maybe the client is a wrong client to be using anyways.

**Comment by djbencrazy** [comment]
oke goed zal uit zoeken tog bedankt sluit maar volledig

**Comment by LegitSoulja** [comment]
@djbencrazy Well you are coming to us about a client that doesnt work. I mean, there's nothing we can do about that.
