### ISSUE TITLE
(NEW temporary)Fix to private server connections

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#531]
https://www.mediafire.com/?oxlmza8lnuky7b4
download that^

**Comment by Jhair2015** [comment]
+Agarian update link please! :D

**Comment by Agarian** [comment]
update link? why

**Comment by Jhair2015** [comment]
@Agarian THX :)

**Comment by Jhair2015** [comment]
@Agarian Helpme Skin not working D:

**Comment by Agarian** [comment]
ik only custom ones work :(

**Comment by Parth1999** [comment]
wat to do after downloading :(

**Comment by Parth1999** [comment]
i got it its a chrome extension but it keeps disconnecting :(

**Comment by Megabyte918** [comment]
is there any way to use it for firefox or no

**Comment by LPArigma** [comment]
@Parth1999 idk if this will work for you but for me I do it on chrome in incognito mode and it doesn't disconnect me
