### ISSUE TITLE
[NEW] Fix for private servers

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#532]
I just got more one fix, just work for windows with chrome
- Install tampermonkey
- Go to agarplus.io
- Install the extension
- Enter on incognito mode (CTRL + SHIFT + N)
- Go to agar.io
- Press f12
- Go to console
- Do ``connect("ws://ipofserver:port");
- Press enter, play
If you don't spawn, open again and type the same thing again!

**Comment by Agarian** [comment]
i dont like agar plus :p

**Comment by problemsofworld** [comment]
cool
thx lukkez

**Comment by Lukkez** [comment]
I like agarplus, for me this was perfect

**Comment by Agarian** [comment]
I get disconnected from servers anyway

**Comment by Parth1999** [comment]
Works but only when i host ogar locally and connect using ip:port but how do i connect to server hosted on c9.io???

**Comment by firelightning13** [comment]
@Parth1999 `connect ("ws://yourproject-yourname.c9users.io")`

**Comment by Parth1999** [comment]
yes i do the same thing but nothing happens :(

**Comment by Parth1999** [comment]
it just shows connecting

**Comment by firelightning13** [comment]
They removed `connect`, again

**Comment by Lukkez** [comment]
I said, you can't select ANY region, if select will not works, @firelightning13 Agarplus still using the old main_out.js for me works perfectly and i can connect to any server

**Comment by Andrews54757** [comment]
Guide for server https://github.com/AJS-development/Ogar-unlimited/issues/537

**Comment by Agarian** [comment]
Closing this
