### ISSUE TITLE
24/7 online private server hope you enjoy :D all credits  to andrew 

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#533]
https://agar-server-1-party-privatebots.c9users.io/

**Comment by Andrews54757** [comment]
so you are the bitch clan bots guy

**Comment by problemsofworld** [comment]
yeah lol

**Comment by Andrews54757** [comment]
you literaly went into my c9 and copy and pasted everything

**Comment by problemsofworld** [comment]
lol am srry btw

**Comment by Andrews54757** [comment]
shameful

**Comment by problemsofworld** [comment]
I just wanted to have fun with some friends

**Comment by problemsofworld** [comment]
why ?

**Comment by Andrews54757** [comment]
@AJS-development/ogar-unlimited-devs  Isnt that shameful?

**Comment by Andrews54757** [comment]
Its okay, just dont do it to anyone else

**Comment by Andrews54757** [comment]
Other people will kill you for that

**Comment by problemsofworld** [comment]
ok 
 agar io sucks I sad I tit will be only hope I will make all workspaces privatte btw I will give my upgrade them so ur will have faster workspcae sryy I wont tell any1 belive me

**Comment by LegitSoulja** [comment]
@Andrews54757 what happened?

**Comment by LegitSoulja** [comment]
im on a plane right now lol, internet is crap

**Comment by Andrews54757** [comment]
no it is okay, I dont care, just dont do it to other devs. It pisses them off.

**Comment by Andrews54757** [comment]
You can make it public.

**Comment by LegitSoulja** [comment]
@Andrews54757 add my skype: mactown51. Let me know its you.

**Comment by problemsofworld** [comment]
ok  I wont belive or not I just wanted to have fun  you can have workspace with 2.5 ram now I added you hope it helps u

**Comment by Andrews54757** [comment]
no, I dont care. You can have it. I dont mind.

**Comment by Andrews54757** [comment]
I know it is just for fun. Who am I to ruin your fun?

**Comment by Andrews54757** [comment]
Il put that server up on the new online servers page

**Comment by problemsofworld** [comment]
that what I was saying most of friends quit agar because of update this will help alot

**Comment by LegitSoulja** [comment]
Is there a client that I can use to get my site back up until i finish the client im using? @Andrews54757 that would be helpful, plus my server are private. No one would be able to steal it. Plus I can customize it my way so it wont look illegal.

**Comment by problemsofworld** [comment]
is it possible for an array for servers ? like if you press party it will randomy pic a server

**Comment by LegitSoulja** [comment]
@problemsofworld no... It will connect to the same server.. Duhhh

**Comment by Andrews54757** [comment]
@problemsofworld  It is possible, I can do it if I tried

**Comment by Andrews54757** [comment]
@LegitSoulja  Remember, I can basically do anything I put my mind to

**Comment by problemsofworld** [comment]
btw minions dont work for me it gives error undefind

**Comment by LegitSoulja** [comment]
@problemsofworld Yea, But I was saying for him. He would have to do that on his own if he wanted a random server when going to party mode.

**Comment by Andrews54757** [comment]
@problemsofworld It works fine

**Comment by problemsofworld** [comment]
[ERROR] Oh my, there seems to be an error with the command minion 1 4 raga
[ERROR] Please alert AJS dev with this message:
TypeError: Cannot read property '34' of undefined it gives me this

**Comment by LegitSoulja** [comment]
what is raga?

**Comment by problemsofworld** [comment]
name of bots

**Comment by LegitSoulja** [comment]
Oh, I didnt even know you could set names..

**Comment by Andrews54757** [comment]
yea, and with the superminion plugin I just made, you can even set their speed and spawnmass

**Comment by Andrews54757** [comment]
@problemsofworld delete the superminions plugin. I had that on and it was the early version of that and it didnt work well

**Comment by Andrews54757** [comment]
I would also delete all the other plugins

**Comment by problemsofworld** [comment]
it worked ur da best andrew

**Comment by LegitSoulja** [comment]
thats good.. @Andrews54757 ill be back wednesday, or thursday. Or whenever I get back home

**Comment by Megabyte918** [comment]
patched

**Comment by Agarian** [comment]
what?
