### ISSUE TITLE
Server Showcase

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#534]
Server showcase. Clients are no longer banned as moneyclip is being stupid

**Comment by Andrews54757** [comment]
https://agar-server-1-party-privatebots.c9users.io/ (problems of the world's server)

**Comment by LegitSoulja** [comment]
http://client.ogar.ml ( Miniclip Dev server | Domain owner: Me.)

**Comment by problemsofworld** [comment]
andrew I reall want to skins how to do that I cant upload :/

**Comment by Lukkez** [comment]
@problemsofworld You need to make a php file to upload, (php is much better than html) and make it works and do chmod 777 ``folder``

**Comment by problemsofworld** [comment]
oh I got thx btw

**Comment by Lukkez** [comment]
I'll make one, someone know how to host 24/7 on c9 or atleast when offline?

**Comment by problemsofworld** [comment]
@lukkez yes I can added to my team on c9.io so you can have 10 hot workspace than can be on 24/7 with 2.5 ram

**Comment by Lukkez** [comment]
Yea, ok, what's your profile, i will ask as "playogar", that's my older profile

**Comment by Andrews54757** [comment]
His profile is `bitch team bots`

**Comment by Lukkez** [comment]
Ok

**Comment by Lukkez** [comment]
Send me link

**Comment by problemsofworld** [comment]
iit bitch clan bots I will help any to host their server

**Comment by problemsofworld** [comment]
https://c9.io/privatebots

**Comment by Lukkez** [comment]
What workspace? agar-project?

**Comment by problemsofworld** [comment]
no it's private you want host 24/7 or files ? what is ur user name of c9.io

**Comment by Lukkez** [comment]
playogar

**Comment by Lukkez** [comment]
https://c9.io/playogar

**Comment by Lukkez** [comment]
Sorry for all that "snake" workspace and bots workspaces, it was before a shared acc =p

**Comment by problemsofworld** [comment]
@lukkez I added enjoy ur 24/7 hosting you can have 10 workspace now with 2.5 ram :D

**Comment by Lukkez** [comment]
Thanks :)

**Comment by Lukkez** [comment]
edit: I wasn't added lol, i don't recieve the confirmation e-mail

**Comment by fayizan** [comment]
@Bot9 can I have it..? :(

**Comment by djbencrazy** [comment]
it is now a client illegally or not

**Comment by Andrews54757** [comment]
a client is illegal but we dont care anymore as moneyclip ruined the game

**Comment by djbencrazy** [comment]
haha okay they ruin every game they believe me they are one to one to update. people will eventually no games count games that are on that website

**Comment by problemsofworld** [comment]
@Andrews54757  can we just use var server prompt; then alert server so any one can put his server to join and it really needs skins

**Comment by Andrews54757** [comment]
?

**Comment by problemsofworld** [comment]
lol I will test if it worked I will tell

**Comment by Andrews54757** [comment]
BTW, I am posting the client files. Follow the directions in the readme

[Agarioclient.tar.gz](https://github.com/AJS-development/Ogar-unlimited/files/255052/Agarioclient.tar.gz)


Note: this will be deleted in about an hour

**Comment by Andrews54757** [comment]
@problemsofworld  You should update your files

**Comment by problemsofworld** [comment]
ok does skins works

**Comment by Andrews54757** [comment]
I also put the custom clients packets up as well so you can update using the update command

**Comment by Andrews54757** [comment]
and skins are broken

**Comment by lulzyyy** [comment]
c0nsume.me

**Comment by problemsofworld** [comment]
I tought that any1 can connect to his server with like this but didn't worked var server = window.prompt(put ur server and port );


function connectToServer() {
	connect("wws://+server");

} 

will just say Connecting to ws://+server :/ on console after I put my server I tought going to work like agar/ip=  :/

**Comment by Megabyte918** [comment]
@Andrews54757 how do I start this

**Comment by Lukkez** [comment]
@problemsofworld Did you give acess? before you said you was going to give the 24/7 host

**Comment by Megabyte918** [comment]
@Andrews54757 I did everything I was supposed to with the OgarUL client and I put the client files where their supposed to go and I ran sudo node index.js but when I tried to connect all that came up was a white screen

**Comment by Lukkez** [comment]
Megabyte, maybe your node version and modules....

**Comment by Megabyte918** [comment]
I did npm install in c9 is it not the right version?

**Comment by Lukkez** [comment]
You need todo npm install on the "client" folder when u get the files

**Comment by Lukkez** [comment]
Omfg, thx @problemsofworld  If i get some money i'll give to you to help!

**Comment by Megabyte918** [comment]
![capture](https://cloud.githubusercontent.com/assets/17245196/15121731/e53e22b4-15e9-11e6-9d50-11a90f955921.PNG)
this is how I have it set up

**Comment by Lukkez** [comment]
You need the ogar-ul server too, do you have?

**Comment by Lukkez** [comment]
I think we need to chat on gitter, we're isn't a good location for that.

**Comment by Megabyte918** [comment]
@Lukkez alright

**Comment by problemsofworld** [comment]
you guys dont know its easy to host but I wont tell andrew should tell you him self

**Comment by problemsofworld** [comment]
@Megabyte918  what the link to ur client

**Comment by Megabyte918** [comment]
just use @LegitSoulja 's agario dump

**Comment by Megabyte918** [comment]
nvm, I think it might be patched now or something IDK

**Comment by problemsofworld** [comment]
lol  but mind works check out https://agar-server-1-party-privatebots.c9users.io/

**Comment by ItzLevvie** [comment]
I just saw this on reddit:

Thank you for contacting Miniclip Support.

The new update focus on removing usage of unauthorized extensions and hacks. It is also focused on improving performance. Yet, your concerns have been raised to our development team.

Best regards,

Nuno ,
Miniclip Support

**Comment by problemsofworld** [comment]
@ItzLevvie  that not helpful they wont reverse update

**Comment by Lukkez** [comment]
[LKZ Agar 24/7](http://lkz-agar-1-playogar.c9users.io/)
This server should be 24/7 because when i made the workspace i made with problemsofworld team.
**Specs**

- 1GB Ram (If need more i put)
- 1CPU Core
- 2GB SSD, Can be upgraded upto 10GB SSD
- 1 FFA Server (Team Allowed), More will be added with the time...
- 3 Skins! (More skins will be added every week)

**Comment by problemsofworld** [comment]
@ lukkez what the hack is that how is that possible see the pic http://prnt.sc/b23qgd

**Comment by Lukkez** [comment]
Do name command, you can have infinite height with name command :)

**Comment by Lukkez** [comment]
Tu hablas español? :smile: I'm brazillian but i can, "Google Traductor" =p

**Comment by problemsofworld** [comment]
I can get ur client ? I gived team

**Comment by Lukkez** [comment]
It's ItzLevvie Cigar

**Comment by Lukkez** [comment]
https://github.com/ItzLevvie/Cigar

**Comment by problemsofworld** [comment]
so only cilent is cigar or fully cigar  I mean you dont use ogar unlitimed ?

**Comment by Lukkez** [comment]
Idk how to implement Ogarul on cigar :/

**Comment by Andrews54757** [comment]
Guide to launching server https://github.com/AJS-development/Ogar-unlimited/issues/537

**Comment by Andrews54757** [comment]
Rage Thread: https://github.com/AJS-development/Ogar-unlimited/issues/539#issuecomment-218029121

**Comment by XxRaizerxX** [comment]
i have
 to give port for the servers

**Comment by Megabyte918** [comment]
same what da hell

**Comment by firelightning13** [comment]
https://myclient-firelightning13.c9users.io/
Have fun kids >:)

**Comment by ErikParacelsus** [comment]
# [Server](http://cl.agariohub.tk/?ip=miniclip-mistakes-erikparacelsus.c9users.io:8081/)
## Info: NOT 24/7

**Comment by Lukkez** [comment]
![image](https://cloud.githubusercontent.com/assets/15003706/15166412/d861e04c-16f4-11e6-86a0-e3102ad1168f.png)
**Client progress :smile: **

**Comment by Megabyte918** [comment]
ima play on everyones server :P

**Comment by Agarian** [comment]
u have custom client? can i have? lol

**Comment by Megabyte918** [comment]
@Agarian hai

**Comment by Agarian** [comment]
wassup

**Comment by Megabyte918** [comment]
@Agarian you wanna team on Lukkez's server?

**Comment by NatsuTheGreat** [comment]
Me too :P

**Comment by Megabyte918** [comment]
ayyye :D

**Comment by Agarian** [comment]
join mine m8s

**Comment by Megabyte918** [comment]
what is it

**Comment by Agarian** [comment]
ogarserverbeta-agarian.c9users.io:8080

**Comment by Megabyte918** [comment]
be there in a sec

**Comment by Agarian** [comment]
http://ajs-development.github.io/client/

**Comment by Agarian** [comment]
what is the link to the premium skin images? i have default skins down

**Comment by Megabyte918** [comment]
it says theres no application that seems to be running here and I have no idea :P

**Comment by Agarian** [comment]
nooo use http://ajs-development.github.io/client/ to connect to it!

**Comment by Agarian** [comment]
either way, its down i gtg

**Comment by Megabyte918** [comment]
damn okay ill cya tomorrow

**Comment by Agarian** [comment]
idfk why its soo impossible to run html files through c9.io

**Comment by Megabyte918** [comment]
@Lukkez what version does ur server run on?

**Comment by firelightning13** [comment]
@Lukkez cool layout bro

**Comment by XxRaizerxX** [comment]
@Andrews54757 whats the ip and port i have to enter one or it wont let me

**Comment by Andrews54757** [comment]
what  ip is your server running? What port?

**Comment by XxRaizerxX** [comment]
your server

**Comment by Lukkez** [comment]
I DONT use OgarUL, BECAUSE it would be soo hard to implement on Cigar, just normal Ogar

**Comment by XxRaizerxX** [comment]
@Lukkez  can you start your server

**Comment by Lukkez** [comment]
Oh it crashed?

**Comment by Lukkez** [comment]
Opened.

**Comment by XxRaizerxX** [comment]
im in

**Comment by Megabyte918** [comment]
@Lukkez which version of Ogar then?

**Comment by XxRaizerxX** [comment]
It says i need to enter adress:port

**Comment by XxRaizerxX** [comment]
HELP ME

**Comment by firelightning13** [comment]
what port?

**Comment by XxRaizerxX** [comment]
it said for andrews server enter adress:port

**Comment by firelightning13** [comment]
`yourip:yourport`

**Comment by XxRaizerxX** [comment]
why my ip and how do i have a port

**Comment by firelightning13** [comment]
do u run in vps,c9.io or in ur pc?

**Comment by XxRaizerxX** [comment]
idk

**Comment by firelightning13** [comment]
The andrews server its NOT A SERVER, its a client

**Comment by XxRaizerxX** [comment]
ik

**Comment by XxRaizerxX** [comment]
whats a client

**Comment by firelightning13** [comment]
im done with this guy

**Comment by XxRaizerxX** [comment]
im just a kid

**Comment by XxRaizerxX** [comment]
im 12

**Comment by XxRaizerxX** [comment]
whats my ip

**Comment by Megabyte918** [comment]
try the link then the port 8080 or 8081
so like https://agar-server-1-party-privatebots.c9users.io:8080 or 8081 idk

**Comment by XxRaizerxX** [comment]
k thnx

**Comment by XxRaizerxX** [comment]
does not work still :P

**Comment by firelightning13** [comment]
do u have c9.io?

**Comment by XxRaizerxX** [comment]
yah it does not work or load

**Comment by firelightning13** [comment]
why

**Comment by XxRaizerxX** [comment]
firelightning your server works and it stopped

**Comment by XxRaizerxX** [comment]
your server stopped
paused

**Comment by firelightning13** [comment]
i restarted it

**Comment by XxRaizerxX** [comment]
oh

**Comment by XxRaizerxX** [comment]
damn

**Comment by firelightning13** [comment]
GG

**Comment by Lukkez** [comment]
@Megabyte918 Sry for long time reply, I just use the newest vers of normal OGAR, i wasn't with time to put ogar-ul, more hard, that's why :/

**Comment by LegitSoulja** [comment]
@Lukkez what?

**Comment by Andrews54757** [comment]
Listen to @LegitSoulja or he might ban you.

**Comment by Andrews54757** [comment]
or i might ban you

**Comment by Lukkez** [comment]
@LegitSoulja I just use Ogar instead of OgarUl

**Comment by Lukkez** [comment]
Server 2 **(lkz-ogarul-playogar.c9users.io) Ip, you need to go to OgarUL client and paste this, specs

- 2.5GB Ram
- 2GB SSD Disk
- 24/7
- 0 Lag

**Comment by Megabyte918** [comment]
@Lukkez how are you hosting it with those specs on c9? premium account?

**Comment by Agarian** [comment]
he joined a team, he wont tell which to join xD

**Comment by Lukkez** [comment]
Yea xD problemsoft team, premium team

**Comment by problemsofworld** [comment]
lukkez I need ur skype

**Comment by Agarian** [comment]
so in PlayerTracker.js, you could see the following code:

> var mult = 2.5; // To simplify multiplier, in case this needs editing later on
      this.viewBox.topY = this.centerPos.y - this.gameServer.config.serverViewBaseY * mult;
      this.viewBox.bottomY = this.centerPos.y + this.gameServer.config.serverViewBaseY * mult;
      this.viewBox.leftX = this.centerPos.x - this.gameServer.config.serverViewBaseX * mult;
      this.viewBox.rightX = this.centerPos.x + this.gameServer.config.serverViewBaseX * mult;
      this.viewBox.width = this.gameServer.config.serverViewBaseX * mult;
      this.viewBox.height = this.gameServer.config.serverViewBaseY * mult;

This code increases the viewbase range in spectate mode, multiplying the viewbase by *2.5*, however, this only affects freeroam spectate, not when spectating a player. The default viewbases X and Y make spectating a player look buggy, as you cannot see all the entities past the viewbase. so you see them appear and dissapear ON SCREEN, unlike in regular agar, the viewbase in all spectate modes spans thw whole screen. So i had the idea for a viewbase multiplier that affects any spectate mode.

Also @AJS-development/ogar-unlimited-devs the spectate bug in the client is caused by the following code in **PlayerTracker.js** (lines 403-423) :

> // Map obfuscation
    var width = this.viewBox.width;
    var height = this.viewBox.height;

  > if (this.cells.length == 0 && this.gameServer.config.serverScrambleMinimaps >= 1) {
      // Update map, it may have changed
      this.socket.sendPacket(new Packet.SetBorder(
        this.gameServer.config.borderLeft + this.scrambleX,
        this.gameServer.config.borderRight + this.scrambleX,
        this.gameServer.config.borderTop + this.scrambleY,
        this.gameServer.config.borderBottom + this.scrambleY
      ));
    } else {
      // Send a border packet to fake the map size
      this.socket.sendPacket(new Packet.SetBorder(
       Math.max(this.centerPos.x + this.scrambleX - width, this.gameServer.config.borderLeft + this.scrambleX),
            Math.min(this.centerPos.x + this.scrambleX + width, this.gameServer.config.borderRight + this.scrambleX),
            Math.max(this.centerPos.y + this.scrambleY - height, this.gameServer.config.borderTop + this.scrambleY),
            Math.min(this.centerPos.y + this.scrambleY + height, this.gameServer.config.borderBottom + this.scrambleY)
      ));
    }

**Comment by LegitSoulja** [comment]
:/

**Comment by firelightning13** [comment]
wow

**Comment by Agarian** [comment]
yeap, found that out  while ago lol

**Comment by Agarian** [comment]
BUG: if "ejectbiggest" is set to 1, it gives the following error
> ReferenceError: ejectedCells is not defined
    at GameServer.ejectBiggest (/home/ubuntu/workspace/src/core/GameServer.js:1273:9)
    at GameServer.ejectMass (/home/ubuntu/workspace/src/core/GameServer.js:1287:14)
    at Mode.pressW (/home/ubuntu/workspace/src/gamemodes/Mode.js:61:18)
    at PlayerTracker.<anonymous> (/home/ubuntu/workspace/src/core/PlayerTracker.js:301:73)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by Lukkez** [comment]
@problemsofworld Mine too wtf

**Comment by Agarian** [comment]
Probably because you're using an agar client, which is probably illegal. May be why your accounts are blocked.

**Comment by Andrews54757** [comment]
I fixed your bug @Agarian (i think)

**Comment by XxRaizerxX** [comment]
[Ogarulserv Splitrun practice](http://ogarulserv1-raizer.c9users.io/)
Status: Online
Version: Ogar Unlimited
Bots: 0-50
Teaming: Allowed
Gamemode: FFA

**Comment by Agarian** [comment]
I've been noticing, when the server lags, it almost seems as if it starts to calculate ticks incorrectly. like when i'm ejecting mass in a certain spot, after a while, ejecting mass becomes rough and can sometimes freeze for a split second (splitting does the same when lag occurs)

**Comment by firelightning13** [comment]
It was sometimes. happens to me too (not c9.io)

**Comment by Megabyte918** [comment]
Anyone want to team on vanilla with me? no private servers are up atm (ill remove this later)

**Comment by ErikParacelsus** [comment]
@LegitSoulja in agariohub.net how do you make moon dust game mode possible?

**Comment by LegitSoulja** [comment]
@ErikParacelsus it's not a gamemode, and its not possible for you to get unless you make it. I have it but I cannot share it since its the owner's and its his custom structures

**Comment by Andrews54757** [comment]
@LegitSoulja Its easy, its basically unlimite ffa but with the splitting fixed like it was a long time ago

**Comment by Andrews54757** [comment]
@ErikParacelsus I will fix unlimited ffa just so you can play on something like that (prev it was broken as I didnt really care)

**Comment by LegitSoulja** [comment]
@Andrews54757 okay, yea i wasnt for sure. I just know most servers he added are custom scripted

**Comment by ErikParacelsus** [comment]
@Andrews54757 Thankkkkk youuuu

**Comment by Andrews54757** [comment]
@ErikParacelsus I did it but I am not sure if there are 100% no bugs. So I added that into opt-in. If you are already included in the opt-in program, use the update command

**Comment by Andrews54757** [comment]
Deleted all inactive servers and c9 servers

**Comment by LegitSoulja** [comment]
@Andrews54757 where's opt in stored? Am i in?

**Comment by Andrews54757** [comment]
see #621

**Comment by BLUclanTDS** [comment]
I have a custom private server client to showcase lol. Play with it here: http://wayclient.comxa.com/
Default ip is my server. Up mostly.

**Comment by Agarian** [comment]
SUGGESTION FOR GAMEMODE: Mothership
If you know diep.io, you know the mothership gamemode. 
Mothership is a new game mode similar to Team DeathMatch and Domination. The biggest difference is that in each team, one player takes control of a large tank called the Mothership. The Motherships can move freely, using its Guardians to attack the enemy. There is a RED and BLUE team. What could happen is when you W into a mothercell, you damage it. After a while of a mothercell getting damaged, it dies and the team that killed it wins! The mothercell color would correspond to the team its in. Food pellets can be used as the "guardians" that damage players. When a food pellet from the mothership touched a player, they could lose mass to symbolize damage. Same could go for the mothership.

**Comment by LegitSoulja** [comment]
@Agarian I will try making it. My first game mode every. Wish my luck.

**Comment by Agarian** [comment]
@LegitSoulja Do you know what the mothership gamemode is in terms of diep.io? If so, cool.

**Comment by LegitSoulja** [comment]
@Agarian No, I will go based off your description, and I will also play to get a visual example.

**Comment by LegitSoulja** [comment]
@Agarian basically it's like protecting the mother cell correct, with each other protection it. Food is used for defense & barriers which barriers could be a virus. 

I thought about the idea a while ago. It kindof reminds me of a game I used to play a long time ago.

**Comment by Agarian** [comment]
@LegitSoulja pretty much. theres 1 set of drones that attack the opposite team and another set you control.
