### ISSUE TITLE
Server Issues.... Coordinates all messed up.

### ISSUE THREAD

**Issue by CubeTiger** [AJS-development/Ogar-unlimited#536]
Please read the FAQ in advance.

What game mode were you in when you had the issue?

What version are you on?

What command did you type if any?

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

Can you make minions split by pressing E or R key?
A: NO, as agar.io client doesn't support those keys. Otherwise, you would need to use another client, and that is illegal.

**Comment by CubeTiger** [comment]
Basically I was able to connect (and still can) to the server using the TEMPORARY method, however it now looks like this:
![screen shot 2016-05-09 at 11 44 25 am](https://cloud.githubusercontent.com/assets/19269633/15118878/17b32266-15dc-11e6-8188-790e957fad47.png)

**Comment by Agarian** [comment]
wtf

**Comment by problemsofworld** [comment]
AJS-development dont care about bots :P

**Comment by Andrews54757** [comment]
https://github.com/AJS-development/Ogar-unlimited/issues/537

**Comment by Andrews54757** [comment]
Rage Thread: https://github.com/AJS-development/Ogar-unlimited/issues/539#issuecomment-218029121

**Comment by Agarian** [comment]
omg miniclip just patched it! :angry:
