### ISSUE TITLE
OgarUL Client Website Temporary*

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#538]
Don't want to host clients? You are free to use my hosted client below. Connect like you would when you connected to agar.io clients.
> http://cl.agariohub.tk/?ip=localhost:443

People who say c9 doesnt work, visit http://cl.agariohub.tk there is a c9 server running. Just connect the same as you would like above. If you are using c9, use your workspace domain/workspace upon connecting instead of localhost.

If you get a blank screen heres some reasons.

- You are running https, instead of http.(**Which I re-routed https connections**)
- You have an extension that is messing up the client.
- Your server is taking a long time to respond back to websocket.
- Your location/country doesn't support my site.
- Your using a proxy, vpn, or some sort(**idk, but it could happen**).
- Your browser doesn't support it. (Yup, Some browsers suck **including chrome**).

If you want the client, feel free to ask me, or andrew, or anyone who has the client. Please note if you want an original non moddified client get it from the devs for safety measures. 

> **Please make sure you download the latest OgarUL to be able to connect without any problems.**

**Remember, this is for my site use only. This is not attended for future public use.**

_Do not use HTTrack, or any site copier on my site. They have been disabled on my site, so they shouldn't work at all. I don't like bots, nor anything that copies my work. Meaning, a site copier could download my whole site, (Not just the client). **Patched**_

**Comment by problemsofworld** [comment]
skins works ?

**Comment by LegitSoulja** [comment]
@problemsofworld Skins areremoved on the server itself.

**Comment by LegitSoulja** [comment]
You can see when you add a skin, the favicon changes to the skin lol

**Comment by LegitSoulja** [comment]
@Andrews54757 why was skins removed again? lol

**Comment by problemsofworld** [comment]
:( plz fix alot of players love skins is that because of moneyclip

**Comment by LegitSoulja** [comment]
Oh yea, i forgot. Because of miniclip. I keep forgetting about miniclip. Thats how bad I hate them

**Comment by problemsofworld** [comment]
I find some good skins that moneyshit dont use

**Comment by LegitSoulja** [comment]
I could also make some skins. Custom skins.

**Comment by Agarian** [comment]
@LegitSoulja it doesnt connect to servers:

Connecting to ws://***IP***
main_out.js?542:290 socket open
main_out.js?542:303 socket close

**Comment by li-gary** [comment]
Um, All I've got when going on the site was a blank page. Was I doing anything wrong?

**Comment by LegitSoulja** [comment]
@li-gary sub domain issues, which should be resolved by now.

**Comment by LegitSoulja** [comment]
@Agarian try again.

**Comment by LegitSoulja** [comment]
use **cl.agariohub.tk/?ip=** or **agariohub.tk/cl/?ip=**

**Comment by LegitSoulja** [comment]
@Agarian you are using ws. Don't use ws method. Just connect the same way you did with agar.io

**Comment by problemsofworld** [comment]
I Had worked on bot project we done it but after 2 days agar update came , and I couldn't fix it but my friend says he can fix it now is that's possible ?

**Comment by Tokoagar** [comment]
How does it work?

**Comment by LegitSoulja** [comment]
@problemsofworld yes

**Comment by LegitSoulja** [comment]
@Tokoagar Download OgarUL latest updated, and get the game installed and running. Then you use the domain cl.agariohub.tk/?ip=127.0.0.1:443 same way like you connected with agar.io

**Comment by Andrews54757** [comment]
@LegitSoulja We need to figure out a permenant site.

**Comment by LegitSoulja** [comment]
@Andrews54757 I will leave that too you unless you want my help with the site. But this is mainly for my site, but im allowing other people to use it.

**Comment by Andrews54757** [comment]
Rage Thread: https://github.com/AJS-development/Ogar-unlimited/issues/539#issuecomment-218029121

**Comment by Agarian** [comment]
f*ck yeah xD

**Comment by problemsofworld** [comment]
I will buy this domain ogar-unlimited.io all credits to AJS-development :P

**Comment by Andrews54757** [comment]
no, buy ogarul.io instead. lol

**Comment by Andrews54757** [comment]
Its easier to type

**Comment by problemsofworld** [comment]
ok

**Comment by LegitSoulja** [comment]
Ooops.. I fixed the client to work with c9.io. You can connect with your c9.io workspace connection.

**Comment by LegitSoulja** [comment]
@problemsofworld let me know when you buy the domain. I can give andrew a place for the website, part of my dedicated hosting. And so we can get security on the domain aswell.

**Comment by LegitSoulja** [comment]
@problemsofworld and make sure you set it up right, because if you dont, miniclip could probably find a way to get your info, and the domain registrar and get the domain shut down. I can register the domain, and get a private registration for free. Just let me know when you do it. DO NOT REGISTER WITH TRUE INFORMATION BECAUSE YOUR NAME AND ADDRESS WILL BE RESOLVED WITH THE DOMAIN UPON REGISTERING!..

**Comment by problemsofworld** [comment]
@LegitSoulja  there no  laws about internet in my counrty miniclip cant do any shit :P it joke for me I used a gift card I need ur help to setup accounts and coins and xp stuff maybe later

**Comment by Andrews54757** [comment]
I wont run it though. Rather not break any laws

**Comment by problemsofworld** [comment]
I just got new agar coondriates by the way I splited bot and eject mass on agario I will remove this msg in 2 mins LOL XD

**Comment by Agarian** [comment]
?

**Comment by problemsofworld** [comment]
agario bots are back willl start sell again soon  btw am ower of bestbots.co.uk (offline now) so I have controll over agario server :D

**Comment by LegitSoulja** [comment]
@Andrews54757 so your gonna set @problemsofworld up? lol thats bad

**Comment by LegitSoulja** [comment]
You might as well since the domain is towards ogarunlimited, and which, You are the owner.

**Comment by Andrews54757** [comment]
@LegitSoulja I dont really care if he makes a webste or not, and I cant maintain a website server for 24/7 even without the legal issues

**Comment by LegitSoulja** [comment]
@Andrews54757 you wouldn't even have to maintain it. Just set it up how you want it and let it run. It's just a website.

**Comment by Andrews54757** [comment]
Im already burdened by taking care of ogarul even with all the dev members, I cant take more. lol

**Comment by LegitSoulja** [comment]
@Andrews54757 Yea, I feel you. You need to rest for like a year or two lol

**Comment by NatsuTheGreat** [comment]
Lmao

**Comment by Andrews54757** [comment]
And realise that ogarUl is not even one year old

**Comment by Andrews54757** [comment]
Soo much things happened in the short timeframe. Its like the development was on steriods

**Comment by LegitSoulja** [comment]
@Andrews54757 Thanks to miniclip, the stress was real.

**Comment by Andrews54757** [comment]
My goal was to pass all the other versions of ogar, In my opinion, I exceded them all and went past even more than that.

**Comment by Andrews54757** [comment]
also RIP ogarproject. They have died.

**Comment by problemsofworld** [comment]
can I be AJS member ?

**Comment by LegitSoulja** [comment]
@Andrews54757 Even if you did or didn't @AJS-development/ogar-unlimited-devs is still proud of you. You grew the OgarUL community. We give love to you. I love you.. No homo.

**Comment by Andrews54757** [comment]
mabye, there is I think two more slots left

**Comment by Andrews54757** [comment]
if you look at the graphs, the view went from about 3 a day to like 1300 views per day really fast (sometimes over 2000 for big updates). Its amazing how fast ogarul came up

**Comment by LegitSoulja** [comment]
Setup a way to donate. I'll donate to you

**Comment by problemsofworld** [comment]
me 2 I want to donate

**Comment by Andrews54757** [comment]
I would like to keep this project away from monetary gain. But thanks for the offer!

**Comment by Andrews54757** [comment]
(I really dont wanna become like moneyclip)

**Comment by LegitSoulja** [comment]
Awe

**Comment by LegitSoulja** [comment]
Your not though, it's for your work. Your not asking, but we are offering the givings

**Comment by LegitSoulja** [comment]
You know you want too

**Comment by Andrews54757** [comment]
actually i found out today alone, this project had over 3000 views

**Comment by Andrews54757** [comment]
and I dont want the money

**Comment by LegitSoulja** [comment]
You just don't understand how important OgarUL is to us right now. But if you insist

**Comment by LegitSoulja** [comment]
Just know, agar.io will never be like OgarUL

**Comment by LegitSoulja** [comment]
It's over 9000. Way better than any other Ogar servers out here

**Comment by Andrews54757** [comment]
Most of it is from youtube videos like https://www.youtube.com/watch?v=NWnMEKgQsuM and other videos

**Comment by LegitSoulja** [comment]
Look at the fame. You could have a site just like my friend over at AgarioHub.net. A lot of famous youtubers go there

**Comment by LegitSoulja** [comment]
He uses some of your servers too. But most of them are original moddified Ogar servers he made on his own.

**Comment by LegitSoulja** [comment]
He's even using his own client he made.

**Comment by LegitSoulja** [comment]
That was before miniclip did what they did. That was his backup. He knew that something like that was going to happen in the future. I'm telling you, he's fully prepared.

**Comment by LegitSoulja** [comment]
@Parth999 use this until then

**Comment by LegitSoulja** [comment]
@firelightning13 same goes for you.

**Comment by Parth1999** [comment]
@LegitSoulja The problem is that i can connect any server which is hosted locally but i want to connect using c9.io . I m using this ip and it just displays nothng .( I have updated ogarUL ) 
http://cl.agariohub.tk/?ip=rexprivateserver-flame123.c9users.io but it doesnt connect :( :( and yes i m complete noob at programming :P so dont mind i can just request for help

**Comment by Agarian** [comment]
how to work on C9??

**Comment by LegitSoulja** [comment]
It works with c9....

**Comment by LegitSoulja** [comment]
I fixed that yesterday, and it's fine for me

**Comment by LegitSoulja** [comment]
@Agarian Like this for an example

> http://cl.agariohub.tk/?ip=ogarul-legitsoulja.c9users.io

**Comment by LegitSoulja** [comment]
@Parth1999 No application is running on _rexprivateserver-flame123.c9users.io_

**Comment by lotfis** [comment]
ogar unlimited works for me with agario infinity
![sans titre](https://cloud.githubusercontent.com/assets/18702189/15153897/f2f8ffe8-16d2-11e6-987e-5601727b6ced.png)

**Comment by LegitSoulja** [comment]
@lotfis Some people don't want an extension. And some people dont want to deal with miniclip mess. They'll eventually patch that.

**Comment by Andrews54757** [comment]
Official one #551

**Comment by LegitSoulja** [comment]
@Andrews54757 Ok, i guess i'll disable my client then for public use.

**Comment by anaelpop** [comment]
@LegitSoulja can you chat me

**Comment by Agarian** [comment]
@Megabyte918 private servers connect again :D

**Comment by NatsuTheGreat** [comment]
they do??????? Without clients??

**Comment by LegitSoulja** [comment]
I added the client back since some people still wants to use it. I'll just keep it open for everyone to use, and I'll just have another client just for my website/servers

**Comment by NatsuTheGreat** [comment]
Wait, but do OGAR-UL servers work without clients?

**Comment by LegitSoulja** [comment]
No you have to have a client to play...

**Comment by NatsuTheGreat** [comment]
> @Megabyte918 OGAR-UL private servers connect again :D 

So that aint true?

**Comment by Agarian** [comment]
NO IN http://ajs-development.github.io/client/

**Comment by NatsuTheGreat** [comment]
Oh kk.

**Comment by Agarian** [comment]
xD

**Comment by LegitSoulja** [comment]
Andrew added his client to a GitHub site.

**Comment by LegitSoulja** [comment]
And who are deleting posts?? It's so annoying.. I'm just gonna stop talking

**Comment by Agarian** [comment]
idk

**Comment by Agarian** [comment]
wtf

**Comment by Agarian** [comment]
@LegitSoulja go to the client and connect to `ogarserverbeta-agarian.c9users.io:8080` if u can

**Comment by LegitSoulja** [comment]
I'm not even on my computer dude. And I don't appreciate you deleting my posts

**Comment by Agarian** [comment]
not just ur posts lol, i dont like spamming issues that dont need to b spammed

**Comment by LegitSoulja** [comment]
Dude my posts wasn't even spam. This is my issue anyways. I just posted like a paragraph about something and you deleted it. I'm just gonna stop talking since stuff gets randomly deleted all the times for no reason at all.

**Comment by LegitSoulja** [comment]
I'm just gonna stop talking period... Deleted whatever you want.

**Comment by LegitSoulja** [comment]
@Agarian how would you feel if I go around deleting your crap. You wouldn't like it neither. But it's all good. Peace.
