### ISSUE TITLE
They Patched My way to join with agarplus

### ISSUE THREAD

**Issue by Yamanourani** [AJS-development/Ogar-unlimited#540]
I had a way to join with agarplus :/ but then those moneywhores patched it,, fuck you miniclip

**Comment by LegitSoulja** [comment]
I'm sorry. But there's nothing we could do. :/

**Comment by LegitSoulja** [comment]
You may try OgarUL and OgarUL client in the replace of agarplus

**Comment by XxRaizerxX** [comment]
:P

**Comment by firelightning13** [comment]
You can rage at miniclip here #539

**Comment by Agarian** [comment]
or use http://ajs-development.github.io/client/
