### ISSUE TITLE
I need graphic pack&index original pack 

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#541]
Please read the FAQ in advance.

What game mode were you in when you had the issue?

What version are you on?

What command did you type if any?

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

Can you make minions split by pressing E or R key?
A: NO, as agar.io client doesn't support those keys. Otherwise, you would need to use another client, and that is illegal.

**Comment by Andrews54757** [comment]
no description
