### ISSUE TITLE
How to download OGAR UL 

### ISSUE THREAD

**Issue by XenoYT** [AJS-development/Ogar-unlimited#542]
Download link please ;-;

**Comment by problemsofworld** [comment]
you  can just use this to connect to ur server https://agar-server-1-party-privatebots.c9users.io/? 
temporary

**Comment by XenoYT** [comment]
k thanks

**Comment by Megabyte918** [comment]
@problemsofworld i need to input the server address and port what it is

**Comment by Agarian** [comment]
i still dont get y dis dont work on Firefox ffs
