### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XenoYT** [AJS-development/Ogar-unlimited#543]
When i run start.bat it gives me errors

**Comment by Andrews54757** [comment]
Please give me the error

**Comment by problemsofworld** [comment]
ssame here just tested

**Comment by lotfis** [comment]
ogar Unlimited works for me with agrio infinity http://agar.io/?ip=127.0.0.1:25565 
![sans titre](https://cloud.githubusercontent.com/assets/18702189/15147661/a715d222-16b9-11e6-8f4f-b80c1c7857ca.png)

**Comment by XenoYT** [comment]
![wee](https://cloud.githubusercontent.com/assets/18215228/15147670/1045af58-16c2-11e6-9dd1-7ee4c20cc154.JPG)

**Comment by XenoYT** [comment]
error

**Comment by XenoYT** [comment]
@Andrews54757 
![wee](https://cloud.githubusercontent.com/assets/18215228/15147709/46d77010-16c2-11e6-833e-2d959bd93d12.JPG)

**Comment by lotfis** [comment]
im using version 11.8.5

**Comment by XenoYT** [comment]
@lotfis upload to mediafire please

**Comment by problemsofworld** [comment]
how to make bots w back if some1 w

**Comment by lotfis** [comment]
http://uptobox.com/2ifdhl2tqp0e

**Comment by Andrews54757** [comment]
@XenoYT do `npm install request`
