### ISSUE TITLE
NEWS miniClip may reverse update

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#545]
`news`
check https://www.reddit.com/r/agario
Check changelog on agar.io
changelog:
https://www.reddit.com/r/agario 
`moneyclip`

**Comment by ErikParacelsus** [comment]
OMFG YESSSS OMGGGGG

**Comment by problemsofworld** [comment]
its was a joke

**Comment by ErikParacelsus** [comment]
ik

**Comment by firelightning13** [comment]
best joke ever 2k16
