### ISSUE TITLE
Locked Files on Mac

### ISSUE THREAD

**Issue by CubeTiger** [AJS-development/Ogar-unlimited#546]
Please read the FAQ in advance.

What game mode were you in when you had the issue?

What version are you on?

What command did you type if any?

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

Can you make minions split by pressing E or R key?
A: NO, as agar.io client doesn't support those keys. Otherwise, you would need to use another client, and that is illegal.

**Comment by Andrews54757** [comment]
No description

**Comment by CubeTiger** [comment]
Basically when I open index.html with textedit it says that the file is locked. Should I try opening it with Sublime text

**Comment by Andrews54757** [comment]
I dont know. Google your problem
