### ISSUE TITLE
INDEX.HTML IS LOCKED ON MY MAC

### ISSUE THREAD

**Issue by CubeTiger** [AJS-development/Ogar-unlimited#547]
WHEN I TRY TO OPEN IT THE FILE SAYS LOCKED AND I CAN'T EDIT THE FILE.

Sorry for caps I'm still in Rage Mode -_-

**Comment by LegitSoulja** [comment]
@CubeTiger chmod the file for read and write permissions.

**Comment by CubeTiger** [comment]
@LegitSoulja Doesn't work

**Comment by Andrews54757** [comment]
see #548 . GOOGLE IT!

**Comment by LegitSoulja** [comment]
@CubeTiger go here http://bfy.tw/5gnX

**Comment by CubeTiger** [comment]
@LegitSoulja Yah nothing is working. The file is locked. Fuck me.

**Comment by LegitSoulja** [comment]
@CubeTiger Where did you get the client from? You should get the client from dev members, and not random people to be more safe.

**Comment by CubeTiger** [comment]
@LegitSoulja I went the the link and it downloaded.
