### ISSUE TITLE
BANNING NOTICE!.

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#548]
I am tired of issues that people post without following the guideline. FOLLOW THE GUIDELINE!! make sure to include the description, error, and dont forget to google it first! THE NEXT PERSON WHO DOESN'T DO THIS THIS WILL BE BANNED FOR A MONTH FROM OGARUL, I AM SERIOUS.

**Comment by CubeTiger** [comment]
I followed the guidelines and the file is locked.... I don't know what to do. @LegitSoulja told me to chmod it but I already have read and write permissions. It's just locked and I can't edit it

**Comment by Andrews54757** [comment]
google it

**Comment by XenoYT** [comment]
I Still have errors
![shit](https://cloud.githubusercontent.com/assets/18215228/15154597/b165d7c0-16de-11e6-981e-8e56c8a96724.PNG)
i did all steps and nothing -.-

**Comment by ErikParacelsus** [comment]
@XenoYT `cd src`

**Comment by LegitSoulja** [comment]
@XenoYT and don't run as adminstrator/root.

**Comment by XenoYT** [comment]
@LegitSoulja what is cd src ?

**Comment by XenoYT** [comment]
No more ogar :/

**Comment by LegitSoulja** [comment]
CD to the **src** folder of OgarUL server. Then use the command **node
index**. Or run the start.bat or start.sh file

**Comment by XenoYT** [comment]
@LegitSoulja i give up dont reply to  a noob like me

**Comment by XenoYT** [comment]
@LegitSoulja Reinstalled OGAR and followed steps and keep getting errors wtf why that happening why old ogar was working and this not wow im done

**Comment by Agarian** [comment]
try c9 bro #280

**Comment by LegitSoulja** [comment]
If you don't know how to run nodejs and is a noob then don't run a server at all.

**Comment by Andrews54757** [comment]
@XenoYT  try using the pre-installed package here https://github.com/AJS-development/Pre-Installed-ogarUL

**Comment by elitajmx** [comment]
how do i delete client thing that i installed cuz of the steps? i found a way to make it work but with the client thing installed it wont workk

**Comment by elitajmx** [comment]
i get weird shapes of a ball and it wont move either.. i used the pre-installed package tho

**Comment by LegitSoulja** [comment]
Hm, what issues are you having with the client? There was a recent updated one did you ever obtain it?

**Comment by elitajmx** [comment]
nevermind, private server don't work, i get kicked out in 5 seconds

**Comment by LegitSoulja** [comment]
@elitajmx well if you want to delete the client you can by deleting the client folder and running this command

> plugin delete Client

**Comment by Agarian** [comment]
i noticed the "hide grid" option only affects the white theme

**Comment by Agarian** [comment]
for some annoying reason, on c9.io, the server is so laggy, i get full memory usage when ONLY i am connected on the server. ovet time it gets worse! TO THE POINT TO WHERE ITS UNPLAYABLE!

**Comment by LegitSoulja** [comment]
@Agarian Free services, alot of people use it. If you buy your workspace is on another service with better performance away from the other free servers.

**Comment by Agarian** [comment]
do people think i have money i can spend all day just laying around??

**Comment by LegitSoulja** [comment]
@Agarian and do you think thats our problem?

**Comment by LPArigma** [comment]
Personally i use Linode for cloud hosting lol @LegitSoulja @Agarian

**Comment by LegitSoulja** [comment]
@LPArigma talking about cloud hosting, I wonder can you turn a wdcloud into a server? Hmm

**Comment by elitajmx** [comment]
how do i get the server to work man..
