### ISSUE TITLE
How to make a 24/7 terminal on c9.io?

### ISSUE THREAD

**Issue by ErikParacelsus** [AJS-development/Ogar-unlimited#549]
Can you guys help me with the 24/7 thingy i want to make my Ogar server to be 24/7

**Comment by LegitSoulja** [comment]
@ErikParacelsus with c9.io you can't run 24/7. You can buy a package that you can run your server 24/7, But i dont know about c9.io though. I have my own vps at home that I use to run my servers 24/7. 

Find something online thats good that does nodejs hosting. You can try amazon web servers free tier for a year. You can host 24/7. But, I don't know about the specs.

**Comment by ErikParacelsus** [comment]
K thx

**Comment by Lukkez** [comment]
Enter on a team on c9.io, I AM on one and I HAVE a 24/7 workspace upto 2.5gb RAM

**Comment by Agarian** [comment]
what team tho?

**Comment by Agarian** [comment]
i'd love to be able to have 2+ gb ram

**Comment by Agarian** [comment]
i dont really care about the 24/7 feature that much :p

**Comment by Megabyte918** [comment]
@Lukkez I'm intrigued

**Comment by Agarian** [comment]
@Lukkez How do you have those specs?? And what team should i join??
