### ISSUE TITLE
Agar.io old graphic

### ISSUE THREAD

**Issue by LostCodesy** [AJS-development/Ogar-unlimited#550]
Hey AJS Team,

I'm need **Agar.io old graphic pack** for real graphic Agar.io private server.

index.html, main_out.js, agar.io.js and i18.js etc. files.

Please give me files.

Good works!

**Comment by Andrews54757** [comment]
we dont have them

**Comment by LostCodesy** [comment]
@Andrews54757 i too need me searching

**Comment by Agarian** [comment]
this should be added into ogarunlimited.io

**Comment by LegitSoulja** [comment]
@LostCodesy I could probably make some nice graphics for agario, and get skins back.

**Comment by Tokoagar** [comment]
@LegitSoulja 
Yup That's a good Idea

**Comment by Agarian** [comment]
@LegitSoulja like the idea lol

**Comment by djbencrazy** [comment]
I still have the old client agario . which is in cigar with me: fun features in zolijk stabbed by relative virus wall and off www.crazyogar.ga
