### ISSUE TITLE
Official Client site

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#551]
Official Client:
> http://play.ogarul.tk

Backup:
> http://ajs-development.github.io/client/

**Comment by problemsofworld** [comment]
thx I have 40 skins can you add to client agario dont use it can you make more like agar like party or ffa so ppl can play on our servers 24/7 online ones or at least a option to add my server to public client select to party or ffa if it's possbile :+1:

**Comment by LegitSoulja** [comment]
Dude lol. It doesn't work like that. You just want people to play on your servers by force.

**Comment by LegitSoulja** [comment]
The client is for someone's private servers. Not yours in particular

**Comment by problemsofworld** [comment]
:/

**Comment by Andrews54757** [comment]
@LegitSoulja See, Github pages are useful

**Comment by LegitSoulja** [comment]
Yea I guess you could say for that use.

**Comment by problemsofworld** [comment]
skins and public server will make it more fun

**Comment by Agarian** [comment]
you should add a "show map borders" or "show mass" option lol

**Comment by Andrews54757** [comment]
that would be good

**Comment by problemsofworld** [comment]
WHat the Hack my cell is catcus now

**Comment by Andrews54757** [comment]
I added the showmass option

**Comment by firelightning13** [comment]
Damn I can run this offline!!!
![offline](https://cloud.githubusercontent.com/assets/17120382/15157133/ccaf8cd6-171c-11e6-9bf8-eaba373f65a5.png)

**Comment by LegitSoulja** [comment]
@firelightning13 Of course.. You have the client..

**Comment by XxRaizerxX** [comment]
Does not work

**Comment by problemsofworld** [comment]
@XxRaizerxX it must work :P

**Comment by problemsofworld** [comment]
new way connect to server `agarplus` `legal` if you want to use agarplus `https://www.youtube.com/watch?v=a0Bmuuk7eUA`

**Comment by Andrews54757** [comment]
it is fixed, there was an unknown issue

**Comment by NoorAgario** [comment]
Hey Andrews
Do it act like 
From My Server ----> To Your Client (site) ----> Player (Me) ?!
cuz I'm getting huge lag and I wanted to run it on my own pc both Client and server

**Comment by Andrews54757** [comment]
ok, the lag is from your server. not my client as it doesnt matter for the client because it runs on your computer. 

1. Client data sent by github server
2. Client is run by your computer, not github server
3. client connects with your server
4. you play

So as you can see, there is no lag from the client server and if the client server was slow, it wouldnt matter except for the fact that loading the page might take a while

**Comment by Agarian** [comment]
i also suggest a "hide grid" option

**Comment by problemsofworld** [comment]
new version is full of bugs and lag many problem now I use old version it's agar.io 100% but the promblem i have question 1- agarplus map dont work and glitch on it 2- I cant have more than 1 minion I write `minion 1 then amount `amount dont work any1 help old version is perfect no bugs

**Comment by li-gary** [comment]
Hum... The client site has just given me this error :"Sorry, The place you are trying to access is currently not available. - LegitSoulja". Maybe there are some maintenance going on?

**Comment by tommyb008** [comment]
I have a problem

**Comment by tommyb008** [comment]
when i connect

**Comment by tommyb008** [comment]
i get this error in the console of when i open inspect element Connecting to wss://127.0.0.1:443
jquery-1.11.3.min.js:5 POST http://ajs-development.github.io/client/checkdir.php 405 (Method Not Allowed)send @ jquery-1.11.3.min.js:5m.extend.ajax @ jquery-1.11.3.min.js:5(anonymous function) @ main_out.js?542:890(anonymous function) @ main_out.js?542:1426
main_out.js?542:268 WebSocket connection to 'wss://127.0.0.1/' failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED
main_out.js?542:274 socket error
main_out.js?542:303 socket close what i see is you put "wss" instead of "ws" is it new or is it my problem?
help

**Comment by tommyb008** [comment]
and when i play i get this 
![download](https://cloud.githubusercontent.com/assets/17815538/15199678/3ef7bbce-1795-11e6-90db-a509f915d5b3.png)

**Comment by Megabyte918** [comment]
@tommyb008 same here

**Comment by Andrews54757** [comment]
Fixed

**Comment by Megabyte918** [comment]
@Andrews54757 where can I find the fix to this? my c9 repo & client are outdated

**Comment by Andrews54757** [comment]
see #537

**Comment by Andrews54757** [comment]
i just posted a comment

**Comment by problemsofworld** [comment]
@Andrews54757 are  you gonna make bots teaming for ogarUL

**Comment by Megabyte918** [comment]
@problemsofworld its postponed and @Andrews54757 when I start my server on port 8081 I get "upgrade required" and when I try port 8080 its just a white screen and nothing else (using the latest client)

**Comment by Andrews54757** [comment]
do plugin update

**Comment by Megabyte918** [comment]
plugin is not a command

**Comment by Andrews54757** [comment]
then update your server

**Comment by LegitSoulja** [comment]
@Andrews54757 check your pm on gitter please. Thanks.

**Comment by Parth1999** [comment]
Amazing😉!!!!!!!

**Comment by Parth1999** [comment]
Just waiting for skins and minion controls and it will be perfect. And yes the physics are awesome when we are above 1000 mass the only problem is split running when small is not that smooth. And for viruses pop and feed you guys have done a great job is like 100% real agar. Io . Is there any donation page or something really wanna help you guys some way. :)

**Comment by PrinceDark9243** [comment]
make a tutorial on how to join you Ogar un client server plz

**Comment by PrinceDark9243** [comment]
@Andrews54757 add E and R Key Support For Minions and Make Graphics Bar Where we can choose graphics

**Comment by Megabyte918** [comment]
@Parth 1999 <3
explain the splitrunning issue again?

**Comment by firelightning13** [comment]
I might create a tutorial about this, probably at weekends :)
(just like c9 tutorial, with intense graphic pictures and worse grammar intended/mlg)

**Comment by LegitSoulja** [comment]
@Andrews54757 You should be good with what I hooked you up with yesterday. Everything's working

**Comment by Lukkez** [comment]
@Andrews54757 Should i redirect Ogar-unlimited.tk to play.ogarul.tk?

**Comment by lotfis** [comment]
@Andrews54757 thanks for the client.
But I noticed that there is a problem since versions 16.0..., when my cell is aproximately 5k , when it split it kid of goes backword and I can't eat other cells. In version 11.5.8 it was correct.
Could you pls chek that and fix it

**Comment by LegitSoulja** [comment]
@Lukkez yes, will be working over there at the domain instead.

**Comment by LegitSoulja** [comment]
@Lukkez and are you serious?? Hosting24? Why use free hosting lol .. That's pointless and theres no security there and the site is flooded with hosting24 ads.. Eww,

**Comment by lotfis** [comment]
@LegitSoulja could you upload it on mediafire pls

**Comment by lotfis** [comment]
@LegitSoulja yes ogarul version 15.9.0

**Comment by LegitSoulja** [comment]
@LPArigma what official agar.io files? The official doesnt unless theres modifications..

**Comment by problemsofworld** [comment]
is there any option for minion random names and how to use it ?

**Comment by LPArigma** [comment]
@LegitSoulja okay i got that to work but i cant connect to my server.... i have ogar UL running on my pc the port and IP are correct idk why its not working... also OgarConsole plugin doesnt work.

**Comment by LegitSoulja** [comment]
@problemsofworld no, this is no way to have random names for a minion. If I have time to do if andrew doesnt deside to add it I could.

@LPArigma OgarConsole should work, it runs on whatever port you assign, by default its port 1000.
Make sure when you connect use the ip 127.0.0.1:<port>. replace <port> with your port.

OgarConsole discontinue, but I made sure it works before I discontinued it.

**Comment by LPArigma** [comment]
@LegitSoulja i get returned the error `Cannot GET /` it says int right on the front page lol and will other people be able to connect to my private server?

**Comment by LegitSoulja** [comment]
Cannot get /? For ogarconsole? or the client?

**Comment by LegitSoulja** [comment]
@LPArigma that doesn't make no sence at all. You did something wrong then

**Comment by LegitSoulja** [comment]
If you aren't hosting the client for yourself then the client plugin shouldn't be installed at all.

**Comment by LPArigma** [comment]
by client you mean the site? i have ogar UL running and it says when i go to localhost:8080 (which it says the the port to go to on the ogarul cmd prompt) it give me that error @LegitSoulja

**Comment by problemsofworld** [comment]
am sure 10000% that new version has 1000 bugs srry 
1-split   sucks 
2-if am close to a cell I die no idea how and screen giltches 
3-big lags with 39% cpu usage
4-spamming problems spam  close to big cell 

am I the only one who has these problems

**Comment by LegitSoulja** [comment]
@LPArigma 
localhost:8080 = Client (If you installed it!)
localhost:1000 = OgarConsole.

If you added the client plugin, you cannot use the client until you get the client files. Thats why it says cannot get / because the client does not exist. OgarConsole does not run on port 8080. 

@problemsofworld Actually, MinionLoader has random names from botnames.txt but it was not fully implemented lol

**Comment by problemsofworld** [comment]
yeah that why I said because I notice botnames.txt

**Comment by LegitSoulja** [comment]
@problemsofworld maybe if you add the minion name with like <random> since <r> for rainbow you can get random names. I can update it in a sec.

**Comment by LPArigma** [comment]
> [Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 16.5.0
[Client] Listening on *:8080
[Game] Loaded stats server on port 88
[Game] Listening on port 34343

@LegitSoulja how do i use the client?

**Comment by LegitSoulja** [comment]
See your using the client plugin, not ogarconsole. You dont even have ogarconsole installed. You need to download the client to be able to use the client. Or go to play.ogarul.tk and connect using localhost:34343

**Comment by LPArigma** [comment]
"See your using the client plugin," "You need to download the client to be able to use the client" you just said i have it... typo?

**Comment by LegitSoulja** [comment]
@LPArigma You have the client server, but not the client files. You see the folder client?? Yea, you dont have the actual client, but you have the plugin client server in the plugins folder.

**Comment by LegitSoulja** [comment]
[Agarioclient (1).zip](https://github.com/AJS-development/Ogar-unlimited/files/262206/Agarioclient.1.zip)

@LPArigma download that zip, and the content inside the agarioclient folder place everything inside the client folder, then go to localhost:8080

**Comment by LPArigma** [comment]
@LegitSoulja now i got it! is it posible for others to connect to my server now that it works?

**Comment by LegitSoulja** [comment]
@LPArigma actually, after you put the content into the client folder, open the client folder and you will see this
```
function connectToServer() {
var defaultserv = "ogar-unlimited-andrews54757.c9users.io:8081"
```

replace defaultserv with your server which will be

```
var defaultserv = "localhost:34343"
````

And the only way for people to connect to your client is if you portforward your router port 8080.

**Comment by LegitSoulja** [comment]
Actually, That wont work out quite well if the client has localhost because then your friend wont be able to connect. And if you add your ip and port to the client then you wont be able to connect. Idk you can try and let me know.

**Comment by problemsofworld** [comment]
@LegitSoulja  I use version 16.5.1 when I press Q  while am playing it crash (on client(freeze) not console) I dont want to update how to fix plz :(

**Comment by LegitSoulja** [comment]
@problemsofworld You dont have to update. I'll see what your issue is and come up with a fix. Give me a sec.

**Comment by LegitSoulja** [comment]
@problemsofworld Q doesnt even work for me.

**Comment by LegitSoulja** [comment]
@problemsofworld ok, I confirm that Q does work.

**Comment by problemsofworld** [comment]
console dont give any error
and still works as same but everthing get frozen when I press q

**Comment by LPArigma** [comment]
@LegitSoulja so if i put my ip and port in the client files all people have to do is type into theyre browser address bar "(MYIP):(MYPORT)" and they will be playing on my server?

**Comment by LegitSoulja** [comment]
put your ip+game port in the index.html and you give your friends your ip+8080

**Comment by LegitSoulja** [comment]
@LPArigma you will have to portforward your client port, and game port.

**Comment by LegitSoulja** [comment]
@problemsofworld after a few testings of op, there is alot of glitches with the client. But I have not frozed yet.

**Comment by problemsofworld** [comment]
not the client problem I just tested with agarplus same problem

**Comment by LegitSoulja** [comment]
@problemsofworld its the client. If it wasnt the client then agarplus would have worked.

**Comment by problemsofworld** [comment]
no same it will get frozen when I press Q  same problem with my friend he joined me on my server

**Comment by LPArigma** [comment]
@LegitSoulja @problemsofworld  Would you mind testing my server? http://73.190.35.16:8080/ 
btw i have sophos firewall, so i cant be tracked and you cant ping my ip or itll return with no response ;-)

**Comment by problemsofworld** [comment]
@LPArigma ur   socket is closed

**Comment by LegitSoulja** [comment]
@LPArigma LOL how retardet are you? Thats your real ip. And yea, it works.

**Comment by LPArigma** [comment]
@LegitSoulja it is my real ip lol i have a sophos firewall lol i trust my hardware lol

**Comment by LegitSoulja** [comment]
@LPArigma Your ip is your ip. You can be tracked. You live in michigan, and your ping came back lol..

**Comment by LegitSoulja** [comment]
Comcast internet too. Suckish

**Comment by LPArigma** [comment]
@LegitSoulja how is 175 mbps down and 120 mbps up bad?

**Comment by LegitSoulja** [comment]
Compared to mines http://www.speedtest.net/my-result/4890910668 YES! lol

**Comment by LPArigma** [comment]
@LegitSoulja whos your ISP!??!?!

**Comment by LegitSoulja** [comment]
Cox..

**Comment by LPArigma** [comment]
cox?

**Comment by LegitSoulja** [comment]
@LPArigma Yes cox..

**Comment by LegitSoulja** [comment]
You can get over 900mbps if you want to pay atleast $500 or more a month lol

**Comment by LPArigma** [comment]
@LegitSoulja are you making money of your hosting? enough to afford that isp plan?

**Comment by LegitSoulja** [comment]
@LPArigma nope. I used to host minecraft servers, and ive be developing games, and having servers for them but I dont no longer do hosting, and every since miniclip did what they did I had shut down all my agario servers, and closed the site. So I dont no longer host nothing nomore. I just have a vps with nothing running at the moment except a website and such.

**Comment by LPArigma** [comment]
@LegitSoulja dang, how can you afford $500 a month!?!!? lol and also i bet this has already been answered before but im to lazy to look for it, how can i use skins?

**Comment by LegitSoulja** [comment]
@LPArigma Well, I have a job, so does my girlfriend. So it's not a big deal. Plus I saved alot of money when I was younger so im not in debt or anything yet. I can afford it for a while, and i've just been saving. And skins was removed from the server.

**Comment by LPArigma** [comment]
@LegitSoulja how much money did you save when you were a kid holy shit

**Comment by LegitSoulja** [comment]
@LPArigma I don't want to go into too much detal, but I lost my mom when I was 15, and I guess social service paid me like $800 of my own money a month, and since then I've been saving, and I have a job on top of that, and I save from my job aswell. As long as all the bills are paid, and my girlfriend is good, then I am good.

**Comment by LPArigma** [comment]
@LegitSoulja when your making big bills off social security DAYUMMM

**Comment by LegitSoulja** [comment]
@LPArigma well that what happens when you loose a mother. They just wont throw you on the streets with nothing to live off of. I stayed with my grandmother till the time came to me of moving out.

**Comment by LPArigma** [comment]
@LegitSoulja sorry about your mom, and is there any way for me to use skins at all?

**Comment by LegitSoulja** [comment]
It's possible. But you'll still need the skins since it's not included with
the client

**Comment by LegitSoulja** [comment]
Well some skins are but not all

**Comment by Agarian** [comment]
so pretty much the premium skins code is useless now?

**Comment by LegitSoulja** [comment]
@Agarian the premium skins? Like the custom skins?

**Comment by LPArigma** [comment]
how would i add them into the client? @LegitSoulja

**Comment by LegitSoulja** [comment]
@LPArigma I'll make a tut later

**Comment by LPArigma** [comment]
Thanks so much @legitsoulja I got the t-Rex skin working but that's it, I added "t-Rex" to the list of skin names and the skin to the skins file but I couldn't get any other skins working and they only work by making your name the skin name

**Comment by Agarian** [comment]
how did you do so?

**Comment by Lukkez** [comment]
Isn't hosting24 =p

**Comment by Lukkez** [comment]
sry for close i'm on mobile and buttons small

**Comment by LPArigma** [comment]
@LegitSoulja tutorial?

**Comment by LegitSoulja** [comment]
@LPArigma I can't right now. Im kindof busy working on something at the moment.

**Comment by Andrews54757** [comment]
Closing client for now until reply from moneysh*t (im emailing them)

**Comment by Agarian** [comment]
uhh ok then lol

**Comment by LegitSoulja** [comment]
@Agarian well nvm then, afterwards I guess then I can show you.

**Comment by Agarian** [comment]
ok, tell me what to add on discord i guess then

**Comment by LegitSoulja** [comment]
@Agarian I don't have discord. Only skype.

**Comment by Agarian** [comment]
miniclip is my favourite cause they created agar.io, but the bane of my existence because they patched private servers lol

also i dont have skype, only discord

**Comment by Agarian** [comment]
try https://discord.gg/0vYaIdmfM1cXNYUy

**Comment by LegitSoulja** [comment]
@Agarian no im good. Discord is annoying. Last time I was in a room, and I wasnt at home, and someone was spamming pictures of nudity, and spamming voice commands.. Nah, im good.

**Comment by Agarian** [comment]
dude no ones gonna spam nudity lol

**Comment by LegitSoulja** [comment]
@Agarion it wasn't even nudity, it was disgusting. It was like poo nudity. After seeing it all it made me have to vomit.

**Comment by Agarian** [comment]
still

**Comment by LegitSoulja** [comment]
@Agarian use skype web version..

**Comment by Agarian** [comment]
dont i need an account? and the web version is the only PC version...

**Comment by LegitSoulja** [comment]
web version is for any browser. I don't like discord, neither do these people https://support.discordapp.com/hc/en-us/articles/212500837-How-do-I-permanently-delete-my-account-

**Comment by Agarian** [comment]
but i need an account.

**Comment by Agarian** [comment]
and it requires revealing too much info.

**Comment by Agarian** [comment]
so im not using skype.

**Comment by LegitSoulja** [comment]
I don't even know if I still have my account. I contacted them and told them to remove mines. They said they made my account inactive or something. So then I would have to register again, which im not because I do not want an account with discord. Im sorry.

**Comment by Agarian** [comment]
ok you know what screw it

**Comment by LegitSoulja** [comment]
@Agarian I could like email you or something?

**Comment by Agarian** [comment]
i guess that could work

**Comment by LegitSoulja** [comment]
@Agarian pm your email on gitter, and ill send you an email when im done

**Comment by Agarian** [comment]
done

**Comment by Andrews54757** [comment]
@LegitSoulja Do you know what happened to the forums page in forum.ogarul.tk? it vanished somehow. Also, with oxwall, I can reproduce skype with anonymous accounts

**Comment by LegitSoulja** [comment]
@Andrews54757 I don't know. I'll check. If its not there i'll add it again and are you sure you really want oxwall? It's slow and idk why,

**Comment by Agarian** [comment]
i pm'ed my email

**Comment by LegitSoulja** [comment]
@Agarian ok i got you when im done with what im doing. Just give me a minute please.

**Comment by Agarian** [comment]
ok

**Comment by LPArigma** [comment]
@LegitSoulja ive been trying at this for an hour and a half kms i dont understand why its not working D:

**Comment by LegitSoulja** [comment]
@LPArigma it's advanced. You have to update the updatenodes, the client, and a few other things. I'll have to go back and retrace my steps to what I did to get the skins working cause I kindof forgot cause it was last week when I did. I'll show you guys as soon as I can.

**Comment by LPArigma** [comment]
Thanks bro, i can get normal skins to work just not custom ones lol. Take your time lol

**Comment by LegitSoulja** [comment]
@LPArigma Yes, I will show you how to get them working, and also your own client skins you upload.

**Comment by LegitSoulja** [comment]
@LPArigma @Agarian Well, the client skins you can use because it will have to run on an actual webserver to pring out json format for the skins, which express doesn't use php unless you install php and implement it.

**Comment by Agarian** [comment]
pls do so
