### ISSUE TITLE
Now that we have to use a separate client...

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#552]
Now can you control the minions by using E and R keys?
(E for split and R for ejecting mass)
(the answer is probably no :P lol )

**Comment by Andrews54757** [comment]
Soon

**Comment by Agarian** [comment]
:D

**Comment by Megabyte918** [comment]
I cant w8 m8

**Comment by Andrews54757** [comment]
FINISHED! (but in the opt in program). see #621
