### ISSUE TITLE
Have fun XD [FIXED] Works with agar IP

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#554]
http://imgur.com/wvQ4Uhh

**Comment by problemsofworld** [comment]
private servers work like before just add bagar.io to ur chrome XD

**Comment by Jhair2015** [comment]
not working, helpme please :D

**Comment by problemsofworld** [comment]
u right it not working with new version of ogar lucky I got the old one which still works but too lazy to upload XD . the only don't work is q . all other thinks work

**Comment by problemsofworld** [comment]
http://imgur.com/MF4OHDP

**Comment by PrinceDark9243** [comment]
use infinity extension it will work with q and other keys

**Comment by Jhair2015** [comment]
Not working in bagar.io :/

**Comment by problemsofworld** [comment]
@Jhair2015

**Comment by problemsofworld** [comment]
agarplus now uses ogarUL and made three servers BUT not giving AJS DEVS credits

**Comment by firelightning13** [comment]
wat do u mean gimme de link

**Comment by LegitSoulja** [comment]
Maybe you should take a look at this before posting crap like this that we dont care about https://github.com/AJS-development/Ogar-unlimited/issues/548

**Comment by problemsofworld** [comment]
srry
