### ISSUE TITLE
What am I doing Wrong? Update : Worked :)

### ISSUE THREAD

**Issue by Parth1999** [AJS-development/Ogar-unlimited#555]
UPDATE :- Server Worked Read only if You want
Ok I have got the client file but I have issues running it so I decided to do it from scratch please help me guys I am doing the exact same thing what I am typing here. Just guess the wrong step.
1.Made a new public project named it and used https://github.com/AJS-development/Ogar-unlimited.git for the clone git files and chose node.js in c9.io (obviously will be the latest ogar UL) 
2.At the very first did npm install in the terminal.
3.Terminal commands : cd src then did sudo node index.js server successfully started then i typed plugin install Client no errors till now but one error (maybe )
Terminal console : 
plugin install Client
>[Console] Installing Client
[Console] Downloading...
[Console] Downloading ./plugins/Client/files.txt
[Console] Downloading ./plugins/Client/index.js
[Console] Downloading ./plugins/Client/README.md
[Console] Done, Reloading...
[Console] Loading plugins
[Plugin] Plugin configs for Client Implementation Cannot be loaded
[Console] Downloading Files
[Console] loaded plugin: Client Implementation By Andrews54757 version 1.0.0
[Console] Failed to load pluginfile README.md Reason: Error: Cannot find module '../plugins/README.md/index.js'
[Update] Running npm install to install new node modules!
[Console] Client installed successfuly! See howtouseclient.md for instructions
OgarUnlimited terminated with code: 0

ok so i don't think any problem exists because whenever i type restart i receive 
OgarUnlimited terminated with code: 0 error

4. Changed the advconfig.ini

    vps to 0
    serverPort to 8081

5. Downloaded Agarioclient.zip (real) 
6. Ok so now the problem start when i try to copy the files in client folder it just uploads and vanishes. Seems I don't have permissions. ( sorry Andrew but i tried to google the issue )
NVM I GOT IT thanks to firelightining13 just delete and recreate :P
7. Copied the files did exact steps according to readme.md files
8. started the server and guess what it worked lol i dont know why the fk it wasn't working before lololololol
Since i have written so much i guess i may keep it for others Sorry guys nvm Thanks everyone

**Comment by firelightning13** [comment]
its good that u have the client working now close dis issue

**Comment by Parth1999** [comment]
Shall I leave it open and make it a tutorial instead?

**Comment by firelightning13** [comment]
Yeah you can

**Comment by firelightning13** [comment]
well nvm lol
