### ISSUE TITLE
OGAR IS NOTHING

### ISSUE THREAD

**Issue by XenoYT** [AJS-development/Ogar-unlimited#556]
FIX THIS ERRORS
OR GIVE A DAMN TUTORIAL I FUCKING FOLLOWED ALL THE DAMN FUCKING STEPS I FUCKING INSTALLED NPM AND UPDATED NODE.JS AND I FUCKING DID THE SETTING IN ADVSETTINGS VPS TO 0 AND PORT 8081 AND STILL GOT THIS SHIT
![weez](https://cloud.githubusercontent.com/assets/18215228/15183520/b8d5c89a-1791-11e6-87dc-1b073148c667.PNG)

**Comment by firelightning13** [comment]
node version?

**Comment by XenoYT** [comment]
@firelightning13 6.1.0

**Comment by firelightning13** [comment]
downgrade ur version to 5.9.0

**Comment by XenoYT** [comment]
@firelightning13 How ?

**Comment by firelightning13** [comment]
Uninstall nodeJS in ur computer then reinstall the 5.9.0 here:
https://nodejs.org/download/release/v5.9.0/

**Comment by XenoYT** [comment]
@firelightning13 Thanks ill try

**Comment by Andrews54757** [comment]
Do `npm install request`

**Comment by XenoYT** [comment]
@Andrews54757 doesnt work keeps same error

**Comment by Andrews54757** [comment]
dont do it in node shell. do it in regular cmd
