### ISSUE TITLE
STOP CLOSING MY ISSUES

### ISSUE THREAD

**Issue by XenoYT** [AJS-development/Ogar-unlimited#557]
FIX THE ERRORS I WISH IF I NEVER KNOW THE FUCKING OGAR SHIT
![weez](https://cloud.githubusercontent.com/assets/18215228/15188307/527a7ba4-17a5-11e6-9d05-0ccc63f5aa9b.PNG)
I DID ALL FUCKING STEPS SO STOP FUCKING REPLYING SAME DAMN THINGS

**Comment by XenoYT** [comment]
AND STOP CLOSING MY DAMN ISSUES UNTIL IT GET FIXED THAT NOT FUCKING FAIR

**Comment by Agarian** [comment]
R U vSabertail?

also just try "npm install process-nextick-args" 
if it doesn't work idk. sorry.

**Comment by XenoYT** [comment]
@Agarian 
![helps](https://cloud.githubusercontent.com/assets/18215228/15188400/d8627f1e-17a5-11e6-935a-5b055fab0b9d.PNG)

**Comment by LegitSoulja** [comment]
@Agarian NOO.. That's wrong.. smg. @XenoYT **npm install request** will fix that problem.

**Comment by LegitSoulja** [comment]
and @XenoYT don't run those in node cmd. You have to open a normal shell. You could install request globally.
