### ISSUE TITLE
REALLY BAD ISSUE PLEZ HELP and ill give the chez to you

### ISSUE THREAD

**Issue by tommyb008** [AJS-development/Ogar-unlimited#558]
please help i get this

![download](https://cloud.githubusercontent.com/assets/17815538/15199858/95852c78-1796-11e6-8879-9852c59c5b7f.png)

F!CK M!N!SH!T

**Comment by Agarian** [comment]
so you get a grid screen? to connect to ur server now, you need to go to http://ajs-development.github.io/client/ and connect to your server with the ip:port.

if ur running this on ur computer, you would use the ip 127.0.0.1:443

**Comment by problemsofworld** [comment]
ur socket is closed if you run on c9.io change  ur port 8080

**Comment by tommyb008** [comment]
I DONT USE C9 OR 443 I USE 8081 AND I STILL GET THE SAME PROBLEM AND I CONNECT TO THAT WEBSITE PLZ HELP

**Comment by problemsofworld** [comment]
problem is with ur server it's must port

**Comment by Andrews54757** [comment]
No, it was the client. it is fixed now

**Comment by Megabyte918** [comment]
@Andrews54757 how do I fix it for my repo?

**Comment by LegitSoulja** [comment]
@Megabyte918 did you fork it?

**Comment by Megabyte918** [comment]
I forked OgarUL and installed the plugin and everything. I followed the OgarUL client guide exactly

**Comment by LegitSoulja** [comment]
@Megabyte918 message me on skype, Ill help you

**Comment by Andrews54757** [comment]
see #537 . i posted a new client
