### ISSUE TITLE
Implement Ogar-unlimited to Cigar

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#559]
Should someone help that? i am going to use Ogar-unlimited (OgarUL) on my server, i can put Ogar-unlimited at Cigar? or maybe transfer all the "html code" to the OgarUL client?

**Comment by LegitSoulja** [comment]
Just by replacing the html code wont bring the textures back lol. Use cigar or dont.

**Comment by Lukkez** [comment]
It's just bootstrap, no textures, i think i'll put and trasnfer css, will need a bit of time but i can

**Comment by LegitSoulja** [comment]
Well if you do, make sure the classes and id's are correct in the elements, or the wont work at all.
