### ISSUE TITLE
Put servers you want people to go to here

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#56]
Please in the comments add private servers that you enjoy,
To do it, please use the format of `[servername] (agar.io/?ip=exampleip:port)` and add a description

Example.

[parisgamma server] (https://agar.io/?ip=parisgamma.iomods.com:1501)
A server where you can do custom skins

**Comment by Megabyte918** [comment]
Well, since no one else has commented i will
http://agar.io/?ip=71.162.139.217:4545
Its nothing special, just a regular old ffa server :)

**Comment by Agarian** [comment]
I cant now i got school ; (

**Comment by firelightning13** [comment]
im playing right now lol

**Comment by ErikParacelsus** [comment]
Megabytes change your map borders to 
`14142`
and your eject speed to
`100`
for more like-agar.io

**Comment by Agarian** [comment]
@Megabyte918 playin now

**Comment by firelightning13** [comment]
How did u get value 14142? :0

**Comment by PrinceDark9243** [comment]
Unamed Cell Server:
http://agar.io/?ip=unnamedcell.ddns.net:28
Info:
      This Server is not 24/7 and is old FFA! etc! 3NGOY!

**Comment by PrinceDark9243** [comment]
CAN SOMEONE KNOW HOW TO HOST 24/7 SERVER

**Comment by firelightning13** [comment]
You need money to do that

**Comment by PrinceDark9243** [comment]
tell me website

**Comment by firelightning13** [comment]
Search in google

**Comment by PrinceDark9243** [comment]
i did but cant find

**Comment by firelightning13** [comment]
great all about minecraft server xD

**Comment by firelightning13** [comment]
just played lol

**Comment by PrinceDark9243** [comment]
lol

**Comment by Megabyte918** [comment]
@ErikParacelsus Done :)

**Comment by firelightning13** [comment]
@Megabyte918 there's something wrong with your server

**Comment by Megabyte918** [comment]
Yeah ik haha ill change it back to ffa

**Comment by StormGS5** [comment]
yeah now pls

**Comment by StormGS5** [comment]
@Megabyte918  please change it theres a giant mothercell

**Comment by StormGS5** [comment]
thanks

**Comment by StormGS5** [comment]
what ur name in server

**Comment by Megabyte918** [comment]
I cant play rn im in school. What's ur skype? We could talk on there

**Comment by Andrews54757** [comment]
THIS IS SOO SHAMEFUL THAT PEOPLE ARE DISRESPECTING OTHERS, I AM FREEZEING ALL ASSETS
