### ISSUE TITLE
How to fix this issue?

### ISSUE THREAD

**Issue by Mozzzzzie** [AJS-development/Ogar-unlimited#562]
Error:

[Console] Failed to load pluginfile README.md Reason: Error: Cannot find module '../plugins/README.md/index.js'

I Made a new public project named it and used https://github.com/AJS-development/Ogar-unlimited.git for the clone git files and chose node.js in c9.io

**Comment by fayizan** [comment]
same Problem for me too ,When I open http://52.76.144.254:443/ 
its shows Upgrade Required,what I have to do..?

**Comment by LegitSoulja** [comment]
@Mozzzzzie delete the readme file in the plugin folder

@fayizan You are connecting directly to the game. You will need a client. Therefore the same ip and port you used enter it here http://play.ogarul.tk

**Comment by LegitSoulja** [comment]
@fayizan without http just ip:port when the alert box shows on connecting.

**Comment by LegitSoulja** [comment]
Normally that readme error just ignore it. If it causes the server to not run then delete that file in the plugin folder to solve that issue

**Comment by Mozzzzzie** [comment]
I delete that file and restart it .There is no  error is on the terminal. But when i connect http://ajs-development.github.io/client/? and type my url:port there will pop new error:
![01](https://cloud.githubusercontent.com/assets/19339372/15239213/380a18dc-1913-11e6-85fb-10fdba3288b0.jpg)

Cannot connect to server, click the reconnect button below to try again

**Comment by LegitSoulja** [comment]
@Mozzzzzie

Make sure you enter it like this for example. 
127.0.0.1:443 or localhost:443

**Comment by Mozzzzzie** [comment]
@LegitSoulja yes, there is my terminal information.

`Loading Config Files...
Loading ./settings/advConfig.ini
Loading ./settings/config.ini
Loading ./settings/override.ini
i8dZaZS
[Console] Loading plugins
[Downloading] http://raw.githubusercontent.com/AJS-development/Ogar-unlimited/master/src/files.json to: filesTemp.json
Starting ConsoleService
                                        _ _       _              _ 
                                       | (_)     (_)_           | |
  ___   ____  ____  ____    _   _ ____ | |_ ____  _| |_  ____ _ | |
 / _ \ / _  |/ _  |/ ___)  | | | |  _ \| | |    \| |  _)/ _  ) || |
| |_| ( ( | ( ( | | |      | |_| | | | | | | | | | | |_( (/ ( (_| |
 \___/ \_|| |\_||_|_|       \____|_| |_|_|_|_|_|_|_|\___)____)____|
      (_____|                                                      
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 16.5.0
[Game] Loaded stats server on port 8082
[Game] Listening on port 8080
[Game] Current game mode is Free For All
[Autopause] The Game Was Paused to save memory. Join the game to resume!`


you can use this usr to test, ogor-tarian.c9users.io:8080

thank you very much

**Comment by LegitSoulja** [comment]
@Mozzzzzie much welcomes

**Comment by Mozzzzzie** [comment]
@LegitSoulja I test open http://ajs-development.github.io/client/? and input my url and port like this, ogor-tarian.c9users.io:8080  ,but the window show me:
Cannot connect to server, click the reconnect button below to try again

so, can you help me fix it?  thanks

**Comment by LegitSoulja** [comment]
@Mozzzzzie 

Your using c9, and I thought port 8080 can't be used. Try going to that url directly. You should see a text that says "Upgrade Required". If you see that text then that confirms that the game is running on port 8080. 

When you enter the url on connected here http://ajs-development.github.io/client/ check the browser console to see if it says anything about a socket. Whether it's open or close. If you don't see anything then maybe you should change the port to something else other than port 8080.

**Comment by Mozzzzzie** [comment]
@LegitSoulja thank you. It works

**Comment by fayizan** [comment]
I m using AWS,I can't connect to server
![screenshot_4](https://cloud.githubusercontent.com/assets/19163419/15240057/9f2d4f34-1904-11e6-9065-d4624420979d.jpg)

**Comment by Mozzzzzie** [comment]
@fayizan try use another browser, like firefox

**Comment by Mozzzzzie** [comment]
@fayizan open your port 8082, I play in your server just moment. and use 52.76.144.254:8081

**Comment by Mozzzzzie** [comment]
1. [Game] Loaded stats server on port 8082
2. [Game] Listening on port 8080

maybe two port need open for wan

**Comment by fayizan** [comment]
![screenshot_6](https://cloud.githubusercontent.com/assets/19163419/15243428/2b58d140-1919-11e6-9a4a-a91de225589f.jpg)

@Mozzzzzie Like this..?

**Comment by fayizan** [comment]
But My Game http://52.76.144.254:8080/ Works without using http://play.ogarul.tk

**Comment by Andrews54757** [comment]
mabe because that ip is your client port, not your server port

**Comment by Andrews54757** [comment]
yourserver ip is 52.76.144.254:8081

**Comment by LegitSoulja** [comment]
@fayizan Don't don't forget about your inbound and outbound rules. Similar as port forwarding but you still will have to with amazon. Also check your firewall. Since you are using aws you can use port 8080 just because there's no other service running port 8080. You can check by typing this cmd command 

> netstat -a

**Comment by fayizan** [comment]
![screenshot_7](https://cloud.githubusercontent.com/assets/19163419/15248168/53dba9cc-1936-11e6-99b2-94b55334a66d.jpg)

well u mean I have to use these ports..?

**Comment by LegitSoulja** [comment]
@fayizan Those ports are the ports you wouldnt want to use, since they already have services listening on them. Your good with port 8080, 8081, and 8082 since there's nothing listening on it.

**Comment by fayizan** [comment]
well ok I set my Rules to this 
![screenshot_8](https://cloud.githubusercontent.com/assets/19163419/15248227/b0533ba2-1936-11e6-93ac-58e0adf912a5.jpg)

**Comment by LegitSoulja** [comment]
Set both inbound, and outbound to all traffic. Don't remove port 3389. Your going to wish you never did.

**Comment by LegitSoulja** [comment]
@fayizan Also, check your firewall. Test if you can connect before and after disabling the firewall. If it works while disabling then also add the port rules in the firewall. Or just disable the firewall, but its not recommended.

**Comment by fayizan** [comment]
I tried soo hard but nothing works I give up
Thanks for helping @Andrews54757  @LegitSoulja and @Mozzzzzie

**Comment by LegitSoulja** [comment]
@fayizan what's your skype? I can help you

**Comment by fayizan** [comment]
My skype fayizbe

**Comment by LegitSoulja** [comment]
@fayizan I sent you a contact request
