### ISSUE TITLE
plZ  Bots e split and r feed add it 

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#568]
Please read the FAQ in advance.

What game mode were you in when you had the issue?

What version are you on?

What command did you type if any?

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

**Comment by ErikParacelsus** [comment]
Client-sided??

**Comment by Andrews54757** [comment]
@problemsofworld . See #548

**Comment by Andrews54757** [comment]
one more time @problemsofworld  then you are banned for a month

**Comment by problemsofworld** [comment]
wow I just need some help :'( I will try by my self then :(

**Comment by LegitSoulja** [comment]
https://github.com/AJS-development/Ogar-unlimited/issues/510

**Comment by LegitSoulja** [comment]
Ask there for suggestions instead of creating new issues. It was my fault I had that issue on hold and locked due to the times there wasn't no client.
