### ISSUE TITLE
big problem c9.io blocked alot of account who use private servers :(

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#569]
hey I just open my both account and they were blocked am i the only who have this problem I even paid for c9.io upgraded my account :( fuck moneyclip again  http://prnt.sc/b3o2dl

**Comment by Andrews54757** [comment]
were you hosting bots?

**Comment by problemsofworld** [comment]
no

**Comment by Andrews54757** [comment]
dont ask about c9 here, ask at the c9.io community

**Comment by problemsofworld** [comment]
lol I was just saying if any1 else is account is blocked

**Comment by Andrews54757** [comment]
https://community.c9.io/t/a-backup-for-blocked-account/669

**Comment by LegitSoulja** [comment]
-_-
