### ISSUE TITLE
From now on, if you duplicate an issue, you will be banned for a week

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#570]
This is serious.

#### Current banlist (name - dateappeased)

**RelTakeover** - Appeal(6.28.16)
- Spam abuse 
- Profanity towards devs
- Not listening to rules/guidelines
- Was told not to make any more issues but did anyways.

**Comment by Andrews54757** [comment]
Also NO MERCY

**Comment by PrinceDark9243** [comment]
What is MERCY dude

**Comment by PrinceDark9243** [comment]
and i found a glitch in my server eject mass at down border you will be tp to up pretty lol haan!

**Comment by NatsuTheGreat** [comment]
Maybe a banning list for rude people like this guy: http://prntscr.com/b9lo7s

(I will delete this comment after you read it)

**Comment by LegitSoulja** [comment]
@Andrews54757 
Unbanned 
* XenoYT - 6.21.16
* XtremeCod kid - 6.21.16

Unknown bans w/o release date.
* forairan
* vram4
* DictatorDan
* LostCodesy

**Comment by Agarian** [comment]
Xeno was re banned for a month

**Comment by Agarian** [comment]
Proof: #618

**Comment by Agarian** [comment]
Vram is banned?

**Comment by Megabyte918** [comment]
and forairan too tf?

**Comment by NatsuTheGreat** [comment]
http://prntscr.com/bjeca3

@Agarian

**Comment by NatsuTheGreat** [comment]
Why would both of them be banned :/

**Comment by LegitSoulja** [comment]
I have no idea. I searched other issues and there's nothing about them being banned.

**Comment by NatsuTheGreat** [comment]
Well they can be banned without notice.

**Comment by LegitSoulja** [comment]
I'll leave that up to andrew. That's the only person who does the banning including me.

**Comment by NatsuTheGreat** [comment]
I can't do banning.

**Comment by LegitSoulja** [comment]
I think you have to be owner to ban, which is only me and andrew the only people that can ban.

**Comment by NatsuTheGreat** [comment]
Oh Alright. Our tag "AJS-development member" is the same. So I thought I could do it too, I was incorrect.

**Comment by LegitSoulja** [comment]
Yes, everyone part of AJS is a member. https://github.com/orgs/AJS-development/people

**Comment by Agarian** [comment]
@NatsuTheGreat mybad its in #810

**Comment by NatsuTheGreat** [comment]
There we go.

**Comment by Andrews54757** [comment]
Very long story I wont explain

**Comment by Andrews54757** [comment]
(starting even before ogarUL exsisted)

**Comment by Andrews54757** [comment]
And I lied. Xeno and others arnt banned for a month. They are banned permenantly, because I realised how much peacful ogarul became without them

**Comment by NatsuTheGreat** [comment]
^ Lmao.
Did you ban vram4 and forairan?

**Comment by Agarian** [comment]
PERMANENTLY? wow, thank you for banning Xeno!
