### ISSUE TITLE
Can someone tell me how to connect with your friends?

### ISSUE THREAD

**Issue by HappyRocketwheel** [AJS-development/Ogar-unlimited#572]
Agar.io patched private servers, tried every bypass and didn't work so I wanna play with my friends using ogar unlimited.

I tried http://play.ogarul.tk/ but that's only solo, can someone share how to connect w/ friends?

**Comment by Agarian** [comment]
try and use c9.io, it is the easiest way currently. #280

**Comment by HappyRocketwheel** [comment]
@Agarian like I said, agar.io doesn't allow private servers anymore.
private servers dont load anymore

**Comment by Agarian** [comment]
You need to use the ogar unlimited client. #551

**Comment by HappyRocketwheel** [comment]
Ogar unlimited client is only you playing in it, your friends cannot join you when you connect a IP.

I want my friends to join in a private server with me, i don't like being solo.

**Comment by NatsuTheGreat** [comment]
@HappyRocketwheel Same here man!

**Comment by LegitSoulja** [comment]
@HappyRocketwheel port forward your ports. Don't use c9 cause its laggy af. I dont know why anyone uses it when there computer they have probably runs better.

**Comment by Agarian** [comment]
the only reason i use c9 is so others actually CAN join my server

**Comment by Megabyte918** [comment]
I use c9 because I can start it at my school and have my friends join, I don't have to have it running all day from my computer at home

**Comment by Andrews54757** [comment]
I sent this mail to moneyclip:

```
Hello nuno (or is it someone else?),

I am a dev from ogar ul as you may already know. I want to first set things straight: Do you, or do you
 not want private servers? if you are okay, then we would work on adjusting the protocal to comply. 
Also, if you dont want them, can you please make a site such as agar.io/private/ which has the old 
client? I know you deleted the old one at agar.io/v72/. I just dont want to use an illegal client because 
of my morals, I even suspended the temporary client sites for ogarul. If all you want is money, you can 
still have ads there and to make more money, you could sell backgrounds as they are highly wanted. It 
would mean a lot to the community if you bring private servers back. It would mean winning over the 
tens of thousands of ex-supporters back. Thank you


andy s
```

**Comment by Agarian** [comment]
lets see how they brush this off... (i'd be surprised if they don't)

**Comment by Megabyte918** [comment]
watch them reply with the template again lmao

**Comment by aymanio** [comment]
GUYS how i use c9.io? i wanna how cuz with hamachi my friends cant join

**Comment by firelightning13** [comment]
@aymanio #1445 

Port forward is the only way to play with your friends.

**Comment by aymanio** [comment]
i dot khow how bro

**Comment by LegitSoulja** [comment]
@aymanio that's why you have to learn. We don't help you with server setups.
