### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by zezofx** [AJS-development/Ogar-unlimited#573]
http://prntscr.com/b3s0wx

**Comment by Agarian** [comment]
make sure to have nodejs v5.9.0

uninstall your node and reinstall
https://nodejs.org/download/release/v5.9.0/

**Comment by zezofx** [comment]
Error Fixed but ..
http://prntscr.com/b3sob5

**Comment by Agarian** [comment]
use the ogarul client #551 
http://ajs-development.github.io/client/

**Comment by zezofx** [comment]
Dont Work .

**Comment by LegitSoulja** [comment]
@zezofx when you go onto the site enter 127.0.01:443

**Comment by zezofx** [comment]
Ty ..

**Comment by LegitSoulja** [comment]
@zezofx The clients are closed right now due to talking to miniclip for clarity about our client and private servers.

You are allowed to get the client for yourself to not have to worry about the client being down if you want it.
