### ISSUE TITLE
I tried everything and i got nothing

### ISSUE THREAD

**Issue by XxRaizerxX** [AJS-development/Ogar-unlimited#574]
I came here to have fun on a private server a Moneyclip ruins it !
I came here for respect from others and i get no respect.
I came here to make a server and i can't make a server.
I came here from VSabertail he quit Github.
I came here to talk about issues and no one will let me use issues.
I came here to make new friends and they all want to ban me.

## I get nothing everything sucks cause of Moneyclip and people here 
Show some respect here I'm starting to get mad and i want you all to not make it worse for me
cause i do not want to be mad cause... you don't wanna know SO...

**Comment by XxRaizerxX** [comment]
## AND DON'T CLOSE THIS ISSUE I WILL CLOSE IT IN A DAY!!!

**Comment by VSabertail** [comment]
I'm still here bro

**Comment by VSabertail** [comment]
I just do not wanna get yelled at anymore cause of stress and its bad for me and i hate stress 
and i thing that's what your going through is stress you might loose your hair just to let you know.

**Comment by XxRaizerxX** [comment]
LOOL.

**Comment by VSabertail** [comment]
yeah that's what i mean and also i know what you mean by moneyclip sucking dick

**Comment by Agarian** [comment]
try #539 rage all u want, use profanity etc

**Comment by LegitSoulja** [comment]
@XxRaizerxX It's because you don't follow the rules and guidelines around here. You pretty much spam chat way to much, after I told you plenty of times to go to an appropriate place like (Chat) to talk to your friends instead adding more and more comments to issues. Then on top of that you use way to much profanity over the issues and I got tired of cleaning up the mess you leave behind. Maybe if you follow rules like everyone else probably you wouldn't loose points as meaning loosing respect towards us. We are not trying to ruin nothing for you, nor act against you in any kind of way. Just follow the rules like everyone else does and you won't face these consequences. 

No, this thread won't be closed tomorrow it will be closed now. I'm pretty sure everyone will still see this if the issue is closed or not. More than likely, you aren't the only one with stress around here. There's many of us thats stressed, and going through depression, so I cannot just act differently just towards you. The way you act here is the way you will be treated as. Just follow the rules like asked and there won't be problems at all. 

Main reason why this has to be closed is because it doesn't follow the guideline. Issues are for issues. Not your personal messages, nor this is not a broadcasting place to get everyone to see your message. You don't need to cause attention on the forums. Just take it easy.

**Comment by XxRaizerxX** [comment]
GO FUCK YOURSELF

**Comment by XxRaizerxX** [comment]
THE GREAT DEPRESSION AGAIN

**Comment by LegitSoulja** [comment]
@XxRaizerxX Yea, Would you like to repeat that one more time? Profanit is your problem kid. You need to chill out.

**Comment by XxRaizerxX** [comment]
ok

**Comment by LegitSoulja** [comment]
I'll let andrew deal with you. I don't want to be the person claimed as being to harsh to you..

**Comment by XxRaizerxX** [comment]
im 12

**Comment by LegitSoulja** [comment]
Go figure!!. No wonder..

**Comment by XxRaizerxX** [comment]
Dude also i got held back IN SCHOOL twice in third and forth grade so yeah im in fifth grade

**Comment by Megabyte918** [comment]
Have some respect for us and follow the rules and you'll get some respect back, simple

**Comment by LegitSoulja** [comment]
@XxRaizerxX keep your personal information to yourself please.

**Comment by XxRaizerxX** [comment]
idgaf

**Comment by XxRaizerxX** [comment]
IM TELLING YOU SOMETHING SO YOU CAN LEARN SOMETHING ABOUT ME

**Comment by LegitSoulja** [comment]
@XxRaizerxX and with that attitude you won't make it no where far in life. I'm telling you. I know people who is struggling to this day trying to live and make something of themselves. Don't down yourself.

**Comment by LegitSoulja** [comment]
@XxRaizerxX Ok, clearly your age was enough, but then you went even more personal.

**Comment by XxRaizerxX** [comment]
And guess what

**Comment by XxRaizerxX** [comment]
nvm i was going to insult you

**Comment by LegitSoulja** [comment]
@XxRaizerxX I don't want to know, and I dont care.

**Comment by LegitSoulja** [comment]
@XxRaizerxX Well keep it too yourself or I will actually ban you. You insulted me enough. Did I give an issult back? No. Keep your words to yourself.

**Comment by XxRaizerxX** [comment]
you think your so special cause you can ban but you are not

**Comment by LegitSoulja** [comment]
@XxRaizerxX Nah, I'm a person just like everyone else. But, I have the ability to do so. Stop being aggy and just follow directions and there wont be no problems. But you insist to use profanit and insult others. There's no need for that.

**Comment by XxRaizerxX** [comment]
Hey let me see if your smart ill ask you a question

**Comment by XxRaizerxX** [comment]
Divide 30 by half and add ten. What do you get

**Comment by LegitSoulja** [comment]
Dude, Im 24 years old. Anything you can ask me ill crush it. I'm not even going to answer non of your questions. I'm done talking to you. You told me to go f myself, im done with you. I tried to be nice to you but you issist to insult me. Bye. I will let andrew deal with you, and the punishment might even be worser than it is now.

**Comment by LegitSoulja** [comment]
I know my mathematics. Maybe you should finish school and learn yours.

**Comment by XxRaizerxX** [comment]
i know the answer you figure it out

**Comment by LegitSoulja** [comment]
@XxRaizerxX I don't have to answer that. This is not a place to answer math questions. That's the most easiest thing. If you don't know what 15*2 + 10 then you must be slow. Bye. I'm done talking to you.

**Comment by XxRaizerxX** [comment]
What does half really mean? 0.5! 30 divided by 0.5 = 60

**Comment by XxRaizerxX** [comment]
you should learn more

**Comment by LegitSoulja** [comment]
@XxRaizerxX Learn how to properly ask a math question.

**Comment by XxRaizerxX** [comment]
look at my comment again i edited it

**Comment by Megabyte918** [comment]
*facepalm * I like you @XxRaizerxX , I really do... but just.... HAHAHAHAHA THAT QUESTION

**Comment by LegitSoulja** [comment]
idc about your comment(s). period. bye now. Stop talking.

**Comment by XxRaizerxX** [comment]
Megabyte wanna question lol

**Comment by Megabyte918** [comment]
@XxRaizerxX go on discord

**Comment by Agarian** [comment]
answer me this:
9x-3y+2x²=118

What are the values of **x** and **y**?

**Comment by LegitSoulja** [comment]
@Agarian dude hes like in 12.. In fifth grade..

**Comment by Agarian** [comment]
lol im 13 in 8th grade

**Comment by LegitSoulja** [comment]
@Agarian Im proud of you. And of course. Around 6/7 you learn that stuff.

**Comment by XxRaizerxX** [comment]
y=
2
3
x2+3x+
−118
3

**Comment by XxRaizerxX** [comment]
i suck i probally got it wrong

**Comment by Agarian** [comment]
yeap, X was 5 and Y was 9

**Comment by LegitSoulja** [comment]
@Agarian Test him with logarithm haha

**Comment by XxRaizerxX** [comment]
tell me something elce

**Comment by Agarian** [comment]
never heard of logarithm :P

**Comment by LegitSoulja** [comment]
Wait till you get to 11th grade then..

**Comment by Agarian** [comment]
try 

10(9x-3)²=360000
what is **X**?

**Comment by XxRaizerxX** [comment]
damn

**Comment by Agarian** [comment]
youll be suprized what X is

**Comment by LegitSoulja** [comment]
log₅x = 2 Solve it.

**Comment by XxRaizerxX** [comment]
i cant put it like i dont have the right caracters

**Comment by LegitSoulja** [comment]
log₂(8) = 3.

Thats even easier..

**Comment by XxRaizerxX** [comment]
1
3
+
−20
3
√10

**Comment by XxRaizerxX** [comment]
i got it wrong right

**Comment by Agarian** [comment]
x=7 m8s

**Comment by Agarian** [comment]
9*7= 63
63-3 =60
60*10= 600
600²=360000

**Comment by XxRaizerxX** [comment]
give me something easier

**Comment by Agarian** [comment]
ok

4x-12=4

**Comment by XxRaizerxX** [comment]
its 4
lol

**Comment by Agarian** [comment]
correct

**Comment by XxRaizerxX** [comment]
Wow

**Comment by Agarian** [comment]
stepping it up

5b+3c=27
what is **b** and **c**?

**Comment by Agarian** [comment]
also lets continue on discord

**Comment by XxRaizerxX** [comment]
3c/7+27/5 is b

**Comment by XxRaizerxX** [comment]
idk the rest

**Comment by Agarian** [comment]
both b and c are 3

**Comment by Andrews54757** [comment]
STOP BEING MEAN TO EACH OTHER!!!
1. @XxRaizerxX I gave power to @LegitSoulja and he has all rights to ban you or do anything. You are sometimes really bad, you spam issues and much more. I know we all have commited the crime of spamming, but you, also go into profanity as @LegitSoulja said. Having issues is not a reason for this. Control yourself and live life as a happy person. Get real friends besides @VSabertail as well as friends are important in life, NOT virtual friends.
2. @LegitSoulja Please, dont insult infiorior people to you, I know it is frustrating but what i do is just suck it up in my head and take a rest. Then I feel better. Control of your mind is very important
3. To all @AJS-development/ogar-unlimited-devs  and all community members. Do not insult each other, spam or insult others who are infiorior. Do not test them with math equations. Trust me, I mess up addition somtimes as well. Always treat others above yourself. Avoid language such as "I told you so" or "oh yeah?" or use profanity. Profanity belongs here #539 against moneyclip only. Thank you for contributing, but just keep this in mind.

**Comment by Andrews54757** [comment]
I am locking this conversation in case of rudeness
