### ISSUE TITLE
'CANNOT GET /' error after creating server.

### ISSUE THREAD

**Issue by darknight99x** [AJS-development/Ogar-unlimited#576]
After using this tutorial: https://github.com/AJS-development/Ogar-unlimited/issues/564
'[Tutorial] How to host your own client in Cloud9 IDE'

No errors in console, but when I try to connect to the IP that was made: 'http://agarboss-darknight99x.c9users.io/'

This appears: 
![capture](https://cloud.githubusercontent.com/assets/19356956/15266592/8026e446-1978-11e6-9a4b-bcb6462b6d62.PNG)

I'm assuming it's an error made by me, as no one else in that tutorial has had this problem.
I thought it could've been a recent update of NodeJS or something.
I have a custom client installed for the server too, as stated in the tutorial.

**Comment by firelightning13** [comment]
you still didnt have the client

**Comment by LegitSoulja** [comment]
You need the client. Since I'm using my phone right now I cannot provide it to you at the moment.

The official client was closed due to us contacting miniclip regarding OgarUL and private server use. One of the dev members or a kind member who has the client could give it to you. Hopefully you would get it soon.

**Comment by LegitSoulja** [comment]
@firelightning13 could you provide him with the client and instructions please since you are on? Thanks

**Comment by darknight99x** [comment]
I have the client in place. 
![capture](https://cloud.githubusercontent.com/assets/19356956/15266609/31f12d4e-1979-11e6-8765-b256576130b3.PNG)

**Comment by darknight99x** [comment]
@LegitSoulja you had a link placed in the comments for it. https://github.com/AJS-development/Ogar-unlimited/files/264302/Agarioclient.1.zip

Is that the correct one?

**Comment by LegitSoulja** [comment]
Hm that is strange. You have the client and followed instructions. Check the file in ./client/main_out and you will see a connection string. Remove that. Just remove what's inside of the quotes. Don't remove the variable itself

**Comment by LegitSoulja** [comment]
Yes, you are correct :)

**Comment by darknight99x** [comment]
Is this correct? haha

![capture](https://cloud.githubusercontent.com/assets/19356956/15266630/cdfb5e3a-1979-11e6-879c-be3a37593756.PNG)

**Comment by LegitSoulja** [comment]
Yes connection_url should not contain a connection string. See if that works. Also right click your src folder and open terminal and type 

> sudo node index

**Comment by darknight99x** [comment]
still no success i'm afraid.

I don't know what I did wrong tbh.
I've re-done this server creation twice with no change

**Comment by darknight99x** [comment]
and it bugs me because no one else seems to be having this issue so it has to be a problem I have done, but I have done trial and error and I can't figure out why it's not reading the client folder.

**Comment by LegitSoulja** [comment]
Please provide one more last screenshot of ./plugins/Client/index.js

**Comment by darknight99x** [comment]
Here you go.
![capture](https://cloud.githubusercontent.com/assets/19356956/15266656/a7da1f88-197a-11e6-9358-f93faf99bcd5.PNG)

**Comment by firelightning13** [comment]
darknight99x its working for me

**Comment by darknight99x** [comment]
@firelightning13 yeah I noticed no one else is having this problem.
I can't troubleshoot this, I have tried everything

**Comment by LegitSoulja** [comment]
The last image you provided did not show a client folder in the src directory by the way

**Comment by LegitSoulja** [comment]
Yea. Normally this issue is because the client. C9 also has a lot of issues aswell. Just to say it's way better to host and port forward on your own. I'm pretty sure your computer operating system is better than c9 free services.

**Comment by darknight99x** [comment]
You have to include the 'https://' !?!?

**Comment by LegitSoulja** [comment]
Yes the client is working fine on my end as well

**Comment by firelightning13** [comment]
yea

**Comment by LegitSoulja** [comment]
No you don't have to include https necessarily. Actually https I think won't work

**Comment by darknight99x** [comment]
Oh my goodness, I apologize

Me and my attention span got to me again
I was using the 1st attempted server link 
'agarboss-darknight99x.c9users.io'
DX
my bad! Thanks though, I probably would've been walking in circles for hours.

**Comment by firelightning13** [comment]
I think i didnt include https in my tutorial. Sry for that D:

**Comment by LegitSoulja** [comment]
@darknight99x oh ok. Well that's good you figured that out. I was getting a little bit confused myself. So issue solved I guess?

**Comment by darknight99x** [comment]
Yep, thanks!

**Comment by firelightning13** [comment]
:+1:

**Comment by LegitSoulja** [comment]
@firelightning13 both http and https works. But https shouldn't really be used because there's no need for ssl. wss uses HTTPS and ws doesn't.

**Comment by firelightning13** [comment]
ok got it

**Comment by LegitSoulja** [comment]
@firelightning13 I don't know. You could be right. Scratch what I said
