### ISSUE TITLE
OMG....

### ISSUE THREAD

**Issue by AirTop** [AJS-development/Ogar-unlimited#577]
http://imgur.com/hFmj6gA
http://imgur.com/hFmj6gA
http://imgur.com/hFmj6gA

**Comment by LegitSoulja** [comment]
npm install request

CD to your directory ./src outside the src folder and enter that command in cmd.

**Comment by LegitSoulja** [comment]
Please read the other issues & closed issues regarding issues like this because this post is duplicate. To risk getting banned please follow the guidelines, do not spam, and make sure no other issues related to your issue exist. Thanks
