### ISSUE TITLE
i created a chat system but i dont know how to make it in game agario

### ISSUE THREAD

**Issue by XxRaizerxX** [AJS-development/Ogar-unlimited#578]
'<?php
// Get username
$user = $_GET['u'];
?>
<html>
<head>
    <title>Agar Chat</title>
	<link rel='stylesheet' type='text/css'/style.css'/>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800
	<script src="//code.jquery.com/jqery-1.11.0.min.js"></script>
	</head>
	<body
	<div class='chatContainer'>
	    <div class='chatHeader'>
		    <h3>Welcome:) <?php echo ucwords ($user); ?></h3>
		</div>
		<div class='chatMessages'></div>
		div class='chatBottom'>
		   <form action'#' OnSubmit='return false;' id='chatForm'>
		       <input type='hidden' id='name'value='<?php echo $user; ?>'/>
			   <input type='text' name='text' id='text' value'' placeholder='Put your message here' />
			   <input type='submit' name='submit value='Post' />
		   </form>
		</div>
	</body>
	</html>'

**Comment by XxRaizerxX** [comment]
i cant upload code

**Comment by XxRaizerxX** [comment]
the rest of it

**Comment by LegitSoulja** [comment]
Wow what?? I could make a chat plugin/server, and a chat extension to the canvas for chat.

**Comment by Agarian** [comment]
can it be possible to use skins from customskins.txt by linking them to the client somehow?

**Comment by firelightning13** [comment]
@LegitSoulja pls make that extension

**Comment by fayizan** [comment]
@LegitSoulja I want the chat system too..Please Make it..
