### ISSUE TITLE
Help me!

### ISSUE THREAD

**Issue by Thibaultt74** [AJS-development/Ogar-unlimited#580]
its how we made ​​to login to the site because http://ajs-development.github.io/client/ puts me a message with a blank page at once how to do it to login to the site that I play with my private server ?

**Comment by Tokoagar** [comment]
The owner is asking moneyclip

**Comment by sukass** [comment]
yes, moneyclip ruins agario. if you still want to connect to your private server you can use my server (http://regario.ddns.net/) and do connect(ws://ip:port) or follow this tut (https://github.com/AJS-development/Ogar-unlimited/issues/564) if you use c9 or not

**Comment by Tokoagar** [comment]
ok

**Comment by Tokoagar** [comment]
Is your server down I can't connect
