### ISSUE TITLE
C9.io error

### ISSUE THREAD

**Issue by XxRaizerxX** [AJS-development/Ogar-unlimited#582]
@Andrews54757 @LegitSoulja 
 
Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at Object.<anonymous> (/home/ubuntu/workspace/src/index.js:33:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
[Error] Server could not bind to port! Please close out of Skype or change 'serverPort' in gameserver.ini to a different number.
OgarUnlimited terminated with code: 1

**Comment by XxRaizerxX** [comment]
i was restarting server and did sudo node index.js and dis showed up  i did not even update or anything or change anything

**Comment by XxRaizerxX** [comment]
#564

**Comment by XxRaizerxX** [comment]
SOMEONE HELP LOL usually they comment like 10 minutes after i make a issue

**Comment by LegitSoulja** [comment]
Fixes
- You must be running another server.
- Port 8080 is occupied.
- Change your port to another port other than 8080
- Make sure you run with sudo w/ permissions

**Comment by LegitSoulja** [comment]
And it does not matter if you have skype on or not. Your not hosting if so skype won't have an issue.

**Comment by XxRaizerxX** [comment]
ok
how do i run it with permissions and i have it on 8081 port

**Comment by LegitSoulja** [comment]
Running with sudo like you did gives you root permissions.

**Comment by XxRaizerxX** [comment]
oh

**Comment by XxRaizerxX** [comment]
i don't know what that means but ok i have already tried those things

**Comment by XxRaizerxX** [comment]
just tell me what i am supposed to do 
becides change ports cause i already did that and it not work+

**Comment by LegitSoulja** [comment]
Right click on src, and open terminal. Input this command
> sudo node index

If that doesn't work, click index.js and right click normally where index.js text editor is, and right click and run, or there should be a run button.

**Comment by LegitSoulja** [comment]
If doesn't work restart your workspace

**Comment by XxRaizerxX** [comment]
i cant click run button it wont let me

**Comment by LegitSoulja** [comment]
Just restart the workspace and try again. I don't know what's wrong with c9. Everyone always have problems with it. I can't tell you much because I don't even use it.

**Comment by XxRaizerxX** [comment]
what will happen if i restart

**Comment by LegitSoulja** [comment]
:/ it's just like restarting your computer.

**Comment by XxRaizerxX** [comment]
oh so it won't hurt anything

**Comment by LegitSoulja** [comment]
No

**Comment by LegitSoulja** [comment]
I wouldn't tell you to restart if so.

**Comment by XxRaizerxX** [comment]
oh it not my c9 server is someone elces i cant do that
:P

**Comment by XxRaizerxX** [comment]
I'm just a member of it

**Comment by LegitSoulja** [comment]
Well I don't know what else to say then

**Comment by XxRaizerxX** [comment]
ok

**Comment by LegitSoulja** [comment]
Changing ports still didn't work?

Change vps to 1

**Comment by XxRaizerxX** [comment]
i even did that

**Comment by XxRaizerxX** [comment]
its firelightnings server
he has another server running i think
i could go to the link of the server i want to run and it goes to the server he has running

**Comment by LegitSoulja** [comment]
So you still got a EADDRINUSE with a different port and while vps is 1? Make it back 0 and just keep going through ports and back and forth from enabling a disabling vps.

**Comment by LegitSoulja** [comment]
That's the problem. Pick a different port range for use

**Comment by XxRaizerxX** [comment]
this happens when i use vps 1  `port` or a `server` must be provided
    at new WebSocketServer (/home/ubuntu/workspace/node_modules/ws/lib/WebSocketServer.js:44:11)
    at GameServer.start (/home/ubuntu/workspace/src/core/GameServer.js:217:25)
    at ControlServer.start (/home/ubuntu/workspace/src/core/ControlServer.js:57:21)
    at Object.<anonymous> (/home/ubuntu/workspace/src/index.js:60:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at Object.<anonymous> (/home/ubuntu/workspace/src/index.js:33:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by LegitSoulja** [comment]
Ok don't. Just keep switching around ports till one works

**Comment by XxRaizerxX** [comment]
8083 works but i go there it goes to the other server running

**Comment by LegitSoulja** [comment]
You need to change the client port too

**Comment by XxRaizerxX** [comment]
where is that

**Comment by LegitSoulja** [comment]
./plugin/Client/index.js or either the config file in the same folder

**Comment by XxRaizerxX** [comment]
i cant change client port ill just wait for firelightning to get on

**Comment by LegitSoulja** [comment]
@firelightning13 @XxRaizerxX okiedookie

**Comment by LegitSoulja** [comment]
And thanks for being nice for once. If your nice to me I will be nice to you.

**Comment by XxRaizerxX** [comment]
ok your welcome

**Comment by firelightning13** [comment]
@LegitSoulja He's running multiple console at once which doesnt support. C9.io is a place where people are really confused very often :P . But i restarted it so it works now

**Comment by AxlorYT** [comment]
I have the same problem as Raizer. I dunno how to fix it and it worked once for me but that's it. The first time I made a private ogar server it worked, and when I closed terminal accidentally to make a new ogar server, it didn't work anymore for some reason. Please help

**Comment by AxlorYT** [comment]
Firelightning please help.

**Comment by ItzLevvie** [comment]
@AxlorYT if you're using C9, then don't use it because you'll get banned. C9 isn't a place to host your servers it's a development platform.

**Comment by firelightning13** [comment]
^^

**Comment by AxlorYT** [comment]
But I am not! I am not using it. I am using a mac, and I used terminal and I have the ogar download, and still it says "Terminated with code 1 please close skype" or blah blah blah. .-.

**Comment by LegitSoulja** [comment]
@AxlorYT disable skype port 443 in skype settings,

make sure you aren't using a port that your computer is already listening on. Im not for sure the exact command to get the netstat of ports that running but you need to make sure there's no interference.
