### ISSUE TITLE
Changing 'splitversion' property in AdvConfig.ini breaks cell collision.

### ISSUE THREAD

**Issue by darknight99x** [AJS-development/Ogar-unlimited#584]
======================================================================================================================================================
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
======================================================================================================================================================
// [Appearance]
// splitversion : If 1, it uses split mech by Megabyte918.
// viruscolorintense : Intensity of the color of the viruses.
// sizeMult : How much bigger you have to be to eat someone, 1.25 is 25%, 1.50 is 50%, etc.
// VsizeMult : How much bigger you have to be to consume a virus, 1.33 is 33%, 1.66 is 66%, etc.
splitversion = 0
viruscolorintense = 10
sizeMult = 1.25
VsizeMult = 1.33
======================================================================================================================================================
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
======================================================================================================================================================

Changing the splitversion to 0, breaks collision in the server. It makes it act as if the cells instantly merge, but in reality they are all under each other.
I'd prefer the old splitting version to the new one.

**Comment by XxRaizerxX** [comment]
lol right when i noticed that for my first time is when you uploaded this thats creepy

**Comment by Agarian** [comment]
I knew this for 2 weeks

**Comment by Andrews54757** [comment]
this is not really a big issue as no one uses the oldsplit

**Comment by Agarian** [comment]
maybe its a good idea abolish that config, what do you have to say about this?

**Comment by Megabyte918** [comment]
Oh yeah :P i guess we never accounted  for anyone to use that splitversion, so we never added a different one... i think its safe to remove it

**Comment by Andrews54757** [comment]
too lazy
