### ISSUE TITLE
Split Speed not working

### ISSUE THREAD

**Issue by XxRaizerxX** [AJS-development/Ogar-unlimited#585]
its not working i can set it to anything no difference try it on your server and try to fix it

**Comment by XxRaizerxX** [comment]
If i have mistaken what split speed is what i think it is is when i split the speed of the split is slo motion when set low and when set high its instant

**Comment by XxRaizerxX** [comment]
@LegitSoulja  @Andrews54757 @Megabyte918  ALL DEVS TELL ME HOW TO FIX or if i am mistaken of it can you make a new config that makes split slo motion and make one fast

**Comment by Andrews54757** [comment]
Fixed
