### ISSUE TITLE
 {  +    "hash": "a15c2229eca15ba2df2439020fb4bc06",  +    "src": "src/modules/commands/garbage.js",  +    "dst": "./modules/commands/garbage.js",  +    "name": "garbage.js"  +  },

### ISSUE THREAD

**Issue by XxRaizerxX** [AJS-development/Ogar-unlimited#587]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?

What version are you on?

What command did you type if any?

You must have a description as well

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

Can you make minions split by pressing E or R key?
A: NO, as agar.io client doesn't support those keys. Otherwise, you would need to use another client, and that is illegal.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

**Comment by LegitSoulja** [comment]
Re-update as ogarul failed to manually update.
