### ISSUE TITLE
error

### ISSUE THREAD

**Issue by XxRaizerxX** [AJS-development/Ogar-unlimited#588]
Error: Cannot find module './commands/garbage.js'

**Comment by XxRaizerxX** [comment]
i have so many errors sorry

**Comment by XxRaizerxX** [comment]
@Andrews54757

**Comment by XxRaizerxX** [comment]
NEVERMIND ILL JUST TRY RESTARTING MY C9.IO OR MAKE A NEW 1 !

**Comment by LegitSoulja** [comment]
@XxRaizerxX You shoud've have provided a full stack trace. That does not help at all with your problem. There's no garbage command, unless its something new to a recent update and the update failed to download garbage.js

**Comment by Andrews54757** [comment]
@LegitSoulja it was my fault. i forgot to include garbage.js

**Comment by LegitSoulja** [comment]
@Andrews54757 Yea, I figured that out. Nice to prevent memory leaks.

**Comment by Megabyte918** [comment]
@Andrew54757 hey this is random, but where did Micheal go? i havent seen him in a while

**Comment by LegitSoulja** [comment]
@Megabyte918 Hobbs? Last time I ever spoke to him he had took his kids to the Docter. That was the last convo I had with him. That was before I was assigned to AJS. He was showing me his OgarMind project but I never got it working
