### ISSUE TITLE
Grid flickering and problem with border

### ISSUE THREAD

**Issue by patrick0888** [AJS-development/Ogar-unlimited#589]
Hello, I got the client working but when I joining the client page the grid is flickering till I start playing.
And when the cell reach the border the screen is flashing and the cell jumps.

Any idea how to fix this?

Thanks allready.

**Comment by HappyRocketwheel** [comment]
does this happen when you run ogar-unlimited or regularly

**Comment by patrick0888** [comment]
yes with ogar-unlimited.

**Comment by Andrews54757** [comment]
its normal

**Comment by Agarian** [comment]
this is caused by the following code in PlayerTracker.js (line 403-423):

    // Map obfuscation
    var width = this.viewBox.width;
    var height = this.viewBox.height;

    if (this.cells.length == 0 && this.gameServer.config.serverScrambleMinimaps >= 1) {
      // Update map, it may have changed
      this.socket.sendPacket(new Packet.SetBorder(
        this.gameServer.config.borderLeft + this.scrambleX,
        this.gameServer.config.borderRight + this.scrambleX,
        this.gameServer.config.borderTop + this.scrambleY,
        this.gameServer.config.borderBottom + this.scrambleY
      ));
    } else {
      // Send a border packet to fake the map size
      this.socket.sendPacket(new Packet.SetBorder(
       Math.max(this.centerPos.x + this.scrambleX - width, this.gameServer.config.borderLeft + this.scrambleX),
            Math.min(this.centerPos.x + this.scrambleX + width, this.gameServer.config.borderRight + this.scrambleX),
            Math.max(this.centerPos.y + this.scrambleY - height, this.gameServer.config.borderTop + this.scrambleY),
            Math.min(this.centerPos.y + this.scrambleY + height, this.gameServer.config.borderBottom + this.scrambleY)
      ));
    }

remove it and ur good :D

**Comment by patrick0888** [comment]
@Agarian Thanks! Fixed it 👍
