### ISSUE TITLE
UnlimitFFA broken

### ISSUE THREAD

**Issue by darknight99x** [AJS-development/Ogar-unlimited#590]
Once you get big enough, you cant split out/
you just instantly combine with the same cell you split out of

**Comment by darknight99x** [comment]
nevermind

**Comment by Agarian** [comment]
no it still happens. don't know why =\

**Comment by darknight99x** [comment]
@Agarian if you set Recombinetime to 0
it will be a temp fix

**Comment by darknight99x** [comment]
@Agarian I got it working here
https://cellzen-darknight99x-2.c9users.io/

**Comment by Agarian** [comment]
"Not authorized to access this private project."

**Comment by firelightning13** [comment]
Its was happened because of the "working popsplit" code that was made by retslac. You could try to revert back(?)

nvm close?

**Comment by Megabyte918** [comment]
@firelightning13 is right, idk why it happens tho :P
