### ISSUE TITLE
Blank Grid Screen

### ISSUE THREAD

**Issue by Ejali2020** [AJS-development/Ogar-unlimited#591]
Everytime I start the console and go on agario my blob flashes and i can't move. I also encountered just a blank grid screen and that's it. Please help. thanks in adv

**Comment by darknight99x** [comment]
was it ever working properly before or was this your first time running the server?

**Comment by Ejali2020** [comment]
first time running the server

**Comment by darknight99x** [comment]
Hmm... nobody else has had this issue.
It could be a problem with the NodeJS version you are running.
Try updating it to the latest version.

If that doesn't fix the issue, then you may want to re-do creating your server,

**Comment by professionalShit** [comment]
I've the same issue. This is not related with NodeJS version, because after the connection, typing 'playerlist' on console shows player as DEAD/NOT IN GAME, and after a 'killall' it says the server removed a cell. I think is a packet error, maybe?

**Comment by problemsofworld** [comment]
change js of update nodes to this 
function UpdateNodes(destroyQueue, nodes, nonVisibleNodes, scrambleX, scrambleY) {
  this.destroyQueue = destroyQueue;
  this.nodes = nodes;
  this.nonVisibleNodes = nonVisibleNodes;
  this.scrambleX = scrambleX;
  this.scrambleY = scrambleY;
}

module.exports = UpdateNodes;

UpdateNodes.prototype.build = function () {
  // Calculate nodes sub packet size before making the data view
  var nodesLength = 0;
  for (var i = 0; i < this.nodes.length; i++) {
    var node = this.nodes[i];

    if (typeof node == "undefined") {
      continue;
    }

    /////        nodesLength = nodesLength + 20 + (node.getName().length * 2);
    /////
    nodesLength = nodesLength + 21 + (node.getName().length * 2) + node.getPremium().length;
    /////
  }

  var buf = new ArrayBuffer(3 + (this.destroyQueue.length * 12) + (this.nonVisibleNodes.length * 4) + nodesLength + 8);
  var view = new DataView(buf);

  view.setUint8(0, 16, true); // Packet ID
  view.setUint16(1, this.destroyQueue.length, true); // Nodes to be destroyed

  var offset = 3;
  for (var i = 0; i < this.destroyQueue.length; i++) {
    var node = this.destroyQueue[i];

    if (!node) {
      continue;
    }

    var killer = 0;
    if (node.getKiller()) {
      killer = node.getKiller().nodeId;
    }

    view.setUint32(offset, killer, true); // Killer ID
    view.setUint32(offset + 4, node.nodeId, true); // Node ID

    offset += 8;
  }

  for (var i = 0; i < this.nodes.length; i++) {
    var node = this.nodes[i];

    if (typeof node == "undefined") {
      continue;
    }

    view.setUint32(offset, node.nodeId, true); // Node ID
    view.setInt32(offset + 4, node.position.x + this.scrambleX, true); // X position
    view.setInt32(offset + 8, node.position.y + this.scrambleY, true); // Y position
    view.setUint16(offset + 12, node.getSize(), true); // Mass formula: Radius (size) = (mass * mass) / 100
    view.setUint8(offset + 14, node.color.r); // Color (R)
    view.setUint8(offset + 15, node.color.g); // Color (G)
    view.setUint8(offset + 16, node.color.b); // Color (B)
    /////view.setUint8(offset + 17, node.spiked, true); // Flags
    /////
    view.setUint8(offset + 17, (node.spiked | 4)); // Flags
    /////
    offset += 18;

    /////
    var skin = node.getPremium();
    if (skin) {
      for (var j = 0; j < skin.length; j++) {
        var c = skin.charCodeAt(j);
        if (c) {
          view.setUint8(offset, c);
        }
        offset++;
      }
    }
    view.setUint8(offset, 0); // End of string
    offset++;
    /////

    var name = node.getName();

    if (name) {
      for (var j = 0; j < name.length; j++) {
        var c = name.charCodeAt(j);
        if (c) {
          view.setUint16(offset, c, true);
        }
        offset += 2;
      }
    }

    view.setUint16(offset, 0, true); // End of string
    offset += 2;
  }

  var len = this.nonVisibleNodes.length + this.destroyQueue.length;
  view.setUint32(offset, 0, true); // End
  view.setUint32(offset + 4, len, true); // # of non-visible nodes to destroy

  offset += 8;

  // Destroy queue + nonvisible nodes
  for (var i = 0; i < this.destroyQueue.length; i++) {
    var node = this.destroyQueue[i];

    if (!node) {
      continue;
    }

    view.setUint32(offset, node.nodeId, true);
    offset += 4;
  }
  for (var i = 0; i < this.nonVisibleNodes.length; i++) {
    var node = this.nonVisibleNodes[i];

    if (!node) {
      continue;
    }

    view.setUint32(offset, node.nodeId, true);
    offset += 4;
  }

  return buf;
};

**Comment by PrinceDark9243** [comment]
wow dude i dont unterstand that code lol

**Comment by Agarian** [comment]
Thats UpdateNodes.js

**Comment by LegitSoulja** [comment]
And what you just gave will give errors.. That won't fix anything. Plus the skin code was commented out for a reason. There's a config where if you are using a custom client or not, disable it then use the extension. Don't even bother messing with updatenodes

**Comment by paulo364gamer** [comment]
I have the same problem can someone make a tutorial?

**Comment by LegitSoulja** [comment]
@paulo364gamer use this

http://cl.agariohub.tk/?ip=localhost:443

**Comment by LegitSoulja** [comment]
@darknight99x What client where you using? and @problemsofworld you just can't say that if he's using another client. There's a config setting that if you are specificly is or not using a custom client, you need to change. Therefor if you are using an extension, and connection through agar.io then that's on the extension behalf, and you need to disable custom client use.

**Comment by tommyb008** [comment]
DUPLICATED THREAD https://github.com/AJS-development/Ogar-unlimited/issues/558

**Comment by tommyb008** [comment]
Or not i just had the same problem...

**Comment by professionalShit** [comment]
There is no a method to fix is for the official Agar.io client? Or is required the 5.9.1 of nodeJS?

**Comment by Agarian** [comment]
5.9.0 or 5.9.1 required for now.

**Comment by Agarian** [comment]
5.9.1 is recommended

**Comment by GOpb** [comment]
still having the blank screen problem even on the http://cl.agariohub.tk/?ip=localhost:443

**Comment by LegitSoulja** [comment]
@GOpb http://cl.agariohub.tk/?ip=localhost:443&method=ws
