### ISSUE TITLE
how do i update?

### ISSUE THREAD

**Issue by iIronicGameryt** [AJS-development/Ogar-unlimited#594]
what is the command to update?

**Comment by darknight99x** [comment]
In config,ini, 

Look for `autoupdate`

Change it to 1, restart your server, it will update any necessary files.

**Comment by Agarian** [comment]
its better to do the command "update all"

**Comment by Andrews54757** [comment]
yeah, do what agarian said

**Comment by Andrews54757** [comment]
the update command was introduced to let people easily keep up with the many updates that ogarul has. but it is still not perfect though and preformance of update depends on your connection and etc
