### ISSUE TITLE
HELP ME!!!!

### ISSUE THREAD

**Issue by AirTop** [AJS-development/Ogar-unlimited#599]
When I go to the server, nothing happens. - http://imgur.com/MpFCSFa
What to do? Help please, I want to play!

**Comment by Peppyrotom** [comment]
Maybe its happen because you using an extension. Try disable it.

**Comment by AGPS153** [comment]
VM787:1 Uncaught ReferenceError: connect is not defined(…)

**Comment by AGPS153** [comment]
I want to play whenever I get VM787 : 1 Uncaught ReferenceError : connect is not defined ( ...): c help please update want to play when I get that and if you do not update a shit help plss

**Comment by iIronicGameryt** [comment]
you need a extension to connect as moneyclip ruined the game

**Comment by AGPS153** [comment]
you have an extention of ip if you have pls raisins me ?

**Comment by AGPS153** [comment]
I now everything goes black
