### ISSUE TITLE
Split problem

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#6]
When i hit a virus the cells will exit from the master cell (the biggest) go to coordinates 0,0 and the master cell not go to 0,0 (I'M NOT USING OP) and this happen with 22500 autosplit

**Comment by Andrews54757** [comment]
Il investigate

**Comment by Andrews54757** [comment]
Does this happen in normal Ogar?

**Comment by Andrews54757** [comment]
I found out the problem. Will fix asap

**Comment by Lukkez** [comment]
Not happen on normal agar.io

**Comment by Andrews54757** [comment]
I fixed it
