### ISSUE TITLE
I'm problems help

### ISSUE THREAD

**Issue by paulo364gamer** [AJS-development/Ogar-unlimited#601]
hello I am Brazilian and I have a problem when connecting to the server, I tested on 2 browser and did not work, I searched the site and found nothing with this problem, and I am with the updated ogar, and Node.js also, when I press play of these http://imgur.com/oI8xVpo http://imgur.com/w5H5jhh problems, and tried to use the connect("ws://127.0.0.1:443") and gave this problem http: // imgur .com / di5sx5v http://imgur.com/0g5i2Lr, here is the print of http://imgur.com/N2arvpP console

**Comment by iIronicGameryt** [comment]
you need a extension as moneyclip fucked us over

**Comment by LegitSoulja** [comment]
Use an extension, or get a hold of the client files

**Comment by paulo364gamer** [comment]
He gave the same problem # 591 using http://imgur.com/Q0n8iYq extent what can I do? I am new in this negoço of Node.js
