### ISSUE TITLE
How do i use custom skins?

### ISSUE THREAD

**Issue by iIronicGameryt** [AJS-development/Ogar-unlimited#602]
i have read the readme and read the instructions for the custom skins but i can get it to work i cant understand the format can someone send me a screenshot of how you do it? like the format :)

**Comment by Agarian** [comment]
This feature is currently broken until it is implemented into the official ogarUL client.

**Comment by LegitSoulja** [comment]
@Agarian it's not broke, it was removed, and not implemented into the client.

**Comment by Agarian** [comment]
im talking about custom skins
