### ISSUE TITLE
Error eveytime help somebody:(

### ISSUE THREAD

**Issue by Kappa0Kappa** [AJS-development/Ogar-unlimited#603]
Please help i get this error all the time idk what to do :( i have node.js version 5.9.1 http://prntscr.com/b4d22z what to do ?

**Comment by LegitSoulja** [comment]
Duplicated post. Please check other issues before making posts like this.

To fix this simply run this command in cmd prior to your outside folder **./src** of the game server 

> npm install request

**Comment by Kappa0Kappa** [comment]
basicaly i'm a noob at this :p sorry but are u saying ii should open cmd promt and type'' ./src '' ?

**Comment by LegitSoulja** [comment]
Go into your game folder, but now where the game files are but outside of the ./src folder.

Copy the directory path above.

Open cmd and type **cd (right click paste)**

Then type **npm install request**

**Comment by Kappa0Kappa** [comment]
these are all the files and stuff i see.. http://prntscr.com/b4dbm1 which one should i click ?

**Comment by LegitSoulja** [comment]
@Kappa0Kappa You are in the wrong folder.. Go outside of **./src** where you see the folder node_modules, and the src folder, and a few other files..

Copy that path directory to that specific folder.

Open cmd and type cd (right click paste)

Then type npm install request

**Comment by Kappa0Kappa** [comment]
Mine telling which one ? http://prntscr.com/b4dfta i am outside of src file now what to do

**Comment by LegitSoulja** [comment]
@Kappa0Kappa Copy that path directory to that specific folder.

**Comment by LegitSoulja** [comment]
For example, Mines would look like this.

@Kappa0Kappa For example.

C:\Users\LegitSoulja\Desktop\Ogar-unlimited-master

Yours will not be the same after you copied the directory path. Once you click at the top, where it normally would say what folder your currently in you want to click there and copy the directory path..

Once you copy that, open cmd and type in the command
> **cd C:\Users\LegitSoulja\Desktop\Ogar-unlimited-master**
then
> **npm install request**

**Comment by Kappa0Kappa** [comment]
lool thats what i was asking bro.. ok so it install and stopped here http://prntscr.com/b4dn8y what to do now?

**Comment by LegitSoulja** [comment]
@Kappa0Kappa I just said what you had to do after that.

**Comment by Kappa0Kappa** [comment]
exactly i did the directory path and npm install request thing and it stopped here http://prntscr.com/b4dpcs so i am asking what should i do now ..

**Comment by LegitSoulja** [comment]
I'm gonna repeat myself one last time okay

@Kappa0Kappa For example, Mines would look like this.

**C:\Users\LegitSoulja\Desktop\Ogar-unlimited-master**

Yours will not be the same after you copied the directory path. Once you click at the top, where it normally would say what folder your currently in you want to click there and copy the directory path..

Once you copy that, open cmd and type in the command
> **cd (Right click paste)** **YOU DID THIS**
then
> **npm install request** **YOU DID THIS**

Than after that, when its done, start the game like normal. **NOW DO THIS**

**Comment by LegitSoulja** [comment]
Whats the last thing I said?

**Comment by LegitSoulja** [comment]
If you don't know how to start the game how did you start it last time?? Have you followed the installation instructions?

go inside the src folder, and run the start.bat file.

**Comment by Kappa0Kappa** [comment]
you explained the first step to me and i completed it :( i didnt close the cmd promt so i still have it open... the last thing u said it go to the game which is ''agar.io''

**Comment by LegitSoulja** [comment]
@Kappa0Kappa I didn't say go to the game, I said start the game.

**Comment by Kappa0Kappa** [comment]
exactly...... http://prntscr.com/b4dtqo i get same error  after installing the stuff in cmd and i install independencies and click ''start '' which is the batch file andd i get that error still so thats why i asked what else to do

**Comment by LegitSoulja** [comment]
go back to the main folder again where you seen the folder **src** and **node_modules**.

Delete the node_modules folder
Download this https://github.com/AJS-development/nodemodules
Replace the delete folder with the new folder that you downloaded
Then start the game again.

You should not have any problems afterwards.

**Comment by Kappa0Kappa** [comment]
Thanks i will do as u say and let u know the result :(

**Comment by LegitSoulja** [comment]
@Kappa0Kappa okay, I will be here.

**Comment by Andrews54757** [comment]
@Kappa0Kappa do not make a duplicate post anymore as it says In the guidelines, duplicate makers will be banned

**Comment by Kappa0Kappa** [comment]
u mean i shouldnt have more than one node modules in the game ffolder?

**Comment by Kappa0Kappa** [comment]
ok i deleted the old node :( downoad the new one and put it in the game folder no i have the new node module that u sent and the other files are still the same and i still get same error :(

**Comment by LegitSoulja** [comment]
@Kappa0Kappa By running the install_dependecies.bat file could fix your problem.. Probably.. Try that and tell me if it still does the same thing.

**Comment by Kappa0Kappa** [comment]
already did like a million times :(

**Comment by Kappa0Kappa** [comment]
i am going to extract the file and try again and let u know ok :/

**Comment by LegitSoulja** [comment]
@Kappa0Kappa I did not say extract again. What's the purpose of doing it again when it doesnt work?

**Comment by Kappa0Kappa** [comment]
exactly it doesnt :( i give up :( i because it doesnt work maybe for me only

**Comment by Kappa0Kappa** [comment]
but it doesnt work for me bro :(
