### ISSUE TITLE
Im curious "question"

### ISSUE THREAD

**Issue by tommyb008** [AJS-development/Ogar-unlimited#604]
What is the best way to learn agarios api and javascript escpessialy for agario? Sorry if this is duplicated.

**Comment by Andrews54757** [comment]
exactly what you say. in google, search agario reverse engineering and look at the code. then go to codeacademy and learn javascript and html

**Comment by Agarian** [comment]
for the courtesy of others, can you please re-activate the client instead of forcing others to download the client separately?

**Comment by Andrews54757** [comment]
no. its that its not buisness hours
