### ISSUE TITLE
Is there a server tracker for OgUn?

### ISSUE THREAD

**Issue by EnTerr** [AJS-development/Ogar-unlimited#606]
I saw OgarServ has a fantastic feature - server tracker, in which each independently run server registers with a "mothership", central repository. That website in turn assembles a master list (http://ogar.mivabe.nl/master in their case), where one can go and choose a server to play on. The list includes game mode, geo location hint, plus some health metrics (how many clients, uptime, when last heard from...)

This way it creates a network, a "community" of servers if you will. It's not as centralized as the tight orchestration Agar.io runs - but then again Agar.io *owns* the servers. Still, i think there is a benefit of "indie" servers being listed in a central catalog, while being free to run their servers with whatever config params they damn well please

**Comment by tommyb008** [comment]
Mabey. If not well ask them to add that as a plugin!

**Comment by LegitSoulja** [comment]
@tommyb008 it would not be a plugin, and since we finally got a site, this could be a thing. But most people locally run servers, and it will be against people privacy to steal there ip and post it on a site for everyone to see. There's major security risks.

For this to happen, the person who uses ogarul will have to accept the use of there server stats to be tracked. OR, users are able to submit there own server to a database.

**Comment by EnTerr** [comment]
@LegitSoulja - i think you are overestimating the privacy implications of listing a server. If one is running a server on a local LAN, because of NAT/firewall it would be unreachable from outside => end of worries. To be reachable, one has to port-forward (puncture hole in fw), a deliberate act.

IMO _by default_ a server should list itself in global catalog, with a config feature to "opt out" from that (either completely or somebody cares, partially - like hide IP). Most hosts would want to bring foot traffic to their server. Read that as in cannon-fodder/"fresh fish" - more human players. The great thing about Agario is it is played by humans. 1 person per server or against N bots is no fun.

**Comment by LegitSoulja** [comment]
@EnTerr Yea, I know localhost wouldn't have a NAT/Firewall open for connections of clients, but still the host will still be obtainable and not kept safe and was taken ignoring people privacy.

I am currently in the process of developing this. If someone is interested they can just install the plugin, and the statistics will be registered and collected. Also server side web for displaying, and getting connections stats, connection links, uptime percent, life percent, and players daily. More will be added in  the future.

**Comment by LegitSoulja** [comment]
Planning: https://github.com/AJS-development/OgarUL-Plugin-Library/issues/6

**Comment by Andrews54757** [comment]
yeah. it would be a plugin but I dont support it as it invades your privacy. When I first found out about the tracker on my ogarserv, I was shocked and I deleted it and reset my ip immediatly

**Comment by EnTerr** [comment]
@Andrews54757 you **as a server** owner don't have to use it. The idea is to build a "co-op" network of servers that can grow in popularity as alternative to agar.io. So that people go to a single web page and select server withe the features they like to play - or a load-balancer like http://m.agar.io/findServer can hand them automatically a server "as appropriate" in some sense (geo-loc, ping, etc)

**Comment by Andrews54757** [comment]
@EnTerr I have my reasons. I dont expect success, and it just suprised me of the success of this project. I still oppose the idea of a masterserver without your knowledge. I mean, we also have a server showcase area. But do people really post their servers? no not really as most dont want their servers out in the public. Remember, this is a private server software. also if they do want it, they could either 

1. use the plugin
2. post server in the server showcase

**Comment by EnTerr** [comment]
Ok, maybe i should disclose more on my bias - like, more openly. I write agario client for exotic device (think smart TV / set-top box) - something with no HTML/JS support and low resources (slow CPU/GPU, little RAM). It's getting good traction and what i want are reliable servers it can connect to. But then MiniClit keeps breaking protocol with unpublished/undocumented changes - and reverse engineering sucks, since no source.

No, i am not interested in running my own isolated server farm for a few reasons:
- First, my hands are already full as-is (yes, i had to write the client from scratch, no JS script modding). 
- Second, i appreciate the advances in server behavior that do happen and improve the game w/o changes in client - one such example is when MC introduced "coordinate scrambling" per client to disrupt bots (i.e. when each client to same server is given different coord system, plus frequent World Size 64 packet reporting nearby walls) - my client worked "magically"
- Third, i like the idea of variety of "worlds" where hosts configure their own servers under slightly different "physical laws", so for players game can be different based on their "luck" connecting
- Fourth, i bring players to the table and would like to face them against other players, from different platforms. This is the kind of thing that benefits non-linearly from addition, i.e. the summary result is better than the sum of results.

**Comment by Barbosik** [comment]
I can suggest an idea from another game. We can setup several master servers. And add some code into ogar, so it will automatically register self on master servers. And master server check the server and take it in the list while it is still available. It should be optional. 
In such way all private servers will be automatically visible for any player.
What do you think?
