### ISSUE TITLE
nodejs keep lag server Help!

### ISSUE THREAD

**Issue by eevaqueen** [AJS-development/Ogar-unlimited#607]
Hello,
I have problem with nodejs,it cause high cpu every 20sec also I dont know the reason for that screenshot
http://prnt.sc/b4g9va
any idea how to fix it?
I use linux ubuntu.
Thank you

**Comment by professionalShit** [comment]
Which node version?

Try 'sudo apt-get update' & 'sudo apt-get upgrade' to load latest libs, but I'm not sure this is the problem. On my Ubuntu 12.04 512MB/DDR3 Ram works fine.

**Comment by LegitSoulja** [comment]
Is the cpu a steady increase?

**Comment by Andrews54757** [comment]
if you have the latest version, run using `sudo node --expose-gc index.js` then if you do the `garbage 0` command, it will run garbage collection. To set at an interval, do `garbage [timeinminutes] true`

**Comment by fayizan** [comment]
how to run garbage in windows,becoz it showing error for me
![screenshot_14](https://cloud.githubusercontent.com/assets/19163419/15301681/92c4f5ce-1bcc-11e6-8de8-40d13ab16c26.jpg)

**Comment by Andrews54757** [comment]
did you start the server using `sudo node --expose-gc index.js?

**Comment by fayizan** [comment]
where should I add this code, to the start.bat file..?

**Comment by LegitSoulja** [comment]
@fayizan Yea, you could
