### ISSUE TITLE
suggestion !

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#608]
can be there a pulgin for adding minion for three players at once and every 5 min it will go to new players and keep do the same thing so all players can have minion without cheating and getting balance for every1 i may have a server with a lot of players I tried to add it my self but i failed am still trying tho hope you can help . `mathing` ramdony for all players picking 3  players add give then an amount of minion  every 5 min then repeating  ` srry for adding  this suggestion if you dont like it .

**Comment by problemsofworld** [comment]
or at least tell how to do it my self

**Comment by LegitSoulja** [comment]
@problemsofworld you can create an easy system to do that. Do you know javascript at all?

**Comment by problemsofworld** [comment]
alot of players on my server they all ask for bots   I know a bit of javascripte

**Comment by LegitSoulja** [comment]
It wont be hard to right a script for that. Or plugin. Just grab the gameServer and just look at gameserver.js and look at what things that are obtainable.

Look at the example plugin
https://github.com/AJS-development/OgarUL-Plugin-Library/tree/master/example-plugin

**Comment by problemsofworld** [comment]
I saw srry am good programmer but very new to scripte and codes :( i dont know how to use it thanks anyway I will try :'(

**Comment by LegitSoulja** [comment]
@problemsofworld I mean, thats if you want to do it yourself.

**Comment by problemsofworld** [comment]
can you help me plz you good coder I dont even have any idea how to this

**Comment by Agarian** [comment]
suggestions should go in #510

**Comment by LegitSoulja** [comment]
@Agarian Im making this for him, @problemsofworld be done in a sec.

**Comment by LegitSoulja** [comment]
@problemsofworld do you want bots to get minions too?

**Comment by LegitSoulja** [comment]
@problemsofworld 
[GiveMeMinions.zip](https://github.com/AJS-development/Ogar-unlimited/files/265439/GiveMeMinions.zip)

You might experience some problems. Let me know if you do. I just threw this together. 
*This is not an official plugin

I'm going to bring out another release soon with bot, and minion detections so bots wont get the minions. I thought you might wanted this in advanced. I will be working on this more.

**Comment by LegitSoulja** [comment]
@problemsofworld check out the configration file too.

**Comment by LegitSoulja** [comment]
Update, this stops bots from getting minions
[GiveMeMinions.zip](https://github.com/AJS-development/Ogar-unlimited/files/265453/GiveMeMinions.zip)

**Comment by LegitSoulja** [comment]
@Andrews54757 you could make this better if you want. Console logging with the commands might get annoying. I was too lazy to not have them output.

I don't think this should be a plugin unless this post gets 10 thumbs up lol

**Comment by LegitSoulja** [comment]
Remove **this.stop = true;** at the bottom. I forgot about it. Line 124

**Comment by problemsofworld** [comment]
@LegitSoulja  wow I love u thx 10000 times for u :)

**Comment by LegitSoulja** [comment]
@problemsofwold I'll release a better one soon. Have you had any bugs? I just need to beware

**Comment by problemsofworld** [comment]
no bugs it's perfect

**Comment by LegitSoulja** [comment]
Ok I'm adding more options like how many people can get minions per time, enable bots to get minions, colorful rainbow minions, getting ride of the console trash it leaves behind because I was too lazy to go around doing this, and a minion cool down if someone mass is huge and receive minions more than 2-3 times in a row.

**Comment by problemsofworld** [comment]
Wow cool add random skins for minions ,

**Comment by LegitSoulja** [comment]
@problemsofworld hmmm, maybe.

**Comment by Martinali12** [comment]
@LegitSoulja  @problemsofworld   I installed plugin minions don't even spawn automatically !!

**Comment by LegitSoulja** [comment]
@Martinali12 Hey, Sorry. I just updated it not to long ago with something fresh. Remove GiveMeMinions from the plugin folder run the game and for the command to install
> plugin install GiveMeMinions

**Comment by Martinali12** [comment]
testing :D

**Comment by Martinali12** [comment]
OMFG it worked wow thx dude :DDDDDD

**Comment by LegitSoulja** [comment]
@Martinali12 check the configuration in ./plugin/GiveMeMinions/config.ini

**Comment by Martinali12** [comment]
is there duplicate  to give to players

**Comment by LegitSoulja** [comment]
@Martinali12 what?

**Comment by Martinali12** [comment]
I tought there duplicate but nah its very good

**Comment by LegitSoulja** [comment]
@Martinali12 I have a config set setPerInterval for how many players will get minions ever switchIntervalTime. But it doesnt work, and only does 1 person. I dont know its weird. @Andrews54757 can you look at it?

**Comment by Martinali12** [comment]
@LegitSoulja  when I changed time to more than 6000ms it dont work I dont know why

**Comment by LegitSoulja** [comment]
@Martinali12 when you set it, you have to wait a minute then before the minions are selected.

**Comment by Martinali12** [comment]
Ya i wait but same when once I change time it will not work I waited alot but no bots

**Comment by LegitSoulja** [comment]
@Martinali12 ok i see now, the config isnt taking effect.

**Comment by LegitSoulja** [comment]
Just change line 16 in index.js **switchIntervalTime: 10000**

**Comment by Martinali12** [comment]
now it goes to 4 players at same time i think it was this     setPerInterval: 1 I notice that `,` was miseed

**Comment by LegitSoulja** [comment]
@Martinali12 yea, because the config file is not updating.

**Comment by LegitSoulja** [comment]
just change
```
this.config = {
    
    switchIntervalTime: 10000, // Every Minute
    minionGiveAmount: 10,
    botGetMinions: 1, // 0 = false, 1 = true
    setPerInterval: 1

    
};
```

instead of the config, I have to go soon

**Comment by Martinali12** [comment]
ok

**Comment by Martinali12** [comment]
6000ms = 0.1 min that the problem

**Comment by Martinali12** [comment]
nvm worked thx

**Comment by Martinali12** [comment]
sometimes give back to person without give to another person

**Comment by LegitSoulja** [comment]
@Martinali12 I was adding that, then I had problems and removed it and forgot to add that back. :/

**Comment by Martinali12** [comment]
system is amazing :)

**Comment by Martinali12** [comment]
I cloned two plugin giveminions1 then giveminions2 and it worked that way now it pick 2 guys each time

**Comment by LegitSoulja** [comment]
@Martinali12 LOL. I guess more than one instance can work haha
