### ISSUE TITLE
"packetversion" handling of "set target" pkg not robust

### ISSUE THREAD

**Issue by EnTerr** [AJS-development/Ogar-unlimited#610]
recently added feature of "packetversion", the handling of "mouse" packet (client 16) is somewhat silly - it checks both the size of the packet AND `packetversion`:
https://github.com/AJS-development/Ogar-unlimited/blob/6b5ee6512375a89a586ffb54cc51bf63833b4e1b/src/core/PacketHandler.js#L78

Then question is, what happens if one of the two is wrong, i.e. they disaggree? The result now is, packet will be ignored. Better solution: just check and act upon `byteLength` here, nvm `packetversion`

**Comment by LegitSoulja** [comment]
I'll keep that in mind, but everything been working fine. If the argument returns false nothing will happen. 

packet version is in the config. Whether or not your using a custom client, that has to be changed.

**Comment by EnTerr** [comment]
LOL... "everything works fine, till it stops working", now that's some thinking!

You **didn't even read** the whole piece of code before closing, did you?! Why do i have to explain like to little kids? There are 4 cases:
- "post-July 2015" client (view.byteLength == 13) with server set to "contemporary" protocol (gameServer.config.packetversion != 1) = **good**, works
- "pre-July 2015" client (view.byteLength == 21) with server set to "ancient" protocol (gameServer.config.packetversion == 1) = **good**, works
- "post-July 2015" client (view.byteLength == 13) with server set to "ancient" protocol (gameServer.config.packetversion == 1) = **bad**, movement ignored
- "pre-July 2015" client (view.byteLength == 21) with server set to "contemporary" protocol (gameServer.config.packetversion != 1) = **bad**, movement ignored

Of course said code can get a 
"![works on my machine](http://blog.codinghorror.com/content/images/uploads/2007/03/6a0120a85dcdae970b0128776ff992970c-pi.png)" approval stamp. The question is what happens when disparate versions of client and server communicate?

**Comment by Andrews54757** [comment]
i will test using the new opt-in feature. I will try to resolve this
