### ISSUE TITLE
How To Connect ?!

### ISSUE THREAD

**Issue by NoorAgario** [AJS-development/Ogar-unlimited#611]
Since MiniClip Disabled connecting to a private server (that what I know)
And Andrews Closed his client , how can I connect to my server ?
also I don't wanna make my own client 
Sorry for my bad English ^_^

**Comment by PrinceDark9243** [comment]
hi @NoorAgario  ^_^

**Comment by PrinceDark9243** [comment]
use bagar.io extension then go to this `agar.io/?ip=<Your IP>:<Port>` and you will get into your server

**Comment by NoorAgario** [comment]
can this get me banned from agario  I am level 56 and I don't wanna lose the account ?! I thought they ban people who use extensions

**Comment by LegitSoulja** [comment]
@NoorAgario

http://cl.agariohub.tk/?ip=

After = enter your game server connection ip:port

**Comment by PrinceDark9243** [comment]
@NoorAgario they dont ban you because you are not in real agar.io server you are in your server they cant get the info form your server

**Comment by Andrews54757** [comment]
@PrinceDark9243 They can ban you because their client detects if you are using extensions. As long as your logged out its okay
