### ISSUE TITLE
there's bug when I hint virus , it kind crash for less than second 

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#612]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?

What version are you on?

What command did you type if any?

You must have a description as well

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

Can you make minions split by pressing E or R key?
A: NO, as agar.io client doesn't support those keys. Otherwise, you would need to use another client, and that is illegal.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

**Comment by problemsofworld** [comment]
am using  v 16.5.0 sorry but there's real bug

**Comment by LegitSoulja** [comment]
@problemsofworld op virus? or a normal virus? comon man you have to be more specific.

**Comment by problemsofworld** [comment]
normal virus

**Comment by problemsofworld** [comment]
sorry I want feel like it's like normal agar.io when I hint virus .

**Comment by LegitSoulja** [comment]
@problemsofworld I'll take a look at it.

**Comment by problemsofworld** [comment]
thxs

**Comment by LegitSoulja** [comment]
@problemsofworld what is your definition of crash?

**Comment by LegitSoulja** [comment]
You said it crashed for a second. 
- This could also be a lag/fallback issue where the client is catching up with your other cells if there's alot of players. Normaly caused from your server specs if it can handle the packets quick. I do agree ogarul needs a little bit more of optimization aswell.

**Comment by problemsofworld** [comment]
yep that's what I meant hope u fix it guys

**Comment by Andrews54757** [comment]
@problemsofworld That was the last straw.


OFFENSE:
> For not following the guideline (not putting description, not providing details and more)


Today I hereby declare you BANNED from ogarUL for 1 week
> Banned on May 16. Will be appeased on May 23

**Comment by Agarian** [comment]
Welp he deleted his comments and account

**Comment by Agarian** [comment]
Where was the offensive comment? He may have deleted em =/
