### ISSUE TITLE
Server is not workin anymore ?

### ISSUE THREAD

**Issue by bangana** [AJS-development/Ogar-unlimited#613]
Im wondering if the problem is my server or something else because my server was workin just fine and today i can't spawn,keep seeing white grid ...

**Comment by LegitSoulja** [comment]
@bangana there's been browser issues lately. Chrome works for me, and it's been working for me and I never had problems.

On the other hand, you should try firefox, or even edge maybe. Clear your browser cache for a specific domain to get rid of old cached client files. It could might just work.

**Comment by NovaAgars** [comment]
my server isnt work i get a blank grid all time and connecting

**Comment by NovaAgars** [comment]
and i cant spawn :(

**Comment by bangana** [comment]
Yep @NovaAgars me 2 @LegitSoulja i did all of that ,same bland grid ..... :'(

**Comment by fayizan** [comment]
what version of node.js you guys have..?

**Comment by bangana** [comment]
5.9.0

**Comment by LegitSoulja** [comment]
@bangana idk, sometimes it works, and sometime it doesnt. 

Try https connecting.

**Comment by bangana** [comment]
i did also i updated nodejs and OgarUL still not working

**Comment by bangana** [comment]
umm btw i get this unusual error 
cfafad:~/workspace $ cd src
fafad:~/workspace/src $ sudo node index
Loading Config Files...
Loading ./settings/advConfig.ini
Loading ./settings/config.ini
Loading ./settings/override.ini
Spmk8lS
[Console] Loading plugins
[Console] loaded plugin: Client Implementation By Andrews54757 version 1.1.0
[Console] Failed to load pluginfile README.md Reason: Error: Cannot find module '../plugins/README.md/index.js'
Garbage collection unavailable.  Pass --expose-gc when launching node to enable garbage collection.(memory leak)
[Downloading] http://raw.githubusercontent.com/AJS-development/Ogar-unlimited/master/src/files.json to: filesTemp.json
[Client] Listening on *:8080
Uniban loaded
>Starting ConsoleService

**Comment by fayizan** [comment]
more info come to skype  fayizbe

**Comment by bangana** [comment]
*.* Fixed Thanks the hall problem was port i didn't rly change it but what ever it was 8080 i changed to 8081 and it worked :D Thanks @LegitSoulja @fayizan
