### ISSUE TITLE
who can help me with the error

### ISSUE THREAD

**Issue by NovaAgars** [AJS-development/Ogar-unlimited#614]
module.js:440
    throw err;
    ^

Error: Cannot find module 'collections/sorted-map'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Alexandre\Downloads\Ogar-unlimited-master (4
)\Ogar-unlimited-master\src\core\WorldModel.js:5:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

Press any key to exit...

**Comment by Andrews54757** [comment]
Duplicate. Dont make me ban you

**Comment by NovaAgars** [comment]
duplicate?

**Comment by NovaAgars** [comment]
sorry im brazilian

**Comment by NovaAgars** [comment]
i need help to create a private server

**Comment by Andrews54757** [comment]
search all  issues for yours

**Comment by NovaAgars** [comment]
okay

**Comment by Andrews54757** [comment]
The answer is do `npm install request`

**Comment by NovaAgars** [comment]
if you can help me thanks

**Comment by NovaAgars** [comment]
im a noob in Node.js ;-;

**Comment by Andrews54757** [comment]
go to cmd then type npm install request

**Comment by NovaAgars** [comment]
can i post what appears?

**Comment by LegitSoulja** [comment]
Resources:
https://github.com/AJS-development/Ogar-unlimited/issues/432
https://github.com/AJS-development/Ogar-unlimited/issues/502#issuecomment-216989548

**Comment by LegitSoulja** [comment]
@NovaAgars cd to your outside directory of ./src and copy the directory path, and go to cmd

in cmd 
> cd (right click paste) **ENTER**
> npm install request **ENTER**
> cd src **ENTER**
> node index **ENTER**

**Comment by NovaAgars** [comment]
the same :(

**Comment by Andrews54757** [comment]
the use the pre-installed version by ajs dev here https://github.com/AJS-development/Pre-Installed-ogarUL

**Comment by NovaAgars** [comment]
sorry andrew because i duplicate i isnt see the Issue

**Comment by NovaAgars** [comment]
THX  soo MUCH

**Comment by NovaAgars** [comment]
@LegitSoulja i isnt have the node_modules how i can get

**Comment by NovaAgars** [comment]
?
