### ISSUE TITLE
OGAR IS PISSING ME OFF

### ISSUE THREAD

**Issue by XenoYT** [AJS-development/Ogar-unlimited#618]
This is bullshit it always give me cant find module i use node 6.00

**Comment by Andrews54757** [comment]
Profanity is not allowed as well as spamming


OFFENSE:
> For spamming, not researching issue(is it really that hard) profanity


Today I hereby declare you BANNED from ogarUL for 1 week
> Banned on May 16. Will be appeased on May 23
