### ISSUE TITLE
It would be very nice if someone made a youtube video showcasing this.

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#62]
If you make a youtube video showcasing this program, please put it in the comments so I can give credit to you

**Comment by Agarian** [comment]
i may......

**Comment by aaxxo** [comment]
I will be able to make a video at some point.

**Comment by aaxxo** [comment]
I will make a video this week @Andrews54757.  Please see my other videos, they will be in a similar style.  https://www.youtube.com/channel/UC2RfXpvLQuJJcRUvawQjTRw

I was thinking of 1 showcase video and one tutorial showing to set one up.  Are you able to come online sometime for a simple Q&A about this project?  Would be great to record a quick segment about what you have planned and also talk about Agario.

**Comment by problemsofworld** [comment]
I can am good editor

**Comment by Andrews54757** [comment]
@aaxxo it depends. Id love to but it depends on a lot of other variables in life
