### ISSUE TITLE
Opting In for beta testing is here!

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#621]
Hello all!

I created an opt-in system where you can opt in to use future features of ogar ul. In the future, I will put some interesting features available for those who opt-in. Please note if you opt-in, there might be bugs. Currently, there are no new features, but there would be soon! To opt in, give me your unique ID shown when first starting the server. 
```
Loading ./settings/advConfig.ini
Loading ./settings/config.ini
Loading ./settings/override.ini
ukzBHAO
[Console] Loading plugins
[Console] Failed to load pluginfile README.md Reason: Error: Cannot find module '../plugins/README.md/index.js'
```
In this example, the unique ID is ukzBHAO

Current Opt-In features
* resolved #610 
* bots that team (can only shoot mass)
* Fixed unlimited FFA and Unlimited PVP
* added ability to control minions with E and R
* Reader Friendly

Note that if you are not opted in but you download the opt-in branch, it would auto revert back to original because its not authorised

**Comment by lotfis** [comment]
fix the split issue plz

**Comment by Andrews54757** [comment]
?

**Comment by Megabyte918** [comment]
Can't fix something that isn't broken ¯\_(ツ)_/¯

**Comment by tommyb008** [comment]
r4s3dLybUR

**Comment by Andrews54757** [comment]
I added you

**Comment by tommyb008** [comment]
how do i use it?

**Comment by tommyb008** [comment]
oh, nevermind

**Comment by tommyb008** [comment]
andrew how do i use ogar unlimited??? what site can i use it on?? i just get blank screen on most of them

**Comment by sukass** [comment]
FGcw4Ss

**Comment by sukass** [comment]
@tommyb008 https://github.com/AJS-development/Ogar-unlimited/issues/280 you need the client

**Comment by LegitSoulja** [comment]
ADiguIh

**Comment by uWotMate** [comment]
Cannot find Process_Nextick_Args?

Plz Fix

**Comment by fayizan** [comment]
My Server Unique Id ZfgRDJZ

**Comment by KiwiDiamond** [comment]
When is ogar coming up moneyclip hasn't replied for 4 days!!!!!!

**Comment by firelightning13** [comment]
BN6H9Ti

**Comment by KiwiDiamond** [comment]
Is their a new private server tell me all the info please like when will ogar private server open or is their a new private system like that thanx and message me ASAP

**Comment by Influxx** [comment]
2erhYFh5zH

**Comment by LegitSoulja** [comment]
Ok um, did all comments get deleted? Because I provided mines and asked how can I apply the id with other servers, and to where they are stored so I can help add others to the id list.

Id is **BNlJO17**

**Comment by Andrews54757** [comment]
I already opted you in before

**Comment by Andrews54757** [comment]
and I opted in everyone else

**Comment by Andrews54757** [comment]
to tell if you opted in, in startup, there is a message stating `you have opted into future features`

**Comment by LegitSoulja** [comment]
@Andrews54757 yup, i confirm that it does say that.

**Comment by Andrews54757** [comment]
okay, then you are using the opt-in version. although, to see my fix to unlimited ffa, use the update command. It would download auto from optin branch. Also, I finished your plugin API wiki

**Comment by LegitSoulja** [comment]
@Andrews54757 can you take a look at this please https://github.com/AJS-development/OgarUL-Plugin-Library/issues/8

**Comment by PrinceDark9243** [comment]
@Andrews54757 opt me plz id ZAM9243

**Comment by LPArigma** [comment]
@LegitSoulja would you mind helping me with my Apache web server? I'm having troubles with the virtual hosts can you add me on skype possibly? My skype is Joshua.latimer40

**Comment by LegitSoulja** [comment]
Yea sure

**Comment by fayizan** [comment]
I changed my server today so I got a new ouid here it is ->> Ocwp8p6
please add me @Andrews54757

**Comment by Andrews54757** [comment]
YAY! I added the ability to control minions with E and R

**Comment by Andrews54757** [comment]
You need to use this special client: 
[Agarioclient.zip](https://github.com/AJS-development/Ogar-unlimited/files/271409/Agarioclient.zip)

**Comment by Andrews54757** [comment]
You can also use : http://ajs-development.github.io/client/. play.ogarul.tk is not updating.

**Comment by Agarian** [comment]
how to get it on the server? lol

**Comment by Agarian** [comment]
i have ljG0xbCrrE what do i do to it? i wanna use the bots splitting feature

**Comment by LegitSoulja** [comment]
@Andrews54757 I'll purge the cache.. That should fix play.ogarul.tk

**Comment by Agarian** [comment]
i need help :P

**Comment by LegitSoulja** [comment]
@Agarian with?

**Comment by Agarian** [comment]
getting the bots (E and R) splitting feature in

**Comment by LegitSoulja** [comment]
Andrew never told me how to opt people in, So i guess you'll have to wait until he does..

**Comment by Agarian** [comment]
damn

**Comment by LegitSoulja** [comment]
@Andrews54757 umm, I see mybb which is nice, and I have an account? But I don't know my credentials :/

**Comment by Agarian** [comment]
@Andrews54757 How would i get the following features in the game?
- The bots (E and R) splitting feature
- Fixed unlimited FFA and Unlimited PVP

**Comment by LegitSoulja** [comment]
@Agarian he has to opt you in, then you just update like normal.

**Comment by Agarian** [comment]
Also the merge command is now broken due to the "UnlimitFFA" fix.

**Comment by Andrews54757** [comment]
@Agarian I opted you in. just start your server. @LegitSoulja Your password is 547573596. change it when you get in

**Comment by Andrews54757** [comment]
Also change your email address in the forums. I had it to mine

**Comment by Agarian** [comment]
actually i just downloaded the OPTIN branch, oddly enough, at one point, it auto updated out of nowhere, it hasn't happened again yet.

**Comment by Andrews54757** [comment]
@Agarian To prevent people from using the branch without being opted in, I made it so it auto-reverts back to the original if not opted in. Your status now is opted in, so if it reverted, it should revrt back again

**Comment by NarutoGamerPro** [comment]
Please add me @Andrews54757

**Comment by LegitSoulja** [comment]
@NarutoGamerPro you have been added

**Comment by LPArigma** [comment]
@legitsoulja did you ass me on skype?

**Comment by LPArigma** [comment]
add me to the beta testing @Andrews54757 bM9DQOY

**Comment by Andrews54757** [comment]
merged

**Comment by ImHyper** [comment]
@Andrews54757 hi, I have some questions. First, do you have to pay a server rent? Does anyone see my ip & port if I make it public? How do you make the server public... is it with the statistics plugin? and lastly is it ran on the ogarul server?

**Comment by LegitSoulja** [comment]
@ImHyper Yes, When you make your server public your ip and port will be shown to everyone who will be connecting to your server. 

In the future, I will be removing Statistics, and I have another remapping of what ill do. You will be able to join a server using its game uid, instead of needing a player ip and port to connect to the server.

No. Alot of people host on there own, and or rent services a month to run ogar servers.

To see future changes, and to keep with ogarul in the future register on the forums. Also check out Year 2017 posting http://forum.ogarul.io/threads/year-2017.25/

**Comment by ImHyper** [comment]
@LegitSoulja  I am BANNED from the OgarUl forums for the following reason: Have some faith, don't be a loser and ruin things for everyone else.. Your ban will be lifted on Jan 1, 2017. 
Ok, WHAT is this because I accidentally Clicked that ogarul should die? IT WAS AN ACCIDENT I felt SOOO bad XC PLEASE UN-BAN ME! Im trying to contact you ANY WAY I CAN XC   XC   XC   XC   XC   XC
XC
XC

**Comment by NatsuTheGreat** [comment]
Where is that ban?

**Comment by ImHyper** [comment]
at http://forum.ogarul.io/  it says: You have been banned for the following reason: Have some faith, don't be a loser and ruin things for everyone else.. Your ban will be lifted on Jan 1, 2017.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat It wasn't because of that. He was on more than one account, which one was f andrews, ogarul gonna die. Just because the site went down early, but then I put the site to old.ogarul.io.

Now, which he was banned until next year which means he can't be part of the development times. He can come back nextgen..

@NatsuTheGreat Login here. http://forum.ogarul.io , same account from the old forums.

**Comment by ImHyper** [comment]
@LegitSoulja @NatsuTheGreat What do you mean? Can you PLEASE LET ME BACK IN PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  PLEASE  sorry im a little crazy... lol Please?

**Comment by LegitSoulja** [comment]
> sorry im a little crazy... lol Please?

Ummm, yeah.

**Comment by Andrews54757** [comment]
@LegitSoulja Dont deal with them. They are just little kids with little capacity. Most of them. Every time it is like "why am I banned I diddnt do anything" when the answer is obvious. Also, it is very frustrating to listen to their complaints. The issues place here is literally a complaint desk where children go for their life problems. It make me so angry and is one of the main motivations to close OgarUl. 



For you little kids, get off agario and do work, be productive. When you are older, it will be to late. You will wish that you had seized the moment. The future needs productive people, and the people who arnt; they get pushed to the bottom and is destroyed. Open your eyes and realise the truth. Dont complain but deal with it. And do everything beforehand. THEN YOU CAN F**KING COMPLAIN TO ME!!

**Comment by SharkFinPro** [comment]
@Andrews54757 Am i like those kids...?

**Comment by ImHyper** [comment]
@LegitSoulja Look can you just tell me why i'm banned... ITS TILL NEXT YEAR Lets see you not do ANY OgarUL stuff 'till next year

**Comment by NatsuTheGreat** [comment]
@ImHyper If you are that f-face who spammed the gitter, then there should be an *x* towards the right end of this GitHub tab.

**Comment by ImHyper** [comment]
I'm not idk what you're talking about I didn't do ANYTHING seriously I had only had my acc for like 2 days... idk my acc is Hyper on the forums he got the wrong guy xC

**Comment by ImHyper** [comment]
@NatsuTheGreat I even tried, but couldn't delete my acc

**Comment by ImHyper** [comment]
@NatsuTheGreat only retards spam it just dumb, pointless, and annoying

**Comment by ImHyper** [comment]
What could anyone do to get banned for that long?

**Comment by Megabyte918** [comment]
> only retards spam it just dumb, pointless, and annoying

[bruh](http://i.imgur.com/M2UDzNY.png)

**Comment by NatsuTheGreat** [comment]
Lol.

**Comment by Megabyte918** [comment]
I know this is unrelated, but I saw [this video](https://www.youtube.com/watch?v=d9TpRfDdyU0) yesterday and I swear its been getting almost 1mil views per hour god dayum

**Comment by LegitSoulja** [comment]
What did I just watch :/

**Comment by NatsuTheGreat** [comment]
Hahaha that last fusion!
