### ISSUE TITLE
Help...

### ISSUE THREAD

**Issue by Tokoagar** [AJS-development/Ogar-unlimited#622]
How can I connect to my private server ?

http://ajs-development.github.io/client/ doest work anymore 

Please help

-Toko

**Comment by Tokoagar** [comment]
Why?

**Comment by LegitSoulja** [comment]
Exactly what it says. Its closed due to asking miniclip something important, and we dont want to violate without asking them first =[

You can use this on my site for behalf, and i take full responsiblity http://cl.agariohub.tk/?ip=ip:port&method=ws

**Comment by Tokoagar** [comment]
ok thanks

**Comment by LegitSoulja** [comment]
replace ip:port with your connection details

**Comment by Tokoagar** [comment]
yeah ik the rest

**Comment by LegitSoulja** [comment]
@Tokoagar okay

**Comment by Tokoagar** [comment]
does my univirsal wifi like 24.122.61.90 work?

**Comment by Tokoagar** [comment]
24.122.62.90*

**Comment by LegitSoulja** [comment]
for other people they can, but not you. For other people to see it you need your port portforwarded. You still use localhost:443

**Comment by Tokoagar** [comment]
I can't put 443 because of skype :p

**Comment by LegitSoulja** [comment]
Change your skype settings

**Comment by Agarian** [comment]
Cl.agariohub uses an outdated client. I have an updated version

**Comment by LegitSoulja** [comment]
@Agarian i know its not updated.. I'm not going to niether. It's temporary.
