### ISSUE TITLE
READ ME

### ISSUE THREAD

**Issue by tommyb008** [AJS-development/Ogar-unlimited#623]
I get the blank Screen and i read https://github.com/AJS-development/Ogar-unlimited/issues/591 and that  doesent even solve the donky verses donky race! So anyone help me the 5 year old robot?
i know this is duplicated but i tried doing those other threads and i cant get help from them. ban me if you must i just ask this one question.

also put label as bug for me andrew? thanks

**Comment by Megabyte918** [comment]
Make sure everything is updated, your using chrome, and you have the latest client (worked for me at least)
