### ISSUE TITLE
does this still work

### ISSUE THREAD

**Issue by GOpb** [AJS-development/Ogar-unlimited#624]
i am curious does this still work?

**Comment by Andrews54757** [comment]
yes. but in a different way


1. update server
2. play using https://play.ogarul.tk

**Comment by GOpb** [comment]
how do you update server

also is the server address your local ip

sorry im new to this

**Comment by tommyb008** [comment]
WHY tf THEY SEE THIS BUT NOT MINE WTF?

**Comment by GOpb** [comment]
idk but i still cant join  my server

**Comment by tommyb008** [comment]
SAME why tf cant i join my server i just see blank am i right?

**Comment by GOpb** [comment]
yeah

**Comment by GOpb** [comment]
same here

**Comment by tommyb008** [comment]
hey you got skype?
we can work this out together mabey?

**Comment by tommyb008** [comment]
if you dont want to say it publicly just say so

**Comment by GOpb** [comment]
naw i dont have skype i am useing a windows boot on my make and i cant get skype to work thanks for the offer though

**Comment by GOpb** [comment]
mac

**Comment by GOpb** [comment]
andrews how do you join we cant do it

**Comment by tommyb008** [comment]
what do you mean skype dont work you mean because it interfears with ogar?

**Comment by tommyb008** [comment]
i think this might work!
one sec!

**Comment by GOpb** [comment]
k

**Comment by GOpb** [comment]
did it work

**Comment by GOpb** [comment]
no like skype wont install cuz im on a boot

**Comment by tommyb008** [comment]
install skype for mac

**Comment by GOpb** [comment]
i have skype for mac on my mac boot but im working in windows so i cant run it

**Comment by GOpb** [comment]
did what you were trying work

**Comment by tommyb008** [comment]
still trying wait

**Comment by tommyb008** [comment]
also what operating systom do you have LINUX? or what

**Comment by GOpb** [comment]
i have mac with a bootcamp version of windows 8.1 pro

**Comment by tommyb008** [comment]
and it failed.. I NEED  ANDREW

**Comment by tommyb008** [comment]
I UPDATED server DOESENT WORK

**Comment by tommyb008** [comment]
EYY
GOTO http://c4clanchat.chatovod.com/

**Comment by GOpb** [comment]
joined

**Comment by Megabyte918** [comment]
Do you guys mean blank as in a blank grid screen or a blank white screen?

**Comment by tommyb008** [comment]
blank grid screen

**Comment by tommyb008** [comment]
ive read all of those threads about it but none worked

**Comment by tommyb008** [comment]
# plz help andrew!

**Comment by LegitSoulja** [comment]
@tommyb008 @GOpb Please don't annoy andrew with these duplicate post, or unless you are wishing for a bad ending.

@GOpb If you are running local your ip will be localhost & your port is the game port...
@tommyb008 , get a better working browser.

**Comment by tommyb008** [comment]
I USE FUCKING CHROME

**Comment by tommyb008** [comment]
WHATS WRONG WITH THAT HUH?

**Comment by LegitSoulja** [comment]
@tommyb008 no need to have anger over a game kid.

**Comment by Andrews54757** [comment]
@tommyb008 Calm down, take a chill pill and rest

**Comment by tommyb008** [comment]
I BET your using chrome arent yah?

**Comment by LegitSoulja** [comment]
@tommyb008 yup with no problems neither :). Non of my browsers.

**Comment by LegitSoulja** [comment]
@tommyb008 even tor browser works.. Haha

**Comment by Andrews54757** [comment]
im using chromium

**Comment by Andrews54757** [comment]
(linux)

**Comment by LegitSoulja** [comment]
Its for windows also

**Comment by tommyb008** [comment]
then tell me whats my problem? "get a better browser"

**Comment by LegitSoulja** [comment]
@tommyb008 Are you using a proxy?

**Comment by tommyb008** [comment]
i dont use proxys

**Comment by LegitSoulja** [comment]
@Andrews54757 I found a problem.. 

when connection localhost or 127.0.0.1 it doesnt change to ws, its still wss :/

**Comment by LegitSoulja** [comment]
@tommyb008 do you get a blank screen here too? http://cl.agariohub.tk

**Comment by tommyb008** [comment]
yup
and this is wat i see in expect element  wss:////localhost:8081 or  wss:////127.0.0.1:8081

**Comment by LegitSoulja** [comment]
@tommyb008 use this http://cl.agariohub.tk/?port=ip:port&method=ws

**Comment by LegitSoulja** [comment]
change ip:port with your info

**Comment by tommyb008** [comment]
still get blank

i put this http://cl.agariohub.tk/?127.0.0.1:8081&method=ws

**Comment by LegitSoulja** [comment]
whats the web console looking like?

**Comment by Andrews54757** [comment]
I fixed the client at play.ogarul.tk
was a minor bug

**Comment by LegitSoulja** [comment]
clear browser cache or something

**Comment by tommyb008** [comment]
I STILL GET IT!

**Comment by tommyb008** [comment]
WTF

**Comment by tommyb008** [comment]
I HAVE BLANK STILL 

PROBLEM NOT SOLVED

**Comment by Andrews54757** [comment]
@tommyb008 Play.ogar.ul works for me

**Comment by LegitSoulja** [comment]
@tommyb008 run chrome dev tools to fix the issue also.

**Comment by Andrews54757** [comment]
@tommyb008 If you cant handle that, why dont you make your own client?

**Comment by LegitSoulja** [comment]
@tommyb008 Put your computer in the microwave for 5 minutes

**Comment by tommyb008** [comment]
like i know the fuck to do that bruh also its a tower it doesent fit nor do the two monitors

**Comment by LegitSoulja** [comment]
That was a working solution though :(

**Comment by tommyb008** [comment]
2 bad

**Comment by Andrews54757** [comment]
@tommyb008 Have some appreciation then, or else, make it your self! I mean, there is something called DIY

**Comment by LegitSoulja** [comment]
Use the oven then at 450 degress

**Comment by tommyb008** [comment]
IM NOT A MAJOR CODER DO I LOOK LIKE ONE NO IF I WAS I WOULD OF FIXED THIS MYSELF WOULDNT I?

**Comment by tommyb008** [comment]
uh :/

**Comment by LegitSoulja** [comment]
@tommyb008 Google "old agario client" boom. Your done.

**Comment by tommyb008** [comment]
# the worst time to be emberessed of it working after a big comeback...

**Comment by tommyb008** [comment]
# :/

**Comment by Andrews54757** [comment]
Next time, double check to see if it actually doesnt work. Okay?

**Comment by tommyb008** [comment]
*facepalm

**Comment by tommyb008** [comment]
# CAN YOU GET SKINS TO WORK PLZ 
xD

**Comment by Andrews54757** [comment]
Well that was a waste of my time and @LegitSoulja's

**Comment by tommyb008** [comment]
# plz

**Comment by Andrews54757** [comment]
bye bye

**Comment by Andrews54757** [comment]
Im unwatching this

**Comment by tommyb008** [comment]
nooooooooooooooooooooooooooooo

**Comment by tommyb008** [comment]
theres a bug on my screen

**Comment by LegitSoulja** [comment]
kill it then

**Comment by tommyb008** [comment]
no poor bug!

**Comment by tommyb008** [comment]
nvm its in my screen

**Comment by tommyb008** [comment]
:/

**Comment by LegitSoulja** [comment]
order a new monitor on amazon

**Comment by NatsuTheGreat** [comment]
I am laughing so hard from you and andrew. And this guy's responses. Whooo, OgarUL is hilarious. Lmfao.

**Comment by firelightning13** [comment]
@tommyb008 Format your computer

Profit

**Comment by LegitSoulja** [comment]
Delete your harddrive partitions and white all partitions with zeros

**Comment by tommyb008** [comment]
I LIKE how andrews is still watching this thread xD

**Comment by Agarian** [comment]
smash your hard disk and put it back together, that'll fix it xD

**Comment by LegitSoulja** [comment]
See, that's permanent damage

**Comment by Agarian** [comment]
how do i prevent the OPTIN branch from auto updating? I have the config *autoupdate* set to 0.

**Comment by LegitSoulja** [comment]
@Agarian I don't think there's an option for that.

**Comment by Agarian** [comment]
i'll have to remove the update database from my GameServer.js then lol

**Comment by Agarian** [comment]
But really the merge command got broken by the UnlimitFFA fix :(

**Comment by LegitSoulja** [comment]
@Agarian I seen your PR

It looks like the merge command is (merge [id] [true or false])

**Comment by Agarian** [comment]
now i can't even use testing features:
"[Console] You have opted out from testing future features."
does that 100% of the time now FFS

**Comment by LegitSoulja** [comment]
@Agarian lol

**Comment by LegitSoulja** [comment]
@Agarian did your id change?

**Comment by Agarian** [comment]
id?

**Comment by LegitSoulja** [comment]
@Agarian yea, for opting in? Check line 1660 to disable opt in updates.

**Comment by Agarian** [comment]
NVM i also removed my server's ability to OPT out lol

**Comment by LegitSoulja** [comment]
@Agarian ? First of all you change the wrong thing for it to say you have been opted out..

**Comment by LegitSoulja** [comment]
comment out line 1665 and dont change nothing else.

**Comment by Andrews54757** [comment]
@LegitSoulja It is because he is not authorised to use the opt-in branch.

**Comment by Andrews54757** [comment]
@Agarian Whats your id?

**Comment by Agarian** [comment]
t4fZnGz

**Comment by LegitSoulja** [comment]
@Andrews54757 @Agarian I re-opted you.

**Comment by Andrews54757** [comment]
@Agarian Your authorised now. use the update command

**Comment by Agarian** [comment]
k

**Comment by Andrews54757** [comment]
if it still says you opted out, that means you will have to wait for like a minute. This is because like I already told @LegitSoulja the raw feature of github is slow

**Comment by Agarian** [comment]
its working lol

**Comment by LegitSoulja** [comment]
@Andrews54757 I had opted another server of mines, and it updated quick

**Comment by Andrews54757** [comment]
@LegitSoulja I will merge optin into master soon
