### ISSUE TITLE
HOW TO JOIN PRIVATE SERVER?

### ISSUE THREAD

**Issue by tommyb008** [AJS-development/Ogar-unlimited#625]
I have UPDATED SERVER AND HAS 5.9.0 NODE AND I GO TO https://play.ogarul.tk/

AND I JUST GET BLANK 

PLEASE HELP

**Comment by Andrews54757** [comment]
WHAT IS YOUR IP:PORT!!!

**Comment by GOpb** [comment]
idk how do you find it

**Comment by GOpb** [comment]
is it the 443

**Comment by LegitSoulja** [comment]
@tommyb008 @GOpb Please don't annoy andrew with these duplicate post, or unless you are wishing for a bad ending.

@GOpb If you are running local your ip will be localhost & your port is the game port...
@tommyb008 , get a better working browser.

**Comment by Andrews54757** [comment]
^^^

**Comment by Andrews54757** [comment]
i already banned 2 people today. Makes me sad that I have to do that

**Comment by GOpb** [comment]
I apoligize for the duplecit posts but i still have a question i have treied putting in 127.0.0.1:443 which is the local host but i still just get the blank backgroung

**Comment by Andrews54757** [comment]
i will investigate

**Comment by GOpb** [comment]
ok thank you

**Comment by Andrews54757** [comment]
Fixed, it was a minor bug
