### ISSUE TITLE
Suggestion (websocket performance)

### ISSUE THREAD

**Issue by Influxx** [AJS-development/Ogar-unlimited#627]
For even better socket performance, you could try switching to:
https://github.com/alexhultman/uWebSockets

It claims to perform a lot better than the regular ws module. It should also handle memory management a lot better.

**Comment by anaelpop** [comment]
can any1 give me client @LegitSoulja

**Comment by firelightning13** [comment]
ill send it to gitter

**Comment by Agarian** [comment]
@Influxx this sounds interesting, how would you implement this into ogar unlimited?

**Comment by Influxx** [comment]
In GameServer.js, you can replace `const WebSocket = require('ws');` with `const WebSocket = require('uws');`

However, `WebSocket.prototype.sendPacket = function (packet) {} ` causes a problem as uws seems to handle the object differently. Maybe @Andrews54757 or someone else knows how to fix this?

**Comment by LegitSoulja** [comment]
@Influxx https://www.npmjs.com/package/uws

**Comment by Influxx** [comment]
@LegitSoulja It's exactly the same package I linked to.... We're talking about how to implement it in OgarUnlimited because it seems to perform a lot better than the regular ws module. ;)

**Comment by Megabyte918** [comment]
interesting

**Comment by Agarian** [comment]
Closing 4 now
