### ISSUE TITLE
Problem with connecting...

### ISSUE THREAD

**Issue by MrMonkeyLOL** [AJS-development/Ogar-unlimited#628]
Hello, i have 1 problem.
I getting in [site](play.ogarul.tk) and write my ip:port. Next i click "Play" and at me on the screen grid in white bg. How connent to server? Thank's beforehand.

**Comment by Megabyte918** [comment]
Make sure everything is updated, your using chrome, and you have the latest client (worked for me at least)

**Comment by LegitSoulja** [comment]
@MrMonkeyLOL provide a web error log so we can see whats going on

**Comment by MrMonkeyLOL** [comment]
Megabyte918, thx you. I all update, and i can connect to server!
