### ISSUE TITLE
DON'T USE C9 FOR HOSTING!!

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#630]
Wow what? Yea, c9 is a vps, but it's not intended for people who wants to host servers for 24/7 unless you are using the services and IDE for development purposes only. If you are not using c9 for that reason, your account could be terminated due to hosting games, websites, or hosting anything in particular for a 24/7 service using there VPS. 

**Q**:
> It would be great if I could just put my app into production right from Cloud9 and it kind of looks like I can do that. Can I host my website on Cloud9?

**A**:
> No. While Cloud9 will host your files, allow you to write code, run code, and debug it, we do not recommend using it as a hosting service. Cloud9 is a top notch development environment, but just that, a development environment. It was never meant to host websites or apps.

> Allowed :thumbsup:
- Using Cloud9 to develop an application / website and have it connect to whatever external services you need to make it work. 
- Sharing that site / application with your friends / coworkers for testing / feedback purposes.

> Not Allowed :thumbsdown:
- Sharing your site / application with the general public.
- Hosting your production site on Cloud9
- Hosting game servers (unless you are developing / modding this game and only running it for short periods of time for testing / feedback purposes)

> Alternatives
If you wish to do anything in the Not Allowed list and still use Cloud9 as your IDE we recommend you buy a VPS from a provider such as AWS, GCE or Digital Ocean and run a SSH Workspace1. If you have a SSH workspace you can do whatever you like with it (within the terms of whoever you purchase it through).

So, for those people who are using c9, with there server at full potential, think again. You wonder why your accounts get banned without a reason? Now you know why. It might just be a good idea for the people who uses c9 find a better proper service for VPS use. 

I'm still very shocked about the game modding, Which would come in handy in the future but eh, don't really need to use there services specificly. Nice to know though.

**This article**: https://community.c9.io/t/can-i-use-cloud9-for-hosting/16

Thanks to @timjrobinson for giving that statement out regarding c9 ToS, and usage.

**Comment by timjrobinson** [comment]
I'm a developer at Cloud9. Thanks for posting this. We give Cloud9 away for free because we want to more people to learn to code and develop anything they like, whether thats games, web apps or enterprise work. 

What we don't want is people using us purely as a free server. Unfortunately we've had a recent increase in users using Cloud9 just to run an Agar server and so we've taken steps to automatically ban anyone who does this. 

R.E. Game Modding: We love game developers and modders, I first learnt to code by making and modding games and believe its a great pathway into the industry. What we don't want are script kiddies that just download game servers and run them.

**Comment by Agarian** [comment]
i could have at least recovered my project not both my normal and backup accounts are BLOCKED
now i have to start from scratch :angry:

**Comment by Agarian** [comment]
apparently c9 didn't seem to give a shit. how typical of people.

**Comment by timjrobinson** [comment]
@Agarian - if you have code you want to recover please post on the community and we can help you out. We've done a blanket ban because 99% of the agar users weren't coding, they were just running the server.

**Comment by Agarian** [comment]
i am unable to, since my account is blocked

**Comment by timjrobinson** [comment]
The community forums are at http://community.c9.io they have different logins than the main Cloud9 IDE.

**Comment by Agarian** [comment]
the problem is when i try to login to the community page, i get "incorrect username, email or password"
this happens to both my accounts

**Comment by Agarian** [comment]
i seriously had to deal with this now... its only 5 minutes until i change classes, and 3 more hours before i can get on another computer

**Comment by Andrews54757** [comment]
@timjrobinson I love your c9.io service. I used to have a raspi as my development enviorment but after c9, I use that

**Comment by LegitSoulja** [comment]
@Andrews54757 nice.. I own 2 rasbery pies :), 1st and 2nd edition

**Comment by ItzLevvie** [comment]
I got odroid-c2 and raspberry pi 3

**Comment by Andrews54757** [comment]
I dont know why my account is suspended though, Probably caught on a filter when I was actually programming. Good thing I back everything up

**Comment by Andrews54757** [comment]
Kinda dissapointed though. But I can manage.

**Comment by Martinali12** [comment]
@timjrobinson u guys should say it before buying ,I bought yesterday and today it's blocked I cant code money back ?

**Comment by LegitSoulja** [comment]
@Martinali12 Well, there's a thing called ToS https://c9.io/site/terms-of-service

It's like your applying for something without reading guidelines. If they say no, I wouldn't blame them.

**Comment by Martinali12** [comment]
my 29$ :'(

**Comment by ItzLevvie** [comment]
go for OVH / DigitalOcean or AWS

**Comment by hassanila97** [comment]
OVH

**Comment by hassanila97** [comment]
I have a very bad reputarion for AWS as Im using it, the free one at least... but I heard OVH is fast and cheap

**Comment by Martinali12** [comment]
ovh ask for passport anyway to buy just with a creadit card I have alot of money and need a good cheap vps

**Comment by LegitSoulja** [comment]
@Martinali12 @hassanila97 Check out https://github.com/AJS-development/Ogar-unlimited/issues/631

**Comment by timjrobinson** [comment]
@Martinali12 yes you can have a refund as you only signed up yesterday. Please contact our support for a refund.

**Comment by Martinali12** [comment]
@timjrobinson  I did I hope I get my babies back

**Comment by timjrobinson** [comment]
@Andrews54757 Yea we just blanket banned anyone. Please contact our support and explain that you're developing, if you're only coding and not using it for hosting you can use Cloud9.

**Comment by Martinali12** [comment]
can ogarUL work with debian os ?

**Comment by LegitSoulja** [comment]
@Martinali12 any OS is capable

**Comment by Andrews54757** [comment]
@timjrobinson Too lazy. gonna try koding.com as i already have an account there

**Comment by ErikParacelsus** [comment]
Lol c9.io account is banned

**Comment by Agarian** [comment]
I guess i have to use koding aswell. I should have known c9 was trash from the start. I mean i can't even login to the c9 community since my account was blocked...

**Comment by Martinali12** [comment]
how to make koding.io to work 24/7 was `screen` or something

**Comment by LegitSoulja** [comment]
Hmm. I might set up a system in the future to allow anyone who wants to host servers use my vps instead of using something free when you can have as much ram, and good cpu.

I have no use for it nomore. Last use was for minecraft servers which I hosted paid, & free minecraft servers, but then minecraft started becoming a thing I no longer enjoy. Basically I quit minecraft around the time Microsoft took over.

**Comment by LegitSoulja** [comment]
So, I now have a custom built vps with no use what so ever :/

**Comment by hassanila97** [comment]
Give it to me.. I have use.. LOL kidding

**Comment by LegitSoulja** [comment]
I can't give you it. Technically isn't possible. It's a home vps I customly built

**Comment by Lukkez** [comment]
@timjrobinson Any chance to unblock my account? i was going to code Discord bots and test on c9.io, my pc is already fully of programs and slow, c9 is very very fast, i am going to delete ALL the workspaces :pray:

**Comment by Agarian** [comment]
I created a "virusExplosionMult" config and cleaned some other configs to look better,but I still have a LOOOONG way to go xD Wish me luck

**Comment by LegitSoulja** [comment]
@Lukkez Like he said, If you get banned, contact support, or visit the community forum and ask

**Comment by Lukkez** [comment]
Yes, i made the two, I contacted e-mail 3 times, and all of e-mails reply but without answer to the problem and i asked on the Community too... :/

**Comment by LegitSoulja** [comment]
@Lukkez support wont come asap. You will have to wait

**Comment by LegitSoulja** [comment]
This one kid XtremePlaysCOD he was using bots, and lied to get himself back unbanned, but he failed.

**Comment by Agarian** [comment]
shall this be closed tho?

**Comment by LegitSoulja** [comment]
keep it so people will know

**Comment by Agarian** [comment]
k

**Comment by Lukkez** [comment]
@timjrobinson My new account was blocken, but on a workspace info i said i am lukkez, account lukkezdev, not violating NOTHING of ToS, just used 10 min Ogar with a bit of my edited code to test, i am just improving it

**Comment by XxRaizerxX** [comment]
@Lukkez The same thing happened to me and im very mad and i want it back!

**Comment by XxRaizerxX** [comment]
any other hosting site

**Comment by Agarian** [comment]
that is FREE?

**Comment by XxRaizerxX** [comment]
yah

**Comment by LegitSoulja** [comment]
@XxRaizerxX nope not really that I know of. Free hosting is kindof a rare thing. It costs a lot of money to provide those services

**Comment by LegitSoulja** [comment]
Aws I know but bad performance, and koding I heard of but never used

**Comment by firelightning13** [comment]
Koding is also bad performance, with 1 CPU and 512 RAM

**Comment by Lukkez** [comment]
I am going to code my game on c++ but i do not have any good IDE's to use right now :/

**Comment by SorryAgario** [comment]
@LegitSoulja can u help me to host a private server for my clan to practice splitrunning since hamachi wont work and portforwarding is not an option for me

**Comment by LegitSoulja** [comment]
@Lukkez Mono developer is what I use when making games also. It fully supports c language :)

Also netbeans is what I use mainly for all my development, even nodejs.

**Comment by Andrews54757** [comment]
Somehow, I cant edit the plugin library. I need to create the permissions solver plugin but I cant

**Comment by LegitSoulja** [comment]
@Andrews54757 I had that problem to. I was not able to edit, just upload only. I reloaded the page and it fixed the problem.
