### ISSUE TITLE
Digital Ocean Guide

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#631]
**Moved Here** :: https://github.com/AJS-development/Ogar-unlimited/wiki/Digital-Ocean-Setup

**Comment by Martinali12** [comment]
expensive for 1 server

**Comment by LegitSoulja** [comment]
@Martinali12 not really unless you get a **JOB**

**Comment by LegitSoulja** [comment]
And who said you have to run the service 24/7? 

Clearly you could have one and pay probably less than $5 a month by optimizing the use of the service.

**Comment by ItzLevvie** [comment]
Oh and don't forget to put "ALLSSD10" as a promotional code so you can get $10 for free.

**Comment by LegitSoulja** [comment]
@iTzLevvie I'll document it down for others use.

**Comment by ItzLevvie** [comment]
Okay.

**Comment by ghostangel2212** [comment]
I know its not the right place but i dont want to open a issue for this



Someone can please tell me a agar.io extension to connect to a private server

I used bagar helper, agar.io powerups, and normal agar.io too but i cant connect to private servers or normal servers too

http://agar.io/?ip=127.0.0.1:443 i use to paste this on my url bar and yesterday worked why today no?

**Comment by Andrews54757** [comment]
turn packetversion to 1

**Comment by ghostangel2212** [comment]
What? 

in english please :+1:

**Comment by ghostangel2212** [comment]
oh, i find it i have it in 1

**Comment by ghostangel2212** [comment]
i still have the same error
:(

**Comment by Andrews54757** [comment]
Oh, i mean 0, i forgot

**Comment by ghostangel2212** [comment]
ok ill try

**Comment by ghostangel2212** [comment]
No D:  i cant 


Agar.io power ups didn't work 

Bagar helper didn't work 

Normal Agar.io didn't work 

Other extension?

**Comment by LegitSoulja** [comment]
@ghostangel2212 Um, no because we dont use extensions.

**Comment by ghostangel2212** [comment]
and what if that us use guys, if i can know?

**Comment by LegitSoulja** [comment]
@ghostangel2212 In english please :)

**Comment by ghostangel2212** [comment]
So sorry, hehehe    "what do us guys use to connect to a private server"



Sorry for my grammar errors i dont speak english well

**Comment by ghostangel2212** [comment]
now i got other error


TypeError: "callback" argument must be a function
    at exports.setTimeout (timers.js:314:11)
    at GameServer.mainLoop (C:\Users\Gmobil_Shop\Desktop\Ogar-unlimited-master\src\core\GameServer.js:1471:7)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)


?

**Comment by LegitSoulja** [comment]
@ghostangel2212 What node version are you using?

**Comment by ghostangel2212** [comment]
6.1.0

**Comment by LegitSoulja** [comment]
@ghostangel2212 I don't think it works for that high of a version yet. Everyone is using 5.9.1 and below.

**Comment by ghostangel2212** [comment]
ok i'll try to use this version :)

**Comment by ghostangel2212** [comment]
![watafo](https://cloud.githubusercontent.com/assets/19393651/15342478/706f587e-1c63-11e6-8a99-40bd00ea579b.PNG)


LOL i have 10 of respawn mass n i got more than 600k


i dont know why but lol

i cant play :+1:

**Comment by ghostangel2212** [comment]
6M sorry

**Comment by Agarian** [comment]
umm yr using my extension... it doesnt work for ogar unlimied anymore...

**Comment by ghostangel2212** [comment]
ok

**Comment by ghostangel2212** [comment]
![watafo 2](https://cloud.githubusercontent.com/assets/19393651/15342627/f595a372-1c64-11e6-8de4-1a454aea6a7b.PNG)

nope

**Comment by Agarian** [comment]
yah, my extension wasn't meant to be leaked like this lol

**Comment by ghostangel2212** [comment]
F*** my life :L

**Comment by ghostangel2212** [comment]
its a script error i downloaded other version and works perfectly :)

**Comment by Agarian** [comment]
other version?

**Comment by firelightning13** [comment]
@ghostangel2212 It's a packet problem. Changing to `packetversion = 0` doesnt do anything at all (it does but it still doesnt work). Mind using the original version of OgarUL
