### ISSUE TITLE
How to connect after new uptade?

### ISSUE THREAD

**Issue by AverageUser123** [AJS-development/Ogar-unlimited#632]
How can I connect to my ogar server after update? Because "connect" command isn't working
anymore.

Sorry for any grammar errors

**Comment by ItzLevvie** [comment]
```connect("ws://127.0.0.1:443):``` is now ```core.connect("ws://127.0.0.1:443):``` Either way, the protocols are changed, and now you won't be able to connect your server without updating the server protocol. You can use a client to connect to your server now

**Comment by AverageUser123** [comment]
Ok thank you very much :)

**Comment by firelightning13** [comment]
what....
