### ISSUE TITLE
getting banned from Cloud9 for using bots

### ISSUE THREAD

**Issue by bangana** [AJS-development/Ogar-unlimited#635]
i just got banned (account blocked) and i can't access to my workspace anymore i contacted support and he said '
Hi there,

Thanks for reaching out about this. It looks like your account has been blocked because you were running a bot or several bots using your workspace. Cloud9 is purely for development, iteration, and testing of apps, not running bots.'
Any ideas what to do ?

**Comment by Martinali12** [comment]
dude I paid 29$ yesterday and today am banned ....

**Comment by bangana** [comment]
lol Rekt

**Comment by ErikParacelsus** [comment]
@LegitSoulja close?

**Comment by LegitSoulja** [comment]
@ErikParacelsus Yes
@bangana Refer to https://github.com/AJS-development/Ogar-unlimited/issues/630
