### ISSUE TITLE
rror: Cannot find module 'process-nextick-args'

### ISSUE THREAD

**Issue by RyanGaming1111** [AJS-development/Ogar-unlimited#637]
I have install npm and Dependencies

**Comment by Andrews54757** [comment]
`npm install request` in cmd

**Comment by RyanGaming1111** [comment]
which folder

**Comment by RyanGaming1111** [comment]
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Ryan\package.json'
npm WARN Ryan No description
npm WARN Ryan No repository field.
npm WARN Ryan No README data
npm WARN Ryan No license field.

**Comment by Andrews54757** [comment]
npm install request. not npm install

**Comment by Andrews54757** [comment]
after you cd into the repo

**Comment by Andrews54757** [comment]
search up installing dependancies npm on google

**Comment by Andrews54757** [comment]
Ticket closed

**Comment by hassanila97** [comment]
But.. why do we have to deal with this crap?

**Comment by LegitSoulja** [comment]
@hassanila97 because things doesn't work 100% all the times.
