### ISSUE TITLE
Client problem

### ISSUE THREAD

**Issue by bean07** [AJS-development/Ogar-unlimited#640]
@Andrews54757 can u give me the client? i very need it :<

**Comment by PrinceDark9243** [comment]
oh i have client

**Comment by bean07** [comment]
@PrinceDark9243 cn you give me?my skype:vietkhanh2007

**Comment by mafiakb** [comment]
@bean07 i have client, u can buy?

**Comment by LegitSoulja** [comment]
@mafiakb Are you serious? Are you kidding me right now? 

@Andrews54757

**Comment by mafiakb** [comment]
my code is private :3 send priv :)

**Comment by LegitSoulja** [comment]
@mafiakb Private you say? 

What's all special?

**Comment by hassanila97** [comment]
Probably only name has been changed... LOL

**Comment by LegitSoulja** [comment]
Lol. I've lost all hope for a happy ending. This is very sad

**Comment by bean07** [comment]
@hassanila97 i think i xee u in agar xp bot and agarlvgen! btw anyone have? pls send me my mail:vietkhanh2007@gmail.com

**Comment by firelightning13** [comment]
Lol selling an ~~illegal~~ client illegally.

**Comment by Andrews54757** [comment]
@mafiakb You selling the client that I gave to people is really imoral.  Remove your post and dont do it again or I ban you as I HATE people who try to make money off of others

**Comment by Andrews54757** [comment]
Here is the client for everyone. FOR FREE! 
[Agarioclient.zip](https://github.com/AJS-development/Ogar-unlimited/files/270558/Agarioclient.zip)

**Comment by Agarian** [comment]
doesn't work bro, doesn't load.

**Comment by Agarian** [comment]
and on http://play.ogarul.tk using 127.0.0.1:*SERVERPORT* does not work.

**Comment by Andrews54757** [comment]
replace serverport with your port

**Comment by Agarian** [comment]
i did, duh lol

**Comment by Agarian** [comment]
"Connecting to ws://127.0.0.1:8080" main_out.js:29:113
socket open main_out.js:32:69
socket close

**Comment by Agarian** [comment]
running out of time here, 10 minutes until i change classes,

**Comment by Agarian** [comment]
Running out of time here, 10 minutes until i change classes.
Who can create an ogar unlimited binary for an x32 system? The school uses x32 systems :P
The one i used was before plugins, its outdated. Possibly why it closed socket.

**Comment by Megabyte918** [comment]
@Agarian this also happened to me when trying to connect to @LegitSoulja 's server, with an x64 system

**Comment by Andrews54757** [comment]
@Agarian I dont recomend playing during school. Focus on your classes. Play at home or in study halls

**Comment by bean07** [comment]
Yes! btw @Megabyte918 i think LegitSoulja's server get closed

**Comment by LegitSoulja** [comment]
@bean07 What server?

**Comment by bean07** [comment]
i dunno sk @Megabyte918
