### ISSUE TITLE
How my friends can join?

### ISSUE THREAD

**Issue by AverageUser123** [AJS-development/Ogar-unlimited#641]
How my friends can join my Ogar server?
Is there any way? 
Thanks ;)

If there is already such a question I apologize.

Sorry for any grammar errors

**Comment by LegitSoulja** [comment]
You need to port forward port 443, and give your friend your ip and port and have them connect here 

http://play.ogarul.tk

**Comment by LegitSoulja** [comment]
Look on google for more info about port forwarding, and opening firewall connections

**Comment by AverageUser123** [comment]
Ok thanks :)
