### ISSUE TITLE
OgarUl Private Server Hosting IDE (BETA)(TESTING)

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#645]
So, like c9 has there own IDE, and there own servers that it connects to..

Well, I have my own vps, and im trying to set up a system to allow some people have access to my vps to run servers. The thing is I cannot find a IDE base that can run from my vps to web to do that. 

Anyone have ideas of an IDE that I can use? I found this http://www.activestate.com/ but it's not web base like I thought, and I almost purchased it without actually getting the trial version

Codiad is a thing to, but ill have to implement a console and etc. 

But does anyone know a fully built IDE or an IDE base that I could use? If I can find one, the faster I can give away some free servers to the ogarul community so you wouldn't no longer have to use c9, or anything else. Max amount ill pay for this is $500

I've also looked at this aswell https://eclipse.org/che/

**Comment by bean07** [comment]
$500? do u crazy?

**Comment by LegitSoulja** [comment]
@bean07 ?

**Comment by LegitSoulja** [comment]
YAA I have my own IDE

![capture](https://cloud.githubusercontent.com/assets/4976824/15381541/8abf80e8-1d3d-11e6-8af1-f6e34fc34580.PNG)

**Comment by LegitSoulja** [comment]
Okay, so this will be already ready tomorrow. You can pick your provided ram space 1-5GB of ram.

**Comment by Andrews54757** [comment]
@LegitSoulja You also need to restrict it so they can only run ogar. or else someone might install a virus

**Comment by LegitSoulja** [comment]
@Andrews54757 Yea i know. Only the github repo will be allowed.

**Comment by LegitSoulja** [comment]
Eclipse che is awesome. I love it

**Comment by bean07** [comment]
@LegitSoulja how u run the project in that?

**Comment by Megabyte918** [comment]
@LegitSoulja what would we do without you

**Comment by LegitSoulja** [comment]
@bean07 

You will select an environment between nodejs with 1GB - 5Gb ram
from there on creating your workspace you have to add the github git to create and start your new workspace

and just like c9, you will have an IDE and such.

**Comment by bean07** [comment]
@LegitSoulja i mean wheres the project folder so i can run?

**Comment by LegitSoulja** [comment]
@bean07 it's not available for use yet.

**Comment by Megabyte918** [comment]
I can't wait, this is a really cool idea. people will be able to use this for OgarUL hosting instead of c9 and koding and not have to deal with the AWFUL lag

**Comment by NarutoGamerPro** [comment]
Great @LegitSoulja

**Comment by Andrews54757** [comment]
kinda funny because i think c9 literaly copied the structure of eclipse but edited the html

**Comment by LegitSoulja** [comment]
@Andrews54757 Out of looking for ages, eclipse che was the only thing I found. I couldn't even find one that I could buy. They could've modified che though.

About che, im having problems with it. I'm submitting issues regarding it, but I was hoping I will get this all done today/tomorrow without sleeping but I can't get it working correctly.

**Comment by Parth1999** [comment]
Amazing :) I was wondering why my account got blocked :P

**Comment by firelightning13** [comment]
@LegitSoulja Cool! Can't wait to see it

**Comment by bean07** [comment]
after i crete a project,i dunno where is it so i cant cd -_-

**Comment by LegitSoulja** [comment]
@bean07 you are confusing me... 

What project are you creating? Please explain

**Comment by timjrobinson** [comment]
Cloud9 is actually open source too https://github.com/c9/core :) Though the open source version is only in single person mode, no account management stuff. 

@Andrews54757 Cloud9 has been around since 2010, Eclipse Che was only released 2 months ago.

**Comment by LegitSoulja** [comment]
@timjrobinson nice to know

**Comment by LPArigma** [comment]
@LegitSoulja may i be one of the "few" people who get to have access to a machine? also i use eclipse for all my programming lol

**Comment by LegitSoulja** [comment]
@LPArigma I opted you in btw, and sure.

**Comment by LPArigma** [comment]
sweet! should i use the new "start" to start the server? @LegitSoulja i think it looks better then the old on which ran a cmd prompt

**Comment by Andrews54757** [comment]
@LegitSoulja How would you add a simple password into eclipse che? I cant figure it out. Not with github but when trying to access the dashboard

**Comment by LegitSoulja** [comment]
@Andrews54757 You have disable local use, and add token abilities. If its localhost it wont work.

**Comment by Andrews54757** [comment]
?

**Comment by Andrews54757** [comment]
Im not using localhost

**Comment by LegitSoulja** [comment]
@LPArigma not, just start the server like normally and it should auto update. if not manually update. You should see it says you have been opted in

**Comment by LegitSoulja** [comment]
@Andrews54757 what are you using? How did you set it up?

**Comment by Andrews54757** [comment]
my raspi server

**Comment by LegitSoulja** [comment]
@Andrews54757 do you have skype? I'd rather not talk here

**Comment by Andrews54757** [comment]
its okay. i got it

**Comment by LegitSoulja** [comment]
.. okay.

**Comment by LegitSoulja** [comment]
@Andrews54757 but anyways, if you want to make your own system you can. use open shift.

**Comment by NatsuTheGreat** [comment]
Tell me when this is coming out, please.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat I'll let you test it out before release.

**Comment by Lukkez** [comment]
Give one to me =p I'm looking to get a server again

**Comment by NatsuTheGreat** [comment]
I don't mean to be rude or anything but this what I have found:

https://gyazo.com/993dc43f14d8ad87b5a87c69647134e6

https://gyazo.com/519e9b3d4077d37bfd46321ca8bd4244

**Comment by Agarian** [comment]
Whats the website?

**Comment by LegitSoulja** [comment]
It's gonna be a minute before I release this. Testing has been postponed.

**Comment by Nothsow** [comment]
**# How, just i can host my Private Server, i need it be Public and other guys, can join. How, i CAN HOST MY SERVER?**

**Comment by Nothsow** [comment]
Guys, please, who can ask, how can i host, my ogarul server? Because, i'm really need to test it, it cool maybe. :(

**Comment by SharkFinPro** [comment]
@Nothsow You port forward
If you dont know how, ur a NOOB

**Comment by Agarian** [comment]
Reopened in #1445

**Comment by LegitSoulja** [comment]
@Agarian stop wasting resources :/

**Comment by Agarian** [comment]
?

**Comment by LegitSoulja** [comment]
I mean, you created another useless post that nobody cares about. This project is dead now, and issues will soon be closed.

Wasting your time

**Comment by Nothsow** [comment]
Yes, i'm a noob, i dont know how to host ogarul server. But if you know, and you not a noob, just say. Or you don't know too? Eh, ah, oh. :dart:

**Comment by LegitSoulja** [comment]
@Nothsow nobody is noob here.

**Comment by Nothsow** [comment]
Okey. But how can i host my ogarul server?

**Comment by ItzLevvie** [comment]
^^ Buy a VPS

**Comment by LegitSoulja** [comment]
@Nothsow you just host. Very simple.

**Comment by NatsuTheGreat** [comment]
Lmao.

**Comment by Nothsow** [comment]
How, i just need to make it faster? really! Can you say or tutorial? i crying xD

**Comment by Nothsow** [comment]
I only need to host my ogarul server. but i don't know how to do that. i need an tutorial. or can you say only say FULL, how can i host server? please! ! !

**Comment by Nothsow** [comment]
Because, only you can know how to host, and it will be public at the site of ogarul servers, and JUST SAY HOW TO HOST! Please, i'm beging you!

**Comment by fayizan** [comment]
goto https://agarsrv.net to make ogarul public server

**Comment by fayizan** [comment]
@Nothsow very simple way to host ogarul -->  https://agarsrv.net

**Comment by SharkFinPro** [comment]
Eclipse che is kind of like codenvy

**Comment by Andrews54757** [comment]
@fayizan This is not the place to advertise

**Comment by SharkFinPro** [comment]
@Andrews54757 Could i help make new ogarUL?

**Comment by fayizan** [comment]
@Andrews54757 ok, I'm just helping out some of the newbies who were much interested to make their own public server and whoever out of knowledge, hence the website I shared is not mine and its using ogarul thats why I shared here

**Comment by SharkFinPro** [comment]
@fayizan I made a video on how to make a server :/

**Comment by LegitSoulja** [comment]
@SharkFinPro eclipse Che is codenvy. They are the developers. But you wouldn't directly use eclipse nor codenvy during installation. 

You would rather use vargrant, or maven. In other words, it's pointless to use if you aren't using it with proper server equipment.
