### ISSUE TITLE
IDE Tutorial (Looking For Testers)

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#647]
Prior to your account setup, it will look different from these administrator pictures/images, but you should get the idea when you get your account access. You will login using your github account. 

**Creating your project**:
When you login after you have been given access you will start by creating a brand new project. By doing so you will see a page like this for example.
![capture](https://cloud.githubusercontent.com/assets/4976824/15445919/fd68d44a-1ec9-11e6-9848-f012ba5197ee.PNG)

_Select Source_:
When selecting your source you will click the radio button **Import from existing location**. From there you can launch of new project with OgarUnlimited files ready with the Git URL.
> https://github.com/AJS-development/Ogar-unlimited.git

_Select Stack_: 
Here when selecting your stack you will be selecting what is highlighted which is Node. OgarUL runs 100% on node. 

_Configure Workspace_:
![capture](https://cloud.githubusercontent.com/assets/4976824/15395561/78ac1242-1d95-11e6-8155-0d5dca668f00.PNG)
When configuring your workspace you will need to provide a name for your workspace, and select the amount of ram. You will only have a selection of 1-5GB of ram per project.
_Project Metdata_:
This is mainly your project information. Name it and give it a description.

**Creating**:
After saving, your workspace, and project will be created asap
![capture](https://cloud.githubusercontent.com/assets/4976824/15395643/d0438a4e-1d95-11e6-904d-9426291f03a8.PNG)

_When Done_:
![capture](https://cloud.githubusercontent.com/assets/4976824/15395813/7cce312e-1d96-11e6-9e1f-9ed318bc7e6a.PNG)
You can now proceed to the IDE!.

**Getting to know your IDE**
When you have made your project, and launched your IDE you should get something that looks similar. I have 2 folders because I have created 2 projects recently.

![capture](https://cloud.githubusercontent.com/assets/4976824/15395866/b8027520-1d96-11e6-9fd2-2847cda9c7fd.PNG)

Click the console button below, then the little small terminal button that appears. Buttons are highlighted
![capture](https://cloud.githubusercontent.com/assets/4976824/15395912/f3ba0060-1d96-11e6-80b4-87ba4a613557.PNG)

Your project starts in the directory of **projects**. You will need to cd to **projects** before you can can cd to your project folders.

As you can see

![capture](https://cloud.githubusercontent.com/assets/4976824/15395956/21f0eb24-1d97-11e6-89fb-e0ad47a0edd0.PNG)

**Check node** 
run the command **node -v** to check if you are running v5.9.0. If not enter the following commands below to install node 5.9.0

> sudo npm cache clean -f
> sudo npm install -g n
> sudo n 5.9.0

_Node should be successfully updated to version 5.9.0. You can confirm by re-checking the node version_
> node -v

and yes, we can confirm that it has been installed.
![capture](https://cloud.githubusercontent.com/assets/4976824/15396066/aabeb076-1d97-11e6-9576-f212999e89ea.PNG)

**Installing modules & Running Ogar**
You would want to cd to your projects/project folder first. Once you have entered your projects/project directory simple have your terminal open and run **npm install**. This will install all your necessary dependencies..

![capture](https://cloud.githubusercontent.com/assets/4976824/15396382/1ac7b196-1d99-11e6-9171-f14ad43feaaf.PNG)

**CD info your _src_ folder**:
After you have installed your modules, cd into your src folder by running the command below
> cd src

Now start ogar by running the command below
> sudo node index

#### Result

![capture](https://cloud.githubusercontent.com/assets/4976824/15396406/3932e218-1d99-11e6-802e-df626159af31.PNG)

Website: Updating in a few

**Comment by LegitSoulja** [comment]
Finishing tutorial soon about port management, and also direct command access.

Currently working on IDE oAuth with github dev. Coming soon.

**Comment by Andrews54757** [comment]
@LegitSoulja How do you get authentication running?

**Comment by systemroot** [comment]
Is this Github For Desktop or anything else ?!

**Comment by LegitSoulja** [comment]
@Andrews54757 I'm running it from **vps.legitsoulja.info**

It will be up shortly.

**Comment by Andrews54757** [comment]
@LegitSoulja How do you have authentication running? (accounts)

**Comment by LegitSoulja** [comment]
With GitHub oauth

**Comment by LegitSoulja** [comment]
More info here https://codenvy.com/

**Comment by Andrews54757** [comment]
I dont get it, on my copy of eclipse she, there is no auth

**Comment by LegitSoulja** [comment]
Che comes with pre oauth

**Comment by Andrews54757** [comment]
it does? how?

**Comment by LegitSoulja** [comment]
@Andrews54757 https://eclipse-che.readme.io/docs/git#ssh-key-management

**Comment by LegitSoulja** [comment]
@Andrews54757 https://eclipse-che.readme.io/docs/authentication

It's not hard.. It's all right there.

**Comment by LegitSoulja** [comment]
@Andrews54757 you understand now?

**Comment by anaelpop** [comment]
@LegitSoulja how can i preview or get link to connect?

**Comment by LegitSoulja** [comment]
@anaelpop do you have skype?

**Comment by Martinali12** [comment]
is this going to be free hosting for ogarUL or IDE to setup on a vps

**Comment by anaelpop** [comment]
skype:bebocapo3

**Comment by anaelpop** [comment]
can you tell me how to connect like c9.io

**Comment by anaelpop** [comment]
@LegitSoulja

**Comment by Lukkez** [comment]
Wow that supports 3gb ram for **FREE** i'll not use for Ogar but for mine C++ projects and i think just make some physics and AI changes to help

**Comment by LegitSoulja** [comment]
@anaelpop this has a similar concept as c9.io
@Lukkez im only providing hosting for OgarUnlimited only. You can select between 1-5GB of ram for each project you create.

**Comment by anaelpop** [comment]
how to preview link  in this site @LegitSoulja  ?

**Comment by Lukkez** [comment]
No, i am saying about Codenvy, I don't know i'm not sure i want OgarUL server

**Comment by LegitSoulja** [comment]
@Lukkez codenvy isnt hosting, it just for testing. You cannot run services for a long period of time. c9 should implement a shutdown for inactive activity like che so they dont have to worry about banning people all the time.

**Comment by Lukkez** [comment]
I know, it's for testing...

**Comment by anaelpop** [comment]
i need to preview link to connect in ogarul ....... @LegitSoulja

**Comment by LegitSoulja** [comment]
@anaelpop you mean http://play.ogarul.tk ??

**Comment by Martinali12** [comment]
so free hosting 24/7 good job man :).

**Comment by anaelpop** [comment]
server ip

**Comment by LegitSoulja** [comment]
@anaelpop with c9, you go to share and copy your workspace domain link or whatever, and enter it here http://play.ogarul.tk/

I'm not providing domain usage with che, so there will be a custom ip and port you will connect with.

**Comment by anaelpop** [comment]
i cant share my link in this workspace http://beta.codenvy.com/?

**Comment by LegitSoulja** [comment]
@anaelpop you cannot use that

**Comment by Lukkez** [comment]
@anaelpop Codenvy ISN'T for hosting, it's more for coding and test's

**Comment by Megabyte918** [comment]
@LegitSoulja you sir, are a god

**Comment by LegitSoulja** [comment]
@Megabyte918 I wished.. If i was I would change this whole entire illuminti world.

**Comment by HappyRocketwheel** [comment]
title named "IDE Tutorial" but no link for the website

**Comment by LegitSoulja** [comment]
@HappyRocketwheel im not finished yet. I'm still trying to understand a few things, and security wise. Also im having a few people test for me before I release it.

**Comment by Agarian** [comment]
So the website isnt available now? Also is this free? If so, AWESOME

**Comment by LegitSoulja** [comment]
@Agarian it's available but not yet for public release

**Comment by LegitSoulja** [comment]
Ok, I am releasing the ide now, and looking for some testers who would like to test it out before final release. If you are interested please say so

**Comment by HappyRocketwheel** [comment]
sure, skype:happyrocketwheel

**Comment by Agarian** [comment]
i am interested

**Comment by LegitSoulja** [comment]
@Agarian ok, i will private msg you on gitter in a sec with the information.

There's a few more things i need to do quick

**Comment by Agarian** [comment]
ok ill b there

**Comment by Martinali12** [comment]
am good tester :D

**Comment by Megabyte918** [comment]
@LegitSoulja you on? I sent you something on skype

**Comment by LegitSoulja** [comment]
@Martinali12 I can't find you because apparently theres alot of you...

**Comment by LegitSoulja** [comment]
@Andrews54757 did you ever make your custom auth?

**Comment by fayizan** [comment]
I m a good tester too

**Comment by LegitSoulja** [comment]
@fayizan I have closed everything down until tomorrow/later this day. I had bad weather today and power outages. If you are on skype in the morning I'll contact you. I don't know if you have school  or not. Many people here do soo, but I'll be getting everything ready once again in the morning

**Comment by fayizan** [comment]
@LegitSoulja  LoL I finished my school before 6 years..!! well no problem,stay safe from bad weather

**Comment by LegitSoulja** [comment]
@fayizan I finished 5 years ago :/. It's 4am right now. Are you still here?

**Comment by firelightning13** [comment]
It works, but how to connect the server?

**Comment by ErikParacelsus** [comment]
Do we need client anymore? #655

**Comment by LegitSoulja** [comment]
@firelightning13 what works?

**Comment by Martinali12** [comment]
try this skype:Martin ali-09

**Comment by iIronicGameryt** [comment]
why cant i make a workspace? it just says error

**Comment by mastkilxp** [comment]
if you do need still a tester you can message me on skype:mastkilxp skype is almost 24/7 since i have it on pc and mobile.

**Comment by CubeTiger** [comment]
Hey my skype is: CubeTiger
Can I be tester for this?
I've been watching both Ogar and Ogar unlimited for a long time now and I hope Moneyshit ACTUALLY allows private servers back

**Comment by Agarian** [comment]
@LegitSoulja  whats the website? i want to be able to host my server lol

**Comment by LegitSoulja** [comment]
@Agarian I have already gave you the url.. 

I'm going to have to buy this from codenvy because it includes more things that I need. Also I been having problems with my vps lately with this and it's been a pain to work with. I thought this will be an early release, but I guess this will be something that will eventually be here in the future after I get everything worked out, and also security. I've been making plugins and such for this, and there's a few more that I need to develop. In the mean time, just give me a little bit much while longer then it will be released to the public / here.

Im closing this for now.

**Comment by Agarian** [comment]
@LegitSoulja where?

**Comment by Agarian** [comment]
is it eclipse?

**Comment by Agarian** [comment]
the max allowed ram is apparently 3gb

**Comment by LegitSoulja** [comment]
@Agarian ?

**Comment by Agarian** [comment]
i got it

**Comment by LegitSoulja** [comment]
@Agarian what are you talking about? I seen eclipse.. and 3GB? Where that come from?

**Comment by Agarian** [comment]
server is running, how to i connect to it?

**Comment by LegitSoulja** [comment]
@Agarian I don't know what you are talking about, nor what you are using.

**Comment by Agarian** [comment]
im using codenvy.com

**Comment by Agarian** [comment]
my server is running so how do i connect to it?

**Comment by LegitSoulja** [comment]
@Agarian im done.. You cannot use codenvy for hosting... It's not a thing you can use for hosting there. It's only for testing incase someone wants to buy eclipse source. You cannot use that.

**Comment by Agarian** [comment]
damnit...

**Comment by Agarian** [comment]
wasted my time

**Comment by LegitSoulja** [comment]
@Agarian I never said, nor told anyone to use that anyways. Thats the 5th time someone asked me how to host using codenvy when you cannot. It's just a demo. 

Personally, I was using eclipse for my vps. You cannot use codenvy to connect to my vps. Then url I gave you on gitter was mines / eclipse hosting.

**Comment by Agarian** [comment]
well im stuck with c9 but even then i cant run my server on c9 for purposes other than testing. I mean it allows usage on ANY device pretty much. i even played it on my tablet!

**Comment by LegitSoulja** [comment]
@Agarian well, when I finished doing all of this nobody wont have to use c9 anymore, and could use my services to host. But its gonna be some time. I have work and etc, and probably wont have alot of time to finish this all up soon. I'm trying to though, but its gonna take a little longer than I expected.

**Comment by Agarian** [comment]
ok =\

**Comment by LegitSoulja** [comment]
@Agarian and then on top of that, I kindof don't like eclipse, but im working with it more to make it better to fit my personal needs, and security.

**Comment by NoorAgario** [comment]
Nice Work but how can we test it ?

**Comment by LegitSoulja** [comment]
@NoorAgario it has already been tested, and there's a few things I need to add before release.

**Comment by NoorAgario** [comment]
Keep up the good work :) 👍

**Comment by firelightning13** [comment]
So when im using your IDE, am i gonna lag?(since im in east asia)

**Comment by RasyiidWho** [comment]
how to check site after "node index.js"?
