### ISSUE TITLE
How to Split/Eject minions in the new version?

### ISSUE THREAD

**Issue by professionalShit** [AJS-development/Ogar-unlimited#648]
Q don't works, R and E same.

**Comment by LegitSoulja** [comment]
e & r keys

**Comment by Martinali12** [comment]
this only gonna work with the new client will this work with agarplus ? because I use 16.0.5 .

**Comment by professionalShit** [comment]
It don't works. How does the server get the E & R keys pressing state if the current Agar.io clients don't have the argument sender to the socket for E & R keys? ...

**Comment by Agarian** [comment]
because we have to use a different client for ogarUL to work. http://ajs-development.github.io/client/

**Comment by professionalShit** [comment]
I know, I've my own client with custom main_out.js and I solved the problem implementing 2 new event handlers to the Client and 2 listeners to the server PacketHandler.

**Comment by LegitSoulja** [comment]
@professionalShit ok, so why did you even make this issue then?? Waste of time @Agarian @Martinali12

**Comment by Martinali12** [comment]
I get working skins with agario ip and client that why I dont want to use ogar client

**Comment by professionalShit** [comment]
I just solved it .-.
This update works only for specify clients, no SDK or documentation

**Comment by LegitSoulja** [comment]
@professionalShit well you should've been knew that. You can't use ogarul anyways with a specific updated client.
