### ISSUE TITLE
I can't Portforward, My friends can't install Hamachi, any Alternatives

### ISSUE THREAD

**Issue by SorryAgario** [AJS-development/Ogar-unlimited#653]
Are there any other ways to play with my clanmates

**Comment by LegitSoulja** [comment]
Unless you self host, and port forward your ports and allow you friends to obtain your ip and they can connect to your game server via our client http://play.ogarul.tk

**Comment by LegitSoulja** [comment]
Other than that of you really can't port forward, and your friends won't get hamachi the only thing I can tell you is to buy hosting for your server.

Also check out Amazon aws. You could get a free tier to run your server on. Performance I doubt isn't great but atleast you and your friends can play together

**Comment by Andrews54757** [comment]
@SorryAgario I have seebn your profile and it looks like you are one of the people that I previously banned
