### ISSUE TITLE
I JUST REDOWNLOADED THE FOLDER THEN THIS HAPPENED.

### ISSUE THREAD

**Issue by SorryAgario** [AJS-development/Ogar-unlimited#654]
![help](https://cloud.githubusercontent.com/assets/19484292/15425748/4eee4a92-1e3f-11e6-8edb-d5b70c6c844d.png)

So This Happened..... What do I do to fix this?

**Comment by Andrews54757** [comment]
Please dont use caps. And this is a duplicate. Please see the guidline or you might be banned

**Comment by firelightning13** [comment]
#638
