### ISSUE TITLE
Private Servers are back

### ISSUE THREAD

**Issue by Yamanourani** [AJS-development/Ogar-unlimited#655]
http://blog.miniclip.com/2016/05/20/private-servers-back-agar-io/

**Comment by hassanila97** [comment]
@Yamanourani YES! Nice **MONEYCLIP**

**Comment by Martinali12** [comment]
I knew it plops said they did not mean to ban private servers & ext they only meant to ban bots :D.

**Comment by ErikParacelsus** [comment]
hOly shrek finnalee

**Comment by Agarian** [comment]
no, it still doesnt work, i still get:

IndexSizeError: Index or size is negative or greater than the allowed amount agario.core.js:9:0
exception thrown: IndexSizeError: Index or size is negative or greater than the allowed amount,J<@http://agar.io/agario.core.js:9:7744
c.Ja._170c2738@http://agar.io/agario.core.js:9:89622
fd@http://agar.io/agario.core.js:10:80083
Dc@http://agar.io/agario.core.js:10:42948
Qb@http://agar.io/agario.core.js:10:4939
Pb@http://agar.io/agario.core.js:10:4676
xr@http://agar.io/agario.core.js:13:2648
m.C@http://agar.io/agario.core.js:7:5777
Ra/e.e.aa/<@http://agar.io/agario.core.js:6:493
e.e.$a@http://agar.io/agario.core.js:9:73515
Ra/e.e.aa@http://agar.io/agario.core.js:6:436

**Comment by LegitSoulja** [comment]
@Agarian did you change the packet version ?? Your using moddified clients packets instead of the original.

**Comment by LegitSoulja** [comment]
I have not yet tested this.. But, i will eventually later. Nice good news to hear. +1 Miniclip.

**Comment by Agarian** [comment]
either way, this breaks the minions E and R splitting, i'm sticking with the ogarUL client.

**Comment by LegitSoulja** [comment]
Unless there's an addon to tamper monkey that allows that.

**Comment by bangana** [comment]
'"but if you’re one of the few who enjoys private servers"'
that's what he said '-'

**Comment by CubeTiger** [comment]
Does is work confirmed?

**Comment by ItzLevvie** [comment]
@CubeTiger Yup.

**Comment by firelightning13** [comment]
@Andrews54757 I think they heard your message ;)

**Comment by NatsuTheGreat** [comment]
I get a white screen :'(

**Comment by NatsuTheGreat** [comment]
http://prntscr.com/b6io0h

**Comment by HappyRocketwheel** [comment]
using hamachi and server doesnt load w/ ogar open

**Comment by NatsuTheGreat** [comment]
Ogar UL doesn't work for me either...

**Comment by Andrews54757** [comment]
@NatsuTheGreat Its because I changed the protocal, Il change back

**Comment by Andrews54757** [comment]
if anyone would like to use e and r, they can use the nonofficial client

**Comment by NatsuTheGreat** [comment]
Okay, please do so, my stomach is getting the twisted from excitement.

**Comment by NatsuTheGreat** [comment]
No more IndexSize error as I see, but still, cannot connect.

**Comment by Andrews54757** [comment]
i think I finished now

**Comment by NatsuTheGreat** [comment]
Let me test :P

**Comment by NatsuTheGreat** [comment]
Dangit, still cannot connect. Update all works right?

**Comment by Andrews54757** [comment]
let me see

**Comment by NatsuTheGreat** [comment]
Seems to work, I am still catching no connection...

**Comment by NatsuTheGreat** [comment]
I don't know what the problem is, people say it works, yet it doesn't...

**Comment by NatsuTheGreat** [comment]
I feel like I got excited over nothing... same thing with *agar.io/?ip=IP:PORT* :'(

**Comment by Andrews54757** [comment]
I found out that moneyclip did not fully reverse it. Some packets are still different

**Comment by NatsuTheGreat** [comment]
How come people say it works? :'(

**Comment by Andrews54757** [comment]
It doesnt

**Comment by Andrews54757** [comment]
im currently trying with regular ogar

**Comment by NatsuTheGreat** [comment]
I swear, if miniclip lied....

**Comment by Andrews54757** [comment]
It doesnt work with regular ogar.

**Comment by Andrews54757** [comment]
THEY LIED!

**Comment by NatsuTheGreat** [comment]
WOW...

**Comment by NatsuTheGreat** [comment]
I thought it was something I did that messed it up.

@ItzLevvie I don't know how you say it works...

**Comment by Andrews54757** [comment]
@ItzLevvie is probably using an extension or is lying

**Comment by Agarian** [comment]
yeap miniclip sucks

**Comment by NatsuTheGreat** [comment]
Sad..

**Comment by NatsuTheGreat** [comment]
https://www.reddit.com/r/Agario/comments/4k876e/private_servers_work_again/ Tell these guys nothing works.

**Comment by firelightning13** [comment]
from Barbosik ([here](https://github.com/OgarProject/Ogar/issues/569#issuecomment-220684634)):

> issy123: it's already works for at least 6 hours. I'm able to connect to my private server.
> But you're a little wrong, it doesn't uses "old protocol". It uses new protocol, but the client now works with private servers without protection. The protection is used with official servers only. So, the new client allows private servers and prevent bots at the same time. It's very good. Thanks to miniclip :)
> 
> There is just need to add a little fix for update cell message. The fix for private servers is pretty easy, you can find details here:issy123/agario-protocol#15

They are already working on encrypting most of the messages(almost all of it?), probably gonna implement to regular ogar. (soon, maybe soon...)

You just need to use protocol 6 (currently 5?), implementing it in OgarUL and it would be good to go.

Correct me if im wrong

**Comment by EnTerr** [comment]
@Andrews54757 - make the server pay attention to the protocol# sent by the client in the 1st handshake packet 254. E.g. "FE 07 00 00 00" would be version 7. So this will a per-session setting to keep.

Then if protocol version is >5, consider sending "world update" id=16 packets in the slightly different new format - see Barbosik https://github.com/issy123/agario-protocol/issues/15 . I spent lots of time reviewing packets the other day. Differences are minimal - out of top of my head, flags come first now, RGB color is optional and strings are UTF8 now (instead of UTF16).

OTOH, if client starts asking for version <=5, use the pre-existing format for 16.

**Comment by Andrews54757** [comment]
@EnTerr I will actually stick with our client for now until Agario does something that WE want, not for their interests. Also, i implemented chat (from cigar) and the T key to freeze minions. see #669

**Comment by EnTerr** [comment]
@Andrews54757 that's fine - all i advocating is not breaking support for existing Agar protocol 5. Hence the suggestion above. I see no reason to use MiniClit's either.

Are you not affected by crashes like https://github.com/JaraLowell/OgarServ/issues/144 ? If so - great!

These new features you are adding to your dialect of the protocol - are they documented somewhere? Outside the sources? I.e. as data stream

**Comment by ItzLevvie** [comment]
@ItzLevvie I don't know how you say it works...

It's because you've not updated your protocol to version 7, that is why it won't work for you.

**Comment by ItzLevvie** [comment]
@Andrews54757 "@ItzLevvie is probably using an extension or is lying"

I don't think you understood how packets work :)

**Comment by EnTerr** [comment]
@Andrews54757 - you will totally have the same server crash issues like JaraLowell because
https://github.com/AJS-development/Ogar-unlimited/blob/453f71b7ac49fe681b119e29b88c0a7c5cc8dbf6/src/core/PacketHandler.js#L52

If i am right, just protect yourself by checking protocol version in 0xFE packet and kicking out clients with version > 5.

**Comment by Andrews54757** [comment]
@EnTerr Dont underestimate me, I recently added yesterday origin protection so people can only use your own client. Also, regular servers, (agar.io) can be crashed too by editing main_out.js in developer tools

**Comment by EnTerr** [comment]
@Andrews54757 - 
you are barking up the wrong tree! 

Whether agar.io servers can be crashed or not is their problem.

**Comment by EnTerr** [comment]
@Andrews54757 - 
you are barking up the wrong tree! 

1. Whether agar.io servers can be crashed or not is their problem. You should be concerned about fixing your server so it is robust and reliable.

2. "Origin" check is a shitty idea for two reasons: 
a) If i wanted, i can fake origin and crash your servers all day long - because you did not bother fixing above. - and 
b) You are being "isolationist" again - instead of thinking how more people can use Ogar servers, you are building little paranoid walls - and what is the end benefit of that? So somebody can run Agario "party" at home between whom, himself and his cat?!

What i am advocating is not "stay home, lock the door and pretend outer world exists" but "try to listen to other people and respond in a way they can understand". So instead of petty origin checks, see if client (ANY client - no "racial" prejudice of origin) speaks protocol you understand - if so, talk to them - otherwise decline.

**Comment by EnTerr** [comment]
Let's pull back a little and think strategically about the situation. Is increasing "market fragmentation" good or bad to Ogar servers? 

Cue the "Tower of Babel" myth: humans got together building in their pride a great tower to reach the heavens - and then god scrambled their tongues and everybody spoke different dialects and could not understand each other - and so they scattered around the world and so the tower crumbled and felt to dust and was no more... that's where Ogar is heading.

I will again disclose my bias: i am writing Agario client for platforms that have no web browser and cannot run JS client. But have things like game pad or gyro sensors. Sounds cool, no? However now that MiniClit bungled their server protocol, i am looking for alternative options like connecting to Ogar networks. That OgUn (OgUL? this project) lacks ability to build some cohesion, some network from individual servers - that's one thing. But if you now limit each server to only work with local browser clients spun-off from local web server - how is this not fragmenting Ogar down to small irrelevant shards?

**Comment by Andrews54757** [comment]
@EnTerr I have my ways.If you want to do it, then you can do it because supposedly you are so smart and the entire world bows at your feet. I will do it later when I am done with the things I want to do.

**Comment by Andrews54757** [comment]
I am kinda insulted by your comments but I will stay chill

**Comment by Andrews54757** [comment]
The only reason why you want a network is so you can implement that into your app and probably make revenue out of games **you dont own**

**Comment by Andrews54757** [comment]
And who said that the tower of babel was a myth?

**Comment by Andrews54757** [comment]
Ogar Ul wasnt expected to succede. It just did. I just made it to help others who wanted their feature requests. Ogar Ul is mostly made  up of people's requests which is why it is successful. I dont care if it crumbles to dust, I just want to help people. I can also easily protect the server from crashing, but I have other things that  I need to do.

**Comment by Andrews54757** [comment]
People can also share their servers if they want to. But most use it because it is **private** and only certain people they allow can use it

**Comment by Andrews54757** [comment]
If you want, I can make ogarUL dissapear. Just be thankful, okay? :+1:

**Comment by Megabyte918** [comment]
Guys just [STOP](http://i.imgur.com/CoWZ05t.gif) pls

**Comment by LegitSoulja** [comment]
Wow. What a dick

**Comment by LegitSoulja** [comment]
@EnTerr If it bothers you, fix it yourself. Other wise, don't worry about whats going on here. Obviously @Andrews54757 knows whats best.

**Comment by Andrews54757** [comment]
@Megabyte918 You can keep it. to show who entarr is

**Comment by Andrews54757** [comment]
il lock though

**Comment by NatsuTheGreat** [comment]
Yeah Enterr is nothing but a b***h to be honest.
