### ISSUE TITLE
skin in play ogar ?

### ISSUE THREAD

**Issue by paulo364gamer** [AJS-development/Ogar-unlimited#659]
Any way to use skin in http://play.ogarul.tk/

**Comment by professionalShit** [comment]
There is a way to load skin by player name, but is a client-side edit, you need to have a custom client to do it.

**Comment by paulo364gamer** [comment]
I do not know client '-' I am new at this, you can give me some tutorial explaining

**Comment by professionalShit** [comment]
Client on Wikipedia: https://en.wikipedia.org/wiki/Client_(computing)

The client in this case is http://play.ogarul.tk
To edit/add skins you need to host your custom client and be sure to host especially those files: 'main_out.js', 'index.html'

You can find the skins loader in the main_out.js file, and you need a basic knowledge of Javascript to do this. (For example, try connect here: http://lucaromani.net/lexusio/ And use these names: Kraken, Lion, Mammoth, Crocodile) This is only an example of custom skins

**Comment by paulo364gamer** [comment]
so client here in Brazil is called host

**Comment by professionalShit** [comment]
Client: An application that can connect to a Server and send/receive data through a Network Stream
Host: Generic, a WebServer, a Virtual Private Server, a Web Space and much more senses

**Comment by Agarian** [comment]
@AJS-development/ogar-unlimited-devs is it possible to allow custom skins to load in the client?

**Comment by Andrews54757** [comment]
@Agarian I am working on a version that uses cigar

**Comment by professionalShit** [comment]
@Andrews54757 are you looking for collaborators?

**Comment by Andrews54757** [comment]
Kinda, but your name disturbs me.

**Comment by paulo364gamer** [comment]
[customskins.txt](https://github.com/AJS-development/Ogar-unlimited/files/275847/customskins.txt)

I like to use fasso esssas skin in http://play.ogarul.tk/

**Comment by firelightning13** [comment]
what

**Comment by paulo364gamer** [comment]
I wanted to know if you have to use those custom skins in http://play.ogarul.tk/
sorry I am Brazilian, there usand wants you google translator
[customskins.txt](https://github.com/AJS-development/Ogar-unlimited/files/275860/customskins.txt)
