### ISSUE TITLE
Can i edit minion's mass?

### ISSUE THREAD

**Issue by andreklp641** [AJS-development/Ogar-unlimited#660]
I want to know if i can edit minion's mass.

**Comment by CubeTiger** [comment]
Yes you can! Type this:

Plugin install SuperMinions

Then type superminion [ID] [Number of Bots] [Name] [Mass}

**Comment by andreklp641** [comment]
I want to edit their mass in ogar configs, then they will spawn with the mass.

**Comment by Megabyte918** [comment]
@andreklp641 there is no config for that, you'll have to install the plugin. but don't worry its EZ

**Comment by HappyRocketwheel** [comment]
@Megabyte918 there actually IS a config for that

for player start mass, bots will be affected from start mass too.
find this in your ogar folder: 

Ogar-unlimited-master\src\settings\config.ini

config.ini contains the configurations of the PS ( private server ) that you are running.

drag config.ini to notepad++ or any text editor and go to line 208

You should see this: 

> playerStartMass = 10

change 10 to any start mass, it will affect your bots.

**Comment by Megabyte918** [comment]
he said minion's mass tho

**Comment by HappyRocketwheel** [comment]
@Megabyte918 that's basically minions mass

you'd have to install superminions if you don't want your player start mass to be affected.

**Comment by andreklp641** [comment]
Ok thanks @HappyRocketwheel

**Comment by Andrews54757** [comment]
if you want the minions speed to be the default, make it 0

**Comment by Andrews54757** [comment]
(same with spawnmass)
