### ISSUE TITLE
Problem connecting with localhost:443

### ISSUE THREAD

**Issue by bangana** [AJS-development/Ogar-unlimited#661]
installed raga helper extension port is 443 http://agar.io/?ip=localhost:443 
any ideas pls @Andrews54757  @LegitSoulja

**Comment by andreklp641** [comment]
Enter here https://bagar.io/en/ download BAGAR helper extension and deactivate RAGA then try again with OGAR ---> OPEN.

**Comment by HappyRocketwheel** [comment]
the thing is, private servers still don't work

extensions like bagar or raga helper don't work and flicker your cell

**Comment by elitajmx** [comment]
then what

**Comment by elitajmx** [comment]
agario said that it works on fb

**Comment by Megabyte918** [comment]
dont use bagar or raga use play.ogarul.tk

**Comment by firelightning13** [comment]
Most extension doesn't work with OgarUL because it uses special packets that extension can't even read. So use the official client instead

**Comment by elitajmx** [comment]
on ogarul skins don't work??

**Comment by firelightning13** [comment]
@elitajmx Not yet. But soon it will
