### ISSUE TITLE
C9.io account blocked

### ISSUE THREAD

**Issue by Lukkez** [AJS-development/Ogar-unlimited#662]
@AJS-development/ogar-unlimited-devs See that, my two accounts was blocked, 
![image](https://cloud.githubusercontent.com/assets/15003706/15442539/401c38de-1eb8-11e6-978d-09ff346dbb8d.png)
And the one i was coding, you guys can please contact Brady to unblock my account? I just have one workspace who isn't breaking the ToS :/

**Comment by Lukkez** [comment]
He's just rage with me and blocked, unfair. I am making the correctly use of c9.io.

**Comment by Andrews54757** [comment]
use @LegitSoulja service

**Comment by Agarian** [comment]
whats his website?

**Comment by HappyRocketwheel** [comment]
@Agarian i believe it's codenvy

**Comment by Andrews54757** [comment]
no

**Comment by systemroot** [comment]
-_- mine too. i think they have make an simple scan for all workspaces which have clone ogar and have make all suspended -_-

**Comment by Lukkez** [comment]
Ok..

**Comment by Martinali12** [comment]
hmmm make new account every 12 hour and make them team but dont pay before making new accounts make sure to deleted all cookies of c9.io its easy to make account :P ..
