### ISSUE TITLE
private servers are back but still aren't working

### ISSUE THREAD

**Issue by HappyRocketwheel** [AJS-development/Ogar-unlimited#663]
I have the latest ogar-unlimited version and installed all dependencies, then I opened up Start.bat and waited for it to load. Once it loaded, I opened my hamachi and copied my IPv4 and pasted it in the end of agar.io/?ip=  with the port as :443

like this:

http://agar.io/?ip=25.105.163.193:443

then I check the node command prompt and it says [Autopause] Game Resumed! but clearly when I press play, nothing loads and a white grid pops up.

**Comment by Andrews54757** [comment]
I found out something. The packets are still different
