### ISSUE TITLE
Mac Error

### ISSUE THREAD

**Issue by Merkie** [AJS-development/Ogar-unlimited#667]
Steps I took:
Downloaded the Ogar Unlimited file.
Changed directory in terminal to src folder.
ran "npm install ws".
ran "npm install request".
ran "node index.js".
got this error: http://imgur.com/bmpLAI8

Thanks in advance,
-Merkie

**Comment by firelightning13** [comment]
#638

**Comment by LegitSoulja** [comment]
You just can't install ws and request.. You need to install them all
