### ISSUE TITLE
Opting here is here again! (this time with interesting features)

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#669]
To opt in, do the same as from here #621 . (im starting to fulfill suggestions)

### New Features
* T for freezing minions
* Chat (yay!, from cigar)
* Other features from cigar (no multi-server platform though. soon though, will be called Multiverse)
* allowonly config (to stop other clients but yours)
* Mass collision disable option (todo)

**Comment by NatsuTheGreat** [comment]
I can add the ejected mass collision thingy, just where?

**Comment by NatsuTheGreat** [comment]
The master or dev branch?

**Comment by SorryAgario** [comment]
Are the Bugs fixed though?

**Comment by fayizan** [comment]
@Andrews54757  I m already opted in for beta testing,could u please send me the special client.zip 
my skype fayizbe

**Comment by Andrews54757** [comment]
@fayizan You have to opt in again

**Comment by firelightning13** [comment]
Opt in me pls: mEqNfG2obC

**Comment by Andrews54757** [comment]
@firelightning13 I opted you in

**Comment by Andrews54757** [comment]
Merged

**Comment by Agarian** [comment]
This is cool tho!

**Comment by Agarian** [comment]
things i never thought possible are happening before my eyes!

**Comment by NoorAgario** [comment]
How can I control minions with E and R ?

**Comment by LegitSoulja** [comment]
@NoorAgario are you opted in? You can only use those extra keybinds using http://play.ogarul.tk

**Comment by NoorAgario** [comment]
no I'm not opted ,:(

**Comment by LegitSoulja** [comment]
@NoorAgario provide me your unique id. When started the server you should see a code on startup

**Comment by NoorAgario** [comment]
I cant see any ID 
                                       | (_)     (_)_           | |
  ___   ____  ____  ____    _   _ ____ | |_ ____  _| |_  ____ _ | |
 / _ \ / _  |/ _  |/ ___)  | | | |  _ \| | |    \| |  _)/ _  ) || |
| |_| ( ( | ( ( | | |      | |_| | | | | | | | | | | |_( (/ ( (_| |
 \___/ \_|| |\_||_|_|       \____|_| |_|_|_|_|_|_|_|\___)____)____|
      (_____|
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 16.5.5
[Client] Listening on *:8080
[Game] Loaded stats server on port 88
[Game] Listening on port 443
[Game] Current game mode is Free For All
[Autopause] The Game Was Paused to save memory. Join the game to resume!
>[Console] We have detected a update, Current version: 16.5.5 ,Available: 16.6.8
[Console] Update Details: Added T for pausing minions. Chat and in-chat commands added
[Console] To update quickly, use the update command!
[Console] We recieved a world-wide message!: If you got ogar unlimited not from github but from sources such as mediafire, Redownload it from https://github.com/AJS-development/Ogar-unlimited. Another source might include third party software that could be malicous
[Autopause] Game Resumed!

**Comment by LegitSoulja** [comment]
@NoorAgario it's in the very beginning when the plugins load.

**Comment by NoorAgario** [comment]
Also the site u gave me is working but what are the controls ?
3acpaLU

**Comment by LegitSoulja** [comment]
@NoorAgario actually. I think you need to update because @Andrews54757 removed all the opted in people.

**Comment by Andrews54757** [comment]
@LegitSoulja It is not neccasary as i merged with master

**Comment by NoorAgario** [comment]
so how what are the bot controls in http://play.ogarul.tk
@Andrews54757 
@LegitSoulja

**Comment by Andrews54757** [comment]
E is for split. R is for feed. T is for freeze

**Comment by NoorAgario** [comment]
its not working :( does it require a plugin or something ? @Andrews54757

**Comment by Agarian** [comment]
you need to use the custom client play.ogarul.tk

**Comment by NoorAgario** [comment]
yes but the controls are not working for me when I press E , R do I have to update OgarUl ?

**Comment by Agarian** [comment]
yes

**Comment by Agarian** [comment]
u have to have the latest version.

**Comment by NoorAgario** [comment]
aaw , that ill take me ages to download :( u don't know my Download Speed Nw , is there any thing else I have todo ?

**Comment by NoorAgario** [comment]
module.js:327
    throw err;
    ^

Error: Cannot find module './Chat'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Anony\Desktop\New All Desktop Shit\Ogario\src\packet\index.js:9:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

Press any key to exit...

**Comment by Agarian** [comment]
use the "update all" command

**Comment by NoorAgario** [comment]
after updating

**Comment by Agarian** [comment]
wait, what TF?

**Comment by Agarian** [comment]
uh idk that doesnt happen to me.

**Comment by firelightning13** [comment]
@Agarian @NoorAgario It's really useless to use `update all`. It's a missing file. Redownload and npm install can do the trick
