### ISSUE TITLE
Hamachi Won't Work...

### ISSUE THREAD

**Issue by SorryAgario** [AJS-development/Ogar-unlimited#670]
So today, I installed hamachi and got my friends to install it to so we can sync up  our splitrunning and when I started ogar-unlimited (I changed the port to 123 so i can use skype) then I went to my browser google chrome then I typed the agar.io/?ip=ipv4address:123 then I went there I pressed play it says connecting (btw i have the bagar helper extension to help) so i waited for 5 more minutes then restarted my hamachi and ogar unlimited... still didn't work so I went to ur website "play.ogarul.tk" i typed the ipv4address:123 then still didnt work so I can't portforward and how do I host it with hamachi?

**Comment by Martinali12** [comment]
did you used old packet or new packet maybe did it worked without ipv4 so it means you typed it wrong , close ? you can search youtube for hamachi problem not here this  not a isusse at all.

**Comment by Andrews54757** [comment]
Hamachi is not supported here. See #121
