### ISSUE TITLE
Bring back The Remove Grid Option

### ISSUE THREAD

**Issue by SardoYT** [AJS-development/Ogar-unlimited#671]
Can you guys please bring back the remove grid option in the client

because my pc cant really handle those gridlines

and im getting like 10 fps with those grid lines

but without grid lines i get 30 fps

**Comment by SorryAgario** [comment]
Try clearing out ur temp files they slow ur computer. delete em all.... press windows button and r at the same time then type %temp% then press enter.... then a folder will pop out press ctrl a then delete then skip the files that cant be deleted then empty ur recycle bin then get ccleaner scan then delete some shit i wish that can help out :smile:

**Comment by SardoYT** [comment]
@SorryAgario Bruh none of this are working i have a 2 gb ram pc SO SLOW AS FK I just really need to remove the grid and ill be happy

**Comment by firelightning13** [comment]
@Andrews54757

**Comment by Andrews54757** [comment]
okay

**Comment by Andrews54757** [comment]
Done

**Comment by Megabyte918** [comment]
What about an extra zoom option? since we now have our own client

**Comment by Agarian** [comment]
One thing, the hide grid option only affects the default white theme.
