### ISSUE TITLE
Weird shapes of the ball and not even spawning?

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#672]
I searched for this but nothing...
I literally just downloaded the server,started it,joined it and then just when i spawn there is a black ball showing up..Fix?? or any suggestions??

**Comment by elitajmx** [comment]
Also i spawn with different amount of mass instead of 44.
randomly: 350- or +,340- or +,600- or +,640- or +,650- or +

**Comment by Martinali12** [comment]
for now you can use www.play.ogarul.tk or  if want to use agario client you must use bagario ext and old packet , close ?

**Comment by SorryAgario** [comment]
#656
