### ISSUE TITLE
Any Ideas For Skins ????

### ISSUE THREAD

**Issue by kareemman00** [AJS-development/Ogar-unlimited#673]
I Have The Custom Client Instaled and the game working but the skins is not work only nasa moon....
I but for EX raptor skins and put url in custom skin file and put it in skins folder in client files and but it in main out of the client files and didn't work !!!!! what should i do ????

**Comment by elitajmx** [comment]
how to u make custom client ??

**Comment by kareemman00** [comment]
download it from internet :smile:

**Comment by elitajmx** [comment]
wtf how

**Comment by firelightning13** [comment]
@kareemman00 It doesnt work at the moment, but it will be in the future (Andrews is testing cigar in OgarUL at the moment)

**Comment by Martinali12** [comment]
use vogar and old packet

**Comment by Martinali12** [comment]
close ?

**Comment by Andrews54757** [comment]
@Martinali12 that is already done

**Comment by Megabyte918** [comment]
@kareemman00 it doesn't work yet, be patient. but if you do want skins i wouod recommend [this](https://chrome.google.com/webstore/detail/agario-skins/ddmbokmmnnhmdllgjohoigfpfmaiahfh?hl=en) extension :)
