### ISSUE TITLE
[MAC] Can't Connect Issue

### ISSUE THREAD

**Issue by Merkie** [AJS-development/Ogar-unlimited#674]
I have started my ogar unlimited server and tried connecting to it with "agar.io/?ip=localhost:443" and it doesn't let me connect: http://imgur.com/tjal8wg . I used the Bagar.io chrome extension and the raga.pw chrome extension with no success. Am I doing something wrong?

**Comment by Andrews54757** [comment]
POP QUIZ!


1. What is this project?
 a Ogar Unlimited
 b Bagar
2. What did we tell you to use officially?
