### ISSUE TITLE
Getting skins and custom skins - Ogar

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#676]
I'm asking if developers can add on their client : ajs-devlopement.github.io/client/ just some skins like veteran skins and premium skins , or if possible , customs skins wich we can add in customskins.txt .

<h1><b>Thanks</b><h1>

**Comment by Tokoagar** [comment]
Hey dude I am not sure if they are going to add some because it's not like the real agar.io it's a client :P

**Comment by Megabyte918** [comment]
it is being worked on, customskins USE to work before miniclit broke private servers, and once we had to switch to the client the skins just broke all together. be patient they will be fixed soon, in the meanwhile just use like a custom skin extension or something

**Comment by Tokoagar** [comment]
How? Im not sure I use http://play.ogarul.tk/ and idk if they are entention on it

**Comment by DarkZYT** [comment]
I really wish that the creator creates this extension , and if it can work with an extension , i think it also can work with the client

**Comment by Andrews54757** [comment]
working on it

**Comment by Tokoagar** [comment]
ok
