### ISSUE TITLE
I cannot connect to new client after the recent update to 16.6.8(old client working)

### ISSUE THREAD

**Issue by fayizan** [AJS-development/Ogar-unlimited#677]
@Andrews54757  Thank you so much for this great update but it seems to be not connecting with the new client (play.ogarul.tk).Just checked connecting my server with the old client which is working fine with new update.
Should I have to upgrade my node version or anything else..?

![screenshot_2](https://cloud.githubusercontent.com/assets/19163419/15449531/0cb9fd14-1f9e-11e6-8c9e-f80564f4943b.jpg)
![screenshot_1](https://cloud.githubusercontent.com/assets/19163419/15449532/0cbc5bcc-1f9e-11e6-9b20-c35d78c0e53f.jpg)

**Comment by DarkZYT** [comment]
Use this one : http://ajs-development.github.io/client/

**Comment by Andrews54757** [comment]
I think i fixed now. It is because the client is bad eat figuring out if you should use ws or was. So i made it manual now

**Comment by fayizan** [comment]
@Andrews54757 can u please give me the fixed client file

**Comment by Andrews54757** [comment]
What do you mean? yours was fixed to begin with

**Comment by fayizan** [comment]
I mean I m using my own client,not playing through your client

**Comment by Andrews54757** [comment]
see #537

**Comment by fayizan** [comment]
@Andrews54757 ok thank u but the client file u provided connects with wss:// method which is not working for me but I can connect through ws:// where to edit in that client file
![screenshot_3](https://cloud.githubusercontent.com/assets/19163419/15450101/1940eaea-1fb0-11e6-9fc9-75e576c16048.jpg)

**Comment by LegitSoulja** [comment]
@fayizan Change it in index.html then....

**Comment by fayizan** [comment]
Ty @LegitSoulja

**Comment by fayizan** [comment]
its working Thank u so much @Andrews54757  and @LegitSoulja
