### ISSUE TITLE
Crazy instant/Crazy Mega Mode Help!

### ISSUE THREAD

**Issue by eevaqueen** [AJS-development/Ogar-unlimited#679]
Hello,
I would like to make cell merge fast like crazy insta and cell split small like crazy mega mode like this website http://abs0rb.me/
any idea for what i can change?
Thanks.!

**Comment by fayizan** [comment]
Change the PlayerRecombineTime to 0 under "Player" section in the config.ini

**Comment by eevaqueen** [comment]
@fayizan 
Thank you but it didn't merge like crazy instant mode above,you can check what i mean in the website.

**Comment by Andrews54757** [comment]
there is a game mode called unlimited ffa
