### ISSUE TITLE
Can't start the server after the update : Cannot find module : "./Chat"

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#682]
Can someone help me with this issue i cant start my server after the 16.8.8 Update , but my friend can , can someone help me ?
![issou](https://cloud.githubusercontent.com/assets/19506199/15449835/1418a87c-1f89-11e6-93c9-6324d49dba98.JPG)

<h1>Thanks !

**Comment by HappyRocketwheel** [comment]
reinstall ogar unlimited and do npm install

**Comment by Megabyte918** [comment]
or use the update command

**Comment by DarkZYT** [comment]
Thanks !!!!

**Comment by firelightning13** [comment]
@Megabyte918 It's the missing files. Do `update all` is useless. Download from github and npm install can do the trick

**Comment by Andrews54757** [comment]
No, it works but sometimes, github raw doesnt update as fast

**Comment by firelightning13** [comment]
Oh ok I didn't think of that
