### ISSUE TITLE
How can i add a chat to my server 

### ISSUE THREAD

**Issue by XxRaizerxX** [AJS-development/Ogar-unlimited#686]
if you have a chat to give me it must have something that allows chat moderator or admin and that auto makes me admin by a command if so maby you might wanna add that in game

**Comment by XxRaizerxX** [comment]
Sorry for posting a stupid issue :'(

**Comment by LegitSoulja** [comment]
@Andrews54757 currently released a client with chat implemented.

**Comment by XxRaizerxX** [comment]
Ok does it have the moderator stuff

**Comment by LegitSoulja** [comment]
https://github.com/AJS-development/Ogar-unlimited/issues/537#issuecomment-220781336

I don't know.. See for yourself.

**Comment by XxRaizerxX** [comment]
It does not say about a chat.

**Comment by Andrews54757** [comment]
The chat is server sided. I added it in yesterday. see #669
