### ISSUE TITLE
Microsoft Azure I got the Node.js VM what to do next?

### ISSUE THREAD

**Issue by SorryAgario** [AJS-development/Ogar-unlimited#688]
I got the Node.js VM what to do next? Im a coding noob so I just want to play with my friends. What do I do next to make my server public?

**Comment by SorryAgario** [comment]
![help](https://cloud.githubusercontent.com/assets/19484292/15451928/2884ef76-1f90-11e6-9920-7b15425efa24.png)

**Comment by SorryAgario** [comment]
@LegitSoulja Help?

**Comment by LegitSoulja** [comment]
@SorryAgario I never used it. Hopefully someone makes a tutorial
