### ISSUE TITLE
Something I found in my private server.

### ISSUE THREAD

**Issue by NatsuTheGreat** [AJS-development/Ogar-unlimited#689]
I spawned without an extension but immediately the server crashed.

After the crash of the server I came back with an extension, and I found I disconnected cell and this is what it looked like:

http://prntscr.com/b6srg1

With the unkown weird nickname that was supposed to say 'testing...' I am guess it's something in the *view.set...* part that we are not getting at right. The part after *if(typeof node === 'undefine') {continue};*. That's just my guess.

**Comment by LegitSoulja** [comment]
This could be a problem with your packets..

**Comment by Andrews54757** [comment]
this was what enterr talked about. I will make it idiot-proof later after I finish multiverse

**Comment by NatsuTheGreat** [comment]
@LegitSoulja You read the whole and understood how I got there right?

@Andrews54757 Alrighty. :P

**Comment by Agarian** [comment]
closing 4 now
