### ISSUE TITLE
What is this

### ISSUE THREAD

**Issue by Ronan01** [AJS-development/Ogar-unlimited#691]
![image](https://cloud.githubusercontent.com/assets/19513287/15452571/7fa344ce-2026-11e6-98fb-4183ac125011.png)

**Comment by firelightning13** [comment]
We don't use or support extension. Extension are for.... nvm.

OgarUL only use official custom client here:
https://play.ogarul.tk or https://ajs-development.github.io/client/

**Comment by Ronan01** [comment]
![image](https://cloud.githubusercontent.com/assets/19513287/15452685/9bb36acc-202b-11e6-980a-4ac0f46d7b80.png)

**Comment by RasyiidWho** [comment]
![capture](https://cloud.githubusercontent.com/assets/19422415/15452695/279d3348-1fae-11e6-94b0-19f49abad95d.PNG)

**Comment by firelightning13** [comment]
@Ronan01 
![2016-05-22_14h12_26](https://cloud.githubusercontent.com/assets/17120382/15452698/1f5ee068-202c-11e6-8916-b90032c35346.png)

Click "Load unsafe scripts"

**Comment by RyanGaming1111** [comment]
does it support skins?

**Comment by firelightning13** [comment]
Not yet. But it will in the future
