### ISSUE TITLE
OGARUL NO SKINS

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#692]
There's no skins in OgarUl...

**Comment by Martinali12** [comment]
you can use skins with old packet and you need to use bagario ext and connect with agario client , close ?

**Comment by elitajmx** [comment]
no like, ogarunlmited.io
when i am on that site and i spawn in server, the skins wont work. and bagario ext wont work connecting on real agarioi

**Comment by Martinali12** [comment]
ye you should use normal agario(site)/?ip=+bagario ext and ofc old packet and it's should work ..

**Comment by Martinali12** [comment]
if you use new packet you will see wired shapes  #672

**Comment by NarutoGamerPro** [comment]
http://agarextreme.ml/

**Comment by ItzLevvie** [comment]
Who ever owns agarextreme.ml, I've just crashed / froze everyone and now people are pissed xD

**Comment by LegitSoulja** [comment]
@ItzLevvie lolll

**Comment by Agarian** [comment]
**.-.**

**Comment by Agarian** [comment]
for the record this is a duplicate, we all know skins currently do not work in the official client.
