### ISSUE TITLE
Hamachi works on OgarUnlimited.io?

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#693]
Hamachi works on OgarUnlimited.io?

**Comment by Martinali12** [comment]
ye it does  its not about agar.io or Ogarunlimited.io both should work if you port forwarded it with hamachi or any other Ogarunlimited,io is client and its same as agario client any1 with any port forwarded server can connect to his ,stop making, or get banned. close?

**Comment by elitajmx** [comment]
ok

**Comment by Ckicky** [comment]
YASYYYYYY

**Comment by SorryAgario** [comment]
@Martinali12  then teach us how to portforward with hamachi. the traditional way was just turn ogar on then go to hamachi make a server then type the credentials on ur friends pc then copy the ipv4 address then go to agar.io/?ip=ipv4:port then it works.......

**Comment by elitajmx** [comment]
yeah

**Comment by Martinali12** [comment]
why do we need hamachi ? you know that you can host on c9.io for 12 hours after that will get blocked 
with 2.5GBram and good bandwidth  internet after you get blocked delete cookies and make new account its not gonna take that much to accounts you can even put fake email

**Comment by Martinali12** [comment]
its the same as agar.io/ip?= but when go to play.ogaruk.tk just put ur ipv4 and port that ur friend send to u. its the same both are client.

**Comment by firelightning13** [comment]
@Martinali12 #630 #564 

That's a really bad idea

**Comment by Martinali12** [comment]
I dont have any other option .........................
