### ISSUE TITLE
Ogar white screen

### ISSUE THREAD

**Issue by Aanis12** [AJS-development/Ogar-unlimited#694]
the server/consol runs fine but when i write the port with ip (agar.io/?ip=000.000.0.00:443)
a white screen comes when i do dark theme still a white screen with grid comes when i press F12 its changes to full white please help i tried updating reinstalling updateall still no luck

**Comment by Martinali12** [comment]
agario client not working use www.play.ogarul.tk and make sure to  put (127.0.0.1:443) and it should work.

**Comment by Aanis12** [comment]
it says site canot be reached

**Comment by Aanis12** [comment]
oh i removed www. and wrote  play.ogarul.tk and worked thx

**Comment by Martinali12** [comment]
http://play.ogarul.tk/

**Comment by Martinali12** [comment]
close isseu then

**Comment by LegitSoulja** [comment]
@Aanis12 Wow, Thanks for pointing that out. I will fix that www. so that it can be used.
