### ISSUE TITLE
I dont know what :TypeError: "callback" argument must be a function at exports.setTimeout (timers.js:314:11) at GameServer.mainLoop (C:\Users\action\OneDrive\Documents\Bandicam\Ogar-unlimited-master\src\core\GameServer.js:1471:7) at tryOn Immediate (timers.js:543:15) at processo Immediate [is immediate Callback] (timers.js:523:5) means

### ISSUE THREAD

**Issue by JakeTDC** [AJS-development/Ogar-unlimited#695]
TypeError: "callback" argument must be a function at exports.setTimeout (timers.js:314:11) at GameServer.mainLoop (C:\Users\action\OneDrive\Documents\Bandicam\Ogar-unlimited-master\src\core\GameServer.js:1471:7) at tryOn Immediate (timers.js:543:15) at processo Immediate [is immediate Callback] (timers.js:523:5)
whats does this mean

**Comment by SorryAgario** [comment]
So u need to install ogar with Node.js 5.9.0 in order to install the dependencies properly https://nodejs.org/download/release/v5.9.0/win-x64/ click the "node.exe" ones make sure to uninstall the other one first......

**Comment by SorryAgario** [comment]
closed?

**Comment by firelightning13** [comment]
@JakeTDC See here if you have trouble running your server #638 

Also, **DONT PASTE YOUR ERROR LOG IN THE TITLE, INSTEAD, DO IT IN DESCRIPTION ONLY!**
