### ISSUE TITLE
Any Other hosting site that i can use for free that does not block you and that allows use of the console

### ISSUE THREAD

**Issue by VSabertail** [AJS-development/Ogar-unlimited#698]
My friend was banned from c9.io but i was not yet so i don't want to be banned so tell me if  there is any other hosting site that i can use for free that does not block you and has performance just like c9.io

**Comment by VSabertail** [comment]
List me the sites here ill test them the one that is best for me! Sorry for making a issue i know i might get banned after making this but i just really want to know

**Comment by ItzLevvie** [comment]
https://github.com/AJS-development/Ogar-unlimited/issues/687#issuecomment-220808172
