### ISSUE TITLE
How does SuperMinions plugin work?

### ISSUE THREAD

**Issue by Tokoagar** [AJS-development/Ogar-unlimited#699]
How does the SuperMinions plugin work ? I play with start mass 150 and I do superminion 1 10 SuperBot 10 65 and they spawn whit 150

**Comment by Tokoagar** [comment]
with*

**Comment by Martinali12** [comment]
superminion [playerid] [amount] [name] [spawnmass] [speed]

**Comment by Martinali12** [comment]
It works for me

**Comment by LegitSoulja** [comment]
@Tokoagar 
- Plugin Usage
superminion [playerid] [amount] [name] [spawnmass] [speed] 

- Install
plugin install SuperMinions

**Comment by Tokoagar** [comment]
Thanks
