### ISSUE TITLE
BUG WITH PAUSE

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#7]
typing *pause* will not pause the game, this instead: 
[console] paused the game.
[autopause] Resumed The Game!
the game won't pause without autopause unpausing it.

**Comment by Andrews54757** [comment]
Oh, il fix it

**Comment by Andrews54757** [comment]
Currently though, you can disable the Autopause by going to gameServer.ini

**Comment by Agarian** [comment]
also splitting at max mass splits the cell to left corner.

**Comment by Andrews54757** [comment]
I fixed both those bugs

**Comment by Agarian** [comment]
could you add ejected mass collision and smooth split like in https://github.com/ItzLevvie/Ogar-1 ?
THAT WOULD BE AWESOME. its also the only thing i dislike about this build (no offense) the fact that the splitting is like teleportation.

**Comment by Andrews54757** [comment]
i will look at it

(oh and I also fixed the secound bug just now)

**Comment by Agarian** [comment]
ok then again thank you.

**Comment by Andrews54757** [comment]
also, for smooth split, this also can have smooth split. just go to Gameserver.ini and change smooth split to 1

**Comment by Agarian** [comment]
O_o

**Comment by Andrews54757** [comment]
can I close this now?

**Comment by Agarian** [comment]
yes

**Comment by Agarian** [comment]
btw smooth split is really buggy

**Comment by Andrews54757** [comment]
I know. But I will improve

**Comment by Andrews54757** [comment]
(Note I have already implemented ogar -1's smoothsplit but not in this branch. it is in the branch called Smooth. The reason I didnt make it into master was that it seemed like the player was gliding too much)

**Comment by Andrews54757** [comment]
I also just added the collision for ejected mass

**Comment by Andrews54757** [comment]
I also added more code so the SmoothSplit option should be MUCH better
