### ISSUE TITLE
Spamming console

### ISSUE THREAD

**Issue by mogokcp** [AJS-development/Ogar-unlimited#70]
Console] 2ch.hk Made a new high score of 1743
[Console] 2ch.hk Made a new high score of 1754
[Console] piccolo Made a new high score of 1768
[Console] 2ch.hk Made a new high score of 1780
[Console] 2ch.hk Made a new high sco

How i can disable this? sorry if its obvious =P

**Comment by Andrews54757** [comment]
You can disable this and it should be disabled by default

**Comment by Andrews54757** [comment]
You disable it at gameserver.ini
```
showtopscore = 0
```

**Comment by mogokcp** [comment]
k

**Comment by Agarian** [comment]
@mogokcp u still alive? lol
