### ISSUE TITLE
AgarioHub Submission

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#700]
Website: http://agariohub.tk

If you would like your server to be displayed over at my hub please provide your server information

- Server ip/address
Your server address.

- Server Game Port
Your server game port 

- Server Stat Port
Your server game stat port

- Server Gamemode
Your server game mode

- Server Name
Your server unique name

- Server Client (0 = ogarul client, 1 = agar.io client, or custom link to client)
Your server client usage.

- Server OgarConsole Port
Provide your OC port, and username upon registration to use on site OgarConsole

- Your username on site.
Provide your site username. This will give you access to modify your game server at any time.

**If your game server is localhost, don't even bother submitting.**

_Please note that your stat port has to be active upon submitting. Stat port are used to determine if the site is online, and is used to gather information like bots, players, gamemode, and etc to keep records. If your stat port is not valid nor is not active your game server will not be added to the hub._

_If you do not provide a username for your server, you will not have abilites to update your server in the future if there are changes. Please register before you submit and provide you registered username. Thanks_

**Comment by kojin323234545** [comment]
plz and a server named bot party and add the plugin of giveMiniontstoo it would be so good

**Comment by SorryAgario** [comment]
please make 2 private servers with the original mechanics

**Comment by ErikParacelsus** [comment]
@SorryAgario lol this is a create server service lol

**Comment by SorryAgario** [comment]
@ErikParacelsus I didnt say that I just suggested that the fact that many ppl want to practice their splitrunning..... also Im just telling

**Comment by LegitSoulja** [comment]
@ErikParacelsus it's cool

@SorryAgario Yes, I would add a vanilla ffa.

**Comment by fayizan** [comment]
@LegitSoulja I would like to submit my server details,where to submit..?
