### ISSUE TITLE
Installation error for dependamcies

### ISSUE THREAD

**Issue by notcarksss** [AJS-development/Ogar-unlimited#702]
npm WARN package.json Ogar_Unlimited@16.1.5 license should be a valid SPDX license expression

**Comment by notcarksss** [comment]
Ok i fixed that error but, i use http://agar.io/?ip=localhost:443 to connect to the server and it loads up like this: http://prntscr.com/b75iz6 which is annoying

**Comment by ItzLevvie** [comment]
Use play.ogarul.tk

**Comment by notcarksss** [comment]
Oh k ty :D

**Comment by notcarksss** [comment]
Ah
im using that link same thing but this time, the ogar ul cmd thing shows this error
http://prntscr.com/b765ct

**Comment by notcarksss** [comment]
oh, and this: http://prntscr.com/b7680w

**Comment by ItzLevvie** [comment]
The license can be ignored

**Comment by notcarksss** [comment]
Yes i know that but the main error is this: http://prntscr.com/b765ct

**Comment by Andrews54757** [comment]
sorry, il fix

**Comment by notcarksss** [comment]
K ty

**Comment by notcarksss** [comment]
I'm off my pc and on phone now so ill try tomorrow, tell me when you have fixed it
