### ISSUE TITLE
How He Did This ?!!!!

### ISSUE THREAD

**Issue by kareemman00** [AJS-development/Ogar-unlimited#705]
https://www.youtube.com/watch?v=BX63JWupyo8

I watched this vid And Wonder how he Did This !!!! HOW I Tried And Didn't got any thing on the screen on the leaderboard and My server work on your client and my Client Please Tell ME HOW !!!!

**Comment by LegitSoulja** [comment]
Hey, you should discuss about it over here http://forum.ogarul.tk

**Comment by NatsuTheGreat** [comment]
This guy is using this program.

**Comment by David1ali12** [comment]
its super easy I always do this for bots put </random> then the name use bagario ext then in config change packer version to 0 and it will work .
