### ISSUE TITLE
How do you use old packet?

### ISSUE THREAD

**Issue by koenoe42** [AJS-development/Ogar-unlimited#706]
Pardon my ignorance but how do you use old packet? I wanted to use skin but I am unsuccessful as I am not able to see the result despite using <spy>, <kraken> etc on the client, play.ogarul.tk. With the bagar.io extension I am able to connect to the server with agar.io but all I see is white screen issue similar to #656 and the solution is to use old packet, which I have no idea how.

**Comment by David1ali12** [comment]
in config you have packet version at very last.

**Comment by koenoe42** [comment]
Yeah I figure it out, apparently I am already using old packet and I am still unable to play my server on agar.io. Is there any other way for me to use skin or is it currently unavailable?

**Comment by David1ali12** [comment]
Skype:david ali-09

**Comment by Andrews54757** [comment]
Unavailable. Will be available soon
