### ISSUE TITLE
Blank screen 

### ISSUE THREAD

**Issue by 3ND3RDRAG0NSSS** [AJS-development/Ogar-unlimited#707]
Whenever i click start, the command prompt will work fine, but when i go to agario and click play, it just shows a blank screen with the grid background. There were no food or viruses and my cell. Also, why is my gameserver.ini gone? I dont remember deleting it

**Comment by ItzLevvie** [comment]
Use play.ogarul.tk instead of the official agario client.

**Comment by 3ND3RDRAG0NSSS** [comment]
Thanks it worked

**Comment by Megabyte918** [comment]
troubleshooting guide

**Comment by Agarian** [comment]
lol

**Comment by wiz1211** [comment]
It still didn't work for me. And I wanted to use agario powerups extension.

**Comment by Agarian** [comment]
that is wayy patched...

**Comment by wiz1211** [comment]
Its still working actually, just that I cant fix the blank screen issue...

**Comment by Agarian** [comment]
wait u fixed it? lemme see

**Comment by Agarian** [comment]
unless ur using the one with the name "hellcat" that was my leaked 1...

**Comment by wiz1211** [comment]
im using the hellcat powerups.

**Comment by Agarian** [comment]
thats my leaked extension =/
its because of the packet version, set packetversion to 0

**Comment by wiz1211** [comment]
What do you mean by packetversion?
