### ISSUE TITLE
Please take this form. Be honest as this will effect our future

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#708]
https://docs.google.com/forms/d/1rl2eGtb3CHw8ZHg9RQ9_0psog9lUPyIbGIACJaAd4Pk/viewform.

Please take it

**Comment by David1ali12** [comment]
yea we should use vanila client

**Comment by Agarian** [comment]
@David1ali12  no bro, that would break soo many features

**Comment by Andrews54757** [comment]
Surprising how most people said to abandon our client and how they put skins last

**Comment by David1ali12** [comment]
Why not making an ext like bagario with all features that we want.

**Comment by Andrews54757** [comment]
because moneyclip hates extensions the most

**Comment by Agarian** [comment]
i want skins the most and want to keep using OUR client

**Comment by Megabyte918** [comment]
I filled it out, I hope I'm not too late

**Comment by problemsofworld** [comment]
Dude the play.ogarul.tk sucks it converting slowly to like copy of agario games agar.lat , agar.xs etc
I liked it ogarUnlimited because it was like vanila agario and now its just looks like a crap copy of agario .

**Comment by Andrews54757** [comment]
We will support both.

**Comment by Andrews54757** [comment]
but we just wanted to see the general consensus

**Comment by Agarian** [comment]
I forgot problemsofworld got unbanned today

**Comment by bean07** [comment]
9+10=21 genius
