### ISSUE TITLE
Blank Screen Problem

### ISSUE THREAD

**Issue by XenoIsBack** [AJS-development/Ogar-unlimited#709]
My Ogar Loads Correctly Last Version 
![last](https://cloud.githubusercontent.com/assets/19531453/15469874/627152a2-20ed-11e6-923f-6f5266471d1c.PNG)
But when i go to this website http://play.ogarul.tk/ Its blank
![blank](https://cloud.githubusercontent.com/assets/19531453/15469924/8bb316f0-20ed-11e6-8501-62b5077b91e7.PNG)

**Comment by kareemman00** [comment]
downgrade the Node To 5.9.0 And You Done With It

**Comment by XenoIsBack** [comment]
@kareemman00 How please ? what command should i type in cmd

**Comment by kareemman00** [comment]
not should write any thing just download it from here https://nodejs.org/download/release/v5.9.0/

**Comment by Andrews54757** [comment]
in cmd do 'npm install -g n`. then do `sudo n 5.9.0`. then restart

**Comment by XenoIsBack** [comment]
@Andrews54757 Thanks and please unban my other XenoYT account ;-;

**Comment by Andrews54757** [comment]
Yes, your ban is expired today

**Comment by XenoIsBack** [comment]
@Andrews54757 it says no sudo known ;-;

**Comment by XenoIsBack** [comment]
@Andrews54757 i did -g n thingy but when i did the sudo thing it doesnt work

**Comment by XenoIsBack** [comment]
@Andrews54757 Its says Sudo not knows im using not mac im using windows

**Comment by Andrews54757** [comment]
what sudo -g thingy

**Comment by XenoIsBack** [comment]
@Andrews54757 Nevermind its worked now thanks but i voted for ogar client its better dude this no skins :/
