### ISSUE TITLE
Quiz

### ISSUE THREAD

**Issue by kareemman00** [AJS-development/Ogar-unlimited#710]
When You Will Done With Skins ???
Can You Add Other Client Or Fix This ****** BUGS AND ADD MORE Things :sweat_smile:

**Comment by XenoIsBack** [comment]
Obama Doge Trump skins are not working add more skins please

**Comment by Andrews54757** [comment]
How many times do I have to say that i will do this later?

**Comment by XenoIsBack** [comment]
@Andrews54757 can i help you make skins just tell me what to do :) i really wanna help

**Comment by XenoIsBack** [comment]
@Andrews54757 Honesty play.ogarul is better than ogar client its so smooth and less laggy

**Comment by LegitSoulja** [comment]
@XenolsBack what experience do you have?
