### ISSUE TITLE
How to connect to ur Server with skins ? [info] [tutorial]

### ISSUE THREAD

**Issue by David1ali12** [AJS-development/Ogar-unlimited#711]
# Alot of ogarUL users have been asking for skins and making issues here is tutorial how you can use. and legal 
because our client have some bugs and no skins and it makes us sad :(.

1- You need bagario ext . [click to download](https://chrome.google.com/webstore/detail/bagar-helper/belokgdnlmnagchjjhcdgkmfdplnofei) click to download

2- You need old packet [click](https://mega.nz/#!CV8GDZib!cyxDcGXlpsucOURF9hge0A5BY6kYBBO4iqa6oYEbf7s) 
 just delete packet folder and replace with this 

3-Go to Agar.io/?ip=ur server ip and port running on pc `http://agar.io/?ip=127.0.0.1:443` [click](http://agar.io/?ip=127.0.0.1:443) here 

4-`<skinnames>`

- for user `</skins name>`.
- random skins `</random>`  .
- random names `/random`.

## Note:You can also use Agarplus(the new version) as long as you are using old packet [kuro+ download link](http://gdriv.es/agar_main_files/PublicAgar/KZx.user.js)

- To connect to ur Server put ur serverip and port then press join Example `ws://127.0.0.1:443`.
- If you getting kicked go to misc tab and press fix private server kicking.

### **Result** 
![result](https://cloud.githubusercontent.com/assets/17472593/15471370/4292667c-20fe-11e6-877d-2d15c7f6734c.PNG)

### Q:Can  minions split by pressing E or R key?
A: am not sure maybe we can use A&D because bagario ext have it I have not tested.
===============================================================================
## Note:if Q is not working 
set useER to 0 in config.ini

**Comment by Andrews54757** [comment]
We do not support bagar

**Comment by XenoIsBack** [comment]
@Andrews54757 Andrew do you want me to make some agario skins in imgur and link you them ?

**Comment by Agarian** [comment]
i already have all agar premium skin.

**Comment by XenoIsBack** [comment]
@Agarian Please link me them + Veteran :P

**Comment by maciej441** [comment]
what is decryption key on https://mega.nz/#!CV8GDZib

**Comment by Agarian** [comment]
http://agarian9876.imgur.com/all/

**Comment by Agarian** [comment]
@David1ali12 if you offer a download, make sure to make it available. It has a decryption key. Plus we should really stick with our official client

**Comment by David1ali12** [comment]
https://mega.nz/#!CV8GDZib!cyxDcGXlpsucOURF9hge0A5BY6kYBBO4iqa6oYEbf7s

**Comment by Andrews54757** [comment]
you could just set packetversion to 0

**Comment by bangana** [comment]
this.PressQ is on true and still can't split dem :'(

**Comment by David1ali12** [comment]
I dont know about that dont ask me it works for me  ;-;

**Comment by elitajmx** [comment]
skins on play.ogarul.tk would be awesome

**Comment by problemsofworld** [comment]
q not working at all .

**Comment by Andrews54757** [comment]
set `useER` to 0 in config.ini

**Comment by problemsofworld** [comment]
thx Andrew it worked

**Comment by NeptoonYT** [comment]
I am using Bagar and when I press Q it does nothing.. and yes I turned usER off what can I do :/

**Comment by Andrews54757** [comment]
Bagar probably doesnt support q then. Try op.

**Comment by David1ali12** [comment]
it does work for me

**Comment by paulo364gamer** [comment]
@David1ali12   how can I set the User to 0?

**Comment by David1ali12** [comment]
does not work anymore reason :-1: miniclip again  fuck this shit (outdated)skins dont work

**Comment by David1ali12** [comment]
![lolss](https://cloud.githubusercontent.com/assets/17472593/15547047/dc58e6b6-22aa-11e6-84f1-546adf6efed1.PNG)
