### ISSUE TITLE
how to connect ?

### ISSUE THREAD

**Issue by cinicz** [AJS-development/Ogar-unlimited#712]
hello, i can't connect i have blank screen.
Bagar helper glitch the game :

![213](https://cloud.githubusercontent.com/assets/17525852/15473940/d30c3738-2102-11e6-9972-fcb99e7bcbe1.PNG)
 

Your client have many bugs.

**Comment by Agarian** [comment]
this is cause of the packet version

**Comment by Andrews54757** [comment]
bagar is not supported but to use it, set packetversion to 0
