### ISSUE TITLE
BotNames

### ISSUE THREAD

**Issue by XenoIsBack** [AJS-development/Ogar-unlimited#714]
How to do for bots realistic names + skins im using old packet btw

**Comment by David1ali12** [comment]
in settings>config change botrealnames to 1 
it will get skins itself lol
close?

**Comment by David1ali12** [comment]
you will get banned three duplicate issues @Andrews54757

**Comment by Andrews54757** [comment]
Do some research. Do some exploring. This is why I banned you in the first place, dont make me do it again. Use `/random` for random names and `</random>` for random skins
