### ISSUE TITLE
Minions Help

### ISSUE THREAD

**Issue by XenoYT** [AJS-development/Ogar-unlimited#717]
Guys Dont ban me again but i really need your help someone give me steps to controll minions again when i do packet to 0 help please i spammed with my alt becuz the issues didnt show to me in github and im sorry

**Comment by David1ali12** [comment]
close issues before get banned again :D just joking XD

**Comment by XenoYT** [comment]
@David1ali12 Help meh ;-;

**Comment by kareemman00** [comment]
i can help you fb.com/kareem.olim

**Comment by Andrews54757** [comment]
change useER to 0 in config.ini
