### ISSUE TITLE
MINION SUGGESTION!!

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#719]
Waddup yall cunts there, hope yall have a bad day.
lol jk, anyways the suggestion is this:
It could have like a letter to press for ex. h, then minions will go get food if you know what i mean? they wont come to you but pick up food and try to get big,after pressing h again they will come to you by normal. Basically that food picking up is called the blind mode for minions yall know that already.

Hopefully it's a good suggestion!
P.S. Don't ban me, just a SUGGESTION

**Comment by Agarian** [comment]
oh so if you Press H, the minions pretty much act like bots?

**Comment by Agarian** [comment]
this should REALLy be in suggestions area!

**Comment by elitajmx** [comment]
yeaa

**Comment by Andrews54757** [comment]
In the future i will add this

**Comment by elitajmx** [comment]
awesome
