### ISSUE TITLE
Cant move... 

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#722]
What game mode were you in when you had the issue?
default
What version are you on?
default

What command did you type if any?
downloaded node 5.9.0
You must have a description as well
?
Most common questions involve:
?
Cant move...
http://prnt.sc/b7mtfp

**Comment by David1ali12** [comment]
###did you change packet to 0 in Advconfig ?

**Comment by firelightning13** [comment]
You can't use agar.io, use custom client instead: http://play.ogarul.tk/

**Comment by David1ali12** [comment]
You must change packet to 0 but ogarUL dont support agar.io client which means you will not have full features of OgarUL.

**Comment by raphyjb** [comment]
o really that means i need poeple to go on a site to join my private server

**Comment by David1ali12** [comment]
Just change packet to 0 or use play.ogarul.tk -_-

**Comment by raphyjb** [comment]
can we use extensions?

**Comment by Agarian** [comment]
for some reason. changing packetversion to 0 doesn't fix anything.

**Comment by systemroot** [comment]
with extensions is not working for me, 
So try to disable your extension.

**Comment by GhostShot3** [comment]
@raphyjb How did you do to get in? I can not please connect me speak like you did it.

**Comment by David1ali12** [comment]
try with this packet https://mega.nz/#!CV8GDZib!cyxDcGXlpsucOURF9hge0A5BY6kYBBO4iqa6oYEbf7s and close this issue .

**Comment by Agarian** [comment]
who TF still uses an extension? attempting to even play on the server with packetversion set to 0 craches my browser instantly (freezes it)

**Comment by raphyjb** [comment]
Ghost i when in Console of Google chrome and wrote connect('ip'port)
not real complicated..

**Comment by raphyjb** [comment]
Can close the thread I got it by thanks firelightning13
