### ISSUE TITLE
No Issue need help :D

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#723]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
No issue need help
What version are you on?
default
What command did you type if any?
nothing
You must have a description as well
Help
Most common questions involve:

Big question of the day. how can we make poeple join the server and have 5 minions when they join?

**Comment by LegitSoulja** [comment]
Try the givememinionstoo plugin.. Or you could create a plugin to give everyone that joins minions.

**Comment by TDashDog1** [comment]
Unfortunately, I'm not a developer. Any slim chance of someone making a plugin?

**Comment by LegitSoulja** [comment]
@TDashDog1 sure.. What type of plugin though?

**Comment by TDashDog1** [comment]
@LegitSoulja The one mentioned above. 

> how can we make people join the server and have x amount of \ minions when they join?

**Comment by LegitSoulja** [comment]
@TDashDog1 Yea, I'll have the plugin finished in a minute

**Comment by TDashDog1** [comment]
Holy crap thanks

**Comment by LegitSoulja** [comment]
@TDashDog1 @raphyjb Done

[MinionStarter.zip](https://github.com/AJS-development/Ogar-unlimited/files/280688/MinionStarter.zip)

**Comment by LegitSoulja** [comment]
There's a config file. Make sure you change it to your needs.

**Comment by TDashDog1** [comment]
@LegitSoulja While the plugin is great, it adds minions every time you die and respawn. Could you potentially fix that?

**Comment by LegitSoulja** [comment]
@TDashDog1 You mean as it repeats right? Adding minions everytime you die?

**Comment by LegitSoulja** [comment]
@TDashDog1 
[MinionStarter.zip](https://github.com/AJS-development/Ogar-unlimited/files/280762/MinionStarter.zip)

**Comment by Andrews54757** [comment]
@LegitSoulja I cleaned up your code and did what @TDashDog1 wanted. 
[MinionStarter.zip](https://github.com/AJS-development/Ogar-unlimited/files/280763/MinionStarter.zip)

**Comment by Andrews54757** [comment]
@LegitSoulja It is not good practice to put a global variable such as `exports.gameServer`. You should do in init `this.gameServer = gameServer` instead.

**Comment by LegitSoulja** [comment]
@Andrews54757 I couldn't get the gameServer using that xD. I had no other way.
