### ISSUE TITLE
 I just updated and I swear a bot teamed with me O_o Wtf 

### ISSUE THREAD

**Issue by David1ali12** [AJS-development/Ogar-unlimited#725]
today I updated and I was playing I feed a bot and he feed me back and I split into him and then he split into 8 pieces and then go into me is that normal 
O-o

**Comment by LegitSoulja** [comment]
@David1ali12 Are you suprised??

**Comment by David1ali12** [comment]
yes am sure that he teamed with me

**Comment by David1ali12** [comment]
they are teaming wow how this I i thought its impossible  you guys are gods :D :+1:

**Comment by bangana** [comment]
lol yeah happened to meh 2 the most annoying thing is reverse tricksplit me '-' they actually did omg i got soo pissed

**Comment by Andrews54757** [comment]
lol. My code is sometimes too good

**Comment by Andrews54757** [comment]
I added teaming and more smarts in the update. thats why

**Comment by David1ali12** [comment]
they only thing missing if player is smaller 90% he will feed and if 25% he split into him Great job btw

**Comment by Andrews54757** [comment]
also, I am pretty sure you are davidmann. Do you really have to fork and star your own repos? really, I think it is immoral.

**Comment by David1ali12** [comment]
nah :p am not david man :P am new to github

**Comment by LegitSoulja** [comment]
@Andrews54757 lol well somebody have too xD, I don't know about a forked project though :/
