### ISSUE TITLE
Weird rigid body behaviour

### ISSUE THREAD

**Issue by pcmxms** [AJS-development/Ogar-unlimited#726]
What version are you on? 2.0.3

Whenever a rigid body stays with its center of mass away from an edge, it should starts rotating. The expected behaviour happens only if the collision shape is in one (maybe more) particular rotation state:

https://media.giphy.com/media/3oAt28ng9R3avLQVry/giphy.gif

**Comment by Andrews54757** [comment]
wrong project. I dont know what that is

**Comment by LegitSoulja** [comment]
Wth lol.. What is this?

**Comment by Megabyte918** [comment]
i dont even know what to say hahaha

**Comment by Andrews54757** [comment]
he meant to post it here: https://github.com/godotengine/godot/issues/4801

**Comment by pcmxms** [comment]
Yep. Sorry about that.
