### ISSUE TITLE
OgarConsole

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#730]
If you are using the OgarConsole plugin please delete the OgarConsole folder in plugins and reinstall it. It has been updated and recoded to a plugin use, with a update functionality for better support.
**Install Usage**
> plugin install OgarConsole

**Whats New?**
- New Console Commands **refresh**(-r, r, -refresh), **update**(-update), **exec**(-exec)
- **Update Functionality**
- **New Coding Layout**
- **New Colors**
- **New Console UI Update**
- **Added Configuration File**(Edit password, and other disables & enables)

**P.S**: 
> OgarConsole was never a plugin, but v1.0.4 of OgarConsole for OgarUl it became a plugin, > v1.0.5 > became 100% plugin functional with updates :).

Any features ideas, or additions please leave below. I'm all about ideas.

**Comment by Tokoagar** [comment]
Nice installing it !

**Comment by Andrews54757** [comment]
or you can do `plugin update`

**Comment by Tokoagar** [comment]
@Andrews54757 Can you add a stop move control and you can move the bots?

**Comment by Andrews54757** [comment]
?

**Comment by LegitSoulja** [comment]
@Tokoagar pausable bots? And move how?

**Comment by Agarian** [comment]
I find it **EXTREMELY** annoying that minions spawn in the corner when I'm huge, and I cannot do anything about it... (setting safeSpawn to 0 does not do anything to fix it.)

**Comment by LegitSoulja** [comment]
@Agarian aren't you a developer? Aren't you supposed to figure these things out and fix it? I mean, I would but I was invited not knowing much about ogarul in the end, and not really part of the development side of OgarUl.

**Comment by Megabyte918** [comment]
@Agarian can you by chance make a gif of it happening? i dont understand

**Comment by NatsuTheGreat** [comment]
@Agarian Well if they spawn in the corner, and you're a circle and big... Obviously safeSpawn is doing something. If what I am talking about is not close to what you are talking about... Like MegaByte said, send us a gif.

**Comment by NeptoonYT** [comment]
@LegitSoulja I think @Tokoagar means that he wants to be frozen whilst moving the bots at the same time. And to answer his question, you'd just have to go into the console and type "freeze (your player ID)

**Comment by Agarian** [comment]
@NatsuTheGreat i will when i have the time.

**Comment by firelightning13** [comment]
@Tokoagar More like mind control? B)

**Comment by bangana** [comment]
yeah we need some shortcuts like D to stop user cell and F to stop bots from moving ect .. :')

**Comment by Agarian** [comment]
the bots freeze is already a feature. use T, you need to use the ogarul client.

**Comment by Tokoagar** [comment]
@NeptoonYT Yes I mean that!

**Comment by Agarian** [comment]
I suggested that, pressing S in agar powerups would freeze the cell. That was in it's hayday...

**Comment by tg170** [comment]
help
![ogarconsole issue 730 ajs-development_ogar-unlimited](https://cloud.githubusercontent.com/assets/18076173/15581366/e0c7f976-2363-11e6-8e67-5cf93b68f44e.png)

**Comment by LegitSoulja** [comment]
@tg170 how did it happen?

**Comment by LegitSoulja** [comment]
@tg170 You could may can fix it if you take this patch 
[modules.zip](https://github.com/AJS-development/Ogar-unlimited/files/284800/modules.zip)

replace the modules folder. Not the node_modules though.

**Comment by tg170** [comment]
can you specfie it more step by step

**Comment by NeptoonYT** [comment]
@Tokoagar No problem :)
