### ISSUE TITLE
getNextId is not defined

### ISSUE THREAD

**Issue by RasyiidWho** [AJS-development/Ogar-unlimited#734]
![capture](https://cloud.githubusercontent.com/assets/19422415/15515349/91d2ad06-21a2-11e6-828d-bd654c2592a1.PNG)

**Comment by CalvinDKHD** [comment]
I got the same problem

**Comment by RasyiidWho** [comment]
Can't use command :(

![capture](https://cloud.githubusercontent.com/assets/19422415/15515650/2318614c-21a4-11e6-8890-966f08ada546.PNG)

**Comment by CalvinDKHD** [comment]
Same.

**Comment by AlexFreeze** [comment]
I am gonna cry ;(

**Comment by LegitSoulja** [comment]
@AlexFreeze @CalvinDKHD @RasyiidWho Fixed it. Use the update command.

**Comment by LegitSoulja** [comment]
Redownload the zip file, and get the file from the core folder and replace it with the one thats messed up.
