### ISSUE TITLE
getNextId not defined

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#735]
hey! So i have the same problem as RasyiidWho.
When i run the new version this error happens.
![91d2ad06-21a2-11e6-828d-bd654c2592a1](https://cloud.githubusercontent.com/assets/18939977/15517503/614cab2c-21f8-11e6-8cef-d17776e52dbf.PNG)

And i cant type anything.

**Comment by LegitSoulja** [comment]
@CalvinDKHD I fixed it.

**Comment by LegitSoulja** [comment]
Redownload the zip file, and get the file from the core folder and replace it with the one thats messed up.
