### ISSUE TITLE
Why me cell is black,i can't play , please help me

### ISSUE THREAD

**Issue by Okay111** [AJS-development/Ogar-unlimited#736]
Please help me,
When i play,my cell is black and i can't play,i see the leaderboard but i cant play
Thanks you

**Comment by David1ali12** [comment]
[play.ogarul.tk](play.ogarul.tk)  or  inconfig change packet to 0

**Comment by Okay111** [comment]
how packet ?

**Comment by Megabyte918** [comment]
in /src/settings/config.ini

**Comment by Andrews54757** [comment]
no, change packetversion to 1. only change to 0 if using bagar
