### ISSUE TITLE
How to make multiple servers?

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#738]
Hello! So i got the client etc to work!
And i did `multiverse create Party1 5421`
And i added the servers in the HTML - https://gyazo.com/fc1df7a22273502126d539551e8c781a
 but Party1 is not working! / https://gyazo.com/f1031bd7b90b28a57ff90feaf6c8332a

**Comment by DarkZYT** [comment]
try play.
Ogarul.tk

**Comment by DarkZYT** [comment]
i mean : http://play.ogarul.tk

**Comment by CalvinDKHD** [comment]
Yes, but i am aiming to make my own server. - like this agarextreme.ml Which run on cigar and is mine but i want to switch over to ogarUL

**Comment by DarkZYT** [comment]
Ok ... close ?

**Comment by CalvinDKHD** [comment]
Well almost, i just need to fix the issue.

**Comment by CalvinDKHD** [comment]
Please someone help me.

**Comment by LegitSoulja** [comment]
Cigar.. Right?

**Comment by CalvinDKHD** [comment]
yes, but i want to move to ogarUL since it is better and has more options. I just need to fix that problem.

**Comment by LegitSoulja** [comment]
When you added the options, you also need to write a script to connect to that specific extra multiverse server, or it will just connect to the main.

**Comment by CalvinDKHD** [comment]
How do i write the script? I am not experienced in coding. Can you link me a copy?

**Comment by LegitSoulja** [comment]
You could easily set a class, or id for the options,
and with jquery you can use a click event.

**Comment by xMuratY** [comment]
Make a connect script in index.html

Example 

Option 1 ; value = "ws://ip:port"

Make onchane ; "connect($this.val())

**Comment by LegitSoulja** [comment]
You could also capture the select change, and connect to the option value.

**Comment by LegitSoulja** [comment]
for example
```
var option = $('option:selected', this).attr('connection');

```
< option connection="ip:port">My Multiverse Server< /option >



or
```
$('option').click(function(){
connect(this.attr('connection').toString());
});
```

**Comment by CalvinDKHD** [comment]
Is that what i will have to put in the main_out.js in Client?

**Comment by LegitSoulja** [comment]
Nope, index.html.

**Comment by CalvinDKHD** [comment]
The connection part, is that only the port? or ip aswell?

**Comment by LegitSoulja** [comment]
YES

**Comment by LegitSoulja** [comment]
Also, it would be best to give options a unique class name, or id to prevent other options to activate it.

**Comment by CalvinDKHD** [comment]
Sorry, but did you say yes to ip and port? or just port? xD

**Comment by CalvinDKHD** [comment]
And what do you mean by options?

**Comment by LegitSoulja** [comment]
ip and port, or you could save a static ip and just use that, and the port.

and option as in the element. < select>< option>< /option>< /select>
