### ISSUE TITLE
[Annoucement] OgarUnlimited.io Feature : Skins Extension

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#739]
Hello @Andrews54757 I'm creating an OgarUnlimited.io Extension , im working on it wich everyone can use skins (premium and veteran ones) , do you think its good ? And what should i name this extension ?

**Comment by bangana** [comment]
Yeahh we want it reallt badd !! um btw i can't use skins on play.ogarul.tk is dat my problem or just everyone can't use it ?

**Comment by DarkZYT** [comment]
Yes im working on it , dont worry , noone can use skins !

**Comment by bangana** [comment]
Great im wondering if you are creating an extension with tamper monkey or not if so please try to creat one that allows me to hold W and R to feed with ogarul website :)

**Comment by DarkZYT** [comment]
Oh , are you looking for and extension to hold W or R ? i already have it

**Comment by bangana** [comment]
Yuuus could you pls send it to me that'll be awsome :D

**Comment by DarkZYT** [comment]
i dont know how to save it :P

**Comment by bangana** [comment]
xD

**Comment by bangana** [comment]
nvm i got one x) chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/options.html#nav=efa35ce6-c4ca-46c6-a413-4ed16210351d+editor

**Comment by XenoYT** [comment]
@DarkZYT When its done ? ;-;

**Comment by DarkZYT** [comment]
Im working on it , im adding also the controls : Hold W for fast feed , D for splitting 16 (tricksplit) , A for double-split , Z for split bots 16 (tricksplit) !

**Comment by XenoYT** [comment]
@DarkZYT Add R Fast feed for minions

**Comment by DarkZYT** [comment]
I tryed before , but doesnt work it keeps feeding after stop holding R but i will retry dont worry !

**Comment by XenoYT** [comment]
@DarkZYT all we want is  skins we can spam the R :3

**Comment by DarkZYT** [comment]
xD Sure !

**Comment by XenoYT** [comment]
@DarkZYT when your done just paste it here im so excited :)

**Comment by DarkZYT** [comment]
Me too :+1: :8ball:

**Comment by DarkZYT** [comment]
Want this extension for ogarul.tk or ajs-development.github.io/client ??

**Comment by XenoYT** [comment]
@DarkZYT play.ogarul.tk
pld

**Comment by LegitSoulja** [comment]
Both are the same...

**Comment by DarkZYT** [comment]
yeah

**Comment by LegitSoulja** [comment]
And we do not support extensions so tho will be closed. Skins will be back in the future :)

**Comment by XenoYT** [comment]
@LegitSoulja How to add skins theres no trump skins ;-;

**Comment by LegitSoulja** [comment]
Skins aren't implement in the client, and was obliterated on the server. They will be back in the future working with both clients.

**Comment by LegitSoulja** [comment]
You actually could get the skins working w/ agar.io without extensions

**Comment by XenoYT** [comment]
@DarkZYT when your done give meh the extension until devs add skins in the future :dancer:

**Comment by LegitSoulja** [comment]
And creating an extension or not won't work unless you modify OgarUL also.

**Comment by XenoYT** [comment]
@LegitSoulja how veterans ?

**Comment by XenoYT** [comment]
@LegitSoulja how to get veterans skin in ogarul ?

**Comment by CalvinDKHD** [comment]
LegitSoulja, can you please look at my problem?

**Comment by CalvinDKHD** [comment]
Its how to add multiple servers. Because i cant get it too work.

**Comment by DarkZYT** [comment]
Ok , i understood , i'm stopping this extension ...
