### ISSUE TITLE
HungerGames mod winner bug

### ISSUE THREAD

**Issue by xMuratY** [AJS-development/Ogar-unlimited#741]
winners mass dont reloading in hungergames mode

&& blackhole mode is have bigbugs

and ı using ogar ul client but have map bugs

my client : http://agar.hotteam.tk

> playerlist
[Console] Showing 13 players:
 ID         | IP              | NICK            | CELLS | SCORE  | POSITION
 ------------------------------------------------------------------------------
         40 | 78.179.42.26    | ----------------------------DEAD OR NOT PLAYING
         72 | 37.155.182.212  | xMuratY ^^      |     1 |    310 |   200,  4800
         73 | BOT             | <=========}==   |     1 |   5444 |  3396,  4730
         94 | BOT             | ackward         |     1 |    310 | -3200, -3200
         95 | BOT             | Wun Wun         |     1 |    310 | -3200, -3200
         96 | BOT             | W=Team          |     1 |    310 | -3200, -3200
         97 | BOT             | help me help u  |     1 |    310 | -3200, -3200
         98 | BOT             | Jumbo           |     1 |    310 | -3200, -3200
         99 | BOT             | An unnamed cell |     1 |    310 | -3200, -3200
        100 | BOT             | An unnamed cell |     1 |    310 | -3200, -3200
        101 | BOT             | my home is a cave |     1 |    310 | -3200, -3200
        102 | BOT             | Lvl 100         |     1 |    310 | -3200, -3200
        103 | BOT             | ᗯᗩᖇᗪ♜ кгк ♧     |     1 |    310 | -3200, -3200`

**Comment by Andrews54757** [comment]
fixed
