### ISSUE TITLE
Skins dont working

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#742]
Veteran skins (Shark,kraken,raptor etc) dont works in play.ogarul.tk

**Comment by David1ali12** [comment]
does not even work with bagario ext anymore miniclip FUCKIN FUCKING SHIT PATCHED THEM

**Comment by GhostShot3** [comment]
@David1ali12 Has no solution?

**Comment by David1ali12** [comment]
You can add customs skins but that ugly line around cell Idk how to remove it

**Comment by GhostShot3** [comment]
@David1ali12 How to add

**Comment by David1ali12** [comment]
costomsskins.txt put name the : then url address 
example `pepsi :http://i.imgur.com/K3Z5eGq.png`

**Comment by GhostShot3** [comment]
@David1ali12 In PlayOgarUrl dont works skins i think

**Comment by GhostShot3** [comment]
@David1ali12 Veteran like a kraken...

**Comment by Megabyte918** [comment]
Andrew said he is working on them

**Comment by LegitSoulja** [comment]
@GhostShot3 skins was never on the client, and was obliterated from the server. play.ogarul.tk never had skins :/

**Comment by GhostShot3** [comment]
@LegitSoulja :( Ok...
