### ISSUE TITLE
[Question] How to make nocollision ejected mass ?

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#747]

**Comment by Agarian** [comment]
i suggested this, andrews said he may do this

**Comment by GhostShot3** [comment]
@Andrews54757 How to make ?

**Comment by LegitSoulja** [comment]
@GhostShot3 if agarian just said andrew will do this, why ask how to? Just wait on it.

**Comment by GhostShot3** [comment]
@Legitsoulja Ok,because closed this inssue ?

**Comment by LegitSoulja** [comment]
It would be too much to explain for showing someone individualy on how to do this when this has already been suggested. It will be implemented in the future.

**Comment by GhostShot3** [comment]
@LegitSoulja  ok

**Comment by Agarian** [comment]
In one of the optin issues, it said todo next to the config

**Comment by Andrews54757** [comment]
i forgot about this. sorry

**Comment by GhostShot3** [comment]
@Andrews54757 No ploblem can add in next update ?
