### ISSUE TITLE
[Question] How to disable connect from f12 console on client

### ISSUE THREAD

**Issue by xMuratY** [AJS-development/Ogar-unlimited#750]
I need disable f12 console connect command

Hiding my game servers and blcoking connect from users on using my client

**Comment by LegitSoulja** [comment]
You could return false for those key events using jquery. But it's really not possible to hide information such as this.

**Comment by LegitSoulja** [comment]
You have **f12**, and **ctrl + shift + I** aswell

**Comment by xMuratY** [comment]
I working on it 

How i can make privating servers from advconfig.ini ?

And onchange=setgamemode($this.val()) in client how can i use this

And i checked config and if i make packetversion 0 game is doesnt playable but map working if i change advconfig mapping seeting 1 dont working again 

S: dimotsai minimap
