### ISSUE TITLE
Sorry, but i have no idea on how to use multiverse. xD. please help me in detail.

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#751]
Title says it. I have some idea but it is very complicated.
And when i do multiverse create [name] [port] an error occurs.
https://gyazo.com/b7225fd99bd6e7fb701842f3bab884c8
But it still seams that it has created the new server.

**Comment by LegitSoulja** [comment]
@CalvinDKHD nothing is wrong. It's the fact you made a new instance of a server, and it reloaded the client again which was already running on port 8080. Just ignore it.
