### ISSUE TITLE
LegitSoulja, sorry but i dont understand how to make multiple servers.

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#752]
Please add me on skype > calvin.leonhardt
I am having problems, i am sorry for disturbing you. And of course it is your choice not to help :)

Thank you, and sorry.

**Comment by LegitSoulja** [comment]
I don't understand why you keep creating new issues over and over again. It's pointless.

**Comment by CalvinDKHD** [comment]
No, i dont know how to add it in the server! I created the verse, but how do i make it so people can connect on the server? from the client.

**Comment by LegitSoulja** [comment]
@CalvinDKHD I gave you plenty of ways you could achieve that via the client.

**Comment by CalvinDKHD** [comment]
Yes i know, but. You said something about options. What options? Which ones Port, ip etc.
And then Where do i put it in?

**Comment by CalvinDKHD** [comment]
And Ip and port? or port.

**Comment by LegitSoulja** [comment]
< option class="party" value="ip:port>My Multiverse Server< /option>

then register a click event for options **.party**, and connect to the attribute value.

**Comment by LegitSoulja** [comment]
$(".party").click(function(){
    connect(this.attr('value'));
});

**Comment by CalvinDKHD** [comment]
Sorry, i dont understand what you mean. What is Register a click? What is Attribute value?
please contact me over skype - calvin.leonhardt
I would even pay you a little amount of money. I am sorry for disturbing you. I just need this done Please.

**Comment by LegitSoulja** [comment]
an attribute is a attribute of an element.
< option value="ip:port" class=".party" >My Multiverse Server< /option>
value, and class are both attributes..

**Comment by LegitSoulja** [comment]
Only thing you need to do is add that code i gave you, then like you did with the parties, add extra option elements, then once its clicked/selected it will connect automatically.

**Comment by CalvinDKHD** [comment]
And sorry, where do i put this piece of code in the index? Please just contact me on skype. If you can make me a server with 4 servers on it i would pay you. skype - calvin.leonhardt

**Comment by LegitSoulja** [comment]
```
$(document).ready(function(){
    $(".party").click(function(){
        connect(this.attr('value'));
    });
});
```
add before body tag/

**Comment by LegitSoulja** [comment]
And like I said, I do not take money offers. Nor I will not add you on skype to make an offer. Skype is also a bad way to discuss this without proper coding formate, which github provides.

**Comment by CalvinDKHD** [comment]
OK sorry about the skype thing, But still i really dont know what you mean. What is body tag? 
and where do i put this in?
`$(document).ready(function(){
    $(".party").click(function(){
        connect(this.attr('value'));
    });
});`

Just i dont know. Sorry for this. But is there a tutorial? step by step?

**Comment by CalvinDKHD** [comment]
I am very sorry, but I dont understand much here. Its so complicated for me.

**Comment by LegitSoulja** [comment]
Send me your index.html file

**Comment by CalvinDKHD** [comment]
Sorry I can't I have to sleep. I will do it here tomorrow.

**Comment by RasyiidWho** [comment]
Help me ._.

![capture](https://cloud.githubusercontent.com/assets/19422415/15564230/251a9888-233a-11e6-9b3e-f52c8aec8ad5.PNG)

**Comment by Agarian** [comment]
Theres a minimap already??

**Comment by RasyiidWho** [comment]
yes

**Comment by RasyiidWho** [comment]
@LegitSoulja help meh ._.

**Comment by CalvinDKHD** [comment]
Rasy, just type localhost:8080 in the browser where the url goes
