### ISSUE TITLE
No Issue

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#753]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
1
What version are you on?
new
What command did you type if any?
nothing to do with that
You must have a description as well
?
So i was wondering if u guys could maybe do something so when someone connects they automaticaly get minions, put minion for 1 person at a time and its random? that could be fucking genious 
Thanks Hope that could be possible (:

**Comment by raphyjb** [comment]
did i need put this in pull requests? :|

**Comment by David1ali12** [comment]
install GiveMeMinionsToo plugin 
you can install by type this command `plugin install GiveMeMinions` in console Thanks to @LegitSoulja  for adding this plugin :D
have fun

**Comment by LegitSoulja** [comment]
@David1ali12 Use givememinionstoo

**Comment by raphyjb** [comment]
>plugin install givememinionstoo
>[Console] That plugin does not exist. Do plugin available to see available plugins

**Comment by David1ali12** [comment]
Then try GiveMeMinions and if still dont work go to [here](https://github.com/AJS-development/OgarUL-Plugin-Library/tree/master/GiveMeMinions) and download then add it manually to plugin folder in src/ogar-unlimited

**Comment by LegitSoulja** [comment]
@David1ali12 noo.. And @raphyjb 1 second.

**Comment by LegitSoulja** [comment]
@raphyjb do
> plugin install GiveMeMinionsToo

**Comment by raphyjb** [comment]
Got a problem, when i start server it doesnt put them automatic? i do install but the time is not changing even if changed it in plugin folder... wd Legit u got skype?

**Comment by David1ali12** [comment]
lol its the timer let's say you put 60000ms which is = 1 min so you need wait 1 mint untill it starts  read info in OgarUL-Plugin-Library   that's All no more helping and stop making issues 
@LegitSoulja I'm confused now `GIveMeMinionsToo` `givememinionstoo` `GiveMinions` which one should I use

**Comment by raphyjb** [comment]
so when i start my server i need wait 3minutes (cuz i set it to 3minutes) before i see bots?

**Comment by David1ali12** [comment]
sure

**Comment by raphyjb** [comment]
ok and how we name those bots?

**Comment by raphyjb** [comment]
cuz its wroten minion on them, id like to call them something else then minion, its there someone were default name if minions?

**Comment by David1ali12** [comment]
easy 1 sec let me check

**Comment by raphyjb** [comment]
david can you add me on skype?

**Comment by David1ali12** [comment]
https://github.com/AJS-development/Ogar-unlimited/blob/master/src/ai/MinionLoader.js place 
`line 55` default `minion` change to any name you want 
btw my skype :David Ali-09 I have played with you I think on agarplus servers

**Comment by raphyjb** [comment]
ya think? not sure i dont play alot of agarplus servers.. but maybe..

**Comment by David1ali12** [comment]
did you played on ogar-dev servers ?

**Comment by raphyjb** [comment]
Chat on skype

**Comment by raphyjb** [comment]
go chat me on my skype: raphy.jb

**Comment by raphyjb** [comment]
is there a way to auto kick poeple when they dont play... cuz they using my bots when they aint on..

**Comment by David1ali12** [comment]
src/settings/config.ini 
line 27 ` kickspectate`

**Comment by LegitSoulja** [comment]
@David1ali12 I have it correctly a while ago. I said the other was recoded better. 

**Use this to install**:
> plugin install GiveMeMinionsToo

It's GiveMeMinionsToo. No other. The one I created was GiveMeMinions, but There's 2.

**Comment by LegitSoulja** [comment]
another way to install... Type in
> plugin add https://raw.githubusercontent.com/AJS-development/OgarUL-Plugin-Library/master/givememinionstoo/files.txt

**Comment by firelightning13** [comment]
Case sensitive -_-
