### ISSUE TITLE
2 Requests from me and my friends

### ISSUE THREAD

**Issue by Tokoagar** [AJS-development/Ogar-unlimited#755]
Hey,

1.Can u add a minion board like : https://i.ytimg.com/vi/wx0eT3PgVYg/maxresdefault.jpg (The bot board)

2. Is it possible to add Extented Zoom

Please anwser .

-Toko

NOTE: I realy like your client I can play with my friend and all have fun! Thanks for making this :)

**Comment by David1ali12** [comment]
I guess it's time to start banning noobs why you need bot board its stupid you can make it if you like it we are not ur personal coders .

**Comment by LegitSoulja** [comment]
Dude thats so easy....  Edit the canvas, and get the json from your stats port// BOOOM!!

**Comment by David1ali12** [comment]
you just copy cavas of orad and add it if you know 1% of javascripte

**Comment by Andrews54757** [comment]
actually, il look into this

**Comment by LegitSoulja** [comment]
:( @Andrews54757 if you do, please provide a way for people to disable it.

**Comment by Tokoagar** [comment]
Yes for poeple who wont like it


2016-05-25 18:15 GMT-04:00 LegiTPanda <notifications@github.com>:

**Comment by Andrews54757** [comment]
why wont people like it?

**Comment by David1ali12** [comment]
Omg the quality of pic are you using windows 98 =3 =3

**Comment by LegitSoulja** [comment]
Dude 98 is

**Comment by LegitSoulja** [comment]
Well I forgot. But I could set up a menu. I was last time but it was overwritin
