### ISSUE TITLE
Random players join my server and kill me 

### ISSUE THREAD

**Issue by loganagar32** [AJS-development/Ogar-unlimited#759]
I installed Ogar-unlimed and  random player join me server then troll me , they feed then kill me how to stop make them join my server , feeding then killing me  I hate them.

**Comment by David1ali12** [comment]
I think you added bots they not players BOTS!  players cant join local host.....

**Comment by systemroot** [comment]
add some minions go bigger and they can't eat you :muscle:

**Comment by loganagar32** [comment]
how to make me minions ?

**Comment by systemroot** [comment]
`playerlist` 
find your name and ID is one number example 1 or 4 or i don't know 
now type 
minion ID 30 <3.OGAR.3>
do remove minions
minion ID

Fist go biger than 20 mass or you can't eat minions :cry:

**Comment by loganagar32** [comment]
are they bots ? even ward tnt and big black car

**Comment by David1ali12** [comment]
ye they are bots....................

**Comment by loganagar32** [comment]
Thx @systemroot now am get big faster :D yay

**Comment by Parth1999** [comment]
@loganagar32  Go in config.ini and set serverbots = 0 if you dont want bots anymore

**Comment by LegitSoulja** [comment]
Whitelist exists, even though the command in help doesn't

**Comment by raphyjb** [comment]
Legit u got skype?
