### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by Logan7432** [AJS-development/Ogar-unlimited#763]
For some reason the playercells are moving very slow! Would that be the fps or do i change the player speed or can it be lag? Im confused.

**Comment by LegitSoulja** [comment]
Hahaha lag, fps, player speed... Well neither fps, and speed. It's lag...

**Comment by Logan7432** [comment]
@LegitSoulja Thanks, They should make this a little less resource consuming so we dont get anymore lag. If you guys want an example try out Cigar, It has no lag what so ever.

**Comment by LegitSoulja** [comment]
@Logan7432 try the garbage collector.
