### ISSUE TITLE
Walls

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#766]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
0
What version are you on?
new
What command did you type if any?
nothing
You must have a description as well
walls are fucked up... they teleport me on top... when im down..

Wat i do?? Walls are being a bitch, restarted server and still nothing is fixed.......... :(

**Comment by LegitSoulja** [comment]
It's a bug with the client. It can't be fixed until fixed.

**Comment by raphyjb** [comment]
ah k, hm also wats the default number of virus in agario and min...

**Comment by Andrews54757** [comment]
@raphyjb No profanity please

**Comment by raphyjb** [comment]
xD kk just had this song in my head

**Comment by Megabyte918** [comment]
@raphyjb min amount 40 and max amount 170 seem to fit pretty well with the vanilla map values

and @LegitSoulja 

> It can't be fixed until fixed 

lolwut
