### ISSUE TITLE
My friends can not enter!!

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#768]
Hello i'm from brazil and my friends can not enter into my server, i use hamachi,and use the site https: //play.ogarul.tk ,I digit the IP " ws://hamachiIPV4:server port ",
they say they can not get and is a white screen,it is possible to get into the site?
## Sorry bad inglish!!!

**Comment by LegitSoulja** [comment]
try
- http://cl.agariohub.tk/?ip=hamachiIPV4:server port

**Comment by GhostShot3** [comment]
@LegitSoulja Hmm ok.

**Comment by GhostShot3** [comment]
@LegitSoulja My friends keep talking that has white screen when tightening to play

**Comment by GhostShot3** [comment]
@LegitSoulja even with another site...

**Comment by LegitSoulja** [comment]
@GhostShot3 Make sure they arent running https.

**Comment by GhostShot3** [comment]
@LegitSoulja How ?

**Comment by firelightning13** [comment]
Can you send me a picture?

**Comment by Andrews54757** [comment]
its because of hamachi. Weve had problems with hamachi before. Best option: port forward instead. if not, too bad

**Comment by GhostShot3** [comment]
@firelightning13 The problem is not with me but with my friends, they say they are a white screen (that grade), I can get normally.

**Comment by David1ali12** [comment]
Make sure 


- they are connected with ur network.
- ipv4 and port .

also
- try `wss` and `ws` 

And if still not working  use old packet and try with agarplus(ws://server:port) or bagario ext(agar.io/?ip=server:port)  use moneyclip client.

**Comment by LegitSoulja** [comment]
Yea Try wss instead of ws.
