### ISSUE TITLE
Skins don't work in play.ogarul.tk

### ISSUE THREAD

**Issue by Merkie** [AJS-development/Ogar-unlimited#771]
When I use a skin like "< spy > lol" It doesn't work. The cell is blank.

I had to write < spy > because GitHub wont let me write it without spaces.

**Comment by David1ali12** [comment]
What is 10+9=?

**Comment by Merkie** [comment]
19

**Comment by David1ali12** [comment]
that why skins dont work XD

**Comment by LegitSoulja** [comment]
LOL https://www.youtube.com/watch?v=OLBOn0Whhyc

**Comment by Merkie** [comment]
I want to kys

**Comment by problemsofworld** [comment]
wired fact 
9        +        10   = 21
     \             /        
   3×3          5×2       
     \    \     /    /       
        \ 3 × 5  / =15   
          \       /     + 
           3 × 2  =  6  
                        =   
                     21﻿

**Comment by NeptoonYT** [comment]
@LegitSoulja Is there a possible way to use custom skins in the private servers...??

**Comment by Merkie** [comment]
just tell me how to fix

**Comment by NatsuTheGreat** [comment]
No one has setup a skin system with "<>" yet I believe.

**Comment by David1ali12** [comment]
update skins are added
