### ISSUE TITLE
i cant play on play.ogarul.tk

### ISSUE THREAD

**Issue by PabloAran** [AJS-development/Ogar-unlimited#772]
i cant play! 
i use play.ogarul.tk and dont work! help!

![captura](https://cloud.githubusercontent.com/assets/8482876/15591225/14c05288-2372-11e6-95bc-a854c71f65a7.PNG)

![captura](https://cloud.githubusercontent.com/assets/8482876/15591245/362c884c-2372-11e6-8b47-07eba2b05102.PNG)

**Comment by Andrews54757** [comment]
are you using an extension?

**Comment by PabloAran** [comment]
bagar.io, tampermonkey, addblock and the anti-virus.

**Comment by Andrews54757** [comment]
disable bagar and tampermoneky

**Comment by PabloAran** [comment]
thanks!
