### ISSUE TITLE
AJS-Dev Break.

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#773]
Beginning Tuesday, next week at May 31, lasting until Saturday, will be a break for @AJS-development/ogar-unlimited-devs During that time, Issues will be closed and development will halt. This is so that the members of AJS-dev can have a break after listening and developing 24/7.

**Comment by XenoYT** [comment]
@Andrews54757 Will you add skins and strong bots 30 may :) ?

**Comment by NatsuTheGreat** [comment]
I can work if I have time, school is ending soon, so it's alright.

**Comment by Megabyte918** [comment]
Your going to close the issues? idk how i feel about this... if anyone wants to talk about ogar unlimited check out the gitter chat or discord chat

**Comment by Agarian** [comment]
Same

**Comment by NatsuTheGreat** [comment]
I don't suggest doing that, if the devs want a break, they can just get off the comp xD

**Comment by Andrews54757** [comment]
I feel like the devs NEED to take a break, even if they dont want to as I would like to finish up my new feature. I think it is good for everyone if they took a break and enjoyed life instead of spending time on a game program. Especially because you probably have other things to do. Make real friends and spend time with your families. Do something other than Ogar-UL.

**Comment by Andrews54757** [comment]
Also, most issues are duplicates, people will figure it out themselves. I think people are just using the 24/7 support to take care of things they are too lazy to do.

**Comment by XenoYT** [comment]
@Andrews54757 you must add a skilled bot :3 like me

**Comment by Andrews54757** [comment]
Another thing is that there are many tutorials on youtube on ogar unlimited, so people will figure out

**Comment by xMuratY** [comment]
Good bye , nice chose

**Comment by Agarian** [comment]
I sure the heck don't need a break

**Comment by LegitSoulja** [comment]
@Andrews54757 I had a break from work for a week and a half almost and going back soon, normally if im here or not im still on the edge of always coming home developing something, since im like a really active person.

**Comment by Agarian** [comment]
lol i seriously dont need a break

**Comment by NatsuTheGreat** [comment]
^^ Same, taking care of this is fun :D

**Comment by Andrews54757** [comment]
Thats the reason why. I know it is fun but you really need to do something else in life besides this. It is just too addictive

**Comment by Megabyte918** [comment]
for YOU but not for US

**Comment by NatsuTheGreat** [comment]
Dude I wasn't on the computer until now, I am fine xD

**Comment by Agarian** [comment]
HOW DO I GET OVER 4K EMAILS IN LESS THAN 2 MONTHS?? I HAD TO DISABLE EMAIL NOTIFICATIONS! lol sorry for caps

**Comment by ItzLevvie** [comment]
I've more than 6K emails.
