### ISSUE TITLE
Error, need help!

### ISSUE THREAD

**Issue by 001002003004** [AJS-development/Ogar-unlimited#774]
I keep getting this error
module.js:341
    throw err;
    ^

Error: Cannot find module 'C:\Users\USER\Downloads\index.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

Press any key to exit...

Can anyone help me

**Comment by David1ali12** [comment]
#638

**Comment by 001002003004** [comment]
did not work

**Comment by Megabyte918** [comment]
run the server in the repo folder

**Comment by Parth1999** [comment]
do this in cmd cd "ogar-onlimited-folder-location" without  " "
then do cd src
then sudo node index.js or only node index.js

**Comment by 001002003004** [comment]
Thanks! it worked

**Comment by 001002003004** [comment]
now it gives me this
    C:\Users\Cool\Desktop\Ogar-unlimited-master(2).zip: Cannot open C:\Users\Cool\Desktop\Ogar-unlimited-master(2).zip
!   The system cannot find the file specified.
    Drag and drop operation failed
!   There are no more files.

**Comment by 001002003004** [comment]
now the server is glithed.

**Comment by Megabyte918** [comment]
@001002003004 what do you mean
