### ISSUE TITLE
root priviledges?

### ISSUE THREAD

**Issue by awikwee** [AJS-development/Ogar-unlimited#775]
PLEASE HELP https://gyazo.com/bcf778d1d914d02140b4c623d28fe0bd

**Comment by LegitSoulja** [comment]
I always get that when a port I change too can't be used.  Try another server port im guessing?

**Comment by awikwee** [comment]
didnt work for me

**Comment by Andrews54757** [comment]
run with `sudo node index.js` instead. Always works

**Comment by awikwee** [comment]
how do i do that exactly?

**Comment by David1ali12** [comment]
I do it like that example 
1- open cmd I type location of ogar-ulimited `cd  Download`
2- `cd Ogar-unlimited` then `cd src`
3- `sudo node index.js` or `node index.js` same

**Comment by awikwee** [comment]
i did that but it still says i need root priveledges :(

**Comment by David1ali12** [comment]
reinstall
