### ISSUE TITLE
Connecting

### ISSUE THREAD

**Issue by CodingKuda** [AJS-development/Ogar-unlimited#777]
Hello,

I am new to all this Ogar-Unlimited stuff, But when I started the Start.bat for ogar-unlimeted. I tried connecting through agar.io. But it didn't seem to work. 
![image](https://cloud.githubusercontent.com/assets/19262985/15607292/11954828-2455-11e6-8c4c-59588eae9f1f.png)
And it does say im playing. But it doesn't show up on the Agar.io Client. 
![image](https://cloud.githubusercontent.com/assets/19262985/15607305/21df7fe6-2455-11e6-8174-c702da53821a.png).
Please help with this situation.
Thanks.
Adrian

**Comment by CodingKuda** [comment]
Oh. And dont say i was spectating. I did actually press play.

**Comment by Aanis12** [comment]
you cant join actual server try join 
play.ogarul.tk

**Comment by Aanis12** [comment]
or they fixed it back on agario and its doesn't run

**Comment by CodingKuda** [comment]
Ok. Thanks. I just found agar disabled private servers. Thanks m8
