### ISSUE TITLE
[Question] Because bots eject mass for a player / bot ?

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#778]
hello im from brazil,the bots is ejecting mass randomly,because they do it and how to disable it ?
## **Sorry bad inglish**

**Comment by David1ali12** [comment]
what you mean 
add a description




VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

**Comment by GhostShot3** [comment]
@David1ali12  ok

**Comment by David1ali12** [comment]
I dont think there is an option to enable or disable teaming you can put `//` line 20 and 21&26 in src/ai/botplayer to disable teaming

**Comment by GhostShot3** [comment]
` this.teamingwith = []; // player teamingwith
    this.team = 0; // stage of teaming. 0 = off, 1 = init (shaking and giving mass), 2 = teamenabled, 3 = betrayal

    this.juke = true;

    this.target;
    this.teameject = 0;`

**Comment by GhostShot3** [comment]
@David1ali12 Set all to 0 ?

**Comment by David1ali12** [comment]
setting to 0 does not effect at all 
` //this.teamingwith = []; // player teamingwith
   // this.team = 0; // stage of teaming. 0 = off, 1 = init (shaking and giving mass), 2 = teamenabled, 3 = betrayal

    this.juke = true;

    this.target;
    //this.teameject = 0;`
//this.shake

**Comment by David1ali12** [comment]
close?

**Comment by GhostShot3** [comment]
This just so, not edited anything and has not changed they continue ejecting mass

**Comment by David1ali12** [comment]
download old version of botplayer [old version](https://mega.nz/#!2Qk11JhD!fhsrAyTpSv17CNxNJ_h7B7EY1-m7WQHrOC46pMA6Fv8)

**Comment by GhostShot3** [comment]
[Module error](http://prntscr.com/b96e8l)

**Comment by David1ali12** [comment]
change first from
`var PlayerTracker = require('../PlayerTracker');`
to this
`var PlayerTracker = require('../core/PlayerTracker.js');`

**Comment by GhostShot3** [comment]
@David1ali12 Where ?

**Comment by David1ali12** [comment]
**src/ai/botplayer line 2**

**Comment by GhostShot3** [comment]
Same error

**Comment by David1ali12** [comment]
lol

**Comment by Megabyte918** [comment]
try removing all the code that has to do with bots teaming use [this](https://github.com/AJS-development/Ogar-unlimited/commit/bc17cac12cda1ddcdd5a49c31daebb280c1d6d25) to compare

**Comment by GhostShot3** [comment]
Fixed! :)
