### ISSUE TITLE
Ogar is working

### ISSUE THREAD

**Issue by ErikParacelsus** [AJS-development/Ogar-unlimited#779]
https://github.com/Luka967/Ogar try this, you can connect to the server with the search bar @LegitSoulja @Andrews54757 @Lukkez @firelightning13 @Megabyte918 @Agarian @NatsuTheGreat

**Comment by Agarian** [comment]
i cannot run it since im in school =/

**Comment by Agarian** [comment]
maybe create i binary of it?

**Comment by ErikParacelsus** [comment]
Lol im at school

**Comment by Agarian** [comment]
how can you run it without node?

**Comment by Agarian** [comment]
?

**Comment by ErikParacelsus** [comment]
I run it on Nitrous.io

**Comment by David1ali12** [comment]
I never knew that Nitrous.io hosts for free thx.

**Comment by ErikParacelsus** [comment]
I think you guys should look at this https://github.com/OgarProject/Ogar/issues/588

**Comment by firelightning13** [comment]
Well i knew it already so uh... thnx for bringing this things up?

pls kill me

**Comment by NatsuTheGreat** [comment]
Uhh I hate this update.. It made agar.io 50% worse :@

**Comment by Agarian** [comment]
so, how can i get a cell's borders to remain visible even in smooth render mode(has to do with the client)?
