### ISSUE TITLE
i put my name <spy>, doesnt work

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#78]
How do i do this skins?
and where do i find the option botrespawn?

**Comment by Andrews54757** [comment]
It is in gameserver.ini and the skins do work

**Comment by elitajmx** [comment]
I put my skin name but it doesnt give me the skin?

**Comment by Andrews54757** [comment]
Are you useing the newest version?

**Comment by elitajmx** [comment]
yes

**Comment by elitajmx** [comment]
i think is there newer?

**Comment by elitajmx** [comment]
oh nvm il ltry to download
