### ISSUE TITLE
i researched this in google but....

### ISSUE THREAD

**Issue by tommyb008** [AJS-development/Ogar-unlimited#780]
i couldnt find how to put agario client into website

**Comment by David1ali12** [comment]
Its easy just download the client and host it.

**Comment by tommyb008** [comment]
how do i host it though

**Comment by David1ali12** [comment]
run with node.js on ur vps

**Comment by David1ali12** [comment]
take a look at https://serv-mogar.c9users.io/ mind you can download the example [here](https://ide.c9.io/mogar/serv)
