### ISSUE TITLE
minion spawning bug

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#781]
note in these gif's, safe spawn was OFF.
![minion spawn bug](https://cloud.githubusercontent.com/assets/15255724/15618502/731f6350-241c-11e6-9ee0-d5562de980d6.gif)
![spawnbug](https://cloud.githubusercontent.com/assets/15255724/15618513/78885fb8-241c-11e6-899b-4868e6ab1687.gif)

**Comment by Agarian** [comment]
all minions tend to spawn in the left corner.

**Comment by asadsayyad123** [comment]
hi friend i require your help

**Comment by asadsayyad123** [comment]
i tried making this work
but it didnt

**Comment by Megabyte918** [comment]
@Agarian is   it the same with safespawn on? if so maybe the client screwed it up just like with the borders

**Comment by Agarian** [comment]
yes it is, the client shouldn't have an effect on minion spawning, this has been going on even b4 we needed a separate client

**Comment by NatsuTheGreat** [comment]
I'll to look into it sometime. Check your spawning functions.

**Comment by Agarian** [comment]
The spawning functions are un-tampered with.

**Comment by NatsuTheGreat** [comment]
Weird, I am not getting this issue... what version you on? 

http://prntscr.com/b9wpr1

**Comment by Andrews54757** [comment]
I found out the reason. Someone coded the pr for safe spawn horribly. The config somehow had no effect because the code was made so the config does nothing. I fixed it on here #786
