### ISSUE TITLE
proplem with my connect with extention

### ISSUE THREAD

**Issue by anaelpop** [AJS-development/Ogar-unlimited#782]
![connect](https://cloud.githubusercontent.com/assets/18750395/15622762/964ccb7e-246c-11e6-9f06-c16a6c0bbf20.png)

**Comment by Kappa0Kappa** [comment]
Having the same issue

**Comment by anaelpop** [comment]
what?

**Comment by David1ali12** [comment]
use [play.ogarul.tk](play.ogarul.tk) skins for private servers are disabled even if you use ext agario patched skins if you still want to use ext you need old packet  #711 .

**Comment by BobyStar** [comment]
this is what happens to me, but i had a older version:11.8.5 and it worked just fine please help.

**Comment by Andrews54757** [comment]
set packetversion to 0

**Comment by Agarian** [comment]
idk why but for me, doing that just causes the browser to freeze when clicking play.

**Comment by BobyStar** [comment]
i set packetversion to 0 and it does the same thing please help!!!!111!!11!111!!

**Comment by Agarian** [comment]
USE PLAY.OGARUL.TK and the latest version of ogarul!!!!!!!!!!!
