### ISSUE TITLE
And another Server Showcase

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#783]
Showcase your servers below!. 

Provide your server
- client address
- server ip and port
- server game mode
- active (24/7, rarely, sometimes, etc...)

**Comment by LegitSoulja** [comment]
#1 
- Website
http://agariohub.tk

- Game Mode
Plenty coming soon

- Active
24/7, hopefully again.

**Comment by anaelpop** [comment]
add skins!!

**Comment by anaelpop** [comment]
can u help me 
![connect](https://cloud.githubusercontent.com/assets/18750395/15623493/6eefbe94-2474-11e6-82f9-3f72d67dd163.png)

**Comment by anaelpop** [comment]
can't connect with extention

**Comment by LegitSoulja** [comment]
Don't use no extensions!!. Come here http://agariohub.tk

**Comment by David1ali12** [comment]
nice :)

**Comment by Ckicky** [comment]
d

**Comment by Ckicky** [comment]
@LegitSoulja What is the map settings of the FFA status, Is it 6000;6000 or 12000;12000?

**Comment by elitajmx** [comment]
and what is the map of merger, 14000;14000 or 99999999999 by 9 fucking 99999999999999

**Comment by Xeeroo** [comment]
LegitSoulja,that 2 servers are rly slow,pls do something about it

**Comment by LegitSoulja** [comment]
@Xeeroo Adding new servers..

**Comment by LegitSoulja** [comment]
@Lukkez @Agarian do you have any servers you want to put on http://agariohub.tk ??

**Comment by Agarian** [comment]
If I could, I would, but i can't host.

**Comment by LegitSoulja** [comment]
@Agarian register on my site, ill give you a server

**Comment by David1ali12** [comment]
I have a server but not online 24/7 using old packet but no lag with 200 bots + 200 minions Can u add ?

**Comment by LegitSoulja** [comment]
@David1ali12 sure, david i have a system to determine if a server is offline or not. Give me your server info
- gamePort
- statPort
- Gamemode
- registered agariohub.tk name

and if you have ogarconsole installed give me your ogarconsole port

**Comment by Agarian** [comment]
logged in

**Comment by David1ali12** [comment]
### Max players 500 

-  ip+port `html-stranger2.c9users.io:8080` dont worry I dont get banned ;)

- server stats port :8082 server port:8080
- FFa but like party mode 
-  server stats port :8082
no I dont have ogar console   I have not ever used ,is it giving more control ?

**Comment by LegitSoulja** [comment]
@David1ali12 OgarConsole is a OgarConsole you can use on the site to access your server.
I need your game Port, and stat port not client port.

**Comment by Andrews54757** [comment]
@LegitSoulja I dont think that ogarconsole is safe though. Now that we have plugins. For example this is what I would do to hack



1. Hack into ogarConsole (not so hard)
2. Create an exec plugin (very easy)
3. Install it over ogarconsole (a tree could do it)
4. Enable ssh through commands using the plugin (especially dangerous if running as root)
5. Other networking stuff I wont explain (expirience needed)
6. Connect to the computers direct console by ssh
7. He now has full access to your computer and can do anything (even access your desktop)

**Comment by Andrews54757** [comment]
@LegitSoulja I have some ideas to beef up the security for ogarconsole though.

**Comment by loganagar32** [comment]
add me server  127.0.1:433 ffa

**Comment by loganagar32** [comment]
Andrew puede unirme dev?

**Comment by LegitSoulja** [comment]
@Andrews54757 I added advanced mode, I took it off, then it put it back again as to having it enabled in the configuration. What other ideas do you have?

P.S exec can only be executed by command -exec via ogarconsole w/ config advanced enabled.

**Comment by Andrews54757** [comment]
@LegitSoulja Please, dont be too ignorant. I dont need ogarconsoles cmd feature. I can create a plugin that adds that command. Then I can install it over ogarconsole using the plugin add command.

**Comment by LegitSoulja** [comment]
@Andrews54757 I didn't say you needed it. I thought it was a cool idea to have, since I was going to host ogar servers in the future, then people wanted it shared, and also working for OgarUnlimited. 

I know, You think it may not be a good idea, but I was using it for my use only before it became public, and only was control via server and no other clients could interact. They could gain access to the console with ease if they figured out the port. that's why a password was implemented.

Therefor, I really didn't know if it was a thing that should have been implemented or not but I added that command there with OgarConsole via the OgarConsole terminal only, by password authentication and config enable.

OgarConsole with my use on my site is only activated if the user has a registered server, which allows them to have a command popup activation, and can only be activated by owners of there server, which they will still need there assigned password to login to the console.

I can remove the -cmd command from OgarConsole if its a big problem. Just know OgarConsole was never a plugin in begin with, but it was assigned a plugin by you, the reconfigured and updated by me into a plugin.

**Comment by LegitSoulja** [comment]
What other security do you have though? Add them. I don't mind. Whatever fits security needs.

**Comment by fayizan** [comment]
#2 

- Website
http://indiaagario.tk

- Server IP/Port
52.77.156.102.443

- Game Mode
FFA,More Coming Soon

- Active
95%

**Comment by ItzLevvie** [comment]
@fayizan 
![image](https://cloud.githubusercontent.com/assets/11600822/15632607/65e4bd6e-2590-11e6-889e-dc2ce7788995.png)

**Comment by Andrews54757** [comment]
I am going to add a security password for `plugin add`

**Comment by Andrews54757** [comment]
I am going to make plugin add inaccessible for plugins

**Comment by LegitSoulja** [comment]
@Andrews54757 Check out the Statistics plugin and this http://stats.ogarul.tk/

**Comment by SorryAgario** [comment]
please make the FFA map size bigger

**Comment by Agarian** [comment]
I have a question, You know how in the new agar.io client, you can now see cell borders even in smooth render right? How would I add that into an ogarUL client? Anyone who can help?

**Comment by NatsuTheGreat** [comment]
It just blurs the screen...

**Comment by Agarian** [comment]
?

**Comment by Lukkez** [comment]
Sorry for all this innactivity, I was makin' a website for a friend, now I think, i'll try to get a host
