### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#784]
**Error in my cmd, its flooding [it](http://prntscr.com/b9binn) !**

**Comment by Andrews54757** [comment]
What is the first 3 lines in the error

**Comment by loganagar32** [comment]
hablas espanol

**Comment by firelightning13** [comment]
Please speak english -_-

**Comment by NatsuTheGreat** [comment]
This probably means you are missing a ```, this```` argument somewhere. let me look into this.

**Comment by NatsuTheGreat** [comment]
Holy! That gamemode is broken! But to try to first your problem, replace like 422 in NoCollisionTeamX.js with this:

```
  var f = new Food(gameServer.getWorld().getNextNodeId(), null, pos, gameServer.config.foodMass, this);
```

**Comment by GhostShot3** [comment]
@NatsuTheGreat Where i out this ?

**Comment by GhostShot3** [comment]
@Andrews54757 Here[http://prntscr.com/b9n86o](url)

**Comment by GhostShot3** [comment]
@NatsuTheGreat I edited as you said but this red !
http://prntscr.com/b9ncox

**Comment by GhostShot3** [comment]
@firelightning13  Im trying sorry.

**Comment by Andrews54757** [comment]
what gamemode?

**Comment by GhostShot3** [comment]
@Andrews54757 NoCollisionTeamX

**Comment by Andrews54757** [comment]
il see

**Comment by NatsuTheGreat** [comment]
I have a final solution for you:

Replace ALL OF ```entity/Food.js``` with this:

http://pastebin.com/XqzeLeUQ

Then, replace ALL OF ```gamemodes/NoCollisionTeamX.js``` with this:

http://pastebin.com/mgxRC2fA

**Comment by GhostShot3** [comment]
@NatsuTheGreat Fixed!

**Comment by NatsuTheGreat** [comment]
No problem.
