### ISSUE TITLE
performance  with versions

### ISSUE THREAD

**Issue by David1ali12** [AJS-development/Ogar-unlimited#785]
# I have tested two version of ogarUL and results below
## running on low vps & pc
I tested version 11.8.5 XD and version 16.7.8 minions and bots
- `11.8.5` added 500 bots to version cpu 179% but no lag at all , added 300 minions cpu 175% smooth as f***.
- `16.7.8` added 500 bots cpu 162% screen frozen of lag  added 300 minions big laggg and delay so much . 
i know this stupid but .................

**Comment by problemsofworld** [comment]
Fast developing -_-

**Comment by Andrews54757** [comment]
Dont worry, see #786

**Comment by David1ali12** [comment]
nice :)
