### ISSUE TITLE
Can you make op spawn with more mass

### ISSUE THREAD

**Issue by MineMooreALT** [AJS-development/Ogar-unlimited#787]
Hey i was wondering if it was possible to make it so op people can spawn with more mass

**Comment by David1ali12** [comment]
you mean they chose a mass that they want to spawn with ?

**Comment by MineMooreALT** [comment]
yeah like i want myself (OP) to spawn with 132 mass and for normal players to start with 43 mass

**Comment by David1ali12** [comment]
put to suggtions its possible to make an plugin for this #510

**Comment by Parth1999** [comment]
Press q one c appears on you name and press w

**Comment by Agarian** [comment]
this should really be in #510
