### ISSUE TITLE
Can I join dev  Andrew puede unirme dev?

### ISSUE THREAD

**Issue by loganagar32** [AJS-development/Ogar-unlimited#788]

**Comment by problemsofworld** [comment]
you ok ? you can join banned list heehe

**Comment by David1ali12** [comment]
you must know security answer to join 
 **What is 10+9=?**

**Comment by firelightning13** [comment]
> you must know security answer to join 
> What is 10+9=?

jokes are too old m8

**Comment by bangana** [comment]
@firelightning13 Rekt.

**Comment by loganagar32** [comment]
@firelightning13 me join ? please security answer 19!! me join ???

**Comment by systemroot** [comment]
:cry: :smile: :smile: :smile:

**Comment by tomsterley** [comment]
Omg this is hilarious, does this kid not know anything about the internet or github?

**Comment by LegitSoulja** [comment]
@tomsterley @systemroot @bangana @David1ali12 @problemsofworld 
He speaks spanish.. Why do him that bad? Ya'll are soo selfish. @problemsofworld thats another ban. Your's the only one here thats stupid.

@loganagar32 La respuesta es 21

**Comment by problemsofworld** [comment]
banning me why I did not do anything

**Comment by loganagar32** [comment]
Gracias  me new dev 
![garis](https://cloud.githubusercontent.com/assets/19589095/15628156/f50d94d6-2502-11e6-86e2-fd0dc7b86fce.PNG)

**Comment by tomsterley** [comment]
Never said that did him any bad.

**Comment by ghostangel2212** [comment]
Amigo no se dice me en ese caso, se dice   "Im"

**Comment by xMuratY** [comment]
Thats is verry hard because peoples alltime need better than all .d u making project and supporting it for free but peoples doesnt devers all make all project with money and support it for money if lu dont like moneyclip reverse it and make minions extensions vs.

**Comment by NatsuTheGreat** [comment]
@problemsofworld Yeah lets say you did absolutely nothing.

>you ok ? you can join banned list heehe stupid kid

Maybe you forgot you sent that.

http://prntscr.com/b9lo7s

**Comment by loganagar32** [comment]
natsu 
me 7 year old new can be developer of ogar hablas espanol?

**Comment by NatsuTheGreat** [comment]
@loganagar32 No estoy seguro de aca . Trate de preguntar Andrews . No estoy seguro de si va a llevar a los niños 7 años sin embargo.

**Comment by loganagar32** [comment]
Andrew puede unirme dev

**Comment by loganagar32** [comment]
Por favor!

**Comment by loganagar32** [comment]
:cry:
