### ISSUE TITLE
Skins doesnt work + cant connect agar.io/?ip=ipadress

### ISSUE THREAD

**Issue by SMASH8530** [AJS-development/Ogar-unlimited#789]
Hey, my skins doesnt work. I tryed < skinname >name, (in console) name 1 < skinname >name,
name 1 [http://url]name .

My problem is that it doesnt show up.
https://gyazo.com/e86ea2643b19c9691897f699ab72b52b
https://gyazo.com/f9e94469fcdd01c76cfc35ad7c446c49

Also i have another problem. If i write agar.io/?ip=ipadress or agar.io/?127.0.0.1
it just goes like this.
https://gyazo.com/35a8cba3e5ffccc731e73721172bb49c
https://gyazo.com/3660b314f7d841e43d3f4111167f28bc
https://gyazo.com/4e2fb134f10160a65396260e68404119

Right now i use; http://ajs-development.github.io/client/ to get into my server.
I think the problem is, that im using http://ajs-development.github.io/client/ , to connect to my server.

Please help, cause i really want to use skins.
If you need any more information, just ask me.

**Comment by wiz1211** [comment]
Try changing the packet version to 0 in src\settings\advConfig,ini. Credits to **Agarian**.

**Comment by David1ali12** [comment]
use [play.ogarul.tk](http://play.ogarul.tk/)

**Comment by SMASH8530** [comment]
+David1ali12 Doesnt work!

https://gyazo.com/8274a051ff1f48358ebde96ab5c50f28
https://gyazo.com/6e7c136ec331a555d2cacecf5374f546

**Comment by SMASH8530** [comment]
+wiz1211 Just maked an white screen .Doesnt work as well.

**Comment by David1ali12** [comment]
ofc I didn't skins will skins dont work because we did n't added  use doge skin it works

**Comment by problemsofworld** [comment]
I made skins for my client but I cant use `<>` 
![ogarul io](https://cloud.githubusercontent.com/assets/17419793/15628029/911e5fea-24fe-11e6-969c-d7207c547a2a.PNG)

**Comment by XenoYT** [comment]
@problemsofworld how pleasE ,

**Comment by problemsofworld** [comment]
I got it from @David1ali12  but he dont share :P yet not finished

**Comment by NatsuTheGreat** [comment]
I had skins but bagar lost them... So now my server is ugly.

**Comment by Icantconnecttoagarioservers** [comment]
WHYYYY!
https://gyazo.com/add45e02f14cbe4a30fdb3e9c0ffc966
https://gyazo.com/95731c654de6d10f5820e82ac93fa4dd

**Comment by Icantconnecttoagarioservers** [comment]
Please help soon!

**Comment by David1ali12** [comment]
does not work get it no way to make this work untill we add skins for play.ogarUL.tk
