### ISSUE TITLE
Bots/Minions

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#79]
why cant i use bots/minions?
they just go top left or bottom right everytime

**Comment by Andrews54757** [comment]
Because I have an anti raga system. to disable, turn scramblecoords off in gameserver.ini and change maxconnectperip to a value like 500

**Comment by elitajmx** [comment]
Thanks

**Comment by elitajmx** [comment]
They are still going top left..

**Comment by Andrews54757** [comment]
Change the value of coordinatescramble fromm 1 to 0

**Comment by Andrews54757** [comment]
in gameserver.ini

**Comment by elitajmx** [comment]
i did

**Comment by Andrews54757** [comment]
I will take a look

**Comment by elitajmx** [comment]
Nvermind, i downloaded the new verison it works now thanks ;)

**Comment by elitajmx** [comment]
can i use TREX skins and such?

**Comment by elitajmx** [comment]
some skins also dont work
like
Halo
...
