### ISSUE TITLE
How to prevent spectator from using chat

### ISSUE THREAD

**Issue by fayizan** [AJS-development/Ogar-unlimited#790]
I seriously need this,bcoz the banned fella spam the chat soo much by accessing the chat through spectate,I tried banning him from chat and banned ip but I can't do nothing

please look at this 
![screenshot_1](https://cloud.githubusercontent.com/assets/19163419/15627053/699973be-24f5-11e6-8dc3-3ab4f994eb41.png)

**Comment by systemroot** [comment]
Where is hosted your client ?!
if is on your server make it ban with iptables, or csf.

**Comment by Andrews54757** [comment]
why dont you use the chatban command

**Comment by NatsuTheGreat** [comment]
Do you want all spectators not being able to chat?

**Comment by Andrews54757** [comment]
il make a plugin

**Comment by NatsuTheGreat** [comment]
aight

**Comment by XenoYT** [comment]
@Andrews54757 can you please link me how to make a server and my friend can join for training ?

**Comment by Agarian** [comment]
this should be a config lol

**Comment by fayizan** [comment]
Yes I don't want the spectator to use the chat Hope my image clearly explains why.!! and I disabled the spectate button..lol
I use AWS for hosting.

**Comment by Andrews54757** [comment]
will be a config here: #786
