### ISSUE TITLE
Agar.io is down for the maintanence.

### ISSUE THREAD

**Issue by NatsuTheGreat** [AJS-development/Ogar-unlimited#795]
This is just an announcement bringing you that the official client is down right. "Connecting..."

Lets hope for something good.

Please do see if your client works, I came to this from a reddit post. I then had the same problem. No extension is being used.

**Comment by NatsuTheGreat** [comment]
Lets hope for something good...

**Comment by NatsuTheGreat** [comment]
K I can connect now... Took long though.

**Comment by David1ali12** [comment]
It  seems it's only for asain servers europe servers and us servers are still up and works

**Comment by NatsuTheGreat** [comment]
North America broke. But it works now. I wonder what the changed...
