### ISSUE TITLE
NO SKINS WORKING :(

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#796]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
default
What version are you on?
default
What command did you type if any?
Nothing...
You must have a description as well
Hm idk how to get skins (THE CUSTOM SKINS)  on the private server on ogar thingy site

**Comment by David1ali12** [comment]
will be added soon already fixed border glitching.

**Comment by raphyjb** [comment]
xD  LOL.
Hm i got a random question wat does op players do ?? :! i dont get it, do they get commands from console .. or wat??

**Comment by David1ali12** [comment]
close?

**Comment by raphyjb** [comment]
wat? u mean by close?

**Comment by David1ali12** [comment]
yes there option to add spawn mass `plugin install account-rewards` and `plugin install  Auth-plugin`
`rewardspawnmass = 30
rewardspeed = 0// 0 = default
op = 0`

**Comment by raphyjb** [comment]
:O nice !!!!!!!!!!!!! Is there a way to put scroll to zoom out... really anoying that there isnt one on the site

**Comment by David1ali12** [comment]
that's cheating ......

**Comment by raphyjb** [comment]
who cares lol!

**Comment by XenoYT** [comment]
@David1ali12 Doge skin is nothing dude its easy to add skins just tell me what u need

**Comment by raphyjb** [comment]
I need all the skins on agar.io.... ALL that would be amazing! id loveee that! Can u add me on skype: raphy.jb
Also got this error while trying to change in settings/config.ini the adminconfig = 1 and poped this error:
What game mode were you in when you had the issue?
default
What version are you on?
newest... Ogar thingy
What command did you type if any?
i put in config.ini adminconfig= true
You must have a description as well
?
Most common questions involve:
?
ERROR SHOWED UP:
ReferenceError: adminArray is not defined
    at GameServer.spawnPlayer (C:\Users\Maurice\Desktop\Ogar-unlimited-master\src\core\GameServer.js:945:20)
    at Mode.FFA.onPlayerSpawn (C:\Users\Maurice\Desktop\Ogar-unlimited-master\src\gamemodes\FFA.js:78:16)
    at MinionPlayer.<anonymous> (C:\Users\Maurice\Desktop\Ogar-unlimited-master\src\ai\MinionPlayer.js:81:32)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (node.js:380:13)
    at process._tickCallback (node.js:407:11)

**Comment by loganagar32** [comment]
me skins dont work too

**Comment by Agarian** [comment]
WE KNOW!
