### ISSUE TITLE
[Question] How gamemode "NoCollisionTeamX" works ? 

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#797]
### Someone explains in great detail I never understood!
# SORRY BAD INGLISH

**Comment by NatsuTheGreat** [comment]
So all this gamemode does it prevent collision with teammate. For example when you play regular teams mode, you'd collide with your teammates. But here, with this gamemode, it doesn't do that yet it broke merging.

**Comment by GhostShot3** [comment]
@NatsuTheGreat Why no merge ?,What is the difference between "NoCollisionTeamX" and "TeamX"?

**Comment by NatsuTheGreat** [comment]
The difference is that in this gamemode you do not collide with your teammates, you can go under them anything, they won't be eaten. (ONLY WITH YOUR TEAMMATES). The merging broke, its not completely disallowed... It's just broken right now.

**Comment by GhostShot3** [comment]
@NatsuTheGreat Why no merge ?,What is the difference between "NoCollisionTeamX" and "TeamX"?

**Comment by GhostShot3** [comment]
@NatsuTheGreat How to merge?,It has a correct time?

**Comment by NatsuTheGreat** [comment]
The merge is BROKEN. You need to fix it in the code. the no team eating broke it.

**Comment by GhostShot3** [comment]
@NatsuTheGreat Give me code ?

**Comment by NatsuTheGreat** [comment]
I don't have the fixed merging code.......

**Comment by GhostShot3** [comment]
@NatsuTheGreat Why the mothercells no works  ?

**Comment by NatsuTheGreat** [comment]
Probably another bug that i'll have to see, when I have time.

**Comment by GhostShot3** [comment]
@NatsuTheGreat Ok

**Comment by NatsuTheGreat** [comment]
I will try to fix it later, I am quite busy today.
