### ISSUE TITLE
Lets Bring Original Back!

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#798]
Yesss.. We all do agres there is a few differences between Original and the latest version of OgarUl. It's kindof poured down on some smooth gameplay, and most of us enjoy 11.9.0, suckish without the plugins, But we can bring all the good things back in the original and have one good clean Orginial Fix/Patch Version.

All @AJS-development/ogar-unlimited-devs invited. 
- [OgarUnlimited 11.9.0](https://github.com/LegitSoulja/OgarUnlimited11.9.0) Also fixed & works with latest -[OgarUl](http://play.ogarul.tk) client

**Comment by SorryAgario** [comment]
But the splits in 11.9.0 is a bit inefficient tbh

**Comment by David1ali12** [comment]
I fixed split its almost like vanila some1 can fix eject

**Comment by raphyjb** [comment]
Hmmmmmmm... soulja i did download ur update but it didnt work, port problem, it says its connecting to port 443 when i changed port to 4411..

**Comment by problemsofworld** [comment]
- [ 1- eject goes trough players  
2- problems with splits ect physics 
3- popsplit dont work]

**Comment by David1ali12** [comment]
- [ 2-is fixed  ]

**Comment by Agarian** [comment]
idk if i want the original back...

**Comment by NatsuTheGreat** [comment]
You don't have to use it...

**Comment by Agarian** [comment]
Ik

**Comment by Agarian** [comment]
I have a question, You know how in the new agar.io client, you can now see cell borders even in smooth render, How would I add that into an ogarUL client?

**Comment by Andrews54757** [comment]
@LegitSoulja performance will be back. #786

**Comment by Agarian** [comment]
i want to know how
