### ISSUE TITLE
STILL GETTING BOTS ERROR

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#80]
TypeError: Cannot read property 'getSize' of null
    at PlayerTracker.BotPlayer.update (C:\Users\owner\Downloads\Ogar-unlimited-master\src\ai\BotPlayer.js:98:17)
    at GameServer.updateClients (C:\Users\owner\Downloads\Ogar-unlimited-master\src\GameServer.js:922:39)
    at GameServer.mainLoop (C:\Users\owner\Downloads\Ogar-unlimited-master\src\GameServer.js:801:14)
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by Agarian** [comment]
also anyone have a fix to this?
![Uploading virussplit.gif…]()

**Comment by Agarian** [comment]
cells splitting on viruses overlap for about a second

**Comment by Andrews54757** [comment]
What fo you want though

**Comment by Andrews54757** [comment]
Il fix the bots errror temporarilty

**Comment by Agarian** [comment]
id like both lol

**Comment by Andrews54757** [comment]
I made the splitting much better

**Comment by Agarian** [comment]
one minor bug: changing the player name to a premium skin < skin name > with the **name** command will also rename the player to a blank name. On splitting after that, you will have 2 cells with different names:
![name](https://cloud.githubusercontent.com/assets/15255724/12995745/bd92a938-d0f7-11e5-82da-50b21b2abec6.jpg)

**Comment by Agarian** [comment]
lol i just noticed s typo "changeing" should be "changing"
i suggest renaming a player to a skin name be a separate command like **premiumskin**

**Comment by Agarian** [comment]
any ideas?

**Comment by Agarian** [comment]
nvm i figured it out

**Comment by Agarian** [comment]
but now i discovered that when merging cells, recombineTime suddenly becomes 0?!? then after merging completely, splitting returns to normal. its very difficult to explain.  
**so see this gif:**
![splits](https://cloud.githubusercontent.com/assets/15255724/12996625/8cb45822-d0ff-11e5-8d2f-be200fe341a9.gif)
that happens. **and no i did not set recombineTime to 0**

**Comment by Agarian** [comment]
i couldn't make the gif any longer because github "cannot accept files larger that 10MB"

**Comment by Agarian** [comment]
try it yourself. 
split ,then use the merge command, then split before you merge yourself. you get that result(in the gif)
after that, merge completely then split. splitting is now normal. 
(note you don't need to use the command for this effect)

**Comment by Agarian** [comment]
ffs bots have new error: 
![nowerror](https://cloud.githubusercontent.com/assets/15255724/12997095/005951de-d104-11e5-99e2-9b5dfd51868b.jpg)

**Comment by Agarian** [comment]
im too frustrated im going to bed. good night. but the custom skins work great!

**Comment by Andrews54757** [comment]
btw the merge command doing that is normal. also, i will look at the bots

**Comment by Agarian** [comment]
DUDE EVEN WITHOUT USING THE MERGE COMMAND THAT ISSUE OCCURS

**Comment by Andrews54757** [comment]
oh i see, i will fix

**Comment by Agarian** [comment]
Sorry 4 caps

**Comment by Andrews54757** [comment]
I fixed the command so that there is a time limit now

**Comment by Agarian** [comment]
For what?

**Comment by Andrews54757** [comment]
The delay is still long though

**Comment by Andrews54757** [comment]
I meant the merging

**Comment by Agarian** [comment]
The problem is not in the command

**Comment by Agarian** [comment]
I cant do this now. Im not even supposed 2 b awake xD

**Comment by Andrews54757** [comment]
so let me guess, after entering it, it would seem like you can rejoin instantly even after all but 1 cell is merged

**Comment by Agarian** [comment]
I dont even know what that scenario would look like

**Comment by Andrews54757** [comment]
so when you type in merge, you start to merge but when you split, you can still merge instantly until all your cells are merged

**Comment by Andrews54757** [comment]
I added a duration so after so and so amount of time, the merge will expire

**Comment by Andrews54757** [comment]
Also it is so fun to use the custom skin url feature to make a gif as your skin. the animation.

**Comment by Agarian** [comment]
I already tried it its cool

**Comment by Agarian** [comment]
Alse the merge timer was something i wanted to avoid in the first place

**Comment by Andrews54757** [comment]
That is why I made it very long

**Comment by Agarian** [comment]
until the bots are fixed, they are completely unusable. u getting the error?

**Comment by Agarian** [comment]
it seems to only appear if premium skins are in use on the server.

**Comment by Agarian** [comment]
also this is not fixed. why is that tag there?

**Comment by Andrews54757** [comment]
nope i am not getting the error

**Comment by Agarian** [comment]
thats not fair ;-;

**Comment by Agarian** [comment]
WITH AUTOBAN I GOT AN ERROR SO LARGE THAT ID DOESN'T FIT IN CMD

![](https://cloud.githubusercontent.com/assets/15255724/13028161/a1e0056c-d234-11e5-9ac2-6ac964122ec3.jpg)
IT GOES ON FOR A LOOOONG TIME
HAPPENED WHEN I TRIED TO RUN MY MINIONS

**Comment by Andrews54757** [comment]
Can I have the full error? you do this by right clicking and clicking mark then highlighting and pressing enter. then you can copy paste it here

**Comment by Agarian** [comment]
its not doing it anymore after i executed "update"

**Comment by Andrews54757** [comment]
does the rainbow work now?

**Comment by Andrews54757** [comment]
i am probably sure you used an old version

**Comment by Agarian** [comment]
nope

**Comment by Andrews54757** [comment]
(btw that update command took forever for me to make)

**Comment by Agarian** [comment]
and using < r > gives the error apparently

**Comment by Agarian** [comment]
TypeError: Cannot read property 'substr' of undefined
    at GameServer.spawnPlayer (C:\Users\owner\Downloads\Ogar-unlimited-master\sr
c\GameServer.js:982:34)
    at Mode.FFA.onPlayerSpawn (C:\Users\owner\Downloads\Ogar-unlimited-master\sr
c\gamemodes\FFA.js:74:20)
    at PacketHandler.setNickname (C:\Users\owner\Downloads\Ogar-unlimited-master
\src\PacketHandler.js:115:34)
    at PacketHandler.handleMessage (C:\Users\owner\Downloads\Ogar-unlimited-mast
er\src\PacketHandler.js:56:18)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (C:\Users\owner\Downloads\Ogar-unlimited-master\node_mo
dules\ws\lib\WebSocket.js:823:10)
    at C:\Users\owner\Downloads\Ogar-unlimited-master\node_modules\ws\lib\Receiv
er.js:537:18
    at Receiver.applyExtensions (C:\Users\owner\Downloads\Ogar-unlimited-master\
node_modules\ws\lib\Receiver.js:364:5)
    at C:\Users\owner\Downloads\Ogar-unlimited-master\node_modules\ws\lib\Receiv
er.js:531:14
TypeError: Cannot read property 'substr' of undefined
    at GameServer.spawnPlayer (C:\Users\owner\Downloads\Ogar-unlimited-master\sr
c\GameServer.js:982:34)
    at Mode.FFA.onPlayerSpawn (C:\Users\owner\Downloads\Ogar-unlimited-master\sr
c\gamemodes\FFA.js:74:20)
    at PacketHandler.setNickname (C:\Users\owner\Downloads\Ogar-unlimited-master
\src\PacketHandler.js:115:34)
    at PacketHandler.handleMessage (C:\Users\owner\Downloads\Ogar-unlimited-mast
er\src\PacketHandler.js:56:18)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (C:\Users\owner\Downloads\Ogar-unlimited-master\node_mo
dules\ws\lib\WebSocket.js:823:10)
    at C:\Users\owner\Downloads\Ogar-unlimited-master\node_modules\ws\lib\Receiv
er.js:537:18
    at Receiver.applyExtensions (C:\Users\owner\Downloads\Ogar-unlimited-master\
node_modules\ws\lib\Receiver.js:364:5)
    at C:\Users\owner\Downloads\Ogar-unlimited-master\node_modules\ws\lib\Receiv
er.js:531:14
TypeError: Cannot read property 'substr' of undefined
    at GameServer.spawnPlayer (C:\Users\owner\Downloads\Ogar-unlimited-master\sr
c\GameServer.js:982:34)
    at Mode.FFA.onPlayerSpawn (C:\Users\owner\Downloads\Ogar-unlimited-master\sr
c\gamemodes\FFA.js:74:20)
    at PacketHandler.setNickname (C:\Users\owner\Downloads\Ogar-unlimited-master
\src\PacketHandler.js:115:34)
    at PacketHandler.handleMessage (C:\Users\owner\Downloads\Ogar-unlimited-mast
er\src\PacketHandler.js:56:18)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (C:\Users\owner\Downloads\Ogar-unlimited-master\node_mo
dules\ws\lib\WebSocket.js:823:10)
    at C:\Users\owner\Downloads\Ogar-unlimited-master\node_modules\ws\lib\Receiv
er.js:537:18
    at Receiver.applyExtensions (C:\Users\owner\Downloads\Ogar-unlimited-master\
node_modules\ws\lib\Receiver.js:364:5)
    at C:\Users\owner\Downloads\Ogar-unlimited-master\node_modules\ws\lib\Receiv
er.js:531:14
TypeError: Cannot read property 'substr' of undefined
    at GameServer.spawnPlayer (C:\Users\owner\Downloads\Ogar-unlimited-master\sr
c\GameServer.js:982:34)
    at Mode.FFA.onPlayerSpawn (C:\Users\owner\Downloads\Ogar-unlimited-master\sr
c\gamemodes\FFA.js:74:20)
    at PacketHandler.setNickname (C:\Users\owner\Downloads\Ogar-unlimited-master
\src\PacketHandler.js:115:34)
    at PacketHandler.handleMessage (C:\Users\owner\Downloads\Ogar-unlimited-mast
er\src\PacketHandler.js:56:18)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (C:\Users\owner\Downloads\Ogar-unlimited-master\node_mo
dules\ws\lib\WebSocket.js:823:10)
    at C:\Users\owner\Downloads\Ogar-unlimited-master\node_modules\ws\lib\Receiv
er.js:537:18
    at Receiver.applyExtensions (C:\Users\owner\Downloads\Ogar-unlimited-master\
node_modules\ws\lib\Receiver.js:364:5)
    at C:\Users\owner\Downloads\Ogar-unlimited-master\node_modules\ws\lib\Receiv
er.js:531:14

**Comment by Andrews54757** [comment]
I know, it was a typo, I fixed it, do update

**Comment by Andrews54757** [comment]
(Its because i accidentally used `this` instead of `player`

**Comment by Agarian** [comment]
i see. it works fine now :)

**Comment by Andrews54757** [comment]
I even sent a global msg

**Comment by Agarian** [comment]
the bots error seems to direct to the config botsrespawn
if a bot tries to re-spawn with the config set to 0, then the server crashes.

**Comment by Agarian** [comment]
**yep the issue links to here:**

    // Respawn if bot is dead
    if (this.cells.length <= 0 ) {
        if (this.gameServer.config.botrespawn == 1) {
        this.gameServer.gameMode.onPlayerSpawn(this.gameServer, this);
        if (this.cells.length == 0) {
            // If the bot cannot spawn any cells, then disconnect it
            this.socket.close();
            return;
        }
        } else {
            this.socket.close();
        }
    }

note *botsrespawn* must be set to 0. eventually if a bot dies, then the error should will occur. it also works with the *kill* command.
