### ISSUE TITLE
Module error.

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#800]
Module [error](http://prntscr.com/b9uiwe) in TeamZ.

**Comment by NatsuTheGreat** [comment]
Pretty sure it's not supposed to be ```'../GameServer```' but it should be ```var GameServer = null;```

**Comment by GhostShot3** [comment]
@NatsuTheGreat 
What do I do ?

**Comment by Agarian** [comment]
replace it with ../core/GameServer if you use the latest version.
