### ISSUE TITLE
Server 100% malfunctioning

### ISSUE THREAD

**Issue by Lucario2** [AJS-development/Ogar-unlimited#801]
I kinda have a problem that's hard to explain so I made a video.
http://expirebox.com/download/bbfca7487124641362cf6f3193f10ca6.html

**Comment by problemsofworld** [comment]
you are just a spammer

**Comment by Lucario2** [comment]
Did you loom at my video you dumb insignificant shit

**Comment by problemsofworld** [comment]
really nigga u think am gonna go to virus website to download  a video that my computer dont read it 
its 100% spam

**Comment by Lucario2** [comment]
its a mp4 format u fuck

**Comment by Lucario2** [comment]
HOW FUCKING STUPID R U!!!!!!!!???????

**Comment by problemsofworld** [comment]
YOU SPAMMER AND DOMEASS its WEBM File (.webm)type

**Comment by Lucario2** [comment]
Thats for linux media

**Comment by Lucario2** [comment]
-_- I feel bad for u

**Comment by problemsofworld** [comment]
something hard to tell what a joke!

**Comment by Lucario2** [comment]
rly hoe

**Comment by Lucario2** [comment]
at least im not racist like u saying nigga

**Comment by problemsofworld** [comment]
I knew it u are nigga or a Russian gay

**Comment by problemsofworld** [comment]
and server malfunctioning?  in OGar Unlimited dude you are in wrong place  check ur URL

**Comment by ItzLevvie** [comment]
![image](https://cloud.githubusercontent.com/assets/11600822/15635483/2cd6d4e8-25d7-11e6-89e4-fdb9d6aadc0d.png)
@problemsofworld ^^ It's not a spam.
@Lucario2 the reason you're getting a wierd black cell is because some extensions will not work with the official client nor will it work with the Ogar-unlimited client. In order to play on your server you'll have to use play.ogarul.tk. **_Also did you try changing the ```packetversion = 1``` to ```packetversion = 0``` in settings/advConfig.ini (TRY THIS FIRST, OTHERWISE USE THE OGAR-UNLIMITED CLIENT)_**

**Comment by problemsofworld** [comment]
he could just pick a pic of problem

**Comment by NatsuTheGreat** [comment]
@Andrews54757 http://prntscr.com/b9wi23 Alright this guy has GOT TO GO.

**Comment by Andrews54757** [comment]
Everyone, should I ban @problemsofworld  again?

**Comment by problemsofworld** [comment]
ye

**Comment by NatsuTheGreat** [comment]
He is continuously flaming people, I say yes.

**Comment by Andrews54757** [comment]
@problemsofworld I am tired of your offensive comments. Why cant you actually be nice? Be a better person and then come here.


OFFENSE:
> Profanity, offending others


Today I hereby declare you BANNED from ogarUL for ~~1 week~~ 1 MONTH!
> Banned on May 29 . Will be appeased on June 29

**Comment by Lucario2** [comment]
.

**Comment by raphyjb** [comment]
.

**Comment by Lucario2** [comment]
...................................

**Comment by Lucario2** [comment]
character

**Comment by Andrews54757** [comment]
I hate offensive people. More than spammers

**Comment by raphyjb** [comment]
1.2.3 Killing spree

**Comment by raphyjb** [comment]
#SavageModeOn

**Comment by Andrews54757** [comment]
pls dont spam.

**Comment by Lucario2** [comment]
omg i love u guys *suicides*

**Comment by raphyjb** [comment]
K but andrew i had a problem can u go check? https://github.com/AJS-development/Ogar-unlimited/issues/796

**Comment by Agarian** [comment]
Am i the only one who regarded Lucario2's comments?

**Comment by Agarian** [comment]
Sum1 call 911
