### ISSUE TITLE
Server shows random stuff and mustly gridlines somtimes it shows me but im a hexagon

### ISSUE THREAD

**Issue by Mayo12** [AJS-development/Ogar-unlimited#802]
Server shows random stuff and mustly gridlines somtimes it shows me but im a hexagon

**Comment by problemsofworld** [comment]
use play.ogarul.tk

**Comment by NatsuTheGreat** [comment]
Make sure you are playing on [the ajs client](http://play.ogarul.tk) and you are not using any extensions. Also try changing ```packetversion``` if that does not help.

**Comment by Mayo12** [comment]
What is the packetversion? if you have skype you can add me : matthew10925
Kind regards Matthew
