### ISSUE TITLE
Question for plugins.

### ISSUE THREAD

**Issue by systemroot** [AJS-development/Ogar-unlimited#804]
Hello, 

Can i add a plugin on plugin library if plugin will not work only with nodejs ?!

**Comment by Tokoagar** [comment]
do plugin available

**Comment by systemroot** [comment]
:trollface: 
i know this, i will create one plugin, but i will not use nodejs with it, and for this i'm asking can i push it on ogar plugin library!

**Comment by LegitSoulja** [comment]
@systemroot No. All plugins will have to be working before its added to our library, and you will have to create a push request to update them in the future.
