### ISSUE TITLE
Help CPU 

### ISSUE THREAD

**Issue by mafiakb** [AJS-development/Ogar-unlimited#806]
My server have 70 user and 69% CPU USAGE for what?

![image](https://cloud.githubusercontent.com/assets/12769609/15636434/0a797ef4-25c4-11e6-990c-ba3d71161eb6.png)

**Comment by David1ali12** [comment]
70 bots or real players ?

**Comment by mafiakb** [comment]
Real players

**Comment by David1ali12** [comment]
#786 update comes soon  well 69% is normal for 70 players

**Comment by mafiakb** [comment]
then, what is of solution?

**Comment by David1ali12** [comment]
be patient untill new updates released

**Comment by mafiakb** [comment]
ohh ok ty :) closed
