### ISSUE TITLE
PLUGIN IP BOTS COUNTER?

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#807]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
default
What version are you on?
default
What command did you type if any?
nothin
You must have a description as well
I just wanna know if u guys could invent a plugin to get certain ip minion with their time, like paid bots.. so i could put my friend 20 bots, till 2016-05-29 to 2016-05-30 u know..

Not sure if that could be possible but that would be fucking great! :D Luv u guys thanks for helping me! Hope u guys can help!

**Comment by Agarian** [comment]
try the LBstats plugin here https://github.com/AJS-development/OgarUL-Plugin-Library

**Comment by raphyjb** [comment]
that only shows on leader board lol....

**Comment by LegitSoulja** [comment]
Hmm not too shabby

**Comment by LegitSoulja** [comment]
So do you want things cloud stored for the period of having minions? If not once the server closes, or stops, the periods won't be saved.

There could be other arranged by having a file to hold period data, but cloud is better :)

**Comment by Andrews54757** [comment]
but, what are you going to do with it? it seems like you want to make money off of them. And we dont support that so we wont make a plugin. You can

**Comment by Andrews54757** [comment]
very easy though

**Comment by David1ali12** [comment]
@Andrews54757  can a plugin add cavas to client ?

**Comment by LegitSoulja** [comment]
@David1ali12 plugins can, but isn't designed to. Therefor not possible, and for what reason?

**Comment by raphyjb** [comment]
ahh ahh ahh ahh ahh ahh ah :( Yes i would like to make money to be honest poeple ask me to put a paid service to play with minions on my server my server reaches 50 poeple playing.. and alot are pissed i dont have that service open. (Closed server for the reason that i need it to work on vps)

**Comment by Andrews54757** [comment]
@raphyjb We wont create it but you can, then if you make a PR to the plugin library, we may add it

**Comment by David1ali12** [comment]
@LegitSoulja i was just saying because  I wanted to make plugin to do add music lyrics to 
leaderboard
