### ISSUE TITLE
Andrew puede unirme a dev?

### ISSUE THREAD

**Issue by loganagar32** [AJS-development/Ogar-unlimited#808]
por favor responde

**Comment by Megabyte918** [comment]
What have you done for OgarUL?

**Comment by loganagar32** [comment]
me new not done anyting but soon me will hablas espanol?

**Comment by tomsterley** [comment]
And do you even know how to program. You posted this as an issue before and it got closed with the answer: No.

**Comment by David1ali12** [comment]
@loganagar32 Cuantos anos tienes ? ?

**Comment by Megabyte918** [comment]
What Andrew said from #509:

> Requirements


> 1. Experience with Node-JS and Javascript
2. Some proof of experience
3. Must be the top one contributed to Ogar UL that is not already a dev (use pull requests)
4. Some social experience (probably already fufilled)


> I am just looking for "well-rounded" people.

Also don't duplicate issues, may result in a ban

Google translate =P:

Andrew lo dijo desde el #509 :

> Requisitos


> 1. La experiencia con el Nodo - JS y Javascript
2. Algunas pruebas de la experiencia
3. Debe ser el de arriba contribuido a OgarUL que no hay ya un dev ( solicitudes de utilización de tracción )
4. Algunos experiencia social ( probablemente ya fufilled )


> Estoy en busca de la gente " bien redondeados " .

Asimismo, no duplicar temas , puede dar lugar a una prohibición

**Comment by loganagar32** [comment]
soy 7 anos soy dev

**Comment by loganagar32** [comment]
:cry:

**Comment by tomsterley** [comment]
You just don't get it do you?

**Comment by David1ali12** [comment]
he is a kid :P ofc  he wont get it
