### ISSUE TITLE
Can't Connect to server

### ISSUE THREAD

**Issue by SharkFinProductions** [AJS-development/Ogar-unlimited#809]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
all

What version are you on?
The Current one

What command did you type if any?
none

You must have a description as well
My server is fine, but when i hit play, i just get the white grid

**Comment by systemroot** [comment]
client host by you ?
or are you trying on play.ogarul.tk?

**Comment by SharkFinProductions** [comment]
Client host by me, i downloaded this yesterday, then it stopped working today, i have tryed reinstalling it multiple times, but it won't work
i am connecting with
ws://127.0.0.1:443
i am connecting by myself only

**Comment by SharkFinProductions** [comment]
**EDIT:** playing on _play.ogarul.tk_, i read what u asked wrong :/

**Comment by systemroot** [comment]
go to your client example http://prntscr.com/ba13j9
click on **console** 
CTRL+R to refresh page and tell me what are you reading on **console**

**Comment by SharkFinProductions** [comment]
![capture](https://cloud.githubusercontent.com/assets/18649707/15638804/e89b98e8-25d8-11e6-8b4b-77ffc7699c20.JPG)

Thats what i see

**Comment by SharkFinProductions** [comment]
![capture2](https://cloud.githubusercontent.com/assets/18649707/15638833/45d6bc4a-25d9-11e6-887e-f3049ceadf3a.JPG)

that broke XD
this is what i see

**Comment by systemroot** [comment]
that is just a image is not problem.
:confused: it looks good 
if your server is working as you say before. you will be able to play :/
if not make one screenshot after you start server with **node index.js**

**Comment by SharkFinProductions** [comment]
It just gives me the blank grid when i load up :/

**Comment by SharkFinProductions** [comment]
why won't it work?

**Comment by systemroot** [comment]
maybe you have an problem which you don't know how to explain us. 
nodejs can make problems anytime. so tell me what are'u reading when you start server right here 
![](https://camo.githubusercontent.com/51e32455d6819c4c0200ffb9c6647e4c54210ac1/687474703a2f2f7333332e706f7374696d672e6f72672f6a316f64686f626b762f53637265656e73686f745f322e706e67)

**Comment by SharkFinProductions** [comment]
![capture432](https://cloud.githubusercontent.com/assets/18649707/15639207/d0438904-25dd-11e6-9e02-25427b9205fd.JPG)

What i see

**Comment by SharkFinProductions** [comment]
I see an error...

**Comment by systemroot** [comment]
i don't know how to fix this in windows because i use Linux, 
So wait for Any reply From others.
Or try to uninstall and install nodejs again!

**Comment by SharkFinProductions** [comment]
i used the latest features version of node.js, should i use the reccommended for most users instead?

**Comment by SharkFinProductions** [comment]
Installed reccommended version and it works now =)
can u look at my YT channel?
(SharkFin Productions)

**Comment by systemroot** [comment]
yes. V.6 of node version some times is making those errors or will not work.
i Sub' you but pls don't spam here. If problem is solved you can hit on **close..**

**Comment by LegitSoulja** [comment]
@SharkFinPrdouctions please check for duplicate posts before creating. There's search filters you know.
