### ISSUE TITLE
Devs break tomorrow

### ISSUE THREAD

**Issue by XenoYT** [AJS-development/Ogar-unlimited#810]
Happy Break Day

**Comment by Agarian** [comment]
Idk

**Comment by Agarian** [comment]
My android has small buttons =/

**Comment by SorryAgario** [comment]
@XenoYT If you are impatient pls dont complain or u can make ur own cuz u think its that easy to code and make everything work again....

**Comment by LegitSoulja** [comment]
@SorryAgario nobody could've said it better

**Comment by Influxx** [comment]
Devs are allowed to go on breaks too, ya know. We're not robots.

**Comment by SorryAgario** [comment]
@XenoYT go stop complaining unless this was a PAID service.... good thing it was free and the devs are working hard for nothing. they have a life too... theyre not robots @Influxx Agreed.

**Comment by XenoYT** [comment]
@SorryAgario Go kill yourself i didnt talk to you

**Comment by raphyjb** [comment]
wowoowowowowowow Ill just hand myself yall could cry about me instead of fighting for a dumb kid who doesnt like a non paid service thats 24/7 and thats awsome!

**Comment by XenoYT** [comment]
@raphyjb your a 9 years old kid go kys

**Comment by NatsuTheGreat** [comment]
@Andrews54757 I think this guy is asking for a second ban too... 

http://prntscr.com/ba7dfb

http://prntscr.com/ba7dj9

**Comment by Andrews54757** [comment]
Offending others is not allowed. I am tired of this


OFFENSE:
> Offending others.


Today I hereby declare you BANNED from ogarUL for 1 month
> Banned on May 30. Will be appeased on june 30

**Comment by LegitSoulja** [comment]
Who was banned though? Guess the ban hammer didn't speak lol

**Comment by raphyjb** [comment]
LOL yo legit can u help meh (go on skype man)

**Comment by Megabyte918** [comment]
Why can't we have normal issues...

**Comment by Agarian** [comment]
Because ogarUL is overcrowding.

**Comment by Agarian** [comment]
`Kys` means 1kill yourself` in case no one knows.

**Comment by NatsuTheGreat** [comment]
I knew that :/
