### ISSUE TITLE
I got my VPS so everything went smooth until..

### ISSUE THREAD

**Issue by SorryAgario** [AJS-development/Ogar-unlimited#811]
I ran ogar unlimited after installing dependencies with npm install
then i typed this cd src
then node index 
Ogar Unlimited popped up, Im so happy till i got this error.
also do i connect with play.ogarul.tk or agar.io with extension?
Error: listen EACCES 0.0.0.0:88
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at StatServer.start (/home/ubuntu/workspace/Ogar-unlimited/src/core/StatServer.js:29:21)
    at GameServer.start (/home/ubuntu/workspace/Ogar-unlimited/src/core/GameServer.js:487:21)
    at ControlServer.start (/home/ubuntu/workspace/Ogar-unlimited/src/core/ControlServer.js:60:21)
    at Multiverse.create (/home/ubuntu/workspace/Ogar-unlimited/src/core/Multiverse.js:86:7)
    at Multiverse.init (/home/ubuntu/workspace/Ogar-unlimited/src/core/Multiverse.js:121:26)

**Comment by ItzLevvie** [comment]
Use sudo to run your server

**Comment by SorryAgario** [comment]
@ItzLevvie It works but im confused on how I can connect to my server? Thanks!

**Comment by David1ali12** [comment]
are u using koding.io?

**Comment by Influxx** [comment]
Make sure that the port you've set isn't already in use when you launch OgarUL. In order to connect to your server, launch OgarUL and connect to ws://your-vps-ip:port at play.ogarul.tk.

**Comment by SorryAgario** [comment]
@Influxx which port do u reccommend? i keep my skype on btw so i can tell my friends to join ^.^

**Comment by David1ali12** [comment]
![ogarw](https://cloud.githubusercontent.com/assets/17472593/15647807/b4d3f1b8-266e-11e6-9032-052e6d0e1c7e.PNG)
example: `ws://ogarul.koding.io:8080 `

**Comment by David1ali12** [comment]
![ogarw](https://cloud.githubusercontent.com/assets/17472593/15647867/214ca308-266f-11e6-9271-abf321f7c30b.PNG)
example:`ws://ogarul.koding.io:8080`

**Comment by Parth1999** [comment]
I cannot create a stack withou credit card?

**Comment by David1ali12** [comment]
![ogarw](https://cloud.githubusercontent.com/assets/17472593/15647931/a84fc790-266f-11e6-9407-6143c23844b2.PNG)

example :`ws://ogarul.koding.io:8080`

**Comment by SorryAgario** [comment]
@David1ali12 Do I get banned for using it? What did you do to not get banned? :3

**Comment by ItzLevvie** [comment]
Read https://github.com/AJS-development/Ogar-unlimited/issues/630#issue-155305531

**Comment by SorryAgario** [comment]
@ItzLevvie Thanks!

**Comment by Parth1999** [comment]
at ControlServer.start (/home/nitrous/Ogar-unlimited/src/core/ControlServer.js:60:21)
    at Multiverse.create (/home/nitrous/Ogar-unlimited/src/core/Multiverse.js:86:7)
    at Multiverse.init (/home/nitrous/Ogar-unlimited/src/core/Multiverse.js:121:26)
[Error] Please make sure you are running Ogar with root privileges.
[INFO] OgarUnlimited terminated with code: 1

:|

**Comment by raphyjb** [comment]
same error but i dont know how to run that Dependencies when on the command window, but i did what u said and i got this error.
Then got this error by changing in advsettings some stuff: 
[main] Listening on port 4411
[main] Current game mode is Free For All
[main] The Game Was Paused to save memory. Join the game to resume!

[Console] We recieved a world-wide message!: Hello, Please take this survey (http://goo.gl/forms/oZKMBudTnVvgD3n62) as we decide on the future of ogar unlimited.
[OK] Uniban updated
update all
[Console] Fetching data from the servers...
[Console] Updating...
[Console] Error: failed to download some or all files. err msg: [Update] [FAIL] Couldn't connect to servers. Failed to download: http://raw.githubusercontent.com/AJ
S-development/Ogar-unlimited/master/src/modules/commands/freeze.js
[Console] Error: server is likely not in a viable state. You should manually reinstall it!
[Console] Error: Shutting down!
[INFO] OgarUnlimited terminated with code: 3
cabox@box-codeanywhere:~/workspace/src$

**Comment by raphyjb** [comment]
sorryagario can u add me on skype: raphy.jb
