### ISSUE TITLE
Nitruos.io Problem

### ISSUE THREAD

**Issue by Parth1999** [AJS-development/Ogar-unlimited#812]
Ok so the sudo node index.js dont work in nitrous.io
Tried only node index.js but got error to start with root privilages
src git:(master) ✗ sudo node index.js
sudo: node: command not found

then tried node index.js
    at ControlServer.start (/home/nitrous/Ogar-unlimited/src/core/ControlServer.js:60:21)
    at Multiverse.create (/home/nitrous/Ogar-unlimited/src/core/Multiverse.js:86:7)
    at Multiverse.init (/home/nitrous/Ogar-unlimited/src/core/Multiverse.js:121:26)
[Error] Please make sure you are running Ogar with root privileges.
[INFO] OgarUnlimited terminated with code: 1

**Comment by ItzLevvie** [comment]
Read http://ubuntuforums.org/showthread.php?t=1695292

**Comment by Parth1999** [comment]
Still :( 
$ sudo su didnt work 
$ sudo su
zsh: command not found: $
so i tried only sudo su in src 
sudo su
root@rex-clan-185751:/home/nitrous/Ogar-unlimited/src#
ok then i tried # node index.js
root@rex-clan-185751:/home/nitrous/Ogar-unlimited/src# # node index.js
root@rex-clan-185751:/home/nitrous/Ogar-unlimited/src#
nothing happened so i tried only node index.js
root@rex-clan-185751:/home/nitrous/Ogar-unlimited/src# node index.js
bash: node: command not found
root@rex-clan-185751:/home/nitrous/Ogar-unlimited/src#

What to do?

**Comment by David1ali12** [comment]
my server is running on Nitruos.io but I cant connect :/ its says Upgrade Required dont connect with play.ogarul.tk

**Comment by Parth1999** [comment]
How have you passed this error?

**Comment by David1ali12** [comment]
I just installed it and it worked but I cant connect I even added 30 bots

**Comment by Parth1999** [comment]
i mean what command u typed to sttart server ? 
sudo node index.js ??

**Comment by David1ali12** [comment]
node index

**Comment by Parth1999** [comment]
and you didnt get error to run with root privilages?
How!!!!????

**Comment by David1ali12** [comment]
no

**Comment by Parth1999** [comment]
at ControlServer.start (/home/nitrous/Ogar-unlimited/src/core/ControlServer.js:60:21)
    at Multiverse.create (/home/nitrous/Ogar-unlimited/src/core/Multiverse.js:86:7)
    at Multiverse.init (/home/nitrous/Ogar-unlimited/src/core/Multiverse.js:121:26)
[Error] Please make sure you are running Ogar with root privileges.
[INFO] OgarUnlimited terminated with code: 1

:|

**Comment by David1ali12** [comment]
change port to 8080 
and server stats to 8082

**Comment by Parth1999** [comment]
OMG IT WORKED!!! Thanks :)

**Comment by David1ali12** [comment]
and how to connect to server it does not let me to connected wait could you connect to ur server?
trough play.ogarul.tk
```
`Connecting to ws://green-blackwater-bay-188175.nitrousapp.com:8080
http://play.ogarul.tk/split.png Failed to load resource: the server responded with a status of 404 (Not Found)
http://play.ogarul.tk/feed.png Failed to load resource: the server responded with a status of 404 (Not Found)
main_out.js?542:430 WebSocket connection to 'ws://green-blackwater-bay-188175.nitrousapp.com:8080/' failed: Error during WebSocket handshake: Unexpected response code: 500
main_out.js?542:436 socket error
main_out.js?542:466 socket close`
```

**Comment by ItzLevvie** [comment]
There should be a tab called "Port Forwarding" try that, and port forward the 8080 port

**Comment by David1ali12** [comment]
@ItzLevvie  no it does not have :confused:

**Comment by David1ali12** [comment]
nvm fixed ! close?

**Comment by SorryAgario** [comment]
@David1ali12 i get this however ;c 
TypeError: "callback" argument must be a function
    at exports.setTimeout (timers.js:314:11)
    at GameServer.mainLoop (/home/nitrous/Ogar-unlimited/src/core/GameServer.js:1543:7)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)


how do i fix this with nitrous.io?

**Comment by SorryAgario** [comment]
@ItzLevvie where is the tab "Port Forwarding"?

**Comment by Parth1999** [comment]
How have you fixed I can't connect through play. Ogarul.tk

**Comment by David1ali12** [comment]
Make sure that node version is 5.9.0 
`nvm install 5.9.0 `

**Comment by David1ali12** [comment]
@SorryAgario its portForwarded itself

**Comment by SorryAgario** [comment]
then after that, what do i do next and what is the ip?

**Comment by Parth1999** [comment]
K I will try it later

**Comment by David1ali12** [comment]
@SorryAgario 
press view tab and there its shows  the ports use `8080` and state port `8082`
you must use node 5.9.0 others wise you cant connect

**Comment by SorryAgario** [comment]
ok thanks bro! i saw what it is now i just need to add ws:// 
can my friends play with me by typing the same ip?

**Comment by SorryAgario** [comment]
thanks man it works! <3 u no homo im happy!
