### ISSUE TITLE
Why i can't make style to load from style.css.!!!

### ISSUE THREAD

**Issue by systemroot** [AJS-development/Ogar-unlimited#813]
I deleted ``style`` From index.html 
and i add one line 

![](http://s33.postimg.org/cbz0bqbqn/Screenshot_6.png)

and i add all style content into css/style.css and is not working
also i try to edit it 
![](http://s33.postimg.org/45dg3e6sv/Screenshot_8.png)
But is not working 
![](http://mylolface.com/assets/faces/annoyed-y-u-no.jpg)
How can i make style to load from css/style.css :confused: :question: :grey_question:

**Comment by NatsuTheGreat** [comment]
I don't know css, but I swee you're making a hyperlink there. Maybe try '.css/style.css' but make sure you have the css folder ready.

**Comment by systemroot** [comment]
folder is ok, you can't open a folder with '**.**' 
i have test with some simple steps

i add one text on index.html

``<div class="test">Wub Wub</div>``

and into css/style.css i write this

[code]
.test{
color: blue;
}
[/img]
and is not working :/ 
when i put .test style into index.html is working!

**Comment by ItzLevvie** [comment]
try ../css/style.css

**Comment by NatsuTheGreat** [comment]
Yeah I made a typo there.

ItzLevvie gave you the two options.

**Comment by systemroot** [comment]
@ItzLevvie 
example my style.css is in /public/css/style.css
and index.html is in /public/index.html
a folder into a folder is called "Sub Folder" and you can open sub folder like this **SubFolder/**
A Folder Can Be Opened with **/Folder** 
if we use **../css/style.css** this will search for **style.css** into **/public** Folder 
not on /public/css/
