### ISSUE TITLE
NEED HELP!!

### ISSUE THREAD

**Issue by anaelpop** [AJS-development/Ogar-unlimited#814]
an any one help me about how to port forwarding and join server?

**Comment by Parth1999** [comment]
Google

**Comment by anaelpop** [comment]
thanks not need to your help!

**Comment by NatsuTheGreat** [comment]
Use google to help you. Make sure you know your ISP as well so you get more accurate information. You can also get help at #174

**Comment by systemroot** [comment]
if you have a public ip you can do this pretty easy -.- open cmd write **ipconfig** get gateway ip and open it in your browser and change your ip from **dynamic** to **static**, 
Btw if your ip is not published by your provider you can't do this and don't try to do because you will start to have problems with internet. 
And as *NatsuTheGreat* say you can start with hamachi!

**Comment by anaelpop** [comment]
@systemroot is port forwarding =port mapping?

**Comment by systemroot** [comment]
yes is the same

**Comment by LegitSoulja** [comment]
@systemroot PF is always provided. It depends on your router type.

As I always say if the box ain't right dd-wrt might bring luck.

**Comment by LegitSoulja** [comment]
Google how to port forward your router type. 

- There's a automatic software called **Simple Port Fowarding** also you could use.
- Also you have to enable your ports to go through your firewall if it still doesnt work.

Depending on your network adapter whilst in cmd type 
> ipconfig

Or Linux 
> ifconfig

You will see your network adapter **Wireless** or **Ethernet** or both if your using both. You decide which network adapter you will use. I recommend Ethernet.

Under the adapter you chosen you will see these names,
- Default Gateway (Router main web page to edit configuration)
Google about how to obtain your router information.

- Ip Address (Your computer main local/lan IP address)
When you set the port use that ip when setting your ports to assign to your computer.

Make your IP address static for no ip changes between networking. You can do that on your computer network settings.
- Subnet (Some stuff to make sure you're not an alien)

Make sure you create and firewall a port of the,
- Client Port (if using)
- ServerPort (Recommended)
- Server Stat Port

**You're done :)**
