### ISSUE TITLE
When I start my server I cant play because my cell is too big, I start with 50000 mass

### ISSUE THREAD

**Issue by WolfOGG** [AJS-development/Ogar-unlimited#816]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?

What version are you on?

What command did you type if any?

You must have a description as well

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

Can you make minions split by pressing E or R key?
A: NO, as agar.io client doesn't support those keys. Otherwise, you would need to use another client, and that is illegal.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

**Comment by David1ali12** [comment]
Change packet version in Config to 1

**Comment by WolfOGG** [comment]
I changed it to 0 because I am using an extension to enter my server, is there a way to enter your own server without an extension?

**Comment by David1ali12** [comment]
no dont use ext make packet version 1 and use http://play.ogar.tk/

**Comment by WolfOGG** [comment]
So I basically just type that and then when it asks for server ip I enter my ip or localhost:443

**Comment by David1ali12** [comment]
its same  just make sure of ur port

**Comment by WolfOGG** [comment]
Ok, thanks for the help. :+1:

**Comment by WolfOGG** [comment]
I'm sorry if I'm bothering too much, but may I ask how do I get skins back I tried the code <Kraken> myname and I dint get the skin nor did the minions when I typed minion 1 20 </random>

**Comment by David1ali12** [comment]
dont ask for skins they will be back soon see 
![added skins](https://cloud.githubusercontent.com/assets/17472593/15654356/22cc8ff4-269c-11e6-9bcd-71469dda5940.PNG)
close issue ?

**Comment by WolfOGG** [comment]
Ok, thanks.

**Comment by notcarksss** [comment]
Easy fix do in the console this command "spawnmass [yourplayerid] 100"

**Comment by raphyjb** [comment]
omg omg omg omg omg omg omg omg CANT WAIT TILL SKINS ARE BACK OMGGGGG :OOOOOOOOOOOOO THIS IMAGE IS OPPPPPPP

**Comment by Agarian** [comment]
thats the agar client.

**Comment by LegitSoulja** [comment]
@Agarian skin minions are possible

**Comment by Agarian** [comment]
I know, he just used an extension on the agar client.

**Comment by Agarian** [comment]
Whi noticed the one minion named Martin?

**Comment by fayizan** [comment]
See this youtuber,he have new skins for ogarul https://youtu.be/Hdsjrd7GbLU
and he is trolling people that he is using facebook bots..!!

**Comment by Agarian** [comment]
HOW DID HE GET SKINS? I swear I'm missing out on skins...

**Comment by David1ali12** [comment]
@Agarian  dude its easy for skins on agario or even on ogarUL

**Comment by Agarian** [comment]
I use the ogarUL client...

**Comment by David1ali12** [comment]
@Agarian dont worry see this ogarul client XD I did not added all skins and smooth render 
![cleint](https://cloud.githubusercontent.com/assets/17472593/15663247/83768d40-2701-11e6-90c8-42a812a97a63.PNG)

**Comment by fayizan** [comment]
I was waiting for Andrew to fix skins but how u guys got the skins working..??!!

**Comment by fayizan** [comment]
@David1ali12 why I cannot connect to ogarul.io ..?

**Comment by LegitSoulja** [comment]
@David1ali12 did you get ogarul.io?

**Comment by LegitSoulja** [comment]
thats new

**Comment by David1ali12** [comment]
ye but it not on it says next 48hours :/
