### ISSUE TITLE
help

### ISSUE THREAD

**Issue by TheAngryGrandpa** [AJS-development/Ogar-unlimited#817]
Hello Everyone im new and i was wondering if someone can link me the website to play in ogar

**Comment by ItzLevvie** [comment]
play.ogarul.tk

**Comment by TheAngryGrandpa** [comment]
Thanks

**Comment by Agarian** [comment]
lol nice name

**Comment by LegitSoulja** [comment]
@Agarian do you know the kid behind the camera? Lol

**Comment by Agarian** [comment]
yes

**Comment by Agarian** [comment]
the angry grandpa show
