### ISSUE TITLE
Router Crashed internet shutdown.

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#818]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
1
What version are you on?
new
What command did you type if any?
nothing
You must have a description as well
Internet crash, router crash

Wat i do? Closed the port to my server.. Idk how to set up on VPS

**Comment by Parth1999** [comment]
Please give a description. If you wanna set up vps use hamachi.

**Comment by Parth1999** [comment]
If you are new never mess up with router settings

**Comment by raphyjb** [comment]
im not new no worry`s got my server port foward and all but.. it crashed my router i only had 150 poeple online i odnt get it... router is anti ddos.. but even anti ddos.. to many connections..

**Comment by raphyjb** [comment]
doing a vps right now can anyone help me up! XD not that good with vps

**Comment by LegitSoulja** [comment]
Wait.. Anti Denial? Haha.. And how does your internet shut down?

**Comment by raphyjb** [comment]
Hm it shut down... I mean internet crashed router did a reboot.. u know normal ddos stuff!
Can u pick up on skype?

**Comment by LegitSoulja** [comment]
You said routers are anti denial, but then you say denials does that types of things, well not.

Denial (low) = Router package flood which could make your internet slow, and also drop internet Mbps.
Denial (high) = Could potentially flood your router for no use until finished, and if your router cannot handle its packages it will crash and reboot. Normally this really doesn't happen.

**Comment by LegitSoulja** [comment]
And if you got attacked that fast, then I don't think you was attacked by denial and your router cannot handle a lot of connections.

**Comment by raphyjb** [comment]
Its Anti DDOS i mean, and my router can connect like 300 connections before
i got a crash

2016-05-30 13:50 GMT-04:00 LegiTPanda <notifications@github.com>:

**Comment by LegitSoulja** [comment]
Ok that's good.. And what about the speed? Not all routers can handle it, and when denial attack happens it will entirely slow down the network and could crash the router. 

By means, what kind of router do you have anyways? I have an high end. Cisco.

**Comment by raphyjb** [comment]
i got Asus, its a bomb router hm ill give more info on skype need talk to u
man :/

2016-05-30 14:10 GMT-04:00 LegiTPanda <notifications@github.com>:

**Comment by systemroot** [comment]
can you tell us port speed of your neet? 
if you are under 50|MB/s Ofcourse you will got crashed.

**Comment by raphyjb** [comment]
faster then urs lol
