### ISSUE TITLE
blobs shaking AF

### ISSUE THREAD

**Issue by bangana** [AJS-development/Ogar-unlimited#819]
Sometime when i start playing i start as 1 mass cell or when i hit the wall it teleports me to the other side and shakes does that happen to you or just me ?

**Comment by WolfOGG** [comment]
you wanna come to my server?

**Comment by David1ali12** [comment]
@LegitSoulja  please fix or pm me because I fixed

**Comment by LegitSoulja** [comment]
@Darwinkel those problems has always been there since the client released. Not to many people claim about this issue, nor people rarely get this issue, but I always do at times. :/

**Comment by NeptoonYT** [comment]
@LegitSoulja I get it a lot I just refresh the page.

**Comment by LegitSoulja** [comment]
@NeptoonYT Yea. or just wait until the cell hits the border lol

**Comment by bangana** [comment]
xD

**Comment by bangana** [comment]
@WolfOGG Uhmm is there any way to join ya ? i mean is it possible to join each other ?

**Comment by Aanis12** [comment]
to fix that problem just refresh well it works for me atleast refresh because you ID if your first will be "1" change into 2 so thats it xD

**Comment by Aanis12** [comment]
refresh the page

**Comment by bangana** [comment]
lel yeah but it is annoying to keep doing that xD
