### ISSUE TITLE
vps?

### ISSUE THREAD

**Issue by alexplayzz** [AJS-development/Ogar-unlimited#820]
i have a vps at ovh.com but can not figure out how to use it to run my server someone plz help

**Comment by LegitSoulja** [comment]
Each hosting company has a different layout if things.. Someone who has used ovh.com could help you but technically this isn't the place for help.

**Comment by alexplayzz** [comment]
okay, well legit can i get ur skype or somewhere where i can private message you and u trry to help me set it up

**Comment by LegitSoulja** [comment]
@alexplayzz I'm affraid sorry, but hopefully someone else can help you.

**Comment by alexplayzz** [comment]
okay well can u leave this open so i can try to get someone to help me?
