### ISSUE TITLE
"Server Info" feature?

### ISSUE THREAD

**Issue by EnTerr** [AJS-development/Ogar-unlimited#823]
I saw this feature in OgarServ that seems useful to me, it's an extension of the Agario protocol at client and server id=90, see http://agar.gcommer.com/Protocol#Server_Info_.28opcode_90.29_.5BOgarServ.5D

OgarServ sends id 90 to the client on connect some info about the server (or the client can explicitly ask for it via empty packet 90). I consider it useful because it may help a "smart" client to judge the health or desirability of a server it just connected to - say by number of connected players (if there are too many - expect lag, if 0 = boring/"sick"/abandoned for some other reason) or uptime.

Seems to me not a bad idea for OgUL to have the feature too

PS. for idea of implementation, https://github.com/JaraLowell/OgarServ/search?q=ServerInfo

**Comment by Andrews54757** [comment]
Use server stats

**Comment by EnTerr** [comment]
What is "server stats"? 
"I am a client", i don't have server console to look at.
