### ISSUE TITLE
fake meh ERROROROROROROr

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#824]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
1
What version are you on?
Newest
What command did you type if any?
npm install, npm install socket.io, npm install websocket
You must have a description as well
Well im trying to run it off on codeanywhere.com and got this error.. I got a vps, i know im really close to get it but idk what missing.
                                        _ _       _              _
                                       | (_)     (_)_           | |
  ___   ____  ____  ____    _   _ ____ | |_ ____  _| |_  ____ _ | |
 / _ \ / _  |/ _  |/ ___)  | | | |  _ \| | |    \| |  _)/ _  ) || |
| |_| ( ( | ( ( | | |      | |_| | | | | | | | | | | |_( (/ ( (_| |
 \___/ \_|| |\_||_|_|       \____|_| |_|_|_|_|_|_|_|\___)____)____|
      (_____|
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 16.7.8
TypeError: `port` or a `server` must be provided
    at new WebSocketServer (/home/cabox/workspace/node_modules/ws/lib/WebSocketServer.js:44:11)
    at GameServer.start (/home/cabox/workspace/src/core/GameServer.js:247:25)
    at ControlServer.start (/home/cabox/workspace/src/core/ControlServer.js:60:21)
    at Multiverse.create (/home/cabox/workspace/src/core/Multiverse.js:86:7)
    at Multiverse.init (/home/cabox/workspace/src/core/Multiverse.js:121:26)
    at Object.<anonymous> (/home/cabox/workspace/src/index.js:38:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
[OK] Uniban updated

**Comment by MrRageGamersMC** [comment]
humm

**Comment by David1ali12** [comment]
how errors u get perday lol

**Comment by raphyjb** [comment]
CANT HOST ???? OMG ._. butttttttttttt Legitsoulja said it could.

**Comment by raphyjb** [comment]
wat site can host it with a vps?

**Comment by LegitSoulja** [comment]
Lol. Don't use vps in advConfig

**Comment by raphyjb** [comment]
ahh ur gay .... FUCKKCKCKCKCK

**Comment by raphyjb** [comment]
#Raging RN

**Comment by raphyjb** [comment]
iohdf gdophfr; oisd;f«odhf;sis«hdf l;ihs;dlfgs;hg`pso;dj fsdraoh reof;ois afdeao o degaoeu urgihfaq;ouh ed;oi ho ;OISG;ODHFAOY;SIOGHD;SOI AHD;SOHFAISDF ;OAIYHERFPIQ UA`WEPU VQ1-9RTYE O893Y5-90137Q ^0 fuck my live wasted 8 hours watching my screen waiting for a answer

**Comment by Megabyte918** [comment]
read the error
