### ISSUE TITLE
Ogarul.io 

### ISSUE THREAD

**Issue by David1ali12** [AJS-development/Ogar-unlimited#825]
![ogarul](https://cloud.githubusercontent.com/assets/17472593/15660298/1fcbd836-26e3-11e6-97e4-79a0a26feb16.PNG)
:tada: 
domain will be on soon  http://ogarul.io/

**Comment by Megabyte918** [comment]
wut

**Comment by David1ali12** [comment]
I got the domain will be on soon

**Comment by Agarian** [comment]
We already have 2 sources for our client, why would we need 3?

**Comment by David1ali12** [comment]
ogarul.io is easy to remember  and good for google SEO .

**Comment by LegitSoulja** [comment]
We do not care about SEO
