### ISSUE TITLE
please help ;( STILL GOT ERROR

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#826]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
default
What version are you on?
new
What command did you type if any?
Nothing special
You must have a description as well
Got error plss help trying to run it off codeanywhere.com

                                        _ _       _              _
                                       | (_)     (_)_           | |
  ___   ____  ____  ____    _   _ ____ | |_ ____  _| |_  ____ _ | |
 / _ \ / _  |/ _  |/ ___)  | | | |  _ \| | |    \| |  _)/ _  ) || |
| |_| ( ( | ( ( | | |      | |_| | | | | | | | | | | |_( (/ ( (_| |
 \___/ \_|| |\_||_|_|       \____|_| |_|_|_|_|_|_|_|\___)____)____|
      (_____|
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 16.7.8
Error: listen EACCES 0.0.0.0:88
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1218:19)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at StatServer.start (/home/cabox/workspace/src/core/StatServer.js:29:21)
    at GameServer.start (/home/cabox/workspace/src/core/GameServer.js:487:21)
    at ControlServer.start (/home/cabox/workspace/src/core/ControlServer.js:60:21)
    at Multiverse.create (/home/cabox/workspace/src/core/Multiverse.js:86:7)
    at Multiverse.init (/home/cabox/workspace/src/core/Multiverse.js:121:26)
[Error] Please make sure you are running Ogar with root privileges.
[INFO] OgarUnlimited terminated with code: 1
cabox@box-codeanywhere:~/workspace/src$

**Comment by Megabyte918** [comment]
use sudo

**Comment by raphyjb** [comment]
sudo?

**Comment by Megabyte918** [comment]
do `sudo node index.js`

**Comment by raphyjb** [comment]
k

**Comment by raphyjb** [comment]
/home/cabox/workspace/src/index.js:3
const Readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by raphyjb** [comment]
how do we run the Install Dependencies (windows) thingy with the command only

**Comment by raphyjb** [comment]
Then got this error by changing in advsettings some stuff: 
[main] Listening on port 4411
[main] Current game mode is Free For All
[main] The Game Was Paused to save memory. Join the game to resume!
>[Console] We recieved a world-wide message!: Hello, Please take this survey (http://goo.gl/forms/oZKMBudTnVvgD3n62) as we decide on the future of ogar unlimited.
[OK] Uniban updated
update all
[Console] Fetching data from the servers...
[Console] Updating...
>[Console] Error: failed to download some or all files. err msg: [Update] [FAIL] Couldn't connect to servers. Failed to download: http://raw.githubusercontent.com/AJ
S-development/Ogar-unlimited/master/src/modules/commands/freeze.js
[Console] Error: server is likely not in a viable state. You should manually reinstall it!
[Console] Error: Shutting down!
[INFO] OgarUnlimited terminated with code: 3
cabox@box-codeanywhere:~/workspace/src$

**Comment by MinersMC** [comment]
update nodejs? maybe

**Comment by ItzLevvie** [comment]
[Console] Error: failed to download some or all files. err msg: [Update] [FAIL] Couldn't connect to servers. Failed to download: http://raw.githubusercontent.com/AJ
S-development/Ogar-unlimited/master/src/modules/commands/freeze.js
[Console] Error: server is likely not in a viable state. **You should manually reinstall it!**

Why don't you read the error first?
