### ISSUE TITLE
How to Setup your own private server in Nitrous.io

### ISSUE THREAD

**Issue by SorryAgario** [AJS-development/Ogar-unlimited#827]
So, I want to post this because I want to help people out in terms of making their own private servers without the need of credit card. 
Go to https://www.nitrous.io if you have an account, sign in, if you don't have one yet, sign up.
*make sure to put your legit email because you will need to confirm it before you can create your VM*
After that, Click the first package, then choose the location closest to where you live.
then Create. then add workspace. Choose "Node.js" then create. this is where the tricky part starts.
so. you will see a window which is color black or so called command prompt/terminal.
i think you cannot use control+v to paste stuff there so you need to type these the same.
`apt-get install git-all`
Be patient. then if it asks you to confirm for installation press y then enter
(important)
`nvm install 5.9.0`
takes about a minute or so, be patient.
(important)
`git clone https://github.com/AJS-development/Ogar-unlimited`
(important) type it with the capital letters and small letters
`cd Ogar-unlimited`
(important) to specify location.
`npm install`
(important) to install dependencies

Do this or it wont run!
-------------------------------------------------
open src folder then open settings folder
click advConfig.ini then it will open.
set serverPort to 8080 and 
serverStatsPort to 8082 then save by clicking the file tab and save.

--------------------------------------------------
**Now You need to start it up.**
`cd src`
(important)
`node index`
**Congrats! You Successfully started OgarUL**
--------------------------------------------------
**Connecting to your server**
in the Preview tab, click port 8080
then copy the link in the address bar.
then go to [play.ogarul.tk](url) then paste the
link you copied from the address bar. then delete
the http:// part and replace it with ws:// then delete the / in the end of the 
address. 
**You can now play with your friends in your private server.**
[play.ogarul.tk](url) then paste the same thing that you put into the address bar.
**HAVE FUN!**

**Comment by Agarian** [comment]
Bruh "copy the thing"
This should seriously be more descriptive, with images as well. And nitrous.io may not be happy with people using ogarUL alot. They would soon ban ogarUL. I mean Its not like any FREE vps would be good. Thats impossible.

**Comment by Agarian** [comment]
lol you didn't need to close this issue

**Comment by David1ali12** [comment]
I still can host on c9.io without getting banned but I dont share if i do they will patch it better dont share info about host ,not public info keep in private :wink:

**Comment by LegitSoulja** [comment]
@David1ali12 It doesn't matter if you dont give out the information. It's already bad enough to have the server running. Once your server get spotted, youy server will get banned along with others. It doesn't matter about the connecting people.

**Comment by David1ali12** [comment]
I know what ur talking about but I found away that its impossible to get banned its a week am running my server but it restarts every 2 hours   which I cant

**Comment by Agarian** [comment]
How? 2.5gb?

**Comment by SorryAgario** [comment]
hacks

**Comment by David1ali12** [comment]
@Agarian  you really want ? any link to private chat I can tell how to do it for #FREE :)

**Comment by Agarian** [comment]
ok

**Comment by Agarian** [comment]
how to pm there?

**Comment by Agarian** [comment]
i dent a message via ogar ul forums

**Comment by Hey1234567** [comment]
first command (this apt-get install git-all) says 
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

**Comment by ItzLevvie** [comment]
do sudo apt-get install git-all

**Comment by Hey1234567** [comment]
Thanks ^^

**Comment by LegitSoulja** [comment]
@ItzLevvie @Hey1234567 git-all doesnt exist..
- sudo yum install git (Install Git)
- sudo yum groupinstall "Development Tools" (C+ compiler update)

When installaing node you may have permissions errors such as doing sudo node or sudo npm
you can fix that by doing
- sudo ln -s /usr/local/bin/node /usr/bin/node
- sudo ln -s /usr/local/lib/node /usr/lib/node
- sudo ln -s /usr/local/bin/npm /usr/bin/npm
- sudo ln -s /usr/local/bin/node-waf /usr/bin/node-waf

**Comment by Hey1234567** [comment]
@LegitSoulja 
Does the ip you get only works for others? like after clicking the port 8080 thing i paste the ip to agario but it doesnt work (agarplus not agario)

**Comment by LegitSoulja** [comment]
@Hey1234567 ? When you make a server by defualt without port forwarding you can connect localhost with 
- ws://127.0.0.1:443

If you have a client yourself. You can go to 127.0.0.1:8080,
and in the client folder via index.html you can change to what your server connects to

**Comment by Hey1234567** [comment]
@LegitSoulja I told someone in my clan to join but it didnt work :/ 
Any help?

**Comment by SorryAgario** [comment]
@LegitSoulja Helped him, he is my clanmate btw :D
