### ISSUE TITLE
Spawned glitch BLACK CELL

### ISSUE THREAD

**Issue by ViinKz** [AJS-development/Ogar-unlimited#828]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?

What version are you on?

What command did you type if any?

You must have a description as well

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

Can you make minions split by pressing E or R key?
A: NO, as agar.io client doesn't support those keys. Otherwise, you would need to use another client, and that is illegal.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

**Comment by Agarian** [comment]
no description?

**Comment by Agarian** [comment]
this is a packet version issue. try setting `packetversion` in `advconfig.ini` to 1

**Comment by ViinKz** [comment]
where is the "packetversion"

**Comment by ViinKz** [comment]
@Agarian How??

**Comment by Megabyte918** [comment]
go to src/settings/advconfig.ini and open it
