### ISSUE TITLE
Spawned glitch BLACK CELL (OGAR UNLIMITED) HELP ;-;

### ISSUE THREAD

**Issue by ViinKz** [AJS-development/Ogar-unlimited#829]
when i have installed the Ogar unlimited 16.7.8

i had a bug spawning with a black or a dark green cell and and my cell glitching , cant even play or move in private server. 
i cant even see anything but the grid moving.
it doesn't happen to everyone i guess. 
but please i tried to find a solution but no one had this problem i guess.
(sorry for my english) 
![image](https://cloud.githubusercontent.com/assets/19667528/15675080/3dff321c-2751-11e6-8b2b-a44948980106.png)

![image](https://cloud.githubusercontent.com/assets/19667528/15675307/6e9d7324-2752-11e6-8ed6-73d45dbe753b.png)

THANK YOU.

**Comment by Megabyte918** [comment]
Disable extensions and try using the packetversion config in advconfig.ini

**Comment by Andrews54757** [comment]
use play.ogarul.tk
