### ISSUE TITLE
Pls improve splitting mechanics

### ISSUE THREAD

**Issue by firelightning13** [AJS-development/Ogar-unlimited#83]
How to split slower but still in further range?

The range is good but the way the split was too fast.

P.S: my english sucks

**Comment by Agarian** [comment]
Try using the splitspeed config in gameserver.ini

**Comment by Andrews54757** [comment]
yes, follow agarians advice

**Comment by firelightning13** [comment]
Well u dont understand my question do u? well thats ok cus i gave u the wrong question. haha (rip english)

What I meant is that how to configure its split range?

I can just simply put in like splitSpeed = 130 to something really lower but the lower the speed, the lower its split range. SO how can I change its range???? Just add var splitRange ? O.o

I dunno much about coding sry ^.^''
