### ISSUE TITLE
Soo smoothh. 

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#835]
I have to say. 17.0.0 Stability update hit the fan. This is pretty impresive. 

@Andrews54757 I don't know if the game still a little bit bugged or its my performance and internet which I doubt. But look at one of my agariohub servers here http://stats.ogarul.tk

**Comment by LegitSoulja** [comment]
I don't know if the game still a little bit bugged or its my performance and internet which I doubt. But look at one of my agariohub servers here http://stats.ogarul.tk

**Comment by Andrews54757** [comment]
Thanks! I worked really hard in that update.I dont see anything wrong

**Comment by Parth1999** [comment]
Fking Andrew you are God Amazing Update FUCK MONEYSHIT ITS BETTER THAN REAL AGAR

**Comment by systemroot** [comment]
good update, 
testing superminions in a srv with 8GB Ram/ 6CPU, 
300 superminions = 28% off server memory,
https://s26.postimg.org/md5571zuh/Screenshot_1.png

But how to fix Client because is not working sometimes is showing an blue screen and some times green screen, !

thanks! :smile:  :+1:

**Comment by Agarian** [comment]
but the client lags

**Comment by Agarian** [comment]
even show mass no longer works

**Comment by Agarian** [comment]
its EPIC

**Comment by Agarian** [comment]
@LegitSoulja now would be a good time 4 a skin changer plugin? :D

**Comment by Agarian** [comment]
lol i wish i could add "Andrews" to the label

**Comment by LegitSoulja** [comment]
@Agarian . Yes it would be :)

**Comment by Zertag** [comment]
in the old client bots were 132 mass and wwe didnt stop growing at 650 fix this plz

**Comment by AgarioIsBest1602** [comment]
How to get 17.0.0?

**Comment by Agarian** [comment]
Download it...

**Comment by Zertag** [comment]
hahahahah
