### ISSUE TITLE
Skins problem

### ISSUE THREAD

**Issue by TheAngryGrandpa** [AJS-development/Ogar-unlimited#837]
My skins doesnt work and Doge skin too :(

**Comment by zKurama** [comment]
HELP MEEE !!!!!! http://prntscr.com/bbyjj0

**Comment by reaper999666** [comment]
Do /update all

**Comment by zKurama** [comment]
New Version OgarUN 17.0.0 - Ex: <kraken>YourName

**Comment by zKurama** [comment]
Nova Versão OgarUN 17.0.0 - Ex:[<kraken>] YourName

**Comment by TheAngryGrandpa** [comment]
@Andrews54757 HELP me andrew

**Comment by firelightning13** [comment]
It's broken

**Comment by olivierek6** [comment]
it's probably broken

**Comment by Andrews54757** [comment]
add this line in custom skins.txt:

>doge :http://agarioskins.com/img/skin/doge.png

**Comment by Agarian** [comment]
Now i have an idea, a file that allows skins to be used by name.

**Comment by Agarian** [comment]
Instead of using < >
