### ISSUE TITLE
Any method to let friends join

### ISSUE THREAD

**Issue by bangana** [AJS-development/Ogar-unlimited#838]
i just need method to let my friends join me hamachi won't work 4 me

**Comment by raphyjb** [comment]
Portfoward. go on ur router (Admin and pass u will need) then go in section where it says port forward and put in port range 443 and there a button to inclued TCP and somehting else click both and ur done

**Comment by bangana** [comment]
i did it's not working :s

**Comment by Andrews54757** [comment]
hamachi is awful. Dont use it
