### ISSUE TITLE
I went to Play.OgarUL.tk (Account Suspended) ???

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#839]
I literally have just went on play.ogarul.tk and then this page comes up:

http://play.ogarul.tk/cgi-sys/suspendedpage.cgi

ACCOUNT SUSPENDED
R.I.P

**Comment by lotfis** [comment]
http://play.ogarul.tk/?ip=s3.agariohub.tk:443

**Comment by elitajmx** [comment]
Doesn't work, same page comes up after i go there wtf? rip for me?

**Comment by elitajmx** [comment]
well i think i got banned even though there is no reason to get me banned off that page!

**Comment by ItzLevvie** [comment]
You didn't get banned, the website got suspended for whatever reason.

**Comment by raphyjb** [comment]
MINICLIP FUCKED US

**Comment by elitajmx** [comment]
oh okay

**Comment by David1ali12** [comment]
Not working for me too :/

**Comment by raphyjb** [comment]
#COPYRIGHT FROM MINICLIP

**Comment by ItzLevvie** [comment]
@raphyjb It's not about Miniclip..

**Comment by David1ali12** [comment]
And my local client does not support version 17.0.0  :/

**Comment by raphyjb** [comment]
17.0.0 works perfectly for me untill i rest it .. :(

**Comment by raphyjb** [comment]
WDF someone is in my server and even refreshed and it works for him BUT NOT OTHERS :(

**Comment by ErikParacelsus** [comment]
@raphyjb lol wtf are you talking about

**Comment by raphyjb** [comment]
Im talking about 1 person who is in my server .. he says it works fine.. but all other 50 poeple complaining on skype saying server doesnt work.. xD

**Comment by David1ali12** [comment]
You can use my client but dont support version 17.0.0 
http://ogarul.io/
![snip](https://cloud.githubusercontent.com/assets/17472593/15782491/3aa50ba0-29b3-11e6-8b5e-f138c0a3ede8.PNG)

**Comment by raphyjb** [comment]
CAN WE DO AN UPDATE FOR THE MINIONS TO GET NO NAMES AND RANDOMS SKINS :O !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
