### ISSUE TITLE
Close this

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#84]
Could i actually use skins like: Kraken,trex,mammoth and such?

**Comment by elitajmx** [comment]
nevermind i can use them haha sorry

**Comment by Agarian** [comment]
cant you?

**Comment by Andrews54757** [comment]
lol agar.io is down

**Comment by ItzLevvie** [comment]
@Andrews54757 Miniclip is doing some security patches.

**Comment by Agarian** [comment]
no wonder...

**Comment by Agarian** [comment]
but what new features?

**Comment by Agarian** [comment]
new gamemodes? or something?
