### ISSUE TITLE
I GOT BANNED? FOR NO REASON????????

### ISSUE THREAD

**Issue by PolluxAgarioYT** [AJS-development/Ogar-unlimited#841]
![wtf](https://cloud.githubusercontent.com/assets/19731334/15782009/cd01b114-29d2-11e6-860f-3fab343fe087.jpg)

Now I got that when I tried to play play.ogarul.tk and that was weird. It happened to my friend to. Normally I would use this link 
ws://*****-*******-189055.nitrousapp.com:8080
or 
ws:/***-***-185751.nitrousapp.com:8080(message me for the real link if you got the solution)

I didn't do anything that got me banned. The time I saw this I was in literally shock.I was like what the heck just happened. I don't think using custom servers like those is breaking the ogar rules. If it is please inform and unban me. I'll stop using those links

THANKS!!!!!!

**Comment by ItzLevvie** [comment]
You're not banned, the website has been suspended. Just wait for a Developer to fix this issue.

**Comment by ErikParacelsus** [comment]
@ItzLevvie lol you're fast

**Comment by ViinKz** [comment]
same :(

**Comment by bangana** [comment]
everyone does lol you're not banned don't cry xDD
they'll fix it

**Comment by olivierek6** [comment]
same

**Comment by PrinceDark9243** [comment]
same

**Comment by LegitSoulja** [comment]
@PolluxAgarioYT I'm changing a few things

**Comment by MonsterYT** [comment]
Same , hope they fix this soon.
