### ISSUE TITLE
I GOT BANNED?! please tell me a fix 

### ISSUE THREAD

**Issue by MizovoGames** [AJS-development/Ogar-unlimited#842]
![2016-06-03](https://cloud.githubusercontent.com/assets/19732364/15782599/a6c9a3b8-29b3-11e6-9aeb-bf5ee3dcfb91.png)

i went on the client thinking i will play, but it says account suspended i didnt do anything wrong plz fix this ;(

**Comment by ErikParacelsus** [comment]
#841

**Comment by MizovoGames** [comment]
?

**Comment by MizovoGames** [comment]
It is fixed now thank u :) also not every skin is in the new ogar can u
please also fix some bugs and get high quality pictures that would be grate
full I love ur work <3
