### ISSUE TITLE
 Working client! with version 17.0.0

### ISSUE THREAD

**Issue by David1ali12** [AJS-development/Ogar-unlimited#843]
http://ogarul.io/ note:dont use ip with link  like `http://ogarul.io/?ip=127.0.0.1:443`
just put ur server in input to join  example`ws://127.0.0.1:443`
Enjoy !
![join](https://cloud.githubusercontent.com/assets/17472593/15784618/f06003ca-29bb-11e6-8640-1cdb08bcb242.PNG)

**Comment by raphyjb** [comment]
cant u do it so we can ahave a link like ?ip=myip:port

**Comment by David1ali12** [comment]
soon I will make it

**Comment by raphyjb** [comment]
ok and how we change minions name to something else?

**Comment by ErikParacelsus** [comment]
@David1ali12 care if you can try my server? http://agar.io/?ip=ogar-server-01-189334.nitrousapp.com:8080 it works on agar.io scearch bar

**Comment by bangana** [comment]
minion 'playerID' 'amount' 'name' 'mass if you have superminion plugin'

**Comment by raphyjb** [comment]
I mean minion name change to something else so when i do minion 1 100 (NAME) i can just dont put a name

**Comment by David1ali12** [comment]
@ErikParacelsus  was that ogar ? or ogar UL

**Comment by bangana** [comment]
'-' same

**Comment by bangana** [comment]
ogar ul is ogarUnlimited bruuuuuuuuuuuh

**Comment by ErikParacelsus** [comment]
Modified Version of Ogar

**Comment by lotfis** [comment]
can u put chat?

**Comment by AverageUser123** [comment]
@David1ali12 Thanks a lot.Because of you I can still play on my private server :D.
I have one question: 

When you going to add party mode? And my friend just need to copy my party token to join? (It's 2 questions xd)

Sorry for any grammar errors ;)

**Comment by olivierek6** [comment]
erik how did you get the server

**Comment by ErikParacelsus** [comment]
@lotfis i cant cause this is official agar.io client

**Comment by David1ali12** [comment]
average he need to put ur token to join 
@lotfis you can use w instead of what :p

**Comment by olivierek6** [comment]
@erikparacelsus srsly u named me..

**Comment by lotfis** [comment]
@ErikParacelsus how did you make the server?

**Comment by ErikParacelsus** [comment]
lol

**Comment by ErikParacelsus** [comment]
rip server crashed

**Comment by raphyjb** [comment]
got a problem anyone knows wat i did to do that, so i put 15 bots to 3 poeple with a plugin and it changes ever 3minutes, ok, now when it goes to someone else it says Remove all minions.. then 15 15 15 to 3 new poeple but bots are going up, started at 45 and now im up to 75 now 60.

**Comment by ErikParacelsus** [comment]
@raphyjb Create your issue

**Comment by lotfis** [comment]
can you a tutorial on youtube or something..................

**Comment by AverageUser123** [comment]
@David1ali12 Thanks a lot ;)

**Comment by raphyjb** [comment]
HM HOSTGATOR ERROR WDF!

**Comment by Agarian** [comment]
Page doesn't work in firefox

**Comment by Andrews54757** [comment]
You can host one if you like, but beware of risks. If you get sued, we will not be responsible

**Comment by David1ali12** [comment]
@Andrews54757 
Dont worry all info are fake miniclip cant do anything , the only thing can close the website . 
I'm responsible for what I'm doing.

**Comment by LegitSoulja** [comment]
@David1ali12 How was the CC fake? If it was you would have never purshased the site. Hostgator has there own privavy. They wont terminate you, but would ask you to remove the files, or they will do it themeselves, or could just delete everything from your FM.

**Comment by Andrews54757** [comment]
im closing this
