### ISSUE TITLE
Help Me!!! New version OgarUN 17.0.0 - http://prntscr.com/bbyjj0

### ISSUE THREAD

**Issue by zKurama** [AJS-development/Ogar-unlimited#844]
Help Me!!! New version OgarUN 17.0.0 - http://prntscr.com/bbyjj0

**Comment by zKurama** [comment]
Help Me!!! New version OgarUN 17.0.0 - http://prntscr.com/bbyjj0

**Comment by MonsterYT** [comment]
Download the 1.7.0 here: https://github.com/AJS-development/Ogar-unlimited/tree/master

**Comment by zKurama** [comment]
did not work

**Comment by LegitSoulja** [comment]
@zKurama https://codeload.github.com/AJS-development/Ogar-unlimited/zip/master

**Comment by zKurama** [comment]
where I enter the server when I open the Server
