### ISSUE TITLE
Working client with 17.0.0

### ISSUE THREAD

**Issue by loboere** [AJS-development/Ogar-unlimited#846]
http://ajs-development.github.io/client/

open console and paste connect("ws://127.0.0.1:443")

**Comment by zKurama** [comment]
did not work

**Comment by LegitSoulja** [comment]
You enter it when it asks you

**Comment by zKurama** [comment]
do not ask me to come

**Comment by firelightning13** [comment]
The prompt box is removed

**Comment by LegitSoulja** [comment]
@firelightning13 it probably was converted to 

http://ajs-development.github.io/client/?ip=127.0.0.1:443

**Comment by firelightning13** [comment]
oh ok then

**Comment by LegitSoulja** [comment]
Just use play.ogarul.tk or your own
