### ISSUE TITLE
When I open the server where I get to play? by which site

### ISSUE THREAD

**Issue by zKurama** [AJS-development/Ogar-unlimited#847]
When I open the server where I get to play? by which site

**Comment by David1ali12** [comment]
use http://ajs-development.github.io/client/
or http://ogarul.io/
untill fix for play.ogarul.tk

**Comment by DarkZYT** [comment]
play.ogarul.tk it is broken and will be up soon !
or ajs-development.github.io/client/ !

**Comment by Andrews54757** [comment]
it is not broken anymore

**Comment by DarkZYT** [comment]
Ok thanks
