### ISSUE TITLE
Broken Client on 1.7

### ISSUE THREAD

**Issue by mrzack506** [AJS-development/Ogar-unlimited#848]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
none
What version are you on?
1.7
What command did you type if any?
none
You must have a description as well
I updated,  used the old client with the packet value in advConfig set to 0, and it doesn't work, it gives me a blue screen that changes colors when I open up my website.
Here is a screenshot
![capture](https://cloud.githubusercontent.com/assets/19736068/15789695/95b70f4c-299b-11e6-9a35-8733797302ab.JPG)

is there any way I can get the ALL of the client files from play.ogarul.tk or http://ajs-development.github.io/client?

**Comment by Andrews54757** [comment]
[Agarioclient.zip](https://github.com/AJS-development/Ogar-unlimited/files/298278/Agarioclient.zip)
