### ISSUE TITLE
About veteran skins and premium skins !

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#849]
Hey everyone , in the client , only custom skins are workin ! if u want others , do like that : 
1 - Search the skin png in google 
2 - Shorten your url with goo.gl
3 - Add the skin with its url in "customskins.txt" example : " star_ball :http://goo.gl/68RTzQ "
4 - Then go into the game and play with your skin !!
<h1>
Thanks

**Comment by Agarian** [comment]
we know.
