### ISSUE TITLE
New client

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#850]
Hello, Here is the new client: 
[Agarioclient.zip](https://github.com/AJS-development/Ogar-unlimited/files/298283/Agarioclient.zip)

**Comment by mrzack506** [comment]
<3 thank you so much you legend

**Comment by flashinglava** [comment]
How do you use this?

**Comment by Zertag** [comment]
how it works plzz

**Comment by Andrews54757** [comment]
UPDATE: Fixes

[Agarioclient.zip](https://github.com/AJS-development/Ogar-unlimited/files/298383/Agarioclient.zip)

**Comment by Zertag** [comment]
but do we need to launch something or anything else what dowe need to do

**Comment by RasyiidWho** [comment]
can you add minimap plz ._.

**Comment by paulo364gamer** [comment]
where has a tutorial teaching the host ?

**Comment by Andrews54757** [comment]
here: #729

**Comment by sethdm02** [comment]
Wtf what is this 4?
