### ISSUE TITLE
What did i do wrong????

### ISSUE THREAD

**Issue by jayoverclick** [AJS-development/Ogar-unlimited#852]
![download 8](https://cloud.githubusercontent.com/assets/19737130/15791742/2a51ff30-29a7-11e6-9d62-aa38eb418348.png)
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue? ffa

What version are you on? 17.0.1

What command did you type if any? none

You must have a description as well
How did this happen
Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

Can you make minions split by pressing E or R key?
A: NO, as agar.io client doesn't support those keys. Otherwise, you would need to use another client, and that is illegal.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

**Comment by ViinKz** [comment]
go play.ogarul.tk if you'r using ogar unlimited

**Comment by Megabyte918** [comment]
also disable any extensions and try changing packetversion
