### ISSUE TITLE
Error??

### ISSUE THREAD

**Issue by ViinKz** [AJS-development/Ogar-unlimited#853]
[INFO] Loading Config Files...
[INFO] Loading ./settings/advConfig.ini
[INFO] Loading ./settings/config.ini
[INFO] Loading ./settings/override.ini
[INFO] Your unique id is: he0xdRRj0f
[INFO] Loading plugins
[INFO] Starting ConsoleService
                                        _ _       _              _
                                       | (_)     (_)_           | |
  ___   ____  ____  ____    _   _ ____ | |_ ____  _| |_  ____ _ | |
 / _ \ / _  |/ _  |/ ___)  | | | |  _ \| | |    \| |  _)/ _  ) || |
| |_| ( ( | ( ( | | |      | |_| | | | | | | | | | | |_( (/ ( (_| |
 \___/ \_|| |\_||_|_|       \____|_| |_|_|_|_|_|_|_|\___)____)____|
      (_____|
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 17.0.1
[Error] Please make sure you are running Ogar with root privileges.
[INFO] OgarUnlimited terminated with code: 1

Press any key to exit...
help!

**Comment by LegitSoulja** [comment]
Change your server port to something else.

**Comment by ViinKz** [comment]
didn't work

**Comment by ViinKz** [comment]
nevermind,  it works after i reinstall ogar ul.
