### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by paulo364gamer** [AJS-development/Ogar-unlimited#855]
has some way to create a website by ip so for me to connect using the Agarioclient.zip ? like so https://192.168.1.56 , so to myself

**Comment by LegitSoulja** [comment]
@paulo364gamer 
### Steps
- Run command
> plugin install Client

- Download AgarioClient.zip
> Upload content to ./plugins/client/

- Start OgarUnlimited
> Visit http://localhost:8080

If you port forward, use your local ip address.

**Comment by paulo364gamer** [comment]
![image](https://cloud.githubusercontent.com/assets/19374379/15796035/dfc7da62-29cd-11e6-94a2-c0a553fb4121.png)

**Comment by LegitSoulja** [comment]
Make sure you dont upload just a folder to Client, but all the files inside the folder.

You would extracteverything to the client folder with the file index.html in the directory.

**Comment by paulo364gamer** [comment]
@LegitSoulja 
thank you!! work, is to use premium skin? this client
