### ISSUE TITLE
Skins FPS Lag

### ISSUE THREAD

**Issue by SardoYT** [AJS-development/Ogar-unlimited#857]
IDK IF its just me

everytime i turn on skins
Premium and veteran skins

Its always Lagging so crazy

**Comment by TheAngryGrandpa** [comment]
@SardoYT OMFG guys why why i reinstalled this OGAR and i dont have skins no skins no doge no countrys skins WTF

**Comment by Agarian** [comment]
Yeah... so default agar skins have been broken but IDC at the moment.

**Comment by David1ali12** [comment]
lol ofc skins are from custom skins which I added ofc it will lag YEP lag is crazy 
FIX ? simple skins should be added to client not as custom skins.

**Comment by DarkZYT** [comment]
If you want it to be smooth , go to options and active : Smooth Render , No grid !

**Comment by firelightning13** [comment]
Well, tbh it was laggy af. With the skins implemented, the screen starts to lag and delay for seconds
For example, when I tried pausing my server, the client took like 5~10 seconds to freeze everything.
But when I disable some of the option like no skin, grid and smooth render, it doesn't lag anymore(still, it took 1/2~2 seconds to freeze).

**Comment by Guardianeqq** [comment]
Skins without fps lag will be added soon
