### ISSUE TITLE
132 mass minions please

### ISSUE THREAD

**Issue by Zertag** [AJS-development/Ogar-unlimited#859]
in the old client version (ajs-development.github.io/client/?) bots were 132 mass and now they are 10 mass and we stop growing at 650 can it get back ?

**Comment by olivierek6** [comment]
go to config and botsgainmass = true
do spawnmass [bot id] 132

**Comment by Zertag** [comment]
thx

**Comment by Guardianeqq** [comment]
config = playerSpawnMass = 132

**Comment by Megabyte918** [comment]
Use the superminions plugin
