### ISSUE TITLE
How can i addbots with cool letters on their names ?

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#860]
Can someone help me to add minions with cool letters ?

**Comment by Ckicky** [comment]
Is it bots or minions?

**Comment by DarkZYT** [comment]
minions , bots names can be changed with realisticnames.txt !

**Comment by Souffer123** [comment]
how can i channge my configservice 
i use (sublime text 3) for javascripts

**Comment by DarkZYT** [comment]
?

**Comment by David1ali12** [comment]
put names botnames.txt & save it 
then when add minions put `/random ` without tag for names and for skins use `</random> ` in tag
for Example if you put 10 names ` /random` will use 10 names .

**Comment by DarkZYT** [comment]
Oh thanks bro !
