### ISSUE TITLE
Can't connect to the server.

### ISSUE THREAD

**Issue by Xtreme533** [AJS-development/Ogar-unlimited#861]
Hello, I just downloaded the Ogar-unlimited and I can't connect to it.
http://prntscr.com/bc7tvr
Whenever I select play, there's only blank screen.
It actually CONNECTS me to the server, but I can't play.
I'm using the latest version, the gamemode is FFA.
No extensions are used.

**Comment by Xtreme533** [comment]
No errors in the console.
http://prntscr.com/bc7uv8

**Comment by ItzLevvie** [comment]
Use play.ogarul.tk

**Comment by Xtreme533** [comment]
Thank you @ItzLevvie, I didn't know that you need to use the different website.

**Comment by Xtreme533** [comment]
Closed.
