### ISSUE TITLE
You know that agar.io half-revamped merging?

### ISSUE THREAD

**Issue by Ckicky** [AJS-development/Ogar-unlimited#862]
So that means that <10 cells have a chance to merge at the same time, not like that kind of ROUGH AF Merging like that anymore

**Comment by NatsuTheGreat** [comment]
That could happen with the current merge, I split sixten when playing solo and with my server merging you have a small chance of that happening, should be the same with you.

**Comment by Ckicky** [comment]
But the update here has only like 2% chance but that agar.io update has 10% chance now

**Comment by NatsuTheGreat** [comment]
Oh, try talking to andrew about it.

**Comment by ErikParacelsus** [comment]
It's on PlayerCell.js
