### ISSUE TITLE
Help me to make server on Heroku :D

### ISSUE THREAD

**Issue by RasyiidWho** [AJS-development/Ogar-unlimited#864]
@Andrews54757 Can you make tutorial how to setup Ogar-unlimited on heroku? like your demo server :+1:

**Comment by raphyjb** [comment]
He should do a tutorial on how to put it on VPS centos 7x64 or ubundle (<--Not sure how its called) 
:D THAT COULD BE AMAZING!!!!!!!!!!!!!!!!!!! ( i got vps that i bought i need to run my server on there but i dont know the commands of it!)

**Comment by ItzLevvie** [comment]
"ubundle" You mean Ubuntu?

**Comment by raphyjb** [comment]
yup! lol

**Comment by Andrews54757** [comment]
@RasyiidWho no
