### ISSUE TITLE
Skins!!!

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#865]
Is it possible to have the new skins that agario had for november 13 and the other one they had 3 days ago! :D

**Comment by lotfis** [comment]
yeah that would be so cooool!!!!

**Comment by Agarian** [comment]
Where can we find all the image links for EVERY SINGLE premium skin?

**Comment by raphyjb** [comment]
good question
!!!!!!!!!!

**Comment by David1ali12** [comment]
I added all to my client :smirk:

**Comment by lotfis** [comment]
links fore the images pls

**Comment by Agarian** [comment]
@David1ali12 Do you have links to ALL premium skins? Specifically new ones?

**Comment by LegitSoulja** [comment]
Not many agar.io skins will be added to ogarul due to there skin imagery copyright. Therefor, most of the skins are custom made, or obtained elsewhere. Not from agar.io, nor used agar.io skins.

Main reason why Andrew closed this. We have to follow guidelines.

**Comment by SharkFinPro** [comment]
just open up the network tab on dev tools while loading up agario
