### ISSUE TITLE
Cant play

### ISSUE THREAD

**Issue by AgarioIsBest1602** [AJS-development/Ogar-unlimited#867]
I wanted to play with 17.0.0 or 17.0.1 and i got on both this:
![agar io - google chrome 6_4_2016 5_12_51 pm](https://cloud.githubusercontent.com/assets/19749230/15800393/c647746c-2a77-11e6-94b1-34a6f927ecb3.png)

Do you know whats wrong?

**Comment by NovaAgars** [comment]
isnt work with bagar.io or raga.pw
try to play in play.ogarul.tk

**Comment by AgarioIsBest1602** [comment]
Thank you! it works!
