### ISSUE TITLE
My Issue Got Deleted

### ISSUE THREAD

**Issue by TheAngryGrandpa** [AJS-development/Ogar-unlimited#868]
Someone Deleted My Issue i updated Ogar and all skins doesnt work Doge countrys and everything Doesnt work

**Comment by raphyjb** [comment]
Bilbo u need install the ogar unlimited and the dependencies

**Comment by TheAngryGrandpa** [comment]
@raphyjb  I DID and nothing this ogar is nothing without skins -_- And andrew i thought your helping everyone and u didnt reply or other devs peoples i need help WTF i installed DEPENDIZ and everything and NOTHING !

**Comment by Andrews54757** [comment]
Add the skins in customkins.txt

**Comment by Andrews54757** [comment]
and use play.ogarul.tk

**Comment by TheAngryGrandpa** [comment]
@Andrews54757 i added alot of skins and nothing fix the ogar
