### ISSUE TITLE
For the skins...

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#869]
Ok so i got a problem can we make the skins not case sensative?? cuz its so complicated for some poeple in my server... they doing <Apple> to get the apple and he says it doesnt work .. then i have to say its <apple> no caps.. its anoying

**Comment by Agarian** [comment]
Actually this could be a config

**Comment by NatsuTheGreat** [comment]
Yeah you can make them not case sensitive. I am pretty sure it;s not the fact that it doesn't work because of the case sensitivity.

**Comment by NatsuTheGreat** [comment]
@Agarian I don't see why making a config for this would be useful xD

**Comment by Andrews54757** [comment]
If the people on servers are not able to figure out skins, they get no skins.

**Comment by raphyjb** [comment]
ok! lel

**Comment by Agarian** [comment]
I mean for skins being case sensitive
