### ISSUE TITLE
Graphic bug

### ISSUE THREAD

**Issue by Nic0x** [AJS-development/Ogar-unlimited#870]
http://i.imgur.com/Bhu5Sjh.gifv
I've got some graphics bugs, I'm just warning you

**Comment by raphyjb** [comment]
got same error sometimes

**Comment by LegitSoulja** [comment]
Dude I thought this was only me!. When more cells are in a frame it glitches out. Players invisible, leaderboard spasms, Yea...

**Comment by Andrews54757** [comment]
dont know why it does this

**Comment by TheAngryGrandpa** [comment]
EVERYONE HAS A FUCKING SKIN AND MINE ARE NOT WORKING FIX THIS OGAR OR GIVE ME A STEP AND STOP BANNING PEOPLE BECAUSE YOU CANT FIX THEIR ISSUES

**Comment by Souffer123** [comment]
me to

**Comment by Andrews54757** [comment]
probably something computer-sided not agreeing with the client

**Comment by Souffer123** [comment]
okay but how do i change the configservice?

**Comment by Souffer123** [comment]
how do i make screenshot?

**Comment by Souffer123** [comment]
**???**

**Comment by ItzLevvie** [comment]
You could use the print scrn button on the keyboard or use a program.

**Comment by Souffer123** [comment]
where is that ? button

**Comment by Nic0x** [comment]
@Souffer123 
![xxltekwgj77gxfrptljc](https://cloud.githubusercontent.com/assets/19686168/15801621/702396b4-2a9b-11e6-897e-d60ff927e43f.jpg)

**Comment by Souffer123** [comment]
@Nic0x  i failxD

**Comment by Souffer123** [comment]
how do i change the  configservice ????

**Comment by Agarian** [comment]
LOL sometimes the skin flickering prettu much says "`seizure time!`"

**Comment by firelightning13** [comment]
xD

**Comment by PrinceDark9243** [comment]
me too i got this bug!

**Comment by Ckicky** [comment]
I just got seizured by the skins...
