### ISSUE TITLE
MINION PROBLEM!

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#871]
What game mode were you in when you had the issue?
Default
What version are you on?
17.0.0.1
What command did you type if any?
no
You must have a description as well
Well the minions are acting wierd.! So when i use GiveMeMinionsToo on my server is says 3 poeple get 10 bots, for 4 minutes, 4 minutes later i see theres 60 bots in server, i dont get it, some of those bots even become ghosts and they cant feed and cant split they pass thro virusses and they cant eat no one... Hm help!
Also can we do on GiveMeMinionsToo a way we could control mass of those minions in the plugin. and also putting random names on it..

**Comment by Agarian** [comment]
I also noticed the `minionstart` plugin disallows a player to spawn

**Comment by Andrews54757** [comment]
@Agarian Fixed

**Comment by Andrews54757** [comment]
@raphyjb I will see

**Comment by raphyjb** [comment]
Awsome thanks!

**Comment by Andrews54757** [comment]
@raphyjb I fixed it, but it is the problem of ogarul. so you have to update ogarul

**Comment by raphyjb** [comment]
ok will do sir! tyvm!!!!!!! Help is highly appriciated here :D
