### ISSUE TITLE
SKINS SKINS SKINS 

### ISSUE THREAD

**Issue by TheAngryGrandpa** [AJS-development/Ogar-unlimited#874]
EVERYONE HAS A FUCKING SKIN AND MINE ARE NOT WORKING FIX THIS OGAR OR GIVE ME A STEP AND STOP BANNING PEOPLE BECAUSE YOU CANT FIX THEIR ISSUES I ADDED SKIN AT CUSTOMSKINS.TXT I DID DOGE NO SKIN I DID FRANCE NO SKIN WTF IS THIS

**Comment by Andrews54757** [comment]
Everyone, should I ban this guy? He is really annoying. it is such as easy issue, but mabye he doesnt have the mental capacity to work it out. @TheAngryGrandpa Go on the demo server and type in `<spy>` as your username. It works.

**Comment by TheAngryGrandpa** [comment]
@Andrews54757 
![wow](https://cloud.githubusercontent.com/assets/19652548/15801445/2dbca154-2a95-11e6-9247-76375fd71c80.PNG)
Wow working so good -_- i installed depencies btw

**Comment by Agarian** [comment]
Dude you are asking for a ban. It works perfectly fine! You must be doing something wrong.
- use http://play.ogarul.tk
- have the latest version of ogarUL
- have node v5.9.0

**Comment by TheAngryGrandpa** [comment]
@Agarian i have alll of that and nothing asking for a ban while NOTHING Works

**Comment by Megabyte918** [comment]
make sure you have the latest client, and default skins dont work only the premium ones do

**Comment by firelightning13** [comment]
Doge, other country skins is broken. But premium skin still works..

**Comment by David1ali12** [comment]
`[goo.gl/2oYZJI]` use as name
