### ISSUE TITLE
TypeError: "Callback" argument must be a function

### ISSUE THREAD

**Issue by sethdm02** [AJS-development/Ogar-unlimited#875]
Well Uhh Im having A Problem Wth ogar unlimited I Guess my pc hates me but , the problem is thiat its preventing me to play on anything image says it all
![crap](https://cloud.githubusercontent.com/assets/18504983/15801519/5a61bef2-2a5d-11e6-900f-7e746ce184f3.PNG) and ive tried installing different nodejs ive tried virtual machines other os's and different version I just want To play it :( sorry for my bad writing probbaly but what ever

**Comment by Andrews54757** [comment]
use node 5.9.0. the latest node doesnt work

**Comment by sethdm02** [comment]
Were do you download it m8 :p

**Comment by sethdm02** [comment]
nvm

**Comment by sethdm02** [comment]
32 or 64

**Comment by ItzLevvie** [comment]
if you have less than 2GB of ram then choose 32, or if you have more than 4GB of ram then choose 64

**Comment by sethdm02** [comment]
no im talking for compatibility reasons :/ whatever

**Comment by sethdm02** [comment]
I oWE YOU A BIG THANX Andrews54757
