### ISSUE TITLE
Is there a way to change minions mass spawn

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#876]
Wanted to know is there a way to change minions mass spawn to different then players mass spawn.

**Comment by raphyjb** [comment]
Andrew i still have same problem says 60 bots when its suppose to stay at 45 (15 bots for 3 users) I really dont understand anything rn

**Comment by Agarian** [comment]
you could have the `SuperMinions` plugin
- it allows you to make minion spawn mass separate from player start mass
- it allows you to change the minion movement speed
The command is in this format:

    superminion [playerID] [amount] [minionname] [spawnmass] [speed]

You can leave the `speed` area blank if you want the minions to use default speed.

**Comment by raphyjb** [comment]
i need it to work with GiveMeMinionsToo plugin..

**Comment by raphyjb** [comment]
Why pellets make server lag? df

**Comment by Souffer123** [comment]
how do i change my spwanmass ??

**Comment by raphyjb** [comment]
go on console do playerlist
look wat ur ID is then do spawnmass ID MASSUWANNASPAWN

**Comment by Souffer123** [comment]
I cant find that !

**Comment by Souffer123** [comment]
@raphyjb  thnx

**Comment by raphyjb** [comment]
np

**Comment by Souffer123** [comment]
@raphyjb do you no how to chang the food in the map ?

**Comment by raphyjb** [comment]
yah go on ogar-unlimited folder then go src go settings go to config.ni then u will find it (Download notepad++ to open that Config.ini)

**Comment by Souffer123** [comment]
@raphyjb is subliem text 3 good to ?

**Comment by Souffer123** [comment]
@raphyjb thank you so much

**Comment by lotfis** [comment]
@Agarian where can I find the SuperMinions plugin? pls

**Comment by Zertag** [comment]
how to get the superminions

**Comment by Andrews54757** [comment]
to get the plugin, do `plugin install SuperMinions`
