### ISSUE TITLE
Need This to be explained precisely how to be set up plz :/

### ISSUE THREAD

**Issue by sethdm02** [AJS-development/Ogar-unlimited#877]
Im trying to start my client #850 I got it set up and yes i saw the other one but i still don think it's explained very clearly i get the same error as he does so if you could explain to me EXACTLY How to set it Up i would be very greatfull

**Comment by Megabyte918** [comment]
what error?

**Comment by Andrews54757** [comment]
@sethdm02 If you cant figure it out. Use play.ogarul.tk instead. You need to have some knowledge of computers to set up

**Comment by Megabyte918** [comment]
YO ANDREWS I NEED YO HELP
