### ISSUE TITLE
skins

### ISSUE THREAD

**Issue by devin1155** [AJS-development/Ogar-unlimited#879]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
ffa
What version are you on?
latest 
17.0.1
What command did you type if any?
minion 1 1 xD mass 1 15000
You must have a description as well
idk?
I can't use skins... i looked at other posts and people say it works fine meanwhile i've spent like 15 minutes trying to figure this out. Its kind of annoying :/ I put it in the corner brackets, <kraken> just like that, does not work at all. Resolve?

**Comment by Souffer123** [comment]
use <skinname>
for example <kraken> or <fly>

**Comment by Souffer123** [comment]
use <skinname> <kraken? <fly> or something else

**Comment by Souffer123** [comment]
<>

**Comment by paulo364gamer** [comment]
my perfect work
![image](https://cloud.githubusercontent.com/assets/19374379/15802357/2b563412-2a85-11e6-9ba6-12cd4859b094.png)
[customskins.txt](https://github.com/AJS-development/Ogar-unlimited/files/299055/customskins.txt)
change your custom skin for my

**Comment by devin1155** [comment]
wait what?

**Comment by paulo364gamer** [comment]
replace your customskin.txt by that I passed you, is in the src folder

**Comment by devin1155** [comment]
ok

**Comment by devin1155** [comment]
wait
why is the borders different color than skin

**Comment by paulo364gamer** [comment]
do not know

**Comment by Agarian** [comment]
The cell border color changing according to skins feature isn't added yet

**Comment by devin1155** [comment]
Do you know when it would be added?

**Comment by TheAngryGrandpa** [comment]
YEAH MY SKINS DOESNT WORK TOO

**Comment by Agarian** [comment]
@Andrews54757 a bug with rainbow command: the rainbow effect only sticks to one cell

**Comment by Megabyte918** [comment]
does anyone even use the rainbow command?

**Comment by Agarian** [comment]
i do

**Comment by Megabyte918** [comment]
hey your on! can i ask your help for something real quick?

**Comment by firelightning13** [comment]
i like rainbows (no joke)

**Comment by Souffer123** [comment]
me to

**Comment by LegitSoulja** [comment]
Rainbows was like a thing I found before minions. Isn't that weird? I though rainbow was pretty cool.
