### ISSUE TITLE
*******************MINION PROBLEM*******************

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#880]
OK BOTS ARE NOW WORST THEN EVER ! I PUT 3 BOTS USER THAT CONTROLS 15 BOTS.. OK.. LISTEN UP NOW I WAS GONE FOR 2 HOURS THE NUMBER CAME UP TO 135, SERVER WAS LAGGY ASF ! HOW TO FIX PLEASE NEED HELP!!!!!! USING THE PLUGIN GIVEMEMINIONSTOO I THINK THATS THE PROBLEM... NOT SURE BUT IF U WANNA CHECK IT OUT ILL BE ON MY SERVER play.ogarul.tk/?ip=24.138.83.25:443

**Comment by Andrews54757** [comment]
I will edit the plugin

**Comment by Andrews54757** [comment]
Do `plugin update`

**Comment by raphyjb** [comment]
Thank u andrew <3 ur the best

**Comment by raphyjb** [comment]
Is there a way to donate you or to help u out?

**Comment by raphyjb** [comment]
Or to help you out?

**Comment by Megabyte918** [comment]
well that de-escalated quickly

**Comment by raphyjb** [comment]
yup :P
