### ISSUE TITLE
PLAY WITH FRIENDS

### ISSUE THREAD

**Issue by Zertag** [AJS-development/Ogar-unlimited#882]
Can we plauy with friends in the serve r? if yes expalint to me plz

**Comment by Souffer123** [comment]
https://c9.io/

**Comment by Zertag** [comment]
? what do i need to

**Comment by ItzLevvie** [comment]
Don't host servers on C9. Just buy a VPS.

**Comment by sukass** [comment]
just portforward your ogar port

**Comment by Zertag** [comment]
what ?

**Comment by Zertag** [comment]
sry im noob at this xD

**Comment by bangana** [comment]
i did portforard on 8081 didn't work ...

**Comment by firelightning13** [comment]
Just google it
