### ISSUE TITLE
Cant make my friends join with hamachi !

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#884]
Please , help me , i cant make my friends join my server , but my friends can btw , please help me !!!
- I use hamachi
- I use play.ogarul.tk
Thanks !

**Comment by Zertag** [comment]
how do they do ?

**Comment by bangana** [comment]
me 2 :'(

**Comment by Andrews54757** [comment]
hamachi is stupid. It never works. Dont use it

**Comment by Megabyte918** [comment]
Hamachi just got ROASTED

**Comment by aymanio** [comment]
what i use ?

**Comment by aymanio** [comment]
my fr(iends cant join with hamachi too

**Comment by aymanio** [comment]
plz talk andrews

**Comment by aymanio** [comment]
# plz

**Comment by aymanio** [comment]
1. 
qqq

**Comment by aymanio** [comment]
_plz bro_

**Comment by Agarian** [comment]
# JUST STOP, HE'S NOT GOING TO RESPOND!

**Comment by aymanio** [comment]
?

**Comment by Agarian** [comment]
Just read my comment...

**Comment by Andrews54757** [comment]
Port forward

**Comment by Agarian** [comment]
Well i guess i've been wrong.
