### ISSUE TITLE
Look at this crap

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#885]
https://youtu.be/YN5lpbte3wg
In this video, the youtuber MAU claims to have free minions, but does not even aknowledge that the server is not his! He also offers an external download link. He even goes as far as to take credit for it by naming the file from his download link "MAU SERVER"!

**Comment by Zertag** [comment]
i know...

**Comment by Zertag** [comment]
i will upload o avideo about the server with 
-the official dl link
-mentionning in the description and start of the video "SERVER MADE BY THE AJS DEVELOPMENT TEAM"
_the link of this forum

Can i have permission to do it ?

**Comment by Zertag** [comment]
anyways mau is just a piece of shit he know that its ur serv but he wants fool people

**Comment by Andrews54757** [comment]
I warned him. I said if he doesnt change the link, I will defame his channel

**Comment by bangana** [comment]
i flagged em x)

**Comment by Andrews54757** [comment]
these things make me want to pull the switch on this project

**Comment by raphyjb** [comment]
:( dont do that!!!

**Comment by frank1iu** [comment]
@Andrews54757 Hello. Have you filed a copyright claim on this youtuber's channel? If not yet, please do so at your first convenience. Check out [here](https://support.google.com/youtube/answer/2807622?hl=en), or use [the form](https://www.youtube.com/copyright_complaint_form) directly.

**Comment by frank1iu** [comment]
@Zertag Hello. Yes, you have permission. This software is licensed under [the Apache Public License 2.0](http://www.apache.org/licenses/LICENSE-2.0).

**Comment by Zertag** [comment]
:D thanks

**Comment by NatsuTheGreat** [comment]
@Andrews54757 Just defame his channel, he is more annoying than ffa teamers.

**Comment by Zertag** [comment]
xD

**Comment by LegitSoulja** [comment]
I file some reports against this.

**Comment by LegitSoulja** [comment]
Submit here https://www.youtube.com/copyright_complaint_form

**Comment by Andrews54757** [comment]
No, dont file charges. I dont do that. Legalities are stupid. il just defame his channel

**Comment by Agarian** [comment]
lol defame?

**Comment by LegitSoulja** [comment]
@Agarian how old are you?

**Comment by LegitSoulja** [comment]
@Andrews54757 No, its not a charge, its a copyright. Either they can fix the links, or the video gets removed. We can still defame them for not providing ajs trademark, and him trying to claim it as his when its not.

**Comment by Andrews54757** [comment]
@LegitSoulja Dont, I have my reasons.

**Comment by Andrews54757** [comment]
also, the licenese belongs to devin ryan, not me because apparently, this is a derivative work of ogar

**Comment by Agarian** [comment]
It kinda is

**Comment by Andrews54757** [comment]
yea, but considering all the work we put in...

**Comment by frank1iu** [comment]
@Andrews54757 Hello. As far as I know, you are the copyright holder instead of Devin. 
@LegitSoulja Hello. Looking at the graphs of this repository, you contributed to this repository once. That means **you** can [submit a copyright claim](https://www.youtube.com/copyright_complaint_form) at YouTube as the co-author of this software.

**Comment by Andrews54757** [comment]
@frank1iu No, your wrong, he has it, he dmcad us months ago

**Comment by NatsuTheGreat** [comment]
:$

**Comment by LegitSoulja** [comment]
So bascially, we can't do nothing about ajs/ogar-unlimited you are saying? Even though, this was built from original ogar, but we re-coded.

**Comment by Andrews54757** [comment]
Also, he put the license in, he didnt edit the files, so it is legal for him as well

**Comment by Andrews54757** [comment]
And yes, thats how legalities work, even though the code diff is probably over 2500, since it was built from the original and progressed to this, it still belongs to devin.

**Comment by Andrews54757** [comment]
Im not so sure though, we need someone who is an expert on the law to figure it out for us

**Comment by frank1iu** [comment]
@Andrews54757 Hello. Try posting a thread in [Law Stack Exchange](https://law.stackexchange.com/).

**Comment by LegitSoulja** [comment]
@Andrews54757 I could talk to my lawyer or attorney for answers if needed.

**Comment by Megabyte918** [comment]
ica gaming did the same thing...

**Comment by NatsuTheGreat** [comment]
This is not okay...

https://www.youtube.com/watch?v=3r8QOsPCDcg

**Comment by LegitSoulja** [comment]
@NatsuTheGreat This dude really said the bots/minions is a hack, and he will release the download link after he gets 7.5k subs...

**Comment by NatsuTheGreat** [comment]
Yeah that's what I am talking about. He is using this as a bribe. *Hiding the fact it's ajs* I hate this guy,

**Comment by LegitSoulja** [comment]
@AJS-development/ogar-unlimited-devs 

Ok. I talked to Mau. He changed the links in his descriptions, and fixed a few comments. I told him as long as he gave credit/trademark towards AJS its fine. 

Looks like he had an uploaded version of Ogar-unlimited because he had his own custom settings.

**Comment by Megabyte918** [comment]
Should we leave commants on that vid too? or is it too late for that

**Comment by Agarian** [comment]
Leave comments anyway.
