### ISSUE TITLE
150 poeple in my server..

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#887]
OK, huge problem, i got 150 poeple in my server.. 95% aint playing. and they are on DEAD OR NOT PLAYING, Is there a way to get they kicked when they are in that mode for more then 3minutes? cuz poeple are complaining they dont get bots.. I know why they dont get the bots.. thats obviously because they connect to poeple that aint playin.. if u wanna go on my server http://play.ogarul.tk/?ip=24.138.83.25:443   (Please tell me theres a solve to this one)
Also, Andrew is there a way to donate you?

**Comment by Souffer123** [comment]
use ws://127.0.0.1:443

**Comment by Souffer123** [comment]
or you need to change your serverMaxConnections

**Comment by raphyjb** [comment]
dude max connection is at 2

**Comment by Souffer123** [comment]
@raphyjb make a printscreen of your config

**Comment by raphyjb** [comment]
wats the site for that

**Comment by raphyjb** [comment]
cant.. fucking google chrome is killing me.. crashing everytime i take a screen shoot... and trying to get link to it!

**Comment by raphyjb** [comment]
i cant copy paste tho!

**Comment by raphyjb** [comment]
serverScrambleCoords = 0
serverMaxConnectionsPerIp = 2
autoban = 0
autobanrecord = 0
verify = 0
vchance = 5
vtime = 25
mousefilter = 1
mbchance = 5
serverScrambleMinimaps = 0

**Comment by raphyjb** [comment]
wat else u need?

**Comment by David1ali12** [comment]
Change disconnect time , 
`/src/settings/config.inin`

**Comment by raphyjb** [comment]
Thanks u very much, im so dumb!

**Comment by David1ali12** [comment]
close
