### ISSUE TITLE
Spawn bug

### ISSUE THREAD

**Issue by Hazani** [AJS-development/Ogar-unlimited#888]
When im on 1.7.0.0 I change PlayerStartMass to 132 and i opened server i connected to my server with ogarul.io and i started with 10 mass? A fix for this?

**Comment by raphyjb** [comment]
do reload on console, or do playerlist then check ur id and do 
spawnmass ID mass

**Comment by Hazani** [comment]
nope dont worked

**Comment by Hazani** [comment]
I want all players to spawn with 132 mass.

**Comment by raphyjb** [comment]
Add me on skype: raphy.jb

**Comment by Hazani** [comment]
An program or anything can effect it

**Comment by Souffer123** [comment]
@Hazani change your config in the settings

**Comment by Hazani** [comment]
I already did.
But doesnt work

**Comment by Souffer123** [comment]
do you use notepadd++?

**Comment by Hazani** [comment]
Like i change it but; It doesnt spawn 132 Mass.I change to 132 and I spawn with 10 mass.

**Comment by Hazani** [comment]
Yeah.

**Comment by Hazani** [comment]
But just That doesnt work others are fine.

**Comment by Hazani** [comment]
Gonna re download

**Comment by Souffer123** [comment]
yes try thath

**Comment by bangana** [comment]
bruh how did ya'all connect trought hamachi i caaaaaaaaaaaaaaaaaaaaaaaan't ;-;

**Comment by Hazani** [comment]
I just tried a 28 times. xD

**Comment by Hazani** [comment]
Im playing solo so Im not using it xD.

**Comment by Souffer123** [comment]
xD

**Comment by Hazani** [comment]
plz work dis time

**Comment by Hazani** [comment]
I played with codes little bit xD It worked

**Comment by Hazani** [comment]
Little fps drops but doesnt matter for playing with codes
