### ISSUE TITLE
Multiverse servers dont stay!

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#889]
title pretty much says it, buy when i do the multiverse create [name] [port] [gamemode] [title] command it works but if i shut the server off and start it again, the multiverse created server is not there!

**Comment by Andrews54757** [comment]
exactly, multiverse serverse are erased if the master is stopped

**Comment by CalvinDKHD** [comment]
then can i change the server region names? and how many here is etc?
