### ISSUE TITLE
I can't use it

### ISSUE THREAD

**Issue by JoeLiu333** [AJS-development/Ogar-unlimited#89]
there is an error calls cannot find 'request'

**Comment by Andrews54757** [comment]
You have to do npm install not npm install ws

**Comment by JoeLiu333** [comment]
I did that but now it just be cannot find module 'extend'

**Comment by JoeLiu333** [comment]
_ _       _              _
                                       | (_)     (_)_           | |
  ___   ____  ____  ____    _   _ ____ | |_ ____  _| |_  ____ _ | |
 / _ \ / _  |/ _  |/ ___)  | | | |  _ \| | |    \| |  _)/ _  ) || |
| |_| ( ( | ( ( | | |      | |_| | | | | | | | | | | |_( (/ ( (_| |
 \___/ \_|| |\_||_|_|       \____|_| |_|_|_|_|_|_|_|\___)____)____|
      (_____|
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
module.js:340
    throw err;
    ^

Error: Cannot find module 'extend'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\JIE LIU\Desktop\Tr\Ogar+\Ogar-unlimited-master(5)\Ogar-unlimited-master\node_modules\request\index.js:17:29)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)

**Comment by ItzLevvie** [comment]
@JoeLiu333 ```npm install extend```.

**Comment by JoeLiu333** [comment]
C:\Users\JIE LIU>npm install entend
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "entend"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/entend
npm ERR! 404
npm ERR! 404 'entend' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\JIE LIU\npm-debug.log

**Comment by Agarian** [comment]
you typed entend instead of extend xD

**Comment by Andrews54757** [comment]
It should work with just npm install

**Comment by Andrews54757** [comment]
first you have to cd into the folder src then you have to do npm install,

**Comment by Andrews54757** [comment]
Its says plainly in the installation guide

**Comment by JoeLiu333** [comment]
thanks it is work now,but how can i use skin?

**Comment by Agarian** [comment]
< skin name >
example:

    <kraken>
