### ISSUE TITLE
Can i make multiverse servers stay?

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#890]
Title says it, sorry i am used to cigar. But i think ogar ul is better :P

**Comment by LegitSoulja** [comment]
No, it doesn't exist yet but could.

**Comment by Andrews54757** [comment]
@CalvinDKHD Yes. On multiverse.js, edit the init function. Add this line `this.create([servername], false, [port], [gamemode] , [title]);`
