### ISSUE TITLE
Servers are different?

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#891]
hey look at this guys - https://gyazo.com/11a3e3fb9e5c735c14f55e8a5220480c
For me its just Main and for him FFA experimental etc.

**Comment by Ckicky** [comment]
WTF Agarextreme?

**Comment by Ckicky** [comment]
Is he using [ajs-development.github.io/client/](url)?

**Comment by Andrews54757** [comment]
Use play.ogarul.tk
