### ISSUE TITLE
(LEGITPANDA)Statistics.. Red bar sayin its not connecting or something

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#892]
Not complicated, just statistic not working right idk wat i need to change for it to work, did plugin update Statistics and it doesnt show it on the site . wdf em i doing wrong please help LEGITPANDA!

**Comment by LegitSoulja** [comment]
Read what I said on the new ogarul statistics issue. And please stop making unecassary issues or you will get banned
