### ISSUE TITLE
On site can we change Names max lengh..

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#893]
Change names max lengh on the site (I changed config)... cuz poeple cant write on my server skin names like <SpaceHunter> Then there name :D thanks!
Also make a place where poeple can chose there skin from my customskins.txt :/

**Comment by Souffer123** [comment]
@raphyjb  are you netherlands?

**Comment by raphyjb** [comment]
Nop!

**Comment by Souffer123** [comment]
you are talking like a netherlander

**Comment by Nic0x** [comment]
Open google chrome, mozilla or others browsers console, and type `document.getElementById('nick').value = "<skin>your_name";`

**Comment by raphyjb** [comment]
I mean the site not to do it myself, i can easy do it myself!

**Comment by LegitSoulja** [comment]
@raphyjb I never understood anything you say nor be trying to do.

**Comment by Andrews54757** [comment]
@raphyjb I am getting tired of your useless issues. You can search it up on google. You must have some knowledge of computers to do it. If not, too bad, we dont care.

**Comment by Andrews54757** [comment]
This is the problem for making a game software, People with no knowledge try to make it and make false issue reports just because they cant figure it out

**Comment by raphyjb** [comment]
then tell me how to put it so poeple can write more then 15 letters on the nick bar.. (sure if u got google chrome, i can just change it...) but i mean i wanna have the nick bar having more then 15

**Comment by Andrews54757** [comment]
@raphyjb Become a programmer

**Comment by Megabyte918** [comment]
@Andrews54757 i would also like to know this

**Comment by ItzLevvie** [comment]
You can change it in index.html

**Comment by Andrews54757** [comment]
This wouldnt matter anyway because I am adding a new feature called clientpacket

**Comment by raphyjb** [comment]
Id love to be a programmer! Andrew wanna help me ?!😂

2016-06-06 14:13 GMT-04:00 Andrew54757 <notifications@github.com>:

**Comment by Andrews54757** [comment]
I added the new feature. You can set the max amount in clientconfig.ini

**Comment by Agarian** [comment]
NICE!
