### ISSUE TITLE
*****DDOS ISSUE *****

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#894]
Ok, im getting tired of poeple ddos my router ... Anoying asf any idea`s on how to block that from happening..

**Comment by sethdm02** [comment]
What Os?

**Comment by raphyjb** [comment]
?

**Comment by sethdm02** [comment]
Opertaing Systeam windows 10 , 8 ,7

**Comment by sethdm02** [comment]
my god my grmmar

**Comment by raphyjb** [comment]
10

**Comment by sethdm02** [comment]
ok

**Comment by raphyjb** [comment]
another ddos, for 7 th today

**Comment by sethdm02** [comment]
IDK

**Comment by sethdm02** [comment]
it may be a router problem

**Comment by sethdm02** [comment]
or a modem problem is it an all in one?

**Comment by raphyjb** [comment]
LoL I SAID I GOT DDOS DUDE

**Comment by LegitSoulja** [comment]
@sethdm02 do you know anything about denial? Clearly I don't think so.

**Comment by raphyjb** [comment]
XD LOL TRUE**

**Comment by LegitSoulja** [comment]
@raphyjb there's really no way to prevent Ddos, unless you use some type of DNS that helps you. 

Check out cloudflare, or blazin.io. Anything that you can use to provide you security.

**Comment by LegitSoulja** [comment]
- [BlazinFast](https://blazingfast.io/)
- [CloudFlare](https://cloudflare.com)

**Comment by raphyjb** [comment]
k

**Comment by sethdm02** [comment]
it could be a router modem issue not a ddos attack duh

**Comment by raphyjb** [comment]
wdf u still coming back to say its modern issue? U mental my router worth 450$ and its anti ddos.
Dont think thats an issue, 2nd i see the ip of the dude who ddos me.. DDOS BACK , everytime his ip is online is auto ddos him :D dont mess with meh <3 (Worst part he didnt have a vps)

**Comment by LegitSoulja** [comment]
@raphyjb a modem can't have a anti-ddos. Your router mainly handles the packages. If you had an anti-ddos, or router then you would not have no problems. 

Most routers can be flooded, and there's nothing you can really do unless your router is smart to determine those packages are fake and should be dropped instantly.

BTW, if you don't know nothing about ddos how did you get the attacker IP address? And an auto ddos is no such thing. You could have the packages be sent right back to him but why even waste time doing so why you can just drop them? Renew your dns, or get a better router that can handle, or get some security on your services.
