### ISSUE TITLE
Lag source skins ect & skin bug, fix for devs

### ISSUE THREAD

**Issue by David1ali12** [AJS-development/Ogar-unlimited#896]
After stability Update everything works much better , but I have notice a big lag source the problem is not With Server Its with Client grid & custom skins& cell border are Source of lag or delay 
Before removing 
```
Wifi - ping= 6mb ` its made a big lag and delay
 hosted server 1200ms sometimes up 2500ms `when using all skins on minions

```
After removing 
```
Wifi-ping=1mb all skins used even for minions 
tested 500 bots 0 lag with all skins 

sever ping 130-150 ms 
```
hosted on h9
notes: 
1- skins better be 512px*512px
2- skins should added to client not from server 1 custom skin dont effect but all effects 
3- Grid&cell borders make a lot of lag.
4- skins bug it never happened with me again after I did the the updates for client

**Comment by Agarian** [comment]
nice!

**Comment by Agarian** [comment]
I added some of your newer skins

**Comment by David1ali12** [comment]
custom skins = lag  it will be added to play.ogarul.tk you dont have to use custom skins

**Comment by raphyjb** [comment]
david u got new skins? like blob chupacabra or Chillipeper? if not contact me on skype i got link for all of em

**Comment by Andrews54757** [comment]
Fine, @David1ali12 Your website could be the official skins site. I will update the clients shortly...

**Comment by Andrews54757** [comment]
its changed

**Comment by Agarian** [comment]
Wait, so now custom skins will not work?

**Comment by Agarian** [comment]
Fuck me

**Comment by LegitSoulja** [comment]
@Agarian custom skins will work, but the default skins are fixed.

**Comment by David1ali12** [comment]
I got so much msg says server blazing fast after skins update :smiling_imp:  finally I could do something for ogarul :smile:
