### ISSUE TITLE
LulzyOgar - my version of Ogar with custom client

### ISSUE THREAD

**Issue by lulzyyy** [AJS-development/Ogar-unlimited#897]
A fully functional open source c0nsume.me server implementation, written in Node.js. LulzyOgar is designed to be used with the c0nsume.me client. If you find any issues, tell me. Btw. code needs to be cleaned up because I edited other version of Ogar. Default port is 600.

To connect to your server, type in browser http://c0nsume.me/private.php?ip=127.0.0.1:600
Made-up client, a few new features (turbo split, full playerlist with countries, ping, auto server restart, uptime, etc)
https://github.com/lulzyyy/lulzyOgar

CHECK IT OUT :)

**Comment by Andrews54757** [comment]
I like play.ogarul.tk better

**Comment by Megabyte918** [comment]
rekt

**Comment by lulzyyy** [comment]
;(

**Comment by ErikParacelsus** [comment]
rip lulzyy

**Comment by lulzyyy** [comment]
xD

**Comment by ErikParacelsus** [comment]
ik

**Comment by Andrews54757** [comment]
really annoying notifications

**Comment by Megabyte918** [comment]
ikr

**Comment by NatsuTheGreat** [comment]
^^ Same here.

**Comment by Andrews54757** [comment]
So do what I do, disable email notifications

**Comment by NatsuTheGreat** [comment]
I never check my gmail anyways xD I just get spammed in my github notifications.

**Comment by Agarian** [comment]
Go to https://github.com/settings/notifications
You'll see `participating` and `watching`.
![screenshot_2016-06-06-22-46-56](https://cloud.githubusercontent.com/assets/15255724/15844479/a848b1a2-2c38-11e6-99a1-478fe2555e89.png)
Uncheck `Emails` for both and boom, no more notifications via email inbox!

**Comment by Andrews54757** [comment]
I already did that ages ago
