### ISSUE TITLE
http://prntscr.com/bcsfki

### ISSUE THREAD

**Issue by Jassim11** [AJS-development/Ogar-unlimited#900]
http://prntscr.com/bcsfki

**Comment by David1ali12** [comment]
use play.ogarul.tk

**Comment by Agarian** [comment]
use http://play.ogarul.tk

**Comment by Jassim11** [comment]
i want to use bots i cant use bots on http://play.ogarul.tk

**Comment by Jassim11** [comment]
https://github.com/David1ali12

**Comment by David1ali12** [comment]
you have a command for minions 
`minions [id] amount name `
and to split` E` and to feed `R`
