### ISSUE TITLE
Cell's outline problem

### ISSUE THREAD

**Issue by Ckicky** [AJS-development/Ogar-unlimited#902]
When smooth render is active (over 2000 mass or smooth render options on) The cells outline color disappears

**Comment by Ckicky** [comment]
Is not invisible, its just hard to see

**Comment by Andrews54757** [comment]
Exactly, the cell border disappears after your view base gets high to reduce lag

**Comment by Ckicky** [comment]
Is there anyways to disable that?
I don't really like it

**Comment by Agarian** [comment]
This doesnt hwppen in regular agar anymore. The cell border stays but just doesnt move.
