### ISSUE TITLE
MAU >:(

### ISSUE THREAD

**Issue by Megabyte918** [AJS-development/Ogar-unlimited#904]
Hey @AJS-development/ogar-unlimited-devs @everyone, click here and go to
[youtube and look for this comment: ](https://www.youtube.com/watch?v=YN5lpbte3wg&google_comment_id=z13ru53hexzlwnjng221sz1qooq4ehfz504)

![capture](https://cloud.githubusercontent.com/assets/4976824/15809842/c50508b0-2b55-11e6-86d2-29d733c84572.PNG)

This guy MAU has stolen OgarUL and has not given us credit or provided a link to this project, see #885 for more info.

I need EVERYONE to go look for @LegitSoulja's comment and like it, so this motherfucker sees it and gets the message. And if it ends up getting deleted, make a new one!

Thanks :)

**Comment by LegitSoulja** [comment]
Everyone should spam on his video in the comments

"**STOP STEALING AJS WORK**"

**Comment by Ckicky** [comment]
YESSSS

**Comment by NatsuTheGreat** [comment]
Kk.

**Comment by Agarian** [comment]
Will do.

**Comment by SorryAgario** [comment]
LOL! mau used to be my friend lmaoooo XD

**Comment by LegitSoulja** [comment]
@Megabyte918 It's all good now :) I handled it

**Comment by Ckicky** [comment]
Gr8

**Comment by Megabyte918** [comment]
gg
