### ISSUE TITLE
This aint a issue

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#906]
AWSOME UPDATE!!!!!!!!!! BLLLLLLLLLLLAZINNNNNNNNNNNNG FAST SERVER !!!
(pellets make abit lag i guess and the feeds W)
BUT REST IS AWSOME SKINS ARE AWSOME! Fucking great!
FUCK AGARIO 
FUCK MINICLIP
FUCK MINICLIPS AIDS
Yay! My server is so sweet now!

**Comment by LegitSoulja** [comment]
@raphyjb You are on the edge of being banned. DON'T MAKE ISSUES WITHOUT A REASON!!.

**Comment by Agarian** [comment]
He has a point, W's lag the server most.

**Comment by NatsuTheGreat** [comment]
You're only ruining your reputation, Raphyjb.
