### ISSUE TITLE
Make a custom client?

### ISSUE THREAD

**Issue by BLUclanTDS** [AJS-development/Ogar-unlimited#907]
I saw the custom client post but i was wondering if you guys had code for it. I want to make my own website like privateservogar-serv1.tk where people could make and host there servers for everyone to see and play. I can do the website and i would use your auth plugin but what about the custom client? i would love any help and feed back for both this website idea and the client. if you are wondering you would register a server on something like privateservogar.tk and the client connecting to your server would be on something like privateservogar-serv193.tk. More info Here: https://github.com/PrivateServOgar/PrivateServOgar/blob/master/README.md . Thanks!!

**Comment by BLUclanTDS** [comment]
Go to https://github.com/PrivateServOgar/PrivateServOgar/blob/master/README.md for things not related to my question. Thank You <3

**Comment by LegitSoulja** [comment]
@BLUclanTDS ok, first of all. You need to have your own hosting and own domain to be able to setup unique domain names like that. .tk you can't.

On the other hand, yes it is really easy to make a website, and allow people to create servers too and from and be able to connect. We have a client that works strictly for OgarUnlimited [client](http://play.ogarul.tk).

Are you looking for the client download for your custom use?

and privateservogar-serv1.tk doesnt exit, so i do

**Comment by NarutoGamerPro** [comment]
Please can pass me the client.zip

**Comment by LegitSoulja** [comment]
[Agarioclient (4).zip](https://github.com/AJS-development/Ogar-unlimited/files/299767/Agarioclient.4.zip)

@NarutoGamerPro

**Comment by NarutoGamerPro** [comment]
Thanks!
