### ISSUE TITLE
Server could not bind to port [No skype open at all]

### ISSUE THREAD

**Issue by Zarakux** [AJS-development/Ogar-unlimited#911]
NFO] Loading Config Files...
[INFO] Loading C:/Users/maste/Downloads/Ogar-unlimited-master/src/core/../settings/advConfig.ini
[INFO] Loading C:/Users/maste/Downloads/Ogar-unlimited-master/src/core/../settings/config.ini
[INFO] Loading C:/Users/maste/Downloads/Ogar-unlimited-master/src/core/../settings/override.ini
[INFO] Your unique id is: 51rqS4Ef4j
[INFO] Loading plugins
[INFO] Starting ConsoleService
                                        _ _       _              _
                                       | (_)     (_)_           | |
  ___   ____  ____  ____    _   _ ____ | |_ ____  _| |_  ____ _ | |
 / _ \ / _  |/ _  |/ ___)  | | | |  _ \| | |    \| |  _)/ _  ) || |
| |_| ( ( | ( ( | | |      | |_| | | | | | | | | | | |_( (/ ( (_| |
 \___/ \_|| |\_||_|_|       \____|_| |_|_|_|_|_|_|_|\___)____)____|
      (_____|
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 17.0.1
[Game] Loaded stats server on port 88
[Error] Server could not bind to port! Please close out of Skype or change 'serverPort' in gameserver.ini to a different number.
[INFO] OgarUnlimited terminated with code: 1

Press any key to exit...

I have this error, now i don't have skype open... i even tried restarting my computer
it never got fixed, i have tried going into the folder gameserver.ini, but i cannot find serverPort in there.
Yes i tried doing ctrl F and searching serverPort.
I tried going to task manager and ending the background process of
skype NOTHING WORKS?

**Comment by LegitSoulja** [comment]
./settings/advConfig.ini
