### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by aqweqwel123** [AJS-development/Ogar-unlimited#913]
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 17.0.1
[Game] Loaded stats server on port 88
[Main] Listening on port 443
[Main] Current game mode is Free For All
TypeError: "callback" argument must be a function
    at exports.setTimeout (timers.js:314:11)
    at GameServer.mainLoop (/root/ogar/new/Ogar-unlimited/src/core/GameServer.js      :1528:7)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
>[OK] Uniban updated
[Console] We recieved a world-wide message!: AJS-Dev break is over early.
 

Help plz

**Comment by NatsuTheGreat** [comment]
Use Node version 5.9.0

**Comment by aqweqwel123** [comment]
i am

**Comment by aqweqwel123** [comment]
do u know?

**Comment by Andrews54757** [comment]
Do `node -v` and tell me the results

**Comment by aqweqwel123** [comment]
says invalid command

**Comment by NatsuTheGreat** [comment]
Do ```node -v``` in your ADMINISTRATOR COMMAND PROMPT

**Comment by aqweqwel123** [comment]
>node -v
[Console] Invalid Command, try help for a list of commands.

**Comment by NatsuTheGreat** [comment]
>Do node -v in your *ADMINISTRATOR COMMAND PROMPT*

**Comment by aqweqwel123** [comment]
[root@vps81601 ~]# node -v
v5.9.0

**Comment by NatsuTheGreat** [comment]
Good, it is 5.9.0 Andrews.

**Comment by aqweqwel123** [comment]
do you know how to fix? the callback error

**Comment by NatsuTheGreat** [comment]
Using 5.9.0 was my only solution, I don't know why you're getting it. Andrew probably knows.

**Comment by aqweqwel123** [comment]
okay, 1 more question

**Comment by aqweqwel123** [comment]
if im using a vps what is my domain>? like where i get to the server.

**Comment by NatsuTheGreat** [comment]
Your domain would be your VPS IP.

**Comment by aqweqwel123** [comment]
okay i thought so

**Comment by aqweqwel123** [comment]
and i just do that ws://ip:443

**Comment by NatsuTheGreat** [comment]
Yes.

**Comment by aqweqwel123** [comment]
alright thanks. guess ill just wait for andrew

**Comment by David1ali12** [comment]
Change ur port server and statsport  I got this problem using Nitruos.io and I fix it that way 
```
change port to 8080 
and server stats to 8082
```
#812

**Comment by aqweqwel123** [comment]
how do i change it from my vps command prompt?

**Comment by ItzLevvie** [comment]
use vim

**Comment by aqweqwel123** [comment]
sorry but whats vim?

**Comment by LegitSoulja** [comment]
Vim is a text editor. I recommend putty, or an online IDE like codeanywhere

**Comment by aqweqwel123** [comment]
i already use putty

**Comment by aqweqwel123** [comment]
but idk how to edit files
