### ISSUE TITLE
 Pellets with chinese names 

### ISSUE THREAD

**Issue by David1ali12** [AJS-development/Ogar-unlimited#916]
I connect to megger and saw that but never happened again once I refresh 

![hidden](https://cloud.githubusercontent.com/assets/17472593/15833154/1db25980-2c2e-11e6-8841-6a698bd0eb6b.PNG)  o.O lol

**Comment by Zertag** [comment]
xD

**Comment by ErikParacelsus** [comment]
This happened to me really rare

**Comment by Andrews54757** [comment]
?. It doesnt happen. Your using another client

**Comment by LegitSoulja** [comment]
@Andrews54757 he's actually using an older version of a client that you modified. I told him to update, but he already added so much to the old one lol

**Comment by David1ali12** [comment]
lol that only happened to merger server I used new client  and it only happened once this only happened version 17.0.0

**Comment by Agarian** [comment]
that happened to viruses once

**Comment by Megabyte918** [comment]
this happens to me all the time

**Comment by Andrews54757** [comment]
version 17.0.0 is not cross compatable with older clients. Although newer servers wont work on old clients, old servers will still work with the new clients

**Comment by Megabyte918** [comment]
@Andrews54757 can you come on gitter?

**Comment by NatsuTheGreat** [comment]
You connect to megger? Try using play.ogaul.tk and make sure you have a compatible version to work with play.ogarul.tk
