### ISSUE TITLE
Please update your clients

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#918]
If you are hosting the client and is not using play.ogarul.tk, update your clients to this: 
[Agarioclient.zip](https://github.com/AJS-development/Ogar-unlimited/files/307871/Agarioclient.zip)

Please, if you do not know what this is, or want to know how to work it out, I DONT CARE!!!! Dont spam the issue by asking questions about it. You must have some computer experience to figure it out and run it

**Comment by Andrews54757** [comment]
UPDATE: 
[Agarioclient.zip](https://github.com/AJS-development/Ogar-unlimited/files/301601/Agarioclient.zip)

**Comment by LegitSoulja** [comment]
@Andrew54757

Ok, so I'm making a game in relative of the game splatter, but agario style.

There's normal foods, you can shoot mass in a good range to injure people(yes there's Heath). Your cell can get big but you cannot split.(maybe)

The objective is that everywhere you move your team color paints on the ground. Also when you shoot, paint splatters, and also makes a paint trail.

To win the game (each round), the team with the most kills, and paint painted wins. Also the winning team are organized into of who painted the most, and killed the most. Points are earned in game to unlock skins, power ups, and etc.

**Power Ups**
- Paint radius 
- Shoot speed
- Player speed increase
- Join with 1-5% mass when start
- Bot assistant to help you, or help paint in your area.

There's more and more I'm adding. Thought I'd share.

**Comment by Andrews54757** [comment]
UPDATE: 
[Agarioclient.zip](https://github.com/AJS-development/Ogar-unlimited/files/307871/Agarioclient.zip)

**Comment by Agarian** [comment]
is this needed?

**Comment by Agarian** [comment]
@Megabyte918 i just noticed the issue number "918"

**Comment by LegitSoulja** [comment]
And? What does that mean? Area code or something?

**Comment by Megabyte918** [comment]
ayye thats my birthday 9/18 xD

**Comment by Agarian** [comment]
This seems pretty outdated, i'll close for now.
