### ISSUE TITLE
Please take this 1 question poll

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#919]
Do you like play.ogarul.tk client or the official agar.io one: http://www.strawpoll.me/10416472. (note in the very recent update, It added client configs)

**Comment by DarkZYT** [comment]
wait will u add retina graphics or wut ?

**Comment by raphyjb** [comment]
OMFG NO LAG W FEEDING DOESNT MAKE LAG :o OOOOMLL!!! AND I PUT 7000 PELLETS NO LAG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! GOOD NEWS!! Lag is gone fucking awsome OGURAL IS BETTER THEN AGARIO!

**Comment by ErikParacelsus** [comment]
@raphyjb lol can you stfu

**Comment by LegitSoulja** [comment]
@Andrews54757 I found something really fucking awesome. You can play agar.io and make money at the same time :)
http://csgocytosis.com/

**Comment by LegitSoulja** [comment]
and what is ogar.io?

**Comment by lotfis** [comment]
OGURAL is so laggy i can't even play with bots!!!!

**Comment by LegitSoulja** [comment]
@Andrews54757 what is difer between play.ogarul.tk and ogar.io which doesnt even exist? 

If you are talking about moving over to ogarul.io that's a bad idea because the site is slow and needs to be upgraded to something else which david will eventually because its soo slow.

**Comment by Andrews54757** [comment]
@LegitSoulja I never said ogar.io, for the poll I said agar.io, it looks like ogar.io, but it is an a

**Comment by Megabyte918** [comment]
I would prefer play.ogarul.tk, but i would also like the new graphics (theyre just SO beautiful)
any way to add them in?

**Comment by Agarian** [comment]
I have a very annoying bug to report. After a while of playing in the client, it would start making me have to press W, SPACE, E, R, T to allow me to move. Is there a fix to that bug? It ruins gameplay. Also when the `rainbow` command is used, the rainbow effect would not update to occupy other cells.
(Say i use the rainbow command on myself, splitting after that would not duplicate the rainbow effect to those cells). One more thing: why does W-ing alot make server physics rough and uneven?

**Comment by Andrews54757** [comment]
I dont see the rainbow bug. Rainbow works perfectly.

**Comment by Andrews54757** [comment]
Fixed bug 1

**Comment by Agarian** [comment]
Noo the rainbow command! Use it on your self then split your cell.

**Comment by Megabyte918** [comment]
@Andrews54757 what about my question? is there?

**Comment by Andrews54757** [comment]
@Agarian I did, it worked

**Comment by LegitSoulja** [comment]
@Megabyte918 I never fully took a look at the client for the graphics, but I could look and find them and make them better.

**Comment by LegitSoulja** [comment]
Looks like there will be a fight between both clients.

**Comment by Megabyte918** [comment]
should this be closed?

**Comment by LegitSoulja** [comment]
No, cause I don't like the fact agar.io client is the best right now lol. I think we can do better without minishit

**Comment by Megabyte918** [comment]
This issue is dead.
