### ISSUE TITLE
Make your server public ??! :[

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#922]
Please people how can i make my server public like @raphyjb 's server , like to allow everyone to join it without the s*** of hamachi !! 
<h1>Thanks

**Comment by bangana** [comment]
Buy a VPS or portforward with hamachi :) no other way

**Comment by DarkZYT** [comment]
;(

**Comment by Andrews54757** [comment]
Hamachi is stupid. don't use it
