### ISSUE TITLE
Ummmmm... Guys? 

### ISSUE THREAD

**Issue by Ckicky** [AJS-development/Ogar-unlimited#923]
[Video.](https://youtu.be/vdDRamfUpXc) Watch it and the description

**Comment by bangana** [comment]
there is millions of that kind of crap

**Comment by firelightning13** [comment]
^

**Comment by NatsuTheGreat** [comment]
Fixed your hyperlink there bud ;)

**Comment by Ckicky** [comment]
@NatsuTheGreat Thx m10-2

**Comment by NatsuTheGreat** [comment]
No problem. :P

**Comment by Andrews54757** [comment]
CONTEST: Create the most forceful defamation global message (yet appropriate and mature) and post it here.
