### ISSUE TITLE
Minions and Superminion Bug

### ISSUE THREAD

**Issue by fayizan** [AJS-development/Ogar-unlimited#924]
I tried playing with minions and superminions but everything just struck on the map not following my mouse

https://gyazo.com/044695ad4042c7e9faeaed216062dad1

My Server Version

https://gyazo.com/37c6a7bfb497c66a9e684a9c094deb92

**Comment by fayizan** [comment]
I updated the client files too from here #918

**Comment by Agarian** [comment]
Press T key -_-

**Comment by fayizan** [comment]
LoL I know that T key option,Just see this Gif  some superminions just spawn and struck on the map 

https://gyazo.com/27c05ec8fb7501d538165151c75adeee

**Comment by fayizan** [comment]
This is with normal minion command

https://gyazo.com/a8478183074492acce4062e54a90fa24

**Comment by Andrews54757** [comment]
Its fixed
