### ISSUE TITLE
Minions Problem

### ISSUE THREAD

**Issue by Daviidee** [AJS-development/Ogar-unlimited#925]
Only some minions follow the mouse, others are still in the map. (key "T" enable).
Please fix this...

**Comment by raphyjb** [comment]
Dont do a copy of other issue 
-1 Week ban

**Comment by Daviidee** [comment]
@raphyjb i don't copy other issue.

**Comment by raphyjb** [comment]
No u just say u got same issue as 924
https://github.com/AJS-development/Ogar-unlimited/issues/570

**Comment by Daviidee** [comment]
@raphyjb ah, sorry

**Comment by Megabyte918** [comment]
this has been an issue for a while, plus another bug: the "B" that appears next to your name glitches out when your cell has no name and it doesnt appear/disappear when it should half the time. its really confusing

**Comment by Andrews54757** [comment]
Fixed
