### ISSUE TITLE
callbackerror?

### ISSUE THREAD

**Issue by aqweqwel123** [AJS-development/Ogar-unlimited#926]
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 17.2.0
[Game] Loaded stats server on port 88
[Main] Listening on port 443
[Main] Current game mode is Free For All
>TypeError: "callback" argument must be a function
    at exports.setTimeout (timers.js:314:11)
    at GameServer.mainLoop (/root/Ogar-unlimited/src/core/GameServer.js:1561:7)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
[Console] We recieved a world-wide message!: AJS-Dev break is over early.
[OK] Uniban updated

i even downgraded to 5.9.0

**Comment by DarkZYT** [comment]
just play

**Comment by Agarian** [comment]
Did you uninstall the previous node?

**Comment by Megabyte918** [comment]
#638
