### ISSUE TITLE
CANT OPEN MY SERVER

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#927]
cant open my server

**Comment by NatsuTheGreat** [comment]
@Andrews54757 This guy is duplicating issues.

**Comment by Megabyte918** [comment]
![screen shot 2016-06-07 at 12 29 01 pm](https://cloud.githubusercontent.com/assets/17245196/15865978/e9c94796-2caa-11e6-8d53-fe6b0703fb98.png)

**Comment by firelightning13** [comment]
dafuq.

Good thing that I disabled email notification :")

**Comment by LegitSoulja** [comment]
@DarkZYT 

For the spam abuse, you will be held against ban for a week. Depending on the past issues/spam created. Next time think about what you do when you do immature things.

**Comment by Agarian** [comment]
He was banned.

**Comment by LegitSoulja** [comment]
I figured that out the hard way. I added his name for the duplicate issue ban list also :/
