### ISSUE TITLE
CUSTOM SKINS DOESNT WORK

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#929]
MY CUSTOM SKINS DOESNT WORK WHEN I UPDATED TO 17.2.0

**Comment by DarkZYT** [comment]
<h1>MAYBE ITS BECAUSE OF THE UPDATE

**Comment by DarkZYT** [comment]
<h10>but can some1 help me

**Comment by NatsuTheGreat** [comment]
You probably have the wrong image then. Now stop spamming issues.

**Comment by DarkZYT** [comment]
<h1>BUT B4 THE UPDATE IT WORKED AND NOW NO

**Comment by NatsuTheGreat** [comment]
Cool, find out what changed and reverse it.

**Comment by DarkZYT** [comment]
Ok thanks
