### ISSUE TITLE
Help me please !

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#930]
<h1>YAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYA YOUUUUUUUUUUUUUUUUUPPPPPPPPPPPPPIIIIIIIIIIIIIIIIIIII YAYAYAYAYAYAYA OMG OMG OMG BOMG%DKLSHNKLFJSDKFLJDSKLFNSKF IM A BOMMMMMMMB YAYAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYAYAYAYAYAAYAYAYAYAYAAYAYA

**Comment by NatsuTheGreat** [comment]
@Andrews54757 Only spam is coming from this guy.

**Comment by ErikParacelsus** [comment]
This guy is really close to getting banned

**Comment by DarkZYT** [comment]
is it too late to say sorry ?

**Comment by DarkZYT** [comment]
i think yes
