### ISSUE TITLE
SORRY

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#931]
Im sorry

**Comment by NatsuTheGreat** [comment]
Got down through your worthless spam. Lets just wait until andrews get here @Andrews54757

**Comment by DarkZYT** [comment]
i wanna just be the 1000th issue !!

**Comment by DarkZYT** [comment]
im sorry

**Comment by DarkZYT** [comment]
IM CLOSING IT

**Comment by NatsuTheGreat** [comment]
We'll let @Andrews54757 decide what to do with you ;)

**Comment by NatsuTheGreat** [comment]
You spammed 5 issues... All worthless.

**Comment by Andrews54757** [comment]
@DarkZYT  Spamming


OFFENSE:
> for spamming


Today I hereby declare you BANNED from ogarUL for 1 week
> Banned on June 7. Will be appeased on June 14
