### ISSUE TITLE
Blue screen !!!

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#932]
Before , i played normaly , then suddenly when i leaved and i joined after some minutes , i see a big black virus , and then my screen go blue !

![issue](https://cloud.githubusercontent.com/assets/19506199/15865101/ff1ea352-2cc8-11e6-8659-14e7d11c71c2.JPG)

Please help me ! 

<h1>Thanks !!!!

**Comment by Andrews54757** [comment]
Turn off tampermoneky
