### ISSUE TITLE
Minions ar gliched , help!!

### ISSUE THREAD

**Issue by MonsterYT** [AJS-development/Ogar-unlimited#933]
Minion dosen t move!!!!

**Comment by Agarian** [comment]
Pressing T will freeze/unfreeze minions.

**Comment by MonsterYT** [comment]
ok thx

**Comment by MonsterYT** [comment]
but still not working

**Comment by MonsterYT** [comment]
just 2 minions come to me

**Comment by Daviidee** [comment]
some

**Comment by Daviidee** [comment]
same for me
http://www.clipular.com/c/5834659142828032.png?k=rLWn3AOF-dhZDyIMaMcqqELRjHs

**Comment by Megabyte918** [comment]
should be fixed

**Comment by Andrews54757** [comment]
fixed
