### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MrMonkeyLOL** [AJS-development/Ogar-unlimited#935]
Hello, i want have his client. How this make in c9?
I have:
AgarioClient.zip
Ogar-Unlimited server.

Help me.

Thanks beforehand.

P.S. I remember what it was issue, but I did not find it :(

**Comment by LegitSouIja** [comment]
You can upload files and git clone on c9

**Comment by LegitSoulja** [comment]
We can't no longer help any with c9. You can't use c9 for hosting. The risks are getting banned.

**Comment by Andrews54757** [comment]
@MrMonkeyLOL If you have no knowledge in hosting a website, too bad, we are not going to teach you.
