### ISSUE TITLE
Run server on Agar.io Client?

### ISSUE THREAD

**Issue by CubeTiger** [AJS-development/Ogar-unlimited#937]
I've been looking through the issues, and I haven't seen much about running it on the Agar.io client. I've been running my server on play.ogarul.tk, but I was wondering If there was still a way to use the Agar.io client?

**Comment by Andrews54757** [comment]
yes, go to ogarunlimited noclient.

**Comment by firelightning13** [comment]
The protocol changed again to version 8 -_-

**Comment by Agarian** [comment]
Really??

**Comment by Agarian** [comment]
Moneyclip must not want us using their client.

**Comment by Megabyte918** [comment]
im even more triggered now

**Comment by LegitSoulja** [comment]
I like how they said they will allow private servers, but still try to prevent bots. 

What's the point? If they allow private servers bots just gonna happen. They keep changing the protocol and not updating us about it. So, yea, working with agar.io you will pretty much have to update the server everytime miniclip decides to piss people off.

**Comment by David1ali12** [comment]
I got some bots working with agario then they changed protocol  again -_-  , WTF  Then they should never blame us for cloning their client if they would  and 48% voted for agario client :confused:
