### ISSUE TITLE
"Callback" error 

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/Ogar-unlimited#938]
http://prntscr.com/bdm87c

**Comment by aqweqwel123** [comment]
downgrade ur node to 5.9.0

**Comment by GhostShot3** [comment]
@aqweqwel123 I use 6.2.1 the last version.

**Comment by NatsuTheGreat** [comment]
Yeah, so downgrade to 5.9.0

**Comment by sethdm02** [comment]
https://nodejs.org/dist/v5.9.0/node-v5.9.0-x64.msi
