### ISSUE TITLE
client?

### ISSUE THREAD

**Issue by aqweqwel123** [AJS-development/Ogar-unlimited#939]
when i download the client file on my vps it doesnt download anything the folder is empty

**Comment by firelightning13** [comment]
This is permission issue. In console, do `cd src` then `sudo chmod 777 client`
or just `sudo chmod 777 src/client`

**Comment by aqweqwel123** [comment]
like when i do plugin install Client
it wont download anything

**Comment by LegitSoulja** [comment]
@aqweqwel123 when you installed the Client look into ./plugins/Client

upload the content from AgarioClient.zio into that folder.
You can connect using port 8080

**Comment by Andrews54757** [comment]
Any questions about hosting the client will be unanswered. If you dont know how to do it, too bad

**Comment by NatsuTheGreat** [comment]
Alright, we'll just close issues ragrding hosting.
