### ISSUE TITLE
IP to get automatically the bots?

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#940]
What game mode were you in when you had the issue?
default
What version are you on?
new
What command did you type if any?
nothing
You must have a description as well
Ok ive had a issue cuz poeple asking for bots in my server and i give them the bots and they go away every 4 minutes (because i got GiveMeMinionsToo) could u guys do a plugin to get ip to get bots automatically or setup something so they dont remove all minions but the minions of those 3 random poeple (Cuz i setup my minions to 3 poeple and it changes every 4min)
Id like to have a plugin so i can control when this person comes in server (with this ip) he get 15 bots so i dont have to type it down every 4minutes.
(also the Rainbow command is messed up, when u die and u respawn u are not in rainbow mode...)

**Comment by LegitSoulja** [comment]
Hm. YML would be a good use in this case. I could be implemented with ease.

**Comment by raphyjb** [comment]
Wats YML?

**Comment by LegitSoulja** [comment]
@raphyjb  A better way to save type of configurations, which can be converted to json to be read easily.

**Comment by raphyjb** [comment]
and how do i do that?!
Also why is there so much lag when theres more then 20 poeple in server? 
go check it out.. i got 700 pellets in server .... 45 minions
http://play.ogarul.tk/?ip=184.75.141.250:443

**Comment by LegitSoulja** [comment]
@raphyjb You won't be able too. I was saying using yml for GiveMeMinionsToo would be a good idea to have specific ip address to get certain amount of mass when join and other things.

And, sorry I can't join. It could also depend on your computer specs. I have no lag with mines what so ever.

**Comment by raphyjb** [comment]
It lags when u get more then 30 poeple in.

**Comment by LegitSoulja** [comment]
@raphyjb It doesn't even lag with 400+ bots for me.

**Comment by raphyjb** [comment]
No its not about the lag with bots. Its about having poeple in the server

**Comment by raphyjb** [comment]
When will it be done? the YML?

**Comment by Andrews54757** [comment]
What is this for?

**Comment by Agarian** [comment]
I think he means like a minions by IP concept

**Comment by Andrews54757** [comment]
It seems like you are trying to sell bots, We do not support that. Proof: #807

**Comment by Agarian** [comment]
wtf? me? or raphyjb?

**Comment by Andrews54757** [comment]
talking about @raphyjb

**Comment by Agarian** [comment]
Oh

**Comment by raphyjb** [comment]
Not trying im just ganna put my friends ip to get bots and spawnmass

**Comment by Andrews54757** [comment]
Model off the opbyip command

**Comment by raphyjb** [comment]
but i dont wat them to get access to get all bots they want i dont want my friends to destroy my server

**Comment by LegitSoulja** [comment]
@Andrews54757 He wants specific ip of people that joins to get a specific amount of minions. I was saying with YAML configuration you could do this with ease, then convert to json. 

When a player joins, check if there ip is stored in yml, and give them the amount of minions stored.

**Comment by raphyjb** [comment]
@LegitSoulja Nice how about spawnmass? would it be as easy?

**Comment by Andrews54757** [comment]
he litterally wants a paid service

**Comment by fayizan** [comment]
Yes @raphyjb is selling bots in his server,just check out his custom leaderboard in his server

**Comment by raphyjb** [comment]
@fayizan wdf u talking about those are the commands to control them, 2nd my server is laggy asf so i cant put more bots then they are, 3rd screen shoot wat u see cuz ur littery saying shit about something that aint real

**Comment by Andrews54757** [comment]
either way, make it yourself

**Comment by raphyjb** [comment]
I dont not know to code program, Im learning.

**Comment by Andrews54757** [comment]
learn then

**Comment by raphyjb** [comment]
can u make me learn?
