### ISSUE TITLE
Game ends up lagging after 10 seconds of playtime due to skins on minions

### ISSUE THREAD

**Issue by HappyRocketwheel** [AJS-development/Ogar-unlimited#941]
I am using the latest ogar version and this is on the agario client ( agar.io/?ip=blahblahblah ) and when I run minions, the game gets lagged out completely.

the problem is because i'm using skins for the bots ( minion 1 100 </random ) but without skins it just works perfectly fine. do you know what's causing this?

**Comment by Andrews54757** [comment]
Look at customskins.txt, if there is a TON of stuff there, thats the problem. There shouldnt be more than whats in in github. Also, use play.ogarul.tk and the lag, I cant do anything about
