### ISSUE TITLE
Help coders?

### ISSUE THREAD

**Issue by darknight99x** [AJS-development/Ogar-unlimited#942]
Can someone implement me the <> to hide skin name mechanic inside of main_out.js 
in Cigar client please?

I can't use this one properly yet as it's multiverse (multiple servers) is kind of broken and I still need ot use cigar.

**Comment by NatsuTheGreat** [comment]
Yeah sorry about this, but we're Ogar Unlimited and we do not support Cigar. Go to cigar issues.

**Comment by darknight99x** [comment]
Funny how your guys's main_out.js is very similar to Cigar's.

**Comment by NatsuTheGreat** [comment]
If it is, then implement them skins into Cigar yourself. Very similar right? No confusion.

**Comment by darknight99x** [comment]
It is almost exact, but I found out that your guys's <> skin thing is not from the client. It's within the actual server.

Could you direct me to where its at then?

**Comment by NatsuTheGreat** [comment]
Do you use file explorer? If so, then you should have a 'search' tool to help you find it.

**Comment by darknight99x** [comment]
Why are you being so smart aleck, of course i'm using a file explorer.
I'm asking what file you may be able to find this in.

**Comment by NatsuTheGreat** [comment]
Why are you not paying attention to me? You're using file explorer, great, use the search tool I talked about.

**Comment by darknight99x** [comment]
God how in the world were you made a contributor.

Do yourself a favor and actually contribute instead of being a smart ass.

**Comment by NatsuTheGreat** [comment]
Now do a favor to yourself, and solve your damn issue on your own. Good bye.

**Comment by LegitSoulja** [comment]
@NatsuTheGreat dude chill. You are doing too much. He only asked where the file was which implemented the "<>" skin use. By that meaning of your answer **Use a file manager** does not solve, nor help him in that case. 

@darknight99x If you are that curios open **GameServer.js** in core, and search for the word **skin**
It's around like 1000'ish,

**Comment by LegitSoulja** [comment]
@NatsuTheGreat And you say that we don't support cigar when we actually do support there client. So you need to like relaxx.

**Comment by darknight99x** [comment]
I appreciate it @LegitSoulja

But I still don't understand much of it.
I'll see if you can figure it out tomorrow.
