### ISSUE TITLE
Skin issue

### ISSUE THREAD

**Issue by MineMooreALT** [AJS-development/Ogar-unlimited#943]
Hey when i get big on ogar skins start to flash with the players color.
dose anyone know how to fix this?

**Comment by Souffer123** [comment]
i have that to

**Comment by WolfOGG** [comment]
yeah my friend told me he saw my skin flashing yesterday, I dint bother to ask but i guess it is a problem huh?

**Comment by Agarian** [comment]
We do not know why this happens.
