### ISSUE TITLE
Can't find the server correctly

### ISSUE THREAD

**Issue by rayer1011** [AJS-development/Ogar-unlimited#944]
Sorry Same issues's like #891 
Here 's the problem: we opened up two servers, A and B
and part of the people can't join server A due to they can't find the "main" server.(most of the people are playing just fine.
For those who can't did use the official client play.ogarul.tk to connect with
However, they can see the leaderboard correctly and connect to server B well.
We've tried to restart the server A and still won't work.

**Comment by Andrews54757** [comment]
you must connect using the master port for it to work. (serverport in advconfig.ini)

**Comment by rayer1011** [comment]
Yes we use the default port ,and there's just a few people cannot join,
they also encountered the same problem.
Server A and B both are using the port 443 and with the different IP address.
And we also try using the different browsers and update to the latest version of server side.

**Comment by Andrews54757** [comment]
Cross server multiverse is not available. Only cross-port
