### ISSUE TITLE
How to make Multiverse servers like Main stay?

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#946]
title says it, i want multiple servers that dont disapear.
Ofc this is optional to answer too. But any help is appreciated!

**Comment by LegitSoulja** [comment]
Don't stop the server. Simple as that :)

**Comment by LegitSoulja** [comment]
Or you can have like a saved configuration for multiverse, and have them recreated on start. You can make a plugin that does that.

**Comment by CalvinDKHD** [comment]
cool, umm. Can i change settings? like instant merge on one and not on
other?

**Comment by Andrews54757** [comment]
Yes, use the change command in each server to change setti ngs
