### ISSUE TITLE
Minion Bug!

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#947]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?

FFA

What version are you on?

17.2.0

What command did you type if any?

minion 1 3 </random>Pro

You must have a description as well

When i did this command Some Bot Dont Come to me when i die!

**Comment by aqweqwel123** [comment]
whats the bug?

**Comment by NatsuTheGreat** [comment]
>When i did this command Some Bot Dont Come to me when i die!

**Comment by David1ali12** [comment]
never happened to me

**Comment by LegitSoulja** [comment]
@PrinceDark9243 Yes, I found that out a while ago. If you have given someone minions and they die the minions won't come back to them. The minions that wasn't eaten before being killed are just roaming around the map, or either still **not moving**.

**Comment by Agarian** [comment]
That doesnt happen to me tho

**Comment by PrinceDark9243** [comment]
yes @Andrews54757 need to fix it!

**Comment by PrinceDark9243** [comment]
sorry Acciendently Closed the Issue

**Comment by Andrews54757** [comment]
Update, it was fixed a while ago
