### ISSUE TITLE
Made a mistake

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/Ogar-unlimited#949]
To start off, I did want to make money with the server, i wanted to get u guys to do a plugin for a bot selling system. I do not own a paypal or any credit card. I did not make any money with this. Nor wouldnt want any of it now. I understand i should of tryed to sell bots, i did not make this server or invent any of it. I wanted to donate to Andrew and Soulja i saw a link where they both didnt want any donations #538 . I will never ask again to make money nor accept no money from nobody. If anyone ask me to donate to get bots, I will say "This isnt my creation, https://github/AJS-development/Ogarul-unlimited made this and they do not accept any donations of any kind" 
I made a server because i didnt like agar.io update they made (fuck miniclip, cough cough Moneyclip=aids) , i saw i could put it online GREAT! then poeple joined and asked for bots.. I said "I do not sell bots". then alot asked to buy bots.. I told them ill try to get a bot system to work so u guys could get bots when joining the server. (That of course didnt happend, cuz 1st i didnt have anything to make that plugin and 2nd I do not own a paypal nor have a credit card). really liked playing my server with poeple that had my tag, it was something! Ive even payed a tech to setup a 24/7 server on vps (that cost me 5$ for vps, and 120$ for the tech to put it up) I put my money to get it to work so much i loved to play! I learned today that Ogarul is not a source of money (not like moneyclip) and that its for poeple to have fun in there own server. Sorry for all issue's ive posted, for that reason i will no more post anything. I will still be on the hub, and check issues and try to help out.
I apologize again and i promise this wont be an issue anymore
-Raph

**Comment by LegitSoulja** [comment]
@raphyjb Ok, so first you said you was not selling anything, and then you said **You did want to make money with the server**. Therefor, you have been banned from OgarUl stats system and will not be unbanned unless told to do so. 

OgarUl stat system is a free system for free servers to play on w/ out having someone to buy things. More info [Why Im Banned](http://stats.ogarul.tk/ban.php)

**Comment by raphyjb** [comment]
Thats why i apologize for wat i tryed to do. That never happended
I promise i will never never accept money for this cause. 
I made a mistake, should of even tryed.

**Comment by David1ali12** [comment]
"DANGER ZONE" ,

**Comment by raphyjb** [comment]
Could i get unbanned Andrew?
I beg you 
I wont do it again!
IMMM SORRY ;(

**Comment by Agarian** [comment]
@raphyjb you are not banned! If you were, you wouldn't be able to send messages...

**Comment by Agarian** [comment]
lol you got busted

**Comment by Andrews54757** [comment]
Actually, @LegitSoulja  I want to insult moneyclip. So i will make plugins that gives its users money now. I am working on an "f you moneyclip advertisement" plugin so  people can get MONEY but moneyclip cant do anything to us because technically, the advertisements are hosted by the server owner

**Comment by Andrews54757** [comment]
so you can unban him

**Comment by raphyjb** [comment]
:D thanks! ill try to help out more in hub!

**Comment by David1ali12** [comment]
make Plugin Name GiveMeMoneyToo  please

**Comment by LegitSoulja** [comment]
@Agarian Yes, the stat's system I made has a ban system. and @Andrews54757 ok.

**Comment by raphyjb** [comment]
Oh shit we got that advertising now! Awsome cant wait to try it!

**Comment by raphyjb** [comment]
Could you make a website to buy those bots and that owner of that site gets money and u get haft of that? so u could be the host of it.

**Comment by LegitSoulja** [comment]
@raphyjb You are thinking about something else. That's too extreme. We are talking about advertisements. That's up to the owner of the server. I don't even have no idea how advertisements will work unless someone has there own domain, and is hosting there own client.

**Comment by raphyjb** [comment]
@LegitSoulja No worry i got an idea! Could put advertising on my brothers company ! Got plenty of idea's here, but would that be possible if you could do the plugin to get ip to get bots and spawnmass?

**Comment by LegitSoulja** [comment]
@raphyjb You are talking about things you have not yet seen yet. What do you mean by putting advertisements on your brothers company? Just keep your ideas to yourself because I don't think they are valid, nor would work in this case.

**Comment by raphyjb** [comment]
oh ok! nvm then.... But u think my plugin could made?

**Comment by Andrews54757** [comment]
Finished the ad plugin. Moving to the ip bots plugin

**Comment by raphyjb** [comment]
Are you doing the spawnmass too Andrews?

**Comment by raphyjb** [comment]
Ip bots plugin coming soon?
