### ISSUE TITLE
How do I change my server name?

### ISSUE THREAD

**Issue by darknight99x** [AJS-development/Ogar-unlimited#950]
How do I change my server name?

I can't find how to change it. All it says is "Main"

**Comment by raphyjb** [comment]
Go on src/plugins/statistics then open the config on notepad and edit the name there!

**Comment by LegitSoulja** [comment]
@darknight99x Main? Where does it say that at? What are you trying to change the name of?

**Comment by darknight99x** [comment]
@LegitSoulja http://167.114.29.68/

**Comment by LegitSoulja** [comment]
@darknight99x That's for multiverse use. Main is your main server. You can create multiple servers using the multiverse command.

**Comment by darknight99x** [comment]
Is there anyway I can change that? I plan on only having one server for now.

**Comment by LegitSoulja** [comment]
@darknight99x in the file ./core/Multiverse.js line 141 you will see
> this.selected = this.create("Main", true);

**Comment by darknight99x** [comment]
@LegitSoulja Okay thanks.

**Comment by fayizan** [comment]
yes setting other names instead of Main won't allow me to switch to another server

**Comment by LegitSoulja** [comment]
@fayizan Yes, I could've figured that'll happen
