### ISSUE TITLE
W spam = extreme lag?

### ISSUE THREAD

**Issue by darknight99x** [AJS-development/Ogar-unlimited#951]
Ok here are my server specifications:

3.70ghz 4core Intel Xeon processor
4GB DDR3 RAM
SSD
WIndows Server 2012

When people shoot 10-15 mass pellets, the server starts lagging like crazy.
There's gotta be a fix for this because it makes the server completely unplayable.

**Comment by Andrews54757** [comment]
interesting, Others reported this but I dont see it happen

**Comment by darknight99x** [comment]
go on agarprivate.ml

you'll see what i mean

**Comment by darknight99x** [comment]
@Andrews54757

**Comment by darknight99x** [comment]
@Andrews54757 
Here is the server resource without any mass pellets from other players laying around and three people on.
![capture](https://cloud.githubusercontent.com/assets/19356956/15916624/c16f4872-2dc2-11e6-9ec8-814d6bea188e.PNG)

Here is the server resource after 15-20 mass pellets were dropped.
*Server was utilizing the whole core for the processor*
![capture2](https://cloud.githubusercontent.com/assets/19356956/15916629/d355676a-2dc2-11e6-8dd2-c02d262bd679.PNG)

**Comment by raphyjb** [comment]
yes w makes lag maybe make a plugin to clear pellets and feeds?
with each like 1 hour they all dissapear and pellets will automatically spawn in the minimum amount
just an idea..

**Comment by LegitSoulja** [comment]
There should be a food limit, and or a game refresher that refreshes a game to a new start without actually restarting.

**Comment by darknight99x** [comment]
@LegitSouja but my issue is that I can't shoot out more than 10 pieces of mass without huge server lag

This should not be happening as my host has 750mb/s+ internet and a very strong processor

**Comment by LegitSoulja** [comment]
I know. I was referring to the comment above mines, and there should be a food limit. But food, and ejected mass are 2 different things.

I'll look into your issue though. I'm also running about 400-800mbs speed, w/ 64Gb ram and my CPU is around 1%-5% running 6 servers, but the memory for nodejs is really high

**Comment by Agarian** [comment]
Plus, <r> does not work anymore.

**Comment by PrinceDark9243** [comment]
yes ejecting 15-20 mass lag the server a lot!

**Comment by Influxx** [comment]
I can confirm the issue exist. This issue can be reproduced by shooting many W's and is caused by: https://github.com/AJS-development/Ogar-unlimited/blob/master/src/entity/EjectedMass.js#L66

`onAutoMove()` calls `gameServer.getNearestVirus(this)` which causes the lag.

**Comment by LegitSoulja** [comment]
@Influxx I'll take a look at it as soon as I can

**Comment by Influxx** [comment]
@LegitSoulja Thanks. Removing [#L66](https://github.com/AJS-development/Ogar-unlimited/blob/master/src/entity/EjectedMass.js#L66) fixes the lag. However, in my testing, after shooting W's for a while, viruses become 'unshootable'.

**Comment by LegitSoulja** [comment]
Why remove L66 when you said the issue was getting the nearest viruses?

**Comment by Influxx** [comment]
Because #L66 calls `onAutoMove()` which calls `getNearestVirus()`. It's only a quickfix to stop the lag issue. I don't know if #L66 is needed but it's probably best if `getNearestVirus()` gets fixed / improved.

**Comment by Andrews54757** [comment]
yeah, but I can't think of any other way

**Comment by Megabyte918** [comment]
@Andrews54757 can you come on gitter? I need your help with a few things

**Comment by Andrews54757** [comment]
Actually, I have a way, but it is too hard to Implement. This is how it would work. The map would be divided into 4 quadrants. When checking for collisions, it would only loop through the nodes in the current quadrant of the object. This would reduce the lag four times. But in the current state of ogar, this would be hard.

**Comment by LegitSoulja** [comment]
@Andrews54757 Can't you just divide the map into sections, and get the nearest virus in that section(quadrant)? #CalculateCoordinates. It doesn't seem as if it would be hard :/. Maybe I'm wrong

**Comment by Influxx** [comment]
That would definitely help. Because it also loops thru all the viruses when ejected mass is moving, so if there is a lot of mass moving simultaneously, the server definitely takes a hit.

**Comment by Agarian** [comment]
Just for the heck of it :)

**Comment by firelightning13** [comment]
Megabyte the issue closer c:

**Comment by LegitSoulja** [comment]
Fixed...
