### ISSUE TITLE
How do you add more outline to text/name

### ISSUE THREAD

**Issue by MineMooreALT** [AJS-development/Ogar-unlimited#952]
Hey how do we add more outline to our name and text like real agario. also when i try to use the client 
it responds on the webpage "Cannot GET /"

**Comment by LegitSoulja** [comment]
@MineMooreALT 
**Install the client plugin**
> plugin install Client

make a folder called **client** where all the other folders are at
Upload the content from AgarioClient.zip to that client folder.

**Comment by MineMooreALT** [comment]
Done now it's working how do i add more outline though?

**Comment by MineMooreALT** [comment]
@LegitSoulja So how do i add more outline to names?

**Comment by LegitSoulja** [comment]
What do you mean by outline to names?

**Comment by MineMooreALT** [comment]
You know in normal agario how there is that thick outline on the font for the names when playing i want to have the same or simmilar outline.

**Comment by LegitSoulja** [comment]
Example? Because when you say outline I'm thinking of something different than what you're talking about.

**Comment by MineMooreALT** [comment]
top: agario
bottom: Private server
http://imgur.com/PFyMG92

**Comment by LegitSoulja** [comment]
Oh so a text solid/stroke you meant haha. I had looked at agario images online but didn't see that. 

Are you using your own client or play.ogarul.tk?

**Comment by MineMooreALT** [comment]
My own client

**Comment by Agarian** [comment]
hard to believe today is the last day of school

**Comment by MineMooreALT** [comment]
Still got 5 weeks for me I'm in Australia

**Comment by LegitSoulja** [comment]
@Agarian my brother school ended 2 weeks ago lol. My school ended 6 years ago :/.

@MineMooreALT I think you can add a text stroke using CSS / WebKit. I'm not 100% sure though

**Comment by LegitSoulja** [comment]
You can edit the canvas ctx font property. When I get on my computer soon I'll give you more in depth about it.

**Comment by MineMooreALT** [comment]
Thanks I gtg to bed soon as its 12:41 am

**Comment by ItzLevvie** [comment]
You can edit it in main_out.js

**Comment by Andrews54757** [comment]
We do not explain client hosting.

**Comment by MineMooreALT** [comment]
@LegitSoulja I still need help on this

**Comment by LegitSoulja** [comment]
@MineMooreALT Sorry, I don't think I can explain it to you since andrew said we don't explain.

**Comment by LegitSoulja** [comment]
Or do you mean the stroke font effect?

**Comment by MineMooreALT** [comment]
yes

**Comment by MineMooreALT** [comment]
@LegitSoulja so how do i add the stroke font effect
