### ISSUE TITLE
Any lastest client with all skins?

### ISSUE THREAD

**Issue by Peppyrotom** [AJS-development/Ogar-unlimited#954]
I need the latest client to host my own client. The client that I have doesnt contain any premium skins and the custom skins doesnt work too. Can anyone give me the client or have a way to fix it?

**Comment by raphyjb** [comment]
I do have them all, go on Stats.ogarul.tk u will see my servers and try new skins <Keeper> <Striker><StarPlayer><HorseSheo><SoccerBoot><SoccerHead>

**Comment by Tokoagar** [comment]
How can u get them? I have alien and I copy the url but to you have mask?

**Comment by David1ali12** [comment]
I added all skins 1000 times I said you dont need custom skins , !!! If you dont update your custom to new which there not should any skins THEN SKIN wont WORK!

**Comment by Andrews54757** [comment]
Client hosting is not explained. You need to have some knowledge to do this

**Comment by HappyRocketwheel** [comment]
skins that the site play.ogarul.tk uses are in http://ogarul.io/skins/

**Comment by LegitSoulja** [comment]
@HappyRocketwheel link doesn't work anymore

**Comment by Agarian** [comment]
Really? Now skins are broken? I cannot test it because my PC is not working ATM :(
