### ISSUE TITLE
BUG name ?

### ISSUE THREAD

**Issue by NoiseControllers** [AJS-development/Ogar-unlimited#955]
Hi, i am using last version, 17.2.0 and client for test http://play.ogarul.tk/ 
it seems to work the skins, although at leandboard no work correctly name

http://i.imgur.com/kES1w8k.png

sorry for my english i am spanish

**Comment by raphyjb** [comment]
Hm what are we suppose to see? Even if ur image is a GIF, in http://play.ogarul.tk/ it wont be moving.

**Comment by NoiseControllers** [comment]
i am using <lol> example why no leandboard show "lol"

**Comment by raphyjb** [comment]
Because its the skins name we do not want to show that.. like in agario.. they do not show anything when u get a skin and u dont name it!

**Comment by NoiseControllers** [comment]
and is there any way I can change that?

**Comment by NoiseControllers** [comment]
I want to show the name in leardboard when they are using skin

**Comment by raphyjb** [comment]
No there isnt

**Comment by NatsuTheGreat** [comment]
There is a way, I need the skin code where ever it is.

**Comment by fayizan** [comment]
@NoiseControllers use the command like this <lol> lol

**Comment by fayizan** [comment]
The actual command is `<skin name> your name` 
Example  `<kraken> NoiseControllers`
