### ISSUE TITLE
How can i host the agar client?

### ISSUE THREAD

**Issue by tommyb008** [AJS-development/Ogar-unlimited#961]
i have a blank domain but do not know how to host the client. i have looked up on google but no chance

**Comment by LegitSoulja** [comment]
Do you have web hosting also? OR just a domain?

**Comment by tommyb008** [comment]
wait can i just use github for this? or no

**Comment by LegitSoulja** [comment]
You can

**Comment by LegitSoulja** [comment]
And you can have the domain redirect to the github pages.

**Comment by tommyb008** [comment]
i want to host a client like petridish or something. is that possible with github and that agarclient?

**Comment by reaper999666** [comment]
I dont think so you would have to probably code your own client or you can get ogar unlimited where you can play with the agario client get it here [https://github.com/AJS-development/Ogar-unlimited-Noclient](url)

**Comment by LegitSoulja** [comment]
@tommyb008 YES You can

**Comment by reaper999666** [comment]
Hey LegitSoulja?
