### ISSUE TITLE
Custom Client or Server

### ISSUE THREAD

**Issue by BLUclanTDS** [AJS-development/Ogar-unlimited#962]
Ok so im making a custom client. (Note i havent updated to the client update 3 days ago.) And i wanted to add extra zoom. I figured out how to scroll farther but now im wondering about the actual vision. i was wondering if the code to make that bigger is located in the client or the server. Im guessing server but if so where? And if on the client where?
If you want the scroll out hack and you have the client:
https://raw.githubusercontent.com/BLUclanTDS/scr/master/scrollout
Read bottom on scroll-out page and on here first.
============================================================
ReadMe!
// I know the risks i am taking by modding this client.
// I dont take responsibility if you mod this client and are sued.
// THANKS!

**Comment by Andrews54757** [comment]
P.S. it is not illegal because this project is open source. We try to stay away from legalistics
