### ISSUE TITLE
Cannot find module even when I type npm install. Server wont load :(

### ISSUE THREAD

**Issue by Dylandonute** [AJS-development/Ogar-unlimited#963]
Error: Cannot find module 'collections/sorted-map'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Dylandonute/Desktop/Ogar-unlimited-master/src/core/WorldModel.js:5:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by LegitSoulja** [comment]
https://github.com/AJS-development/Ogar-unlimited/issues/638

**Comment by Dylandonute** [comment]
I typed npm install collections/sorted-map but it didn't work. It said I need a file, which I dont know if I have it or not.

Dylandonutes-MacBook-Pro:Ogar-unlimited-master Dylandonute$ npm install collections/sorted-map
npm WARN package.json Ogar_Unlimited@17.0.0 license should be a valid SPDX license expression
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de: Cloning into bare repository '/Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de'...
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de: Permission denied (publickey).
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de: 
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de: and the repository exists.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "collections/sorted-map"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de
npm ERR! Cloning into bare repository '/Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Dylandonute/Desktop/Ogar-unlimited-master/npm-debug.log
Dylandonutes-MacBook-Pro:Ogar-unlimited-master Dylandonute$

**Comment by Dylandonute** [comment]
New issue
