### ISSUE TITLE
codeanywhere problem

### ISSUE THREAD

**Issue by SorryAgario** [AJS-development/Ogar-unlimited#964]
Hi! So I ran my server on Nitrous.io so today, I got a bit of research of other alternatives of Nitrous.io, I found codeanywhere I cloned this project (ogar-unlimited) from this website using https://www.github.com/AJS-development/Ogar-unlimited then i chose node.js then create. I installed the dependencies, changed the ports to 8080 and 8082 which is fine. then i typed node index it was succesfully ran without errors :).... now, i wanted to test my server and then I facepalmed when i dont even know what was the ip of the project xD can anyone help me on that rofl.

**Comment by SorryAgario** [comment]
keep in mind that everything ran perfectly, i just didnt know what to put in ws:// XD

**Comment by NatsuTheGreat** [comment]
```ws://ip:port```

As I see you're using Nitrous, it may make your IP different. In that case, do some research on NItrous if you do not the IP.

**Comment by SorryAgario** [comment]
@NatsuTheGreat I already knew how to make it work and get the ip in Nitrous, I was asking on what should i type on my ws as i run my ogar-unlimited in codeanywhere ;c halp

**Comment by SorryAgario** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19484292/15954697/ec7c65a0-2e8e-11e6-83e1-61c4adbd84be.png)
no problem at all

**Comment by LegitSoulja** [comment]
@SorryAgario Try right clicking your nodejs bucket and view information. Note that codeanywhere is not a solution to running nodejs servers, and that you won't get the results you think you will get.

**Comment by David1ali12** [comment]
@SorryAgario install Ogar stats it it will be auto listed on stats.ogarul.tk

**Comment by SorryAgario** [comment]
@David1ali12 link to ogar stats?

**Comment by SorryAgario** [comment]
@LegitSoulja so i wouldnt be able to run my server and play with my friends? well, i was just looking for an alternative for nitrous (:

**Comment by David1ali12** [comment]
`plugin install Statistics` I think

**Comment by SorryAgario** [comment]
@David1ali12 Yep, it installed, now what do i do next?

**Comment by SorryAgario** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19484292/15954821/7121a65c-2e90-11e6-976c-0cfe32bace4f.png)

**Comment by LegitSoulja** [comment]
@David1ali12 No it doesn't work like that

**Comment by David1ali12** [comment]
ok :P

**Comment by LegitSoulja** [comment]
@SorryAgario Codeanywhere has a special dns for each bucket thats created. If you right click the nodejs application you created, and view the info it will tell you your link for the application. You will have to change the port thats there with the application because its marked as an x

**Comment by SorryAgario** [comment]
@LegitSoulja http://preview.0bg8wae3lmrvygb9benpa4xnc2n5qaor26j5w480a6zp8pvi.box.codeanywhere.com/
I have tried to put
ws://preview.0bg8wae3lmrvygb9benpa4xnc2n5qaor26j5w480a6zp8pvi.box.codeanywhere.com:8080 nothing happened. i clicked this http://preview.0bg8wae3lmrvygb9benpa4xnc2n5qaor26j5w480a6zp8pvi.box.codeanywhere.com/ then this happened 
![untitled](https://cloud.githubusercontent.com/assets/19484292/15954870/eab6272c-2e90-11e6-8fe4-cc3962d8fc36.png)

**Comment by LegitSoulja** [comment]
The port doesn't go at the end *sigh*. Why are you coming here for help?

**Comment by LegitSoulja** [comment]
And plus you are using the wrong link.

**Comment by SorryAgario** [comment]
tbh im rlly bad at these stuff, im pretty grateful that u guys still reply though :( idek where to put the port, im sorry

**Comment by SorryAgario** [comment]
then is it http://port-xx.0bg8wae3lmrvygb9benpa4xnc2n5qaor26j5w480a6zp8pvi.box.codeanywhere.com/? then the port 8080 (replacing the "xx")

**Comment by LegitSoulja** [comment]
YES!. Read sometimes

**Comment by SorryAgario** [comment]
welp, i tried ws://port-8080.0bg8wae3lmrvygb9benpa4xnc2n5qaor26j5w480a6zp8pvi.box.codeanywhere.com didnt work i also tried ws://port-8080.0bg8wae3lmrvygb9benpa4xnc2n5qaor26j5w480a6zp8pvi.box.codeanywhere.com:8080

**Comment by LegitSoulja** [comment]
I just made one and it works.. http://port-8080.pdnst5ox2c2chaorsb6zlz3bnu434n294ccr6a4b0x06n7b9.box.codeanywhere.com/

Obviously you are doing something wrong. Do you even have the container running??

**Comment by SorryAgario** [comment]
yes

**Comment by LegitSoulja** [comment]
Are you sure its on?

**Comment by SorryAgario** [comment]
this is probably the problem. 
![untitled](https://cloud.githubusercontent.com/assets/19484292/15955018/7a670dea-2e92-11e6-8b73-cda6a59ca413.png)
is it?

**Comment by SorryAgario** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19484292/15955027/8f698074-2e92-11e6-860d-7c38be5322ae.png)

**Comment by LegitSoulja** [comment]
Don't change non of that stuff. That's probably the reason why.

**Comment by LegitSoulja** [comment]
Restart the container after you reverted your changes. You need to change the ports in advConfig with a port 1024-9999

**Comment by SorryAgario** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19484292/15955055/d3df1e08-2e92-11e6-999b-ed6ee43c3996.png)
i already did like before even typing node index

**Comment by LegitSoulja** [comment]
But this is just a waste of time because that little container cannot handle Ogar

**Comment by LegitSoulja** [comment]
Ok good. Make sure the container is on, before you start the server

**Comment by SorryAgario** [comment]
how could it be off if i can run the ogar-unlimited XD

**Comment by LegitSoulja** [comment]
Because sometimes it can glitches out if you dont know nothing about codeanywhere like I do.

**Comment by LegitSoulja** [comment]
And plus you change configurations, so you need to restart.

**Comment by SorryAgario** [comment]
i did

**Comment by LegitSoulja** [comment]
Ok and I have already told you what you need to do. If you don't know how to do something that simple then I suggest you not to anyways. I don't understand why you changed the config when you didn't even know what you was doing in the first place.

**Comment by SorryAgario** [comment]
welp XD can u just share it to me my email is pobletehanz20@gmail.com

**Comment by LegitSoulja** [comment]
Share what with you?

**Comment by SorryAgario** [comment]
the ogar-unlimited pls.

**Comment by LegitSoulja** [comment]
I've already deleted it. It's simple to install. It's almost 2am and you can't get codeanywhere working wow.

**Comment by SorryAgario** [comment]
oh ok its almost 2pm for me rofl.

**Comment by LegitSoulja** [comment]
Cool beans.

**Comment by LegitSoulja** [comment]
Well, I helped you with what you needed that was finding the link to your container. Do the same exact thing instead of tinkering with the container configurations which shouldn't even be touched, and launch  ogar and use that link when connecting.

You can also test it using the client as **http://play.ogarul.tk/?ip=[past link]**. Make sure you don't paste it with https added, nor any other forward slash because it wont work.

**Comment by SorryAgario** [comment]
aight thanks man :)

**Comment by SorryAgario** [comment]
i made a new account, it worked!

**Comment by LegitSoulja** [comment]
You could've just destroyed the container, but whatever floats your boat.

**Comment by Agarian** [comment]
wait, codeanywhere can actually run an ogarUL server and allow connections?

**Comment by firelightning13** [comment]
@Agarian Yes

**Comment by LegitSoulja** [comment]
Barely can support it.. I don't recommend using it. Only 216mb ram. Unless you consider upgrading
