### ISSUE TITLE
Does anyone know how to make OgarUL multithreaded??

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#965]
Title says it.
THANKS

**Comment by firelightning13** [comment]
bruh

**Comment by LegitSoulja** [comment]
Multiverse, or either create more than 1 server in different folders.

**Comment by CalvinDKHD** [comment]
Yeah, but how do i do the 2nd option you told me? do i make a 2nd AdvConfig?
