### ISSUE TITLE
Does agar.io/?ip=ip=port work again? someone told me it does and i found a server that works with it is this true

### ISSUE THREAD

**Issue by XxRaizerxX** [AJS-development/Ogar-unlimited#966]
Does it work im just wondering i quit ogar unlimited and i came back with THIS question.

**Comment by XxRaizerxX** [comment]
does it work anyone

**Comment by Ckicky** [comment]
Give it a shot
Nothing is better than testing it urself =)

**Comment by ItzLevvie** [comment]
yes it works

**Comment by HappyRocketwheel** [comment]
it works but it's only local, only you can join it.

**Comment by Ckicky** [comment]
I can't join :(

**Comment by Ckicky** [comment]
dont know why.... =(

**Comment by XxRaizerxX** [comment]
lies it wont work

**Comment by ItzLevvie** [comment]
Use Ogar-unlimited-Noclient
