### ISSUE TITLE
Help agario server 17.2.3 VPS this.log error

### ISSUE THREAD

**Issue by agariobro12** [AJS-development/Ogar-unlimited#967]
hey i have an vps error
Here the Complete log

Your code is running at https://agarioserver-gameserveragario.c9users.io.
[INFO] Garbage collection unavailable.  Pass --expose-gc when launching node to enable garbage collection.(memory leak)
[INFO] Loading Config Files...
[INFO] Loading /home/ubuntu/workspace/src/settings/1config.ini
[INFO] Loading /home/ubuntu/workspace/src/settings/advConfig.ini
[INFO] Loading /home/ubuntu/workspace/src/settings/clientConfig.ini
[INFO] Loading /home/ubuntu/workspace/src/settings/confi2g.ini
[INFO] Loading /home/ubuntu/workspace/src/settings/config.ini
[INFO] Loading /home/ubuntu/workspace/src/settings/override.ini
[INFO] Your unique id is: eGua3mPla5
[INFO] Loading plugins
[LBStats] Started up and enabled. Use the CustomLB command to interact with this plugin
[OK] loaded plugin: Leaderboard Stats By Andrews54757 version 1.0.0
[OK] loaded plugin: RandomSkins By LegitSoulja version 1.0.0
[OK] loaded plugin: Statistics By LegitSoulja version 1.0.7
[OK] loaded plugin: Super Minions By Andrews54757 version 1.0.0
[INFO] Starting ConsoleService
                                        _ _       _              _ 
                                       | (_)     (_)_           | |
  ___   ____  ____  ____    _   _ ____ | |_ ____  _| |_  ____ _ | |
 / _ \ / _  |/ _  |/ ___)  | | | |  _ \| | |    \| |  _)/ _  ) || |
| |_| ( ( | ( ( | | |      | |_| | | | | | | | | | | |_( (/ ( (_| |
 \___/ \_|| |\_||_|_|       \____|_| |_|_|_|_|_|_|_|\___)____)____|
      (_____|                                                      
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 17.2.3
[Main] Listening on port 8080
[Main] Current game mode is Free For All
TypeError: this.log is not a function
    at GameServer.<anonymous> (/home/ubuntu/workspace/src/core/GameServer.js:330:38)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1260:10)
    at nextTickCallbackWith1Arg (node.js:431:9)
    at process._tickCallback (node.js:353:17)
    at Module.runMain [as _onTimeout] (module.js:443:11)
    at Timer.listOnTimeout (timers.js:92:15)
[Node] > v4.4.5

[Main] The Game Was Paused to save memory. Join the game to resume!
>[OK] Uniban updated
[Statistics] No recent updates :)
{
Server Name: lel
Server Ip: Private
{

[Statistics] , Updated Server Port 
[Statistics] , Updated Ping

**Comment by ItzLevvie** [comment]
BTW: Don't use C9 for hosting servers.

**Comment by agariobro12** [comment]
why

**Comment by David1ali12** [comment]
change stats port to 8081

**Comment by agariobro12** [comment]
okay wait

**Comment by agariobro12** [comment]
nope

TypeError: this.log is not a function
    at GameServer.<anonymous> (/home/ubuntu/workspace/src/core/GameServer.js:330:38)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1260:10)
    at nextTickCallbackWith1Arg (node.js:431:9)
    at process._tickCallback (node.js:353:17)
    at Module.runMain [as _onTimeout] (module.js:443:11)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by agariobro12** [comment]
ADVConfig=



// Advanced conugurations file for Ogar-Unlimited
// Lines starting with slashes are comment lines
======================================================================================================================================================
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
======================================================================================================================================================
// [Server]
// serverPort : Port for the server. (default is 443)
// serverStatsPort : Port for the server stats. Having a negative number will disable the stats server. (default is 88)
// serverStatsUpdate : Amount of seconds per update for server stats.
// serverViewBase : Base view distance of players. (WARNING: High values may cause lag)
// playerSafeSpawn: Makes sure players dont spawn near, inside, or on top of one another 
// vps : If 1, the port will change to process.env.PORT instead of serverPort/serverStatsPort. (enable this if you have VPS)
// fps : Amount of frames per second. (Note: This will affect the ticks of the server)
serverPort = 8081
serverStatsPort = 8081
serverStatsUpdate = 60
serverViewBaseX = 1024
serverViewBaseY = 592
playerSafeSpawn = 1
vps = 1
fps = 20
======================================================================================================================================================
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
======================================================================================================================================================
// [Bots and Minions]
// smartbotspawn : If 1, if one player joins, the amount in the config below of bots are added. As more players join, the bots despawn.
// smartbspawnbase : Number of bots to spawn when a player enters the game.
smartbotspawn = 0
smartbspawnbase = 20
======================================================================================================================================================
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
======================================================================================================================================================
// [Appearance]
// splitversion : If 1, it uses split mech by Megabyte918.
// viruscolorintense : Intensity of the color of the viruses.
// sizeMult : How much bigger you have to be to eat someone, 1.25 is 25%, 1.50 is 50%, etc.
// VsizeMult : How much bigger you have to be to consume a virus, 1.33 is 33%, 1.66 is 66%, etc.
splitversion = 1
viruscolorintense = 255
sizeMult = 1.25
VsizeMult = 1.33
======================================================================================================================================================
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
======================================================================================================================================================
// [Console]
// liveConsole : 1 = Display the stats of the server in real time, 0 = Off (default).
// consoleUpdateTime : 100 = How often the console will update where 100 = 100 miliseconds or 10 times a second. This mostly effects the live console.
// showjlinfo : 1 = Notifies you if a player joined/left, 0 = Doesnt notify you (default).
// showbmessage : 1 = Notifies you about banned people trying to join and autoban msgs, 0 = Off (default).
// showopactions : 1 = Notifies you of an OPs actions, 0 = Off (default).
// showtopscore : 1 = Shows top score, 0 = Off (default).
liveConsole = 0
consoleUpdateTime = 100
showjlinfo = 0
showbmessage = 0
showopactions = 0
showtopscore = 0
======================================================================================================================================================
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
======================================================================================================================================================
// [Border]
// porportional : If 1, the game size will adjust to the amount of players.
// borderDec : Amount to change the border when a player joins/leaves. (porportional)
porportional = 0
borderDec = 200
======================================================================================================================================================
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
======================================================================================================================================================
// [Anti-Suicide Bot Measures]
// serverScrambleCoords : Scrambles coordinates. 1 = On, 0 = Off. (WARNING: If you turn off, your server could be infested with suicide bots)
// serverMaxConnectionsPerIp : Only allows a certain amount of players per IP to prevent suicide bots. (WARNING: If you set it to more than 10, your server may experience many suicide bots)
// autoban : Bans an IP after reaching over the amount of clients allowed in serverMaxConnectionsPerIP, 1 = Enabled, 2 = Disabled (default). (NOTE: If you enable, you might expirience server performance issues because the bots continuously trying to connect)
// autobanrecord : If 1, it will record banned IP(s) automatically.
// verify : If 1, it will enable Easy Verify where clients will have to verify it is a human by typing a 3 digit random generated number into their nickname box. If failed (X) times, they would be kicked.
// vchance : Amount of trys to verify a player gets before getting kicked.
// vtime : Number of seconds a player has to verify.
// mousefilter : If 1, it will kick players who have the same mouse.
// mbchance : Amount of same mouse players allowed before kick.
// serverScrambleMinimaps : If 1, it will scramble map size. (making minimaps and davidmanns bots useless)
serverScrambleCoords = 0
serverMaxConnectionsPerIp = 5
autoban = 0
autobanrecord = 0
verify = 0
vchance = 5
vtime = 25
mousefilter = 1
mbchance = 5
serverScrambleMinimaps = 0
======================================================================================================================================================
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
======================================================================================================================================================
// [Client ZONE]
// clientclone : If 1, it allows other clients other than agar.io.
// WARNING : IT IS NOT RECOMMENDED TO DO SO BECAUSE IT VIOLATES THE TOS OF AGAR.IO. ALSO, IF THE CLIENT IS NOT PROPERLY MADE, IT CAN BE BAD FOR YOU. NOTICE THAT TURNING THIS ON IS 100% ILLEGAL!
// Never mind, Moneyclip F---ed up the game

// Packetversion: 1 = old packet from about 10 months ago (most clients use this) 0 = latest client before moneyclip ruined the game
// allowonly: The url/ip of your client. (so that only that website can access it)
clientclone = 1
packetversion = 1
allowonly = ""
======================================================================================================================================================
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
======================================================================================================================================================
// [Dev]
// dev : if 1, dev mode is turned on
dev = 0

**Comment by David1ali12** [comment]
I think you should upgrade node version 5.9.0

**Comment by agariobro12** [comment]
ok wait

**Comment by David1ali12** [comment]
Hhhh you are using same port for stats and server port  faceplam

**Comment by ItzLevvie** [comment]
"why" - @agariobro12 

because you'll get banned.

**Comment by agariobro12** [comment]
:c

**Comment by tommyb008** [comment]
why dont you put in update all then update your node then change your port? it fixed for me

**Comment by agariobro12** [comment]
what i need for the server port and stats?

**Comment by David1ali12** [comment]
stats port 8081 server port 8080 XD

**Comment by agariobro12** [comment]
xDDD

**Comment by tommyb008** [comment]
i would use 4411 for port and stats 8081

**Comment by tommyb008** [comment]
ez to remember

**Comment by agariobro12** [comment]
#0070FFWait guys

**Comment by David1ali12** [comment]
4411 dont work for c9 :P  you can use 8080&8081&8082

**Comment by tommyb008** [comment]
oh i cant use c9 they banned my account # WAITING MODE ACTIVATED

**Comment by agariobro12** [comment]
agin the error

TypeError: this.log is not a function
    at GameServer.<anonymous> (/home/ubuntu/workspace/src/core/GameServer.js:330:38)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1260:10)
    at nextTickCallbackWith1Arg (node.js:431:9)
    at process._tickCallback (node.js:353:17)
    at Module.runMain [as _onTimeout] (module.js:443:11)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by tommyb008** [comment]
hmmm ive had that error

**Comment by tommyb008** [comment]
i think i know how to fix that in a nother way

**Comment by David1ali12** [comment]
lol just reinstall and make sure this time node is v5.9.0

**Comment by agariobro12** [comment]
can´t edit the node js its from ic9

soll i post the complete log here?

**Comment by David1ali12** [comment]
make another workspace

**Comment by agariobro12** [comment]
anthor needs cash

**Comment by agariobro12** [comment]
Your code is running at https://agarioserver-gameserveragario.c9users.io.
[INFO] Garbage collection unavailable.  Pass --expose-gc when launching node to enable garbage collection.(memory leak)
[INFO] Loading Config Files...
[INFO] Loading /home/ubuntu/workspace/src/settings/1config.ini
[INFO] Loading /home/ubuntu/workspace/src/settings/advConfig.ini
[INFO] Loading /home/ubuntu/workspace/src/settings/clientConfig.ini
[INFO] Loading /home/ubuntu/workspace/src/settings/confi2g.ini
[INFO] Loading /home/ubuntu/workspace/src/settings/config.ini
[INFO] Loading /home/ubuntu/workspace/src/settings/override.ini
[INFO] Your unique id is: eGua3mPla5
[INFO] Loading plugins
[LBStats] Started up and enabled. Use the CustomLB command to interact with this plugin
[OK] loaded plugin: Leaderboard Stats By Andrews54757 version 1.0.0
[OK] loaded plugin: RandomSkins By LegitSoulja version 1.0.0
[OK] loaded plugin: Statistics By LegitSoulja version 1.0.7
[OK] loaded plugin: Super Minions By Andrews54757 version 1.0.0
[INFO] Starting ConsoleService
                                        _ _       _              _ 
                                       | (_)     (_)_           | |
  ___   ____  ____  ____    _   _ ____ | |_ ____  _| |_  ____ _ | |
 / _ \ / _  |/ _  |/ ___)  | | | |  _ \| | |    \| |  _)/ _  ) || |
| |_| ( ( | ( ( | | |      | |_| | | | | | | | | | | |_( (/ ( (_| |
 \___/ \_|| |\_||_|_|       \____|_| |_|_|_|_|_|_|_|\___)____)____|
      (_____|                                                      
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Server version is 17.2.3
[Main] Listening on port 8080
[Main] Current game mode is Free For All
TypeError: this.log is not a function
    at GameServer.<anonymous> (/home/ubuntu/workspace/src/core/GameServer.js:330:38)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitListeningNT (net.js:1260:10)
    at nextTickCallbackWith1Arg (node.js:431:9)
    at process._tickCallback (node.js:353:17)
    at Module.runMain [as _onTimeout] (module.js:443:11)
    at Timer.listOnTimeout (timers.js:92:15)
[Node] > v4.4.5

[Main] The Game Was Paused to save memory. Join the game to resume!
>[OK] Uniban updated
[Statistics] No recent updates :)
{
Server Name: lel
Server Ip: 104.155.17.34
{

[Statistics] , Updated Server Port 
[Statistics] , Updated Ping 

here agin the log

**Comment by agariobro12** [comment]
this.log is not a function

**Comment by tommyb008** [comment]
fuck node

just download [this ](https://github.com/AJS-development/nodemodules)

**Comment by tommyb008** [comment]
/\ should help

**Comment by tommyb008** [comment]
it helped me

**Comment by tommyb008** [comment]
a sh*t ton

**Comment by agariobro12** [comment]
wait

**Comment by tommyb008** [comment]
# (0)-(0)

**Comment by tommyb008** [comment]
# waiting mode activated

**Comment by agariobro12** [comment]
and when i upload my nodemodules anyone file cant be uploaded

**Comment by agariobro12** [comment]
# OK :D

**Comment by ItzLevvie** [comment]
Set VPS to 0 and manually set the port.

**Comment by agariobro12** [comment]
hey i dont need private server´s :cactus:

**Comment by agariobro12** [comment]
:dancer:

**Comment by tommyb008** [comment]
# :/

**Comment by tommyb008** [comment]
# so you give up?

**Comment by tommyb008** [comment]
# never give up

**Comment by agariobro12** [comment]
my friend will not install hamachi -.-
No i dont give up! m Hard

**Comment by tommyb008** [comment]
# nothing is impossible

**Comment by agariobro12** [comment]
ok in uploading the node_modules this are 15000 daten or more :c

**Comment by David1ali12** [comment]
@agariobro12  RIP after upload is done your account is banned

**Comment by agariobro12** [comment]
and yes my english is bad im from germany

**Comment by agariobro12** [comment]
sorry guys :d

**Comment by tommyb008** [comment]
why is he banned?

**Comment by agariobro12** [comment]
nope and thanks vps are now functionate Special thanks on tommyb008

**Comment by tommyb008** [comment]
:+1:

**Comment by LegitSoulja** [comment]
@tommyb008 @agariobro12 
I have told everyone, and even @ItzLevvie told you don't use c9. If you get banned don't come crying to us because we didn't tell you to use c9, and we are against even telling people how to setup c9 since they don't even want kiddies using there stuff. 

More info https://github.com/AJS-development/Ogar-unlimited/issues/630
