### ISSUE TITLE
What are all the working skins/new ones that are added?

### ISSUE THREAD

**Issue by tommyb008** [AJS-development/Ogar-unlimited#968]
is there a list of them i can look at them or can you tell me them? i want to know so i can put my self as those skins

**Comment by raphyjb** [comment]
yes go on Ogar-unlimited/src/ and open customskins with notepad+

**Comment by BLUclanTDS** [comment]
there are a few client skins that are not included in the customskins.txt
soccer :http://i.imgur.com/uMeo8Of.jpg
splayer :http://i.imgur.com/XjghM0H.png
soccers :http://i.imgur.com/An4cvdH.png
soccerb :http://i.imgur.com/JegqDKa.png
striker :http://i.imgur.com/Wc9pJln.png
keeper :http://i.imgur.com/vkI87vl.png

The soccer skins! They are in client but not server so if you use custom client like me then you cant see these skins! The soccer won is custom but I through it in there.

**Comment by LegitSoulja** [comment]
On play.ogarul.tk click the **Want skin list?**. It provides all the updated and new skins.

**Comment by Agarian** [comment]
Actually, clicking it just opens a new tab with the URL http://http://play.ogarul.tk/#

**Comment by LegitSoulja** [comment]
@Agarian xD well that only happens to you.. Not anyone else

**Comment by LegitSoulja** [comment]
And why that url like that? Links doesn't do that if it failed to prevent the event / page from redirecting.

**Comment by Agarian** [comment]
it works now lol

**Comment by LegitSoulja** [comment]
it been working
