### ISSUE TITLE
After I did npm install collections/sorted-map it still didn't work. 

### ISSUE THREAD

**Issue by Dylandonute** [AJS-development/Ogar-unlimited#969]
First Conversation: https://github.com/AJS-development/Ogar-unlimited/issues/963

I typed npm install collections/sorted-map but it didn't work. It said I need a file, which I dont know if I have it or not.

Dylandonutes-MacBook-Pro:Ogar-unlimited-master Dylandonute$ npm install collections/sorted-map
npm WARN package.json Ogar_Unlimited@17.0.0 license should be a valid SPDX license expression
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de: Cloning into bare repository '/Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de'...
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de: Permission denied (publickey).
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de: 
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de: and the repository exists.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "collections/sorted-map"
npm ERR! node v4.4.1
npm ERR! npm v2.14.20
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de
npm ERR! Cloning into bare repository '/Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-290ba2de'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR! /Users/Dylandonute/Desktop/Ogar-unlimited-master/npm-debug.log
Dylandonutes-MacBook-Pro:Ogar-unlimited-master Dylandonute$

**Comment by raphyjb** [comment]
clearly see: npm ERR! https://github.com/npm/npm/issues
This is suppose to be a for windows linux, not mac

**Comment by Dylandonute** [comment]
Yeah, but I ran it yesterday, and it worked. The commands I did in terminal were
1. Drag the Ogar folder into terminal, clicked enter.
2.I typed npm install ws, clicked enter.
3.I typed sudo -s
4. I typed node(space) and dragged index.js from the src folder into it, and clicked enter.
I'm not saying that your wrong, but I think it works, and there is something missing? xD 
Thanks anyway.

**Comment by Megabyte918** [comment]
What version of node is it?

**Comment by BLUclanTDS** [comment]
Try using 5.9.0 node version

**Comment by LegitSoulja** [comment]
You guys really need to learn how to read a stack trace, and you did not properly install the module correctly because you typed it incorrectly.

You are running nose v4.4.1, which is good, but 5.9.0 is recommended, but you'll be okay with just that.

**Comment by Agarian** [comment]
"nose v4.4.1" xD

**Comment by Dylandonute** [comment]
Thx. =D I will try that today, I hope it works because I have been trying for 2 days now xD.
Node 5.9.0?

**Comment by Dylandonute** [comment]
Nooo.... it still doesn't work. I downloaded the new node 5.9.0 correctly, but it still didn't work. 
Dylandonutes-MacBook-Pro:~ Dylandonute$ cd /Users/Dylandonute/Desktop/Ogar-unlimited-16.5.7 
Dylandonutes-MacBook-Pro:Ogar-unlimited-16.5.7 Dylandonute$ npm install collections/sorted-map
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731: Cloning into bare repository '/Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731'...
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731: Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731: Permission denied (publickey).
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731: 
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731: and the repository exists.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "collections/sorted-map"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731
npm ERR! Cloning into bare repository '/Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731'...
npm ERR! Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Dylandonute/Desktop/Ogar-unlimited-16.5.7/npm-debug.log
Dylandonutes-MacBook-Pro:Ogar-unlimited-16.5.7 Dylandonute$ sudo -s
Password:
bash-3.2# node /Users/Dylandonute/Desktop/Ogar-unlimited-16.5.7/src/index.js 
module.js:341
    throw err;
    ^

Error: Cannot find module 'collections/sorted-map'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/Dylandonute/Desktop/Ogar-unlimited-16.5.7/src/core/WorldModel.js:5:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
bash-3.2#

**Comment by LegitSoulja** [comment]
delete your node_modules folder in the src folder and run npm install again.
