### ISSUE TITLE
Im a little worried

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#970]
I keep hearing this errie sound outside my house, im not the only one hearing it either...
Here is the sound(my sound recorder kinda sucks):
https://vid.me/TAYH
If you have an explanation to this, please do so!

**Comment by NatsuTheGreat** [comment]
Uhm, please specify how this noise comes to life.

**Comment by Agarian** [comment]
I really dont know, there are many vids like this on YT, its creepy AF

**Comment by Agarian** [comment]
And this the first time ive heard it in person

**Comment by Agarian** [comment]
Idk what to do...

**Comment by NatsuTheGreat** [comment]
Check to make sure nothing in your computer is malfunctioning, disks could make weird noises too. Happened to me once. And check and make sure there aren't any spoofs.

**Comment by NatsuTheGreat** [comment]
That is a scary noise though.

**Comment by Agarian** [comment]
How long did it take you to notice that this is a prank? The noise was just a nearby industrial building :p

**Comment by NatsuTheGreat** [comment]
Uhm I knew it was a prank...

**Comment by Megabyte918** [comment]
this place is for issues df

**Comment by firelightning13** [comment]
wtf is this

**Comment by LegitSoulja** [comment]
Don't even ask lol

**Comment by Ckicky** [comment]
'

**Comment by Megabyte918** [comment]
.
