### ISSUE TITLE
See more of the map with scroll out.

### ISSUE THREAD

**Issue by BLUclanTDS** [AJS-development/Ogar-unlimited#971]
I want to have my players see more of the map. I have scrollout working but i cant see much more of the map. Where is the code located? Client or server? If so where? THANKS. P.S the scroll out is located in the main_out.js part in the client.

**Comment by BLUclanTDS** [comment]
Please dont take this down again.

**Comment by PrinceDark9243** [comment]
change the serverViewBaseX and serverViewBaseY to higher number
