### ISSUE TITLE
Port Forwarding Help

### ISSUE THREAD

**Issue by agariobro12** [AJS-development/Ogar-unlimited#973]
What i need four a port and Protocoll?    please help

**Comment by agariobro12** [comment]
i can forwarding port 80/443-447 8081

**Comment by raphyjb** [comment]
? thats doesnt make sense.. but if u wanna port foward
watch this: https://www.youtube.com/watch?v=usSpl0yJFnY
You will need to port forward port 443

**Comment by LegitSoulja** [comment]
Port forward whatever game/ServerPort you are using prior to your computer IPv4. If you have a router that you can do a port range with go for it, open them all.

If you want to use the statistics plunging you have to have your stay port open aswell.
