### ISSUE TITLE
agar.io/?ip=localhost:443 not working

### ISSUE THREAD

**Issue by XxRaizerxX** [AJS-development/Ogar-unlimited#974]
its not working

**Comment by XxRaizerxX** [comment]
someone said it works

**Comment by XxRaizerxX** [comment]
anything i have to do to make it work

**Comment by David1ali12** [comment]
what did you used ogar-unlimited noclient?  miniclip can change protocol any time use playl.ogarul.tk Fmoneyclip

**Comment by raphyjb** [comment]
Fuck agario

**Comment by LegitSoulja** [comment]
Protocol and packets was probably changed once again. If so, no clients will work with agar.io
