### ISSUE TITLE
MULTIVERSE NOT WOKING!?

### ISSUE THREAD

**Issue by sethdm02** [AJS-development/Ogar-unlimited#977]
Multiverse does not work click on that server and does not take me to it :/

**Comment by LegitSoulja** [comment]
Can you provide the web log?

**Comment by raphyjb** [comment]
True Its not working

**Comment by sethdm02** [comment]
no web log?!

**Comment by raphyjb** [comment]
Wats web log?

**Comment by fayizan** [comment]
Multiverse not working for me too

**Comment by PrinceDark9243** [comment]
its is not working for me too

**Comment by lotfis** [comment]
what does multiverse do??? (pls don't lol at me or ignore me, im trying hard to learn here)

**Comment by firelightning13** [comment]
@lotfis Multiverse is a thing that you can connect with multiple games at one server

**Comment by lotfis** [comment]
@firelightning13 thanks

**Comment by LegitSoulja** [comment]
I confirm that multiverse is working correctly and no issues. Make sure you set up your servers correctly, and your PORTS you can created with multiverse is also open.
