### ISSUE TITLE
Youtube vids that copyright ogar unlimited/do not give credit to ogar unlimited/offer 3rd party downloads for ogar unlimited 

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#980]
Here is one for example.
https://youtu.be/Zxh_kTpjxlw
You should spread the word in this video and other videos like it that this person committed copyright by not giving credit to the real creators of ogarUL!

**Comment by David1ali12** [comment]
https://www.youtube.com/watch?v=ZzJJAB79TgI he renamed it to break agar v6 what a joke -_-

**Comment by LegitSoulja** [comment]
Let me know if i have to go onto a video an act a fool because I will.

**Comment by HappyRocketwheel** [comment]
infact, i've caught someone making videos with these bots and calling them real.

I commented in his videos that they're private servers, but people think it's real

https://www.youtube.com/watch?v=Hdsjrd7GbLU

description of his vids say "300 LIKES AND I'LL RELEASE THE BOTS"

**Comment by firelightning13** [comment]
The same youtuber do same thing :/

**Comment by David1ali12** [comment]
https://www.youtube.com/watch?v=UTAShrH7MqM stavj

**Comment by CalvinDKHD** [comment]
Server that use OgarUL that should be closed - http://u-bot.co/game1/index.html

**Comment by Tokoagar** [comment]
Reporting this channel : https://www.youtube.com/channel/UCH7jXwmv_hKfSlrayjqDVJQ asking for likes and sub this video in particular : https://www.youtube.com/watch?v=3r8QOsPCDcg description OMG! AGAR.IO FREE 9999 BOTS / FREE MINIONS - 132 MASS BOTS / FACEBOOK BOTS HACK

● Link - 20k subscribe!

● Subscribe - http://goo.gl/CKZXry
● Twitter - https://twitter.com/BiksloOu

● Music of video:
♫ http://incompetech.com

Thank you for watching!
1 week ago he add 10k now 19k almost 20 when he will rech 20k he will change again....

**Comment by HappyRocketwheel** [comment]
@Tokoagar I reported him also, and he got his verified sign removed 2 days ago.

**Comment by BLUclanTDS** [comment]
https://www.youtube.com/watch?v=cejobefsfuc

**Comment by Andrews54757** [comment]
Really, is this neccasary? I dont really care anymore.

**Comment by Agarian** [comment]
I do.

**Comment by maciej441** [comment]
@Andrews54757 Yes, it i. (I think)

**Comment by Megabyte918** [comment]
As long as the command prompt says that its by AJS and they can still update the server i dont think this matters

**Comment by raphyjb** [comment]
https://www.youtube.com/watch?v=ql7XGghepHs

**Comment by Agarian** [comment]
The /rcon thing doesnt work, it always says Wrong password
Even when a password is specified in the config

**Comment by LegitSoulja** [comment]
Mega they could've patched it, or replaced the console ascii with something else. I've seen 1 or 2 people that did it before.

But 9/10 the people that make videos are probably little kids that doesn't know a thing, and call Ogar Unlimites # AGAR.IO # W/ Free bots when they don't even know what minions are -_-

**Comment by jackmio32** [comment]
im reporting this vid
> https://www.youtube.com/watch?v=ql7XGghepHs

**Comment by NatsuTheGreat** [comment]
> But 9/10 the people that make videos are probably little kids that doesn't know a thing, and call Ogar Unlimited # AGAR.IO # W/ Free bots when they don't even know what minions are -_-

Very true.

**Comment by Andrews54757** [comment]
not so neccesary
