### ISSUE TITLE
I am making a server using OgarUL and its Client!

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#981]
Hey guys! so i will soon make a server, with OgarUL and its cool features.
So i dont want to get copyrighted or anything! so how do i go about not getting rekt from this fantasitc community?

**Comment by firelightning13** [comment]
@CalvinDKHD Just make a server. Don't ever post issues here **if it's not an issue**

**Comment by CalvinDKHD** [comment]
Ohh Sorry! Well hehe, it is an issue.

**Comment by Andrews54757** [comment]
we dont care about copyrights. We try to stay away from legalities

**Comment by CalvinDKHD** [comment]
I am sorry, i will stop posting questions here.
