### ISSUE TITLE
Changing interface! Issue

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#982]
Hello people! So i have been having issues when trying to change it in the index.html. Because the css is in the html. I dunno how exactly to do this, so i am asking someone so help me!

I would gladly pay some money for someone to make a sexy looking interface/style/main or what ever!
Maybe something like this / https://gyazo.com/8b3ebbf28237d92b29f68cd495beec52
But different colours etc.
Add me on skype please! / calvin.leonhardt

**Comment by LegitSoulja** [comment]
It's ease, but we don't discuss clients, and client modifications.

**Comment by LegitSoulja** [comment]
And I think someone else already told you not to make issues if you don't have an issue, but this has to be closed.

**Comment by CalvinDKHD** [comment]
This is an issue, getting errors.

**Comment by CalvinDKHD** [comment]
But i fixed it
