### ISSUE TITLE
Retina Graphics Option? Just like agario.

### ISSUE THREAD

**Issue by DTMClanDeveloper** [AJS-development/Ogar-unlimited#983]
Some people love the Retina graphics. How ever dont get a chance to play with them on a private server, it would be awesome if you can put an option on the client settings for Retina Graphics! :) Thanks in advance.

**Comment by CalvinDKHD** [comment]
DTMClanDevelepor, add me on skype - calvin.leonhardt

**Comment by DTMClanDeveloper** [comment]
Sure :)

**Comment by HappyRocketwheel** [comment]
you want it in your own client of play.ogarul.tk?

**Comment by DTMClanDeveloper** [comment]
No no, i use play.ogarul.tk client, how ever i was wondering if they can just make an option for retina mode.

**Comment by LegitSoulja** [comment]
Soon.
