### ISSUE TITLE
Can I change the skin list ?

### ISSUE THREAD

**Issue by Tokoagar** [AJS-development/Ogar-unlimited#984]
Sorry for bad english
What game mode were you in when you had the issue?
ffa
What version are you on?
17.2.3
What command did you type if any?
Nan
description: Can I change the skin list like remove or add ? or where is the file whitch contain this skin? Thanks for your answers

**Comment by HappyRocketwheel** [comment]
You can find the file at /src/customskins.txt and /src/randomSkins.txt ( only if you want to use it on bots )

example:

name :imgur.com/testurl

**Comment by Tokoagar** [comment]
Control your cell using the mouse, w for eject, space for split. Add <skinname> in your username for skins. Want skin list?

There if you click `want skin list` you have all skin can i delete some?

**Comment by Tokoagar** [comment]
https://cdn.discordapp.com/attachments/171246318092550144/191577499702919171/unknown.png

**Comment by Tokoagar** [comment]
here's a screen shot

**Comment by HappyRocketwheel** [comment]
@Tokoagar i don't think so unless you use agario client itself

**Comment by Tokoagar** [comment]
ok

**Comment by BLUclanTDS** [comment]
You would have to have there client and then you can delete them. You can ask them for an agar.io client in a new issue or in this one.

**Comment by Tokoagar** [comment]
ok

**Comment by LegitSoulja** [comment]
@BLUclanTDS @Tokoagar no clients are released with the skins view, nor you can't decide which ones to show and not to show. They are live updates skins, so if there was ever new skins it will show automatically.

No released clients contain this yet, but soon.

**Comment by Tokoagar** [comment]
ok
