### ISSUE TITLE
 I can change url ?

### ISSUE THREAD

**Issue by RelTakeover** [AJS-development/Ogar-unlimited#985]
i can change url ? play.ogarul.tk/?ip:127.0.0.1:443  to ---> mysyte.com

is possible?

**Comment by PrinceDark9243** [comment]
you need to get a domain

**Comment by RelTakeover** [comment]
i have a premium domain , how to change ?

**Comment by BLUclanTDS** [comment]
Example: wayclient.comxa.com   This is a website i made. What you will need is a domain and a hosting service. You need to access c panel and upload the agar.io client to your c panel files so they can be seen by people when they log on to your website. I will happily give you my taemplate of the agar.io client or you can ask the developers of ogar unlimited for it. If you need a hosting service go to https://www.000webhost.com/cpanel-login an sign up. I will gladly go into more detail if needed.

**Comment by LegitSoulja** [comment]
You just need a domain, not all that other crappy hosting.

**Comment by LegitSoulja** [comment]
000webhost is bad also, don't register no domain with them, nor think you'll have a lot of people because you can barely get traffic before CPU limit increases. Plus I think they have on-site ads

**Comment by raphyjb** [comment]
000webhost = aids  (AKA MONEYCLIP)
