### ISSUE TITLE
After I typed npm install collections/sorted-map and I deleted the node_modules folder in src it still didn't work. 

### ISSUE THREAD

**Issue by Dylandonute** [AJS-development/Ogar-unlimited#986]
First Conversation:
https://github.com/AJS-development/Ogar-unlimited/issues/963

Second Conversation:
https://github.com/AJS-development/Ogar-unlimited/issues/969

Last login: Sun Jun 12 09:14:30 on ttys001
Dylandonutes-MacBook-Pro:~ Dylandonute$ node -v
-bash: node: command not found
Dylandonutes-MacBook-Pro:~ Dylandonute$ 
  [Restored Jun 12, 2016, 11:10:43 AM]
Last login: Sun Jun 12 11:09:53 on console
Restored session: Sun Jun 12 09:18:13 PDT 2016
Dylandonutes-MacBook-Pro:~ Dylandonute$ node -v
-bash: node: command not found
Dylandonutes-MacBook-Pro:~ Dylandonute$ node -v
v6.2.1
Dylandonutes-MacBook-Pro:~ Dylandonute$ /Users/Dylandonute/Desktop/Ogar-unlimited-master 
-bash: /Users/Dylandonute/Desktop/Ogar-unlimited-master: is a directory
Dylandonutes-MacBook-Pro:~ Dylandonute$ npm install ws
Ogar_Unlimited@17.0.0 /Users/Dylandonute
└─┬ ws@1.1.0 
  ├── options@0.0.6 
  └── ultron@1.0.2 

npm WARN Ogar_Unlimited@17.0.0 license should be a valid SPDX license expression
Dylandonutes-MacBook-Pro:~ Dylandonute$ sudo -s
Password:
bash-3.2# node /Users/Dylandonute/Desktop/Ogar-unlimited-master/src/index.js 
module.js:442
    throw err;
    ^

Error: Cannot find module 'collections/sorted-map'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Dylandonute/Desktop/Ogar-unlimited-master/src/core/WorldModel.js:5:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
bash-3.2# 
  [Restored Jun 12, 2016, 11:12:31 AM]
Last login: Sun Jun 12 11:10:43 on ttys000
Restored session: Sun Jun 12 11:12:30 PDT 2016
Dylandonutes-MacBook-Pro:~ Dylandonute$ /Users/Dylandonute/Desktop/Ogar-unlimited-master 
-bash: /Users/Dylandonute/Desktop/Ogar-unlimited-master: is a directory
Dylandonutes-MacBook-Pro:~ Dylandonute$ npm install collections/sorted-map
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731: Cloning into bare repository '/Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731'...
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731: Permission denied (publickey).
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731: fatal: Could not read from remote repository.
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731: 
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731: Please make sure you have the correct access rights
npm ERR! git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731: and the repository exists.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "collections/sorted-map"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/Dylandonute/.npm/_git-remotes/_templates --mirror git@github.com:collections/sorted-map.git /Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731
npm ERR! Cloning into bare repository '/Users/Dylandonute/.npm/_git-remotes/git-github-com-collections-sorted-map-git-d173d731'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Dylandonute/npm-debug.log
Dylandonutes-MacBook-Pro:~ Dylandonute$ sudo -s
bash-3.2# node /Users/Dylandonute/Desktop/Ogar-unlimited-master/src/index.js 
module.js:442
    throw err;
    ^

Error: Cannot find module 'collections/sorted-map'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Dylandonute/Desktop/Ogar-unlimited-master/src/core/WorldModel.js:5:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
bash-3.2#

**Comment by BLUclanTDS** [comment]
Look here: https://github.com/AJS-development/Ogar-unlimited/issues/638

**Comment by XxRaizerxX** [comment]
Ok well i used to have to same issue but go #638 it will fix

**Comment by LegitSoulja** [comment]
Ok you know what, too many new people coming her trying to make on of these servers and barely read nor look at other issues. Don't help duplicate posts, let them figure it out. Tired of repeating myself.
