### ISSUE TITLE
Can u make a only agar.io client?

### ISSUE THREAD

**Issue by Tokoagar** [AJS-development/Ogar-unlimited#987]
Quick question can u make a new client with only agar.io skins? because we have skins who is not in real agar.io and I don't want poeple to have (I don't like them) or can I just delete them?

**Comment by LegitSoulja** [comment]
I'm main_out remove the skin_url and replace it back with the old link that's commented out. 

I'm sorry you don't like the skins, but I guess you aren't looking towards the future. Good luck with the non, or old skins.
