### ISSUE TITLE
MULTIVERSE SERVERS ..

### ISSUE THREAD

**Issue by RelTakeover** [AJS-development/Ogar-unlimited#988]
I create server of multiverse create title port gamemode 

where is the configuration of the servers?

**Comment by LegitSoulja** [comment]
You can create
- multiverse [create] [name] [serverPort]

You can control
- multiverse select [name]

You can delete
- multiverse delete [name]

You can list them
- multiverse list

**Comment by RelTakeover** [comment]
Say error when i wrote multiverse select ffa

**Comment by RelTakeover** [comment]
i cant select servers , say error

**Comment by LegitSoulja** [comment]
What error?

**Comment by RelTakeover** [comment]
not , now works 100% , but ... where 
are all commands ? a list or something

**Comment by LegitSoulja** [comment]
type help in the command. Mostly every command you type will give an usage, for example
> multiverse

**Comment by RelTakeover** [comment]
for example , how i change "the start mass from cmd?"

**Comment by RelTakeover** [comment]
pls help

**Comment by LegitSoulja** [comment]
@RelTakeover

So if you look inside the main settings/config.ini you have your config setting and values,
First you select the multiverse server, then you can change whatever for example

> change playerStartMass 50

**Comment by fayizan** [comment]
Multiverse is buggy for me @LegitSoulja 
Try my server, Selecting the second server makes nothing 
the port which I m running my second server is 54.169.110.104:8080
