### ISSUE TITLE
Skin Gallery

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#989]
Do you have experience with designing graphics? Making pictures? Or anything in that nature?
You can help us make skins for http://play.ogarul.tk. Drop some skins below if you want to create some for everyone else to use.

**Note:**
- NO ORIGINAL AGAR.IO SKINS (STOLEN), We will not use the skins agar.io made. You could recreate. (NOT EDIT)
- Skin Size: **508x508px**.
- Include skin name
- No nudity, nor inappropriate images (You will face consequences if posted).

**Skin Gallery/List**
Skin Gallery will soon be released for all clients hopefully. Only for http://play.ogarul.tk as of right now until released.

@David1ali12

**Comment by David1ali12** [comment]
This for msg moneyclip that we also can make our skins because they care too much about skin
![wasa](https://cloud.githubusercontent.com/assets/17472593/15993684/6add396a-30f6-11e6-8cd3-51b8f128a542.PNG) #Fuck you miniclip :smile:

**Comment by SharkFinPro** [comment]
![untitled](https://cloud.githubusercontent.com/assets/18649707/15994635/f26ac736-30be-11e6-9cdf-931cfdbf259c.png)
The Blackness is where miniclip is headed...

**Comment by systemroot** [comment]
only 508x508px 
?
i use this skin which i've create, it works good with agar+ or any extension, but i've not test with ogar!
![](http://www.dope-sa.com/img/RAW.png)

**Comment by David1ali12** [comment]
it does works normal with play.ogarul.tk [skinurl]

**Comment by SorryAgario** [comment]
welp i like some original agario skins though, why remove em lol

**Comment by SorryAgario** [comment]
i can make graphics though 
![green_blob](https://cloud.githubusercontent.com/assets/19484292/15999321/bfd08ea6-30f9-11e6-8396-eb5eb8737252.png)

**Comment by VirgoAgario** [comment]
I use this for ogario.ovh but here it is
![vmcs51n](https://cloud.githubusercontent.com/assets/19752048/16008657/0b0fca4c-3147-11e6-908f-f90994afab42.jpg)
![ekwrnle](https://cloud.githubusercontent.com/assets/19752048/16008663/11be0ae8-3147-11e6-8015-265711cff553.jpg)
![0csipqh](https://cloud.githubusercontent.com/assets/19752048/16008666/137b9ecc-3147-11e6-8d38-2f69faf57bca.png)
 
I give all credit to the makers of these skins....

**Comment by VirgoAgario** [comment]
Oh and this 
https://cdn.discordapp.com/attachments/134059731357663232/155777764518133761/Drawing_42.png

**Comment by LegitSoulja** [comment]
@SorryAgario because agario like there skins, and don't want us with there's, so we have our own **private** skins that's nothing like agar.io skins

**Comment by Andrews54757** [comment]
^^ yep, because we hate moneyclip. F Moneysh*t

**Comment by LegitSoulja** [comment]
@VirgoAgario oh i forgot. Can you edit, and add names to the skins? Thanks.

**Comment by systemroot** [comment]
if you like can get those. i will edit some more but i don't have time today.
http://www.dope-sa.com/img/panda.png
http://www.dope-sa.com/img/l.png
http://www.dope-sa.com/img/d.png

**Comment by Hunter2890** [comment]
<yinyang> 
![images 1](https://cloud.githubusercontent.com/assets/19917683/16025347/7380c2bc-318c-11e6-98a9-3ff89c4a290d.jpg)

**Comment by David1ali12** [comment]
@Hunter2890 ok renamed

**Comment by LegitSoulja** [comment]
@Hunter2890 we already have a yinyang..

**Comment by Agarian** [comment]
Creeper skin
![creeper](https://cloud.githubusercontent.com/assets/15255724/16028457/694f3672-31ad-11e6-837c-7bf5bfe357fb.png)

**Comment by LegitSoulja** [comment]
@Agarian nice. Skin will be added :)

**Comment by LegitSoulja** [comment]
@VirgoAgario deadpool is added. Please provide names. @systemroot Please provide names for the skins.

**Comment by Agarian** [comment]
Mario and luigi
![download](https://cloud.githubusercontent.com/assets/15255724/16029377/75210454-31b6-11e6-8fbf-6b8878de1d4e.png)
![dktmsay](https://cloud.githubusercontent.com/assets/15255724/16029380/795b4b60-31b6-11e6-8cb9-33ffdf52c1d0.png)

**Comment by Agarian** [comment]
Rockstar north and south
![rockstar](https://cloud.githubusercontent.com/assets/15255724/16029435/e77bc82c-31b6-11e6-9d4f-3f83e3eeb093.png)
![nqlqugg](https://cloud.githubusercontent.com/assets/15255724/16029437/ebce447c-31b6-11e6-8a98-21714437afac.png)

**Comment by LegitSoulja** [comment]
@Agarian What does rockstar have to do with agario? Mario & Luigi edited and added.

**Comment by David1ali12** [comment]
@Agarian but those are used by agario :/ in its private servers

**Comment by Agarian** [comment]
@LegitSoulja @David1ali12 Does it matter? These skins used to be in customskins.txt

**Comment by LegitSoulja** [comment]
@Agarian well, we can't use agar.io skins because they can file complaints about us stealing skins. I said above that agar.io skins are not allowed.

**Comment by SorryAgario** [comment]
![61fe11_e7517453e00f4c11bd46716020b8bbb0](https://cloud.githubusercontent.com/assets/19484292/16030007/67373890-31a2-11e6-86b0-4e865f8a65f4.png)
Background color depends on your blob color

**Comment by Agarian** [comment]
Rockstar is not in agar skins...

**Comment by David1ali12** [comment]
@Agarian  @SorryAgario @VirgoAgario we all know that we can get a ton of skin on google Anyways 
as you can see we are making our own skins do not post skins that are already exist
 make you own  with 508px & we will added our own skins are greenpower,ninjapanda,raw,wing,duck,rat,yinyang, yet

**Comment by jrgryph** [comment]
deviantart.com might be a good place to go for skins...

**Comment by Megabyte918** [comment]
Guys I made an skin
![capture](https://cloud.githubusercontent.com/assets/17245196/16041999/776a257e-3206-11e6-952c-b4ce4b94265e.png)
lol

**Comment by fayizan** [comment]
@Megabyte918 LoL 
hahaha

**Comment by mastkilxp** [comment]
<img src="http://i.imgur.com/J9ABwud.jpg?1"/>

:D american football please!
<img src="http://i.imgur.com/h9TrQLX.png?1"/>
or soccer!! :D i just love sport lol <3

**Comment by Agarian** [comment]
Lol rockstar north is the one i made off of rockstar south

**Comment by fayizan** [comment]
Can u please add this skin http://imgur.com/pEauCKs 
the image size is 508x508px

![kungfu power](https://cloud.githubusercontent.com/assets/19163419/16072204/4d85df94-32fd-11e6-959f-e86bf94cff9b.png)

**Comment by LegitSoulja** [comment]
@fayizan I can, once you provide a name for this skin. We already have a yingyang and yinyang

**Comment by fayizan** [comment]
@LegitSoulja Name it as **mlg**

**Comment by LegitSoulja** [comment]
@fayizan ok i will add it

**Comment by fayizan** [comment]
@LegitSoulja  the skin is not working

**Comment by LegitSoulja** [comment]
MLG was added a long time ago, and tested and works :/

**Comment by fayizan** [comment]
See not working for me :(
https://gyazo.com/04a4576ca67d6151314213ab3ad4a906

**Comment by LegitSoulja** [comment]
Do you see the skin on the skin list? That's weird if you don't see it. I made sure it was working.

**Comment by fayizan** [comment]
@LegitSoulja  I selected it through the the skin list

**Comment by LegitSoulja** [comment]
Does any other skins work?

**Comment by fayizan** [comment]
yes other skins were working cool

**Comment by LegitSoulja** [comment]
I don't know what to say. The only thing I can say is that it will soon eventually work. It could be cache problems, or the image took a long time to load? Idk.

Try using another browser and see if the same thing happens or not.

**Comment by fayizan** [comment]
I tried different browser but not working on my side

**Comment by fayizan** [comment]
I found the problem I added mlg skin to my customskins.txt so its not working on my server but works in all other servers

**Comment by fayizan** [comment]
@LegitSoulja Two More skins,Both image size is 508x508px

Skin Name **whirl :http://imgur.com/aobCnVj** 

![whirl](https://cloud.githubusercontent.com/assets/19163419/16170316/894a6e84-356c-11e6-8e7f-39730ea0abb3.png)

Skin Name **indagar :http://imgur.com/Wm6RmNm**

![indagar](https://cloud.githubusercontent.com/assets/19163419/16170323/a570191a-356c-11e6-8be9-5ad465bfdde3.png)

**Comment by fayizan** [comment]
@Legitsoulja Please look into this http://m.imgur.com/account/divakarmeena/albums
He said we can use all his skins and most of the skins were really awesome please add it

**Comment by fayizan** [comment]
@Legitsoulja say something..!! 😕

**Comment by David1ali12** [comment]
@fayizan  you can just use as custom skins [skinurl]  you need to use url shorter though

**Comment by David1ali12** [comment]
Added!

**Comment by fayizan** [comment]
@David1ali12 thank u..!!
Can u please look into the link I had sent above,once again 
http://m.imgur.com/account/divakarmeena/albums

**Comment by LegitSoulja** [comment]
@fayizan sorry, I'm kindof busy. Not uploading skins ATM :/. Workspace occupied.

**Comment by fayizan** [comment]
@David1ali12 Skin Name: barbcoc
Imgur link : http://imgur.com/0T8Fvow

![screenshot_2016-06-22-10-01-35-01-508x508](https://cloud.githubusercontent.com/assets/19163419/16255659/6122468e-3869-11e6-9f85-df14aa71e23a.png)

**Comment by LegitSoulja** [comment]
@fayizan we will get to them shortly I promise.

**Comment by firelightning13** [comment]
Wow so much skin this is cooler than agar.io (if u know what i mean ;)  )

**Comment by VirgoAgario** [comment]
@Megabyte918 the first one is anime 3rd one is ninja 4th one is getrekt

**Comment by RevivedSol** [comment]
![fb_img_1466689017543](https://cloud.githubusercontent.com/assets/18722207/16305176/478e3ac0-398b-11e6-83db-6dfa36a788af.jpg)

**Comment by RevivedSol** [comment]
![fb_img_1466689041043](https://cloud.githubusercontent.com/assets/18722207/16305202/686489a2-398b-11e6-8bc7-5d1d0c340844.jpg)
![fb_img_1466689035546](https://cloud.githubusercontent.com/assets/18722207/16305207/6e428cac-398b-11e6-9dbf-ab751993d245.jpg)
![fb_img_1466689032252](https://cloud.githubusercontent.com/assets/18722207/16305213/739f9e10-398b-11e6-9b12-bca2a51f1755.jpg)
![fb_img_1466689029346](https://cloud.githubusercontent.com/assets/18722207/16305223/78df92c2-398b-11e6-8fcf-b502354499ce.jpg)
![fb_img_1466689023872](https://cloud.githubusercontent.com/assets/18722207/16305233/7e7d7776-398b-11e6-86eb-7a06af9b5ea0.jpg)
![fb_img_1466689021067](https://cloud.githubusercontent.com/assets/18722207/16305237/8330a18a-398b-11e6-8ecf-4878e829481f.jpg)

**Comment by LegitSoulja** [comment]
@RevivedSol what are you doing play Ogar? Go be an artist!!. Wow that's amazing!!. Well done. That's if you actually drew that then congrats.

**Comment by RevivedSol** [comment]
i didnt create these stuff. my friend just shared these pic on facebook and theyre very cool and i wanted them to be added to ogar

**Comment by fayizan** [comment]
@LegitSoulja or @David1ali12  could someone please add my last barbcoc skin...

**Comment by LegitSoulja** [comment]
@fayizan Message from david, is that you guys are mainly getting picture off of google, and he kindof wanted rare images or images that was self created as of what I said above if you have experience in making pictures. We could easily search google for images, but we came here to see if someone had custom images that they made, or rare that could be added. Right now, there's 142 skins. We are choosing wisely on skins now.

**Comment by LegitSoulja** [comment]
I will add the barbarian since coc is fairly popular. Anything else will be added by david's decision. I will not be uploading images anymore.

**Comment by Agarian** [comment]
I was about to close this til i read "Anything else will be added by david's decision."

**Comment by David1ali12** [comment]
lol I mean you still can use any skin you want [skinurl]

**Comment by Agarian** [comment]
IK lol

**Comment by SorryAgario** [comment]
https://cdn.discordapp.com/attachments/181649965037125632/197717348159979531/Rip_Agario.png

When Ur Bored and u used to be an agarplus player

**Comment by Agarian** [comment]
? agarplus is fine

**Comment by fayizan** [comment]
Ok what about now??!! ogarul.io(Davidali) is dead and who is incharge of adding skins..??

**Comment by LegitSoulja** [comment]
I an unfortunately

**Comment by Agarian** [comment]
Welp, a kitten just died under my porch

**Comment by SharkFinPro** [comment]
:|
