### ISSUE TITLE
how restart multiverse ? PLS NEED HELP

### ISSUE THREAD

**Issue by RelTakeover** [AJS-development/Ogar-unlimited#991]
NEED HELP ! :(
After changing something in a multiverse , example : " playerStartMass 4" , as I save changes or reset only one server?

**Comment by David1ali12** [comment]
you are spamming 5 issues until now ! that's already closed @LegitSoulja @Andrews54757

**Comment by LegitSoulja** [comment]
@RelTakeover Last chance @RelTakeover Make another duplicate issue I will have to ban you for spam. Last warning.
