### ISSUE TITLE
How do i....

### ISSUE THREAD

**Issue by SorryAgario** [AJS-development/Ogar-unlimited#993]
I want to practice and get used to the new agario mechanics and graphics, i wanna use it on my private server, how do i activate it on ogar unlimited

**Comment by LegitSoulja** [comment]
Activate? You want to use the agario mechanics/graphics with ogar?

**Comment by GhostShot3** [comment]
use cigar

**Comment by Agarian** [comment]
TF cigar?

**Comment by Andrews54757** [comment]
Cigar has horrible physics.

**Comment by Megabyte918** [comment]
Cigar = **ROASTED**

**Comment by ItzLevvie** [comment]
Use MultiOgar (https://github.com/Barbosik/MultiOgar)
