### ISSUE TITLE
<SKIN> Not working for many skins!

### ISSUE THREAD

**Issue by CalvinDKHD** [AJS-development/Ogar-unlimited#994]
Hello, i hope this is an issue xD
But when i do < SkinName > NAME  etc. The skin doesnt work.
https://gyazo.com/39526a6d68b28da9e2ecc51c6343bab1
Is that because agario has changes their skin link?
If you look in the end there is a basket ball minion, some skins work. But not many. < /random > doesnt work either. I checked on my friends ogar UL server aswell. They dont work.

Thanks!

**Comment by Flip123** [comment]
Have you put a space, instead of ex. <dog>calvin ?

**Comment by Flip123** [comment]
<dog> and them ur name i think

**Comment by CalvinDKHD** [comment]
No No, i didnt. Its if i do < NAME > without spaces it wont show up on github. I do it without spaces between the arrows.

**Comment by CalvinDKHD** [comment]
I think its something to do with the main_out.js in the client. - https://gyazo.com/916f3fd8335c3406db6aabe26516b252
The agario skins link doesnt work, forbidden access.    https://gyazo.com/37a5f4d6db8e48ae5401aa485f585ec8

**Comment by CalvinDKHD** [comment]
i tried switching the agario skin URL to the ogar ul one. - http://ogarul.io/skins/
Nothing either.

**Comment by Flip123** [comment]
i mean, do this: [http://imgur.com/h9wsqRa](url)

**Comment by Flip123** [comment]
Do a space after the last >

**Comment by CalvinDKHD** [comment]
Ok, let me try.

**Comment by CalvinDKHD** [comment]
Nope, didnt work.

**Comment by CalvinDKHD** [comment]
It, i did <name> Calvin

**Comment by Flip123** [comment]
then i dont know it, sorry i just cant help u further.... :'(

**Comment by CalvinDKHD** [comment]
Uhh, k. You try please. I am using the client.

**Comment by CalvinDKHD** [comment]
Actually, 1 second.

**Comment by Flip123** [comment]
do u have skype?, so i can help u with voice and screen

**Comment by CalvinDKHD** [comment]
Yes, - calvin.leonhardt

**Comment by Flip123** [comment]
ok im Gr champ ( im in a clan) im gonna search you up ok? cya in 1 min

**Comment by CalvinDKHD** [comment]
k

**Comment by Flip123** [comment]
ive sended a request

**Comment by ItzLevvie** [comment]
The agario skins link doesnt work, forbidden access. https://gyazo.com/37a5f4d6db8e48ae5401aa485f585ec8

That isn't the skins folder for Agar.io.

**Comment by raphyjb** [comment]
lol yall wrong just do <invader> with no caps Mouhahahaahahahaa

**Comment by CalvinDKHD** [comment]
I did it without caps, doesnt work.

**Comment by CalvinDKHD** [comment]
And levvie, thats what it is saying in the index.html.

**Comment by ItzLevvie** [comment]
^^ that main_out.js was written ages ago.

**Comment by CalvinDKHD** [comment]
Ohh, can you send me the new one?

**Comment by Megabyte918** [comment]
i think this has the latest client, #918
try it and let me know if it works

**Comment by CalvinDKHD** [comment]
Aint working, i think its the Skins link here / http://ogarul.io/skins/\
Thats what is in the mainout. Thats what it is using

**Comment by CalvinDKHD** [comment]
Lol, some of the skins work sometimes - https://gyazo.com/8b830d7f6819b48d6f27ba1827186c0c

**Comment by LegitSoulja** [comment]
Use http://ogarul.tk there was a lot of people downloading skins, hot linking etc.

**Comment by CalvinDKHD** [comment]
@LegitSoulja Sorry, should i signup and post the problem there? or what do you mean?

**Comment by Megabyte918** [comment]
thats weird that they arent working... make sure everythings updated to the latest and try using play.ogarul.tk instead, all the skins seem to be working on there

**Comment by CalvinDKHD** [comment]
Yeah, i know. But. It was working yesterday, so it cant be my client i am using. But some skins work, not all. And its random which ones work. - https://gyazo.com/8b830d7f6819b48d6f27ba1827186c0c

**Comment by LegitSoulja** [comment]
@CalvinDKHD what's the link to your client?

**Comment by CalvinDKHD** [comment]
Uhh this one - https://github.com/AJS-development/Ogar-unlimited/issues/918

**Comment by LegitSoulja** [comment]
No your custom client

**Comment by CalvinDKHD** [comment]
Ok, here - https://www.mediafire.com/?ou94wd8ikr03dv9

**Comment by LegitSoulja** [comment]
Dude the link to your site/custom client...

**Comment by CalvinDKHD** [comment]
ohh my site, k. ok go to Agarextreme.ml
Then click on AE W/ MINIONS that is based on OgarUl the one in the start is another client.

**Comment by CalvinDKHD** [comment]
But the mediafire link is the client files of the one i have.

**Comment by LegitSoulja** [comment]
No I don't need the files, I was just testing

**Comment by CalvinDKHD** [comment]
ok ok, the AE W/ MINIONS uses Ogar UL.

**Comment by CalvinDKHD** [comment]
so - http://188.183.155.66:8080/

**Comment by CalvinDKHD** [comment]
Thats the client url that u put in URL bar.
