### ISSUE TITLE
Help with minions please.

### ISSUE THREAD

**Issue by systemroot** [AJS-development/Ogar-unlimited#995]
Is any plugin to give all players minions at same time or how to do that thing random minions ?!
just i install Statics plugin, i start today to play with my minions and people start login to my server and asking for minions -_- 
![](http://image.prntscr.com/image/aed516e4b215409987e63e82ddea8995.png)

**Comment by LegitSoulja** [comment]
Lol Statatics getting popular, you added it so expect people to join, You can use GiveMeMinionsToo. I don't know for me it crashes the server when it doesn't clean the minions

**Comment by systemroot** [comment]
@LegitSoulja  Thanks i will try :confused:

**Comment by LegitSoulja** [comment]
You don't have to give people minions lol

**Comment by systemroot** [comment]
yes i will not give anymore a minions start making team with himself :trollface: 
![](http://image.prntscr.com/image/1b464792e92042f9bfee1ce063791363.png)

**Comment by Megabyte918** [comment]
I suggested something like <m> when you put it in front of your name it gives you a certain amount of minions, idk where thats going

**Comment by systemroot** [comment]
and one question :/ i use "board" to write NO MINIONS, and leader board has gone :/ how to get it back :/ ?

**Comment by LegitSoulja** [comment]
@Megabyte918 nice idea for a plugin. Skin options
<minions=5;skin=sc> lol
