### ISSUE TITLE
How minions to everyone who sent

### ISSUE THREAD

**Issue by LostCodesy** [AJS-development/Ogar-unlimited#996]
Hello,

How minions to everyone who sent in ogar-unlimited server?

Good Work!

**Comment by David1ali12** [comment]
install the plugin
`plugin install GiveMeMinionsToo`

**Comment by LostCodesy** [comment]
Thanks ...

**Comment by LostCodesy** [comment]
**plugin install GiveMeMinions** is good and automatic...

**Comment by LegitSoulja** [comment]
GiveMeMinions gives you GiveMeMinionsToo unless you manually download it lol. GiveMeMinions was the version I made

**Comment by LostCodesy** [comment]
GiveMeMinions good and yes you made but 

// switchIntervalTime : Time in when minions switch to another player in (1000ms equals 1 second) :: Default 60000 (1 minute).
// minionGiveAmount : Amount a minions to give to a player.
// botGetMinions : 0 false, 1 true, set bots to get minions.
// setPerInterval : How many people will get a minion each random time
switchIntervalTime = 60000
minionGiveAmount = 100 // Yes minion count
botGetMinions = 1
setPerInterval = 2


need more explanation, insufficient :/ Help me.

**Comment by LegitSoulja** [comment]
I don't even remember if the config worked or not lol

**Comment by LegitSoulja** [comment]
That was like the first plugin I made

**Comment by LegitSoulja** [comment]
But it discontinued now, and there's GiveMeMinionsToo instead.

**Comment by LostCodesy** [comment]
**GiveMeMinions good or GiveMeMinionsToo good?**

**Comment by LostCodesy** [comment]
I'm noob, sorry. Help me for minions to give all players in ogar-unlimited server. only.

**Comment by LostCodesy** [comment]
**# problem solved.**
